### ISSUE TITLE
Webpack error when build custom strapi project - 'use strict'

### ISSUE THREAD

**Issue by YasiruDev** [strapi/strapi#10084]
Im trying to connect my existing mysql db to strapi.there for i created custom strapi project.when i tried to `npm run develop`, i got bellow error.

`Error: ./.cache/plugins/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/Banner.js 2:87
Module parse failed: Unexpected token (2:87)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| "use strict";var _interopRequireDefault=require("@babel/runtime/helpers/interopRequireDefault");var _interopRequireWildcard=require("@babel/runtime/helpers/interopRequireWildcard");Object.defineProperty(exports,"__esModule",{value:true});exports.default=void 0;var _react=_interopRequireWildcard(require("react"));var _reactIntl=require("react-intl");var _propTypes=_interopRequireDefault(require("prop-types"));var _icons=require("@buffetjs/icons");var _reactFontawesome=require("@fortawesome/react-fontawesome");var _pluginId=_interopRequireDefault(require("../../pluginId"));var _PreviewCarret=_interopRequireDefault(require("../PreviewCarret"));var _BannerWrapper=_interopRequireDefault(require("./BannerWrapper"));/* eslint-disable jsx-a11y/click-events-have-key-events */ /* eslint-disable jsx-a11y/no-static-element-interactions */const Banner=/*#__PURE__*/(0,_react.forwardRef)(({displayedValue,doesPreviousFieldContainErrorsAndIsOpen,hasErrors,hasMinError,isFirst,isReadOnly,isDragging,isOpen,onClickToggle,onClickRemove,style},refs)=>{const display=isDragging?'none':'';return/*#__PURE__*/_react.default.createElement(_BannerWrapper.default,{doesPreviousFieldContainErrorsAndIsOpen:doesPreviousFieldContainErrorsAndIsOpen,type:"button",hasMinError:hasMinError,hasErrors:hasErrors,isFirst:isFirst,isOpen:isOpen,isReadOnly:isReadOnly,onClick:onClickToggle,ref:refs?refs.dropRef:null,style:style},isDragging&&/*#__PURE__*/_react.default.createElement(_PreviewCarret.default,{isComponent:true}),/*#__PURE__*/_react.default.createElement(_react.default.Fragment,null,/*#__PURE__*/_react.default.createElement("div",{className:"img-wrapper",style:{display}},/*#__PURE__*/_react.default.createElement(_icons.Carret,null)),/*#__PURE__*/_react.default.createElement(_reactIntl.FormattedMessage,{id:`${_pluginId.default}.containers.Edit.pluginHeader.title.new`},msg=>{// The displayed value may be "falsey" when the main field is a number or boolean
> return/*#__PURE__*/_react.default.createElement("div",{style:{display}},displayedValue??msg);}),/*#__PURE__*/_react.default.createElement("div",{className:"cta-wrapper",style:{display}},!isReadOnly&&/*#__PURE__*/_react.default.createElement(_react.default.Fragment,null,/*#__PURE__*/_react.default.createElement("div",{className:"trash-icon",style:{marginRight:10,padding:'0 5px'},onClick:e=>{e.preventDefault();e.stopPropagation();onClickRemove();}},/*#__PURE__*/_react.default.createElement(_reactFontawesome.FontAwesomeIcon,{icon:"trash-alt"})),/*#__PURE__*/_react.default.createElement("div",{className:"grab",ref:refs?refs.dragRef:null},/*#__PURE__*/_react.default.createElement(_icons.Grab,null))))));});Banner.defaultProps={displayedValue:null,doesPreviousFieldContainErrorsAndIsOpen:false,hasErrors:false,hasMinError:false,isDragging:false,isFirst:false,isOpen:false,onClickRemove:()=>{},onClickToggle:()=>{},style:{}};Banner.propTypes={displayedValue:_propTypes.default.oneOfType([_propTypes.default.string,_propTypes.default.number,_propTypes.default.object]),doesPreviousFieldContainErrorsAndIsOpen:_propTypes.default.bool,hasErrors:_propTypes.default.bool,hasMinError:_propTypes.default.bool,isDragging:_propTypes.default.bool,isFirst:_propTypes.default.bool,isOpen:_propTypes.default.bool,isReadOnly:_propTypes.default.bool.isRequired,onClickToggle:_propTypes.default.func,onClickRemove:_propTypes.default.func,style:_propTypes.default.object};Banner.displayName='Banner';var _default=Banner;exports.default=_default;
    at compiler.run (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/strapi-admin/index.js:71:23)
    at finalCallback (/home/xx/Documents/Tutorials/Strapi/my-project/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/webpack/lib/Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxxx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxxx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxxx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/webpack/lib/Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/home/xx/Documents/Tutorials/Strapi/my-project/node_modules/webpack/lib/Compilation.js:1423:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/home/xxx/Documents/Tutorials/Strapi/my-project/node_modules/webpack/lib/Compilation.js:1414:32)`

I tried these as well

1. remove cache and build file
2. remove node_modules
3. run `npm i`
4. run `npm run develop`

but same error

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
