### ISSUE TITLE
i18n in a model from a plugin crashes

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#10120]
### Describe the bug

I am running models from a plugin. I'm trying to install i18n in those models. It fails to start:

```
yarn workspace v1.22.4
yarn run v1.22.4
$ strapi develop
[2021-04-23T07:18:02.197Z] error Something went wrong in the model `Pages` with the attribute `localizations`
[2021-04-23T07:18:02.198Z] error TypeError: Cannot read property 'uid' of undefined
    at Object.defineAssociations (/Users/laurenskling/sites/strapi/node_modules/strapi-utils/lib/models.js:389:34)
    at buildRelation (/Users/laurenskling/sites/strapi/node_modules/strapi-connector-mongoose/lib/mount-models.js:438:15)
    at /Users/laurenskling/sites/strapi/node_modules/strapi-connector-mongoose/lib/mount-models.js:121:7
    at Array.forEach (<anonymous>)
    at mountModel (/Users/laurenskling/sites/strapi/node_modules/strapi-connector-mongoose/lib/mount-models.js:120:26)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/laurenskling/sites/strapi/node_modules/strapi-connector-mongoose/lib/mount-models.js:341:23)
    at /Users/laurenskling/sites/strapi/node_modules/strapi-connector-mongoose/lib/index.js:193:16
    at Array.map (<anonymous>)
    at mountPlugins (/Users/laurenskling/sites/strapi/node_modules/strapi-connector-mongoose/lib/index.js:191:35)
    at /Users/laurenskling/sites/strapi/node_modules/strapi-connector-mongoose/lib/index.js:155:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async Object.initialize (/Users/laurenskling/sites/strapi/node_modules/strapi-database/lib/connector-registry.js:30:9)
    at async DatabaseManager.initialize (/Users/laurenskling/sites/strapi/node_modules/strapi-database/lib/database-manager.js:43:5)
    at async Strapi.load (/Users/laurenskling/sites/strapi/node_modules/strapi/lib/Strapi.js:354:5)
error Command failed with exit code 1.
```

### Steps to reproduce the behavior

1. create a plugin like "strapi-plugin-pages", add a model with:
```
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
 ```
2. install the plugin in your project
3. run start

### Expected behavior

i18n working from a plugin model :)

### System

- Node.js version: 14.15.1
- NPM version: 6.14.11
- Strapi version: 3.6.0
- Database: atlas mongodb
- Operating system: macos

**Comment by laurenskling** [comment]
ah, so `localizations` is a relation to itself. which doesn't seem to take in account it need to query the model from a plugin

**Comment by laurenskling** [comment]
https://github.com/strapi/strapi/blob/4ab210eec65d7f1a4f6334cdef4c797b4e6b9531/packages/strapi-plugin-i18n/config/functions/register.js#L21 when a add `plugin` (from `contentType`) to this, the above error is fixed.

It will get me into trouble with the router. With some fixes I end up in:

` Error creating endpoint post /pages/:id/localizations: handler not found "pages.createLocalization"`

which is ofcourse also not the correct REST route for a plugin. It should be `/pages/pages/:id/localizations`. (plugin/model/:id/..)

**Comment by laurenskling** [comment]
also hacking that error away gives me: 

` [GraphQL] Cannot find action "plugins::pages.pages.createLocalization". Check your graphql configurations.`

**Comment by laurenskling** [comment]
If you disable the graphql schema creation for localization, everything works fine 😅

**Comment by ericraio** [comment]
We're currently dealing with this issue and it's blocking us from continue our work :/

**Comment by UltraMarine107** [comment]
It would be great if Strapi team could try fixing this issue, cuz I'm having same issue for my project too

**Comment by meep-morp** [comment]
My project is on hold due to this bug, would really help if someone on the Strapi team took a look at this.

**Comment by Kronos66** [comment]
Hi,
I had similar problem when I working on our plugin and we resolved this issue to added some logic to i18n bootstrap process to disable adding endpoints to `content-manager` and GQL, because in plugiins we handle this in custom logic.
I resolved this problem in strapi 3.6.5 version, to apply our fix we use https://www.npmjs.com/package/patch-package.

```
diff --git a/node_modules/strapi-plugin-i18n/config/functions/register.js b/node_modules/strapi-plugin-i18n/config/functions/register.js
index 7a94f08..7a2e86f 100644
--- a/node_modules/strapi-plugin-i18n/config/functions/register.js
+++ b/node_modules/strapi-plugin-i18n/config/functions/register.js
@@ -24,6 +24,7 @@ module.exports = () => {
         configurable: false,
         visible: false,
         collection: modelName,
+        plugin: contentType.plugin,
         populate: ['_id', 'id', 'locale', PUBLISHED_AT_ATTRIBUTE],
       });
 
diff --git a/node_modules/strapi-plugin-i18n/services/core-api.js b/node_modules/strapi-plugin-i18n/services/core-api.js
index c81361a..b85bf24 100644
--- a/node_modules/strapi-plugin-i18n/services/core-api.js
+++ b/node_modules/strapi-plugin-i18n/services/core-api.js
@@ -193,8 +193,10 @@ const createLocalizationRoute = contentType => {
  * @param {object} contentType
  */
 const addCreateLocalizationAction = contentType => {
-  const { modelName, apiName } = contentType;
-
+  const { modelName, apiName, plugin } = contentType;
+  if (!apiName && plugin){
+    return;
+  }
   const localizationRoute = createLocalizationRoute(contentType);
 
   const coreApiControllerPath = `api.${apiName}.controllers.${modelName}.createLocalization`;
@@ -224,9 +226,9 @@ const addGraphqlSchema = schema => {
  * @param {object} contentType
  */
 const addGraphqlLocalizationAction = contentType => {
-  const { globalId, modelName } = contentType;
+  const { globalId, modelName, plugin } = contentType;
 
-  if (!strapi.plugins.graphql) {
+  if (!strapi.plugins.graphql || plugin) {
     return;
   }
```

**Comment by mitkodkn** [comment]
I'm still getting this error. Is there any progress on the issue?

**Comment by conorjohn** [comment]
I've also run into this when trying to launch my project, and updates? Or even workarounds?

**Comment by Jbmanllr** [comment]
Still having this issue in V4.

Workaround for V4?

**Comment by saifullahakhtar** [comment]
Having the same issue.

**Comment by DerMambo** [comment]
You can use the `content-type-builder` plugin as a workaround. You would not create the content type under the `content-types` folder but create it programmatically.

As an example of a very simple `tag` content type:

      {
        "singularName": "tag",
        "pluralName": "tags",
        "displayName": "tag",
        "description": "",
        "draftAndPublish": false,
        "pluginOptions": {
          "i18n": {
            "localized": true
          }
        },
        "attributes": {
          "label": {
            "type": "string",
            "pluginOptions": {
              "i18n": {
                "localized": true
              }
            },
            "unique": true
          }
        }
      }

Note, this schema of the json is a bit different from the ones in `plugin/server/content-types`.

Then you can create the content type programmatically like this:

    import { Strapi } from "@strapi/strapi";
    import tag from "../content-types/tag.json";
    import page from "../content-types/page.json";
    
    export default ({ strapi }: { strapi: Strapi }) => ({
      async createContentComponent() {
        if (!tag) return null;
    
        try {
          const components: any = [];
    
          const contentType = await strapi
            .plugin("content-type-builder")
            .services["content-types"].createContentType({
              contentType: tag,
              components,
            });
    
          return contentType;
        } catch (e) {
          console.log("error", e);
          return null;
        }
      },
    });

This is exactly how the admin creates content types using the content builder UI.

And it works using the `pluginOptions.i18n.localized: true`.

One approach would be to do this, e.g., on the bootstrap phase of the plugin. Here you could also check whether or not the contents are created or not.

As a bonus, you can also create components that otherwise would not work.


Hope that helps.

Links:
Create components programmatically in a plugin: https://github.com/strapi/strapi-plugin-seo/blob/main/server/services/seo.js

Create content types:
https://github.com/strapi/strapi/blob/88caa92f878a068926255dd482180202f53fcdcc/packages/core/content-type-builder/server/controllers/content-types.js#L48

**Comment by Kuraikari** [comment]
> You can use the `content-type-builder` plugin as a workaround. You would not create the content type under the `content-types` folder but create it programmatically.
> 
> As an example of a very simple `tag` content type:
> 
> ```
>   {
>     "singularName": "tag",
>     "pluralName": "tags",
>     "displayName": "tag",
>     "description": "",
>     "draftAndPublish": false,
>     "pluginOptions": {
>       "i18n": {
>         "localized": true
>       }
>     },
>     "attributes": {
>       "label": {
>         "type": "string",
>         "pluginOptions": {
>           "i18n": {
>             "localized": true
>           }
>         },
>         "unique": true
>       }
>     }
>   }
> ```
> 
> Note, this schema of the json is a bit different from the ones in `plugin/server/content-types`.
> 
> Then you can create the content type programmatically like this:
> 
> ```
> import { Strapi } from "@strapi/strapi";
> import tag from "../content-types/tag.json";
> import page from "../content-types/page.json";
> 
> export default ({ strapi }: { strapi: Strapi }) => ({
>   async createContentComponent() {
>     if (!tag) return null;
> 
>     try {
>       const components: any = [];
> 
>       const contentType = await strapi
>         .plugin("content-type-builder")
>         .services["content-types"].createContentType({
>           contentType: tag,
>           components,
>         });
> 
>       return contentType;
>     } catch (e) {
>       console.log("error", e);
>       return null;
>     }
>   },
> });
> ```
> 
> This is exactly how the admin creates content types using the content builder UI.
> 
> And it works using the `pluginOptions.i18n.localized: true`.
> 
> One approach would be to do this, e.g., on the bootstrap phase of the plugin. Here you could also check whether or not the contents are created or not.
> 
> As a bonus, you can also create components that otherwise would not work.
> 
> Hope that helps.
> 
> Links: Create components programmatically in a plugin: https://github.com/strapi/strapi-plugin-seo/blob/main/server/services/seo.js
> 
> Create content types:
> 
> https://github.com/strapi/strapi/blob/88caa92f878a068926255dd482180202f53fcdcc/packages/core/content-type-builder/server/controllers/content-types.js#L48
> 
> EDIT: You could also keep the original schema and use this fn to transform it - at least for now as long as the other approach is not working:
> 
> https://github.com/strapi/strapi/blob/1eab2fb08c7a4d3d40a5a7ff3b2f137ce0afcf8a/packages/core/content-type-builder/server/services/content-types.js#L37

I'm sorry for being this late, but I thought it would be the best putting it here.

I tried using that, but the application crashes when generating the schema, when trying to add the value for "isDraftAndPublish". It just fills some whitespace and comma, which is obviously invalid JSON.
