### ISSUE TITLE
Cloudinary upload provider - Large file uploads fail

### ISSUE THREAD

**Issue by LouisMarzorati** [strapi/strapi#10147]
### Describe the bug

Cloudinary upload provider fails to upload files larger than 100mb. This includes direct media library uploads, and calls to the media library from the front end. I believe the issue is that the provider isn't using the [upload_large](https://cloudinary.com/documentation/upload_images#chunked_asset_upload) cloudinary function. I have a paid cloudinary account, which allows for large uploads. Uploading directly through cloudinary works. Uploading through cloudinary node sdk's upload_large functions works. Uploading through strapi does not.

Strapi sends back generic error, but the real error is a 413 from cloudinary. 

### Steps to reproduce the behavior

1. Install / config https://www.npmjs.com/package/strapi-provider-upload-cloudinary
2. Go to media library
3. Attempt to upload media larger than 100Mb
4. See error.

### Expected behavior

That the media would upload to cloudinary. 

### Screenshots
![image](https://user-images.githubusercontent.com/6119655/116109726-0f25e380-a683-11eb-93ff-d5e1f7dc8764.png)

### System

- Node.js version: ">=10.16.0 <=14.x.x",
- NPM version: ^6.0.0"
- Strapi version: "3.6.0"
- Database: Mongo DB cluster
- Operating system: Win 10

**Comment by LouisMarzorati** [comment]
Strapi console output when uploading directly from media library.

```
[2021-04-26T15:30:58.984Z] debug POST /upload (90645 ms) 500

[2021-04-26T15:30:58.984Z] error Error: Error uploading to cloudinary: Server returned unexpected status code - 413
    at Object.unknownError (...node_modules\strapi-plugin-upload\errors.js:16:17)
    at ....\node_modules\strapi-provider-upload-cloudinary\lib\index.js:35:38
    at ....\node_modules\cloudinary\lib\utils\index.js:1182:14   
    at ClientRequest.handle_response (....\node_modules\cloudinary\lib\uploader.js:454:7)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

[2021-04-26T15:30:58.986Z] error Error: Internal Server Error
    at convertToStrapiError (....\node_modules\strapi-plugin-upload\errors.js:38:26)
    at Object.upload (....\node_modules\strapi-plugin-upload\config\functions\bootstrap.js:35:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.uploadFileAndPersist (....\node_modules\strapi-plugin-upload\services\Upload.js:154:5)
    at async Promise.all (index 0)
    at async Object.upload (....\node_modules\strapi-plugin-upload\services\Upload.js:140:12)
    at async uploadFiles (....\node_modules\strapi-plugin-upload\controllers\upload\admin.js:187:27)
    at async Object.upload (....\node_modules\strapi-plugin-upload\controllers\Upload.js:65:5)
    at async ...\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:79:22
    at async ....\node_modules\strapi-utils\lib\policy.js:68:5
    at async ....\node_modules\strapi\lib\middlewares\parser\index.js:48:23
    at async ....\node_modules\strapi\lib\middlewares\xss\index.js:26:9
```

**Comment by derrickmehaffy** [comment]
> error Error: Error uploading to cloudinary: Server returned unexpected status code - 413

Typically this means the file is too large but it appears to be coming from cloudinary directly, what plan are you on and what type of file are you uploading?

**Comment by LouisMarzorati** [comment]
I have an _Advanced Extra Plan_ 

Maximum image file size
40 MB
Maximum video file size
4 GB

And media files, mostly .MOV or .MP4

**Comment by SonnyCastro** [comment]
I'm having this same issue but the only difference is that the images I'm trying to upload are not greater than 100MB
![Screen Shot 2021-06-03 at 11 09 21 AM](https://user-images.githubusercontent.com/65030730/120668236-45ae0580-c45c-11eb-809f-2c6cdcc168e9.png)

**Comment by derrickmehaffy** [comment]
> I'm having this same issue but the only difference is that the images I'm trying to upload are not greater than 100MB
> ![Screen Shot 2021-06-03 at 11 09 21 AM](https://user-images.githubusercontent.com/65030730/120668236-45ae0580-c45c-11eb-809f-2c6cdcc168e9.png)

@SonnyCastro can you provide the log message from the server side? All 500 errors should be throwing an error in the server console.

**Comment by anupjk-5** [comment]
@SonnyCastro have you found any solution to it?

**Comment by SonnyCastro** [comment]
> @SonnyCastro have you found any solution to it?

I believe the reason why it wasn't working for me was 2 things.

1. I was trying to upload images in "production". I have to do this in staging then do something like deploy or download the data and import it into my "production" environment.
2. I had incorrect environment variables in Heroku.

This was some time ago so I don't exactly remember but hopefully that helps ^

**Comment by JabStrapi** [comment]
At some point, we could use the `upload_large()` method if the file size is bigger than a limit. That's a nice first contribution 😉.

**Comment by UsmanAsif193** [comment]
Any solution till yet? Need to use the upload_large()....

**Comment by derrickmehaffy** [comment]
converting this to an enhancement as it requires additional feature development that doesn't apply to other providers

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/customization/p/handle-large-file-uploads-on-cloudinary
