### ISSUE TITLE
error TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by Lykeosovandara** [strapi/strapi#10174]
## Bug report
debug ⛔️ Server wasn't able to start properly.
error TypeError: Cannot read property 'register' of undefined

### Describe the bug

debug ⛔️ Server wasn't able to start properly.
[2021-04-29T02:04:10.425Z] error TypeError: Cannot read property 'register' of undefined
    at module.exports (/Users/keo/Documents/Projects/Freelance/flipKhmer/flip_khmer_cms/node_modules/strapi-connector-mongoose/lib/migrations/index.js:6:24)
    at Object.initialize (/Users/keo/Documents/Projects/Freelance/flipKhmer/flip_khmer_cms/node_modules/strapi-connector-mongoose/lib/index.js:57:5)
    at Object.initialize (/Users/keo/Documents/Projects/Freelance/flipKhmer/flip_khmer_cms/node_modules/strapi-database/lib/connector-registry.js:30:25)
    at DatabaseManager.initialize (/Users/keo/Documents/Projects/Freelance/flipKhmer/flip_khmer_cms/node_modules/strapi-database/lib/database-manager.js:36:27)
    at Strapi.load (/Users/keo/Documents/Projects/Freelance/flipKhmer/flip_khmer_cms/node_modules/strapi/lib/Strapi.js:339:19)
    at async Strapi.start (/Users/keo/Documents/Projects/Freelance/flipKhmer/flip_khmer_cms/node_modules/strapi/lib/Strapi.js:191:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Steps to reproduce the behavior

- yarn install
- yarn develop show error

### Steps to reproduce

- Update to 3.6.0
- Remove node_modules folder
- yarn Install
- yarn develop

### System

- Node.js version: v12.22.1
- NPM version: 6.14.12
- Strapi version: 3.5.3
- Database: Mongodb
- Operating system: MacOS

**Comment by kasonde** [comment]
> Steps to reproduce 

@Lykeosovandara is this after a fresh install/have you provided the full description of what brought you to this point?

**Comment by Lykeosovandara** [comment]
### Steps to reproduce
- Remove node_modules folder
- yarn Install
- yarn develop
It will show error

**Comment by derrickmehaffy** [comment]
@Lykeosovandara do you have a sample repo that you have reproduced the issue on as I tested this locally and could not reproduce.

**Comment by Lykeosovandara** [comment]
I try to test another project it works fine.
Now I update it to a new version 3.6.1 everything seems to work ok.
