### ISSUE TITLE
Build error: Can't resolve hooks/useDataManager

### ISSUE THREAD

**Issue by selfagency** [strapi/strapi#10244]
### Describe the bug

The build step fails towards the end of the process.

### Steps to reproduce the behavior

1. Upgrade a Strapi 3.5.x project to Strapi 3.6.x.
2. Run `strapi build`.

### Expected behavior

For the project to build.

### Screenshots

```
Error: Module not found: Error: Can't resolve '../../../../hooks/useDataManager' in '/Users/daniel/code/clients/kifa/kifa-cms/.cache/plugins/strapi-plugin-content-manager/admin/src/containers/EditView/Header/utils'
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/Users/daniel/code/clients/kifa/kifa-cms/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/Users/daniel/code/clients/kifa/kifa-cms/node_modules/webpack/lib/Compiler.js:265:20)
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/Users/daniel/code/clients/kifa/kifa-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/webpack/lib/Compilation.js:1173:13
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/webpack/lib/Compilation.js:1096:25
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/neo-async/async.js:2830:7
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/neo-async/async.js:2830:7
    at done (/Users/daniel/code/clients/kifa/kifa-cms/node_modules/neo-async/async.js:2863:11)
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/neo-async/async.js:2818:7
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/neo-async/async.js:2830:7
    at /Users/daniel/code/clients/kifa/kifa-cms/node_modules/neo-async/async.js:2830:7
    at done (/Users/daniel/code/clients/kifa/kifa-cms/node_modules/neo-async/async.js:2863:11)
```

### System

- Node.js version: 14.6.1
- NPM version: 7.11.2
- Strapi version: 3.6.1
- Database: MySQL 8
- Operating system: MacOS and Ubuntu

**Comment by selfagency** [comment]
Never mind, I was working in the wrong project like a big idiot

**Comment by selfagency** [comment]
Wait I'm not wrong

**Comment by selfagency** [comment]
Mac local

```
📂 kifa/kifa-strapi ⋅  master ⋅ 📦 v0.1.0 ⋅  v14.16.1 » 9s
18:45:35 ➜ strapi build
Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (68%) 2569/2624 modules 55 active
 babel-loader › .cache/plugins/strapi-plugin-content-manager/admin/src/components/Truncate/index.js

Error: Module not found: Error: Can't resolve '../../../../hooks/useDataManager' in '/Users/daniel/code/clients/kifa/kifa-strapi/.cache/plugins/strapi-plugin-content-manager/admin/src/containers/EditView/Header/utils'
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/Users/daniel/code/clients/kifa/kifa-strapi/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/Users/daniel/code/clients/kifa/kifa-strapi/node_modules/webpack/lib/Compiler.js:265:20)
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/Users/daniel/code/clients/kifa/kifa-strapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/webpack/lib/Compilation.js:1173:13
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/webpack/lib/Compilation.js:1096:25
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/neo-async/async.js:2830:7
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/neo-async/async.js:2830:7
    at done (/Users/daniel/code/clients/kifa/kifa-strapi/node_modules/neo-async/async.js:2863:11)
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/neo-async/async.js:2818:7
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/neo-async/async.js:2830:7
    at /Users/daniel/code/clients/kifa/kifa-strapi/node_modules/neo-async/async.js:2830:7
    at done (/Users/daniel/code/clients/kifa/kifa-strapi/node_modules/neo-async/async.js:2863:11)
```

Ubuntu remote

```
selfagency in selfagency.dev in /var/www/cms.kansasinterfaithaction.org/html via ⬢ v14.16.1
➜ strapi build
Building your admin UI with production configuration ...

● Webpack █████████████████████████ building (68%) 2820/2879 modules 59 active
 ...babel-loader › .cache/plugins/strapi-plugin-content-manager/admin/src/components/InputUID/Options/index.js

Error: Module not found: Error: Can't resolve '../../../../hooks/useDataManager' in '/mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/.cache/plugins/strapi-plugin-content-manager/admin/src/containers/EditView/Header/utils'
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/webpack/lib/Compiler.js:265:20)
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/webpack/lib/Compilation.js:1173:13
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/webpack/lib/Compilation.js:1096:25
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/webpack/lib/Compilation.js:1017:13
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/neo-async/async.js:2830:7
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/neo-async/async.js:2830:7
    at done (/mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/neo-async/async.js:2863:11)
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/neo-async/async.js:2818:7
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/webpack/lib/Compilation.js:1017:13
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/neo-async/async.js:2830:7
    at /mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/neo-async/async.js:2830:7
    at done (/mnt/selfagency_web_data/www/cms.kansasinterfaithaction.org/html/node_modules/neo-async/async.js:2863:11)
```

**Comment by selfagency** [comment]
Ok this was because of a plugin — strapi-plugin-preview-content

**Comment by nicoculotta** [comment]
Hi, I have the same issue. I upgraded the strapi version to 3.6.6 and then when I want to do the build I have the error. 

`Error: Module not found: Error: Can't resolve '../../hooks/useDataManager' in '/Users/a310619/strapi/wcm-be-strapi/.cache/plugins/strapi-plugin-content-manager/admin/src/containers/EditView'`

how did you fix it? Thanks

**Comment by selfagency** [comment]
@nicoculotta i decided using the plugin wasn't worth me tearing my hair out

**Comment by Prause** [comment]
@nicoculotta apparently you have to copy (replace) files from their [repo](https://github.com/danestves/strapi-plugin-preview-content/tree/main/strapi-files/v3.6.x/extensions) into your local `extensions/` folder (see also the "Copy required files" step in the [install readme](https://github.com/danestves/strapi-plugin-preview-content/blob/main/README.md) )
