### ISSUE TITLE
PostgreSQL: ERROR:  relation "core_store" does not exist at character 13

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#10290]
## Bug report

At initializing a new project with postgres in a docker stack, we are getting `ERROR:  relation "core_store" does not exist at character 13` from `postgres` container.

### Describe the bug

At running the stack we are looking:
```shell
postgres_1  | 2021-05-11 09:54:29.544 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-05-11 09:54:29.544 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-05-11 09:54:29.546 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-05-11 09:54:29.551 UTC [26] LOG:  database system was shut down at 2021-05-11 09:54:07 UTC
postgres_1  | 2021-05-11 09:54:29.559 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2021-05-11 09:54:34.079 UTC [33] ERROR:  relation "core_store" does not exist at character 13
postgres_1  | 2021-05-11 09:54:34.079 UTC [33] STATEMENT:  insert into "core_store" ("key", "type", "value") values ($1, $2, $3) returning *
strapi_1    | [2021-05-11T09:54:34.090Z] debug ⛔️ Server wasn't able to start properly.
strapi_1    | [2021-05-11T09:54:34.092Z] error error: insert into "core_store" ("key", "type", "value") values ($1, $2, $3) returning * - relation "core_store" does not exist
strapi_1    |     at Parser.parseErrorMessage (/srv/app/node_modules/pg-protocol/dist/parser.js:287:98)
strapi_1    |     at Parser.handlePacket (/srv/app/node_modules/pg-protocol/dist/parser.js:126:29)
strapi_1    |     at Parser.parse (/srv/app/node_modules/pg-protocol/dist/parser.js:39:38)
strapi_1    |     at Socket.<anonymous> (/srv/app/node_modules/pg-protocol/dist/index.js:11:42)
strapi_1    |     at Socket.emit (events.js:314:20)
strapi_1    |     at addChunk (_stream_readable.js:297:12)
strapi_1    |     at readableAddChunk (_stream_readable.js:272:9)
strapi_1    |     at Socket.Readable.push (_stream_readable.js:213:10)
strapi_1    |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
strapi_1    | From previous event:
strapi_1    |     at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/model.js:1160:42)
strapi_1    | From previous event:
strapi_1    |     at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/model.js:1159:14)
strapi_1    |     at processImmediate (internal/timers.js:461:21)
strapi_1    | From previous event:
strapi_1    |     at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/model.js:1060:10)
strapi_1    | From previous event:
strapi_1    |     at storeDefinition (/srv/app/node_modules/strapi-connector-bookshelf/lib/utils/store-definition.js:51:53)
strapi_1    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
strapi_1    |     at async module.exports (/srv/app/node_modules/strapi-connector-bookshelf/lib/build-database-schema.js:417:3)
strapi_1    |     at async /srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:671:11
strapi_1    |     at async module.exports (/srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:708:7)
strapi_1    |     at async mountConnection (/srv/app/node_modules/strapi-connector-bookshelf/lib/index.js:84:7)
strapi_1    |     at async Promise.all (index 0)
strapi_1    |     at async Object.initialize (/srv/app/node_modules/strapi-database/lib/connector-registry.js:30:9)
strapi_1    |     at async DatabaseManager.initialize (/srv/app/node_modules/strapi-database/lib/database-manager.js:43:5)
strapi_1    |     at async Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:354:5)
strapi_1    |     at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:196:9)
postgres_1  | 2021-05-11 09:54:34.116 UTC [33] LOG:  could not receive data from client: Connection reset by peer
cancer_strapi_1 exited with code 1
```

### Steps to reproduce the behavior

1. Initialize a new project.
2. Setup the docker compose file.
3. Launch the stack.
4. See error.

### Expected behavior
We should not see any problem and we should see the admin page.

### Code snippets
`./config/database`:
```javascript
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "postgres",
        host: env("DATABASE_HOST", "localhost"),
        port: env.int("DATABASE_PORT", 5432),
        database: env("DATABASE_NAME", "strapi"),
        username: env("DATABASE_USERNAME", "strapi"),
        password: env("DATABASE_PASSWORD", "strapi"),
        schema: env("DATABASE_SCHEMA", "public"),  // Not Required
        ssl: env.bool("DATABASE_SSL", false),
      },
    },
  },
});
```

`docker-compose.yml`:
```yaml
version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
```

`package.json`:
```json
"dependencies": {
    "knex": "0.21.18",
    "pg": "^8.6.0",
    "pg-connection-string": "^2.5.0",
    "strapi": "^3.6.1",
    "strapi-admin": "3.6.1",
    "strapi-connector-bookshelf": "^3.6.1",
    "strapi-plugin-content-manager": "3.6.1",
    "strapi-plugin-content-type-builder": "3.6.1",
    "strapi-plugin-email": "3.6.1",
    "strapi-plugin-graphql": "3.6.1",
    "strapi-plugin-i18n": "3.6.1",
    "strapi-plugin-upload": "3.6.1",
    "strapi-plugin-users-permissions": "3.6.1",
    "strapi-utils": "3.6.1"
  },
```

### System

- Node.js version: `12.20.1`
- NPM version: 
- Strapi version: `3.6.1`
- Database: `Postgres 13.2-1.pgdg100+1`
- Operating system:

### Additional context

This one does not solve our [problem](https://github.com/strapi/strapi/issues/9471#issuecomment-830728133).
We deleted the containers and its volumes multiple times and the issue persist.
Tested with **strapi** `3.6.2`, it still does not work.

**Comment by derrickmehaffy** [comment]
Using your reproduction steps I was not able to reproduce this issue, can you please try to create a new project to reproduce the problem and push it to a public github repo?

**Comment by SalahAdDin** [comment]
> Using your reproduction steps I was not able to reproduce this issue, can you please try to create a new project to reproduce the problem and push it to a public github repo?

![image](https://user-images.githubusercontent.com/5034215/118118272-5cc97c80-b3f5-11eb-8e3c-9d35d5354de9.png)

I tried it again, and it does not work, same bug again.

More specs:
```shell
❯ docker-compose -v
docker-compose version 1.29.1, build c34c88b2
❯ docker --version
Docker version 20.10.6, build 370c289
```
![image](https://user-images.githubusercontent.com/5034215/118118978-58519380-b3f6-11eb-87f5-203e628a183d.png)
![image](https://user-images.githubusercontent.com/5034215/118119034-68697300-b3f6-11eb-9b20-569ca67db41d.png)


Repository [here](https://github.com/SalahAdDin/strapi-postgres-docker).

**Comment by derrickmehaffy** [comment]
Found the problem, you were missing the options key.

add it your `./config/database.js` (it is created automatically meaning you had to manually edit this file).

```js
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "postgres",
        host: env("DATABASE_HOST", "localhost"),
        port: env.int("DATABASE_PORT", 5432),
        database: env("DATABASE_NAME", "strapi"),
        username: env("DATABASE_USERNAME", "strapi"),
        password: env("DATABASE_PASSWORD", "strapi"),
        schema: env("DATABASE_SCHEMA", "public"), // Not Required
        ssl: env.bool("DATABASE_SSL", false),
      },
      options: {}, // You were missing this
    },
  },
});
```

Marking as closed, but let me know if this fixed your issue.

**Comment by SalahAdDin** [comment]
> Found the problem, you were missing the options key.
> 
> add it your `./config/database.js` (it is created automatically meaning you had to manually edit this file).
> 
> ```js
> module.exports = ({ env }) => ({
>   defaultConnection: "default",
>   connections: {
>     default: {
>       connector: "bookshelf",
>       settings: {
>         client: "postgres",
>         host: env("DATABASE_HOST", "localhost"),
>         port: env.int("DATABASE_PORT", 5432),
>         database: env("DATABASE_NAME", "strapi"),
>         username: env("DATABASE_USERNAME", "strapi"),
>         password: env("DATABASE_PASSWORD", "strapi"),
>         schema: env("DATABASE_SCHEMA", "public"), // Not Required
>         ssl: env.bool("DATABASE_SSL", false),
>       },
>       options: {}, // You were missing this
>     },
>   },
> });
> ```
> 
> Marking as closed, but let me know if this fixed your issue.

It worked, thanks, how can we know `options` must exists? It is just a empty object.

**Comment by derrickmehaffy** [comment]
It's added by default, expect anything that exists by default is required.

**Comment by SalahAdDin** [comment]
> It's added by default, expect anything that exists by default is required.

May it be added to the documentation?

Thank you very much.

**Comment by derrickmehaffy** [comment]
Sure, reopening and transferring to documentation repo
