### ISSUE TITLE
Cannot convert undefined or null to object: Strapi Database related

### ISSUE THREAD

**Issue by michaelstokes** [strapi/strapi#10326]
Hi there!

Hope you're all doing okay!

When deploying a strapi app onto Digital Ocean Apps.

I'm getting the following error of which seems to be database related:

```
[2021-05-16T10:53:53.156557348Z] 
[2021-05-16T10:53:53.156594073Z] > strapitoheroku@0.1.0 start /workspace
[2021-05-16T10:53:53.156600267Z] > strapi start
[2021-05-16T10:53:53.156605046Z] 
[2021-05-16T10:54:03.044278780Z] [2021-05-16T10:54:03.043Z] debug ⛔️ Server wasn't able to start properly.
[2021-05-16T10:54:03.045744581Z] [2021-05-16T10:54:03.045Z] error TypeError: Cannot convert undefined or null to object
[2021-05-16T10:54:03.046627915Z]     at Function.values (<anonymous>)
[2021-05-16T10:54:03.046641806Z]     at Object.load (/workspace/node_modules/strapi-database/lib/connector-registry.js:17:39)
[2021-05-16T10:54:03.046663149Z]     at DatabaseManager.initialize (/workspace/node_modules/strapi-database/lib/database-manager.js:32:21)
[2021-05-16T10:54:03.046672445Z]     at Strapi.load (/workspace/node_modules/strapi/lib/Strapi.js:311:19)
[2021-05-16T10:54:03.046678399Z]     at async Strapi.start (/workspace/node_modules/strapi/lib/Strapi.js:190:9)
[2021-05-16T10:54:03.095879174Z] npm ERR! code ELIFECYCLE
[2021-05-16T10:54:03.097417712Z] npm ERR! errno 1
[2021-05-16T10:54:03.102707153Z] npm ERR! strapitoheroku@0.1.0 start: `strapi start`
[2021-05-16T10:54:03.103357439Z] npm ERR! Exit status 1
[2021-05-16T10:54:03.104039956Z] npm ERR! 
[2021-05-16T10:54:03.104739249Z] npm ERR! Failed at the strapitoheroku@0.1.0 start script.
[2021-05-16T10:54:03.105249973Z] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2021-05-16T10:54:03.134369178Z] 
[2021-05-16T10:54:03.134779524Z] npm ERR! A complete log of this run can be found in:
[2021-05-16T10:54:03.135135663Z] npm ERR!     /workspace/.npm/_logs/2021-05-16T10_54_03_106Z-debug.log
```

I have several environment configurations and the one I'm working with here is `qa` and so in the `config/env/qa` directory I have a `database.js` of which has the following content:

```
const fs = require('fs');

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST'),
        port: env('DATABASE_PORT'),
        database: env('DATABASE_NAME'),
        username: env('DATABASE_USERNAME'),
        password: env('DATABASE_PASSWORD'),
        ssl: {
          ca: fs.readFileSync(`${__dirname}/ca-certificate.crt`).toString(),
          rejectUnauthorized: false
        }
      },
      options: {
        ssl: false
      }
    },
  },
});
```

The build seems to succeed with `NODE_ENV=qa npm run build -- --clean` but starting the application server is where it seems to error.

I'm currently exploring Digital Ocean Apps to simplify things.

I have been able to build and run the application on my own managed ubuntu server under `pm2` with `ssl` enabled.

Thank you for your help :)

**Comment by michaelstokes** [comment]
**Update**
The issue was resolved with the strapi application server starting successfully following removal of:

```
const fs = require('fs');`
ca: fs.readFileSync(`${__dirname}/ca-certificate.crt`).toString(),
```

As I mentioned above, using ssl on my own managed ubuntu instance with pm2 works.

This brings me to question as to what the problem is with using `fs`.

**Comment by michaelstokes** [comment]
**Update**
I was able to get this working and using `fs` (which previously appeared to be an issue). `database.js` file now looks like this:

```
const fs = require('fs');

const ca = fs.readFileSync(`${__dirname}/ca-certificate.crt`).toString();

console.log('listing directory contents', __dirname)
fs.readdirSync(__dirname).forEach(file => {
  console.log(file);
});

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST'),
        port: env('DATABASE_PORT'),
        database: env('DATABASE_NAME'),
        username: env('DATABASE_USERNAME'),
        password: env('DATABASE_PASSWORD'),
        ssl: {
          ca,
          rejectUnauthorized: false
        }
      },
      options: {
        ssl: true
      }
    },
  },
});
```

I'm not sure why it worked this time as all you can see, I moved the `fs.readFileSync` to the top and adding in the `fs.readfirsync` as I wanted to verify the contents of the directory ... and it started working.

I'd still be interested if anyone has any comments on this.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by crussell42** [comment]
EXTRANEOUS CONFIG FILES.
This is also caused by extraneous files in the config dir.
e.g. if you use emacs and 'database.js~' file is created by the editor, 
you will see this error. 
Solution
find . -name "*~" -exec rm {} \;
