### ISSUE TITLE
while uploading image I am getting error

### ISSUE THREAD

**Issue by harshitsan** [strapi/strapi#10391]
## Bug report

Whenever I am trying to add an image, I am getting an error like this:
![Screenshot (584)](https://user-images.githubusercontent.com/30543655/119767182-0586da00-bed4-11eb-8be7-4bbebcafaa63.png)
` error CastError: Cast to ObjectId failed for value "[object Object]" at path "_id" for model "file"
    at model.Query.exec (C:\Users\harsh\Documents\programming\dein-strapi\node_modules\mongoose\lib\query.js:4371:21)
    at model.Query.Query.then (C:\Users\harsh\Documents\programming\dein-strapi\node_modules\mongoose\lib\query.js:4463:15)   
    at processTicksAndRejections (internal/process/task_queues.iled for value "[object Object]" at path "_id" fjs:93:5)                                                       ein-strapi\node_modules\mongoose\lib\query.js:43
[2021-05-27T04:19:22.756Z] debug PUT /content-manager/collectioming\dein-strapi\node_modules\mongoose\lib\queryn-types/application::gigs.gigs/6083e82922ba1c2e69e9bd48 (4514 mjs:93:5)s) 400      `

### Describe the bug

Could not save image
Using Cloudinary for storing assets and MongoDB as database.

### Steps to reproduce the behavior

1. Not exactly sure, how do I reproduce this, because in my another strapi project, I am not facing this issue.

### Expected behavior
1. Image should save successfully 

### System

-Strapi Version: 3.6.0
-Operating System: Windows 10
-Database: MongoDB
-Node Version: v14.16.0
-NPM Version: 6.14.11
-Yarn Version: 1.22.10

### Additional context

shifting to MongoDB could be the problem

**Comment by harshitsan** [comment]
I removed the field, saved the collection, and then again added the field and it worked.
