### ISSUE TITLE
Cannot find module 'uuid/v4' when installing on AWS server

### ISSUE THREAD

**Issue by erik-valtechsd** [strapi/strapi#10395]
## Bug report
I am trying to install on AWS using your guide https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html

I installed strapi using quickstart, uploaded to git and installed in on my AWS server. When I npm build on the server I get the following error (see below). How can I fix this? I can confirm it builds locally, this only happens on the server. Thanks

> backend@0.1.0 build /home/ubuntu/TES-backend
> strapi build

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'uuid/v4'
Require stack:
- /home/ubuntu/TES-backend/node_modules/webpack-log/src/index.js
- /home/ubuntu/TES-backend/node_modules/webpack-dev-middleware/lib/context.js
- /home/ubuntu/TES-backend/node_modules/webpack-dev-middleware/index.js
- /home/ubuntu/TES-backend/node_modules/webpack-dev-server/lib/Server.js
- /home/ubuntu/TES-backend/node_modules/strapi-admin/index.js
- /home/ubuntu/TES-backend/node_modules/strapi/lib/commands/build.js
- /home/ubuntu/TES-backend/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/TES-backend/node_modules/webpack-log/src/index.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/TES-backend/node_modules/webpack-log/src/index.js',
    '/home/ubuntu/TES-backend/node_modules/webpack-dev-middleware/lib/context.js',
    '/home/ubuntu/TES-backend/node_modules/webpack-dev-middleware/index.js',
    '/home/ubuntu/TES-backend/node_modules/webpack-dev-server/lib/Server.js',
    '/home/ubuntu/TES-backend/node_modules/strapi-admin/index.js',
    '/home/ubuntu/TES-backend/node_modules/strapi/lib/commands/build.js',
    '/home/ubuntu/TES-backend/node_modules/strapi/bin/strapi.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the backend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-05-27T11_26_38_941Z-debug.log

**Comment by erik-valtechsd** [comment]
For some reason `npm clean-install` fixed this issue
