### ISSUE TITLE
Getting error targetModel.updateMany is not a function

### ISSUE THREAD

**Issue by singetak** [strapi/strapi#10438]
https://github.com/strapi/strapi/blob/0ab3503e3c68c0e794878324a866ce9e6cfe5d47/packages/strapi-connector-mongoose/lib/relations.js#L476

When trying to delete a file that is related to a collection on strapi i get an error here

error TypeError: targetModel.updateMany is not a function
at Promise.all.entry.(anonymous function).map.val (/node_modules/strapi-connector-mongoose/lib/relations.js:476:40)
at CoreDocumentArray.map ()
at CoreDocumentArray.map (/node_modules/mongoose/lib/types/documentarray.js:42:27)
at Promise.all.associations.map (/node_modules/strapi-connector-mongoose/lib/relations.js:464:42)
at Array.map ()
at Function.deleteRelations (/node_modules/strapi-connector-mongoose/lib/relations.js:393:25)
at deleteOne (/node_modules/strapi-connector-mongoose/lib/queries.js:560:17)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by kasonde** [comment]
Hi @singetak please share some information about your current environment.

**Comment by AndreaGero** [comment]
Hi,

i'm having the same issue, those are the info:

  - OS: Windows 10
  - Node: 14.16.0
  - Strapi: 3.6.3
  - Mongo DB 4.4.6

I have a model with a collection of photos, and when i try to delete a single photo with the default route `/upload/files/${id}` or with a custom controller using this service:

`await strapi.plugins.upload.services.upload.remove(file);`

I have this error:

`TypeError: targetModel.updateMany is not a function
    at C:\laragon\www\support-sf-backend\node_modules\strapi-connector-mongoose\lib\relations.js:487:38
    at CoreDocumentArray.map (<anonymous>)
    at CoreDocumentArray.map (C:\laragon\www\support-sf-backend\node_modules\mongoose\lib\types\documentarray.js:42:27)
    at C:\laragon\www\support-sf-backend\node_modules\strapi-connector-mongoose\lib\relations.js:464:42
    at Array.map (<anonymous>)
    at Function.deleteRelations (C:\laragon\www\support-sf-backend\node_modules\strapi-connector-mongoose\lib\relations.js:393:25)
    at deleteOne (C:\laragon\www\support-sf-backend\node_modules\strapi-connector-mongoose\lib\queries.js:560:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.delete (C:\laragon\www\support-sf-backend\node_modules\strapi-database\lib\queries\helpers.js:15:18)
    at async Object.removePhoto (C:\laragon\www\support-sf-backend\api\cases\services\cases.js:91:5)
    at async Object.removePhoto (C:\laragon\www\support-sf-backend\api\cases\controllers\cases.js:102:5)
    at async C:\laragon\www\support-sf-backend\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:79:22
    at async module.exports (C:\laragon\www\support-sf-backend\node_modules\strapi-plugin-users-permissions\config\policies\permissions.js:88:3)
    at async C:\laragon\www\support-sf-backend\node_modules\strapi-utils\lib\policy.js:68:5
    at async C:\laragon\www\support-sf-backend\node_modules\strapi\lib\middlewares\parser\index.js:48:23
    at async C:\laragon\www\support-sf-backend\node_modules\strapi\lib\middlewares\xss\index.js:26:9
`

Thank you

**Comment by aksdevac** [comment]
Got similar error while calling `strapi.query('file', 'upload').delete()` as workaround deleted using mongoose query, & also deleted related object manually using another query using mongoose.

**Comment by kasonde** [comment]
Thanks for the info @singetak , I'll review this issue and provide feedback with my findings

**Comment by CanadaViet** [comment]
I have the same error also. 
    deleteFile(apiURL) {
        return fetch("/upload/files/" + idfile, {
            method: "DELETE",
            headers: {
                "Authorization": "Bearer " + Cookies.get("token")
            }
        });
    };

**Comment by LNeziriDev** [comment]
Hi all, until the Strapi team solves this,
I managed to solve this by removing the reference of the media first then delete it.
My use case: I have a user and an avatar as a profile picture.
So when I wanted to remove the avatar I did "Put" request to the user collection with avatar: null, then I removed the avatar and it worked perfectly.

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed

**Comment by topovik** [comment]
Use it, guys
https://stackoverflow.com/a/71432801/12369840
