### ISSUE TITLE
malicious requests crashed server

### ISSUE THREAD

**Issue by garytube** [strapi/strapi#10460]
### Describe the bug
Today I noticed malicious request on my backend server which caused the server to crash.
```
[2021-06-09T13:51:40.646Z] debug GET /admin/.htpasswd (0 ms) 200
[2021-06-09T13:51:40.646Z] debug GET /dist/wiki.php/<script>foo</script> (2 ms) 404
[2021-06-09T13:51:40.657Z] debug GET /moniwiki/wiki.php (1 ms) 404
[2021-06-09T13:51:40.673Z] debug GET /mollify/backend/plugin/Registration/index.php?confirm=%3Cscript%3Ealert(%27openvasvt%27)%3C/script%3E (0 ms) 404
[2021-06-09T13:51:40.708Z] debug GET /admin/.htpasswd-all (1 ms) 200
[2021-06-09T13:51:40.713Z] debug GET /milw0rm/ (0 ms) 404
[2021-06-09T13:51:40.719Z] debug GET /backend/plugin/Registration/index.php?confirm=%3Cscript%3Ealert(%27openvasvt%27)%3C/script%3E (1 ms) 404

  Error: Parse Error: Invalid method encountered

[2021-06-09T13:51:40.731Z] error Error: Request aborted
    at IncomingMessage.<anonymous> (/srv/app/node_modules/formidable/lib/incoming_form.js:122:19)
    at IncomingMessage.emit (events.js:314:20)
    at abortIncoming (_http_server.js:533:9)
    at socketOnClose (_http_server.js:526:3)
    at Socket.emit (events.js:326:22)
    at TCP.<anonymous> (net.js:675:12)
[2021-06-09T13:51:40.732Z] debug POST /AAAAAAAAAAAAAAAAAAAAA (4 ms) 500
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at WriteStream._write (internal/fs/streams.js:379:33)
    at WriteStream.<anonymous> (internal/fs/streams.js:375:12)
    at Object.onceWrapper (events.js:421:26)
    at WriteStream.emit (events.js:326:22)
    at internal/fs/streams.js:366:10
    at FSReqCallback.oncomplete (fs.js:156:23)
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at WriteStream._write (internal/fs/streams.js:379:30)
    at WriteStream.<anonymous> (internal/fs/streams.js:375:12)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:156:23) {
  code: 'ERR_STREAM_DESTROYED'
}
```

#### Strapi Docker
- Node.js version:  v12.20.1
- Strapi version: v3.6.3
- Database: PSQL
- Operating system: Ubuntu 20.1 / Docker

**Comment by derrickmehaffy** [comment]
On a side note, can you also check your available space on the mounted storage to the container.

**Comment by garytube** [comment]
sadly no. I will dig into the server logs and try to find the post body

**Comment by derrickmehaffy** [comment]
How many resources (ram) is given to your container as we are wondering if it's possible slow-loris style attack (cc @kasonde) where they are intentionally slowing down the connection to try and fill your memory buffer.

We did some testing with large file payloads but on most of our test apps either a 413 response is returned from Cloudflare, Nginx, or Strapi itself so it seems unlikely.

But outside of that I haven't been able to reproduce it, but we do want to get to the bottom of this ASAP.

**Comment by garytube** [comment]
Sadly my nginx does not log the post data

```
34.107.96.89 - - [09/Jun/2021:13:51:40 +0000] "POST /AAAAAAAAAAAAAAAAAAAAA HTTP/1.1" 500 96 "-" "cyberscan.io"''
```

The Server is running on digital ocean droplet
4 GB Memory / 2 Intel vCPUs / 80 GB Disk / FRA1 - Ubuntu 20.04 (LTS) x64

```
CONTAINER ID   NAME                       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
ee3c0ba17ff3   x-backend_strapi_1     3.51%     104.9MiB / 3.844GiB   2.67%     576MB / 662MB   0B / 4.1kB       11
abd13599ff28   x-backend_postgres_1   1.15%     38.56MiB / 3.844GiB
```

**Comment by derrickmehaffy** [comment]
We may just need to hold this issue until we can figure out the payload that was sent so we can reproduce it. :thinking:

**Comment by derrickmehaffy** [comment]
To date we haven't been able to reproduce this in v3 or v4. I'm gonna mark it as closed since we are at the 6 month mark and no one has provided any additional information or reports of this attack happening.

**Comment by AntonioDev152** [comment]
I have a similar problem.
When I make a request of type GET more than 3 times I get the same error.
` |   Error: Parse Error: Invalid method encountered`

System:
Node.js version: v14.20.0
Strapi version: v3.6.8
Database: Mongo  DB
Operating system: Linux 2

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
