### ISSUE TITLE
Upload media content doesn't work with plugin upload-aws-s3

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#10469]
### Describe the bug

I use Strapi and plugin for uploads media to S3 bucket.

Docs: https://habr.com/ru/post/546938/ (in Russian)
Cloud Service: Yandex Cloud, it supports S3.

Uploading worked correctly in Strapi version 3.6.2. 
Now it has error in version 3.6.3.

### Steps to reproduce the behavior

1. Go to item of collection "posts"
2. Try to upload image to the Media Library for that post
3. Click to button "Upload 1 asset to the library"
4. See error "An internal server error occured"

Also I see the error message in console: 
```
[2021-06-11t14:01:54.069z] error MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/param_validator.js:50:37) 
at ParamValidator.validateStructure (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/config.js:386:7)
    at /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/config.js:428:9
    at Object.<anonymous> (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:111:13)
    at Object.arrayEach (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/util.js:521:32)
    at resolveNext (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:110:20)
    at /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
    at /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/credentials.js:124:23
    at /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/aws-sdk/lib/credentials.js:212:15

[2021-06-11T14:01:54.073Z] error Error: Internal Server Error
    at convertToStrapiError (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi-plugin-upload/errors.js:38:26)
    at Object.upload (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.uploadFileAndPersist (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi-plugin-upload/services/Upload.js:154:5)
    at async Promise.all (index 0)
    at async Object.upload (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi-plugin-upload/services/Upload.js:140:12)
    at async uploadFiles (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi-plugin-upload/controllers/upload/admin.js:187:27)
    at async Object.upload (/Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi-plugin-upload/controllers/Upload.js:65:5)
    at async /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi-utils/lib/policy.js:68:5
    at async /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /Users/teine/Development/traffic-exchange-media/media-backend/node_modules/strapi/lib/middlewares/xss/index.js:26:9

[2021-06-11T14:01:54.073Z] debug POST /upload (5566 ms) 500

```

### Expected behavior

Image is uploaded to the cloud correctly as it was in version Strapi 3.6.2.

### Screenshots

<img width="1398" alt="112" src="https://user-images.githubusercontent.com/1038168/121701317-72f05880-cad9-11eb-8a05-165bccfa9540.png">

<img width="925" alt="111" src="https://user-images.githubusercontent.com/1038168/121701291-6bc94a80-cad9-11eb-9ed4-987e6afc5714.png">

### Code snippets

I have file `config/plugins.js` as it's described in docs.
```
module.exports = ({ env })=>({
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      endpoint: 'https://storage.yandexcloud.net',
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_ACCESS_SECRET'),
      region: env('AWS_REGION'),
      params: {
        Bucket: env('AWS_BUCKET'),
      },
    },
  },
});
```

`.env.local`

```
HOST=0.0.0.0
PORT=1337
AWS_ACCESS_KEY_ID=mycodekey
AWS_ACCESS_SECRET="mycodesecret"
AWS_REGION="ru-central1"
AWS_BUCKET="strapi-static"
```

### System

- Node.js version: 14.16.1
- NPM version: 6.14.13
- Strapi version: 3.6.3
- Database: SQlite
- Operating system: MacOS localhost

**Comment by derrickmehaffy** [comment]
That specific provider is only designed to work with AWS-S3, any other "S3-like" provider is not supported by that package and we would recommend you create your own provider as others have done for "S3-like" hosts:

https://www.npmjs.com/package/strapi-provider-upload-do

**Comment by chiragkanjariya** [comment]
anyone has worked on [Wasabi](https://wasabi.com/) Provider?

**Comment by romatou** [comment]
Every example on the web, [Strapi maintained providers](https://github.com/strapi/strapi/tree/master/packages/providers) and packages in NPM registry use v2 SDK for their provider upload plugin. Has anyone tried applying [AWS JavaScript V3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/introduction/)?

I've been trying for a couple of days now and had no luck. 

```TypeScript
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3'

export = {
  init(providerOptions) {
    const {...config} = providerOptions
    
    const getFileKey = (file: File) => {
      const path = `${config.endpoint}/${config.bucket}/${file.hash}${file.ext}`
      return path
    }

    const s3Client = new S3Client({
      endpoint: config.endpoint || 'https://s3.timeweb.com',
      region: config.region || 'ru-1',
      forcePathStyle: true,
      credentials: {
        accessKeyId: config.accessKeyId,
        secretAccessKey: config.secretAccessKey,
      },
    })

    return {
      async upload(file: File) {
        const fileKey = getFileKey(file)

        await s3Client.send(
          new PutObjectCommand({
            Bucket: config.bucket,
            Key: fileKey,
            Body: file.buffer,
            ContentType: file.mime,
          })
        )
      },
      // ...
  }
}
```

I tried writing hardcoded variables (error: 502: UnknownError), for uploadStream, I get:

```
Error: Resolved credential object is not valid
    at SignatureV4.validateResolvedCredentials (/Users/roma/Sites/reelstories/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:182:19)
    at SignatureV4.signRequest (/Users/roma/Sites/reelstories/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:107:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
```

Maybe I have missed something 🤷
Their API reference is not very friendly and it is not easy to go through types and interfaces on their website.
