### ISSUE TITLE
Can't disable relation types in GraphQL schema

### ISSUE THREAD

**Issue by NGuldager** [strapi/strapi#10477]
### Describe the bug

I want to disable querying for a specific relation in GraphQL. I'm following the guide here: https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#disable-a-type-attribute

But it only works for regular attributes and components, but not if it's a list relation to another collection.

### Steps to reproduce the behavior

1. Create 2 collections.
2. Use the GraphQL plugin
3. Create a many to many relation (or one to many)
3. Follow the guide to disable a type here: https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#disable-a-type-attribute
    - If using many to many relation it doesn't matter which one you disable
    - If using one to many. Disable the relation on the collection that has a list of the other collection
4. See error in console

### Expected behavior

The relation attribute should no longer appear in GraphQL schema

### Code snippets

```javascript
module.exports = {
    type: {
        Organization: {
            assessments: false,
        },
    },
}
```

### System

- Node.js version: v12.22.1
- NPM version: 6.14.12
- Strapi version: 3.6.3
- Database: SQLite
- Operating system: macOS Version 11.1

### Additional info

In the code snippet i have a one-to-many relation between the Organization and Assessment collections.
In Strapi UI: Organization has many Assessments

**Comment by kasonde** [comment]
For reference is a snippet of my stack trace after reproducing this issue:
```
debug ⛔️ Server wasn't able to start properly.
[2021-06-15T08:49:10.225Z] error TypeError: Cannot read property 'replace' of undefined
    at nonRequired (/project-folder/node_modules/strapi-plugin-graphql/services/utils.js:106:34)
    at isNumberType (/project-folder/node_modules/strapi-plugin-graphql/services/build-aggregation.js:63:27)
    at /project-folder/node_modules/strapi-plugin-graphql/services/build-aggregation.js:74:11
    at /project-folder/node_modules/lodash/lodash.js:928:11
    at /project-folder/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/project-folder/node_modules/lodash/lodash.js:3032:24)
    at /project-folder/node_modules/lodash/lodash.js:4936:18
    at baseReduce (/project-folder/node_modules/lodash/lodash.js:925:5)
    at Function.reduce (/project-folder/node_modules/lodash/lodash.js:9749:14)
    at getFieldsByTypes (/project-folder/node_modules/strapi-plugin-graphql/services/build-aggregation.js:71:12)
    at formatConnectionAggregator (/project-folder/node_modules/strapi-plugin-graphql/services/build-aggregation.js:359:25)
    at formatModelConnectionsGQL (/project-folder/node_modules/strapi-plugin-graphql/services/build-aggregation.js:503:28)
    at buildCollectionType (/project-folder/node_modules/strapi-plugin-graphql/services/shadow-crud.js:526:35)
    at /project-folder/node_modules/strapi-plugin-graphql/services/shadow-crud.js:348:16
    at Array.map (<anonymous>)
    at buildModels (/project-folder/node_modules/strapi-plugin-graphql/services/shadow-crud.js:337:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
