### ISSUE TITLE
Setting up strapi apollo graphQL on AWS

### ISSUE THREAD

**Issue by erik-valtechsd** [strapi/strapi#10489]
### Describe the bug
 I followed [this guide](https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo) to create a Nuxt + Strapi + Apollo GraphQL website and then followed the [strapi guide](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html) for deploying to AWS.

I now have Strapi running on an aws instance and my frontend on AWS Amplify. I am now trying to setup GraphQL so my website can pull content from strapi. But I'm not able to get it working.

### Steps to reproduce the behavior
1. Create Strapi backend as described in  [this guide](https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo) 
2. Deploy Strapi backend to AWS as described in [strapi guide](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html)  
3. Create Nuxt frontend as described in  [this guide](https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo) 
4. Deploy Nuxt frontend to AWS Amplify as described in [this guide](https://nuxtjs.org/docs/2.x/deployment/deployment-amazon-web-services)
5. Now you have a front end and a back end,  we arrive at the problem: how to configure a strapi AWS endpoint so the frontend can query the strapi backend to get strapi content?

### Expected behavior
Nuxt frontend should be able to connect to strapi endpoint and query strapi content. Instead an error is appearing (see **_code snippet_** section)

### Code snippets

I  apollo configured on  `~/config/plugins.js`  like this:
```
  graphql: {
    endpoint: "/graphql",
    shadowCRUD: true,
    playgroundAlways: false,
    depthLimit: 7,
    amountLimit: 100,
    apolloServer: {
      tracing: false
    }
  }
```

On the frontend, I have apollo configured on `nuxt.config.js` like this:
```
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: http://xx.xx.xx.xx:1337/graphql
      }
    }
  },
```

But I building my nuxt frontend I am getting the following error:
```
Error: Network error: Unexpected token M in JSON at position 0
    at new ApolloError (/.../.../frontend/node_modules/apollo-client/bundle.umd.js:92:26)
    at .../.../frontend/node_modules/apollo-client/bundle.umd.js:1588:34
    at .../.../frontend/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /.../...//frontend/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/.../.../frontend/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /.../.../frontend/node_modules/apollo-client/bundle.umd.js:1483:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)  
```
### System
- Node.js version: v12.13.1
- NPM version:6.12.1
- Strapi version: "3.6.2"
- Database: Amazon AWS EC2 
- Operating system: MacOS 11.3.1

I was able to send queries from my frontend to a different graphql, so I think the problem is how I'm configuring strapi graphQL. Any help is much appreciated.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by erik-valtechsd** [comment]
@derrickmehaffy  I updated this issue
