### ISSUE TITLE
Multiple database connections: Invalid input data. Please verify input constraints

### ISSUE THREAD

**Issue by adrianorsouza** [strapi/strapi#10576]
## Bug report

A Relation Field where data comes from a second MySQL connection does not update the model and also the oneWay relation in a another collection as expected.

### Describe the bug

The scenario is 2 MySQL connections setup within `database.js`, the `default` and `blog`.
The blog connection already contains a table e.g: `wp_posts` where I can read data from then populate a Select field that I can make as a oneWay relation in another CollectionType e.g: `Pages`.

The Page CollectionType in the Admin have the select field _(Relation with Posts)_ where I can select a post from blog connection and grab the ID and store it in a table `pages` column called `post`.

The problem happens when you choose one item from the relation field and click save. Then you see the message:

`Then the message Invalid input data. Please verify input constraints.`

Here is the console error, as you can see in the first line the query for post model is looking in the wrong connection `strapi_db1.wp_posts` and not `strapi_db2.wp_posts` as it supposed to be:

```sh
[2021-07-02T14:30:59.258Z] error Error: select distinct `wp_posts`.* from `wp_posts` where `wp_posts`.`id` in (2) - ER_NO_SUCH_TABLE: Table 'strapi_db1.wp_posts' doesn't exist
    at Query.Sequence._packetToError (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at Protocol._enqueue (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/client.js:168:17)
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/transaction.js:325:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/transaction.js:320:12)
    at Runner.query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/runner.js:151:36)
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/runner.js:40:23
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/runner.js:277:24
From previous event:
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Sync.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/sync.js:204:8)
From previous event:
    at EagerRelation.eagerFetch (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/eager.js:30:8)
    at EagerRelation.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1526:56)
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:732:27)
From previous event:
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:730:12)
From previous event:
    at Child.refresh (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:544:19)
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1191:27)
From previous event:
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1162:14)
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1060:10)
From previous event:
    at Function.update [as updateRelations] (/Users/ars/Temp/strapi-issue/app/node_modules/strapi-connector-bookshelf/lib/relations.js:384:10)
```

### Steps to reproduce the behavior

1. Create 2 MySQL connections, default and blog.
2. The Blog database already have one table called `wp_posts` or whatever.
3. Create a new CollectionType called `Page` for the default connection.
4. Create a new model called Posts within the `api/pages/models` and place a file `post.js` and `post.settings.json`.
5. Define `post.settings.json` to use the blog connection instead of default one as: `"connection": "blog"`.
6. In the Admin Panel create a new a one-way Relation field in `Page` collectionType and choose the Posts model.
7. Go to the Page collection and select one item from relation field and click save.

### Expected behavior

A query for the model Post within blog connection should prefix the table name with the name of the database like:

```
select distinct `strapi_db2`.`wp_posts`.* from `strapi_db2`.`wp_posts` where `strapi_db2`.`wp_posts`.`id` in (2)
```

This way we can read data from different connections and update relations.

NOTE: 
If I hardcoded the database name for the second connection within `post.settings.json` like below, the query will work just fine, but by doing this can arise some problems when the application goes to different environment where the database may change the name, let's say `strapi_db2_dev` and `strapi_db2_prod`: 

```
{
  "kind": "collectionType",
  "connection": "blog",
  "collectionName": "strapi_db2.wp_posts",
  "info": {
    "name": "Posts",
    "description": ""
  },
 ...
}
```

### Screenshots
<img width="1878" alt="Screen Shot 2021-07-02 at 12 14 34" src="https://user-images.githubusercontent.com/5430240/124295410-2ecc0300-db2f-11eb-83bd-889933fa94e4.png">

<img width="1878" alt="Screen Shot 2021-07-02 at 12 16 00" src="https://user-images.githubusercontent.com/5430240/124295510-4d31fe80-db2f-11eb-8c3e-f3a50a97b27b.png">

### Code snippets

**Database configuration**

```js
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
          client: 'mysql',
          host: 'localhost',
          port: 3306,
          database: 'strapi_db1',
          username: 'strapi',
          password: 'strapi'
      },
      options: {
        useNullAsDefault: true,
        autoMigration: true
      },
    },
    blog: {
      connector: 'bookshelf',
      settings: {
          client: 'mysql',
          host: 'localhost',
          port: 3306,
          database: 'strapi_db2',
          username: 'strapi',
          password: 'strapi'
      },
      options: {
        useNullAsDefault: true,
        autoMigration: false
      },
    },
  },
});

```

**Pages Collection**

```json
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "name": "page",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "text"
    },
    "post": {
      "model": "post"
    }
  }
}
```
**Post Collection**

```JSON
{
  "kind": "collectionType",
  "connection": "blog",
  "collectionName": "wp_posts",
  "info": {
    "name": "Posts",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": false,
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "post_title": {
      "type": "text"
    }
  }
}
```

### System

- Node.js version: v14.17.1
- NPM version: 6.14.13
- Strapi version: 3.6.5
- Database: MySQL 8.0.23
- Operating system: macOS 11.4

### Additional context

The same error happens if you try to update an entry from the Admin Panel where the connection for collectionType is different of the default you get this error: 

<img width="1878" alt="Screen Shot 2021-07-02 at 12 18 04" src="https://user-images.githubusercontent.com/5430240/124295754-95e9b780-db2f-11eb-8184-0d66bd86c324.png">

```
[2021-07-02T15:18:31.174Z] error Error: select distinct `strapi_administrator`.* from `strapi_administrator` where 1 = 0 - ER_NO_SUCH_TABLE: Table 'strapi_db2.strapi_administrator' doesn't exist
    at Query.Sequence._packetToError (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at Protocol._enqueue (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/ars/Temp/strapi-issue/app/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/client.js:168:17)
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/transaction.js:325:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/transaction.js:320:12)
    at Runner.query (/Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/runner.js:151:36)
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/runner.js:40:23
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/runner.js:277:24
From previous event:
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Sync.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/sync.js:204:8)
From previous event:
    at EagerRelation.eagerFetch (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/eager.js:30:8)
    at EagerRelation.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1526:56)
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:732:27)
From previous event:
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:730:12)
From previous event:
    at Child.refresh (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:544:19)
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1191:27)
From previous event:
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1162:14)
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Child.<anonymous> (/Users/ars/Temp/strapi-issue/app/node_modules/bookshelf/lib/model.js:1060:10)
From previous event:
    at runCreate (/Users/ars/Temp/strapi-issue/app/node_modules/strapi-connector-bookshelf/lib/queries.js:113:45)
    at /Users/ars/Temp/strapi-issue/app/node_modules/strapi-connector-bookshelf/lib/queries.js:53:34
    at /Users/ars/Temp/strapi-issue/app/node_modules/knex/lib/transaction.js:183:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-07-02T15:18:31.175Z] debug POST /content-manager/collection-types/application::page.post (28 ms) 400
```

**Comment by derrickmehaffy** [comment]
We do not currently support cross database relations due to missing logic within bookshelf itself and in our v4 we will be entirely removing the multi-database connections.

I'm going to set this as closed since it's not something we plan to fix, thank you for the report though.
