### ISSUE TITLE
strapi-plugin-graphql: disabling associations in schema.graphql.js

### ISSUE THREAD

**Issue by landeholt** [strapi/strapi#10606]
### Describe the bug

Strapi crashes upon trying to disable associations for GraphQL requests.

### Steps to reproduce the behavior

1. Create 2 collections, with a 1:M relation, in my instance its Events and Orders
2. Create a `schema.graphql.js` file for Events.
3. Add following to `schema.graphql.js`:
```js
  type: {
    Event: {
      orders: false,
    },
  }
```
4. Strapi crashes with this error message:
```
[2021-07-13T16:25:14.415Z] debug ⛔️ Server wasn't able to start properly.
[2021-07-13T16:25:14.416Z] error TypeError: Cannot read property 'replace' of undefined
    at nonRequired (<PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/utils.js:106:34)
    at isNumberType (<PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/build-aggregation.js:63:27)
    at <PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/build-aggregation.js:74:11
    at <PROJECT_FOLDER>/node_modules/lodash/lodash.js:928:11
    at <PROJECT_FOLDER>/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (<PROJECT_FOLDER>/node_modules/lodash/lodash.js:3032:24)
    at <PROJECT_FOLDER>/node_modules/lodash/lodash.js:4936:18
    at baseReduce (<PROJECT_FOLDER>/node_modules/lodash/lodash.js:925:5)
    at Function.reduce (<PROJECT_FOLDER>/node_modules/lodash/lodash.js:9749:14)
    at getFieldsByTypes (<PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/build-aggregation.js:71:12)
    at formatConnectionAggregator (<PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/build-aggregation.js:359:25)
    at formatModelConnectionsGQL (<PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/build-aggregation.js:503:28)
    at buildCollectionType (<PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/shadow-crud.js:526:35)
    at <PROJECT_FOLDER>/node_modules/strapi-plugin-graphql/services/shadow-crud.js:348:16
    at Array.map (<anonymous>)
    at buildModels (<PROJECT_FOLDER>/strapi-plugin-graphql/services/shadow-crud.js:337:17)
```

### Expected behavior

This seems to be a case where the devs have forgotten to implement tests. You should be able to disable associations aswell as regular attributes.

### System

- Node.js version: 14.17.1
- NPM version:6.14.13
- Strapi version: 3.6.2
- Database: sqlite / postgres
- Operating system: macOS

### Additional context

I've tried to debug `strapi-plugin-graphql` but was overwhelmed over trying to contribute with a PR.

I think I've found the missing link in the puzzle.

https://github.com/strapi/strapi/blob/df832fafd1705266d65bae22d8dd3a0fe37964cf/packages/strapi-plugin-graphql/services/shadow-crud.js#L122-L134

where if you make this change:

```js
associations
    .filter(association => association.type === 'collection')
    .filter(association => isNotPrivate(model, association.alias))
    .filter(association => isTypeAssociationEnabled(model, association))
    .forEach(association => {
      typeDef[`${association.alias}(sort: String, limit: Int, start: Int, where: JSON)`] =
        typeDef[association.alias];

      delete typeDef[association.alias];
    });
```

and create the new function `isTypeAssociationEnabled` as

```js
const isTypeAssociationEnabled = (model, {alias}) => _.get(strapi.plugins.graphql, `config._schema.graphql.type.${model.globalId}.${alias}`) !== false;
```

This makes strapi start properly again, because we are actually removing associations that are flagged as false now. Which wasn't the case before.

As well as not allowing GraphQL queries for Event.orders.

**Comment by derrickmehaffy** [comment]
@Convly is this something you can confirm and do you think it will be fixed with the GraphQL v4 rewrite?

**Comment by Convly** [comment]
I'll look at this and try to reproduce it ASAP. However, as @derrickmehaffy mentioned, this behavior will be changed in V4 anyway.

**Comment by derrickmehaffy** [comment]
closing as it shouldn't apply in the v4
