### ISSUE TITLE
Setting `published_at` throws an error

### ISSUE THREAD

**Issue by jackHedaya** [strapi/strapi#10611]
### Describe the bug

I'd like every request that hits might endpoint to create a draft as opposed to automatically publishing it. I tried manually setting `published_at` to null but the server reports a crash, though saves all the fields correctly and labels the model as a draft.

Currently, my service looks like this:

```js
const vendorData = await strapi.entityValidator.validateEntityCreation(
          strapi.models.vendor,
          { ...otherData, users, addresses },
          { isDraft: true } // Indicates that a full validation should be done
 );

// Attempt to unset published_at which causes 500 Internal Server error
// vendorData.published_at = null;

 const vendor = await strapi
          .query("vendor")
          .create(vendorData, { transacting });

return vendor;
```

The error is like so:

```
[2021-07-15T19:48:34.552Z] error TypeError: Cannot convert undefined or null to object
    at Object.create (/api/vendor/controllers/vendor.js:30:5)
    at async (/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async Object.module.exports [as isauthenticated] (/node_modules/strapi-plugin-users-permissions/config/policies/isAuthenticated.js:8:3)
    at async module.exports (/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:84:12)
    at async /node_modules/strapi-utils/lib/policy.js:68:5
    at async node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /node_modules/strapi/lib/middlewares/xss/index.js:26:9
```

**Comment by jackHedaya** [comment]
Ehh my bad, looks like it was an issue where adding the line of code was causing a race condition to fail. All good now!

**Comment by derrickmehaffy** [comment]
Glad you got it fixed because I was having some trouble reproducing the issue :wink:
