### ISSUE TITLE
Server unable to start properly - relation already exists

### ISSUE THREAD

**Issue by HydraCOREY** [strapi/strapi#10636]
## Bug report

Unable to start server `yarn develop` after shutdown.
Seems like it's trying to migrate and create all the tables over again.
The table name seems like it's being cut off in postgres. "blog_posts_topics__blog_post_topics_blog_p" seems like it's cut off at the "_p" at the end...

### Steps to reproduce the behavior

1. Run:
    `npx create-strapi-app backend`
2. Select "Custom (manual settings)
3. Type "N" to create a template
4. Choose "postgres"
5. Setup postgres credentials and select "no" for SSL connection
6. Application completes
7. Added email provider:
    `yarn add strapi-provider-email-sendgrid`
8. Added upload provider:
    `yarn add strapi-provider-upload-aws-s3`
9. Edited `config/plugins.js`
    ```js
    module.exports = ({ env }) => ({
        email: {
            provider: 'sendgrid',
            providerOptions: {
                apiKey: env('SENDGRID_API_KEY', 'my API key is here, not showing for security'),
            },
            settings: {
              defaultFrom: 'noreply@test.com',
              defaultReplyTo: 'noreply@test.com',
              testAddress: 'noreply@test.com',
            },
        },
        upload: {
            provider: 'aws-s3',
            providerOptions: {
                accessKeyId: env('AWS_ACCESS_KEY_ID'),
                secretAccessKey: env('AWS_ACCESS_SECRET'),
                region: env('AWS_REGION'),
                params: {
                    Bucket: env('AWS_BUCKET_NAME'),
                },
                logger: console // Only if you want to 'stdout' logs
            }
        }
    });
    ```
10. Ran:
      `yarn build`
11. Ran:
      `yarn develop`
12. Entered "super admin" credentials and entered admin panel
13. Created two tables("blog post", and "blog post topic" each with a name field
14. Added a "many to many" relationship
15. Created some topics, then created some posts and attached a topic to each
16. Shut server down
17. Tried running server again and got the following error:
      ```bash
      strapi develop
      [2021-07-21T19:39:15.526Z] debug ⛔️ Server wasn't able to start properly.
      [2021-07-21T19:39:15.527Z] error error: create table "blog_posts_topics__blog_post_topics_blog_posts" ("id" serial primary key, "blog-post-topic_id" integer null, "blog-post_id" integer null) - relation "blog_posts_topics__blog_post_topics_blog_p" already exists
      at Parser.parseErrorMessage (/home/user/workspace/strapi/backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/user/workspace/strapi/backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/user/workspace/strapi/backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/user/workspace/strapi/backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      error Command failed with exit code 1.
      ```

### Expected behavior

Expected the server to start and continue where I left off.

### System

- Operating system: Ubuntu 20.04.2
- Strapi: 3.6.5
- Database: postgres
- package.json:
  ```json
  {
    "name": "backend",
    "private": true,
    "version": "0.1.0",
    "description": "A Strapi application",
    "scripts": {
          "develop": "strapi develop",
          "start": "strapi start",
          "build": "strapi build",
          "strapi": "strapi"
      },
      "devDependencies": {
          "babel-eslint": "^10.1.0",
          "eslint": "^7.31.0"
      },
      "dependencies": {
          "knex": "0.21.18",
          "pg": "8.5.1",
          "strapi": "3.6.5",
          "strapi-admin": "3.6.5",
          "strapi-connector-bookshelf": "3.6.5",
          "strapi-plugin-content-manager": "3.6.5",
          "strapi-plugin-content-type-builder": "3.6.5",
          "strapi-plugin-email": "3.6.5",
          "strapi-plugin-i18n": "3.6.5",
          "strapi-plugin-upload": "3.6.5",
          "strapi-plugin-users-permissions": "3.6.5",
          "strapi-provider-email-sendgrid": "^3.6.5",
          "strapi-provider-upload-aws-s3": "^3.6.5",
          "strapi-utils": "3.6.5"
      },
      "author": {
          "name": "A Strapi developer"
      },
      "strapi": {
          "uuid": "9397a713-f145-4acc-955b-96d7ed56de30"
      },
      "engines": {
          "node": ">=10.16.0 <=14.x.x",
          "npm": "^6.0.0"
      },
      "license": "MIT"
  }
  ```

**Comment by HydraCOREY** [comment]
Seems to be related to:
https://github.com/strapi/strapi/issues/3409
Even though that issue was closed...

**Comment by valerie-makes** [comment]
I'm experiencing this issue too with Strapi v4 and PostgreSQL hosted on Render.

Each time I make a schema change and deploy to Render, the first `strapi start` fails, stating that the new table has already been created:

```
Dec 13 10:57:28 AM  [2021-12-13 10:57:28.849] error: create table "work_pages" ("id" serial primary key, "title" varchar(255) null, "summary" varchar(255) null, "created_at" timestamp(6) null, "updated_at" timestamp(6) null, "published_at" timestamp(6) null, "created_by_id" integer null, "updated_by_id" integer null) - relation "work_pages" already exists
Dec 13 10:57:28 AM  error: create table "work_pages" ("id" serial primary key, "title" varchar(255) null, "summary" varchar(255) null, "created_at" timestamp(6) null, "updated_at" timestamp(6) null, "published_at" timestamp(6) null, "created_by_id" integer null, "updated_by_id" integer null) - relation "work_pages" already exists
```

However, the next deploy succeeds. This happens consistently each time I make a schema update.

I'm surprised this is labelled with "severity: low" considering it doubles the deployment time for each schema change.

**Comment by valerie-makes** [comment]
If someone more familiar with the codebase could point me towards where database migrations are generated and performed, specifically those for new relations, I would be happy to look into this and see if I can create a PR to fix.

**Comment by derrickmehaffy** [comment]
relational side should be fixed in v4. Components is still an issue, for that see: https://github.com/strapi/strapi/issues/12101

Marking as closed as this should be more or less fixed in v4
