### ISSUE TITLE
SQL error prevents server starting

### ISSUE THREAD

**Issue by callum-gander** [strapi/strapi#10649]
## Bug report

``
### Describe the bug

Incorrectly added a second 'user' field to the Orders type, saved it and then the server crashed, wouldn't run and I repeatedly got the error message below

### Steps to reproduce the behavior

[2021-07-23T20:22:51.530Z] debug ⛔️ Server wasn't able to start properly.
[2021-07-23T20:22:51.531Z] error Error: There can be only one type named "OrdersConnectionUser".

Field "OrdersConnectionUser.key" can only be defined once.

Field "OrdersConnectionUser.connection" can only be defined once.
    at assertValidSDL (/Users/callum/Documents/WebDev/Portfolio-v2/normans-website/backend/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/Users/callum/Documents/WebDev/Portfolio-v2/normans-website/backend/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/callum/Documents/WebDev/Portfolio-v2/normans-website/backend/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (/Users/callum/Documents/WebDev/Portfolio-v2/normans-website/backend/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/callum/Documents/WebDev/Portfolio-v2/normans-website/backend/node_modules/strapi-plugin-graphql/services/schema-generator.js:101:18)
    at Object.initialize (/Users/callum/Documents/WebDev/Portfolio-v2/normans-website/backend/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:76:74)
    at /Users/callum/Documents/WebDev/Portfolio-v2/normans-website/backend/node_modules/strapi/lib/hooks/index.js:37:28

1. Run the backend server
2. The following error message shows up and I'm unable to run the server and delete this incorrect content-type

### Expected behavior

I created a new content-type called Orders. It had a many to one relation with the Users type, I wasn't really making the content-type and thinking about how it would translate into SQL, forgot to delete the old 'user' field when I added the new relation to the user type, server crashed and then the above error came up. I can't start the dashboard to delete the offending relation and field. I have no idea how strapi builds or links the database. I tried to delete various parts of the orders.settings.json, tried to mess around with the schema.graphql but generally have no idea how strapi creates and links the database. I need to get this server running again, how can I just delete the orders type and the relation to the users type so that I can run the server again? 

### System

- Node.js version: v15.4.0
- NPM version: 7.19.0
- Strapi version: 3.6.5
- Database: SQLite
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Delete the orders folder under the api folder, then go to the extensions/users-permissions/models/user.settings.json and delete the key in the attributes object that is the relation to that model.

You may need to open the database in a GUI or CLI and delete the related table for the orders model and the column in the users table. We plan to automatically handle the database cleanup in the coming v4.

Still a bit confused how you managed to get the error in the first place :thinking:

**Comment by callum-gander** [comment]
That fixed it, cheers! Didn't need to open the database and clean the tables up.
I was just as confused as you 😅 all I did was add a relational field with the same name and saved it before realising and it just crashed and gave me that errror. Thanks again!

**Comment by callum-gander** [comment]
That fixed it, cheers! I'm just as confused as you 😅 all I did was add a relational field to orders with the same name as an existing field, saved without realising and it crashed. Thanks again!
