### ISSUE TITLE
Malformed Foreign key constraint on Admin Permissions (v4)

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#10693]
### Describe the bug

When attempting to start a fresh v4-alpha project on MariaDB the `@strapi/admin` is attempting to create a foreign key constraint between the created_by causing a failure to init the database

### Steps to reproduce the behavior

1. Create project targeting a MariaDB database
2. Start the server

### Expected behavior

Either we disable the FQ constraint or validate the creation and make sure it's using the proper syntax

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/128233377-97bd4619-930d-47d6-bfcc-dbe3cecd9a52.png)

### Code snippets

Raw Query Error log:

```
Error: ER_CANT_CREATE_TABLE: Can't create table `strapi`.`strapi_permissions` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.Sequence._packetToError (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    --------------------
    at Protocol._enqueue (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/Connection.js:198:25)
    at /mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/client.js:134:12)
    at /mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/execution/transaction.js:358:12) {
  code: 'ER_CANT_CREATE_TABLE',
  errno: 1005,
  sqlMessage: 'Can\'t create table `strapi`.`strapi_permissions` (errno: 150 "Foreign key constraint is incorrectly formed")',
  sqlState: 'HY000',
  index: 0,
  sql: 'alter table `strapi_permissions` add constraint `created_by_id_fk` foreign key (`created_by_id`) references `strapi_users` (`id`) on delete SET NULL'
}
```

Strapi Error Log:

```
[2021-08-04 11:13:29.173] error: alter table `strapi_permissions` add constraint `created_by_id_fk` foreign key (`created_by_id`) references `strapi_users` (`id`) on delete SET NULL - ER_CANT_CREATE_TABLE: Can't create table `strapi`.`strapi_permissions` (errno: 150 "Foreign key constraint is incorrectly formed")
Error: ER_CANT_CREATE_TABLE: Can't create table `strapi`.`strapi_permissions` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.Sequence._packetToError (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    --------------------
    at Protocol._enqueue (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/mnt/storage/Development/v4-alpha-test2/node_modules/mysql/lib/Connection.js:198:25)
    at /mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/client.js:134:12)
    at /mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/mnt/storage/Development/v4-alpha-test2/node_modules/knex/lib/execution/transaction.js:358:12)
error Command failed with exit code 1.
```

### System

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v4.0.0-next.2
- Database: MariaDB v10.5.11
- Operating system: Linux Mint 20.2 (Ubuntu 20.04.2)

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
Tested on MariaDB 10.5 and MySQL 8 with similar results. Retested both in a clean Ubuntu 20.04.2 Server Virtual machine with the same results

**Comment by derrickmehaffy** [comment]
Original issue is fixed but a new one appeared:

```
[2021-09-10 14:26:09.606] error: delete from `up_permissions` as `t0` where (`t0`.`id` = 3) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `t0` where (`t0`.`id` = 3)' at line 1
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `t0` where (`t0`.`id` = 3)' at line 1
    at Query.Sequence._packetToError (/mnt/storage/Development/testNext11/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/mnt/storage/Development/testNext11/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/mnt/storage/Development/testNext11/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/mnt/storage/Development/testNext11/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/mnt/storage/Development/testNext11/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/mnt/storage/Development/testNext11/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/mnt/storage/Development/testNext11/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/mnt/storage/Development/testNext11/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    --------------------
    at Protocol._enqueue (/mnt/storage/Development/testNext11/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/mnt/storage/Development/testNext11/node_modules/mysql/lib/Connection.js:198:25)
    at /mnt/storage/Development/testNext11/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/mnt/storage/Development/testNext11/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/mnt/storage/Development/testNext11/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/mnt/storage/Development/testNext11/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/mnt/storage/Development/testNext11/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/mnt/storage/Development/testNext11/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/mnt/storage/Development/testNext11/node_modules/knex/lib/execution/runner.js:272:20)
error Command failed with exit code 1.
```

**Comment by derrickmehaffy** [comment]
fixed in beta.0
