### ISSUE TITLE
Strapi server failed to start after I install graphql plugin

### ISSUE THREAD

**Issue by krazylearner** [strapi/strapi#10726]
### Describe the bug

Strapi server failed to start after I install grapql plugin

### Steps to reproduce the behavior

1. npm run strapi install graphql
2. npm run develop

### Expected behavior

Strapi server should start and graphql should be accessible at http://localhost:1337/graphql

### Screenshots

`> strapi develop

[2021-08-12T16:21:26.653Z] debug ⛔️ Server wasn't able to start properly.
[2021-08-12T16:21:26.657Z] error Error: Enum type ENUM_COMPONENTBUTTONBUTTON_TARGET cannot include value: null.

Enum type ENUM_COMPONENTHORIZONTALSECTIONSTIMELINEITEMS_ALIGN cannot include value: null.
    at assertValidSchema (D:\bob\myproject\node_modules\graphql\type\validate.js:69:11)
    at assertValidExecutionArguments (D:\bob\myproject\node_modules\graphql\execution\execute.js:150:35)
    at executeImpl (D:\bob\myproject\node_modules\graphql\execution\execute.js:98:3)
    at Object.execute (D:\bob\myproject\node_modules\graphql\execution\execute.js:60:63)
    at Object.generateSchemaHash (D:\bob\myproject\node_modules\apollo-server-core\dist\utils\schemaHash.js:15:32)
    at ApolloServer.generateSchemaDerivedData (D:\bob\myproject\node_modules\apollo-server-core\dist\ApolloServer.js:407:41)
    at new ApolloServerBase (D:\bob\myproject\node_modules\apollo-server-core\dist\ApolloServer.js:204:41)
    at new ApolloServer (D:\bob\myproject\node_modules\apollo-server-koa\dist\ApolloServer.js:64:1)
    at Object.initialize (D:\bob\myproject\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:136:22)
    at D:\bob\myproject\node_modules\strapi\lib\hooks\index.js:37:28`

### System

- Node.js version: 
12.22.0
- NPM version:
6.14.11
- Strapi version: 
- Database:
sqllite
- Operating system:
Windows 10 64 BIT

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7904
