### ISSUE TITLE
Unable to upgrade Strapi from 3.6.7 to 3.6.8

### ISSUE THREAD

**Issue by multiwebinc** [strapi/strapi#10821]
I previously had Strapi working perfectly with version 3.6.7, however today I upgraded it to 3.6.8 by editing the package.json file and then executing `npm run build -- --clean` and now I get the following error when trying to start the dev server:

```
$ npm run develop

> ibgs@0.1.0 develop
> strapi develop

[2021-08-28T22:12:15.557Z] debug ⛔️ Server wasn't able to start properly.
[2021-08-28T22:12:15.557Z] error Error: Cannot use GraphQLObjectType "Query" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/node_modules/graphql/jsutils/instanceOf.js:29:13)
    at isObjectType (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/node_modules/graphql/type/definition.js:122:34)
    at printType (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:130:36)
    at /home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:59:12
    at Array.map (<anonymous>)
    at printFilteredSchema (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:58:13)
    at Object.printSchema (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:40:10)
    at writeGenerateSchema (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/services/schema-generator.js:138:31)
    at Object.generateSchema (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/services/schema-generator.js:109:5)
    at Object.initialize (/home/mike/Seafile/www/ibgs/strapi/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:76:74)
    at /home/mike/Seafile/www/ibgs/strapi/node_modules/strapi/lib/hooks/index.js:37:28
```

Here is my `package.json` file:

```json
{
  "name": "ibgs",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "slugify": "^1.4.7",
    "strapi": "^3.6.8",
    "strapi-admin": "^3.6.8",
    "strapi-connector-mongoose": "^3.6.8",
    "strapi-plugin-content-manager": "^3.6.8",
    "strapi-plugin-content-type-builder": "^3.6.8",
    "strapi-plugin-documentation": "^3.6.8",
    "strapi-plugin-email": "^3.6.8",
    "strapi-plugin-graphql": "^3.6.8",
    "strapi-plugin-upload": "^3.6.8",
    "strapi-plugin-users-permissions": "^3.6.8",
    "strapi-utils": "^3.6.8"
  },
  "resolutions": {
    "graphql": "^14.7.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "7a9ae376-5de0-466c-af8e-cda5d04a5820"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^7.0.0"
  },
  "license": "MIT"
}
```

I tried deleting my `package-lock.json` file and the `node_modules` directory and running `npm install` and I get the following messages:

```
$ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: graphql-type-long@0.1.1
npm WARN Found: graphql@14.7.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^14.5.0 || ^15.0.0" from @apollo/federation@0.20.7
npm WARN   node_modules/@apollo/federation
npm WARN     @apollo/federation@"^0.20.7" from strapi-plugin-graphql@3.6.8
npm WARN     node_modules/strapi-plugin-graphql
npm WARN   25 more (@graphql-tools/utils, apollo-server-koa, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from graphql-type-long@0.1.1
npm WARN node_modules/graphql-type-long
npm WARN   graphql-type-long@"^0.1.1" from strapi-plugin-graphql@3.6.8
npm WARN   node_modules/strapi-plugin-graphql
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.21.0' }
npm WARN EBADENGINE }
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated intl-messageformat-parser@5.5.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat

added 1824 packages, and audited 1825 packages in 35s

118 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

I also tried adding:

```
  "resolutions": {
    "graphql": "^14.7.0"
  },
```

to my package.json and then `npm install`, but that didn't seem to fix it.

Here is the output for `npm list graphql`:

```
$ npm list graphql
ibgs@0.1.0 /home/mike/Seafile/www/ibgs/strapi
└─┬ strapi-plugin-graphql@3.6.8
  ├─┬ @apollo/federation@0.20.7
  │ ├─┬ apollo-graphql@0.6.1
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ └── graphql@14.7.0 invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  ├─┬ @graphql-tools/utils@7.2.4
  │ └── graphql@14.7.0 deduped
  ├─┬ apollo-server-koa@2.24.0
  │ ├─┬ apollo-server-core@2.25.2
  │ │ ├─┬ @apollographql/graphql-upload-8-fork@8.1.3
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ apollo-cache-control@0.14.0
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ apollo-graphql@0.9.3
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ apollo-server-errors@2.5.0
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ apollo-server-plugin-base@0.13.0
  │ │ │ ├─┬ apollo-server-types@0.9.0
  │ │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ apollo-server-types@0.9.0
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ apollo-tracing@0.15.0
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ graphql-extensions@0.15.0
  │ │ │ ├─┬ apollo-server-types@0.9.0
  │ │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├─┬ graphql-tag@2.12.5
  │ │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ ├── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ └─┬ subscriptions-transport-ws@0.9.19
  │ │   └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ ├─┬ apollo-server-types@0.8.0
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ ├─┬ graphql-subscriptions@1.2.1
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-depth-limit@1.1.0
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-iso-date@3.6.1
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-tools@4.0.8
  │ ├─┬ apollo-link@1.2.14
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ ├─┬ apollo-utilities@1.3.4
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-type-json@0.3.2
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-type-long@0.1.1
  │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  ├─┬ graphql-upload@11.0.0
  │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  └── graphql@15.5.0

npm ERR! code ELSPROBLEMS
npm ERR! invalid: graphql@14.7.0 /home/mike/Seafile/www/ibgs/strapi/node_modules/graphql

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mike/.npm/_logs/2021-08-28T22_09_21_259Z-debug.log
```

It would appear that both 14.7.0 and 15.5.0 are installed, so I tried to override 15.5.0 with 14.7.0, but I get the following error message:

```
$ npm install graphql@14.7.0
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: graphql-type-long@0.1.1
npm WARN Found: graphql@14.7.0
npm WARN node_modules/graphql
npm WARN   graphql@"14.7.0" from the root project
npm WARN   26 more (@apollo/federation, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from graphql-type-long@0.1.1
npm WARN node_modules/graphql-type-long
npm WARN   graphql-type-long@"^0.1.1" from strapi-plugin-graphql@3.6.8
npm WARN   node_modules/strapi-plugin-graphql
npm WARN 
npm WARN Conflicting peer dependency: graphql@0.13.2
npm WARN node_modules/graphql
npm WARN   peer graphql@"^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from graphql-type-long@0.1.1
npm WARN   node_modules/graphql-type-long
npm WARN     graphql-type-long@"^0.1.1" from strapi-plugin-graphql@3.6.8
npm WARN     node_modules/strapi-plugin-graphql
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.21.0' }
npm WARN EBADENGINE }
```

### System

- Node.js version: 14.16.0
- NPM version: 7.21.0
- Database: MongoDB
- Operating system: Linux

**Comment by multiwebinc** [comment]
I dunno. I tried removing `node_modules` and `package.json` a second time, then just did `npm i` and it's working now.

**Comment by derrickmehaffy** [comment]
> I dunno. I tried removing `node_modules` and `package.json` a second time, then just did `npm i` and it's working now.

I assume you mean package-lock.json and not package.json :stuck_out_tongue:

**Comment by multiwebinc** [comment]
> I assume you mean package-lock.json and not package.json

Yes. Sorry about that. I've updated my other post.
