### ISSUE TITLE
`yarn develop` and `yarn start` error with TypeError: Cannot redefine property: __filename__

### ISSUE THREAD

**Issue by stutrek** [strapi/strapi#10822]
### Describe the bug

`yarn start` and `yarn develop` fail like so:

```
% yarn develop 
yarn run v1.22.10
$ strapi develop
[2021-08-29T01:28:08.778Z] debug ⛔️ Server wasn't able to start properly.
[2021-08-29T01:28:08.780Z] error TypeError: Cannot redefine property: __filename__
    at Function.defineProperty (<anonymous>)
    at loadFiles (/Users/stuart/Repos/eagle-api/node_modules/strapi/lib/load/load-files.js:40:12)
    at async module.exports (/Users/stuart/Repos/eagle-api/node_modules/strapi/lib/core/load-apis.js:18:16)
    at async Promise.all (index 0)
    at async module.exports (/Users/stuart/Repos/eagle-api/node_modules/strapi/lib/core/load-modules.js:24:76)
    at async Strapi.load (/Users/stuart/Repos/eagle-api/node_modules/strapi/lib/Strapi.js:329:21)
    at async Strapi.start (/Users/stuart/Repos/eagle-api/node_modules/strapi/lib/Strapi.js:196:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System

- Node.js version: v14.17.5
- NPM version: 6.14.14
- yarn version: 1.22.10
- Strapi version: 3.6.6 and 3.6.8
- Database: sqlite
- Operating system: latest macos

**Comment by stutrek** [comment]
I tracked it down to this file: `node_modules/@apollo/federation/dist/composition/index.js`

contents are this:
```js
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./compose"), exports);
__exportStar(require("./composeAndValidate"), exports);
__exportStar(require("./types"), exports);
var rules_1 = require("./rules");
Object.defineProperty(exports, "compositionRules", { enumerable: true, get: function () { return rules_1.compositionRules; } });
var normalize_1 = require("./normalize");
Object.defineProperty(exports, "normalizeTypeDefs", { enumerable: true, get: function () { return normalize_1.normalizeTypeDefs; } });
var utils_1 = require("./utils");
Object.defineProperty(exports, "defaultRootOperationNameLookup", { enumerable: true, get: function () { return utils_1.defaultRootOperationNameLookup; } });
//# sourceMappingURL=index.js.map%
```

**Comment by stutrek** [comment]
Nevermind, this was my fault.
