### ISSUE TITLE
Creating project fails ...

### ISSUE THREAD

**Issue by blaasvaer** [strapi/strapi#1108]
I get this when following your get started guide:

```
/Users/sam/.nvm/versions/node/v6.11.5/lib/node_modules/strapi/node_modules/strapi-utils/lib/policy.js:96
    return async (ctx, next) => {
                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sam/.nvm/versions/node/v6.11.5/lib/node_modules/strapi/node_modules/strapi-utils/lib/index.js:16:11)
```

**Comment by blaasvaer** [comment]
Well, running the wrong npm version for whatever reason.
