### ISSUE TITLE
v4 does not run on windows

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#11137]
The Strapi v4 Quickstart does not boot up on windows

Excerpt:
```
node_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\Luca\Downloads\temp\beta.cache\admin\src'
  Parsed request is a module
  using description file: C:\Users\Luca\Downloads\temp\beta.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as modul
```

Full build output
```
C:\Users\Luca\Downloads\temp\beta
λ npm run build

> beta@0.1.0 build C:\Users\Luca\Downloads\temp\beta
> strapi build

Building your admin UI with development configuration ...

* Webpack █████████████████████████ building (10%) 0/1 entries 111/124 dependencies 10/83 modules 70 active
 babel-loader » .cache\admin\src\core\utils\createHook.js

ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapistrapi
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\Luca\Downloads\temp\beta\.cache\admin\src'
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\Compilation.js:1765:28
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (C:\Users\Luca\Downloads\temp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\Users\Luca\Downloads\temp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at C:\Users\Luca\Downloads\temp\beta\node_modules\neo-async\async.js:6883:13
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (C:\Users\Luca\Downloads\temp\beta\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\Luca\Downloads\temp\beta\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\Luca\Downloads\temp\beta\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\Luca\Downloads\temp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapistrapi
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\Luca\Downloads\temp\beta\.cache\admin\src'
  Parsed request is a module
  using description file: C:\Users\Luca\Downloads\temp\beta\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\Luca\Downloads\temp\beta\.cache\admin\src\node_modules doesn't exist or is not a directory
      C:\Users\Luca\Downloads\temp\beta\.cache\admin\node_modules doesn't exist or is not a directory
      C:\Users\Luca\Downloads\temp\beta\.cache\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\Luca\Downloads\temp\beta\node_modules
        C:\Users\Luca\Downloads\temp\beta\node_modules\......
ode_modules@strapistrapi
ode_modules@strapiplugin-content-type-builder doesn't exist
      C:\Users\Luca\Downloads\temp\node_modules doesn't exist or is not a directory
      C:\Users\Luca\Downloads\node_modules doesn't exist or is not a directory
      C:\Users\Luca\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapistrapi
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\Luca\Downloads\temp\beta\.cache\admin\src'
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\Compilation.js:1765:28
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (C:\Users\Luca\Downloads\temp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\Users\Luca\Downloads\temp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at C:\Users\Luca\Downloads\temp\beta\node_modules\neo-async\async.js:6883:13
    at C:\Users\Luca\Downloads\temp\beta\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (C:\Users\Luca\Downloads\temp\beta\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\Luca\Downloads\temp\beta\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\Luca\Downloads\temp\beta\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\Luca\Downloads\temp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapistrapi
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\Luca\Downloads\temp\beta\.cache\admin\src'
  Parsed request is a module
  using description file: C:\Users\Luca\Downloads\temp\beta\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\Luca\Downloads\temp\beta\.cache\admin\src\node_modules doesn't exist or is not a directory
      C:\Users\Luca\Downloads\temp\beta\.cache\admin\node_modules doesn't exist or is not a directory
      C:\Users\Luca\Downloads\temp\beta\.cache\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\Luca\Downloads\temp\beta\node_modules
        C:\Users\Luca\Downloads\temp\beta\node_modules\......
ode_modules@strapistrapi
ode_modules@strapiplugin-content-type-builder doesn't exist
      C:\Users\Luca\Downloads\temp\node_modules doesn't exist or is not a directory
      C:\Users\Luca\Downloads\node_modules doesn't exist or is not a directory
      C:\Users\Luca\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beta@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the beta@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luca\AppData\Roaming\npm-cache\_logs\2021-09-29T17_40_53_897Z-debug.log
```

As confirmed via discord, I am not the only one with this issue and it can be "easily" replicated.
Just run the `npx create-strapi-app@beta beta --quickstart` command on a windows os.

### System

- Node.js version: v14 LTS
- Strapi version: 4.0.0-beta.0
- Database: sqlite
- Operating system: windows 11

**Comment by derrickmehaffy** [comment]
@malgamves can you also add your windows error stuff as well.

**Comment by fristyr** [comment]
I have same issue

**Comment by derrickmehaffy** [comment]
## Temporary solutions for windows users! Please use WSL until we patch this.

**Comment by ChristherLenander** [comment]
Same problem here.

**Comment by aaron5670** [comment]
Same issue here.

**Comment by niklasfjeldberg** [comment]
Same problem.

**Comment by galago** [comment]
Same issue

**Comment by aaron5670** [comment]
## Strapi V4 beta inside a Docker container
If you want to try the Strapi beta, you can clone my repo and run ``docker-compose up``. 😃 

**Repo:**
https://github.com/aaron5670/strapi-v4-docker

**Comment by malgamves** [comment]
> @malgamves can you also add your windows error stuff as well.


Sure @derrickmehaffy 


Command: `npx create-strapi-app@beta beta.15 --quickstart`

Error: 
```
Creating a quickstart project.
Creating a new Strapi application at C:\Users\malga\beta.15.
Creating files.
Dependencies installed successfully.

Your application was created at C:\Users\malga\beta.15.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode.

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd C:\Users\malga\beta.15
  yarn develop


> beta-15@0.1.0 build
> strapi build "--no-optimization"

Building your admin UI with development configuration ...

* Webpack █████████████████████████ building (10%) 0/1 entries 54/115 dependencies 7/33 modules 18 active
 node_modules\react\index.js

ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\malga\beta.15\.cache\admin\src'
    at C:\Users\malga\beta.15\node_modules\webpack\lib\Compilation.js:1765:28
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (C:\Users\malga\beta.15\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\Users\malga\beta.15\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at C:\Users\malga\beta.15\node_modules\neo-async\async.js:6883:13
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (C:\Users\malga\beta.15\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\malga\beta.15\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\malga\beta.15\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\malga\beta.15\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\malga\beta.15\.cache\admin\src'
  Parsed request is a module
  using description file: C:\Users\malga\beta.15\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\malga\beta.15\.cache\admin\src\node_modules doesn't exist or is not a directory
      C:\Users\malga\beta.15\.cache\admin\node_modules doesn't exist or is not a directory
      C:\Users\malga\beta.15\.cache\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\malga\beta.15\node_modules
        C:\Users\malga\beta.15\node_modules\......
ode_modules@strapiplugin-content-type-builder doesn't exist
      C:\Users\malga\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\malga\beta.15\.cache\admin\src'
    at C:\Users\malga\beta.15\node_modules\webpack\lib\Compilation.js:1765:28
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (C:\Users\malga\beta.15\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\Users\malga\beta.15\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at C:\Users\malga\beta.15\node_modules\neo-async\async.js:6883:13
    at C:\Users\malga\beta.15\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (C:\Users\malga\beta.15\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\malga\beta.15\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\malga\beta.15\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\malga\beta.15\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\malga\beta.15\.cache\admin\src'
  Parsed request is a module
  using description file: C:\Users\malga\beta.15\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\malga\beta.15\.cache\admin\src\node_modules doesn't exist or is not a directory
      C:\Users\malga\beta.15\.cache\admin\node_modules doesn't exist or is not a directory
      C:\Users\malga\beta.15\.cache\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\malga\beta.15\node_modules
        C:\Users\malga\beta.15\node_modules\......
ode_modules@strapiplugin-content-type-builder doesn't exist
      C:\Users\malga\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
```

System
- Node.js version: v14.15.0
- Strapi version: 4.0.0-beta.1
- Database: SQLite
- Operating System: Windows 10

**Comment by LucaNerlich** [comment]
Seems to work with beta.2

![image](https://user-images.githubusercontent.com/5942270/135902527-0b25ebf7-b983-42da-a7ec-98d4f0fff2ec.png)

Windows 11

```json
    "@strapi/strapi": "4.0.0-beta.2",
    "@strapi/plugin-users-permissions": "4.0.0-beta.2",
    "@strapi/plugin-i18n": "4.0.0-beta.2",
```

**Comment by derrickmehaffy** [comment]
fixed with beta.2
