### ISSUE TITLE
[V4] Getting "Plural name should be unique" error on content type creation

### ISSUE THREAD

**Issue by codesxt** [strapi/strapi#11145]
---
name: 🐛 Plural name should be unique
about: Error happens on creation of content type in V4 Beta
---

### Describe the bug

I just created a Collection Type called Restaurants and got the error: `The plural name "restaurants" should be unique` on server restart. Files of the Collection Type seem to be created properly.

### Steps to reproduce the behavior

1. Create new project with: `npx create-strapi-app@beta beta --quickstart`
2. Create a Collection Type called Restaurants.
3. Add field called 'name'.
4. Save Collection Type.
5. See error on server restart

I also tried with the name "Items"

### Expected behavior

I expected the Collection Type to be created and the server to be restarted properly.

### Screenshots

Not necessary.

### Code snippets

Not necessary.

### System

- Node.js version: v14.17.6
- NPM version: v6.14.15.
- Strapi version: v4 beta
- Database: Sqlite
- Operating system: Debian Linux 4.19.0-17-amd64

### Additional context

Error log is:

```
[2021-09-29 17:29:26.818] info: File created: /home/bruno/Escritorio/TBDEL/beta/src/api/restaurants/routes/restaurants.js
[2021-09-29 17:29:26.827] info: File created: /home/bruno/Escritorio/TBDEL/beta/src/api/restaurants/controllers/restaurants.js
[2021-09-29 17:29:26.834] info: File created: /home/bruno/Escritorio/TBDEL/beta/src/api/restaurants/content-types/restaurants/schema.json
[2021-09-29 17:29:26.836] info: File created: /home/bruno/Escritorio/TBDEL/beta/src/api/restaurants/services/restaurants.js
[2021-09-29 17:29:27.835] http: POST /content-type-builder/content-types (1588 ms) 201
[2021-09-29 17:29:27.837] info: The server is restarting

[2021-09-29 17:29:29.087] debug: ⛔️ Server wasn't able to start properly.
[2021-09-29 17:29:29.090] error: The plural name "restaurants" should be unique
Error: The plural name "restaurants" should be unique
    at /home/bruno/Escritorio/TBDEL/beta/node_modules/@strapi/strapi/lib/core/loaders/apis.js:57:15
    at Array.forEach (<anonymous>)
    at validateContentTypesUnicity (/home/bruno/Escritorio/TBDEL/beta/node_modules/@strapi/strapi/lib/core/loaders/apis.js:45:18)
    at Object.module.exports [as loadAPIs] (/home/bruno/Escritorio/TBDEL/beta/node_modules/@strapi/strapi/lib/core/loaders/apis.js:34:3)
    at async Strapi.loadAPIs (/home/bruno/Escritorio/TBDEL/beta/node_modules/@strapi/strapi/lib/Strapi.js:275:5)
    at async Promise.all (index 3)
    at async Strapi.load (/home/bruno/Escritorio/TBDEL/beta/node_modules/@strapi/strapi/lib/Strapi.js:299:5)
    at async Strapi.start (/home/bruno/Escritorio/TBDEL/beta/node_modules/@strapi/strapi/lib/Strapi.js:141:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beta@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beta@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruno/.npm/_logs/2021-09-29T20_29_29_108Z-debug.log
```

**Comment by MattieBelt** [comment]
Hello, please update your message to the follow issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

**Comment by codesxt** [comment]
@MattieBelt Done.

**Comment by alexandrebodin** [comment]
Fix in mentionned PR. will be released in next beta
