### ISSUE TITLE
Strapi 4 beta install not working on windows

### ISSUE THREAD

**Issue by leonvanderstel** [strapi/strapi#11168]
System
- Strapi Version 4 beta:
- Operating System Windows:
- Node Version 14.15.3:
- NPM Version 6.14.9:

Hello,

When I run the strapi 4 beta command

```
npx create-strapi-app@beta beta --quickstart
```

I get a module not found error while it is running strapi build

```
ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-content-type-builder/strapi-admin.js' in 'C:\Users\leonv\coding\tmp\beta\.cache\admin\src'
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\Compilation.js:1765:28
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (C:\Users\leonv\coding\tmp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\Users\leonv\coding\tmp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at C:\Users\leonv\coding\tmp\beta\node_modules\neo-async\async.js:6883:13
    at C:\Users\leonv\coding\tmp\beta\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (C:\Users\leonv\coding\tmp\beta\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\leonv\coding\tmp\beta\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\leonv\coding\tmp\beta\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\leonv\coding\tmp\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
```

Has anyone experienced this?

I did some digging on the imports and compared it with strapi v3 which works on the same setup

file: .cache\admin\src\plugins.js

strapi v3
```
module.exports = {
  'content-type-builder': require('../../plugins/strapi-plugin-content-type-builder/admin/src').default,
   .....
}
```

strapi v4 beta

```
import contentTypeBuilder from '..\..\..\node_modules\@strapi\plugin-content-type-builder/strapi-admin.js';
```

Isn't this a problem on the slashes, like windows versus unix thing?

**Comment by leonvanderstel** [comment]
duplicate [https://github.com/strapi/strapi/issues/11137](11137)
