### ISSUE TITLE
MySQL relations attempt to store json in an INT column

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1118]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: 10.2.14-MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**
Based on this error:

```
error update `body` set `id` = 1, `system` = {"id":1,"systemName":"test","edsmID":null,"edsmID64":null,"edsmCoordX":null,"edsmCoordY":null,"edsmCoordZ":null,"edsmCoordLocked":null,"created_at":"2018-05-04T10:58:59.000Z","updated_at":"2018-05-04T10:58:59.000Z"}, `updated_at` = '2018-05-04 03:59:13.076' where `id` = 1 - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: '[object Object]' for column 'system' at row 1
```
Strapi is trying to put:
```
{"id":1,"systemName":"test","edsmID":null,"edsmID64":null,"edsmCoordX":null,"edsmCoordY":null,"edsmCoordZ":null,"edsmCoordLocked":null,"created_at":"2018-05-04T10:58:59.000Z","updated_at":"2018-05-04T10:58:59.000Z"}
```
into the `system` column, whereas strapi created this column with an INT (likely to use the ID of the foreign table)

**Steps to reproduce the problem**
Create 2 content types, in my example `system` and `body`
System can have many bodies, body can only have one system.

Create a new entry in the `system`, and attempt to create a new body that references said system.

**What is the expected behavior?**
Strapi should create relations with an INT column, and properly setup foreign keys, and reference the foreign data via that key.

**Suggested solutions**
N/A

- [x] I'm sure that this issue hasn't already been referenced

**Comment by derrickmehaffy** [comment]
For context here is my System/Body Content:

![image](https://user-images.githubusercontent.com/8593673/39625212-56261016-4f51-11e8-8974-8cc02486e8d6.png)

![image](https://user-images.githubusercontent.com/8593673/39625224-6239dbda-4f51-11e8-8299-ee83efefc8e0.png)

**Comment by lauriejim** [comment]
You are using the content-manager ?

**Comment by piere129** [comment]
I just got the exact same error as @derrickmehaffy . For me at least, it is using the content manager. This is the api call: 
`[2018-05-07T12:32:38.675Z] debug POST /content-manager/explorer/term/?source=content-manager (37 ms)
`
in my example, I have a content-type 'term' that adds a 'project' content-type. I'm guessing it tries to add a json object in the 'term' schema, to the project column, which is an integer column

**Comment by lauriejim** [comment]
Can you try with the last version of Strapi, I patched something link you explain yesterday.
Can you tell me if it's ok or your issue still happening.

**Comment by derrickmehaffy** [comment]
@lauriejim sure give me a bit and I will build out a new project to test.

**Comment by derrickmehaffy** [comment]
Just for clarification on my testing environment:

```
dmehaffy@capi1:~$ node --version && npm --version && strapi version && mysql --version && uname -a
v9.11.1
5.6.0
3.0.0-alpha.12.1.3
mysql  Ver 15.1 Distrib 10.2.14-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Linux capi1 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

On my brand new test project I do still get the following error on the initial start:

```
dmehaffy@capi1:~/test1$ strapi start
(node:4026) UnhandledPromiseRejectionWarning: Error: A model cannot be destroyed without a "where" clause or an idAttribute.
    at Sync.<anonymous> (/home/ad.derrickmehaffy.com/dmehaffy/test1/node_modules/bookshelf/lib/sync.js:219:13)
From previous event:
    at Child.<anonymous> (/home/ad.derrickmehaffy.com/dmehaffy/test1/node_modules/bookshelf/lib/model.js:1236:19)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)
From previous event:
    at Child.<anonymous> (/home/ad.derrickmehaffy.com/dmehaffy/test1/node_modules/bookshelf/lib/model.js:1235:8)
From previous event:
    at Function.removePermission (/home/ad.derrickmehaffy.com/dmehaffy/test1/plugins/users-permissions/config/queries/bookshelf.js:138:8)
    at Promise.all.Promise.all.toRemove.map.action (/home/ad.derrickmehaffy.com/dmehaffy/test1/plugins/users-permissions/services/UsersPermissions.js:279:92)
    at Array.map (<anonymous>)
    at Object.updatePermissions (/home/ad.derrickmehaffy.com/dmehaffy/test1/plugins/users-permissions/services/UsersPermissions.js:279:30)
    at <anonymous>
(node:4026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-05-08T08:46:54.931Z] info Server started in /home/ad.derrickmehaffy.com/dmehaffy/test1
[2018-05-08T08:46:54.932Z] info Your server is running at http://localhost:1337
[2018-05-08T08:46:54.932Z] debug Time: Tue May 08 2018 01:46:54 GMT-0700 (MST)
[2018-05-08T08:46:54.933Z] debug Launched in: 3758 ms
[2018-05-08T08:46:54.933Z] debug Environment: development
[2018-05-08T08:46:54.933Z] debug Process PID: 4026
[2018-05-08T08:46:54.933Z] debug Version: 3.0.0-alpha.12.1.3 (node v9.11.1)
[2018-05-08T08:46:54.933Z] info To shut down your server, press <CTRL> + C at any time
```

However it does seem this issue should be resolved, I'm going to do some more in depth testing @lauriejim  but nice job on the quick fix :)

```
[
    {
        "id": 1,
        "systemName": "SOL",
        "edsmID": 1,
        "edsmID64": 12345,
        "created_at": "2018-05-08T08:51:01.000Z",
        "updated_at": "2018-05-08T08:51:01.000Z",
        "bodies": [
            {
                "id": 1,
                "system": 1,
                "bodyName": "testbody",
                "edsmID": 2,
                "edsmID64": 2345,
                "created_at": "2018-05-08T08:51:14.000Z",
                "updated_at": "2018-05-08T08:51:14.000Z"
            }
        ]
    }
]
```
