### ISSUE TITLE
Error on strapi application with new DB

### ISSUE THREAD

**Issue by rahulrkr08** [strapi/strapi#11278]
## Bug report
I am getting the below error when I am starting my existing Strapi application with the new DB. Can anyone help?
```
[2021-10-17T15:32:36.369Z] error MongoError: arguments to $lookup must be strings, let: { localId: "$_id", localAlias: "$users" } is type object
    at MessageStream.messageHandler (/srv/app/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:467:12)
    at processIncomingData (/srv/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/srv/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```
### Steps to reproduce the behavior

1. Create a strap application and create some content types
2. Reconfigure the application with new DB
3. Create an entry for existing content type
4. Trying to open/delete entry

### Screenshots

![Screenshot 2021-10-17 at 9 12 55 PM](https://user-images.githubusercontent.com/2932484/137634650-0c135d04-df63-47da-9f71-59598913a72c.png)

### System

- Node.js version: v13.10.1
- NPM version: 7.19.0
- Strapi version: 3.6.8
- Database: MongoDB
- Operating system: Mac

**Comment by derrickmehaffy** [comment]
```
Node.js version: v13.10.1
NPM version: 7.19.0
```

We do not support Node 13 only 12 and 14
We do not support NPM v7 only NPM v6

Please set with the recommended versions, also can you please give the version of your MongoDB database

**Comment by rahulrkr08** [comment]
Thanks, @derrickmehaffy, found the issue I was using the MongoDB 3.4 version instead of 3.6.
