### ISSUE TITLE
MySQL Database Values Set to NULL on concurrent Strapi connections causing crashes

### ISSUE THREAD

**Issue by devesh-kumar-unacademy** [strapi/strapi#11448]
### Describe the bug

Hi, we have been using Strapi for our staging and production CMS. On staging, while launching Strapi from multiple servers connected to a common database, their are crashes caused by values of certain columns in tables randomly being set to NULL, causing failures in other concurrently running Strapi instances. The behaviour is very random and occurs in any of the numerous tables associated with Strapi.

This is probably happening due to locks implemented on rows by one Strapi instance, and another Strapi instance trying to access the same resource but failing to get it.

The failures are internal (As in, the failures are of the type `cannot read property _ of _` inside Strapi source code).

### Steps to reproduce the behaviour

1. Install Strapi on multiple server instances.
2. Have one common MySQL database that serves content to all the Strapi instances.
3. Start the server instances together
4. 8 times out of 10, the instances should crash and on inspection, you will notice that some of the database values are set to NULL.

### Expected behaviour

If the access to a row in a table is not received, Strapi should wait for the resource to be freed.

### Screenshots

<img width="1450" alt="Screenshot 2021-11-03 at 12 36 02 PM" src="https://user-images.githubusercontent.com/87963338/140020621-177266a3-eef0-40cb-80e5-08fa5532196d.png">

### System

- Node.js version: >=10.0.0
- NPM version: >=6.0.0
- Strapi version: 3.6.6
- Database: MySQL
- Operating system: Linux

### Additional context

Related Issues and PRs:

#10907 
#3927

**Comment by devesh-kumar-unacademy** [comment]
Hey @derrickmehaffy Thanks for checking the bug, surprising it could not be reproduced. However, we have been consistently facing this issue for over a month now.

A log if that can help:

```
$ strapi start
[2021-11-02T11:55:45.872Z] error bootstrap function in admin failed
[2021-11-02T11:55:45.873Z] error TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at sortPermissionProperties (/web-scms/node_modules/strapi-admin/services/role.js:51:17)
    at Array.map (<anonymous>)
    at arePermissionsEqual (/web-scms/node_modules/strapi-admin/services/role.js:60:6)
    at f (/web-scms/node_modules/lodash/lodash.min.js:10:238)
    at Hr (/web-scms/node_modules/lodash/lodash.min.js:34:209)
    at /web-scms/node_modules/lodash/lodash.min.js:117:39
    at n (/web-scms/node_modules/lodash/lodash.min.js:9:117)
    at /web-scms/node_modules/lodash/lodash.min.js:73:58
    at l (/web-scms/node_modules/lodash/lodash.min.js:58:213)
    at assignPermissions (/web-scms/node_modules/strapi-admin/services/role.js:355:28)
    at async Object.resetSuperAdminPermissions (/web-scms/node_modules/strapi-admin/services/role.js:430:3)
    at async module.exports (/web-scms/node_modules/strapi-admin/config/functions/bootstrap.js:51:3)
    at async module.exports (/web-scms/node_modules/strapi-admin/ee/config/functions/bootstrap.js:18:3)
    at async Strapi.load (/web-scms/node_modules/strapi/lib/Strapi.js:379:5)
    at async Strapi.start (/web-scms/node_modules/strapi/lib/Strapi.js:196:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by derrickmehaffy** [comment]
Can you give me some info on where you are hosting and what the specs are of everything?

**Comment by devesh-kumar-unacademy** [comment]
Sure @derrickmehaffy

![image](https://user-images.githubusercontent.com/87963338/141062298-3f799ccf-52bc-41a8-8ad3-381e716ee0ed.png)

The service is hosted on the node with minimum 0.3 CPU and Memory 250MB. There is no upper limit.

MySQL Environment:
CPU: 2
Memory: 8GB

**Comment by derrickmehaffy** [comment]
It appears you have a user somewhere that doesn't have a role.

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
