### ISSUE TITLE
Unable to boot after installing GraphQL module

### ISSUE THREAD

**Issue by jonlambert** [strapi/strapi#11625]
### Describe the bug

I'm a newcomer to Strapi. I ran the command listed on the website and attempted to install the GraphQL plugin. Starting Strapi now fails with the error:

  
  ```
  > my-project@0.1.0 start
> strapi start

[2021-11-18T13:46:02.856Z] debug ⛔️ Server wasn't able to start properly.
[2021-11-18T13:46:02.857Z] error Error: Cannot use GraphQLObjectType "Query" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/node_modules/graphql/jsutils/instanceOf.js:29:13)
    at isObjectType (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/node_modules/graphql/type/definition.js:122:34)
    at printType (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:130:36)
    at /Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:59:12
    at Array.map (<anonymous>)
    at printFilteredSchema (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:58:13)
    at Object.printSchema (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/node_modules/graphql/utilities/printSchema.js:40:10)
    at writeGenerateSchema (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/services/schema-generator.js:138:31)
    at Object.generateSchema (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/services/schema-generator.js:109:5)
    at Object.initialize (/Users/jon/Code/strapi-test/my-project/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:76:74)
    at /Users/jon/Code/strapi-test/my-project/node_modules/strapi/lib/hooks/index.js:37:28
  ```

### Steps to reproduce the behavior

1. Run the init command `npx create-strapi-app my-project --quickstart`
2. Create account
3. Navigate to Marketplace
4. Download and install GraphQL module
5. See Strapi fail to restart. When starting, see error emitted above.

### Expected behavior

Strapi to startup with GraphQL installed.

### Screenshots

n/a

### Code snippets

n/a

### System

- Node.js version: v16.13.0
- NPM version: 7.11.2
- Strapi version: 3.6.8
- Database: sqlite
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
> Node.js version: v16.13.0
> NPM version: 7.11.2

Strapi v3 doesn't support Node 16 or NPM v7+

Downgrade to Node 14 and NPM 6
