### ISSUE TITLE
[v4] Router Factory - Setting Auth true throws an invalid route config

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11644]
### Describe the bug

If you set a Route config - `auth: true` it will throw a yup error for an invalid config. Source of issue is here:

https://github.com/strapi/strapi/blob/0c0789354d34c685b94474911b79c1b679155dfa/packages/core/strapi/lib/services/server/routing.js#L45-L58

As it's only validating `auth: false` or if `auth` is an object

Error:

```
[2021-11-19 10:49:37.794] error: Invalid route config
Error: Invalid route config
    at validateRouteConfig (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/routing.js:79:11)
    at createRoute (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/routing.js:89:5)
    at /mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/routing.js:105:9
    at Array.forEach (<anonymous>)
    at Object.addRoutes (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/routing.js:103:21)
    at Object.routes (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/api.js:25:20)
    at Object.routes (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/index.js:72:27)
    at /mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/register-routes.js:103:28
    at /mnt/Storage/Development/testBeta14/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/mnt/Storage/Development/testBeta14/node_modules/lodash/lodash.js:3032:24)
    at /mnt/Storage/Development/testBeta14/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/mnt/Storage/Development/testBeta14/node_modules/lodash/lodash.js:9410:14)
    at registerAPIRoutes (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/register-routes.js:94:7)
    at module.exports (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/register-routes.js:25:3)
    at Object.initRouting (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/services/server/index.js:90:13)
    at Strapi.bootstrap (/mnt/Storage/Development/testBeta14/node_modules/@strapi/strapi/lib/Strapi.js:399:23)
error Command failed with exit code 1.
```

### Steps to reproduce the behavior

1. Create a new content-type
2. Try testing `auth: false` on it's config
3. Revert test by setting `auth: true`

### Expected behavior

Should still be valid since the default is `auth: true` 

### Screenshots

N/A

### Code snippets

Router code:

```js
const { createCoreRouter } = require('@strapi/strapi').factories;

module.exports = createCoreRouter('api::blog-post.blog-post', {
  config: {
    find: {
      auth: true
    }
  }
});
```

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.14
- Database: SQLite
- Operating system:  Linux Mint 20.2

### Additional context

N/A

**Comment by alexandrebodin** [comment]
Auth can only be disable it is enabled by default and should not be set to true.
True is not the default value but it is. An object with scope (something)
