### ISSUE TITLE
[V4] ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/themes'

### ISSUE THREAD

**Issue by spathon** [strapi/strapi#11640]
### Describe the bug

Running `npx create-strapi-app@beta beta --quickstart` throws an error during webpack build:
`ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/themes' in '/Users/spathon/Sites/tmp/beta/.cache/admin/src'`

This is a new submisson from https://github.com/strapi/strapi/issues/11599

I have run `rm -rf node_modules` & `npm cache clean --force`
I have tried downgrading npm from 8.1.4 to 7.24.2

Installing `@strapi/design-system` got me one step further when running `npm run build` but get the following error:
`ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/EmptyStateDocument' in '/Users/spathon/Sites/tmp/betaV4/node_modules/@strapi/plugin-upload/admin/src/components/EmptyAssets'`
Looking inside node_modules and `@strapi/icons` there is no EmptyStateDocument.

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@beta beta --quickstart`
2. See error

### Expected behavior

Install and run strapi

### Code snippets

```
npx create-strapi-app@beta beta --quickstart
Creating a quickstart project.
Creating a new Strapi application at /Users/spathon/Sites/tmp/beta.
Creating files.
Dependencies installed successfully.

Your application was created at /Users/spathon/Sites/tmp/beta.

Available commands in your project:

  npm run develop
  Start Strapi in watch mode.

  npm run start
  Start Strapi without watch mode.

  npm run build
  Build Strapi admin panel.

  npm run strapi
  Display all available commands.

You can start by doing:

  cd /Users/spathon/Sites/tmp/beta
  npm run develop


> beta@0.1.0 build
> strapi build "--no-optimization"

Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (10%) 0/1 entries 105/115 dependencies 35/85 modules 48 active
 url-loader › .cache/admin/src/favicon.ico

ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/themes' in '/Users/spathon/Sites/tmp/beta/.cache/admin/src'
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/Compilation.js:1765:28
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/Users/spathon/Sites/tmp/beta/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/spathon/Sites/tmp/beta/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /Users/spathon/Sites/tmp/beta/node_modules/neo-async/async.js:6883:13
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/Users/spathon/Sites/tmp/beta/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/spathon/Sites/tmp/beta/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/spathon/Sites/tmp/beta/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/spathon/Sites/tmp/beta/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/themes' in '/Users/spathon/Sites/tmp/beta/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/spathon/Sites/tmp/beta/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/spathon/Sites/tmp/beta/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/spathon/Sites/tmp/beta/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/spathon/Sites/tmp/beta/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/spathon/Sites/tmp/beta/node_modules
        /Users/spathon/Sites/tmp/beta/node_modules/@strapi/design-system doesn't exist
      /Users/spathon/Sites/tmp/node_modules doesn't exist or is not a directory
      /Users/spathon/Sites/node_modules doesn't exist or is not a directory
      /Users/spathon/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/themes' in '/Users/spathon/Sites/tmp/beta/.cache/admin/src'
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/Compilation.js:1765:28
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/Users/spathon/Sites/tmp/beta/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/spathon/Sites/tmp/beta/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /Users/spathon/Sites/tmp/beta/node_modules/neo-async/async.js:6883:13
    at /Users/spathon/Sites/tmp/beta/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/Users/spathon/Sites/tmp/beta/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/spathon/Sites/tmp/beta/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/spathon/Sites/tmp/beta/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/spathon/Sites/tmp/beta/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/themes' in '/Users/spathon/Sites/tmp/beta/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/spathon/Sites/tmp/beta/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/spathon/Sites/tmp/beta/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/spathon/Sites/tmp/beta/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/spathon/Sites/tmp/beta/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/spathon/Sites/tmp/beta/node_modules
        /Users/spathon/Sites/tmp/beta/node_modules/@strapi/design-system doesn't exist
      /Users/spathon/Sites/tmp/node_modules doesn't exist or is not a directory
      /Users/spathon/Sites/node_modules doesn't exist or is not a directory
      /Users/spathon/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

### System

- Node.js version:  16.13.0
- NPM version: 8.1.4 & 7.24.2
- Strapi version: 4.0.0-beta.13
- Database: Mysql 5.7.28
- Operating system: MacBook Pro (16-inch, 2019) MacOS Big Sur

**Comment by derrickmehaffy** [comment]
During the beta please use yarn.

**Comment by spathon** [comment]
Thank you @derrickmehaffy that worked :)

**Comment by mirkonasato** [comment]
This is still happening with npm 8, even though Strapi 4 is no longer in beta.  Is using Yarn mandatory?

**Comment by Jimmeyy** [comment]
Hi, I have the same problem in current official version (4.0.0)

**Comment by pierrenel** [comment]
Same here - freshly deployed Digital Ocean box + node 16 via nvm.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/11729

Locking this thread
