### ISSUE TITLE
error TypeError: Cannot read property 'prototype' of undefined when trying to log into strapi backend

### ISSUE THREAD

**Issue by jonlo** [strapi/strapi#11676]
### Describe the bug

I can't login into the strapi backend.

when i try to login ( localhost:1337/auth/local ) im getting a server 500 error:

```javascript
[2021-11-25T12:22:32.272Z] error TypeError: Cannot read property 'prototype' of undefined
    at module.exports (G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\promise-redis\index.js:17:31)
    at Object.<anonymous> (G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\koa2-ratelimit\src\RedisStore.js:22:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\koa2-ratelimit\src\index.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.get RateLimit [as RateLimit] (G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\strapi-plugin-users-permissions\config\policies\rateLimit.js:5:12)
    at module.exports (G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\strapi-plugin-users-permissions\config\policies\rateLimit.js:21:24)
    at dispatch (G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\koa-compose\index.js:42:32)
    at module.exports (G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\strapi-plugin-users-permissions\config\policies\permissions.js:88:9)
    at async G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\strapi-utils\lib\policy.js:68:5
    at async G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\strapi\lib\middlewares\parser\index.js:48:23
    at async G:\Development\Repositorios\Tecnalia\Configuradores2d3d\mygreen\backend\node_modules\strapi\lib\middlewares\xss\index.js:26:9
[2021-11-25T12:22:32.276Z] debug POST /auth/local (647 ms) 500
```

It started failing in a working app which was on docker, so it gets built every time i push a commit to my repo.

I had an older strapi app which was working , until i removed the node_modules and cache folder. So i guess there is a problem with some library.

### Steps to reproduce the behavior

Download a new strapi api and try to login into the backend via postman or similar.

### System

- Node.js version: '14.15.3'
- NPM version: '6.14.9'
- Strapi version: 3.6.8
- Database: postgresql and sqlite
- Operating system: windows & linux (docker)

**Comment by renanbym** [comment]
+1

**Comment by guilhermevini** [comment]
+1

**Comment by abdurrahmantarek** [comment]
+1

**Comment by k-3st3ban** [comment]
+1

**Comment by kasonde** [comment]
Pulling the source code down and running it outside docker locally; does this still occur?

**Comment by jonlo** [comment]
Yes, i tried in a project outside docker which was working, after deleting the cache and node_modules, it started failing

**Comment by jonlo** [comment]
> Pulling the source code down and running it outside docker locally; does this still occur?

It happens in a new strapi project too, just folowing the start guide

**Comment by hdeadman** [comment]
The redis-promise npm package depends on "redis" with version "*". The "redis" npm module released 4.0.0 yesterday and maybe it is picking that up (whereas it didn't pick up the release candidates that were out prior to that). That's just a guess but redis-promise module looks sort of dead so probably can't expect fix from them.

**Comment by Distil62** [comment]
I have the same issue. Do you have any workaround ?

**Comment by hdeadman** [comment]
I think you should be able to use "resolutions" to force the version of redis (or whatever dependency is breaking it) that gets used. https://yarnpkg.com/configuration/manifest/#resolutions 
If using npm instead of yarn there is a module that does the same thing.

**Comment by Distil62** [comment]
Thank you @hdeadman !
Add 
```json
  "resolutions": {
    "redis": "3.1.2"
  },
```
in my package.json solve the issue.

**Comment by jonlo** [comment]
Thank you all! @hdeadman @Distil62

**Comment by renanbym** [comment]
Tks @hdeadman

**Comment by MutlaqAldhbuiub** [comment]
> Thank you @hdeadman ! Add
> 
> ```json
>   "resolutions": {
>     "redis": "3.1.2"
>   },
> ```
> 
> in my package.json solve the issue.

Thank you! works for me

**Comment by alexandrebodin** [comment]
Trying to get the 1st lvl dependency fixed https://github.com/ysocorp/koa2-ratelimit/issues/37

**Comment by petersg83** [comment]
[koa2-ratelimit](https://github.com/ysocorp/koa2-ratelimit) was fixed ! Thanks @julienwilmet

If you still have the issue after reinstalling your `node_modules`, delete your `yarn.lock` or your `package-lock.json` and install them again :)

**Comment by makkahwi** [comment]
May I ask what does 

"resolutions": {
    "redis": "3.1.2"
  },

exactly do?

**Comment by IvarHagen** [comment]
For NPM I used this package for the resolutions to work - https://www.npmjs.com/package/npm-force-resolutions
Now I can use the /auth/local endpoint again. :)

**Comment by jonlo** [comment]
> May I ask what does
> 
> "resolutions": { "redis": "3.1.2" },
> 
> exactly do?

It forces the redis dependency to stay in that version even if the package which has that dependency tries to update it.

**Comment by prernagp** [comment]
@hdeadman @Distil62 I am still facing the issue. Also, when I tried using the above solution I am getting this below error:-

└─┬ strapi-plugin-users-permissions@3.6.8
  └─┬ koa2-ratelimit@0.9.1
    └── redis@3.1.2 invalid

npm ERR! code ELSPROBLEMS
npm ERR! invalid: redis@3.1.2

**Comment by hdeadman** [comment]
@prernagp Did you delete your package-lock.json or yarn-lock.json? Are you using yarn or npm to install? At this point, from what I understand, you shouldn't need to use the `resolutions` anymore, as long as you delete package-lock.json or yarn-lock.json and regenerate them, because koa2-ratelimit has been updated to not depend on the promise-redis module anymore.

**Comment by prernagp** [comment]
@hdeadman Yes, it worked. I deleted the package-lock.json file and regenerated it. Thanks so much.

**Comment by TheSilentDev** [comment]
Tried all of the above solutions, but the issue is still persisting. any ideas?

**Comment by prernagp** [comment]
> 
No need to do any changes. Just delete your lock file and generate it again.
