### ISSUE TITLE
[V4] Handler not found

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#11674]
### Describe the bug

I upgraded form beta.12 to beta.15 and got the following error
```bash
strapi_1    | [2021-11-24 17:24:24.776] error: Error creating endpoint GET /accessories: Handler not found "accessory.find"
strapi_1    | Error: Error creating endpoint GET /accessories: Handler not found "accessory.find"
strapi_1    |     at getAction (/srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:131:11)
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:71:22
strapi_1    |     at createRoute (/srv/app/node_modules/@strapi/strapi/lib/services/server/routing.js:94:5)
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/services/server/routing.js:105:9
strapi_1    |     at Array.forEach (<anonymous>)
strapi_1    |     at Object.addRoutes (/srv/app/node_modules/@strapi/strapi/lib/services/server/routing.js:103:21)
strapi_1    |     at Object.routes (/srv/app/node_modules/@strapi/strapi/lib/services/server/api.js:25:20)
strapi_1    |     at Object.routes (/srv/app/node_modules/@strapi/strapi/lib/services/server/index.js:72:27)
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:103:28
strapi_1    |     at /srv/app/node_modules/lodash/lodash.js:4967:15
strapi_1    |     at baseForOwn (/srv/app/node_modules/lodash/lodash.js:3032:24)
strapi_1    |     at /srv/app/node_modules/lodash/lodash.js:4936:18
strapi_1    |     at Function.forEach (/srv/app/node_modules/lodash/lodash.js:9410:14)
strapi_1    |     at registerAPIRoutes (/srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:94:7)
strapi_1    |     at module.exports (/srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:25:3)
strapi_1    |     at Object.initRouting (/srv/app/node_modules/@strapi/strapi/lib/services/server/index.js:90:13)
strapi_1    | error Command failed with exit code 1.
strapi_1    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
/api/accessory/routes/accessory.js
```js
module.exports = {
  routes: [
    {
      method: 'GET',
      path: '/accessories',
      handler: 'accessory.find',
      config: {
        policies: [],
      },
    },
    {
      method: 'GET',
      path: '/accessories/:id',
      handler: 'accessory.findOne',
      config: {
        policies: [],
      },
    },
    {
      method: 'POST',
      path: '/accessories',
      handler: 'accessory.create',
      config: {
        policies: [],
      },
    },
    {
      method: 'PUT',
      path: '/accessories/:id',
      handler: 'accessory.update',
      config: {
        policies: [],
      },
    },
    {
      method: 'DELETE',
      path: '/accessories/:id',
      handler: 'accessory.delete',
      config: {
        policies: [],
      },
    },
  ],
}
```

### Steps to reproduce the behavior

1. Upgrade to beta.15

### Expected behavior

Should just work. :D

### System

- Node.js version: v14.15.3
- NPM version: 7.17.0
- Strapi version: 7.17.0
- Database: postgres
- Operating system: fedora

**Comment by gu-stav** [comment]
@tw1t611 In beta.14 the format of routes has changed: https://github.com/strapi/strapi/releases/tag/v4.0.0-beta.14 Between beta releases there is no migration path, so have to do this yourself.

**Comment by tw1t611** [comment]
Ty for you fast reply. Will I also need to migrate the controllers, or is the empty file still working?
'use strict';

```js
/**
 * A set of functions called "actions" for `accessory`
 */

module.exports = {
  // exampleAction: async (ctx, next) => {
  //   try {
  //     ctx.body = 'ok';
  //   } catch (err) {
  //     ctx.body = err;
  //   }
  // }
};
```

**Comment by tw1t611** [comment]
For everyone else coming across this issue. You need to change routes, controllers and services file.
However, you can use a shorter (default) version compared to the the docs.

controllers/accessory.js
```js
"use strict";

/**
 *  accessory controller
 */

const { createCoreController } = require("@strapi/strapi").factories;

module.exports = createCoreController("api::accessory.accessory");
```


routes/accessory.js
```js
"use strict";

/**
 * accessory router.
 */

const { createCoreRouter } = require("@strapi/strapi").factories;

module.exports = createCoreRouter("api::accessory.accessory");
```


services/accessory.js
```js
"use strict";

/**
 * accessory service.
 */

const { createCoreService } = require("@strapi/strapi").factories;

module.exports = createCoreService("api::accessory.accessory");
```
