### ISSUE TITLE
[v4] When trying to use "?populate=user.username" on REST API GET, Error: Invalid populate field. Expected a relation, got string

### ISSUE THREAD

**Issue by VansonLeung** [strapi/strapi#11740]
### Describe the bug

[v4] 
1. When trying to use "?populate=user.username" on REST API GET, Show error:
Expected result: "user.username" field is visible
Error: Invalid populate field. Expected a relation, got string

![image](https://user-images.githubusercontent.com/1129695/144196410-35bca7d0-f495-45ae-854a-7e37191bd25b.png)

![image](https://user-images.githubusercontent.com/1129695/144196076-9b0b8e14-0c9c-4a20-aba0-2120e2951bbc.png)

```
[2021-12-01 16:03:12.562] error: Invalid populate field. Expected a relation, got string
Error: Invalid populate field. Expected a relation, got string
    at Object.processPopulate (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/database/lib/query/helpers/populate.js:83:13)
    at Object.processState (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/database/lib/query/query-builder.js:235:32)
    at Object.getKnexQuery (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/database/lib/query/query-builder.js:271:12)
    at Object.execute (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/database/lib/query/query-builder.js:352:25)
    at Object.applyPopulate (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/database/lib/query/helpers/populate.js:207:12)
    at Object.execute (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/database/lib/query/query-builder.js:357:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.findMany (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/database/lib/entity-manager.js:132:22)
    at async Object.findMany (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
    at async Object.find (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/strapi/lib/core-api/service/collection-type.js:34:23)
    at async Object.find (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/strapi/lib/core-api/controller/collection-type.js:24:39)
    at async returnBodyMiddleware (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/van/Documents/projects/fs/wwj_ev_cms/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)

```

2. When trying to use "?populate=user" or "?populate=*" on REST API GET, 
Expected result: "user" field is visible
Actual result: no "user" field

![image](https://user-images.githubusercontent.com/1129695/144196280-c3357685-f603-4c46-93b0-16a77d7aeffc.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/1129695/144195885-2b764da0-0bf2-4ec0-896c-e31273e6b475.png)

According to the latest Strapi documentation, no error should be seen, and "user" field should be populated

### System

- Node.js version: v12
- NPM version:
- Strapi version: v4
- Database: MySQL (MAMP)
- Operating system: OS X

**Comment by kasonde** [comment]
@VansonLeung, could you share what your collection type looks like and the relations involved?

**Comment by Strapi-User** [comment]
@VansonLeung - check the permissions to make sure your API user has been given read access to the user collection referenced, otherwise I think Strapi will strip them out from the response object

**Comment by eikaramba** [comment]
yes that was the case for me however that opens up a lot of security issues. you don't want every user to be able to access other users information. how to prevent that?

**Comment by Strapi-User** [comment]
Agree, I've not found a good solution for this yet. It appears that you either have to give the API caller full access to list all users or they won't be able to see data for any user relation. What I would like to see is the ability to display only certain fields, like the name, of the linked user without exposing the full set of user objects. [This issue](https://github.com/strapi/strapi/issues/2161) has a bigger discussion on field-level permissions.

**Comment by syahnur197** [comment]
I got the same issue as well, I have given unauthenticated role the permission to "find", and "fineOne" the related entities.

![Screenshot from 2021-12-02 22-59-54](https://user-images.githubusercontent.com/18722385/144447022-44f67c0e-8ab2-41ce-945f-596e72c37843.png)

This is the error message

![Screenshot from 2021-12-02 23-00-39](https://user-images.githubusercontent.com/18722385/144447130-16849934-a52c-42de-a8fd-a02caafbafd6.png)

**Comment by derrickmehaffy** [comment]
see: https://github.com/strapi/strapi/issues/11787
