### ISSUE TITLE
V4 ecommerce starter fails on install

### ISSUE THREAD

**Issue by myrddral** [strapi/strapi#11771]
### Describe the bug

When I run the command
**npx create-strapi-starter my-project next-ecommerce** or **yarn create strapi-starter my-project next-ecommerce**

I get the following error:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (C:\Users\pc\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\fetch-npm-starter.js:19:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getStarterInfo (C:\Users\pc\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\build-starter.js:109:26)
    at async buildStarter (C:\Users\pc\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\build-starter.js:133:7)
```

On a side note, the blog starter installs and runs nicely.

### Steps to reproduce the behavior

1. try to install the ecommerce starter with npx or yarn
2. Coose "Quickstart" or "Custom"
3. See error in console

### Expected behavior

The ecommerce starter installs without errors.

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: v4
- Database: n/a
- Operating system: Windows 11

**Comment by logical-potato** [comment]
I also have this same output...

tried node v.12 to v.16, npm v6 to v8 in windows 10 and ubuntu 18 with similar results.
