### ISSUE TITLE
Cannot deploy Strapi v4 to Google App Engine with the Old Guide

### ISSUE THREAD

**Issue by Fierce-Cat** [strapi/strapi#11783]
### Describe the bug

Based on the existing guide: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html
An error occurred when deploying Strapi to App Engine in GCP:
`Error: ENOENT: no such file or directory, mkdir '/workspace/database/migrations'`

### Steps to reproduce the behavior

1. Follow the process in the tutorial to the Deploy section.
2. View the application url in the browser, after the service is successfully deployed.
3. A 500 error appears on the page, prompting "Error: Server Error."
4. GCP error report:

```
Error: ENOENT: no such file or directory, mkdir '/workspace/database/migrations'
    at Object.mkdirSync (fs.js:1009:3)
    at Object.module.exports.makeDirSync (/workspace/node_modules/fs-extra/lib/mkdirs/make-dir.js:23:13)
    at createUmzugProvider (/workspace/node_modules/@strapi/database/lib/migrations/index.js:28:7)
    at createMigrationsProvider (/workspace/node_modules/@strapi/database/lib/migrations/index.js:52:22)
    at new Database (/workspace/node_modules/@strapi/database/lib/index.js:47:23)
    at Function.Database.init (/workspace/node_modules/@strapi/database/lib/index.js:84:33)
    at Strapi.bootstrap (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:347:30)
    at Strapi.load (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:410:16)
```

### Expected behavior

There should be no errors, use the app url could access to Strapi admin page.

### Screenshots

Browser shows:
![image](https://user-images.githubusercontent.com/21760321/144616037-cf666c09-e539-4f35-a011-7801cfd4f5fa.png)

### System

- Node.js version: V14
- NPM version: >=6.0.0
- Strapi version: v4
- Database: postgres
- Operating system: GCP / App Engine

### Additional context

Since in the GAE tutorial, the database config are applicable to the V3 version, I have made additional changes to `config/database.js`:
```
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: `/cloudsql/${env('INSTANCE_CONNECTION_NAME')}`,
      database: env('DATABASE_NAME'),
      user: env('DATABASE_USERNAME'),
      password: env('DATABASE_PASSWORD'),
    },
    debug: false,
  },
});
```

**Comment by derrickmehaffy** [comment]
Can you try adding a .gitkeep to that folder please, I don't understand why GCP complains about an empty folder.

**Comment by Fierce-Cat** [comment]
> Can you try adding a .gitkeep to that folder please, I don't understand why GCP complains about an empty folder.

I created a .keep file into the folder and the problem was resolved. It seems that App Engine does not give Strapi the permission to create folders, so we need to upload empty folders together during deployment.

**Comment by derrickmehaffy** [comment]
Moving this to documentation so it can be added as a notice
