### ISSUE TITLE
Filtering on any field for Users in Users-Permissions yields a 500 error

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11789]
### Describe the bug

When running an `$eq` filter on any field from users-permissions => user model yields the following error:

```
[2021-12-03 13:10:44.546] error: Undefined attribute level operator email
Error: Undefined attribute level operator email
    at processAttributeWhere (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:82:13)
    at processWhere (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:142:45)
    at /mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:104:29
    at Array.map (<anonymous>)
    at Object.processWhere (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:104:18)
    at Object.processState (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/query-builder.js:234:29)
    at Object.getKnexQuery (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/query-builder.js:271:12)
    at Object.execute (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/query-builder.js:352:25)
    at Object.findMany (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/entity-manager.js:134:10)
    at async Object.find (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/plugin-users-permissions/server/controllers/user.js:137:19)
    at async returnBodyMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/mnt/Storage/Development/testPopDocs/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/middlewares/body.js:24:7
```

### Steps to reproduce the behavior

1. Create a user in Users-Permissions
2. Enable public find permission
3. Try to filter for `username`, `email`, or `role`

### Expected behavior

Should Filter :)

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/144667214-17a6577f-2224-4761-a58a-0be0a2426d8e.png)

![image](https://user-images.githubusercontent.com/8593673/144667254-4eebe998-41b8-4424-94a2-1a949b62bfec.png)

### Code snippets

qs structure:

```js
const qs = require('qs');
const query = qs.stringify({
  filters: {
    username: {
      $eq: 'test'
    },
  },
}, {
  encodeValuesOnly: true,
});

await request(`/api/users?${query}`);
// GET /api/users?filters[username][$eq]=test
```

### System

- Node.js version: v14.18.1
- NPM version: v6.14.15
- Strapi version: 4.0.0
- Database: SQLite
- Operating system: Linux Mint 20.2

### Additional context

N/A

**Comment by Cpaczek** [comment]
#11847 Similar bug

**Comment by kamal-choudhary** [comment]
Hi, I was facing the same error. Filtering and population on User-permissions were not working. I added the changes that were pushed in PR #11795 in my project. The filtering started working but the population of relational fields is still not working. Can someone guide me on how can I fix it?

**Comment by derrickmehaffy** [comment]
> Hi, I was facing the same error. Filtering and population on User-permissions were not working. I added the changes that were pushed in PR #11795 in my project. The filtering started working but the population of relational fields is still not working. Can someone guide me on how can I fix it?

Can you create a new bug report as this one was specifically for filtering and not population please. Thank you!

**Comment by kamal-choudhary** [comment]
@derrickmehaffy sorry, I didn't know that I should not post my question here. I will create a new bug report. Thanks!

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy sorry, I didn't know that I should not post my question here. I will create a new bug report. Thanks!

No problem :)
