### ISSUE TITLE
Cannot create controllers

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#11824]
### Describe the bug

Strapi is throwing errors on a newly created controller.

error:
```bash
strapi_1    | [2021-12-06 14:16:31.655] error: Error creating endpoint POST /forms/newsletter/create: Cannot read properties of undefined (reading 'kind')
strapi_1    | TypeError: Error creating endpoint POST /forms/newsletter/create: Cannot read properties of undefined (reading 'kind')
strapi_1    |     at Object.isSingleType (/srv/app/node_modules/@strapi/utils/lib/content-types.js:90:25)
strapi_1    |     at createController (/srv/app/node_modules/@strapi/strapi/lib/core-api/controller/index.js:36:20)
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/factories.js:11:28
strapi_1    |     at Object.get (/srv/app/node_modules/@strapi/strapi/lib/core/registries/controllers.js:37:61)
strapi_1    |     at Strapi.controller (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:103:46)
strapi_1    |     at getController (/srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:101:19)
strapi_1    |     at getAction (/srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:128:22)
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:71:22
strapi_1    |     at createRoute (/srv/app/node_modules/@strapi/strapi/lib/services/server/routing.js:94:5)
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/services/server/routing.js:105:9
strapi_1    |     at Array.forEach (<anonymous>)
strapi_1    |     at Object.addRoutes (/srv/app/node_modules/@strapi/strapi/lib/services/server/routing.js:103:21)
strapi_1    |     at Object.routes (/srv/app/node_modules/@strapi/strapi/lib/services/server/api.js:25:20)
strapi_1    |     at Object.routes (/srv/app/node_modules/@strapi/strapi/lib/services/server/index.js:72:27)
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:103:28
strapi_1    |     at /srv/app/node_modules/lodash/lodash.js:4967:15
```

### Steps to reproduce the behavior

1. `yarn strapi generate controller forms`
2. Add routes/custom-forms.js
3. Edit controllers/forms.js
4. Run Strapi
5. See error.

### Expected behavior

Controller gets executed without errors.

### Code snippets

controllers/forms.js
```js
"use strict";

const { createCoreController } = require("@strapi/strapi").factories;

module.exports = createCoreController("api::forms.forms", () => ({
  async createNewsletter(ctx) {
    try {
      ctx.body = "ok";
    } catch (err) {
      ctx.body = err;
    }
  },
}));
```

routes/custom-forms.js
```js
module.exports = {
  routes: [
    {
      method: "POST",
      path: "/forms/newsletter/create",
      handler: "forms.createNewsletter",
    },
  ],
}
```

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.0
- Database: postgres 14
- Operating system: fedora 35

**Comment by tw1t611** [comment]
If you rename `custom-forms.js` to `custom-forms.js.bak` this error is thrown.

error
```bash
Cannot read properties of undefined (reading 'forEach')
strapi_1    | TypeError: Cannot read properties of undefined (reading 'forEach')
strapi_1    |     at /srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:98:21
strapi_1    |     at /srv/app/node_modules/lodash/lodash.js:4967:15
strapi_1    |     at baseForOwn (/srv/app/node_modules/lodash/lodash.js:3032:24)
strapi_1    |     at /srv/app/node_modules/lodash/lodash.js:4936:18
strapi_1    |     at Function.forEach (/srv/app/node_modules/lodash/lodash.js:9410:14)
strapi_1    |     at registerAPIRoutes (/srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:94:7)
strapi_1    |     at module.exports (/srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:25:3)
strapi_1    |     at Object.initRouting (/srv/app/node_modules/@strapi/strapi/lib/services/server/index.js:90:13)
strapi_1    |     at Strapi.bootstrap (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:399:23)
strapi_1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
strapi_1    |     at async Strapi.load (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:410:5)
strapi_1    |     at async Strapi.start (/srv/app/node_modules/@strapi/strapi/lib/Strapi
```

It might be possible exit the loop in case there is no file found under `routes`.

**Comment by tw1t611** [comment]
The solution:

If you create a new controller through the cli and choose "new api", you don't need the factory.

controllers/forms.js
```js
"use strict";

const createNewsletter = require("./create-newsletter");

module.exports = {
  createNewsletter,

};
```
