### ISSUE TITLE
Schema seems to not be properly passed down when configuring Strapi to launch with a specific schema on PostgreSQL

### ISSUE THREAD

**Issue by nacho-carnicero** [strapi/strapi#11841]
### Describe the bug

Hi, 

I have a postgres DB that was populated with Strapi tables and columns once. I recently wanted to move all Strapi related entities from the `public` schema to a new schema called `strapi` on my DB. I have managed to do this, and I have added the needed config options in `strapi/config/database.js`:

```js
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "postgres",
        host: env("STRAPI_DATABASE_HOST", ""),
        port: env.int("STRAPI_DATABASE_PORT", 5432),
        database: env("STRAPI_DATABASE_NAME", ""),
        username: env("STRAPI_DATABASE_USERNAME", ""),
        password: env("STRAPI_DATABASE_PASSWORD", ""),
        ssl: env.bool("STRAPI_DATABASE_SSL", false),
        schema: env("STRAPI_DATABASE_SCHEMA", "public"),
      },
      options: { autoMigration: false, debug: true }, // autoMigration is set to false willingly, otherwise Strapi would always try to create new tables on every startup
    },
  },
});
```

When I try to launch Strapi I get the following error (I've pasted as well the failing query):

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'plugin_users-permissions_email', '', '', 1 ],
  __knexQueryUid: 'EmMWpvu-sgpZt7nC_ua6f',
  sql: 'select "core_store".* from "core_store" where "core_store"."key" = ? and "core_store"."environment" = ? and "core_store"."tag" = ? limit ?'
}
[2021-12-07T17:58:20.881Z] error bootstrap function in plugin "content-manager" failed
[2021-12-07T17:58:20.882Z] error error: select "core_store".* from "core_store" where "core_store"."key" = $1 and "core_store"."environment" = $2 and "core_store"."tag" = $3 limit $4 - relation "core_store" does not exist
    at Parser.parseErrorMessage (/Users/nachocarnicero/git/labelflow/strapi/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/nachocarnicero/git/labelflow/strapi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/nachocarnicero/git/labelflow/strapi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/nachocarnicero/git/labelflow/strapi/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

When I try to execute that query in pgAdmin4 I indeed get the same error, but if I change the query to (notice the addition of "strapi" to specify the schema):

```
'select "core_store".* from "strapi"."core_store" where "core_store"."key" = ? and "core_store"."environment" = ? and "core_store"."tag" = ? limit ?'
```

then the query works properly in pgadmin4

### Steps to reproduce the behavior

1. Create a postgresDB and let Strapi create the tables and columns in the `public` schema (I'm using the `https://github.com/strapi/strapi-template-blog` template)
2. Stop Strapi and move the related tables to a new schema called `strapi`
3. Configure Strapi to connect to the DB using the `strapi` schema

### Expected behavior

We should be able to connect to another schema that is not `public`.

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version: 3.6.5
- Database: PostgreSQL
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Fixed in v4, closing
