### ISSUE TITLE
I can't seem to run Strapi V4 through PM2 in Cluster mode

### ISSUE THREAD

**Issue by MaheshCasiraghi** [strapi/strapi#11844]
The process of running Strapi V4 through PM2 ecosystem.json in cluster mode seems to break: PM2 is trying to run different instances of strapi on the same port.

Here is my ecosystem.json configuration, which was working with Strapi v3:
`
  apps: [{
    name: 'appname',
    cwd: '/home/ubuntu/appfolder/current',
    script: 'npm',
    exec_interpreter: 'node',
    args: 'start',
    instances : 'max',
    exec_mode : 'cluster',
`

PM2 documentation isn't helping. Any suggestions of why this is happening?

**Comment by MaheshCasiraghi** [comment]
This solution: https://forum.strapi.io/t/strapi-cron-using-pm2-cluster-mode/4670 doesn't seem to work, either.

**Comment by MaheshCasiraghi** [comment]
Ok, it does work through the workaround:

Create a file `strapiloader.js`, and add this (note the requirement is @strapi/strapi, which differs in v4):

```
const strapi = require('@strapi/strapi');
strapi().start();
```
And then call the file in the ecosystem.config.js:

```
  apps: [{
    name: 'sf',
    cwd: '/home/ubuntu/sf-production/current',
    script: 'strapiloader.js',
    exec_interpreter: 'node',
    instances : 'max',
    exec_mode : 'cluster',
    env: {
```

**Comment by shivarajnaidu** [comment]
When i tried this method in starpi 4.20.0 (typescript)

I got following error
<img width="989" alt="Screenshot 2024-04-03 at 2 19 13 AM" src="https://github.com/strapi/strapi/assets/12374494/85631f59-4ace-4ee3-aaf4-baeb056dd71a">

```
[2024-04-03 02:18:48.121] error: Cannot read properties of undefined (reading 'push')
TypeError: Cannot read properties of undefined (reading 'push')
    at Object.addCreateLocalizationAction (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:3362:48)
    at /Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:2787:22
    at Array.forEach (<anonymous>)
    at extendLocalizedContentTypes (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:2768:39)
    at Object.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:2743:3)
    at Object.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/core/domain/module/index.js:46:46)
    at Object.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/core/registries/modules.js:28:19)
    at async Strapi.runLifecyclesFunctions (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/Strapi.js:440:5)
    at async Strapi.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/Strapi.js:361:5)
    at async Strapi.load (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/Strapi.js:425:5
```
