### ISSUE TITLE
Cannot start if dependency's package.json has "exports"

### ISSUE THREAD

**Issue by yuku** [strapi/strapi#11848]
### Describe the bug

If `dependencies` includes a package whose package.json has `"exports"` and it doesn't export package.json itself, `strapi develop` fails to start development server.

For example, `firebase-admin`'s package.json looks like:

```jsonc
// ...
  "exports": {
    ".": "./lib/index.js",
    "./app": {
      "require": "./lib/app/index.js",
      "import": "./lib/esm/app/index.js"
    },
//...  
```

So, if `firebase-admin` is in the dependencies:

```
$ yarn strapi develop
[2021-12-08 13:34:29.075] debug: ⛔️ Server wasn't able to start properly.
[2021-12-08 13:34:29.076] error: Package subpath './package.json' is not defined by "exports" in /workspace/node_modules/firebase-admin/package.json
  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /workspace/node_modules/firebase-admin/package.json
      at new NodeError (internal/errors.js:322:7)
      at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
      at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
      at resolveExports (internal/modules/cjs/loader.js:450:36)
      at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:93:18)
      at getEnabledPlugins (/workspace/node_modules/@strapi/strapi/lib/core/loaders/plugins/get-enabled-plugins.js:64:25)
      at Object.loadPlugins (/workspace/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:95:32)
      at Strapi.loadPlugins (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:279:19)
      at Strapi.register (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:313:12)
      at Strapi.load (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:409:16)
      at Strapi.start (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:161:20)
      at module.exports (/workspace/node_modules/@strapi/strapi/lib/commands/develop.js:95:29)
```

### Steps to reproduce the behavior

1. `yarn create strapi-app sample --quickstart`
2. Add `"firebase-admin": "10.0.0"` to `package.json`'s `dependencies`, then `yarn install`
3. `yarn develop`
4. 💥 

### Expected behavior

Server can start properly.

### Screenshots

![image](https://user-images.githubusercontent.com/96157/145218061-8e7430ab-e41a-4457-8ee1-f08e14ac3e34.png)

### Code snippets

After the reproduce steps, package.json may look like this:

```jsonc
{
  "name": "bugreport",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/strapi": "4.0.0",
    "@strapi/plugin-users-permissions": "4.0.0",
    "@strapi/plugin-i18n": "4.0.0",
    "firebase-admin": "^10.0.0",  // added
    "sqlite3": "5.0.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

### System

- Node.js version: v16
- NPM version: 
- Strapi version: 4.0.0

### Additional context

The error caused at L63

https://github.com/strapi/strapi/blob/b181702f0202b2c6d645d42b195a831f25cd0b03/packages/core/strapi/lib/core/loaders/plugins/get-enabled-plugins.js#L61-L63

**Comment by yuku** [comment]
Workaround is to move the dependency from `dependencies` to `devDependencies`. In my case, moving `firebase-admin` to `devDependencies` works.

**Comment by yuku** [comment]
It seems the `"exports"` of package.json is described at this page: https://nodejs.org/api/packages.html#package-entry-points
