### ISSUE TITLE
Error when starting strapi with sqlite v3.3.4 : Bootstrap function in plugin "content-manager" failed, SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by ctaque** [strapi/strapi#11885]
### Describe the bug

When I run strapi with the commands `./node_modules/.bin/strapi develop` or `./node_modules/.bin/strapi start`

It crashes with the stack trace below : 

```
 cyprien@cyprien-ubuntu  ~/projets/strapi.cineum.fr  ./node_modules/.bin/strapi develop
[2021-12-13T14:37:38.467Z] error Bootstrap function in plugin "content-manager" failed
[2021-12-13T14:37:38.468Z] error Error: SQLITE_BUSY: database is locked
    at Client_SQLite3._query (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/dialects/sqlite3/index.js:99:12)
    at Client_SQLite3.query (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/client.js:158:17)
    at /home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/transaction.js:331:24
From previous event:
    at Client_SQLite3.trxClient.query (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/transaction.js:326:12)
    at Runner.query (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/runner.js:135:36)
    at /home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/interface.js:14:43)
    at Child.<anonymous> (/home/cyprien/projets/strapi.cineum.fr/node_modules/bookshelf/lib/model.js:1160:42)
From previous event:
    at Child.<anonymous> (/home/cyprien/projets/strapi.cineum.fr/node_modules/bookshelf/lib/model.js:1159:14)
From previous event:
    at Child.<anonymous> (/home/cyprien/projets/strapi.cineum.fr/node_modules/bookshelf/lib/model.js:1060:10)
From previous event:
    at runCreate (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-connector-bookshelf/lib/queries.js:98:45)
    at /home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-connector-bookshelf/lib/queries.js:46:34
    at /home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/transaction.js:91:24
From previous event:
    at /home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/transaction.js:77:12
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at new Transaction (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/transaction.js:57:30)
    at Client_SQLite3.transaction (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/client.js:114:12)
    at Function.transaction (/home/cyprien/projets/strapi.cineum.fr/node_modules/knex/lib/util/make-knex.js:40:31)
    at wrapTransaction (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-connector-bookshelf/lib/queries.js:46:15)
    at Object.create (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-connector-bookshelf/lib/queries.js:105:12)
    at fn (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.create (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-database/lib/queries/helpers.js:15:24)
    at async Object.set (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi/lib/services/core-store.js:104:9)
    at async Promise.all (index 0)
    at async updateContentTypes (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:44:3)
    at async syncContentTypesSchemas (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:55:3)
    at async module.exports (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:172:3)
    at async Promise.all (index 0)
    at async Strapi.runBootstrapFunctions (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi/lib/Strapi.js:407:5)
    at async Strapi.load (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi/lib/Strapi.js:339:5)
    at async Strapi.start (/home/cyprien/projets/strapi.cineum.fr/node_modules/strapi/lib/Strapi.js:193:9)

```

package.json :

```
{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "mysql": "^2.18.1",
    "pg": "^8.6.0",
    "react-color": "^2.19.3",
    "sqlite3": "^5.0.2",
    "strapi": "3.3.4",
    "strapi-admin": "3.3.4",
    "strapi-connector-bookshelf": "3.3.4",
    "strapi-plugin-content-manager": "3.3.4",
    "strapi-plugin-content-type-builder": "3.3.4",
    "strapi-plugin-email": "3.3.4",
    "strapi-plugin-upload": "3.3.4",
    "strapi-plugin-users-permissions": "3.3.4",
    "strapi-utils": "3.3.4"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "dac75d1e-c661-490c-9bfd-4b7c760f5220"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

### System

- Node.js version: v14.0.0
- NPM version: 6.14.4
 Strapi version: 3.3.4
- Database: sqlite
- Operating system: ubuntu 20.04

### Additional informations : 

As suggested by others, I tried to kill the sqlite process/drop the database

**Comment by derrickmehaffy** [comment]
V3 is no longer supported unless it's a critical bug or a security issue.

See: https://github.com/strapi/strapi/issues/11726
