### ISSUE TITLE
Project cannot start in new database - New content types cannot be added - Some fields cannot be added in existing content types

### ISSUE THREAD

**Issue by TasosBak** [strapi/strapi#11914]
Hello guys, I've already built many collection/single types, customized the admin and some plugins but lately I've been having a very strange issue. I run strapi with npm run develop and I cannot create a new collection type! 

After I've entered all the details in the admin and press save, it tries to restart but fails with either of the following messages:

```
error Error: ER_NO_SUCH_TABLE: Table 'db_name.table_name' doesn't exist
    at Query.Sequence._packetToError (C:\Users\user/cms\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14) etc
```
or
```
Error: insert into `core_store` (`key`, `type`, `value`) values ('model_def_strapi::core-store', 'object', '{\"uid\":\"strapi::core-store\",\"collectionName\":\"core_store\",\"info\":{\"name\":\"core_store\",\"description\":\"\"},\"options\":{\"timestamps\":false},\"attributes\":{\"key\":{\"type\":\"string\"},\"value\":{\"type\":\"text\"},\"type\":{\"type\":\"string\"},\"environment\":{\"type\":\"string\"},\"tag\":{\"type\":\"string\"}}}') - ER_NO_SUCH_TABLE: Table 'myDB.core_store' doesn't exist
    at Query.Sequence._packetToError (C:\Users\user\Projects\cms\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
```

### Additional issue
I've tried to start the project from the beginning and add the api, components, plugins, extentions, admin modifications one by one in order to see where the problem occurs but the new project cannot even start and it gives out the following:
```
debug ⛔️ Server wasn't able to start properly.
[2021-12-15T09:01:29.623Z] error Error: insert into `core_store` (`key`, `type`, `value`) values ('model_def_strapi::core-store', 'object', '{\"uid\":\"strapi::core-store\",\"collectionName\":\"core_store\",\"info\":{\"name\":\"core_store\",\"description\":\"\"},\"options\":{\"timestamps\":false},\"attributes\":{\"key\":{\"type\":\"string\"},\"value\":{\"type\":\"text\"},\"type\":{\"type\":\"string\"},\"environment\":{\"type\":\"string\"},\"tag\":{\"type\":\"string\"}}}') - ER_NO_SUCH_TABLE: Table 'db_name.core_store' doesn't exist
```

### System

- Node.js version: 14.17.1
- NPM version: 7.18.1
- Strapi version: 3.5.4
- Database: mysql
- Operating system: windows

**Comment by derrickmehaffy** [comment]
We currently aren't accepting bug reports for v3 issues unless they are critical or security related.
see: https://github.com/strapi/strapi/issues/11726

Likewise we simply don't accept bug reports for any versions where the topic is about customization, for these types of questions I recommend either our forum or our Discord.

**Comment by TasosBak** [comment]
Isn't not able to start or not able to add content type critical? I am not talking about any customization.

**Comment by derrickmehaffy** [comment]
> customized the admin and some plugins

Can you reproduce the issue on a fresh project?
