### ISSUE TITLE
[Strapi 4] After to install package socket.io, don't work.

### ISSUE THREAD

**Issue by Marcosul** [strapi/strapi#11927]
### Describe the bug

After installing the socket.io package, the project does not run.

### Steps to reproduce the behavior

1. Go to 'root folder project'
2. Install socket.io package 'yarn add socket.io'
3. Run 'yarn develop'

### CONSOLE ERROR:

```
$ yarn develop
yarn run v1.22.5
$ strapi develop
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /var/www/prod/msg-app/strapi/node_modules/socket.io/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at getEnabledPlugins (/var/www/prod/msg-app/strapi/node_modules/@strapi/strapi/lib/core/loaders/plugins/get-enabled-plugins.js:63:25)
    at module.exports (/var/www/prod/msg-app/strapi/node_modules/@strapi/strapi/lib/commands/build.js:24:25)
    at /var/www/prod/msg-app/strapi/node_modules/@strapi/strapi/bin/strapi.js:52:14 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
```

### Expected behavior

Project run fine.

### System

- Node.js version: v14.17.2
- NPM version: 6.14.13
- Strapi version: 4.0.0
- Database: mysql
- Operating system: 18.04.5 LTS (GNU/Linux 4.15.0-163-generic x86_64)

**Comment by derrickmehaffy** [comment]
fixed in v4.0.2
