### ISSUE TITLE
Disabling contentSecurityPolicy would cause the GraphQL playground crash

### ISSUE THREAD

**Issue by tianqiwuben** [strapi/strapi#11941]
## Bug report
Disabling contentSecurityPolicy would cause the GraphQL playground crash.

### Describe the bug

We use `aws-s3` as the image upload plugin provider, however the image in the admin dashboard is blocked by `Content Security Policy`: 

    Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

According to the docs, we shall disable the `contentSecurityPolicy` in order to show the images. So I configure the `strapi::security` inside `config/middleware.js` as:

````
{
  name: 'strapi::security',
  config: {
    contentSecurityPolicy: false,
  }
}
````

However, the Graphql playground `/graphql` start to crash:

````
{"data":null,"error":{"status":500,"name":"InternalServerError","message":"Internal Server Error"}}
````

And the terminal would have the following error:

````
Error: Content-Security-Policy needs a default-src but none was provided. If you really want to disable it, set it to `contentSecurityPolicy.dangerouslyDisableDefaultSrc`.
    at normalizeDirectives (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/helmet/dist/middlewares/content-security-policy/index.js:82:9)
    at Object.contentSecurityPolicy [as default] (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/helmet/dist/middlewares/content-security-policy/index.js:117:31)
    at getMiddlewareFunctionsFromOptions (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/helmet/dist/index.js:44:48)
    at helmet (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/helmet/dist/index.js:132:31)
    at koaHelmet (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/koa-helmet/lib/koa-helmet.js:7:42)
    at /home/tianqi/dev/pocketmade/lhs-backend/node_modules/@strapi/strapi/lib/middlewares/security.js:50:10
    at dispatch (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/koa-compose/index.js:42:32)
    at /home/tianqi/dev/pocketmade/lhs-backend/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:13
    at dispatch (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/koa-compose/index.js:42:32)
    at /home/tianqi/dev/pocketmade/lhs-backend/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:11
    at dispatch (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/koa-compose/index.js:42:32)
    at /home/tianqi/dev/pocketmade/lhs-backend/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/koa/lib/application.js:168:12)
    at handleRequest (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/koa/lib/application.js:150:19)
    at Server.handleRequest (/home/tianqi/dev/pocketmade/lhs-backend/node_modules/@strapi/strapi/lib/services/server/http-server.js:15:12)
    at Server.emit (events.js:375:28)
````

### System

- Node.js version: v14.17.3
- NPM version: 8.2.0
- Strapi version: V4
- Database: Postgresql
- Operating system: Ubuntu 20.04.2 LTS

**Comment by qhoirulanwar** [comment]
maybe same like this issue [https://github.com/strapi/strapi/issues/11637#issuecomment-977244572](https://github.com/strapi/strapi/issues/11637#issuecomment-977244572)

**Comment by tianqiwuben** [comment]
> maybe same like this issue [#11637 (comment)](https://github.com/strapi/strapi/issues/11637#issuecomment-977244572)

Yes, same issue. By applying the config in the comment, it solves my issue.
