### ISSUE TITLE
[v4] Can't override the favicon following the docs

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#11951]
### Describe the bug

Can't override the favicon following the docs:

https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#configuration-options

### Steps to reproduce the behavior

1. Add the file `src/extensions/favicon.ico`
2. Update the `src/admin/app.js` to:
    ```javascript
    import favicon from './extensions/favicon.ico';

    export default {
      config: {
        head: {
          favicon: favicon,
        },
      },
      bootstrap() {},
    };
    ```
3. Run `yarn build`
4. See the error in the terminal:
    ```
    ➜  my-project git:(main) ✗ yarn build
    yarn run v1.22.17
    $ strapi build
    Building your admin UI with development configuration ...

    ● Webpack █████████████████████████ building (10%) 0/1 entries 33/65 dependencies 3/19 modules 11 active 
    babel-loader › .cache/admin/src/components/RBACProvider/reducer.js

    ModuleNotFoundError: Module not found: Error: Can't resolve './extensions/favicon.ico' in '/Users/abdonrd/Desktop/my-project/.cache/admin/src'
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/Compilation.js:1765:28
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:730:13
        at eval (eval at create (/Users/abdonrd/Desktop/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:273:22
        at eval (eval at create (/Users/abdonrd/Desktop/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:402:22
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:117:11
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:646:24
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:800:8
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:920:5
        at /Users/abdonrd/Desktop/my-project/node_modules/neo-async/async.js:6883:13
        at Array.<anonymous> (/Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:895:14)
        at arrayEachFunc (/Users/abdonrd/Desktop/my-project/node_modules/neo-async/async.js:2517:19)
        at Object.parallel (/Users/abdonrd/Desktop/my-project/node_modules/neo-async/async.js:6858:9)
        at NormalModuleFactory._resolveResourceErrorHints (/Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:818:12)
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:779:18
    resolve './extensions/favicon.ico' in '/Users/abdonrd/Desktop/my-project/.cache/admin/src'
      using description file: /Users/abdonrd/Desktop/my-project/.cache/package.json (relative path: ./admin/src)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: /Users/abdonrd/Desktop/my-project/.cache/package.json (relative path: ./admin/src/extensions/favicon.ico)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico.js doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico.jsx doesn't exist
          .react.js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico.react.js doesn't exist
          as directory
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico doesn't exist
    ModuleNotFoundError: Module not found: Error: Can't resolve './extensions/favicon.ico' in '/Users/abdonrd/Desktop/my-project/.cache/admin/src'
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/Compilation.js:1765:28
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:730:13
        at eval (eval at create (/Users/abdonrd/Desktop/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:273:22
        at eval (eval at create (/Users/abdonrd/Desktop/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:402:22
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:117:11
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:646:24
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:800:8
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:920:5
        at /Users/abdonrd/Desktop/my-project/node_modules/neo-async/async.js:6883:13
        at Array.<anonymous> (/Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:895:14)
        at arrayEachFunc (/Users/abdonrd/Desktop/my-project/node_modules/neo-async/async.js:2517:19)
        at Object.parallel (/Users/abdonrd/Desktop/my-project/node_modules/neo-async/async.js:6858:9)
        at NormalModuleFactory._resolveResourceErrorHints (/Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:818:12)
        at /Users/abdonrd/Desktop/my-project/node_modules/webpack/lib/NormalModuleFactory.js:779:18
    resolve './extensions/favicon.ico' in '/Users/abdonrd/Desktop/my-project/.cache/admin/src'
      using description file: /Users/abdonrd/Desktop/my-project/.cache/package.json (relative path: ./admin/src)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: /Users/abdonrd/Desktop/my-project/.cache/package.json (relative path: ./admin/src/extensions/favicon.ico)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico.js doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico.jsx doesn't exist
          .react.js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico.react.js doesn't exist
          as directory
            /Users/abdonrd/Desktop/my-project/.cache/admin/src/extensions/favicon.ico doesn't exist
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ```

### Expected behavior

The instructions in the documentation work.

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4
- Database: SQLite
- Operating system: macOS

**Comment by soupette** [comment]
Hello @abdonrd 👋 

I tried to reproduce your issue and it's working on my side. Can you try with the following command and see if it works?

```
yarn strapi build --clean
```

**Comment by abdonrd** [comment]
Thanks for the answer @soupette!

I just try with `yarn strapi build --clean`, but the same error appears.

**Comment by soupette** [comment]
Sorry I did not read your issue carefully enough...
The favicon.ico file should be put in the `./src/admin/extensions` and not the `./src/extensions` one

**Comment by abdonrd** [comment]
Oh, yeah! Now it works! 👏🏻
