### ISSUE TITLE
[V4] QueryEngine - deleteMany not working when filter by nested entity.

### ISSUE THREAD

**Issue by c7ming** [strapi/strapi#11998]
### Describe the bug

When trying to deleteMany by the nested entity filtering, An error occurs.

### Steps to reproduce the behavior

1. Have eneties A & B.
2. Add relation between A & B, and B has many A.
3. Execute codes 

### Expected behavior
All B filtered A will be deleted.

### Screenshots

![image](https://user-images.githubusercontent.com/12271187/147122112-f4ca0414-5f93-460b-a8c8-9fc02efd72b2.png)

### Code snippets

`await strapi.query(A).deleteMany({
        where: {
          B: {
            id: {
              $eq: params.id
            },
          }
        }
      })`

### System

- Node.js version: V14
- NPM version: 7.22.0
- Strapi version: 4.0.1
- Database: MySql
- Operating system: MacOs Monterey

**Comment by iicdii** [comment]
I reproduced it with sqlite too
```js
[Error: delete from `addresses` where (`t2`.`id` = 1) - SQLITE_ERROR: no such column: t2.id] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
```

**Comment by iicdii** [comment]
Temporary workaround. assume that
```
api::address.address - A
api::category.category - B (has many addresses)
```
```js
let addressItems;
try {
  addressItems = await strapi
    .query("api::address.address")
    .findMany({ where: { category: { id: 1 } } });
} catch (e) {
  console.error(e);
}

try {
  for (const address of addressItems) {
    await strapi
      .query("api::address.address")
      .delete({ where: { id: address.id } });
  }
} catch (e) {
  console.error(e);
}
```

**Comment by rcdk** [comment]
I would also love to get this fixed :-)

**Comment by antokhio** [comment]
Just came across this, with oneToOne relation, strapi version 4.3.2
Works: 
```
let tasks = await strapi.db.query("api::task.task").findMany({
  where: {
    parent: section.id,
  },
});
```
Doesn't work:
```
let tasks = await strapi.db.query("api::task.task").deleteMany({
  where: {
    parent: section.id,
  },
});
```

Error message: 
```
error: delete from "tasks" using "tasks_parent_links" as "t1","sections" as "t2" where ("t2"."id" = $1) and "t0"."id" = "t1"."task_id" and "t1"."section_id" = "t2"."id" - missing FROM-clause entry for table "t0"
    at Parser.parseErrorMessage (C:\Users\Smart\source\repos\_sistema\sistema-api\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Users\Smart\source\repos\_sistema\sistema-api\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\Smart\source\repos\_sistema\sistema-api\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\Smart\source\repos\_sistema\sistema-api\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    ```

**Comment by borisNG** [comment]
> 

i'm currently having this issue do you have any clue on how to solve that?

**Comment by MHase** [comment]
I had exactly the same issue and I've managed to solve this by adding additional query

I wanted to remove all all products (lamps) which are related to common family
in my case I had to query for all related items and after that remove them one by one

I know it's not perfect, but for this `deleteMany` error should be enough 😞

still I hope that they will fix it in near future

```
beforeDelete: async (event) => {
  const { params } = event;

  const familyId = params.where.id;
 
  const lampsToDelete = await strapi.db.query("api::lamp.lamp").findMany({
    where: {
      family: {
        id: {
          $eq: familyId,
        },
      },
    },
  });

  await Promise.all(
    lampsToDelete.map(({ id }) =>
      strapi.db.query("api::lamp.lamp").delete({
        where: { id },
      })
    )
  );
},
```

**Comment by XanderD99** [comment]
Just encountered this issue as well. 

Got it working with the code below. Seems like strapi just expects us to pass something in the id value in the where filter. So passing a query to match all ids in an array of numbers works just fine.

```
module.exports = {
  async beforeDelete({ params }) {
    const channels = await strapi.db.query('api::discord.channel').findMany({ where: { guild: params.where.id } });
    return strapi.db.query('api::discord.channel').deleteMany({ where: { id: { $in: channels.map(({ id }) => id) } } });
  },
}
```

**Comment by itruf** [comment]
I have same issue with `updateMany` method:
```
await strapi.db.query("api::message.message").updateMany({
                        where: {
                            $and: [
                                { chat: decoded.chatId },
                                { in_context: true },
                            ],
                        },
                        data: {
                            in_context: false,
                        },
                    }).catch((e) => console.log("error", e.message));
```

**Comment by ItsHMS** [comment]
> Just encountered this issue as well.
> 
> Got it working with the code below. Seems like strapi just expects us to pass something in the id value in the where filter. So passing a query to match all ids in an array of numbers works just fine.
> 
> ```
> module.exports = {
>   async beforeDelete({ params }) {
>     const toDelete = await strapi.db.query('api::discord.channel').findMany({ where: { guild: params.where.id } });
>     return strapi.db.query('api::discord.channel').deleteMany({ where: { id: { $in: toDelete.map(({ id }) => id) } } });
>   },
> }
> ```

this one is perfectly working.Here is what i have done exactly this person did:
`console.log("itemsToDelete", itemsToDelete);
                const deleted = await strapi
                  .query("api::order-item.order-item")
                  .deleteMany({
                    where: {
                      id: {
                        $in: itemsToDelete.map((item) => item.id),
                      },
                    },
                  });`

**Comment by boazpoolman** [comment]
> this one is perfectly working.Here is what i have done exactly this person did:
console.log("itemsToDelete", itemsToDelete); const deleted = await strapi .query("api::order-item.order-item") .deleteMany({ where: { id: { $in: itemsToDelete.map((item) => item.id), }, }, });

It's a nice workaround, but it's suboptimal in terms of performance.

**Comment by MaksZhukov** [comment]
Any updates from strapi?

**Comment by DweyDev** [comment]
> 

Unfortunately I experienced the bug yesterday

**Comment by angelplusultra** [comment]
Experienced this bug today, used @XanderD99 solution and it works

**Comment by OdifYltsaeb** [comment]
I have the same issue with Postgresql, where I'm looking to update multiple addresses and filtering them by owner id ( FK to the user ). The issue has been open for close to 2 years already. Perhaps it's time to fix this?

**Comment by AlexanderFuse** [comment]
same issue

**Comment by briankandersen** [comment]
As per today, this bug is still there. It's been almost 2 years now. What is going on? Why hasn't this been fixed yet?

**Comment by AndriiKlymchuk** [comment]
Still occurs in the version 4.14.6
Since so many people experience it for a long time, @alexandrebodin could the team pay attention on it?

**Comment by Dimitris-Arabatzis** [comment]
This is an important defect. Please pay attention to this.

**Comment by MaksZhukov** [comment]
Any updates from strapi team?

**Comment by alexandrebodin** [comment]
Hello all 👋 

Sadly we cannot work on this issue at the moment because we are prioritizing other more critical issues. This one was defiend as low severity because a workaround exists for now. We are still a small team doing all our best to address the more urgent topics 🙏 
 
 If some of you are interested in contributing a fix let us know so we can guide you through the codebase 💯

**Comment by opiredev** [comment]
@nabby27 created a $60.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by glebsergeevich** [comment]
updateMany still have this issue

**Comment by kevinvugts** [comment]
> await Promise.all(
>     lampsToDelete.map(({ id }) =>
>       strapi.db.query("api::lamp.lamp").delete({
>         where: { id },
>       })
>     )
>   );

This has been a bug for way too long. And in term of effort to fix this, the severity should be higher than this.
Query related bugs can't spoke around for years in a core code.

**Comment by kevinvugts** [comment]
> Hello all 👋
> 
> Sadly we cannot work on this issue at the moment because we are prioritizing other more critical issues. This one was defiend as low severity because a workaround exists for now. We are still a small team doing all our best to address the more urgent topics 🙏
> 
> If some of you are interested in contributing a fix let us know so we can guide you through the codebase 💯

This has been a bug for way too long. And in term of effort to fix this, the severity should be higher than this.
Query related bugs can't spoke around for years in a core code, that's not acceptable if you'd ask me.

Could you elaborate more on when this is fixed? I think there is nothing more important than have a v4 stable version. Instead of moving to "more important" tasks such as v5. :-) I think this deserves more attention as this thread is growing and growing each and every week.

**Comment by MHase** [comment]
I encountered this issue on November 5, 2022
this discussion started on December 22, 2021
now it's August 2024, and still NOTHING has changed - just some workarounds and hacks
it makes me want to cry and laugh at the same time

**Comment by NotAhmedNasr** [comment]
I have made a [PR](https://github.com/strapi/strapi/pull/17312) for this issue for a long time now but it hasn't been reviewed yet. It's a simple one-line change, and it worked for us. You can try to introduce it locally to the code in the node_modules and if it works for you, you can do a [patch-package](https://www.npmjs.com/package/patch-package) until a permanent solution is done.

**Comment by glacierck** [comment]
> I have made a [PR](https://github.com/strapi/strapi/pull/17312) for this issue for a long time now but it hasn't been reviewed yet. It's a simple one-line change, and it worked for us. You can try to introduce it locally to the code in the node_modules and if it works for you, you can do a [patch-package](https://www.npmjs.com/package/patch-package) until a permanent solution is done.

No longer throwing exceptions but not completing batch deletion！
code
`
await strapi.db.query("api::job-member.job-member").deleteMany({
        where: {
          job: {
            $null: true,
          }
        },
      });
`
’job‘ is populate，possible issue is that with $null

**Comment by alexandrebodin** [comment]
Hi 👋  We have fixed this on v5. It was quite a complex bug fix to do. 

I'm not sure it is possible to backport it to v4 but if someone want to try here is the original v5 fix PR https://github.com/strapi/strapi/pull/20543

**Comment by briankandersen** [comment]
It sucks so extremely bad that this bug is still in v4.

**Comment by semiaddict** [comment]
Hello @alexandrebodin,

> Hi 👋 We have fixed this on v5. It was quite a complex bug fix to do.

I don't seem to be able to do a `deleteMany` in v5 while filtering on a nested entity.

Running this:
```js
await strapi.db.query("api::datavis.datum").deleteMany({
    where: { recording: { $in: recordingIds } }
})
```
gives me the following error:
```bash
delete from "public"."data" using "public"."data_recording_lnk" as "t1","public"."recordings" as "t2" where ("t2"."id" in ($1)) and "t0"."id" = "t1"."datum_id" and "t1"."recording_id" = "t2"."id" - missing FROM-clause entry for table "t0"
```

I've also tried this with the same result:
```js
await strapi.db.query("api::datavis.datum").deleteMany({
    where: { recording: { id: { $in: recordingIds } } }
})
``` 

Is this supposed to work now in v5 ?

**Comment by swjcpy** [comment]
I opened PR #25420 to ensure deleteMany runs query builder init so nested relation filters are processed, plus a small unit test that validates the params are forwarded.

**Comment by vietducn19-maker** [comment]
I'm working on this $30 bounty from Opire.

**Comment by keepinitkrispy** [comment]
Withdrawing this claim: Opire currently lists this bounty as open, but GitHub correctly shows the issue was completed and closed on March 20, 2025. No duplicate work or PR will be submitted.
