### ISSUE TITLE
Cannot edit existing collection entries

### ISSUE THREAD

**Issue by artcoded-net** [strapi/strapi#12014]
### Describe the bug

I have bootstrapped a brand new Strapi app, v. 4.0.2 with node 16.13.1 using the yarn installation script.
I am creating a simple Blog application. With my "Post" content type (collection) I can create entries but when I save it, though it actually saves it, I get a blank screen and I have to restart from the admin home. Also, when accessing these entries, I get the same white screen and no possibility to access again to edit my content. For all the other content types, instead, I get no errors.

Here's the errors shown in the console in both cases:
```shell
main.d3ce37d0.js:2 TypeError: te.map is not a function
    at content-manager.b0919fbd.chunk.js:1:170710
    at Object.useMemo (main.d3ce37d0.js:2:1927855)
    at t.useMemo (main.d3ce37d0.js:2:2093530)
    at B (content-manager.b0919fbd.chunk.js:1:170673)
    at si (main.d3ce37d0.js:2:1921890)
    at Xu (main.d3ce37d0.js:2:1974187)
    at ks (main.d3ce37d0.js:2:1961428)
    at Ps (main.d3ce37d0.js:2:1961356)
    at Ms (main.d3ce37d0.js:2:1961219)
    at xs (main.d3ce37d0.js:2:1958185)
fu @ main.d3ce37d0.js:2
main.d3ce37d0.js:2 Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (3706.37d8dec1.chunk.js:2:1600017)
    at Gi (main.d3ce37d0.js:2:1934521)
    at Qi (main.d3ce37d0.js:2:1934318)
    at Xu (main.d3ce37d0.js:2:1975260)
    at ks (main.d3ce37d0.js:2:1961428)
    at Ps (main.d3ce37d0.js:2:1961356)
    at Ms (main.d3ce37d0.js:2:1961219)
    at xs (main.d3ce37d0.js:2:1958185)
    at main.d3ce37d0.js:2:1907682
    at t.unstable_runWithPriority (main.d3ce37d0.js:2:2108478)
fu @ main.d3ce37d0.js:2
main.d3ce37d0.js:2 Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (3706.37d8dec1.chunk.js:2:1600017)
    at Gi (main.d3ce37d0.js:2:1934521)
    at Qi (main.d3ce37d0.js:2:1934318)
    at Xu (main.d3ce37d0.js:2:1975260)
    at ks (main.d3ce37d0.js:2:1961428)
    at Ps (main.d3ce37d0.js:2:1961356)
    at Ms (main.d3ce37d0.js:2:1961219)
    at xs (main.d3ce37d0.js:2:1958185)
    at main.d3ce37d0.js:2:1907682
    at t.unstable_runWithPriority (main.d3ce37d0.js:2:2108478)
```

### Steps to reproduce the behavior

1. Clone my [public repo](https://github.com/artcoded-net/strapi-template-corporateblog)
2. Start the app in dev mode
3. Create a "Post" entry
4. See the error when saving the entry and when trying to access/edit the already created entry

### Code snippets

Here is my "post" content schema:
```
{
  "kind": "collectionType",
  "collectionName": "posts",
  "info": {
    "singularName": "post",
    "pluralName": "posts",
    "displayName": "Post",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "Title": {
      "type": "string",
      "required": true,
      "unique": true,
      "minLength": 3
    },
    "Authors": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "admin::user"
    },
    "Cover": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },
    "Content": {
      "type": "richtext",
      "required": true
    },
    "PostSEO": {
      "type": "component",
      "repeatable": false,
      "component": "seo.seo-information"
    },
    "Slug": {
      "type": "uid",
      "targetField": "Title",
      "required": true
    },
    "tags": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::tag.tag"
    }
  }
}
```

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: v. 4.0.2
- Database: sqlite (default settings)
- Operating system: reproduced in both Mac OS 11.6.1 and on Windows 10

**Comment by soupette** [comment]
It seems to be related to the relation made with the admin user model.

The weird part is that the API response for the Authors field is an object instead of an Array even thought the relation made between posts and author is a manyWay.

Related to #11891

**Comment by nextrapi** [comment]
I am looking into this. The issue is with the sanitization. Otherwise the data is correctly stored.

**Comment by boehlerlukas** [comment]
I run into a similar issue (but for me it's related to file uploads - happening after uploading a file)

```
main.dfa22c7a.js:2 TypeError: Cannot read properties of null (reading 'split')
    at main.dfa22c7a.js:2
    at Array.filter (<anonymous>)
    at a (main.dfa22c7a.js:2)
    at E (main.dfa22c7a.js:2)
    at si (main.dfa22c7a.js:2)
    at Xu (main.dfa22c7a.js:2)
    at ks (main.dfa22c7a.js:2)
    at Ps (main.dfa22c7a.js:2)
    at Ms (main.dfa22c7a.js:2)
    at xs (main.dfa22c7a.js:2)
fu @ main.dfa22c7a.js:2
main.dfa22c7a.js:2 Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (:1337/admin/3226.1a4b5cd1.chunk.js:2)
    at Vi (main.dfa22c7a.js:2)
    at Qi (main.dfa22c7a.js:2)
    at Xu (main.dfa22c7a.js:2)
    at ks (main.dfa22c7a.js:2)
    at Ps (main.dfa22c7a.js:2)
    at Ms (main.dfa22c7a.js:2)
    at xs (main.dfa22c7a.js:2)
    at main.dfa22c7a.js:2
    at t.unstable_runWithPriority (main.dfa22c7a.js:2)
fu @ main.dfa22c7a.js:2
main.dfa22c7a.js:2 Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (:1337/admin/3226.1a4b5cd1.chunk.js:2)
    at Vi (main.dfa22c7a.js:2)
    at Qi (main.dfa22c7a.js:2)
    at Xu (main.dfa22c7a.js:2)
    at ks (main.dfa22c7a.js:2)
    at Ps (main.dfa22c7a.js:2)
    at Ms (main.dfa22c7a.js:2)
    at xs (main.dfa22c7a.js:2)
    at main.dfa22c7a.js:2
    at t.unstable_runWithPriority (main.dfa22c7a.js:2)
```
