### ISSUE TITLE
[V4.0.2] white page on single types without i18n

### ISSUE THREAD

**Issue by ekimv** [strapi/strapi#12013]
## Bug report
white page on single types without i18n

### Describe the bug
Strapi is with i18n configured ; but when some single types with translations and some with no translation (option i18n localized set to false), it is impossible to access the not translatable types.
in v4.0.1 : there was a white page with parameter ?null but when refreshing the page (F5) the admin panel was working
in v4.0.2 : there is no more parameter on not translatable single types, but the page is empty and refreshing does nothing ; setting a parameter ?null does nothing more
In javascript console, an error occurs :

react_devtools_backend.js:4045 TypeError: Cannot read properties of undefined (reading 'toggleNotification')
    at t.default (main.d7778317.js:2)
    at t.CloudinaryProvider (main.d7778317.js:2)
    at li (main.d7778317.js:2)
    at Zu (main.d7778317.js:2)
    at kl (main.d7778317.js:2)
    at Pl (main.d7778317.js:2)
    at Sl (main.d7778317.js:2)
    at xl (main.d7778317.js:2)
    at main.d7778317.js:2
    at t.unstable_runWithPriority (main.d7778317.js:2)

### Steps to reproduce the behavior

Create a strapi with 2 single types : one translatable, and another not translatable
Try to fill the single type not translatable : it will show white screen with the above error

### System

- Node.js version: 14.18.2
- NPM version: 8.1.4 & yarn 1.22.17
- Strapi version: 4.0.2
- Database: mysql
- Operating system: linux

**Comment by ippoippo** [comment]
I think this is related to https://github.com/strapi/strapi/issues/11996

**Comment by ekimv** [comment]
Thank you for your answer !
I agree, the effect of "white page" seems to be the same

I reverted to **4.0.1** and the problem is sligthly different, and not *blocking* :
If I go directly to the single type not translatable, no problem
If I go first to a translatable single type, it works, and then to the single type not translatable, I got a similar white page with a different js error :
react_devtools_backend.js:4045 
TypeError: Cannot read properties of undefined (reading 'code')
    at O (main.aefa8713.js:2)
    at si (main.aefa8713.js:2)
    at Yi (main.aefa8713.js:2)
    at Zu (main.aefa8713.js:2)
    at ks (main.aefa8713.js:2)
    at Ps (main.aefa8713.js:2)
    at Ss (main.aefa8713.js:2)
    at xs (main.aefa8713.js:2)
    at main.aefa8713.js:2
    at t.unstable_runWithPriority (main.aefa8713.js:2)
    
 If I hit F5, the page reloads correctly in v4.0.1 (in v4.0.2, it was always white page)

Good luck

**Comment by soupette** [comment]
@ekimv can you provide us with a demo app I am not able to reproduce the issue.

Thanks a lot!

**Comment by soupette** [comment]
I am closing this issue due to inactivity. Feel free to reopen it.

**Comment by zrninlive** [comment]
Hey guys, how are u?

I've been facing the same problem here, I deployed a project from scratch (just basic configs to Google App Engine) and I got this error:

TypeError: Cannot read properties of undefined (reading 'toggleNotification')
    at t.default (main.70b7511c.js:2:966589)
    at f (main.70b7511c.js:2:1191356)
    at s (main.70b7511c.js:2:1175539)
    at si (main.70b7511c.js:2:1945411)
    at Gu (main.70b7511c.js:2:1997708)
    at ks (main.70b7511c.js:2:1984949)
    at Ps (main.70b7511c.js:2:1984877)
    at Ss (main.70b7511c.js:2:1984740)
    at xs (main.70b7511c.js:2:1981706)
    at main.70b7511c.js:2:1931203


Uncaught TypeError: Cannot read properties of undefined (reading 'toggleNotification')
    at t.default (main.70b7511c.js:2:966589)
    at f (main.70b7511c.js:2:1191356)
    at s (main.70b7511c.js:2:1175539)
    at si (main.70b7511c.js:2:1945411)
    at Gu (main.70b7511c.js:2:1997708)
    at ks (main.70b7511c.js:2:1984949)
    at Ps (main.70b7511c.js:2:1984877)
    at Ss (main.70b7511c.js:2:1984740)
    at xs (main.70b7511c.js:2:1981706)
    at main.70b7511c.js:2:1931203

![image](https://user-images.githubusercontent.com/10995394/156641502-10c4e619-03cf-464a-a244-6bbf30a0d7a1.png)

These error appear after login/register an user, I try to navigate to other logged pages and got the same :\

Could someone please help-me?

Thanks a lot! ;)

**Comment by soupette** [comment]
@zrninlive is your app working locally after building it?

**Comment by rasmus-rudling** [comment]
> Hey guys, how are u?
> 
> I've been facing the same problem here, I deployed a project from scratch (just basic configs to Google App Engine) and I got this error:
> 
> TypeError: Cannot read properties of undefined (reading 'toggleNotification') at t.default (main.70b7511c.js:2:966589) at f (main.70b7511c.js:2:1191356) at s (main.70b7511c.js:2:1175539) at si (main.70b7511c.js:2:1945411) at Gu (main.70b7511c.js:2:1997708) at ks (main.70b7511c.js:2:1984949) at Ps (main.70b7511c.js:2:1984877) at Ss (main.70b7511c.js:2:1984740) at xs (main.70b7511c.js:2:1981706) at main.70b7511c.js:2:1931203
> 
> Uncaught TypeError: Cannot read properties of undefined (reading 'toggleNotification') at t.default (main.70b7511c.js:2:966589) at f (main.70b7511c.js:2:1191356) at s (main.70b7511c.js:2:1175539) at si (main.70b7511c.js:2:1945411) at Gu (main.70b7511c.js:2:1997708) at ks (main.70b7511c.js:2:1984949) at Ps (main.70b7511c.js:2:1984877) at Ss (main.70b7511c.js:2:1984740) at xs (main.70b7511c.js:2:1981706) at main.70b7511c.js:2:1931203
> 
> ![image](https://user-images.githubusercontent.com/10995394/156641502-10c4e619-03cf-464a-a244-6bbf30a0d7a1.png)
> 
> These error appear after login/register an user, I try to navigate to other logged pages and got the same :\
> 
> Could someone please help-me?
> 
> Thanks a lot! ;)

I get the exact same error when trying to deploy to app engine

**Comment by soupette** [comment]
Do you have any custom plugin that have the @strapi/helper-plugin in their dependencies?

**Comment by AntoineXevlabs** [comment]
I got the exact same issue on google app Engine. Everything is working perfectly fine otherwise.
here is my package.json 

```
{
  "name": "afem-backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "gcp-build": "export NODE_ENV=production && strapi build",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.0.7",
    "@strapi/plugin-users-permissions": "4.0.7",
    "@strapi/strapi": "4.0.7",
    "file-saver": "^2.0.5",
    "joi": "^17.6.0",
    "json2csv": "^5.0.7",
    "pg": "^8.7.1",
    "sqlite3": "5.0.2",
    "strapi-provider-upload-google-cloud-storage": "^4.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "70249a51-6887-4c39-b326-2911dc325431"
  },
  "engines": {
    "node": "^14.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by soupette** [comment]
@AntoineXevlabs can you share me with an access to your repo?

**Comment by AntoineXevlabs** [comment]
@soupette sure I added you to the repo

**Comment by rideddy84** [comment]
Same with Strapi 4.1.3 on Google App Engine. Just created by `yarn create strapi-app PROJECT_NAME --quickstart`

**Comment by AntoineXevlabs** [comment]
@soupette where you able to find something about the issue ?

**Comment by AntoineXevlabs** [comment]
If you want an app engine console or environment I'll be happy to provide

**Comment by niko20** [comment]
I have same issue, please help

**Comment by soupette** [comment]
@AntoineXevlabs No I haven't yet.

**Comment by link3321** [comment]
I got the exact same issue with an deployed service on Google App Engine following guide provided by Strapi: 
https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html

`{
  "name": "bollify",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "gcp-build": "strapi build"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.1.3",
    "@strapi/plugin-users-permissions": "4.1.3",
    "@strapi/strapi": "4.1.3",
    "pg": "^8.7.3",
    "sqlite3": "5.0.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "e2ff7a2b-6e60-4ecc-83e0-095d65559a4b"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
`

If anyone finds a fix please let me know!

**Comment by rideddy84** [comment]
If there was an [ErrorBoundaryComponent](https://reactjs.org/docs/error-boundaries.html), all we could avoid full white screen.

**Comment by adamk72** [comment]
Try running this with 'npm' instead of 'yarn' (presuming that's what you're doing). I spent a long time on this till it finally dawned (and was one of my last remaining hopes) that I hadn't tried another package manager.

**Comment by rasmus-rudling** [comment]
See solution for this [here](https://github.com/strapi/strapi/issues/12869)! @rideddy84 saved my day
