### ISSUE TITLE
Plugin registerMany Validation Errors are not thrown correctly

### ISSUE THREAD

**Issue by tilman** [strapi/strapi#12026]
### Describe the bug

If we use `await strapi.admin.services.permission.actionProvider.registerMany(actions);` during a plugin bootstrap phase and have some wrong config in the actions (like a wrong pluginName) I expect to get some informative error why the register was unsuccessful. Instead I get the following error: 
```
[2021-12-26 13:54:51.217] debug: ⛔️ Server wasn't able to start properly.
[2021-12-26 13:54:51.217] error: 2 errors occurred
ValidationError: 2 errors occurred
    at handleYupError (/.../strapi-v4-trial/node_modules/@strapi/utils/lib/validators.js:64:9)
    at /.../strapi-v4-trial/node_modules/@strapi/utils/lib/validators.js:83:5
    at Object.registerMany (/.../strapi-v4-trial/node_modules/@strapi/admin/server/domain/action/provider.js:47:7)
    at Object.module.exports [as bootstrap] (/.../strapi-v4-trial/src/plugins/strapi-plugin-db-seeding/server/bootstrap.js:39:57)
    at Object.bootstrap (/.../strapi-v4-trial/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:47)
    at Object.bootstrap (/.../strapi-v4-trial/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Strapi.runLifecyclesFunctions (/.../strapi-v4-trial/node_modules/@strapi/strapi/lib/Strapi.js:463:5)
    at async Strapi.bootstrap (/.../strapi-v4-trial/node_modules/@strapi/strapi/lib/Strapi.js:401:5)
    at async Strapi.load (/.../strapi-v4-trial/node_modules/@strapi/strapi/lib/Strapi.js:410:5)
    at async Strapi.start (/.../strapi-v4-trial/node_modules/@strapi/strapi/lib/Strapi.js:161:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The Stack trace is not helping as well. 

If I add some console.log's to `strapi/utils/lib/validators.js`:
```
const handleYupError = (error, errorMessage) => {
  console.log("error", error, errorMessage)
  throw new YupValidationError(error, errorMessage);
};
```
The error is way more informative:
```
error ValidationError: 2 errors occurred
    at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:63:20)
    at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:17:5
    at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:63:11)
    at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:17:5
    at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:67:9)
    at validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:96:103)
    at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
    at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:248:29
    at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:17:5
    at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:67:9)
    at validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:96:103)
    at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
    at StringSchema._validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:239:27)
    at StringSchema.validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:264:51)
    at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/object.js:182:17
    at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5) {
  value: [
    {
      section: 'plugins',
      displayName: 'Access the plugin settings',
      uid: 'settings.read',
      pluginName: 'db-seeding'
    },
    {
      section: 'plugins',
      displayName: 'Menu link to plugin settings',
      uid: 'menu-link',
      pluginName: 'db-seeding'
    }
  ],
  path: undefined,
  type: undefined,
  errors: [
    '[0].pluginName is not an existing plugin',
    '[1].pluginName is not an existing plugin'
  ],
  inner: [
    ValidationError: [0].pluginName is not an existing plugin
        at Object.createError (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:54:21)
        at Object.<anonymous> (.../strapi-v4-trial/node_modules/@strapi/admin/server/validation/common-validators.js:42:14)
        at validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:86:21)
        at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:248:29
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:17:5
        at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:67:9)
        at validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:96:103)
        at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
        at StringSchema._validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:239:27)
        at BaseSchema.validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:264:51)
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/object.js:182:17
        at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/object.js:199:29
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:17:5
        at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:67:9) {
      value: 'db-seeding',
      path: '[0].pluginName',
      type: 'is-a-plugin-name',
      errors: [Array],
      inner: [],
      params: [Object]
    },
    ValidationError: [1].pluginName is not an existing plugin
        at Object.createError (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:54:21)
        at Object.<anonymous> (.../strapi-v4-trial/node_modules/@strapi/admin/server/validation/common-validators.js:42:14)
        at validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:86:21)
        at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:248:29
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:17:5
        at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:67:9)
        at validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/createValidation.js:96:103)
        at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
        at StringSchema._validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:239:27)
        at BaseSchema.validate (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/schema.js:264:51)
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/object.js:182:17
        at runTests (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:39:5)
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/object.js:199:29
        at .../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:17:5
        at finishTestRun (.../strapi-v4-trial/node_modules/@strapi/utils/node_modules/yup/lib/util/runTests.js:67:9) {
      value: 'db-seeding',
      path: '[1].pluginName',
      type: 'is-a-plugin-name',
      errors: [Array],
      inner: [],
      params: [Object]
    }
  ]
} undefined
```

### Steps to reproduce the behavior

Create a new plugin using the generator and in bootstrap register phase register a new action with a not existing name.

### Expected behavior

Is it possible to pass the error information upwards so a plugin developer knows what was causing the validation error?

### System

- Node.js version: v16.13.1
- NPM version: yarn 1.22.17
- Strapi version: "@strapi/strapi": "4.0.2"
- Database: PostgreSQL
- Operating system: Mac OSX

**Comment by tilman** [comment]
How about changing `YupValidationError` in file `utils/lib/errors.js` to the following:
```

**Comment by derrickmehaffy** [comment]
> Should I create a PR with this change? I think that's valid. @markkaylor / @remidej what do you think?

**Comment by derrickmehaffy** [comment]
(Assigned to expansion and DevExp as I wasn't sure which squad is handling issues like this, PM please remove issue from your project if it's not for your squad)

**Comment by tilman** [comment]
> > Should I create a PR with this change?
> 
> I think that's valid. @markkaylor / @remidej what do you think?

Totally forgot to create the PR. I have done it now.

**Comment by emilieringwald** [comment]
Hey @tilman ! Thanks for the ticket, we added it to our backlog and we'll review it asap.

**Comment by gfsd3v** [comment]
I think this should have some priority on Strapi side, I spent some time trying to figure it out what was happening and trying to log the actual error, thx for the example code @tilman, it saved me a lot of time debugging (:
