### ISSUE TITLE
Strapi not building with pnpm workspace

### ISSUE THREAD

**Issue by DenisLaboureyras** [strapi/strapi#12034]
### Describe the bug

I tried to build strapi in a monorepo using pnpm. I've seen a issue that strapi is not supporting pnpm but manage to build strapi with a small fix.
The issue is in the file : https://github.com/strapi/strapi/blob/master/packages/core/email/admin/src/pages/Settings/utils/api.js
First line:
`import { axiosInstance } from '../../../../../../admin/admin/src/core/utils';`
is refering to the @strapi/admin package and pnpm does not found it, as it renames the packages.

If you replace it by:
`import { axiosInstance } from '@strapi/admin/admin/src/core/utils';`
and add the admin dependency to the email package
it works correctly.

Furthermore it's best for the package isolations not to refer to another package with a relative path.

### Steps to reproduce the behavior

1. create pnpm monorepo
2. create a strapi app in the apps folder
3. try to build

### Expected behavior

The build is successful

### System

- Node.js version: v16
- PNPM version: 6
- Strapi version: v4.0.2
- Database: PostgreSQL
- Operating system: MacOS

**Comment by arpadgabor** [comment]
@DenisLaboureyras did the PR fix all your issues with pnpm workspace? Experiencing a similar problem but with `strapi-helper-plugin`, webpack cannot resolve it. If I install it manually then it erros with `lodash`.

```
Module not found: Error: Can't resolve 'lodash' in '/home/arpad/projects/turbo-test/apps/cms/.cache/admin/src'
```

My usecase: setting up a mono-repo with turborepo. Works with yarn v1, does not work with pnpm. Running strapi standalone with pnpm works too (as in not in a monorepo).

**Comment by arpadgabor** [comment]
Update, build fails with the following error, with pnpm workspaces:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime/regenerator' in '/home/arpad/projects/turbo-test/apps/cms/.cache/admin/src'
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/Compilation.js:1765:28
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/home/arpad/projects/turbo-test/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/home/arpad/projects/turbo-test/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:6883:13
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/home/arpad/projects/turbo-test/node_modules/.pnpm/enhanced-resolve@5.8.3/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/enhanced-resolve@5.8.3/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/enhanced-resolve@5.8.3/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/arpad/projects/turbo-test/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@babel/runtime/regenerator' in '/home/arpad/projects/turbo-test/apps/cms/.cache/admin/src'
  Parsed request is a module
  using description file: /home/arpad/projects/turbo-test/apps/cms/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/arpad/projects/turbo-test/apps/cms/.cache/admin/src/node_modules doesn't exist or is not a directory
      /home/arpad/projects/turbo-test/apps/cms/.cache/admin/node_modules doesn't exist or is not a directory
      /home/arpad/projects/turbo-test/apps/cms/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /home/arpad/projects/turbo-test/apps/cms/node_modules
        /home/arpad/projects/turbo-test/apps/cms/node_modules/@babel/runtime doesn't exist
      /home/arpad/projects/turbo-test/apps/node_modules doesn't exist or is not a directory
      looking for modules in /home/arpad/projects/turbo-test/node_modules
        /home/arpad/projects/turbo-test/node_modules/@babel/runtime doesn't exist
      /home/arpad/projects/node_modules doesn't exist or is not a directory
      /home/arpad/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime/regenerator' in '/home/arpad/projects/turbo-test/apps/cms/.cache/admin/src'
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/Compilation.js:1765:28
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/home/arpad/projects/turbo-test/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/home/arpad/projects/turbo-test/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:6883:13
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.9.1/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/home/arpad/projects/turbo-test/node_modules/.pnpm/enhanced-resolve@5.8.3/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/enhanced-resolve@5.8.3/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /home/arpad/projects/turbo-test/node_modules/.pnpm/enhanced-resolve@5.8.3/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/arpad/projects/turbo-test/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@babel/runtime/regenerator' in '/home/arpad/projects/turbo-test/apps/cms/.cache/admin/src'
  Parsed request is a module
  using description file: /home/arpad/projects/turbo-test/apps/cms/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/arpad/projects/turbo-test/apps/cms/.cache/admin/src/node_modules doesn't exist or is not a directory
      /home/arpad/projects/turbo-test/apps/cms/.cache/admin/node_modules doesn't exist or is not a directory
      /home/arpad/projects/turbo-test/apps/cms/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /home/arpad/projects/turbo-test/apps/cms/node_modules
        /home/arpad/projects/turbo-test/apps/cms/node_modules/@babel/runtime doesn't exist
      /home/arpad/projects/turbo-test/apps/node_modules doesn't exist or is not a directory
      looking for modules in /home/arpad/projects/turbo-test/node_modules
        /home/arpad/projects/turbo-test/node_modules/@babel/runtime doesn't exist
      /home/arpad/projects/node_modules doesn't exist or is not a directory
      /home/arpad/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by DenisLaboureyras** [comment]
Hello @arpadgabor,

I've managed to do a successful build after I corrected manually this bug. I'm waiting the 4.0.3 version of Strapi to do further tests.
I remember having this kind of issue, I used Turborepo as well. Deleting the Turborepo cache folder before a successful build fix the errors. I think your bug is more related to Turborepo than Strapi.

**Comment by arpadgabor** [comment]
Thanks @DenisLaboureyras for your reply. Honestly not sure where the problem is. I tried installing each package `build` was failing with, but after about 10-15 installs I said f* it. Tried creating another repo with npm as package manager, now I got another issue from webpack `The 'compilation' argument must be an instance of Compilation`. I removed the code from node modules that threw this error and build works (ofc, it's not a good solution).

If you have a working repository with strapi in a monorepo as example that would be great.

**Comment by derrickmehaffy** [comment]
> 

that complication error is an npm 8 issue we are already aware of but yes if you use yarn v1 with npm 8 it works fine. unrelated to this issue specifically

**Comment by teamchong** [comment]
I ran into this pnpm problem, and this is how I solve it.

1. I created my project with the CLI `strapi new --use-npm <directory>`
2. run `pnpm import` or `pnpm import yarn.lock` if you're using yarn
3. according to [pnpm FAQ](https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here), there are 3 solutions, but 1 & 2 take forever, so I am using solution 3
4. pnpm i -r --prod --shamefully-hoist && pnpm run build --parallel
5. if you doing this in docker, this is my dockerfile
```
pnpm i -r --offline --prod --shamefully-hoist && pnpm run build --parallel
FROM strapi/base:latest
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
WORKDIR /app
ENV NODE_ENV production

COPY pnpm-lock.yaml ./
RUN pnpm fetch --prod

ADD . ./
RUN pnpm i -r --offline --prod --shamefully-hoist && pnpm run build --parallel

EXPOSE 1337
CMD ["pnpm", "start"]
```
hope it help
