### ISSUE TITLE
[v4] examples/getstarted does not work

### ISSUE THREAD

**Issue by matsubaraDaisuke** [strapi/strapi#12039]
## Bug report

examples/getstarted does not work

### Steps to reproduce the behavior

1 git clone https://github.com/strapi/strapi.git
2 cd strapi/examples/getstarted
3 yarn install
4 yarn develop

### Expected behavior

open admin panel

### Screenshots

<details>
    <summary>Error script</summary>
$ strapi develop
Building your admin UI with development configuration ...

```
● Webpack █████████████████████████ building (11%) 0/1 entries 739/803 dependencies 148/364 modu
les 98 active
 ../../node_modules/inherits/inherits_browser.js

ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/helper-plugin' in '/Users/matsubara_d/Desktop/strapi/packages/core/email/admin/src'
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/Compilation.js:1765:28
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /Users/matsubara_d/Desktop/strapi/node_modules/neo-async/async.js:6883:13
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/helper-plugin' in '/Users/matsubara_d/Desktop/strapi/packages/core/email/admin/src'
  Parsed request is a module
  using description file: /Users/matsubara_d/Desktop/strapi/packages/core/email/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/matsubara_d/Desktop/strapi/packages/core/email/admin/src/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/core/email/admin/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/core/email/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/core/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/node_modules doesn't exist or is not a directory
      looking for modules in /Users/matsubara_d/Desktop/strapi/node_modules
        single file module
          using description file: /Users/matsubara_d/Desktop/strapi/package.json (relative path: ./node_modules/@strapi/helper-plugin)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.react.js doesn't exist
        existing directory /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin
          using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: .)
            using description file: /Users/matsubara_d/Desktop/strapi/package.json (relative path: ./node_modules/@strapi/helper-plugin)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin is not a file
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.react.js doesn't exist
              as directory
                existing directory /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin
                  using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: .)
                    use ./build/index.js from main in package.json
                      using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: ./build/index.js)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js.js doesn't exist
                        .jsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js.jsx doesn't exist
                        .react.js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js.react.js doesn't exist
                        as directory
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js doesn't exist
                    using path: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index
                      using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: ./index)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index.js doesn't exist
                        .jsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index.jsx doesn't exist
                        .react.js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index.react.js doesn't exist
      /Users/matsubara_d/Desktop/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/helper-plugin' in '/Users/matsubara_d/Desktop/strapi/packages/core/email/admin/src'
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/Compilation.js:1765:28
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /Users/matsubara_d/Desktop/strapi/node_modules/neo-async/async.js:6883:13
    at /Users/matsubara_d/Desktop/strapi/packages/core/admin/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/matsubara_d/Desktop/strapi/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/helper-plugin' in '/Users/matsubara_d/Desktop/strapi/packages/core/email/admin/src'
  Parsed request is a module
  using description file: /Users/matsubara_d/Desktop/strapi/packages/core/email/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/matsubara_d/Desktop/strapi/packages/core/email/admin/src/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/core/email/admin/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/core/email/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/core/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/Desktop/strapi/packages/node_modules doesn't exist or is not a directory
      looking for modules in /Users/matsubara_d/Desktop/strapi/node_modules
        single file module
          using description file: /Users/matsubara_d/Desktop/strapi/package.json (relative path: ./node_modules/@strapi/helper-plugin)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.react.js doesn't exist
        existing directory /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin
          using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: .)
            using description file: /Users/matsubara_d/Desktop/strapi/package.json (relative path: ./node_modules/@strapi/helper-plugin)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin is not a file
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin.react.js doesn't exist
              as directory
                existing directory /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin
                  using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: .)
                    use ./build/index.js from main in package.json
                      using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: ./build/index.js)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js.js doesn't exist
                        .jsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js.jsx doesn't exist
                        .react.js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js.react.js doesn't exist
                        as directory
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/build/index.js doesn't exist
                    using path: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index
                      using description file: /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/package.json (relative path: ./index)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index.js doesn't exist
                        .jsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index.jsx doesn't exist
                        .react.js
                          Field 'browser' doesn't contain a valid alias configuration
                          /Users/matsubara_d/Desktop/strapi/node_modules/@strapi/helper-plugin/index.react.js doesn't exist
      /Users/matsubara_d/Desktop/node_modules doesn't exist or is not a directory
      /Users/matsubara_d/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 1.
```
</details>

### System

- Node.js version:  nodebrew v16.0.0
- NPM version: 7.10.0
- Strapi version: master
- Database:
- Operating system: Mac Big Sur 11.5.2

**Comment by soupette** [comment]
Hello @matsubaraDaisuke in order to make the getstarted app to work you need to follow the [CONTRIBUTING GUIDE](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) .

Here is a quick recap:

1. fork the repository and clone it locally
2. run the following command:

```bash
cd strapi

yarn setup
```

3. Once all the dependencies are installed open a new terminal window and run the following

```bash
cd examples/getstarted 

yarn develop
```

And go to http://localhost:1337/admin

4. (Optional) if you want to make modification to the admin panel open another terminal window

```bash
cd packages/core/admin

yarn develop
```

Go to  http://localhost:4000/admin

I am closing this issue feel free to reopen it.
