### ISSUE TITLE
Dialect error when migrating to v4 from v3

### ISSUE THREAD

**Issue by LilyLauben** [strapi/strapi#12117]
### Describe the bug

Hello, I have a strapi instance running on a server that I was trying to upgrade to v4 from v3 (specifically I believe it was 3.4.0). I was able to install the new packages and rebuild the admin panel successfully, but upon running `npm run develop`, I initially got an error that the the `./scr` folder was missing. I created a `./src` folder, ran `develop` and then I got an error that the `./src/api` folder was missing. I created this folder, run `develop` a third time, and receive the following error:

```
[2022-01-05 23:32:01.186] error: Unknown dialect undefined
Error: Unknown dialect undefined
    at getDialectClass (/srv/strapi/strapi-development/node_modules/@strapi/database/lib/dialects/index.js:12:13)
    at getDialect (/srv/strapi/strapi-development/node_modules/@strapi/database/lib/dialects/index.js:19:23)
    at new Database (/srv/strapi/strapi-development/node_modules/@strapi/database/lib/index.js:38:20)
    at Function.Database.init (/srv/strapi/strapi-development/node_modules/@strapi/database/lib/index.js:84:33)
    at Strapi.bootstrap (/srv/strapi/strapi-development/node_modules/@strapi/strapi/lib/Strapi.js:347:30)
    at Strapi.load (/srv/strapi/strapi-development/node_modules/@strapi/strapi/lib/Strapi.js:410:16)
    at async Strapi.start (/srv/strapi/strapi-development/node_modules/@strapi/strapi/lib/Strapi.js:161:9)
```

I have a suspicion that my folder structure is not correct, since it is still using the v3 folder structure, but without a migration guide I have no idea what strapi is looking for and what is going wrong.

My current folder structure is:
```
/srv/strapi/strapi-development
  ├─ .cache/
  ├─ api/
  ├─ build/
  ├─ components/
  ├─ config/
  ├─ extensions/
  ├─ node_modules/
  ├─ package.json/
  ├─ plugins/
  ├─ public/
```
Plus an empty `/srv/strapi/strapi-development/src/api` folder that I created myself.

### System

- Node.js version: 14.18.0
- NPM version: 6.14.15
- Strapi version: v4 (from v3)
- Database: PostgresQL
- Operating system:

### Additional context

I am not sure if it is relevant, but this strapi instance has a fair amount of content types defined and content entered into it already before the migration process was begun.

**Comment by kasonde** [comment]
Hi @LilyLauben we currently do not have a migration guide for projects attempting to move from v4 to v3 (or vice-versa). The development of such a guide is one of our focuses for Q1 2022. v4 Introduced a lot of breaking changes not limited to just the folder structure or DB Schema. Because of that, we are working on a guide that takes all important changes into account.

**Comment by derrickmehaffy** [comment]
Marking as closed for now as we don't support migrations from v3 to v4 until the migration guide is published this quarter.

When we release it we will let everyone know.
