### ISSUE TITLE
Strapi v4: Error: write EPIPE 

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#12184]
### Describe the bug

There is an error at the moment of stopping the server.

### Steps to reproduce the behavior

1. Start the Strapi server.
2. Stop it with Ctrl + C
3. See the error 

### Expected behavior

No error at ending process.

### Screenshots

<img width="1387" alt="strapi4-error-19 51 29" src="https://user-images.githubusercontent.com/1038168/149185444-2dab6ba4-5ef1-42b8-9013-6d935588b3a9.png">

### Code snippets

```
[2022-01-12 19:34:22.224] http: POST /graphql (7 ms) 200
^C
Error: write EPIPE                                                                                                                        
    at process.target._send (internal/child_process.js:839:20)
    at process.target.send (internal/child_process.js:710:19)
    at sendHelper (internal/cluster/utils.js:27:15)
    at send (internal/cluster/child.js:199:10)
    at Object.close (internal/cluster/child.js:158:5)
    at Server.close (net.js:1616:18)
    at /Users/teine/Development/traffic-exchange-media/strapi/node_modules/@strapi/strapi/lib/services/server/http-server.js:49:14
    at new Promise (<anonymous>)
    at Server.server.destroy (/Users/teine/Development/traffic-exchange-media/strapi/node_modules/@strapi/strapi/lib/services/server/http-server.js:48:12)
    at Object.destroy (/Users/teine/Development/traffic-exchange-media/strapi/node_modules/@strapi/strapi/lib/services/server/index.js:120:24)
    at Strapi.destroy (/Users/teine/Development/traffic-exchange-media/strapi/node_modules/@strapi/strapi/lib/Strapi.js:173:23)
    at process.terminateStrapi (/Users/teine/Development/traffic-exchange-media/strapi/node_modules/@strapi/strapi/lib/utils/signals.js:12:20)
    at process.emit (events.js:412:35)
    at process.emit (domain.js:470:12)
```

### System

- Node.js version: 14.17.5
- NPM version: 6.14.14
- Strapi version: 4.0.4 Community Edition
- Database: SQlite
- Operating system: MacOS

### Additional context

It's repeatable problem, but not in every case. I had it in Strapi 4.0.3 and have it now in 4.0.4.

**Comment by j0hn5on** [comment]
Is this issue resolved. Facing the same issue

**Comment by derrickmehaffy** [comment]
> Is this issue resolved. Facing the same issue

We were not able to reproduce, there wasn't enough information

**Comment by chemagares** [comment]
I had the same problem and I could solve it by changing node version to 16 (I was in version 20), removing node_modules and installing deps again.
