### ISSUE TITLE
Unable to show relation when route's authentication set to false

### ISSUE THREAD

**Issue by cheuksing** [strapi/strapi#12226]
### Describe the bug
When a route's authentication set to false, relation can not be populated, even if public role is allowed to access its data.

### Steps to reproduce the behavior

1. Allow Public role to access relevant content-type in Permission Plugin
2. Call API /api/{modelUids}?populate=*
3. None of the relation will be shown **if route's auth set to false**

### Expected behavior
The relation data will be populated.

### Code snippets

```javascript
// api/{modelUid}/route.js
module.exports = createCoreRouter(modelUid, {
  config: {
    find: {
      auth: false,
    },
    findOne: {
      auth: false,
    },
  },
});
```

```javascript
// api/{modelUid}/content-type/schema.json
{
  "kind": "collectionType",
  "collectionName": "post",
  "info": {
    "singularName": "post",
    "pluralName": "posts",
    "displayName": "Post",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string",
      "unique": true,
      "required": true
    },
    "authors": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::user.user",
      "mappedBy": "user"
    }
  }
}
```

### System

- Node.js version: v16 LTS
- NPM version: 7.2.1
- Strapi version: v4.0.4
- Database: sqlite
- Operating system: MacOS/Linux

**Comment by derrickmehaffy** [comment]
Tested on v4.0.6 with find permission enabled on users-permissions

![image](https://user-images.githubusercontent.com/8593673/152051133-4f1bccb6-42b3-441d-9588-7e45ac4b9619.png)

Normal route setting:
![image](https://user-images.githubusercontent.com/8593673/152051198-783a2333-9e95-4a04-91bc-96fda4964e91.png)

With auth disabled:
![image](https://user-images.githubusercontent.com/8593673/152051215-3c0774b8-df48-451d-b16b-1d12e12964af.png)

**Comment by findridoy** [comment]
Anything on that?

**Comment by wscourge** [comment]
While trying to understand this problem I found the badly designed catch-all code here: _node_modules/@strapi/utils/lib/sanitize/visitors/remove-restricted-relations.js_, in the `hasAccessToSomeScopes` function:

```
const hasAccessToSomeScopes = async (scopes, auth) => {
  for (const scope of scopes) {
    try {
      await strapi.auth.verify(auth, { scope });
      return true;
    } catch {
      continue;
    }
  }

  return false;
};
```
The idea was to catch the specific exceptions thrown by `strapi.auth.verify`, yet in this particular case it silently fails with the more generic `TypeError`, the result of `auth` being assigned the default `{}` value.

My suggestion is to, while fixing this bug, follow [this guidelines](https://stackoverflow.com/a/1433608/6439240) on handling the specific exceptions instead. In this case:

```
const hasAccessToSomeScopes = async (scopes, auth) => {
  for (const scope of scopes) {
    try {
      await strapi.auth.verify(auth, { scope });
      return true;
    } catch (exception) {
      if (exception instanceof UnauthorizedError || exception instanceof ForbiddenError) {
        continue
       } else {
         throw exception;
       }
    }
  }

  return false;
};
```

Keep up the good work.

**Comment by derrickmehaffy** [comment]
Something I noticed when I was playing with API keys last week is that trying to use `populate=*` doesn't work with read-only API keys (works fine with read-write) and I'm wondering if the same is true here. @wscourge can you try populating something specific (I don't have the ability to spin a test project up right this second) with auth disabled and see if you hit the same thing?

**Comment by timur-khakhalev** [comment]
Any updates? Its same for me.
I trying to create a new entry with some relations and with custom routes:

`{
      method: 'POST',
      path: '/sp',
      handler: 'sprite.create'
    },`

Its work good. But If I set 
`config: {
auth: false
}
`
its not working. I just need to use no auth endpoints with custom handler. Any ideas?

**Comment by derrickmehaffy** [comment]
> config: { auth: false }

If you have this set then you shouldn't be passing any auth header at all. This disables all authentication checking.

**Comment by mohammed7aafar** [comment]
**Solution**  is to remove route's **auth** parameter from **config** object.

removing it will activate strapi authentication system which is based on users-permissions-plugin and without it **relation population** won't work.

please see [Strapi documentation v4](https://docs.strapi.io/developer-docs/latest/development/backend-customization/routes.html#public-routes)  about **public routes** for more information.

module.exports = {

      config: {
        auth: false,  // remove this
      }
   
` 

@timur-khakhalev @derrickmehaffy @wscourge @cheuksing @findridoy

**Comment by mohammed7aafar** [comment]
@derrickmehaffy 

in my case where I had custom router with a public route and custom function controller the population of relattion wasn't working unless I removed auth from config object.

I used 01-custom-route.js in routes folder to load my custom route. 
So you are right the best is @alexandrebodin or @Convly comment on this though.

**Comment by alsoamit** [comment]
In my case, when I use [populate deep plugin](https://market.strapi.io/plugins/strapi-plugin-populate-deep), media, component types and relations are all populated as usual. 

But when I use a public route with a custom controller, relations are not populated. 

On removing `auth: false`, I get Forbidden error as expected.

**Comment by Zielgestalt** [comment]
As workaround I overwrote the existing core controller. There I get the missing relation (location in my case)

```
async find(ctx) {
    const entries = await strapi.db.query('api::tgroup.tgroup').findMany({
      populate: ['location'],
    });
  
    return entries;
}
```

**Comment by jhoward1994** [comment]
Hi all, thanks for the detailed bug report. We will be scheduling work on this issue in an upcoming sprint 🙂

**Comment by AndColla** [comment]
Hi, is there any news about this issue?

**Comment by ifeltsweet** [comment]
> We will be scheduling work on this issue in an upcoming sprint

@jhoward1994 any update on this? We are facing this issue as well.

**Comment by Namstel** [comment]
Running into the same issue. Will write custom controllers to circumvent this for now.

**Comment by GregorSondermeier** [comment]
What's the use of disabling strapi's users-permission plugin for certain routes by providing `auth: false` with the route configuration, when in the end it's not competely disabled?

**Comment by trantuananh1** [comment]
I am also facing with this same issue

**Comment by GregorSondermeier** [comment]
I know now why this happens and can offer a workaround.

## First: Why does this happen?

Core Controllers that are created with the `createCoreController()` factory method use the `sanitizeOutput()` function (as seen [here](https://github.com/strapi/strapi/blob/develop/packages/core/strapi/src/core-api/controller/collection-type.ts#L30)).  
This function reads the auth token from the koa context and passes it to `sanitize.contentAPI.output()` (as seen [here](https://github.com/strapi/strapi/blob/develop/packages/core/strapi/src/core-api/controller/index.ts#L29)).  
And that function removes private feels as well as restricted relations (if `auth` is provided).

IMO `auth` should only be provided if it is not configured to `auth: false` and I guess that's the bug, however it might as well be possible it wouldn't fit strapi's bigger picture.

## Second: Here is my workaround:

I strictly want to avoid writing custom controllers or redundantly extending core controllers for multiple APIs. Also later middlewares as well as the frontend are dependant on that weird `{ data, meta }` structure that CoreControllers produce, which EntityService does not.  
So using Strapi's EntityService myself in multiple places is not an acceptable option for me.

Instead I created my own CoreController factory which opts out of query sanitization and uses a less restricted output sanitization (removing only private properties and not also restricted relations).

So:
No `this.validateQuery()`, no `validate.contentAPI.query()`.  
No `this.sanitizeQuery()`, no `sanitize.contentAPI.query()`.  
No `this.sanitizeOutput()`, instead `sanitize.contentApi.output()` (without `auth` param).

```js
// /src/utils/core-controller.js

const { createCoreController } = require('@strapi/strapi').factories;
const { sanitize } = require('@strapi/utils');

const createAuthFalseCapableCoreController = (contentTypeUid) =>
  createCoreController(contentTypeUid, ({ strapi }) => {
    const contentType = strapi.contentType(contentTypeUid);

    return {
      async find(ctx) {
        const routeConfig = ctx.state.route.config;

        if (routeConfig.auth === false) {
          const { results, pagination } = await strapi.service(contentTypeUid).find(ctx.query);
          const sanitizedResults = await sanitize.contentAPI.output(results, contentType);
          const transformedResponse = this.transformResponse(sanitizedResults, { pagination });

          return transformedResponse;
        }

        return super.find(ctx);
      },

      async findOne(ctx) {
        const routeConfig = ctx.state.route.config;

        if (routeConfig.auth === false) {
          const result = await strapi.service(contentTypeUid).findOne(ctx.query);
          const sanitizedResult = await sanitize.contentAPI.output(result, contentType);

          return sanitizedResult;
        }

        return super.findOne(ctx);
      },
    };
  });

module.exports = {
  createAuthFalseCapableCoreController,
};
```

This can then be used in my APIs:

```js
// /src/api/restaurant/controllers/restaurant.js

const { createAuthFalseCapableCoreController } = require('../../../utils/core-controller');

module.exports = createAuthFalseCapableCoreController('api::restaurant.restaurant');
```

**Comment by trantuananh1** [comment]
> I know now why this happens and can offer a workaround.
> 
> ## First: Why does this happen?
> Core Controllers that are created with the `createCoreController()` factory method use the `sanitizeOutput()` function (as seen [here](https://github.com/strapi/strapi/blob/develop/packages/core/strapi/src/core-api/controller/collection-type.ts#L30)). This function reads the auth token from the koa context and passes it to `sanitize.contentAPI.output()` (as seen [here](https://github.com/strapi/strapi/blob/develop/packages/core/strapi/src/core-api/controller/index.ts#L29)). And that function removes private feels as well as restricted relations (if `auth` is provided).
> 
> I got this from reading [Strapi's documentation on Controllers](https://docs.strapi.io/dev-docs/backend-customization/controllers), especially the part `// Method 3: Replacing a core action with proper sanitization`.
> 
> IMO `auth` should only be provided and considered for sanitzation if the matched route is not configured to `auth: false` and I guess _that's the bug_, however it might as well be possible it wouldn't fit strapi's bigger picture to add some `if`s here.
> 
> ## Second: Here is my workaround:
> I strictly want to avoid writing custom controllers or redundantly extending core controllers for multiple APIs. Also later middlewares as well as the frontend are dependant on that weird `{ data, meta }` structure that CoreControllers produce, which EntityService does not. So using Strapi's EntityService myself in multiple places is not an acceptable option for me.
> 
> Instead I created my own CoreController factory which opts out of query sanitization and uses a less restricted output sanitization (removing only private properties and not also restricted relations).
> 
> So: No `this.validateQuery()`, no `validate.contentAPI.query()`. No `this.sanitizeQuery()`, no `sanitize.contentAPI.query()`. No `this.sanitizeOutput()`, instead `sanitize.contentApi.output()` (without `auth` param).
> 
> ```js
> // /src/utils/core-controller.js
> 
> const { createCoreController } = require('@strapi/strapi').factories;
> const { sanitize } = require('@strapi/utils');
> 
> const createAuthFalseCapableCoreController = (contentTypeUid) =>
>   createCoreController(contentTypeUid, ({ strapi }) => {
>     const contentType = strapi.contentType(contentTypeUid);
> 
>     return {
>       async find(ctx) {
>         const routeConfig = ctx.state.route.config;
> 
>         if (routeConfig.auth === false) {
>           const { results, pagination } = await strapi.service(contentTypeUid).find(ctx.query);
>           const sanitizedResults = await sanitize.contentAPI.output(results, contentType);
> 
>           return this.transformResponse(sanitizedResults, { pagination });
>         }
> 
>         return super.find(ctx);
>       },
> 
>       async findOne(ctx) {
>         const routeConfig = ctx.state.route.config;
> 
>         if (routeConfig.auth === false) {
>           const result = await strapi.service(contentTypeUid).findOne(ctx.params.id, ctx.query);
>           const sanitizedResult = await sanitize.contentAPI.output(result, contentType);
> 
>           return this.transformResponse(sanitizedResult);
>         }
> 
>         return super.findOne(ctx);
>       },
>     };
>   });
> 
> module.exports = {
>   createAuthFalseCapableCoreController,
> };
> ```
> 
> This can then be used in my APIs:
> 
> ```js
> // /src/api/restaurant/controllers/restaurant.js
> 
> const { createAuthFalseCapableCoreController } = require('../../../utils/core-controller');
> 
> module.exports = createAuthFalseCapableCoreController('api::restaurant.restaurant');
> ```

after I inserted your code, I catched the error
` TypeError: createAuthFalseCapableCoreController is not a function                                                 │
│       at Object.<anonymous> (/media/anh/FS/Project/bv3-system/dist/src/api/task/controllers/task.js:8:19)           │
│       at Module._compile (node:internal/modules/cjs/loader:1233:14)                                                 │
│       at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)                                          │
│       at Module.load (node:internal/modules/cjs/loader:1091:32)                                                     │
│       at Module._load (node:internal/modules/cjs/loader:938:12)                                                     │
│       at Module.require (node:internal/modules/cjs/loader:1115:19)                                                  │
│       at require (node:internal/modules/helpers:130:18)                                                             │
│       at Module.importDefault (/media/anh/FS/Project/bv3-system/node_modules/@strapi/utils/dist/index.js:2914:15)   │
│       at loadFile (/media/anh/FS/Project/bv3-system/node_modules/@strapi/strapi/dist/core/loaders/apis.js:122:26)   │
│       at loadDir (/media/anh/FS/Project/bv3-system/node_modules/@strapi/strapi/dist/core/loaders/apis.js:114:38`

**Comment by GregorSondermeier** [comment]
> @GregorSondermeier after I inserted your code, I catched the error

Check your require path. Probably something wrong with it? `createAuthFalseCapableCoreController` is definitely a function.

**Comment by EwenQuim** [comment]
Any updates on this issue ? It doesn't seems a logical behaviour and can be tricky to guess the link between route authentication and populating fields.

@wscourge did a good work identifying the issue, it seems that we are near a solution !

Anyone motivated to work on a PR?

**Comment by GregorSondermeier** [comment]
Sure, closed as "completed".
You could at least be honest about why the issue has been closed, lol.

How is this handled in Strapi 5 btw?

**Comment by oiorain** [comment]
Hi @GregorSondermeier,

Thank you for your message.
We apologise if this comes across as being dishonest. This is the default status being applied when closing issues with a github actions. We will look into having a different status when closing stale issues. Thank you for the feedback.

We are looking to make our issue load more manageable so we can better address them. We suspect we have a lot of duplicate so we are closing older issues. If the issues exists in V5, we might have an open issue for it. Otherwise, you are more than welcome to open a new one for v5.

Since support for [v4 is winding down](https://github.com/strapi/strapi/issues/24240), our limited resources are dedicated to v5 development, v4 security issues and new features.

We appreciate your understanding, and we definitely don’t intend to give the impression of “pretending” issues are fixed. Your feedback helps us improve both our communication and issue handling process.

**Comment by GregorSondermeier** [comment]
Hi @oiorain!

It's perfectly fine and understandable to stop supporting the old Strapi v4 version and cleaning up the board. I probably would have forgotten about this issue anyway, had I not received an E-Mail notification about the status change.

My only problem was indeed about the honesty on the surface level. I remember being very very frustrated with Strapi about 2 years ago and I guess some of that frustration came back immediately when I saw one of the long long existing issues being closed as "completed". It's perfectly alright to close it as "not planned" or "outdated" or whatever fits the reason behind it :)
