### ISSUE TITLE
Strapi doesn't work with IPv6 addresses properly

### ISSUE THREAD

**Issue by mkg20001** [strapi/strapi#12285]
### Describe the bug

Using IPv6 address as server address makes things fail left and right

### Steps to reproduce the behavior

1. Edit 'config/server.js'
2. Set host to `::1`
3. `strapi develop` and `strapi develop --watch-admin`

strapi develop:
The message printed contains 
```
Welcome back!
To access the server ⚡️, go to:
http://::1:1337
```

`http://::1:1337` is an invalid address, it should be `http://[::1]:1337`

strapi develop --watch-admin:
It opens `http://localhost:8080/` which eventually loads only to give the error `Warning: An error occurred while requesting the API` (why is a fatal error a warning?)

It keeps loading ad-infinitum. 

Console shows
```
main.bundle.js:40325 DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at dispatchXhrRequest (http://localhost:8080/admin/main.bundle.js:36835:13)
    at new Promise (<anonymous>)
    at xhrAdapter (http://localhost:8080/admin/main.bundle.js:36806:10)
    at dispatchRequest (http://localhost:8080/admin/main.bundle.js:37600:10)
```

The URL it tries to load is `http://::1:1337/admin/project-type`. Again, improper IPv6 handling.

### Expected behavior

It just works with IPv6 addresses

### Screenshots

![image](https://user-images.githubusercontent.com/7735145/150779552-7437b462-9979-4d38-9108-5975b48a298d.png)

### Code snippets

this is a good stopgap, no idea if that's going to break at some edge case

```js
if (ip.indexOf(':') != -1) ip = `[${ip}]`
```

### System

- Node.js version: v17.3.0
- NPM version: 8.3.0
- Strapi version: 4.0.4
- Database: sqlite3
- Operating system: nixos 22.05beta

**Comment by derrickmehaffy** [comment]
> Node.js version: v17.3.0

While I don't think this will matter, can you please test on a valid supported version of node? We don't support Node 17 or any odd version.

**Comment by mkg20001** [comment]
v16.13.1, same errors

**Comment by mirkonasato** [comment]
Similarly, if you set `HOST=::` in `.env` then `strapi develop` or `strapi start` will print

```
Create your first administrator 💻 by going to the administration panel at:

┌──────────────────────┐
│ http://:::1337/admin │
└──────────────────────┘
```
which won't work.

`::` in IPv6 is like `0.0.0.0` in IPv4 and should probably be treated [in the same way](https://github.com/strapi/strapi/blob/v4.11.3/packages/core/utils/lib/config.js#L77).

**Comment by matthijsch** [comment]
We are currently using Strapi 4 with IPv6 by setting HOST=::, and it works perfectly. However, after upgrading to Strapi 5, this configuration no longer functions as expected. The following error is thrown
```
{
  code: 'ERR_INVALID_URL',
  input: 'http://:::1337/admin'
}
```

Is this issue still being tracked? Additionally, is there a known workaround for IPv6 with Strapi 5?

Thank you for your support!

**Comment by boiiiboi** [comment]
Any updates? We’d like to use it on Railway, which only supports IPv6.

**Comment by davimdantas** [comment]
> We are currently using Strapi 4 with IPv6 by setting HOST=::, and it works perfectly. However, after upgrading to Strapi 5, this configuration no longer functions as expected. The following error is thrown
> 
> ```
> {
>   code: 'ERR_INVALID_URL',
>   input: 'http://:::1337/admin'
> }
> ```
> 
> Is this issue still being tracked? Additionally, is there a known workaround for IPv6 with Strapi 5?

Exact the same thing here.

**Comment by derrickmehaffy** [comment]
Related ticket ID: 11511

**Comment by Plumillon** [comment]
> Any updates? We’d like to use it on Railway, which only supports IPv6.

I need ipv6 in the exact same usecase.
Railway internal network only work with ipv6 and setting the host to '::' fails to build.

**Comment by chsanch** [comment]
Hi, I also have this issue with Railway, any updates on this?

**Comment by Plumillon** [comment]
> Hi, I also have this issue with Railway, any updates on this?

One workaround is to wrap Strapi inside a Docker container and route all IPv6 to Strapi IPv4 internally via the nginx config.
I'll try this way.

**Comment by chsanch** [comment]
> > Hi, I also have this issue with Railway, any updates on this?
> 
> One workaround is to wrap Strapi inside a Docker container and route all IPv6 to Strapi IPv4 internally via the nginx config. I'll try this way.

If you manage to make it work, can you share the workaround? I will appreciate it 👍

**Comment by chsanch** [comment]
Just in case I have created a PR as an attempt to fix this #23212

**Comment by davimdantas** [comment]
As a temporary workaround Im using socat to forward pod's IPV6 requests to Strapi IPV4 server 

socat TCP6-LISTEN:1337,fork TCP4:127.0.0.1:1338 &

**Comment by derrickmehaffy** [comment]
Should be fixed in https://github.com/strapi/strapi/releases/tag/v5.12.5
