### ISSUE TITLE
Generated plugin breaks Strapi

### ISSUE THREAD

**Issue by Paratron** [strapi/strapi#12310]
## Bug report
I tried to create a new plugin using `strapi generate`. After enabling the freshly generated plugin without touching anything, the Strapi app cannot boot anymore.

The chosen plugin name is `t-finance`.

I created `/config/plugins.js` with this content:

```javascript
module.exports = ({ env }) => ({
    "t-finance": true
});
```

Starting the Strapi app in development mode results in this error:

```
> strapi develop

[2022-01-26 11:59:54.738] debug: ⛔️ Server wasn't able to start properly.
[2022-01-26 11:59:54.742] error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at join (node:path:429:7)
    at Object.loadPlugins ([snip]\node_modules\@strapi\strapi\lib\core\loaders\plugins\index.js:100:34)
    at async Strapi.loadPlugins ([snip]\node_modules\@strapi\strapi\lib\Strapi.js:279:5)
    at async Promise.all (index 1)
    at async Strapi.register ([snip]\node_modules\@strapi\strapi\lib\Strapi.js:311:5)
    at async Strapi.load ([snip]\node_modules\@strapi\strapi\lib\Strapi.js:409:5)
    at async Strapi.start ([snip]\node_modules\@strapi\strapi\lib\Strapi.js:161:9)

Process finished with exit code 1

```

### Steps to reproduce the behavior

1. Install Strapi
2. Call `strapi generate`
3. Choose "plugin"
4. Use the name "t-finance"
5. Enable the plugin
6. Try to boot

### Expected behavior

The app should boot.

### System

- Node.js version: 16.13.1
- NPM version: 8.3.0
- Strapi version: 4.0.2
- Database: SQLite
- Operating system: Windows 10

**Comment by Paratron** [comment]
Update:
The problem goes away when I not just enable the plugin but also provide its path in the config:

```javascript
module.exports = ({ env }) => ({
    "t-finance": {
        resolve: "./src/plugins/t-finance"
    }
});
```

Reading the docs, this should not be necessary, tough.

**Comment by Paratron** [comment]
Thanks, that bent my mind a bit! <3
