### ISSUE TITLE
foreign key index names too long for mariadb (MySQL has same limits)

### ISSUE THREAD

**Issue by bline** [strapi/strapi#12339]
### Describe the bug

Using a relation in a component which is then placed in a dynamic zone can create invalid indexes in mariadb. The index names end up too long.

I tracked down the code that generates the indexes and foreignKey relations: node_modules/@strapi/database/lib/metadata/relations.js in function createJoinTable the index names and foreign key names are based on the join table names. No checks are done on the length of these. mariadb has a hard limit of 64 characters for most indentifiers. See https://mariadb.com/kb/en/identifier-names/

> Databases, tables, columns, indexes, constraints, stored routines, triggers, events, views, tablespaces, servers and log file groups have a maximum length of 64 characters.

for the mysql docs https://dev.mysql.com/doc/refman/5.6/en/identifier-length.html (64 limit as well)

I could not find any other references to these auto-generated names in strapi code which leads me to believe these names could just be random strings. Aside from it not being pretty, is there any reason these can't be  something like `_.snakeCase(uuid.v4())`. I modified the code and changed the names to use just that and things seem to be working now. I'm not sure the snakeCase is needed there but all the examples in the docs seem to suggest it should use underscore.

### Steps to reproduce the behavior

1. Create a dynamic zone `componentSection` in a multi type content type.
2. Create a componentLayout multi type content type with a Dynamic zone which contains components that have relations.
3. If the auto-generated indexes are too long you will see the error pasted below.

### Expected behavior

index names should be generated within the specified 64 characters so relation nesting can happen.

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- yarn version: 1.22.17
- Strapi version: 4.0.5
- Database: mysql  Ver 15.1 Distrib 10.5.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.
- Operating system: Debian GNU/Linux 9 stretch

### Additional context

```
[2022-01-28 00:18:53.034] info: File changed: /home/scottbeck/Development/kcl_website/backend/src/components/sections/component-layout.json
[2022-01-28 00:18:53.034] http: POST /content-type-builder/components (114 ms) 201
[2022-01-28 00:18:53.036] info: The server is restarting

[2022-01-28 00:19:13.779] debug: ⛔️ Server wasn't able to start properly.
[2022-01-28 00:19:13.781] error: alter table `components_sections_component_layouts_component_layout_links` add index `components_sections_component_layouts_component_layout_links_inv_fk`(`inv_component_layout_id`) - ER_TOO_LONG_IDENT: Identifier name 'components_section
s_component_layouts_component_layout_links_inv_fk' is too long
Error: ER_TOO_LONG_IDENT: Identifier name 'components_sections_component_layouts_component_layout_links_inv_fk' is too long
    at Query.Sequence._packetToError (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    --------------------
    at Protocol._enqueue (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/scottbeck/Development/kcl_website/backend/node_modules/mysql/lib/Connection.js:198:25)
    at /home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/client.js:134:12)
    at /home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/execution/runner.js:241:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.ensureConnection (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/execution/runner.js:272:14)
    at async Runner.run (/home/scottbeck/Development/kcl_website/backend/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.createTable (/home/scottbeck/Development/kcl_website/backend/node_modules/@strapi/database/lib/schema/builder.js:246:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bline** [comment]
The work-around I've decided to go with on this is to just use shorter names.

**Comment by derrickmehaffy** [comment]
Confirmed, we need to apply the same length checking limits as we do for regular tables

**Comment by derrickmehaffy** [comment]
Closing in favor of tracking issue: https://github.com/strapi/strapi/issues/13117
