### ISSUE TITLE
After fresh install getting, Error: Cannot find module 'pluralize'

### ISSUE THREAD

**Issue by tomachinz** [strapi/strapi#1234]
node -v
v9.11.1
 npm -v
5.6.0

strapi -v
1.6.4

- **Database**: export MONGO_URL="mongodb://localhost:27017"

- **Operating system**: uname -a
Darwin 13inch 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64

**What is the current behavior?**

 npm install strapi -g
strapi login
...
 strapi new strapi.funk.nz
cd strapi.funk.nz
strapi start
strapi generate api car name:string year:integer license:string
strapi start

shows succesful install. then i edit and link to Studio....

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'pluralize'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/tom/Dropbox/Sites/strapi.funk.nz/api/user/services/user.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at /usr/local/lib/node_modules/strapi/node_modules/include-all/index.js:129:29
    at Array.forEach (<anonymous>)
    at requireAll (/usr/local/lib/node_modules/strapi/node_modules/include-all/index.js:44:9)
    at /usr/local/lib/node_modules/strapi/node_modules/include-all/index.js:54:23
    at Array.forEach (<anonymous>)
    at requireAll (/usr/local/lib/node_modules/strapi/node_modules/include-all/index.js:44:9)
    at /usr/local/lib/node_modules/strapi/node_modules/include-all/index.js:54:23
    at Array.forEach (<anonymous>)
    at requireAll (/usr/local/lib/node_modules/strapi/node_modules/include-all/index.js:44:9)
    at dictionary (/usr/local/lib/node_modules/strapi/util/dictionary.js:63:17)
[tom@13inch:~/Dropbox/Sites/strapi.funk.nz]

**Steps to reproduce the problem**
ah the steps are above thanks.

actually it happened after i added this config:

{
  "studio": {
    "enabled": true,
    "secretKey": "vzr237fZ9****************************Xvoc99g==",
    "appId": 7***
  }
}

**What is the expected behavior?**

not sure its such a new product :)
good work guys!

**Suggested solutions**
ill get back to you. 

---

- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @tomachinz , sadly we will not support for Strapi v1. Fill free to use `npm i strapi@alpha` version.

> Maybe don't use `.` in your project name
