### ISSUE TITLE
Can't Make API Requests | error: Module Did not self-register

### ISSUE THREAD

**Issue by selected-pixel-jameson** [strapi/strapi#12391]
### Describe the bug

I'm unable to make any API calls without getting  the below error message. 
```
/Users/xxxxxxxxxxxxx/node_modules/snappy/build/Release/binding.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at bindings (/Users/xxxxxxxxxxxxx/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/xxxxxxxxxxxxx/node_modules/snappy/snappy.js:2:34)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Object.require (internal/modules/cjs/helpers.js:101:18)
    at _optionalRequire (/Users/xxxxxxxxxxxxx/Documents/xxxxxxxxxxx/node_modules/mongodb/node_modules/optional-require/dist/index.js:111:65)
    at x (/Users/xxxxxxxxxxxxx/Documents/xxxxxxxxxxx/node_modules/mongodb/node_modules/optional-require/dist/index.js:172:16)
    at Object.retrieveSnappy (/Users/xxxxxxxxxxxxx/Documents/xxxxxxxxxxx/node_modules/mongodb/lib/core/connection/utils.js:49:18)
    at Object.<anonymous> (/Users/xxxxxxxxxxxxx/Documents/xxxxxxxxxxx/node_modules/mongodb/lib/core/wireprotocol/compression.js:3:47)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
  ```

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest my-project --quickstart`
2. Make a Postman request to `/api/auth/local/register/`

### Expected behavior

I expect a user to get created and have a token returned. Instead the above error is shown in the console and a 500 internal error is returned in Postman.

### System

- Node.js version: v14.19
- NPM version:6.14.13
- Strapi version: 4.0.7
- Database: I've tried with Postgres and SQLLite
- Operating system: MacOS 11.6

### Additional context
I've read all the SO posts regarding this and I've deleted and reinstalled the node_modules file numerous times. I've created multiple Strapi Projects and the same things happens on all of them. 

The interesting part is that I setup one instance with a Dockerfile and deployed this instance to ElasticBeanstalk with a database connecting to an RDS instance. 

```
FROM strapi/base

WORKDIR /strapi-app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV development

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]
```

When I try to run the API commands on that instance they work without an issue.  I've exhausted all resources I can think of and I'm still unable to resolve this issue.

**Comment by selected-pixel-jameson** [comment]
Ok. I finally resolve this issue, but I'm not exactly sure why or how. These are the steps I took. 

I removed all other versions from NVM. 
`nvm list`
 - v14.19.0
 - system 
 
I also went out to nodejs.org and downloaded the latest package so my system is using v16.13.2.

Once again removed node_modules and reinstalled. Still the same problem.

I have this in my .bash_profile
```
###NVM CONFIG###
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  #This loads nvm bash_completion
```

I'm not sure why this fixed it finally but the last thing I did was actually go into the folder using Finder on MacOS and deleted the node_modules folder and the package.lock file. 

Then I ran `npm uninstall snappy -D` and for some reason this finally fixed the issue.
