### ISSUE TITLE
MySQL error when saving more than one Field to a Content Type

### ISSUE THREAD

**Issue by H-L** [strapi/strapi#1241]
- **Node.js version**: v10.0.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: MySQL
- **MySQL version**: 5.6.35
- **Operating system**: macOS Sierra 10.12.6

**What is the current behavior?**
Strapi throw an error when trying to save more than one Field to a content type. Then it throw this error :
```bash
(node:53920) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
(node:53920) UnhandledPromiseRejectionWarning: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `provider` ADD `secondField` int' at line 2
    at Query.Sequence._packetToError (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
    at Protocol._enqueue (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/mysql/lib/Connection.js:208:25)
    at /Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/knex/lib/dialects/mysql/index.js:161:18
From previous event:
    at Client_MySQL._query (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/knex/lib/dialects/mysql/index.js:155:12)
    at Client_MySQL.query (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/knex/lib/runner.js:155:36)
From previous event:
    at /Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/knex/lib/runner.js:61:21
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/knex/lib/runner.js:47:31)
    at Raw.Target.then (/Users/hadrienlepoutre/_Projects/_Dev/sites/lab/test/node_modules/knex/lib/interface.js:39:43)
(node:53920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-05-18T15:39:00.333Z] debug Server wasn't able to start properly.
(hook:bookshelf) takes too long to load
```
It works well if you add only one field and then save. The error appears only if there are more than one field added before saving the content type.

**Steps to reproduce the problem**
Just create a new content type and save it with at least one field. Then edit it and try to add more than one field to it. Then click the save button. It should throw the error.

**What is the expected behavior?**
When adding more than one field to a content type, and then save it, the content type is saved with the new fields and the MySQL DB is updated with the new columns in the corresponding table.

**Suggested solutions**
It might just be a bad behaviour in some loop in strapi-bookshelf. 

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@H-L when you created this, did you create the model with one field, save, then attempt to add a second field? If so you will have to manually drop the table in the database before strapi will start as it does not delete tables or columns when modifying the model. You read more about this discussion here: https://github.com/strapi/strapi/issues/1114

**Comment by H-L** [comment]
@derrickmehaffy yes it happens wether on creation or on editing the content type. It just throw the error no matter what, as long as there is more than one field.

**Comment by derrickmehaffy** [comment]
@H-L I'm wondering if its related to the model name. Can you try creating a new project and using a different name for the model to see if the same error happens?

**Comment by derrickmehaffy** [comment]
Also which version of MySQL are you using?

**Comment by derrickmehaffy** [comment]
`(hook:bookshelf) takes too long to load` this bit here is a known issue. You may need to modify the `config/hook.json` and increase that limit, I think the default is like 3000 milliseconds, try increasing that to say 10000 or 30000 (10 seconds or 30 seconds). In some cases, like my project I had to increase this to 60 seconds to ensure strapi starts.

**Comment by H-L** [comment]
@derrickmehaffy I just tried to reproduce the error on a new project.
The error does appear only when editing, not on creation.
Here are the logs of all my actions to test the error.
[strapi_testing_error_mysql.log](https://github.com/strapi/strapi/files/2022314/mysql_strapi_testing_error.log)

**Comment by H-L** [comment]
I'm using the **MySQL version:** 5.6.35

**Comment by derrickmehaffy** [comment]
@H-L yeah this seems like the table for this model isn't deleted. Basically what is going on is Strapi cannot (as of right now) add a new column into a table, in the issue I linked me and @Aurelsicoko were discussing possible solutions for this that would fit all of the databases (Mongo, MySQL, and Post). 

So if you want to edit a model as of right now, your best bet is to Edit the model in the content manager, and before you hit save go and drop the table for that model in the database, then hit save. Strapi will restart and create the new table.

1. Create Model `test`
2. Add field `teststring`
3. Save
  A. Server restarts successfully
5. Edit Model `test` and add field `testnumber`
6. Delete table in mysql `test`
7. Save
  A. Server restarts successfully

**Comment by derrickmehaffy** [comment]
It should be noted that of course dropping the table will delete the data, The alternative is to manually add the column into the table.

**Comment by H-L** [comment]
@derrickmehaffy Thank you for your time and explanations.
I let a few examples below, just for debugging later, even if it's not planned yet as said the issue [#1114](https://github.com/strapi/strapi/issues/1114) :

**Works**
1. Create Model `test`
2. Add field `teststring`
3. Save
    A. Server restarts successfully
4. Edit Model `test` and add field `testNumber`
5. Save
    A. Serve restarts successfully

**Works**
1. Create Model `test`
2. Add field `testString`
3. Add field `testText`
4. Save
    A. Server restarts successfully

**Does not work**
1. Create Model `test`
2. Add field `testString`
3. Save
    A. Server restarts successfully
4. Edit Model `test` 
5. Add `testNumber`
6. Add `testText`
7. Save
    B. Server fails with the error above.

**Comment by lauriejim** [comment]
@H-L Thank you for these details. Will be usefull to work on.
@derrickmehaffy Thank you for your tile on this issue. Appreciate !

But we are currently on another feature and bug fix. Since time is lacking on our side, feel free to investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
@lauriejim I think @Aurelsicoko is already working on the fix in the related issue.

**Comment by lauriejim** [comment]
Hello @H-L 

I reproduce exactly steps of your [comment](https://github.com/strapi/strapi/issues/1241#issuecomment-390768065) and I hasn't able to have your issue.

@derrickmehaffy are you able to reproduce this issue ?

**Comment by derrickmehaffy** [comment]
This was @Aurelsicoko thoughts on how to handle it:

> To resume our thoughts:
> 
> Adding a strict mode that will remove the table when a content-type is deleted or when a relationship changes between two models (especially in a many-to-many case because it creates a relational table). In my opinion, we shouldn't enable this mode by default.
> Quick vs safe migration mode:
> Quick mode will rename, drop columns and tables.
> Safe mode will do the same but it will also create a backup before starting the work. It will be slower but the developer will be able to rollback if the migration doesn't work as expected.
> Both proposals are complementaries. If the strict mode is activated, then you will have to choose between the quick or safe mode. If the strict mode is disabled, the quick or safe mode is useless because nothing will be deleted.

**Comment by lauriejim** [comment]
@derrickmehaffy In this case, it's not an update. @H-L get an error on just adding new fields.

**Comment by derrickmehaffy** [comment]
For testing I created the following model:

```
{
  "connection": "default",
  "collectionName": "testadds",
  "info": {
    "name": "testadd",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "teststring1": {
      "type": "string"
    },
    "testint1": {
      "type": "integer"
    },
    "testfloat1": {
      "type": "float"
    },
    "testdec": {
      "type": "decimal"
    },
    "testboolean1": {
      "type": "boolean"
    }
  }
}
```

I then saved the model and strapi restarted fine, I also confirmed it generated the table and columns in MySQL:
![image](https://user-images.githubusercontent.com/8593673/40735194-6a6505d4-63ef-11e8-982f-95ed3e996e04.png)

I then attempted to add a new string field:

```
{
  "connection": "default",
  "collectionName": "testadds",
  "info": {
    "name": "testadd",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "teststring1": {
      "type": "string"
    },
    "testint1": {
      "type": "integer"
    },
    "testfloat1": {
      "type": "float"
    },
    "testdec": {
      "type": "decimal"
    },
    "testboolean1": {
      "type": "boolean"
    },
    "teststring2": {
      "type": "string"
    }
  }
}
```

Saved and strapi restarted fine, confirmed in the database that the new column was added:
![image](https://user-images.githubusercontent.com/8593673/40735324-c4cac45a-63ef-11e8-9954-90fd22f272e3.png)

**Comment by derrickmehaffy** [comment]
When attempting to edit the new `teststring2` field and change it to `teststring2edit` the server restarted fine however a duplicate entry was added to the database:

![image](https://user-images.githubusercontent.com/8593673/40735456-13e2bafc-63f0-11e8-8819-8f40b7b813bd.png)

**Comment by derrickmehaffy** [comment]
Attempting to add multiple fields fails, below is the model config and the error:

```
{
  "connection": "default",
  "collectionName": "testadds",
  "info": {
    "name": "testadd",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "teststring1": {
      "type": "string"
    },
    "testint1": {
      "type": "integer"
    },
    "testfloat1": {
      "type": "float"
    },
    "testdec": {
      "type": "decimal"
    },
    "testboolean1": {
      "type": "boolean"
    },
    "teststring2edit": {
      "type": "string"
    },
    "teststring3": {
      "type": "string"
    },
    "testint2": {
      "type": "integer"
    },
    "testfloat2": {
      "type": "float"
    },
    "testboolean2": {
      "type": "boolean"
    }
  }
}
```

Error: ```
[2018-05-30T17:03:06.375Z] debug PUT /content-type-builder/models/testadd (25 ms)
[2018-05-30T17:03:06.375Z] info The server is restarting

(node:11263) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
(node:11263) UnhandledPromiseRejectionWarning: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ALTER TABLE `testadds` ADD `testint2` int;
ALTER TABLE `testadds` ADD `testfloa' at line 2
    at Query.Sequence._packetToError (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/strapitest/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/strapitest/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
    at Protocol._enqueue (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/root/strapitest/node_modules/mysql/lib/Connection.js:208:25)
    at /root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:161:18
From previous event:
    at Client_MySQL._query (/root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:155:12)
    at Client_MySQL.query (/root/strapitest/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/root/strapitest/node_modules/knex/lib/runner.js:155:36)
From previous event:
    at /root/strapitest/node_modules/knex/lib/runner.js:61:21
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/root/strapitest/node_modules/knex/lib/runner.js:47:31)
    at Raw.Target.then (/root/strapitest/node_modules/knex/lib/interface.js:39:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11263) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
[2018-05-30T17:04:08.736Z] debug Server wasn't able to start properly.
(hook:bookshelf) takes too long to load
```

**Comment by derrickmehaffy** [comment]
To me it looks like the `ALTER TABLE` command is being cut off or mal-formatted

**Comment by derrickmehaffy** [comment]
Adding single fields works fine, adding any more than 1 will result in either this error or bookshelf stalls and fails to restart.

**Comment by lauriejim** [comment]
@derrickmehaffy Thank you for this investigation. I will try to reproduce.
