### ISSUE TITLE
 Strapi restart failed after creating new relation

### ISSUE THREAD

**Issue by gertmulder** [strapi/strapi#12448]
## Bug report

Strapi crashes after adding a new relation to one of the collection types with the following error

```
Error: ER_DROP_INDEX_FK: Cannot drop index 'someCollectionType_anotherCollectionType_links_inv_fk': needed in a foreign key constraint
```

### Describe the bug

After changing the relations between two collections types Strapi does not startup again, but crashes. 

Possibly this had something to do with the User collection type. What I did was:
1. Create a connection between a collection type Author with the User collection type, so I could add additional information and a bio for some users.
2. Then I created another connection between the newly created Author collection type with a Blog collection type, where I allow every blog to have multiple authors and the other way around. (many to many)
3. After hitting the save button Strapi does not restart but crashes.

### System

- Node.js version: 14.19.0
- NPM version: 6.14.16
- Strapi version: 4.0.7
- Database: MySQL
- Operating system: Ubuntu 20.04

**Comment by gertmulder** [comment]
After removing the relations to User from the schema.json file Strapi is able to start again. Maybe certain actions on the User data in MySQL to create relations are not allowed?

**Comment by Keith-Hon** [comment]
I have the same issue

System
Node.js version: 14.18.3
NPM version: 6.14.15
Strapi version: 4.0.5
Database: MySQL
Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Can you provide some information on what you did to produce this error?

**Comment by Manthanjain** [comment]
@gertmulder, can you provide more details on how did you produce the issue. I tried to reproduce the issue by mimicking the above steps it just took a while to save the details (but this also happened only once and it worked completely fine for rest of the steps)but it did not crash.

**Comment by derrickmehaffy** [comment]
> @gertmulder, can you provide more details on how did you produce the issue. I tried to reproduce the issue by mimicking the above steps it just took a while to save the details (but this also happened only once and it worked completely fine for rest of the steps)but it did not crash.

I mean exact steps to reproduce the issue, what were the names used for things, ect

**Comment by gertmulder** [comment]
Today I ran into a similar issue, which gives a bit more information I think.

Within a single/collection type I tried to delete a relation that was part of a component, which gave me the same error again.

So.
1. Create component with many to many relation
2. Create collection type that includes this component along with other fields
3. Try to delete the relation in the component when the collection type is opened in the content type builder

**Comment by derrickmehaffy** [comment]
> Today I ran into the same issue again, which gives a bit more information I think.
> 
> Within a single/collection type I tried to delete a relation that was part of a component, which gave me the same error again.
> 
> So.
> 
> 1. Create component with many to many relation
> 2. Create collection type that includes this component along with other fields
> 3. Try to delete the relation in the component when the collection type is opened in the content type builder
> 
> Strapi tries to restart but crashes.
> 
> Further error information: `Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting. at Query.Sequence._packetToError (/home/gertmulder/partpetuum.nl/strapi-partpetuum.nl/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14) at Query.ErrorPacket (/home/gertmulder/partpetuum.nl/strapi-partpetuum.nl/node_modules/mysql/lib/protocol/sequences/Query.js:79:18) at Protocol._parsePacket (/home/gertmulder/partpetuum.nl/strapi-partpetuum.nl/node_modules/mysql/lib/protocol/Protocol.js:291:23) at Parser._parsePacket (/home/gertmulder/partpetuum.nl/strapi-partpetuum.nl/node_modules/mysql/lib/protocol/Parser.js:433:10) at Parser.write (/home/gertmulder/partpetuum.nl/strapi-partpetuum.nl/node_modules/mysql/lib/protocol/Parser.js:43:10) at Protocol.write (/home/gertmulder/partpetuum.nl/strapi-partpetuum.nl/node_modules/mysql/lib/protocol/Protocol.js:38:16) at TLSSocket.ondata (internal/streams/readable.js:731:22) at TLSSocket.emit (events.js:400:28) at TLSSocket.emit (domain.js:475:12) at addChunk (internal/streams/readable.js:293:12) at readableAddChunk (internal/streams/readable.js:267:9) at TLSSocket.Readable.push (internal/streams/readable.js:206:10) at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

Your issue is this one: https://github.com/strapi/strapi/issues/11723
