### ISSUE TITLE
Bypassing role security in GraphQL

### ISSUE THREAD

**Issue by raulriera** [strapi/strapi#1247]
**Informations**
- **Node.js version**:
- **npm version**:
- **Strapi version**:
- **Database**:
- **Operating system**:

**What is the current behavior?**
It seems that when passing several queries its possible to bypass the security specified by roles and permissions. For the users endpoint, the user shouldn't be allowed to query anything as specific in the admin

<img width="588" alt="screen shot 2018-05-21 at 1 13 58 pm" src="https://user-images.githubusercontent.com/24159/40320223-dec1ff70-5cf8-11e8-8d8d-fdee42fd5bb0.png">

Yet, making another valid query after the prohibited one seems to return value from the previous one and then error on GraphQL.js but still return the unauthorized information back to the client 

**Steps to reproduce the problem**

Query the users list, the following query

```graphql
query {
  users {
    username
  }
}
```

Will return

```shell
Mongoose: users-permissions_user.findOne({ _id: ObjectId("5aee1e6b7ae7d334d9247e79") }, { fields: {} })
collection.js:188
Mongoose: users-permissions_role.find({ _id: { '$in': [ ObjectId("5aedd8b3e235fa32d54c7b63") ] } }, { fields: {} })
collection.js:188
Mongoose: appointment.find({ staff: { '$in': [ ObjectId("5aee1e6b7ae7d334d9247e79") ] } }, { fields: {} })
collection.js:188
Mongoose: practice.find({ _id: { '$in': [ ObjectId("5aef661dca53d04354a36adc") ] } }, { fields: {} })
collection.js:188
Mongoose: users-permissions_permission.findOne({ role: ObjectId("5aedd8b3e235fa32d54c7b63"), type: 'users-permissions', controller: 'user', action: 'find', enabled: true }, { fields: {} })
collection.js:188
Error: Forbidden
```

Which is the expected behaviour, but adding unto the query like this (something I do have access to

```graphql
query {
  users {
    username
  }  

  # Including this query will result in the previous
  # query actually responding data, with the error on the right
  # I don't have access to the `users` endpoint tho
  # making this a potential security error
  practice(id:"5aef661dca53d04354a36adc") {
    name
    users {
      username
      practices {
        name
      }
    }
  }
}
```

```shell
Mongoose: users-permissions_user.findOne({ _id: ObjectId("5aee1e6b7ae7d334d9247e79") }, { fields: {} })
collection.js:188
Mongoose: users-permissions_user.findOne({ _id: ObjectId("5aee1e6b7ae7d334d9247e79") }, { fields: {} })
collection.js:188
Mongoose: users-permissions_role.find({ _id: { '$in': [ ObjectId("5aedd8b3e235fa32d54c7b63") ] } }, { fields: {} })
collection.js:188
Mongoose: appointment.find({ staff: { '$in': [ ObjectId("5aee1e6b7ae7d334d9247e79") ] } }, { fields: {} })
collection.js:188
Mongoose: practice.find({ _id: { '$in': [ ObjectId("5aef661dca53d04354a36adc") ] } }, { fields: {} })
collection.js:188
Mongoose: users-permissions_role.find({ _id: { '$in': [ ObjectId("5aedd8b3e235fa32d54c7b63") ] } }, { fields: {} })
collection.js:188
Mongoose: appointment.find({ staff: { '$in': [ ObjectId("5aee1e6b7ae7d334d9247e79") ] } }, { fields: {} })
collection.js:188
Mongoose: practice.find({ _id: { '$in': [ ObjectId("5aef661dca53d04354a36adc") ] } }, { fields: {} })
collection.js:188
Mongoose: users-permissions_permission.findOne({ role: ObjectId("5aedd8b3e235fa32d54c7b63"), type: 'application', controller: 'practice', action: 'findmine', enabled: true }, { fields: {} })
collection.js:188
Mongoose: users-permissions_permission.findOne({ role: ObjectId("5aedd8b3e235fa32d54c7b63"), type: 'application', controller: 'practice', action: 'findmine', enabled: true }, { fields: {} })
collection.js:188
Mongoose: practice.findOne({ _id: ObjectId("5aef661dca53d04354a36adc") }, { fields: {} })
collection.js:188
Mongoose: users-permissions_user.find({}, { limit: 100, skip: NaN, fields: {} })
collection.js:188
Mongoose: patient.find({ practice: { '$in': [ ObjectId("5aef661dca53d04354a36adc") ] } }, { fields: {} })
collection.js:188
Mongoose: users-permissions_user.find({ practices: { '$in': [ ObjectId("5aef661dca53d04354a36adc") ] } }, { fields: {} })
collection.js:188
Mongoose: users-permissions_user.find({ practices: { '$in': [ ObjectId("5aef661dca53d04354a36adc") ] } }, { fields: {} })
collection.js:188
Mongoose: users-permissions_role.find({ _id: { '$in': [ ObjectId("5aedd8b3e235fa32d54c7b63"), ObjectId("5aedd8b3e235fa32d54c7b62") ] } }, { fields: {} })
collection.js:188
Mongoose: appointment.find({ staff: { '$in': [ ObjectId("5aee1e6b7ae7d334d9247e79"), ObjectId("5b0243a3b0fd07556c0299d4") ] } }, { fields: {} })
collection.js:188
Mongoose: practice.find({ _id: { '$in': [ ObjectId("5aef661dca53d04354a36adc"), ObjectId("5aef71ee9c03be4598a2ab53") ] } }, { fields: {} })
collection.js:188
TypeError: Cannot read property 'map' of undefined
runQuery.ts:83
    at users (/Users/raulriera/Desktop/odontome/plugins/graphql/services/GraphQL.js:565:61)
    at resolveFieldValueOrError (/Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:531:18)
    at resolveField (/Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:495:16)
    at /Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:772:10)
    at completeObjectValue (/Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:762:10)
    at completeValue (/Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:660:12)
    at /Users/raulriera/Desktop/odontome/plugins/graphql/node_modules/graphql/execution/execute.js:617:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

The "scary part" is that the values of the first query are returned

<img width="1327" alt="screen shot 2018-05-21 at 1 18 46 pm" src="https://user-images.githubusercontent.com/24159/40320384-8765cf4e-5cf9-11e8-8451-cc6f7d718ff7.png">

**What is the expected behavior?**
It should fail on the first query and succeed on the last one, at the moment is doing the opposite.

**Suggested solutions**
Sadly, I don't know

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@lauriejim ^^

**Comment by lauriejim** [comment]
Hello @raulriera, thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature and bug fix. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate your contribution on this issue! 

I know it's will be hard to investigate, but 💪 !

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by Aurelsicoko** [comment]
@derrickmehaffy Not a big deal to fix this one. We don't have time but this security pattern has been handled during the development phase.

**Comment by derrickmehaffy** [comment]
Noted @Aurelsicoko just wanted to make sure this wasn't a critical security issue. 😛

**Comment by avirankatzsofi** [comment]
I'm experiencing the same issue with updateUser mutation in version beta.15.
Here are my public role configurations for users-permissions:
![image](https://user-images.githubusercontent.com/42338902/64584214-8e767e80-d39c-11e9-8c72-39f12dd176b1.png)
However, updateUser mutation works:
![image](https://user-images.githubusercontent.com/42338902/64584292-cb427580-d39c-11e9-85d3-a9c1eb4e94f1.png)
