### ISSUE TITLE
"duplicate key value violates unique constraint" error when adding a new field

### ISSUE THREAD

**Issue by gvocale** [strapi/strapi#12493]
### Describe the bug

Sometimes, when adding a new field to a component, the following error appears.

### Steps to reproduce the behavior

1. I add a field to a short text field to a component
2. Push save
3. See error

I have tried deleting the created field, running `rm -rf .cache` and `yarn dev` again, but the error keeps happening and can't start `yarn dev` successfully.

Finally closing and reopening terminal, running `yarn dev` again, fixed it. Although adding again the field `textColor` reproduce again the issue.

### Screenshots

<img width="1618" alt="Screen Shot 2022-02-11 at 11 15 17 AM" src="https://user-images.githubusercontent.com/1319291/153627760-577e2ab6-9278-4767-a30c-47411b2d23ef.png">

### Code snippets

Error
```js
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    'plugin::content-manager.explorer.update',
    '[]',
    2022-02-11T16:12:20.526Z,
    '{"fields":["title","slug","wpDatabaseId","type","featuredImage","description","excerpt","expertise","logo","makers","makersList","products","events","exhibits","addresses.address1","addresses.address2","addresses.city","addresses.name","addresses.state","addresses.postcode","addresses.country","addresses.phone","links.website","links.instagramHandle","rows","hero.title","hero.logo","hero.image","hero.backgroundColor","hero.matterport.image","hero.matterport.matterTag","hero.matterport.modelId"]}',
    'api::gallery.gallery',
    2022-02-11T16:12:20.526Z
  ],
  __knexQueryUid: 'P3aBnXksM5ayxxL5WG2JZ',
  sql: 'insert into "admin_permissions" ("action", "conditions", "created_at", "properties", "subject", "updated_at") values (?, ?, ?, ?, ?, ?) returning "id"',
  returning: 'id'
}
[2022-02-11 11:12:20.529] debug: ⛔️ Server wasn't able to start properly.
[2022-02-11 11:12:20.529] error: insert into "admin_permissions" ("action", "conditions", "created_at", "properties", "subject", "updated_at") values ($1, $2, $3, $4, $5, $6) returning "id" - duplicate key value violates unique constraint "admin_permissions_pkey"
error: insert into "admin_permissions" ("action", "conditions", "created_at", "properties", "subject", "updated_at") values ($1, $2, $3, $4, $5, $6) returning "id" - duplicate key value violates unique constraint "admin_permissions_pkey"
    at Parser.parseErrorMessage (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
```

### System

- Node.js version: v16.6.0
- NPM version: 7.19.1
- Strapi version: 4.0.7
- Database: Postgres
- Operating system: MacOs

**Comment by derrickmehaffy** [comment]
What version of PostgreSQL are you using as this seems kinda related to https://github.com/strapi/strapi/issues/11723

**Comment by gvocale** [comment]
I'm using `postgres (PostgreSQL) 14.1`

**Comment by gvocale** [comment]
Running in the same issue also when I try to change permission for public user on one single type:

```tsx
[2022-02-15 12:50:43.440] error: insert into "up_permissions" ("action", "created_at", "updated_at") values ($1, $2, $3) returning "id" - duplicate key value violates unique constraint "up_permissions_pkey"
error: insert into "up_permissions" ("action", "created_at", "updated_at") values ($1, $2, $3) returning "id" - duplicate key value violates unique constraint "up_permissions_pkey"
    at Parser.parseErrorMessage (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/gvocale/Sites/strapi/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
<img width="850" alt="Screen Shot 2022-02-15 at 12 51 42 PM" src="https://user-images.githubusercontent.com/1319291/154120062-87d4f5f8-c5ed-499e-bdb6-97d799f2a3bf.png">

**Comment by gvocale** [comment]
By the way just tried version Strapi 4.0.8 and the issue persists.

**Comment by gvocale** [comment]
@ibnlanre that helped! Thank you so much!

**Comment by derrickmehaffy** [comment]
Marking as closed as it was made clear this isn't a Strapi bug but a PostgreSQL issue on imports.

**Comment by Eli-Nathan** [comment]
@ibnlanre's [answer](https://github.com/strapi/strapi/issues/12493#issuecomment-1044724834) did the trick for me.
After trying to import some data, it hit a conflict and stopped the import leaving some IDs in a bad state in the DB.

I had to tweak it a bunch so if anyone is hitting repeated errors such as:
```
column "facilities" does not exist
```

Then try wrapping the table name in single quotes as well as doubles.

My table was called `facilities` and the column in question was `id` so my query had to be:
```
SELECT SETVAL((SELECT PG_GET_SERIAL_SEQUENCE('"facilities"', 'id')), (SELECT MAX(id) FROM facilities) + 1, FALSE);
```

**Comment by rokal** [comment]
@Eli-Nathan I got the same error and it seems that the fix is updating the table sequence.
`alter sequence <sequence_table probably facilities_id_seq> restart with <the-max-value>;` fixed my issue.
You might want to look into your data to know what was the last id inserted.

**Comment by everythinginjs** [comment]
@ibnlanre Hey, I am wondering it is the same issue I am facing now, after 216 products imports using [import/export strapi plugin](https://github.com/Baboo7/strapi-plugin-import-export-entries). I should run the query you said after every mass imports!!! that would be so frustrating. does switching to MySQL fix the issue? thanks a lot for any response.
![26ba7266-4b02-4276-b11b-572c2b124bf8](https://user-images.githubusercontent.com/34276557/184539332-6bf5a1d3-df1e-4f79-9d8c-f41ea2a591d1.jpeg)
w

**Comment by hoang-innomizetech** [comment]
Not sure why we close this issue, but it seems this is an issue of the native Strapi entity service/query. After inserting the record with the id value into the database, it should automatically increase the sequence. It worked properly on the previous version, but after we upgrade to the latest version this issue is occurs. 

The code below is used to insert a new record into the database

`
// Actually create the entry in Strapi
await strapi.entityService.create(`api::${model}.${model}`, {
  data: entry,
});
`

Worked version: 3.6.8
The current version that not working: 4.11.1

**Comment by jakubjanousek** [comment]
We are also seeing this error on multiple tables, despite not doing any importing. After implementing the fix in the db it works for a bit but then the sequence gets out of sync again somehow

**Comment by IvoNet** [comment]
We see the same problem. For us this happens after we used a migration file to fill a table with initial data. Now we can edit existing items but not create new ones with exactly this the above problem.

**Comment by arashkevich25** [comment]
Yhe same issue during migration from v4.5.1 to v4.6.1

**Comment by IvoNet** [comment]
Please this issue is NOT resolved.

**Comment by mdxprograms** [comment]
@derrickmehaffy will this be merged in soon if it hasn't? I keep getting this after creating a new collection type locally and pushing to production. Granted I'm using sqliite locally and postgres in production (which is default).

**Comment by andreasaker** [comment]
@ibnlanre Thank you! 
Solved it for me, hope there is a way to fix it without meddling with postgresql in the future.

**Comment by donkeycomm** [comment]
This worked for me, but of course you empty the table completely;
TRUNCATE TABLE admin_permissions CASCADE;

**Comment by AlexisSniffer** [comment]
The id column has `nextval('products_id_seq'::regclass)` as default value, I corrected the error by looking for the maximum value `select max(id) from table
` and then setting the value with `SELECT setval('table_id_seq', <max_value>, true);
`

**Comment by oiorain** [comment]
Hi! 
This issue seems to be a dupplicate to an issue that was solved in the mean time so I am closing it. 
By all means let us know if that's not the case. 

Thank you!

**Comment by devrahulagarwal1990** [comment]
Hi,
Thanks for the information. due to this i am able to solve the issue by executing below query
SELECT SETVAL(
  (SELECT PG_GET_SERIAL_SEQUENCE('"admin_permissions_role_lnk"', 'id')),
  (SELECT COALESCE(MAX(id), 1) FROM "admin_permissions_role_lnk") + 1,
  FALSE
);
