### ISSUE TITLE
Creating a collection with a "key" field result : Warning:  An error occurred during models config fetch.

### ISSUE THREAD

**Issue by Kazdan1994** [strapi/strapi#12569]
## Bug report
Creating a collection with a "key" field result : Warning:  An error occurred during models config fetch.

### Describe the bug

Create a collection with a field type text | rich text | number | date | boolean | email | enumeration | json | uid, only relation and media fields works) whose name is "key".

Go to Content Manager and access to the collection. A 500 error and a message : "Warning: An error occurred during models config fetch."

#

### Steps to reproduce the behavior

1. Go to Content-Type Builder
2. Click on 'Create new collection type'
3. Set a name and click on Advanced settings
4. Select Enable localization for this Content-Type
5. Choose a field type text | rich text | number | date | boolean | email | enumeration | json | uid
6. Give the name key to your field
7. Save your collection
8. Go to Content Manager
9. Go to your collection
10. You will see an error message : "Warning: An error occurred during models config fetch."

### Expected behavior

I expected to fetch successfully my collection.

### Screenshots

![image](https://user-images.githubusercontent.com/11750263/154476641-10963586-309c-4e31-93f1-22856032cca2.png)

### Code snippets

`
error: Cannot read property 'attributes' of undefined
TypeError: Cannot read property 'attributes' of undefined
    at convertAndSanitizeFilters (/home/<user>/tests/strapi-translate/node_modules/@strapi/utils/lib/convert-query-params.js:253:41)
    at /home/<user>/tests/strapi-translate/node_modules/@strapi/utils/lib/convert-query-params.js:243:24
    at Array.map (<anonymous>)
    at convertAndSanitizeFilters (/home/<user>/tests/strapi-translate/node_modules/@strapi/utils/lib/convert-query-params.js:243:10)
    at convertAndSanitizeFilters (/home/<user>/tests/strapi-translate/node_modules/@strapi/utils/lib/convert-query-params.js:283:26)
    at convertFiltersQueryParams (/home/<user>/tests/strapi-translate/node_modules/@strapi/utils/lib/convert-query-params.js:231:10)
    at transformParamsToQuery (/home/<user>/tests/strapi-translate/node_modules/@strapi/strapi/lib/services/entity-service/params.js:35:19)
    at Object.findWithRelationCounts (/home/<user>/tests/strapi-translate/node_modules/@strapi/strapi/lib/services/entity-service/index.js:131:19)
    at async Object.findWithRelationCounts (/home/<user>/tests/strapi-translate/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
    at async Object.find (/home/<user>/tests/strapi-translate/node_modules/@strapi/plugin-content-manager/server/controllers/collection-types.js:25:37)
    at async returnBodyMiddleware (/home/<user>/tests/strapi-translate/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async module.exports (/home/<user>/tests/strapi-translate/node_modules/@strapi/plugin-content-manager/server/middlewares/routing.js:39:3)
    at async policiesMiddleware (/home/<user>/tests/strapi-translate/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/home/<user>/tests/strapi-translate/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/home/<user>/tests/strapi-translate/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/<user>/tests/strapi-translate/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
`

### System

- Node.js version: 14.18.3
- NPM version: 8.4.0
- Yarn version: 1.22.7
- Strapi version: 4.0.8
- Database: sqlite
- Operating system: linux Fedora 34 version 5.16.8-100.fc34.x86_64

**Comment by Kazdan1994** [comment]
Update.

I'm pretty sure the error comes to here:

file: packages/core/utils/lib/convert-query-params.js, line 253:41
![image](https://user-images.githubusercontent.com/11750263/154480960-6f62ede1-fe41-4647-87ca-e764b9803a94.png)

I think it's a conflict with the 'key'.

**Comment by tuxuuman** [comment]
I think that the problem is that a string "key" is used and not a variable.

![image](https://user-images.githubusercontent.com/17300270/154490284-78520911-9a5d-4067-939f-9530be9af9a3.png)

**Comment by Kazdan1994** [comment]
Hi and thank you for your feedback.

The optional chaining operator (?.) is not supported for Node version below 14.0.0, strapi can be used by  "node": ">=12.22.0 <=16.x.x" according to the "engines" specification in package.json. So we can't use it if we want to maintain compatibility with old node version. You can read the documentation below.

[[optional chaining operator (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#relationship_with_the_optional_chaining_operator_)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

Have a nice day !

**Comment by JonasJW** [comment]
Encountered the same issue, noteworthy is that this happens only when the collection has localization enabled

**Comment by dzcpy** [comment]
Same issue

**Comment by gu-stav** [comment]
Thanks again for your bug report. We believe the issue was fixed already in https://github.com/strapi/strapi/pull/12579. Therefore upgrading to the latest version of Strapiu should fix your problem.

In case it doesn't feel free to ping me and I'll re-open the issue.
