### ISSUE TITLE
Cannot upload image during entry creation

### ISSUE THREAD

**Issue by zeattacker** [strapi/strapi#12673]
### Describe the bug

Cannot upload image durint entry creation from REST API. The error is : 

```[2022-02-27 03:51:44.253] error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at join (node:path:1172:7)
    at optimize (/projects/node_modules/@strapi/plugin-upload/server/services/image-manipulation.js:93:22)
    at async Promise.all (index 0)
    at async Object.uploadToEntity (/projects/node_modules/@strapi/plugin-upload/server/services/upload.js:363:27)
    at async Promise.all (index 0)
    at async Object.module.exports (/projects/node_modules/@strapi/strapi/lib/services/utils/upload-files.js:78:3)

### Reproduce

```curl --request POST \
  --url http://localhost:1337/api/posts \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --form 'files.Image=@Screen Shot 2022-02-27 at 03.05.40.png' \
  --form 'data={"Title":"Lorem test","Content":"Lorem content","Date":"2022-02-27 08:00:00","Slug":"lorem-test"}'


Do any users face the same issue ? Thanks

**Comment by katyperrycbt** [comment]
Yes, I have the same issue. Guess I need to downgrade to 4.0.7 one.

**Comment by hopcycle** [comment]
Same problem here. I downgraded to 4.1.0 as @katyperrycbt said and it worked for me!

**Comment by petersg83** [comment]
Thank you, I could reproduce the bug. A fix is on its way!
