### ISSUE TITLE
Cannot edit permissions 'SELF_SIGNED_CERT_IN_CHAIN'

### ISSUE THREAD

**Issue by VonOx** [strapi/strapi#1272]
**Informations**
- **Node.js version**: 9.0.0
- **npm version**: 6.0.1
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: MariaDB
- **Operating system**: W10 1709

**What is the current behavior?**

I can't edit permission because of 
```
[2018-05-25T06:34:52.692Z] debug GET /users-permissions/routes (16 ms)
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1032:34)
    at emitNone (events.js:115:13)
    at TLSSocket.emit (events.js:218:7)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
[2018-05-25T06:34:53.067Z] debug GET /users-permissions/roles/3?lang=fr (391 ms)
```
![ui](https://user-images.githubusercontent.com/1528694/40530125-d6d5ac6a-5ff7-11e8-9c3c-5f7f5f5945df.png)

**Steps to reproduce the problem**

I'm behind corporate proxy but i dont understand why i have this error in localhost

**What is the expected behavior?**

Click and Edit what else 😀

**Suggested solutions**
😶

Thank you for your help

**Comment by lauriejim** [comment]
@VonOx can you provide all logs from your app start please.

**Comment by VonOx** [comment]
Of course:

```
[2018-06-06T06:52:04.728Z] info Server started in #################
[2018-06-06T06:52:04.731Z] info Your server is running at http://localhost:1337
[2018-06-06T06:52:04.732Z] debug Time: Wed Jun 06 2018 08:52:04 GMT+0200 (Paris, Madrid (heure d’été))
[2018-06-06T06:52:04.733Z] debug Launched in: 17327 ms
[2018-06-06T06:52:04.734Z] debug Environment: development
[2018-06-06T06:52:04.734Z] debug Process PID: 14912
[2018-06-06T06:52:04.736Z] debug Version: 3.0.0-alpha.12.2 (node v9.0.0)
[2018-06-06T06:52:04.737Z] info To shut down your server, press <CTRL> + C at any time
[2018-06-06T06:52:11.987Z] debug GET index.html (35 ms)
[2018-06-06T06:52:12.041Z] debug GET vendor.dll.js (10 ms)
[2018-06-06T06:52:12.043Z] debug GET main.js (7 ms)
[2018-06-06T06:52:12.373Z] debug GET plugins.json (8 ms)
[2018-06-06T06:52:12.472Z] debug GET 1.3abcde57a078e508705a.chunk.js (5 ms)
[2018-06-06T06:52:12.583Z] debug GET /admin/gaConfig (71 ms)
[2018-06-06T06:52:12.599Z] debug GET /admin/strapiVersion (4 ms)
[2018-06-06T06:52:12.601Z] debug GET bd03a2cc277bbbc338d464e679fe9942.woff2 (10 ms)
[2018-06-06T06:52:12.606Z] debug GET /admin/currentEnvironment (4 ms)
[2018-06-06T06:52:12.608Z] debug GET 3.e894045e5095eb1a314c.chunk.js (23 ms)
[2018-06-06T06:52:12.615Z] debug GET /admin/layout (5 ms)
[2018-06-06T06:52:12.629Z] debug GET 8b4f872c5de19974857328d06d3fe48f.woff2 (13 ms)
[2018-06-06T06:52:12.638Z] debug GET cccb897485813c7c256901dbca54ecf2.woff2 (16 ms)
[2018-06-06T06:52:12.658Z] debug GET main.js (27 ms)
[2018-06-06T06:52:12.662Z] debug GET main.js (21 ms)
[2018-06-06T06:52:12.664Z] debug GET main.js (17 ms)
[2018-06-06T06:52:12.666Z] debug GET main.js (14 ms)
[2018-06-06T06:52:12.682Z] debug GET main.js (13 ms)
[2018-06-06T06:52:12.721Z] debug GET /favicon.ico (3 ms)
[2018-06-06T06:52:13.028Z] debug GET /settings-manager/autoReload (18 ms)
[2018-06-06T06:52:13.266Z] debug GET /content-type-builder/autoReload (13 ms)
[2018-06-06T06:52:13.379Z] debug GET /users-permissions/init (20 ms)
[2018-06-06T06:52:13.525Z] debug GET af7ae505a9eed503f8b8e6982036873e.woff2 (12 ms)
[2018-06-06T06:52:13.527Z] debug GET 33d5f0d956f3fc30bc51f81047a2c47d.woff2 (9 ms)
[2018-06-06T06:52:13.529Z] debug GET 2ff0049a00e47b56bffc059daf9be78b.png (28 ms)
[2018-06-06T06:52:13.532Z] debug GET 0bd35bad03d09ca61ac6cce225112e36.svg (24 ms)
[2018-06-06T06:52:49.491Z] debug POST /auth/local/register (236 ms)
[2018-06-06T06:52:49.604Z] debug GET 11.bfb1c2706e0dd37cd9b3.chunk.js (8 ms)
[2018-06-06T06:52:49.609Z] debug GET /settings-manager/autoReload (28 ms)
[2018-06-06T06:52:49.615Z] debug GET /content-type-builder/autoReload (26 ms)
[2018-06-06T06:52:49.641Z] debug GET c9cbbdc3762c340d5d37073a54971487.woff2 (6 ms)
[2018-06-06T06:52:49.643Z] debug GET ac7d0ef8528ed4230148886fe1a21b3b.png (15 ms)
[2018-06-06T06:52:49.650Z] debug GET /content-manager/models (30 ms)
[2018-06-06T06:52:49.765Z] debug GET 10.5ee0ee04a8d12eea967f.chunk.js (22 ms)
[2018-06-06T06:52:49.767Z] debug GET 20001789a249c0d8d721531434ce02ba.png (18 ms)
[2018-06-06T06:52:49.775Z] debug GET 9d15cd22252febb1667c5c1727d3d6ff.png (21 ms)
[2018-06-06T06:52:49.782Z] debug GET 3c2fd7a5298d52578097b7258362d751.png (22 ms)
[2018-06-06T06:52:49.785Z] debug GET 85f4e87cbdf8d922994c47a1356a856e.png (16 ms)
[2018-06-06T06:52:49.793Z] debug GET d6e16b2fbe60b5924c12d74cdcec49ec.png (16 ms)
[2018-06-06T06:52:49.813Z] debug GET 8.581a994a695647a4701e.chunk.js (26 ms)
[2018-06-06T06:52:49.815Z] debug GET 9.ffd4385391b3a84f56e3.chunk.js (19 ms)
[2018-06-06T06:52:49.817Z] debug GET c995503babdc2069f2d5f440b36771a1.png (16 ms)
[2018-06-06T06:52:49.819Z] debug GET e89e581cc335503916d3001c717e40b2.png (12 ms)
[2018-06-06T06:52:49.873Z] debug GET 80f6811f6c30735dab68a01372d8b78f.woff2 (4 ms)
[2018-06-06T06:53:10.807Z] debug GET /users-permissions/roles (27 ms)
[2018-06-06T06:53:27.599Z] debug GET /users-permissions/policies (30 ms)
[2018-06-06T06:53:27.612Z] debug GET /users-permissions/routes (36 ms)
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1032:34)
    at emitNone (events.js:115:13)
    at TLSSocket.emit (events.js:218:7)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
[2018-06-06T06:53:27.957Z] debug GET /users-permissions/roles/3?lang=en (373 ms)
```

**Comment by Aurelsicoko** [comment]
Where is hosted your database?

**Comment by VonOx** [comment]
On another computer, same network, no ssl

**Comment by Aurelsicoko** [comment]
Interesting... Does it work when the database is on the same computer or hosted on AWS?

**Comment by VonOx** [comment]
Yes tested on localhost ( same computer ) just now and same error occur

**Comment by derrickmehaffy** [comment]
@VonOx I can't reproduce this issue either. And my Database is in a whole other country running through a proxy as well. What version of MariaDB are you using?

**Comment by VonOx** [comment]
Yeah weird issue

`
mysql  Ver 15.1 Distrib 10.3.7-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**Comment by derrickmehaffy** [comment]
@VonOx try creating a clean new project and create a new table and try testing with that. Given I use MariaDB Galera 10.2.something but from what I've read on the change logs between 10.2 and 10.3 nothing should be causing that issue on the DB side.

**Comment by VonOx** [comment]
@derrickmehaffy After testing (right now), this is not DB related.
I have tested strapi on ubuntu and the same DB. And it works.

So this issue is about Windows 10 and my Corporate proxy

**Comment by derrickmehaffy** [comment]
@VonOx there are many issues with Windows 10, if I were you I would stick to ubuntu or some other linux flavor. (Who runs nodejs projects on windows anyway :stuck_out_tongue: wouldn't want to deal with that overhead)
