### ISSUE TITLE
Server wasn't able to start properly. " Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication  protocol requested by server; consider upgrading MySQL client"

### ISSUE THREAD

**Issue by PeaceAntoHim** [strapi/strapi#12748]
## Bug report
This error message i got it:
$ strapi develop
(node:12224) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\user01\Documents\miracle-strapi\node_modules\koa\package.json.   
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
[2022-03-04T02:55:22.303Z] debug ⛔️ Server wasn't able to start properly.
[2022-03-04T02:55:22.305Z] error Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication 
protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at Protocol._enqueue (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\Users\user01\Documents\miracle-strapi\node_modules\mysql\lib\Connection.js:116:18)
    at C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\dialects\mysql\index.js:68:18        
From previous event:
    at Client_MySQL.acquireRawConnection (C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\dialects\mysql\index.js:63:12)
    at create (C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\client.js:258:21)
    at C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\Pool.js:389:34
    at Object.tryPromise (C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\utils.js:53:24)   
    at C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\Pool.js:389:17
    at new Promise (<anonymous>)
    at callbackOrPromise (C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\Pool.js:380:12)   
    at Pool._create (C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\Pool.js:290:9)
    at Pool._doCreate (C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\Pool.js:260:36)      
    at Pool._tryAcquireOrCreate (C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\Pool.js:211:18)
    at Pool.acquire (C:\Users\user01\Documents\miracle-strapi\node_modules\tarn\lib\Pool.js:117:14)        
    at C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\client.js:312:43
From previous event:
    at Client_MySQL.acquireConnection (C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\client.js:312:26)
    at Runner.ensureConnection (C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\runner.js:246:8)
    at Runner.run (C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\runner.js:25:27)
    at SchemaBuilder.Target.then (C:\Users\user01\Documents\miracle-strapi\node_modules\knex\lib\interface.js:14:43)

### Describe the bug

when is write yan develop i can't run it because strapi can't render my db

### Steps to reproduce the behavior

Create Strapi app with yarn create strapi-app my-app
Open the app (my-app) in a text editor like VScode.
Run yarn develop.
See error

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 3.4.4
- Database: mysql
- Operating system: windows 10

**Comment by derrickmehaffy** [comment]
We aren't currently fixing bugs on Strapi v3, but in this case it's because the `mysql` dialect in Knex doesn't support the MySQL 8 new auth syntax. You need to use native password auth if you are using MySQL 8
