### ISSUE TITLE
SQL error when deploying to Cloud Run using CloudSQL Postgres 13

### ISSUE THREAD

**Issue by akshay-sri123** [strapi/strapi#12803]
### Describe the bug

Getting the following error when the application is deployed using CloudSQL on Cloud Run

```
Error: 
    SELECT
      tco."constraint_name" as constraint_name,
      kcu."column_name" as column_name,
      rel_kcu."table_name" as foreign_table,
      rel_kcu."column_name" as fk_column_name,
      rco.update_rule as on_update,
      rco.delete_rule as on_delete
    FROM information_schema.table_constraints tco
    JOIN information_schema.key_column_usage kcu
      ON tco.constraint_schema = kcu.constraint_schema
      AND tco.constraint_name = kcu.constraint_name
    JOIN information_schema.referential_constraints rco
      ON tco.constraint_schema = rco.constraint_schema
      AND tco.constraint_name = rco.constraint_name
    JOIN information_schema.key_column_usage rel_kcu
      ON rco.unique_constraint_schema = rel_kcu.constraint_schema
      AND rco.unique_constraint_name = rel_kcu.constraint_name
      AND kcu.ordinal_position = rel_kcu.ordinal_position
    WHERE
      tco.constraint_type = 'FOREIGN KEY'
      AND tco.constraint_schema = $1
      AND tco.table_name = $2
    ORDER BY kcu.table_schema, kcu.table_name, kcu.ordinal_position, kcu.constraint_name;
   - Connection terminated unexpectedly
    at Connection.<anonymous> (/home/akshay/Documents/Flip/website-strapi/app/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:509:28)
    at Connection.emit (node:events:390:28)
    at Connection.emit (node:domain:475:12)
    at TLSSocket.<anonymous> (/home/akshay/Documents/Flip/website-strapi/app/node_modules/pg/lib/connection.js:107:12)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
 

### Steps to reproduce the behavior

1. Deploy changes to Cloud Run
2. Application fails with the above error

### Expected behavior

The application should start without an error.

### Screenshots

Cloud Run logs
![Screenshot from 2022-03-10 08-40-43](https://user-images.githubusercontent.com/12184097/157581243-77541d39-111f-4519-8420-9e6f3a29c076.png)
![Screenshot from 2022-03-10 08-41-07](https://user-images.githubusercontent.com/12184097/157581251-0e2e7f07-0b8c-48e3-a9c6-143e18f71c53.png)

### System

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.2
- Database: PostgresSQL 13
- Operating system: Docker (`node:16-alpine3.15`)

**Comment by akshay-sri123** [comment]
The issue was with the specs for the CloudSQL instance. Increasing the specs resolved the error. 
Thanks 🙏🏽

**Comment by PranshuTyagi2003** [comment]
> The issue was with the specs for the CloudSQL instance. Increasing the specs resolved the error. Thanks 🙏🏽

I have hosted my database on render. how should i change the specs in render ?
