### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'components') when using my plugin

### ISSUE THREAD

**Issue by dasmikko** [strapi/strapi#12848]
### Describe the bug
I'm getting this error when I try use my own plugin strapi-tiptap-editor, via a git clone into src/plugins/strapi-tiptap-editor

and using the plugin inside the plugins.js
```
module.exports = {
  'strapi-tiptap-editor': {
    enabled: true,
    resolve: './src/plugins/strapi-tiptap-editor'
  },

  // ...
}

```

Here is the error message

```
Uncaught TypeError: Cannot read properties of undefined (reading 'components')
    at useLibrary (webpack-internal:///./lib/src/hooks/useLibrary/index.js:19:32)
    at MediaLib (main.bundle.js:85734:50)
    at renderWithHooks (main.bundle.js:46595:18)
    at mountIndeterminateComponent (main.bundle.js:49421:13)
    at beginWork (main.bundle.js:50659:16)
    at HTMLUnknownElement.callCallback (main.bundle.js:35555:14)
    at Object.invokeGuardedCallbackDev (main.bundle.js:35604:16)
    at invokeGuardedCallback (main.bundle.js:35666:31)
    at beginWork$1 (main.bundle.js:55569:7)
    at performUnitOfWork (main.bundle.js:54381:12)
```
I'm trying to make a development environment, where it's easy to make changes, and commit them.

The weird part is, it seems to work if i just copy the files over to the folder. 

I really don't understand what is going on.

### Steps to reproduce the behavior

1. Clone https://github.com/dasmikko/strapi-tiptap-editor into src/plugins
2. Enable the plugin inside config/plugins.js
3. Add a Rich text field
4. edit item that has rich text field
5. Errors show

### Expected behavior

It should just show my editor

### Screenshots

![image](https://user-images.githubusercontent.com/4254869/158376694-8e22c102-0acd-42c3-80c9-bc28825e5cc1.png)

### System

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.3.1
- Database: Postgresql 13.4
- Operating system: Fedora 35

**Comment by dasmikko** [comment]
Here is the second error it throws.

```
The above error occurred in the <MediaLib> component:

    at MediaLib (http://localhost:8000/dashboard/main.bundle.js:85730:21)
    at Wysiwyg (http://localhost:8000/dashboard/main.bundle.js:85903:20)
    at GenericInput (webpack-internal:///./lib/src/components/GenericInput/index.js:55:27)
    at Inputs (http://localhost:8000/dashboard/content-manager.chunk.js:7845:28)
    at http://localhost:8000/dashboard/content-manager.chunk.js:8133:34
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at GridItem (webpack-internal:///./src/Grid/GridItem.js:43:19)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at Grid (webpack-internal:///./src/Grid/Grid.js:40:19)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at eval (webpack-internal:///./src/Stack/Stack.js:55:26)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at eval (webpack-internal:///./src/Stack/Stack.js:55:26)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at GridItem (webpack-internal:///./src/Grid/GridItem.js:43:19)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at Grid (webpack-internal:///./src/Grid/Grid.js:40:19)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at ContentLayout (webpack-internal:///./src/Layout/ContentLayout.js:12:23)
    at main
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at Main (webpack-internal:///./src/Main/Main.js:27:25)
    at form
    at EditViewDataManagerProvider (http://localhost:8000/dashboard/content-manager.chunk.js:3789:28)
    at CollectionTypeFormWrapper (http://localhost:8000/dashboard/content-manager.chunk.js:290:28)
    at EditView (http://localhost:8000/dashboard/content-manager.chunk.js:20629:29)
    at Permissions (http://localhost:8000/dashboard/content-manager.chunk.js:21334:13)
    at EditViewLayoutManager (http://localhost:8000/dashboard/content-manager.chunk.js:21449:21)
    at Route (http://localhost:8000/dashboard/main.bundle.js:58602:29)
    at Switch (http://localhost:8000/dashboard/main.bundle.js:58808:29)
    at ErrorBoundary (http://localhost:8000/dashboard/vendors-node_modules_strapi_admin_node_modules_strapi_design-system_Avatar_js-node_modules_st-b2f37b.chunk.js:82676:35)
    at CollectionTypeRecursivePath (http://localhost:8000/dashboard/content-manager.chunk.js:16125:25)
    at Route (http://localhost:8000/dashboard/main.bundle.js:58602:29)
    at Switch (http://localhost:8000/dashboard/main.bundle.js:58808:29)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at Layout (webpack-internal:///./src/Layout/Layout.js:26:23)
    at App (http://localhost:8000/dashboard/content-manager.chunk.js:15488:60)
    at _default (http://localhost:8000/dashboard/content-manager.chunk.js:15582:42)
    at Route (http://localhost:8000/dashboard/main.bundle.js:58602:29)
    at Switch (http://localhost:8000/dashboard/main.bundle.js:58808:29)
    at Suspense
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at div
    at I (http://localhost:8000/dashboard/main.bundle.js:350202:20124)
    at AppLayout (http://localhost:8000/dashboard/Admin-authenticatedApp.chunk.js:1828:23)
    at DndProvider (http://localhost:8000/dashboard/main.bundle.js:335000:23)
    at Admin (http://localhost:8000/dashboard/Admin-authenticatedApp.chunk.js:2128:37)
    at PluginsInitializer (http://localhost:8000/dashboard/Admin-authenticatedApp.chunk.js:1559:54)
    at RBACProvider (http://localhost:8000/dashboard/Admin-authenticatedApp.chunk.js:1754:23)
    at AuthenticatedApp (http://localhost:8000/dashboard/Admin-authenticatedApp.chunk.js:58:56)
    at Route (http://localhost:8000/dashboard/main.bundle.js:58602:29)
    at PrivateRoute (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:2382:24)
    at Switch (http://localhost:8000/dashboard/main.bundle.js:58808:29)
    at Suspense
    at App (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:5409:62)
    at Router (http://localhost:8000/dashboard/main.bundle.js:58231:30)
    at BrowserRouter (http://localhost:8000/dashboard/main.bundle.js:346955:35)
    at NotificationsProvider (webpack-internal:///./lib/src/providers/NotificationsProvider/index.js:20:23)
    at Notifications (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:2128:23)
    at GuidedTourProvider (webpack-internal:///./lib/src/providers/GuidedTourProvider/index.js:15:23)
    at GuidedTour (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:1212:23)
    at OverlayBlockerProvider (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:2311:24)
    at AutoReloadOverlayBlockerProvider (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:993:23)
    at LocalesProvider (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:1868:27)
    at IntlProvider (http://localhost:8000/dashboard/main.bundle.js:340234:47)
    at LanguageProvider (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:1661:23)
    at LibraryProvider (webpack-internal:///./lib/src/providers/LibraryProvider/index.js:20:23)
    at StrapiAppProvider (webpack-internal:///./lib/src/providers/StrapiAppProvider/index.js:20:23)
    at Provider (http://localhost:8000/dashboard/main.bundle.js:345201:20)
    at QueryClientProvider (http://localhost:8000/dashboard/main.bundle.js:344424:21)
    at Providers (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:2455:23)
    at exports.ThemeProvider (http://localhost:8000/dashboard/main.bundle.js:350202:25298)
    at ThemeProvider (webpack-internal:///./src/ThemeProvider/ThemeProvider.js:25:24)
    at Theme (http://localhost:8000/dashboard/_cache_admin_src_StrapiApp_js.chunk.js:2566:23)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by dasmikko** [comment]
After hours of debugging, i realized that i needed to add my dependencies the root package.json file. (The one strapi uses)

Then i can use my git clone without issues.
