### ISSUE TITLE
Can't find module `strapi-admin`

### ISSUE THREAD

**Issue by mitch3ls** [strapi/strapi#12913]
### Describe the bug

Strapi build fails with `Error: Cannot find module 'strapi-admin'`.

### Steps to reproduce the behavior

1. Make sure the dependencies in package.json look like this:
```json
"dependencies": {
    "@strapi/plugin-i18n": "4.1.5",
    "@strapi/plugin-users-permissions": "4.1.5",
    "@strapi/strapi": "4.1.5",
    "sqlite3": "5.0.2",
    "strapi": "^3.6.8"
  },
```
2. Remove yarn.lock and the node_modules folder
3. Run `yarn`
4. Run `yarn build`
5. See error

### Expected behavior

A successful build.

### Screenshots

```sh
> yarn build
yarn run v1.22.17
$ strapi build
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'strapi-admin'
Require stack:
- /Path/to/project/folder/node_modules/strapi/lib/commands/build.js
- /Path/to/project/folder/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Path/to/project/folder/node_modules/strapi/lib/commands/build.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Path/to/project/folder/node_modules/strapi/lib/commands/build.js',
    '/Path/to/project/folder/node_modules/strapi/bin/strapi.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System

- Node.js version: lts/fermium
- yarn version: 1.22.17
- Strapi version: 4.1.5
- Database: sqlite3
- Operating system: macOS Monterey 12.3

**Comment by derrickmehaffy** [comment]
Cannot reproduce, can you please add more information as to how you got to this error

**Comment by derrickmehaffy** [comment]
Also you shouldn't have `"strapi": "^3.6.8"` in your package.json

**Comment by mitch3ls** [comment]
Thank you, the problem was the extra strapi package in package.json!

**Comment by TimMTech** [comment]
I swear to god these libraries have the most piss poor documentation out of everything in this world.  Who hires these idiots to write.  Stick to coding.  Dont write content please.  Let someone educated in that field write them.

**Comment by ashkan7929** [comment]
123456789
