### ISSUE TITLE
Crashes when changes to controller is made.

### ISSUE THREAD

**Issue by musthakeem** [strapi/strapi#12956]
**Whenever I make an edit to the controller with the new custom handler, the following error is thrown. The painful part is that the error will never go away even if I restore the default controller code. Seem like kind of a loop once it enters this error**

```
[2022-03-25 13:16:35.954] debug: ⛔️ Server wasn't able to start properly.
[2022-03-25 13:16:35.956] error: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at /Users/macbook-pc/Projects/datalah/node_modules/@strapi/strapi/lib/services/server/register-routes.js:98:21
    at /Users/macbook-pc/Projects/datalah/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/Users/macbook-pc/Projects/datalah/node_modules/lodash/lodash.js:3032:24)
    at /Users/macbook-pc/Projects/datalah/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/Users/macbook-pc/Projects/datalah/node_modules/lodash/lodash.js:9410:14)
    at registerAPIRoutes (/Users/macbook-pc/Projects/datalah/node_modules/@strapi/strapi/lib/services/server/register-routes.js:94:7)
    at module.exports (/Users/macbook-pc/Projects/datalah/node_modules/@strapi/strapi/lib/services/server/register-routes.js:25:3)
    at Object.initRouting (/Users/macbook-pc/Projects/datalah/node_modules/@strapi/strapi/lib/services/server/index.js:93:13)
    at Strapi.bootstrap (/Users/macbook-pc/Projects/datalah/node_modules/@strapi/strapi/lib/Strapi.js:402:23)
    at async Strapi.load (/Users/macbook-pc/Projects/datalah/node_modules/@strapi/strapi/lib/Strapi.js:413:5)
    at async Strapi.start (/Users/macbook-pc/Projects/datalah/node_modules/@strapi/strapi/lib/Strapi.js:161:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wfzong** [comment]
I got the same error ~~~

**Comment by RaimonxDev** [comment]
I've worked with custom controllers and haven't had that problem. That is a code error basically there is a property or variable that is not defined and therefore forEach cannot be applied. if you share your code we can take a better look at it and see what the problem really is

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
