### ISSUE TITLE
[4.2 beta]: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by Kinbaum** [strapi/strapi#12960]
## Describe the Bug

When using the `4.2.0-beta.0` with `typescript`, when I run a production build and then try to start my application, I get the following error:

```
[2022-03-25 08:47:55.681] debug: ⛔️ Server wasn't able to start properly.
[2022-03-25 08:47:55.682] error: Cannot read properties of undefined (reading 'push')
TypeError: Cannot read properties of undefined (reading 'push')
    at Object.addCreateLocalizationAction (/node_modules/@strapi/plugin-i18n/server/services/core-api.js:184:48)
    at /node_modules/@strapi/plugin-i18n/server/register.js:78:22
    at Array.forEach (<anonymous>)
    at extendLocalizedContentTypes (/node_modules/@strapi/plugin-i18n/server/register.js:56:38)
    at Object.module.exports [as register] (/node_modules/@strapi/plugin-i18n/server/register.js:12:3)
    at Object.register (/node_modules/@strapi/strapi/lib/core/domain/module/index.js:47:46)
    at Object.register (/node_modules/@strapi/strapi/lib/core/registries/modules.js:33:19)
    at async Strapi.runLifecyclesFunctions (/node_modules/@strapi/strapi/lib/Strapi.js:499:5)
    at async Strapi.register (/node_modules/@strapi/strapi/lib/Strapi.js:370:5)
    at async Strapi.load (/node_modules/@strapi/strapi/lib/Strapi.js:445:5)
    at async Strapi.start (/node_modules/@strapi/strapi/lib/Strapi.js:194:9)
Error: command finished with error: command (apps/strapi) yarn run start exited (1)
```

This is the code the error is thrown on:

```js
const addCreateLocalizationAction = contentType => {
  const { modelName, apiName } = contentType;

  const localizationRoute = createLocalizationRoute(contentType);

  // !! Error is thrown here
  strapi.api[apiName].routes[modelName].routes.push(localizationRoute);

  strapi.container.get('controllers').extend(`api::${apiName}.${modelName}`, controller => {
    return Object.assign(controller, {
      createLocalization: createLocalizationHandler(contentType),
    });
  });
};
```

Here are the files of my collection.
There has been no customization to these

```js
import { factories } from '@strapi/strapi';

export default factories.createCoreController('api::my-collection.my-collection');
```

```js
import { factories } from '@strapi/strapi';

export default factories.createCoreRouter('api::my-collection.my-collection');
```

```js
import { factories } from '@strapi/strapi';

export default factories.createCoreService('api::my-collection.my-collection');
```

### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.2.0-beta.0
- Database: MySQL
- Operating system: macOS

### Expected behavior

Strapi to start correctly

**Comment by mhagmajer** [comment]
We've also run into this problem. When can we expect a stable release of Strapi 4.2?

**Comment by sapkra** [comment]
Bug still persists on `4.2.0-beta.3`.

**Comment by Bassel17** [comment]
This issue doesn't seem to be present in the current latest release of Strapi `4.3.0`
will consider it resolved

**Comment by sjoukedv** [comment]
I'd like to re-open with`"@strapi/plugin-i18n": "4.3.0"` (and core `4.3.0`):

```
yarn run v1.22.19
$ strapi start
[2022-08-01 14:21:33.623] debug: ⛔️ Server wasn't able to start properly.
[2022-08-01 14:21:33.626] error: Cannot read properties of undefined (reading 'push')
TypeError: Cannot read properties of undefined (reading 'push')
    at Object.addCreateLocalizationAction (/app/node_modules/@strapi/plugin-i18n/server/services/core-api.js:182:48)
    at /app/node_modules/@strapi/plugin-i18n/server/register.js:78:22
    at Array.forEach (<anonymous>)
    at extendLocalizedContentTypes (/app/node_modules/@strapi/plugin-i18n/server/register.js:56:38)
    at Object.module.exports [as register] (/app/node_modules/@strapi/plugin-i18n/server/register.js:12:3)
    at Object.register (/app/node_modules/@strapi/strapi/lib/core/domain/module/index.js:47:46)
    at Object.register (/app/node_modules/@strapi/strapi/lib/core/registries/modules.js:33:19)
    at async Strapi.runLifecyclesFunctions (/app/node_modules/@strapi/strapi/lib/Strapi.js:510:5)
    at async Strapi.register (/app/node_modules/@strapi/strapi/lib/Strapi.js:379:5)
    at async Strapi.load (/app/node_modules/@strapi/strapi/lib/Strapi.js:456:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

FYI: I migrated this existing project to Typescript

**Comment by biko8** [comment]
Im not sure why but to me this error appears when adding `"sourceMap": true,` into compilerOptions of tsconfig.json.
I removed it and it works to me.

**Comment by roelbeerens** [comment]
Seems to be still happening on 4.3.2 as well. Local build is fine, Docker build however, seems to be breaking.

**Comment by Bassel17** [comment]
@roelbeerens the `dist` folder is something that is generated while you develop a typescript project it doesn't really exist beforehand and the naming can also be changed by the user in the `tsconfig` which is why we can't really use it to determine the project.
As for why we are not using an `env` to determine if it's TS or not, it's simply because the `tsconfig` is necessary to run a typescript project. However I am interested to see in what usecase you wouldn't want the tsconfig to be present ?

**Comment by antixrist** [comment]
@Bassel17 this is the same issue as https://github.com/strapi/strapi/pull/14088

**Comment by sjoukedv** [comment]
> @sjoukedv I would want to know more information about this, I wasn't able to reproduce this. it might be related to an issue we faced with windows (if you are using windows), I invite you to try again on `4.3.2` and let me know how to goes.

I believe I ended up adding a debug `console.log()` to the i18n plugin source to find out that I had a route (or controller) file with only commented out code in it. I'd suggest a try catch statement for that loop with a more clear error message.

FYI: I am on Ubuntu 20.04

**Comment by FieldMarshallVague** [comment]
Antixrist is correct, it's the same issue (well, solution) as the above linked issue.  It can be fixed in my case (on windows, strapi 4.4.0) by changing these lines in the strapi package:

In @strapi/typescript-utils/lib/utils/get-config-path.js.  Comment out the return line on line 33 and replace with the following lines (line 33 included for reference).  

``` js
// return configFilePath.startsWith(dirAbsolutePath) ? configFilePath : undefined;
  const configFileAbsolutePath = path.resolve(configFilePath)
  return configFileAbsolutePath.startsWith(dirAbsolutePath)
    ? configFileAbsolutePath
    : undefined

```

**Comment by BoburbekDev** [comment]
**[2022-11-06 07:34:20.782] debug: ⛔️ Server wasn't able to start properly.
[2022-11-06 07:34:20.784] error: Cannot read property 'api' of undefined
TypeError: Cannot read property 'api' of undefined
    at Object.getApiDocumentationPath (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/plugin-documentation/server/services/documentation.js:89:40)
    at Object.generateFullDoc (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/plugin-documentation/server/services/documentation.js:141:43)
    at Object.module.exports [as bootstrap] (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/plugin-documentation/server/bootstrap.js:53:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.bootstrap (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:468:5)
    at async Strapi.bootstrap (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:406:5)
    at async Strapi.load (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:415:5)
 I   at async Strapi.start (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:163:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@0.1.0 develop: `strapi develop`
npm ERR! Exit statu
npm ERR! 
npm ERR! Failed at the strapi@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-11-06T02_34_20_817Z-debug.log**

**Comment by BoburbekDev** [comment]
I cannot find solution to this error
[2022-11-06 07:34:20.782] debug: ⛔️ Server wasn't able to start properly.
[2022-11-06 07:34:20.784] error: Cannot read property 'api' of undefined
TypeError: Cannot read property 'api' of undefined
    at Object.getApiDocumentationPath (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/plugin-documentation/server/services/documentation.js:89:40)
    at Object.generateFullDoc (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/plugin-documentation/server/services/documentation.js:141:43)
    at Object.module.exports [as bootstrap] (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/plugin-documentation/server/bootstrap.js:53:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.bootstrap (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:468:5)
    at async Strapi.bootstrap (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:406:5)
    at async Strapi.load (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:415:5)
    at async Strapi.start (/home/user/Desktop/strapi/akbar-rich-strapi/node_modules/@strapi/strapi/lib/Strapi.js:163:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-11-06T02_34_20_817Z-debug.log

**Comment by roelbeerens** [comment]
> @roelbeerens the `dist` folder is something that is generated while you develop a typescript project it doesn't really exist beforehand and the naming can also be changed by the user in the `tsconfig` which is why we can't really use it to determine the project. As for why we are not using an `env` to determine if it's TS or not, it's simply because the `tsconfig` is necessary to run a typescript project. However I am interested to see in what usecase you wouldn't want the tsconfig to be present ?

My bad for not replying earlier, seems like my Github notification settings are all messed up. Anyways, you are right about the `dist` folder not being present and wouldn't be a correct way to check if it's a TS project or not. Indeed, a `tsconfig.json` should indicate it's a TS project, as it's a requirement to run a TS project. In our case, we fired the build command in our Dockerfile (which works just fine) and after that, we always tend to cleanup all dev related stuff for production images (stuff we don't need). As we already built the TS project, and had the `dist`, we kind of assumed that the `tsconfig.json` wouldn't be necessary anymore as we had already built the project. 

It's totally not a big deal to keep the `tsconfig.json` file, but maybe you guys could discuss to check for multiple paths when starting Strapi (on start check if there's a `dist` > run from there. If no `dist`, run from `src`)

**Comment by LukaHedt** [comment]
Can we add this fix in to the testing documentation?

> For me issue resolved by passing distDir in options
>
> `await Strapi({ distDir: './dist' }).load();`

That and the fact that non-default environment config files need to be `.js` and not `.ts`.

**Comment by shivarajnaidu** [comment]
When i tried this method in starpi 4.20.0 (typescript)

I got following error

```
[2024-04-03 02:18:48.121] error: Cannot read properties of undefined (reading 'push')
TypeError: Cannot read properties of undefined (reading 'push')
    at Object.addCreateLocalizationAction (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:3362:48)
    at /Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:2787:22
    at Array.forEach (<anonymous>)
    at extendLocalizedContentTypes (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:2768:39)
    at Object.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/plugin-i18n/dist/server/index.js:2743:3)
    at Object.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/core/domain/module/index.js:46:46)
    at Object.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/core/registries/modules.js:28:19)
    at async Strapi.runLifecyclesFunctions (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/Strapi.js:440:5)
    at async Strapi.register (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/Strapi.js:361:5)
    at async Strapi.load (/Users/myuser/oth/myapp/myapp-web-cms/node_modules/@strapi/strapi/dist/Strapi.js:425:5
```
