### ISSUE TITLE
[4.2 beta] Cannot add sourceMap files for typescript debugging

### ISSUE THREAD

**Issue by miwi-dev** [strapi/strapi#13016]
## Bug report

To be able to set breakpoints in typescript files and debug my custom controllers using VSCode, I need to add sourceMap files so that VSCode enables me to debug typescript. But after adding the configuration option `"sourceMap": true` to `tsconfig-server.json`, strapi crashes on startup.

Log:

```
Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at C:\Code\Playground\strapiTicket\my-project\node_modules\@strapi\strapi\lib\services\server\register-routes.js:98:21
    at C:\Code\Playground\strapiTicket\my-project\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Code\Playground\strapiTicket\my-project\node_modules\lodash\lodash.js:3032:24)
    at C:\Code\Playground\strapiTicket\my-project\node_modules\lodash\lodash.js:4936:18
    at Function.forEach (C:\Code\Playground\strapiTicket\my-project\node_modules\lodash\lodash.js:9410:14)
    at registerAPIRoutes (C:\Code\Playground\strapiTicket\my-project\node_modules\@strapi\strapi\lib\services\server\register-routes.js:94:7)
    at module.exports (C:\Code\Playground\strapiTicket\my-project\node_modules\@strapi\strapi\lib\services\server\register-routes.js:25:3)
    at Object.initRouting (C:\Code\Playground\strapiTicket\my-project\node_modules\@strapi\strapi\lib\services\server\index.js:93:13)
    at Strapi.bootstrap (C:\Code\Playground\strapiTicket\my-project\node_modules\@strapi\strapi\lib\Strapi.js:435:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Strapi.load (C:\Code\Playground\strapiTicket\my-project\node_modules\@strapi\strapi\lib\Strapi.js:446:5)
    at async Strapi.start (C:\Code\Playground\strapiTicket\my-project\node_modules\@strapi\strapi\lib\Strapi.js:194:9)
```
Looking at the stacktrace, it seems like the problem occurs in `register-routes.js`:

```typescript
const registerAPIRoutes = strapi => {
  for (const apiName in strapi.api) {
    const api = strapi.api[apiName];

    const generateRouteScope = createRouteScopeGenerator(`api::${apiName}`);

    _.forEach(api.routes, router => {
      // TODO: remove once auth setup
      // pass meta down to compose endpoint
      router.type = 'content-api';
      router.routes.forEach(route => {
        generateRouteScope(route);
        route.info = { apiName };
      });

      return strapi.server.routes(router);
    });
  }
```
  
While debugging this JS file it found, that `api.routes` contains two entries. One valid `about` route and one invalid `about-js` route:

![Screenshot 2022-03-30 160138](https://user-images.githubusercontent.com/102700273/160937962-d19d1e75-1ad0-4fd0-9238-c8028a232dd2.png)

Whereas there's only one (valid) route if the `sourceMap` configuration is set to `false`:

![Screenshot 2022-03-30 160419](https://user-images.githubusercontent.com/102700273/160938053-c5a94684-65ae-43ac-b922-e1e3486ce335.png)

It seems like strapi takes the *.js.map files also into account, despite the fact these are only for debugging purposes?

### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.2.0-beta.0
- Database: PostgreSQL
- Operating system: Windows 11

### Steps to reproduce the behavior

1. create a new typescript project `npx create-strapi-app@4.2.0-beta.0 --typescript my-project`
2. create new `single type` in admin ui
3. add `"sourceMap": true` to `tsconfig-server.json`
4. run strapi

### Expected behavior

Strapi starts correctly and sourceMap files are generated for debugging purposes.

**Comment by lkho** [comment]
In the meanwhile before they fix the bug, you can use `"inlineSourceMap": true` first to make `tsc` not emit the separate `.js.map` file.
