### ISSUE TITLE
Cannot build if path contains '#'

### ISSUE THREAD

**Issue by unaussprechlich** [strapi/strapi#13069]
### Required System information

- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: 4.1.7 
- Database: sqlite
- Operating system: Win11

### Describe the bug

Webpack breaks if the project path contains the character `#`. 

### Steps to reproduce the behavior

1. `npx create-strapi-app@latest \# --quickstart`
2. `cd \#`
3. `npx strapi build`
4. _Module build failed: Error: Cannot find module 'C:\\\x00#\\node_modules\\babel-loader\\lib\\index.js'\n_

### Expected behavior

Builds in path with character `#`.

### Code snippets

```
C:\> npx create-strapi-app@latest \# --quickstart
npx: installed 103 in 7.096s
Creating a quickstart project.
Creating a new Strapi application at C:\#.
Creating files.
Dependencies installed successfully.

Your application was created at C:\#.
```

```
C:\#> npx strapi build
Building your admin UI with development configuration ...

× Webpack
  Compiled with some errors in 472.51ms

[
  {
    moduleIdentifier: 'C:\\\x00#\\node_modules\\babel-loader\\lib\\index.js??ruleSet[1].rules[0].use!C:\\\x00#\\.cache\\admin\\src\\index.js',
    moduleName: '../\x00#/.cache/admin/src/index.js',
    message: "Module build failed: Error: Cannot find module 'C:\\\x00#\\node_modules\\babel-loader\\lib\\index.js'\n" +
      'Require stack:\n' +
      '- C:\\#\\node_modules\\webpack\\lib\\ProgressPlugin.js\n' +
      '- C:\\#\\node_modules\\webpack\\lib\\index.js\n' +
      '- C:\\#\\node_modules\\@strapi\\admin\\index.js\n' +
      '- C:\\#\\node_modules\\@strapi\\strapi\\lib\\commands\\build.js\n' +
      '- C:\\#\\node_modules\\@strapi\\strapi\\bin\\strapi.js\n' +
      '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\n' +
      '    at Module.require (internal/modules/cjs/loader.js:974:19)\n' +
      '    at require (internal/modules/cjs/helpers.js:101:18)\n' +
      '    at C:\\#\\node_modules\\webpack\\lib\\ProgressPlugin.js:412:9\n' +
      '    at Hook.eval [as call] (eval at create (C:\\#\\node_modules\\tapable\\lib\\HookCodeFactory.js:19:10), <anonymous>:7:1)\n' +
      '    at Hook.CALL_DELEGATE [as _call] (C:\\#\\node_modules\\tapable\\lib\\Hook.js:14:14)\n' +
      '    at NormalModule._doBuild (C:\\#\\node_modules\\webpack\\lib\\NormalModule.js:802:24)\n' +
      '    at NormalModule.build (C:\\#\\node_modules\\webpack\\lib\\NormalModule.js:956:15)\n' +
      '    at C:\\#\\node_modules\\webpack\\lib\\Compilation.js:1367:12\n' +
      '    at NormalModule.needBuild (C:\\#\\node_modules\\webpack\\lib\\NormalModule.js:1243:32)\n' +
      '    at Compilation._buildModule (C:\\#\\node_modules\\webpack\\lib\\Compilation.js:1348:10)\n' +
      '    at C:\\#\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:303:10\n' +
      '    at Hook.eval [as callAsync] (eval at create (C:\\#\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\\#\\node_modules\\tapable\\lib\\Hook.js:18:14)\n' +
      '    at AsyncQueue._startProcessing (C:\\#\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:293:26)',

.........
```

### Additional context

Found a [related Issue at webpack/loader-runner](https://github.com/webpack/loader-runner/issues/46#issue-777343557)

**Comment by derrickmehaffy** [comment]
Not possible for us to fix without an update to webpack loader, I'll close this but if an update happens on that issue please feel free to ping us and we can reopen this and re-evaluate later.
