### ISSUE TITLE
Updating UsersPermissionsUser model using graphql returns undefined bindings error

### ISSUE THREAD

**Issue by creaseaj** [strapi/strapi#13072]
### Required System information

- Node.js version:  16.14.2
- NPM version: 
- Strapi version: 4.1.7
- Database: mysql 8.0
- Operating system: Docker(node:16-alpine)

### Describe the bug

When I attempt to use the GraphQL API to update a user I get this error in response: 
```
  "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [t0.id] query: where `t0`.`id` = ?",
                        "    at QueryCompiler_MySQL.toSQL (/srv/app/cms/node_modules/knex/lib/query/querycompiler.js:110:13)",
                        "    at compileCallback (/srv/app/cms/node_modules/knex/lib/formatter/formatterUtils.js:13:19)",
                        "    at rawOrFn (/srv/app/cms/node_modules/knex/lib/formatter/wrappingFormatter.js:225:7)",
                        "    at QueryCompiler_MySQL.whereWrapped (/srv/app/cms/node_modules/knex/lib/query/querycompiler.js:1066:17)",
                        "    at QueryCompiler_MySQL.where (/srv/app/cms/node_modules/knex/lib/query/querycompiler.js:555:34)",
                        "    at /srv/app/cms/node_modules/knex/lib/query/querycompiler.js:130:40",
                        "    at Array.map (<anonymous>)",
                        "    at QueryCompiler_MySQL.select (/srv/app/cms/node_modules/knex/lib/query/querycompiler.js:129:35)",
                        "    at QueryCompiler_MySQL.toSQL (/srv/app/cms/node_modules/knex/lib/query/querycompiler.js:73:29)",
                        "    at Builder.toSQL (/srv/app/cms/node_modules/knex/lib/query/querybuilder.js:83:44)",
                        "    at ensureConnectionCallback (/srv/app/cms/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)",
                        "    at Runner.ensureConnection (/srv/app/cms/node_modules/knex/lib/execution/runner.js:307:20)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async Runner.run (/srv/app/cms/node_modules/knex/lib/execution/runner.js:30:19)",
                        "    at async Object.execute (/srv/app/cms/node_modules/@strapi/database/lib/query/query-builder.js:354:22)",
                        "    at async Object.findOne (/srv/app/cms/node_modules/@strapi/database/lib/entity-manager.js:118:22)",
                        "    at async Object.afterUpdate (/srv/app/cms/src/index.js:24:22)",
                        "    at async Object.run (/srv/app/cms/node_modules/@strapi/database/lib/lifecycles/index.js:57:11)",
                        "    at async Object.update (/srv/app/cms/node_modules/@strapi/database/lib/entity-manager.js:262:7)",
                        "    at async Object.update (/srv/app/cms/node_modules/@strapi/strapi/lib/services/entity-service/index.js:219:18)",
                        "    at async Object.<anonymous> (/srv/app/cms/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)",
                        "    at async Object.update (/srv/app/cms/node_modules/@strapi/plugin-users-permissions/server/controllers/user.js:126:18)"
                    ]
                }
            }
```

Currently, the mutation is successful but this query fails and then sends the error back to the client, instead of the expected user model.

### Steps to reproduce the behavior

1. Create a user in strapi.
2. Send graphql query in code blocks section.

### Expected behavior

The user model is returned as well as updated.

### Code snippets

GraphQL Query: 
```
mutation updateSettings {
    updateUsersPermissionsUser(id: 1, data: { email: "test@test.com" }) {
        data {
            id
            attributes {
                email
            }
        }
    }
}
```

**Comment by creaseaj** [comment]
Duplicate https://github.com/strapi/strapi/issues/11957
