### ISSUE TITLE
Strapi v4 typescript "config:dump" not working

### ISSUE THREAD

**Issue by JairSmith** [strapi/strapi#13079]
### Required System information

- Node.js version: v16.13.0
- NPM version: 8.0.0
- Strapi version: v4.2.0-beta.0
- Database: sqlite/mysql (tested with both)
- Operating system: MacOSX 12.2.1

### Describe the bug

When running the CLI command `strapi config dump`, an error is thrown. In summary, the error is `Error: Unknown dialect undefined`. Usually, this error is caused by incorrect formatting of the `config/database.js` file.

My `config/database.ts` file
```typescript
export default ({ env }) => ({
  connection: {
    client: "mysql",
    connection: {
      host: env("DATABASE_HOST", "127.0.0.1"),
      port: env.int("DATABASE_PORT", 3306),
      database: env("DATABASE_NAME", "database_name"),
      user: env("DATABASE_USERNAME", "root"),
      password: env("DATABASE_PASSWORD", ""),
      ssl: env.bool("DATABASE_SSL", false),
    }
  },
});
```

I think the error is caused because the typescript file is not being red correctly.

### Steps to reproduce the behavior

1. Run command `npx create-strapi-app@4.2.0-beta.0 --typescript <project_name>`
2. Navigate to the project directory
3. Run `yarn strapi config:dump -p -f dump.json`

### Expected behavior

Strapi configuration should be dumped to a file called `dump.json`.

### Screenshots

N/A

### Code snippets

If applicable, add code samples to help explain your problem.

```zsh
$ strapi config:dump -p -f dump.json
Error: Unknown dialect undefined
    at getDialectClass (/Users/jsmith/workplace/playground/config-test/node_modules/@strapi/database/lib/dialects/index.js:12:13)
    at getDialect (/Users/jsmith/workplace/playground/config-test/node_modules/@strapi/database/lib/dialects/index.js:19:23)
    at new Database (/Users/jsmith/workplace/playground/config-test/node_modules/@strapi/database/lib/index.js:38:20)
    at Function.Database.init (/Users/jsmith/workplace/playground/config-test/node_modules/@strapi/database/lib/index.js:84:33)
    at Strapi.bootstrap (/Users/jsmith/workplace/playground/config-test/node_modules/@strapi/strapi/lib/Strapi.js:383:30)
    at Strapi.load (/Users/jsmith/workplace/playground/config-test/node_modules/@strapi/strapi/lib/Strapi.js:446:16)
    at async module.exports (/Users/jsmith/workplace/playground/config-test/node_modules/@strapi/strapi/lib/commands/configurationDump.js:15:15)
error Command failed with exit code 1.
```

### Additional context

The same error is thrown when running the `config:restore` command.

**Comment by DimitriGilbert** [comment]
When using typescript, no config are loaded when using the CLI because Strapi is looking for .js or .json file in your current directory ```config``` folder, but, when you are using typescript, no js file are to be found, only .ts therefore, no config....

Trying js config files do not work either :
* just adding built js file with ts file at the same time result in the config being reset
* using js config file with typescript don't seem to work properly

I tried modifying node_modules/@strapi/strapi/lib/core/app-configuration/config-loader.js to filter out ts file but it crashes with the following error :
```bash
error: Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at /srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:98:21
    at /srv/app/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/srv/app/node_modules/lodash/lodash.js:3032:24)
    at /srv/app/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/srv/app/node_modules/lodash/lodash.js:9410:14)
    at registerAPIRoutes (/srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:94:7)
    at module.exports (/srv/app/node_modules/@strapi/strapi/lib/services/server/register-routes.js:25:3)
    at Object.initRouting (/srv/app/node_modules/@strapi/strapi/lib/services/server/index.js:93:13)
    at Strapi.bootstrap (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:435:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Strapi.load (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:446:5)
    at async Strapi.start (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:194:9)
```

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/13095
