### ISSUE TITLE
After change encoding to utf8mb4 then content type builder stop showing

### ISSUE THREAD

**Issue by EnterVPL** [strapi/strapi#13119]
### Required System information

- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: 4.1.7
- Database: MySQL
- Operating system: Debian 9

### Steps to reproduce the behavior

1. Create new project
2. Add to `config/database.js`
```js
charset: env('DATABASE_CHARSET', 'utf8mb4')
```
3. Open Content type builder
4. See white page and get this error
```
TypeError: Cannot read properties of undefined (reading 'startSection')
    at _ (content-type-builder.11503389.chunk.js:1:197458)
    at li (main.00774daf.js:2:1152465)
    at Vu (main.00774daf.js:2:1204762)
    at kl (main.00774daf.js:2:1192003)
    at Pl (main.00774daf.js:2:1191931)
    at jl (main.00774daf.js:2:1191794)
    at xl (main.00774daf.js:2:1188760)
    at main.00774daf.js:2:1138257
    at t.unstable_runWithPriority (main.00774daf.js:2:1229062)
    at Go (main.00774daf.js:2:1138034)
```

**Comment by EnterVPL** [comment]
All plugins not working

**Comment by derrickmehaffy** [comment]
You can't just set the charset in the database.js if your database isn't actually using this charset, you'll also need to convert all your tables over to that charset.

https://stackoverflow.com/questions/6115612/how-to-convert-an-entire-mysql-database-characterset-and-collation-to-utf-8

This isn't a Strapi issue
