### ISSUE TITLE
Content-Type builder and Media Library not working using --watch-admin

### ISSUE THREAD

**Issue by davefv** [strapi/strapi#13123]
### Required System information

- Node.js version: v14.19.1
- NPM version: 8.6.0
- Strapi version: 4.1.8
- Database: 10.3.34-MariaDB-0ubuntu0.20.04.1-log 
- Operating system: Ubuntu 20.04

### Describe the bug

Content-type builder not working (a blank page is showing) working with flag --watch-admin on version 4.1.8. Media Library not working also. 

### Steps to reproduce the behavior

Execute `npm run develop -- --watch-admin`

Click on Content-Type Builder or Media Library on left menu

Blank page is shown. 

Chrome console:

Uncaught TypeError: Cannot destructure property 'startSection' of '(0 , _strapi_helper_plugin__WEBPACK_IMPORTED_MODULE_2__.useGuidedTour)(...)' as it is undefined.
    at App (content-type-builder.chunk.js:8414:11)
    at renderWithHooks (main.bundle.js:50957:18)
    at mountIndeterminateComponent (main.bundle.js:53783:13)
    at beginWork (main.bundle.js:55021:16)
    at HTMLUnknownElement.callCallback (main.bundle.js:39917:14)
    at Object.invokeGuardedCallbackDev (main.bundle.js:39966:16)
    at invokeGuardedCallback (main.bundle.js:40028:31)
    at beginWork$1 (main.bundle.js:59931:7)
    at performUnitOfWork (main.bundle.js:58746:12)
    at workLoopSync (main.bundle.js:58674:5)
App @ content-type-builder.chunk.js:8414
renderWithHooks @ main.bundle.js:50957
mountIndeterminateComponent @ main.bundle.js:53783
beginWork @ main.bundle.js:55021
callCallback @ main.bundle.js:39917
invokeGuardedCallbackDev @ main.bundle.js:39966
invokeGuardedCallback @ main.bundle.js:40028
beginWork$1 @ main.bundle.js:59931
performUnitOfWork @ main.bundle.js:58746
workLoopSync @ main.bundle.js:58674
renderRootSync @ main.bundle.js:58637
performSyncWorkOnRoot @ main.bundle.js:58260
(anonymous) @ main.bundle.js:47299
unstable_runWithPriority @ main.bundle.js:66325
runWithPriority$1 @ main.bundle.js:47248
flushSyncCallbackQueueImpl @ main.bundle.js:47294
flushSyncCallbackQueue @ main.bundle.js:47281
scheduleUpdateOnFiber @ main.bundle.js:57860
dispatchAction @ main.bundle.js:52111
(anonymous) @ _cache_admin_src_StrapiApp_js.chunk.js:6757
fulfilled @ _cache_admin_src_StrapiApp_js.chunk.js:6731
Promise.then (async)
step @ _cache_admin_src_StrapiApp_js.chunk.js:6743
(anonymous) @ _cache_admin_src_StrapiApp_js.chunk.js:6744
__async @ _cache_admin_src_StrapiApp_js.chunk.js:6728
loadCompo @ _cache_admin_src_StrapiApp_js.chunk.js:6754
(anonymous) @ _cache_admin_src_StrapiApp_js.chunk.js:6762
invokePassiveEffectCreate @ main.bundle.js:59454
callCallback @ main.bundle.js:39917
invokeGuardedCallbackDev @ main.bundle.js:39966
invokeGuardedCallback @ main.bundle.js:40028
flushPassiveEffectsImpl @ main.bundle.js:59541
unstable_runWithPriority @ main.bundle.js:66325
runWithPriority$1 @ main.bundle.js:47248
flushPassiveEffects @ main.bundle.js:59414
(anonymous) @ main.bundle.js:59291
workLoop @ main.bundle.js:66274
flushWork @ main.bundle.js:66247
performWorkUntilDeadline @ main.bundle.js:66014
main.bundle.js:56057 The above error occurred in the <App> component:

    at App (http://localhost:8000/admin/content-type-builder.chunk.js:8409:81)
    at LazyCompo (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:6751:22)
    at Route (http://localhost:8000/admin/main.bundle.js:62755:29)
    at Switch (http://localhost:8000/admin/main.bundle.js:62961:29)
    at Suspense
    at div
    at I (http://localhost:8000/admin/main.bundle.js:185330:20057)
    at div
    at I (http://localhost:8000/admin/main.bundle.js:185330:20057)
    at div
    at I (http://localhost:8000/admin/main.bundle.js:185330:20057)
    at AppLayout (http://localhost:8000/admin/Admin-authenticatedApp.chunk.js:1549:22)
    at DndProvider (http://localhost:8000/admin/main.bundle.js:170683:23)
    at Admin (http://localhost:8000/admin/Admin-authenticatedApp.chunk.js:1759:3)
    at PluginsInitializer (http://localhost:8000/admin/Admin-authenticatedApp.chunk.js:1345:102)
    at RBACProvider (http://localhost:8000/admin/Admin-authenticatedApp.chunk.js:1491:25)
    at AuthenticatedApp (http://localhost:8000/admin/Admin-authenticatedApp.chunk.js:60:107)
    at Route (http://localhost:8000/admin/main.bundle.js:62755:29)
    at PrivateRoute (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2602:29)
    at Switch (http://localhost:8000/admin/main.bundle.js:62961:29)
    at Suspense
    at App (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:4887:100)
    at Router (http://localhost:8000/admin/main.bundle.js:62384:30)
    at BrowserRouter (http://localhost:8000/admin/main.bundle.js:182847:35)
    at NotificationsProvider (webpack-internal:///./lib/src/providers/NotificationsProvider/index.js:20:23)
    at Notifications (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2394:26)
    at GuidedTourProvider (webpack-internal:///./lib/src/providers/GuidedTourProvider/index.js:15:23)
    at GuidedTour (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:1711:23)
    at OverlayBlockerProvider (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2530:35)
    at AutoReloadOverlayBlockerProvider (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:1558:45)
    at LocalesProvider (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2194:28)
    at IntlProvider (http://localhost:8000/admin/main.bundle.js:175917:47)
    at LanguageProvider (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2026:29)
    at LibraryProvider (webpack-internal:///./lib/src/providers/LibraryProvider/index.js:20:23)
    at StrapiAppProvider (webpack-internal:///./lib/src/providers/StrapiAppProvider/index.js:20:23)
    at Provider (http://localhost:8000/admin/main.bundle.js:181093:20)
    at QueryClientProvider (http://localhost:8000/admin/main.bundle.js:180316:21)
    at exports.ThemeProvider (http://localhost:8000/admin/main.bundle.js:185330:25231)
    at ThemeProvider (webpack-internal:///./src/ThemeProvider/ThemeProvider.js:25:24)
    at Theme (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2801:18)
    at ThemeToggleProvider (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2839:32)
    at Providers (http://localhost:8000/admin/_cache_admin_src_StrapiApp_js.chunk.js:2671:3)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ main.bundle.js:56057
update.callback @ main.bundle.js:56085
callCallback @ main.bundle.js:48290
commitUpdateQueue @ main.bundle.js:48311
commitLifeCycles @ main.bundle.js:56703
commitLayoutEffects @ main.bundle.js:59393
callCallback @ main.bundle.js:39917
invokeGuardedCallbackDev @ main.bundle.js:39966
invokeGuardedCallback @ main.bundle.js:40028
commitRootImpl @ main.bundle.js:59118
unstable_runWithPriority @ main.bundle.js:66325
runWithPriority$1 @ main.bundle.js:47248
commitRoot @ main.bundle.js:58957
performSyncWorkOnRoot @ main.bundle.js:58296
(anonymous) @ main.bundle.js:47299
unstable_runWithPriority @ main.bundle.js:66325
runWithPriority$1 @ main.bundle.js:47248
flushSyncCallbackQueueImpl @ main.bundle.js:47294
flushSyncCallbackQueue @ main.bundle.js:47281
scheduleUpdateOnFiber @ main.bundle.js:57860
dispatchAction @ main.bundle.js:52111
(anonymous) @ _cache_admin_src_StrapiApp_js.chunk.js:6757
fulfilled @ _cache_admin_src_StrapiApp_js.chunk.js:6731
Promise.then (async)
step @ _cache_admin_src_StrapiApp_js.chunk.js:6743
(anonymous) @ _cache_admin_src_StrapiApp_js.chunk.js:6744
__async @ _cache_admin_src_StrapiApp_js.chunk.js:6728
loadCompo @ _cache_admin_src_StrapiApp_js.chunk.js:6754
(anonymous) @ _cache_admin_src_StrapiApp_js.chunk.js:6762
invokePassiveEffectCreate @ main.bundle.js:59454
callCallback @ main.bundle.js:39917
invokeGuardedCallbackDev @ main.bundle.js:39966
invokeGuardedCallback @ main.bundle.js:40028
flushPassiveEffectsImpl @ main.bundle.js:59541
unstable_runWithPriority @ main.bundle.js:66325
runWithPriority$1 @ main.bundle.js:47248
flushPassiveEffects @ main.bundle.js:59414
(anonymous) @ main.bundle.js:59291
workLoop @ main.bundle.js:66274
flushWork @ main.bundle.js:66247
performWorkUntilDeadline @ main.bundle.js:66014
_cache_admin_src_StrapiApp_js.chunk.js:6759 TypeError: Cannot destructure property 'startSection' of '(0 , _strapi_helper_plugin__WEBPACK_IMPORTED_MODULE_2__.useGuidedTour)(...)' as it is undefined.
    at App (content-type-builder.chunk.js:8414:11)
    at renderWithHooks (main.bundle.js:50957:18)
    at mountIndeterminateComponent (main.bundle.js:53783:13)
    at beginWork (main.bundle.js:55021:16)
    at HTMLUnknownElement.callCallback (main.bundle.js:39917:14)
    at Object.invokeGuardedCallbackDev (main.bundle.js:39966:16)
    at invokeGuardedCallback (main.bundle.js:40028:31)
    at beginWork$1 (main.bundle.js:59931:7)
    at performUnitOfWork (main.bundle.js:58746:12)
    at workLoopSync (main.bundle.js:58674:5)

### Expected behavior

Content-Type Builder and Media Library should work as without --watch-admin

**Comment by davefv** [comment]
Solved! Works well after:
```
rm -rf build/
rm -rf node_modules
npm i
npm run build
npm run develop -- --watch-admin
```
Sorry.
