### ISSUE TITLE
Can't run npm start using meilisearch

### ISSUE THREAD

**Issue by Alecattie** [strapi/strapi#13159]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database: 
- Operating system: Linux Ubuntu

### Describe the bug

I can't start the project on an ubuntu machine after installing meilisearch the log is: 

`> my-project@0.1.0 start /home/ubuntu/cybertiks-strapi
> strapi start

[2022-04-20 04:41:25.581] debug: ⛔️ Server wasn't able to start properly.
[2022-04-20 04:41:25.584] error: Could not load js config file /home/ubuntu/cybertiks-strapi/node_modules/strapi-plugin-meilisearch/strapi-server.js: Unexpected token '.'
Error: Could not load js config file /home/ubuntu/cybertiks-strapi/node_modules/strapi-plugin-meilisearch/strapi-server.js: Unexpected token '.'
    at loadJsFile (/home/ubuntu/cybertiks-strapi/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:18:11)
    at loadFile (/home/ubuntu/cybertiks-strapi/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:35:14)
    at Object.loadPlugins (/home/ubuntu/cybertiks-strapi/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:96:26)
    at async Strapi.loadPlugins (/home/ubuntu/cybertiks-strapi/node_modules/@strapi/strapi/lib/Strapi.js:284:5)
    at async Promise.all (index 1)
    at async Strapi.register (/home/ubuntu/cybertiks-strapi/node_modules/@strapi/strapi/lib/Strapi.js:316:5)
    at async Strapi.load (/home/ubuntu/cybertiks-strapi/node_modules/@strapi/strapi/lib/Strapi.js:414:5)
    at async Strapi.start (/home/ubuntu/cybertiks-strapi/node_modules/@strapi/strapi/lib/Strapi.js:163:9)`
I am running npm start

### Steps to reproduce the behavior

1. `npm install strapi-plugin-meilisearch`
2. `strapi build` 
3. `npm start`
### Expected behavior

Should start the project

### Screenshots

<img width="1237" alt="Screen Shot 2022-04-20 at 12 27 17 AM" src="https://user-images.githubusercontent.com/16178867/164156702-c8219e09-b4b5-443d-8992-4a3a574df908.png">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
As this isn't a Strapi maintained plugin I'll set this as closed, please reach out the plugin author

**Comment by mNutella** [comment]
I had the same problem with node version 12, then I just upgraded it to 14
I hope this helps
