### ISSUE TITLE
i18n plugin create locale: [29] is not an existing permission action

### ISSUE THREAD

**Issue by Hazeman28** [strapi/strapi#13244]
### Required System information

- Node.js version: `v16.13.1`
- NPM version: `v8.1.2`
- Strapi version: `v4.1.9`
- Database: `SQLite`
- Operating system: `macOS 12.3.1`

### Describe the bug

When trying to create a locale within the `bootstrap` function using the i18n plugin service, following error is thrown upon starting the server:
```bash
yarn run v1.22.17
$ strapi develop
Building your admin UI with development configuration ...
Admin UI built successfully
[2022-05-05 15:15:32.901] debug: ⛔️ Server wasn't able to start properly.
[2022-05-05 15:15:32.901] error: [29] is not an existing permission action
ValidationError: [29] is not an existing permission action
    at handleYupError (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/utils/lib/validators.js:63:9)
    at /Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/utils/lib/validators.js:73:5
    at async Object.assignPermissions (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/admin/server/services/role.js:313:3)
    at async Object.syncSuperAdminPermissionsWithLocales (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/plugin-i18n/server/services/permissions/actions.js:95:3)
    at async Object.afterCreate (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/plugin-i18n/server/bootstrap.js:52:7)
    at async Object.run (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/database/lib/lifecycles/index.js:57:11)
    at async Object.create (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/database/lib/entity-manager.js:185:7)
    at async Object.create (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/plugin-i18n/server/services/locales.js:18:18)
    at async bootstrap (/Users/hazeman/Development/experimental/strapi-nvmrc-test/src/index.js:22:5)
    at async Strapi.runLifecyclesFunctions (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/strapi/lib/Strapi.js:473:7)
    at async Strapi.bootstrap (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/strapi/lib/Strapi.js:406:5)
    at async Strapi.load (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/strapi/lib/Strapi.js:415:5)
    at async Strapi.start (/Users/hazeman/Development/experimental/strapi-nvmrc-test/node_modules/@strapi/strapi/lib/Strapi.js:163:9)
error Command failed with exit code 1.
```
However, despite the error, **locale is successfully created**, and can be viewed in the admin panel.

Here is the code in the `bootstrap` function:
```javascript
  async bootstrap({ strapi }) {
    await strapi.plugin("i18n").service("locales").create({
      code: "sk",
      name: "Slovak (sk)",
    });
  },
```

I'm trying to setup seeding, and since project requires i18n, I also need to seed locales. Since the locale is actually being created ignoring the error, currently I have a workaround of wrapping the call in a try-catch:
```javascript
    try {
      await strapi.plugin("i18n").service("locales").create({
        code: "sk",
        name: "Slovak (sk)",
      });
    } catch (error) {}
``` 
This is not ideal, and it would be great if we could seed locales without receiving this error.

### Steps to reproduce the behavior

1. Create a Strapi starter project.
2. Add code described above to create a locale programatically.
3. Start the development server.
4. See the error.

### Expected behavior

Ability to create locales without receiving errors.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by czyzby** [comment]
For anyone that has encountered this error, you can use `createMany` instead to avoid the error.

```typescript
await strapi.query("plugin::i18n.locale").createMany({
  data: [
    {
      name,
      code,
    },
  ],
});
```

**Comment by segovia** [comment]
Why was this closed? It is clearly a bug and I ran into the same issue.
