### ISSUE TITLE
Socket error when connection with flutter application server.handleUpgrade()

### ISSUE THREAD

**Issue by oybek1024** [strapi/strapi#13258]
/root/agsat-agromart-admin/node_modules/engine.io/node_modules/ws/lib/websocket-server.js:340
      throw new Error(
      ^

Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
    at WebSocketServer.completeUpgrade (/root/agsat-agromart-admin/node_modules/engine.io/node_modules/ws/lib/websocket-server.js:340:13)
    at WebSocketServer.handleUpgrade (/root/agsat-agromart-admin/node_modules/engine.io/node_modules/ws/lib/websocket-server.js:316:10)
    at /root/agsat-agromart-admin/node_modules/engine.io/build/server.js:397:21
    at Server.verify (/root/agsat-agromart-admin/node_modules/engine.io/build/server.js:127:24)
    at Server.handleUpgrade (/root/agsat-agromart-admin/node_modules/engine.io/build/server.js:383:14)
    at Server.<anonymous> (/root/agsat-agromart-admin/node_modules/engine.io/build/server.js:495:26)
    at Server.emit (events.js:327:22)
    at onParserExecuteCommon (_http_server.js:695:14)
    at onParserExecute (_http_server.js:608:3)

Thanks, answer.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
