### ISSUE TITLE
[v4] GraphQL create mutation returns error, however entity is properly created

### ISSUE THREAD

**Issue by ynechaev** [strapi/strapi#13263]
### Required System information

- Node.js version: 14.17.0
- NPM version: 8.8.0
- Strapi version: 4.1.5
- Database: SQLite
- Operating system: Mac OS 12.3.1

### Describe the bug

GraphQL mutation returns error and malformed data, however entity is created.

### Steps to reproduce the behavior

1. Install strapi graphql plugin
2. Create new content type with one text field (for ex. Subscription { email: String })
3. Set Public permissions to allow all for the Subscription content type
4. Open GraphQL playground
5. Execute mutation as following:
```graphql
mutation AddSubscription($email: String!) {
  createSubscription(data:{email: $email}){
    data{
      id
      attributes{
        email
      }
    }
  }
}
```

### Expected behavior
Return no error and new entity with fields:
```graphql
{
  "data": {
    "createSubscription": {
      "data": {
        "id": "13",
        "attributes": {
          "email": "hello@world.com"
        }
      }
    }
  }
}
```

But instead I receive a response as following:
```graphql
{
  "errors": [
    {
      "message": "Forbidden access",
      "extensions": {
        "error": {
          "name": "ForbiddenError",
          "message": "Forbidden access",
          "details": {}
        },
        "code": "FORBIDDEN"
      }
    }
  ],
  "data": {
    "createSubscription": {
      "data": {
        "id": "13",
        "attributes": {
          "email": null
        }
      }
    }
  }
}
```

### Screenshots

This is a screenshot of properly populated entity:

<img width="1072" alt="Снимок экрана 2022-05-07 в 10 50 06" src="https://user-images.githubusercontent.com/1216785/167249174-d4031260-41e5-4e37-b62c-8d1018bc1099.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

I am using the following plugin:
```
"@strapi/plugin-graphql": "4.1.5",
```

**Comment by derrickmehaffy** [comment]
> "@strapi/plugin-graphql": "4.1.5",

Can you please try to upgrade your project to the latest version v4.1.10 and validate the issue exists here also?

For now I'll mark as closed but please do reply once you have tested on the latest version and if the issue still exists we can reopen.

Thank you!

**Comment by ynechaev** [comment]
@derrickmehaffy I can confirm this issue persists on both `4.1.10` and `4.1.11` versions

**Comment by ynechaev** [comment]
Bump

**Comment by cristhos** [comment]
For me, the bug disappears with this config.

```json
 "dependencies": {
    "@strapi/plugin-graphql": "^4.1.11",
    "@strapi/plugin-i18n": "4.1.11",
    "@strapi/plugin-users-permissions": "4.1.11",
    "@strapi/strapi": "4.1.11",
    "better-sqlite3": "7.4.6"
  },
```

**Comment by tugaybaltaci** [comment]
Stack:
```json
"dependencies": {
    "@strapi/plugin-graphql": "^4.1.11",
    "@strapi/plugin-i18n": "4.2.0-beta.2",
    "@strapi/plugin-users-permissions": "4.2.0-beta.2",
    "@strapi/strapi": "4.2.0-beta.2",
    "better-sqlite3": "7.4.6"
}
```
Query:
```graphql
mutation CreateCar($model: String!, $brand: String!) {
  createCar(
    data: {
      model: $model
      brand: $brand
    }
  ) {
    data {
      id
      attributes {
        model
        brand
      }
    }
  }
}
```
Getting this error even if the permissions works

Response: 
```json
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'get')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createCar"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read properties of undefined (reading 'get')",
            "    at Object.input (\\@strapi\\plugin-graphql\\node_modules\\@strapi\\utils\\lib\\sanitize\\index.js:33:10)",
            "    at resolve (\\@strapi\\plugin-graphql\\server\\services\\builders\\mutations\\collection-type.js:40:62)",
            "    at \\@strapi\\plugin-graphql\\server\\services\\content-api\\policy.js:26:12",
            "    at \\@strapi\\plugin-graphql\\server\\services\\content-api\\wrap-resolvers.js:67:11",
            "    at fieldDefinition.resolve (\\@strapi\\plugin-graphql\\server\\services\\content-api\\wrap-resolvers.js:109:40)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "createCar": null
  }
}
```

**Comment by derrickmehaffy** [comment]
I've not been able to reproduce this myself thus I'll set it as closed until we have more steps to reproduce.

**Comment by ynechaev** [comment]
@derrickmehaffy It is somehow related to the collection name. Try naming it exactly `Subscription`. I made several more tests, and yes, mutations work fine with other names and even `email` field name. But as soon as I create `Subscription` and use the following mutation, the error reproduces 100%:
```graphql
mutation AddSubscription($email: String!) {
  createSubscription(data:{email: $email}){
    data{
      id
      attributes{
        email
      }
    }
  }
}
```
```
{
  "email": "hello@world.com"
}
```

**Comment by DeividVeloso** [comment]
Why this issue was closed?

I am getting the same issue.

Could anyone help, please?

![image](https://github.com/strapi/strapi/assets/16343871/9c12921b-b516-4ad4-a19e-c0172e45d82b)
![image](https://github.com/strapi/strapi/assets/16343871/f24703fc-ad17-4a0a-90ae-a7f07c1f2a00)

**Comment by DeividVeloso** [comment]
it is creating, but I don't know why it is returning 

```
[
    {
        "message": "Forbidden access",
        "extensions": {
            "error": {
                "name": "ForbiddenError",
                "message": "Forbidden access",
                "details": {}
            },
            "code": "FORBIDDEN"
        }
    },
    {
        "message": "Forbidden access",
        "extensions": {
            "error": {
                "name": "ForbiddenError",
                "message": "Forbidden access",
                "details": {}
            },
            "code": "FORBIDDEN"
        }
    },
    {
        "message": "Forbidden access",
        "extensions": {
            "error": {
                "name": "ForbiddenError",
                "message": "Forbidden access",
                "details": {}
            },
            "code": "FORBIDDEN"
        }
    }
]
```

![image](https://github.com/strapi/strapi/assets/16343871/c44caea6-f56e-4d8e-9814-b11ebf3ccce4)

**Comment by DeividVeloso** [comment]
My permissions:

Wishlist
![image](https://github.com/strapi/strapi/assets/16343871/f9298674-5971-4f0b-8feb-63d1be9cfcf3)

User
![image](https://github.com/strapi/strapi/assets/16343871/7f6ba5e6-b2a4-4ebb-b1a2-2fd12e9dfbd4)

**Comment by DeividVeloso** [comment]
@ynechaev how did you solve that?

**Comment by ynechaev** [comment]
@DeividVeloso I did not manage to find a solution. I ended up renaming my collection to avoid internal errors.

**Comment by qraxiss** [comment]
I getting same error too.
