### ISSUE TITLE
Internal Server Error when trying to login

### ISSUE THREAD

**Issue by davidkobielski** [strapi/strapi#13278]
### Required System information

Strapi Version: 4.1.8
Operating System: Windows 10 and macOS Monterey 
Database: sqlite
Node Version: 16.14.2
NPM Version: 8.5.0

### Describe the bug

When trying to login using api it throws me an error.
It seems like Strapi is not compatible with redis rn.

### Steps to reproduce the behavior

1. send POST request with data as identifier and password to http://localhost:1337/api/auth/local 
2. *InternalServerError* - Hello it's me :)

### Expected behavior

I think I should let my user log into a service.

### Code snippets

```
error: Unexpected token '.' 
\node_modules\koa2-ratelimit\node_modules\redis\dist\index.js:42
...options?.modules
```
```
SyntaxError: Unexpected token '.'
at wrapSafe (internal/modules/cjs/loader.js:1047:16)
at Module._compile (internal/modules/cjs/loader.js:1097:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous> node_modules\koa2-ratelimit\src\RedisStore.js:21:15)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous>\node_modules\koa2-ratelimit\src\index.js:5:20)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10) 
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at \node_modules\@strapi\plugin-users-permissions\server\middlewares\rateLimit.js:4:21
at dispatch \node_modules\koa-compose\index.js:42:32)
at policiesMiddleware \node_modules\@strapi\strapi\lib\services\server\policy.js:24:11)
at dispatch \node_modules\koa-compose\index.js:42:32)
at \node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:33:12
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async \node_modules\@strapi\strapi\lib\middlewares\body.js:25:7 
```

### Additional context
I tried to downgrade the redis package to 3.0.2 and 3.1.2

**Comment by kirill3333** [comment]
@davidkobielski Hey, how do you resolve this issue?

**Comment by anthify** [comment]
@davidkobielski @kirill3333 any joy?

**Comment by davidkobielski** [comment]
@kirill3333 @anthify  Sorry for late response, I forgot to reply. I had to reinstall my entire node.js then It started to work.
