### ISSUE TITLE
Slow load time and crashes in production

### ISSUE THREAD

**Issue by heyalbertdev** [strapi/strapi#13280]
## Bug report
I have a blog application hosted on heroku. For some reason, when I trying accessing any of the content type, it loads for long period of time and if I reresh the dashboard. I get error from heroku `Application Error` and then when I check the logs, I had this message

### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:

### Describe the bug

```

022-05-10T02:36:36.284275+00:00 heroku[router]: at=info method=GET path="/content-manager/collection-types/api::author.author/1" host=crypto-university-strapi.herokuapp.com request_id=f5497e7b-dc94-463c-acff-8289fe5afc00 fwd="154.160.23.104" dyno=web.1 connect=0ms service=233ms status=200 bytes=1560014 protocol=https
2022-05-10T02:36:38.146311+00:00 app[web.1]: [2022-05-10 02:36:38.145] error: request entity too large
2022-05-10T02:36:38.146320+00:00 app[web.1]: PayloadTooLargeError: request entity too large
2022-05-10T02:36:38.146320+00:00 app[web.1]: at readStream (/app/node_modules/raw-body/index.js:156:17)
2022-05-10T02:36:38.146320+00:00 app[web.1]: at executor (/app/node_modules/raw-body/index.js:113:5)
2022-05-10T02:36:38.146321+00:00 app[web.1]: at new Promise (<anonymous>)
2022-05-10T02:36:38.146321+00:00 app[web.1]: at getRawBody (/app/node_modules/raw-body/index.js:112:10)
2022-05-10T02:36:38.146321+00:00 app[web.1]: at /app/node_modules/co-body/lib/json.js:41:14
2022-05-10T02:36:38.146321+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-05-10T02:36:38.146322+00:00 app[web.1]: at async /app/node_modules/@strapi/strapi/lib/middlewares/body.js:24:7
2022-05-10T02:36:38.146322+00:00 app[web.1]: at async /app/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
2022-05-10T02:36:38.146322+00:00 app[web.1]: at async /app/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
2022-05-10T02:36:38.146323+00:00 app[web.1]: at async cors (/app/node_modules/@koa/cors/index.js:95:16)
2022-05-10T02:36:38.146323+00:00 app[web.1]: at async /app/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
2022-05-10T02:36:38.146323+00:00 app[web.1]: at async session (/app/node_modules/koa-session/index.js:41:7)
2022-05-10T02:36:38.146323+00:00 app[web.1]: at async /app/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
```

### Expected behavior

I expected to see my posts in the collection  but it crashes each time I refresh the page and would have to restart the dyno again and . I'm not sure what is wrong. The version of strapi I am on is @4.1.0

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by heyalbertdev** [comment]
I upgraded to 4.1.7 and its still the same

**Comment by c3s4** [comment]
Hi, we hase a similar issue. We found out that is something related to double relations, at least in our use case.
Think about the typical "category" <--> "product" double relationship, in case we open a category with a bunch of product (~100) the admin page takes very long time to load and with a low end machine crashes with the same error.

We think that strapi is performing an huge number of queries.

**Comment by albertdugba** [comment]
> Hi, we have a similar issue. We found out that is something related to double relations, at least in our use case. Think about the typical "category" <--> "product" double relationship, in case we open a category with a bunch of product (~100) the admin page takes very long time to load and with a low end machine crashes with the same error.
> 
> We think that strapi is performing an huge number of queries.

What version of strapi are you currently running on ?  I had the same issue too and my fix around was to upgrade to the latest version [https://strapi.io/changelog](https://strapi.io/changelog) which fixed the issue for me. You can also look at their migration guide on how you can do that. [https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
