### ISSUE TITLE
Email confirmation is failed

### ISSUE THREAD

**Issue by klikkn** [strapi/strapi#13297]
## Bug report

Email confirmation is failed

### Required System information

- Node.js version: 14.17.6
- NPM version: 8.3.0
- Strapi version: 14.1.10
- Database: sqllite
- Operating system: macos

### Describe the bug

Email confirmation is failed

### Steps to reproduce the behavior

1. GET `/api/auth/email-confirmation?${confirmationLink}`

### Expected behavior

302 status

### Code snippets

```
   Undefined attribute level operator confirmationToken

      at processAttributeWhere (node_modules/@strapi/database/lib/query/helpers/where.js:82:13)
      at processWhere (node_modules/@strapi/database/lib/query/helpers/where.js:176:36)
      at node_modules/@strapi/database/lib/query/helpers/where.js:104:29
          at Array.map (<anonymous>)
      at Object.processWhere (node_modules/@strapi/database/lib/query/helpers/where.js:104:18)
      at Object.processState (node_modules/@strapi/database/lib/query/query-builder.js:234:29)
      at Object.getKnexQuery (node_modules/@strapi/database/lib/query/query-builder.js:271:12)
      at Object.execute (node_modules/@strapi/database/lib/query/query-builder.js:352:25)
      at Object.findOne (node_modules/@strapi/database/lib/entity-manager.js:121:10)
      at Object.findOne (node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
      at Object.emailConfirmation (node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:381:18)
```

### Additional context

`emailConfirmation` method is failed because `userService.fetch` applies only `id` after [User population MR](https://github.com/strapi/strapi/pull/11960) was merged.

**Comment by derrickmehaffy** [comment]
Am able to reproduce this issue on v4.1.10 using sendgrid
