### ISSUE TITLE
Create a content type with MySQL got error 168 - 'Unknown (generic) error from engine' from storage engine

### ISSUE THREAD

**Issue by chioio** [strapi/strapi#13421]
### Required System information

- Node.js version: `v14.19.2`
- NPM version: `v8.9.0`
- Strapi version: `4.1.12`
- Database: MySQL `v8.0`
- Operating system: OSX

### Describe the bug

When create a content type and save, then app restart got this error:
```bash
error: create table `tests` (`id` int unsigned not null auto_increment primary key, `title` varchar(255) null, `created_at` datetime(6) null, `updated_at` datetime(6) null, `published_at` datetime(6) null, `created_by_id` int unsigned null, `updated_by_id` int unsigned null) - ER_GET_ERRNO: Got error 168 - 'Unknown (generic) error from engine' from storage engine
Error: ER_GET_ERRNO: Got error 168 - 'Unknown (generic) error from engine' from storage engine
    at Query.Sequence._packetToError (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    --------------------
    at Protocol._enqueue (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/chio/GitHub/chioio/strapi-cms/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/chio/GitHub/chioio/strapi-cms/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/chio/GitHub/chioio/strapi-cms/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/chio/GitHub/chioio/strapi-cms/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/chio/GitHub/chioio/strapi-cms/node_modules/knex/lib/client.js:146:12)
    at /Users/chio/GitHub/chioio/strapi-cms/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/chio/GitHub/chioio/strapi-cms/node_modules/knex/lib/execution/transaction.js:358:12)
```

### Steps to reproduce the behavior

1. Create strapi app with mysql
2. Run app in `develop` mode
3. Create a content type and save
4. The app restart error

### Code snippets

`config/database.js`:
```js
module.exports = ({ env }) => ({
  connection: {
    client: 'mysql',
    connection: {
      host: env('DATABASE_HOST', '127.0.0.1'),
      port: env.int('DATABASE_PORT', 3306),
      database: env('DATABASE_NAME', 'strapi_cms'),
      user: env('DATABASE_USERNAME', 'root'),
      password: env('DATABASE_PASSWORD', 'strapi'),
      ssl: env.bool('DATABASE_SSL', false),
    },
  },
});
```
`deps`:
```json
  "dependencies": {
    "@strapi/plugin-i18n": "4.1.12",
    "@strapi/plugin-users-permissions": "4.1.12",
    "@strapi/strapi": "4.1.12",
    "mysql": "2.18.1"
  }
```

**Comment by derrickmehaffy** [comment]
This looks like either:

- There is no free space on the drive 
- MySQL doesn't have the permissions to actually write to the filesystem
- MySQL is being ran in a docker container with no writable volume

This error is one directly returned from the database itself, I would suggest validating you can actually connect to and perform read/write actions on the database as it's not a Strapi error.

Going to set this as closed as I'm about 99.999% confident this isn't a Strapi bug.

**Comment by mosenth** [comment]
hi,
i have this error in cpanel since upgraded miaradb to the last version,
rename query dosnt work and when i export a database and import right there again, i have this error too:
Error on rename of (table name) 1025 - 71c-4a830' (errno: 168 "Unknown (generic) error from engine")

**Comment by Gauravst** [comment]
> hi, i have this error in cpanel since upgraded miaradb to the last version, rename query dosnt work and when i export a database and import right there again, i have this error too: Error on rename of (table name) 1025 - 71c-4a830' (errno: 168 "Unknown (generic) error from engine")

yes , i have also this problem how to solve this problem... please help!!!
