### ISSUE TITLE
Forget password - User-Role relation MYSQL error

### ISSUE THREAD

**Issue by guillermodoghel** [strapi/strapi#1351]
**Informations**
- **Node.js version**:Node v8.11.1
- **npm version**: npm 6.1.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: 10.1.32-MariaDB
- **Operating system**:  mac os high sierra 10.13.4

**What is the current behavior?**

Forgot password flow.
Fist, I have done this https://github.com/strapi/strapi/issues/864#issuecomment-395600491 workarround to get the mailer work with my SMTP server. So far so good.

The mail is sent without problems, but in the next step it fails throwing the following error:

```
TypeError: Cannot read property 'split' of undefined
    at Child.forge.save.catch (/Users/MYUSERNAME/MYPROJECT/plugins/users-permissions/config/queries/bookshelf.js:119:49)
    at runCallback (timers.js:794:20)
```

The code on Auth.js goes like

`   
// bla bla, send mail
 // Update the user.
    await strapi.query('user', 'users-permissions').update(user);

    ctx.send({ ok: true });`

Debbuging, I found that there is some issue updating the forget password token inside user, 
bookshelf.js when doing: 

```
    return this.forge(search)
      .save(params, {
        patch: true
      }).catch((err) => {
        console.log(err);
        const field = _.last(_.words(err.detail.split('=')[0]));
        const error = { message: `This ${field} is already taken`, field };

        throw error;
      });

```
inside error I found that something is going wrong in the MYSQL query handling of the relation between user and role:

```
code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'name\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql: 'update `users-permissions_user` set `email` = \'some@mail.com.ar\', `id` = 2, `username` = \'user2\', `provider` = \'local\', `password` = \'$2a$10$uKvZgg.7mKLUUte/f0tVh.qRIvgnE1pEWEa.xu0nJHaEwepE8lPqm\', `resetPasswordToken` = \'8c2f3e42eb6c91c2a566b22350c9ae2600406e0dbee9d12332c8bed325e1e7fdae75923ee83a7d9acc12f21af03f2990ea91e22c2cd5344c8bc28da118ae661d\', `role` = `id` = 2, `name` = \'Authenticated\', `description` = \'Default role given to authenticated user.\', `type` = \'authenticated\' where `id` = 2' }

```
It seems that forge(?) is seeing user-role as one object, trying to do the modification inside one query.

**Comment by guillermodoghel** [comment]
Temporary fix: in Auth.js, on methods forgotPassword and changePassword

just BEFORE:
`      await strapi.query('user', 'users-permissions').update(user);`
do:
      `user.role =  user.role.id;`

**Comment by lauriejim** [comment]
It's cause we not omit relation during the update of the user. PR is coming to fix it.

**Comment by azerothl** [comment]
I still have the issue with strapi 3.0 stable version.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
