### ISSUE TITLE
Unable to edit user - TypeError w/ defaultLocale

### ISSUE THREAD

**Issue by dawnerd** [strapi/strapi#13526]
Fresh install, getting this error which points to the defaultLocale check when editing a user at /admin/content-manager/collectionType/plugin::users-permissions.user/1

```
main.7d89d97c.js:formatted:170261 TypeError: Cannot read properties of undefined (reading 'code')
    at CMEditViewInjectedComponents (main.7d89d97c.js:formatted:114575:93)
    at Ch (main.7d89d97c.js:formatted:168688:17)
    at ck (main.7d89d97c.js:formatted:171873:21)
    at bk (main.7d89d97c.js:formatted:171320:21)
    at ak (main.7d89d97c.js:formatted:171313:17)
    at Tj (main.7d89d97c.js:formatted:171296:21)
    at Lj (main.7d89d97c.js:formatted:171039:21)
    at main.7d89d97c.js:formatted:167749:37
    at exports.unstable_runWithPriority (main.7d89d97c.js:formatted:183612:24)
    at gg (main.7d89d97c.js:formatted:167725:20)
Ni @ main.7d89d97c.js:formatted:170261
main.7d89d97c.js:formatted:170261 Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at ErrorBoundary.render (1424.6b04bdc3.chunk.js:80843:15)
    at qi (main.7d89d97c.js:formatted:169456:86)
    at pi (main.7d89d97c.js:formatted:169446:20)
    at ck (main.7d89d97c.js:formatted:171936:17)
    at bk (main.7d89d97c.js:formatted:171320:21)
    at ak (main.7d89d97c.js:formatted:171313:17)
    at Tj (main.7d89d97c.js:formatted:171296:21)
    at Lj (main.7d89d97c.js:formatted:171039:21)
    at main.7d89d97c.js:formatted:167749:37
    at exports.unstable_runWithPriority (main.7d89d97c.js:formatted:183612:24)
Ni @ main.7d89d97c.js:formatted:170261
main.7d89d97c.js:formatted:183409 Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at ErrorBoundary.render (1424.6b04bdc3.chunk.js:80843:15)
    at qi (main.7d89d97c.js:formatted:169456:86)
    at pi (main.7d89d97c.js:formatted:169446:20)
    at ck (main.7d89d97c.js:formatted:171936:17)
    at bk (main.7d89d97c.js:formatted:171320:21)
    at ak (main.7d89d97c.js:formatted:171313:17)
    at Tj (main.7d89d97c.js:formatted:171296:21)
    at Lj (main.7d89d97c.js:formatted:171039:21)
    at main.7d89d97c.js:formatted:167749:37
    at exports.unstable_runWithPriority (main.7d89d97c.js:formatted:183612:24)
```

Issue is with these lines of code:

```js
const defaultLocale = locales.find((loc)=>loc.isDefault);
const currentLocale = get_default()(query, "plugins.i18n.locale", defaultLocale.code);
```

In chrome (102.0.5005.61 / macos) the locales variable is:

```js
[
code: "en"
createdAt: "2022-06-11T16:36:19.633Z"
id: 1
isDefault: false
name: "English (en)"
updatedAt: "2022-06-11T16:36:19.633Z"
]
```

```
"@strapi/plugin-i18n": "4.1.12",
"@strapi/plugin-users-permissions": "4.1.12",
"@strapi/strapi": "4.1.12",
"better-sqlite3": "7.4.6"
```

For reference I also got this when using a migrated codebase and was able to reproduce with a clean install to rule any of my code out.

**Comment by dawnerd** [comment]
I got it to work but I'm not sure what exactly tricked it into getting isDefault to true. Perhaps a better fix is to check if there's only one item in locales and make that default no matter what the setting?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by sibudar** [comment]
Hi was a fix for this issue found

**Comment by sibudar** [comment]
I just found a solution just now basically you have to set a default language for Internationalization

![strap 1](https://user-images.githubusercontent.com/38851239/175129595-b7165bec-4aa8-4078-8254-b5f0fd80a01e.png)

![strap2](https://user-images.githubusercontent.com/38851239/175129607-eadb5b8a-1eeb-4538-be5a-6fb6326c5a44.png)
