### ISSUE TITLE
Error in creation of new Strapi project

### ISSUE THREAD

**Issue by 1ncidental** [strapi/strapi#1355]
Great work on the new build
New issue with Strapi 12.3
When creating a new project, if you type "Strapi new" and forget to include the name of the project.
Rather than a message about correct syntax an exception error is thrown

```
strapi new
[2018-06-09T14:21:49.632Z] info Creating your application... It might take a few seconds.
/usr/lib/node_modules/strapi/bin/strapi-new.js:33
  const developerMode = cliArguments.dev !== undefined;
                                     ^

TypeError: Cannot read property 'dev' of undefined
    at Command.module.exports (/usr/lib/node_modules/strapi/bin/strapi-new.js:33:38)
    at Command.listener (/usr/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/lib/node_modules/strapi/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/lib/node_modules/strapi/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/lib/node_modules/strapi/bin/strapi.js:165:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```

**Comment by derrickmehaffy** [comment]
@1ncidental please use the proper bug report format.

**Comment by wisniewski94** [comment]
Add a flag --dev=true. It won't help much with installation anyway. See #https://github.com/strapi/strapi/issues/1927#issuecomment-432040364
