### ISSUE TITLE
Unknown 500 response for simple REST GET

### ISSUE THREAD

**Issue by Martin-Eckleben** [strapi/strapi#13552]
### Required System information

- Npm version: 8.11.0
- NodeJS version: 16.15.1
- Browser: Chrome Version 102.0.5005.115 (official build) (64-Bit)
( with --disable-web-security --disable-gpu flags(!) )
- Database: PostgreSQL 14.3 (docker)
- Operating system: Windows 10

### Describe the bug

I get a 500 response for a simple REST GET request for all entities of a content-type (I called machine-type).

![grafik](https://user-images.githubusercontent.com/1571683/173626974-ea476cb5-a8ac-4cd3-90a1-22cc1a392cdc.png)

![grafik](https://user-images.githubusercontent.com/1571683/173627290-810da761-c026-4570-91d8-1a3f33f1b42c.png)

Other similar requests work:

![grafik](https://user-images.githubusercontent.com/1571683/173627085-e7641622-585e-4bac-a1da-0d6ee92d5c35.png)

![grafik](https://user-images.githubusercontent.com/1571683/173627110-03f84a2e-ff6b-4f63-a156-8bec3dc638c8.png)

### Additional context

stdout logger logs:
```
[2022-06-14 17:58:23.873] error: Cannot read properties of undefined (reading 'find')
TypeError: Cannot read properties of undefined (reading 'find')
  at Object.find (C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\core-api\controller\collection-type.js:24:64)
  at dispatch (C:\Users\username\Desktop\git\mystrapi\node_modules\koa-compose\index.js:42:32)
  at returnBodyMiddleware (C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:24)
  at dispatch (C:\Users\username\Desktop\git\mystrapi\node_modules\koa-compose\index.js:42:32)
  at policiesMiddleware (C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\services\server\policy.js:24:11)
  at dispatch (C:\Users\username\Desktop\git\mystrapi\node_modules\koa-compose\index.js:42:32)
  at C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:33:12
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async serve (C:\Users\username\Desktop\git\mystrapi\node_modules\koa-static\index.js:59:5)
  at async returnBodyMiddleware (C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
  at async policiesMiddleware (C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
  at async C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\middlewares\body.js:25:7
  at async C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\middlewares\logger.js:22:5
  at async C:\Users\username\Desktop\git\mystrapi\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
  at async cors (C:\Users\username\Desktop\git\mystrapi\node_modules\@koa\cors\index.js:56:32)
```

Not a single custom class etc. in there.
Thats why I think it´s a real Strapi bug.

Successfull requests between look like this:
```
[2022-06-14 18:14:51.859] http: GET /api/category-pages?realm=1 (188 ms) 200
[2022-06-14 18:14:51.925] http: GET /api/realms/1 (186 ms) 200
[2022-06-14 18:14:53.038] http: GET /api/i18n/locales (121 ms) 200
[2022-06-14 18:14:53.063] error: Cannot read properties of undefined (reading 'find')
TypeError: Cannot read properties of undefined (reading 'find')
    at Object.find (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\core-api\controller\collection-type.js:24:64)
    at dispatch (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\koa-compose\index.js:42:32)
    at returnBodyMiddleware (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:24)
    at dispatch (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\koa-compose\index.js:42:32)
    at policiesMiddleware (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\services\server\policy.js:24:11)
    at dispatch (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\koa-compose\index.js:42:32)
    at C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:33:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async serve (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\koa-static\index.js:59:5)
    at async returnBodyMiddleware (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
    at async policiesMiddleware (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
    at async C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\middlewares\body.js:25:7
    at async C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\middlewares\logger.js:22:5
    at async C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
    at async cors (C:\Users\x-ecklebenm\Desktop\git\goa_mp_cms\node_modules\@koa\cors\index.js:56:32)
[2022-06-14 18:14:53.170] http: GET /api/realms/1 (130 ms) 200
[2022-06-14 18:19:55.531] http: GET /api/realms (171 ms) 200
```

**How can I proceed to analyse it?**
Tomorrow I´ll set up a fresh project and create a fresh content-type without localization and test.

**Comment by derrickmehaffy** [comment]
Strapi version was not specified and there is not enough information to reproduce. Please update once you have setup a fresh project to reproduce and share the code.

Thanks!

Reply back and we will review and reopen the issue.
