### ISSUE TITLE
Creating a content type named `rest` breaks the app

### ISSUE THREAD

**Issue by Antoine-lb** [strapi/strapi#13643]
### Required System information

- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: 4.2.0
- Database: ^5.0.2
- Operating system:  MacOS Monterey 12.4

### Describe the bug

If a content type called `rest` is created it breaks the app.

### Steps to reproduce the behavior

1. On a fresh install of Strapi with `npx create-strapi-app@latest my-project`
2. `yarn && yarn develop`
3. Log in with dummy credentials
4. Go to content type builder
5. Create a new content type (collection) called `rest` (`rests` for plurals)
6. Add any field to it (e.g. `name` with short string)
7. Save
8. In the logs you should have an error

### Logs

I leave you with the entire log of the first run of `yarn develop` to show you how **fast** I broke the app (not bragging 😎):

```
Building your admin UI with development configuration ...
Admin UI built successfully
[2022-06-27 20:13:53.130] info: The Users & Permissions plugin automatically generated a jwt secret and stored it in .env under the name JWT_SECRET.

 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Mon Jun 27 2022 20:13:53 GMT+0200 (Central Euro… │
│ Launched in        │ 1705 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 36130                                            │
│ Version            │ 4.2.0 (node v14.19.1)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available

One more thing...
Create your first administrator 💻 by going to the administration panel at:

┌─────────────────────────────┐
│ http://localhost:1337/admin │
└─────────────────────────────┘

[2022-06-27 20:13:54.009] http: GET /admin (22 ms) 200
[2022-06-27 20:13:54.126] http: GET /admin/runtime~main.de49adfd.js (13 ms) 200
[2022-06-27 20:13:54.131] http: GET /admin/main.3257934a.js (7 ms) 200
[2022-06-27 20:13:54.214] http: GET /admin/runtime~main.de49adfd.js (5 ms) 200
[2022-06-27 20:13:54.281] http: GET /admin/main.3257934a.js (3 ms) 200
[2022-06-27 20:13:57.280] http: GET /admin/project-type (1 ms) 200
[2022-06-27 20:13:57.289] http: GET /favicon.ico (2 ms) 200
[2022-06-27 20:13:57.364] http: GET /admin/1856.6a94980b.chunk.js (7 ms) 200
[2022-06-27 20:13:57.367] http: GET /admin/2077.5456ccd1.chunk.js (9 ms) 200
[2022-06-27 20:13:57.368] http: GET /admin/9158.e48d88af.chunk.js (5 ms) 200
[2022-06-27 20:13:57.369] http: GET /admin/7197.ed8d6752.chunk.js (4 ms) 200
[2022-06-27 20:13:57.410] http: GET /admin/2077.5456ccd1.chunk.js (5 ms) 200
[2022-06-27 20:13:57.436] http: GET /admin/1856.6a94980b.chunk.js (11 ms) 200
[2022-06-27 20:13:57.437] http: GET /admin/9158.e48d88af.chunk.js (8 ms) 200
[2022-06-27 20:13:57.438] http: GET /admin/7197.ed8d6752.chunk.js (6 ms) 200
[2022-06-27 20:13:57.492] http: GET /admin/fontawesome-css.59dc4459.chunk.js (14 ms) 200
[2022-06-27 20:13:57.493] http: GET /admin/en-json.0a5ba154.chunk.js (13 ms) 200
[2022-06-27 20:13:57.494] http: GET /admin/fr-json.84064a0b.chunk.js (10 ms) 200
[2022-06-27 20:13:57.797] http: GET /admin/fr-json.84064a0b.chunk.js (4 ms) 200
[2022-06-27 20:13:57.797] http: GET /admin/fontawesome-css.59dc4459.chunk.js (5 ms) 200
[2022-06-27 20:13:57.798] http: GET /admin/en-json.0a5ba154.chunk.js (4 ms) 200
[2022-06-27 20:13:57.805] http: GET /admin/fontawesome-css-all.b88d464e.chunk.js (6 ms) 200
[2022-06-27 20:13:57.806] http: GET /admin/content-type-builder-translation-en-json.e5110288.chunk.js (6 ms) 200
[2022-06-27 20:13:57.806] http: GET /admin/content-type-builder-translation-fr-json.aa6eeea8.chunk.js (6 ms) 200
[2022-06-27 20:13:57.806] http: GET /admin/email-translation-en-json.6da7e388.chunk.js (5 ms) 200
[2022-06-27 20:13:57.808] http: GET /admin/email-translation-fr-json.9f125db0.chunk.js (5 ms) 200
[2022-06-27 20:13:57.828] http: GET /admin/upload-translation-en-json.59269508.chunk.js (21 ms) 200
[2022-06-27 20:13:57.831] http: GET /admin/i18n-translation-en-json.85bc892c.chunk.js (16 ms) 200
[2022-06-27 20:13:57.831] http: GET /admin/i18n-translation-fr-json.0839d68d.chunk.js (16 ms) 200
[2022-06-27 20:13:57.831] http: GET /admin/upload-translation-fr-json.eb9b4f84.chunk.js (18 ms) 200
[2022-06-27 20:13:57.832] http: GET /admin/users-permissions-translation-en-json.3fe86528.chunk.js (16 ms) 200
[2022-06-27 20:13:57.833] http: GET /admin/users-permissions-translation-fr-json.172aa69f.chunk.js (8 ms) 200
[2022-06-27 20:13:57.987] http: GET /admin/email-translation-en-json.6da7e388.chunk.js (4 ms) 200
[2022-06-27 20:13:57.998] http: GET /admin/fontawesome-css-all.b88d464e.chunk.js (6 ms) 200
[2022-06-27 20:13:58.009] http: GET /admin/content-type-builder-translation-en-json.e5110288.chunk.js (6 ms) 200
[2022-06-27 20:13:58.036] http: GET /admin/fontawesome-js.252cc5f3.chunk.js (13 ms) 200
[2022-06-27 20:13:58.038] http: GET /admin/content-type-builder-translation-fr-json.aa6eeea8.chunk.js (5 ms) 200
[2022-06-27 20:13:58.070] http: GET /admin/email-translation-fr-json.9f125db0.chunk.js (6 ms) 200
[2022-06-27 20:13:58.071] http: GET /admin/upload-translation-en-json.59269508.chunk.js (7 ms) 200
[2022-06-27 20:13:58.119] http: GET /admin/init (20 ms) 200
[2022-06-27 20:13:58.120] http: GET /admin/i18n-translation-en-json.85bc892c.chunk.js (17 ms) 200
[2022-06-27 20:13:58.121] http: GET /admin/i18n-translation-fr-json.0839d68d.chunk.js (10 ms) 200
[2022-06-27 20:13:58.122] http: GET /admin/users-permissions-translation-en-json.3fe86528.chunk.js (8 ms) 200
[2022-06-27 20:13:58.127] http: GET /admin/upload-translation-fr-json.eb9b4f84.chunk.js (5 ms) 200
[2022-06-27 20:13:58.128] http: GET /admin/users-permissions-translation-fr-json.172aa69f.chunk.js (5 ms) 200
[2022-06-27 20:13:58.245] http: GET /admin/fontawesome-js.252cc5f3.chunk.js (36 ms) 200
[2022-06-27 20:13:58.254] http: GET /admin/cropper-css.0055cd53.chunk.js (19 ms) 200
[2022-06-27 20:13:58.482] http: GET /admin/fde9b1ad0670d29a2516.png (1 ms) 200
[2022-06-27 20:13:58.501] http: GET /admin/cropper-css.0055cd53.chunk.js (1 ms) 200
[2022-06-27 20:13:58.663] http: GET /admin/b997a22a2e0b87ef1fa2.ico (1 ms) 200
[2022-06-27 20:14:19.222] http: POST /admin/register-admin (175 ms) 200
[2022-06-27 20:14:19.330] http: GET /admin/6925.fafef528.chunk.js (16 ms) 200
[2022-06-27 20:14:19.332] http: GET /admin/7757.f6eb5e92.chunk.js (6 ms) 200
[2022-06-27 20:14:19.333] http: GET /admin/Admin-authenticatedApp.e7ed0550.chunk.js (4 ms) 200
[2022-06-27 20:14:19.380] http: GET /admin/6925.fafef528.chunk.js (5 ms) 200
[2022-06-27 20:14:19.385] http: GET /admin/Admin-authenticatedApp.e7ed0550.chunk.js (8 ms) 200
[2022-06-27 20:14:19.427] http: GET /admin/7757.f6eb5e92.chunk.js (1 ms) 200
[2022-06-27 20:14:19.589] http: GET /admin/information (25 ms) 200
[2022-06-27 20:14:19.620] http: GET /admin/users/me/permissions (29 ms) 200
[2022-06-27 20:14:19.638] http: GET /admin/users/me (44 ms) 200
[2022-06-27 20:14:20.734] http: GET /i18n/locales (14 ms) 200
[2022-06-27 20:14:20.831] http: GET /admin/15026a3d58aeb2828134.png (3 ms) 200
[2022-06-27 20:14:20.831] http: GET /admin/4800.d3ebc81d.chunk.js (2 ms) 200
[2022-06-27 20:14:20.832] http: GET /admin/Admin_homePage.8c00145e.chunk.js (2 ms) 200
[2022-06-27 20:14:20.888] http: GET /content-manager/components (11 ms) 200
[2022-06-27 20:14:20.906] http: GET /content-manager/content-types (15 ms) 200
[2022-06-27 20:14:20.913] http: GET /admin/4800.d3ebc81d.chunk.js (4 ms) 200
[2022-06-27 20:14:20.914] http: GET /admin/Admin_homePage.8c00145e.chunk.js (3 ms) 200
[2022-06-27 20:14:20.960] http: GET /admin/fb376b132d18bf4522ca.png (2 ms) 200
[2022-06-27 20:22:46.439] http: GET /admin/8469.3af1823d.chunk.js (4 ms) 200
[2022-06-27 20:22:46.450] http: GET /admin/4715.4588fdf5.chunk.js (12 ms) 200
[2022-06-27 20:22:46.456] http: GET /admin/9420.ba035f29.chunk.js (11 ms) 200
[2022-06-27 20:22:46.464] http: GET /admin/948.d64fb515.chunk.js (9 ms) 200
[2022-06-27 20:22:46.466] http: GET /admin/8681.aec05472.chunk.js (7 ms) 200
[2022-06-27 20:22:46.467] http: GET /admin/content-type-builder.b3139cb1.chunk.js (7 ms) 200
[2022-06-27 20:22:46.531] http: GET /admin/8469.3af1823d.chunk.js (5 ms) 200
[2022-06-27 20:22:46.532] http: GET /admin/4715.4588fdf5.chunk.js (4 ms) 200
[2022-06-27 20:22:46.533] http: GET /admin/9420.ba035f29.chunk.js (4 ms) 200
[2022-06-27 20:22:46.607] http: GET /admin/948.d64fb515.chunk.js (60 ms) 200
[2022-06-27 20:22:46.618] http: GET /admin/content-type-builder.b3139cb1.chunk.js (9 ms) 200
[2022-06-27 20:22:46.618] http: GET /admin/8681.aec05472.chunk.js (6 ms) 200
[2022-06-27 20:22:46.709] http: GET /content-type-builder/components (16 ms) 200
[2022-06-27 20:22:46.732] http: GET /content-type-builder/content-types (19 ms) 200
[2022-06-27 20:22:46.749] http: GET /content-type-builder/reserved-names (11 ms) 200
[2022-06-27 20:22:47.389] http: GET /admin/7589.577cf729.chunk.js (1 ms) 200
[2022-06-27 20:22:47.456] http: GET /admin/7589.577cf729.chunk.js (2 ms) 200
[2022-06-27 20:23:09.160] info: File created: /Users/lb/Desktop/my-project/src/api/rest/controllers/rest.js
[2022-06-27 20:23:09.161] info: File created: /Users/lb/Desktop/my-project/src/api/rest/services/rest.js
[2022-06-27 20:23:09.163] info: File created: /Users/lb/Desktop/my-project/src/api/rest/routes/rest.js
[2022-06-27 20:23:09.165] info: File created: /Users/lb/Desktop/my-project/src/api/rest/content-types/rest/schema.json
[2022-06-27 20:23:09.969] http: POST /content-type-builder/content-types (1931 ms) 201
[2022-06-27 20:23:09.973] info: The server is restarting

[2022-06-27 20:23:13.945] debug: ⛔️ Server wasn't able to start properly.
[2022-06-27 20:23:13.948] error: Url must be a string. Received undefined
TypeError: Url must be a string. Received undefined
    at normalize (/Users/lb/Desktop/my-project/node_modules/url-join/lib/url-join.js:32:15)
    at /Users/lb/Desktop/my-project/node_modules/url-join/lib/url-join.js:75:12
    at initGrant (/Users/lb/Desktop/my-project/node_modules/@strapi/plugin-users-permissions/server/bootstrap/index.js:55:19)
    at Object.module.exports [as bootstrap] (/Users/lb/Desktop/my-project/node_modules/@strapi/plugin-users-permissions/server/bootstrap/index.js:21:9)
    at Object.bootstrap (/Users/lb/Desktop/my-project/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:47)
    at Object.bootstrap (/Users/lb/Desktop/my-project/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:19)
    at async Strapi.runLifecyclesFunctions (/Users/lb/Desktop/my-project/node_modules/@strapi/strapi/lib/Strapi.js:479:5)
    at async Strapi.bootstrap (/Users/lb/Desktop/my-project/node_modules/@strapi/strapi/lib/Strapi.js:417:5)
    at async Strapi.load (/Users/lb/Desktop/my-project/node_modules/@strapi/strapi/lib/Strapi.js:426:5)
    at async Strapi.start (/Users/lb/Desktop/my-project/node_modules/@strapi/strapi/lib/Strapi.js:169:9)
error Command failed with exit code 1.
```

Quite inconvenient when you want to create a `rest`aurant like me. This used to work on v3, the bug most have been introduced in v4.

Have a grate day!

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1198
