### ISSUE TITLE
Populate conflicts for dynamic zone

### ISSUE THREAD

**Issue by giacomoforlani** [strapi/strapi#13666]
### Required System information

- Node.js version: 14.19.3
- NPM version: 8.12.2
- Strapi version: 4.2.2
- Database: sqlite
- Operating system: macOS Monterey 12.4

### Describe the bug
The function `convertPopulateObject` returns wrong populate params when there are two or more components inside the same dynamic zone that have the same attribute field names but with different types. 

The function is here: https://github.com/strapi/strapi/blob/master/packages/core/utils/lib/convert-query-params.js#L156

The problem is caused because properties inside the reduce function are overridden at every cycle.
```
const generatedFakeDynamicZoneSchema = {
        uid: `${schema.uid}.${key}`,
        attributes: attribute.components
          .sort()
          .map(uid => strapi.getModel(uid).attributes)
          .reduce((acc, componentAttributes) => ({ ...acc, ...componentAttributes }), {}),
};
``` 

### Steps to reproduce the behavior
1. Create the component Foo
```
{
  "collectionName": "components_foos",
  "info": {
    "displayName": "Foo"
  },
  "options": {},
  "attributes": {
    "user": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "admin::user"
    }
  }
}
```
2.  Create the component Bar
```
{
  "collectionName": "components_bars",
  "info": {
    "displayName": "Bar"
  },
  "options": {},
  "attributes": {
    "user": {
      "type": "string"
    }
  }
}
```
3. Create the content type Post
```
{
  "kind": "collectionType",
  "collectionName": "posts",
  "info": {
    "singularName": "post",
    "pluralName": "posts",
    "displayName": "Post",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "stack": {
      "type": "dynamiczone",
      "components": ["unit.foo", "unit.bar"]
    }
  }
}
```
4. Try to create content inside Post, adding a component Bar inside the stack
5. You'll receive the exception below because the `convertPopulateObject` function returns the populate params compatible for the Foo component (only because is the last of the list).
```
Error: Invalid populate field. Expected a relation, got string
    at Object.processPopulate (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/query/helpers/populate.js:83:13)
    at Object.processState (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/query/query-builder.js:235:32)
    at Object.getKnexQuery (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/query/query-builder.js:271:12)
    at Object.execute (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/query/query-builder.js:352:25)
    at Object.applyPopulate (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/query/helpers/populate.js:566:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.execute (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/query/query-builder.js:357:11)
    at async Object.findOne (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/entity-manager.js:118:22)
    at async Object.update (/Users/gforlani/Desktop/my-project/node_modules/@strapi/database/lib/entity-manager.js:256:22)
    at async Object.update (/Users/gforlani/Desktop/my-project/node_modules/@strapi/strapi/lib/services/entity-service/index.js:219:18)
```

**Comment by giacomoforlani** [comment]
Hi @derrickmehaffy , 
thank you for your reply.

Yes, the issue is exactly the same. I apologize but I was not able to find it. I close this one and follow that.
