### ISSUE TITLE
oneToOne relation under different name causes exception

### ISSUE THREAD

**Issue by GregorSondermeier** [strapi/strapi#13973]
### Required System information

- Node.js version: 14.18.2
- NPM version: 6.15.14
- Strapi version: 4.3.2
- Database: MySQL
- Operating system: Ubuntu 20.04

### Describe the bug

**TLDR**:

If a component has a oneToOne relation to a certain collection type, an exception is thrown by the backend when trying to edit the component instance unless the field name matches the target collection name. Further editing of the component instance is not possible.
If the field name is different from the target collection type name, this exception is thrown.
If the field name matches the target collection type name, everything works.

**More context**

We're currently trying to migrate from v3 to v4.

I have a component called **Bullet List**. That component has in its attributes a oneToOne relation to the collection type **site**. This relation is stored the field name **theme**.

```
{
  "collectionName": "components_content_block_bullet_lists",
  "info": {
    "name": "bulletList",
    "displayName": "Bullet List",
    "singularName": "bullet-list",
    "pluralName": "bullet-lists"
  },
  "attributes": {
    "theme": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::site.site"
    }
  }
}
```

When starting Strapi, the lookup table for this relation is successfully created under the name _component_content_block_bullet_lists_theme_link_.

However, when trying to edit an entity that contains the bullet list component in the admin ui, no form is shown because the backend throws an exception:

![image](https://user-images.githubusercontent.com/11959747/182813999-77c77e67-4c8c-4847-8e54-bd329f9c29d3.png)

```
[2022-08-04 09:23:33.809] error: Invalid populate field. Expected a relation, got undefined
Error: Invalid populate field. Expected a relation, got undefined
    at Object.processPopulate (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/database/lib/query/helpers/populate.js:83:13)
    at Object.processState (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/database/lib/query/query-builder.js:255:32)
    at Object.getKnexQuery (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/database/lib/query/query-builder.js:291:12)
    at Object.execute (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/database/lib/query/query-builder.js:388:25)
    at Object.applyPopulate (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/database/lib/query/helpers/populate.js:566:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.execute (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/database/lib/query/query-builder.js:393:11)
    at async Object.findOne (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/database/lib/entity-manager.js:118:22)
    at async Object.findOne (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
    at async Object.findOneWithCreatorRoles (/home/gregor/repos/acker-platform/projects/bitbucket/ackerdemia/acker-cms-strapi-4/node_modules/@strapi/plugin-content-manager/server/services/entity-manager.js:160:20)
```

When I change the name of the relation from **theme** to **site**, so that the name matches the targed collection type name **site**, it works. The lookup table for this relation is successfully created under the name _component_content_block_bullet_lists_site_link_.

```
{
  "collectionName": "components_content_block_bullet_lists",
  "info": {
    "name": "bulletList",
    "displayName": "Bullet List",
    "singularName": "bullet-list",
    "pluralName": "bullet-lists"
  },
  "attributes": {
    "site": { // <- notice "site" instead of "theme", matching the target collection type name.
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::site.site"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/11959747/182814619-1b094994-8611-446b-8fb2-972313b611cb.png)

The content type builder allows me to edit the field name for that relation so I would expect this to be supported.

![image](https://user-images.githubusercontent.com/11959747/182814951-ff3272ab-af3e-4ef2-988d-8ccd87eceef4.png)

Strapi v3 supported renamed relations. Strapi v4 seems to have problems in this regard. However, if that relation would be a oneToMany relation, it works for some reason. Only the oneToOne relation with a different field name than the target collection type name causes this issue.

### Expected behavior

It should be allowed and fully supported to define a field name for a oneToOne relation that is different from the target collection type name.

### Additional context

We're currently migrating from v3 to v4 and this is only one of the problems, but it seems to be the first one we stumbled across that does not seem to be discussed by the Strapi community already.

**Comment by GregorSondermeier** [comment]
Turns out it was a problem on our site. The oneToOne relation works fine as provided natively by Strapi.

We did not migrate our collection schemas completely, we overlooked some places where relations were still written in [v3 syntax](https://docs-v3.strapi.io/developer-docs/latest/development/backend-customization.html#relations) as opposed to [v4 syntax](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#relations)
