### ISSUE TITLE
TypeError: dep.getContext is not a function (strapi failing to build UI)

### ISSUE THREAD

**Issue by callum-gander** [strapi/strapi#13977]
## Bug report

TypeError: dep.getContext is not a function 

### Required System information

- Node.js version:
- NPM version: 14.0.0 and 14.19.1 both tried 
- Strapi version: 4.3.2 
- Database: PostgreSQL 14
- Operating system: Ubuntu WSL2

### Describe the bug

Whenever I run strapi develop, the admin UI build fails at around 10% due to TypeError: dep.getContext is not a function. Completely prevents me from using the latest version of Strapi. I've tried clearing the cache and build as well as building it in production mode, which also fails. The only solution so far has been to revert version, which is leading to unrelated issues. It seems to be a webpack compiling issue or potentially an issue with one of strapi's dependencies but I'm not sure

### Steps to reproduce the behavior

1. run `strapi develop`
2. admin UI will crash with the following error
```
Building your admin UI with development configuration...

● Webpack █████████████████████████ building (10%) 0/2 entries 1/2 dependencies 1/1 modules 0 active 
 

TypeError: dep.getContext is not a function
    at processDependencyForResolving (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/Compilation.js:1671:20)
    at processDependency (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/Compilation.js:1607:4)
    at Compilation._processModuleDependencies (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/Compilation.js:1690:44)
    at /home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/util/AsyncQueue.js:303:10
    at Hook.eval [as callAsync] (eval at create (/home/callum/coding/ino-creative-main-website/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/callum/coding/ino-creative-main-website/backend/node_modules/tapable/lib/Hook.js:18:14)
    at AsyncQueue._startProcessing (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/util/AsyncQueue.js:293:26)
    at AsyncQueue._ensureProcessing (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/util/AsyncQueue.js:269:9)
    at processImmediate (internal/timers.js:464:21)
TypeError: dep.getContext is not a function
    at processDependencyForResolving (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/Compilation.js:1671:20)
    at processDependency (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/Compilation.js:1607:4)
    at Compilation._processModuleDependencies (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/Compilation.js:1690:44)
    at /home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/util/AsyncQueue.js:303:10
    at Hook.eval [as callAsync] (eval at create (/home/callum/coding/ino-creative-main-website/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/callum/coding/ino-creative-main-website/backend/node_modules/tapable/lib/Hook.js:18:14)
    at AsyncQueue._startProcessing (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/util/AsyncQueue.js:293:26)
    at AsyncQueue._ensureProcessing (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/node_modules/webpack/lib/util/AsyncQueue.js:269:9)
    at processImmediate (internal/timers.js:464:21)
```

### Expected behavior

To be able to build the admin UI without this error

**Comment by kasonde** [comment]
Thanks for this: can you please pick out the actual version of the OS you're running in WSL? It'd be useful for us to attempt reproduction.

**Comment by callum-gander** [comment]
Apologies, I'm running Ubuntu 20.04 LTS on WSL2, hope this helps, the only way I was able to stop this error was to revert to @strapi/strapi 4.2.2

**Comment by gu-stav** [comment]
@callum-gander Could you share your package.json file with us? It looks like as if this is an error thrown by webpack itself while it is compiling the bundle.

**Comment by callum-gander** [comment]
```
{
    "name": "inocreative",
    "private": true,
    "version": "0.1.0",
    "description": "Ino Creative's backend API",
    "scripts": {
       ....
    },
    "dependencies": {
        "@strapi/admin": "4.1.7",
        "@strapi/codemods": "^1.0.2",
        "@strapi/design-system": "^1.2.1-beta.0",
        "@strapi/plugin-content-manager": "4.1.7",
        "@strapi/plugin-content-type-builder": "4.1.7",
        "@strapi/plugin-email": "4.1.7",
        "@strapi/plugin-i18n": "4.1.7",
        "@strapi/plugin-sentry": "^4.2.0",
        "@strapi/plugin-upload": "4.1.7",
        "@strapi/plugin-users-permissions": "4.1.7",
        "@strapi/provider-email-gmail-api": "npm:@bztes/strapi-provider-email-gmail-api@^4.0.1",
        "@strapi/strapi": "^4.2.2",
        "@strapi/utils": "^4.1.7",
        "async-retry": "^1.3.3",
        "axios": "^0.21.1",
        "console-browserify": "^1.2.0",
        "dotenv": "^8.2.0",
        "firebase-admin": "^10.1.0",
        "hcaptcha": "^0.1.0",
        "jest": "^27.4.5",
        "jose": "^4.8.3",
        "jwt-decode": "^3.1.2",
        "knex": "0.21.18",
        "koa-body": "^5.0.0",
        "koa-helmet": "^6.1.0",
        "lodash": "^4.17.21",
        "luxon": "^2.4.0",
        "ngrok": "^4.3.1",
        "node-fetch": "^2.6.1",
        "pg": "^8.6.0",
        "pg-connection-string": "^2.4.0",
        "qrcode": "^1.5.0",
        "raw-body": "^2.5.1",
        "react-helmet": "^6.1.0",
        "slugify": "^1.6.0",
        "sqlite3": "5.0.0",
        "strapi-plugin-measurement-protocol": "^1.0.1",
        "strapi-plugin-populate-deep": "^0.1.2",
        "strapi-plugin-rest-cache": "^4.2.4",
        "strapi-plugin-transformer": "^2.0.1",
        "strapi-provider-rest-cache-memory": "^4.2.4",
        "strapi-provider-upload-firebase-storage": "^1.0.0",
        "uuid": "^8.3.2",
        "validata-koa": "^4.0.14",
        "validator": "^13.7.0",
        "wait-on": "^6.0.0",
        "xero-node": "^4.19.1",
        "yup": "^0.32.11",
        "yup-phone": "^1.3.2"
    },
    "author": {
        "name": "Callum Gander, Ino Creative"
    },
    "strapi": {
        "uuid": "ed4c9ced-8fb7-4883-9b34-6ac67e24d58f",
    },
    "engines": {
        "node": ">=14.x <=16.x",
        "npm": "^6.0.0"
    },
    "license": "MIT",
    "devDependencies": {
        "@babel/core": "^7.16.7",
        "@babel/eslint-parser": "^7.16.5",
        "eslint": "^8.6.0",
        "eslint-plugin-security": "^1.4.0",
        "prettier": "^2.5.1",
        "supertest": "^6.1.6"
    },
    "jest": {
        "testPathIgnorePatterns": [
            "/node_modules/",
            ".tmp",
            ".cache"
        ],
        "testEnvironment": "node"
    }
}
```
This is my current package.json, which works, the only difference when it wasn't working was using strapi's latest version. I'm using npm not yarn btw, something which I know can cause issues

**Comment by callum-gander** [comment]
Is this still being looked at? I can't upgrade to the latest versions until this is resolved

**Comment by gu-stav** [comment]
@callum-gander Unfortunately, I didn't have the time yet to look into the issue. I'll try to reproduce it this week ...

**Comment by callum-gander** [comment]
Thanks, if you need anything else, let me know

**Comment by callum-gander** [comment]
Any updates on this? It's preventing me from updating to the latest version, which may fix other issues, sorry for the hassle

**Comment by callum-gander** [comment]
Closing this as latest version of Strapi seemingly worked fine compared to 4.2.2
