### ISSUE TITLE
Errors when installing @strapi/plugin-documentation

### ISSUE THREAD

**Issue by IHIutch** [strapi/strapi#14019]
### Required System information

- Node.js version: v16.14.0
- Yarn version: 1.22.18
- Strapi version: v4.1.7
- Database: postgres
- Operating system: MacOS Monterey v12.4 (21F79)

### Describe the bug

Running into several issues when installing `@strapi/plugin-documentation` (v4.3.2) on a recently fresh project (I've only created some simple content types)

First one appears to be an issue with the `@strapi/design-system` version:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/v2/Link' in '/Users/jbhutch/Sites/render-strapi-cloudinary/node_modules/@strapi/plugin-documentation/node_modules/@strapi/helper-plugin/build'
```

If install  `@strapi/design-system@1.1.0` manually, the above error goes away, but then when wbepack tries to build I get this a different error (that I don't know how to work around):
```
TypeError: Cannot read properties of undefined (reading 'api')
    at Object.getApiDocumentationPath (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/plugin-documentation/server/services/documentation.js:88:40)
    at Object.generateFullDoc (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/plugin-documentation/server/services/documentation.js:140:43)
    at Object.module.exports [as bootstrap] (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/plugin-documentation/server/bootstrap.js:55:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.bootstrap (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/strapi/lib/Strapi.js:468:5)
    at async Strapi.bootstrap (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/strapi/lib/Strapi.js:406:5)
    at async Strapi.load (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/strapi/lib/Strapi.js:415:5)
    at async Strapi.start (/path-to-project/render-strapi-cloudinary/node_modules/@strapi/strapi/lib/Strapi.js:163:9)
```

### Steps to reproduce the behavior

1. Run `yarn add @strapi/plugin-documentation`
2. Run `yarn develop`
3. See error

### Expected behavior

I can add the documentation plugin, restart my project, and navigated to my newly created swagger documentation via the Strapi Admin UI

### Additional context

I'm assuming I only need to run `yarn add @strapi/plugin-documentation` and `yarn develop` to get this plugin working. The readme isn't super clear. I have also added `src/extensions/documentation/config/settings.json` and tried some of the options from various places but with no luck.

**Comment by IHIutch** [comment]
Looks like this ended up being related to differing strapi package versions. Did a fresh install using the Strapi CLI and migrated that to my existing project. Now working like a charm
