### ISSUE TITLE
[4.3.3] bootup fails due to "merge.extractExtensionsFromSchema"

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#14062]
## Bug report

Hi, after upgrading to `4.3.3`, strapi fails to start:

[2022-08-10 16:29:15.396] debug: ⛔️ Server wasn't able to start properly.
[2022-08-10 16:29:15.398] error: merge.extractExtensionsFromSchema is not a function
TypeError: merge.extractExtensionsFromSchema is not a function

```
    at mergeSchemas (C:\Users\Luca\[...]\node_modules\@graphql-tools\schema\index.js:532:46)
    at buildMergedSchema (C:\Users\Luca\[...]\node_modules\@strapi\plugin-graphql\server\services\content-api\index.js:109:12)
    at Object.buildSchema (C:\Users\Luca\[...]\node_modules\@strapi\plugin-graphql\server\services\content-api\index.js:54:20)
    at Object.module.exports [as bootstrap] (C:\Users\Luca\[...]\node_modules\@strapi\plugin-graphql\server\bootstrap.js:26:6)
    at Object.bootstrap (C:\Users\Luca\[...]\node_modules\@strapi\strapi\lib\core\domain\module\index.js:40:47)
    at Object.bootstrap (C:\Users\Luca\[...]\node_modules\@strapi\strapi\lib\core\registries\modules.js:28:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Strapi.runLifecyclesFunctions (C:\Users\Luca\[...]\node_modules\@strapi\strapi\lib\Strapi.js:510:5)
    at async Strapi.bootstrap (C:\Users\Luca\[...]\node_modules\@strapi\strapi\lib\Strapi.js:448:5)
    at async Strapi.load (C:\Users\Luca\[...]\node_modules\@strapi\strapi\lib\Strapi.js:457:5)

```

Deleting `.cache` and `node_modules` did **not** help.

### Required System information

- Node.js version: 16.1.0
- NPM version: 8.5
- Strapi version: 4.3.3
- Database: psql
- Operating system: Windows 11

### Steps to reproduce the behavior

1. upgrade to 4.3.3
2. run strapi

### Dependencies

```json
 "dependencies": {
        "@_sh/strapi-plugin-ckeditor": "^1.1.1",
        "@strapi/plugin-graphql": "^4.3.3",
        "@strapi/plugin-i18n": "^4.3.3",
        "@strapi/plugin-users-permissions": "^4.3.3",
        "@strapi/provider-email-mailgun": "^4.3.3",
        "@strapi/provider-upload-aws-s3": "^4.3.3",
        "@strapi/strapi": "^4.3.3",
        "pg": "~8.7.3",
        "sharp": "^0.30.7",
        "strapi-plugin-config-sync": "^1.0.3"
    },
```

Id be happy to privately share our repo / code with the Strapi Team.

**Comment by anthonytison** [comment]
Same problem here

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/14048
