### ISSUE TITLE
`strapi-app` template failing using yarn

### ISSUE THREAD

**Issue by nk9** [strapi/strapi#14099]
### Required System information

- Node.js version: v16.14.2
- ~~NPM~~ yarn version: 3.1.1
- Strapi version: 4.3.4
- Database: Default, SQLite I guess
- Operating system: macOS 12.5

### Describe the bug

When I attempt to run the `strapi-app` app template locally, it fails with an error about `react-select`. (I'm attempting to follow instructions from the Fly.io deployment guide PR https://github.com/strapi/documentation/pull/982.) Here is the error:

```
🕙 18:30:56 ❯ yarn develop
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: @strapi/admin tried to access react-select, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: react-select (via "react-select/animated")
Required by: @strapi/admin@npm:4.3.4 (via /Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/)

Require stack:
- /Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/webpack.alias.js
- /Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/webpack.config.js
- /Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
- /Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/utils/index.js
- /Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/index.js
- /Users/nick/Projects/test/strapi-fly/.yarn/unplugged/@strapi-strapi-npm-4.3.4-47b8e573ce/node_modules/@strapi/strapi/lib/commands/builders/admin.js
- /Users/nick/Projects/test/strapi-fly/.yarn/unplugged/@strapi-strapi-npm-4.3.4-47b8e573ce/node_modules/@strapi/strapi/lib/commands/builders/index.js
- /Users/nick/Projects/test/strapi-fly/.yarn/unplugged/@strapi-strapi-npm-4.3.4-47b8e573ce/node_modules/@strapi/strapi/lib/commands/develop.js
- /Users/nick/Projects/test/strapi-fly/.yarn/unplugged/@strapi-strapi-npm-4.3.4-47b8e573ce/node_modules/@strapi/strapi/bin/strapi.js
    at Function.external_module_.Module._resolveFilename (/Users/nick/Projects/test/strapi-fly/.pnp.cjs:26834:55)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/webpack.alias.js:51:25
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/nick/Projects/test/strapi-fly/.yarn/cache/@strapi-admin-npm-4.3.4-a96a31a86e-a0c64f8199.zip/node_modules/@strapi/admin/webpack.alias.js:50:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (/Users/nick/Projects/test/strapi-fly/.pnp.cjs:26683:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

### Steps to reproduce the behavior

1. `yarn create strapi-app strapi-fly --quickstart`
2. `cd strapi-fly && yarn install`
3. `yarn develop`

**UPDATE:** I've been able to get everything working using npm, but yarn is always failing.

I have tried this twice and it has failed the same way both times. Here is the full log of the run:

```
🕙 18:29:25 ❯ yarn create strapi-app strapi-fly --quickstart
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 4s 654ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ commander@npm:6.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ create-strapi-app@npm:4.3.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 4s 860ms

Creating a quickstart project.
Creating a new Strapi application at /Users/nick/Projects/test/strapi-fly.
Creating files.
Error while installing dependencies:

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd /Users/nick/Projects/test/strapi-fly && yarn install


~/Projects/test via 🐍 v3.10.4 on ☁️  (us-east-2) took 14s
🕙 18:29:43 [🔴 ERROR] ❯ cd strapi-fly

Projects/test/strapi-fly via  v16.14.2 on ☁️  (us-east-2)
🕙 18:30:14 ❯ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0032: │ better-sqlite3@npm:7.4.6: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ debug@npm:4.1.1 is deprecated: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ formidable@npm:1.2.6 is deprecated: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
➤ YN0032: │ sharp@npm:0.30.7: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:5.0.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @babel/polyfill@npm:7.12.1 is deprecated: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
➤ YN0061: │ mailcomposer@npm:3.12.0 is deprecated: This project is unmaintained
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: │ buildmail@npm:3.10.0 is deprecated: This project is unmaintained
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0060: │ @strapi/admin@npm:4.3.4 provides immer (p5115a) with version 9.0.15, which doesn't satisfy what @strapi/helper-plugin requests
➤ YN0002: │ @strapi/admin@npm:4.3.4 doesn't provide react-is (pa3cd2), requested by styled-components
➤ YN0002: │ @strapi/admin@npm:4.3.4 doesn't provide typescript (p6d796), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @strapi/helper-plugin@npm:4.3.4 [11b89] doesn't provide react-is (pbd2cf), requested by styled-components
➤ YN0002: │ @strapi/helper-plugin@npm:4.3.4 [22c3d] doesn't provide react-is (p5adb6), requested by styled-components
➤ YN0002: │ @strapi/helper-plugin@npm:4.3.4 [a96a3] doesn't provide react-is (p67e86), requested by styled-components
➤ YN0002: │ @strapi/plugin-content-type-builder@npm:4.3.4 doesn't provide immer (paaa57), requested by @strapi/helper-plugin
➤ YN0002: │ @strapi/plugin-content-type-builder@npm:4.3.4 doesn't provide qs (pf6959), requested by @strapi/helper-plugin
➤ YN0060: │ @strapi/plugin-upload@npm:4.3.4 provides immer (p4a5c6) with version 9.0.15, which doesn't satisfy what @strapi/helper-plugin requests
➤ YN0002: │ @strapi/plugin-upload@npm:4.3.4 doesn't provide qs (p80e00), requested by @strapi/helper-plugin
➤ YN0002: │ @strapi/plugin-users-permissions@npm:4.3.4 doesn't provide immer (pc782a), requested by @strapi/helper-plugin
➤ YN0002: │ @strapi/plugin-users-permissions@npm:4.3.4 doesn't provide koa (p5daae), requested by grant-koa
➤ YN0002: │ @strapi/plugin-users-permissions@npm:4.3.4 doesn't provide mongoose (pfa5cd), requested by koa2-ratelimit
➤ YN0002: │ @strapi/plugin-users-permissions@npm:4.3.4 doesn't provide qs (pf8261), requested by @strapi/helper-plugin
➤ YN0002: │ @strapi/plugin-users-permissions@npm:4.3.4 doesn't provide redis (pe06c2), requested by koa2-ratelimit
➤ YN0002: │ @strapi/plugin-users-permissions@npm:4.3.4 doesn't provide sequelize (pfbe1f), requested by koa2-ratelimit
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 11s 276ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yaml@npm:1.10.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ ylru@npm:1.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yup@npm:0.32.11 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yup@npm:0.32.9 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 3s 914ms
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @fortawesome/fontawesome-free@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-common-types@npm:0.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-brands-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-solid-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @strapi/strapi@npm:4.3.4 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.24.1 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.54 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.30.7 must be built because it never has been before or the last one failed
➤ YN0007: │ better-sqlite3@npm:7.4.6 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:1.2.36 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 24s 617ms
➤ YN0000: Done with warnings in 39s 937ms
```

Then I run `yarn develop`, and get the error above.

### Expected behavior

I would expect strapi to start.

### Code snippets

I haven't changed anything.

### Possibly related

I'm not sure whether or not this bug is related: #13229

**Comment by derrickmehaffy** [comment]
Can't reproduce: 

https://www.loom.com/share/ae7288543061435bab178a9469f4d2e1

![image](https://user-images.githubusercontent.com/8593673/184649589-66022569-c026-4d5a-9fd9-4624a81c82d8.png)

Gonna mark this as closed for now until we get more information but I have a feeling this is a local cache issue or something. Also tested on my Mac (Intel) and my Windows machine and couldn't reproduce.

**Comment by pdavid0** [comment]
Same issue after upgrading to `4.4.3`
```bash
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Cannot find module 'react-select/animated'
Require stack:
- /Users/dev/workspace/app-cms/node_modules/@strapi/admin/webpack.alias.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/admin/webpack.config.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/admin/utils/index.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/admin/index.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/strapi/lib/commands/builders/admin.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/strapi/lib/commands/builders/index.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/strapi/lib/commands/build.js
- /Users/dev/workspace/app-cms/node_modules/@strapi/strapi/bin/strapi.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.resolve (node:internal/modules/cjs/helpers:108:19)
at /Users/dev/workspace/app-cms/node_modules/@strapi/admin/webpack.alias.js:51:25
at Array.reduce (<anonymous>)
at Object.<anonymous> (/Users/dev/workspace/app-cms/node_modules/@strapi/admin/webpack.alias.js:50:12)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by nk9** [comment]
I was able to get mine working with npm. Not a real solution, but does that workaround at least succeed for you?

**Comment by pdavid0** [comment]
I was able to make it work by adding the faulty dependancy to the root `package.json`, I'm in a monorepo using `yarn 3`.

@derrickmehaffy should I open a new issue ?

**Comment by derrickmehaffy** [comment]
> I was able to make it work by adding the faulty dependancy to the root `package.json`, I'm in a monorepo using `yarn 3`.
> 
> @derrickmehaffy should I open a new issue ?

Yes please
