### ISSUE TITLE
migration issue (4.1.7 -> 4.3.4): folder_path field

### ISSUE THREAD

**Issue by aquadesk** [strapi/strapi#14113]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.4
- Database: Mysql 8
- Operating system: Mac

### Describe the bug

I get this error starting strapi service after upgrading strapi 4.1.7 to 4.3.4

```
[2022-08-16 10:17:00.972] error: alter table `files` add index `upload_files_folder_path_index`(`folder_path`) - 
ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'folder_path' doesn't exist in table
```

`node_modules/@strapi/plugin-upload/server/content-types/file/schema.js`

this file contains the below at the end of the file which is expected.

```
    folderPath: {
      type: 'string',
      min: 1,
      required: true,
      private: true,
    },
  },
  // experimental feature:
  indexes: [
    {
      name: 'upload_files_folder_path_index',
      columns: ['folder_path'],
      type: null,
    },
  ],

```

I tried to reproduce this with sqlite but it works just fine. I think this only happens on Mysql I will try to reproduce with mysql later tonight.

### Steps to reproduce the behavior

[WIP]

### Expected behavior

start service without a problem

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

```
yarn run v1.22.19
$ PORT=1401 strapi develop
[2022-08-16 10:17:00.970] debug: ⛔️ Server wasn't able to start properly.
[2022-08-16 10:17:00.972] error: alter table `files` add index `upload_files_folder_path_index`(`folder_path`) - ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'folder_path' doesn't exist in table
Error: ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'folder_path' doesn't exist in table
    at Query.Sequence._packetToError (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/eng1/projects/aquadesk/web-code/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/eng1/projects/aquadesk/web-code/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/eng1/projects/aquadesk/web-code/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/eng1/projects/aquadesk/web-code/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/eng1/projects/aquadesk/web-code/node_modules/knex/lib/client.js:146:12)
    at /Users/eng1/projects/aquadesk/web-code/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/eng1/projects/aquadesk/web-code/node_modules/knex/lib/execution/transaction.js:358:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by aquadesk** [comment]
I've tried clean setup upgrading from 4.1 or 4.2 to 4.3.4 and found no problem.
so it must be one of my configurations for my monorepo.

thanks
