### ISSUE TITLE
Create-strapi-app doesn't create template project

### ISSUE THREAD

**Issue by MaximStone** [strapi/strapi#14114]
### Required System information

- Node.js version: 14.20.0
- NPM version: 6.14.17
- Strapi version: v4.3.0
- Database: -
- Operating system: Windows 11

### Describe the bug

Hello! When I use command `npx create-strapi-app@latest my-project --quickstart --template --ts` it shows me an error

```
Error: ⛔️ Template installation failed: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at createProject (C:\Users\maxst\AppData\Roaming\npm-cache\_npx\45072\node_modules\create-strapi-app\node_modules\@strapi\generate-new\lib\create-project.js:118:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createQuickStartProject (C:\Users\maxst\AppData\Roaming\npm-cache\_npx\45072\node_modules\create-strapi-app\node_modules\@strapi\generate-new\lib\create-quickstart-project.js:23:3)
```

### Steps to reproduce the behavior

1. Open CMD with administrator rights (just in case)
2. Type command `npx create-strapi-app@latest my-project --quickstart --template --ts` it shows me an error`
3. See error

### Expected behavior

Project template is installed and does work.

**Comment by derrickmehaffy** [comment]
For templates, you need to pass the name of the template, indeed this could be made clearer by telling the user they are missing the template.

**Comment by WalkingPizza** [comment]
> For templates, you need to pass the name of the template, indeed this could be made clearer by telling the user they are missing the template.

Just tested this out, the problem turns out to be the fact that Commander is parsing `--ts` as the name of the template to be used instead of parsing it as a CLI parameter.

**Comment by derrickmehaffy** [comment]
> > For templates, you need to pass the name of the template, indeed this could be made clearer by telling the user they are missing the template.
> 
> Just tested this out, the problem turns out to be the fact that Commander is parsing `--ts` as the name of the template to be used instead of parsing it as a CLI parameter.
> 
> I'd happily make a PR with a fix but I am not sure what the best course of action is in this scenario.
> Should we check that the template name matches a certain regex, or merely check that the name is not another CLI parameter?

I suppose yeah, it basically should have a regex check to exclude flags either `--something` or `-smth`

**Comment by Boegie19** [comment]
fixed in https://github.com/strapi/strapi/pull/14128
