### ISSUE TITLE
Can't load custom middleware using Typescript

### ISSUE THREAD

**Issue by 5ika** [strapi/strapi#14146]
### Required System information

- Node.js version: v16.13.1
- NPM version:  8.1.2
- Strapi version: v4.3.4
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug

With a TS installation, Strapi fails to load custom middleware because module returns `{default: ...}` instead of default export directly.

### Steps to reproduce the behavior

1. Create a new custom middleware in `src/middlewares/custom-middleware.ts`
  ```typescript
  export default (config, { strapi })=> {
    return (context, next) => {};
};
  ```
2. Set config for the custom middleware
  ```typescript
export default [
  ...
  {
    resolve: "./src/middlewares/custom-middleware",
    config: {
      enabled: true,
      conf: {},
    },
  },
  ];
   ````

### Expected behavior

Strapi starts successfuly and uses the custom middleware.

### Error

```
yarn run v1.22.17
$ strapi develop
Starting the compilation for TypeScript files in /home/tim/Projets/caroster/backend
{ resolvedMiddlewareFactory: { default: [Function (anonymous)] } }
[2022-08-19 17:41:19.629] debug: ⛔️ Server wasn't able to start properly.
[2022-08-19 17:41:19.630] error: Middleware "[object Object]": middlewareFactory is not a function
Error: Middleware "[object Object]": middlewareFactory is not a function
    at instantiateMiddleware (/home/tim/Projets/caroster/backend/node_modules/@strapi/strapi/lib/services/server/middleware.js:12:11)
    at resolveMiddlewares (/home/tim/Projets/caroster/backend/node_modules/@strapi/strapi/lib/services/server/middleware.js:82:20)
    at registerApplicationMiddlewares (/home/tim/Projets/caroster/backend/node_modules/@strapi/strapi/lib/services/server/register-middlewares.js:66:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.initMiddlewares (/home/tim/Projets/caroster/backend/node_modules/@strapi/strapi/lib/services/server/index.js:99:7)
    at async Strapi.bootstrap (/home/tim/Projets/caroster/backend/node_modules/@strapi/strapi/lib/Strapi.js:445:5)
    at async Strapi.load (/home/tim/Projets/caroster/backend/node_modules/@strapi/strapi/lib/Strapi.js:457:5)
    at async Strapi.start (/home/tim/Projets/caroster/backend/node_modules/@strapi/strapi/lib/Strapi.js:198:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

--- 

I've found a quick fix. I don't know if it works for every use-cases but one can add update those lines in `https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/services/server/middleware.js`:

```typescript
...
// From Line 121
  try {
    const module = require(modulePath);
    if(module.default) return module.default;
    return module;
}
...
```

**Comment by 5ika** [comment]
Closed by https://github.com/strapi/strapi/pull/14280

**Comment by imfrostii8** [comment]
Is this still solved ? 
I am using strapi version 4.9.1 and I have the exact same issue
