### ISSUE TITLE
Json Data Type not working properly on MySQL

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1425]
**Informations**
- **Node.js version**: v10.4.1
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.5
- **Database**: 10.2.15-MariaDB
- **Operating system**: Linux Mint 19 Beta (Ubuntu 18.04)

**What is the current behavior?**

The AdminUI will fail to save json data giving the following error (with DB debug on):

```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: 'accc022d-968b-4a63-b2cb-7ac671996850',
  sql:
   'select `users-permissions_user`.* from `users-permissions_user` where `users-permissions_user`.`id` = ? limit ?' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '0d53c8eb-a97f-4f87-a22d-bb974407bdb4',
  sql:
   'select `users-permissions_role`.* from `users-permissions_role` where `users-permissions_role`.`id` in (?)' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '1', 1 ],
  __knexQueryUid: '711ff811-dee8-4653-b5e9-f4fce8786fa7',
  sql:
   'select `testmodels`.* from `testmodels` where `testmodels`.`id` = ? limit ?' }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, { a: 5, b: 12 }, 2018-06-19T12:29:19.262Z, 1 ],
  __knexQueryUid: '1b032dcf-b8a2-48c8-8a19-d6167fefac72',
  sql:
   'update `testmodels` set `id` = ?, `data` = ?, `updated_at` = ? where `id` = ?' }
[2018-06-19T12:29:19.267Z] error update `testmodels` set `id` = 1, `data` = {"a":5,"b":12}, `updated_at` = '2018-06-19 05:29:19.262' where `id` = 1 - ER_BAD_FIELD_ERROR: Unknown column 'b' in 'field list'
```

If I manually put the following into the database (Using MySQL workbench) `{"a": 5, "b": 12}` and GET the data from the API I'm given it like so:

Data is properly formatted in the DB:
![image](https://user-images.githubusercontent.com/8593673/41597330-06295d7a-7382-11e8-87e6-5a1e8eb8df85.png)

API Response:
![image](https://user-images.githubusercontent.com/8593673/41597375-29c62326-7382-11e8-889e-6acf1f48b4ad.png)

**Steps to reproduce the problem**

Create a model with the json data type (I had issues doing so with the adminUI, another error when trying to restart).

Attempt to use the adminUI to send data, will fail to save.

**What is the expected behavior?**

Json Data shouldn't be formatted when sending to and retrieving from the database

**Suggested solutions**

I believe for the sending data the Knex query is not formatting the json properly

**Comment by derrickmehaffy** [comment]
Error when trying to create a model that has a the Json data type:

```
[2018-06-19T12:39:18.018Z] debug POST /content-type-builder/models/ (75 ms)
[2018-06-19T12:39:18.021Z] info The server is restarting

[2018-06-19T12:39:19.690Z] debug Server wasn't able to start properly.
TypeError: Cannot read property 'find' of undefined
    at routerChecker (/usr/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:28:28)
    at cb (/usr/lib/node_modules/strapi/lib/middlewares/router/utils/composeEndpoint.js:21:46)
    at _.forEach.value (/usr/lib/node_modules/strapi/lib/middlewares/router/index.js:25:52)
    at arrayEach (/usr/lib/node_modules/strapi/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/usr/lib/node_modules/strapi/node_modules/lodash/lodash.js:9342:14)
    at Object.initialize (/usr/lib/node_modules/strapi/lib/middlewares/router/index.js:24:9)
    at /usr/lib/node_modules/strapi/lib/middlewares/index.js:30:23
    at after (/usr/lib/node_modules/strapi/lib/middlewares/index.js:134:45)
    at /usr/lib/node_modules/strapi/node_modules/lodash/lodash.js:9997:23
    at Strapi.once (/usr/lib/node_modules/strapi/lib/middlewares/index.js:145:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:187:15)
    at Strapi.EventEmitter.emit (domain.js:442:20)
    at module.initialize.call.err (/usr/lib/node_modules/strapi/lib/middlewares/index.js:40:12)
    at Object.initialize (/usr/lib/node_modules/strapi/lib/middlewares/xss/index.js:42:7)
    at /usr/lib/node_modules/strapi/lib/middlewares/index.js:30:23
    at after (/usr/lib/node_modules/strapi/lib/middlewares/index.js:134:45)
    at /usr/lib/node_modules/strapi/node_modules/lodash/lodash.js:9997:23
    at Strapi.once (/usr/lib/node_modules/strapi/lib/middlewares/index.js:145:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:187:15)
    at Strapi.EventEmitter.emit (domain.js:442:20)
```
