### ISSUE TITLE
Generated Typescript plugin wont run due to server import

### ISSUE THREAD

**Issue by mattpfeffer** [strapi/strapi#14294]
### Required System information

Node.js version: 16.16.0
Yarn version: 1.22.19
Strapi version: 4.3.6
Database: sqlite (dev environment)
Operating system: MacOS 12.5.1

### Describe the bug

Following on from issues like #13998. I think i found another problem with the Typescript version of the default generated plugin config. Initially generating the plugin works as expected with no errors, as does `yarn build`. But when actually trying to run it via either `yarn develop` or `yarn start` I run into the following:

```
yarn run v1.22.19
$ strapi start

[2022-09-02 08:05:17.870] debug: ⛔️ Server wasn't able to start properly.
[2022-09-02 08:05:17.870] error: Could not load js config file /Users/user-name/Projects/project-name/src/plugins/plugin-name/strapi-server.js: Cannot find module './dist/server'
Require stack:
- /Users/user-name/Projects/project-name/src/plugins/plugin-name/strapi-server.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/utils/import-default.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/config-loader.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/index.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/Strapi.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/index.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/commands/start.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/bin/strapi.js
Error: Could not load js config file /Users/user-name/Projects/project-name/src/plugins/plugin-name/strapi-server.js: Cannot find module './dist/server'
Require stack:
- /Users/user-name/Projects/project-name/src/plugins/plugin-name/strapi-server.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/utils/import-default.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/config-loader.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/index.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/Strapi.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/index.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/commands/start.js
- /Users/user-name/Projects/project-name/node_modules/@strapi/strapi/bin/strapi.js
    at loadJsFile (/Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:20:11)
    at loadFile (/Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:37:14)
    at Object.loadPlugins (/Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:95:26)
    at async Strapi.loadPlugins (/Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/Strapi.js:319:5)
    at async Promise.all (index 2)
    at async Strapi.register (/Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/Strapi.js:355:5)
    at async Strapi.load (/Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/Strapi.js:456:5)
    at async Strapi.start (/Users/user-name/Projects/project-name/node_modules/@strapi/strapi/lib/Strapi.js:198:9)
error Command failed with exit code 1.
```
Now I realise that the following import is the culprit:

```js
\\ arc\plugins\plugin-name\strapi-server.js

'use strict';

module.exports = require('./dist/server');
```

But what I can work out is if it's because:

1. The `dist` folder hasn't compiled (It's not there)
2. It's meant to reference a different location like `/dist`
3. Webpack is meant to do some sort of transform on that path to point somewhere else, or
4. Some other error entirely

_P.S. I'm new to Strapi and still working out how to navigate the ecosystem so apologies if anything here is a bit daft._ 🙏🏻
### Steps to reproduce the behavior

```console
yarn strapi generate plugin
// Answer the relevant prompts

yarn build

yarn start|develop
```

### Expected behavior

I can change that line myself but my expectation was that `plugin generate` would create a working bolilerpate as it does with vanilla JS. Sorry if that's a faulty assumption.

### Additional context

All my `tsconfig.json` files are default, different Typescript versions don't seem to make any difference

**Comment by StrapiShaun** [comment]
Hello @mattpfeffer did you run the `install` and `build` commands in the plugin directory? Details can be found [here](https://docs.strapi.io/developer-docs/latest/development/typescript.html#develop-a-plugin-using-typescript)

**Comment by mattpfeffer** [comment]
@StrapiShaun Thanks for the reply. Yep, I realise can that be done and that's how I've been using it to get it working. I think my initial confusion extends somewhat from that page in the documentation, point two says: 

_"Run yarn build or npm run build in the plugin directory src/admin/plugins/[my-plugin-name] to build the admin panel including the plugin."_

In reality, this is not my experience. I have to either run a watcher on the plugin directory to build the server part or continually switch between the build in the plugin directory and the top level `yarn build` to get everything running. Perhaps that's intended, I just found that a bit counterintuitive.

It seems the plugin boilerplate is configured to build everything under `admin/src` with the project level build but `server/` needs to be built directly from the plugin directory.

I also can't see how `yarn build` in the plugin directory will also build the full admin panel given the following config, which just runs `tsc`:

```jsonc

// package.json

"scripts": {
        "develop": "tsc -w",
        "build": "tsc"
    },
```

```jsonc

// tsconfig.json

{
    "extends": "@strapi/typescript-utils/tsconfigs/server",

    "compilerOptions": {
        "outDir": "dist",
        "rootDir": "."
    },

    "include": [
        // Include the root directory
        "server",
        // Force the JSON files in the src folder to be included
        "server/**/*.json"
    ],

    "exclude": [
        "node_modules/",
        "dist/",

        // Do not include admin files in the server compilation
        "admin/",
        // Do not include test files
        "**/*.test.ts"
    ]
}
```

I also fully realise I could just have Friday brain 🤪

**Comment by kasonde** [comment]
Hi @mattpfeffer I'm curious to know what's going on. Was this a newly generated project? With typescript? Or did you move a JS project over to typescript? I didn't get that from the steps to reproduce

**Comment by mattpfeffer** [comment]
Fairly newly generated, I had done some of the usual things like setup one or two collection types but no major modifications. Both the project and plugin were typescript from scratch. I did try regenerating with similar result. I'll try again with blank project and report back.

**Comment by mattpfeffer** [comment]
Ok, so perhaps my initial report was a bit of a red herring, but I think it extended from an expectation I got from my reading of the documentation. Maybe this is turning into more of a docs feedback/feature request type situation 🤷🏼‍♂️

So if you read all the relevant sections in the docs about creating a project and then generating a plugin in typescript, you end up with a workflow something like this:

```sh
yarn create strapi-app --ts my-app

# select 'Quickstart' at the prompt

# the create script normally installs dependencies and handles the initial
# build, but if not run "yarn && yarn build" at the project root

yarn strapi generate plugin my-plugin

# select 'Typescript' at the prompt

nano ./config/plugins.ts

# add the following:
#
# export default {
#     'my-plugin': {
#         enabled: true,
#         resolve: './src/plugins/my-plugin'
#      },
# }

cd src/plugins/my-plugin/

yarn && yarn build

cd ../../../

yarn start
# or
yarn develop
```

That will work on first run, which is fine.

The problem is, when you're building a plugin, you're often building the admin parts and server parts simultaneously. The documentation (specifically [this section](https://docs.strapi.io/developer-docs/latest/development/typescript.html#develop-a-plugin-using-typescript)) leaves you with the impression that running `yarn build` will rebuild both the plugin and admin panel.

In reality it doesn't do this though, it just compiles the anything .ts in the `/server` section of the plugin. So to compile the admin part you still have to build that from the project root. You basically end up continually building in two places. 

To get around this, I do the following:

```sh
# my-app/
yarn develop --watch-admin

# my-app/src/plugins/my-plugin/
yarn develop   # 'tsc -w'
```

The second part is necessary because the top-level `yarn develop` will trigger on any file changes but it wont recompile the files under `my-plugin/server`. Same goes for `yarn build`.

Am I missing something obvious? If this is the intended behaviour, that's totally fine but the docs probably could reflect that I guess. It was because of that I started to think 'I must be doing this wrong, needs to be done from the project root'. So i deleted the `my-plugin/dist` folder and tried at the project level which resulted in the original error.

**Comment by ahmedsliman** [comment]
Hi @mattpfeffer 

Thanks for your explanation, 

when I run `yarn build` inside the plugin directory I got this error 

```
server/controllers/my-controller.ts:6:8 - error TS2339: Property 'plugin' does not exist on type 'StrapiInterface'.
6       .plugin('todo')
```

Any idea if there is a missing step or so?

**Comment by mattpfeffer** [comment]
> ahmedsliman

Sorry I didn't run into that issue, could be a seperate thing. Was this on a new or existing project? Have you modified anything?

**Comment by kasonde** [comment]
Hi @mattpfeffer are you aware of steps 7 and 8 in [our docs about this](https://docs.strapi.io/developer-docs/latest/development/plugins-development.html#create-a-plugin)? Did you do that and still experience failure?

**Comment by kasonde** [comment]
Hi @StrapiShaun I think this could be a useful suggesting from @mattpfeffer. 

> Am I missing something obvious? If this is the intended behaviour, that's totally fine but the docs probably could reflect that I guess. It was because of that I started to think 'I must be doing this wrong, needs to be done from the project root'. So i deleted the my-plugin/dist folder and tried at the project level which resulted in the original error.

@mattpfeffer I've read your response and as you mentioned yes you have to run npm install and build the plugin as well as your project. I'll go ahead and close this for now as the instructions are in the docs for anyone who might experience the same.
