### ISSUE TITLE
Media Library UI: TypeError: Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [strapi/strapi#14308]
# Bug report

I have problems accessing the Media Library from the UI in production (api hosted on AWS), the page goes blank and shows me the following error.

I did a test locally (localhost) and I can enter without problems or by building the API locally.

```shell
react_devtools_backend.js:4026 TypeError: Cannot read properties of null (reading 'split')
    at Ve (main.916ce3c2.js:24301:2016)
    at w0 (main.916ce3c2.js:25171:56065)
    at Mp (main.916ce3c2.js:25175:9437)
    at Tp (main.916ce3c2.js:25175:1012)
    at Ef (main.916ce3c2.js:25175:939)
    at bf (main.916ce3c2.js:25175:789)
    at B0 (main.916ce3c2.js:25173:11608)
    at main.916ce3c2.js:25171:40527
    at w.unstable_runWithPriority (main.916ce3c2.js:25203:3974)
    at qc (main.916ce3c2.js:25171:40295)
```

<img width="1390" alt="Untitled" src="https://user-images.githubusercontent.com/21962584/188302945-be270936-10e1-4383-b5a9-40a0f6668116.png">

- Node.js version: v14
- Strapi version: 4.3.6
- Database: postgres
- Operating system: MAC

## Packages:
```json
  "@strapi/plugin-i18n": "4.3.6",
  "@strapi/plugin-users-permissions": "4.3.6",
  "@strapi/provider-upload-aws-s3": "4.3.6",
  "@strapi/strapi": "4.3.6"
```

**Comment by ChrisMichaelPerezSantiago** [comment]
Bug fixed. 

For unknown reasons the error was caused by broken images. After removing them using *postman* the problem was solved.
