### ISSUE TITLE
[Bug] Cannot get Strapi@latest to run with Typescript (step 1 of Getting Started)

### ISSUE THREAD

**Issue by palbrecht1** [strapi/strapi#14305]
### Link to the documentation page or resource

https://docs.strapi.io/developer-docs/latest/getting-started/introduction.html

### Describe the bug

If you follow the Getting Started documentation but decides not to use the `--quickstart` flag, nor to use the _Starters_, you are unable to start Strapi.

You can replicate this issue by running `npx create-strapi-app@latest .` and going through the setup wizard, **make sure to pick TypeScript** and **MySQL**.

I've tried with both MySQL and PostgreSQL and it resulted in the same error message.

```
[2022-09-03 10:19:38.871] debug: ⛔️ Server wasn't able to start properly.
[2022-09-03 10:19:38.872] error: Unknown dialect undefined
Error: Unknown dialect undefined
    at getDialectClass (C:\Users\pablo\Documents\GitHub\strapi\node_modules\@strapi\database\lib\dialects\index.js:12:13)
    at getDialect (C:\Users\pablo\Documents\GitHub\strapi\node_modules\@strapi\database\lib\dialects\index.js:19:23)
    at new Database (C:\Users\pablo\Documents\GitHub\strapi\node_modules\@strapi\database\lib\index.js:27:20)
    at Function.Database.init (C:\Users\pablo\Documents\GitHub\strapi\node_modules\@strapi\database\lib\index.js:77:35)
    at Strapi.bootstrap (C:\Users\pablo\Documents\GitHub\strapi\node_modules\@strapi\strapi\lib\Strapi.js:395:30)
    at Strapi.load (C:\Users\pablo\Documents\GitHub\strapi\node_modules\@strapi\strapi\lib\Strapi.js:460:16)
    at async Strapi.start (C:\Users\pablo\Documents\GitHub\strapi\node_modules\@strapi\strapi\lib\Strapi.js:198:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
```

### Additional context

```
$ npm version
{
  npm: '6.14.16',
  ares: '1.18.1',
  brotli: '1.0.9',
  cldr: '40.0',
  icu: '70.1',
  llhttp: '2.1.4',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.19.1',
  openssl: '1.1.1n',
  tz: '2021a3',
  unicode: '14.0',
  uv: '1.42.0',
  v8: '8.4.371.23-node.85',
  zlib: '1.2.11'
}
```

### Suggested improvements or fixes

I tried some basic console logging on Strapi.bootstrap and it seems that the database config object is never loaded, this issue doesn't seem to be present in the non typescript version.

**Comment by rachasakr** [comment]
Seems like this is caused by different slash things between Windows and other OS. I've opened [an issue](https://github.com/strapi/strapi/issues/14306) that you might want to check it out BTW.

**Comment by lessborders** [comment]
Yeah Strapi TS setup is broken atm

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/13237
