### ISSUE TITLE
New release - Updating from 4.3.6 to 4.3.7 - SQLite

### ISSUE THREAD

**Issue by tit1** [strapi/strapi#14340]
### Required System information

- Node.js version: 16.4.2
- YARN version: 1.3.2
- Strapi version: 4.3.7
- Database: SQLite
- Operating system: Mac OS

### Describe the bug

Im upgrading a dev environment form 4.3.6 to 4.3.7 and it appears that the migrations are not compatible with SQLite; please see below. I am getting around these issues by opening the DB directly adding the field required by the migration and adding the data myself. 

### Steps to reproduce the behavior

Update package.json: 
```
  "dependencies": {
    "@strapi/plugin-i18n": "4.3.7",
    "@strapi/plugin-users-permissions": "4.3.7",
    "@strapi/strapi": "4.3.7",
    "better-sqlite3": "7.4.6",
    "strapi-plugin-import-export-entries": "^1.14.1"
  },
```
Run: Yarn 
Run: yarn build
Run yarn dev*

*I changed the start command to yarn dev to be in line with my other projects.

```
  "scripts": {
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
```
### Expected behavior

The database will be upgraded to the new scheme.

### Screenshots

```
yarn run v1.3.2
warning ../../../package.json: No license field
$ strapi develop
[2022-09-07 09:44:31.783] debug: ⛔️ Server wasn't able to start properly.
[2022-09-07 09:44:31.785] error: alter table `admin_permissions_role_links` add column `id` integer not null - Cannot add a NOT NULL column with default value NULL
SqliteError: alter table `admin_permissions_role_links` add column `id` integer not null - Cannot add a NOT NULL column with default value NULL
    at Client_BetterSQLite3._query (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)
    at executeQuery (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/client.js:146:12)
    at /Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_BetterSQLite3.trxClient.query (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/runner.js:224:21)
    at Runner.queryArray (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/runner.js:276:31)
    at ensureConnectionCallback (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
    at Runner.ensureConnection (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/runner.js:307:20)
    at async Runner.run (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.alterTable (/Users/thomastrutt/site_base/strapi_disney/backend/node_modules/@strapi/database/lib/schema/builder.js:264:5)
    at async /Users/thomastrutt/site_base/strapi_disney/backend/node_modules/@strapi/database/lib/schema/builder.js:101:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by kasonde** [comment]
Hi 👋🏾 This has been fixed in v4.3.8 released a little less than an hour ago. Thanks for the report.
