### ISSUE TITLE
Documentation Plugin Cannot read properties of undefined (reading 'contentTypes') when uninstalling plugin users-permissions 

### ISSUE THREAD

**Issue by fabianmu** [strapi/strapi#14349]
### Required System information

- Node.js version: v16.17.0
- YARN version: 1.22.19
- Strapi version: 4.3.6
- Database: sqlite and mysql
- Operating system: macos 12.5.1

### Steps to reproduce the behavior

1. `yarn remove @strapi/plugin-users-permissions`  
2. `yarn build`  
3. `yarn develop`  

[2022-09-08 06:35:00.513] debug: ⛔️ Server wasn't able to start properly.
[2022-09-08 06:35:00.514] error: Cannot read properties of undefined (reading 'contentTypes')
TypeError: Cannot read properties of undefined (reading 'contentTypes')
    at /Users/fabian/code/xxx/node_modules/@strapi/plugin-documentation/server/services/documentation.js:109:53
    at Array.map (<anonymous>)
    at Object.getPluginAndApiInfo (/Users/fabian/code/xxx/node_modules/@strapi/plugin-documentation/server/services/documentation.js:104:41)
...

I then added the following to `src/extensions/documentation/config/settings.json` but that did not work.

```
"x-strapi-config": {
    "path": "/documentation",
    "showGeneratedFiles": true,
    "generateDefaultResponse": true,
    "plugins": ["upload"]
  },
```

I then went into the plugin code and added a console.log
```
getPluginAndApiInfo() {
      const plugins = _.get(config, 'x-strapi-config.plugins');
      console.log(plugins)
```

which gives `[ 'upload', 'upload', 'users-permissions' ]` and that's indicating that `x-strapi-config` from `src/extensions/documentation/config/settings.json` is ignored. Perhaps relates to #14020

### Expected behavior

Either: Generation of Documentation simply work when @strapi/plugin-users-permissions is not installed
Or it should respect the x-strapi-config.plugins setting to exclude that plugin via config.

**Comment by kasonde** [comment]
Hey @marcoautiero and @emilieringwald I've tagged this to both your squads. I wasn't quite sure which it falls under.

**Comment by dohoangtung** [comment]
Same issue here! Is there a workaround for this?

**Comment by tlinneberger** [comment]
+1

**Comment by edverillo** [comment]
Experiencing the same on Strapi 5
