### ISSUE TITLE
createCoreRouter breaks in plugin

### ISSUE THREAD

**Issue by ivanThePleasant** [strapi/strapi#14438]
## Bug report
When generating new Content Type for a Plugin via CLI, the automatically added routes factory file breaks the plugin and crashes the application. Presumably, this is happening because `createCoreRouter` is being called earlier than it should.

### Required System information

- Node.js version: 16.14.2
- Yarn version: 1.22.18
- Strapi version: 4.3.8
- Database: SQLite
- Operating system: MacOS Monterey 12.5

### Describe the bug

When generating new plugin and then generating new content type for the plugin via the CLI, factories for routes, services and controllers are created. It seems that routes factory crashes the application. If the routes are declared manually like shown below, everything works as expected. But, if `/routes/index.js` exports the contents of the factory file, an error occurs if you are trying to list anything via CLI or launch the app:

```
'/routes/index.js' - example of routes declared manually

module.exports = [
    {
      method: 'GET',
      path: '/',
      handler: 'deployment.find',
    },
]
```
```
'/routes/index.js' - example of routes exported from factory file

const deployment = require('./deployment')

module.exports = deployment
```
```
TypeError: Cannot read properties of undefined (reading 'kind')
    at isSingleType (/Users/Katsudev/Strapi/dev/test/node_modules/@strapi/utils/lib/content-types.js:90:25)
    at createRoutes (/Users/Katsudev/Strapi/dev/test/node_modules/@strapi/strapi/lib/core-api/routes/index.js:6:7)
    at Object.get routes [as routes] (/Users/Katsudev/Strapi/dev/test/node_modules/@strapi/strapi/lib/factories.js:59:31)
    at /Users/Katsudev/Strapi/dev/test/node_modules/lodash/lodash.min.js:54:69
    at Ke (/Users/Katsudev/Strapi/dev/test/node_modules/lodash/lodash.min.js:41:281)
    at Ve (/Users/Katsudev/Strapi/dev/test/node_modules/lodash/lodash.min.js:42:206)
    at /Users/Katsudev/Strapi/dev/test/node_modules/lodash/lodash.min.js:41:323
    at /Users/Katsudev/Strapi/dev/test/node_modules/lodash/lodash.min.js:54:66
    at Ke (/Users/Katsudev/Strapi/dev/test/node_modules/lodash/lodash.min.js:41:281)
    at /Users/Katsudev/Strapi/dev/test/node_modules/lodash/lodash.min.js:124:37

```

### Steps to reproduce the behavior

1. Install latest version of Strapi via CLI using quickstart
2. Shut down the application straight after install and generate a new plugin via CLI
3. Generate a new content type for the plugin via CLI
4. Make sure that all the imports and exports in the `content-types`, `routes`, `controllers` and `services` folders are correct
5. Create a `plugins.js` file in the root config folder of your Strapi app and enable the plugin
6. Try to list anything (routes, controllers) via CLI or try launching the app, you should get an error

### Expected behavior

Everything should work correctly after generating new plugin and content-type via CLI

**Comment by derrickmehaffy** [comment]
Not sure if this is expansion or DX honestly since it's plugin related but the issue likely comes from the core.

**Comment by lucasff** [comment]
[2022-09-20 22:55:23.698] error: Cannot read properties of undefined (reading 'routes')
TypeError: Cannot read properties of undefined (reading 'routes')
    at Object.addCreateLocalizationAction (node_modules/@strapi/plugin-i18n/server/services/core-api.js:184:41)
    at @strapi/plugin-i18n/server/register.js:78:22
    at Array.forEach (<anonymous>)

**Comment by emilieringwald** [comment]
Hey @ivanThePleasant ! Thanks for the ticket, we added it in the Expansion squad's backlog.

**Comment by Eggwise** [comment]
Well.. What is the status on this ? Developers cannot create decent plugins now

**Comment by Eggwise** [comment]
@emilieringwald What is the status ? This is blocking our development for major companies. Seems like a basic think that needs to work.

**Comment by ynssenem** [comment]
> @emilieringwald What is the status ? This is blocking our development for major companies. Seems like a basic think that needs to work.

Yes, I am waiting for this to be fixed.

**Comment by derrickmehaffy** [comment]
Our CTO Alex was working on this before he left for paternity leave, once he gets back the dev work should pick back up.

**Comment by antokhio** [comment]
https://discord.com/channels/811989166782021633/1073553042152112128 discord thread about that with workarounds

**Comment by Eggwise** [comment]
What is the status on this ?

**Comment by Eggwise** [comment]
A workaround:

https://discord.com/channels/811989166782021633/1073553042152112128/1083914151765745734

**Comment by Eggwise** [comment]
@ivanThePleasant 

PR: https://github.com/strapi/strapi/pull/16053

please check it out and fix it 🙏

**Comment by Eggwise** [comment]
Still pending......

**Comment by alexandrebodin** [comment]
The original PR was updated today and is ready to review. It should be reviewed in the upcoming days https://github.com/strapi/strapi/pull/14456

**Comment by daan-ef2** [comment]
Still doesnt work in 4.11.1? I just created a new plugin from scratch and added a content type via CLI with all bootstrapping files.

_export default factories.createCoreRouter('plugin::tenants.tenant');_

Breaks the application after running a build:
_TypeError: Cannot read properties of undefined (reading 'type')
    at ./node_modules/@strapi/strapi/lib/services/server/register-routes.js:70:30_

Am I missing something?

**Comment by sevensinjai** [comment]
I came across with the similar situation.
I am working on v4.14.0, i just created a new plugin and added a content type via CLI with all bootstrapping files.

but when i run `strapi routes:list`, there is not routes for the content type that i have just created. I am checking why, but my gut guess is that these two are related.

**Comment by derrickmehaffy** [comment]
Reopening this as it's still broke

**Comment by kevinvugts** [comment]
@derrickmehaffy what is the status of this? It's still present in the latest version..

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy what is the status of this? It's still present in the latest version..

Still broken as of now I believe and I don't think we can fix this in v4 at the moment and might be something we can address in Strapi v5

**Comment by unrevised6419** [comment]
Also got into this problem, but I figured it out somehow. I'm using v4, but I suppose in v5 is the same.

> [!NOTE]
> All this is based on what I investigated and experimented for a few hours to understand all possible cases, what works what not.

All the code changes are happening in this file

```
src/plugins/whitelabel/server/routes/index.ts
```

In a plugin, you can either return an array of routes (example below) but it comes with downsides:

- Route is accessed via URL `/{plugin-name}/${handler}` (maybe not a downside)
- Route is not visible in User Permissions, so it does not allow in any way to control permission. (probably because is not registered as a `content-api` route

```ts
export default [
	{
		method: 'GET',
		path: '/affiliates/:id',
		handler: 'plugin::whitelabel.affiliate.find',
		config: { auth: false },
	},
];
```

Either you can return such an object (example below), which does not have the downsides above

- Route is accessed via URL `/api/{plugin-name}/${handler}`
- Route becomes visible in User Permissions, so you can change it's permissions.

<img width="416" alt="Image" src="https://github.com/user-attachments/assets/6946df65-9df5-4f58-aff5-f8e16e5e6b6a" />

```ts
export default {
	'content-api': {
		type: 'content-api',
		routes: [
			{
				method: 'GET',
				path: '/affiliates/:id',
				handler: 'plugin::whitelabel.affiliate.find',
				config: { auth: false },
			},
		],
	},
};
```

The `createCoreRouter` method returns an object with similar structure:

```ts
const router = {
	type: 'content-api',
	routes: [
		{
			method: 'GET',
			path: '/affiliates/:id',
			handler: 'plugin::whitelabel.affiliate.find',
			config: { auth: false },
		},
	],
};
```

So to use `createCoreRouter` in plugin the right way is to do it like this:

```ts
export default {
	'content-api': createCoreRouter('plugin::whitelabel.affiliate', {
		config: {
			// This if you want to disable auth for findOne route
			findOne: { auth: false },
		},
	}),
};
```

With this code now we have all default routes for CRUD

<img width="412" alt="Image" src="https://github.com/user-attachments/assets/01e91eaf-6f56-4720-bcfe-0f2d865824f9" />

Now to extend the router with more routes is a little bit tricky as we cannot directly mutate `router.routes`.

Code below wont work. If you are using TypeScript you should see an error (but not because is a getter function)

```ts
const router = createCoreRouter('plugin::whitelabel.affiliate');
router.routes.push({ /* route config */ })
```

```
Error: Could not load js config file /Users/luca/project/src/plugins/whitelabel/strapi-server.js: Cannot read properties of undefined (reading 'kind')
```

You will need to return a new object as a "wrapper" of what router returns

```ts
const router = createCoreRouter('plugin::whitelabel.affiliate');
let routes;

export default {
	'content-api': {
		type: router.type,
		prefix: router.prefix,
		get routes() {
			if (!routes) {
				routes = [
					...router.routes,
					{
						method: 'GET',
						path: '/affiliates/styles/:affiliateId',
						handler: 'plugin::whitelabel.affiliate.getAffiliateTheme',
						config: { auth: false },
					},
				];
			}

			return routes;
		},
	},
};
```

Now you should see all the methods in User Permissions

<img width="420" alt="Image" src="https://github.com/user-attachments/assets/4c091377-cb9f-44c9-bbaf-f13d28c17b07" />

But this is not very maintainable, so I created a helper function which can be reused:

```ts
function extendRouter(
	router: CoreApi.Router.Router,
	customRoutes: Common.RouteInput[],
): CoreApi.Router.Router {
	let routes: CoreApi.Router.Route[];
	return {
		type: router.type,
		prefix: router.prefix,
		get routes() {
			if (!routes) {
				// @ts-expect-error CoreApi.Router.Router#routes is actually an array
				routes = [...router.routes, ...customRoutes];
			}
			return routes;
		},
	};
}
```

Now this function can be reused to extend any router created with `createCoreRouter`:

```ts
export default {
	'content-api': extendRouter(router, [
		{
			method: 'GET',
			path: '/affiliates/styles/:affiliateId',
			handler: 'plugin::whitelabel.affiliate.getAffiliateTheme',
			config: { auth: false },
		},
	]),
};
```

The only downside is that for some reason when I try to extend the router returned by `createCoreRouter` the `config` of the route it does not work. For example having `config.auth: false` will have no effect.

This is the only thing that I still investigate. Will update when I figure it out.
