### ISSUE TITLE
Strapi won't start using ProxySQL

### ISSUE THREAD

**Issue by fitraditya** [strapi/strapi#14487]
### Required System information

- Node.js version: 16.3.1
- NPM version: 8.1.2
- Strapi version: 4.2.2
- Database: ProxySQL
- Operating system: MacOS Big Sur (Apple M1)

### Describe the bug

We tried to deploy strapi into production environment using ProxySQL (MySQL). When we run `yarn start`, we got following error:

```
[2022-09-29 05:23:56.265] error: select * from information_schema.tables where table_name = 'strapi_database_schema' and table_schema = database() - UNKNOWN_CODE_PLEASE_REPORT: ProxySQL Error: connection is locked to hostgroup 10 but trying to reach hostgroup 11
Error: UNKNOWN_CODE_PLEASE_REPORT: ProxySQL Error: connection is locked to hostgroup 10 but trying to reach hostgroup 11
```

It run well in staging environment with ProxySQL

### Steps to reproduce the behavior

```
fitra@localhost % yarn start
yarn run v1.22.17
$ strapi start
.
.
.
[
  {
    sql: 'alter table `tags_subjects_links` add constraint `tags_subjects_links_fk` foreign key (`tag_id`) references `tags` (`id`) on delete CASCADE',
    bindings: []
  },
  {
    sql: 'alter table `tags_subjects_links` add constraint `tags_subjects_links_inv_fk` foreign key (`subject_id`) references `subjects` (`id`) on delete CASCADE',
    bindings: []
  }
]
{
  method: 'raw',
  sql: 'set foreign_key_checks = 1;',
  bindings: [],
  options: {},
  __knexQueryUid: 'GdBGfGallxWqz_ryqqanv'
}
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = database()',
    bindings: [ 'strapi_database_schema' ],
    output: [Function: output]
  }
]
[2022-09-29 05:45:19.633] debug: ⛔️ Server wasn't able to start properly.
[2022-09-29 05:45:19.635] error: select * from information_schema.tables where table_name = 'strapi_database_schema' and table_schema = database() - UNKNOWN_CODE_PLEASE_REPORT: ProxySQL Error: connection is locked to hostgroup 10 but trying to reach hostgroup 11
Error: UNKNOWN_CODE_PLEASE_REPORT: ProxySQL Error: connection is locked to hostgroup 10 but trying to reach hostgroup 11
    at Query.Sequence._packetToError (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/fitra/Workspace/dictionary-cms/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/fitra/Workspace/dictionary-cms/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/fitra/Workspace/dictionary-cms/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/fitra/Workspace/dictionary-cms/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/fitra/Workspace/dictionary-cms/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/Users/fitra/Workspace/dictionary-cms/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/Users/fitra/Workspace/dictionary-cms/node_modules/knex/lib/execution/runner.js:224:21)
    at ensureConnectionCallback (/Users/fitra/Workspace/dictionary-cms/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022/09/29 05:45:19 cmd.Run() failed with exit status 1
```

### Expected behavior

Strapi is able start up normally.

### Additional context

It seems like strapi tried to read in write mysql node.

**Comment by derrickmehaffy** [comment]
This is not a Strapi issue, it's a ProxySQL issue, your group mappings are not correct or you have something odd going on with some kind of read/write split.
