### ISSUE TITLE
alter table `strapi_webhooks` modify `headers` json null

### ISSUE THREAD

**Issue by dcr31000** [strapi/strapi#14539]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: MariaDB
- Operating system: Debian

### Describe the bug

I created a new component in develop mode. When I want to deploy a new version of Strapi in the production environment, I got this error:
`
error: alter table `strapi_webhooks` modify `headers` json null, modify `events` json null - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, modify `events` json null' at line 1
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, modify `events` json null' at line 1
    at Query.Sequence._packetToError (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/user/Desktop/git/proj-strapi/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/user/Desktop/git/proj-strapi/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/user/Desktop/git/proj-strapi/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/user/Desktop/git/proj-strapi/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/user/Desktop/git/proj-strapi/node_modules/knex/lib/client.js:146:12)
    at /Users/user/Desktop/git/proj-strapi/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/user/Desktop/git/proj-strapi/node_modules/knex/lib/execution/transaction.js:358:12)
`

### Additional context

I see that MariaDB, in version 10.2.7, created an alias "json" for "longtext".
I'm using MariaDB 10.1.48. It's difficult to me to update now...
I can't specify my database version in database.js.

**Comment by dcr31000** [comment]
Force updating my database to >= 10.2.7. It's now working.

**Comment by derrickmehaffy** [comment]
We require at minimum that you are on MariaDB 10.3: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html
