### ISSUE TITLE
Error occurs when running after changing from sqlite to mysql.

### ISSUE THREAD

**Issue by ktt9117** [strapi/strapi#14534]
### Required System information
- Node.js version: v16.14.0
- NPM version: 8.5.4
- Strapi version: 4.4.1
- Database: 10.5.10-MariaDB
- Operating system: macOS Monterey 12.5.1 (Apple M1)

### Describe the bug

Error occurs when running after changing from sqlite to mysql.

### Steps to reproduce the behavior
1. npx create-strapi-app@latest hello-strapi --quickstart
2. Register the first administrator user
3. npm i mysql
4. change default database.js connection info like this:
  connection: {
    client: "mysql",  
    connection: {
      host: config.database_host,  
      port: config.database_port,  
      database: config.database_name,  
      user: config.database_user,  
      password: config.database_pwd,  
      ssl: false,  
    },  
  },
5. npm run develop
6. see this error
`
> hello-strapi@0.1.0 develop
> strapi develop

Building your admin UI with development configuration...
Admin UI built successfully
[2022-10-04 13:11:51.579] debug: ⛔️ Server wasn't able to start properly.
[2022-10-04 13:11:51.584] error: insert into `up_permissions_role_links` (`permission_id`, `role_id`) values (2, 1) - ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at Query.Sequence._packetToError (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/ssg/workspace/code/hello-strapi/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/ssg/workspace/code/hello-strapi/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/ssg/workspace/code/hello-strapi/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/ssg/workspace/code/hello-strapi/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/ssg/workspace/code/hello-strapi/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/Users/ssg/workspace/code/hello-strapi/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/Users/ssg/workspace/code/hello-strapi/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/ssg/workspace/code/hello-strapi/node_modules/knex/lib/execution/runner.js:307:20)
`

**Comment by Rupesh-Darimisetti** [comment]
may i know how to setup the project after yarn install , when I am trying to run yarn build it not work in and throwing build failed

**Comment by ktt9117** [comment]
After the npm install, I opened the `config/database.js` file to annotate the default connection object, made the following changes
```
connection: {
    client: "mysql",
    connection: {
      host: "10.xxx.xx.xxx",
      port: "3306",
      database: "test",
      user: "username",
      password: "user_pwd",
      ssl: false,
    },
 }
```
and installed the mysql(`npm i mysql`) module. Nothing else has been changed.

**Comment by bolg55** [comment]
Not able to reproduce -> what happens if you change host to "localhost" rather than the IP? That is the only difference I can see from my attempt.

**Comment by ktt9117** [comment]
@bolg55 MariaDB is not installed in my local development environment, so I tried it with a remote server. I will install mariadb locally and test it and tell you again.

**Comment by ktt9117** [comment]
When I tested it again, I encountered the following error. Who can tell me how to solve it?

```
> bug-mgmt-system-backend@0.1.0 develop
> strapi develop

[2022-10-18 16:00:01.726] ^[[34mdebug^[[39m: ⛔️ Server wasn't able to start properly.
[2022-10-18 16:00:01.729] ^[[31merror^[[39m: insert into `up_permissions_role_links` (`permission_id`, `role_id`) values (2, 1) - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`test`.`up_permissions_role_links`, CONSTRAINT `up_permissions_role_links_inv_fk` FOREIGN KEY (`role_id`) REFERENCES `up_roles` (`id`) ON DELETE CASCADE)
Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`test`.`up_permissions_role_links`, CONSTRAINT `up_permissions_role_links_inv_fk` FOREIGN KEY (`role_id`) REFERENCES `up_roles` (`id`) ON DELETE CASCADE)
    at Query.Sequence._packetToError (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/data/new-bugapp/bug-mgmt-system-backend/node_modules/mysql/lib/Connection.js:198:25)
    at /data/new-bugapp/bug-mgmt-system-backend/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/data/new-bugapp/bug-mgmt-system-backend/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/data/new-bugapp/bug-mgmt-system-backend/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/data/new-bugapp/bug-mgmt-system-backend/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/data/new-bugapp/bug-mgmt-system-backend/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/data/new-bugapp/bug-mgmt-system-backend/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
```

**Comment by ktt9117** [comment]
I installed the mariadb version as 10.9.3 and tested it, but it works well without any errors. 
The minimum supported version of mariadb in the document is 10.3, so I think it needs to be updated.

**Comment by 1158821967** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by derrickmehaffy** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。
>  
> 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

Please use English

**Comment by derrickmehaffy** [comment]
> I installed the mariadb version as 10.9.3 and tested it, but it works well without any errors. 
> The minimum supported version of mariadb in the document is 10.3, so I think it needs to be updated.

Where/who is hosting this remote DB as I just tested a locally installed MariaDB 10.4 and it works fine.

**Comment by ktt9117** [comment]
@derrickmehaffy on-premise

**Comment by derrickmehaffy** [comment]
> @bolg55 MariaDB is not installed in my local development environment, so I tried it with a remote server. I will install mariadb locally and test it and tell you again.

You just said up here you were using a remote DB and it didn't work but your locally installed one did. Who/where was hosting the remote DB

**Comment by ktt9117** [comment]
@derrickmehaffy The hosting server I am using is a private cloud server built in our company. The reason why I described it as a remote server is because the web server and the DB server are separated. The server is blocked by a firewall, no one outside the company can access it. If the mariadbDB version is not a problem, it may be a problem to setting the mariadb that was installed before. Anyway, I installed the latest version of mariadb and solved the problem, so I think I can close the issue. If you want to continue solving the issue, please tell me the information you need. I will cooperate as much as I can.

**Comment by derrickmehaffy** [comment]
Ah no problem, thanks for the context :)

As you mentioned I'll go ahead and mark this as closed. If others hit the issue please let us know.
