### ISSUE TITLE
Documentation plugin doesn't work and prevents start up without uninstalling

### ISSUE THREAD

**Issue by callum-gander** [strapi/strapi#14537]
### Required System information

    Node.js version: 14.19.1
    NPM version: 6.14.4
    Strapi version: 4.2.2
    Database: Postgresql 14
    Operating system: Ubuntu WSL x86_64

Note, I'm on an out of date version due to existing unresolved issues updating, see #13977

### Describe the bug

The Documentation plugin doesn't work. The error below comes up and the server can no longer be started without uninstalling the plugin

```
[2022-10-04 09:56:19.761] error: Cannot read property 'api' of undefined
TypeError: Cannot read property 'api' of undefined
    at Object.getApiDocumentationPath (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/plugin-documentation/server/services/documentation.js:88:40)
    at Object.generateFullDoc (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/plugin-documentation/server/services/documentation.js:140:43)
    at Object.module.exports [as bootstrap] (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/plugin-documentation/server/bootstrap.js:53:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.bootstrap (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:479:5)
    at async Strapi.bootstrap (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:417:5)
    at async Strapi.load (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:426:5)
    at async Strapi.start (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:169:9)
```
### Steps to reproduce the behavior

1. Install latest version of `@strapi/plugin-documentation`, currently 4.3.6 (I also tried this with multiple previous versions)
2. run npm run develop
3. Command fails, see error

```
[2022-10-04 09:56:19.761] error: Cannot read property 'api' of undefined
TypeError: Cannot read property 'api' of undefined
    at Object.getApiDocumentationPath (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/plugin-documentation/server/services/documentation.js:88:40)
    at Object.generateFullDoc (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/plugin-documentation/server/services/documentation.js:140:43)
    at Object.module.exports [as bootstrap] (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/plugin-documentation/server/bootstrap.js:53:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.bootstrap (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:479:5)
    at async Strapi.bootstrap (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:417:5)
    at async Strapi.load (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:426:5)
    at async Strapi.start (/home/callum/coding/ino-creative-main-website/backend/node_modules/@strapi/strapi/lib/Strapi.js:169:9)
```

### Expected behavior

Installing the plugin and running dev should generate documentation and not crash the server and render the server unable to start without uninstalling the plugin

**Comment by bolg55** [comment]
Not able to reproduce on the latest version. I know you said you're stuck on an older version. Are you able to reproduce if you make a fresh install of v4.2.2?

**Comment by aleksei-savitski-softswiss** [comment]
@bolg55  Hi, have the same issue after updating strapi from v4.1.2 to v.4.4.5. In my case error says `TypeError: Cannot read property 'contentTypes' of undefined` but also points to this line https://github.com/strapi/strapi/blob/v4.4.5/packages/plugins/documentation/server/services/documentation.js#L107.

I found that the reason is that I don't use `user-permissions` plugin, I disabled it in `config/plugins.js` with `'users-permissions': false` and doesn't include it as a dependency in package.json. All that leads to the error when `strapi.plugin(plugin).contentTypes` executes.

I found that removing 'user-permissions' plugin from config here https://github.com/strapi/strapi/blob/main/packages/plugins/documentation/server/config/default-plugin-config.js#L24 would fix the bug but I **couldn't** change it by following this instruction https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings.

So far I found only two options: 
a) disabling the documentation plugin in package.json
b) enabling the missing 'user-permissions' plugin

**Comment by internalfx** [comment]
I can confirm the same error. I also have the user-permissions plugin disabled.

**Comment by dkryvi** [comment]
Any updates on this issue?

**Comment by callum-gander** [comment]
Closing this issue, as I'm no longer using Strapi. Feel free to reopen if others are still encountering this issue
