### ISSUE TITLE
Project fails to compile after scaffolding a local plugin with cli

### ISSUE THREAD

**Issue by ayhid** [strapi/strapi#14559]
### Required System information

- Node.js version: v14.20.0
- NPM version: 6.14.17
- Strapi version: 4.3.4
- Database: Postgres
- Operating system:

### Describe the bug

Creating a Typescript plugin with cli generator crashes the project which won't start anymore.

### Error Stack

```
Compiled with problems:X

ERROR in ./node_modules/@strapi/admin/node_modules/react-is/index.js

Module build failed: Error: ENOENT: no such file or directory, open '/backend/node_modules/@strapi/admin/node_modules/react-is/index.js'


ERROR in ./.cache/admin/src/StrapiApp.js 58:0-63

Module not found: Error: Can't resolve './assets/images/logo_strapi_auth_v4.png' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/StrapiApp.js 59:0-60

Module not found: Error: Can't resolve './assets/images/logo_strapi_menu.png' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/StrapiApp.js 60:0-47

Module not found: Error: Can't resolve './components/Providers' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/app.js 3:0-50

Module not found: Error: Can't resolve './extensions/auth-logo.png' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/app.js 4:0-50

Module not found: Error: Can't resolve './extensions/menu-logo.png' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/layouts/UnauthenticatedLayout/LocaleToggle/index.js 6:0-88

Module not found: Error: Can't resolve '../../../components/LocalesProvider/useLocalesProvider' in '/backend/.cache/admin/src/layouts/UnauthenticatedLayout/LocaleToggle'


ERROR in ./.cache/admin/src/pages/App/index.js 56:0-57

Module not found: Error: Can't resolve '../../components/PrivateRoute' in '/backend/.cache/admin/src/pages/App'


ERROR in ./.cache/admin/src/pages/App/index.js 58:0-35

Module not found: Error: Can't resolve '../AuthPage' in '/backend/.cache/admin/src/pages/App'


ERROR in ./.cache/admin/src/pages/App/index.js 59:0-43

Module not found: Error: Can't resolve '../NotFoundPage' in '/backend/.cache/admin/src/pages/App'


ERROR in ./.cache/admin/src/pages/App/index.js 65:8-68:3

Module not found: Error: Can't resolve '../../components/AuthenticatedApp' in '/backend/.cache/admin/src/pages/App'


ERROR in ./.cache/admin/src/pages/UseCasePage/index.js 19:0-56

Module not found: Error: Can't resolve '../../components/UnauthenticatedLogo' in '/backend/.cache/admin/src/pages/UseCasePage'


ERROR in ./.cache/admin/src/reducers.js 19:0-45

Module not found: Error: Can't resolve './pages/App/reducer' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/reducers.js 20:0-68

Module not found: Error: Can't resolve './components/RBACProvider/reducer' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/reducers.js 21:0-63

Module not found: Error: Can't resolve './content-manager/pages/App/reducer' in '/backend/.cache/admin/src'


ERROR in ./.cache/admin/src/reducers.js 24:0-77

Module not found: Error: Can't resolve './content-manager/hooks/useSyncRbac/reducer' in '/backend/.cache/admin/src'


ERROR

  Error: Child compilation failed:
  Module not found: Error: Can't resolve '/backend/node_modules/html-webpack-plugin/lib/loader.js' in '/projects/tiween/backend'
  ModuleNotFoundError: Module not found: Error: Can't resolve '/backend/node_modules/html-webpack-plugin/li  b/loader.js' in '/backend'
      at /backend/node_modules/webpack/lib/Compilation.js:2016:28
      at /backend/node_modules/webpack/lib/NormalModuleFactory.js:798:13
      at eval (eval at create (/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:  1)
      at /backend/node_modules/webpack/lib/NormalModuleFactory.js:270:22
      at eval (eval at create (/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1  )
      at /backend/node_modules/webpack/lib/NormalModuleFactory.js:434:22
      at /backend/node_modules/webpack/lib/NormalModuleFactory.js:120:11
      at /backend/node_modules/webpack/lib/NormalModuleFactory.js:635:23
      at /backend/node_modules/neo-async/async.js:2830:7
      at done (/backend/node_modules/neo-async/async.js:2925:13)
  
  - Compilation.js:2016 
    [backend]/[webpack]/lib/Compilation.js:2016:28
  
  - NormalModuleFactory.js:798 
    [backend]/[webpack]/lib/NormalModuleFactory.js:798:13
  
  
  - NormalModuleFactory.js:270 
    [backend]/[webpack]/lib/NormalModuleFactory.js:270:22
  
  
  - NormalModuleFactory.js:434 
    [backend]/[webpack]/lib/NormalModuleFactory.js:434:22
  
  - NormalModuleFactory.js:120 
    [backend]/[webpack]/lib/NormalModuleFactory.js:120:11
  
  - NormalModuleFactory.js:635 
    [backend]/[webpack]/lib/NormalModuleFactory.js:635:23
  
  - async.js:2830 
    [backend]/[neo-async]/async.js:2830:7
  
  - async.js:2925 done
    [backend]/[neo-async]/async.js:2925:13
  
  - child-compiler.js:169 
    [backend]/[html-webpack-plugin]/lib/child-compiler.js:169:18
  
  - Compiler.js:551 finalCallback
    [backend]/[webpack]/lib/Compiler.js:551:5
  
  - Compiler.js:577 
    [backend]/[webpack]/lib/Compiler.js:577:11
  
  - Compiler.js:1196 
    [backend]/[webpack]/lib/Compiler.js:1196:17
  
  
  - runMicrotasks
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
```

**Comment by ayhid** [comment]
> Hi, can you please include explicit steps to reproduce? Thanks

I'll try to reproduce on a fresh strapi installation and get back to you with more details

**Comment by ayhid** [comment]
Hello @bolg55 I created a fresh project here with a local plugin generated from the CLI, you can check it here
https://github.com/ayhid/strapi-local-plugin-example

The generated path in `strapi-server.js` is `./dist/server` is this normal ?
Here is the output when running `yarn develop`

```
Admin UI built successfully
[2022-10-07 15:24:15.856] debug: ⛔️ Server wasn't able to start properly.
[2022-10-07 15:24:15.857] error: Could not load js config file /test-local-plugin/src/plugins/tickets/strapi-server.js: Cannot find module './dist/server'
Require stack:
- /test-local-plugin/src/plugins/tickets/strapi-server.js
- /test-local-plugin/node_modules/@strapi/strapi/lib/utils/import-default.js
- /test-local-plugin/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js
- /test-local-plugin/node_modules/@strapi/strapi/lib/core/app-configuration/config-loader.js
- /test-local-plugin/node_modules/@strapi/strapi/lib/core/app-configuration/index.js
- /test-local-plugin/node_modules/@strapi/strapi/lib/commands/develop.js
- /test-local-plugin/node_modules/@strapi/strapi/bin/strapi.js
```

**Comment by akcyp** [comment]
@ayhid You need to run: `yarn run build` in `test-local-plugin/src/plugins/tickets/`, this command will transpile typescript files inside `server/` into `dist/` directory.

**Comment by ayhid** [comment]
> @ayhid You need to run: `yarn run build` in `test-local-plugin/src/plugins/tickets/`, this command will transpile typescript files inside `server/` into `dist/` directory.

@akcyp doing this gives me this error
<img width="891" alt="Capture d’écran 2022-10-09 à 08 15 10" src="https://user-images.githubusercontent.com/235381/194741140-74e98929-c434-4b0a-bba4-77d58eae2607.png">

**Comment by akcyp** [comment]
@ayhid Run `yarn install -D` previously to install typescript compiler.

**Comment by ayhid** [comment]
> @ayhid Run `yarn install -D` previously to install typescript compiler.

Thank you @akcyp it works, I was assuming that running`yarn install` in the project root directory does install the plugin dependencies.

So If my plugin has it's own dependecies how to make sure they are installed along with the plugin without going to the plugin folder and do it manually ?

I also noticed that this part was well documented 🤦, sorry for wasting you time 🙏
