### ISSUE TITLE
Passing non-existing ID to relation field causes HTTP 500

### ISSUE THREAD

**Issue by goodhoko** [strapi/strapi#14744]
### Required System information

- Node.js version: 16.16.0
- Yarn version: 1.22.19
- Strapi version: 4.3.9
- Database: Postgres:12.0
- Operating system: node:16 [Docker image](https://hub.docker.com/_/node).
### Describe the bug

Passing non-existent ID into a relation field when creating or updating entry via the REST API causes HTTP 500.

### Steps to reproduce the behavior

1. Create a content type that relate to other content type. Below is an example using `Relating Type` type that references `Related Type` using `has one` cardinality. However this bug applies to any cardinality as far as I experimented.
    <img width="1331" alt="image" src="https://user-images.githubusercontent.com/16712262/198880404-e6b3e80e-5fdf-4bf5-89c4-77937cffcfeb.png">
2. Allow public role to create the `Relating Type`:
    <img width="855" alt="image" src="https://user-images.githubusercontent.com/16712262/198880453-9f08f4fa-3804-4802-86c5-1fc36b89e7a8.png">
3. Try to create an entry using non-existent ID for the relation field.
    ```
    POST /api/relating-types?populate=*
    {
        data: {
            // Use ID that doesn't exist.
            related_type: 99
        }
    }
    ```
4. HTTP 500 is returned and this error is logged:
    ```
    [2022-10-30 13:15:57.626] error: insert into "relating_types_related_type_links" ("related_type_id", "relating_type_id") values ($1, $2) returning "id" - insert or update on table "relating_types_related_type_links" violates foreign key constraint "relating_types_related_type_links_inv_fk"
    error: insert into "relating_types_related_type_links" ("related_type_id", "relating_type_id") values ($1, $2) returning "id" - insert or update on table "relating_types_related_type_links" violates foreign key constraint "relating_types_related_type_links_inv_fk"
        at Parser.parseErrorMessage (/opt/node_modules/pg-protocol/dist/parser.js:287:98)
        at Parser.handlePacket (/opt/node_modules/pg-protocol/dist/parser.js:126:29)
        at Parser.parse (/opt/node_modules/pg-protocol/dist/parser.js:39:38)
        at Socket.<anonymous> (/opt/node_modules/pg-protocol/dist/index.js:11:42)
        at Socket.emit (node:events:513:28)
        at Socket.emit (node:domain:489:12)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at Socket.Readable.push (node:internal/streams/readable:228:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    ```

### Expected behavior

HTTP 400 is returned stating that the specified ID doesn't exist.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/199111022-e1ad79b6-cce4-4b00-bd8f-9aa0a1387973.png)
![image](https://user-images.githubusercontent.com/8593673/199111056-4d8f9bd4-97d0-4c67-8463-dcfa7f57f143.png)
![image](https://user-images.githubusercontent.com/8593673/199111103-0a301cb7-5ed2-4e91-8a38-007eef3239af.png)

**Comment by derrickmehaffy** [comment]
Reproduction reminder, you will need to allow the `find` permission on `users-permissions` `user` to see the error

**Comment by christiancp100** [comment]
This error might be related to this one here: https://github.com/strapi/strapi/issues/14060 but besides checking the query parameters at the database layer, we should check the data passed to create a new entry.

**Comment by derrickmehaffy** [comment]
Absolutely related, not quite a duplicate so I'll leave both open but I think it should be possible to solve both at once.
