### ISSUE TITLE
Passing invalid field to `fields` param causes 500.

### ISSUE THREAD

**Issue by goodhoko** [strapi/strapi#14813]
### Required System information

- Node.js version: 16.16.0
- Yarn version: 1.22.19
- Strapi version: 4.4.5
- Database: Postgres:12.0
- Operating system: node:16 [Docker image](https://hub.docker.com/_/node).

### Describe the bug

When the `fields` param of REST API is passed with a name of a field that doesn't exist HTTP 500 is returned.

### Steps to reproduce the behavior

1. Call `GET:/api/content-type?fields[]=nonexistent` against any content-type that doesn't have a field `nonexistent`.
2. 500 is returned and this error logged:

    ```
    [2022-11-08 13:37:36.318] error: select "t0"."id", "t0"."content" from "entries" as "t0" where ("t0"."id" = $1) limit $2 - column t0.content does not exist
    error: select "t0"."id", "t0"."content" from "entries" as "t0" where ("t0"."id" = $1) limit $2 - column t0.content does not exist
        at Parser.parseErrorMessage (/opt/node_modules/pg-protocol/dist/parser.js:287:98)
        at Parser.handlePacket (/opt/node_modules/pg-protocol/dist/parser.js:126:29)
        at Parser.parse (/opt/node_modules/pg-protocol/dist/parser.js:39:38)
        at Socket.<anonymous> (/opt/node_modules/pg-protocol/dist/index.js:11:42)
        at Socket.emit (node:events:513:28)
        at Socket.emit (node:domain:489:12)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at Socket.Readable.push (node:internal/streams/readable:228:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    ```

### Expected behavior
`400` is returned stating that the field doesn't exist.

Silently ignoring the error is also an option IMO - the client requested a field, and we don't have it, so just don't return in.

**Comment by derrickmehaffy** [comment]
Duplicate (kinda) of the following:

https://github.com/strapi/strapi/issues/14744
https://github.com/strapi/strapi/issues/14060
https://github.com/strapi/strapi/issues/11696
