### ISSUE TITLE
Extend user registration using Typescript strapi-server file

### ISSUE THREAD

**Issue by Florian-crg** [strapi/strapi#14889]
## Bug report

We cannot extend a plugin with typescript. No documentation about neither a SOF post.

### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:

### Describe the bug

```
Starting the compilation for TypeScript files in /Users/florian/remotly/strapi
[2022-11-16 09:06:49.889] error: The collection "api_key" configuration should be of type object
undefined
[2022-11-16 09:06:49.932] debug: ⛔️ Server wasn't able to start properly.
[2022-11-16 09:06:49.933] error: Cannot read properties of undefined (reading 'contentTypes')
TypeError: Cannot read properties of undefined (reading 'contentTypes')
    at Object.load (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/core/domain/module/index.js:57:70)
    at Object.add (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/core/registries/modules.js:22:26)
    at Object.add (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/core/registries/plugins.js:20:60)
    at Object.loadPlugins (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:104:37)
    at async Strapi.loadPlugins (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/Strapi.js:333:5)
    at async Promise.all (index 2)
    at async Strapi.register (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/Strapi.js:369:5)
    at async Strapi.load (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/Strapi.js:474:5)
    at async Strapi.start (/Users/florian/remotly/strapi/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
error Command failed with exit code 1.
```

### Steps to reproduce the behavior

1. Create a project using strapi
2. Create a strapi-server.ts file under the plugin. `strapi/src/extensions/users-permissions/strapi-server.ts`
3.  run `strapi develop`
4. And the error is prompt

### Expected behavior

I as well tried with native javascript files. 
```
module.exports = (plugin) => {
  console.log(plugin)

  return plugin;
};
```

I tried to do other stuff on this file but non of my tries worked.

### Additional context

The main goal is to extend the auth registration to create the user on stripe. I could create it from the frontend but it wouldn't be the best solution. Prefer to do it on backend side.

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
