### ISSUE TITLE
Error : alter table `TABLENAME_components` add unique `TABLENAME_unique`

### ISSUE THREAD

**Issue by Awerta** [strapi/strapi#14936]
I've migrated from Strapi v4.4.5 to v4.5.1 .
Database migration script worked right. But when I want to start strapi I see this error:
```
error: alter table `kindergartens_components` add unique `kindergartens_unique`(`entity_id`, `component_id`, `field`, `component_type`) - ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes
Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes
```
I'm using :
- Node.js version: 16.14.0
- NPM version: 8.19.2
- Strapi version: 4.5.1
- Database: MySQL
- Operating system: Windows 11
- 
and this is the full log in terminal:

```
yarn run v1.22.17
$ strapi develop
[2022-11-18 18:55:37.072] info: Deleting duplicates of table admin_permissions_role_links...
[2022-11-18 18:55:37.114] info: Deleting duplicates of table admin_users_roles_links...
[2022-11-18 18:55:37.133] info: Deleting duplicates of table files_related_morphs...
[2022-11-18 18:55:37.148] info: Deleting duplicates of table files_folder_links...
[2022-11-18 18:55:37.158] info: Deleting duplicates of table upload_folders_parent_links...
[2022-11-18 18:55:37.170] info: Deleting duplicates of table up_permissions_role_links...
[2022-11-18 18:55:37.183] info: Deleting duplicates of table up_users_role_links...
[2022-11-18 18:55:37.195] info: Deleting duplicates of table articles_user_links...
[2022-11-18 18:55:37.206] info: Deleting duplicates of table kindergartens_user_links...
[2022-11-18 18:55:37.218] info: Deleting duplicates of table comments_comment_author_user_links...
[2022-11-18 18:55:37.229] info: Deleting duplicates of table comments_comment_report_related_links...
[2022-11-18 18:55:37.240] info: Deleting duplicates of table comments_comment_thread_of_links...
[2022-11-18 18:55:37.252] info: Deleting duplicates of table menu_items_root_menu_links...
[2022-11-18 18:55:37.262] info: Deleting duplicates of table menu_items_parent_links...
[2022-11-18 18:55:37.274] info: Deleting duplicates of table navigations_items_links...
[2022-11-18 18:55:37.285] info: Deleting duplicates of table navigations_localizations_links...
[2022-11-18 18:55:37.296] info: Deleting duplicates of table navigations_items_related_links...
[2022-11-18 18:55:37.307] info: Deleting duplicates of table navigations_items_parent_links...
[2022-11-18 18:55:37.319] info: Deleting duplicates of table navigations_items_master_links...
[2022-11-18 18:55:37.333] info: Deleting duplicates of table navigations_items_audience_links...
[2022-11-18 18:55:37.342] info: Deleting duplicates of table magazine_categories_articles_links...
[2022-11-18 18:55:37.354] info: Deleting duplicates of table articles_localizations_links...
[2022-11-18 18:55:37.363] info: Deleting duplicates of table kindergartens_city_links...
[2022-11-18 18:55:37.563] info: Deleting duplicates of table cities_province_links...
[2022-11-18 18:55:37.578] info: Deleting duplicates of table provinces_country_links...
[2022-11-18 18:55:37.590] info: Deleting duplicates of table kindergartens_components...
[2022-11-18 18:55:37.664] info: Deleting duplicates of table kindergartens_localizations_links...
[2022-11-18 18:55:37.679] info: Deleting duplicates of table magazine_categories_parent_category_links...
[2022-11-18 18:55:37.690] info: Deleting duplicates of table magazine_categories_localizations_links...
[2022-11-18 18:55:37.701] info: Deleting duplicates of table components_kindergarten_admissions_components...
[2022-11-18 18:55:37.750] info: Deleting duplicates of table components_kindergarten_facilities_components...
[2022-11-18 18:55:37.811] info: Deleting duplicates of table components_kindergarten_general_infos_components...
[2022-11-18 18:55:46.247] debug: ⛔️ Server wasn't able to start properly.
[2022-11-18 18:55:46.248] error: alter table `kindergartens_components` add unique `kindergartens_unique`(`entity_id`, `component_id`, `field`, `component_type`) - ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes
Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes
    at Query.Sequence._packetToError (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)  
    at Protocol._parsePacket (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\protocol\Protocol.js:291:23)    
    at Parser._parsePacket (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\protocol\Parser.js:433:10)        
    at Parser.write (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\protocol\Protocol.js:144:48)        
    at Connection.query (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\mysql\lib\Connection.js:198:25)
    at D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\knex\lib\dialects\mysql\index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\knex\lib\dialects\mysql\index.js:126:12)    
    at executeQuery (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
    at Client_MySQL.query (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\knex\lib\client.js:146:12)
    at D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\knex\lib\execution\transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (D:\wamp64\www\Svelte\mahdrooAppBackend\node_modules\knex\lib\execution\transaction.js:358:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Awerta** [comment]
Issue has been solved.
Related to : #10248
