### ISSUE TITLE
Cannot update from 4.4.3 to 4.5.2 due to new unique index on table admin_permissions_role_links

### ISSUE THREAD

**Issue by jsanta** [strapi/strapi#14978]
### Required System information

- Node.js version:  v16.15.1
- NPM version: 8.11.0
- yarn version: 1.22.19
- Strapi version: 4.5.2
- Database: Postgres 
- Operating system: Linux

### Describe the bug

Tried to update Strapi from version 4.4.3 to current version 4.5.2
Cannot update due to a new index that should be created in table _admin_permissions_role_links_ because of duplicate records that already exist in such table.

### Steps to reproduce the behavior

1. Update an existing and not so simple already populated Strapi editing package.json
2. yarn install
3. yarn strapi develop

```
[2022-11-23 13:08:20.088] debug: ⛔️ Server wasn't able to start properly.
[2022-11-23 13:08:20.093] error: alter table "strapi"."admin_permissions_role_links" add constraint "admin_permissions_role_links_unique" unique ("permission_id", "role_id") - could not create unique index "admin_permissions_role_links_unique"
error: alter table "strapi"."admin_permissions_role_links" add constraint "admin_permissions_role_links_unique" unique ("permission_id", "role_id") - could not create unique index "admin_permissions_role_links_unique"

```

### Expected behavior

Update should be possible without any errors.
Hopefully: Duplicated records shoudl be  deleted (if there aren't  any problems with that)

### Extra question  (<-- this is not on the  bug reporting  template)
I'm being tempted to manually delete  duplicate records, but  as I don't  know the Strapi internals I won´t do it, unless  there's   official information that doing this doesn't break anything.
Besides the known risks and screwing up  all the  installation (and probably having some impact on  our users), is this table used elsewhere, in order to safely delete  duplicate records?

Best regards.

**Comment by willempie96** [comment]
Hey there,

I think you should probably read the release migration notes. It seems like you need the 'optional' database migration script. 

https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html

**Comment by arpadgabor** [comment]
We've experienced the same issue on our production environment (other environments didn't need to migration script) however the migration script fails on the production environment. Leaving this here, we are investigating on our side.

![image](https://user-images.githubusercontent.com/9270494/203762790-93109019-a8b7-409a-88cb-4151ef4fd3f0.png)

**Comment by jsanta** [comment]
> Hey there,
> 
> I think you should probably read the release migration notes. It seems like you need the 'optional' database migration script.
> 
> https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html

Thanks  @willempie96 what troubles my mind is that this is supposed to be a minor change, without anything breaking. I'm pretty thankful for migration guides, but as being used to a non breaking "out of the box" semver logic, this kind of things besides breaking  our updates, also blow my mind (not in a good way precisely).

**Comment by arpadgabor** [comment]
Yeah, it'd be great if releases highlighted better these kinds of problems, there's a link to the migration guide but it's the same one in each release, so you're less likely to check it because most of the time there's no big issue upgrading.

**Comment by arpadgabor** [comment]
Seems like a column does not exist in `admin_permissions_role_links`... any idea how we can fix this easily?

![image](https://user-images.githubusercontent.com/9270494/203874924-292e649f-86d8-4792-8371-00f68ac055d5.png)

**Comment by bencehusi** [comment]
Same issue.

Tried to migrate to 4.5.2 from 3.6.0.

I am using the migration script as [described in the docs](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html).

`Migration 2022.11.16T00.00.00.remove_duplicated_relationships.js (up) failed: Original error: DROP TABLE IF EXISTS tmp  - current transaction is aborted, commands ignored until end of transaction block`

What is the solution here?

**Comment by ADIPSprout** [comment]
![image](https://user-images.githubusercontent.com/109570549/204708598-3bd0b2f2-93be-45d7-8cdc-22f36f4b6b14.png)
I've got the same issue when merging my Development branch to my Main branch (different Database). On my Development Branch I don't have this issue when updating to v4.5.1

**Comment by Marc-Roig** [comment]
Hello, this issue should indeed be fixed using the migration guide but it seems there is giving an error for some people.

This is caused when having duplicated relationships. If you manually can remove duplicates from admin_permissions_role_links table, it should fix it.

We had a discussion about the initial issue here https://github.com/strapi/strapi/issues/14824 if it helps someone.
We will fix the migration script asap.

**Comment by jsanta** [comment]
Thanks @Marc-Roig 
Don´t know if this question is related or not, just attempting to solve the version update  by myself.

Is there any way to skip the database creation on a first run?

I'm trying to generate by hand first the  new version schema, and then making the data loading, but Strapi server is not being able to start due to: 

```
yarn strapi develop
yarn run v1.22.19
$ strapi develop
[2022-12-07 13:49:33.369] debug: ⛔️ Server wasn't able to start properly.
[2022-12-07 13:49:33.372] error: create table "strapi-schema"."strapi_migrations" ("id" serial primary key, "name" varchar(255), "time" timestamp) - relation "strapi_migrations" already exists
error: create table "strapi-schema"."strapi_migrations" ("id" serial primary key, "name" varchar(255), "time" timestamp) - relation "strapi_migrations" already exists
    at Parser.parseErrorMessage (/Desarrollos/strapi/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Desarrollos/strapi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Desarrollos/strapi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Desarrollos/strapi/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
```

**Comment by Marc-Roig** [comment]
> Thanks @Marc-Roig Don´t know if this question is related or not, just attempting to solve the version update by myself.
> 
> Is there any way to skip the database creation on a first run?
> 
> I'm trying to generate by hand first the new version schema, and then making the data loading, but Strapi server is not being able to start due to:
>

I am afraid that is not possible , strapi will generate the schema defined in your api folder files. I think there is no way of skip the database creation on a first run.

**Comment by jsanta** [comment]
> > Thanks @Marc-Roig Don´t know if this question is related or not, just attempting to solve the version update by myself.
> > Is there any way to skip the database creation on a first run?
> > I'm trying to generate by hand first the new version schema, and then making the data loading, but Strapi server is not being able to start due to:
> 
> I am afraid that is not possible , strapi will generate the schema defined in your api folder files. I think there is no way of skip the database creation on a first run.

Uuuuuh, auch.... that's not good at all. I mean most ORMs have some settings to force or skip the schema creation. Knex should too, guess I'll have to dig into Knex configuration, but don´t like the "hot patching Strapi" idea.
Do you know where to look on the Strapi code, where the database creation  is being triggered on the first run? in order to search for this without being so blindfolded.

**Comment by Marc-Roig** [comment]
@jsanta I would start checking Strapi app first which syncs the schema with the database:
https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/Strapi.js#L445
It might interest you also checking the database layer. https://github.com/strapi/strapi/blob/main/packages/core/database/lib/index.js#L37

I want to dig into this error and find a proper solution. 4.5.0 introduced some necessary changes in the database layer and it's the foundation for other features. Changing this layer affects many parts of the codebase and for that reason, in some cases, there are problems we are trying to fix.

What error did you encounter when using the migration script? If it is the `current transaction is aborted, commands ignored until end of transaction block` could you comment the line 57 `trx.raw(`DROP TABLE IF EXISTS tmp `);` , it might be stepping onto another error inside the try-catch.

Nevertheless, I am very interested in knowing your opinion about, how should we communicate this problem better? I will be working with this issue to be resolved and try to improve the process of communicating this better & reducing problems when migrating.

**Comment by Marc-Roig** [comment]
@bencehusi 

> Same issue.
> 
> Tried to migrate to 4.5.2 from 3.6.0.
> 
> I am using the migration script as [described in the docs](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html).
> 
> Migration 2022.11.16T00.00.00.remove_duplicated_relationships.js (up) failed: Original error: DROP TABLE IF EXISTS tmp - current transaction is aborted, commands ignored until end of transaction block
> 
> What is the solution here?

Have you executed the other migration scripts mentioned in here?
https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html

There might be some intermediate migration step you missed.

**Comment by Marc-Roig** [comment]
@arpadgabor 

> We've experienced the same issue on our production environment (other environments didn't need the migration script) however the migration script fails on the production environment. Leaving this here, we are investigating on our side.

From which version are you updating? I am trying to replicate the problem.

If you are updating from a version older than 5 months ago & if it's not an inconvenience for you, could you try to update first to 4.4.5 and then to 4.5.X?

**Comment by jsanta** [comment]
> @jsanta I would start checking Strapi app first which syncs the schema with the database:
> 
> https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/Strapi.js#L445
> 
> It might interest you also checking the database layer.
> 
> https://github.com/strapi/strapi/blob/main/packages/core/database/lib/index.js#L37
> 
> What error did you encounter when using the migration script? If it is the `current transaction is aborted, commands ignored until end of transaction block` could you comment the line 57 `trx.raw(`DROP TABLE IF EXISTS tmp `);` , it might be stepping onto another error inside the try-catch.
> 
> I want to dig into this error and find a proper solution. 4.5.0 introduced some necessary changes in the database layer and it's the foundation for other features. Changing this layer affects many parts of the codebase and for that reason, in some cases, some problems appeared that we are trying to fix.
> 
> Nevertheless, I am very interested in knowing your opinion about, how should we communicate this problem better? I will be working with this issue to be resolved and try to improve the process of communicating this better & reducing problems when migrating.

Thanks @Marc-Roig .
When trying out the migration script, Strapi began to complain that every Strapi related entity already existed.. Tried a brute-force approach renaming every table when getting the error, only caused even more destruction and ended up Screwing up my Strapi instalaltion (a local backup of a very populated production environment).

The only way of addressing this issue would be like creating a  database  data dump, recreating the schema  including all new constraints, bulk inserting the  data just dumped. As constaints would avoid duplicate records it would theoretically result in a Strapi 4.5.3 compatible database. If all that can be done  with a migration it would be great. 
Tried to do exactly that by hand, but Strapi believes I'm cold starting the app so it tries to create all the tables again (thus the table already exist error).

Not saying that skipping the database creation is totally correct, but when doing these king of upgrades we should have at least a way of reusing an already existing database. The backup-restore flow is not uncommon on databases. It would even ease the developer process with production database clones for developing.

**Comment by mpinter** [comment]
Hi!

We're running into the same issue as @bencehusi and @arpadgabor 

`Migration 2022.11.16T00.00.00.remove_duplicated_relationships.js (up) failed: Original error: DROP TABLE IF EXISTS tmp - current transaction is aborted, commands ignored until end of transaction block` 

And when we add a catch clause to the script the error is:

```
error: 
        CREATE TEMPORARY TABLE tmp as SELECT DISTINCT t2.id as id
        FROM "admin_permissions_role_links" as t1 JOIN "admin_permissions_role_links" as t2
        ON t1.id < t2.id
       AND t1."permission_id" = t2."permission_id" AND t1."role_id" = t2."role_id" - column t1.id does not exist
```

Looking through the database - none of our `*_links` tables have id columns. If this isn't the case for everyone (and if they indeed should have ids), it may be perhaps caused by our database being originally migrated from v3 ? We've done it rather early in the life of strapi's official migration_scripts.

Either way, @Marc-Roig should we just manually add id columns to all of these tables ? @bencehusi or @arpadgabor have you resolved this issue in the meanwhile ?

**Comment by arpadgabor** [comment]
> @arpadgabor
> 
> > We've experienced the same issue on our production environment (other environments didn't need the migration script) however the migration script fails on the production environment. Leaving this here, we are investigating on our side.
> 
> From which version are you updating? I am trying to replicate the problem.
> 
> If you are updating from a version older than 5 months ago & if it's not an inconvenience for you, could you try to update first to 4.4.5 and then to 4.5.X?

We've tried upgrading from 4.3 -> 4.5. Upgrading to 4.4 first then did the job (I guess the id columns in _links were added in 4.4?), though it was a bit unexpected.

Note: If anyone's wondering and if it may help someone in the future, we are using AWS RDS Postgres and we couldn't access the production DB as it is isolated in our VPC, we created a snapshot of the database and created a new instance that was publicly accessible in order to try and do the migration one-by-one without affecting production.

**Comment by Marc-Roig** [comment]
@mpinter Can you try to upgrade first to 4.4?
@arpadgabor Yes, the id columns in join tables were introduced in the middle of 4.3 - 4.4 ~ and that was causing the issue. We will update the migration guide  to prevent other people having this problem.

**Comment by mpinter** [comment]
@Marc-Roig @arpadgabor thanks a lot for the quick responses - indeed, updating to 4.4 first solves the issue 👍

**Comment by Marc-Roig** [comment]
@mpinter Glad that fix it.  Thank you for replying that worked! We are now working on a more reliable solution.

**Comment by Marc-Roig** [comment]
Closing this, for now. We changed the migration steps to mention the required upgrade to 4.4 first.

**Comment by jsanta** [comment]
> Tried to update Strapi from version 4.4.3 to current version 4.5.2
I guess rollbacking to a previous version < 4.4.* is not an option...

**Comment by Marc-Roig** [comment]
> > Tried to update Strapi from version 4.4.3 to current version 4.5.2
> 
> 
> 
> I guess rollbacking to a previous version < 4.4.* is not an option...

If the migration script is giving you problems in 4.4.* we should look at that. Your original issue should be solved by the migration script.

I didnt quite understood the error you got using the migration script. Could you share the specific error?

**Comment by alucav** [comment]
i do not believe that this is fully resolved. I have followed all of the above steps, upgrading from 4.4.3, then to 4.4.5, then to 4.5.1... i tried running the DB script and am receiving the error:

```js
[2022-12-27 19:53:19.943] error: Migration 2022.11.16T00.00.00.remove_duplicated_relationships.js (up) failed: Original error: 
        CREATE TEMPORARY TABLE tmp as SELECT DISTINCT t2.id as id
        FROM `admin_permissions_role_links` as t1 JOIN `admin_permissions_role_links` as t2
        ON t1.id < t2.id
       AND t1.`permission_id` = t2.`permission_id` AND t1.`role_id` = t2.`role_id` - ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION: Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context.  These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.
MigrationError: Migration 2022.11.16T00.00.00.remove_duplicated_relationships.js (up) failed: Original error: 
        CREATE TEMPORARY TABLE tmp as SELECT DISTINCT t2.id as id
        FROM `admin_permissions_role_links` as t1 JOIN `admin_permissions_role_links` as t2
        ON t1.id < t2.id
       AND t1.`permission_id` = t2.`permission_id` AND t1.`role_id` = t2.`role_id` - ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION: Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context.  These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.
```

**Comment by derrickmehaffy** [comment]
Will reopen this so we can take a look

**Comment by Marc-Roig** [comment]
@alucav can you remove line 57 from the migration script? 
`await trx.raw(`DROP TABLE IF EXISTS tmp `);`

It's shadowing the actual error I think

**Comment by jsanta** [comment]
A question regarding first Strapi runs. 

Is there some kind of mark or database record or file that says to Strapi "this is my first run"? 
I'm still thinking of some way to re use existing Strapi databases.

**Comment by derrickmehaffy** [comment]
@jsanta yes more or less we save a copy of the db schema in `strapi_database_schema` to do a comparison too

**Comment by jsanta** [comment]
> @jsanta yes more or less we save a copy of the db schema in `strapi_database_schema` to do a comparison too

Any hint on how to trick Strapi on believing it's not the first run?
I think that could work in order to reuse a Strapi database (acknowledging the risks of doing so if there's a version missmatch for eg)

**Comment by alucav** [comment]
> @alucav can you remove line 57 from the migration script? `` await trx.raw(`DROP TABLE IF EXISTS tmp `); ``
> 
> It's shadowing the actual error I think

okay, the error is now:

```

[2023-01-09 16:35:05.473] info: Deleting duplicates of table admin_permissions_role_links...
[2023-01-09 16:35:05.483] debug: ⛔️ Server wasn't able to start properly.
[2023-01-09 16:35:05.484] error: Migration 2022.11.16T00.00.00.remove_duplicated_relationships.js (up) failed: Original error: DELETE FROM `admin_permissions_role_links` WHERE id in (SELECT * FROM tmp) - ER_NO_SUCH_TABLE: Table 'XXXXXX_data_v4.tmp' doesn't exist
MigrationError: Migration 2022.11.16T00.00.00.remove_duplicated_relationships.js (up) failed: Original error: DELETE FROM `admin_permissions_role_links` WHERE id in (SELECT * FROM tmp) - ER_NO_SUCH_TABLE: Table 'XXXXXX_data_v4.tmp' doesn't exist
    at /var/www/html/API.XXXXXX.COM/app/node_modules/umzug/lib/umzug.js:151:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Umzug.runCommand (/var/www/html/API.XXXXXX.COM/app/node_modules/umzug/lib/umzug.js:107:20)
    at async Object.up (/var/www/html/API.XXXXXX.COM/app/node_modules/@strapi/database/lib/migrations/index.js:68:7)
    at async Object.sync (/var/www/html/API.XXXXXX.COM/app/node_modules/@strapi/database/lib/schema/index.js:68:9)
    at async Strapi.bootstrap (/var/www/html/API.XXXXXX.COM/app/node_modules/@strapi/strapi/lib/Strapi.js:448:5)
    at async Strapi.load (/var/www/html/API.XXXXXX.COM/app/node_modules/@strapi/strapi/lib/Strapi.js:478:5)
    at async Strapi.start (/var/www/html/API.XXXXXX.COM/app/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
user@XXXXXX-1cwn:/var/www/html/API.XXXXXX.COM/app# 
```

**Comment by alucav** [comment]
this is breaking strapi for me. i have added a new database, deleted and re-created components, and am not able to get past this error when trying to have a repeatable component - everything is up to date:
```

CREATE TABLE `orderTable_1673284381683_850992270b42bccc6275a5a5cdaed239`
            SELECT
              id,
              (
                SELECT count(*)
                FROM `articles_components` b
                WHERE a.`order` >= b.`order` AND a.`entity_id` = b.`entity_id` AND a.`entity_id` = 1
              ) AS src_order
            FROM `articles_components` a - ER_GTID_UNSAFE_CREATE_SELECT: Statement violates GTID consistency: CREATE TABLE ... SELECT.
Error: ER_GTID_UNSAFE_CREATE_SELECT: Statement violates GTID consistency: CREATE TABLE ... SELECT.
```

**Comment by derrickmehaffy** [comment]
@alucav sounds like a duplicate of this issue: https://github.com/strapi/strapi/issues/15246

**Comment by alucav** [comment]
thank you. reading this made me realize that if i switch this app to postgres, the issue may be resolved. I am doing that now and will update this post as well as the other.

**Comment by alucav** [comment]
that fixed it. well not sure if this is an option for everyone but... one solution to this is to switch from MySQL to postGres.

**Comment by derrickmehaffy** [comment]
We do still want to fix the issue with MySQL of course but glad the work around worked for you.

**Comment by petersg83** [comment]
Hello :) What is the issue we are discussing here? Is it the GTID or something else?
If it's GTID, could we open another issue instead and close this one?

**Comment by derrickmehaffy** [comment]
> Hello :) What is the issue we are discussing here? Is it the GTID or something else? If it's GTID, could we open another issue instead and close this one?

I don't think so, it's an issue when the application boots up it throws an error as it tries to recreate the index.

**Comment by Marc-Roig** [comment]
Removed the can not reproduce label

**Comment by MikolJ** [comment]
Hello
We have a very similar issue as jsanta (and similar configuration with postgres). 

In October, we tried to upgrade our Strapi version but unfortunately we encountered an issue with duplicates. So we postponed the upgrade to wait for the appropriate patch. Unfortunately, after going through all the migration guides (we started from strapi 4.3.2), we get an error when running Strapi: 
`alter table "application_configs_components" add constraint "application_configs_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "application_configs_unique" already exists`

We tried to remove the constraints manually and then Strapi starts up (not only first time), but it only works until any model update (e.g. adding a field). Then the error reappears and the application cannot be started.

**Comment by Marc-Roig** [comment]
@MikolJ This might be related to this sother issue https://github.com/strapi/strapi/issues/14912

From 4.6.0, you should see a warning that requires you to update the schema.json files. 
Once starting the app in development, you should see those warnings that explain how to fix the issue hopefuly :) .

**Comment by PaRoxUs** [comment]
We are running into the issue each type we try to create a new content type. It's been a frustrating experience but we will try to change to PostgreSQL next week.

**Comment by MikolJ** [comment]
> @MikolJ This might be related to this sother issue #14912
> 
> From 4.6.0, you should see a warning that requires you to update the schema.json files. Once starting the app in development, you should see those warnings that explain how to fix the issue hopefuly :) .
Thanks Marc for the answer, but I don't think it's related. As I mentioned, we do not have an inversedBy relations. Also update to 4.6 didn't fix the situation - nothing is listed.

**Comment by petersg83** [comment]
Hello everyone :) Did you try this migration step : https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html#installing-database-migration-script-optional ?

**Comment by PaRoxUs** [comment]
> Hello everyone :) Did you try this migration step : https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html#installing-database-migration-script-optional ?

Yes, several times without any success.

**Comment by PaRoxUs** [comment]
> Seems like a column does not exist in `admin_permissions_role_links`... any idea how we can fix this easily?
> 
> ![image](https://user-images.githubusercontent.com/9270494/203874924-292e649f-86d8-4792-8371-00f68ac055d5.png)

Did you find a solution?

**Comment by PaRoxUs** [comment]
Okay. So after further investigation. I needed to remove the admin_permissions_role_links_unique key for admin_permissions_role_links.

Then execute `npm run develop`. After that, I could see the duplicates in the database and delete them. Before I removed the admin_permissions_role_links_unique Strapi just failed because it could not add the new permission_id and role_id link. 

I needed to repeat that process every time I tried to add a field to a content type.

The difference between the old and the new entries, besides the unique id, was that the new entries had a value for permission_order.

I also found out that I had a lot of entries in admin_permissions_role_links where the permission_id was not linking to an existing entry in admin_permissions. After deleting all of those entries I could add the admin_permissions_role_links_unique key again and add new content types and update existing ones as expected.

**Comment by Marc-Roig** [comment]
@PaRoxUs I have run into a similar issue while trying to replicate this.
By any chance, have you used the same database for multiple strapi projects?
