### ISSUE TITLE
Can't serve admin panel after adding plugins.ts to conifg

### ISSUE THREAD

**Issue by Chudroy** [strapi/strapi#14990]
### Required System information

- Node.js version: 14.20.1
- NPM version: 6.14.17
- Strapi version: 4.3.9
- Database: sqlite
- Operating system: Ubuntu

### Describe the bug

When I add a custom plugin, I can't serve the admin panel anymore.  This also occurs with node version 16.xx.xx

### Steps to reproduce the behavior

When I run the command `npm run strapi generate`, and choose to create a plugin, a message is logged to the console:

```
You can now enable your plugin by adding the following in ./config/plugins.ts
────────────────────────────────────────
export default {
  // ...
  'plugin-demo': {
    enabled: true,
    resolve: './src/plugins/plugin-demo'
  },
  // ...
}
```

When I do this, I can no longer serve the admin panel. When I run `npm run cms:develop`, which in the background is `nx serve cms`, I get the following error. But when I delete the plugins.ts file, I can serve the admin panel again.

```
Running:  npx strapi develop
Starting the compilation for TypeScript files in /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms
Building your admin UI with development configuration...
ℹ Compiling Webpack
✘ [ERROR] Cannot start service: Host version "0.15.15" does not match binary version "0.15.5"

1 error
✔ Webpack: Compiled with some errors in 4.77s
[
  {
    moduleIdentifier: '/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild-loader/dist/index.js??ruleSet[1].rules[1].oneOf[1].use!/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/.cache/admin/src/index.js',
    moduleName: './.cache/admin/src/index.js',
    message: 'Module build failed (from ./node_modules/esbuild-loader/dist/index.js):\n' +
      'Error: The service was stopped: write EPIPE\n' +
      '    at /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:792:29\n' +
      '    at Object.responseCallbacks.<computed> (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:671:9)\n' +
      '    at afterClose (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:661:28)\n' +
      '    at /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:2052:11\n' +
      '    at onwriteError (internal/streams/writable.js:384:3)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:84:21)',
    moduleId: 48,
    moduleTrace: [],
    details: undefined,
    stack: 'ModuleBuildError: Module build failed (from ./node_modules/esbuild-loader/dist/index.js):\n' +
      'Error: The service was stopped: write EPIPE\n' +
      '    at /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:792:29\n' +
      '    at Object.responseCallbacks.<computed> (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:671:9)\n' +
      '    at afterClose (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:661:28)\n' +
      '    at /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild/lib/main.js:2052:11\n' +
      '    at onwriteError (internal/streams/writable.js:384:3)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n' +
      '    at processResult (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/webpack/lib/NormalModule.js:758:19)\n' +
      '    at /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/webpack/lib/NormalModule.js:860:5\n' +
      '    at /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/loader-runner/lib/LoaderRunner.js:400:11\n' +
      '    at /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/loader-runner/lib/LoaderRunner.js:252:18\n' +
      '    at context.callback (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/loader-runner/lib/LoaderRunner.js:124:13)\n' +
      '    at Object.ESBuildLoader (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/esbuild-loader/dist/loader.js:62:9)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)'
  }
]
Admin UI built successfully
[2022-11-24 13:18:59.209] debug: ⛔️ Server wasn't able to start properly.
[2022-11-24 13:18:59.211] error: Could not load js config file /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/src/plugins/plugin-demo/strapi-server.js: Cannot find module './dist/server'
Require stack:
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/src/plugins/plugin-demo/strapi-server.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/utils/lib/import-default.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/utils/lib/index.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/commands/develop.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/bin/strapi.js
Error: Could not load js config file /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/src/plugins/plugin-demo/strapi-server.js: Cannot find module './dist/server'
Require stack:
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/src/plugins/plugin-demo/strapi-server.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/utils/lib/import-default.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/utils/lib/index.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/commands/develop.js
- /home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/bin/strapi.js
    at loadJsFile (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:18:11)
    at loadFile (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:35:14)
    at Object.loadPlugins (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:95:26)
    at async Strapi.loadPlugins (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/Strapi.js:333:5)
    at async Promise.all (index 2)
    at async Strapi.register (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/Strapi.js:369:5)
    at async Strapi.load (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/Strapi.js:474:5)
    at async Strapi.start (/home/ngaritagoitia/Documentos/Playground/plugin-demo/apps/cms/node_modules/@strapi/strapi/lib/Strapi.js:212:9)

 —————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "cms:serve" failed

   Failed tasks:
   
   - cms:serve
   
   Hint: run the command with --verbose for more details.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plugin-demo@0.0.0 cms:develop: `nx serve cms`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plugin-demo@0.0.0 cms:develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ngaritagoitia/.npm/_logs/2022-11-24T12_18_59_310Z-debug.log
ngaritagoitia~/Documentos/Playground/plugin-demo: (main)$ 
```

### Expected behavior

Not to crash

### Screenshots

![image](https://user-images.githubusercontent.com/73020686/203783427-74cf7ec0-fe4a-49b8-9e19-9689d475ce71.png)
![image](https://user-images.githubusercontent.com/73020686/203783471-e77573a9-79f0-452d-abff-4f2f3c24e075.png)
![image](https://user-images.githubusercontent.com/73020686/203784976-4291f2ca-0e0c-49e5-8896-5fe0603cfc67.png)

**Comment by fenghan34** [comment]
Hi @Chudroy, you need to build your TypeScript-based plugin before serving the admin panel. See step 8 of [Create a plugin](https://docs.strapi.io/developer-docs/latest/development/plugins-development.html#create-a-plugin).

```shell
npx tsc -p ./path/to/your-strapi-plugin/tsconfig.json
```

**Comment by Chudroy** [comment]
OK thank you

**Comment by derrickmehaffy** [comment]
Closing, as the fix was provided here: https://github.com/strapi/strapi/issues/14990#issuecomment-1327052859
