### ISSUE TITLE
Migration problem to 12.6 (SQL)

### ISSUE THREAD

**Issue by dulgeoion** [strapi/strapi#1502]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: pg
- **Operating system**: Ubuntu 17.10

**What is the current behavior?**
After migrating due to migration docs from 12.5 to 12.6, typing `npm run start` at first time got this error.
```
(node:18326) UnhandledPromiseRejectionWarning: error: invalid input syntax for type json
    at Connection.parseE (/home/dulgeoion/projects/lacing-lab-api/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/home/dulgeoion/projects/lacing-lab-api/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/home/dulgeoion/projects/lacing-lab-api/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
From previous event:
    at Client_PG._query (/home/dulgeoion/projects/lacing-lab-api/node_modules/knex/lib/dialects/postgres/index.js:265:12)
    at Client_PG.query (/home/dulgeoion/projects/lacing-lab-api/node_modules/knex/lib/client.js:198:17)
    at Runner.<anonymous> (/home/dulgeoion/projects/lacing-lab-api/node_modules/knex/lib/runner.js:148:36)
From previous event:
    at /home/dulgeoion/projects/lacing-lab-api/node_modules/knex/lib/runner.js:49:21
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)
From previous event:
    at Runner.run (/home/dulgeoion/projects/lacing-lab-api/node_modules/knex/lib/runner.js:35:31)
    at Builder.Target.then (/home/dulgeoion/projects/lacing-lab-api/node_modules/knex/lib/interface.js:21:43)
    at Child.<anonymous> (/home/dulgeoion/projects/lacing-lab-api/node_modules/bookshelf/lib/model.js:1118:36)
From previous event:
    at Child.<anonymous> (/home/dulgeoion/projects/lacing-lab-api/node_modules/bookshelf/lib/model.js:1117:125)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)
From previous event:
    at Child.<anonymous> (/home/dulgeoion/projects/lacing-lab-api/node_modules/bookshelf/lib/model.js:1000:8)
From previous event:
    at Function.addPermission (/home/dulgeoion/projects/lacing-lab-api/plugins/users-permissions/config/queries/bookshelf.js:139:8)
    at Promise.all.toAdd.map.map.action (/home/dulgeoion/projects/lacing-lab-api/plugins/users-permissions/services/UsersPermissions.js:276:18)
    at Array.map (<anonymous>)
    at Promise.all.roles.map.role (/home/dulgeoion/projects/lacing-lab-api/plugins/users-permissions/services/UsersPermissions.js:275:16)
    at Array.map (<anonymous>)
    at Object.updatePermissions (/home/dulgeoion/projects/lacing-lab-api/plugins/users-permissions/services/UsersPermissions.js:271:15)
    at <anonymous>
(node:18326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18326) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce the problem**
Don't know, try to migrate with pg.

**What is the expected behavior?**
Don't have this error.

**Suggested solutions**
Don't have any.

**Comment by derrickmehaffy** [comment]
@dulgeoion have you made any modifications to your models other than the `blah.settings.json` file?

**Comment by dulgeoion** [comment]
@derrickmehaffy I modified only `User.settings.json`

**Comment by derrickmehaffy** [comment]
@dulgeoion can you give me the user.settings.json file with your modifications?

**Comment by derrickmehaffy** [comment]
The better question is in which model are you using the JSON data type @dulgeoion

**Comment by dulgeoion** [comment]
@derrickmehaffy [Gist link for user.settings.json](https://gist.github.com/dulgeoion/65e7b186c6d43e5c7c92212182da1dce)

I don't use json model at all, I found that in DB it is only in one table and that table is `core_store`

**Comment by derrickmehaffy** [comment]
@dulgeoion can you create a new fresh project with a new postgres database and test if you have the same issue?

**Comment by derrickmehaffy** [comment]
@dulgeoion typically when I update I create a new project, create all the same models as the previous project (usually with just a string called `test`) then after I delete the database I copy over all my `model.settings.json` Since I don't typically modify the services,config,ect files.

My guess is something didn't get properly updated. I would recreate your project in a fresh one and use something like Meld on Linux to compare the two directories. that will give you a rough idea on what wasn't upgraded properly.

http://meldmerge.org/

**Comment by dulgeoion** [comment]
@derrickmehaffy thanks, I'll do as you told
