### ISSUE TITLE
many to many relationship to the same content type gives error on save

### ISSUE THREAD

**Issue by violabg** [strapi/strapi#15073]
## Bug report
see https://github.com/strapi/strapi/issues/14918
it still present in version 4.5.3
```bash
error: UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "user_id" = $1 OR "inv_user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
error: UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "user_id" = $1 OR "inv_user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
    at Parser.parseErrorMessage (/Users/paolo/Sites/mc-intranet-strapi/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/paolo/Sites/mc-intranet-strapi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/paolo/Sites/mc-intranet-strapi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/paolo/Sites/mc-intranet-strapi/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Required System information

- Node.js version: 14 latest
- NPM version:
- Strapi version: 4.5.3
- Database: postgress 14
- Operating system: ubuntu

### Steps to reproduce the behavior

1. start a new strapi 4.5.3 project with **Postgres** DB
2. add a relationship field to the user permissions, of type many to many (managers to users)
3. add one or more user to managers field and **save**
4. remove one user from managers and save
5. the error above is printed on the console

### Expected behavior

to be able to remove user and save

**Comment by Marc-Roig** [comment]
@violabg Hello! As pointed in  https://github.com/strapi/strapi/issues/14918 we merged the fix https://github.com/strapi/strapi/pull/15003 a little bit late, after 4.5.3 release, it will be released next week on dec 14th on 4.5.4.
