### ISSUE TITLE
[Bug]: Strapi can't be installed & ran with yarn 3

### ISSUE THREAD

**Issue by dmaksimov** [strapi/strapi#15094]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: latest (4.5.3)
- Database: mysql
- Operating system: mac os

### Describe the bug

I'm experiencing an error getting a new project set up.

When I run `npx create-strapi-app@latest` I get this error:

```
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /Users/davidmaksimov/Code/flex/strapi.
Creating files.
Error while installing dependencies:

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd /Users/davidmaksimov/Code/flex/strapi && yarn install
```

I changed into the directory and ran `yarn install` which seems to work fine. 

I then run `yarn develop` and get the following error:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: @strapi/admin tried to access react-select, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: react-select
Required by: @strapi/admin@virtual:0e0b361ea125fea6aef5414778335350c53c829922cb0799bd87a287a3354324816d84b3aae46eabe07386e38e673df647fca0bff89ef0a46217b1c6e3345189#npm:4.5.3 (via /Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/)

Require stack:
- /Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/webpack.alias.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/webpack.config.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/utils/index.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/index.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/unplugged/@strapi-strapi-npm-4.5.3-0e0b361ea1/node_modules/@strapi/strapi/lib/commands/builders/admin.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/unplugged/@strapi-strapi-npm-4.5.3-0e0b361ea1/node_modules/@strapi/strapi/lib/commands/builders/index.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/unplugged/@strapi-strapi-npm-4.5.3-0e0b361ea1/node_modules/@strapi/strapi/lib/commands/develop.js
- /Users/davidmaksimov/Code/flex/strapi/.yarn/unplugged/@strapi-strapi-npm-4.5.3-0e0b361ea1/node_modules/@strapi/strapi/bin/strapi.js
    at Function.require$$0.Module._resolveFilename (/Users/davidmaksimov/Code/flex/strapi/.pnp.cjs:26231:13)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/webpack.alias.js:44:46
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/davidmaksimov/Code/flex/strapi/.yarn/__virtual__/@strapi-admin-virtual-0f4cee0939/0/cache/@strapi-admin-npm-4.5.3-816867274e-bbf6246710.zip/node_modules/@strapi/admin/webpack.alias.js:43:22)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require$$0.Module._extensions..js (/Users/davidmaksimov/Code/flex/strapi/.pnp.cjs:26275:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (/Users/davidmaksimov/Code/flex/strapi/.pnp.cjs:26112:14)
```

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest` to create a new project.
2. See `Error while installing dependencies`
3. cd into project, run `yarn install`
4. Run `yarn develop`
5. See errror

### Expected behavior

Installation to complete successfully and being able to run `yarn develop`

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by joshuaellis** [comment]
Are you using `yarn 2||3`?

**Comment by dmaksimov** [comment]
> Are you using `yarn 2||3`?

I'm using 3.3.0

**Comment by gu-stav** [comment]
`yarn@3` is broken at the moment. We haven't had the time to properly define the support matrix, but we know there are several problems when using it with Strapi. There were [some attempts to make it compatible](https://github.com/strapi/strapi/pull/13769), but so far they all failed.

**Comment by malgamves** [comment]
It seems to exclusively be a yarn 3 issue. I had the same errors as you @dmaksimov. Running the command to create a new Strapi app with both yarn and npx wouldn't work smoothy when I had yarn 3 installed; they would both error out and prompt me to navigate to the project directory and install the dependencies (it's worth noting the cli asks you to do this with yarn), if you go ahead and install them with npm instead it should work. This doesn't work with yarn.

I had to downgrade to yarn 1.22.19 and everything works smoothy. Let me know if you need some help making the compatibility matrix @gu-stav or if you've got it covered already :)

**Comment by dmaksimov** [comment]
Got it. Yeah I tried with an earlier version of yarn and it seems to work now.

Thank you!

**Comment by gu-stav** [comment]
@dmaksimov I'd like to keep the issue open if you don't mind because I don't think we got one yet asking for yarn@3 support.

**Comment by Bat-m** [comment]
hello
I got the same problem
I want to upgrade from strapi 4.2.3 to 4.5.5
my version of yarn is 1.22.19

```Error: Cannot find module 'react-select'
Require stack:
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/admin/webpack.alias.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/admin/webpack.config.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/admin/utils/index.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/admin/index.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/strapi/lib/commands/builders/admin.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/strapi/lib/commands/builders/index.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/strapi/lib/commands/build.js
- /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at /Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/admin/webpack.alias.js:42:46
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/bat/Documents/grinn/carpe-deum/node_modules/@strapi/admin/webpack.alias.js:41:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
✨  Done in 2.62s.
✨  Done in 2.89s.```

**Comment by Aurelsicoko** [comment]
If you have the same issue, please follow these steps:

1. Disable Corepack `corepack disable` (I was using Yarn via Corepack as recommended in their documentation)
2. Uninstall yarn `npm uninstall --global yarn`
3. Reinstall yarn `npm install --global yarn` and check you are on v1.xx

**Comment by enyineer** [comment]
Thanks @Aurelsicoko. This is however rather a workaround then a fix. I hope this issue can be resolved by Strapi because yarn v3 can be required in some enterprise environments.

**Comment by smorimoto** [comment]
I believe it's not precisely a yarn issue. The new radar has just caught a few new problems flying in the blind spots of the old radar. (With yarn v3 improvements...)
I believe this PR https://github.com/strapi/strapi/pull/15792 will fix the issue, and it would be nice if someone on the team could review it and merge it.
