### ISSUE TITLE
Logout or Login Error 

### ISSUE THREAD

**Issue by theccc** [strapi/strapi#151]
Hello,

After making a logout the strapi on localhost, the same can not access more giving the error attached.
![captura de tela 2016-10-03 as 16 09 16](https://cloud.githubusercontent.com/assets/11972035/19114445/655a9116-8ae4-11e6-9c72-0e2f5794fa33.png)

Can someone help me?

in terminal:

`info: Connection with the Studio server found, please wait a few seconds...
warn:  Error: xhr poll error
    at XHR.Transport.onError (/usr/local/lib/node_modules/strapi/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:66:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/strapi/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:122:10)
    at Request.Emitter.emit (/usr/local/lib/node_modules/strapi/node_modules/socket.io-client/node_modules/component-emitter/index.js:134:20)
    at Request.onError (/usr/local/lib/node_modules/strapi/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:278:8)
    at null._onTimeout (/usr/local/lib/node_modules/strapi/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:225:18)
    at Timer.listOnTimeout (timers.js:92:15)`

**4.5**:
**2.15.9**:
**v1**:
**MACOSX**:

**Comment by Aurelsicoko** [comment]
Hi @theccc! Is the server trying to reconnect to the Studio?

**Comment by theccc** [comment]
Yes @Aurelsicoko, it connects, it appears in the studio to manage and admin. I can normally access the studio the application, create apis and everything, only on localhost that do not connect.

**Comment by Aurelsicoko** [comment]
Did you change some configurations? That's really weird... Did you try to create a new app and transfer your files on it, as well?

**Comment by theccc** [comment]
@Aurelsicoko I did not change any default settings. The only thing I did was after the error change the port. I will try to create a new project and transfer the files.

**Comment by Aurelsicoko** [comment]
Thanks, keep me informed ;)

**Comment by Aurelsicoko** [comment]
@theccc Any news? Did the transfer of your project fix the issue?
