### ISSUE TITLE
Could not load email provider "sendgrid".

### ISSUE THREAD

**Issue by exotexot** [strapi/strapi#15384]
Hello,

I'm installing the latest version (4.5.5) of strap and want to test the Sendgrid (4.5.5) plugin (https://www.npmjs.com/package/@strapi/provider-email-sendgrid)

Spinning up my dockerised strapi instance, I receive the error that the email provider "sendgrid" couldn't be loaded. Am I missing something?

> strapi@0.1.0 develop
> strapi develop
Starting the compilation for TypeScript files in /opt/app
[2023-01-09 14:28:57.639] debug: ⛔️ Server wasn't able to start properly.
[2023-01-09 14:28:57.641] error: **Could not load email provider "sendgrid".**
Error: Could not load email provider "sendgrid".
    at createProvider (/opt/node_modules/@strapi/plugin-email/server/bootstrap.js:23:11)
    at Object.module.exports [as bootstrap] (/opt/node_modules/@strapi/plugin-email/server/bootstrap.js:31:37)
    at Object.bootstrap (/opt/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:47)
    at Object.bootstrap (/opt/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Strapi.runLifecyclesFunctions (/opt/node_modules/@strapi/strapi/lib/Strapi.js:528:5)
    at async Strapi.bootstrap (/opt/node_modules/@strapi/strapi/lib/Strapi.js:466:5)
    at async Strapi.load (/opt/node_modules/@strapi/strapi/lib/Strapi.js:475:5)
    at async Strapi.start (/opt/node_modules/@strapi/strapi/lib/Strapi.js:212:9)

  },
  "dependencies": {
    "@sendgrid/mail": "^7.7.0",
    "@strapi/plugin-documentation": "^4.5.3",
    "@strapi/plugin-users-permissions": "4.5.0",
    "@strapi/provider-email-nodemailer": "^4.5.2",
    "@strapi/provider-email-sendgrid": "^4.5.5",
    "@strapi/strapi": "4.5.5",
    "pg": "^8.8.0",
    "strapi-plugin-populate-deep": "^1.1.2",
    "strapi-plugin-transformer": "^2.1.1"
  },

**plugins.ts**

> export default ({ env }) => ({
>   email: {
>     config: {
>       provider: "sendgrid",
>       providerOptions: {
>         apiKey:
>           "key",
>       },
>     },
>   },
> });
>

**Comment by nikita-fuchs** [comment]
Same issue here I, followed this documentation: https://docs.strapi.io/developer-docs/latest/development/providers.html#configuring-providers

**Comment by exotexot** [comment]
Closing this issue.

I was using a dockerized strapi instance and the strapi container wasn't rebuild after installing this sendgrid plugin.
