### ISSUE TITLE
Strapi 12.7 unable to create project - Can't create /tmp

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1548]
**Informations**
- **Node.js version**: v10.6.0
- **npm version**: v6.1.0
- **Strapi version**: 3.0.0-alpha.12.7
- **Database**: 10.2.16-MariaDB
- **Operating system**: Linux Mint 19 (Ubuntu 18.04)

**What is the current behavior?**

If you attempt to use `strapi new projectname` you are provided the following error:

```
(node:10925) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/tmp/strapi84856c99f671/node_modules/mysql/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at exec (/usr/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:234:30)
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
```

Even attempting to delete this folder (/tmp) and attempting to run as sudo all provide the same response.

**Steps to reproduce the problem**

Install Strapi 12.7 and attempt to create a new project with any database.

**What is the expected behavior?**

Strapi should not fail if /tmp already exists or if it already has other files/folders in it.

**Suggested solutions**

Roll back this commit until proper testing is done: https://github.com/strapi/strapi/pull/1464

**Comment by derrickmehaffy** [comment]
Spoke with @lauriejim on slack, he stated on MacOS the issue doesn't exist.

I am going to test on Ubuntu 16.04 to confirm its not just my normal dev machine

**Comment by derrickmehaffy** [comment]
Confirmed issue on Ubuntu 16.04, Centos 7, and RHEL 7

**Comment by derrickmehaffy** [comment]
@maturano can you weigh in on this, what OS do you use?

**Comment by maturano** [comment]
I can confirm the error. Is not creating a directory under `/tmp` (the temporary directory for Linux), instead is creating a `tmp/` directory at the same level of the project.

I don't know why, I will take a look later.

**Comment by derrickmehaffy** [comment]
@maturano update to 12.7.1 and/or completely remove your strapi folder installed with npm

I can't reproduce it now.

**Comment by derrickmehaffy** [comment]
@lauriejim leaving this open for ~24 hours to see if anyone else hits this error.

**Comment by derrickmehaffy** [comment]
for me either updating fixed it or running `rm -R /usr/lib/node_modules/strapi` and reinstalling it with `npm install -g strapi@alpha`

Not sure which fixed it.

**Comment by maturano** [comment]
I was about to see this issue but I can confirm is fixed now.  I can confirm the error is reproducible before the commit 8a0bca02 ... doesn't looks like related :confused:

**Comment by derrickmehaffy** [comment]
Yeah @maturano I have no idea how fixing yarn fixed my issue either. @lauriejim wasn't able to reproduce our issue on an AWS instance (after he fixed yarn :stuck_out_tongue: ) this is likely the reason. 

I'll go ahead and mark this as resolved then since it seems to be solved.

**Comment by maturano** [comment]
The problem is the same that I reported on #1463 there are a [direct command making assumptions over the file system](https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/before.js#L217). The conditional on 8a0bca0 skip that when using `npm`...

I'll work on a new patch to improve that when I have time :+1:

**Comment by derrickmehaffy** [comment]
@maturano Alright I'll reopen this, we can close it when you submit a PR.

**Comment by maturano** [comment]
@derrickmehaffy FYI: PR merged :+1:
