### ISSUE TITLE
Changing logo leads to validation error

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#15494]
### Required System information

Node.js version: v18.12.1
NPM version: v9.2.0
Strapi version: 4.5.6
Database: postgres
Operating system: OSX

### Describe the bug

Trying to change the logo via the admin panel leads to a validation error, so that feature is broken in general. 

### Steps to reproduce the behaviour

1. Go to admin panel -> settings -> overview -> logo
2. Upload some PNG image and click save
4. See error:

```
ValidationError: menuLogo must be a `string` type, but the final value was: `{}`.
    at handleYupError (/Users/macbook/Documents/DAPPS/strapi/node_modules/@strapi/admin/node_modules/@strapi/utils/lib/validators.js:67:9)
    at /Users/macbook/Documents/DAPPS/strapi/node_modules/@strapi/admin/node_modules/@strapi/utils/lib/validators.js:90:7
    at Object.updateProjectSettings (/Users/macbook/Documents/DAPPS/strapi/node_modules/@strapi/admin/server/controllers/admin.js:77:11)
    at dispatch (/Users/macbook/Documents/DAPPS/strapi/node_modules/koa-compose/index.js:42:32)
    at returnBodyMiddleware (/Users/macbook/Documents/DAPPS/strapi/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:24)
    at dispatch (/Users/macbook/Documents/DAPPS/strapi/node_modules/koa-compose/index.js:42:32)
    at policiesMiddleware (/Users/macbook/Documents/DAPPS/strapi/node_modules/@strapi/strapi/lib/services/server/policy.js:24:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/macbook/Documents/DAPPS/strapi/dist/src/middlewares/userhooks.js:5:9
    at async /Users/macbook/Documents/DAPPS/strapi/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
```

### Expected behaviour

Logo would be changeable without issues.

**Comment by Boegie19** [comment]
See https://github.com/strapi/strapi/issues/15318

**Comment by nikita-fuchs** [comment]
oh, thanks, nvm then.
