### ISSUE TITLE
Create project with non global install

### ISSUE THREAD

**Issue by kenjikato** [strapi/strapi#1550]
**Informations**
- **Node.js version**: 10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: MongoDB v4.0.0
- **Operating system**: Mac OS 10.12.6 and CentOS 7.5 (1804)

**What is the current behavior?**
I'm running in a managed corporate environment, and can't do a global node module installs.

I have to use nvm to manage my node version (which is currently v10.6.0).

I have MongoDB v4.0.0 installed locally as well.

I have full permission in my personal dev space, but not above it (hence why I have to use nvm and can't do -g installs of modules).

Other node.js apps I'm using work in this setup. But I can't get strapi to start in this environment on either Mac OS 10.12.6 or on CentOS 7.5 (1804) by just typing strapi (I'm assuming because it's not a global install).

**Steps to reproduce the problem**

In the outlined dev environment above, if I do `node ./node_modules/strapi/bin/strapi.js new myProject` I can get strapi to start.

I walk through the setup inputs (which I leave at defaults). But get back this error.
```
⏳ Testing database connection...
Error: Error: Failed to load `admin`...
(Error: Cannot find module '/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/strapi/node_modules/strapi-generate-admin')
```
followed by a long list of other issues...

**What is the expected behavior?**

I was hoping this would work, but not sure what to do next as I'm new to strapi.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @kenjikato.

To fix it run `npm i` in `/Users/appdevk5k4/Documents/Dev/newDataServer/strapi`.

**Comment by kenjikato** [comment]
@lauriejim thanks for the feedback, but unless I'm not understanding what you mean by `npm i`, getting strapi to install locally isn't the issue.

The problem is getting strapi to actually run from a local install rather than a global install. Following through the getting started to do the setup `strapi new myProject`

It appears that the local install gets hung up on loading the `admin`. Below is the full transcript from my attempt to re-run the setup from a local install. My full directory structure to the parent directory is: `/Users/appdevk5k4/Documents/Dev/newDataServer/strapi`

From within this directory I run the following (since I can't just type `strapi` at the command line).
```
./node_modules/strapi/bin/strapi.js new myProject
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
? Choose your main database: MongoDB (recommended)
? Database name: strapi
? Host: 127.0.0.1
? Port: 27017
? Username: user
? Password: ****
? Authentication database: strapi
? Enable SSL connection: false

⏳ Testing database connection...
Error: Error: Failed to load `admin`... (Error: Cannot find module '/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/strapi/node_modules/strapi-generate-admin')
    at parseTarget (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/strapi-generate/lib/target.js:253:15)
    at async.until.asyncCb (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/strapi-generate/lib/target.js:46:7)
    at whilst (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:5227:5)
    at Object.until (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:5253:5)
    at generateTarget (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/strapi-generate/lib/target.js:41:9)
    at async.eachSeries (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/strapi-generate/lib/generate.js:117:13)
    at /Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:3110:16
    at replenish (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:1011:17)
    at /Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:3196:24)
    at Object.<anonymous> (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:1046:16)
    at async.each (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/strapi-generate/lib/generate.js:116:17)
    at /Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:1069:9)
    at eachOf (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/Users/appdevk5k4/Documents/Dev/newDataServer/strapi/node_modules/async/dist/async.js:3172:5)

```

It appears as if the setup is looking for a `node_modules` within the `strapi` folder that is already within a `node_modules` folder.

**Comment by lauriejim** [comment]
The process you have to do for your case:

1. `cd newDataServer`
2. `npm init -y`
3. `npm i strapi@alpha`
4. `cd node_modules/strapi`
5. `npm i`
6. `cd ../..`
7. `node ./node_modules/strapi/bin/strapi.js new myProject`

**Comment by g-div** [comment]
I think @maturano is right, but alternatively you can try [npx](https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner). This worked for me:
```
npx strapi@alpha new my-project
```

**Comment by damons-sportsbet** [comment]
I really really think you should reopen this ticket. I want to try out this CMS and the last thing in the world I want is to install it globally into the version of node I am currently using, especially when I'm using nodenv or nvm. Surely it would be trival to get it to load properly in a portable way?
