### ISSUE TITLE
Enum field error when upgrade from 4.5.3

### ISSUE THREAD

**Issue by thongbn** [strapi/strapi#15556]
### Required System information

- Node.js version: 18-apline
- NPM version: yarn
- Strapi version: 4.5.6

### Describe the bug
Got problem with Enumeration, sometime dropdown field when update form 4.5.3 to 4.5.6. When click in enum field
Error in admin gui console
TypeError: Cannot convert undefined or null to object
    at getOwnPropertyDescriptors (<anonymous>)
    at Oi (8958.621eac7b.chunk.js:1:487)
    at d (main.c927eed1.js:4173:4288)
    at k (main.c927eed1.js:4173:21813)
    at main.c927eed1.js:5:36949
    at Object.V [as current] (main.c927eed1.js:4173:21609)
    at main.c927eed1.js:5:37323
    at main.c927eed1.js:5:37415
    at main.c927eed1.js:3250:492
    at md (main.c927eed1.js:1883:1455)
![image](https://user-images.githubusercontent.com/14286010/214385560-e00d41ea-91c8-4a6b-90ea-7f5b17d05505.png)

**Comment by thongbn** [comment]
It only happend when "yarn run build" and "yarn run start or develop", but ok in mode --watch-admin

**Comment by c3s4** [comment]
Something similar here, clicking on the enum dropdown I get this in console:

```
Uncaught (in promise) TypeError: Property description must be an object: undefined
    at defineProperty (<anonymous>)
    at main.b60a74c4.js:12012:11917
    at Generator.next (<anonymous>)
    at main.b60a74c4.js:1:823
    at new Promise (<anonymous>)
    at da (main.b60a74c4.js:1:643)
    at fn (main.b60a74c4.js:12012:11759)
    at main.b60a74c4.js:12012:4670
    at Generator.next (<anonymous>)
    at c (main.b60a74c4.js:1:681)
```

I am also getting same error if I click on the language dropdown in the content type data entry page.

Strapi version 4.5.6

**Comment by brychter-merix** [comment]
I also encountered the same error as @c3s4. Strapi version `4.5.6`.

**Comment by Xzandro** [comment]
Can confirm, although I had slightly different error message I believe. Had to roll back to my previous version (which is 4.5.2). I did not test 4.6.0 yet. Always happened when I clicked on some kind of select field.

**Comment by thongbn** [comment]
Seem it fixed in 4.6.0, i will do more test to confirm

**Comment by joshuaellis** [comment]
This _should_ be fixed in `4.6.0` this was a minification issue we were having compiling down to ES2015 – we've since moved to a browserlist configuration which I believe will better for everyone in the long run.

**Comment by benrychter** [comment]
On version `4.6.0` all select fields are working correctly.
