### ISSUE TITLE
Unable to send True/False boolean value in POST Request on MySQL

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1556]
**Informations**
- **Node.js version**: v10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: 10.2.16-MariaDB
- **Operating system**: Linux Mint 19 (Ubuntu 18.04)

**What is the current behavior?**

Unable to send a POST request on a boolean field using `True` or `False`, I have to send `1` or `0`

**Steps to reproduce the problem**

Using Mysql create a model with a boolean field and attempt to send a POST request in Postman using True or False. 

Make sure you have debugging turned on in `database.json`

**What is the expected behavior?**

you should be able to send True or False in a post request and strapi should handle the conversion in bookshelf/knex

**Suggested solutions**

It seems this error that was previously fixed has regressed again, related issue and previous PR:

Issue: https://github.com/strapi/strapi/issues/1203
PR: https://github.com/strapi/strapi/pull/1299

@lauriejim

**Comment by lauriejim** [comment]
Hello @derrickmehaffy , I just tried to create an entry that have a boolean attribute. And by sending true or false as value for this attribute, it works fine with MySQL.

Don't know what can I do to reproduce your issue.

**Comment by derrickmehaffy** [comment]
@lauriejim I just created a test project using the following model:

```
{
  "connection": "default",
  "collectionName": "testmodels",
  "info": {
    "name": "testmodel",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "testboolean": {
      "type": "boolean"
    }
  }
}
```

Attempting to send a POST request with Postman:

```
{
    "message": "An internal server error occurred",
    "statusCode": 500,
    "error": "Internal Server Error"
}
```

![image](https://user-images.githubusercontent.com/8593673/42685892-22ecb842-8649-11e8-80f9-198ae6464935.png)


Error message in Strapi:

```
{ Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'true' for column 'testboolean' at row 1
    at Query.Sequence._packetToError (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
    at Protocol._enqueue (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/mnt/nixstorage/Development/strapitest/node_modules/mysql/lib/Connection.js:208:25)
    at /mnt/nixstorage/Development/strapitest/node_modules/knex/lib/dialects/mysql/index.js:154:18
From previous event:
    at Client_MySQL._query (/mnt/nixstorage/Development/strapitest/node_modules/knex/lib/dialects/mysql/index.js:148:12)
    at Client_MySQL.query (/mnt/nixstorage/Development/strapitest/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/mnt/nixstorage/Development/strapitest/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /mnt/nixstorage/Development/strapitest/node_modules/knex/lib/runner.js:48:21
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/mnt/nixstorage/Development/strapitest/node_modules/knex/lib/runner.js:34:31)
    at Builder.Target.then (/mnt/nixstorage/Development/strapitest/node_modules/knex/lib/interface.js:20:43)
    at Child.<anonymous> (/mnt/nixstorage/Development/strapitest/node_modules/bookshelf/lib/model.js:1118:36)
From previous event:
    at Child.<anonymous> (/mnt/nixstorage/Development/strapitest/node_modules/bookshelf/lib/model.js:1117:125)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Child.<anonymous> (/mnt/nixstorage/Development/strapitest/node_modules/bookshelf/lib/model.js:1000:8)
From previous event:
    at Object.add (/mnt/nixstorage/Development/strapitest/api/testmodel/services/Testmodel.js:105:47)
    at create (/mnt/nixstorage/Development/strapitest/api/testmodel/controllers/Testmodel.js:52:38)
    at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/usr/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at policies.push (/usr/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:59:26)
    at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at module.exports (/mnt/nixstorage/Development/strapitest/plugins/users-permissions/config/policies/permissions.js:55:9)
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage:
   'Incorrect integer value: \'true\' for column \'testboolean\' at row 1',
  sqlState: '22007',
  index: 0,
  sql:
   'insert into `testmodels` (`created_at`, `testboolean`, `updated_at`) values (\'2018-07-13 10:00:20.624\', \'true\', \'2018-07-13 10:00:20.624\')' }
[2018-07-13T10:00:20.630Z] debug POST /testmodel (13 ms)
```

**Comment by derrickmehaffy** [comment]
Based on this response the fix that was applied to bookshelf is not being referenced to alias `True` = `1' and 'False' = '0'

**Comment by lauriejim** [comment]
Please try with `RAW` format when you use Postman.
We actually check on `raw` format. We know issue can exist on the format you use.

**Comment by derrickmehaffy** [comment]
@lauriejim Just tested using the raw format with `application/json`

I also spun up a VM outside my normal environments, in this case on the Vultr cloud.

![image](https://user-images.githubusercontent.com/8593673/42736863-0a5f8a7c-8822-11e8-96be-625dd85e613f.png)

On this server the following versions:

![image](https://user-images.githubusercontent.com/8593673/42736871-3a94cf40-8822-11e8-84d4-2c7356bfab93.png)

Your welcome to test this VM yourself as it's just a temporary host:

Login is `test/test` and IP is `45.77.3.163`

In this case I created a model called `testmodel` with a field of `testboolean1`

**Comment by derrickmehaffy** [comment]
The same error happened

**Comment by derrickmehaffy** [comment]
Odd, if you remove the "" around the value:

```
{
	"testboolean1": false
}
```

It seems to work. @lauriejim is x-www-form-urlencoded something that is planned to be supported or just raw JSON

**Comment by derrickmehaffy** [comment]
Closing this as it "Works" just not as expected, likely deeper issues than just the boolean.

**Comment by sbalasa** [comment]
This worked for me:

`"0"`
