### ISSUE TITLE
Upgrade to 4.6.0 throws ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by limpep** [strapi/strapi#15592]
## Bug report
After upgrading to 4.6.0 getting the following error when doing a build 
```
λ yarn build
yarn run v1.22.19
$ strapi build
Building your admin UI with development configuration...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:167:9)
    at C:\Users\\Documents\projects\react\defidive\cms\node_modules\@strapi\admin\utils\create-cache-dir.js:82:33
    at Array.filter (<anonymous>)
    at createCacheDir (C:\Users\\Documents\projects\react\defidive\cms\node_modules\@strapi\admin\utils\create-cache-dir.js:80:6)
    at async Object.build (C:\Users\\Documents\projects\react\defidive\cms\node_modules\@strapi\admin\index.js:27:3)
    at async module.exports (C:\Users\\Documents\projects\react\defidive\cms\node_modules\@strapi\strapi\lib\commands\build.js:12:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
```

### Required System information

- Node.js version: 16.19.0
- Yarn version: 1.22.19
- Strapi version: 4.6.0
- Database: local
- Operating system: windows 10

```
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.0",
    "@strapi/plugin-graphql": "^4.6.0",
    "@strapi/plugin-i18n": "4.6.0",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "4.6.0",
    "@strapi/provider-upload-aws-s3": "^4.6.0",
    "@strapi/strapi": "4.6.0",
    "mysql": "^2.18.1",
    "sqlite3": "5.1.4",
    "strapi-google-auth": "^0.1.2",
    "strapi-plugin-sitemap": "^2.0.9",
    "strapi-plugin-slugify": "^2.3.2"
  },
 ```

I have deleted node_modules and yarn.lock but no luck.

**Comment by eualex** [comment]
I've the same problem after upgrading to 4.6.0.

**Comment by Cpaczek** [comment]
This seems to have something to do with plugins, can you show me your plugins config.  Also what version are you updating from?

**Comment by cristiangonsevi** [comment]
@limpep I had same problem and it was due to ckeditor version, u should downgrade to previous version. I figured out using "@_sh/strapi-plugin-ckeditor": "1.1.3", version
![image](https://user-images.githubusercontent.com/50585874/215015151-65c1e541-3872-4876-9f6b-7158dc0c705c.png)

**Comment by limpep** [comment]
@Cpaczek here is production plugin 

```
module.exports = ({env}) => ({
  seo: {
    enabled: true,
  },
  ckeditor: true,
  upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        // accessKeyId: env('AWS_ACCESS_KEY_ID'),
        // secretAccessKey: env('AWS_ACCESS_SECRET'),
        // region: env('AWS_REGION'),
        params: {
          Bucket: env('AWS_ASSETS_BUCKET'),
        },
        logger: console
      },
      actionOptions: {
        upload: {
        },
        uploadStream: {
        },
        delete: {},
      },
    },
  },
  'users-permissions': {
    config: {
      jwt: {
        expiresIn: '7d',
      },
      jwtSecret: env('JWT_SECRET', 'zgwxFdvJAvCgSb3XcFxSfPVxjbJVPbFj')
    },
  },
});
```
@cristiangonsevi Thanks will give it ago

**Comment by darkcherrycreative** [comment]
The configuration has changed for ckeditor, take a look at this: https://www.npmjs.com/package/@_sh/strapi-plugin-ckeditor. Update this and it works.

**Comment by JoshuaAlzate** [comment]
Do we have a fix for this?

**Comment by M-GRV** [comment]
Cleaning out my plugins.js config fixed this issue for me.

**Comment by EsGeh** [comment]
A more descriptive error message for such issues would be nice.
For a normal user such messages are rather obscure, because of not pointing to the problem.
