### ISSUE TITLE
Error while fetching with date param.

### ISSUE THREAD

**Issue by dulgeoion** [strapi/strapi#1565]
**Informations**
- **Node.js version**: 10.5.0
- **npm version**: 5.6.0
- **Strapi version**: 12.7.1
- **Database**: pg
- **Operating system**: Mac

**What is the current behavior?**
So, when I am trying to fetch all data with `_gt`, `_lt` etc, with dateTime parameter, got this error: 
```
UnhandledPromiseRejectionWarning: error: date/time field value out of range: "1531416565002"
    at Connection.parseE (/Users/vitamind2/projects/lacing-lab-api/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/Users/vitamind2/projects/lacing-lab-api/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/Users/vitamind2/projects/lacing-lab-api/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
From previous event:
    at Client_PG._query (/Users/vitamind2/projects/lacing-lab-api/node_modules/knex/lib/dialects/postgres/index.js:265:12)
    at Client_PG.query (/Users/vitamind2/projects/lacing-lab-api/node_modules/knex/lib/client.js:198:17)
    at Runner.<anonymous> (/Users/vitamind2/projects/lacing-lab-api/node_modules/knex/lib/runner.js:148:36)
From previous event:
    at /Users/vitamind2/projects/lacing-lab-api/node_modules/knex/lib/runner.js:49:21
```
For example I have this part of code: 
```
let before = moment().utcOffset(0).subtract(5, 'minutes').add(6, 'hours');
let requests = await strapi.services.request.fetchAll({end_date_gt: before});
```
Even if I will try to reassign before variable to `Date.now()` or `new Date()` it throws me the same error;

**Steps to reproduce the problem**
Just to try do that code. 

**What is the expected behavior?**
I suggest, that it just shoud give me back my response, I'm trying to fetch...

**Comment by lauriejim** [comment]
Hello @dulgeoion.

This part of the documentation https://strapi.io/documentation/guides/filters.html is not for services but for API routes.

You have to use bookshelf documentation for what you need.
Check how data queries are made when you generate an API. The code is in the service file.

**Comment by dulgeoion** [comment]
Hi @lauriejim.
Actually, when you are calling `fetchAll` inside controller, you put there variable `ctx.params`. That variable is the same as  this object inside this fetch`await strapi.services.request.fetchAll({end_date_gt: before}) `, the only difference is that you put there real values, in case of date '16/07/2018', in my case I found that I need to do this changes with my variable to make it work correctly:
```
let before = moment().subtract(5, 'minutes').add(9, 'hours');
before = before.format(moment.HTML5_FMT.DATETIME_LOCAL_MS);
```
I think even if it's not a bug, but maybe it could be a good feature to make some function, that will convert different types of data to timestamp, before try to fetch data from db.
