### ISSUE TITLE
Server won't start after updating to latest version from 4.4.3 to 4.6.0

### ISSUE THREAD

**Issue by MohamedSonata** [strapi/strapi#15699]
- Node.js version:16
- NPM version:8.19.1
- Strapi version:4.6.0
- Database:sqlite
- Operating system:windows

i've meet a problem after updating to latest version every thing was working well at version 4.4.3

after updating and build the project when trying to start the server with npm run develop it's return  this message :

```
[2023-02-03 05:04:44.195] error: create unique index `favorites_fav_products_links_unique` on `favorites_fav_products_links` (`favorite_id`, `product_id`) - UNIQUE constraint failed: favorites_fav_products_links.favorite_id, favorites_fav_products_links.product_id
SqliteError: create unique index `favorites_fav_products_links_unique` on `favorites_fav_products_links` (`favorite_id`, `product_id`) - UNIQUE constraint failed: favorites_fav_products_links.favorite_id, favorites_fav_products_links.product_id
    at Client_BetterSQLite3._query (C:\Users\msona\sonata-cart\node_modules\knex\lib\dialects\better-sqlite3\index.js:39:38)
    at executeQuery (C:\Users\msona\sonata-cart\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
    at Client_BetterSQLite3.query (C:\Users\msona\sonata-cart\node_modules\knex\lib\client.js:146:12)
    at C:\Users\msona\sonata-cart\node_modules\knex\lib\execution\transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_BetterSQLite3.trxClient.query (C:\Users\msona\sonata-cart\node_modules\knex\lib\execution\transaction.js:358:12)
    at Runner.query (C:\Users\msona\sonata-cart\node_modules\knex\lib\execution\runner.js:123:36)
    at Runner.queryArray (C:\Users\msona\sonata-cart\node_modules\knex\lib\execution\runner.js:217:21)
    at Runner.queryArray (C:\Users\msona\sonata-cart\node_modules\knex\lib\execution\runner.js:269:31)
    at async Runner.ensureConnection (C:\Users\msona\sonata-cart\node_modules\knex\lib\execution\runner.js:300:14)
```

**Comment by ElmcHostedApplications** [comment]
I have the same problem moving from 4.5.5 to 4.6.0

**Comment by petersg83** [comment]
Hello :) Have you seen and tried this migration guide: https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html#installing-database-migration-script-optional ?

**Comment by MohamedSonata** [comment]
> Hello :) Have you seen and tried this migration guide: https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html#installing-database-migration-script-optional ?

@petersg83
Thanks so much for your helping, it's resolved by installing database migration script. And now the server is working on latest version.

So can you describe the problem i do, to avoided in the future
