### ISSUE TITLE
error: column "t0.id" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by krzysztof-dk** [strapi/strapi#15910]
### Required System information

- Node.js version: 18.11.0
- NPM version: 8.19.2
- Strapi version: 4.6.2
- Database: dockerized postgresql:13
- Operating system: production on docker node:18-alpine3.15, dev on MacOS 13.2
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

After upgrading from strapi 4.4.7 to 4.6.2 I started getting HTTP 500s on some entries in some collection types when trying to access them in Admin UI in my setup.

Strapi runtime logs are showing errors like this:
```
[2023-02-24 10:37:23.295] error: select "t1"."entity_id", count(*) AS count, "t0"."id" from "components_common_product_tiles" as "t0" left join "components_common_product_prices_components" as "t1" on "t0"."id" = "t1"."component_id" and "t1"."field" = $1 where ("t1"."entity_id" in ($2)) group by "t1"."entity_id" - column "t0.id" must appear in the GROUP BY clause or be used in an aggregate function
error: select "t1"."entity_id", count(*) AS count, "t0"."id" from "components_common_product_tiles" as "t0" left join "components_common_product_prices_components" as "t1" on "t0"."id" = "t1"."component_id" and "t1"."field" = $1 where ("t1"."entity_id" in ($2)) group by "t1"."entity_id" - column "t0.id" must appear in the GROUP BY clause or be used in an aggregate function
    at Parser.parseErrorMessage (/Users/kdk/Dev/TWG/DT/strapi/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/kdk/Dev/TWG/DT/strapi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/kdk/Dev/TWG/DT/strapi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/kdk/Dev/TWG/DT/strapi/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/106629516/221147665-d34776bc-0f1a-450d-ae05-dec71fa7861d.png">
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/106629516/221147774-f5945cea-adfe-4c4c-abc5-6d671f4018c2.png">

**Comment by gh-kdk** [comment]
I didn't find direct cause or solution; had to go back to version 4.4.7.

**Comment by Marc-Roig** [comment]
Hello, could you share a screenshot of some of the component definitions that your `Page` Content type has?
It could help replicate your problem :)

**Comment by benoist** [comment]
I ran into the same error, but downgrading didn't fix it.

I noticed the error was fixed when I renamed the products field to items.

Please note that products is a collection type as well, maybe thats where the issue comes from?

See the following component definitions
```json
{
  "collectionName": "components_sections_pricing_cards",
  "info": {
    "displayName": "Pricing cards",
    "description": ""
  },
  "options": {},
  "attributes": {
    "row": {
      "type": "component",
      "repeatable": false,
      "component": "components.row"
    },
    "direction": {
      "type": "enumeration",
      "enum": [
        "row",
        "col"
      ]
    },
    "justify": {
      "type": "enumeration",
      "enum": [
        "between",
        "center",
        "around",
        "start",
        "end"
      ]
    },
    "month": {
      "type": "string"
    },
    "products": {
      "type": "component",
      "repeatable": true,
      "component": "components.pricing-card"
    }
  }
}
```

```json
{
  "collectionName": "components_sections_pricing_cards",
  "info": {
    "displayName": "Pricing cards",
    "description": ""
  },
  "options": {},
  "attributes": {
    "row": {
      "type": "component",
      "repeatable": false,
      "component": "components.row"
    },
    "direction": {
      "type": "enumeration",
      "enum": [
        "row",
        "col"
      ]
    },
    "justify": {
      "type": "enumeration",
      "enum": [
        "between",
        "center",
        "around",
        "start",
        "end"
      ]
    },
    "month": {
      "type": "string"
    },
    "items": {
      "type": "component",
      "repeatable": true,
      "component": "components.pricing-card"
    }
  }
}
```

```json
{
  "collectionName": "components_components_pricing_cards",
  "info": {
    "displayName": "Pricing Card",
    "description": ""
  },
  "options": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "richtext"
    },
    "price": {
      "type": "decimal"
    },
    "button": {
      "type": "component",
      "repeatable": false,
      "component": "components.button"
    }
  }
}
```

**Comment by bpetrov98** [comment]
I couldn't find what causes the issue with v4.6.0 and reverting to v4.4.7 fixed the issue. I guess the bug will be fixed in a future release.
