### ISSUE TITLE
getting an error

### ISSUE THREAD

**Issue by ashish784** [strapi/strapi#15918]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by ashish784** [comment]
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new <anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:83:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:71:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  errno: -1,
  code: 'EPERM',
  syscall: 'uv_cwd'
}
