### ISSUE TITLE
Throwing 500 Error when trying to login using /api/auth/local

### ISSUE THREAD

**Issue by cjboco** [strapi/strapi#15915]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.4.0
- Strapi version: 4.6.2 (Community)
- Database: mysql
- Operating system: Deployed on DO, Ubuntu 18.04
- Is your project Javascript or Typescript: Client is TypeScript, Strapi is JS

### Describe the bug

Trying to access user login via the /api/auth/local route throwing 500 error.

Using various methods of testing login with axios, fetch and then Postman I couldn't get login to work. Kept getting 500 error. Finally went to DO logs and saw the following:

```
[2023-02-24 17:37:39] [2023-02-24 17:37:39.192] error: "jwtSecret" is not allowed in "options"
[api] [2023-02-24 17:37:39] Error: "jwtSecret" is not allowed in "options"
[api] [2023-02-24 17:37:39]     at /workspace/node_modules/jsonwebtoken/sign.js:45:17
[api] [2023-02-24 17:37:39]     at Array.forEach (<anonymous>)
[api] [2023-02-24 17:37:39]     at validate (/workspace/node_modules/jsonwebtoken/sign.js:41:6)
[api] [2023-02-24 17:37:39]     at validateOptions (/workspace/node_modules/jsonwebtoken/sign.js:56:10)
[api] [2023-02-24 17:37:39]     at Object.module.exports [as sign] (/workspace/node_modules/jsonwebtoken/sign.js:165:5)
[api] [2023-02-24 17:37:39]     at Object.issue (/workspace/node_modules/@strapi/plugin-users-permissions/server/services/jwt.js:33:16)
[api] [2023-02-24 17:37:39]     at Object.callback (/workspace/node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:90:32)
[api] [2023-02-24 17:37:39]     at runMicrotasks (<anonymous>)
[api] [2023-02-24 17:37:39]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[api] [2023-02-24 17:37:39]     at async returnBodyMiddleware (/workspace/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
```

### Steps to reproduce the behavior

1. Go to Use Postman and do a POST to '/api/auth/local' with { "identifier": IDENTIFIER, "password": PASSWORD } and you will get a 500 error.

### Expected behavior

Should return something like:

```
{
	"jwt": "JWT_TOKEEN",
	"user": {
		"id": 1,
		"username": "bob",
		"email": "bob@text.com",
		"provider": "local",
		"confirmed": true,
		"blocked": false,
		"createdAt": "2023-02-24T10:27:19.897Z",
		"updatedAt": "2023-02-24T10:27:19.897Z"
	}
}
```

### Traced bug
I started debugging with `auth.js`, then `jwt.js` and here's what I discovered:

jsonwebtoken's `jwt.sign()` required three parameters. 

In `jwt.j`s in the `plugin-user-permissions`, you are sending **jwtOptions** as the third parameter:

```
return jwt.sign(
   _.clone(payload.toJSON ? payload.toJSON() : payload),
   strapi.config.get('plugin.users-permissions.jwtSecret'),
   jwtOptions
);
```

`jwt.sign()` has a `validate()` function and it will validate the option you pass to it. You are passing:

```
param3: {
    jwtSecret: '918f8ecb-2396-4d6c-8f6d-ba24e89385b1',
    expiresIn: '30d'
  }
```

Unfortunately, **jwtSectret** is not a valid option and **jsonwebtoken** it throwing an error back to Strapi, but Strapi is not handling the error properly, so it throws the 500 error.

I changed the option to just send the `expiresIn` key/value and that fixes the issue. 

### Fix
Remove the **jwtSectret** parameter from the 3rd option to jwt.sign()

**Comment by cjboco** [comment]
https://user-images.githubusercontent.com/351122/221328072-cfd96b2b-5489-4d7e-95be-6d8cc82561ac.mp4

In this movie, all I did was add a new line to the `config.js`, called `ppp` which is basically a dupe of `jwt`. 

In the `jwt.js` file, I added a console log, that is dumping the result from calling `strapi.config.get('plugin.users-permissions.jwt')` changing `jwt`, to `ppp`.

As you can see, when using `jwt`, it's pulling the `jwtSecret`. When using `ppp` it does not. Not sure why.

**Comment by cjboco** [comment]
After an exhaustive step by step debug of loading the `user-permissions` plug-in, I was able to trace this to, what appears to be a bad custom config setting file in `api/config/plugin.js`.

```
'users-permissions': {
    config: {
      jwt: {
        jwtSecret: env('JWT_SECRET'),
      },
    },
  },
```

This was being added to the 'jwt' object in the plugin config, which was then being passed to `jsonwebtoken`, which in turn threw the error..
