### ISSUE TITLE
Failed to create component when I use non-alphanumeric characters for component's display name

### ISSUE THREAD

**Issue by marromugi** [strapi/strapi#15946]
## Bug report
Failed to reboot Strapi when i use non-alphanumeric characters (like Kanji) for component's display name

![image](https://user-images.githubusercontent.com/101984097/221807188-4fb3f9a0-c7de-414b-a5b2-53424020b017.png)

I think the reason for failed reboot is that the component's schema file named `.json` is created when i use japanese to component's display name
I can define component with fixing schema file manually, but leave this as a report

#### Content schema file（only attributes）
```json
{
"attributes": {
    "title": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "slug": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "thumbnail": {
      "type": "media",
      "multiple": true,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },
    "series": {
      "displayName": "あいうえお",
      "type": "component",
      "repeatable": false,
      "component": "hello."  // component looks incorrect because of schema file .json
    }
  }
}
```

### error detail
```
[2023-02-28 16:52:44.940] debug: ⛔️ Server wasn't able to start properly.
[2023-02-28 16:52:44.941] error: Cannot read properties of undefined (reading 'attributes')
TypeError: Cannot read properties of undefined (reading 'attributes')
    at cleanSchemaAttributes (/Users/marromugi/strapi-test/node_modules/@strapi/plugin-documentation/server/services/helpers/utils/clean-schema-attributes.js:96:76)
    at getAllSchemasForContentType (/Users/marromugi/strapi-test/node_modules/@strapi/plugin-documentation/server/services/helpers/build-component-schema.js:89:25)
    at loopContentTypeNames (/Users/marromugi/strapi-test/node_modules/@strapi/plugin-documentation/server/services/helpers/utils/loop-content-type-names.js:46:10)
    at buildComponentSchema (/Users/marromugi/strapi-test/node_modules/@strapi/plugin-documentation/server/services/helpers/build-component-schema.js:213:10)
    at Object.generateFullDoc (/Users/marromugi/strapi-test/node_modules/@strapi/plugin-documentation/server/services/documentation.js:154:33)
    at async Object.module.exports [as bootstrap] (/Users/marromugi/strapi-test/node_modules/@strapi/plugin-documentation/server/bootstrap.js:53:3)
    at async Object.bootstrap (/Users/marromugi/strapi-test/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/Users/marromugi/strapi-test/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/Users/marromugi/strapi-test/node_modules/@strapi/strapi/lib/Strapi.js:541:5)
    at async Strapi.bootstrap (/Users/marromugi/strapi-test/node_modules/@strapi/strapi/lib/Strapi.js:479:5)
error Command failed with exit code 1.
```

### Required System information

- node: v16.15.1
- npm: v9.3.1
- strapi: v4.6.1
- database: mysql
- os: macOS12.5
- language: Typescript

**Comment by Boegie19** [comment]
Can you confirm what encoding your tables has? Some MariaDB / MySQL instances set a default encoding type of latin1-swedish_ci or latin1 which doesn't support unicode chars, you should change to utf8mb4 if possible (optionally set your server's default to this as well). Node that simply changing the database type isn't enough, you will also have to migrate each table as well.

**Comment by TechQuery** [comment]
> Can you confirm what encoding your tables has? Some MariaDB / MySQL instances set a default encoding type of latin1-swedish_ci or latin1 which doesn't support unicode chars, you should change to utf8mb4 if possible (optionally set your server's default to this as well). Node that simply changing the database type isn't enough, you will also have to migrate each table as well.

@Boegie19 PostgreSQL has the same issue, and I don't think that it's a Database Charset issue, because invalid Component names appear in Strapi schema JSON, it must be some logic bugs in JavaScript code.

**Comment by Boegie19** [comment]
@TechQuery Please open a new issue for this.
