### ISSUE TITLE
When clicking on 'Roles', dashboard goes blank and displays JS errors

### ISSUE THREAD

**Issue by lowercasename** [strapi/strapi#15961]
### Required System information

- Node.js version: 18.12.1
- NPM version: 9.5.1
- Strapi version: 4.7.0
- Database: mysql
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I click on 'Roles' in the Settings menu, the whole page goes blank and I see JS errors in the console:

```
main.14f3852b.js:1407 TypeError: (0 , r.default) is not a function
    at ce (Admin_settingsPage.b52ef349.chunk.js:169:1576)
    at xe (Admin_settingsPage.b52ef349.chunk.js:169:2518)
    at El (main.14f3852b.js:1405:54686)
    at vc (main.14f3852b.js:1409:9133)
    at Nc (main.14f3852b.js:1409:989)
    at Xc (main.14f3852b.js:1409:917)
    at Du (main.14f3852b.js:1409:768)
    at Qu (main.14f3852b.js:1407:11074)
    at main.14f3852b.js:1405:39503
    at n.unstable_runWithPriority (main.14f3852b.js:1489:3837)
```

### Expected behavior

The roles panel should appear.

### Screenshots

https://user-images.githubusercontent.com/1748384/222211290-a1681dec-3167-4111-8d3e-3579d7dd326b.mov

**Comment by lowercasename** [comment]
Looks like this is a plugin-related issue.
