### ISSUE TITLE
Database migration alter table add constraint  _unique relation already exists

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#16055]
### Required System information

- Node.js version: v18
- Strapi version: v4.7.1
- Database: PostgresQL 14
- Operating system: Alpine
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Every time I [rollout a new deployment](https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/) the database migration complains about uniqueness constraints on the tables:

```
alter table \"public\".\"collections_components\" add constraint \"collections_unique\" unique (\"entity_id\", \"component_id\", \"field\", \"component_type\") - relation \"collections_unique\" already exists\nerror: alter table \"public\".\"collections_components\" add constraint \"collections_unique\" unique (\"entity_id\", \"component_id\", \"field\", \"component_type\") - relation \"collections_unique\" already exists
   at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
   at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

Running the following query I can see that the constraint is there:

```
SELECT con.*
       FROM pg_catalog.pg_constraint con
            INNER JOIN pg_catalog.pg_class rel
                       ON rel.oid = con.conrelid
            INNER JOIN pg_catalog.pg_namespace nsp
                       ON nsp.oid = connamespace
     WHERE rel.relname = 'collections_components';
```

```
  oid   |           conname           | connamespace | contype | condeferrable | condeferred | convalidated | conrelid | contypid | conindid | conparentid | confrelid | confupdtype | confdeltype | confmatchtype | conislocal | coninhcount | connoinherit |  conkey   | confkey | conpfeqop | conppeqop | conffeqop | conexclop | conbin 
--------+-----------------------------+--------------+---------+---------------+-------------+--------------+----------+----------+----------+-------------+-----------+-------------+-------------+---------------+------------+-------------+--------------+-----------+---------+-----------+-----------+-----------+-----------+--------
 163147 | collections_components_pkey |         2200 | p       | f             | f           | t            |   161904 |        0 |   163146 |           0 |         0 |             |             |               | t          |           0 | t            | {1}       |         |           |           |           |           | 
 163078 | collections_entity_fk       |         2200 | f       | f             | f           | t            |   161904 |        0 |   162461 |           0 |    161899 | a           | c           | s             | t          |           0 | t            | {2}       | {1}     | {96}      | {96}      | {96}      |           | 
 163344 | collections_unique          |         2200 | u       | f             | f           | t            |   161904 |        0 |   163343 |           0 |         0 |             |             |               | t          |           0 | t            | {2,3,5,4} |         |           |           |           |           | 
(3 rows)
```

### Steps to reproduce the behavior

1.Dump and import the database

```shell
pg_dump <credentials> --inserts --no-owner  -Fc <db-name> > "dump.pg"
```

```shell
pg_restore <credentials> -j 8 --no-owner --clean -d  <db-name> "dump.pg"
```

2. Run `strapi start`

### Expected behavior

Detect the existing uniqueness constraints and do not try to create them in the migration or use `IF NOT EXISTS` statement to prevent error.

### Code snippets

<details>

<summary> database/migrations/<date>.remove_duplicated_relationships.js </summary>

```javascript
'use strict';

/**
 * Get the link tables names that need to be updated
 */
const getLinkTables = ({ strapi }) => {
  const contentTypes = strapi.db.metadata;
  const tablesToUpdate = {};

  contentTypes.forEach(contentType => {
    // Get attributes
    const attributes = contentType.attributes;

    // For each relation type, add the joinTable name to tablesToUpdate
    Object.values(attributes).forEach(attribute => {
      if (attribute.type === 'relation' && attribute.joinTable) {
        tablesToUpdate[attribute.joinTable.name] = attribute.joinTable;
      }
    });
  });

  return Object.values(tablesToUpdate);
};

async function up(trx) {
  const linkTablesToUpdate = getLinkTables({ strapi });

  // Remove duplicates from link tables
  for (const table of linkTablesToUpdate) {
    const tableExists = await trx.schema.hasTable(table.name);
    if (!tableExists) continue;

    strapi.log.info(`Deleting duplicates of table ${table.name}...`);

    try {
      // Query to delete duplicates from a link table
      let query = `
        CREATE TEMPORARY TABLE tmp as SELECT DISTINCT t2.id as id
        FROM ?? as t1 JOIN ?? as t2
        ON t1.id < t2.id
      `;
      const pivotWhereParams = [];

      // For each pivot column, add a on condition to the query
      table.pivotColumns.forEach(column => {
        query += ` AND t1.?? = t2.??`;
        pivotWhereParams.push(column, column);
      });

      // Create temporary table with the ids of the repeated rows
      await trx.raw(query, [table.name, table.name, ...pivotWhereParams]);

      // Delete repeated rows from the original table
      await trx.raw(`DELETE FROM ?? WHERE id in (SELECT * FROM tmp)`, [table.name]);
    } finally {
      // Drop temporary table
      await trx.raw(`DROP TABLE IF EXISTS tmp `);
    }
  }
}

async function down() {}

module.exports = { up, down };
```

</details>

**Comment by sjoukedv** [comment]
This is still an ongoing issue for me. I have to manually remove all the constraints on `_components` tables. 

Isn't it possible to do change the logic to check for the existence of the constraint first? Or add a `IF NOT EXISTS` or `ON CONFLICT DO NOTHING` to the statement?

**Comment by AlbertCardo** [comment]
We are facing the same error. When doing `npm run dev` locally we get this:

```
> cardo-admin@0.1.0 dev
> strapi develop

error: alter table "backend_configs_components" add constraint "backend_configs_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "backend_configs_unique" already exists
    at Parser.parseErrorMessage (/Users/albert/code/monorepo-test2/apps/admin/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/albert/code/monorepo-test2/apps/admin/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/albert/code/monorepo-test2/apps/admin/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/albert/code/monorepo-test2/apps/admin/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 104,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '864',
  routine: 'index_create'
}
```

Same happens on the remote development server:

```
error: alter table "up_users_components" add constraint "up_users_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "up_users_unique" already exists
```

The fix is to remove the `*_unique` index on all `*_components` tables, eg:

```
ALTER TABLE "up_users_components" DROP CONSTRAINT IF EXISTS "up_users_unique";
```

We have 8 index like this. All them need to be removed to make Strapi run.

The interesting/curious thing is that these errors happen with 2 repositories using the _same_ database. Eg locally I cloned again our Strapi code, so now I have the same code in 2 different folders. When I run the old clone it works, but the new clone throws the error, even though the database is the same. And on the remote server, when we create a pull request we deploy the PR code to test the changes, but pointing to the same database than our development environment. The error only happens on the new deployment for the pull request, but not the development environment.

**Comment by AlbertCardo** [comment]
Same issue has been reported in StackOverflow: https://stackoverflow.com/questions/76231417/strapi-index-error-when-i-try-to-save-anything

And in https://github.com/strapi/strapi/issues/14912

**Comment by AlbertCardo** [comment]
We fixed the issue by setting `settings: { forceMigration: true }` in our [database configuration](https://docs.strapi.io/dev-docs/configurations/database#settings-configuration-object).

Note that [this deletes unknown tables](https://docs.strapi.io/dev-docs/database-migrations#understanding-database-migration-files), so you'll need to watch out if you want to rename a database table copying the content from the old to the new one.
