### ISSUE TITLE
Upgrade to 4.8.x got error when populate dynamic component

### ISSUE THREAD

**Issue by thongbn** [strapi/strapi#16105]
### Required System information

- Node.js version: 18-alpine
- NPM version: 
- Strapi version: 4.8.1
- Database: mysql
- Operating system: Docker env
- Is your project Javascript or Typescript: javascript

### Describe the bug
Sorry, i post another issue follow template.
When populate Dynamic Component . I got this error

[2023-03-16 11:37:35.437] error: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
at Function.entries ()
at Object.handler (/opt/app/node_modules/@strapi/utils/lib/traverse/query-populate.js:106:45)
at traverse (/opt/app/node_modules/@strapi/utils/lib/traverse/factory.js:104:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.handler (/opt/app/node_modules/@strapi/utils/lib/traverse/query-populate.js:172:21)
at async traverse (/opt/app/node_modules/@strapi/utils/lib/traverse/factory.js:104:11)
at async /opt/app/node_modules/@strapi/utils/lib/async.js:11:13
at async /opt/app/node_modules/@strapi/utils/lib/async.js:11:13
at async Object.sanitizeQuery [as query] (/opt/app/node_modules/@strapi/utils/lib/sanitize/index.js:77:49)
at async Object.find (/opt/app/node_modules/@strapi/strapi/lib/core-api/controller/collection-type.js:22:30)

It work fine when downgrade to 4.6.2, not test in 4.7.x

### Steps to reproduce the behavior

1. Just populate an api have dynamic components
![image](https://user-images.githubusercontent.com/14286010/225609978-7908bb33-1b3f-4c8f-bb2d-e901763e13c3.png)
2. This is my tour schema
`{
  "kind": "collectionType",
  "collectionName": "tours",
  "info": {
    "singularName": "tour",
    "pluralName": "tours",
    "displayName": "Tour",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "title": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "shortDescription": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "text"
    },
    "brochure": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "cover": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      }
    },
    "images": {
      "type": "media",
      "multiple": true,
      "required": false,
      "allowedTypes": [
        "images"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "tourCard": {
      "type": "component",
      "repeatable": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "component": "tour.tour-card"
    },
    "destination": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::destination.destination"
    },
    "slug": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "uid",
      "targetField": "title"
    },
    "scheduleImage": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "mapImage": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "tourCustom": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "dynamiczone",
      "components": [
        "common.feature",
        "common.icon-value",
        "common.list-contact",
        "common.list-features",
        "common.list-with-icon-value",
        "common.custom-ck-editor"
      ]
    },
    "features": {
      "type": "component",
      "repeatable": true,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "component": "common.feature"
    },
    "byg": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "text"
    },
    "tags": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::tag.tag"
    },
    "category": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::category.category"
    },
    "paymentProduct": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::payment-vns.payment-product",
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      }
    },
    "places": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::place.place"
    },
    "adultPrice": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "decimal"
    },
    "childPrice": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "decimal"
    },
    "isHot": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "boolean",
      "default": false
    },
    "discountLabel": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "hideBookingButton": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "boolean",
      "default": false,
      "required": true
    },
    "vnsPriceList": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "customField",
      "customField": "plugin::payment-vns.VnsPriceList"
    }
  }
}
`

### Expected behavior

Just return dynamic content

**Comment by thongbn** [comment]
I tested in 4.7.1, my code still work fine, only happend in 4.8.x

**Comment by Convly** [comment]
Hey I've been able to reproduce your issue. This is indeed caused by 4.8.(0|1).
I'll provide a fix today & it'll be part of the next release.
Sorry for that.

**Comment by Convly** [comment]
I've created a PR that fixes the issue [here](https://github.com/strapi/strapi/pull/16109). Thanks again for reporting this!

**Comment by thongbn** [comment]
Thank for quick response
