### ISSUE TITLE
Content-manager Cannot read properties of undefined (reading 'list') for UID field

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#16147]
### Required System information

- Node.js version: v18.15.0
- Strapi version: v4.8.2
- Database: psql
- Is your project Javascript or Typescript: Typescript

### Describe the bug

 UID field without a linked field throws error in the content-manager. `/admin/content-manager/collectionType/api::<collection>/<id>` works fine, but the overview, `/admin/content-manager/collectionType/api::<collection>/`, throws an error (see screenshot below)

```javascript
main.db10b01b.js:1699 TypeError: Cannot read properties of undefined (reading 'list')
    at content-manager.e83a46bb.chunk.js:1068:4402
    at Array.map (<anonymous>)
    at jr (content-manager.e83a46bb.chunk.js:1068:4359)
    at Uu (main.db10b01b.js:1697:54685)
    at _u (main.db10b01b.js:1697:64519)
    at hu (main.db10b01b.js:1697:63831)
    at Yu (main.db10b01b.js:1697:63402)
    at hc (main.db10b01b.js:1701:12514)
    at kc (main.db10b01b.js:1701:989)
    at qc (main.db10b01b.js:1701:917)
```

The corresponding line in the content manager script:

```javascript
            const o = (0,
            le.useDispatch)()
              , r = (0,
            le.useSelector)(Rr)
              , {trackUsage: s} = (0,
            h.useTracking)()
              , {formatMessage: i} = (0,
            Z.useIntl)()
              , c = Fd(e.contentType.attributes).map(u=>{
                const m = e.contentType.metadatas[u].list; // <-- this line
                return {
                    name: u,
                    intlLabel: {
                        id: m.label,
                        defaultMessage: m.label
                    }
                }
            }
  ```

### Steps to reproduce the behavior

1. Add a UID field without a linked field.

```javascript
 "slug": {
      "type": "uid",
      "required": true
    },
```

2. Vist the collection overview `/admin/content-manager/collectionType/api::<collection>`

### Expected behavior

Display content overview

### Screenshots

![image](https://user-images.githubusercontent.com/24683344/226544543-40a945ae-a3e8-47e1-86ce-fbece93716c9.png)

**Comment by Boegie19** [comment]
I can confirm this some times but if I refesh it fixes itself

**Comment by Boegie19** [comment]
code block that is failing

        , []).sort()
          , Is = ({layout: t})=>{
            const o = (0,
            _.I0)()
              , r = (0,
            _.v9)(rs)
              , {trackUsage: s} = (0,
            h.rS)()
              , {formatMessage: a} = (0,
            H.Z)()
              , l = Eu(t.contentType.attributes).map(p=>{
                const u = t.contentType.metadatas[p].list;
                return {
                    name: p,
                    intlLabel: {
                        id: u.label,
                        defaultMessage: u.label
                    }
                }
            }

**Comment by joshuaellis** [comment]
if you add a `webpack.config.js` in your `src/admin` folder and include:

```js
'use strict';

/* eslint-disable no-unused-vars */
module.exports = (config, webpack) => {
  // Note: we provide webpack above so you should not `require` it
  // Perform customizations to webpack config
  // Important: return the modified config
  config.devtool = 'source-map'

  return config;
};
```

It _should_ give you source-maps and we can easier identify the code because at the moment the demonstrated codeblock is not _that_ helpful.

**Comment by coldman333** [comment]
hi have the same issue  version  4.14 - 4.14.5,  looks like  crush  on  line 
`  , {mainField: re, label: xe} = v[ee].list `
`ee: "createdBy"` 
 but object does not have this property

`~ v: Obiect
particles: (list: (.), edit: (.) avatar: {edit: (.), list: {-3] createdAt: (edit: (.), list: [_}} email: fedit: {.), list: {)} id: fedit: {.), list: {.)} name: fedit: {-), list: {.]} updatedAt: (edit: {-), list: {-))`

i will try add source-map to clarify this

**Comment by joshuaellis** [comment]
this will be fixed in v5.
