### ISSUE TITLE
⏳ Testing database connection...

### ISSUE THREAD

**Issue by wancode** [strapi/strapi#1617]
What is the problem? And how can I solve it.

`(node:1252) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:328:20)
    at getRootPath (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\win32.js:7:27)
    at invalidWin32Path (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\win32.js:17:14)
    at mkdirsSync (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:17:39)
    at mkdirsSync (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:37:16)
    at mkdirsSync (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:38:9)
    at mkdirsSync (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:38:9)
    at mkdirsSync (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:38:9)
    at mkdirsSync (C:\Users\Wancode\AppData\Roaming\npm\node_modules\strapi\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:38:9)
(node:1252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Node version: v8.11.3
Strapi version: 3.0.0-alpha.12.7.1

**Comment by lauriejim** [comment]
We have a lot of troubles running on Windows. The recommendation is work with Linux under a VM or with WSL.

**Comment by raczak** [comment]
Same problem for me on Windows ... I spent a lot of time trying to understand what I did wrong before discovering this thread.

Is a fix planned?
