### ISSUE TITLE
Can't create project with `yarn create strapi-app` ModuleNotFoundError

### ISSUE THREAD

**Issue by antokhio** [strapi/strapi#16191]
## Bug report
Hello, i wanted o migrate project on 4.8.2 but ran in to an dependency issue, there were to more issues reporting same errors. 
The issue was suggested, as an issue with plugin. 

But today i decided to create new strapi app to test this in ran in to this issue directly: 

### Required System information

- Node.js version: v16.18.0
- NPM version: 8.13.1
- Strapi version: 4.8.2
- Database: sqlite3 8.0.1
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

```ModuleNotFoundError: Module not found: Error: Can't resolve 'codemirror5/addon/display/placeholder'```

### Steps to reproduce the behavior

```py
$ yarn create strapi-app
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-r3f-app > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "expo-cli > xdl > @expo/dev-server > @expo/metro-config > metro-react-native-babel-transformer@0.59.0" has unmet peer dependency "@babel/core@*".
[4/4] Building fresh packages...
success Installed "create-strapi-app@4.8.2" with binaries:
      - create-strapi-app
? What would you like to name your project? (my-strapi-project)
? What would you like to name your project? my-strapi-project
? Choose your installation type (Use arrow keys)
> Quickstart (recommended)
? Choose your installation type Custom (manual settings)
? Choose your preferred language (Use arrow keys)
> JavaScript
? Choose your preferred language TypeScript
? Choose your default database client (Use arrow keys)
? Choose your default database client sqlite
? Filename: (.tmp/data.db)
? Filename: .tmp/data.db
```

```yarn build```

error: 
```ModuleNotFoundError: Module not found: Error: Can't resolve 'codemirror5/addon/display/placeholder'```

### Expected behavior

strapi builds 

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context
package.json
```json
{
  "name": "my-strapi-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/strapi": "4.8.2",
    "@strapi/plugin-users-permissions": "4.8.2",
    "@strapi/plugin-i18n": "4.8.2",
    "better-sqlite3": "8.0.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "1648832b-abf6-493b-aaa3-7794b8ca7cc0"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by antokhio** [comment]
@joshuaellis hmm, then this might be an issue with my environment, did you do that on Windows?
Checking another windows desktop, and it works!

**Comment by matepaiva** [comment]
I am with the same problem since I updated to the latest version:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'codemirror5/addon/display/placeholder' in '/home/workmedia/anteprojectos.com.pt/server/.cache/admin/src/content-manager/components/Wysiwyg'
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/Compilation.js:2022:28
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/home/workmedia/anteprojectos.com.pt/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/home/workmedia/anteprojectos.com.pt/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /home/workmedia/anteprojectos.com.pt/server/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
```

## Details:
1. The problem only happens at the server, but not in my local computer, although they have the same version (package.json) and same version of node & npm.
2. Here are the dependencies at package.json:
```
"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@strapi/plugin-i18n": "4.13.7",
    "@strapi/plugin-users-permissions": "4.13.7",
    "@strapi/strapi": "4.13.7",
    "axios": "^1.5.0",
    "crypto-js": "^4.1.1",
    "locutus": "^2.0.16",
    "lodash": "^4.17.21",
    "mysql": "2.18.1",
    "patch-package": "^8.0.0",
    "strapi-plugin-import-export-entries": "^1.21.1",
    "strapi-plugin-meilisearch": "^0.9.2",
    "strapi-plugin-multi-select": "^1.2.2",
    "strapi-plugin-preview-button": "^2.0.0",
    "strapi-plugin-schemas-to-ts": "^1.1.10",
    "strapi-plugin-slugify": "^2.3.4",
    "strapi-provider-email-smtp": "^1.0.3"
  },
```

**Comment by matepaiva** [comment]
The sad solution: using yarn.
