### ISSUE TITLE
Documentation generate RangeError

### ISSUE THREAD

**Issue by willempie96** [strapi/strapi#16205]
### Required System information

- Node.js version: 16
- NPM version: 8 
- Strapi version: 4.7.1
- Database: MariaDB
- Operating system: MacOs
- Is your project Javascript or Typescript: JS

### Describe the bug

We have a strapi system that is quite extensive (~30 entities, ~30 components, lots of custom endpoints). After adding a relation to an entity strapi won't startup anymore and shows this error: 

`
[2023-03-24 03:50:29.955] error: Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/jsonfile/utils.js:3:20)
    at Object._writeFile (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/jsonfile/index.js:66:15)
    at Object._writeFile (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/universalify/index.js:21:45)
    at Object.generateFullDoc (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/@strapi/plugin-documentation/server/services/documentation.js:207:16)
    at async Object.module.exports [as bootstrap] (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/@strapi/plugin-documentation/server/bootstrap.js:53:3)
    at async Object.bootstrap (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/@strapi/strapi/lib/Strapi.js:537:5)
    at async Strapi.bootstrap (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/@strapi/strapi/lib/Strapi.js:475:5)
`

When I disable the documentation plugin, strapi builds and works fine.
I suspect that in our case the schema has grown to big to be stringified by the JSON.stringify method used by the documentation plugin. 
Can the documentation plugin be adjusted to also accommodate to applications of a bigger scale?

**Comment by ShaheryarK** [comment]
Hi, @joshuaellis  I am also having the same error "error: Invalid string length" on typescript compilation, unable to use the documentation plugin, in my case I have around 130+ entities :( ...

**Comment by aarbanas** [comment]
Hi @ShaheryarK I am having same problem you are, but uninstalling documentation plugin did not help the issue. Project is really big and now it crashes on compiling Typescript when running `$ strapi develop` or `$ tsc`:

`strapi develop

Starting the compilation for TypeScript files in /Users/user/Test/strapi
RangeError: Invalid string length
    at writeText (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:18004:27)
    at Object.write (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:18011:13)
    at writeStringLiteral (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:112232:20)
    at emitLiteral (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109914:17)
    at pipelineEmitWithHintWorker (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109708:32)
    at pipelineEmitWithHint (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109334:17)
    at pipelineEmitWithComments (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:112936:13)
    at pipelineEmit (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109274:13)
    at emit (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109247:13)
    at emitPropertyAssignment (/Users/user/Test/strapi/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:111505:13)
`
