### ISSUE TITLE
Upgrade to 4.8.2

### ISSUE THREAD

**Issue by octohuguesdumont** [strapi/strapi#16218]
### Required System information

- Node.js version: >=14.19.1 <=18.x.x
- NPM version: >=6.0.0
- Strapi version: 4.7.1 to 4.8.2
- Database: PostgresQL
- Operating system: Linux & docker
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When I want to upgrade the strapi version from 4.7.1 to 4.8.2 a compilation error appears 

### Steps to reproduce the behavior

1. Go to strapi 4.7.1
2  update strapi to 4.8.2
3. launch npm run build

### Expected behavior
```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.resolve (node:path:1098:7)
    at /data/1J1S/workspace/1j1s-main-cms/node_modules/@strapi/admin/utils/create-cache-dir.js:82:33
    at Array.filter (<anonymous>)
    at createCacheDir (/data/1J1S/workspace/1j1s-main-cms/node_modules/@strapi/admin/utils/create-cache-dir.js:80:6)
    at async Object.build (/data/1J1S/workspace/1j1s-main-cms/node_modules/@strapi/admin/index.js:27:3)
    at async module.exports (/data/1J1S/workspace/1j1s-main-cms/node_modules/@strapi/strapi/lib/commands/build.js:12:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by octohuguesdumont** [comment]
Sorry user error

**Comment by Alexnortung** [comment]
Hello @octohuguesdumont, how did you solve this issue? And what was the user error? I am having the same issue.
