### ISSUE TITLE
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string

### ISSUE THREAD

**Issue by webhype** [strapi/strapi#16271]
### Required System information

- Node.js version: 16.20
- NPM version: 8.19.4
- Strapi version: 4.7.1 and 4.9.0
- Database: Postgres@14
- Operating system: Linux Ubuntu 22.04
- Is your project Javascript or Typescript: JS

### Describe the bug

```
~/myproject-strapi/backend$ yarn develop
yarn run v1.22.19
$ strapi develop
(node:227716) Warning: S3 configuration options passed at root level of the plugin's providerOptions is deprecated and will be removed in a future release. Please wrap them inside the 's3Options:{}' property.
(Use `node --trace-warnings ...` to show where the warning was created)
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
    at Object.continueSession (/home/linuxuser/myproject-strapi/backend/node_modules/pg/lib/sasl.js:24:11)
    at Client._handleAuthSASLContinue (/home/linuxuser/myproject-strapi/backend/node_modules/pg/lib/client.js:257:10)
    at Connection.emit (node:events:513:28)
    at Connection.emit (node:domain:489:12)
    at /home/linuxuser/myproject-strapi/backend/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/home/linuxuser/myproject-strapi/backend/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/linuxuser/myproject-strapi/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
SentryError: HTTP Error (429)
    at new SentryError (/home/linuxuser/myproject-strapi/backend/node_modules/@sentry/utils/dist/error.js:9:28)
    at ClientRequest.<anonymous> (/home/linuxuser/myproject-strapi/backend/node_modules/@sentry/node/dist/transports/base/index.js:214:44)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
[2023-03-31 20:15:44.991] debug: ⛔️ Server wasn't able to start properly.
[2023-03-31 20:15:44.995] error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/home/linuxuser/myproject-strapi/backend/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/home/linuxuser/myproject-strapi/backend/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/home/linuxuser/myproject-strapi/backend/node_modules/knex/lib/execution/runner.js:30:19)
    at async Strapi.bootstrap (/home/linuxuser/myproject-strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:437:9)
    at async Strapi.load (/home/linuxuser/myproject-strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:484:5)
    at async Strapi.start (/home/linuxuser/myproject-strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:215:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce the behavior

After moving the source code and database of a working project from Mac OS to Linux, deleting yarn.lock, node_modules and running `yarn` then `yarn build`, the backend crashes with the above error in response to the yarn develop command.

### Expected behavior

That the backend start up with no errors.

**Comment by webhype** [comment]
Anyone got a hint where to start looking? Something with S3 credentials? The database is identical on both Mac OS and Linux; completely lost as to what the problem is on Linux. Note: The identical setup works fine on Mac OS.

**Comment by webhype** [comment]
Ok this totally unintuitive error was, in fact, a Postgres error message complaining that the database was configured to expect a password, but my database user (simply `postgres` for development purposes) had no password set (as is the default on a fresh PSQL install).

So essentially this is Postgres policing itself telling me that the non-existing password for its  user `postgres` is insufficient to log in.

To resolve this, I edited the `pg_hba.conf` file ( `$ sudo nano /etc/postgresql/14/main/pg_hba.conf` ):

# "local" is for Unix domain socket connections only
#local   all             all                                     peer
local   all             all                                     trust
# IPv4 local connections:
#host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
#host    all             all             ::1/128                 scram-sha-256
host    all             all             ::1/128                 trust

This will trust all local IPs and non-IP connections with a passwordless user. Don't forget to restart Postgres:

`$ sudo systemctl restart postgresql@14-main.service`

Hope this helps someone!

**Comment by Vinntoo** [comment]
Can we get a solution for windows?

**Comment by vallesluiggi** [comment]
I can't see exactly the configuration they have, but I imagine that they have a .env 
file, this file is not being read.

Otherwise, they may not have a password for the database, if not they have an .env but instead.

Maybe you have something similar, such as .develop.env they must configure the script well so that it can find it, this will solve the problem, in any case, you need to show the package.json to check and know the name of the configuration file
