### ISSUE TITLE
Filters with populate cause error: only be used as root level operators

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [strapi/strapi#16299]
### Required System information

- Node.js version: v18.14.1
- NPM version: v9.5.0
- Strapi version: v4.9.0
- Database: PostgreSQL
- Operating system: debian
- Is your project Javascript or Typescript: Javascript

### Describe the bug

- try to filters populated field:
```
http://localhost:1337/api/posts?populate[0]=category&filters[category][$eq]=1
```

### Steps to reproduce the behavior

1. Fresh strapi project.
2. Create `Post` content type.
3. Create `Category` content type.
4. Add relation between `Post` and `Category` with : `Category has many Posts`
5. Ensure `Find` and `FindOne` Permissions for both content types.
6. Try get posts (Worked):
`http://localhost:1337/api/posts`
7. Try get posts and populate category (Worked):
`http://localhost:1337/api/posts?populate[0]=category`
8. Try get posts and populate category and use filters (Not Working):
`http://localhost:1337/api/posts?populate[0]=category&filters[category][$eq]=1`
9. Try get posts and populate category and use filters with `$and` (Not Working):
`http://localhost:1337/api/posts?populate[0]=category&filters[$and][0][category][$eq]=1`

### Code snippets
Terminal: 

```bash
[2023-04-05 06:38:23.886] error: Only $and, $or and $not can only be used as root level operators. Found $eq.
Error: Only $and, $or and $not can only be used as root level operators. Found $eq.
    at processWhere (/home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:140:13)
    at processNested (/home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:116:12)
    at processWhere (/home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:161:25)
    at processNested (/home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:116:12)
    at /home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:130:41
    at Array.map (<anonymous>)
    at processWhere (/home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:130:28)
    at /home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:108:31
    at Array.map (<anonymous>)
    at Object.processWhere (/home/nadhir/Projects/test/node_modules/@strapi/database/lib/query/helpers/where.js:108:18)

```
Api Response
```json

{
  "data": null,
  "error": {
    "status": 500,
    "name": "InternalServerError",
    "message": "Internal Server Error"
  }
}
```

**Comment by NadhirBoukhenifra** [comment]
I'm sorry.
I have solved this issue.

I had to specify the exact field of populated type:

```
// use this:
filters[category][id][$eq]=1
// instead of this: 
// XXX filters[category][$eq]=1 XXX
```
```
http://localhost:1337/api/posts?populate[0]=category&filters[category][id][$eq]=1
```

Thank you.

**Comment by Marc-Roig** [comment]
exactly! :) you need to specify the exact field of the populate type

you can see more in the docs https://docs.strapi.io/dev-docs/api/rest/populate-select
or try the #beta-bot-help discord channel, it might be useful for usecases like this 

I will close this issue as this is working for you now
