### ISSUE TITLE
Promise.deferred is obsoleted, and conflicts with babel

### ISSUE THREAD

**Issue by fishmacs** [strapi/strapi#163]
**5.3.0**:
**2.15.11**:
**1.5.4**:
**OSX**:

api/user/config/fixtures/route.js run into error:

```
error:  TypeError: _promise2.default.defer is not a function
    at Object.exports.create (/Users/zw/work/palmtao/IMSPortal/web/api/user/config/fixtures/route.js:18:28)
    at /Users/zw/work/palmtao/IMSPortal/web/config/functions/bootstrap.js:16:29
    at run (/Users/zw/work/palmtao/IMSPortal/web/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /Users/zw/work/palmtao/IMSPortal/web/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/Users/zw/work/palmtao/IMSPortal/web/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
error: Bootstrap encountered an error.
error:  TypeError: _promise2.default.defer is not a function
    at Object.exports.create (/Users/zw/work/palmtao/IMSPortal/web/api/user/config/fixtures/route.js:18:28)
    at /Users/zw/work/palmtao/IMSPortal/web/config/functions/bootstrap.js:16:29
    at run (/Users/zw/work/palmtao/IMSPortal/web/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /Users/zw/work/palmtao/IMSPortal/web/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/Users/zw/work/palmtao/IMSPortal/web/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
```

I've changed it with new Promise(...), works ok

```
exports.create = function () {
  // const deferred = Promise.defer();
  const promises = [];
  const newRoutes = [];
  let routesFound;

  return new Promise(function(resolve, reject) {
    async.auto({
      findRoutes: function (callback) {

        // Find all routes.
        strapi.orm
          .collections
          .route
          .find()
          .exec(function (err, routesFound) {
            if (err) {
              callback(err);
            } else {
              callback(null, routesFound);
            }
          });
      },
      deleteRoutes: ['findRoutes', function (callback, results) {

        // Async dependencies.
        routesFound = results.findRoutes;

        // Delete destroyed routes.
        _.forEach(routesFound, function (routeFound) {
          if (!strapi.config.routes[routeFound.name]) {
            promises.push(strapi.orm.collections.route.destroy({id: routeFound.id}));
          }
        });

        callback(null);
      }],
      updateOrCreateRoutes: ['findRoutes', function (callback, results) {

        // Async dependencies.
        routesFound = results.findRoutes;
        let verb;

        // Find or create routes.
        _.forEach(strapi.config.routes, function (route, key) {
          verb = regex.detectRoute(key).verb;

          // Check if the controller is a stringified function.
          route.controller = _.startsWith(route.controller, 'function') ? 'Specific function' : route.controller;

          if (_.find(routesFound, {name: key})) {
            promises.push(strapi.orm.collections.route.update({
              name: _.trim(key)
            }, {
              name: _.trim(key),
              policies: route.policies,
              controller: _.trim(route.controller),
              action: _.trim(route.action),
              verb: _.trim(verb)
            }));
          } else {
            newRoutes.push(_.trim(key));
            promises.push(strapi.orm.collections.route.create({
              name: _.trim(key),
              policies: route.policies,
              controller: route.controller,
              action: _.trim(route.action),
              verb: _.trim(verb)
            }));
          }
        });

        callback(null);
      }],
      execRoutesModifications: ['deleteRoutes', 'updateOrCreateRoutes', function (callback) {

        // Exec the promises.
        Promise.all(promises)
          .then(function (responses) {
            callback(null, responses);
          })
          .catch(function (err) {
            callback(err);
          });
      }],

      findNewRoutes: ['execRoutesModifications', function (callback) {

        // Find created routes.
        strapi.orm
          .collections
          .route
          .find({
            'name': newRoutes
          })
          .populate('roles')
          .exec(function (err, newRoutesFound) {
            if (err) {
              callback(err);
            } else {
              callback(null, newRoutesFound);
            }
          });
      }],
      updateCreatedRoutes: ['execRoutesModifications', 'findNewRoutes', 'findRoles', function (callback, results) {

        // Async dependencies.
        const newRoutesFound = results.findNewRoutes;
        const roles = results.findRoles;

        const userContributorRoutes = [
          'GET /user/:id',
          'PUT /user/:id',
          'DELETE /user/:id'
        ];

        const userRegisteredRoutes = [
          'PUT /user/:id',
          'DELETE /user/:id'
        ];

        let verb;

        const adminRole = _.find(roles, {
          name: 'admin'
        });

        _.forEach(newRoutesFound, function (newRoute) {
          if (!_.contains(newRoute.name, '/dashboard')) {

            // Contributor permissions.
            verb = regex.detectRoute(newRoute.name).verb;
            newRoute.verb = _.trim(verb);
            newRoute.isPublic = false;
            newRoute.registeredAuthorized = false;
            newRoute.contributorsAuthorized = false;

            if (_.contains(newRoute.name, '/auth')) {
              newRoute.isPublic = true;
            } else if (_.contains(newRoute.name, '/user')) {
              if (_.contains(userContributorRoutes, newRoute.name)) {
                newRoute.contributorsAuthorized = true;
              }
              if (_.contains(userRegisteredRoutes, newRoute.name)) {
                newRoute.registeredAuthorized = true;
              }
            } else {
              if (verb === 'get') {
                newRoute.isPublic = true;
                newRoute.registeredAuthorized = true;
              }

              newRoute.contributorsAuthorized = true;
            }

            newRoute.roles.add(adminRole.id);

            promises.push(new Promise(function (resolve, reject) {
              newRoute.save(function (err) {
                if (err) {
                  reject(err);
                }
              });

              resolve();
            }));
          }
        });

        Promise.all(promises)
          .then(function (newRoutes) {
            callback(null, newRoutes);
          })
          .catch(function (err) {
            callback(err);
          });

      }],
      findRoles: [function (callback) {

        // Find roles.
        strapi.orm
          .collections
          .role
          .find()
          .exec(function (err, roles) {
            if (err) {
              callback(err);
            } else {
              callback(null, roles);
            }
          });
      }]
    }, function cb(err, results) {
      if (err) {
        // deferred.reject(err);
        reject(err);
      } else {
        // deferred.resolve(results);
        resolve(results);
      }
    });

    // return deferred.promise;
  })
}
```

**Comment by fishmacs** [comment]
Em, seems my fix does not really work
if I put "require('babel-register')" in server.js, model lists are just weired:

![image](https://cloud.githubusercontent.com/assets/1478581/20300073/68b45bbe-ab58-11e6-9d8b-2a47ef956239.png)

**Comment by Aurelsicoko** [comment]
Can you try to downgrade to Node v4. It should fix the issue. Strapi works only with Node version <= 4

**Comment by fishmacs** [comment]
The original api/user/config/fixtures/routes.js with Promise.deferred has no problem, the problem is just about my version with new Promise(...) , I think it is not so easy to fix it.

Anyway, I downgraded node to 4.6.2, result is same.

**Comment by fishmacs** [comment]
make babel-register ignore this file, or set
```
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }],
```
in .babelrc

**Comment by Aurelsicoko** [comment]
What happens if you remove your updates and stay on Node v4? I just tested it yesterday and it worked well.

**Comment by fishmacs** [comment]
Promise.deferred not work with babel's Promise, it is ok using Node's Promise without babel polyfill. 
No matter Node 5 or 4.

**Comment by Aurelsicoko** [comment]
Is the issue fixed?

**Comment by pkoretic** [comment]
Is is possible to use it with node 6.x?
Better yet, for non production, could we use master?

**Comment by fishmacs** [comment]
Hard to say...my modification should work, but apparently it has problem with babel's polyfill.

**Comment by Aurelsicoko** [comment]
@fishmacs Can you send me your app again on Slack? I will try to fix the issue.

@pkoretic I recommend using Node 4 LTS for Strapi v1.5.4. Concerning the `master` branch, you can test it but some breaking changes could happen. We need to improve our session management, integrate the administration panel, and make optimisations. As you rightly stated, please don't use it in production!

**Comment by Aurelsicoko** [comment]
@fishmacs Is this issue fixed on your side? As you know, I tested your app and it works well on my machine.

**Comment by fishmacs** [comment]
I just bypassed this problem by let babel not to process this file. But the problem still there on my side

**Comment by Aurelsicoko** [comment]
This is weird! I used the same npm and Node version as yours... And it works well on my side. I send you a PM on our Slack. I hope that we can find and share the solution on GitHub for helping others people.

**Comment by fishmacs** [comment]
Yes, very weired! I tried node 4, just could not get it right

**Comment by Aurelsicoko** [comment]
I close this issue. The problem comes from Babel or wrong Node.js version... If it turns out that the issue comes from Strapi, please feel free to reopen it.

**Comment by pierreburgy** [comment]
@fishmacs Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.

**Comment by fishmacs** [comment]
Thank! Is it 1.5.5?

**Comment by pierreburgy** [comment]
@fishmacs it is 1.6.0: 
 - https://github.com/strapi/strapi/releases/tag/v1.6.0
 - http://blog.strapi.io/release-v1-6

**Comment by fishmacs** [comment]
great!
