### ISSUE TITLE
Internal error 500 when edit content that not exists of collection Internationalized (i18n)

### ISSUE THREAD

**Issue by lucsoliveira** [strapi/strapi#16306]
### Required System information

- Node.js version: v18.15.0
- NPM version: 9.5.0
- Strapi version: 4.9.0
- Database: MySQL 5.7
- Operating system: Linux Deepin 20.8
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When you try to update an content that not exists in an collection that was createad with "internacionalization", Strapi throw an error 500 and the console reports as follow:
Example:  [PUT] api/collection-name/id-that-not-exists

Results in the console:

`
[2023-04-05 09:52:08.969] error: Cannot read properties of null (reading 'localizations')
TypeError: Cannot read properties of null (reading 'localizations')
    at syncNonLocalizedAttributes (/home/lucas/Documents/GitHub/project/node_modules/@strapi/plugin-i18n/server/services/localizations.js:59:27)
    at Object.update (/home/lucas/Documents/GitHub/project/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:150:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.update (/home/lucas/Documents/GitHub/project/node_modules/@strapi/strapi/lib/core-api/controller/collection-type.js:84:22)
    at async returnBodyMiddleware (/home/lucas/Documents/GitHub/project/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/lucas/Documents/GitHub/project/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /home/lucas/Documents/GitHub/project/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
    at async /home/lucas/Documents/GitHub/project/node_modules/@strapi/strapi/lib/middlewares/logger.js:9:5
    at async /home/lucas/Documents/GitHub/project/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/home/lucas/Documents/GitHub/project/node_modules/@koa/cors/index.js:61:32)
`

And the response of API:

`
{
    "data": null,
    "error": {
        "status": 500,
        "name": "InternalServerError",
        "message": "Internal Server Error"
    }
}
`

### Steps to reproduce the behavior

1. Create one collection and permit internationalization; 
2. Try to edit in the PUT method of API an content Id that not exists 
3. See the error 

### Expected behavior

Expected an error 404 in the API and not an internal error in the console.

Error expected on API:
`
{
    "data": null,
    "error": {
        "status": 404,
        "name": "NotFoundError",
        "message": "Not Found",
        "details": {}
    }
}
`

### Additional context

Analysing the code of the method "syncNonLocalizedAttributes" in @strapi/plugin-i18n/server/services/localizations.js " if I change this line:
`
  if (Array.isArray(entry.localizations)) { ....}
`
To this:
`
if (entry && Array.isArray(entry.localizations)) { ... }
`

The internal error is not thorwing and returns 404 in API as expected.

**Comment by Marc-Roig** [comment]
Good one! :) Thank you for checking the possible fix, I will just create a PR with your proposal 🚀
