### ISSUE TITLE
Cannot post file - TypeError: Cannot destructure property `refId` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by madd86** [strapi/strapi#1637]
**Informations**
- **Node.js version**:  v8.10.0
- **npm version**: v6.2.0
- **Strapi version**: v3.0.0-alpha.12.7.1
- **Database**: Mongo DB 
- **Operating system**: Ubuntu

**What is the current behavior?**

Whenever I try to post a file I get the following JSON back:

```
{
    "message": "An internal server error occurred",
    "statusCode": 500,
    "error": "Internal Server Error"
}
```

And when I read the console I see the following:

```
TypeError: Cannot destructure property `refId` of 'undefined' or 'null'.
    at upload (/root/fileApi/plugins/upload/controllers/Upload.js:27:60)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Steps to reproduce the problem**

1. Create a new strapi project

2. Create a new Content Type Builder called 'upload'

3. Create a new field inside it called 'upload'

4. Try to upload a file using postman, POST on localhost:1337/upload with the header Authorization: Bearer TOKEN_HERE, and the body form-data with the key **upload** and the value the file I want to upload.

**What is the expected behavior?**

It's expected that the file be uploaded successfully.

**Suggested solutions**

No idea.

**Comment by madd86** [comment]
The problem was that there already is a /upload, it was conflicting with the content type builder I added myself.
