### ISSUE TITLE
[RBAC] Roles page is not accessible with only read permission

### ISSUE THREAD

**Issue by dobrik-ardas** [strapi/strapi#16396]
### Required System information

- Node.js version: 14.21.1
- NPM version: 6.14.17
- Strapi version: 4.9.0
- Database: mysql
- Operating system: Ubuntu 18.04
- Is your project Javascript or Typescript: Javascript

### Describe the bug

User with only READ roles permission sees white screen after opening roles section.

### Steps to reproduce the behavior

1. Give some role access to only READ roles permission
2. Login user with that role
3. Go to the settings -> roles section
4. See white screen and error in console

### Expected behavior

User should see roles list but should not have access to create, update or delete.

### Screenshots

![image](https://user-images.githubusercontent.com/57217952/232032092-d17a0e6c-4c88-41d4-9a64-ca39f0a74beb.png)
![image](https://user-images.githubusercontent.com/57217952/232032258-19f70267-f0ba-496e-a777-a8936641fde9.png)

### Additional context

URL with error: /admin/settings/roles
Console error:
`react_devtools_backend.js:2655 TypeError: Cannot read properties of undefined (reading 'onClick')
    at RoleRow (admin-roles-list.dd942762.chunk.js:99:22)
    at Ch (main.12e20ee8.js:75465:137)
    at ck (main.12e20ee8.js:75575:460)
    at bk (main.12e20ee8.js:75558:347)
    at ak (main.12e20ee8.js:75558:278)
    at Tj (main.12e20ee8.js:75558:138)
    at Lj (main.12e20ee8.js:75551:163)
    at main.12e20ee8.js:75431:115
    at exports.unstable_runWithPriority (main.12e20ee8.js:83084:343)
    at gg (main.12e20ee8.js:75430:325)`

**Comment by varloc2000** [comment]
Similar or same issue is still relevant in Strapi version: 5.40.0
---
If "Create" Role permission is enabled then person having that configured role can open Roles in settings with no problem
<img width="1101" height="365" alt="Image" src="https://github.com/user-attachments/assets/e00e98ce-0a62-475f-b2e4-6e0c63f951ec" />

<img width="1523" height="433" alt="Image" src="https://github.com/user-attachments/assets/d93c2c72-76c4-4fe9-b01a-52bf5f8814ed" />

---
**But** if "Create" Role permission is disabled and only Read Update are left.  Then person see the error when opening /admin/settings/roles page 

<img width="1081" height="362" alt="Image" src="https://github.com/user-attachments/assets/e464e373-d404-410f-a74e-31ddba43d2f4" />

<img width="1528" height="697" alt="Image" src="https://github.com/user-attachments/assets/95e8e029-7065-4261-826e-96954fd4afff" />

  
```
strapi-BWw-2Euj.js:42 TypeError: Cannot read properties of undefined (reading 'onClick')
    at de (ListPage-C1wqE-R0.js:1:736)
    at Dle (strapi-BWw-2Euj.js:40:17111)
    at lPe (strapi-BWw-2Euj.js:42:44377)
    at aPe (strapi-BWw-2Euj.js:42:40065)
    at Dpt (strapi-BWw-2Euj.js:42:39988)
    at qB (strapi-BWw-2Euj.js:42:39836)
    at jee (strapi-BWw-2Euj.js:42:36165)
    at J0e (strapi-BWw-2Euj.js:42:36975)
    at Zb (strapi-BWw-2Euj.js:40:3312)
    at strapi-BWw-2Euj.js:42:34472
```
