### ISSUE TITLE
core_store value cannot store large models due to data type

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1642]
**Informations**
- **Node.js version**: v10.7.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13
- **Database**: 10.2.16-MariaDB
- **Operating system**: Linux Mint 19 (Ubuntu 18.04)

**What is the current behavior?**

In the process of updating my project from Strapi 12.7.1 to Strapi 13 I was getting the following errors, which caused all my models to not show up in the `content-manager` but they were showing up in the `content-type-builder`:

AdminUI: 
![image](https://user-images.githubusercontent.com/8593673/43217744-3fffc034-8ff7-11e8-8574-9c370189f4b7.png)

Console:
```
(node:115966) UnhandledPromiseRejectionWarning: Error: ER_DATA_TOO_LONG: Data too long for column 'value' at row 1
    at Query.Sequence._packetToError (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
    at Protocol._enqueue (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/mysql/lib/Connection.js:200:25)
    at /nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/dialects/mysql/index.js:154:18
From previous event:
    at Client_MySQL._query (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/dialects/mysql/index.js:148:12)
    at Client_MySQL.query (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/runner.js:48:21
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/runner.js:34:31)
    at Builder.Target.then (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/interface.js:20:43)
    at Child.<anonymous> (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/bookshelf/lib/model.js:1118:36)
From previous event:
    at Child.<anonymous> (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/bookshelf/lib/model.js:1117:125)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Child.<anonymous> (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/bookshelf/lib/model.js:1000:8)
From previous event:
    at Object.set (/usr/lib/node_modules/strapi/lib/core/store.js:125:57)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:115966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:115966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce the problem**

Create a model with a **stupid** amount of fields :wink: and attempt to start the server

**What is the expected behavior?**

Strapi should store the json values in core_store with the mysql data type `longtext`

**Suggested solutions**

I've tested the fix of changing the `value` data type in the `core_store` from `text` to `longtext` and the server is able to start and all models show up.

My suggestion is to fix the bookshelf/knex creation/validation to change the core_store `value` to `longtext`

With mysql the total characters that can be stored is as such:
      TEXT |        65,535 (216−1) bytes = 64 KiB
MEDIUMTEXT |    16,777,215 (224−1) bytes = 16 MiB
  LONGTEXT | 4,294,967,295 (232−1) bytes =  4 GiB

You could probably change this to `mediumtext` but if some other crazy person creates a model bigger than one of mine they will hit the same issue.

**Comment by derrickmehaffy** [comment]
@lauriejim I was going to submit a PR for this but I'm unsure how to handle this, the related file for this is here:

https://github.com/strapi/strapi/blob/7b2ce955ff227267f1fed8a1d20876d934f77d44/packages/strapi/lib/core/store.js#L3-L30

This looks like a hard coded model that is using the following switch to set the value type:
https://github.com/strapi/strapi/blob/7b2ce955ff227267f1fed8a1d20876d934f77d44/packages/strapi-hook-bookshelf/lib/index.js#L403-L407

There doesn't seem to be an easy way to change this to longtext without setting all `text` values to `longtext`

That shouldn't cause issues (if anything beneficial for every field using `text`) However postgres doesn't have the `longtext` data type.

I'll create a PR to modify the MySQL part of this and see if you guys approve.

**Comment by derrickmehaffy** [comment]
@lauriejim @soupette I think I found the problem:

In `core_store` the column `plugin_content-manager_schema` stores all the content-manager custom views in one entry..... and in my case with ~64 models its gigantic. Way past the normal limit of a `text` field.

Technically that field should be a `json` field type in MySQL (which with MariaDB defaults to longtext)

**Comment by derrickmehaffy** [comment]
So here, that type needs to be changed to `json`: https://github.com/strapi/strapi/blob/7b2ce955ff227267f1fed8a1d20876d934f77d44/packages/strapi/lib/core/store.js#L15-L317

**Comment by derrickmehaffy** [comment]
PR Closed, resolving
