### ISSUE TITLE
(hook:strapi-mongoose) `strapi-hook-strapi-mongoose` is missing in your dependencies.

### ISSUE THREAD

**Issue by npjonath** [strapi/strapi#1644]
**Informations**
- **Node.js version**: 10.6
- **npm version**: 6.1
- **Strapi version**: 3.0.0@alpha-12.13
- **Database**: mongo
- **Operating system**: ubuntu 16.04

**What is the current behavior?**
After migration following wiki guide to alpha 12.13. I get following message : 
` warn (hook:strapi-mongoose) strapi-hook-strapi-mongoose is missing in your dependencies. Please run npm install strapi-hook-strapi-mongoose`.

then the following error : 
`error TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/home/ubuntu/stackatom/stackatom/node_modules/strapi/lib/core/store.js:55:47)
    at module.exports (/home/ubuntu/stackatom/stackatom/plugins/content-manager/config/functions/bootstrap.js:156:42)
    at Promise (/home/ubuntu/stackatom/stackatom/node_modules/strapi/lib/Strapi.js:285:13)
    at new Promise (<anonymous>)
    at execBootstrap (/home/ubuntu/stackatom/stackatom/node_modules/strapi/lib/Strapi.js:273:11)
    at Promise.all.Object.values.map.x (/home/ubuntu/stackatom/stackatom/node_modules/strapi/lib/Strapi.js:312:44)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/home/ubuntu/stackatom/stackatom/node_modules/strapi/lib/Strapi.js:312:35)
    at Strapi.start (/home/ubuntu/stackatom/stackatom/node_modules/strapi/lib/Strapi.js:107:18)`

**Steps to reproduce the problem**
Upgrading from previous version to the latest (12.13) then try to run it using "yarn run start"...
(I have updated : package.json, admin folder, plugins folder)

**What is the expected behavior?**
Make it work again.

**Suggested solutions**
 strapi-hook-strapi-mongoose  doesn't exist. It should be renammed strapi-hook-mongoose

Thanks !

**Comment by npjonath** [comment]
Ok, Just notice that I have to update database.json with the correct connector "strapi-hook-mongoose". It's working now.

**Comment by lauriejim** [comment]
@npjonath thank you for this repport. It has been add.

**Comment by adamkhan** [comment]
I just had the same problem after fiddling around with npm not knowing quite what I'm doing. @npjonath's solution fixed it for me, but in case like me anyone didn't know where the database.json file is, it's in /config/environments and then whichever of the environments you're using.
