### ISSUE TITLE
Encountered Application Error after upgrading to 4.9.2

### ISSUE THREAD

**Issue by sancel22** [strapi/strapi#16598]
### Required System information

- Node.js version: v16.19.0
- NPM version: 8.19.3
- Strapi version: 4.9.2
- Database: Mysql
- Operating system: MacOS Monterey
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After upgrading from strapi **4.9.1** to **4.9.2** i'm unable to start the aplication, i'm able to build the application (_npm run build_) but when i try to run _npm develop_ i got the following error :

>[2023-05-03 11:54:23.673] debug: ⛔️ Server wasn't able to start properly.
[2023-05-03 11:54:23.674] error: The type is required
ApplicationError: The type is required
    at getFieldSize (/strapi/node_modules/@strapi/plugin-content-manager/server/services/field-sizes.js:57:15)
    at getDefaultFieldSize (/strapi/node_modules/@strapi/plugin-content-manager/server/services/utils/configuration/layouts.js:34:10)
    ...

### Steps to reproduce the behavior

-Set version 4.9.2 in package.json
-Run npm install
-run npm run strapi develop
-get error

### Expected behavior

Strapi starts correctly

### Additional context

I am currently on version 4.8.2 and I want to upgrade to the latest available version. Upgrading to version 4.9.0 and 4.9.1 did not produce any errors. However, when I upgraded to version 4.9.2, I encountered the issue I mentioned earlier."

**Comment by Marc-Roig** [comment]
@remidej Is it possible that this might be caused by a custom field that misses some configuraation?

**Comment by antokhio** [comment]
related coversations https://discord.com/channels/811989166782021633/1104658895751876669
https://discord.com/channels/811989166782021633/1101991663502639315

**Comment by Boegie19** [comment]
https://github.com/strapi/strapi/issues/16610

Seems to me like strapi made a change that invalidates core stores if something specific is set

Also confirmed by valume

**Comment by Boegie19** [comment]
linked to https://github.com/strapi/strapi/pull/16387

**Comment by antokhio** [comment]
Would it be possible to reset thouse thru CLI or something, this also affects that if change something in `Edit View` then whenever you add new fields directly to schema.json they are displayed at the bottom of CT

**Comment by sancel22** [comment]
> Workaround is deleting your core store layouts

hi @Boegie19 I wonder where could I find this core store layouts that I should delete as a workaround.

**Comment by elsaso** [comment]
> > Workaround is deleting your core store layouts
> 
> hi @Boegie19 I wonder where could I find this core store layouts that I should delete as a workaround.

Based on the discussion on discord, it's apparently table : strapi_core_store_settings

Dropping this table for me did not solve the issue however.

**Comment by remidej** [comment]
Hello! This is an error that is supposed to be thrown when Strapi loads an incomplete custom field. Could you please share which custom fields you are using? So that we can reproduce and investigate the issue

**Comment by sancel22** [comment]
<img width="797" alt="Screen Shot 2023-06-01 at 9 09 35 AM" src="https://github.com/strapi/strapi/assets/5856449/a7b28b9b-b72c-42d4-8b5b-3933592269f3">

I am not sure if there are any custom fields, but I am only using the provided default fields in my case.

**Comment by elsaso** [comment]
> 

I'm only using default fields too, but some plugins can also create some custom fields too. Maybe we can find the culprit by comparing what plugins we have installed. 

I'm using 

"strapi-stripe": "^3.3.0"
"@strapi/plugin-i18n": "4.10.7",
"@strapi/plugin-users-permissions": "4.9.2",
"@strapi/provider-email-sendgrid": "4.9.2",
"@strapi/provider-upload-cloudinary": "4.9.2",

**Comment by Marc-Roig** [comment]
I am not able to reproduce this but my guess is, in your schema files, there is some attribute without a type. For example, I get the same error if I create a schema.json file like this:

```
{
  "kind": "collectionType",
  "collectionName": "addresses",
  "info": {
    "displayName": "Address",
    "singularName": "address",
    "pluralName": "addresses",
    "description": "",
    "name": "Address"
  },
  "attributes": {
    "postal_code": { <--- this one does not have a type
      
      "pluginOptions": {},
      "maxLength": 2
    },
    "city": {  <--- this one does 
      "type": "string",
      "required": true,
      "maxLength": 200,
      "pluginOptions": {}
    },
  }
}

```

could you check if this is the case?
@remidej I think it could be a good idea in the error message to showcase which attribute is actually missing the type property, wdyt?

**Comment by sancel22** [comment]
It's possible that that is the issue, since my codebase is from version 3.x and some schemas may not have types. I'll check it out.

**Comment by Marc-Roig** [comment]
I am glad this fixed your issue :) 
I think that we need to work on the following:
- Error message should be more explicit
- We need to mention this in a v3 migration guide

I will keep this issue opened as a tracker until that work is done :)

**Comment by JomaKar** [comment]
looks like this tool can help https://github.com/strapi/codemods
