### ISSUE TITLE
sanitize.contentAPI.query breaks components

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#16630]
### Required System information

- Node.js version: 18.9.1
- NPM version: 8.19.1
- Strapi version: 4.10.1
- Database: SQLite
- Operating system: Windows 10
- Is your project Javascript or Typescript: Javascript 

### Describe the bug

Components when senatized get a subfix of `.`

### Steps to reproduce the behavior

1. pull https://github.com/Boegie19/strapi/tree/entity-service-decorator-checklist
2. run the following command yarn test:api -- basic-compo-repeatable.test.api.js
4. See the output diffrence of senatiseQuery

Aka input
  console.log
    { populate: [ 'compo' ] }

      at Object.sanitizeQuery (packages/core/strapi/lib/core-api/controller/index.js:39:15)       
Output
  console.log
    { populate: [ 'compo.' ] }

      at Object.sanitizeQuery (packages/core/strapi/lib/core-api/controller/index.js:41:15)       

### Expected behavior

for it to not add a . behind the component

### Additional context

@joshuaellis

**Comment by Boegie19** [comment]
Let me do some more checking to figure out the conditions of this issue

**Comment by Boegie19** [comment]
Did some more research and the issue exists but I could only replicate it with tests it is because it gets set to undefined instead of null fixed it in derricks pr
