### ISSUE TITLE
[Bug]: We had to disable telemetry because of errors, but we would be happy to re-enable it

### ISSUE THREAD

**Issue by liarco** [strapi/strapi#16699]
### Required System information

- Node.js version: `v18.11.0`
- NPM version: `8.19.2`
- Strapi version: `4.10.5`
- Database: `SQLite` & `MySQL`
- Operating system: `MacOS` & `Linux`
- Is your project Javascript or Typescript: `TypeScript`

### Describe the bug

We just updated our app to `4.10.5` (previously we were using `4.8.2`) and we started getting the following error on every single call to a custom controller:
```
[2023-05-12 12:08:47.265] http: GET /api/me/tokens (33 ms) 200
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at Hash.update (node:internal/crypto/hash:109:11)
    at generateAdminUserHash (***PRIVATE_PATH***/node_modules/@strapi/strapi/lib/services/metrics/admin-user-hash.js:16:38)
    at ***PRIVATE_PATH***/node_modules/@strapi/strapi/lib/services/metrics/sender.js:64:20
    at ***PRIVATE_PATH***/node_modules/@strapi/strapi/lib/services/metrics/rate-limiter.js:12:14
    at Object.send (***PRIVATE_PATH***/node_modules/@strapi/strapi/lib/services/metrics/index.js:56:14)
    at Object.verify (***PRIVATE_PATH***/node_modules/@strapi/plugin-users-permissions/server/strategies/users-permissions.js:83:20)
    at Object.verify (***PRIVATE_PATH***/node_modules/@strapi/strapi/lib/services/auth/index.js:103:30)
    at ***PRIVATE_PATH***/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:31:23
    at dispatch (***PRIVATE_PATH***/node_modules/koa-compose/index.js:42:32)
```

I think it might be due to the following line:
https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/services/metrics/admin-user-hash.js#L16

Our project is Web3 based and we have a custom authentication method in order to avoid using any users data. That's why we removed some fields from the users entity (e.g. `password` and `email`) and we disabled the default auth method.

Disabling telemetry makes the error disappear, but we would be happy to contribute if there's any suggested way to avoid the errors.

### Steps to reproduce the behavior

Removing the `email` user field breaks the hash generation.

### Expected behavior

We suggest using a different field (e.g. `id`), this would provide with a few benefits for both Strapi and the end users:
- works on any auth configuration because that field is always required so less people would have to disable the telemetry feature
- improves security and privacy because it makes it impossible to cross-reference users from different projects (same e-mail address generates the same hash)

I hope this is useful, thank you for your time.

**Comment by Convly** [comment]
Hey there :wave: 
Thanks for reporting this issue. While this is a very uncommon scenario (_admin content types are considered internal and removing an attribute such as the email is expected to break some features_), I believe that we should do a better job at making sure we have a valid email before trying to hash it. I've thus created a PR to adjust the condition and make it more secure.

**Comment by liarco** [comment]
I completely understand your point and agree that this is definitely an unusual use case, but I really appreciate you taking the time to review this and provide a solution.

Thank you.
