### ISSUE TITLE
Could not load js config file for a custom plugin

### ISSUE THREAD

**Issue by coderjib** [strapi/strapi#16823]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.10.5
- Database: sqlite
- Operating system: Mac OS 13.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I have updated my Strapi v. 4.5.x application to 4.10.5 (latest version) ([link to repo](https://github.com/artcoded-net/strapi-devblog/tree/plugin-error)).
I also had to update my custom plugin ([link to repo](https://github.com/artcoded-net/strapi-plugin-github-projects)) (mainly to remove axios calls).
Now, when running my application in dev mode it fails with the following error, which seems to be related to @strapi/design-system plugin which I use in my custom plugin. 

```
Error: Could not load js config file /Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@artcoded/strapi-plugin-github-projects/strapi-server.js: Cannot find module '/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/design-system/dist/v2'
    at loadJsFile (/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:18:11)
    at loadFile (/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:35:14)
    at Object.loadPlugins (/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:103:26)
    at async Strapi.loadPlugins (/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/strapi/lib/Strapi.js:344:5)
    at async Promise.all (index 2)
    at async Strapi.register (/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/strapi/lib/Strapi.js:380:5)
    at async Strapi.load (/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/strapi/lib/Strapi.js:490:5)
    at async workerProcess (/Users/main/_Projects_2023_/Artcoded/_Courses/Complete-Strapi-Course/_Code/dev-blog/node_modules/@strapi/strapi/lib/commands/actions/develop/action.js:110:26)
```

Also sometimes it shows a nearly identical error related to @strapi/helper-plugin.

### Steps to reproduce the behavior

1. Clone this [app repo](https://github.com/artcoded-net/strapi-devblog/tree/plugin-error)
2. Install dependencies and try to run with `yarn develop`
3. See error in console
4. Compare source code of the plugin which is apparently causing the error ([link](https://github.com/artcoded-net/strapi-plugin-github-projects))

### Expected behavior

The app should run without errors

### Additional context

The app does run fine when downgrading my custom plugin to v. 1.0.5 (from the current 1.1.1), but since then I've made only minor changes (specifically removing axios calls and - trying to solve this issue - applying tree shaking to the design-system plugin) which I don't understand how may have caused this issue...

**Comment by coderjib** [comment]
Good morning, do you have any updates on how to solve (or at least work around) this issue? Because of this, I'm unable to update the plugin developed as part of my Strapi Course and make it compliant with the latest versions of Strapi. 
Thank you

**Comment by uigywnkiub** [comment]
> Good morning, do you have any updates on how to solve (or at least work around) this issue? Because of this, I'm unable to update the plugin developed as part of my Strapi Course and make it compliant with the latest versions of Strapi. Thank you

This will help
https://forum.strapi.io/t/error-while-building-new-plugin-cannot-find-dist-server/32458/2
