### ISSUE TITLE
docs: distDir and/or appDir property missing

### ISSUE THREAD

**Issue by woteska** [strapi/strapi#16900]
### Required System information

- Strapi version: 4

### Describe the bug

From https://docs.strapi.io/dev-docs/deployment:

```
const strapi = require('@strapi/strapi');
strapi(/* {...} */).start();
```

`strapi()` requires at least 1 property passing to it (appDir or distDir).
Calling the function without appDir or distDir throws an error that does not tell what the problem is:

```
> node .\server.js
[2023-06-02 15:51:53.162] debug: ⛔️ Server wasn't able to start properly.
[2023-06-02 15:51:53.164] error: Unknown dialect undefined
Error: Unknown dialect undefined
    at getDialectName (path-to-project\node_modules\@strapi\database\lib\dialects\index.js:36:13)
    at getDialect (path-to-project\node_modules\@strapi\database\lib\dialects\index.js:42:23)
    at new Database (path-to-project\node_modules\@strapi\database\lib\index.js:31:20)
    at Function.Database.init (path-to-project\node_modules\@strapi\database\lib\index.js:121:14)
    at Strapi.bootstrap (path-to-project\node_modules\@strapi\strapi\lib\Strapi.js:421:30)
    at Strapi.load (path-to-project\node_modules\@strapi\strapi\lib\Strapi.js:492:16)
    at async Strapi.start (path-to-project\node_modules\@strapi\strapi\lib\Strapi.js:218:9)
```

It will work:

```
const strapi = require('@strapi/strapi');
strapi({distDir: './dist'}).start();
```

### Expected behavior

- The mentioned docs should include that either distDir or appDir is required to pass.
- If distDir or appDir is not passed, Strapi should throw a descriptive error message, like: 'heyy, you forgot to pass distDir and/or appDirst'

**Comment by harshlancer** [comment]
Can I work on this ?

**Comment by alefemafra** [comment]
@woteska thanks this save me
