### ISSUE TITLE
Unable to create the new component in plugin

### ISSUE THREAD

**Issue by ryanleung96** [strapi/strapi#16935]
### Required System information

- Node.js version: 18.16.0
- NPM version: 8.12.1
- Strapi version: 4.9.2
- Database: MySQL/SQLite
- Operating system: Windows/RHEL 8
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Unable to create a new component in plugin with `createComponent` method in content type builder's components service

### Steps to reproduce the behavior

1. Create the definition of new component
2. Wait for app to start up
3. Plugin bootstrap, try to create the component

### Expected behavior

App started successfully with the newly created component

### Screenshots

![image](https://github.com/strapi/strapi/assets/47978557/0cb1704f-3179-4ef1-a1b2-d88cea97e9e6)

### Code snippets

Create new component:

```typescript
const createProductInfoComponent = async ({ strapi } : { strapi: Strapi }) => {
  console.log('creating the info component');
  let productInfoComponet = await strapi.plugin('content-type-builder').services.components.createComponent(
    {
      component: {
        catagory: 'product',
        displayName: productInfoDef.info.displayName,
        attributes: productInfoDef.attributes,
      }
    }
  );

  return productInfoComponet;
}
```

Component definition:

```json
{
  "collectionName": "components_product_prod_info",
  "info": {
    "displayName": "Product Information"
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": false
    },
    "subtitle": {
      "type": "string",
      "required": false
    },
    "image": {
      "type": "media",
      "required": false,
      "multiple": false,
      "allowedType": [
        "images"
      ]
    },
    "description" : {
      "type": "richtext",
      "required": false
    },
    "lang": {
      "type": "enumeration",
      "enum": [
          "zh",
          "en"
      ],
      "required": true
    }
  }
}
```

### Additional context

Errorlog:

```
> yarn develop
yarn run v1.22.17
warning ..\..\..\..\package.json: No license field
$ strapi develop
Starting the compilation for TypeScript files in C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms
component init
skip updating pricing comp
creating the details component
{
  title: { type: 'string', required: false },
  subtitle: { type: 'string', required: false },
  ext_url: { type: 'string', required: false },
  caption: { type: 'string', required: false },
  image: {
    type: 'media',
    required: false,
    multiple: false,
    allowedType: [ 'images' ]
  },
  description: { type: 'richtext', required: false },
  lang: { type: 'enumeration', enum: [ 'zh', 'en' ], required: true }
}
[2023-06-07 14:57:54.173] debug: ⛔️ Server wasn't able to start properly.
[2023-06-07 14:57:54.174] error: Cannot read properties of undefined (reading 'attributes')
    at Object.getNonVisibleAttributes (C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\@strapi\utils\lib\content-types.js:69:11)
    at getNestedFields (C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\@strapi\admin\server\services\content-type.js:30:51)
    at C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\@strapi\admin\server\services\content-type.js:43:31
    at C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\lodash\lodash.js:928:11
    at C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\lodash\lodash.js:3032:24)
    at C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\lodash\lodash.js:4936:18
    at baseReduce (C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\lodash\lodash.js:925:5)
    at Function.reduce (C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\lodash\lodash.js:9749:14)
    at getNestedFields (C:\Users\01667492\Desktop\GitLab Projects\ebb\ebb-cms\node_modules\@strapi\admin\server\services\content-type.js:32:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by derrickmehaffy** [comment]
duplicate: https://feedback.strapi.io/developer-experience/p/components-inside-of-plugins
