### ISSUE TITLE
Strapi errors in Heroku

### ISSUE THREAD

**Issue by bgrabbi** [strapi/strapi#16943]
My strapi project is working on local and i am able to open the urls
with out any error

    http://localhost:1337/admin/settings/application-infos
    http://localhost:1337/admin/plugins/content-type-builder/content-types/api::account-cms.account-cms

but when i push and deploy on heroku i am getting below error

    13react_devtools_backend_compact.js:2367 TypeError: Property description must be an object: undefined
        at defineProperty (<anonymous>)
        at ye (7909.4877546f.chunk.js:504:1387)
        at ss (main.1de49b44.js:48:54759)
        at h4 (main.1de49b44.js:52:9145)
        at bd (main.1de49b44.js:52:989)
        at l4 (main.1de49b44.js:52:917)
        at h0 (main.1de49b44.js:52:768)
        at U0 (main.1de49b44.js:50:11072)
        at main.1de49b44.js:48:39565
        at f.unstable_runWithPriority (main.1de49b44.js:84:3950)
    overrideMethod @ react_devtools_backend_compact.js:2367
    7909.4877546f.chunk.js:504 

I tried to purge cache and updated yarn.lock and deployed many times but i am getting same error. i am connected to same database 

### Required System information

```
{
  "name": "main_p",
  "private": true,
  "version": "0.1.1",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.0.7",
    "@strapi/icons": "^1.7.3",
    "@strapi/plugin-graphql": "^4.1.8",
    "@strapi/plugin-i18n": "4.4.3",
    "@strapi/plugin-users-permissions": "4.4.3",
    "@strapi/provider-email-sendgrid": "^4.1.12",
    "@strapi/provider-upload-aws-s3": "^4.1.9",
    "@strapi/strapi": "4.4.3",
    "chargebee": "^2.10.0",
    "cheerio": "^1.0.0-rc.11",
    "koa-static": "^5.0.0",
    "mime-types": "^2.1.35",
    "moment": "^2.29.3",
    "pg": "^8.6.0",
    "pg-connection-string": "^2.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sanitize-filename": "^1.6.3",
    "strapi-plugin-measurement-protocol": "^1.0.1",
    "strapi-provider-email-smtp": "^1.0.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "9b33cdcc-bad0-4fee-a674-da565a2a2b4c"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": "8.11.0"
  },
  "license": "MIT"
}

```

- Is your project Javascript or Typescript: Javascript

### Describe the bug
Unable to open settings and Content-Type builder pages.
When I refresh from browser. Page can open
when I click from side menu. pages show the error in screenshot

### Steps to reproduce the behavior

Install strapi with package.json
deploy to Heroku

### Expected behavior

<img width="503" alt="Screenshot 2023-06-07 at 4 26 55 PM" src="https://github.com/strapi/strapi/assets/114888857/683ea9e6-02fa-4a1b-8d3c-7f4df2017239">

**Comment by bgrabbi** [comment]
anything on this bug

**Comment by Boegie19** [comment]
This is 1 a building issue or a database issue spesfic to Heroku
