### ISSUE TITLE
strapi can not start caused by setting sql_require_primary_key

### ISSUE THREAD

**Issue by cataglyphis** [strapi/strapi#16954]
- Strapi version: 4.10.5 (node v16.15.1)  
- Database: AWS Aurora MySQL 8.0.23
- ProxySQL: 2.5.2-217-g7f727b3

From the error logs, It said that strapi cms service want to set `sql_require_primary_key` to "OFF", but this failed.
The default value of variable `sql_require_primary_key` in Aurora is "OFF". 
Why strapi cms tries to set sql_require_primary_key when connecting to database?

```
2023-06-08 07:14:03 MySQL_Session.cpp:2602:handler_again___status_SETTING_GENERIC_VARIABLE(): [WARNING] Error while setting sql_require_primary_key to "OFF" on pre-us-instance-1.cp22vumu2eah.us-west-1.rds.amazonaws.com:3306 hg 1 :  1235, This version of MySQL doesn't yet support 'Modifying this variable at the session level'
2023-06-08 07:14:03 MySQL_Session.cpp:240:kill_query_thread(): [WARNING] KILL CONNECTION 80989 on pre-us-instance-1.cp22vumu2eah.us-west-1.rds.amazonaws.com:3306
2023-06-08 07:14:04 MySQL_Session.cpp:2602:handler_again___status_SETTING_GENERIC_VARIABLE(): [WARNING] Error while setting sql_require_primary_key to "OFF" on pre-us-instance-1.cp22vumu2eah.us-west-1.rds.amazonaws.com:3306 hg 1 :  1235, This version of MySQL doesn't yet support 'Modifying this variable at the session level'
2023-06-08 07:14:04 MySQL_Session.cpp:240:kill_query_thread(): [WARNING] KILL CONNECTION 80991 on pre-us-instance-1.cp22vumu2eah.us-west-1.rds.amazonaws.com:3306
2023-06-08 07:14:04 MySQL_Session.cpp:2602:handler_again___status_SETTING_GENERIC_VARIABLE(): [WARNING] Error while setting sql_require_primary_key to "OFF" on pre-us-instance-1.cp22vumu2eah.us-west-1.rds.amazonaws.com:3306 hg 1 :  1235, This version of MySQL doesn't yet support 'Modifying this variable at the session level'
2023-06-08 07:14:04 MySQL_Session.cpp:240:kill_query_thread(): [WARNING] KILL CONNECTION 80993 on pre-us-instance-1.cp22vumu2eah.us-west-1.rds.amazonaws.com:3306
```

strapi logs
```
yarn run v1.22.19
$ strapi start
{
  method: 'raw',
  sql: 'set session sql_require_primary_key = 0;',
  bindings: [],
  options: {},
  __knexQueryUid: 'vOoZghk7-1LnZaPWdXY4q'
}
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = database()',
    bindings: [ 'strapi_core_store_settings' ],
    output: [Function: output]
  }
]
{
  method: 'raw',
  sql: 'SELECT version() as version',
  bindings: [],
  options: {},
  __knexQueryUid: 'BEnwybRw6gEEvBCdr8V1N'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'strapi_content_types_schema', 1 ],
  __knexQueryUid: 'qjQmPXcOCV-GddXw7kaxz',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` = ? and `t0`.`environment` is null and `t0`.`tag` is null) limit ?'
}
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = database()',
    bindings: [ 'strapi_migrations' ],
    output: [Function: output]
  }
]
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'D3slNbAfPJETiIOwddCrB',
  sql: 'select * from `strapi_migrations` order by `time` asc'
}
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = database()',
    bindings: [ 'strapi_database_schema' ],
    output: [Function: output]
  }
]
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: 'rErCDFJ_khxLC2_Y-JQyJ',
  sql: 'select * from `strapi_database_schema` order by `time` DESC limit ?'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'strapi_content_types_schema', 1 ],
  __knexQueryUid: 'E_Ti0YtVIixKS8XcA4Nde',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` = ? and `t0`.`environment` is null and `t0`.`tag` is null) limit ?'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: 'aWuCEHyh9Bnruznn9OGQh',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`id` = ?) limit ?'
}
{
  method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    '{"admin::permission":{"collectionName":"admin_permissions","info":{"name":"Permission","description":"","singularName":"permission","pluralName":"permissions","displayName":"Permission"},"options":{},"pluginOptions":{"content-manager":{"visible":false},"content-type-builder":{"visible":false}},"attributes":{"action":{"type":"string","minLength":1,"configurable":false,"required":true},"subject":{"type":"string","minLength":1,"configurable":false,"required":false},"properties":{"type":"json","configurable":false,"required":false,"default":{}},"conditions":{"type":"json","configurable":false,"required":false,"default":[]},"role":{"configurable":false,"type":"relation","relation":"manyToOne","inversedBy":"permissions","target":"admin::role"},"createdAt":{"type":"datetime"},"updatedAt":{"type":"datetime"},"createdBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true},"updatedBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true}},"kind":"collectionType","__schema__":{"collectionName":"admin_permissions","info":{"name":"Permission","description":"","singularName":"permission","pluralName":"permissions","displayName":"Permission"},"options":{},"pluginOptions":{"content-manager":{"visible":false},"content-type-builder":{"visible":false}},"attributes":{"action":{"type":"string","minLength":1,"configurable":false,"required":true},"subject":{"type":"string","minLength":1,"configurable":false,"required":false},"properties":{"type":"json","configurable":false,"required":false,"default":{}},"conditions":{"type":"json","configurable":false,"required":false,"default":[]},"role":{"configurable":false,"type":"relation","relation":"manyToOne","inversedBy":"permissions","target":"admin::role"}},"kind":"collectionType"},"modelType":"contentType","modelName":"permission","connection":"default","uid":"admin::permission","plugi
n":"admin","globalId":"AdminPermission"},"admin::user":{"collectionName":"admin_users","info":{"name":"User","description":"","singularName":"user","pluralName":"users","displayName":"User"},"pluginOptions":{"content-manager":{"visible":false},"content-type-builder":{"visible":false}},"attributes":{"firstname":{"type":"string","unique":false,"minLength":1,"configurable":false,"required":false},"lastname":{"type":"string","unique":false,"minLength":1,"configurable":false,"required":false},"username":{"type":"string","unique":false,"configurable":false,"required":false},"email":{"type":"email","minLength":6,"configurable":false,"required":true,"unique":true,"private":true},"password":{"type":"password","minLength":6,"configurable":false,"required":false,"private":true,"searchable":false},"resetPasswordToken":{"type":"string","configurable":false,"private":true,"searchable":false},"registrationToken":{"type":"string","configurable":false,"private":true,"searchable":false},"isActive":{"type":"boolean","default":false,"configurable":false,"private":true},"roles":{"configurable":false,"private":true,"type":"relation","relation":"manyToMany","inversedBy":"users","target":"admin::role","collectionName":"strapi_users_roles"},"blocked":{"type":"boolean","default":false,"configurable":false,"private":true},"preferedLanguage":{"type":"string","configurable":false,"required":false,"searchable":false},"createdAt":{"type":"datetime"},"updatedAt":{"type":"datetime"},"createdBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true},"updatedBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true}},"kind":"collectionType","__schema__":{"collectionName":"admin_users","info":{"name":"User","description":"","singularName":"user","pluralName":"users","displayName":"User"},"pluginOptions":{"content-manager":{"visible":false},"content-typ
e-builder":{"visible":false}},"attributes":{"firstname":{"type":"string","unique":false,"minLength":1,"configurable":false,"required":false},"lastname":{"type":"string","unique":false,"minLength":1,"configurable":false,"required":false},"username":{"type":"string","unique":false,"configurable":false,"required":false},"email":{"type":"email","minLength":6,"configurable":false,"required":true,"unique":true,"private":true},"password":{"type":"password","minLength":6,"configurable":false,"required":false,"private":true,"searchable":false},"resetPasswordToken":{"type":"string","configurable":false,"private":true,"searchable":false},"registrationToken":{"type":"string","configurable":false,"private":true,"searchable":false},"isActive":{"type":"boolean","default":false,"configurable":false,"private":true},"roles":{"configurable":false,"private":true,"type":"relation","relation":"manyToMany","inversedBy":"users","target":"admin::role","collectionName":"strapi_users_roles"},"blocked":{"type":"boolean","default":false,"configurable":false,"private":true},"preferedLanguage":{"type":"string","configurable":false,"required":false,"searchable":false}},"kind":"collectionType"},"modelType":"contentType","modelName":"user","connection":"default","uid":"admin::user","plugin":"admin","globalId":"AdminUser"},"admin::role":{"collectionName":"admin_roles","info":{"name":"Role","description":"","singularName":"role","pluralName":"roles","displayName":"Role"},"options":{},"pluginOptions":{"content-manager":{"visible":false},"content-type-builder":{"visible":false}},"attributes":{"name":{"type":"string","minLength":1,"unique":true,"configurable":false,"required":true},"code":{"type":"string","minLength":1,"unique":true,"configurable":false,"required":true},"description":{"type":"string","configurable":false},"users":{"configurable":false,"type":"relation","relation":"manyToMany","mappedBy":"roles","target":"admin::user"},"permissions":{"configurable":false,"type":"relation","relation":"oneToMany","mappedBy":"role","target":"admin::permis
sion"},"createdAt":{"type":"datetime"},"updatedAt":{"type":"datetime"},"createdBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true},"updatedBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true}},"kind":"collectionType","__schema__":{"collectionName":"admin_roles","info":{"name":"Role","description":"","singularName":"role","pluralName":"roles","displayName":"Role"},"options":{},"pluginOptions":{"content-manager":{"visible":false},"content-type-builder":{"visible":false}},"attributes":{"name":{"type":"string","minLength":1,"unique":true,"configurable":false,"required":true},"code":{"type":"string","minLength":1,"unique":true,"configurable":false,"required":true},"description":{"type":"string","configurable":false},"users":{"configurable":false,"type":"relation","relation":"manyToMany","mappedBy":"roles","target":"admin::user"},"permissions":{"configurable":false,"type":"relation","relation":"oneToMany","mappedBy":"role","target":"admin::permission"}},"kind":"collectionType"},"modelType":"contentType","modelName":"role","connection":"default","uid":"admin::role","plugin":"admin","globalId":"AdminRole"},"admin::api-token":{"collectionName":"strapi_api_tokens","info":{"name":"Api Token","singularName":"api-token","pluralName":"api-tokens","displayName":"Api Token","description":""},"options":{},"pluginOptions":{"content-manager":{"visible":false},"content-type-builder":{"visible":false}},"attributes":{"name":{"type":"string","minLength":1,"configurable":false,"required":true,"unique":true},"description":{"type":"string","minLength":1,"configurable":false,"required":false,"default":""},"type":{"type":"enumeration","enum":["read-only","full-access","custom"],"configurable":false,"required":true,"default":"read-only"},"accessKey":{"type":"string","minLength":1,"configurable":false,"required":true,"searchable":fal
se},"lastUsedAt":{"type":"datetime","configurable":false,"required":false},"permissions":{"type":"relation","target":"admin::api-token-permission","relation":"oneToMany","mappedBy":"token","configurable":false,"required":false},"expiresAt":{"type":"datetime","configurable":false,"required":false},"lifespan":{"type":"biginteger","configurable":false,"required":false},"createdAt":{"type":"datetime"},"updatedAt":{"type":"datetime"},"createdBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true},"updatedBy":{"type":"relation","relation":"oneToOne","target":"admin::user","configurable":false,"writable":false,"visible":false,"useJoinTable":false,"private":true}},"kind":"collectionType","__schema__":{"collectionName":"strapi_api_tokens","info":{"name":"Api Token","singularName":"api-token","pluralName":"api-tokens","displayName":"Api Token","description":""},"options":{},"pluginOptions":{"content-manager":{"visible":false},"content-type-builder":{"visible":false}},"attributes":{"name":{"type":"string","minLength":1,"configurable":false,"required":true,"unique":true},"description":{"type":"string","minLength":1,"configurable":false,"required":false,"default":""},"type":{"type":"enumeration","enum":["read-only","full-access","custom"],"configurable":false,"required":true,"default":"read-only"},"accessKey":{"type":"string","minLength":1,"configurable":false,"required":true,"searchable":false},"lastUsedAt":{"type":"datetime","configurable":false,"required":false},"permissions":{"type":"relation","target":"admin::api-token-permission","relation":"oneToMany","mappedBy":"token","configurable":false,"required":false},"expiresAt":{"type":"datetime","configurable":false,"required":false},"lifespan"'... 136017 more characters,
    'object',
    1
  ],
  __knexQueryUid: 'TcN9RTbYvMxjTjMIs2WsP',
  sql: 'update `strapi_core_store_settings` set `value` = ?, `type` = ? where (`id` = ?)'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: 'DoYUkR76q1bzrFvLB1wgq',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`id` = ?) limit ?'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'e7cqIedyviJFApCebSkMf',
  sql: 'select `t0`.* from `strapi_webhooks` as `t0`'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'plugin_content_manager_configuration_components%' ],
  __knexQueryUid: '2pSXMe799vSrps1UEFND0',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` like ?)'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'plugin_content_manager_configuration_content_types%' ],
  __knexQueryUid: 'GO7CMfbfywJS5mjoCmMFI',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` like ?)'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    'plugin_content_manager_configuration_content_types::admin::permission',
    1
  ],
  __knexQueryUid: '6Nsg7okk0kdfP8SO_YxrX',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` = ? and `t0`.`environment` is null and `t0`.`tag` is null) limit ?'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    'plugin_content_manager_configuration_content_types::admin::user',
    1
  ],
  __knexQueryUid: 'T7gKBtOpgivBl4DXhEdM7',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` = ? and `t0`.`environment` is null and `t0`.`tag` is null) limit ?'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    'plugin_content_manager_configuration_content_types::admin::role',
    1
  ],
  __knexQueryUid: 'n3TF66wXqV6OXyjp7w-NL',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` = ? and `t0`.`environment` is null and `t0`.`tag` is null) limit ?'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    'plugin_content_manager_configuration_content_types::admin::api-token',
    1
  ],
  __knexQueryUid: 'Um1XS2uFcfy2v7gzanCKg',
  sql: 'select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` = ? and `t0`.`environment` is null and `t0`.`tag` is null) limit ?'
}
[2023-06-08 12:04:24.167] debug: ⛔️ Server wasn't able to start properly.
[2023-06-08 12:04:24.169] error: select `t0`.* from `strapi_core_store_settings` as `t0` where (`t0`.`key` = 'plugin_content_manager_configuration_content_types::admin::user' and `t0`.`environment` is null and `t0`.`tag` is null) limit 1 - ER_NOT_SUPPORTED_YET: This version of MySQL doesn't yet support 'Modifying this variable at the session level'
Error: ER_NOT_SUPPORTED_YET: This version of MySQL doesn't yet support 'Modifying this variable at the session level'
    at Query.Sequence._packetToError (/opt/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/opt/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/opt/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/opt/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/opt/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/opt/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/opt/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/opt/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (/opt/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/opt/node_modules/mysql/lib/Connection.js:198:25)
    at /opt/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/opt/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/opt/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/opt/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/opt/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/opt/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/opt/node_modules/knex/lib/execution/runner.js:300:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by derrickmehaffy** [comment]
We don't support AWS Aurora as it's not an official native version of PostgreSQL, MySQL, or MariaDB.

Since it's proprietary and offers no way to run in an isolated environment for testing we have no plans to support it.
