### ISSUE TITLE
I am getting following error while start the new strapi project. Kindly advice me to get a solution?

### ISSUE THREAD

**Issue by Anbarasan-321** [strapi/strapi#1695]
D:\node>strapi new Demo-Project
? Start creating your Strapi application. It might take a minute, please take a
coffee ??

Lets configurate the connection to your database:
? Choose your main database: MySQL
? Database name: node-demo-1
? Host: localhost
? Port: 3306
? Username: root
? Password:

‼ An error occurred during settings-manager plugin installation.
{ Error: Command failed: node C:\Users\AppData\Roaming\npm\node_mo
dules\strapi\bin\strapi.js install settings-manager
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\Users\\AppData\\Roaming\\npm\\node_modules\\stra
pi\\bin\\strapi.js install settings-manager ' }
‼ An error occurred during content-type-builder plugin installation.
{ Error: Command failed: node C:\Users\AppData\Roaming\npm\node_mo
dules\strapi\bin\strapi.js install content-type-builder
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\Users\\AppData\\Roaming\\npm\\node_modules\\stra
pi\\bin\\strapi.js install content-type-builder ' }
‼ An error occurred during content-manager plugin installation.
{ Error: Command failed: node C:\Users\AppData\Roaming\npm\node_mo
dules\strapi\bin\strapi.js install content-manager
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\Users\\AppData\\Roaming\\npm\\node_modules\\stra
pi\\bin\\strapi.js install content-manager ' }
‼ An error occurred during users-permissions plugin installation.
{ Error: Command failed: node C:\Users\AppData\Roaming\npm\node_mo
dules\strapi\bin\strapi.js install users-permissions
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\Users\\AppData\\Roaming\\npm\\node_modules\\stra
pi\\bin\\strapi.js install users-permissions ' }
‼ An error occurred during email plugin installation.
{ Error: Command failed: node C:\Users\AppData\Roaming\npm\node_mo
dules\strapi\bin\strapi.js install email
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\Users\\AppData\\Roaming\\npm\\node_modules\\stra
pi\\bin\\strapi.js install email ' }
‼ An error occurred during upload plugin installation.
{ Error: Command failed: node C:\Users\AppData\Roaming\npm\node_mo
dules\strapi\bin\strapi.js install upload
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\Users\\AppData\\Roaming\\npm\\node_modules\\stra
pi\\bin\\strapi.js install upload ' }
√ Link strapi dependency to the project.

? Your new application Demo-Project is ready at D:\node\Demo-Project.

?? change directory:
$ cd Demo-Project

?? start application:
$ strapi start

**Comment by lauriejim** [comment]
Hello @Anbarasan-321 , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
