### ISSUE TITLE
Strapi wont start after editing schema because of duplicate index keyname

### ISSUE THREAD

**Issue by willempie96** [strapi/strapi#16959]
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.11.0
- Database: MariaDB 10.6.5
- Operating system: Mac
- Is your project Javascript or Typescript: JS

### Describe the bug

When starting up strapi after a schema change (adding a field to an entity) strapi wont startup and throws an error:

``
Error: alter table `upload_folders` add unique `upload_folders_path_index`(`path`) - Duplicate key name 'upload_folders_path_index'
    at Packet.asError (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/mysql2/lib/connection.js:490:32)
    at PacketParser.onPacket (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/mysql2/lib/connection.js:95:12)
    at PacketParser.executeStart (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/user/Documents/GitHub/btstay-platform-api/node_modules/mysql2/lib/connection.js:102:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUP_KEYNAME',
  errno: 1061,
  sqlState: '42000',
  sqlMessage: "Duplicate key name 'upload_folders_path_index'",
  sql: 'alter table `upload_folders` add unique `upload_folders_path_index`(`path`)'
}
``

If i delete that index it starts throwing errors about another one.

### Expected behavior

Strapi starts up :)

**Comment by willempie96** [comment]
This seems to be a problem explicitly with mariaDB vs mysql. MariaDB returns a string value for index.Non_unique whilst mysql returns a bit (0/1).

**Comment by Boegie19** [comment]
Mind giving replication staps?

**Comment by willempie96** [comment]
The problem on startup is hard to reproduce because it seems to be really specific to our database schema/custom logic. In other projects the underlying problem doesn't seem to escalate towards the breaking on startup. 
But i am able to demonstrate the underlying problem / presumed mistake in the strapi source code:

https://github.com/willempie96/16959-reproduction
I have created a new strapi project running on a mariadb database. (You can use the docker compose in the repo for the database) In this strapi project i have created an entity 'blog' that has a unique field 'slug.'
To demonstrate the problem that occurs you can overwrite the strapi schema-inspector with the file in the repo. So replace node_modules/@strapi/database/lib/dialects/mysql/schema-inspector.js with schema-inspector.js. In this version of the schema inspector i log the data concerning the 'blogs' table about the database schema requested from the database and the resulting model of the schema generated by strapi. 

It will probably run on the first startup but to trigger it yourself you can empty the strapi_database_schema table in the database. This will trigger a regeneration of this database schema.

In the logs that will result you should see the following:
``
RowDataPacket {
  Table: 'blogs',
  Non_unique: '0',
  Key_name: 'blogs_slug_unique',
  Seq_in_index: '1',
  Column_name: 'slug',
  Collation: 'A',
  Cardinality: '0',
  Sub_part: null,
  Packed: null,
  Null: 'YES',
  Index_type: 'BTREE',
  Comment: '',
  Index_comment: '',
  Ignored: 'NO'
}

{
  blogs_slug_unique: { columns: [ 'slug' ], name: 'blogs_slug_unique', type: null },
  blogs_created_by_id_fk: {
    columns: [ 'created_by_id' ],
    name: 'blogs_created_by_id_fk',
    type: null
  },
  blogs_updated_by_id_fk: {
    columns: [ 'updated_by_id' ],
    name: 'blogs_updated_by_id_fk',
    type: null
  }
}
``

Note that the value retrieved from the database about the key has Non_unique: '0'. So this should result in a type unique but the generated keys for this table show that the type of the blogs_slug_unique key is null instead of 'unique'.
If you were to do this same test with a mysql database you will see that the value of Non_unique will be 0 and the type of the generated key will be 'unique'

The reason for this is that schema inspector on line 177 (183 in my modified file) checks for the truthy value of index.Non_unique. The mysql value of 0 results in the truthy value of false whilst the mariadb value of '0' results in the truthy value of true. 

(In the meantime we have been migrating our databases to mysql instead of mariadb so we will not be having this issue any longer, but this is something that should be fixed if you want to have mariadb support)

**Comment by derrickmehaffy** [comment]
While the error message is different this is likely because the long name is being truncated by the database making this a duplicate of https://github.com/strapi/strapi/issues/13117

**Comment by willempie96** [comment]
I'm sorry but this has nothing to do with long index names. The problem here is that because mariadb and mysql seem to give different values for if an index (not related to its length) i a non_unique index the schema inspector won't handle the mariadb version the right way

**Comment by derrickmehaffy** [comment]
Ahhh gotcha, sorry I didn't completely read through your last comment will reopen so we can fix it.

**Comment by Anurag-modgil** [comment]
can i work on this issue ?

**Comment by hanpaine** [comment]
This was fixed by #19351 in 5.0.2 (during beta phase)
