### ISSUE TITLE
Dynamic zone breaks after upgrading from 4.9.2 to 4.11.0

### ISSUE THREAD

**Issue by jastrand** [strapi/strapi#16966]
### Required System information

- Node.js version: 16
- NPM version: 6
- Strapi version: 4.11.0
- Database: postgres
- Operating system: ios

### Describe the bug

After upgrading from 4.9.2 to 4.11.0 strapi admin breaks with "Woops! Something went wrong. Please, try again" after trying to use a component in the dynamic zone. 

### Steps to reproduce the behavior

1. In the strapi admin ui, go to any collection type using dynamic zone.
2. Click on any of the components in the dynamic zone to add it
4. See error "Woops! Something went wrong. Please, try again" and the console logs:

```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at Object.entries.reduce (content-manager.4e46c41a.chunk.js:6660:67)
    at Array.reduce (<anonymous>)
    at findAllAndReplace (content-manager.4e46c41a.chunk.js:6651:39)
    at content-manager.4e46c41a.chunk.js:6782:40
    at produce (main.e40cee3e.js:45810:15892)
    at reducer (content-manager.4e46c41a.chunk.js:6728:32)
    at Object.fi [as useReducer] (main.e40cee3e.js:75945:451)
    at exports.useReducer (main.e40cee3e.js:86305:274)
    at EditViewDataManagerProvider (content-manager.4e46c41a.chunk.js:7052:56)
    at Xh (main.e40cee3e.js:75942:137)
```

### Expected behavior

Expected to be able to use components in the zone :) 

### Screenshots

How the UI looks like before click: 

<img width="338" alt="image" src="https://github.com/strapi/strapi/assets/57670121/2b5c8127-f9b1-44e0-ad68-b92c805a83ba">

How the ui looks when click on any of the components: 

<img width="785" alt="image" src="https://github.com/strapi/strapi/assets/57670121/ac67ed78-752a-44e8-a6da-4e56e7d520e2">

### Code snippets

This is one example of the schema for one of the components:

```
{
  "collectionName": "components_landing_pages_big_numbers",
  "info": {
    "displayName": "Big Numbers",
    "description": "",
    "icon": "bold"
  },
  "options": {},
  "attributes": {
    "header": {
      "type": "text",
      "required": false
    },
    "items": {
      "type": "component",
      "repeatable": true,
      "max": 4,
      "min": 2,
      "component": "landing-pages.big-number-item"
    },
    "disclaimer": {
      "type": "text"
    },
    "backgroundColor": {
      "type": "enumeration",
      "enum": [
        "None",
        "Yellow",
        "Alpha"
      ],
      "default": "None"
    }
  }
}
```

Let me know if I can provide any more context, thanks

**Comment by BorisKamp** [comment]
I have the same while I'm close to a deadline. Now I cannot enter my content, this is really urgent to fix guys!

Context from my side:

1. In only get the error when I try to select a component from the dynamic zone which has a nested component in it. Meaning I can select a component which only has a text field in it, but I cannot select a component which has a nested other component in it.
2. Downgrading does not fix the problem.
3. I have this locally and on my production server

**Comment by jastrand** [comment]
I have tested again and can also confirm that this is only happening for components with nested components.

**Comment by joshuaellis** [comment]
Thanks for the report everyone – this was an oversight, there's a PR to resolve this open now

**Comment by BorisKamp** [comment]
> 

Okay, any ETA on the release that should fix this? Because I really need the fix asap (-:

**Comment by joshuaellis** [comment]
> Okay, any ETA on the release that should fix this? Because I really need the fix asap (-:

The PR is open and the aim is 4.11.1 which we're hoping to release on Monday. That's all I can say for now. You could, if it's blocking you over the weekend use patch-package temporarily until the patch is released.

**Comment by BorisKamp** [comment]
> 

Okay thank you for the reply, I understand. Can you elaborate a bit on the Patch package and how I can 'use' that in the meantime?

**Comment by BorisKamp** [comment]
@joshuaellis 
When I use patch-package and I change the `node_modules/@strapi/admin/admin/src/content-manager/components/DynamicZone/index.js` file and run `yarn patch-package @strapi/strapi` I get `There don't appear to be any changes` back. Although I changed the file I can confirm because the problem is fixed when I run strapi locally.

**Comment by BarrySaikSoundry** [comment]
OMG - this has caused me hours of problems!  Glad to find this fix.

**Comment by zrothauser** [comment]
I'm not sure if this is exactly the same issue (I can open a new ticket, but it seems to be related), but I get the same error page when loading a collection type with a Dynamic Zone. I get the error as soon as I open an entry of that collection type though, and not when trying to add to the dynamic zone. 

I tried applying the patch with `patch-package`, but it doesn't seem to resolve the issue. 

My console log output is slightly different:
```
react_devtools_backend_compact.js:2367 TypeError: Cannot read properties of undefined (reading 'Root')
    at _n (content-manager.25c6d328.chunk.js:770:10202)
    at Ju (main.0b04b030.js:488:20587)
    at Mh (main.0b04b030.js:490:45446)
    at Oh (main.0b04b030.js:490:41049)
    at Ch (main.0b04b030.js:490:40977)
    at Ff (main.0b04b030.js:490:40829)
    at lc (main.0b04b030.js:490:37074)
    at eh (main.0b04b030.js:490:36002)
    at H (main.0b04b030.js:529:1553)
    at MessagePort.We (main.0b04b030.js:529:1923)
```

**Comment by joshuaellis** [comment]
That looks like some sort of interference with react-dev tools. I'd look at your extensions

**Comment by Alexnortung** [comment]
After applying the patch it is now possible to add items to dynamic zones, however I still exerience issues when navigating. If I open an entry that has a dynamic zone (Page) and then click back or on the collection type name in the sidebar, I get a runtime error. Has this been resolved or should that be opened as a new issue?

**Comment by zrothauser** [comment]
@joshuaellis I still get the same error with React dev-tools disabled, and with Strapi 4.11.1:

```
main.76fb801e.js:490 TypeError: Cannot read properties of undefined (reading 'Root')
    at Jn (content-manager.55dedc2e.chunk.js:770:10202)
    at Ju (main.76fb801e.js:488:20588)
    at Mh (main.76fb801e.js:490:45446)
    at Oh (main.76fb801e.js:490:41049)
    at Ch (main.76fb801e.js:490:40977)
    at Ff (main.76fb801e.js:490:40829)
    at lc (main.76fb801e.js:490:37074)
    at eh (main.76fb801e.js:490:36002)
    at V (main.76fb801e.js:529:1568)
    at MessagePort.ze (main.76fb801e.js:529:1937)
```

**Comment by cooperwfloyd** [comment]
not fixed on my end as well, and this isn't a browser extension error because it's happening with all extensions disabled. 4.11.1 on core, admin, graphql, etc.

in production, getting an error on the frontend when querying the collection in the content manager that has a recently created component in it's dynamic zone. it's hitting a `layouts.edit.reduce` in the `configuration.json` that it's looping through, so I pulled the response from that file and found that the new component that I've created doesn't have a `layouts.edit` property. getting an infinite load when trying to access the collection in the content type manager, so I'm totally bricked currently.

**Comment by VeladzicS** [comment]
Not fixed for me as well. I am using Strapi version "4.11.3". 

When trying to add a Dynamic Zone component I get "Woops! Something went wrong. Please, try again." and the error message in browser console. 

I used incognito browser, deleted .cache and package.lock, run the build again. Only happens in production, in development everything works.

"``main.e1de1f7e.js:658 TypeError: Cannot read properties of undefined (reading 'Root')
    at yo (content-manager.60a7eea5.chunk.js:913:5786)
    at z (main.e1de1f7e.js:656:20696)
    at Vh (main.e1de1f7e.js:658:45915)
    at of (main.e1de1f7e.js:658:41497)
    at rf (main.e1de1f7e.js:658:41425)
    at dh (main.e1de1f7e.js:658:41276)
    at jh (main.e1de1f7e.js:658:37490)
    at tf (main.e1de1f7e.js:658:38309)
    at Dl (main.e1de1f7e.js:656:3311)
    at main.e1de1f7e.js:658:35751
