### ISSUE TITLE
strapi admin breaks - Any Content type with DynamicZone Component - "Woops! Something went wrong. Please, try again"

### ISSUE THREAD

**Issue by cherring07** [strapi/strapi#17008]
- Node.js version: 16.16.0
- NPM version: 8.11
- Strapi version: 4.11.1
- Database: Either
- Operating system: Linux
-Typescript:

### Steps to reproduce the behavior

1. From the admin list view click on a content type containing a dynamic component (with data)
2. Visual error = Woops! Something went wrong. Please, try again.
3. Console error = TypeError: Cannot read properties of undefined (reading 'Root') at Jn (content-manager.dce90948.chunk.js:770:10201)

**Comment by cherring07** [comment]
Just to add this is happening on a fresh npm install

**Comment by Pavan-Sai-Grandhi** [comment]
Same issue here. Attaching image for reference.
<img width="915" alt="image" src="https://github.com/strapi/strapi/assets/77682875/a8a89862-5457-4457-a55b-abc4deb349b0">

**Comment by joshuaellis** [comment]
This sounds like a react error, there are no clear reproduction steps apart from @cherring07's guideline of "fresh NPM install" so i've done `create-strapi-app@latest` to confirm, there doesn't seem to be any issue. LMK if there's something else I should have done 👍🏼

**Comment by cherring07** [comment]
I will attempt to get a repo with the issue together. 

The issue did not exist in 4.10.8 and below. 

When I run `strapi build --no-optimization`  
```
TypeError: Cannot read properties of undefined (reading 'Root') at Jn (content-manager.dce90948.chunk.js:770:10201)
```
Points to

```
 /* @__PURE__ */ react.createElement(v2.Menu.Root, null, /* @__PURE__ */ react.createElement(v2.Menu.Trigger, { size: "S", endIcon: void 0, paddingLeft: 2, paddingRight: 2 }, /* @__PURE__ */ react.createElement(More/* default */.Z, { "aria-hidden": true, focusable: false }), /* @__PURE__ */ react.createElement(VisuallyHidden/* VisuallyHidden */.T, { as: "span" }, formatMessage({
    id: (0,utils/* getTrad */.OB)("options.DynamicZone.more-actions"),
    defaultMessage: "More actions"
  }))),

```

**Comment by joshuaellis** [comment]
> I will attempt to get a repo with the issue together.
> 
> The issue did not exist in 4.10.8 and below.
> 
> When I run `strapi build --no-optimization`
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'Root') at Jn (content-manager.dce90948.chunk.js:770:10201)
> ```
> 
> Points to
> 
> ```
>  /* @__PURE__ */ react.createElement(v2.Menu.Root, null, /* @__PURE__ */ react.createElement(v2.Menu.Trigger, { size: "S", endIcon: void 0, paddingLeft: 2, paddingRight: 2 }, /* @__PURE__ */ react.createElement(More/* default */.Z, { "aria-hidden": true, focusable: false }), /* @__PURE__ */ react.createElement(VisuallyHidden/* VisuallyHidden */.T, { as: "span" }, formatMessage({
>     id: (0,utils/* getTrad */.OB)("options.DynamicZone.more-actions"),
>     defaultMessage: "More actions"
>   }))),
> ```

Thanks for the additional info can you run `npm ls @strapi/design-system`?

**Comment by Boegie19** [comment]
@joshuaellis Did you test javascript or ts?

**Comment by ekimv** [comment]
Hello,

I just upgraded from 4.10.5 to 4.11.1 and I have almost the same issue.
I have some personnal plugins, but they are working well as I have some collection types with no dynamic zone with these plugins.
The issue occurs only when you have to display the dynamic zone chooser or to display existing components in the dynamic zone :
![simplescreenrecorder-2023-06-20_14 44 22](https://github.com/strapi/strapi/assets/75667665/09310ab8-2e6c-4c66-bb8b-cb518af4f981)

As it is old content types, can it be the content types schema that have info.icon (when it was with fontAwesome) ?
I will try to remove my icons and I tell you... Otherwise, I will go back to 4.10.8

**Comment by ekimv** [comment]
I have tried to remove all my icons on the content-types, but unfortunately, the issue was still there.

After multiple tests, I found that it was due, for my part, to a patch that I realized on Strapi (to display a helper with a screenshot of each component on mouseover...)
Finally, I don't have this issue anymore

**Comment by Krak86** [comment]
I have the same issue. Tested each prev version, and everything works ok, seems that it's not working with content types that have dynamic zones.
P.S. UI is crashes, but endpoint works as expected

**Comment by muffeeee** [comment]
I had the same issue, in 4.11.2. Tried re-installing packages and re-building several times.

As I could not reproduce the issue myself in a new Strapi installation, I assumed that this was the cause of a plugin. I started by removing strapi-plugin-preview-button, which is the only plugin I have that alters the front-end (even though it has nothing to do with the Dynamic Zone..). This did work - however, after re-installing the same plugin at the same version, the problem did not reappear, so as I was not able to fully reproduce this, I am not 100% sure that that plugin was the cause of my issues.

However, I would suggest that anyone who faces this issues tries to remove some plugins and see if that works. It doesn't really seem like it's a problem with Strapi itself.

**Comment by Maxservais** [comment]
Can confirm I am facing the same issue with 4.11.1 and 4.11.2. When I downgrade to 4.10.8 everything seems fine again.

Using TS on nodejs 18

**Comment by Boegie19** [comment]
@Maxservais Is most likely that strpai changed someting what one of the plugins did not like

**Comment by Pablo-Aldana** [comment]
I'm having same issue since upgraded but not related with dynamic zone. When I'm viewing a record and click the back button this is happening all the times. 

It also happening when I click on the different content type that all the screen gets blank and I need to F5 to make it work again. This also happens like 6/10 which makes impossible to work since upgrade to 4.11.X.

In terms of plugins I only have meilisearch and sitemap

**Comment by Boegie19** [comment]
@Pablo-Aldana I would remove the plugins rebuild your admin and see if it is fixed

**Comment by YannickFi** [comment]
I'm having the same issue with Strapi v4.11.3 and node v18. The issue only occurs when Strapi is configured with TypeScript. Disabling and removing plugins did not resolve the error. Only switching back to JS helped.

**Comment by joshuaellis** [comment]
This has been open for three weeks, we're unable to reproduce the error and no one has been able to give us a viable reproduction – therefore I am going to close this issue. If you can supply a minimal reproduction of said error, please open a new issue.

**Comment by cherring07** [comment]
The move from 4.10.8 up introduced potentially a number of issues regarding Dynamic Zone #17008, #16966 & #17086. A minor release 4.10.8 to 4.11.* shouldn't introduce breaking changes, especially as 3rd party plugins require consistency between releases.

**Comment by Pablo-Aldana** [comment]
Attaching a video on the behaviour and the error on the browser logs


https://github.com/strapi/strapi/assets/9969839/c5e24b3c-4604-4ace-aa3a-ca504d078c36


I'm not using dynamics zones tho and I show different errors on different content types.

Attached the error I can appreciate is thrown every time that happens

![image](https://github.com/strapi/strapi/assets/9969839/54c42199-c0ca-4730-8050-6aa37d6448a1) in the meantime  I would appreciate if you  leave the issue open so that we don't need to create new ones as seems is affecting a lot of people and doesn't have a step reproduction yet doesn't evade the issue itself, just delay the problem and possible fix

**Comment by Boegie19** [comment]
Again we need minimal reproduction aka reproduction steps since if we can't replicate the issue we can't fix it

**Comment by joshuaellis** [comment]
> The move from 4.10.8 up introduced potentially a number of issues regarding Dynamic Zone #17008, #16966 & #17086. A minor release 4.10.8 to 4.11.* shouldn't introduce breaking changes, especially as 3rd party plugins require consistency between releases.

Bugs happen – one issue was resolved almost immediately, the others had no reproduction steps and third party plugins caused the issue, if you can tell us what the breaking change is, we can solve it – but because no one can provide consistent reproduction steps in strapi we can't identify what you believe it be a breaking change.

**Comment by derrickmehaffy** [comment]
reopening and flagging with EE due to internal TID 4189

Still pending reproduction

**Comment by joshuaellis** [comment]
> reopening and flagging with EE due to internal TID 4189
> 
> Still pending reproduction

Will you be able to share the repro steps here when you have them?

**Comment by Pablo-Aldana** [comment]
I managed to reproduce the issue by installing the plugin https://www.npmjs.com/package/strapi-plugin-sitemap/v/2.1.0-beta.2 if you disable the plugin and rebuild the admin, it will stop the issue.

**Comment by joshuaellis** [comment]
I think the issue here is plugin developers have been writing `useEffect` with an async function which `react` does not allow, see line 19 - https://www.npmjs.com/package/strapi-plugin-sitemap/v/2.1.0-beta.2?activeTab=code

They did fix this however – https://github.com/boazpoolman/strapi-plugin-sitemap/pull/118/files

But i suspect this is the issue for everyone to be honest.

**Comment by derrickmehaffy** [comment]
@joshuaellis for the EE ticket, we are waiting for the customer to provide us their package.json so we can see what plugins they have installed to test with.

**Comment by zirho** [comment]
I had the similar issue and I think I found a reason. 
Not sure if this is the same bug but I guess it could help someone to debug it.

Mine is happening when you are adding a new field after updating list view options.

I debugged it in chrome console

![image](https://github.com/strapi/strapi/assets/1251296/19b56023-925d-498f-9cd3-03da6448deed)

so basically ` t.contentType.metadatas[u]` is undefined but you are acessing `.list` 

```
const m = t.contentType.metadatas[u].list;
```

Mine was related to your admin configuration.

![image](https://github.com/strapi/strapi/assets/1251296/c4867d51-801a-4aed-87c3-7f84a74079ef)

so try 

1. setup a new strapi 
2. custom list view with [order, max list count] so on
3. add a new field
