### ISSUE TITLE
Error when using locale=all and Populate

### ISSUE THREAD

**Issue by meganoob1337** [strapi/strapi#17116]
### Required System information

- Node.js version: 16.19.0
- NPM version:  8.19.3
- Strapi version: 4.11.1
- Database: Postgres
- Operating system: Mac (idk what version atm)
- Is your project Javascript or Typescript: JS

### Describe the bug
I have a Middleware that gets called on the find and findAll routes:

``` 

module.exports = (config, { strapi }) => {

  return async (ctx, next) => {
    console.log( ctx?.query)
    if(!ctx.query.locale) {
      ctx.query.locale="all";
    }
    if (!ctx.query.populate) {
      ctx.query.populate="deep,4"
    }
    console.log( ctx?.query);

    await next();
  };
};

```

And i get the Following error :
```
{}
{ locale: 'all', populate: 'deep,4' }
[2023-06-27 17:36:18.955] error: Populate must be an object
Error: Populate must be an object
    at Object.processPopulate (strapi-v4/node_modules/@strapi/database/lib/query/helpers/populate/process.js:70:11)
    at Object.processState (strapi-v4/node_modules/@strapi/database/lib/query/query-builder.js:318:32)
    at Object.getKnexQuery (strapi-v4/node_modules/@strapi/database/lib/query/query-builder.js:354:12)
    at Object.execute (strapi-v4/node_modules/@strapi/database/lib/query/query-builder.js:475:25)
    at Object.findMany (strapi-v4/node_modules/@strapi/database/lib/entity-manager/index.js:189:70)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.find (strapi-v4/node_modules/@strapi/strapi/lib/core-api/controller/single-type.js:22:22)
    at async returnBodyMiddleware (strapi-v4/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async strapi-v4/src/middlewares/pageResolver.js:19:5
    at async policiesMiddleware (strapi-v4/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
```
If i comment out either the locale=all or the populate deep its working, but both together are not working 

### Expected behavior

it should not break :D
### Additional context

Talked with Boegie19 on disc he will elaborate further

**Comment by Boegie19** [comment]
@Marc-Roig It seems like what we did in the entity service broke this I think somehow

**Comment by Boegie19** [comment]
forgot to transformParamsToQuery in #16486. will make a pr to fix this later today

**Comment by Marc-Roig** [comment]
👍 you are right, nice catch Boegie
