### ISSUE TITLE
Documentation plugin generate json with errors

### ISSUE THREAD

**Issue by teddybee** [strapi/strapi#17180]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.7.6
- Strapi version: 4.11.3
- Database: sqlite
- Operating system: Windows 11
- Is your project Javascript or Typescript: typescript

### Describe the bug

I am using the documentation plugin and openapi-generator-cli to generate client side api service for Strapi.
Looks like the generated full_documentation.json has some incompatibility with the standard. I have got these errors:
```
Errors:
        -info.contact.mywebsite.io
        -paths.'/upload?id={id}'. Declared path parameter id needs to be defined as a path parameter in path or operation level

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
the second one can be fixed by changing this part of the json:
```
"/upload?id={id}": {
      "post": {
        "parameters": [
          {
            "name": "id",
            "in": "query", //this should be changed to "path"
            "description": "File id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
```

### Steps to reproduce the behavior

1. Install the documentation plugin
2. In a client side project (for example React ) generate client side api by this script:
3. "rimraf gen/api && openapi-generator-cli generate -i ../strapi-backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json --generator-name typescript-axios -o gen/api --config api.json && cd gen/api && npm install && npm run build"

### Expected behavior

The generation should be finished without error.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by teddybee** [comment]
PS: the first error can be fixed by adding http:// to the row in info part
```
"info": {
    "version": "1.0.0",
    "title": "DOCUMENTATION",
    "description": "",
    "termsOfService": "YOUR_TERMS_OF_SERVICE_URL",
    "contact": {
      "name": "TEAM",
      "email": "contact-email@something.io",
      "url": "http://mywebsite.io"                        //this should be a correct url
    },
```

**Comment by teddybee** [comment]
Other than that, a type (UploadIdIdPostRequestFileInfo) is somehow missing in the generated code, I don`t know it it is your bug or the generator`s
```
public uploadididPost(id: string, fileInfo?: UploadIdIdPostRequestFileInfo, files?: File, options?: AxiosRequestConfig) {   
}
```
