### ISSUE TITLE
updateMany with relations

### ISSUE THREAD

**Issue by luzadev** [strapi/strapi#17264]
### System information

- Node.js version: 16.10.0
- NPM version: 7.24.0
- Strapi version: 4.11.4
- Database: MySql V8
- Operating system: MacOs Ventura 13.4.11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I want to update a table relation with another table (Many-to-One).

This is my function: 

```
const result = await strapi.db.query('api::slot.slot').updateMany({
                  where: {
                    rifAnagraficheSlot: {
                      id: 1
                    },
                    nWeek: 1,
                    anno: 2023,
                  },
                  data: {
                    qtaIniziale: 3,
                  },
                });
```

I get the following error:

```shell
Error: ER_BAD_FIELD_ERROR: Unknown column 't0.id' in 'on clause'
    at Query.Sequence._packetToError (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
    --------------------
    at Protocol._enqueue (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/execution/runner.js:300:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.run (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.execute (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/@strapi/database/lib/query/query-builder.js:481:22)
    at async Object.updateMany (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/@strapi/database/lib/entity-manager/index.js:361:27)
    at async Object.caricaSlotInizioAnno (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/dist/src/api/custom-r/controllers/custom-r.js:71:38)
    at async returnBodyMiddleware (/Users/luciano/Sviluppo/Omp/Progetti/Viberti/server/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 't0.id' in 'on clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'update `slots` left join `slots_rif_anagrafiche_slot_links` as `t1` on `t0`.`id` = `t1`.`slot_id` left join `anagrafiche_slots` as `t2` on `t1`.`anagrafiche_slot_id` = `t2`.`id` set `qta_iniziale` = 4 where (`t2`.`id` = 1 and `n_week` = 51 and `anno` = 2023)'
}
```

### Question

I think the problem is that querybuilder miss to insert alias 't0' after 'slots' table.

**Comment by luzadev** [comment]
I just find the possible issue:

../node_modules/@strapi/database/lib/query/query-builder.js

at line 265 of this file...

`mustUseAlias() {
      return ['select', 'count'].includes(state.type);
    },`

I've added 'update' into array like this:

`mustUseAlias() {
      return ['select', 'count', 'update'].includes(state.type);
    },`

After this change its work fine.
