### ISSUE TITLE
Strapi server wasn't able to start properly, Error aborted

### ISSUE THREAD

**Issue by supercede** [strapi/strapi#17272]
### Required System information

- Node.js version: 16.18
- NPM version: 8.19
- Strapi version: 4.6.1
- Database: Postgres
- Operating system: Alpine Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I'm trying to deploy my Strapi application but when I run `strapi start`, the app crashes and I get the following error:

```
⛔️ Server wasn't able to start properly.
   Error aborted
    at PendingOperation.abort (/opt/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /opt/app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /opt/app/node_modules/tarn/dist/Pool.js:207:53
    at Client_PG.destroy (/opt/app/node_modules/knex/lib/client.js:338:9)
    at Database.destroy (/opt/app/node_modules/@strapi/database/lib/index.js:109:5)
    at Strapi.destroy (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:236:7)
    at process.terminateStrapi (/opt/app/node_modules/@strapi/strapi/lib/utils/signals.js:12:7)
```

### Steps to reproduce the behavior

1. Build app with dockerfile
2. Run `npm start`

### Expected behavior

App should start

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by joshuaellis** [comment]
Can you share your dockerfile? there's simply not enough information here to debug this issue.

**Comment by supercede** [comment]
Hi, turns out it was a database connection issue. It's been resolved.

**Comment by devm3rt** [comment]
> Hi, turns out it was a database connection issue. It's been resolved.

Hello, could you share your solution? Was it in the Strapi code, or did you modify your database?
