### ISSUE TITLE
V3 won't build when running `make setup`

### ISSUE THREAD

**Issue by chrisbull** [strapi/strapi#173]
When doing a fresh setup/build by cloning and running `make setup` an error is given:
```
./scripts/setup.sh
Installing dependencies...
Bootstraping packages and building dashboard...
This can take few minutes (2-3)
module.js:472
    throw err;
    ^

Error: Cannot find module '.../packages/strapi/node_modules/lerna/bin/lerna'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
make: *** [setup] Error 1
```

So after running through the `./scripts/setup.sh` manually, I run the command `node node_modules/lerna/bin/lerna bootstrap` but with the error response:
```
Lerna v2.0.0-beta.30
`packages/` directory does not exist, have you run `lerna init`?
```

Then ran `lerna init`: which ruturned: `-bash: lerna: command not found`

So in short, I found that I need lerna globally installed.

Solution:

Installed lerna `npm install -g lerna`

However... now I'm getting a link error for 'strapi-mongoose'.

Does anyone have this working, and how?

Thanks

**Comment by chrisbull** [comment]
Nevermind. It's because Lerna bases the package files based on .git and I had not yet initiated git.
