### ISSUE TITLE
Deleting content-type with extra file called *.js.* or *.ts.* then the app fails to start

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#17360]
### Required System information

- Node.js version: 18
- NPM version: 8
- Strapi version: 4.11.5
- Database: SQLite
- Operating system: Linux Mint 21.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When you have an extra file that is named `*.js.*` or `*.ts.*` and delete the content-type via the content-type builder you will get an error that it can't find the content-type schema. Example would be: `src/api/test/content-types/test/test.js.whatever`

```
The server is restarting

Error: Could not load content type found at /home/dmehaffy/Development/deleteCT/src/api/test/content-types
    at loadContentTypes (/home/dmehaffy/Development/deleteCT/node_modules/@strapi/strapi/lib/core/loaders/apis.js:120:13)
    at async Promise.all (index 7)
    at async loadAPI (/home/dmehaffy/Development/deleteCT/node_modules/@strapi/strapi/lib/core/loaders/apis.js:73:5)
    at async module.exports [as loadAPIs] (/home/dmehaffy/Development/deleteCT/node_modules/@strapi/strapi/lib/core/loaders/apis.js:36:17)
    at async Strapi.loadAPIs (/home/dmehaffy/Development/deleteCT/node_modules/@strapi/strapi/lib/Strapi.js:353:5)
    at async Promise.all (index 4)
    at async Strapi.register (/home/dmehaffy/Development/deleteCT/node_modules/@strapi/strapi/lib/Strapi.js:381:5)
    at async Strapi.load (/home/dmehaffy/Development/deleteCT/node_modules/@strapi/strapi/lib/Strapi.js:491:5)
    at async workerProcess (/home/dmehaffy/Development/deleteCT/node_modules/@strapi/strapi/lib/commands/actions/develop/action.js:110:26)
Done in 16.51s.
```

### Steps to reproduce the behavior

1. Create a content-type and manually add a file with any name ending in `.js.disabled` into the `content-types/CTName/` directory
2. Start the server
3. Use the CTB to try and delete the content-type

### Expected behavior

Our file parser should not care if the file has a suffix and should delete the entire directory regardless

### Screenshots

N/A

### Code snippets

N/A

### Additional context

Internal TID4347

**Comment by amanmalh** [comment]
Hi @derrickmehaffy, [this condition](https://github.com/strapi/strapi/blob/main/packages/core/content-type-builder/server/services/api-handler.js#L86C17-L86C17) is preventing any file other than `<content-type>.<extension>` or `schema.json` from being deleted (not just `*.js.* or *.ts.*` files as mentioned on the issue). Is there any particular file we want to prevent from being deleted? Else, we can remove this condition altogether to delete the entire directory.

**Comment by amanmalh** [comment]
> there
@derrickmehaffy How should we proceed on this?

**Comment by derrickmehaffy** [comment]
We'll need to wait for an engineer to confirm it and start working on it.

**Comment by sivakrishnamattadev** [comment]
I faced the similar issue today; I added one new content-type and then deleted my changes / undo changes as the approach is not working. since then, the app having some running issue as mentioned like you.

Error: Could not load content type found at C:\xxx-backend\src\api\app-setting\content-types

Solution worked for me: Delete the respective folder which was create by the content-type which is expecting while starting the app.

**Comment by ayhid** [comment]
Opened #27208 for this.

Root cause: `createDeleteApiFunction` in `packages/core/content-type-builder/server/src/services/api-handler.ts` matches files with `path.basename(filePath, path.extname(filePath))`. `path.extname` only reads the last dot-segment, so `test.js.whatever` becomes `test.js`, which never equals the model name `test`. The stray file is kept, `recursiveRemoveFiles` therefore sees a non-empty directory and skips removing the folder, and `content-types/test/` survives without its `schema.json`. On the next boot `loadContentTypes` finds a schema-less content type folder and throws, so the server never comes back up.

The PR treats every file under `content-types/<name>` as belonging to that content type, so the folder is emptied and removed whatever it holds. Files elsewhere in the API folder keep the existing name-based matching and are untouched.

It also includes two related fixes in `@strapi/core`'s api loader: `loadDir` now skips files it cannot parse instead of registering them under a mangled key (`foo.js.bak` became a `foo-js` entry holding an empty object), and the error names the offending content type folder rather than its parent — as reported here, the message points at `content-types` and gives no clue which content type is broken.

Covered by new unit tests in both packages, verified to fail on `develop` and pass with the change.
