### ISSUE TITLE
Export from local Strapi errors out with http

### ISSUE THREAD

**Issue by PascalFilion** [strapi/strapi#17481]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.7
- Database: Postgres
- Operating system: Windows 10
- Is your project Javascript or Typescript: Strapi itself

### Describe the bug

When performing an export from a local Strapi instance, the export fails due to not supporting `http` protocol.

### Steps to reproduce the behavior

Invoke the following command:
`yarn strapi export --no-encrypt --no-compress`

### Expected behavior

The export should succeed successfully.

### Output

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new NodeError (node:internal/errors:399:5)
    at new ClientRequest (node:_http_client:189:11)
    at request (node:https:360:10)
    at Object.get (node:https:394:15)
    at <my_project>\node_modules\@strapi\data-transfer\dist\strapi\providers\local-source\assets.js:35:14
    at new Promise (<anonymous>)
    at getFileStats (<my_project>\node_modules\@strapi\data-transfer\dist\strapi\providers\local-source\assets.js:33:12)
    at generator (<my_project>\node_modules\@strapi\data-transfer\dist\strapi\providers\local-source\assets.js:66:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async next (node:internal/streams/from:85:11)
Emitted 'error' event on Duplexify instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_INVALID_PROTOCOL'
```

### Local fix

- I changed
`node_modules\@strapi\data-transfer\dist\strapi\providers\local-source\assets.js`
 to include http module
 `const http_1 = __importDefault(require("http"));`
- Then I changed
  `https_1.default`
  to
  ```
    const client = filepath.startsWith('https:') ? https_1 : http_1;
    client.default
  ```
  and the export succeeded successfully.

**Comment by builtim** [comment]
Same issue here. Can't export in dev as images on localhost are accessed via HTTP.

**Comment by innerdvations** [comment]
I'm unable to reproduce the error, but I created [this PR](https://github.com/strapi/strapi/pull/17537) in case someone who can reproduce is able to check that it solves the problem.

**Comment by davimdantas** [comment]
> I'm unable to reproduce the error, but I created [this PR](https://github.com/strapi/strapi/pull/17537) in case someone who can reproduce is able to check that it solves the problem.

That fixed my problem, thank you @innerdvations 

Is there any chance of it being applied? I'm currently on v4.13.7
