### ISSUE TITLE
Can't load 

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1749]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**:  v3.0.0-alpha.13.1
- **Database**: postgres
- **Operating system**: Ubuntu Linux/WSL

**What is the current behavior?**

When loading the content type builder for a model, I get the following error:

```
[2018-08-14T15:07:38.403Z] debug GET /content-type-builder/connections (108 ms)
TypeError: Cannot read property 'attributes' of undefined
    at _.forEach (~/test-strapi/plugins/content-type-builder/services/ContentTypeBuilder.js:90:130)
    at ~/test-strapi/plugins/content-type-builder/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (~/test-strapi/plugins/content-type-builder/node_modules/lodash/lodash.js:3010:24)
    at ~/test-strapi/plugins/content-type-builder/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (~/test-strapi/plugins/content-type-builder/node_modules/lodash/lodash.js:9342:14)
    at Object.getModel (~/test-strapi/plugins/content-type-builder/services/ContentTypeBuilder.js:76:7)
    at getModel (~/test-strapi/plugins/content-type-builder/controllers/ContentTypeBuilder.js:27:31)
    at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/usr/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at policies.push (/usr/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:59:26)
    at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at module.exports (~/test-strapi/plugins/users-permissions/config/policies/permissions.js:24:20)
[2018-08-14T15:07:38.452Z] debug GET /content-type-builder/models/pagemodule? (148 ms)
```

Then the page prompts me to ask new fields, when the overview page says it already has 4 fields.

**Steps to reproduce the problem**

Create a model with the following attributes:

``` json
{
  "connection": "default",
  "collectionName": "pagemodules",
  "info": {
    "name": "pagemodule",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "config": {
      "type": "json"
    },
    "pages": {
      "collection": "page",
      "via": "pageModules",
      "dominant": true
    },
    "pageModuleType": {
      "model": "pageModuleType"
    }
  }
}
```

If required, please let me know if the other models are also required to debug this.

**What is the expected behavior?**

load the fields for editing

**Suggested solutions**

This is the affected line of the function: `getModel` of `plugins/content-type-builder/services/ContentTypeBuilder.js`

``` js
params.targetColumnName = _.get((params.plugin ? strapi.plugins[params.plugin].models : strapi.models )[params.target].attributes[params.key], 'columnName', '');
```

It looks like you will always expect to have a `params.target` and that model has one.
To me, this looks like the model - when created, was misconfigured.

**Comment by lauriejim** [comment]
Hello @MartinMuzatko I think you issue is related to this issue https://github.com/strapi/strapi/issues/1139
Please try to lowercase your relations attributes.

**Comment by MartinMuzatko** [comment]
Maybe partially. I see that when I use lowerCamelCase, that there are always all lowercase attributes added, that I did not add.

Model:
![image](https://user-images.githubusercontent.com/2950505/44337190-0617f980-a47a-11e8-999c-fc15b7dc224f.png)

Response:
![image](https://user-images.githubusercontent.com/2950505/44337152-ea145800-a479-11e8-9295-d99ecfbcd554.png)

**Comment by derrickmehaffy** [comment]
@lauriejim wouldn't it just be best to make sure model callbacks are always lowercase as to not mess with the field case? something like `field.tolowercase()`

**Comment by derrickmehaffy** [comment]
I agree @MartinMuzatko there was some discussion on this a while back (for the life of me can't find the issue I created :laughing: )

Everyone has different case types they normally use, I think honestly Strapi shouldn't limit users to a particular type and just handle the creation and management as far as needed, actual display values shouldn't be breaking thing (Both in the AdminUI and in the Rest/GraphQL response)

If I have a `camelCase` or a `break_case` being shown in the Rest strapi should handle these however it needs to in the backend (and database) but leave them in the frontend.

**Comment by derrickmehaffy** [comment]
My original issue I outlined was the values displayed in the left menu, right now it can be quite ugly especially when it uses Plural values on things that should not be Plural.
