### ISSUE TITLE
Installation by guideline

### ISSUE THREAD

**Issue by nanocreaator** [strapi/strapi#175]
Hello guys!

I just installed strapi based on the docs you have on the website and I had some issues that I would like to share with you.
I guess it's a minor issue however, new users might be discouraged to continue ... 

strapi start
warn: The `package.json` in the current directory does not list Strapi as a dependency...
warn: Are you sure /Users/mario/Documents/Apps/jobs is a Strapi application?
info: Server started in /Users/mario/Documents/Apps/jobs
info: Your server is running at http://localhost:1337
info: Your admin panel is available at http://localhost:1337/admin/
debug: Time: Wed Jan 04 2017 22:48:05 GMT+0100 (CET)
debug: Environment: development
debug: Process PID: 9585
debug: Cluster: master
info: To shut down your server, press <CTRL> + C at any time

error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/Users/mario/Documents/Apps/jobs/api/user/config/fixtures/route.js:18:28)
error: Bootstrap encountered an error.
error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/Users/mario/Documents/Apps/jobs/api/user/config/fixtures/route.js:18:28)
(node:9585) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Callback was already called.
(node:9585) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
debug: GET / (5ms)
...
...
  Error: Route not found
      at Object.isUserAuthorized (/Users/mario/Documents/Apps/jobs/api/user/services/user.js:91:13)
      at isUserAuthorized.next (<anonymous>)
      at onFulfilled (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/co/index.js:65:19)
      at tryCatcher (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
      at Promise._settlePromiseAt (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
      at Promise._settlePromises (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
      at Async._drainQueue (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
      at tryOnImmediate (timers.js:624:5)
      at processImmediate [as _immediateCallback] (timers.js:596:5)

debug: GET /admin/config (4ms)
debug: GET /admin/assets/images/user-picture.png (2ms)
debug: GET /admin/assets/images/logo.png (2ms)
debug: GET /admin/routes (3ms)

  Error: Route not found
      at Object.isUserAuthorized (/Users/mario/Documents/Apps/jobs/api/user/services/user.js:91:13)
      at isUserAuthorized.next (<anonymous>)
      at onFulfilled (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/co/index.js:65:19)
      at tryCatcher (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
      at Promise._settlePromiseAt (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:1

<img width="1039" alt="captura de tela 2017-01-04 as 22 53 23" src="https://cloud.githubusercontent.com/assets/3308721/21660722/e03a4faa-d2d0-11e6-8764-373c3319c08a.png">

<img width="1304" alt="captura de tela 2017-01-04 as 22 52 44" src="https://cloud.githubusercontent.com/assets/3308721/21660727/e559d348-d2d0-11e6-84ef-8c5c04aa7613.png">

**Node.js version**:
v7.4.0
**npm version**:
4.0.5
**Strapi version**:
1.5.4
**Operating system**:
macOS Sierra
10.12.2

Thanks

**Comment by pierreburgy** [comment]
Hi @nanocreaator, Strapi v1.x supports only Node versions between 0.12 and 4. Please downgrade to Node v4 to use it.
Of course, Strapi v3 will support Node v7 and more.
