### ISSUE TITLE
ER_ACCESS_DENIED_ERROR to local mysql database after updating to v4.12.1

### ISSUE THREAD

**Issue by luboslives** [strapi/strapi#17555]
### Required System information

- Node.js version: 18.14.0
- NPM version: 9.8.1
- Strapi version: 4.12.1
- Database: "mariadb from 11.0.2-MariaDB, client 15.2 for osx10.14 (x86_64) using EditLine wrapper"
- Operating system: macOS Mojave 10.14.6
- Is your project Javascript or Typescript: JS

### Describe the bug

Looking to see if anyone else has this problem – I upgraded to Strapi 4.12.1, `npm install` had no problems, `npm run build` had no problems, but `npm run develop` will run into this error:

```
> strapi develop

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'user'@'localhost' (using password: YES)
    at Sequence._packetToError (/projectdir/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/projectdir/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/projectdir/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/projectdir/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/projectdir/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/projectdir/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/projectdir/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/projectdir/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/projectdir/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/projectdir/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/projectdir/node_modules/mysql/lib/Connection.js:116:18)
    at /projectdir/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/projectdir/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/projectdir/node_modules/knex/lib/client.js:262:39) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'user'@'localhost' (using password: YES)",
  sqlState: '28000',
  fatal: true
}
```

### Additional context

Now, I had a look at `.env` and everything looks correct. I thought maybe the problem was that the local SQL server is running in a socket – so I tried to add a `socketPath` to `config/database.js`, as suggested in this old thread: https://github.com/strapi/strapi/issues/1714 but the error persists.

As an aside, there is nothing in the docs about connecting to a database using a socket, only the port. Now I don't know why my local SQL db would have switched to a socket on its own – I'm assuming it was running like that all along and Strapi did not have a problem connecting to it until the update to v4.12.1

MariaDB had to be _built_ as there was no prebuild available for my system in `homebrew` - maybe that plays a factor here, if nothing else can be found.

**Comment by plcdnl** [comment]
Same error

**Comment by Shooteger** [comment]
Same error here.

And with or PostgreSQL Instance we get the same error. Update v4.12.1 breaks everything regarding fetching.

**Comment by atipezda** [comment]
same error

**Comment by kenzone** [comment]
same error

**Comment by innerdvations** [comment]
Could you try using the 'mysql2' client and see if it changes anything?

`yarn add 'mysql2'` and then change your database `client` value from `'mysql'` to `'mysql2'`

**Comment by derrickmehaffy** [comment]
> Could you try using the 'mysql2' client and see if it changes anything?
> 
> `npm install mysql2` (or `yarn add mysql2`) and then change your database `client` value from `'mysql'` to `'mysql2'`

I was testing 4.12.1 last week for some tickets and couldn't reproduce this (both mysql 5 and 8 using both mysql and mysql2) and MariaDB. My gut tells me this is a user config issue but we need more examples of their configs and which mysql/mariadb versions they are using to validate.

**Comment by luboslives** [comment]
> Could you try using the 'mysql2' client and see if it changes anything?
> 
> `npm install mysql2` (or `yarn add mysql2`) and then change your database `client` value from `'mysql'` to `'mysql2'`

I tried `mysql2` and we have the `ER_ACCESS_DENIED_ERROR` again, but this time the print out is a bit shorter. Maybe you can compare the two:

```
Error: Access denied for user 'user'@'localhost' (using password: YES)
    at Packet.asError (/projectdir/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/projectdir/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/projectdir/node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (/projectdir/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/projectdir/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/projectdir/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  sqlMessage: "Access denied for user 'user'@'localhost' (using password: YES)",
  sql: undefined
}
```
Steps to reproduce:

1) `npm install mysql2`
2) update `DATABASE_CLIENT=mysql2` inside `.env`
3) update `package.json` to update the versions of strapi from 4.12.0 to 4.12.1, and removed `mysql` dependency
4) `npm install`
```
added 3 packages, removed 32 packages, changed 24 packages, and audited 1319 packages in 52s
```
5) `npm run build`
```
Building your admin UI with development configuration...

✔ Webpack
  Compiled successfully in 18.80s

Admin UI built successfully
```
6) `npm run develop` and we get the error.

**Comment by luboslives** [comment]
> My gut tells me this is a user config issue but we need more examples of their configs and which mysql/mariadb versions they are using to validate.

Strapi runs fine on version 4.12.0. The only steps I personally took are the update steps listed in the first post.

@plcdnl @Shooteger @atipezda @kenzone please provide your environment details so the support team can try to reproduce the error.

**Comment by Shooteger** [comment]
I am using a PostgreSQL Database on the production server, I get the ERR_CONNECTION_REFUSED Error too. Everything runs fine on v4.12.0, when I upgraded to v4.12.1, I got the same error, as listed here in the ticket. Here more specific details and logs of my setup, locally I get the same errors:

We started with early Version 4 of Strapi and upgraded until now without ever having problems. Dependencies in Strapi project:


```javascript
"@_sh/strapi-plugin-ckeditor": "1.1.3", 
"@strapi/plugin-i18n": "4.12.1",
"@strapi/plugin-users-permissions": "4.12.1",
"@strapi/provider-upload-cloudinary": "4.12.1",
"@strapi/strapi": "4.12.1",
"better-sqlite3": "7.6.2",
"pg": "8.11.1",
"pg-connection-string": "2.6.1",
"strapi-plugin-populate-deep": "3.0.0"
``` 

When we installed the currently newset version v4.12.1 (in the frontend we did not change anything). The frontend get this error message in the browser command line:

```javascript
1.
Error in fetch(): FetchError: request to http://localhost:1337/api/the-navs?filters[site_name][$eq]=index&populate[0]=%2A&populate[1]=nav&populate[2]=nav.sub_links&populate[3]=logo&locale= failed, reason: connect ECONNREFUSED ::1:1337
    at ClientRequest.<anonymous> (/Users/mauriceputz/Documents/mp_sys_llc/projekte.nosync/haiberg-gmbh/haiberg-frontend-1/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
 
2.
GET http://localhost:1337/api/the-navs?filters[site_name][$eq]=index&populate[0]=%2A&populate[1]=nav&populate[2]=nav.sub_links&populate[3]=logo&locale=de 500 (Internal Server Error)

3.
Error in fetch(): HTTPError
    at _callee$ (index.js:316:1)
    at tryCatch (runtime.js:64:1)
    at Generator.invoke (runtime.js:299:1)
    at Generator.eval [as next] (runtime.js:124:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
``` 

This following error I get in the Command Console where I ran my Nuxt Frontend:

```javascript
Error in fetch(): request to http://localhost:1337/api/the-navs?filters[site_name][$eq]=index&populate[0]=%2A&populate[1]=nav&populate[2]=nav.sub_links&populate[3]=logo&locale= failed, reason: connect ECONNREFUSED ::1:1337
``` 

Now I get following Error in the Command Console where I have my Strapi Instance running with yarn develop and my Frontend tries to connect / fetch:

```javascript
[2023-08-07 19:22:06.832] error: Invalid populate parameter. Expected a string, an array of strings, a populate object
Error: Invalid populate parameter. Expected a string, an array of strings, a populate object

```

**Comment by brantwills** [comment]
Ran into this myself, on a whim I wrapped my .env db passwod variable in single ticks and things started to work 
Maybe something to check.. meh.. 

---

Deets:
- I ended updating to 4.12.5
- I am using MariaDB and PostgreSQL
- Was seeing the `ER_ACCESS_DENIED_ERROR` error message
- Still feeling things out but seems ok so far

```diff
# .env

DATABASE_NAME=foo
DATABASE_USERNAME=bar
+ DATABASE_PASSWORD='example-i-had-special-chars-like-#'
- DATABASE_PASSWORD=example-i-had-special-chars-like-#
DATABASE_SSL=true
```

**Comment by luboslives** [comment]
Thanks @brantwills, that appears to have done the trick.

I ran the update today from 4.12.0 to 4.12.1, tried it without the quotes around the password (crash) and then with the quotes, and now it starts up as usual.

FYI, I updated to 4.12.5 and tested the unquoted password again, and the error persists in the latest version. But it works with the quoted password.

**Strapi team**, it appears that you need to enforce quotes around `DATABASE_PASSWORD` inside `.env`

**Comment by ntarandek** [comment]
@luboslives Maybe enforcing is a bit too much since this seems to affect (if I understood correctly) only cases where special characters are used in password (not to mention that this seems to be a ENV value handling issue not Strapi issue).

So, maybe a very clearly documented case about special characters usage would be more advisable than possibly braking a lot more installations that do not even use any special characters.

**Comment by derrickmehaffy** [comment]
> @luboslives Maybe enforcing is a bit too much since this seems to affect (if I understood correctly) only cases where special characters are used in password (not to mention that this seems to be a ENV value handling issue not Strapi issue).
> 
> So, maybe a very clearly documented case about special characters usage would be more advisable than possibly braking a lot more installations that do not even use any special characters.

That is a very good point, we should probably just update our docs since the dotenv package isn't really related to us (which is what we use to parse the .env files).

I'll transfer this issue over to our docs repo but if anyone wants to submit a PR to the docs that would be great.
