### ISSUE TITLE
@strapi/provider-upload-aws-s3 override endpoint fail

### ISSUE THREAD

**Issue by aperez900907** [strapi/strapi#17573]
### Required System information

- Node.js version: 16.20.1
- NPM version: 8.19.4
- Strapi version: 4.12.0-beta.1
- Database: sqlite
- Operating system: docker 24.0.2 on windows 11 wsl backend
- Is your project Javascript or Typescript: js

### Describe the bug

The plugin @strapi/provider-upload-aws-s3 provides the option to override with `endpoint` to connect to locally deploy minio object storage, I get an error ENETUNREACH

```
error: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
Error: connect ENETUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2023-08-03 17:31:59.166] error: MultipartParser.end(): stream ended unexpectedly: state = PART_DATA
Error: MultipartParser.end(): stream ended unexpectedly: state = PART_DATA
    at MultipartParser.end (C:\Users\apere\foodadvisor\api\node_modules\formidable\lib\multipart_parser.js:326:12)
    at IncomingMessage.<anonymous> (C:\Users\apere\foodadvisor\api\node_modules\formidable\lib\incoming_form.js:132:30)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

The connections still going to an AWS S3 service IP address pool and stop strapi to run in dev mode

### Steps to reproduce the behavior

1. Setup the provider and point to a locally minio s3 and use the `endpoint` option to override the default hostname of was s3 service.

### Expected behavior

Connect to a locally deploy minio instance with the endpoint value set to this instance IP:PORT prefer on docker environments. 

### Code snippets
```
upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        s3Options:{
          accessKeyId: env('S3_ACCESS_KEY_ID'),
          secretAccessKey: env('S3_ACCESS_SECRET'),
          endpoint: env('S3_ENDPOINT'),
          region: 'us-west-rack2', // set as default on the minio config
          //s3ForcePathStyle: true,
          //signatureVersion: 'v4',
          params: {
          //ACL: env('AWS_ACL', 'public-read'),
          //signedUrlExpires: env('AWS_SIGNED_URL_EXPIRES', 15 * 60),
            Bucket: env('S3_BUCKET'),
          },
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
```

**Comment by aperez900907** [comment]
Thanks, with latest version works!
