### ISSUE TITLE
SqliteError: create table when going through 'create your first content type'

### ISSUE THREAD

**Issue by PaulSinghDev** [strapi/strapi#17657]
### Required System information

- Node.js version: v18.13.0
- NPM version: 8.19.3
- Yarn version: 1.22.19
- Strapi version: 4.12.4
- Database: SQLLite (8.5.0)
- Operating system: macOS (13.0.1 (22A400)) -- M1 Max processor (if that helps)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Cannot create any content types as going through the builder to create the first one corrupts the database, causes it to crash then prevents it from ever loading again.

### Steps to reproduce the behaviour

1. `npx create-strapi-app@latest my-project --quickstart --typescript` or `yarn create strapi-app my-project --typescript --quickstart `
2. Fill in signup details
3. Click create first content type
4. Create a content type -- mine had a UID and a few other fields first then just a UID. I called it 'Menu' first, then just 'Test' to check if Menu was a reserved word (unlikely but hey)

### Expected behavior

The content type to be created and for me to move on my merry old way.

### Error output (actual path replaced with REDACTED_PATH)
```
SqliteError: create table `tests` (`id` integer not null primary key autoincrement, `id` varchar(255) null, `created_at` datetime null, `updated_at` datetime null, `published_at` datetime null, `created_by_id` integer null, `updated_by_id` integer null, constraint `tests_created_by_id_fk` foreign key(`created_by_id`) references `admin_users`(`id`) on delete SET NULL, constraint `tests_updated_by_id_fk` foreign key(`updated_by_id`) references `admin_users`(`id`) on delete SET NULL) - duplicate column name: id
    at Database.prepare (REDACTED_PATH/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (REDACTED_PATH/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:34)
    at executeQuery (REDACTED_PATH/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (REDACTED_PATH/node_modules/knex/lib/client.js:154:12)
    at REDACTED_PATH/node_modules/knex/lib/execution/transaction.js:371:24
    at new Promise (<anonymous>)
    at trxClient.query (REDACTED_PATH/node_modules/knex/lib/execution/transaction.js:366:12)
    at Runner.query (REDACTED_PATH/node_modules/knex/lib/execution/runner.js:141:36)
    at Runner.queryArray (REDACTED_PATH/node_modules/knex/lib/execution/runner.js:235:21)
    at Runner.queryArray (REDACTED_PATH/node_modules/knex/lib/execution/runner.js:287:31) {
  code: 'SQLITE_ERROR'
}
```

Any help very much appreciated, happy to give more information just let me know what :)

**Comment by PaulSinghDev** [comment]
Re-reading the error I can see it is because I created a field called _id_ which is reserved. Might be an idea to prevent this from being possible.
