### ISSUE TITLE
TypeError: C is not a function

### ISSUE THREAD

**Issue by Audit-a-la-Carte** [strapi/strapi#17759]
When I add content to a collection, using the Strapi interface everything works fine. Once I navigate to the collection overview, I get an error in the console like:

TypeError: C is not a function
    at ks (main.ee4542dd.js:1158:22917)
    at $o (main.ee4542dd.js:1158:24698)
    at Hc (main.ee4542dd.js:1158:42699)
    at mf (main.ee4542dd.js:1158:42229)
    at mc (main.ee4542dd.js:1158:41260)
    at ef (main.ee4542dd.js:1158:37761)
    at fl (main.ee4542dd.js:1156:3278)
    at main.ee4542dd.js:1158:35126

and the screen shows the standard error screen. Has anyone also noticed this, or is it something I can try to resolve? If not I might be better off creating an issue on Github.

I am using the latest version by the way, but have it (at least) since 4.12.1 

- Node.js version: v18.17.0
- NPM version: 9.6.7
- Strapi version: 4.12.5
- Database: Cloud database DigitalOcean
- Operating system: Docker on [Ubuntu](node:18-alpine)
- Is your project Javascript or Typescript: TS

### Describe the bug

I am using Strapi to manage article (blog) content. I add an entry, with a title, body et all and then save it. It doesn't return to the list overview, so I click on the left on the collection name and it results in the error shared above (console and on screen).

### Screenshots

[Screenshot here](https://cdn.discordapp.com/attachments/1143536207658229771/1143536208161554513/CleanShot_2023-08-22_at_15.23.552x.png)

**Comment by Audit-a-la-Carte** [comment]
Done @derrickmehaffy, sorry for the inconvenience!

**Comment by Audit-a-la-Carte** [comment]
I just noticed a new version that was published 3 hours ago and this seem to have resolved the issue!
