### ISSUE TITLE
Errors when navigating through the sidebar in the content manager

### ISSUE THREAD

**Issue by AdrianFahrbach** [strapi/strapi#17838]
### Required System information

- Strapi version: 4.12.5

### Describe the bug

When navigating through the panel we regularly get an error that leads to "Woops! Something went wrong. Please, try again.".
It seems like this is happening when clicking an item in the sidebar. Some collections immediately return the error and some only when clicking the same navigation entry twice.  

This can be seen in the console.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'plugins')
```

Here is a video. I also attached a screenshot with the line the throws the error according to Chrome Dev-Tools.

https://github.com/strapi/strapi/assets/45072099/ad33f692-71d8-470b-b163-8f3af65c510b

### Steps to reproduce the behavior

1. Open the content manager
2. Click on a sidebar entry multiple times

### Expected behavior

The navigation should be working without errors.

### Screenshots

![screenshot 2023-08-28 at 16 55 00@2x](https://github.com/strapi/strapi/assets/45072099/962136c5-ae91-43b0-acd0-9b6e1b260d7c)

**Comment by t-fritsch** [comment]
I've got the same problem when I try to create a `LinkButton` to an internal page : 
```ts
import { LinkButton } from '@strapi/design-system/v2';
import { Link as RRLink } from 'react-router-dom';

// ...
<LinkButton
    as={RRLink}
    to={`/content-manager/collectionType/api::mymodel.mymodel`}
>
    My internal link
</LinkButton>
```

Passing no querystring to any content-type's list view, results in this `cannot read properties of undefined (reading plugins)` error. 

Adding an arbitrary `?page=1` removes the error, but then the view's default settings (_sort column, sort order, etc._) are not applied... 😕 
Are there any workaround ?

**Comment by joshuaellis** [comment]
I don't think there's a workaround, but that's really helpful to know because that's not a hard fix, we simply pass some defaults as the query 😊

**Comment by t-fritsch** [comment]
OK so I may be crazy : I tried getting the contentTypeLinks from the redux store, but reverted my code (since the value is empty until you do visit any content-type page), so I'm getting back to the code above and the `cannot read property...` error has gone... 😳 need to do some more testing, since this doesn't make any sense 😂

**Comment by t-fritsch** [comment]
OK the bug is still there, at least with one reproduction scenario : given a plugin page with 2 internal links : 
- 1 Link to the list view (table)
- 1 Link to the edit view (create entity form)
```tsx
import { LinkButton } from '@strapi/design-system/v2';
import { Link as RRLink } from 'react-router-dom';
// ...
<LinkButton as={RRLink} to={`/content-manager/collectionType/api::mymodel.mymodel`}>
    List view
</LinkButton>
<LinkButton as={RRLink} to={`/content-manager/collectionType/api::mymodel.mymodel/create`}>
    Create entity view
</LinkButton>
```

1. navigate to your plugin custom page, click on the create entity link
2. go back to the plugin page (either from the strapi "back" link on the top of the table, with browser back button, or by clicking on your plugin icon in the main menu)
3. click on the List view link

From there : 
- the list view loads
- strapi happens to the current URL all the default query parameters configured by the administrator in the view (sort field + order), redirecting to something like `/content-manager/collectionType/api::mymodel.mymodel?page=1&pageSize=10&sort=updatedAt:DESC`
- then the error shows : \
    ![image](https://github.com/strapi/strapi/assets/10920280/7716b908-ce66-42e2-bc63-a099e05db7cf)

Note that due to the recent move to a dist-only npm package, this kind of bug is a pain to debug due to the lack of source files and only compiled chunks (like the `vendors-node_modules_strapi_admin_dist__chunks_index-81509193_mjs.js` file from where this error is originating...)

**Comment by HelloDimension** [comment]
i love how there are ZERO solutions or feed back from strapi and so many people are having this same issue. i should have never used this now im stuck or need to restart with a new cms strapi caused me way too much headaches. they said it was production-ready. it is definitely NOT

**Comment by 5hraddha** [comment]
@derrickmehaffy Any updates on this issue? I just pushed a new change to the production strapi and everything works fine until I click on Content Manager and try to navigate to one of the content types.
```
main.9cc47718.js:5882 TypeError: Cannot destructure property 'params' of '(0 , ae.W5)(...)' as it is null.
    at at (main.9cc47718.js:4972:5366)
    at qa (main.9cc47718.js:5880:20865)
    at Jl (main.9cc47718.js:5882:46444)
    at es (main.9cc47718.js:5882:41968)
    at Ko (main.9cc47718.js:5882:41896)
    at go (main.9cc47718.js:5882:41746)
    at G0 (main.9cc47718.js:5882:37910)
    at hg (main.9cc47718.js:5882:36800)
    at L (main.9cc47718.js:5969:1615)
    at MessagePort.ae (main.9cc47718.js:5969:1986)
    ```

**Comment by derrickmehaffy** [comment]
Setting confirmed based on volume of reports

**Comment by 5hraddha** [comment]
Sure, @derrickmehaffy. Thanks for confirming the issue though.

**Comment by 5hraddha** [comment]
Any updates on the remediation of this issue?

**Comment by derrickmehaffy** [comment]
We don't have any workarounds or a timeline at this time as most of the team is focused on Strapi 5 at the moment
