### ISSUE TITLE
Deleting your own admin user from SSO yields a 500 error

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#17854]
### Required System information

```
Environment: development
OS: linux-x64
Strapi Version: 4.12.7
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.12.1 linux x64
Edition: Enterprise
Database: sqlite
```
- Is your project Javascript or Typescript: JAvascript

### Describe the bug

When a user signs in via SSO (during testing used GitHub) and deletes themselves they do not get redirected to the login page but instead an internal server error is thrown:

```
[2023-08-29 14:54:12.543] http: POST /admin/users/batch-delete (70 ms) 200
/home/dmehaffy/Development/testingBugs/node_modules/@strapi/utils/dist/validators.js:86
    throw new errors_1.YupValidationError(error, errorMessage);
          ^

YupValidationError: 1 relation(s) of type admin::user associated with this entity do not exist
    at handleYupError (/home/dmehaffy/Development/testingBugs/node_modules/@strapi/utils/dist/validators.js:86:11)
    at /home/dmehaffy/Development/testingBugs/node_modules/@strapi/utils/dist/validators.js:98:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.create (/home/dmehaffy/Development/testingBugs/node_modules/@strapi/strapi/lib/services/entity-service/index.js:156:23)
    at async Object.<anonymous> (/home/dmehaffy/Development/testingBugs/node_modules/@strapi/strapi/lib/services/entity-service/index.js:415:20)
    at async Object.saveEvent (/home/dmehaffy/Development/testingBugs/node_modules/@strapi/provider-audit-logs-local/dist/index.js:18:17) {
  details: {
    errors: [
      {
        path: [],
        message: '1 relation(s) of type admin::user associated with this entity do not exist',
        name: 'ValidationError'
      }
    ]
  }
}
```

This leads to a hard crash of the server requiring a restart to bring the service back online

### Steps to reproduce the behavior

1. Setup Strapi Project with SSO (doesn't matter which one)
2. Sign in Via SSO
3. Try to delete your own user account from within settings

### Expected behavior

User should be deleted and redirected back to login page, as is what happens with non SSO based users

### Screenshots

![image](https://github.com/strapi/strapi/assets/8593673/310b5cd7-e070-49a0-9484-390914679412)
![image](https://github.com/strapi/strapi/assets/8593673/ad0d380b-38fa-4a46-9996-73ffd46b4a40)
![image](https://github.com/strapi/strapi/assets/8593673/6dc0ba9a-eb94-49a2-b98e-cac3fa6b1a76)
![image](https://github.com/strapi/strapi/assets/8593673/21970daf-5ab3-415d-938b-c9882dba97b2)

### Code snippets

N/A

### Additional context

Internal TID4568

**Comment by Eventyret** [comment]
To add some info to this.
If this is SSO, it's the provider that should control if a user should be able to be removed or not.
Also, mostly in any database-related thing, you should not be able to delete yourself while a session is active.
As you delete the user and the session, it will crash, and you won't get thrown out. Since you don't get thrown out you also will be stuck in an infinite 500 crash, most likely.

**Comment by derrickmehaffy** [comment]
Related to TID 1394

**Comment by hanpaine** [comment]
@derrickmehaffy if Simen's comment is correct, this isn't something we will make any changes to in Strapi AFAIAA? @maccomaccomaccomacco any views?

**Comment by derrickmehaffy** [comment]
It's not correct in this case, we just need to disable the ability to delete yourself. If that user should be deleted, another super admin should have to do it so that we always have a super admin in the system.
