### ISSUE TITLE
React build fails after Strapi upgrade from 4.12.7 to 4.13.1

### ISSUE THREAD

**Issue by CAJazzer** [strapi/strapi#17874]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.8.0
- Strapi version: 4.13.1
- Database: Posgresql V15
- Operating system: macOS Ventura 13.5.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Note: I have had the same problem on 2 different installations.

After project upgrade via npm install, I ran npm run build.  The following error occurs:

```

● Webpack █████████████████████████ building (10%) 0/1 entries 1/1 dependencies 0/1 modules 1 active
 esbuild-loader › .cache/admin/src/index.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/myuser/nodejs/ouidecide/.cache/admin/src'
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/myuser/nodejs/ouidecide/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/myuser/nodejs/ouidecide/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/Users/myuser/nodejs/ouidecide/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/myuser/nodejs/ouidecide/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/myuser/nodejs/ouidecide/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/myuser/nodejs/ouidecide/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/myuser/nodejs/ouidecide/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/myuser/nodejs/ouidecide/node_modules
        existing directory /Users/myuser/nodejs/ouidecide/node_modules/react-dom
          using description file: /Users/myuser/nodejs/ouidecide/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/myuser/nodejs/ouidecide/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client doesn't exist
              .js
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.js doesn't exist
              .jsx
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client doesn't exist
      /Users/myuser/nodejs/node_modules doesn't exist or is not a directory
      /Users/myuser/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/myuser/nodejs/ouidecide/.cache/admin/src'
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/myuser/nodejs/ouidecide/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/myuser/nodejs/ouidecide/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/myuser/nodejs/ouidecide/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/Users/myuser/nodejs/ouidecide/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/myuser/nodejs/ouidecide/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/myuser/nodejs/ouidecide/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/myuser/nodejs/ouidecide/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/myuser/nodejs/ouidecide/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/myuser/nodejs/ouidecide/node_modules
        existing directory /Users/myuser/nodejs/ouidecide/node_modules/react-dom
          using description file: /Users/myuser/nodejs/ouidecide/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/myuser/nodejs/ouidecide/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client doesn't exist
              .js
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.js doesn't exist
              .jsx
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /Users/myuser/nodejs/ouidecide/node_modules/react-dom/client doesn't exist
      /Users/myuser/nodejs/node_modules doesn't exist or is not a directory
      /Users/myuser/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

**Comment by joshuaellis** [comment]
please see this comment: https://github.com/strapi/strapi/issues/17872#issuecomment-1699939091

**Comment by ruslanyar** [comment]
Deleting the .cache folder, in addition to the node_modules folder, worked for me.

**Comment by francescob** [comment]
for me none of these worked, i've deleted yarn.lock, .cache and node_modules folders. Only working solution was 
`yarn add react-dom`

**Comment by oxuk85** [comment]
I had to bump up my version of react react-dom react-is and react-router-dom to @latest and that fixed it for me

**Comment by cooperwfloyd** [comment]
Tried clearing out cache, build, node_modules, package-lock.json and no luck with that approach — **necessary fix for me here was upgrading from `react` and `react-dom` 17 to 18 (latest)**. Is there a requirement now for React 18 to be used in Strapi projects?

**Comment by BabyDino** [comment]
We are also running into this issue. Clearing everything and deleting cache, build and node-modules does nothing. Possible plugin related?

**Comment by BabyDino** [comment]
Anyone using https://github.com/VirtusLab-Open-Source/strapi-plugin-comments in their project?

When I force install `react-dom` I get the following warnings:

```
$ npm i --force
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-dom@18.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@">=16.8.0" from @emotion/react@11.11.1
npm WARN   node_modules/@emotion/react
npm WARN     @emotion/react@"^11.8.1" from react-select@5.7.0
npm WARN     node_modules/react-select
npm WARN   81 more (@emotion/use-insertion-effect-with-fallbacks, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^18.2.0" from react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   40 more (@floating-ui/react-dom, @monaco-editor/react, ...)
npm WARN 
npm WARN Conflicting peer dependency: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from react-dom@18.2.0
npm WARN   node_modules/react-dom
npm WARN     react-dom@"^18.2.0" from the root project
npm WARN     40 more (@floating-ui/react-dom, @monaco-editor/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: strapi-plugin-comments@2.2.12
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   40 more (@floating-ui/react-dom, @monaco-editor/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^17.0.2" from strapi-plugin-comments@2.2.12
npm WARN node_modules/strapi-plugin-comments
npm WARN   strapi-plugin-comments@"^2.2.12" from the root project
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^17.0.2" from strapi-plugin-comments@2.2.12
npm WARN   node_modules/strapi-plugin-comments
npm WARN     strapi-plugin-comments@"^2.2.12" from the root project
```

**Comment by spietrek** [comment]
I was running into the same issue. Tried deleting node_modules, yarn.lock, and .cache. Ended up having to downgrade to 4.12.7.

  "dependencies": {
    "@strapi/plugin-i18n": "4.12.7",
    "@strapi/plugin-users-permissions": "4.12.7",
    "@strapi/strapi": "4.12.7",
    "better-sqlite3": "8.5.2",
    "strapi-plugin-menus": "^1.4.3",
    "strapi-plugin-publisher": "^1.4.0"
  },

**Comment by CAJazzer** [comment]
Thanks @francescob.  ``npm install react-dom`` fixed my issue.

**Comment by ainsleyclark** [comment]
Same issue here. Is this a versioning issue?

**Comment by jp06** [comment]
I encountered this issue while trying to update the Strapi dependencies on one of our projects. What I did is delete `.cache`, `node_modules`, and `package-lock.json` and then `npm i` again to get through.

**Comment by PoliPG** [comment]
I solve this problem installing all of this modules, I think the problem in my case is using pnpm which is not compatible with the strapi build script.

`   "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
`

Strapi says:
```

 [INFO] The Strapi admin needs to install the following dependencies:
backend-blog:build:    - react@^18.0.0
backend-blog:build:   - react-dom@^18.0.0
backend-blog:build:   - react-router-dom@^5.2.0
backend-blog:build:   - styled-components@^5.2.1
backend-blog:build: ? Would you like to install these dependencies now? These are not required but 
backend-blog:build: are recommended, from V5 these will be required. (Y/n)    
```
