### ISSUE TITLE
ModuleNotFound on npm run build in 4.13.1

### ISSUE THREAD

**Issue by kordax** [strapi/strapi#17899]
### Required System information

- Node.js version:
- v17.6.0
- NPM version:
- 8.5.1
- Strapi version:
- 4.13.1
- Database:
- MySQL
- Operating system:
- Linux
- Is your project Javascript or Typescript:
- js

### Describe the bug
package.js:
`{
  "name": "cryp-advise-landing-admin",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@bn-digital/strapi-plugin-field-uuid": "^1.2.12",
    "@strapi/plugin-i18n": "4.13.1",
    "@strapi/plugin-users-permissions": "4.13.1",
    "@strapi/strapi": "4.13.1",
    "mysql": "2.18.1"
  },
  "author": {
    "name": "Cryp Advise"
  },
  "strapi": {
    "uuid": "4437f7dd-f2a1-42fa-9a31-e527c8c2f048"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  }
}
`

`npm run build

> cryp-advise-landing-admin@0.1.0 build
> strapi build

Starting the compilation for TypeScript files in /var/www/mywebsite.com
Building your admin UI with development configuration...

● Webpack █████████████████████████ building (10%) 0/1 entries 73/82 dependencies 4/72 modules 62 active 
 esbuild-loader › .cache/admin/src/pages/App/index.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/var/www/mywebsite.com/.cache/admin/src'
    at /var/www/mywebsite.com/node_modules/webpack/lib/Compilation.js:2022:28
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/var/www/mywebsite.com/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/var/www/mywebsite.com/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/var/www/mywebsite.com/.cache/admin/src'
  Parsed request is a module
  using description file: /var/www/mywebsite.com/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /var/www/mywebsite.com/.cache/admin/src/node_modules doesn't exist or is not a directory
      /var/www/mywebsite.com/.cache/admin/node_modules doesn't exist or is not a directory
      /var/www/mywebsite.com/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /var/www/mywebsite.com/node_modules
        existing directory /var/www/mywebsite.com/node_modules/react-dom
          using description file: /var/www/mywebsite.com/node_modules/react-dom/package.json (relative path: .)
            using description file: /var/www/mywebsite.com/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /var/www/mywebsite.com/node_modules/react-dom/client doesn't exist
              .js
                /var/www/mywebsite.com/node_modules/react-dom/client.js doesn't exist
              .jsx
                /var/www/mywebsite.com/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /var/www/mywebsite.com/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /var/www/mywebsite.com/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /var/www/mywebsite.com/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /var/www/mywebsite.com/node_modules/react-dom/client doesn't exist
      /var/www/node_modules doesn't exist or is not a directory
      /var/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/var/www/mywebsite.com/.cache/admin/src'
    at /var/www/mywebsite.com/node_modules/webpack/lib/Compilation.js:2022:28
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/var/www/mywebsite.com/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/var/www/mywebsite.com/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /var/www/mywebsite.com/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/var/www/mywebsite.com/.cache/admin/src'
  Parsed request is a module
  using description file: /var/www/mywebsite.com/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /var/www/mywebsite.com/.cache/admin/src/node_modules doesn't exist or is not a directory
      /var/www/mywebsite.com/.cache/admin/node_modules doesn't exist or is not a directory
      /var/www/mywebsite.com/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /var/www/mywebsite.com/node_modules
        existing directory /var/www/mywebsite.com/node_modules/react-dom
          using description file: /var/www/mywebsite.com/node_modules/react-dom/package.json (relative path: .)
            using description file: /var/www/mywebsite.com/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /var/www/mywebsite.com/node_modules/react-dom/client doesn't exist
              .js
                /var/www/mywebsite.com/node_modules/react-dom/client.js doesn't exist
              .jsx
                /var/www/mywebsite.com/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /var/www/mywebsite.com/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /var/www/mywebsite.com/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /var/www/mywebsite.com/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /var/www/mywebsite.com/node_modules/react-dom/client doesn't exist
      /var/www/node_modules doesn't exist or is not a directory
      /var/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory`

1. npm install
2. npm run build
3. See error

**Comment by Antvirf** [comment]
Related: https://github.com/strapi/strapi/issues/17874

`npm install react-dom` seems to fix
