### ISSUE TITLE
Error handling: Throwing an error in a model lifecycle

### ISSUE THREAD

**Issue by yasirhaleem** [strapi/strapi#18041]
### Required System information

- Node.js version: 18.16.0
- NPM version: yarn/1.22.17 npm/? node/v18.16.0 darwin x64
- Strapi version: 4.11.5
- Database: mysql
- Operating system: darwin-x64
- Is your project Javascript or Typescript: javascript

### Describe the bug

The ApplicationError class is a generic error class for application errors and is generally recommended as the default error class. This class is specifically designed to throw proper error messages that the admin panel can read and show to the user. It accepts the following parameters:

**No Error message is shown to the user**

### Steps to reproduce the behavior

1. Install Strapi 4.11.5 with mysql
2. create content type
3. add lifecycles.js under contenttype

code below from the doc
```
const { errors } = require("@strapi/utils");
const { ApplicationError } = errors;
module.exports = {
  beforeCreate(event) {
    let okay = false;

    // Throwing an error will prevent the entity from being created
    if (!okay) {
      throw new ApplicationError("Something went wrong", { foo: "bar" });
    }
  },
};
```

### Expected behavior

**A custom error message for the admin user** instead this message is being shown 
<img width="892" alt="Screen Shot 2023-09-12 at 6 34 01 PM" src="https://github.com/strapi/strapi/assets/989956/86157d65-3821-44a5-b407-0bdc71ce3ea5">

### Screenshots

<img width="457" alt="Screen Shot 2023-09-12 at 6 14 05 PM" src="https://github.com/strapi/strapi/assets/989956/0128aab9-5b89-4744-a2b4-485930c7f3f7">

### Code snippets

```
const { errors } = require("@strapi/utils");
const { ApplicationError } = errors;
module.exports = {
  beforeCreate(event) {
    let okay = false;

    // Throwing an error will prevent the entity from being created
    if (!okay) {
      throw new ApplicationError("Something went wrong", { foo: "bar" });
    }
  },
};
```

**Comment by Boegie19** [comment]
This issue seems not to be present in the latest version of strapi.

**Comment by 00sapo** [comment]
@Boegie19 can you check if this can be reproduced now?

**Comment by lajeunadmin** [comment]
I am also seeing no custom notification with a ForbiddenError.
![image](https://github.com/strapi/strapi/assets/131491807/0cc858ed-f0f9-45ba-80cc-ca2c6463f3de)
![image](https://github.com/strapi/strapi/assets/131491807/7e8d0a07-2162-46dd-a582-7d1e5bafe6fb)

**Comment by Boegie19** [comment]
@lajeunadmin Try trowwing an application error.

**Comment by lajeunadmin** [comment]
No, sadly, same problem and generic message on the frontend. Here's my logs (email is meant to model a 'sent' newsletter email, I want to disable all further sending on a 'sent' email).

```
[2024-03-15 10:52:03.692] error: Editing sent emails is not allowed, as they are already sent.
ApplicationError: Editing sent emails is not allowed, as they are already sent.
    at Object.beforeUpdate (/home/maxine/Documents/redstack/backend/dist/src/api/email/content-types/email/lifecycles.js:12:15)
    at modelsLifecyclesSubscriber (/home/maxine/Documents/redstack/backend/node_modules/@strapi/database/dist/index.js:5862:43)
    at Object.run (/home/maxine/Documents/redstack/backend/node_modules/@strapi/database/dist/index.js:5947:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.update (/home/maxine/Documents/redstack/backend/node_modules/@strapi/database/dist/index.js:5070:22)
    at async Object.update (/home/maxine/Documents/redstack/backend/node_modules/@strapi/strapi/dist/services/entity-service/index.js:170:18)
    at async Object.<anonymous> (/home/maxine/Documents/redstack/backend/node_modules/@strapi/strapi/dist/services/entity-service/index.js:309:18)
    at async Object.update (/home/maxine/Documents/redstack/backend/node_modules/@strapi/plugin-content-manager/dist/server/index.js:2569:27)
    at async Object.update (/home/maxine/Documents/redstack/backend/node_modules/@strapi/plugin-content-manager/dist/server/index.js:963:27)
    at async returnBodyMiddleware (/home/maxine/Documents/redstack/backend/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
[2024-03-15 10:52:03.694] http: PUT /content-manager/collection-types/api::email.email/1 (54 ms) 500
```

**Comment by lajeunadmin** [comment]
No luck, sadly. As well, only a generic 500 is returned from the API according to the logs, below the correctly raised error message and statement.

**Comment by Boegie19** [comment]
@lajeunadmin just to confirm what strapi version are you on?

**Comment by 00sapo** [comment]
Also, since this problem seems to recurrently appear in various versions and is hardly reproducible by the developers (apparently), it may be caused by some other factors that we are not controlling. For instance, I do have that problem in a docker container running Ubuntu 20.04 and node 18.18.0.

**Comment by lajeunadmin** [comment]
> @lajeunadmin just to confirm what strapi version are you on? since for me on 4.20.5 it just works fine

I am on the latest version as well.

**Comment by 00sapo** [comment]
Retried today with the latest release and still having the error. My package.json:

```
{
  "name": "laudare-strapi",
  "version": "0.1.0",
  "private": true,
  "description": "A Strapi application",
  "license": "MIT",
  "author": {
    "name": "A Strapi developer"
  },
  "scripts": {
    "build": "strapi build",
    "develop": "strapi develop",
    "start": "strapi start",
    "strapi": "strapi"
  },
  "dependencies": {
    "@babel/core": "^7.0.0-0",
    "@babel/runtime": "",
    "@codemirror/autocomplete": "",
    "@codemirror/fold": "",
    "@codemirror/language": "",
    "@codemirror/lint": "",
    "@codemirror/search": "",
    "@codemirror/state": "",
    "@codemirror/theme-one-dark": "",
    "@codemirror/view": "",
    "@lezer/common": "^1.0.0",
    "@strapi/plugin-cloud": "*",
    "@strapi/plugin-i18n": "*",
    "@strapi/plugin-users-permissions": "*",
    "@strapi/strapi": "*",
    "@strapi/utils": "*",
    "axios": "*",
    "bibtex-parse-js": "*",
    "codemirror": ">=6.0.0",
    "googleapis": "*",
    "mysql2": "*",
    "mysqldump": "*",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-is": "",
    "react-router-dom": "^5.2.0",
    "scheduler": "*",
    "strapi-plugin-import-export-entries": "*",
    "styled-components": "5.3.3",
    "webpack": ""
  },
  "engines": {
    "node": ">=16.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "strapi": {
    "uuid": "60d714b2-4724-4423-9116-52db46c6728d"
  }
}
```

**Comment by WDeenik** [comment]
Had this issue before and when updating Strapi it worked again. Now we're running into it again, but I seem to have managed to find what was causing it: we had a version difference between `@strapi/strapi` and `@strapi/utils`. This caused Strapi to use a different version of `@strapi/utils` internally than we were using in our lifecycles, which in turn made Strapi not recognize our `ApplicationError`s as such, treating it like any other generic error instead of nicely formatting it.

Solution: make sure the `@strapi/utils` packge you use in your lifecycles has the same version number as the `@strapi/strapi` package you're using.

**Comment by 00sapo** [comment]
I'm not sure why you people continuously state that this is not a bug and that it is not reproducible. It's easy: create an ubuntu docker, install node nad yarn and use the above `package.json`. 

@WDeenik your solution (i.e. adding `"@strapi/strapi": "4.22.1",  "@strapi/utils": "4.22.1"` simply doesn't work and is not a solution for this bug.

**Comment by Boegie19** [comment]
@00sapo since you use * (Matches any version) this means that if a plugin requires an older version of for example utils it will use that instead mind confirming in your package.lock file if 

    "@strapi/plugin-cloud": "*",
    "@strapi/plugin-i18n": "*",
    "@strapi/plugin-users-permissions": "*",
    "@strapi/strapi": "*",
    "@strapi/utils": "*",
    
    all have the same version in the lock?
    
    if there are version diffrences in your package.lock file that would cause this issue. 
    
    did not yet try to reproduce this. (Also to be clear I don't work for strapi)

**Comment by 00sapo** [comment]
> @00sapo since you use * (Matches any version) this means that if a plugin requires an older version of for example utils it will use that instead mind confirming in your package.lock file if
> 
> ```
> "@strapi/plugin-cloud": "*",
> "@strapi/plugin-i18n": "*",
> "@strapi/plugin-users-permissions": "*",
> "@strapi/strapi": "*",
> "@strapi/utils": "*",
> ```
> 
> all have the same version in the lock?
> 
> if there are version diffrences in your package.lock file that would cause issues since the packages all depend on being the same versions as echother a miss match would cause wired behavoir.
> 
> did not yet try to reproduce this. (Also to be clear I don't work for strapi)

All packages I installed are on the same strapi version (4.22.1) and the lock file confirms it to me.

**Comment by lajeunadmin** [comment]
I'm now no longer seeing anything but "Internal Server Error" anywhere, breaking all errors on the app

![image](https://github.com/strapi/strapi/assets/131491807/1ccb5e9b-334d-4e8c-be51-814ca7f9b293)

**Comment by up_the_irons** [comment]
I was also having this same problem.  I forced `@strapi/utils` to be the exact same version as `@strapi/strapi` and then when an `ApplicationError` was thrown, I saw it correctly in the front-end.

Here's my current relevant `package.json`:

```
  "dependencies": {
    "@strapi/plugin-cloud": "4.25.14",
    "@strapi/plugin-i18n": "4.25.14",
    "@strapi/plugin-users-permissions": "4.25.14",
    "@strapi/provider-email-nodemailer": "4.25.14",
    "@strapi/strapi": "4.25.14",
    "@strapi/utils": "4.25.14",
```

**Comment by cyprille** [comment]
I can confirm that the [WDeenik](https://github.com/WDeenik) solution is working by my side, thank you so much 🙏🏻
