### ISSUE TITLE
Cannot upload file :: `error: Undefined attribute level operator id`

### ISSUE THREAD

**Issue by bjornpijnacker** [strapi/strapi#18061]
### Required System information

Running in RKE Kubernetes
```
# npm run strapi report

> cms@0.1.0 strapi
> strapi report

Starting the compilation for TypeScript files in /app
Launched In: 446 ms
Environment: production
OS: linux-x64
Strapi Version: 4.13.5
Node/Yarn Version: npm/9.6.7 node/v18.17.1 linux x64 workspaces/false
Edition: Community
Database: postgres
```

### Steps to reproduce the behavior

1. Go to media library
2. Attempt to upload a file

### Expected behavior

The file is uploaded.

### Logs
```
[2023-09-13 18:05:38.201] error: Undefined attribute level operator id
Error: Undefined attribute level operator id
    at processAttributeWhere (/app/node_modules/@strapi/database/lib/query/helpers/where.js:45:13)
    at processWhere (/app/node_modules/@strapi/database/lib/query/helpers/where.js:141:36)
    at /app/node_modules/@strapi/database/lib/query/helpers/where.js:67:31
    at Array.map (<anonymous>)
    at Object.processWhere (/app/node_modules/@strapi/database/lib/query/helpers/where.js:67:18)
    at Object.processState (/app/node_modules/@strapi/database/lib/query/query-builder.js:317:29)
    at Object.getKnexQuery (/app/node_modules/@strapi/database/lib/query/query-builder.js:354:12)
    at Object.execute (/app/node_modules/@strapi/database/lib/query/query-builder.js:475:25)
    at Object.create (/app/node_modules/@strapi/database/lib/entity-manager/index.js:246:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.13.5 or v4.13.6

**Comment by bjornpijnacker** [comment]
Thanks for having a look. I could not reproduce it on a new project. Turns out, it was my own fault.

I recently migrated to a new database. Turns out I messed up the migration somewhat, and database constraints and sequences did not transfer. Therefore, the data got royally messed up.
