### ISSUE TITLE
@strapi/plugin-color-picker not working when upgrading to 4.13.6

### ISSUE THREAD

**Issue by jramstedt** [strapi/strapi#18070]
## Bug report

Color picker no longer works with strapi version 4.13.6

### Required System information

Environment: development
OS: win32-x64
Strapi Version: 4.13.6
Node/Yarn Version: yarn/1.22.19 npm/? node/v16.15.1 win32 x64
Edition: Community
Database: sqlite

### Describe the bug

After upgrading to 4.13.6 color picker is not showing up when adding custom fields.
Plugin is visible in plugins list.

If I try to edit collection type with color-picker (in component) I get:
```
index.js:33 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'default')
    at index.js:33:48
    at Array.forEach (<anonymous>)
    at m (index.js:32:12)
(anonymous) @ index.js:33
m @ index.js:32
await in m (async)
(anonymous) @ index.js:53
da @ react-dom.production.min.js:244
ac @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
L @ scheduler.production.min.js:13
ye @ scheduler.production.min.js:14
```

And if I try to edit component type:
```
react-dom.production.min.js:189 TypeError: Cannot destructure property 'icon' of 'At.get(...)' as it is undefined.
    at je (index.js:71:13)
    at Rs (react-dom.production.min.js:167:137)
    at Ye (react-dom.production.min.js:290:337)
    at tf (react-dom.production.min.js:280:389)
    at Af (react-dom.production.min.js:280:320)
    at jc (react-dom.production.min.js:280:180)
    at Ad (react-dom.production.min.js:271:88)
    at qd (react-dom.production.min.js:268:429)
    at L (scheduler.production.min.js:13:203)
    at MessagePort.ye (scheduler.production.min.js:14:128)
Kr @ react-dom.production.min.js:189
Pc.b.callback @ react-dom.production.min.js:189
Bl @ react-dom.production.min.js:144
Bc @ react-dom.production.min.js:262
yd @ react-dom.production.min.js:260
vd @ react-dom.production.min.js:259
Tf @ react-dom.production.min.js:283
sc @ react-dom.production.min.js:281
qd @ react-dom.production.min.js:269
L @ scheduler.production.min.js:13
ye @ scheduler.production.min.js:14
```

### Steps to reproduce the behavior

Try to add or edit types with color picker
Try to add or edit data with color picker

### Expected behavior

Color picker should be available when adding new fields.
Color picker should work when editing data.

### Additional context

Strapi 4.13.5 works fine.

**Comment by joshuaellis** [comment]
I've just made a new strapi project and added the color picker and didn't have any issues 🤔 did you rebuild your admin panel etc?

**Comment by jramstedt** [comment]
Yes I did.

.cache/admin/src/plugins.js doesn't have color picker in it:

```
import contentTypeBuilder from '@strapi/plugin-content-type-builder/strapi-admin';
import email from '@strapi/plugin-email/strapi-admin';
import upload from '@strapi/plugin-upload/strapi-admin';
import ckeditor from '@ckeditor/strapi-plugin-ckeditor/strapi-admin';
import i18N from '@strapi/plugin-i18n/strapi-admin';
import usersPermissions from '@strapi/plugin-users-permissions/strapi-admin';


const plugins = {
  'content-type-builder': contentTypeBuilder,
  'email': email,
  'upload': upload,
  'ckeditor': ckeditor,
  'i18n': i18N,
  'users-permissions': usersPermissions,
};

export default plugins;
```

**Comment by joshuaellis** [comment]
Have you tried to remove your cache folder and then rebuild? can you do `npm ls @strapi/plugin-color-picker` as well?

**Comment by jramstedt** [comment]
I went trough the plugin resolving code.
It fails in filterPluginsByAdminEntry with MODULE_NOT_FOUND

Then I checked the package:
https://www.npmjs.com/package/@strapi/plugin-color-picker/v/4.13.6?activeTab=code

It is missing strapi-admin.js

**Comment by jramstedt** [comment]
I just did a clean project:
```
yarn create strapi-app colorpickertest --quickstart --ts --no-run
yarn add @strapi/plugin-color-picker
```

And the picker is not working and it is not in .cache/admin/src/plugins.js either:
```

import contentTypeBuilder from '@strapi/plugin-content-type-builder/strapi-admin';
import email from '@strapi/plugin-email/strapi-admin';
import upload from '@strapi/plugin-upload/strapi-admin';
import i18N from '@strapi/plugin-i18n/strapi-admin';
import usersPermissions from '@strapi/plugin-users-permissions/strapi-admin';


const plugins = {
  'content-type-builder': contentTypeBuilder,
  'email': email,
  'upload': upload,
  'i18n': i18N,
  'users-permissions': usersPermissions,
};

export default plugins;

```
tsc -v
Version 5.2.2

node
v16.15.1

**Comment by JimmyRice** [comment]
I'm also encountering the same issue. I've installed the plugin-color-picker in Strapi, but when I open Custom Field, I can't find this plugin.

Strapi Version: `"@strapi/strapi": "4.13.6"`
Color Picker Verison: `"@strapi/plugin-color-picker": "^4.13.6",`

On:
Windows 11 version 22H2
NodeJS: `v18.12.1`

**Comment by A1exPR0** [comment]
I've encountered the same issue today.

> I'm also encountering the same issue. I've installed the plugin-color-picker in Strapi, but when I open Custom Field, I can't find this plugin.
> 
> Strapi Version: `"@strapi/strapi": "4.13.6"` Color Picker Verison: `"@strapi/plugin-color-picker": "^4.13.6",`
> 
> On: Windows 11 version 22H2 NodeJS: `v18.12.1`

Node version v18.16.0

**Comment by joshuaellis** [comment]
@jramstedt i've just followed your steps although if we're being pedantic one was missing so it was in fact these steps:

```shell
yarn create strapi-app colorpickertest --quickstart --ts --no-run
cd colorpickertest
yarn add @strapi/plugin-color-picker
yarn build
```

Which then produced the `plugin.js` file:

```js

import contentTypeBuilder from '@strapi/plugin-content-type-builder/strapi-admin';
import email from '@strapi/plugin-email/strapi-admin';
import upload from '@strapi/plugin-upload/strapi-admin';
import colorPicker from '@strapi/plugin-color-picker/strapi-admin';
import i18N from '@strapi/plugin-i18n/strapi-admin';
import usersPermissions from '@strapi/plugin-users-permissions/strapi-admin';


const plugins = {
  'content-type-builder': contentTypeBuilder,
  'email': email,
  'upload': upload,
  'color-picker': colorPicker,
  'i18n': i18N,
  'users-permissions': usersPermissions,
};

export default plugins;
```

So, unfortunately I am still unable to reproduce your issue.

**Comment by jramstedt** [comment]
@joshuaellis Are you running windows?

**Comment by joshuaellis** [comment]
> Hello @joshuaellis I've been trough the same problem described by @jramstedt .
> 
> Did you try to add the colorpicker package to an existing Strapi project?
> 
> I just updated the strapi to the 4.13.6 few days ago and then I try to add the color-picker package using npm.
> 
> I still see the plugin correctly installed inside the list of plugins on Strapi admin but it still not showing up inside the custom fields.

I would encourage you to supply a reproduction of the issue in that case then :)

**Comment by axelpezzo** [comment]
> > Hello @joshuaellis I've been trough the same problem described by @jramstedt .
> > Did you try to add the colorpicker package to an existing Strapi project?
> > I just updated the strapi to the 4.13.6 few days ago and then I try to add the color-picker package using npm.
> > I still see the plugin correctly installed inside the list of plugins on Strapi admin but it still not showing up inside the custom fields.
> 
> I would encourage you to supply a reproduction of the issue in that case then :)

I don't understand: the steps are the same as described by @jramstedt. I just tried to add the package in a strapi 4.13.6 installation and I can't see it inside the plugin.js file under .cache folder but I see the plugin installed inside the admin panel.

I run windows too I don't know if this could be a lead to solve it.

**Comment by JimmyRice** [comment]
I installed the Color Picker plugin after creating a new Strapi project. Similarly, I can see that the Color Picker plugin has been correctly installed in the admin panel. However, I cannot find this plugin in the Custom Field.

**Comment by JimmyRice** [comment]
> > > Hello @joshuaellis I've been trough the same problem described by @jramstedt .
> > > Did you try to add the colorpicker package to an existing Strapi project?
> > > I just updated the strapi to the 4.13.6 few days ago and then I try to add the color-picker package using npm.
> > > I still see the plugin correctly installed inside the list of plugins on Strapi admin but it still not showing up inside the custom fields.
> > 
> > 
> > I would encourage you to supply a reproduction of the issue in that case then :)
> 
> I don't understand: the steps are the same as described by @jramstedt. I just tried to add the package in a strapi 4.13.6 installation and I can't see it inside the plugin.js file under .cache folder but I see the plugin installed inside the admin panel.
> 
> I run windows too I don't know if this could be a lead to solve it.


I believe there might be some correlation with the operating system. I used my server (Linux, Debian distribution) to run npm run build, and after launching it with npm run develop, I found that I could locate the Color in the Custom Field.

@joshuaellis

**Comment by marcelodelta** [comment]
I have the same problem. I'm using it on Windows.
