### ISSUE TITLE
Error: Trying to associate a collection attribute to a model that doesn't have a Foreign Key

### ISSUE THREAD

**Issue by andyjessop** [strapi/strapi#181]
**Node.js version**: 4.1.0
**npm version**: 3.10.8
**Strapi version**: 1.5.4
**Operating system**: OS X Yosemite 10.10.5

After creating my APIs via the studio, I restart strapi locally, but get the following error:

```
/usr/local/lib/node_modules/strapi/node_modules/waterline-schema/lib/waterline-schema/references.js:115
    throw new Error('Trying to associate a collection attribute to a model that doesn\'t have a ' +
    ^

Error: Trying to associate a collection attribute to a model that doesn't have a Foreign Key. game is trying to reference a foreign key in user
    at References.findReference (/usr/local/lib/node_modules/strapi/node_modules/waterline-schema/lib/waterline-schema/references.js:115:11)
    at References.addKeys (/usr/local/lib/node_modules/strapi/node_modules/waterline-schema/lib/waterline-schema/references.js:72:22)
    at new References (/usr/local/lib/node_modules/strapi/node_modules/waterline-schema/lib/waterline-schema/references.js:31:10)
    at new module.exports (/usr/local/lib/node_modules/strapi/node_modules/waterline-schema/lib/waterline-schema.js:36:17)
    at Waterline.initialize (/usr/local/lib/node_modules/strapi/node_modules/waterline/lib/waterline.js:107:17)
    at Hook.hook.initialize (/usr/local/lib/node_modules/strapi/lib/configuration/hooks/waterline/index.js:167:20)
    at Hook.wrapper [as initialize] (/usr/local/lib/node_modules/strapi/node_modules/lodash/index.js:3095:19)
    at /usr/local/lib/node_modules/strapi/lib/configuration/hooks/index.js:54:14
    at /usr/local/lib/node_modules/strapi/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/strapi/node_modules/async/lib/async.js:550:17
    at /usr/local/lib/node_modules/strapi/node_modules/async/lib/async.js:544:17
    at _arrayEach (/usr/local/lib/node_modules/strapi/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/local/lib/node_modules/strapi/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

I tried to go back into the studio to see what's wrong, but can't access the app as it's greyed out:

<img width="417" alt="screen shot 2017-01-28 at 11 24 20" src="https://cloud.githubusercontent.com/assets/1304307/22395926/780084a2-e54c-11e6-9e52-9abef6af1d79.png">

**Comment by andyjessop** [comment]
I have solved this now by manually editing the models json to fix the relations.
