### ISSUE TITLE
@ckeditor/strapi-plugin-ckeditor throw an error when npm run build

### ISSUE THREAD

**Issue by 523299338** [strapi/strapi#18150]
### Required System information

- Node.js version: 16.20.2
- NPM version: 8.5.2
- Strapi version: 3.5.3
- Database: mysql
- Operating system: windows
- Is your project Javascript or Typescript: Javascript 

### Describe the bug

when npm run build, @ckeditor/strapi-plugin-ckeditor throw errors

### Steps to reproduce the behavior

 "@ckeditor/strapi-plugin-ckeditor": "^0.0.7",
```
> strapi build
17:19:43  
17:19:43  Building your admin UI with development configuration...
17:19:43  [info] [webpackbar] Compiling Webpack
17:20:10  [success] [webpackbar] Webpack: Compiled with some errors in 23.45s
17:20:10  [
17:20:10    {
17:20:10      moduleIdentifier: '/app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/@ckeditor/strapi-plugin-ckeditor/admin/src/index.js',
17:20:10      moduleName: './node_modules/@ckeditor/strapi-plugin-ckeditor/admin/src/index.js',
17:20:10      loc: '26:10',
17:20:10      message: 'Module parse failed: Unexpected token (26:10)\n' +
17:20:10        'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
17:20:10        '|       icon: () => {\n' +
17:20:10        '|         return (\n' +
17:20:10        '>           <IconBox justifyContent="center" alignItems="center" width={ 7 } height={ 6 } hasRadius aria-hidden>\n' +
17:20:10        '|             <Icon as={ CKEditorIcon } />\n' +
17:20:10        '|           </IconBox>',
17:20:10      moduleId: 6575,
17:20:10      moduleTrace: [ [Object], [Object], [Object] ],
17:20:10      details: undefined,
17:20:10      stack: 'ModuleParseError: Module parse failed: Unexpected token (26:10)\n' +
17:20:10        'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
17:20:10        '|       icon: () => {\n' +
17:20:10        '|         return (\n' +
17:20:10        '>           <IconBox justifyContent="center" alignItems="center" width={ 7 } height={ 6 } hasRadius aria-hidden>\n' +
17:20:10        '|             <Icon as={ CKEditorIcon } />\n' +
17:20:10        '|           </IconBox>\n' +
17:20:10        '    at handleParseError (/app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/webpack/lib/NormalModule.js:982:19)\n' +
17:20:10        '    at /app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/webpack/lib/NormalModule.js:1101:5\n' +
17:20:10        '    at processResult (/app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/webpack/lib/NormalModule.js:806:11)\n' +
17:20:10        '    at /app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/webpack/lib/NormalModule.js:866:5\n' +
17:20:10        '    at /app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/loader-runner/lib/LoaderRunner.js:407:3\n' +
17:20:10        '    at iterateNormalLoaders (/app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/loader-runner/lib/LoaderRunner.js:233:10)\n' +
17:20:10        '    at /app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/loader-runner/lib/LoaderRunner.js:224:4\n' +
17:20:10        '    at /app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/webpack/lib/NormalModule.js:840:15\n' +
17:20:10        '    at Array.eval (eval at create (/app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)\n' +
17:20:10        '    at runCallbacks (/app/workspace/DEPLOY/esg-owf-core/esg-owf-core-strapi4/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:15)'
17:20:10    }
17:20:10  ]
17:20:10  Admin UI built successfully
```

how to resolve this error?

**Comment by elrhourha** [comment]
@523299338 hey, do you have a solution for this issue ?
thanks

**Comment by 523299338** [comment]
> @523299338 hey, do you have a solution for this issue ? thanks

@elrhourha 
in my case, i misundertand the use of  @ckeditor/strapi-plugin-ckeditor 

i delete the config of @ckeditor/strapi-plugin-ckeditor in file 'config/plugins.js', and then, no error occurs
```
   // 'ckeditor': {
    //   enabled: true,
    //   resolve: 'node_modules/@ckeditor/strapi-plugin-ckeditor'
    // },
```

**Comment by SalahAdDin** [comment]
I'm having this issue with every plugin I installed, I don't know why!!!
