### ISSUE TITLE
Forgot-password: no email sent with sendmail

### ISSUE THREAD

**Issue by pgsfredda** [strapi/strapi#18176]
### Required System information

- Strapi Version: 4.13.7
- Operating System: Ubuntu 20.04.6 LTS
- Database: mySQL 8.0.34 (using mysql2 as driver)
- Node Version: 18.18.0
- NPM Version: 9.8.1
- Yarn Version: none
- Dev language: typescript

### Describe the bug
Invoking strapi api https://mydomain/strapi/api/auth/forgot-password/ the response is:
~~~js
{
    "ok": true
}
~~~
**but no email sent nor received**

### Steps to reproduce the behavior

With postman, or any other tool to invoke rest api or in a client app, 

1. set `request method`: POST
2. set `url`: `https://mydomain/strapi/api/auth/forgot-password/`
3. set `body`: `{ "email": youremail@domain.ext  }` using a valid and a registered user mail address
4. send the request

### Expected behavior
The response is
~~~js
{
    "ok": true
}
~~~
and an email is sent by `sendmail` and received by the user

### Additional context

- `strapi email plugin` is correctly configured and successfully tested with the mail test send process in strapi admin app
- `sendmail`  on the same server is successfully used

Can someone help me?

Thank you in advance

**Comment by akhil888binoy** [comment]
is anybody working on this issue?

**Comment by pgsfredda** [comment]
# UPDATE

I installed @strapi/provider-email-nodemailer plugin (nodemailer for strapi v4).

Sending emails to gmail, aruba, tin addresses I get a Strapi Error about a `no-replay` sender address or, when I receive an `ok` answer from the server **no mail is send nor received** exactly as when I use `sendmail`.

### Strapi error log
~~~code
Error: Mail command failed: 550 5.1.0 <no-reply@mydomain> lZwHqEkCXZKt6lZwHqcENf - Mittente non consentito / Sender not allowed ( mail from )
    at SMTPConnection._formatError (.../server/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection._actionMAIL (.../server/node_modules/nodemailer/lib/smtp-connection/index.js:1578:34)
    at SMTPConnection.<anonymous> (.../server/node_modules/nodemailer/lib/smtp-connection/index.js:1047:18)
    at SMTPConnection._processResponse (.../server/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)
    at SMTPConnection._onData (.../server/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)
    at SMTPConnection._onSocketData (.../server/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
~~~

### My plugin config:
~~~js
email: {
        config: {
            provider: env('EMAIL_PROVIDER'),
            providerOptions: {
                host: env('EMAIL_SMTP_HOST'),
                port: env('EMAIL_SMTP_PORT'),
                auth: {
                  user: env('EMAIL_SMTP_USER'),
                  pass: env('EMAIL_SMTP_PASS'),
                },
              },
            settings: {
                defaultFrom: env('EMAIL_ADDRESS_FROM'),
                defaultReplyTo: env('EMAIL_ADDRESS_REPLY'),
            },
        }
    },
~~~

### My .env (email section):
~~~js
# Email SMTP
EMAIL_PROVIDER=nodemailer
EMAIL_SMTP_HOST=smtps server
EMAIL_SMTP_PORT=port
EMAIL_SMTP_USER=mysmtpuser
EMAIL_SMTP_PASS=mysmtppwd
EMAIL_ADDRESS_FROM=myemail
EMAIL_ADDRESS_REPLY=myemail
~~~

**Comment by Janaki4** [comment]
@pgsfredda 
 Anyone working on this ? Can i take it ?

**Comment by kvengerov** [comment]
I have same problem

- Strapi Version: 4.14.0
- Node Version: 18.17.1
- NPM Version: 10.1.0
- Dev language: typescript
- "@strapi/provider-email-nodemailer": "4.14.0",

```
email: {
    provider: env('AUTH_EMAIL_PROVIDER', 'nodemailer'),
    providerOptions: {
      host: env('AUTH_SMTP_HOST', 'mailhog'),
      port: env('AUTH_SMTP_PORT', 1025),
      auth: {
        user: env('AUTH_SMTP_USER', 'user'),
        pass: env('AUTH_SMTP_PASS', 'password'),
      },
      tls: {
        version: "TLSv1",
      },
      ignoreTLS: true,
    },
    settings: {
      defaultFrom: 'hello@example.com',
      defaultReplyTo: 'hello@example.com',
    },
  },
  ```
  

>   /admin/settings/email
>   test email failed (on real email)

>   api/auth/forgot-password
>   500 Internal Server Error

>  error in console
>  Error: Couldn't send test email: SMTP code:550 msg:550-5.7.26 Unauthenticated email from strapi.io is not accepted due to domain's

**Comment by pgsfredda** [comment]
@Janaki4 
Unfortunately I don’t know. I think that you can take it but I'm not in the strapi team.

**Comment by derrickmehaffy** [comment]
Did you change the email addresses in the email templates in the settings section of the admin? It appears an email is trying to be sent but is not authorized due to a DKIM error as the application is not authorized to send.

**Comment by pgsfredda** [comment]
Thank you @derrickmehaffy  for your suggestion.

Of course, I did it.
I tested with `no-replay`, with another unexisting address and with an existing address of my domain.

I also think it might be a dkim problem but I don’t know how to get around it.
However, `sendmail` does not work at all.
The tests I’m doing now are with `nodemailer`.

**Comment by Vansh17555555** [comment]
anyone working on this ?can i take it?
