### ISSUE TITLE
warn (hook:strapi-mongoose) `strapi-hook-strapi-mongoose` is missing in your dependencies

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#1821]
**Informations**
- **Node.js version**: 10.7.0
- **npm version**: 6.2.0
- **Strapi version**: 12.6
- **Database**: mongodb
- **Operating system**: win10

**What is the current behavior?**
```warn (hook:strapi-mongoose) `strapi-hook-strapi-mongoose` is missing in your dependencies. Please run `npm install strapi-hook-strapi-mongoose```

and this is following error
```
(node:9085) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/core/store.js:55:47)
    at module.exports (/mnt/g/freelance/wrapify_backend/plugins/settings-manager/config/functions/bootstrap.js:17:26)
    at Promise (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:285:13)
    at new Promise (<anonymous>)
    at execBootstrap (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:273:11)
    at Promise.all.Object.values.map.x (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:312:44)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:312:35)
    at Strapi.start (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:107:18)
(node:9085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:9085) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9085) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/core/store.js:55:47)
    at module.exports (/mnt/g/freelance/wrapify_backend/plugins/users-permissions/config/functions/bootstrap.js:77:45)
    at Promise (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:285:13)
    at new Promise (<anonymous>)
    at execBootstrap (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:273:11)
    at Promise.all.Object.values.map.x (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:312:44)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:312:35)
    at Strapi.start (/mnt/g/freelance/wrapify_backend/node_modules/strapi/lib/Strapi.js:107:18)
(node:9085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:9085) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
    at fs.readdir (/mnt/g/freelance/wrapify_backend/plugins/email/config/functions/bootstrap.js:53:40)
(node:9085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:9085) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
    at fs.readdir (/mnt/g/freelance/wrapify_backend/plugins/upload/config/functions/bootstrap.js:55:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[2018-08-27T18:56:24.539Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2018-08-27T18:56:24.541Z] warn Perhaps you forgot to call it?
[2018-08-27T18:56:24.542Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2018-08-27T18:56:24.544Z] warn Perhaps you forgot to call it?
[2018-08-27T18:56:24.549Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2018-08-27T18:56:24.553Z] warn Perhaps you forgot to call it?
[2018-08-27T18:56:24.555Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2018-08-27T18:56:24.557Z] warn Perhaps you forgot to call it?
```
when I run ```npm run dev``` or ```strapi start```

**Steps to reproduce the problem**
Previously it worked fine untiI I push a project to my repository and I clone project to my droplet on digitalocean but It not work, 
I tried delete my local project folder and ```git clone``` from repo to my computer again for solve this issue But I get a error same as my droplet server

**What is the expected behavior?**
Make it work again

**Comment by xeastcrast** [comment]
@derrickmehaffy It work for me. Thanks a lot 👍 👍 👍 👍 👍

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/wiki/migration-guide-alpha.12.7-to-alpha.13#%EF%B8%8F-update-hook-name
