### ISSUE TITLE
main.105dcf23.js:933 TypeError: ht?.toDate is not a function     at main.105dcf23.js:1618:2459     at sf (main.105dcf23.js:931:20470)     at kf (main.105dcf23.js:933:1578)     at Ca (main.105dcf23.js:933:47145)     at ti (main.105dcf23.js:933:40771)     at gr (main.105dcf23.js:933:40699)     at wr (main.105dcf23.js:933:40553)     at Q (main.105dcf23.js:933:36809)     at ie (main.105dcf23.js:933:37614)     at ds (main.105dcf23.js:931:3278) overrideMethod	@	console.js:213 Sl	@	main.105dcf23.js:933 Ff.M.callback	@	main.105dcf23.js:933 qc	@	main.105dcf23.js:931 ou	@	main.105dcf23.js:933 Pu	@	main.105dcf23.js:933 Vf	@	main.105dcf23.js:933 Yi	@	main.105dcf23.js:933 Si	@	main.105dcf23.js:933 ie	@	main.105dcf23.js:933 ds	@	main.105dcf23.js:931 (anonyme)	@	main.105dcf23.js:933 Afficher moins

### ISSUE THREAD

**Issue by ouipark** [strapi/strapi#18216]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by GHkrishna** [comment]
@ouipark, can you please provide a way to reproduce the error?

The current comment seems unhelpful.

**Comment by Aryan9592** [comment]
@ouipark Try to write a short title for any particular issue which let other devs understand the error/bug you pointing out.
