### ISSUE TITLE
error: INSERT INTO pages_localizations_links (page_id, inv_page_id) VALUES (148, undefined),(148, 155) - ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'.

### ISSUE THREAD

**Issue by arnoldski** [strapi/strapi#18231]
## Bug report
error: INSERT INTO pages_localizations_links (page_id, inv_page_id) VALUES (148, undefined),(148, 155) - ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'.

### Required System information
- Node.js version: v16.20.0
- Yarn version: 1.22.19
- Strapi version: 4.14.0
- Database: mysql 8.0
- Operating system: macOS 13.5.2
- Is your project Javascript or Typescript: JS

### Describe the bug

[2023-10-02 10:53:20.145] error: INSERT INTO pages_localizations_links (page_id, inv_page_id) VALUES (148, undefined) - ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
    at Query.Sequence._packetToError (/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
    --------------------
    at Protocol._enqueue (/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/node_modules/mysql/lib/Connection.js:198:25)
    at /node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/node_modules/knex/lib/client.js:154:12)
    at Runner.query (/node_modules/knex/lib/execution/runner.js:141:36)
    at ensureConnectionCallback (/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/node_modules/knex/lib/execution/runner.js:318:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.run (/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.beforeDelete (/node_modules/@notum-cz/strapi-plugin-content-versioning/server/services/lifecycles/beforeDelete.js:78:7)
    at async Object.beforeDelete (/node_modules/@notum-cz/strapi-plugin-content-versioning/server/bootstrap.js:64:9)
    at async Object.run (/node_modules/@strapi/database/lib/lifecycles/index.js:76:11)
    at async Object.delete (/node_modules/@strapi/database/lib/entity-manager/index.js:429:22)

### Steps to reproduce the behavior
1. Go to 'Content manager'
2. Click on 'Page'
3. Till in the `Title of the page`
4. Click on 'Save'
5. Click on 'Publish'
6. See the error `success Internal Server Error` in the UI

The same issues appears when trying to "Delete the entry".

### Screenshots

![Screenshot 2023-10-02 at 10 53 16](https://github.com/strapi/strapi/assets/344496/9785f13e-8f38-450f-ba2a-cc0ddcef5b3a)

![Screenshot 2023-10-02 at 10 53 21](https://github.com/strapi/strapi/assets/344496/7c864540-a376-4365-b8c2-2902b55ed4b8)

### Code snippets

`package.json` dependencies:

"@_sh/strapi-plugin-ckeditor": "^2.0.4",
  "@notum-cz/strapi-plugin-content-versioning": "^0.4.11",
  "@retikolo/drag-drop-content-types": "^1.3.9",
  "@strapi/plugin-graphql": "^4.14.0",
  "@strapi/plugin-i18n": "4.14.0",
  "@strapi/plugin-seo": "^1.9.5",
  "@strapi/plugin-users-permissions": "4.14.0",
  "@strapi/strapi": "4.14.0",
  "better-sqlite3": "8.6.0",
  "mysql": "^2.18.1",
  "patch-package": "^6.5.1",
  "strapi-plugin-cloudflare-pages": "^0.5.0",
  "strapi-plugin-duplicate-button": "^1.1.13",
  "strapi-plugin-import-export-entries": "^1.21.0",
  "strapi-plugin-multi-select": "^1.2.2",
  "strapi-plugin-publisher": "^1.4.1",
  "strapi-plugin-rest-cache": "^4.2.8",
  "strapi-plugin-server-route-permission": "^2.0.2",
  "strapi-plugin-slugify": "^2.3.4"

**Comment by Boegie19** [comment]
@arnoldski could you to ensure the issue is not the content-type can you send me the content-type of pages?

**Comment by arnoldski** [comment]
This is the `schema.json` of page:

`
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "singularName": "page",
    "pluralName": "pages",
    "displayName": "Page",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "versions": {
      "versioned": true
    },
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "title": {
      "type": "string",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "required": true
    },
    "body": {
      "type": "customField",
      "options": {
        "preset": "custom"
      },
      "customField": "plugin::ckeditor5.CKEditor",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "image": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "slice": {
      "type": "dynamiczone",
      "components": [
        "slices.account",
        "slices.accordion",
        "slices.article",
        "slices.badge",
        "slices.benefits",
        "slices.content-columns",
        "slices.card",
        "slices.card-circle",
        "slices.card-custom",
        "slices.card-product",
        "slices.cards-carousel",
        "slices.content-background-image",
        "slices.content-columns-circle",
        "slices.content-numbers",
        "slices.content-stamp",
        "slices.content-with-image",
        "slices.country-list",
        "slices.cta",
        "slices.faq",
        "slices.hero",
        "slices.hero-homepage",
        "slices.hero-products",
        "slices.hero-product-promo",
        "slices.highlight",
        "slices.images",
        "slices.logos",
        "shared.meta-social",
        "slices.product-group",
        "slices.product-overview",
        "shared.seo",
        "slices.testimonial",
        "slices.trustpilot-reviews",
        "slices.review",
        "slices.video"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "type": {
      "type": "enumeration",
      "enum": [
        "Default",
        "Account",
        "Articles",
        "Contact",
        "Dialog",
        "FAQ",
        "Homepage",
        "Landing page",
        "Product overview",
        "Reviews",
        "Store locator",
        "Error 404"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "default": "Default",
      "required": true
    },
    "seo": {
      "type": "component",
      "repeatable": false,
      "component": "shared.seo",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "slug": {
      "type": "uid",
      "targetField": "title"
    },
    "rank": {
      "pluginOptions": {
        "versions": {
          "versioned": true
        },
        "i18n": {
          "localized": true
        }
      },
      "type": "integer"
    },
    "slugLocale": {
      "pluginOptions": {
        "versions": {
          "versioned": true
        },
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    }
  }
}

`

**Comment by arnoldski** [comment]
@Boegie19 I've installed a clean version of Strapi, copy-pasted all my content and now everything seems to be working again.

**Comment by Boegie19** [comment]
@arnoldski Can I mark this issue as solved?
