### ISSUE TITLE
mysql not connecting to strapi application

### ISSUE THREAD

**Issue by Nixan04** [strapi/strapi#18243]
Hi Team,

strapi version-3.1.0-alpha.5
node -18
mysql -8.0.34
npm-10.1.0
 when I am trying to connect to mysql database using strapi and the command "npm run develop" it is showing the following error"

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'strapi_user'@'localhost' (using password: YES)
    at Sequence._packetToError (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at TLSSocket.ondata (node:internal/streams/readable:777:22)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:335:12)
    --------------------
    at Protocol._enqueue (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/ubuntu/my-project/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/ubuntu/my-project/node_modules/mysql/lib/Connection.js:116:18)
    at /home/ubuntu/my-project/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/home/ubuntu/my-project/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/home/ubuntu/my-project/node_modules/knex/lib/client.js:262:39) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'strapi_user'@'localhost' (using password: YES)",
  sqlState: '28000',
  fatal: true

"but when i check all the username password for mysql are same in .env file and /config/database.js"

"please do help me it will be really help for me "

**Comment by aethiss** [comment]
For mysql version 2.16.0 (Sept 2018):
just create a new user on mysql.

GRANT ALL PRIVILEGES ON *.* TO 'username'@'localhost' IDENTIFIED BY 'password';

**Comment by Boegie19** [comment]
1 are you sure you .env variables are named correctly.
2 depending on the mysql version you are using you need to use the mysql2 package.
