### ISSUE TITLE
TypeError: strapi.plugins.email.services.send is not a function

### ISSUE THREAD

**Issue by henricazottes** [strapi/strapi#1858]
**Informations**
- **Node.js version**:
v9.11.2
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.14

- **Database**:
Mongodb

- **Operating system**:
Ubuntu 18.04

**What is the current behavior?**
When posting to ``/email``, I get a server error on the client. The server error is the following:

```
Services: { getProviderConfig: [AsyncFunction: getProviderConfig],
  send: [AsyncFunction: send] }
TypeError: strapi.plugins.email.services.send is not a function
    at send (/home/henri/Documents/2018/content-manager/plugins/email/controllers/Email.js:35:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Steps to reproduce the problem**
Install Strapi
Use postman and pots to ``/email``

**What is the expected behavior?**
Sending the email

**Suggested solutions**
I just added replace the following line in ``/plugins/email/controllers/Email.js``
```js
await strapi.plugins.email.services.send(options, config);
```
by
```js
await strapi.plugins.email.services.email.send(options, config);
```
And it works like a charm. Didn't check any further.

**Comment by henricazottes** [comment]
@lauriejim totally sorry! Missed your mention, glad you fixed it :)
