### ISSUE TITLE
Cannot create entry containing floats

### ISSUE THREAD

**Issue by g-div** [strapi/strapi#1859]
**Informations**
- **Node.js version**: v10.1.0
- **npm version**: 6.0.1
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MongoDB
- **Operating system**: Linux

**What is the current behavior?**
Creating a new entry containing a *float* field returns the error:
```
Error:  not a valid Decimal128 string
```
which is otherwise not easily debuggable because the error gets catched [here](https://github.com/strapi/strapi/blob/60a7e99d11a2ac15317c7aeb378dec5022fb7776/packages/strapi-plugin-content-manager/config/queries/mongoose.js#L111) displaying: 
```
This not,a,valid,Decimal,128,string is already taken
```

**Steps to reproduce the problem**
- Create a new *Type* using the *Content Type Builder*
- Add a *float* field
- Create a new *Entry* of the new *Type*
- Fill out the input fields
- Click on *Save*

**What is the expected behavior?**
The new entry gets created

**Comment by derrickmehaffy** [comment]
what mongoDB version?

**Comment by g-div** [comment]
I've tried 3.2.8 locally and 3.6.7 on the server

**Comment by lauriejim** [comment]
@g-div What is the value to set to have this issue please.

**Comment by Blacknosaur** [comment]
I confirm this issue at Node v10.5, npm v6.1, Strapi Alpha 14 and mongoDB v3.6.5

**Comment by g-div** [comment]
@lauriejim I've just tried to add fill out the form with a float, like for example `3.4539`

**Comment by TokenChingy** [comment]
I'm confirming this issue for GraphQL Mutations #1650 . Initially I thought it was a MongoDB version issue (thanks to @Aurelsicoko) however upon doing a full wipe of the server and fresh install of MongoDB, it still occurs.

Node.js version: v10.9.0
npm version: 6.2.0
Strapi version: 3.0.0-alpha.14 (modified to include upstream GraphQL Mutations).
Database: MongoDB 4.0
Operating system: Ubuntu 18.04 LTS

**Current Behaviour**
Send a mutations query with a float input:
```
mutation {
  createItem(input: {
    data: {
      name: "Orange",
      description: "A sweet and tasty fruit.",
      price: 3.4539,
      inStock: true,
    }
  }) {
    item {
      name
      description
      price
      inStock
    }
  }
}
```
 An error is returned:
```
{
  "data": {
    "createItem": null
  },
  "errors": [
    {
      "message": " not a valid Decimal128 string",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createItem"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error:  not a valid Decimal128 string",
            "    at Function.Decimal128.fromString (/home/jason/LittleMenuStrapi/node_modules/mongodb-core/node_modules/bson/lib/bson/decimal128.js:252:11)",
            "    at Decimal128.cast (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/schema/decimal128.js:122:27)",
            "    at Decimal128.SchemaType.getDefault (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/schematype.js:702:25)",
            "    at $__applyDefaults (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/document.js:309:22)",
            "    at model.Document (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/document.js:104:3)",
            "    at model.Model (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/model.js:72:12)",
            "    at new model (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/model.js:4286:13)",
            "    at toExecute.push.callback (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/model.js:2491:22)",
            "    at /home/jason/LittleMenuStrapi/node_modules/async/internal/parallel.js:31:39",
            "    at eachOfArrayLike (/home/jason/LittleMenuStrapi/node_modules/async/eachOf.js:65:9)",
            "    at exports.default (/home/jason/LittleMenuStrapi/node_modules/async/eachOf.js:9:5)",
            "    at _parallel (/home/jason/LittleMenuStrapi/node_modules/async/internal/parallel.js:30:5)",
            "    at parallelLimit (/home/jason/LittleMenuStrapi/node_modules/async/parallel.js:88:26)",
            "    at utils.promiseOrCallback.cb (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/model.js:2501:5)",
            "    at Promise (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/utils.js:246:5)",
            "    at new Promise (<anonymous>)",
            "    at Object.promiseOrCallback (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/utils.js:245:10)",
            "    at Function.create (/home/jason/LittleMenuStrapi/node_modules/mongoose/lib/model.js:2462:16)",
            "    at Object.add (/home/jason/LittleMenuStrapi/api/item/services/Item.js:83:30)",
            "    at create (/home/jason/LittleMenuStrapi/api/item/controllers/Item.js:56:33)",
            "    at resolver (/home/jason/LittleMenuStrapi/plugins/graphql/services/Mutation.js:136:16)",
            "    at /home/jason/LittleMenuStrapi/plugins/graphql/services/Mutation.js:218:41"
          ]
        }
      }
    }
  ]
}
```

**Expected Behaviour**
Accept the float input and create a new entry.

**Comment by TokenChingy** [comment]
Another issue occurs in the admin panel...

**Current Behaviour**
Define a new type with only one field and set that field to Float. Try and create a new content of that type. Admin panel freezes and will not load the form to do so.

**Expected Behaviour**
Be able to see the admin form to create the content.

**Comment by TokenChingy** [comment]
So after a long night of looking through all of Strapi, I've come to realise that this code breaks everything in terms of `floats` and `decimals`:

> ./node_modules/strapi-hook-mongoose/lib/utils/index.js

```js
'use strict';

/**
 * Module dependencies
 */

module.exports = mongoose => {
  require('mongoose-float').loadType(mongoose);

  return {
    convertType: mongooseType => {
      switch (mongooseType.toLowerCase()) {
        case 'array':
          return Array;
        case 'boolean':
          return 'Boolean';
        case 'binary':
          return 'Buffer';
        case 'date':
        case 'datetime':
        case 'time':
        case 'timestamp':
          return Date;
        case 'decimal':
          return 'Float';
        case 'float':
          return mongoose.Schema.Types.Decimal128;
        case 'json':
          return 'Mixed';
        case 'biginteger':
        case 'integer':
          return 'Number';
        case 'uuid':
          return 'ObjectId';
        case 'email':
        case 'enumeration':
        case 'password':
        case 'string':
        case 'text':
          return 'String';
        default:
      }
    },
  };
};

```

I suspect it's to do with that case on `decimal` being returned as a `Float`? Which causes the Decimal128 parser to freak out as it's expecting a `String` or `NaN` or `Something not a Float`?

Anyway, I managed to fix `floats` to now allow them to be created, edited, and read via Shadow CRUD and GraphQL. This is the replacement code:

```js
'use strict';

/**
 * Module dependencies
 */

module.exports = mongoose => {
  require('mongoose-float').loadType(mongoose);

  const SchemaTypes = mongoose.Schema.Types;

  /**
   * Since we don't want to use decimals for the time being... we can just reimplement the trivial decimal handler...
   *
   * case 'decimal':
   *   return 'Float';
   *
   * would cause string expectations. Now it gets a string and is quite happy. Don't use decimals until this is properly addressed.
   */
  SchemaTypes.Decimal.prototype.cast = function(value) {
    // Note: The decimal format isn't well supported by MongoDB.
    return value.toString(); // It's recommended to use Float or Number type instead.
  };

  return {
    convertType: mongooseType => {
      switch (mongooseType.toLowerCase()) {
        case 'array':
          return Array;
        case 'boolean':
          return 'Boolean';
        case 'binary':
          return 'Buffer';
        case 'date':
        case 'datetime':
        case 'time':
        case 'timestamp':
          return Date;
        case 'decimal':
          return 'Decimal';
        case 'float':
          return mongoose.Schema.Types.Decimal128;
        case 'json':
          return 'Mixed';
        case 'biginteger':
        case 'integer':
          return 'Number';
        case 'uuid':
          return 'ObjectId';
        case 'email':
        case 'enumeration':
        case 'password':
        case 'string':
        case 'text':
          return 'String';
        default:
      }
    },
  };
};

```

I managed to dig up an old commit from Strapi that removed the trivial `decimal` to `String` trick and reimplemented it; see this [commit](https://github.com/strapi/strapi/commit/065346e7ef3e5e9c4f50af976a504a6e307a9efc#diff-4d12c8409a675d9f4b42b4da96467e22).

**What this means however... we should not use this trivial implementation as a permanent thing, instead we should probably look at the underlying problem and figure out how better to handle `decimals`.**

**Comment by fezproof** [comment]
Seems that decimal types need to be passed through a constructor of NumberDecimal(string amount) before they are passed into the database.
See https://docs.mongodb.com/manual/core/shell-types/#numberdecimal
This might be a way to fix it more permanently while keeping the accuracy difference between decimal and float. Both types should exist because they are quite different use cases.

**Comment by TokenChingy** [comment]
@lauriejim a temporary patch to enable working `float` and semi-working `decimal` can be found [here](https://github.com/TokenChingy/StrapiGraphQLMutationsPatch).

Files you should look at:

> /node_modules/strapi-hook-mongoose/libs/utils/index.js
> /plugins/graphql/services/Types.js

**Decimal**
- Inputs and returns as a float, parsed as a String.
- Aggregator functions: sum and avg do not work but min and max do?

**Comment by g-div** [comment]
This issue isn't completely solved. The content type manager will set `"default": ""` to a new created float field, which will cause the error popping up again on save (since we are trying to save an empty string as decimal value). Removing the default value will fix it.

**Comment by lauriejim** [comment]
Hello @g-div , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
