### ISSUE TITLE
Error Occurs When Adding app.js to /src/admin/ and then running npm run develop (Can't resolve 'react-dom/client')

### ISSUE THREAD

**Issue by inannan423** [strapi/strapi#18637]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.15.0
- Database: sqlite
- Operating system: Windows 11
- Is your project Javascript or Typescript: Javascript 

### Describe the bug

Title: Error Occurs When Adding app.js to /src/admin/ and Running `npm run develop` (Can't resolve 'react-dom/client')

Added the following content:

```javascript
export default {
  config: {
    locales: ['zh']
  },
  bootstrap() {},
}
```

Error Message:

```bash
> strapi develop

Building your admin UI with development configuration...

● Webpack █████████████████████████ building (10%) 0/1 entries 5/7 dependencies 0/5 modules 5 active
 esbuild-loader › .cache\admin\src\core\apis\index.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in 'E:\Desktop\实创\carera-back\.cache\admin\src'
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\Compilation.js:2022:28
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:817:13
    at eval (eval at create (E:\Desktop\实创\carera-back\node_modules\.store\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (E:\Desktop\实创\carera-back\node_modules\.store\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:448:22
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:118:11
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:689:25
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:893:8
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in 'E:\Desktop\实创\carera-back\.cache\admin\src'
  Parsed request is a module
  using description file: E:\Desktop\实创\carera-back\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\Desktop\实创\carera-back\.cache\admin\src\node_modules doesn't exist or is not a directory
      E:\Desktop\实创\carera-back\.cache\admin\node_modules doesn't exist or is not a directory
      E:\Desktop\实创\carera-back\.cache\node_modules doesn't exist or is not a directory
      looking for modules in E:\Desktop\实创\carera-back\node_modules
        E:\Desktop\实创\carera-back\node_modules\react-dom doesn't exist
      E:\Desktop\实创\node_modules doesn't exist or is not a directory
      E:\Desktop\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in 'E:\Desktop\实创\carera-back\.cache\admin\src'
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\Compilation.js:2022:28
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:817:13
    at eval (eval at create (E:\Desktop\实创\carera-back\node_modules\.store\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (E:\Desktop\实创\carera-back\node_modules\.store\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:448:22
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:118:11
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:689:25
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:893:8
    at E:\Desktop\实创\carera-back\node_modules\.store\webpack@5.89.0\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in 'E:\Desktop\实创\carera-back\.cache\admin\src'
  Parsed request is a module
  using description file: E:\Desktop\实创\carera-back\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\Desktop\实创\carera-back\.cache\admin\src\node_modules doesn't exist or is not a directory
      E:\Desktop\实创\carera-back\.cache\admin\node_modules doesn't exist or is not a directory
      E:\Desktop\实创\carera-back\.cache\node_modules doesn't exist or is not a directory
      looking for modules in E:\Desktop\实创\carera-back\node_modules
        E:\Desktop\实创\carera-back\node_modules\react-dom doesn't exist
      E:\Desktop\实创\node_modules doesn't exist or is not a directory
      E:\Desktop\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
```

**Comment by gu-stav** [comment]
This should be fixed by https://github.com/strapi/strapi/pull/18658
