### ISSUE TITLE
loadUserPluginsFile tries to evaluate function without required parameter

### ISSUE THREAD

**Issue by dzsibi** [strapi/strapi#18649]
### Required System information

- Node.js version: v18.17.1
- NPM version: 10.2.2
- Strapi version: 4.15.1
- Database: sqlite
- Operating system: linux-x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I have a plugins.js file in my config directory that exports a function:

```javascript
module.exports = ({ env }) => {
  ...
};
```

This is in line with the documentation:

https://docs.strapi.io/dev-docs/configurations/plugins

When I build the project, however, I receive the following error:

```
TypeError: Cannot destructure property 'env' of 'undefined' as it is undefined.
    at module.exports (<REDACTED>/config/plugins.js:74:21)
    at loadUserPluginsFile (<REDACTED>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:759:49)
    at async getEnabledPlugins (<REDACTED>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:736:27)
    at async createBuildContext (<REDACTED>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:811:19)
    at async Object.build (<REDACTED>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:901:15)
    at async build (<REDACTED>/node_modules/@strapi/admin/dist/_chunks/build-f36bfc97.js:56:5)
    at async Command.parseAsync (<REDACTED>/node_modules/commander/lib/command.js:923:5)
    at async Module.runStrapiCommand (<REDACTED>/node_modules/@strapi/strapi/dist/commands/index.js:124:3)
```

As far as I can see this is due to [loadUserPluginsFile](https://github.com/strapi/strapi/blob/d482633e774699cc8d4e05531deaeb6001e791cd/packages/core/admin/_internal/node/core/plugins.ts#L131C21-L131C21) trying to execute the exported function without an argument:

```javascript
const PLUGIN_CONFIGS = ["plugins.js", "plugins.mjs", "plugins.ts"];
const loadUserPluginsFile = async (root) => {
  for (const file of PLUGIN_CONFIGS) {
    const filePath = path__default.default.join(root, file);
    const configFile = await loadFile(filePath);
    if (configFile) {
      return typeof configFile === "function" ? configFile() : configFile;
    }
  }
  return {};
};
```

### Steps to reproduce the behavior

1. Create a config/plugins.js file that exports a function
2. Run strapi build

(To reproduce the exact error, the function exported by plugins.js needs to destructure the parameter like in the documentation.)

### Expected behavior

There should be no error.

**Comment by fmann** [comment]
I just experienced the same error while upgrading from 4.13.1 to 4.15.1.

Node.js version: v18.16.0
NPM version: 9.5.1
Strapi version: 4.15.1
Database: mysql
Operating system: Mac OS (Sonoma) ARM
Is your project Javascript or Typescript: Typescript

```
TypeError: Cannot destructure property 'env' of 'undefined' as it is undefined.
  at module.exports (/www/strapi/config/plugins.ts:1:21)
  at loadUserPluginsFile (/www/strapi/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:759:49)
  at async getEnabledPlugins (/www/strapi/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:736:27)
  at async createBuildContext (/www/strapi/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:811:19)
  at async Object.build (/www/strapi/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:901:15)
  at async build (/www/strapi/node_modules/@strapi/admin/dist/_chunks/build-f36bfc97.js:56:5)
  at async Command.parseAsync (/www/strapi/node_modules/commander/lib/command.js:923:5)
  at async Module.runStrapiCommand (/www/strapi/node_modules/@strapi/strapi/dist/commands/index.js:124:3)
```

My `plugins.js`: 
```js
module.exports = ({ env }) => ({
  "import-export-entries": {
    enabled: true,
    config: {
    },
  },
});
```

**Comment by joshuaellis** [comment]
I assume env is was supposed to be "development" or "production"? Can anyone confirm.

A temp workaround would be to remove that object in the function if you don't need it. If you do and "env" is just a string, you could probably use NODE_ENV 🙂

**Comment by dzsibi** [comment]
`env` is actually a function:

https://github.com/strapi/strapi/blob/d482633e774699cc8d4e05531deaeb6001e791cd/packages/core/strapi/src/core/loaders/plugins/index.ts#L68

If you don't use it, then you should be able to simply switch to an inline object and be done with it as a workaround.

**Comment by derrickmehaffy** [comment]
> I assume env is was supposed to be "development" or "production"? Can anyone confirm.
> 
> A temp workaround would be to remove that object in the function if you don't need it. If you do and "env" is just a string, you could probably use NODE_ENV 🙂

It's a function used to cast environment variables: https://docs.strapi.io/dev-docs/configurations/guides/access-cast-environment-variables

**Comment by derrickmehaffy** [comment]
FYI @joshuaellis workaround won't work here as that is extremely common in order to load environment variables with a fallback, an actual workaround is to use process.env but that could be a lot of changes to workaround.

**Comment by derrickmehaffy** [comment]
Here is a workaround for now for those who want to use 4.15.1 and the proper env() function:

```js
const { env } = require("@strapi/utils");

module.exports = (/*{ env } */) => ({
  // ...
  "users-permissions": {
    config: {
      jwt: {
        expiresIn: env('JWT_EXPIRES_IN', '7d'),
      },
    },
  },
  // ...
});
```

**Comment by derrickmehaffy** [comment]
Looks like the issue is during the dynamic admin build, not the core strapi backend

**Comment by LucaNerlich** [comment]
This even happend to me after downgrading again. For some reason strapi really needs to have the node_modules, cache etc cleaned very often ...

**Comment by itlackey** [comment]
It has broken my deployment pipeline too. I am unable to update my site until this is resolved.

**Comment by riesemann** [comment]
> It has broken my deployment pipeline too. I am unable to update my site until this is resolved.

same here

**Comment by AkshayBhimani** [comment]
> Here is a workaround for now for those who want to use 4.15.1 and the proper env() function:
> 
> ```js
> const { env } = require("@strapi/utils");
> 
> module.exports = (/*{ env } */) => ({
>   // ...
>   "users-permissions": {
>     config: {
>       jwt: {
>         expiresIn: env('JWT_EXPIRES_IN', '7d'),
>       },
>     },
>   },
>   // ...
> });
> ```

Given workaround is giving following error 

`TypeError: webpack.EnvironmentPlugin is not a constructor`
```
TypeError: webpack.EnvironmentPlugin is not a constructor                                                 
    at module.exports(<path>/src/admin/webpack.config.js: 7: 23)                                           
    at mergeConfigWithUserConfig (<path>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:627:12)
    at async watch (<path>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:927:23)              
    at async Object.develop (<path>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:1053:5)     
    at async develop (<path>/node_modules/@strapi/admin/dist/_chunks/develop-513c9644.js:50:5)            
    at async Command.parseAsync (<path>/node_modules/commander/lib/command.js:923:5)                       
    at async Module.runStrapiCommand (<path>/node_modules/@strapi/strapi/dist/commands/index.js:124:3)
    ```

**Comment by LucaNerlich** [comment]
@AkshayBhimani 

Please see my comment here: https://github.com/strapi/strapi/issues/18656#issuecomment-1791944924
There seems to be another, similar regression.

**Comment by AkshayBhimani** [comment]
> @AkshayBhimani
> 
> Please see my comment here: [#18656 (comment)](https://github.com/strapi/strapi/issues/18656#issuecomment-1791944924) There seems to be another, similar regression.

Doesn't seems to be related @LucaNerlich . Can you give me more insight if that is the case?
