### ISSUE TITLE
v4.15.1 build error - not passing env object to plugin config file

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#18662]
### Required System information

- Node.js version: v20.9.0 (LTS)
- NPM version: yarn v4
- Strapi version: 4.15.1
- Database: n.a.
- Operating system: Ubuntu 22.04 (not relevant also in node docker v20)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

```sh
$ yarn install --immutable
$ yarn build
✔ Compiling TS (10524.976006999612ms)
⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                       │
│   TypeError: Cannot destructure property 'env' of 'undefined' as it is undefined.                                                                     │
│       at plugins_default (<my-path>/config/plugins.ts:3:19)                                                      │
│       at loadUserPluginsFile (<my-path>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:759:49)        │
│       at async getEnabledPlugins (<my-path>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:736:27)    │
│       at async createBuildContext (<my-path>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:811:19)   │
│       at async Object.build (<my-path>/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js:901:15)         │
│       at async build (<my-path>/node_modules/@strapi/admin/dist/_chunks/build-f36bfc97.js:56:5)                  │
│       at async Command.parseAsync (<my-path>/node_modules/commander/lib/command.js:923:5)                        │
│       at async Module.runStrapiCommand (<my-path>/node_modules/@strapi/strapi/dist/commands/index.js:124:3)      │
│                                                                                                                                                       │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

My plugin configuration file

```js
export default ({ env }) => ({
...
// somewhere
//  env('MY_ENV_VARIABLE')
})
```

### Steps to reproduce the behavior

See above

### Expected behavior

Works fine for v4.15.0

```sh
$ yarn add @strapi/strapi@4.15.0
....
$ yarn build
Building your admin UI with development configuration...

✔ Webpack
  Compiled successfully in 38.23s
```

Did not find any breaking changes in the release notes so I expect this to keep working.

**Comment by sjoukedv** [comment]
Related to the refactoring of the build pipeline? https://github.com/strapi/strapi/pull/18539

**Comment by broksonic21** [comment]
We are running into this as well. Definitely a new issue.

**Comment by joshuaellis** [comment]
closed by #18657

**Comment by sjoukedv** [comment]
@joshuaellis thanks! Is there also a simple `strapi build` in continuous integration? If not, can we add this also to avoid future issues like this? My project has nothing special but only uses `({env})` for the plugin parameters.

**Comment by broksonic21** [comment]
+1 to @sjoukedv comment re a `strapi build` as a CI test. That's what we do on our usage side as a confirmation (and what caused us to run into this breaking change, but that's a different issue: https://github.com/strapi/strapi/issues/18666 )

**Comment by alexandrebodin** [comment]
Thanks for the suggestion. We do build strapi multiple times in CI. But the plugins.js field doesn't exist by default as it's something you only add when using plugins :) We will definitely have to add a case with some custom plugin config 👍
