### ISSUE TITLE
How to downgrade strapi from 4.15.0 to 4.14.0 

### ISSUE THREAD

**Issue by kennethcagoco** [strapi/strapi#18677]
A white screen appears, when I click “Add a component” in a Dynamic zone. 

this is the error from the console: 

main.f84563f1.js:738 TypeError: Cannot read properties of undefined (reading 'length')
    at Aa (content-type-builder.0bc97051.chunk.js:131:5319)
    at Ss (main.f84563f1.js:736:20469)
    at fh (main.f84563f1.js:738:45155)
    at lh (main.f84563f1.js:738:40774)
    at ip (main.f84563f1.js:738:40702)
    at $f (main.f84563f1.js:738:40556)
    at Gu (main.f84563f1.js:738:36811)
    at xd (main.f84563f1.js:738:37616)
    at za (main.f84563f1.js:736:3278)
    at main.f84563f1.js:738:35128
vl @ main.f84563f1.js:738
main.f84563f1.js:736 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Aa (content-type-builder.0bc97051.chunk.js:131:5319)
    at Ss (main.f84563f1.js:736:20469)
    at fh (main.f84563f1.js:738:45155)
    at lh (main.f84563f1.js:738:40774)
    at ip (main.f84563f1.js:738:40702)
    at $f (main.f84563f1.js:738:40556)
    at Gu (main.f84563f1.js:738:36811)
    at xd (main.f84563f1.js:738:37616)
    at za (main.f84563f1.js:736:3278)
    at main.f84563f1.js:738:35128

and it seems that it only works if you downgrade it
i was talking from this strapi forum.

https://forum.strapi.io/t/error-when-clicking-on-add-a-component-in-dynamic-zone-typeerror-cannot-read-properties-of-undefined-reading-length/33211

**Comment by Eventyret** [comment]
The version you want to try is [4.14.6](https://github.com/strapi/strapi/releases/tag/v4.14.6)
You can change package.json and make sure you delete, `node_modules` `build` and `cache` then `yarn install` or `npm install` again and the version should change.
