### ISSUE TITLE
Node 20 url.parse deprecated

### ISSUE THREAD

**Issue by broksonic21** [strapi/strapi#18685]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 4.15.0
Node/Yarn Version: npm/10.2.3 node/v20.9.0 darwin arm64 workspaces/false
Edition: Community
Database: sqlite

### Describe the bug

`npm run dev` shows a deprecation warning in the logs on some URLs:

Example URL:

`http://localhost:4002/admin/content-manager/collectionType/api::page.page?page=1&pageSize=10&sort=slug:ASC`

Gets this warning:

`(node:62111) [DEP0170] DeprecationWarning: The URL api::page.page?page=1&pageSize=10&sort=slug:ASC is invalid. Future versions of Node.js will throw an error.`

### Steps to reproduce the behavior

1. Launch Strapi in `npm run dev` mode while using Node 20
2. click on list view for any content type
3. sort by something
4. grab URL from address bar, copy/paste into browser again, hit enter (on Chrome at least)
5. see error/warning

Note: I only get this once per server process, and only when putting into URL in address bar -> not when just clicking around

Happens on any content type

### Expected behavior

No warnings/logs

**Comment by derrickmehaffy** [comment]
This doesn't make any sense, could be something with node and koa?

**Comment by rktyt** [comment]
This is due to the fact that `url.parse` is being used somewhere.

Just for reference, `parseurl` is used in `koa` and `url.parse` is used within `parseurl`.
https://github.com/koajs/koa/blob/2.13.4/lib/request.js#L13

Note that this is probably not the only place where `url.parse` is used.

**Comment by termiagithub** [comment]
I have the same issue
![image](https://github.com/strapi/strapi/assets/116946832/ca726b00-1ff4-4ae8-a92e-3ad347ae6fc6)

**Comment by MikalaiLappo** [comment]
Same problem. I had to switch to 18.18.2 Node version to make it work

**Comment by imaksp** [comment]
Hi all, just created an issue in parseurl repo for this, based on their response someone should create an issue with koa too.

**Comment by Sfolkerts89** [comment]
Still an active issue with a fresh up to date Strapi install:

```
(node:29108) [DEP0170] DeprecationWarning: The URL api::home-page.home-page is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by iantrudell** [comment]
Same issue here:
```
2024-07-08T19:59:52.710459032Z (node:3456) [DEP0170] DeprecationWarning: The URL api::alfred-industry.alfred-industry is invalid. Future versions of Node.js will throw an error.
```

**Comment by syharona** [comment]
Same issue : 
```
(node:31978) [DEP0170] DeprecationWarning: The URL api::wishlist.wishlist is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)``
```

**Comment by victoRomano** [comment]
same issue: any news ?
```
(node:19260) [DEP0170] DeprecationWarning: The URL api::layout.layout is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Decryptu** [comment]
Similar issue on Strapi 5.11.3 with Node 20.19.0

```js
/home/user/.pm2/logs/strapi-app-prod-error.log last 15 lines:
0|strapi-a | (node:249778) [DEP0170] DeprecationWarning: The URL api::author.author?page=1&pageSize=10&sort=name:ASC is invalid. Future versions of Node.js will throw an error.
0|strapi-a | (Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by gregauger** [comment]
I've just observed this in Strapi v5.33. (Decryptu above also observes the issue in v5.)

@oiorain @derrickmehaffy You marked this as being v4, but it actually applies to latest v5 too. Please can you reopen and amend the labels?

**Comment by unrevised6419** [comment]
While I was looking through logs, right in front of my eyes 😄 

```
 ┌────────────────────┬──────────────────────────────────────────────────┐
 │ Time               │ Thu Jul 23 2026 08:47:24 GMT+0000 (Coordinated … │
 │ Launched in        │ 4927 ms                                          │
 │ Environment        │ production                                       │
 │ Process PID        │ 533580                                           │
 │ Version            │ 5.31.2 (node v22.15.0)                           │
 │ Edition            │ Community                                        │
 │ Database           │ postgres                                         │
 │ Database name      │ arya                                             │
 │ Database schema    │ public                                           │
 └────────────────────┴──────────────────────────────────────────────────┘
```

```
 (node:534089) [DEP0170] DeprecationWarning: The URL api::reservation.reservation?page=1&pageSize=10&sort=guest_name%3AASC is invalid. Future versions of Node.js will throw an error.
     at getHostname (node:url:517:17)
     at Url.parse (node:url:385:14)
     at urlParse (node:url:142:13)
     at fastparse (/app/arya/node_modules/parseurl/index.js:97:12)
     at parseurl (/app/arya/node_modules/parseurl/index.js:51:12)
     at get path (/app/arya/node_modules/@strapi/core/node_modules/koa/lib/request.js:145:12)
     at Object.path (/app/arya/node_modules/delegates/index.js:72:24)
     at serve (/app/arya/node_modules/koa-static/index.js:44:38)
     at /app/arya/node_modules/@strapi/admin/dist/server/server/src/routes/serve-admin-panel.js:55:15
     at dispatch (/app/arya/node_modules/koa-compose/index.js:42:32)
```
