### ISSUE TITLE
Error with super simple install from site steps

### ISSUE THREAD

**Issue by flashfoxter** [strapi/strapi#1868]
node -v v10.9.0

npm -v 6.2.0

3.0.0-alpha.14

**Informations**
- node -v v10.9.0
- npm -v 6.2.0
- 3.0.0-alpha.14
- ?
- **Operating system**:
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102

**What is the current behavior?**
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/strapi/bin/strapi-install.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Steps to reproduce the problem**
npm install strapi@alpha -g
strapi new my-project

**What is the expected behavior?**
minimal working example from you site

**Suggested solutions**
try to reproduce and try to understand why error happens with text: Cannot find module 'fs-extra'

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
