### ISSUE TITLE
Can't published localized entry after duplicating

### ISSUE THREAD

**Issue by OlfaKaroui** [strapi/strapi#18703]
## Bug report
error: INSERT INTO articles_localizations_links (article_id, inv_article_id) VALUES (1, undefined),(1, 2) - Unknown column 'undefined' in 'field list'
Error: INSERT INTO articles_localizations_links (article_id, inv_article_id) VALUES (1, undefined),(1, 2) - Unknown column 'undefined' in 'field list'
    at Packet.asError (node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
### Required System information

- Node.js version: v20.8.0
- NPM version: 10.1.0
- YARN version: 10.1.0
- Strapi version: 4.15.0
- Database: mysql2
- OS: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have an article with a relation to a Tag entity. I am currently migrating to support multiple locales, while creating an article in the second locale I get this error. The article gets saved despite having some warnings (empty fields which aren't empty), but on publish this error happens.
Note that I have other localised entities which work just fine, this error only happens for this specific contentType.

### Expected behavior

`INSERT INTO articles_localizations_links (article_id, inv_article_id) VALUES (1, 2),(2, 1)`

### Screenshots
Example of warnings that happen on save
<img width="378" alt="Screenshot 2023-11-08 at 15 53 13" src="https://github.com/strapi/strapi/assets/36195894/6e24d90c-4f76-4b3e-adf4-b6ae0595684c">
Articles gets saved anyway regardless of warning
<img width="548" alt="Screenshot 2023-11-08 at 15 54 50" src="https://github.com/strapi/strapi/assets/36195894/233e31b2-c7e8-4468-973c-691744b589bc">
Then on publish the error above occurs

### Code snippets

Article collection type:

```
{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "singularName": "article",
    "pluralName": "articles",
    "displayName": "Article",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "versions": {
      "versioned": true
    },
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "banner": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images"
      ],
      "pluginOptions": {}
    },
    "body": {
      "type": "blocks",
      "required": true,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "tags": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::tag.tag",
      "mappedBy": "articles"
    }
  }
}
```

Tag collection type:

```
{
  "kind": "collectionType",
  "collectionName": "tags",
  "info": {
    "singularName": "tag",
    "pluralName": "tags",
    "displayName": "Tag",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "description": {
      "type": "text",
      "private": true,
      "pluginOptions": {}
    },
    "articles": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::article.article",
      "private": true,
      "inversedBy": "tags"
    }
  }
}
```

**Comment by OlfaKaroui** [comment]
More info: I just tested publishing from the article list view, article was published without any issues. It seems like this error happens only within the Edit screen publish button ? 
<img width="941" alt="Screenshot 2023-11-08 at 15 59 22" src="https://github.com/strapi/strapi/assets/36195894/f9b532f9-54dd-4811-9cb6-90d2a70ca80e">

**Comment by Marc-Roig** [comment]
Hello! Indeed there seems to be an issue with duplicating and i18n, I am taking a look now
