### ISSUE TITLE
Can't install Strapi@4.15.2 with --quickstart flag using npm due to peerDep values

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#18706]
- Node.js version: 18.18.1
- NPM version: 9.8.1
- Strapi version: create-strapi-app@4.15.2
- Database: sqlite (by default)
- Operating system: MacOS Sonoma 14.1
- Is your project Javascript or Typescript: didn't come to this step

```

➜  npx create-strapi-app@latest strapi-sqlite --quickstart
Need to install the following packages:
create-strapi-app@4.15.2
Ok to proceed? (y) y
Creating a quickstart project.
Creating a new Strapi application at /Users/teine/Development/happyhour-media-docker/strapi-sqlite.
Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: strapi-sqlite@0.1.0
npm ERR! Found: @strapi/strapi@4.15.2
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"4.15.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@4.15.2
npm ERR! node_modules/@strapi/plugin-users-permissions
npm ERR!   @strapi/plugin-users-permissions@"4.15.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/teine/.npm/_logs/2023-11-08T16_08_19_784Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/teine/.npm/_logs/2023-11-08T16_08_19_784Z-debug-0.log
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /Users/teine/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/Users/teine/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
    at createProject (/Users/teine/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createQuickStartProject (/Users/teine/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:18:3)
➜  happyhour-media-docker git:(master) ✗ 

```

**Comment by julesrenaud** [comment]
You actually can't run `npm install` at all unless you use the --legacy-peer-deps flag

**Comment by coderdix24** [comment]
dealing with same issue

**Comment by doug-stewart** [comment]
I don't believe this is explicitly related to quickstart. I updated a pre-existing repo top `4.15.2` and started getting this error when running `npm i`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: amt-callisto-protocol-web-strapi@0.1.1
npm ERR! Found: @strapi/strapi@4.15.2
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"^4.15.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@4.15.2
npm ERR! node_modules/@strapi/plugin-users-permissions
npm ERR!   @strapi/plugin-users-permissions@"^4.15.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! <redacted>/2023-11-08T18_47_02_805Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: <redacted>
```

Setting my version explicitly to `4.15.0` seems to have solved the issue for now.

**Comment by joshuaellis** [comment]
I'm gonna lock this, we know the issue, there's a peerDep mistake in a package. We will fix it for the next release. The workaround would be to use the legacy peer does argument as suggested above.

Thank you all for highlighting this 🙂

**Comment by derrickmehaffy** [comment]
While there is a workaround I'm raising this to medium as normally it would be high because it impacts new project creation and new users may not see this GitHub issue.

**Comment by joshuaellis** [comment]
Sure, it will be fixed Monday anyway. I ran out of time today unfortunately.

**Comment by alexandrebodin** [comment]
Hello 👋  We just release 4.15.4 that fixes this issue. If you encounter anything else similar in the upcoming days let us know 🙏
