### ISSUE TITLE
Package subpath './server/utils' is not defined by "exports" for @strapi/plugin-users-permissions@4.15.2

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#18729]
### Required System information

- Node.js version: 20.9.0 (lts)
- Yarn version: v4
- Strapi version: 4.15.2
- Database: Postgres v14
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

```
$ yarn build
[WARN] Declared version of react-router-dom (6.0.0) is not compatible with the version required by Strapi (^5.2.0).
You may experience issues, we recommend you change this.
[WARN] Declared version of react-router-dom (6.18.0) is not compatible with the version required by Strapi (^5.2.0).
You may experience issues, we recommend you change this.
[WARN] Declared version of styled-components (6.0.0) is not compatible with the version required by Strapi (^5.2.1).
You may experience issues, we recommend you change this.
[WARN] Declared version of styled-components (6.1.1) is not compatible with the version required by Strapi (^5.2.1).
You may experience issues, we recommend you change this.
✔ Compiling TS (9642.822272000834ms)
⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (428.98182700015604ms)
⠋ Building admin panel
✔ Building admin panel (33652.36962599866ms)

$ yarn start
[2023-11-10 09:26:19.273] debug: ⛔️ Server wasn't able to start properly.
[2023-11-10 09:26:19.274] error: Package subpath './server/utils' is not defined by "exports" in <my-repo>/node_modules/@strapi/plugin-users-permissions/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server/utils' is not defined by "exports" in <my-repo>/node_modules/@strapi/plugin-users-permissions/package.json
    at new NodeError (node:internal/errors:406:5)
    at exportsNotFound (node:internal/modules/esm/resolve:268:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:598:9)
    at resolveExports (node:internal/modules/cjs/loader:547:36)
    at Module._findPath (node:internal/modules/cjs/loader:621:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (<my-repo>/dist/src/extensions/users-permissions/strapi-server.js:11:24)
```

Works fine for `4.14.6` of `@strapi/plugin-users-permissions`

Also does not work when trying to generate the types:

```
$ yarn strapi ts:generate-types
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server/utils' is not defined by "exports" in <my-repo>/node_modules/@strapi/plugin-users-permissions/package.json
    at new NodeError (node:internal/errors:406:5)
    at exportsNotFound (node:internal/modules/esm/resolve:268:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:598:9)
    at resolveExports (node:internal/modules/cjs/loader:547:36)
    at Module._findPath (node:internal/modules/cjs/loader:621:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (<my-repo>/dist/src/extensions/users-permissions/strapi-server.js:11:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
### Code snippets

`tsconfig.json`
```json
{
  "extends": "@strapi/typescript-utils/tsconfigs/server",

  "compilerOptions": {
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "lib": ["DOM"]
  },
  "include": ["./", "src/**/*.json"],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    ".cache/",
    ".tmp/",
    "src/admin/",
    "**/*.test.ts",
    "src/plugins/**"
  ]
}

```

**Comment by ventsislavnikolov** [comment]
I have reproducing the bug as well.

Required System information
Node.js version: 20.9.0 (lts)
Strapi version: 4.15.2
Database: Postgres v14
Operating system: Ubuntu 22.04
Is your project Javascript or Typescript: Javascript
Hosting: Railway

```
yarn run v1.22.19

$ strapi start

[2023-11-10 09:15:40.515] debug: ⛔️ Server wasn't able to start properly.

[2023-11-10 09:15:40.516] error: Package subpath './server/controllers/validation/auth' is not defined by "exports" in /app/node_modules/@strapi/plugin-users-permissions/package.json

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server/controllers/validation/auth' is not defined by "exports" in /app/node_modules/@strapi/plugin-users-permissions/package.json

at new NodeError (node:internal/errors:405:5)

at exportsNotFound (node:internal/modules/esm/resolve:259:10)

at packageExportsResolve (node:internal/modules/esm/resolve:589:9)

at resolveExports (node:internal/modules/cjs/loader:547:36)

at Module._findPath (node:internal/modules/cjs/loader:621:31)

at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)

at Module._load (node:internal/modules/cjs/loader:901:27)

at Module.require (node:internal/modules/cjs/loader:1115:19)

at require (node:internal/modules/helpers:130:18)

at Object.<anonymous> (/app/src/extensions/users-permissions/strapi-server.js:7:5)
```


strapi-server.js is changes on my back end.

Reverting back to "@strapi/plugin-users-permissions": "4.15.1" fixing the problem.

**Comment by coderdix24** [comment]
I'm having this issue as well 

Node.js version: v18.18.2
Strapi version: 4.15.4
Database: Postgres v14
Operating system: Debian GNU/Linux 10 (buster)
Is your project Javascript or Typescript: Javascript
Hosting: Render

```
Package subpath './server/utils' is not defined by "exports" in ../node_modules/@strapi/plugin-users-permissions/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server/utils' is not defined by "exports" in ../node_modules/@strapi/plugin-users-permissions/package.json
at new NodeError (node:internal/errors:405:5)
at exportsNotFound (node:internal/modules/esm/resolve:362:10)
at packageExportsResolve (node:internal/modules/esm/resolve:698:9)
at resolveExports (node:internal/modules/cjs/loader:567:36)
at Module._findPath (node:internal/modules/cjs/loader:636:31)
at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
at Module._load (node:internal/modules/cjs/loader:922:27)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/opt/render/project/src/api/src/extensions/users-permissions/strapi-server.js:6:24)

```

**Comment by sjoukedv** [comment]
Looks like the module resolution changed as `@strapi/plugin-users-permissions/server/utils` still contains


```javascript
'use strict';

const sanitize = require('./sanitize');

const getService = (name) => {
  return strapi.plugin('users-permissions').service(name);
};

module.exports = {
  getService,
  sanitize,
};

```

Does this have anything do with it being inside the `extensions` directory?

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/18771

**Comment by jerodfritz** [comment]
I was using getService in a custom auth module and it threw this error.  

```
const { getService } = require("@strapi/plugin-users-permissions/server/utils");
```

fwiw, I just removed the reliance on the require and changed my code to the following and all is well again

```
const getService = (name) => {
  return strapi.plugin("users-permissions").service(name);
};
```

**Comment by ArtKuz** [comment]
Help me

Before I use in `src/extensions/users-permissions/strapi-server.ts`

```
import { validateForgotPasswordBody } from "@strapi/plugin-users-permissions/server/controllers/validation/auth";

...
plugin.controllers.auth.forgotPassword = async (ctx) => {
    const { email } = await validateForgotPasswordBody(ctx.request.body);
    ...
```

Now I can error  
<img width="1682" alt="Снимок экрана 2024-06-08 в 20 49 39" src="https://github.com/strapi/strapi/assets/1880304/73eac617-ace2-4451-847b-a8ce908faf79">

How i can fix it?
