### ISSUE TITLE
@strapi/plugin-users-permissions@4.15.2 does not pass error to api response

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#18734]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10 (yarn v4)
- Strapi version: 4.15.2
- Database: Postgres v14
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Calling an endpoint of the user-permissions plugin e.g. `http://localhost:1337/api/auth/email-confirmation?confirmation=fake-token` and observe the logs:

```sh
[2023-11-10 11:29:29.173] error: Invalid token
ValidationError: Invalid token
    at Object.emailConfirmation (<my-repo>/node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:408:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async returnBodyMiddleware (<my-repo>/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
    at async policiesMiddleware (<my-repo>/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
    at async <my-repo>/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
    at async serve (<my-repo>/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (<my-repo>/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
    at async policiesMiddleware (<my-repo>/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
    at async <my-repo>/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
    at async <my-repo>/dist/src/index.js:243:17
```

and the response body

```json
{"data":null,"error":{"status":500,"name":"InternalServerError","message":"Internal Server Error"}}
```

### Expected behavior

Pass the error on to the client as described in https://docs.strapi.io/dev-docs/error-handling, e.g.

```json
{
  "data": null,
  "error": {
    "status": "", // HTTP status
    "name": "", // Strapi error name ('ApplicationError' or 'ValidationError')
    "message": "", // A human readable error message
    "details": {
      // error info specific to the error type
    }
  }
}
```

in this case `error.message` should be `Invalid token`

**Comment by sjoukedv** [comment]
We are not seeing this anymore with `v4.15.5`

```sh
curl --location 'https://<url>/api/auth/email-confirmation' \
--header 'confirmation: fake-token'
```

```json
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "confirmation is a required field",
        "details": {
            "errors": [
                {
                    "path": [
                        "confirmation"
                    ],
                    "message": "confirmation is a required field",
                    "name": "ValidationError"
                }
            ]
        }
    }
}
```
