### ISSUE TITLE
Compatibility of the strapi-plugin-slugify

### ISSUE THREAD

**Issue by dmytro-poputnikov** [strapi/strapi#18792]
### Required System information

- Node.js version: 18.12.1
- Yarn version: 1.22.19
- Strapi version: 4.15.4
- Database: postgresql
- Operating system: Windows and Alpine Linux
- Is your project Javascript or Typescript: JS
- Edition: Community

### Describe the bug

I received an error message while executing the yarn develop command.

Could not load js config file /opt/node_modules/strapi-plugin-slugify/strapi-server.js: Package subpath './dist/core-api/controller/transform' is not defined by "exports" in /opt/node_modules/@strapi/strapi/package.json
Error: Could not load js config file /opt/node_modules/strapi-plugin-slugify/strapi-server.js: Package subpath './dist/core-api/controller/transform' is not defined by "exports" in /opt/node_modules/@strapi/strapi/package.json
    at loadJsFile (/opt/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:18:13)
    at Module.loadFile (/opt/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:37:14)
    at Object.loadPlugins (/opt/node_modules/@strapi/strapi/dist/core/loaders/plugins/index.js:90:41)
    at async Strapi.loadPlugins (/opt/node_modules/@strapi/strapi/dist/Strapi.js:304:5)
    at async Promise.all (index 3)
    at async Strapi.register (/opt/node_modules/@strapi/strapi/dist/Strapi.js:334:5)
    at async Strapi.load (/opt/node_modules/@strapi/strapi/dist/Strapi.js:418:5)
    at async Strapi.start (/opt/node_modules/@strapi/strapi/dist/Strapi.js:213:9)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

### Steps to reproduce the behavior

1. yarn create strapi-app my-project --quickstart
2. yarn add strapi-plugin-slugify
3. add plugin config to plugins.js
4. yarn build
5. yarn develop

### Additional context

To solve the problem I have to modify the file:    

node_modules\@strapi\strapi\package.json

and add to exports field:

"./dist/core-api/controller/transform": {
      "types": "./dist/core-api/controller/transform.d.ts",
      "source": "./src/core-api/controller/transform.ts",
      "import": "./dist/core-api/controller/transform.mjs",
      "require": "./dist/core-api/controller/transform.js",
      "default": "./dist/core-api/controller/transform.js"
    },

**Comment by joshuaellis** [comment]
importing source code from our packages was never supported. I would reach out to the repo owner of the plugin.
