### ISSUE TITLE
White screen when accessing advanced settings from the datetime field in the content-type builder

### ISSUE THREAD

**Issue by rerecampos** [strapi/strapi#18899]
### Required System information

- Node.js version: **16.17.1**
- NPM version: **8.15.0** | yarn **1.22.19**
- Strapi version: **4.14.3**
- Edition: **Community**
- Database: **MySQL**
- Operating system: **Windows 11** | win32 x64
- Is your project Javascript or Typescript: **Javascript**

### Describe the bug

I came across this bug when trying to create a new date field, directly through the project's frontend.
Following the sequence described in the "steps to reproduce" or "screenshots" section the error will occur.

### Steps to reproduce the behavior
(In DEVELOP mode)
1. Go to 'Content-Type Builder'
2. Click on '**Any** collection type'
3. Add new 'Date field'
4. Change date type to **'datetime'**
5. Click on 'Advanced Settings'
6. See error

### Expected behavior

What is expected is that I will be able to access the advanced field settings

### Screenshots

1. Content-Type Builder -> X Collection Type -> Add new field -> Date field
![image](https://github.com/strapi/strapi/assets/82174766/64fe5c0a-2a5c-4525-bc5e-e948cd6bcb85)

2. Change date type to 'datetime'
![image](https://github.com/strapi/strapi/assets/82174766/e71fb1b9-a370-4fb6-b44e-b00f9f91de50)

3. Click on "Advanced Settings"
![image](https://github.com/strapi/strapi/assets/82174766/21a988c3-5f60-40ac-bea4-687e0e567b30)

4. The screen will turn white
![image](https://github.com/strapi/strapi/assets/82174766/6cdfb4ac-4a7f-43a4-88ed-c8de77999bd4)

5. Error in browser console
![image](https://github.com/strapi/strapi/assets/82174766/865aef52-9162-4cfe-ba0a-47e24dc782bf)

### Code snippets

```
main.c5cb3c17.js:10643 TypeError: ht?.toDate is not a function
    at main.c5cb3c17.js:11331:2453
    at Ra (main.c5cb3c17.js:10641:20606)
    at Bs (main.c5cb3c17.js:10643:1593)
    at J4 (main.c5cb3c17.js:10643:47478)
    at ch (main.c5cb3c17.js:10643:41048)
    at Nh (main.c5cb3c17.js:10643:40976)
    at pd (main.c5cb3c17.js:10643:40828)
    at pc (main.c5cb3c17.js:10643:37073)
    at Uo (main.c5cb3c17.js:10643:37883)
    at ks (main.c5cb3c17.js:10641:3291)

Uncaught TypeError: ht?.toDate is not a function
    at main.c5cb3c17.js:11331:2453
    at Ra (main.c5cb3c17.js:10641:20606)
    at Bs (main.c5cb3c17.js:10643:1593)
    at J4 (main.c5cb3c17.js:10643:47478)
    at ch (main.c5cb3c17.js:10643:41048)
    at Nh (main.c5cb3c17.js:10643:40976)
    at pd (main.c5cb3c17.js:10643:40828)
    at pc (main.c5cb3c17.js:10643:37073)
    at Uo (main.c5cb3c17.js:10643:37883)
    at ks (main.c5cb3c17.js:10641:3291)
```

**Comment by joshuaellis** [comment]
This was fixed in a more recent version of strapi – you should try `4.15.5-alpha.5` :)
