### ISSUE TITLE
Migrate from Rich text (Markdown) to Rich text (block)

### ISSUE THREAD

**Issue by BorisKamp** [strapi/strapi#18958]
Using the latest Strapi, when I migrate from Rich text (Markdown) to Rich text (block) on localhost by removing a field called `text`, (Markdown) saving, and adding a field `text` (block), this works. However, when I push it to production I get the following error:
```
[2023-11-30 09:51:24.161] error: alter table "public"."components_content_sections_forms_lists" alter column "text" type jsonb using ("text"::jsonb) - invalid input syntax for type json
       error: alter table "public"."components_content_sections_forms_lists" alter column "text" type jsonb using ("text"::jsonb) - invalid input syntax for type json
           at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
           at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
           at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
           at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
           at TLSSocket.emit (node:events:514:28)
           at TLSSocket.emit (node:domain:488:12)
           at addChunk (node:internal/streams/readable:376:12)
           at readableAddChunk (node:internal/streams/readable:349:9)
           at Readable.push (node:internal/streams/readable:286:10)
           at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
=====> End of  container output (.)
```

**Comment by andbalashov** [comment]
This issue seems to be a data format compatibility problem, where existing Markdown data cannot be directly converted to `jsonb`.

#### 1. Add a Temporary JSONB Column
```sql
ALTER TABLE public.components_content_sections_forms_lists ADD COLUMN text_jsonb jsonb;
```

#### 2. Data Migration Script
```javascript
const { Pool } = require('pg');

const pool = new Pool({
  // Your database configuration
});

pool.query('SELECT id, text FROM public.components_content_sections_forms_lists', (error, results) => {
  if (error) {
    throw error;
  }

  results.rows.forEach(row => {
    const jsonbData = { markdown: row.text };
    pool.query('UPDATE public.components_content_sections_forms_lists SET text_jsonb = $1 WHERE id = $2', [jsonbData, row.id], (updateError) => {
      if (updateError) {
        console.error(updateError);
      }
    });
  });
});
```

#### 3. Update Strapi Model
Modify the Strapi model to use the new `text_jsonb` field.

#### 4. Remove Original Column and Rename Temporary Column
After confirming the successful migration and model update:
- Remove the original `text` column:
  ```sql
  ALTER TABLE public.components_content_sections_forms_lists DROP COLUMN text;
  ```
- Rename the `text_jsonb` column back to `text`:
  ```sql
  ALTER TABLE public.components_content_sections_forms_lists RENAME COLUMN text_jsonb TO text;
  ```
