### ISSUE TITLE
package.json (directory description file): Error: No file content

### ISSUE THREAD

**Issue by Prains** [strapi/strapi#19003]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.2.1
- Strapi version: 4.15.5
- Database: sqlite
- Operating system: ubuntu 22.04
- Is your project Javascript or Typescript: javascript

### Describe the bug

Strapi can't start development server after changing the url in /config/server.js . leaves this error:

[ERROR] Module not found: Error: /home/prains/thaliastudio/thaliaserver/package.json (directory description file): Error: No file content
[ERROR]  There seems to be an unexpected error, try again with --debug for more information

### Steps to reproduce the behavior

1. use yarn create strapi-app bug --quickstart
2. register a new admin, close development server
3. change url in /config/server.js
4. rebuild admin panel using npm run build
5. try to start development server using npm run develop

if you use npm run start it will start, but in the browser there's will be console errors

### Expected behavior

expected to start development server on the url mentioned on /config/server.js

**Comment by joshuaellis** [comment]
Can you run with the debug flag and share those complete logs please?

**Comment by Prains** [comment]
> Can you run with the debug flag and share those complete logs please?

![image](https://github.com/strapi/strapi/assets/17417227/8b789a5d-1a89-4899-8ee0-7e3c381fb402)

that's errors on builded version, using npm run start.

```
$ strapi develop --debug
[DEBUG] Loaded package.json: 
 {
  name: 'thaliaserver',
  private: true,
  version: '0.1.0',
  description: 'A Strapi application',
  scripts: {
    develop: 'strapi develop',
    start: 'strapi start',
    build: 'strapi build',
    strapi: 'strapi'
  },
  devDependencies: {},
  dependencies: {
    '@strapi/strapi': '4.15.5',
    '@strapi/plugin-users-permissions': '4.15.5',
    '@strapi/plugin-i18n': '4.15.5',
    '@strapi/plugin-cloud': '4.15.5',
    'better-sqlite3': '8.6.0',
    react: '^18.0.0',
    'react-dom': '^18.0.0',
    'react-router-dom': '5.3.4',
    'styled-components': '5.3.3'
  },
  author: { name: 'A Strapi developer' },
  strapi: { uuid: 'd316d7c4-f425-4b9f-baf5-b353a89f2225' },
  engines: { node: '>=18.0.0 <=20.x.x', npm: '>=6.0.0' },
  license: 'MIT',
  readme: 'ERROR: No README data found!',
  _id: 'thaliaserver@0.1.0'
}
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
[DEBUG] Cleaning dist folder: /home/prains/thaliastudio/thaliaserver/build
[DEBUG] Cleaned dist folder
[DEBUG] Dependencies from user's project 
 {
  '@strapi/strapi': '4.15.5',
  '@strapi/plugin-users-permissions': '4.15.5',
  '@strapi/plugin-i18n': '4.15.5',
  '@strapi/plugin-cloud': '4.15.5',
  'better-sqlite3': '8.6.0',
  react: '^18.0.0',
  'react-dom': '^18.0.0',
  'react-router-dom': '5.3.4',
  'styled-components': '5.3.3'
}
[DEBUG] User's plugins file 
 {}
[DEBUG] Enabled plugins 
 {
  'users-permissions': {
    name: 'users-permissions',
    importName: 'usersPermissions',
    type: 'module',
    modulePath: '@strapi/plugin-users-permissions'
  },
  i18n: {
    name: 'i18n',
    importName: 'i18N',
    type: 'module',
    modulePath: '@strapi/plugin-i18n'
  },
  'strapi-cloud': {
    name: 'strapi-cloud',
    importName: 'strapiCloud',
    type: 'module',
    modulePath: '@strapi/plugin-cloud'
  }
}
[DEBUG] Enabled plugins with FE 
 {
  'users-permissions': {
    name: 'users-permissions',
    importName: 'usersPermissions',
    type: 'module',
    modulePath: '@strapi/plugin-users-permissions'
  },
  i18n: {
    name: 'i18n',
    importName: 'i18N',
    type: 'module',
    modulePath: '@strapi/plugin-i18n'
  },
  'strapi-cloud': {
    name: 'strapi-cloud',
    importName: 'strapiCloud',
    type: 'module',
    modulePath: '@strapi/plugin-cloud'
  }
}
✔ Building build context (29ms)
⠋ Creating admin[DEBUG] Created the runtime directory
[DEBUG] Rendered the HTML
⠙ Creating admin[DEBUG] Wrote the index.html file
[DEBUG] Wrote the app.js file
⠹ Creating admin[DEBUG] Webpack config {
  experiments: { topLevelAwait: true },
  entry: { main: [ './.strapi/client/app.js' ] },
  resolve: {
    alias: {
      '@strapi/design-system$': '/home/prains/thaliastudio/thaliaserver/node_modules/@strapi/design-system',
      '@strapi/helper-plugin$': '/home/prains/thaliastudio/thaliaserver/node_modules/@strapi/helper-plugin',
      '@strapi/icons$': '/home/prains/thaliastudio/thaliaserver/node_modules/@strapi/icons',
      'date-fns$': '/home/prains/thaliastudio/thaliaserver/node_modules/date-fns',
      'formik$': '/home/prains/thaliastudio/thaliaserver/node_modules/formik',
      'history$': '/home/prains/thaliastudio/thaliaserver/node_modules/history',
      'immer$': '/home/prains/thaliastudio/thaliaserver/node_modules/immer',
      'qs$': '/home/prains/thaliastudio/thaliaserver/node_modules/qs',
      'lodash$': '/home/prains/thaliastudio/thaliaserver/node_modules/lodash',
      'react$': '/home/prains/thaliastudio/thaliaserver/node_modules/react',
      'react-dnd$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-dnd',
      'react-dnd-html5-backend$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-dnd-html5-backend',
      'react-dom$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-dom',
      'react-error-boundary$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-error-boundary',
      'react-helmet$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-helmet',
      'react-is$': '/home/prains/thaliastudio/thaliaserver/node_modules/@strapi/admin/node_modules/react-is',
      'react-intl$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-intl',
      'react-query$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-query',
      'react-redux$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-redux',
      'react-router-dom$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-router-dom',
      'react-window$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-window',
      'react-select$': '/home/prains/thaliastudio/thaliaserver/node_modules/react-select',
      'redux$': '/home/prains/thaliastudio/thaliaserver/node_modules/redux',
      'reselect$': '/home/prains/thaliastudio/thaliaserver/node_modules/reselect',
      'styled-components$': '/home/prains/thaliastudio/thaliaserver/node_modules/styled-components',
      'yup$': '/home/prains/thaliastudio/thaliaserver/node_modules/yup'
    },
    extensions: [ '.js', '.jsx', '.react.js', '.ts', '.tsx' ]
  },
  module: {
    rules: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  plugins: [
    HtmlWebpackPlugin { userOptions: [Object], version: 5 },
    DefinePlugin { definitions: [Object] },
    MiniCssExtractPlugin {
      _sortedModulesCache: [WeakMap],
      options: [Object],
      runtimeOptions: [Object]
    }
  ],
  stats: 'errors-only',
  mode: 'production',
  bail: true,
  devtool: false,
  output: {
    path: '/home/prains/thaliastudio/thaliaserver/build',
    publicPath: '/strapi/admin/',
    filename: '[name].[contenthash:8].js',
    chunkFilename: '[name].[contenthash:8].chunk.js'
  },
  optimization: {
    minimize: undefined,
    minimizer: [ [ESBuildMinifyPlugin] ],
    moduleIds: 'deterministic',
    runtimeChunk: true
  }
}
⠸ Creating admin[ERROR] Module not found: Error: /home/prains/thaliastudio/thaliaserver/package.json (directory description file): Error: No file content
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

error: script "develop" exited with code 1 (SIGHUP)
```

this is command with debug logs

**Comment by derrickmehaffy** [comment]
Can you share your server.js file?

**Comment by Prains** [comment]
> Can you share your server.js file?

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'https://thaliastudio.ru/strapi',
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
```

**Comment by derrickmehaffy** [comment]
And if you remove the url key that error doesn't happen? Quite an odd one 🤔

**Comment by Prains** [comment]
> And if you remove the url key that error doesn't happen? Quite an odd one 🤔

this happens even if i remove url key. but starts only when i add url on config and then rebuild admin panel. both builded version with start command and develop is not working. when running start with version created by build i can access welcome screen, but after - console errors. develop build drops when start develop command. tried to reinstall strapi with another npx command, but everything repeats when i add url to server config

**Comment by Prains** [comment]
UPD:

if i start develop server directly from linux terminal, not vscode bash, develop server starts correctly.

![image](https://github.com/strapi/strapi/assets/17417227/278d1c66-5c35-46b9-b33c-8cc1e23099d0)


![image](https://github.com/strapi/strapi/assets/17417227/05f15381-2727-4a1f-bce5-90dd684807f5)


i get welcome screen, but get errors while requesting api

**Comment by Prains** [comment]
reproduced same error on windows 10.

all good until changed url in server.js

when url changed, develop server starts successfully, but cannot be open, get error while requesting api

**Comment by zhefciad** [comment]
just happened to me too, can work on a separate terminal, but not on vscode's terminal. I didnt change anything on the server. Please update.

**Comment by zhefciad** [comment]
Same thing happened to me. This is how I fixed it. 
1. Used NVM and downgraded to node v18.17.0
2. npm rebuild
3. npm install
4. npm run develop

**Comment by Prains** [comment]
> Same thing happened to me. This is how I fixed it.
> 
> 1. Used NVM and downgraded to node v18.17.0
> 2. npm rebuild
> 3. npm install
> 4. npm run develop

thank you very much for your workaround, but i cant downgrade my node version since all my project requires node 20

**Comment by zhefciad** [comment]
> > Same thing happened to me. This is how I fixed it.
> > 
> > 1. Used NVM and downgraded to node v18.17.0
> > 2. npm rebuild
> > 3. npm install
> > 4. npm run develop
> 
> thank you very much for your workaround, but i cant downgrade my node version since all my project requires node 20

Maybe try to downgrade it to the least version of node 20?

**Comment by thaker0503** [comment]
> Same thing happened to me. This is how I fixed it.
> 
> 1. Used NVM and downgraded to node v18.17.0
> 2. npm rebuild
> 3. npm install
> 4. npm run develop

Thanx man this worked for me too

**Comment by denisales** [comment]
> A mesma coisa aconteceu comigo. Foi assim que eu consertei.
> 
> 1. NVM usado e rebaixado para o nó v18.17.0
> 2. conexão npm
> 3. instalação npm
> 4. npm executar desenvolver

Thanx bro, this worked for me!

**Comment by elvisMat** [comment]
> Same thing happened to me. This is how I fixed it.
> 
> 1. Used NVM and downgraded to node v18.17.0
> 2. npm rebuild
> 3. npm install
> 4. npm run develop

I tried this but, it gives an error 
```
✔ Building build context (641ms)
⠋ Creating admin[DEBUG] Created the runtime directory
[DEBUG] Rendered the HTML
⠙ Creating admin[DEBUG] Wrote the index.html file
⠹ Creating admin[DEBUG] Wrote the app.js file
/media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:825
      new webpack.DefinePlugin(
      ^

TypeError: webpack.DefinePlugin is not a constructor
    at resolveBaseConfig (/media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:825:7)
    at async resolveProductionConfig (/media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:883:22)
    at async /media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:953:18

Node.js v18.19.0
```

**Comment by elvisMat** [comment]
> > Same thing happened to me. This is how I fixed it.
> > 
> > 1. Used NVM and downgraded to node v18.17.0
> > 2. npm rebuild
> > 3. npm install
> > 4. npm run develop
> 
> I tried this but, it gives an error
> 
> ```
> ✔ Building build context (641ms)
> ⠋ Creating admin[DEBUG] Created the runtime directory
> [DEBUG] Rendered the HTML
> ⠙ Creating admin[DEBUG] Wrote the index.html file
> ⠹ Creating admin[DEBUG] Wrote the app.js file
> /media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:825
>       new webpack.DefinePlugin(
>       ^
> 
> TypeError: webpack.DefinePlugin is not a constructor
>     at resolveBaseConfig (/media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:825:7)
>     at async resolveProductionConfig (/media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:883:22)
>     at async /media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:953:18
> 
> Node.js v18.19.0
> ```

So my project was in another drive, i simply moved the project to the drive where node and npm are installed. I can now run the project in dev mode.

**Comment by elvisMat** [comment]
> > > Same thing happened to me. This is how I fixed it.
> > > 
> > > 1. Used NVM and downgraded to node v18.17.0
> > > 2. npm rebuild
> > > 3. npm install
> > > 4. npm run develop
> > 
> > 
> > I tried this but, it gives an error
> > ```
> > ✔ Building build context (641ms)
> > ⠋ Creating admin[DEBUG] Created the runtime directory
> > [DEBUG] Rendered the HTML
> > ⠙ Creating admin[DEBUG] Wrote the index.html file
> > ⠹ Creating admin[DEBUG] Wrote the app.js file
> > /media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:825
> >       new webpack.DefinePlugin(
> >       ^
> > 
> > TypeError: webpack.DefinePlugin is not a constructor
> >     at resolveBaseConfig (/media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:825:7)
> >     at async resolveProductionConfig (/media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:883:22)
> >     at async /media/raps/raps/Projects/strapi/tshepo/api/node_modules/@strapi/admin/dist/_chunks/index-1a74fa41.js:953:18
> > 
> > Node.js v18.19.0
> > ```
> 
> So my project was in another drive, i simply moved the project to the drive where node and npm are installed. I can now run the project in dev mode.

Update: I still had the error after re starting my computer. I proceeded to switch between node different versions until one of them allowed me to run the project successfully
