### ISSUE TITLE
babel parser choking on object spread with `Unexpected token: ....`

### ISSUE THREAD

**Issue by robbywashere** [strapi/strapi#1902]
Strange, your readme.md specifies `NodeJS >= 10.x` ?

Again, `NPM >= 6.x` ?

`npm install strapi@alpha -g`
**Informations**
- **Node.js version**: v10.7.0
- **npm version**: 6.1.0
- **Strapi version**: 'alpha'
- **Database**: postgres
- **Operating system**: OS X

**What is the current behavior?**
`strapi start`
```
$>strapi start
[2018-09-05T16:47:15.735Z] warn
⚠️  TABLE `core_store` DOESN'T EXIST

CREATE TABLE "core_store" (
  id SERIAL NOT NULL PRIMARY KEY,
  "key" text,
  "value" text,
  environment text,
  type text,
  tag text
);

ALTER TABLE "core_store" ADD COLUMN "parent" integer, ADD FOREIGN KEY ("parent") REFERENCES "core_store"("id");

1️⃣  EXECUTE THE FOLLOWING SQL QUERY

2️⃣  RESTART YOUR SERVER
```
🤔🤔🤔
`yarn setup`

```
$>npm run setup

> my-project@0.1.0 setup /Users/robby/etc/Playgrounds/my-project
> cd admin && npm run setup
> strapi-admin@3.0.0-alpha.11.2 setup /Users/robby/etc/Playgrounds/my-project/admin
> node ./scripts/setup.js


🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...
🏗  Building...
  0% compiling/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /Users/robby/etc/Playgrounds/my-project/plugins/users-permissions/services/UsersPermissions.js: Unexpected token (34:12)
  32 |             controller,
  33 |             action: action.toLowerCase(),
> 34 |             ...params.permissions[type].controllers[controller][action]
     |             ^
  35 |           }));
  36 |         });
  37 |       });
    at Parser.pp$5.raise (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$3.parseArrowExpression (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:4190:8)
    at Parser.pp$3.parseExprAtom (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3665:21)
    at Parser.pp$3.parseExprSubscripts (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/robby/etc/Playgrounds/my-project/admin/node_modules/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.11.2 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.11.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robby/.npm/_logs/2018-09-05T16_35_06_053Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.11.2 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.11.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robby/.npm/_logs/2018-09-05T16_35_06_318Z-debug.log
error Command failed with exit code 1.
```

**Steps to reproduce the problem**
See above ^^^

**What is the expected behavior?**

To work.

**Suggested solutions**

Upgrade to babel7 and lock down your babel config and plugins correctly

**Comment by lauriejim** [comment]
What is the `alpha` version you use ?

**Comment by derrickmehaffy** [comment]
@robbywashere Yeahhh your running some really old stuff. Can you use the latest strapi version? Also Yarn support is minimal and is not recommended. The Strapi team are still working on that.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
