### ISSUE TITLE
Plugin Color Picker Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by coexJoy** [strapi/strapi#19077]
[Strapi plugin Color Picker](https://market.strapi.io/plugins/@strapi-plugin-color-picker) is breaking `strapi build` and `strapi develop`

- Environment: develop
- OS: darwin-arm64
- Strapi Version: 4.13.2
- Node/Yarn Version: yarn/1.22.19 npm/? node/v18.15.0 darwin arm64
- Edition: Community
- Database: postgres
- Is your project Javascript or Typescript: Typescript

### Describe the bug

`yarn build` is throwing the following error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './strapi-admin.js' is not defined by "exports" in /Users/user/project/node_modules/@strapi/plugin-color-picker/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at /Users/user/project/node_modules/@strapi/admin/utils/create-cache-dir.js:110:55
    at Array.filter (<anonymous>)
    at createCacheDir (/Users/user/project/node_modules/@strapi/admin/utils/create-cache-dir.js:89:6) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce the behavior

1. `nvm use 18.15`
2. `yarn add @strapi/plugin-color-picker`
3. `yarn build`

### Expected behavior

The subpath for `./strapi-admin.js` is exported from `package.json` of the plugin so that it will not crash on later node versions.

**Comment by coexJoy** [comment]
This seems like a node version issue.

Sorry for the trouble. Closing this off.
