### ISSUE TITLE
create-strapi-app --quickstart doesn't work (JSONError)

### ISSUE THREAD

**Issue by KristofKekesi** [strapi/strapi#19132]
### Required System information

- Node.js version: 18.19.0
- NPM version: 10.2.3
- Strapi version: 4.16.2
- Database: SqLite
- Operating system: Macos Sonoma 14.0

### Describe the bug
I ran `npx create-strapi-app cms --quickstart` and the process failed with a JSONError of `Unexpected end of JSON input while parsing empty string`.
```
kristofkekesi@Kristofs-MacBook-Pro csaladihazneked.hu % npx create-strapi-app@latest cms
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms.
Creating files.
Dependencies installed successfully.

Your application was created at /Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms
  yarn develop

Running your Strapi application.

> cms@0.1.0 develop
> strapi develop

⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (71ms)
⠙ Creating admin
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
ErrorEXError [JSONError]: Unexpected end of JSON input while parsing empty string
    at parseJson (/Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms/node_modules/parse-json/index.js:29:21)
    at module.exports (/Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms/node_modules/read-pkg/index.js:17:15)
    at async module.exports [as default] (/Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms/node_modules/read-pkg-up/index.js:14:16)
    at async loadStrapiMonorepo (/Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:743:24)
    at async resolveBaseConfig (/Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:755:20)
    at async resolveProductionConfig (/Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:887:22)
    at async /Users/kristofkekesi/Developer/Web/csaladihazneked.hu/cms/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:957:18

Node.js v18.19.0
```

### Steps to reproduce the behavior
1. run `npx create-strapi-app cms --quickstart`
2. See error

### Expected behavior
Finish initializing Strapi.

**Comment by KristofKekesi** [comment]
As requested I'll upload a zip of a repo with the error. I'll send you the terminal session where I reproduced this error from a fresh start.

```
kristofkekesi@Kristofs-MacBook-Pro new-repo % yarn create strapi-app new-repo  
yarn create v1.22.17
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-strapi-app@4.16.2" with binaries:
      - create-strapi-app
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /Users/kristofkekesi/Developer/new-repo/new-repo.
Creating files.
Dependencies installed successfully.
Initialized a git repository.


Your application was created at /Users/kristofkekesi/Developer/new-repo/new-repo.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /Users/kristofkekesi/Developer/new-repo/new-repo
  yarn develop

Running your Strapi application.

> new-repo@0.1.0 develop
> strapi develop

⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (81ms)
⠙ Creating admin
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
ErrorEXError [JSONError]: Unexpected end of JSON input while parsing empty string
    at parseJson (/Users/kristofkekesi/Developer/new-repo/new-repo/node_modules/parse-json/index.js:29:21)
    at module.exports (/Users/kristofkekesi/Developer/new-repo/new-repo/node_modules/read-pkg/index.js:17:15)
    at async module.exports [as default] (/Users/kristofkekesi/Developer/new-repo/new-repo/node_modules/read-pkg-up/index.js:14:16)
    at async loadStrapiMonorepo (/Users/kristofkekesi/Developer/new-repo/new-repo/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:743:24)
    at async resolveBaseConfig (/Users/kristofkekesi/Developer/new-repo/new-repo/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:755:20)
    at async resolveProductionConfig (/Users/kristofkekesi/Developer/new-repo/new-repo/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:887:22)
    at async /Users/kristofkekesi/Developer/new-repo/new-repo/node_modules/@strapi/admin/dist/_chunks/index-ffd2f664.js:957:18

Node.js v18.19.0
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-strapi-app
Arguments: new-repo
Directory: /Users/kristofkekesi/Developer/new-repo
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
[new-repo.zip](https://github.com/strapi/strapi/files/13815258/new-repo.zip)

**Comment by derrickmehaffy** [comment]
@KristofKekesi I downloaded that zip and tested it, works fine for me:

![image](https://github.com/strapi/strapi/assets/8593673/ba4ce238-e3d5-444a-ae92-369d6bdf7983)

**Comment by KristofKekesi** [comment]
I've managed to make a working strapi project by using yarn instead of npx. Which is weird because it didn't work when I tried it.

Will close this as cannot reproduce.

**Comment by jijojosein** [comment]
Facing the same issue. I will create a separate issue.

**Comment by mamadOuologuem** [comment]
Deleting `.strapi-updater.json` at the root of the project solved it for me.

Hope it helps.
