### ISSUE TITLE
User-permissions unauthorized endpoint ForbiddenError not caught and transformed to 403 response

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#19282]
### Required System information

- Node.js version: v20
- Strapi version: 4.17.1
- Database: Postgres v14
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Returning "Internal Server Error" HTTP 500 instead of 403 Unauthorized. This is the stack

```
[2024-01-19 14:01:29.680] error: Forbidden access
ForbiddenError: Forbidden access
    at Object.verify (/app/node_modules/@strapi/plugin-users-permissions/server/strategies/users-permissions.js:115:11)
    at Object.verify (/app/node_modules/@strapi/strapi/src/services/auth/index.ts:133:30)
    at /app/node_modules/@strapi/strapi/src/services/server/compose-endpoint.ts:38:25
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at Object.authenticate (/app/node_modules/@strapi/strapi/src/services/auth/index.ts:116:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /app/src/index.ts:264:9
    at /app/node_modules/@strapi/strapi/src/middlewares/body.ts:56:9
    at /app/node_modules/@strapi/strapi/src/middlewares/logger.ts:6:5
    at /app/node_modules/@strapi/strapi/src/middlewares/powered-by.ts:15:5
    at cors (/app/node_modules/@koa/cors/index.js:61:32)
    at /app/node_modules/@strapi/strapi/src/middlewares/errors.ts:9:7
    at session (/app/node_modules/koa-session/index.js:41:7)
```

- Here `authenticate(ctx)` is called - https://github.com/strapi/strapi/blob/develop/packages/core/strapi/src/services/auth/index.ts#L100
- Which refers to this method here for the users-permissions plugin -https://github.com/strapi/strapi/blob/develop/packages/plugins/users-permissions/server/strategies/users-permissions.js#L106

Is there a part of the framework that is not catching these errors anymore?

### Steps to reproduce the behavior

1. Call a collection endpoint which you are unauthorized to

### Expected behavior

To catch the `ForbiddenError` and return HTTP 403

### Code snippets

<details>

<summary>Custom patch to allow 48h before requiring e-mail confirmation</summary>

I don't think this is related to the error, but just in case

```
--- a/server/strategies/users-permissions.js
+++ b/server/strategies/users-permissions.js
@@ -31,7 +31,16 @@ const authenticate = async (ctx) => {
       const advancedSettings = await getAdvancedSettings();
 
       // User not confirmed
-      if (advancedSettings.email_confirmation && !user.confirmed) {
+      const now = new Date();
+      const userCreatedAt = new Date(user.createdAt);
+      const userGracePeriod = new Date(userCreatedAt.setDate(userCreatedAt.getDate() + 2));
+      strapi.log.debug(
+        now > userGracePeriod
+          ? `user has expired e-mail confirm grace period ${user.createdAt} (created), ${userGracePeriod} (grace), ${now} (now)`
+          : `user still has e-mail confirm grace period ${user.createdAt} (created), ${userGracePeriod} (grace), ${now} (now)`
+      );
+      // customized grace period of 2d within creation
+      if (advancedSettings.email_confirmation && !user.confirmed && now > userGracePeriod) {
         return { error: 'Invalid credentials' };
       }
```

</details>

**Comment by dgrebb** [comment]
Speaking of `koa`...

https://github.com/advisories/GHSA-qxrj-hx23-xp82 👀

**Comment by sjoukedv** [comment]
Issues seems to be resoled in `4.19.1`
