### ISSUE TITLE
AWS S3 compatible service upload fail - Region is missing (Cloudflare R2)

### ISSUE THREAD

**Issue by MartinMikita** [strapi/strapi#19299]
### Required System information

- Node.js version: 18.16.1
- NPM version: 9.5.1
- Strapi version: 4.17.0
- Database: postgres
- Operating system: linux-x64 (Alpine Linux 3.18.2 in Docker)
- Is your project Javascript or Typescript: Javascript

```
$ yarn strapi report
Launched In: 817 ms
Environment: development
OS: linux-x64
Strapi Version: 4.17.0
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.16.1 linux x64
Edition: Community
Database: postgres
Done in 2.73s.

```

### Describe the bug

[**README is not updated**](https://market.strapi.io/providers/@strapi-provider-upload-aws-s3) for a new version of the plugin, that `region` is required option for AWS SDK v3

Resolution from the comment - https://github.com/strapi/strapi/issues/18761#issuecomment-1825879871

![image](https://github.com/strapi/strapi/assets/2283182/841865ce-d6f4-4019-9eba-45678fe81a79)

### Steps to reproduce the behavior

1. Go to `config/plugins.js`
2. Write config for `upload` section from README
```
      provider: "aws-s3",
      providerOptions: {
        baseUrl: env("R2_PUBLIC_ACCESS_URL"),
        rootPath: env("R2_PUBLIC_FOLDER", "upload"),
        accessKeyId: env("R2_ACCESS_KEY_ID"),
        secretAccessKey: env("R2_ACCESS_SECRET"),
        endpoint: env("R2_ENDPOINT"),
        params: {
          ACL: "public-read",
          Bucket: env("R2_BUCKET"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
```

4. Go to Media Library of Strapi Admin (`/admin/plugins/upload`)
5. Click on the big blue button **+ Add new assets**
6. Drop any image file from your computer
7. Click on the blue button **Upload 1 asset to the library**
8. Check error logs from `yarn develop` command in terminal
```
[2024-01-22 19:51:01.944] http: GET /upload/folders?sort=createdAt:DESC&page=1&pageSize=50&pagination[pageSize]=-1&filters[$and][0][parent][id][$null]=true (56 ms) 200
/opt/app/node_modules/@smithy/config-resolver/dist-cjs/index.js:117
    throw new Error("Region is missing");
          ^

Error: Region is missing
    at default (/opt/app/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
    at /opt/app/node_modules/@smithy/node-config-provider/dist-cjs/index.js:72:104
    at /opt/app/node_modules/@smithy/property-provider/dist-cjs/index.js:79:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/opt/app/node_modules/@smithy/property-provider/dist-cjs/index.js:106:18)
    at async /opt/app/node_modules/@smithy/property-provider/dist-cjs/index.js:117:20
    at async region (/opt/app/node_modules/@smithy/config-resolver/dist-cjs/index.js:142:30)
    at async /opt/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:6:32
    at async /opt/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
    at async /opt/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26

```

### Expected behavior

Update README to include new required config - `region`, even with `endpoint`

**Comment by chaeyan** [comment]
obviously you need to put the region in provider options..

**Comment by MartinMikita** [comment]
Yes, after adding, it is working, but without that it yells Exception which is not explained in README. Note that this stopped working after update from Strapi 4.12.0

**Comment by claudiobgit** [comment]
In regards of the documentation, it could be improved with examples correctly nesting `s3Options` in `providerOptions` as warned at Strapi startup. Following a working setup (tested on Strapi v4.19.1) of S3 compatible upload on Linode:
```
 upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        s3Options: {
          credentials: {
            accessKeyId: env('LINODE_ACCESS_KEY_ID'),
            secretAccessKey: env('LINODE_ACCESS_SECRET'),
          },
          region: env('LINODE_REGION'),
          endpoint: env('LINODE_ENDPOINT'),
          params: {
          Bucket: env('LINODE_BUCKET'),
          },
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },  
    },
  },
```

**Comment by Eventyret** [comment]
@MartinMikita would this not be a duplicate of this https://github.com/strapi/strapi/issues/18951

**Comment by davidlj95** [comment]
I think this can be closed, was fixed in https://github.com/strapi/strapi/pull/19679

**Comment by TechQuery** [comment]
> obviously you need to put the region in provider options..

@yunylz CloudFlare has no "obvious" region value in its dashboard, so CF users like @MartinMikita & me feel confused about this option: https://developers.cloudflare.com/r2/api/s3/api/#bucket-region

Just set `region: 'auto'`, this error can be fixed.
