### ISSUE TITLE
14.9.0 Vite TypeError: userConfig is not a function  

### ISSUE THREAD

**Issue by jerodfritz** [strapi/strapi#19321]
## Bug report
Trying to use the vite bundler throws an error during development.  Webpack has no errors.
```strapi develop --watch-admin --bundler=vite```

### Required System information
Node v18.18.2
NPM 10.2.5
Strapi v4.19.0
Local developmen using MySQL on Macbook M1

### Describe the bug

The error occurs during -Creating admin step:

```
TypeError: userConfig is not a function
at Object.mergeConfigWithUserConfig (/myproject/node_modules/@strapi/admin/_internal/node/vite/config.ts:104:12)
at watch (/myproject/node_modules/@strapi/admin/_internal/node/vite/watch.ts:15:23)
at async Object.develop (/myproject/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:831:25)
at async develop (/myproject/node_modules/@strapi/admin/dist/_chunks/develop-YNTGWKMC.js:61:5)
at async Command.parseAsync (/myproject/node_modules/commander/lib/command.js:923:5)
at async Module.runStrapiCommand (/myproject/node_modules/@strapi/strapi/dist/commands/index.js:130:3)
```

### Steps to reproduce the behavior
Update all project.json strapi modules to 14.9.0 
Update the stapir develop run command to use the vite bundler with  --bundler=vite

### Expected behavior
Expected to build and render admin same as webpack

Related to [fear: add vite](https://github.com/strapi/strapi/pull/18697)
May be related to this [TypeError: userConfig is not a function](https://github.com/strapi/strapi/issues/18723)

**Comment by jerodfritz** [comment]
I was trying to use a custom vite.config in a custom plugin to mimic a custom webpack.config.  When I removed that this error goes away.  

Any suggestions on how best to alias plugin assets in a plugin like we did with webpack.config:

```
'use strict';
const _ = require('lodash');
const path = require('path');

module.exports = (config, webpack) => {
  _.set(config, 'resolve.alias.assets', path.resolve(__dirname, './assets'));
  config.stats = 'detailed';
  return config;
};
```
