### ISSUE TITLE
GraphQL plugin breaks AdminUI loading plugins on all ORMs

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1938]
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1
- **Database**: 10.2.17-MariaDB
- **Operating system**: Linux Mint 19 // Ubuntu Server 18.04

**What is the current behavior?**

After installing GraphQL plugin the AdminUI will no longer load other plugins, below is a screenshot of a fresh v14.1 project (right) and my upgraded project with graphql installed (left)

![image 1](https://user-images.githubusercontent.com/8593673/45454972-6a556400-b69a-11e8-812f-5d3f1969ca01.png)

After removing the graphql plugin the adminUI loads all the plugins and functions normally.

**Steps to reproduce the problem**

Create a Strapi v14.1 project, start it, create user, confirm adminUI works ~~(with bookshelf)~~

Kill server, install graphql plugin and start (note that the plugins no longer load, login page also isn't shown)

Kill Server and remove graphql plugin, restart to confirm adminUI goes back to normal.

**What is the expected behavior?**

GraphQL should not cause the other plugins to fail.  

**Suggested solutions**

~~issue likely stems from recent additions to graphql for mongoose only, and not for bookshelf. These features likely aren't being disabled and are failing to load properly.~~

**note** will provide more feedback in a few hours when I can work with @soupette to figure this out.

**Comment by TokenChingy** [comment]
Can confirm, it also breaks on Mongoose ORM.

**Comment by DMomplaisirASC** [comment]
It seems that if you refresh the page x amount of times, it functions.  It might be sourced from the multiple instances of the babel-polyfill or something with the strapi-helper-plugin which I cant seem to source.

**Comment by derrickmehaffy** [comment]
@TokenChingy Updated title, also updating issue to reflect all ORMs.

@DMomplaisirASC I noticed the same when using Firefox, on Chrome Beta I couldn't get it load no matter the amount of refreshes. Good to know it isn't just me though, worked with both @lauriejim and @soupette and they couldn't reproduce.

**Comment by DMomplaisirASC** [comment]
@derrickmehaffy I'm on Chrome right now, and I can do it after a random ammount of refreshes (about 6ish).  It seems when you get to a refresh it works but if you try to save content, it automatically white screen and crashes again.

**Comment by derrickmehaffy** [comment]
Example of a test project:

No GraphQL Plugin:

![image](https://user-images.githubusercontent.com/8593673/45476788-bfbe5f00-b6f4-11e8-9751-758adb0c7a1f.png)

Installed GraphQL:

![image](https://user-images.githubusercontent.com/8593673/45476824-d6fd4c80-b6f4-11e8-8b43-43a4064aecad.png)

Removed GraphQL (and a few refreshes):

![image](https://user-images.githubusercontent.com/8593673/45476883-fdbb8300-b6f4-11e8-9dd5-db263c43b1f8.png)

@soupette most definitely is reproducible

**Comment by DMomplaisirASC** [comment]
I'm still having this issue. What should I do?

**Comment by derrickmehaffy** [comment]
@DMomplaisirASC update to Strapi 14.1.1 I confirmed with @lauriejim in testing that 14.1.1 fixes this.

**Comment by ghufr** [comment]
![screenshot from 2018-09-14 15-56-31](https://user-images.githubusercontent.com/20156570/45540967-f650c280-b837-11e8-9926-0cbef0bf2cee.png)
I got 403 error in `/admin/plugins` (production build), is this related to this issue?

**Comment by derrickmehaffy** [comment]
@ghufr that is an unrelated issue, what strapi version. @Aurelsicoko didn't you fix disconnecting the marketplace from projects?

**Comment by Aurelsicoko** [comment]
@derrickmehaffy We removed everything related to the marketplace since alpha@12...

**Comment by derrickmehaffy** [comment]
I thought so @ghufr what version are you running? I think you likely need to update your project...

**Comment by ghufr** [comment]
@derrickmehaffy It's `3.0.0-alpha.14.1`

**Comment by derrickmehaffy** [comment]
@ghufr update to 14.1.1, that is the hotfix for the issue I created this for.

**Comment by tomekkozysa** [comment]
I'm experiencing similar issue with strapi 3.0.0-alpha.16 and MySql (MAMP) plugin install, both GUI and cli, breaks the app. Uninstalling the app fixes the problem.

**Comment by tomekkozysa** [comment]
@derrickmehaffy I've just installed the plugin, and started strapi, here's what I get:



(node:93403) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Expected :, found Name "title"
    at syntaxError (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at expect (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:1463:32)
    at parseFieldDefinition (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:886:3)
    at many (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:1523:16)
    at parseFieldsDefinition (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:873:50)
    at parseObjectTypeDefinition (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:826:16)
    at parseTypeSystemDefinition (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:724:16)
    at parseDefinition (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:150:12)
    at many (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:1523:16)
    at parseDocument (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:113:18)
    at Object.parse (/Users/tk/vue/strapi/s3/plugins/graphql/node_modules/graphql/language/parser.js:48:10)
    at Object.addPolymorphicUnionType (/Users/tk/vue/strapi/s3/plugins/graphql/services/Types.js:153:8)
    at Object.generateSchema (/Users/tk/vue/strapi/s3/plugins/graphql/services/Schema.js:179:15)
    at Function.initialize (/Users/tk/vue/strapi/s3/plugins/graphql/hooks/graphql/index.js:148:50)
    at /Users/tk/vue/strapi/s3/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/Users/tk/vue/strapi/s3/node_modules/strapi/lib/hooks/index.js:122:39)
    at /Users/tk/vue/strapi/s3/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/Users/tk/vue/strapi/s3/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at Strapi.EventEmitter.emit (domain.js:442:20)
    at loadedModule.initialize.call.err (/Users/tk/vue/strapi/s3/node_modules/strapi/lib/hooks/index.js:32:12)
    at Function.initialize (/Users/tk/vue/strapi/s3/node_modules/strapi-hook-bookshelf/lib/index.js:1003:7)
(node:93403) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:93403) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


next is : 
debug ⛔️ Server wasn't able to start properly.
error (hook:graphql) takes too long to load

**Comment by tomekkozysa** [comment]
@derrickmehaffy + sorry, no code. I've been only using strapi for two days (highly possible there is an issue elsewhere)

**Comment by derrickmehaffy** [comment]
@tomekkozysa more than likely you have a typo in one of your model fields:

```
(node:93403) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Expected :, found Name "title"
```

Which ever one contains a field called `title`

**Comment by tomekkozysa** [comment]
@derrickmehaffy  I run a clean install and added the plugin before creating anything else. No problems starting or running strapi!  Thanks for helping me out here!
