### ISSUE TITLE
JS Strapi projects cannot build if they find a tsconfig.json in a parent directory 

### ISSUE THREAD

**Issue by ojeytonwilliams** [strapi/strapi#19395]
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.1.0
- Strapi version: 4.19.1
- Database: sqlite
- Operating system: linux-x64
- Is your project Javascript or Typescript: the Strapi workspace uses JS, the monorepo uses both.

### Describe the bug

Adding a `tsconfig.json` file in a parent directory of JS Strapi app breaks `strapi build` and `strapi develop`.

### Steps to reproduce the behavior

I created a small repo to reproduce the issue https://github.com/ojeytonwilliams/strapi-repro. To test, you can try `npm run develop` with and without the `tsconfig.json`

Alternatively:

1. Create a monorepo with Strapi as a workspace 
2. put a `tsconfig.json` file in a parent directory
3. navigate to your Strapi package
4. `npx strapi develop`
5. See error:

```
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                 │
│   Error: Debug Failure.                                                                                                                         │
│       at /media/external/Code/tmp/strapi-mono/node_modules/typescript/lib/typescript.js:17850:67                                                │
│       at String.replace (<anonymous>)                                                                                                           │
│       at formatStringFromArgs (/media/external/Code/tmp/strapi-mono/node_modules/typescript/lib/typescript.js:17850:17)                         │
│       at createCompilerDiagnostic (/media/external/Code/tmp/strapi-mono/node_modules/typescript/lib/typescript.js:17951:14)                     │
│       at tryReadFile (/media/external/Code/tmp/strapi-mono/node_modules/typescript/lib/typescript.js:36199:30)                                  │
│       at Object.getParsedCommandLineOfConfigFile (/media/external/Code/tmp/strapi-mono/node_modules/typescript/lib/typescript.js:36149:28)      │
│       at module.exports (/media/external/Code/tmp/strapi-mono/node_modules/@strapi/typescript-utils/lib/utils/resolve-config-options.js:9:43)   │
│       at Object.run (/media/external/Code/tmp/strapi-mono/node_modules/@strapi/typescript-utils/lib/compilers/basic.js:21:55)                   │
│       at module.exports (/media/external/Code/tmp/strapi-mono/node_modules/@strapi/typescript-utils/lib/compile.js:9:19)                        │
│       at Object.develop (/media/external/Code/tmp/strapi-mono/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:744:32)                 │
│                                                                                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

`--debug` is helpful, since it tells you that you've "Loaded user TS config", but it's not obvious why that's happened.

### Expected behavior

Ideally `strapi` should catch that error and add some context explaining why it might have happened. I'm not sure what the best wording would be, but something to let people know that this might be the wrong `tsconfig.json`. Also that if the Strapi project is just using JS, that any parent `tsconfig`s will need to be renamed.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by nvitulli71** [comment]
I am seeing this same error on my project as well. I do not have a `tsconfig.json` in my parent directory. 

```
                                                                                                                                                                                          │
│   Error: Debug Failure.                                                                                                                                                                     │
│       at /Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:17850:67                                             │
│       at [Symbol.replace] (<anonymous>)                                                                                                                                                     │
│       at String.replace (<anonymous>)                                                                                                                                                       │
│       at formatStringFromArgs (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:17850:17)                      │
│       at createCompilerDiagnostic (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:17951:14)                  │
│       at tryReadFile (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:36199:30)                               │
│       at Object.getParsedCommandLineOfConfigFile (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:36149:28)   │
│       at module.exports (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/lib/utils/resolve-config-options.js:9:43)                                      │
│       at Object.run (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/lib/compilers/basic.js:21:55)                                                      │
│       at module.exports (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/lib/compile.js:9:19)                                                           │
│                                                                                                                                          
```

**Comment by shiny** [comment]
I encountered this problem too.

**Comment by shiny** [comment]
When I use version 5 beta, this issue no longer occurs.

**Comment by mad-zephyr** [comment]
Some body know how to resolve this problem?

**Comment by nvitulli71** [comment]
> Some body know how to resolve this problem?

Check out the `EDIT` in this comment https://github.com/strapi/strapi/issues/19395#issuecomment-1919741668. You likely have a rouge `tsconfig.js` file somewhere.

**Comment by ramazansancar** [comment]
# Solution to the problem:

It occurs if there is a config named `jsconfig.json` in the parent folder of the project. Dockerization would be the healthiest way to ensure a smooth deployment process.

**Comment by sayalisss7** [comment]
> I am seeing this same error on my project as well. I do not have a `tsconfig.json` in my parent directory.
> 
> ```
>                                                                                                                                                                                           │
> │   Error: Debug Failure.                                                                                                                                                                     │
> │       at /Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:17850:67                                             │
> │       at [Symbol.replace] (<anonymous>)                                                                                                                                                     │
> │       at String.replace (<anonymous>)                                                                                                                                                       │
> │       at formatStringFromArgs (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:17850:17)                      │
> │       at createCompilerDiagnostic (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:17951:14)                  │
> │       at tryReadFile (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:36199:30)                               │
> │       at Object.getParsedCommandLineOfConfigFile (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:36149:28)   │
> │       at module.exports (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/lib/utils/resolve-config-options.js:9:43)                                      │
> │       at Object.run (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/lib/compilers/basic.js:21:55)                                                      │
> │       at module.exports (/Users/user/strapi-app/backend/node_modules/@strapi/typescript-utils/lib/compile.js:9:19)                                                           │
> │                                                                                                                                          
> ```
> 
> EDIT: Come to find out I did end up finding a `tsconfig.json` file that was outside of my repo and once I deleted that it removed the issue.

Yes, after deleting the tsconfig.json file, it worked. The file was located outside the project folder.

**Comment by ramazansancar** [comment]
@derrickmehaffy There seems to be no problem here anymore. It can be closed. An explanation can be written as a solution.
