### ISSUE TITLE
create new project with postgres

### ISSUE THREAD

**Issue by isabolic** [strapi/strapi#1949]
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**:strapi@3.0.0-alpha.14.1.1
- **Database**: postgres
- **Operating system**: windows 10

**What is the current behavior?**
create new project with postgres db connection

**Steps to reproduce the problem**
in terminal run 
```strapi new test-prject --dbclient=postgres --dbhost=localhost --dbport=5432 --dbname=test --dbusername=test --dbpassword=test ```

```
Testing database connection...
{ Error: Cannot find module 'C:\Users\user\AppData\Local\Temp\strapi1580b946367c\node_modules\knex'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (C:\Users\user\AppData\Local\Temp\strapi1580b946367c\node_modules\strapi-hook-bookshelf\lib\utils\connectivity.js:11:17)
    at Promise.all.then (C:\Users\user\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\before.js:259:126)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
The app has been connected to the database successfully!
```

**What is the expected behavior?**
create new project 

**Suggested solutions**
check dependency packages

**Comment by derrickmehaffy** [comment]
There are known issues with Windows, please use WSL or a Linux VM. The Strapi team is working on better Windows support.

**Comment by isabolic** [comment]
@derrickmehaffy thanks for the quick response 👍

**Comment by zhoub** [comment]
![2018-09-14 18_14_17-administrator_ c__windows_system32_cmd exe - strapi new lf-web](https://user-images.githubusercontent.com/1798206/45541462-286b2000-b84a-11e8-90dd-0667e7f0bd0b.png)

I also got this issue for when choosing SQL server

**Comment by derrickmehaffy** [comment]
Same thing, windows support isn't there right now. You will need to use either a linux vm or install WSL and run your project there.

**Comment by lauriejim** [comment]
Related https://github.com/strapi/strapi/issues/1879

**Comment by NickBolles** [comment]
Just to add the link here, should be fixed by #1941

**Comment by karianpour** [comment]
Same issue on Ubunut 16.04

```
🚀 Start creating your Strapi application.

? Choose your installation type Custom (manual settings)
? Choose your main database: Postgres
? Database name: (jack-cms) 
module.js:550
    throw err;
    ^

Error: Cannot find module '/tmp/strapi6986c278628f/node_modules/pg/package.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at shell.exec (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:324:26)
    at /usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/node_modules/shelljs/src/exec.js:204:9
    at ChildProcess.exithandler (child_process.js:288:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
```

`node v8.15.1`
`npm 6.9.0`
 My node is installed via `snap`  on `/snap/node/1738/bin/node`

**Comment by derrickmehaffy** [comment]
@karianpour only node 10 is supported. I would recommend that you purge your snap installed version and follow the following guide to installing node 10 properly on ubuntu: https://github.com/nodesource/distributions/blob/master/README.md

**Comment by raajnadar** [comment]
Is this issue fixed for windows 10 now?
