### ISSUE TITLE
Deleting content type in UI crashes strapi

### ISSUE THREAD

**Issue by alex-lechner** [strapi/strapi#19556]
### Required System information

- Environment: development
- OS: darwin-x64
- Strapi Version: 4.20.0
- Node/Yarn Version: npm/10.2.5 node/v21.5.0 darwin x64 workspaces/false
- Edition: Community
- Database: postgres
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

1. Go to `Content-Type Builder`
2. Click on a Content Type
3. Click on `Edit` and the `Delete`
4. Strapi deletes the content type but creates a `lifecycles.js` file under `src/api/your_content_type/content-types/your_content_type` 

### Expected behavior

Delete the content type (also please from the database as mentioned in #19320) and restart successfully.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Command line error:

```
⠹ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                            │
│   Error: Could not load content type found at                                                                                              │
│   /Users/me/projects/example/example-strapi-lp/backend/src/api/about-us-text/content-types                                                 │
│   at loadContentTypes                                                                                                                      │
│   (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/strapi/dist/core/loaders/apis.js:94:13)                       │
│   at async Promise.all (index 7)                                                                                                           │
│   at async loadAPI                                                                                                                         │
│   (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/strapi/dist/core/loaders/apis.js:55:95)                       │
│   at async Object.loadAPIs                                                                                                                 │
│   (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/strapi/dist/core/loaders/apis.js:26:17)                       │
│   at async Strapi.loadAPIs (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/strapi/dist/Strapi.js:317:5)         │
│   at async Promise.all (index 5)                                                                                                           │
│   at async Strapi.register (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/strapi/dist/Strapi.js:341:5)         │
│   at async Strapi.load (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/strapi/dist/Strapi.js:425:5)             │
│   at async Object.develop                                                                                                                  │
│   (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:837:28)                  │
│   at async develop                                                                                                                         │
│   (/Users/me/projects/example/example-strapi-lp/backend/node_modules/@strapi/admin/dist/_chunks/develop-YNTGWKMC.js:61:5)                  │
│                                                                                                                                            │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Eventyret** [comment]
Unable to reproduce this issue on v4.20.2

**Comment by alex-lechner** [comment]
I have a guess as to what might be causing this issue:
The project I'm working on was initially created with strapi v3 and has been migrated to strapi v4. All content types created in strap v3 were affected by this issue whereas all newly created content types with strapi v4 were unaffected.

**Comment by jornhymcfly** [comment]
@alex-lechner I had the same issue as you. My fix was to manually delete a lifecycle.ts file I had created earlier. This was preventing the directory from being deleted.

**Comment by uigywnkiub** [comment]
The same wtf Strapi

**Comment by uigywnkiub** [comment]
> > This is a templated message
> 
> Hello @alex-lechner,
> 
> Thank you for reporting this bug, however we are unable to reproduce the issue you described given the information we have on hand. Can you please create a fresh project that you are able to reproduce the issue in, provide clear steps to reproduce this issue, and either upload this fresh project to a new GitHub repo or compress it into a `.zip` and upload it on this issue?
> 
> We would greatly appreciate your assistance with this, by working in a fresh project it will cut out any possible variables that might be unrelated. Please note that issues labeled with `status: can not reproduce` will be closed in 14 days if there is no activity.
> 
> Thank you!

Just make a collection or single type, and discard files from git locally!!!

**Comment by coditive-przemek-h** [comment]
@uigywnkiub  I did the same. After discarding `GIT` changes, the files are removed, but the directory structure created by Strapi is not. YOu need to remove empty directories manually to fix this.
