### ISSUE TITLE
Can't import `factories`

### ISSUE THREAD

**Issue by Dawsoncodes** [strapi/strapi#19580]
I'm using TypeScript and importing `createCoreController` from "@strapi/strapi/dist/factories"

```ts
import { createCoreController } from "@strapi/strapi/dist/factories"
```

TypeScript compiles without error.

After I upgraded Strapi to `4.20.2` I get this runtime error:

```bash
yarn run v1.22.21
$ strapi start
[2024-02-22 11:11:04.276] debug: ⛔️ Server wasn't able to start properly.
[2024-02-22 11:11:04.277] error: Package subpath './dist/factories' is not defined by "exports" in /home/dev/Desktop/myproject/strapi/node_modules/@strapi/strapi/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/factories' is not defined by "exports" in /home/dev/Desktop/myproject/strapi/node_modules/@strapi/strapi/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/dev/Desktop/myproject/strapi/dist/src/api/email/controllers/email.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Module.importDefault (/home/dev/Desktop/myproject/strapi/node_modules/@strapi/utils/dist/index.js:2924:15)
    at loadFile (/home/dev/Desktop/myproject/strapi/node_modules/@strapi/strapi/dist/core/loaders/apis.js:122:26)
    at loadDir (/home/dev/Desktop/myproject/strapi/node_modules/@strapi/strapi/dist/core/loaders/apis.js:114:38)
    at async Promise.all (index 3)
    at async loadAPI (/home/dev/Desktop/myproject/strapi/node_modules/@strapi/strapi/dist/core/loaders/apis.js:55:95)
    at async Object.loadAPIs (/home/dev/Desktop/myproject/strapi/node_modules/@strapi/strapi/dist/core/loaders/apis.js:26:17)
    at async Strapi.loadAPIs (/home/dev/Desktop/myproject/strapi/node_modules/@strapi/strapi/dist/Strapi.js:317:5)
error Command failed with exit code 1.
```

### Solution

Add the subpaths to the `exports` property in the strapi `package.json`

**Comment by joshuaellis** [comment]
This isn't a bug, we didn't support you importing code from `/dist/xxx`

**Comment by Convly** [comment]
What Josh said + here's the correct way of importing the factories:

```ts
import { factories } from '@strapi/strapi';

factories.createCoreController(/*...*/)
factories.createCoreRouter(/*...*/)
factories.createCoreService(/*...*/)
```

**Comment by Dawsoncodes** [comment]
Thank you very much 🙏
