### ISSUE TITLE
Using shared types from monorepo project outside of Strapi's `tsconfig.json` `rootDir` causes config to be undefined.

### ISSUE THREAD

**Issue by snappymob-woon** [strapi/strapi#19591]
### Required System information

- Node.js version: 20.8.0
- NPM version: 10.1.0
- Strapi version: 4.15.0
- Database: PostgreSQL
- Operating system: MacOS M1 / darwin-arm64
- Is your project Javascript or Typescript: Typescript
- Workspaces: npm workspaces

### Describe the bug

I have a monorepo project using npm workspaces which contains `frontend`, `backend` (Strapi) and `shared` projects.

To use types in the `shared` project, I removed `rootDir` out of `tsconfig.json` and use `paths` to add an alias to the `shared` project. Typescript manages to resolve the imports and I am able to use the shared types.

However, when running `npm run develop`,  the error below occurs:

```
TypeError: Cannot destructure property 'client' of 'db.config.connection' as it is undefined.
    at getDialect (/Users/user/Desktop/dev/project/node_modules/@strapi/database/dist/index.js:1014:11)
    at new Database (/Users/user/Desktop/dev/project/node_modules/@strapi/database/dist/index.js:6114:20)
    at Database.init (/Users/user/Desktop/dev/project/node_modules/@strapi/database/dist/index.js:6100:16)
    at Strapi.bootstrap (/Users/user/Desktop/dev/project/node_modules/@strapi/strapi/dist/Strapi.js:365:39)
    at Strapi.load (/Users/user/Desktop/dev/project/node_modules/@strapi/strapi/dist/Strapi.js:419:16)
    at async workerProcess (/Users/user/Desktop/dev/project/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js:110:26)
    at async action (/Users/user/Desktop/dev/project/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js:38:14)
```

### Steps to reproduce the behavior

1. Create a folder outside of the Strapi folder to store the shared types.
2. Remove `rootDir` from `tsconfig.json` and add the `paths` attribute with an alias pointing to the `shared` folder.
3. Import and use the types.
4. Run `npm run develop`
5. See the error.

### Expected behavior

The error shouldn't happen. Types can be used across projects and Strapi should still build without any issue.

### Code snippets

```json
// tsconfig.json
{
  "extends": "@strapi/typescript-utils/tsconfigs/server",
  "compilerOptions": {
    "outDir": "dist",
    // "rootDir": ".",
    "paths": { "./*": ["./backend/*"], "@shared/*": ["../shared/*"] },
  },
  ...
}
```

### Additional context

I did some digging and narrowed it down to how the outdir is being resolved. Due to the fact that when including external projects into Strapi, the `dist` folder is now up one level:
```
dist
├── backend
├── shared
└── tsconfig.tsbuildinfo
```
instead of the usual:
```
dist
├── config
├── src
└── tsconfig.tsbuildinfo
```

which is why the configs are not found.

The file I narrowed down the issue to is [`resolve-outdir.js`](https://github.com/strapi/strapi/blob/develop/packages/utils/typescript/lib/utils/resolve-outdir.js).

Some checking needs to be done to see if there are external projects being included in the `dist` and append the project folder name accordingly to the outdir.

**Comment by vjself** [comment]
@snappymob-woon 

I'm trying to set up something identical to the situation you are describing. Did you ever find a workaround for this issue that doesn't include having to include types directly from the Strapi server directory into the client directory? (I'd like a globally available shared types folder as well.) It doesn't look like this is getting much light since March but I'd really love a solution.

Thank you

**Comment by snappymob-woon** [comment]
> @snappymob-woon 
> 
> 
> 
> I'm trying to set up something identical to the situation you are describing. Did you ever find a workaround for this issue that doesn't include having to include types directly from the Strapi server directory into the client directory? (I'd like a globally available shared types folder as well.) It doesn't look like this is getting much light since March but I'd really love a solution.
> 
> 
> 
> Thank you

Unfortunately, no.

My team decided to just have duplicate files for the types and make sure they are updated together.

I've tried tampering with the code to make it generate the correct `outDir` but to no avail. I do not have enough time nor the knowledge of the Strapi codebase to fix this issue.
