### ISSUE TITLE
Error when uploading any media to the media library

### ISSUE THREAD

**Issue by L-Weisz** [strapi/strapi#19649]
### Required System information

- Node.js version: node/v18.16.1
- Yarn version: yarn/1.22.21
- Strapi version: 4.16.2
- Database: SQLite
- Operating system: MacOs
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

Our strapi instance is deployed with strapi cloud. 
This bug is only on deployed app , we do not replicate locally : 

1. Go to media library
2. Click on add new assets 
3. Browse file
4. Add any image
5. Click on "upload 1 asset to the library" 
6. See an internal server error

### Expected behavior

I expect the image to upload 

### Screenshots

<img width="780" alt="image" src="https://github.com/strapi/strapi/assets/117728108/c70ea591-33fa-4d2f-b213-2fa7452def14">

### Code snippets

In strapi cloud log runtime I see this error 
```sql
AxiosError: Request failed with status code 401
[2024-03-01 10:31:45]     at settle (/home/app/node_modules/strapi-provider-upload-strapi-cloud/node_modules/axios/dist/node/axios.cjs:1967:12)
[2024-03-01 10:31:45]     at IncomingMessage.handleStreamEnd (/home/app/node_modules/strapi-provider-upload-strapi-cloud/node_modules/axios/dist/node/axios.cjs:3066:11)
[2024-03-01 10:31:45]     at IncomingMessage.emit (node:events:529:35)
[2024-03-01 10:31:45]     at IncomingMessage.emit (node:domain:489:12)
[2024-03-01 10:31:45]     at endReadableNT (node:internal/streams/readable:1400:12)
[2024-03-01 10:31:45]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-03-01 10:31:45]     at Axios.request (/home/app/node_modules/strapi-provider-upload-strapi-cloud/node_modules/axios/dist/node/axios.cjs:3877:41)
[2024-03-01 10:31:45]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-03-01 10:31:45]     at async getPresignedUrl (/home/app/node_modules/strapi-provider-upload-strapi-cloud/lib/index.js:36:20)
[2024-03-01 10:31:45]     at async Object.upload (/home/app/node_modules/strapi-provider-upload-strapi-cloud/lib/index.js:106:28)
[2024-03-01 10:31:45]     at async Object.upload (/home/app/node_modules/@strapi/plugin-upload/server/services/provider.js:16:7)
[2024-03-01 10:31:45]     at async Promise.all (index 0)
[2024-03-01 10:31:45]     at async Object.uploadImage (/home/app/node_modules/@strapi/plugin-upload/server/services/upload.js:238:5)
[2024-03-01 10:31:45]     at async Object.uploadFileAndPersist (/home/app/node_modules/@strapi/plugin-upload/server/services/upload.js:252:7)
[2024-03-01 10:31:45]     at async Promise.all (index 0)
[2024-03-01 10:31:45]     at async Object.upload (/home/app/node_modules/@strapi/plugin-upload/server/services/upload.js:172:23)
[2024-03-01 10:31:45]     at async uploadFiles (/home/app/node_modules/@strapi/plugin-upload/server/controllers/admin-upload.js:79:27)
[2024-03-01 10:31:45]     at async Object.upload (/home/app/node_modules/@strapi/plugin-upload/server/controllers/admin-upload.js:101:5)
[2024-03-01 10:31:45]     at async returnBodyMiddleware (/home/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
[2024-03-01 10:31:45]     at async policiesMiddleware (/home/app/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
[2024-03-01 10:31:45]     at async /home/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
[2024-03-01 10:31:45]     at async /home/app/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
```

### Additional context

I checked the role and the file is uploaded with super admin rights that has the authorization to upload images
![image](https://github.com/strapi/strapi/assets/117728108/b111f011-956d-4e99-9226-88b2388b18da)

**Comment by L-Weisz** [comment]
Update : I redeployed my app and it solved the issue , but it would be interesting to understand why this happened

**Comment by L-Weisz** [comment]
reopening so support team can be aware of this problem
