### ISSUE TITLE
Entity name modification doesn't cause changing related names

### ISSUE THREAD

**Issue by robozb** [strapi/strapi#19658]
When modifying the name of an entity, the related names doesn't change: e.g. at settings -> USERS & PERMISSIONS PLUGIN
 -> Roles -> Public -> Permissions -> ...

This is a serious bug

![image](https://github.com/strapi/strapi/assets/8656998/c817430e-2cc7-4eed-8c1c-bee3833fb460)

![image](https://github.com/strapi/strapi/assets/8656998/7dd332eb-0aa7-411d-925d-3fbef875e569)

![image](https://github.com/strapi/strapi/assets/8656998/0a76433a-5bdf-4671-b3b4-46944dc24e01)

**Comment by robozb** [comment]
Or the original name will never change?

![image](https://github.com/strapi/strapi/assets/8656998/207defb0-b0ad-4dcd-8384-1f9f3cd990c0)

Just the display name?

Thank you so much!

**Comment by robozb** [comment]
Another thing arised, Maybe it is realted to the nam e modification: 

```
strapi_app  | Error: ER_TOO_LONG_IDENT: Identifier name 'inspiring_creations_inspirational_artwork_categories_links_inv_fk' is too long
strapi_app  |     at Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
strapi_app  |     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
strapi_app  |     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
strapi_app  |     at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
strapi_app  |     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
strapi_app  |     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
strapi_app  |     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
strapi_app  |     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
strapi_app  |     at Socket.emit (node:events:517:28)
strapi_app  |     at Socket.emit (node:domain:489:12)
strapi_app  |     --------------------
strapi_app  |     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
strapi_app  |     at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
strapi_app  |     at /app/node_modules/knex/lib/dialects/mysql/index.js:132:18
strapi_app  |     at new Promise (<anonymous>)
strapi_app  |     at Client_MySQL._query (/app/node_modules/knex/lib/dialects/mysql/index.js:126:12)
strapi_app  |     at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
strapi_app  |     at Client_MySQL.query (/app/node_modules/knex/lib/client.js:154:12)
strapi_app  |     at /app/node_modules/knex/lib/execution/transaction.js:371:24
strapi_app  |     at new Promise (<anonymous>)
strapi_app  |     at trxClient.query (/app/node_modules/knex/lib/execution/transaction.js:366:12) {
strapi_app  |   code: 'ER_TOO_LONG_IDENT',
strapi_app  |   errno: 1059,
strapi_app  |   sqlMessage: "Identifier name 'inspiring_creations_inspirational_artwork_categories_links_inv_fk' is too long",
strapi_app  |   sqlState: '42000',
strapi_app  |   index: 0,
strapi_app  |   sql: 'alter table `inspiring_creations_inspirational_artwork_categories_links` add constraint `inspiring_creations_inspirational_artwork_categories_links_inv_fk` foreign key (`inspirational_artwork_category_id`) references `inspirational_artwork_categories` (`id`) on delete CASCADE'
strapi_app  | }

```
