### ISSUE TITLE
4.20.3: strapi export throwing error "Unhandled error"

### ISSUE THREAD

**Issue by chrisli-sas** [strapi/strapi#19674]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Strapi version: 4.20.3
- Database: postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When running `npx strapi transfer --from URL --from-token TRANSFER_TOKEN --force` I get `Unhandled error` error.

```
? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
[2024-03-04 13:40:47.937] warn: (Schema Integrity) Review workflows feature does not exist on destination
? There are differences in schema between the source and destination, and the data listed above will be lost. Are you sure you want to continue? Yes
Starting transfer...
✔ entities: 3158 transfered (size: 3.7 MB) (elapsed: 22186 ms) 
⠴ assets: 1372 transfered (size: 119.6 MB) (elapsed: 107691 ms) (1.1 MB/s)node:events:505
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({})
    at new NodeError (node:internal/errors:406:5)
    at PassThrough.emit (node:events:503:17)
    at PassThrough.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {}
}
```

### Steps to reproduce the behavior

1. Run transfer command with --from flag

### Expected behavior

Expect transfer to complete without error

### Additional context

I removed url and transfer token in this post, they are correct and are not cause of issue.

I have about 600mb assets, the asset step causes the most issue so it might have something to do with the amount of assets.

I was able to finish the transfer with v4.20.2, but it had a lot of missing relations. Upgrading to v4.20.3 gave me this error.

I reran the command more times and gotten different error messages.

```
The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
[2024-03-04 13:50:57.129] warn: (Schema Integrity) Review workflows feature does not exist on destination
? There are differences in schema between the source and destination, and the data listed above will be lost. Are you sure you want to continue? Yes
Starting transfer...
✔ entities: 3158 transfered (size: 3.7 MB) (elapsed: 21105 ms) 
⠇ assets: 1114 transfered (size: 72 MB) (elapsed: 71353 ms) (1 MB/s)node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:406:5)
    at _write (node:internal/streams/writable:378:11)
    at Writable.write (node:internal/streams/writable:393:10)
    at /Users/chrisli/Desktop/strapi/node_modules/@strapi/data-transfer/dist/index.js:2868:15
    at new Promise (<anonymous>)
    at RemoteStrapiSourceProvider.writeAsync (/Users/chrisli/Desktop/strapi/node_modules/@strapi/data-transfer/dist/index.js:2867:12)
    at PassThrough.<anonymous> (/Users/chrisli/Desktop/strapi/node_modules/@strapi/data-transfer/dist/index.js:2889:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

```
The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
[2024-03-04 13:53:18.081] warn: (Schema Integrity) Review workflows feature does not exist on destination
? There are differences in schema between the source and destination, and the data listed above will be lost. Are you sure you want to continue? Yes
Starting transfer...
✔ entities: 3158 transfered (size: 3.7 MB) (elapsed: 17090 ms) 
⠹ assets: 57 transfered (size: 7.7 MB) (elapsed: 3866 ms) (2 MB/s)/Users/chrisli/Desktop/strapi/node_modules/@strapi/data-transfer/dist/index.js:2889
          await this.writeAsync(assets[item.assetID].stream, chunk);
                                                     ^

TypeError: Cannot read properties of undefined (reading 'stream')
    at PassThrough.<anonymous> (/Users/chrisli/Desktop/strapi/node_modules/@strapi/data-transfer/dist/index.js:2889:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ststaynov** [comment]
+1, same issue with versions 20.1 & 20.3

**Comment by genibus** [comment]
+1, Same issue with version 4.21.1

**Comment by CorentinNrd** [comment]
I found the problem on node_modules/@strapi/data-transfer/dist/index.js line 2914, i added an optional chain on the line before the stream in the writeAsync. Can you please fix the issue

![Capture d’écran 2024-04-04 à 14 33 03](https://github.com/strapi/strapi/assets/83210854/cd569b3f-19e7-41d5-993f-bd75724a68b1)

**Comment by genibus** [comment]
> +1, Same issue with version 4.21.1

We manage to get the transfer working by adding two element inside **node_modules/@strapi/data-transfer/dist/index.js**
First check if the stream2 exist, if not return
![Capture d’écran 2024-04-04 à 14 43 20](https://github.com/strapi/strapi/assets/29832586/d3076789-a520-499c-8ac2-a457dae05235)
Add optional chaining line 2915
![Capture d’écran 2024-04-04 à 14 43 27](https://github.com/strapi/strapi/assets/29832586/2eeb2d99-fa6d-4593-9fe9-df778478bdbe)

Not the best work, but it work... Can you please add a fix, thanks guys.

**Comment by akantic** [comment]
+1, trying transfer first time after #18350 was _fixed_,  now getting this error... 

```
? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
(node:2219) Warning: S3 configuration options passed at root level of the plugin's providerOptions is deprecated and will be removed in a future release. Please wrap them inside the 's3Options:{}' property.
(Use `node --trace-warnings ...` to show where the warning was created)
Starting transfer...
✔ entities: 367 transfered (size: 408.3 KB) (elapsed: 1117 ms) 
⠋ assets: 0 transfered (size: 0) (elapsed: 0 ms) node:events:508
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({})
    at new NodeError (node:internal/errors:405:5)
    at PassThrough.emit (node:events:506:17)
    at PassThrough.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {}
}

Node.js v18.20.1
```

**Comment by kwooccli** [comment]
Pretty frustrating, I'm working with 4.24.2 and it appears the error still exists and is very identical to @akantic 's console: 
``` 
Starting transfer...
✔ entities: 165 transfered (size: 157.8 KB) (elapsed: 406 ms) 
⠸ assets: 0 transfered (size: 0) (elapsed: 0 ms) node:events:510
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({})
    at PassThrough.emit (node:events:508:17)
    at PassThrough.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {}
}

Node.js v20.13.1
```

A potential workaround for some people might be to use the third party plugin: `strapi-plugin-import-export-entries` 

Please fix this soon.

**Comment by kyguney** [comment]
I encountered the same error. After researching as mentioned by @genibus, I identified the issue. The problem lies within the "createAssetsReadStream" function in the `node_modules/@strapi/data-transfer/dist/index.js` file. We're using stream2 objects, but they're not being properly handled when an error occurs.

Specifically, we're using `stream2.destroy(error);` to terminate the stream when an error occurs, but we're not handling the error event emitted when the stream is destroyed. Consequently, even though I added the following code to line 2927, I received a console error, but the transfer continued and completed.

```
.on('error', (error) => {
     console.error('An error occurred in stream2:', error);
 });
```
I hope they are going to resolve in next release.

Strapi version: v4.24.2
Node version: v18.20.3

**Comment by sabir-Hussain** [comment]
> If the files is somehow less important, the rest of the transfer process will work correctly with the extra cli argument: `--exclude files`

Worked for me <3

**Comment by derrickmehaffy** [comment]
Just for some further clarification can you all share/confirm the following:

- Are both the source and destination sides of the transfer running on 4.24.2?
- Which upload providers are you using (AWS-S3, Local, Cloudinary, or a 3rd party one like Azure)?

**Comment by kyguney** [comment]
@derrickmehaffy Here are my answers:

- Yes, my both the source and destination sides of the transfer are running on 4.24.2
- I am using AWS-S3

**Comment by kwooccli** [comment]
@derrickmehaffy  for me: 
- I am using: `strapi-provider-upload-azure-storage@3.4.0`
- and both source/destinations are running with `4.24.2`

**Comment by derrickmehaffy** [comment]
Thank you both, are either of you in a "resource constrained" environment such as low RAM availability and during the failure did your RAM usage spike heavily to the point where one side of the transfer crashed?

**Comment by derrickmehaffy** [comment]
We are trying to figure out why the stream crashes and to see if the memory leak is raising it's ugly head again.

**Comment by lzhou-aops** [comment]
We're also seeing this! We have a lot of images, though they are not very large (215 items, 30.7MB), and are running Strapi inside Docker on a somewhat limited machine.

**Comment by gavgrego** [comment]
Having this issue as well, still.  Unable to export or transfer when using S3.

**Comment by gybratyy** [comment]
had the same issue(i have dockerized cms and db separately), sounds strange but try shutting down strapi itself before running transfer/import.

**Comment by gavgrego** [comment]
Any movement on this?  I hate to have to use the `--exclude files` flag.

**Comment by lzhou-aops** [comment]
@derrickmehaffy FYI, in case y'all haven't tried this yet, the issue seems to happen consistently with images on the order of 5MB, regardless of the RAM capacity of the machines involved in the transfer. 

(Also I'll second the sentiment above that while this issue is not _completely_ blocking, it does make sharing data for testing between prod/staging/multiple local instances extremely annoying, especially when containerization is involved. It's currently the primary reason we're considering not using strapi for future projects.)

**Comment by zelal-dev** [comment]
> If the files is somehow less important, the rest of the transfer process will work correctly with the extra cli argument: `--exclude files`

It worked. Thank you
