### ISSUE TITLE
Yarn build stuck in Admin UI built successfully

### ISSUE THREAD

**Issue by mvaisberg** [strapi/strapi#19688]
### Required System information

Node.js version: 18.16.0
NPM version: 9.5.1
Strapi version: 4.15.0
Operating system: Linux - Ubuntu
Is your project Javascript or Typescript: TS

### Describe the bug

When i ran yarn build it get build but get stucked in after succes message "Admin UI built successfully"

### Steps to reproduce the behavior

1. Go to console project folder
2. run "yarn build"

### Expected behavior

The command should finish as any other command

### Screenshots

![Selection_1313](https://github.com/strapi/strapi/assets/4543889/8a5f393c-47ac-464f-9caf-3bf922a61b0b)

**Comment by ri5h** [comment]
I was in same situation. After waiting a few minutes, I got this error, maybe it helps you,
```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (node_modules/knex/lib/client.js:332:26)
    at async Runner.ensureConnection (node_modules/knex/lib/execution/runner.js:305:28)
    at async Runner.run (node_modules/knex/lib/execution/runner.js:30:19)
    at async Strapi.bootstrap (node_modules/@strapi/strapi/lib/Strapi.js:446:9)
    at async Strapi.load (node_modules/@strapi/strapi/lib/Strapi.js:493:5)
    at async workerProcess (node_modules/@strapi/strapi/lib/commands/actions/develop/action.js:110:26) {
  sql: undefined,
  bindings: undefined
}
```

**Comment by mvaisberg** [comment]
Hi @ri5h thanks for answering!

how did you fix it?

**Comment by derrickmehaffy** [comment]
That is a database error meaning either your database can't be connected to or is taking too long to respond.

As this is environmental I'm setting this bug as cannot reproduce as it almost certainly is not a bug within our code.
