### ISSUE TITLE
Drop constraint error on Strapi startup

### ISSUE THREAD

**Issue by toastyghost** [strapi/strapi#19699]
This is still happening for me on Strapi v4.12.7, it's trying to use `drop constraint` on something that's set up as a unique index, NOT a unique constraint. We can get CI/CD through by manually running `drop index` in the db during the deployment but before the instance fails health checks. If we leave it unattended, it just continually spins up instances in an infinite loop. We've tried putting the `drop index` statement in bootstrap and register in index.js, to no avail.

### Current error:
(redacted vendor names)
```
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]: [2024-03-06 18:01:43.851] error: alter table "public"."transaction_synapse" drop constraint "trans_syn_process_dups" - constraint "trans_syn_process_dups" of relation "transaction_synapse" does not exist
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]: error: alter table "public"."transaction_synapse" drop constraint "trans_[vendor]_process_dups" - constraint "trans_[vendor]_process_dups" of relation "transaction_[vendor]" does not exist
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at Parser.parseErrorMessage (/opt/sdf-api/node_modules/pg-protocol/dist/parser.js:287:98)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at Parser.handlePacket (/opt/sdf-api/node_modules/pg-protocol/dist/parser.js:126:29)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at Parser.parse (/opt/sdf-api/node_modules/pg-protocol/dist/parser.js:39:38)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at Socket.<anonymous> (/opt/sdf-api/node_modules/pg-protocol/dist/index.js:11:42)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at Socket.emit (node:events:517:28)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at Socket.emit (node:domain:489:12)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at addChunk (node:internal/streams/readable:335:12)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at readableAddChunk (node:internal/streams/readable:308:9)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at Readable.push (node:internal/streams/readable:245:10)
Mar 06 18:01:43 ip-172-30-0-79 SDF-API[1201]:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### From the previous ticket:
Same problem on 4.1.10. - why is Strapi altering the tables on startup? I'm using Supabase Postgres as the DB for Strapi as well as for the rest of my app, and it is very beneficial to be able to link my Strapi content to the backend entities which only live in Supabase.

```
[2022-05-26 17:44:12.146] debug: ⛔️ Server wasn't able to start properly.
[2022-05-26 17:44:12.147] error: alter table "groups" drop constraint "groups_pathway_id_fkey" - must be owner of table groups
error: alter table "groups" drop constraint "groups_pathway_id_fkey" - must be owner of table groups
    at Parser.parseErrorMessage (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

_Originally posted by @seth146 in https://github.com/strapi/strapi/issues/11421#issuecomment-1138729665_

**Comment by kiuma** [comment]
still present in version 4.25.8

**Comment by monolithed** [comment]
I removed the description property of type Rich Text (Markdown) and created a new one with the same name of type Rich Text (Block), and now when I run it, I see this error.

I'm using the latest version of Strapi, but I created the field when I was still on version 4.

```
> strapi develop

✔ Cleaning dist dir (5ms)
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (82ms)
✔ Creating admin (167ms)
⠧ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                  │
│   error: alter table "public"."topics" alter column "description" type jsonb using ("description"::jsonb) - invalid input syntax for type json   │
│       at Parser.parseErrorMessage (/www/strapi/node_modules/pg-protocol/src/parser.ts:368:69)        │
│       at Parser.handlePacket (/www/strapi/node_modules/pg-protocol/src/parser.ts:187:21)             │
│       at Parser.parse (/www/strapi/node_modules/pg-protocol/src/parser.ts:102:30)                    │
│       at Socket.<anonymous> (/www/strapi/node_modules/pg-protocol/src/index.ts:7:48)                 │
│       at Socket.emit (node:events:514:28)                                                                                                        │
│       at Socket.emit (node:domain:488:12)                                                                                                        │
│       at addChunk (node:internal/streams/readable:376:12)                                                                                        │
│       at readableAddChunk (node:internal/streams/readable:349:9)                                                                                 │
│       at Readable.push (node:internal/streams/readable:286:10)                                                                                   │
│       at TCP.onStreamRead (node:internal/stream_base_commons:190:23)    
```

**Comment by CTOlet** [comment]
Same issue:

```
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                               │
│   error: alter table "public"."cars" drop constraint "cars_number_published_unq" - constraint "cars_number_published_unq" of relation "cars" does not exist   │
│       at Parser.parseErrorMessage (/Users/alimzhan/work/okauto-b2b/backend/node_modules/pg-protocol/dist/parser.js:283:98)                                    │
│       at Parser.handlePacket (/Users/alimzhan/work/okauto-b2b/backend/node_modules/pg-protocol/dist/parser.js:122:29)                                         │
│       at Parser.parse (/Users/alimzhan/work/okauto-b2b/backend/node_modules/pg-protocol/dist/parser.js:35:38)                                                 │
│       at Socket.<anonymous> (/Users/alimzhan/work/okauto-b2b/backend/node_modules/pg-protocol/dist/index.js:11:42)                                            │
│       at Socket.emit (node:events:519:28)                                                                                                                     │
│       at Socket.emit (node:domain:488:12)                                                                                                                     │
│       at addChunk (node:internal/streams/readable:559:12)                                                                                                     │
│       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)                                                                                  │
│       at Readable.push (node:internal/streams/readable:390:5)                                                                                                 │
│       at TCP.onStreamRead (node:internal/stream_base_commons:191:23)                                                                                          │
│                                                                                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Comment by djacquemard** [comment]
Same issue with Strapi 4.24 + 
https://github.com/strapi/strapi/issues/23321

**Comment by lgoria** [comment]
Any news on this? Similar issue here in Strapi 4.24.5

error:
 alter table "public"."upload_folders" drop constraint 
"idx_33266_upload_folders_path_id_index" - constraint 
"idx_33266_upload_folders_path_id_index" of relation "upload_folders" 
does not exist
