### ISSUE TITLE
Undefined single type's ID when fetching relationships

### ISSUE THREAD

**Issue by gfragioud** [strapi/strapi#19709]
### Required System information

- Node.js version: v18.18.2
- NPM version: 9.8.1
- Strapi version: 4.20.4
- Database: postgres 14
- Operating system: windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When viewing a single type in admin panel, requests to fetch its relationships return 500 because the id is undefined as you can see in the screenshot.
The error below is logged in the console:
`error: select "t0".* from "public"."homepages" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "undefined"
error: select "t0".* from "public"."homepages" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "undefined"
    at Parser.parseErrorMessage (\node_modules\pg-protocol\dist\parser.js:287:98)       
    at Parser.handlePacket (\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

After the failed requests I see one more that is successful.

Before upgrading to v4.20.4, I had v4.15.5 where everything worked as expected.

### Steps to reproduce the behavior

1. Create a single type that has one to many relationship with a collection
2. Go to content manager
3. Click on single type to view it
4. See error in network and console

### Expected behavior

No errors

### Screenshots

![image](https://github.com/strapi/strapi/assets/2271951/307f7af5-ed4e-4b17-9685-af7547143e18)

**Comment by garrettheaver** [comment]
👍 Experiencing same issue on v4.20.2

**Comment by n-alonso** [comment]
Internal TID: 6439

**Comment by sharmavikas24** [comment]
We are experiencing same issue.

**Comment by raulbalestra** [comment]
Internal TID: 10794

**Comment by kulak91** [comment]
Any progress?

**Comment by aniketnegi** [comment]
any progress?

**Comment by MIT120** [comment]
any progress?
