### ISSUE TITLE
Strapi 5: Can't create admin during installation - Cannot find module @rollup/rollup-darwin-arm64

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#19952]
### Required System information

Launched In: 1043 ms
Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.1
Node/Yarn Version: npm/9.8.1 node/v18.18.1 darwin arm64 workspaces/false
Edition: Community
Database: sqlite

### Describe the bug

I am installing Strapi 5: `npx create-strapi-app@beta learn-strapi-5 --quickstart`

The process stopped on the step: Creating admin

```package.json
"dependencies": {
    "@strapi/strapi": "5.0.0-beta.1",
    "@strapi/plugin-users-permissions": "5.0.0-beta.1",
    "@strapi/plugin-cloud": "5.0.0-beta.1",
    "better-sqlite3": "9.4.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "5.3.3"
  },
```

Error:

```
⠙ Creating admin[ERROR]  There seems to be an unexpected error, try again with --debug for more information

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐│                                                                                                                               ││   Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies                       ││   (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules   ││   directory.                                                                                                                  ││   at requireWithFriendlyError (/Users/teine/Development/learn-strapi-5/node_modules/rollup/dist/native.js:88:9)               ││   at Object.<anonymous> (/Users/teine/Development/learn-strapi-5/node_modules/rollup/dist/native.js:97:76)                    ││   at Module._compile (node:internal/modules/cjs/loader:1256:14)                                                               ││   at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)                                                        ││   at Object.newLoader [as .js] (/Users/teine/Development/learn-strapi-5/node_modules/esbuild-register/dist/node.js:2262:9)    ││   at Module.load (node:internal/modules/cjs/loader:1119:32)                                                                   ││   at Module._load (node:internal/modules/cjs/loader:960:12)                                                                   ││   at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)                                                    ││   at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### Screenshots

![2024-03-28 10-58-28](https://github.com/strapi/strapi/assets/1038168/8d257606-4b5a-49c9-8ea9-a6e3bd0e0e42)

**Comment by joshuaellis** [comment]
This looks like a bug with `npm` as opposed to strapi, have you tried looking at the aforementioned issue in the terminal & trying the steps it suggests?

**Comment by teinett** [comment]
Deleted folder `node_modules` and `package-lock.json`. 
Started `npm i`, next `npm build`.
It worked. Now I can try Strapi 5.

**Comment by egyleader** [comment]
I think this issue should be re-opened as the installation process doesn't complete normally without manually deleting the `node_modules` and `package-lock.json` and running `npm i` manually , I don't think this is the intended behaveior of the installer  , faced the same error : 

```node
Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug       ││   related to optional dependencies                                           ││   (https://github.com/npm/cli/issues/4828). Please try `npm i` again after   ││   removing both package-lock.json and node_modules directory.                ││   at requireWithFriendlyError (/Users/egyleader/dev/_plygrnd/beta/node_mod   ││   ules/rollup/dist/native.js:89:9)                                           ││   at Object.<anonymous> (/Users/egyleader/dev/_plygrnd/beta/node_modules/r   ││   ollup/dist/native.js:98:76)                                                ││   at Module._compile (node:internal/modules/cjs/loader:1364:14)              ││   at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)       ││   at Object.newLoader [as .js] (/Users/egyleader/dev/_plygrnd/beta/node_mo   ││   dules/esbuild-register/dist/node.js:2262:9)                                ││   at Module.load (node:internal/modules/cjs/loader:1203:32)                  ││   at Module._load (node:internal/modules/cjs/loader:1019:12)                 ││   at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)   ││   at ModuleJob.run (node:internal/modules/esm/module_job:195:25)             ││   at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)     ││                                                                         
```

**Comment by derrickmehaffy** [comment]
I'm guessing the first install doesn't detect that it's apple arm CPU and grabs a wrong binary but there is nothing we can do about that, need to report this to the upstream.
