### ISSUE TITLE
Relations not saved when updating content type

### ISSUE THREAD

**Issue by mnagy112** [strapi/strapi#19977]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Yarn version: 1.22.17
- Strapi version: 5.0.0-beta.1
- Database: postgres
- Operating system: darwin-arm64 (MacOS Sonoma 14.1.1)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When updating content type relation field, nothing is saved and 500 error is reported with maximum call stack exceeded.

### Steps to reproduce the behavior

Note: Not using Draft & publish feature 

1. Create content type A
2. Create content type B with any relation to content type A (lets say A has many B)
3. Create record for content type A (A1)
4. Create record for content type B (B1) with added relation to A1 (here everything works)
5. Remove relation A1 from record B1 and save (everything works)
6. Add relation A1 to record B1 (crashes with 500 Internal server error)

### Expected behavior

Expect relation A1 to be added to B1

### Screenshots

<img width="948" alt="image" src="https://github.com/strapi/strapi/assets/12200234/6337df70-0f14-4948-81e5-07aecccc6943">

### Code snippets

Error trace from logs:

```
[2024-03-31 19:40:36.920] error: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at QueryCompiler_PG.columns (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/query/querycompiler.js:277:10)
    at /Users/mnagy/projects/strapi-project/node_modules/knex/lib/query/querycompiler.js:135:40
    at Array.forEach (<anonymous>)
    at QueryCompiler_PG.select (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/query/querycompiler.js:134:16)
    at QueryCompiler_PG.toSQL (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/query/querycompiler.js:75:29)
    at unwrapRaw (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/formatter/wrappingFormatter.js:102:41)
    at Client_PG.parameter (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/client.js:409:12)
    at QueryCompiler_PG._valueClause (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/query/querycompiler.js:988:21)
    at QueryCompiler_PG.whereBasic (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/query/querycompiler.js:1075:12)
    at QueryCompiler_PG.where (/Users/mnagy/projects/strapi-project/node_modules/knex/lib/query/querycompiler.js:584:34)
```

Payload:

```
{
   "name": "item 1",
   "amount": 10,
   "order": {
      "connect": [
         {
            "id":10,
            "__temp_key__":"a0",
            "name":"asdfasd",
            "label":"asdfasd",
            "href":"../collection-types/api::order.order/l4s6dx02jbogt4vmqn15b35x"
         }
      ],
      "disconnect":[]
   }
}
```

### Additional context

Same happens in plain new application when using postgres, with sqlite everything works as expected

**Comment by eugle** [comment]
Having the same problem

**Comment by thoranrion** [comment]
Same here.

**Comment by derrickmehaffy** [comment]
Can't reproduce in beta.5

**Comment by derrickmehaffy** [comment]
According to the other issue this may only happen with PG

**Comment by kasonde** [comment]
Hi there. With the steps you have provided, I am unable to reproce this issue in Strapi 5.0.0-beta.5. If possible, can you try to test this on the latest beta and let us know if you still experience it?

**Comment by petrmifek** [comment]
There's a repository showing the issue with docker, please see https://github.com/strapi/strapi/issues/20187#issuecomment-2076060659

For steps to reproduce, please see here:

https://github.com/strapi/strapi/issues/20187#issuecomment-2076060659

I'm wondering if there's just some setup error, since it's not reported that often?

Thanks

**Comment by kasonde** [comment]
Actually, I just confirmed it in Strapi Beta 5 with postgres

**Comment by alexandrebodin** [comment]
Fixed
