### ISSUE TITLE
Strapi Start - Promise error

### ISSUE THREAD

**Issue by soccer99** [strapi/strapi#200]
Strapi: 1.5.7

#199 Last issue was resolved, now I'm getting a new one.

```
info: Your server is running at http://localhost:1337
info: Your admin panel is available at http://localhost:1337/admin/
debug: Time: Wed Apr 12 2017 12:21:28 GMT-0700 (PDT)
debug: Environment: development
debug: Process PID: 8585
debug: Cluster: master
info: To shut down your server, press <CTRL> + C at any time

error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/Users/bradyendres/Desktop/_Scripting/_WEBSITES/avail/api/user/config/fixtures/route.js:18:28)
error: Bootstrap encountered an error.
error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/Users/bradyendres/Desktop/_Scripting/_WEBSITES/avail/api/user/config/fixtures/route.js:18:28)
(node:8585) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Callback was already called.
(node:8585) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by Aurelsicoko** [comment]
You shouldn't be able to start the server with another Node.js version than 4.x.x. You can't use Strapi v1 with Node v5/6/7.

**Comment by pierreburgy** [comment]
@soccer99 Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.
