### ISSUE TITLE
500 when adding filter in content-type list on a many2many relation

### ISSUE THREAD

**Issue by verdverm** [strapi/strapi#20058]
### Required System information

- Node.js version: 20.x
- Strapi version: v5.0.0-beta.2
- Database: Postgres
- Operating system: linux
- Is your project Javascript or Typescript:

### Describe the bug

500 error when filtering on relation column where other side has no entries in the database yet

`function lower(integer) does not exist` seems to be the root of the error. Looks like the generated query is trying to call `lower` on an `id` field which is an int type

### Steps to reproduce the behavior

1. Blog content-type
2. Tags content-type
3. Add many2many relation between
4. Have some blogs, no tags yet
5. Try to add tag filter, `contains (insensitive)`

### Expected behavior

Filter should be added, probably no results?

It looks like the filter on a relation cannot specify a subfield. I'd like to be able to filter based on the value of the tag, not the id

### Error logs

```
[2024-04-08 02:42:25.785] error: select count(distinct "t0"."id") as "count" from "public"."blogs" as "t0" left join "public"."blogs_tags_lnk" as "t1" on "t0"."id" = "t1"."blog_id" left join "public"."tags" as "t2" on "t1"."tag_id" = "t2"."id" where ("t0"."published_at" is null and ((LOWER("t2"."id") LIKE LOWER($1))) and "t0"."published_at" is null) limit $2 - function lower(integer) does not exist
error: select count(distinct "t0"."id") as "count" from "public"."blogs" as "t0" left join "public"."blogs_tags_lnk" as "t1" on "t0"."id" = "t1"."blog_id" left join "public"."tags" as "t2" on "t1"."tag_id" = "t2"."id" where ("t0"."published_at" is null and ((LOWER("t2"."id") LIKE LOWER($1))) and "t0"."published_at" is null) limit $2 - function lower(integer) does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2024-04-08 02:42:25.786] http: GET /content-manager/collection-types/api::blog.blog?page=1&pageSize=20&sort=updatedAt:DESC&filters[$and][0][tags][id][$containsi]=jobs (51 ms) 500
```

**Comment by Eventyret** [comment]
Unable to reproduce this on `v5.0.0-beta.2`


![Image](https://github.com/strapi/strapi/assets/977232/c788a2ef-3973-404d-9360-897e221158cd)

Though I want to relate that I found another bug that I created from this. https://github.com/strapi/strapi/issues/20155

**Comment by verdverm** [comment]
I upgraded to `beta.4` and am still seeing the same error I outlined above

@Eventyret are you filtering on a many-2-many relation? The column titles in your image do not indicate a relation exists

**Comment by dennism501** [comment]
@verdverm - I was not able to reproduce this on `5.0.0-beta.6`, are you still facing this error even when you upgrade to `5.0.0-beta.6`?

**Comment by verdverm** [comment]
Yes, the error persists. Again, the issue is that the SQL query generated is creating `(LOWER("t2"."id")` which is trying to make an INT lowercase

**Comment by verdverm** [comment]
Still present on `v5-beta.7`

**Comment by derrickmehaffy** [comment]
able to reproduce on beta.8 but you must be using postgresql as a database, on sqlite it doesn't happen

![image](https://github.com/strapi/strapi/assets/8593673/f428adba-ea4d-4f60-a9fc-669dc9fd01b9)

**Comment by verdverm** [comment]
yes, psql, see the original bug report
