### ISSUE TITLE
Strapi data transfer fails on specific files: Write after end error

### ISSUE THREAD

**Issue by bieblebrox** [strapi/strapi#20087]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 4.15.5
Node/Yarn Version: yarn/3.6.1 npm/? node/v18.19.0 darwin arm64
Edition: Community
Database: postgres

### Describe the bug

I'm trying to use the strapi data transfer command to move data across environments. It worked fine initially but now the client has uploaded a large number of files and the scripts fails when transferring these files. We are using the google cloud storage plugin @strapi-community/strapi-provider-upload-google-cloud-storage. 

When running the transfer command and it reaches the transfer assets I get this error:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:405:5)
    at _write (node:internal/streams/writable:322:11)
    at Writable.write (node:internal/streams/writable:337:10)
    at /my_project_path/node_modules/@strapi/data-transfer/dist/index.js:2816:15
    at new Promise (<anonymous>)
    at RemoteStrapiSourceProvider.writeAsync (/my_project_path/node_modules/@strapi/data-transfer/dist/index.js:2814:12)
    at PassThrough.<anonymous> (/my_project_path/node_modules/@strapi/data-transfer/dist/index.js:2850:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

I've added some logs in the transfer script which shows that this issue happens with large files.
When I delete one of these files the script runs further, but it's not really an option for us to remove all the files that throw errors.

**Comment by OIvanytskyi-Conduent** [comment]
The same issue is with the `strapi-provider-upload-azure-storage` provider.

Environment: development
OS: darwin-x64
Strapi Version: 4.23.1
Yarn/Node Version: yarn/1.22.18 node/v20.10.0
Edition: Community
Database: postgres / sqlite

**Comment by ststaynov** [comment]
Issue persists in version 4.24 as well. :/

**Comment by jimwib** [comment]
It seems to be with files that are 1MB or larger

**Comment by johachi** [comment]
I have was able to solve this problem but now have a problem that download speed goes to 0kb/s after transferring 1-14 GB of data (I've tried a few times). That is much more than just a few MB before my "fix".

Maybe my solution will be of help to someone if they have less data than me, or maybe it can be a step in the right direction if anyone else is also debugging this as well.

I believe (as the error strongly hints at) that the problem is a race condition where the last chunk is written to disk and the stream closed before the earlier chunks finished being written to. This can be solved by writing data synchronously instead of asynchronously. I have not noticed any speed decrees in my transfer speed doing this.

Below is the code changes I did. I'm on Strapi `v4.22.1`, but I believe the code is very similar (or the same) to other versions as well.

```diff
// In node_modules/@strapi/data-transfer/dist/index.js
  writeAsync = (stream2, data) => {
-    return new Promise((resolve, reject2) => {
+   // return new Promise((resolve, reject2) => {
      stream2.write(data, (error) => {
-        if (error) {
-          reject2(error);
-        }
-        resolve();
+        console.error("Something went terrible wrong: ", error);
      });
-    });
+    // });
  };
```

**And also remove all the awaiting of the function** (several places)

```diff
- await this.writeAsync(...
+ this.writeAsync(...
```

I'm currently not getting any errors, connection just stops. I've got a feeling that whatever kills the connection is on the server side but I'm not getting any errors there either and that is totally just a feeling. Might not be.
