### ISSUE TITLE
Strapi import fails error: update "public"."strapi_core_store_settings" set "value" = $1, "type" = $2 where ("id" = $3) - canceling statement due to statement timeout

### ISSUE THREAD

**Issue by anujd61** [strapi/strapi#20089]
### Required System information

- Node.js version: v20.12.2
- NPM version:10.5.0
- Strapi version:4.23.0
- Database: Postgres | Supabase
- Operating system: MacOS Sonoma 14.1.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I am trying to use `strapi import` and I get this error

```
Starting import...
✔ entities: 365 transfered (size: 381.4 KB) (elapsed: 159612 ms) 
⠙ assets: 539 transfered (size: 81.2 MB) (elapsed: 256326 ms) (324.2 KB/s)/Users/bigdaddy/Desktop/moshi_moshi/rnr/rnr-strapi/node_modules/pg-protocol/dist/parser.js:283
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: update "public"."strapi_core_store_settings" set "value" = $1, "type" = $2 where ("id" = $3) - canceling statement due to statement timeout

    at Parser.parseErrorMessage (/Users/bigdaddy/Desktop/moshi_moshi/rnr/rnr-strapi/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/Users/bigdaddy/Desktop/moshi_moshi/rnr/rnr-strapi/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/Users/bigdaddy/Desktop/moshi_moshi/rnr/rnr-strapi/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/Users/bigdaddy/Desktop/moshi_moshi/rnr/rnr-strapi/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Job instance at:
    at /Users/bigdaddy/Desktop/moshi_moshi/rnr/rnr-strapi/node_modules/node-schedule/lib/Invocation.js:277:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  length: 180,
  severity: 'ERROR',
  code: '57014',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'while updating tuple (23,11) in relation "strapi_core_store_settings"',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '3314',
  routine: 'ProcessInterrupts'
}
```

### Additional context

I have tried multiple backups, including a backup that worked with `strapi import` previously, still get the same error but at different times, sometimes I get the error when assets is transferred `553 transfered` or when it is `300 transferred` and sometimes it breaks in the linking stage.

**Comment by georlitz** [comment]
I'm getting a very similar error, though in my case it's a sqlite database, so maybe it's not database-specific (I'm attempting to get an instance a third-party vendor made for me up and running locally before I deploy; versioning is based on what they used).

**System information**
Node.js version: v18.16.0
NPM version: 9.5.1
Strapi version: 4.22.0
Database: Sqlite3
Operating system: node:18-alpine (docker)
Is your project Javascript or Typescript: Typescript

Similar to BigDaddy-Zephyr, the import starts, I get entities transferred, and after a kind of random amount of the assets being transferred, it errors out with the following:

```
SqliteError: update `strapi_core_store_settings` set `value` = '...huge json string...' - database is locked
at Client_BetterSQLite3._query (/opt/node_modules/knex/lib/dialects/better-sqlite3/index.js:44:38)
at executeQuery (/opt/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
at Client_BetterSQLite3.query (/opt/node_modules/knex/lib/client.js:154:12)
at Runner.query (/opt/node_modules/knex/lib/execution/runner.js:141:36)
at ensureConnectionCallback (/opt/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
at Runner.ensureConnection (/opt/node_modules/knex/lib/execution/runner.js:318:20)
at async Runner.run (/opt/node_modules/knex/lib/execution/runner.js:30:19)
at async Object.execute (/opt/node_modules/@strapi/database/dist/index.js:4254:22)
at async Object.update (/opt/node_modules/@strapi/database/dist/index.js:5086:9)
at async Strapi.bootstrap (/opt/node_modules/@strapi/strapi/dist/Strapi.js:410:5)
```

**Additional Info**
As alluded to above, this is running in a docker container based on node:18-alpine. This occurs when attempting to import the export file that my vendor created for me, or when I attempt to do a transfer from their remote instance. I thought maybe the --throttle option would make a difference, but any time delay I put in there doesn't have an effect. The SQL error does appear to have nothing to do with the number of assets transferred though, as a high throttle number will cause the error after only 1 asset is transferred.
