### ISSUE TITLE
Error after adding an api Strapi v3

### ISSUE THREAD

**Issue by GreenGremlin** [strapi/strapi#201]
node v7.9.0 (npm v4.2.0)
strapi alpha.4 (from github)
os macOS 10.12.4

I installed Strapi by
- cloning the github repo
- checking out the alpha.4 branch
- running `npm install` && `npm run setup`

I made strapi globally available by running `cd packages/strapi` && `npm link`

I then created a new strapi project by running `strapi new strapiTest` && `cd strapiTest`

I ran `strapi run` and verified the server loaded by visiting `http://localhost:1337`

Lastly I created an api by running `strapi generate:api blarg` and got the following error in the server console. When I restart the server I get the same error, minus the first line.

```
(node:31646) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
error: The hook `mongoose` failed to load (in `external`)!
error:  MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/jonathan/code/github/strapi/packages/strapi-mongoose/node_modules/mongodb-core/lib/topologies/server.js:327:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (/Users/jonathan/code/github/strapi/packages/strapi-mongoose/node_modules/mongodb-core/lib/connection/pool.js:274:12)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at Socket.<anonymous> (/Users/jonathan/code/github/strapi/packages/strapi-mongoose/node_modules/mongodb-core/lib/connection/connection.js:177:49)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by GreenGremlin** [comment]
I also get "not found" when refreshing the page

**Comment by Aurelsicoko** [comment]
It seems that you forgot to launch a MongoDB instance? If this is not the case, please check that the connection name is the correct one in your `Blarg.settings.json` file.

**Comment by GreenGremlin** [comment]
Is that mentioned in the documentation? I don't recall seeing that.

**Comment by Aurelsicoko** [comment]
@GreenGremlin I don't think this is mentioned in the documentation because there is no documentation for the v3 (not released yet). Does it work when you run a MongoDB instance?

**Comment by Aurelsicoko** [comment]
I'm closing this issue because of lack of activity. The issue has been fixed in the latest releases.

**Comment by kgrosvenor** [comment]
This is happening to me in v3

**Comment by kgrosvenor** [comment]
Error log

```
0|strapi   | npm ERR! file sh
0|strapi   | npm ERR! code ELIFECYCLE
0|strapi   | npm ERR! errno ENOENT
0|strapi   | npm ERR! syscall spawn
0|strapi   | npm ERR! strapi@0.1.0 start: `strapi start`
0|strapi   | npm ERR! spawn ENOENT
0|strapi   | npm ERR!
0|strapi   | npm ERR! Failed at the strapi@0.1.0 start script.
0|strapi   | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
0|strapi   |
0|strapi   | npm ERR! A complete log of this run can be found in:
0|strapi   | npm ERR!     /home/ubuntu/.npm/_logs/2019-11-20T00_07_52_255Z-debug.log
0|strapi   | (node:20007) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 topologyDescriptionChanged listeners added. Use emitter.setMaxListeners() to increase limit
0|strapi   | (node:3451) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 topologyDescriptionChanged listeners added. Use emitter.setMaxListeners() to increase limit
0|strapi   | (node:652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 topologyDescriptionChanged listeners added. Use emitter.setMaxListeners() to increase limit

/home/ubuntu/.pm2/logs/strapi-out.log last 15 lines:
0|strapi   |     at tryOnTimeout (timers.js:300:5)
0|strapi   |     at listOnTimeout (timers.js:263:5)
0|strapi   |     at Timer.processTimers (timers.js:223:10)
0|strapi   | [2020-01-13T19:08:50.315Z] error MongoTimeoutError: Server selection timed out after 30000 ms
0|strapi   |     at Timeout.setTimeout [as _onTimeout] (/home/ubuntu/headmastershairteam-api/node_modules/mongodb/lib/core/sdam/topology.js:850:16)
0|strapi   |     at ontimeout (timers.js:436:11)
0|strapi   |     at tryOnTimeout (timers.js:300:5)
0|strapi   |     at listOnTimeout (timers.js:263:5)
0|strapi   |     at Timer.processTimers (timers.js:223:10)
0|strapi   | [2020-01-13T19:09:27.082Z] error MongoTimeoutError: Server selection timed out after 30000 ms
0|strapi   |     at Timeout.setTimeout [as _onTimeout] (/home/ubuntu/headmastershairteam-api/node_modules/mongodb/lib/core/sdam/topology.js:850:16)
0|strapi   |     at ontimeout (timers.js:436:11)
0|strapi   |     at tryOnTimeout (timers.js:300:5)
0|strapi   |     at listOnTimeout (timers.js:263:5)
0|strapi   |     at Timer.processTimers (timers.js:223:10)

0|strapi  | [2020-01-13T19:15:07.688Z] error MongoTimeoutError: Server selection timed out after 30000 ms
0|strapi  |     at Timeout.setTimeout [as _onTimeout] (/home/ubuntu/headmastershairteam-api/node_modules/mongodb/lib/core/sdam/topology.js:850:16)
0|strapi  |     at ontimeout (timers.js:436:11)
0|strapi  |     at tryOnTimeout (timers.js:300:5)
0|strapi  |     at listOnTimeout (timers.js:263:5)
0|strapi  |     at Timer.processTimers (timers.js:223:10)
```
