### ISSUE TITLE
500 server error while trying to upload images with cloudinary configaration

### ISSUE THREAD

**Issue by cliffgor** [strapi/strapi#20110]
### Required System information

- Node.js version:*20.11.0*
- NPM version:*10.2.4*
- Strapi version:*4.23.0*
- Database:*postgres supabase*
- Operating system: *linux*
- Is your project Javascript or Typescript: *Javascript*

### Describe the bug

I am trying to add cloudinary to my strapi backend but it's not working. I have followed the documentation even changed cloudinary keys but still nothing works and i get an error when uploading an image from the media library error: Error uploading to cloudinary:  Error: Error uploading to cloudinary: 

I have tried following up on the documentation but still nothing works

This is the error I am getting from my terminal

[2024-04-14 14:39:51.051] error: Error uploading to cloudinary: Error: Error uploading to cloudinary: at /home/cliff/Documents/projects/daktari-admin/node_modules/@strapi/provider-upload-cloudinary/dist/index.js:47:22 at /home/cliff/Documents/projects/daktari-admin/node_modules/cloudinary/lib/utils/index.js:1354:14 at handle_response (/home/cliff/Documents/projects/daktari-admin/node_modules/cloudinary/lib/uploader.js:486:7) at ClientRequest. (/home/cliff/Documents/projects/daktari-admin/node_modules/cloudinary/lib/uploader.js:603:12) at ClientRequest.emit (node:events:530:35) at ClientRequest.emit (node:domain:488:12) at TLSSocket.socketErrorListener (node:_http_client:495:9) at TLSSocket.emit (node:events:518:28) at TLSSocket.emit (node:domain:488:12) at emitErrorNT (node:internal/streams/destroy:169:8) [2024-04-14 14:39:51.052] http: POST /upload (3646 ms) 500

https://market.strapi.io/providers/@strapi-provider-upload-cloudinary

### Code snippets
- Plugins.js file

``` 
module.exports = ({ env }) => ({    
    upload: {
        config: {
            provider: 'cloudinary',
            providerOptions: {
                cloud_name: env('CLOUDINARY_NAME'),
                api_key: env('CLOUDINARY_KEY'),
                api_secret: env('CLOUDINARY_SECRET'),
            },
            actionOptions: {
                upload: {},
                uploadStream: {},
                delete: {},
            },
        },
    },

});

```

- middleware.js file 

```
module.exports = [
  'strapi::logger',
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', 'market-assets.strapi.io', 'res.cloudinary.com'],
          'media-src': [
            "'self'",
            'data:',
            'blob:',
            'market-assets.strapi.io',
            'res.cloudinary.com',
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',

];

```

**Comment by cliffgor** [comment]
I wish to close this issue since I was able to make it work. With this, I did the manual setup which I was adding my supabase database credentials maybe that tempered with something. On the second attempt I just added the `node-progress` package and then added my database configurations. 

From the database file in config, I also removed the other databases and remained only with Postgres

**Comment by cliffgor** [comment]
I am reopening this issue since i have faced it again with a production build on render which returned a memory leak. I suspect a bug on the cloudinary provider

**Comment by znwhite** [comment]
Experiencing same thing. What is the solution here?

**Comment by gopichandreddy001** [comment]
Experiencing same issue, any updates?

**Comment by BetCareCasino** [comment]
I’m having the same problem — a 500 error. When I first connected Cloudinary to Strapi on Railway, everything was working on the first day. But the next day, I started getting a 500 error with any operation involving images.

**Comment by anastasiiaxfr** [comment]
When Strapi is running locally in development mode, with PostgreSQL connected via Railway and Cloudinary as well — everything loads. But when I go to the Strapi admin panel on Railway as a super admin, the images fail with a 500 error.

**Comment by Masterprecie** [comment]
> I am having same issue with cloudinary upload. Everything works well on development but gets a 500 error on production

I have figured this out. It turns out there was an issue with the env variables on production hence the initial 500 error response

**Comment by alexandrebodin** [comment]
if some of you are still facing errors we need the logs and the configurations you are using and more reproduction information to help you. this looks to be configuration problems and not a strapi problem directly.

**Comment by anastasiiaxfr** [comment]
This issue in Strapi occurs because of the secret key used to sign images — there was information like that in the Railway logs. Or it might be because either Railway or Cloudinary has some kind of sleep period during which they take a long time to send and receive requests — something like that. I have the correct env variables on Railway. The error resolved itself in the evening, and I don’t understand how.
