### ISSUE TITLE
Can not load one to many relations in content  manager

### ISSUE THREAD

**Issue by Marc-Roig** [strapi/strapi#20117]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Yarn version: 1.22.17
- Strapi version: 5.0.0-beta.4
- Database: sqlite
- Operating system: MacOs
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have a one to many relation that can not be loaded in the content manager,

The server throws an error everytime it tries to load it:
```
[2024-04-15 13:33:42.724] error: select `t0`.`id`, `t0`.`document_id`, `t0`.`name`, `t0`.`published_at`, `t0`.`updated_at`, `t0`.`locale` from `dogs` as `t0` where ((((`t0`.`locale` in ('en', 'es')))) and (`t0`.`locale` = 'en' and `t0`.`id` not in (select `t1`.`id` from `breeds` as `t0` where (`t1`.`id` is not null and `t1`.`document_id` is not null and `t0`.`document_id` = 'oo45h3ozvbui1y0ztd0fhba8' and `t1`.`locale` = 'en')))) order by `t0`.`name` asc limit 10 - no such column: t1.id
SqliteError: select `t0`.`id`, `t0`.`document_id`, `t0`.`name`, `t0`.`published_at`, `t0`.`updated_at`, `t0`.`locale` from `dogs` as `t0` where ((((`t0`.`locale` in ('en', 'es')))) and (`t0`.`locale` = 'en' and `t0`.`id` not in (select `t1`.`id` from `breeds` as `t0` where (`t1`.`id` is not null and `t1`.`document_id` is not null and `t0`.`document_id` = 'oo45h3ozvbui1y0ztd0fhba8' and `t1`.`locale` = 'en')))) order by `t0`.`name` asc limit 10 - no such column: t1.id
    at Database.prepare (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:34)
    at executeQuery (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/knex/lib/client.js:154:12)
    at Runner.query (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/knex/lib/execution/runner.js:141:36)
    at ensureConnectionCallback (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/knex/lib/execution/runner.js:318:20)
    at async Runner.run (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.execute (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/@strapi/database/dist/index.js:4559:22)
    at async Object.findMany (/Users/marcroig/Documents/strapi/releases/test-history/node_modules/@strapi/database/dist/index.js:5185:22)
```

### Steps to reproduce the behavior

- Create a content type with a one to many relation (no d&P and i18n enabled on it)
- Try to create a relation
- You will see thee 500 status error when loading that relation.

**Comment by Marc-Roig** [comment]
This error seems to be fixed and I can not reproduce it anymore, feel free to ping this thread if  you continue to see this issue.
