### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'kind') when trying to create a new content type from dashboard or command line.

### ISSUE THREAD

**Issue by palashCItobuz** [strapi/strapi#20127]
### Required System information

- Node.js version: 20.11
- NPM version: 10.2.4
- Strapi version: 4.20
- Database: postgres
- Operating system: IOS
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

1. Go to 'Content-Type Builder'
2. Click on 'Create new collection type'
3. Create new collection type

### Expected behavior

A new content type created with it's associated files in the api folder, entry in the database and types in the contentTypes.d.ts file.

### Error shows instead:
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                             │
│   TypeError: Cannot read properties of undefined (reading 'kind')                                                                           │
│       at Module.isSingleType (/Users/itobuz/Development/testtrou/node_modules/@strapi/utils/dist/index.js:771:25)                           │
│       at Module.createRoutes (/Users/itobuz/Development/testtrou/node_modules/@strapi/strapi/dist/core-api/routes/index.js:5:32)            │
│       at get routes [as routes] (/Users/itobuz/Development/testtrou/node_modules/@strapi/strapi/dist/factories.js:63:39)                    │
│       at /Users/itobuz/Development/testtrou/node_modules/@strapi/strapi/dist/services/server/register-routes.js:67:14                       │
│       at /Users/itobuz/Development/testtrou/node_modules/lodash/lodash.js:4967:15                                                           │
│       at baseForOwn (/Users/itobuz/Development/testtrou/node_modules/lodash/lodash.js:3032:24)                                              │
│       at /Users/itobuz/Development/testtrou/node_modules/lodash/lodash.js:4936:18                                                           │
│       at Function.forEach (/Users/itobuz/Development/testtrou/node_modules/lodash/lodash.js:9410:14)                                        │
│       at registerAPIRoutes (/Users/itobuz/Development/testtrou/node_modules/@strapi/strapi/dist/services/server/register-routes.js:65:24)   │
│       at registerAllRoutes (/Users/itobuz/Development/testtrou/node_modules/@strapi/strapi/dist/services/server/register-routes.js:19:3)    │
│                                                                                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by palashCItobuz** [comment]
Hi, I was able to figure out the issue. The issue for me was due to `"resolveJsonModule": false` in `tsconfig.json` file. Once I enabled it and rebuilt everything the issue was resolved. So leaving the message here as it might be helpful for others facing similar issue.
