### ISSUE TITLE
An error occurred during when new project ....

### ISSUE THREAD

**Issue by Restry** [strapi/strapi#2022]
new project ......

An error occurred during settings-manager plugin installation.

**Informations**
- **Node.js version**: 9.0
- **npm version**: 5.5.1
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: mongo 2.6.10
- **Operating system**: mac 10.13.4

**What is the current behavior?**
strapi new projectname

**Steps to reproduce the problem**
strapi new projectname

`
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
⚠ An error occurred during settings-manager plugin installation.
{ Error: Command failed: node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install settings-manager
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/settings-manager/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at touchFile (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:67:19)
    at /Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/restry/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:135:13)
    at Command.emit (events.js:224:7)

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install settings-manager ' }
⚠ An error occurred during content-type-builder plugin installation.
{ Error: Command failed: node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install content-type-builder
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/content-type-builder/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at touchFile (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:67:19)
    at /Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/restry/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:135:13)
    at Command.emit (events.js:224:7)

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install content-type-builder ' }
⚠ An error occurred during content-manager plugin installation.
{ Error: Command failed: node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install content-manager
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/content-manager/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at touchFile (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:67:19)
    at /Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/restry/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:135:13)
    at Command.emit (events.js:224:7)

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install content-manager ' }
⚠ An error occurred during users-permissions plugin installation.
{ Error: Command failed: node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install users-permissions
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/users-permissions/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at touchFile (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:67:19)
    at /Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/restry/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:135:13)
    at Command.emit (events.js:224:7)

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install users-permissions ' }
⚠ An error occurred during email plugin installation.
{ Error: Command failed: node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install email
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/email/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at touchFile (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:67:19)
    at /Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/restry/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:135:13)
    at Command.emit (events.js:224:7)

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install email ' }
⚠ An error occurred during upload plugin installation.
{ Error: Command failed: node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install upload
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/upload/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at touchFile (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:67:19)
    at /Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/restry/.config/yarn/global/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/restry/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:135:13)
    at Command.emit (events.js:224:7)

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /Users/restry/.config/yarn/global/node_modules/strapi/bin/strapi.js install upload ' }
✔ Link strapi dependency to the project.

`

**What is the expected behavior?**

how can i fix it ....

**Suggested solutions**

**Comment by Restry** [comment]
难道没人觉得这个项目实在是很浪费人的时间吗? 虽然功能看似非常好.

**Comment by derrickmehaffy** [comment]
@Restry please use english for all issues and updates.

Also can you please use code blocks.

**Comment by derrickmehaffy** [comment]
Yarn support is minimal, please use node to setup, install, and create a new project.

**Comment by henrych4** [comment]
Hi @Restry, I suggest you take some time to read the requirement of strapi before posting a new issue.
As stated [here](https://github.com/strapi/strapi#getting-started), minimum requirements are:

Node:
 * NodeJS >= 10.x
 * NPM >= 6.x

Database:
 * MongoDB >= 3.x 
 * MySQL >= 5.6
 * MariaDB >= 10.1
 * PostgreSQL >= 10

Therefore you may try upgrading node, npm and mongodb to latest version and see whether the problem still exists.

**Comment by Restry** [comment]
@henrych4  https://strapi.io/documentation/getting-started/installation.html#requirements i have find the requirement here .  it there no update ?

**Comment by derrickmehaffy** [comment]
@Restry those are not updated, please use the ones on this githubs README.md

**Comment by Restry** [comment]
@derrickmehaffy thanks for your reply . I tried this product six months ago, and there are various problems. lose the data or not update it, so I complained. Sorry.   

but  it's really , the function of this product is very useful

**Comment by Restry** [comment]
okay , i'll try again with npm . 

 I have been looking for such a tool, maybe it was too high for me before.

**Comment by Restry** [comment]
@derrickmehaffy Which version is the most stable? I want to use it in the project to be carried out immediately.

**Comment by derrickmehaffy** [comment]
@Restry Always use the latest, since Strapi is still alpha you should try and upgrade when you can. Current release was today Strapi v3.0.0-alpha.14.2

**Comment by derrickmehaffy** [comment]
Note that bug reports on previous versions, you will always be asked to update to the latest.

**Comment by Restry** [comment]
ok thanks :) 👍

**Comment by caoer** [comment]
@derrickmehaffy I can confirm that it is also not working in node 10.4.1, npm 6.1

```
➜ strapi new myYproject
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
? Choose your main database: MongoDB (recommended)
? Database name: myYproject
? Host: 127.0.0.1
? +srv connection: false
? Port (It will be ignored if you enable +srv): 27017
? Username:
? Password:
? Authentication database (Maybe "admin" or blank):
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
⚠ An error occurred during settings-manager plugin installation.
{ Error: Command failed: node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install settings-manager
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/settings-manager/package.json'
    at Object.fs.openSync (fs.js:579:3)
    at touchFile (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:67:19)
    at /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install settings-manager ' }
⚠ An error occurred during content-type-builder plugin installation.
{ Error: Command failed: node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install content-type-builder
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/content-type-builder/package.json'
    at Object.fs.openSync (fs.js:579:3)
    at touchFile (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:67:19)
    at /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install content-type-builder ' }
⚠ An error occurred during content-manager plugin installation.
{ Error: Command failed: node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install content-manager
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/content-manager/package.json'
    at Object.fs.openSync (fs.js:579:3)
    at touchFile (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:67:19)
    at /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install content-manager ' }
⚠ An error occurred during users-permissions plugin installation.
{ Error: Command failed: node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install users-permissions
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/users-permissions/package.json'
    at Object.fs.openSync (fs.js:579:3)
    at touchFile (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:67:19)
    at /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install users-permissions ' }
⚠ An error occurred during email plugin installation.
{ Error: Command failed: node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install email
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/email/package.json'
    at Object.fs.openSync (fs.js:579:3)
    at touchFile (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:67:19)
    at /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install email ' }
⚠ An error occurred during upload plugin installation.
{ Error: Command failed: node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install upload
usage: mkdir [-pv] [-m mode] directory ...
ShellJS: internal error
Error: ENOENT: no such file or directory, open './plugins/upload/package.json'
    at Object.fs.openSync (fs.js:579:3)
    at touchFile (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:67:19)
    at /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:46:5
    at Array.forEach (<anonymous>)
    at Object._touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/touch.js:45:9)
    at Object.touch (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/shelljs/src/common.js:399:25)
    at Command.module.exports (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi-install.js:65:13)
    at Command.listener (/Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/caoer115/.nvm/versions/node/v10.4.1/lib/node_modules/strapi/bin/strapi.js install upload ' }

👌 Your new application myYproject is ready at /Users/caoer115/Documents/Projects/yicai/sales-bot/webs/backend/adlfjs/myYproject.

⚡️ Change directory:
$ cd myYproject

⚡️ Start application:
$ strapi start

```

**Comment by caoer** [comment]
and it success with node 10.11.0

**Comment by derrickmehaffy** [comment]
That is really odd.... Either way if it is working on a newer version of node then the issue wasn't with Strapi in this case.

**Comment by johnnypenggg** [comment]
Is it cause by the reason below? 
==
(node:51266) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, **unlink '/Users/johnny/Documents/workspaces/nodes_proj/strtest/myproj2/admin/.gitignore'**
    at Object.unlinkSync (fs.js:952:3)
    at copyFileSync (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-admin/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:15:10)
    at Object.copySync (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-admin/node_modules/fs-extra/lib/copy-sync/copy-sync.js:43:5)
    at module.exports (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-admin/lib/after.js:21:6)
    at async.each.err (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate/lib/generate.js:150:16)
    at /usr/local/lib/node_modules/strapi/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/usr/local/lib/node_modules/strapi/node_modules/async/dist/async.js:1057:9)
    at eachOf (/usr/local/lib/node_modules/strapi/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/usr/local/lib/node_modules/strapi/node_modules/async/dist/async.js:3172:5)
    at Function.success (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate/lib/generate.js:52:13)
    at Object.module.exports [as before] (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-admin/lib/before.js:37:13)
    at generate (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate/lib/generate.js:46:13)
    at async.until.err (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate/lib/target.js:103:14)
    at /usr/local/lib/node_modules/strapi/node_modules/async/dist/async.js:969:16
    at next (/usr/local/lib/node_modules/strapi/node_modules/async/dist/async.js:5225:18)
    at parseTarget (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate/lib/target.js:51:16)
==

**Comment by vedmant** [comment]
I have the same issue tried to install it and got:

```
🏗  Application generation:
✔ Copy dashboard
⚠ An error occurred during settings-manager plugin installation.
- Install settings-manager plugin
✖ An error occurred during plugin installation.

✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
⚠ An error occurred during users-permissions plugin installation.
- Install users-permissions plugin
✖ An error occurred during plugin installation.

✔ Install plugin email.
⚠ An error occurred during upload plugin installation.
- Install upload plugin
✖ An error occurred during plugin installation.
Link strapi dependency to the project.

👌 Your new application strapi is ready at /Users/vedmant/Projects/_Test/strapi.

⚡️ Change directory:
$ cd strapi

⚡️ Start application:
$ strapi start

(node:99717) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/Users/iam/Projects/_Test/strapi/plugins/users-permissions/config/functions/bootstrap.js:167:48)
(node:99717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99717) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-15T16:36:29.935Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-03-15T16:36:29.937Z] warn Perhaps you forgot to call it?
```

node v10.15.1
npm 6.4.1

**Comment by chaomediashaker** [comment]
Also same error with @vedmant  here 

node v10.15.3
npm 6.4.1
