### ISSUE TITLE
New project creation fails with type error

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#20232]
### Required System information

- Node.js version: v20.12.2 (nvm)
- NPM version: v10.5.0 (nvm)
- Strapi version: v4.24.0
- Database: SQLite
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When trying to create a new project using `npm create-strapi-app@latest my-api` or `yarn create strapi-app@latest my-api` the project initialization fails after choosing the quickstart option. Following error is displayed for me:

```text
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /Users/fabio_nettis/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/Users/fabio_nettis/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
    at createProject (/Users/fabio_nettis/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createQuickStartProject (/Users/fabio_nettis/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:18:3)
```

### Steps to reproduce the behavior

1. Run `yarn create strapi-app@latest my-api` 
2. Choose the quickstart option
3. See error

### Expected behavior

The project should be created without any error, or display a more consice description of  what the problem is.

**Comment by aminajao** [comment]
Having the same issue creating a strapi project without the quickstart option, but with a different error

success Installed "create-strapi-app@4.24.1" with binaries:

const stripAnsi = require('strip-ansi');

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/bilal/.config/yarn/global/node_modules/strip-ansi/index.js from /Users/bilal/.config/yarn/global/node_modules/ora/index.js not supported.

**Comment by num13ru** [comment]
The same thing happens when creating a project
```
Creating a project with custom database options.
Creating a new Strapi application at /Users/user/GIT/hello-world-strapi.
Creating files.
Error while installing dependencies:
error An unexpected error occurred: "Invalid URL".
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /Users/user/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/Users/user/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
    at createProject (/Users/user/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

**Comment by creotip** [comment]
i have the following error while creating new project according to the docs:
Creating a quickstart project.
Creating a new Strapi application at /Users/ruslanelishaev/Desktop/projects/jsonserve-new.
Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: jsonserve-new@0.1.0
npm ERR! Found: @strapi/strapi@undefined
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"4.24.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.0.0" from @strapi/plugin-i18n@4.24.2
npm ERR! node_modules/@strapi/plugin-i18n
npm ERR!   @strapi/plugin-i18n@"4.24.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/ruslanelishaev/.npm/_logs/2024-05-09T09_14_18_011Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/ruslanelishaev/.npm/_logs/2024-05-09T09_14_18_011Z-debug-0.log
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')

**Comment by liweikui** [comment]
I get the same error in Ubuntu20.02.

**Comment by lwiklander** [comment]
I got this error as well, it seems to have sorted itself out after I uninstalled yarn classic from my global npm packages.
I enabled corepack as well.

Now the installation finished without errors and started the strapi app as expected.
