### ISSUE TITLE
[BUG] Populating locales programatically breaks the admin

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#20253]
### Required System information

- Environment: development
- OS: linux-x64
- Strapi Version: 5.0.0-beta.5
- Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
- Edition: Community
- Database: sqlite
- Typescript

### Describe the bug

We are using the following code to add locales to our project:
```ts title="addLocales.ts"
import { Core } from "@strapi/strapi";

type StrapiLocale = { code: string; name: string; isDefault?: boolean };

const locales: Array<StrapiLocale> = [
  { code: "es", name: "Spanish (es)" },
  { code: "tr", name: "Turkish (tr)" },
];

async function addLocale(locale: StrapiLocale, strapi: Core.Strapi) {
  const { code, name, isDefault = false } = locale;

  try {
    const existingLocale = await strapi
      .plugin("i18n")
      .service("locales")
      .findByCode(code);

    if (!existingLocale) {
      await strapi.plugin("i18n").service("locales").create({
        name,
        code,
        isDefault,
      });
      console.log(`Locale ${code} added successfully.`);
    } else {
      console.log(`Locale ${code} already exists.`);
    }
  } catch (error) {
    console.error(`Error adding locale ${code}:\n`, error);
  }
}

export const addLocales = async (strapi: Core.Strapi) => {
  console.info("\nAdding given locales to the admin.\n");

  for (const locale of locales) {
    await addLocale(locale, strapi);
  }

  console.info("\nLocales have been set up!");
};
```

And the following goes on the `index` bootstrap function:
```ts
  async bootstrap({ strapi }: { strapi: Core.Strapi }) {
    await createMediaFolders(strapi);
    await addLocales(strapi);
  },
```

When running the first time it gives the following issue:
 ```shell
 yarn develop                                                                                            ✔  20.12.2  
✔ Cleaning dist dir (23ms)
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (211ms)
✔ Creating admin (916ms)
⠧ Loading Strapi
Creating media folders based on given paths.

Folder '/posts' already exists.
Folder 'posts/hero' already exists.
Folder 'hero/images' already exists.
Folder '/posts' already exists.
Folder 'posts/hero' already exists.
Folder 'hero/videos' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/audios' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/files' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/images' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/videos' already exists.
Folder '/profiles' already exists.
Folder 'profiles/photos' already exists.

Media folders have been set up!

Adding given locales to the admin.

Error adding locale es:
 ApplicationError: No action found with id "admin::marketplace.read"
    at Object.appliesToProperty (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/admin/server/src/domain/action/provider.ts:54:15)
    at <anonymous> (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/permissions/actions.ts:56:61)
    at Array.map (<anonymous>)
    at addAllLocalesToPermissions (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/permissions/actions.ts:53:17)
    at Object.syncSuperAdminPermissionsWithLocales (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/permissions/actions.ts:91:36)
    at Object.afterCreate (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/bootstrap.ts:9:7)
    at async Object.run (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/database/dist/index.js:6375:11)
    at async Object.create (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/database/dist/index.js:5221:7)
    at Object.create (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/locales.ts:16:18)
    at async addLocale (/home/luisalaguna/Projects/experiments/strapi-template/dist/src/functions/addLocales.js:16:13) {
  details: {}
}
Error adding locale tr:
 ApplicationError: No action found with id "admin::marketplace.read"
    at Object.appliesToProperty (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/admin/server/src/domain/action/provider.ts:54:15)
    at <anonymous> (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/permissions/actions.ts:56:61)
    at Array.map (<anonymous>)
    at addAllLocalesToPermissions (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/permissions/actions.ts:53:17)
    at Object.syncSuperAdminPermissionsWithLocales (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/permissions/actions.ts:91:36)
    at Object.afterCreate (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/bootstrap.ts:9:7)
    at async Object.run (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/database/dist/index.js:6375:11)
    at async Object.create (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/database/dist/index.js:5221:7)
    at Object.create (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/server/src/services/locales.ts:16:18)
    at async addLocale (/home/luisalaguna/Projects/experiments/strapi-template/dist/src/functions/addLocales.js:16:13) {
  details: {}
}

Locales have been set up!
✔ Loading Strapi (4583ms)
✔ Generating types (1350ms)
✔ Cleaning dist dir (61ms)
✔ Compiling TS (7396ms)

 Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Mon Apr 29 2024 00:15:04 GMT-0500 (Colombia Sta… │
│ Launched in        │ 13368 ms                                         │
│ Environment        │ development                                      │
│ Process PID        │ 3069582                                          │
│ Version            │ 5.0.0-beta.5 (node v20.12.2)                     │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available                                                            

Welcome back!
To access the server ⚡️, go to:
http://localhost:1337

[2024-04-29 00:15:04.060] info: Strapi started successfully
[2024-04-29 00:22:23.626] http: GET /admin (123 ms) 200
[2024-04-29 00:22:25.155] http: GET /admin/project-type (18 ms) 200
[2024-04-29 00:22:25.682] http: GET /admin/init (10 ms) 200
[2024-04-29 00:22:25.755] http: GET /admin/users/me (66 ms) 200
[2024-04-29 00:22:25.794] http: POST /admin/renew-token (35 ms) 200
[2024-04-29 00:22:25.873] http: GET /admin/users/me/permissions (71 ms) 200
[2024-04-29 00:22:26.031] http: GET /admin/information (87 ms) 200
[2024-04-29 00:22:26.036] http: GET /admin/telemetry-properties (46 ms) 200
[2024-04-29 00:22:26.251] http: GET /content-manager/content-types (41 ms) 200
... (7 lines left)
```

Despite this, the locales are added, but it breaks the admin when browsing on the settings section, see the video.

What's the better way to add locales to the admin programmatically?

### Steps to reproduce the behavior

1. Write the function.
2. Import it on the `index` file in the bootstrap function.
3. Run the development server.
4. Check the logs.

### Expected behavior
It should not give any error logs nor break the admin panel.

### Screenshots

![AdminBrokenAfterLoadingLocales](https://github.com/strapi/strapi/assets/5034215/4e043f42-7c28-4e64-a1af-4a268fd359d8)

### Additional context

In the latest Strapi v4 there is not such issue.

**Comment by burakozdemir32** [comment]
I am experiencing the same exact issue. Doesn't happen on local environment, but on staging.

**Comment by burakozdemir32** [comment]
```
strapi    | /app/node_modules/.pnpm/@strapi+admin@5.0.0-beta.7_@babel+runtime@7.24.5_@codemirror+autocomplete@6.16.0_@codemirror+_whs44xiiiegseiyf5ydzqk7w64/node_modules/@strapi/admin/dist/server/index.js:2384
strapi    |         throw new ApplicationError$5(`No action found with id "${actionId}"`);
strapi    |               ^
strapi    | 
strapi    | ApplicationError: No action found with id "admin::marketplace.read"
strapi    |     at Object.appliesToProperty (/app/node_modules/.pnpm/@strapi+admin@5.0.0-beta.7_@babel+runtime@7.24.5_@codemirror+autocomplete@6.16.0_@codemirror+_whs44xiiiegseiyf5ydzqk7w64/node_modules/@strapi/admin/dist/server/index.js:2384:15)
strapi    |     at /app/node_modules/.pnpm/@strapi+i18n@5.0.0-beta.7_@babel+runtime@7.24.5_@codemirror+autocomplete@6.16.0_@codemirror+l_q37lqclkmsncmumys5qbd7y6ii/node_modules/@strapi/i18n/dist/server/index.js:2791:61
strapi    |     at Array.map (<anonymous>)
strapi    |     at addAllLocalesToPermissions (/app/node_modules/.pnpm/@strapi+i18n@5.0.0-beta.7_@babel+runtime@7.24.5_@codemirror+autocomplete@6.16.0_@codemirror+l_q37lqclkmsncmumys5qbd7y6ii/node_modules/@strapi/i18n/dist/server/index.js:2789:18)
strapi    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
strapi    |     at async Object.syncSuperAdminPermissionsWithLocales (/app/node_modules/.pnpm/@strapi+i18n@5.0.0-beta.7_@babel+runtime@7.24.5_@codemirror+autocomplete@6.16.0_@codemirror+l_q37lqclkmsncmumys5qbd7y6ii/node_modules/@strapi/i18n/dist/server/index.js:2818:36)
strapi    |     at async Object.afterDelete (/app/node_modules/.pnpm/@strapi+i18n@5.0.0-beta.7_@babel+runtime@7.24.5_@codemirror+autocomplete@6.16.0_@codemirror+l_q37lqclkmsncmumys5qbd7y6ii/node_modules/@strapi/i18n/dist/server/index.js:39:7)
strapi    |     at async Object.run (/app/node_modules/.pnpm/@strapi+database@5.0.0-beta.7_@types+node@20.12.12_mysql2@3.9.7/node_modules/@strapi/database/dist/index.js:6382:11)
strapi    |     at async Object.delete (/app/node_modules/.pnpm/@strapi+database@5.0.0-beta.7_@types+node@20.12.12_mysql2@3.9.7/node_modules/@strapi/database/dist/index.js:5330:7)
strapi    |     at async Object.deleteFn [as delete] (/app/node_modules/.pnpm/@strapi+i18n@5.0.0-beta.7_@babel+runtime@7.24.5_@codemirror+autocomplete@6.16.0_@codemirror+l_q37lqclkmsncmumys5qbd7y6ii/node_modules/@strapi/i18n/dist/server/index.js:2991:20) {
strapi    |   details: {}
strapi    | }
strapi    | 
strapi    | Node.js v20.10.0
strapi    |  ELIFECYCLE  Command failed with exit code 1.
strapi exited with code 0
```

**Comment by burakozdemir32** [comment]
Hey!

Maybe this could help. The issue only happens if you have a DB that was created in Strapi v4 or earlier. It doesn't happen with a fresh DB.

**Comment by SalahAdDin** [comment]
It happened to me in a fresh database.

**Comment by alexandrebodin** [comment]
@SalahAdDin is this something you were able to do in v4 the exact same way ?

**Comment by alexandrebodin** [comment]
This will be fixed in the next beta :)

**Comment by SalahAdDin** [comment]
@alexandrebodin Confirmed, it is fixed.
