### ISSUE TITLE
Error: read ECONNRESET Strapi container

### ISSUE THREAD

**Issue by vadim-ostafiychuk** [strapi/strapi#20311]
### Required System information

- Node.js version: v18.20.2
- NPM version: - 
- Strapi version: 4.20.2
- Database:  mysql:5.7
- Operating system: CentOS-84-64-minimal
- Is your project Javascript or Typescript: Javascript

### Describe the bug

At midnight the container crashes with the following error

2024-05-15T00:00:00.016533796Z node:internal/process/promises:288
2024-05-15T00:00:00.016544276Z             triggerUncaughtException(err, true /* fromPromise */);
2024-05-15T00:00:00.016549093Z             ^
2024-05-15T00:00:00.016553076Z 
2024-05-15T00:00:00.016557041Z Error: read ECONNRESET
2024-05-15T00:00:00.016561139Z     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2024-05-15T00:00:00.016564926Z     at TCP.callbackTrampoline (node:internal/async_hooks:128:17)
2024-05-15T00:00:00.016568728Z     --------------------
2024-05-15T00:00:00.016572518Z     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2024-05-15T00:00:00.016576492Z     at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
2024-05-15T00:00:00.016581013Z     at /app/node_modules/knex/lib/dialects/mysql/index.js:132:18
2024-05-15T00:00:00.016585283Z     at new Promise (<anonymous>)
2024-05-15T00:00:00.016589307Z     at Client_MySQL._query (/app/node_modules/knex/lib/dialects/mysql/index.js:126:12)
9808
2024-05-15T00:00:00.016593301Z     at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
9809
2024-05-15T00:00:00.016597075Z     at Client_MySQL.query (/app/node_modules/knex/lib/client.js:154:12)
9810
2024-05-15T00:00:00.016600912Z     at Runner.query (/app/node_modules/knex/lib/execution/runner.js:141:36)
9811
2024-05-15T00:00:00.016604790Z     at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
9812
2024-05-15T00:00:00.016608683Z     at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:318:20)
9813
2024-05-15T00:00:00.016612722Z Emitted 'error' event on Job instance at:
9814
2024-05-15T00:00:00.016616496Z     at /app/node_modules/node-schedule/lib/Invocation.js:277:17
9815
2024-05-15T00:00:00.016628947Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
9816
2024-05-15T00:00:00.016632585Z   errno: -104,
9817
2024-05-15T00:00:00.016635838Z   code: 'ECONNRESET',
9818
2024-05-15T00:00:00.016638986Z   syscall: 'read',
9819
2024-05-15T00:00:00.016642197Z   fatal: true
9820
2024-05-15T00:00:00.016645438Z }
9821
2024-05-15T00:00:00.016652487Z 
9822
2024-05-15T00:00:00.016655750Z Node.js v18.20.2
9823
2024-05-15T00:00:00.074153449Z error Command failed with exit code 1.
9824
2024-05-15T00:00:00.075963246Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by derrickmehaffy** [comment]
Since you use docker you need to set your pool min to 0 as we mention in the docs: https://docs.strapi.io/dev-docs/configurations/database#database-pooling-options
