### ISSUE TITLE
 Getting 'Error: EBUSY: resource busy or locked, unlink' while trying to upload media in media library in strapi v4.24.2

### ISSUE THREAD

**Issue by girish-soman** [strapi/strapi#20349]
### Required System information

- Node.js version: 20.11.1
- NPM version: 10.2.4
- Strapi version: 4.24.2
- Database: Postgres 15
- Operating system: Windows 11 Pro (win32-x64)
- Is your project Javascript or Typescript: Javascript

### Describe the bug
 Getting Error: EBUSY: resource busy or locked, unlink 'C:\Users\ASUS\AppData\Local\Temp\strapi-upload-33QGrg\optimized-88_C6584_copy_1_2975622f26'
Error: EBUSY: resource busy or locked, unlink 'C:\Users\ASUS\AppData\Local\Temp\strapi-upload-33QGrg\optimized-88_C6584_copy_1_2975622f26'
[2024-05-21 20:28:15.330] http: POST /upload (399 ms) 500

This is happening when I try to upload a file to the media library. Even though I am getting error while uploading, but when I refresh the admin panel I can see the uploaded asset in the media library.

I have tested this on an older version of strapi (4.20.3) and it works fine on it.

Adding the error screenshots from the Browser console and network tabs
Media Library

![image](https://github.com/strapi/strapi/assets/139741810/f88e4789-70fd-4a26-a581-4b96cf461450)

Console Tab errors
![image](https://github.com/strapi/strapi/assets/139741810/128c5a97-16fb-4643-885c-7942f48d6ffd)

![image](https://github.com/strapi/strapi/assets/139741810/38f2e341-ee25-428d-a8a1-3d8c8c172905)

![image](https://github.com/strapi/strapi/assets/139741810/ec1a5f9c-69a2-4ed7-93f1-9a14ff77c816)

Network tab

![image](https://github.com/strapi/strapi/assets/139741810/b942e880-aba7-481c-9be2-d7f46460d1d4)

### Steps to reproduce the behavior

1. Install the above strapi version(4.24.2)
2. Build the admin panel
3. Login into your strapi admin panel and navigate to media-library.
4. Try to upload a new asset to the media library.

### Expected behavior
Strapi should upload the file and should show a thumbnail preview once upload is completed in the media library.

**Comment by gerickehoeksema** [comment]
I'm also facing this error when uploading. I'm trying to upload to Azurite for local development but am unable to test as I encounter this error. Any feedback on this?

**Comment by tro-ggenaud** [comment]
im also facing this error when uploading!

**Comment by GastonAGenaud** [comment]
Same error! 
![image](https://github.com/user-attachments/assets/0f0d5966-bde7-43f6-8a3f-9505888165e3)

**Comment by MehdiRazaNaqvi** [comment]
Same error only when I try to upload .webP format file, other image formats works fine

![image](https://github.com/user-attachments/assets/5bb71d80-fcbc-4d49-ad92-e228dec83c71)

**Comment by derrickmehaffy** [comment]
This is probably an obvious question but all of you hitting this issue I assume are on Windows of some flavor?

Windows is notorious for not allowing multiple applications to access the same file at the same time.

**Comment by giGa-1** [comment]
> Same error only when I try to upload .webP format file, other image formats works fine
> 
> ![image](https://private-user-images.githubusercontent.com/60016135/359912523-5bb71d80-fcbc-4d49-ad92-e228dec83c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Njk5NTksIm5iZiI6MTcyNDg2OTY1OSwicGF0aCI6Ii82MDAxNjEzNS8zNTk5MTI1MjMtNWJiNzFkODAtZmNiYy00ZDQ5LWFkOTItZTIyOGRlYzgzYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4MjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MDdlZTA3YjkyZGJjZTA1YzJjNzcyNmRmOTI4MDQyNTdmNjdhMjAzNTkzMzNiYmM0NDE1OTYxOTMyODVjNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hbXgFlLwk6_aTEzyHoGgdaVmPZ1AUFE-_srh-3XTPc)

.GIF files as well =(

**Comment by giGa-1** [comment]
> This is probably an obvious question but all of you hitting this issue I assume are on Windows of some flavor?
> 
> Windows is notorious for not allowing multiple applications to access the same file at the same time.

But why only certain formats don't work?

**Comment by Jabir-Fulcro** [comment]
Same issue when I try to upload media files ( initially it occured only when I upload webp ) but in some rare cases giving me this same error with png format too

![image](https://github.com/user-attachments/assets/5490a4bf-b7f5-4842-b249-e0a0810ef427)

**Comment by nedagosa-cod** [comment]
> This is probably an obvious question but all of you hitting this issue I assume are on Windows of some flavor?
> 
> Windows is notorious for not allowing multiple applications to access the same file at the same time.

I had this problem a few days ago, and I couldn't stand not being able to load images in the webp format correctly. As "derrickmehaffy" mentioned, Windows uses the Windows temporary folder in the background, just like Strapi uses it to optimize webp images, and Windows doesn't allow two or more applications to use the temporary folder.

The solution I have for now, which is quick, is to install WSL (Windows Subsystem for Linux). It’s easy to install, and you can run the project from WSL; there you won’t have that problem, and you get both Windows and Linux on the same screen.

I should note that this is my first time using Linux (Ubuntu), and it wasn’t difficult.

**Comment by jy1989** [comment]
I also encountered this problem. In my case, when uploading PNGs, some can be uploaded normally while others will report an error. 

`[2025-01-09 11:50:10.502] error: EBUSY: resource busy or locked, unlink 'C:\Users\chen\AppData\Local\Temp\strapi-upload-JOoYqb\optimized-0_671561ee20'
Error: EBUSY: resource busy or locked, unlink 'C:\Users\chen\AppData\Local\Temp\strapi-upload-JOoYqb\optimized-0_671561ee20'
[2025-01-09 11:50:10.503] http: POST /upload (302 ms) 500`

**Comment by jy1989** [comment]
![image](https://github.com/user-attachments/assets/56dbfe68-f346-4e74-ae41-3924239345d7)
When I deleted the file manually, it showed me locked by nodejs.

**Comment by Mohit1310** [comment]
I am also facing this issue now only for webp format images but it was working fine and suddenly started giving this error, in my production, if I upload the webp image I am getting, the below error and the server is restarting again, I am hosting my strapi on digital ocean

```
error: remaining connection slots are reserved for roles with the SUPERUSER attribute
[my-cms] [2025-02-13 09:16:38] error: remaining connection slots are reserved for roles with the SUPERUSER attribute
[my-cms] [2025-02-13 09:16:38]     at Parser.parseErrorMessage (/workspace/node_modules/pg-protocol/dist/parser.js:283:98)
[my-cms] [2025-02-13 09:16:38]     at Parser.handlePacket (/workspace/node_modules/pg-protocol/dist/parser.js:122:29)
[my-cms] [2025-02-13 09:16:38]     at Parser.parse (/workspace/node_modules/pg-protocol/dist/parser.js:35:38)
[my-cms] [2025-02-13 09:16:38]     at TLSSocket.<anonymous> (/workspace/node_modules/pg-protocol/dist/index.js:11:42)
[my-cms] [2025-02-13 09:16:38]     at TLSSocket.emit (node:events:519:28)
[my-cms] [2025-02-13 09:16:38]     at TLSSocket.emit (node:domain:488:12)
[my-cms] [2025-02-13 09:16:38]     at addChunk (node:internal/streams/readable:559:12)
[my-cms] [2025-02-13 09:16:38]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[my-cms] [2025-02-13 09:16:38]     at Readable.push (node:internal/streams/readable:390:5)
[my-cms] [2025-02-13 09:16:38]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)
[my-cms] [2025-02-13 09:16:38] [2025-02-13 09:16:38.520] info: Shutting down Strapi
```

I started getting this issue on strapi 5.9.0 but when I updated to 5.10.2 still my deploy failed and gave this error

```
error: sorry, too many clients already
[2025-02-13 08:56:20] error: sorry, too many clients already
[2025-02-13 08:56:20]     at Parser.parseErrorMessage (/workspace/node_modules/pg-protocol/dist/parser.js:283:98)
[2025-02-13 08:56:20]     at Parser.handlePacket (/workspace/node_modules/pg-protocol/dist/parser.js:122:29)
[2025-02-13 08:56:20]     at Parser.parse (/workspace/node_modules/pg-protocol/dist/parser.js:35:38)
[2025-02-13 08:56:20]     at TLSSocket.<anonymous> (/workspace/node_modules/pg-protocol/dist/index.js:11:42)
[2025-02-13 08:56:20]     at TLSSocket.emit (node:events:519:28)
[2025-02-13 08:56:20]     at TLSSocket.emit (node:domain:488:12)
[2025-02-13 08:56:20]     at addChunk (node:internal/streams/readable:559:12)
[2025-02-13 08:56:20]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[2025-02-13 08:56:20]     at Readable.push (node:internal/streams/readable:390:5)
[2025-02-13 08:56:20]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by RUTENCO** [comment]
12/09/2025, to date the error persists, also as several mentioned, Windows does not allow having the same file open by different processes, which causes the server to crash.

**Comment by respe** [comment]
To reproduce the issue, I simply created a new project in version 5.31.2
with example structure and data.
On Windows. I haven't tested it on Linux.

Then, in the bootstrap function of src/index.ts, I upload a file:
```
async bootstrap() {
    const file = {
      filepath: "./src/image.webp",
      originalFileName: 'image',
      size: 123798,
      mimetype: "image/webp",
    };
    const uploadedFile = await strapi
      .plugin("upload")
      .service("upload")
      .upload({
        files: file,
        data: {
          fileInfo: {
            alternativeText: "image",
            caption: "image",
            name: "image",
          },
        },
      });
  },
```

With a JPEG image, everything works fine. 
But with a WebP image, I get the error:

```
┌───────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                               │
│   Error: EBUSY: resource busy or locked, unlink                                               │
│   'C:\Users\R046F~1.ESP\AppData\Local\Temp\strapi-upload-BMBZKC\optimized-image_08411b9618'   │
│                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Clasen00** [comment]
In 2025 its still here. Windows 10, webp image,  @strapi/strapi": "5.29.0"

<img width="1164" height="107" alt="Image" src="https://github.com/user-attachments/assets/be185cf8-854e-456a-a250-c2044b5e3088" />

**Comment by s4int-man** [comment]
I have the same problem and it happens every time I try to upload 2 images with same name but different extension for example MyImg.png and MyImg.gif
