### ISSUE TITLE
Cannot delete a collection item after renaming a component category

### ISSUE THREAD

**Issue by exoer** [strapi/strapi#20356]
### Required System information
- Node.js version: Now using node v20.13.1 (npm v10.5.2)
- NPM version:10.5.2
- Strapi version: 5-0-8-beta.8
- Database: local development
- Operating system: macos
- Is your project Javascript or Typescript: ts

### Steps to reproduce the behavior

I had a Page collection type with dynamic zones. 
I changed the category name of the components used in the dynamic zones from section.Hero to block.Hero
After that I get `internal server error` when trying to delete a page. 

### Expected behavior

Delete a collection item wil remove it without error 

### Screenshots

[2024-05-23 15:08:54.822] error: Metadata for "sections.hero" not found
Error: Metadata for "sections.hero" not found
    at Metadata.get (xxx/my-project/node_modules/@strapi/database/dist/index.js:2650:13)
    at morphToMany (xxx/my-project/node_modules/@strapi/database/dist/index.js:3528:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async applyPopulate (xxx/my-project/node_modules/@strapi/database/dist/index.js:3655:9)
    at async Object.execute (xxx/my-project/node_modules/@strapi/database/dist/index.js:4570:11)
    at async Object.findMany (xxx/my-project/node_modules/@strapi/database/dist/index.js:5194:22)
    at async xxx/my-project/node_modules/@strapi/database/dist/index.js:6557:21
    at async Array.databaseErrorsMiddleware (xxx/my-project/node_modules/@strapi/core/dist/services/document-service/middlewares/errors.js:13:12)
    at async CollectionTypeService.find (xxx/my-project/node_modules/@strapi/core/dist/core-api/service/collection-type.js:16:21)
    at async Object.find (xxx/my-project/node_modules/@strapi/core/dist/core-api/controller/collection-type.js:16:39)
### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by alexandrebodin** [comment]
@kasonde I think this is also in v4 can you verify this ?

**Comment by Eventyret** [comment]
I can get it try get it verified or verified tomorrow @alexandrebodin

**Comment by Eventyret** [comment]
@exoer could you by any chance provide the schema for this to try replicate this please ?

**Comment by hanpaine** [comment]
@Eventyret we've reproduced in DX - working on a temp fix to prevent data loss now (full fix will be more complex and require rework; this will be picked up at a later date)
