### ISSUE TITLE
REST API filters $contains operator not working in Strapi Cloud environment

### ISSUE THREAD

**Issue by hunganhAtWhill** [strapi/strapi#20367]
### Required System information

- Node.js version: v18.20.3
- NPM version: strapi cloud
- Strapi version: v4.20.5
- Database: strapi cloud
- Operating system: strapi cloud
- Is your project Javascript or Typescript: Typescript

### Describe the bug

In my local environment, I can use /api/my-content?filters[fieldName][$contains]=somevalue without issues, but in Strapi cloud deployed environment /api/my-content?filters[fieldName][$contains]=somevalue returns 500 error. Checking the runtime logs it is saying $contains operator does not exist. I can use /api/my-content?filters[fieldName][$containsi]=somevalue without problem though.
Also, I am using a plugin called [Multi Select Input ](https://market.strapi.io/plugins/strapi-plugin-multi-select) for the field in question 

### Steps to reproduce the behavior

1. Go to https://accidental-loud-pets.strapiapp.com/api/news?locale=en&publicationState=live&filters[categories][$contains]=product
2. Get 500 error
3. Check the runtime logs
4. See the operator not exists error
5. If using $containsi instead of $contains, it works

### Expected behavior

Can use $contains operator

### Screenshots

<img width="978" alt="Screenshot 2024-05-24 at 18 21 32" src="https://github.com/strapi/strapi/assets/130959147/56dbf0bf-1542-40b5-95bc-0fd1faa64e0b">
<img width="976" alt="Screenshot 2024-05-24 at 18 21 18" src="https://github.com/strapi/strapi/assets/130959147/0a247899-726a-460a-a1e9-7fb5a58c0085">

### Code snippets

Runtime logs
```
[2024-05-24 09:04:41] [2024-05-24 09:04:41.141] http: GET /api/news-pieces?locale=en&publicationState=live&filters[categories][$contains]=product (7 ms) 404
[2024-05-24 09:04:47] [2024-05-24 09:04:47.479] error: select "t0".* from "public"."news" as "t0" where (("t0"."locale" = $1 and "t0"."categories" like $2) and "t0"."published_at" is not null) limit $3 - operator does not exist: jsonb ~~ unknown
[2024-05-24 09:04:47] error: select "t0".* from "public"."news" as "t0" where (("t0"."locale" = $1 and "t0"."categories" like $2) and "t0"."published_at" is not null) limit $3 - operator does not exist: jsonb ~~ unknown
[2024-05-24 09:04:47]     at Parser.parseErrorMessage (/home/app/node_modules/pg-protocol/dist/parser.js:283:98)
[2024-05-24 09:04:47]     at Parser.handlePacket (/home/app/node_modules/pg-protocol/dist/parser.js:122:29)
[2024-05-24 09:04:47]     at Parser.parse (/home/app/node_modules/pg-protocol/dist/parser.js:35:38)
[2024-05-24 09:04:47]     at TLSSocket.<anonymous> (/home/app/node_modules/pg-protocol/dist/index.js:11:42)
[2024-05-24 09:04:47]     at TLSSocket.emit (node:events:517:28)
[2024-05-24 09:04:47]     at TLSSocket.emit (node:domain:489:12)
[2024-05-24 09:04:47]     at addChunk (node:internal/streams/readable:368:12)
[2024-05-24 09:04:47]     at readableAddChunk (node:internal/streams/readable:341:9)
[2024-05-24 09:04:47]     at Readable.push (node:internal/streams/readable:278:10)
[2024-05-24 09:04:47]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Additional context

I am using a plugin called [Multi Select Input ](https://market.strapi.io/plugins/strapi-plugin-multi-select) for the field in question
Also, I suspect this might apply to graphql as well, if using filters with contains operator.

**Comment by joaoprcosta** [comment]
The same is happening with me. Works fine using `$containsi` but shouldn't be case sensitive.
