### ISSUE TITLE
[BUG] Beta >4 breaks admin

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#20446]
### Required System information

- Node.js version: v20.12.2
- NPM version: 10.5.0
- Strapi version: 5.0.0-beta.9
- Database: SQLite
- Operating system: 6.6.32-1-MANJARO
- Is your project Javascript or Typescript: Typescript

```bash
Launched In: 383 ms
Environment: development
OS: linux-x64
Strapi Version: 5.0.0-beta.9
Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
Edition: Community
Database: sqlite
[2024-06-05 22:53:14.334] info: Shutting down Strapi
[2024-06-05 22:53:14.335] info: Strapi has been shut down
```

### Describe the bug

We just updated the project from beta 6 to beta 9 and we are trying to launch the server, but it breaks on running.

### Steps to reproduce the behavior

1. Update the Strapi packages replacing the current version with the new one on the `package.json` file.
2. Install with `yarn`.
3. Run the server.
4. See the error.
5. Remove both `node_modules` and `yarn.lock` and reinstall.
6. Run the server.
7. See the error.

### Screenshots
On the first run, we got this:
```bash
yarn develop                                                              ✔  8s   system  
✔ Cleaning dist dir (6ms)
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (75ms)
✔ Creating admin (261ms)
⠇ Loading Strapi
Creating media folders based on given paths.

Folder '/posts' already exists.
Folder 'posts/hero' already exists.
Folder 'hero/images' already exists.
Folder '/posts' already exists.
Folder 'posts/hero' already exists.
Folder 'hero/videos' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/audios' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/files' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/images' already exists.
Folder '/posts' already exists.
Folder 'posts/content' already exists.
Folder 'content/videos' already exists.
Folder '/profiles' already exists.
Folder 'profiles/photos' already exists.

Media folders have been set up!
✔ Loading Strapi (1206ms)
✔ Generating types (336ms)
✔ Cleaning dist dir (20ms)
✔ Compiling TS (1782ms)

 Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Wed Jun 05 2024 22:30:29 GMT-0500 (Colombia Sta… │
│ Launched in        │ 3348 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 358841                                           │
│ Version            │ 5.0.0-beta.9 (node v20.12.2)                     │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available                                                            

One more thing...
Create your first administrator 💻 by going to the administration panel at:

┌─────────────────────────────┐
│ http://localhost:1337/admin │
└─────────────────────────────┘

[2024-06-05 22:30:29.176] info: Strapi started successfully
[2024-06-05 22:30:58.275] http: GET /admin/content-manager/collection-types/plugin::users-permissions.user?page=1&pageSize=20&sort=username:ASC (40 ms) 200
✘ [ERROR] Could not resolve "@strapi/plugin-content-manager/strapi-admin"

    node_modules/@strapi/plugin-i18n/dist/_chunks/index-B5g3IkON.mjs:10:66:
      10 │ import { unstable_useDocument, unstable_useDocumentActions } from "@strapi/plugin-content-manager/strapi-admin";
         ╵                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@strapi/plugin-content-manager/strapi-admin" as external to exclude it from
  the bundle, which will remove this error and leave the unresolved path in the bundle.

22:30:58 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@strapi/plugin-i18n/dist/_chunks/index-B5g3IkON.mjs:10:66: ERROR: Could not resolve "@strapi/plugin-content-manager/strapi-admin"
    at failureErrorWithLog (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
    at /home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
    at /home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-05 22:31:01.556] http: GET /admin/content-manager/collection-types/plugin::users-permissions.user?page=1&pageSize=20&sort=username:ASC (5 ms) 200
^C[2024-06-05 22:31:41.665] info: Shutting down Strapi
[2024-06-05 22:31:41.669] info: Strapi has been shut down
```

So we deleted the `node_modules` and `yarn.lock` files and rebuilt the admin; at execution, we got:
```bash
    ~/Pr/e/strapi-template    v5 ⇡2 *1 +3 !3  yarn build                                                        HUP ✘  1m 19s   system  
[WARN] [@strapi/strapi]: The NODE_ENV is not set to production. This may result in unexpected behavior.
✔ Compiling TS (1485ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (66ms)
⠋ Building admin panel
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 
││   Error: [vite]: Rollup failed to resolve import "@strapi/plugin-content-manager/strapi-admin" from 
││   "/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/dist/_chunks/index-B5g3IkON.mjs".                      ││   This is most likely unintended because it can break your application at runtime. ││   If you do want to externalize this module explicitly add it to
││   `build.rollupOptions.external` 
││   at viteWarn (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/dist/node/chunks/dep
││   -jvB8WLp9.js:67190:27) 
││   at onwarn  
││   (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/@vitejs/plugin-react-swc/index.cjs:198:9)      ││   at onRollupWarning (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/dist/node/chu   ││   nks/dep-jvB8WLp9.js:67215:9) 
││   at onwarn (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/dist/node/chunks/dep-j   ││   vB8WLp9.js:66922:13)                                                                                                                            ││   at file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:18518:13                      ││   at Object.logger [as onLog]                                                                                                                     ││   (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:20166:9)                        ││   at ModuleLoader.handleInvalidResolvedId                                                                                                         ││   (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:19108:26)                       ││   at file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:19066:26
```

![image](https://github.com/strapi/strapi/assets/5034215/856cfa34-d31c-4341-b071-c41bfde274a8)

**Comment by SalahAdDin** [comment]
Update:
It also breaks with Beta 6!

**Comment by Eventyret** [comment]
So i do not get the media folder error that was there first doing this upgrading from 6-9

```javascript

✘ [ERROR] No matching export in "node_modules/styled-components/dist/styled-components.browser.esm.js" for import "styled"

    node_modules/@strapi/plugin-users-permissions/dist/_chunks/index-EQL2s09p-DzUzGVgd.mjs:19:28:
      19 │ import { createGlobalStyle, styled } from "styled-components";
         ╵                             ~~~~~~

✘ [ERROR] No matching export in "node_modules/styled-components/dist/styled-components.browser.esm.js" for import "styled"

    node_modules/@strapi/plugin-cloud/dist/_chunks/App-FtBcdtGN.mjs:6:9:
      6 │ import { styled } from "styled-components";
        ╵          ~~~~~~
```

Though I am getting this error by upgrading this, I have added some content and some media folders btw. to try replicate this.
![Image](https://github.com/strapi/strapi/assets/977232/a4c4bae4-cdd3-4436-8477-d9bfdb12ff47)

The issue for the error is because `styled-components` needs to be upgraded from `5.3.3` to `^6.0.0` changing this and it all works fine with no errors, upgrading from 6 to 9.
Downgrading you would have to swap from `6.0.0` to `5.3.3` to make it work again.

**Comment by SalahAdDin** [comment]
Upgrading to **beta 14** we get the first issue:
```
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @strapi/plugin-cloud@npm:5.0.0-beta.14, @strapi/plugin-documentation@npm:5.0.0-beta.14, and 87 more.
➤ YN0085: │ - @esbuild/aix-ppc64@npm:0.19.11, @esbuild/android-arm64@npm:0.19.11, @esbuild/android-arm@npm:0.19.11, and 84 more.
➤ YN0000: └ Completed in 0s 945ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ react-router-dom is listed by your project with version 6.23.1 (pbc6e4), which doesn't satisfy what @strapi/plugin-cloud and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ styled-components is listed by your project with version 5.3.11 (pf3ed0), which doesn't satisfy what @strapi/plugin-cloud and other dependencies request (but they have non-overlapping ranges!).
➤ YN0002: │ strapi-template@workspace:. doesn't provide @strapi/admin (pba5ee), requested by @strapi/plugin-i18n.
➤ YN0002: │ strapi-template@workspace:. doesn't provide @strapi/plugin-content-manager (pf623a), requested by @strapi/plugin-i18n.
➤ YN0002: │ strapi-template@workspace:. doesn't provide react-is (pc139c), requested by styled-components.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 48 packages were added to the project (+ 46.49 MiB).
➤ YN0000: └ Completed in 1s 939ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ core-js@npm:3.37.1 must be built because it never has been before or the last one failed
➤ YN0007: │ better-sqlite3@npm:11.0.0 must be built because it never has been before or the last one failed
➤ YN0007: │ msw@npm:1.3.0 [138e9] must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.37.1 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.5.25 [613fc] must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.3 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.32.6 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.16.17 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.19.12 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 2s 855ms
➤ YN0000: · Done with warnings in 5s 918ms
```

> Downgrading you would have to swap from 6.0.0 to 5.3.3 to make it work again.

We are using **5.3.11**, which works fine with Strapi 4. Strapi 5 requires: 
```
[WARN] Declared version of styled-components (5.3.11) is not compatible with the version required by Strapi (^6.0.0).
You may experience issues, we recommend you change this.
```

And the admin is still broken:
```
✘ [ERROR] Could not resolve "@strapi/plugin-content-manager/strapi-admin"

    node_modules/@strapi/plugin-i18n/dist/_chunks/index-B5g3IkON.mjs:10:66:
      10 │ import { unstable_useDocument, unstable_useDocumentActions } from "@strapi/plugin-content-manager/strapi-admin";
         ╵                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@strapi/plugin-content-manager/strapi-admin" as external to exclude it from
  the bundle, which will remove this error and leave the unresolved path in the bundle.

20:41:59 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@strapi/plugin-i18n/dist/_chunks/index-B5g3IkON.mjs:10:66: ERROR: Could not resolve "@strapi/plugin-content-manager/strapi-admin"
    at failureErrorWithLog (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
    at /home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
    at /home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-23 20:41:59.457] http: GET /favicon.ico (0 ms) 200
```

**Comment by SalahAdDin** [comment]
Another issue when building:
```
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐│                                                                                                                                           ││   Error: [vite]: Rollup failed to resolve import "@strapi/plugin-content-manager/strapi-admin" from                                       ││   "/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/plugin-i18n/dist/_chunks/index-B5g3IkON.mjs".              ││   This is most likely unintended because it can break your application at runtime.                                                        ││   If you do want to externalize this module explicitly add it to                                                                          ││   `build.rollupOptions.external`                                                                                                          ││   at viteWarn (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/dist/node/ch   ││   unks/dep-jvB8WLp9.js:67190:27)                                                                                                          ││   at onwarn (/home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/@vitejs/plugin-react-swc/i   ││   ndex.cjs:198:9)                                                                                                                         ││   at onRollupWarning (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/dist/   ││   node/chunks/dep-jvB8WLp9.js:67215:9)                                                                                                    ││   at onwarn (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/@strapi/strapi/node_modules/vite/dist/node/chun   ││   ks/dep-jvB8WLp9.js:66922:13)                                                                                                            ││   at file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:18514:13              ││   at Object.logger [as onLog]                                                                                                             ││   (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:20162:9)                ││   at ModuleLoader.handleInvalidResolvedId                                                                                                 ││   (file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:19104:26)               ││   at file:///home/luisalaguna/Projects/experiments/strapi-template/node_modules/rollup/dist/es/shared/node-entry.js:19062:26              ││                                                                                                                                           │└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by SalahAdDin** [comment]
It is still happening in the release candidate:
```
> strapi-template@1.0.1 strapi
> strapi report

Launched In: 488 ms
Environment: development
OS: linux-x64
Strapi Version: 5.0.0-rc.0
Node/Yarn Version: npm/10.5.0 node/v20.12.2 linux x64 workspaces/false
Edition: Community
Database: sqlite
[2024-06-26 23:14:51.525] info: Shutting down Strapi
[2024-06-26 23:14:51.527] info: Strapi has been shut down
```

**Comment by SalahAdDin** [comment]
The plugin package is deprecated and must be uninstalled, see [here](https://github.com/strapi/documentation/issues/2137).
