### ISSUE TITLE
Strapi Down in Production :  Timeout acquiring a connection. 

### ISSUE THREAD

**Issue by L-Weisz** [strapi/strapi#20491]
### Required System information

- Node.js version: node/v18.20.2 darwin arm64
- NPM version:  yarn/1.22.19
- Strapi version: 4.16.2
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Strapi is unreachable in production, all API are down

### Steps to reproduce the behavior

1. Try to connect to admin panel 
2. It loads forever 

1bis. Try to call any API
2. We have an error 

### Expected behavior

It should be recheable

### Screenshots

![image](https://github.com/strapi/strapi/assets/117728108/4ab645b2-f638-4aae-8d50-ecd775e48f58)

### Code snippets

Error in logs is 
` [2024-06-11 08:12:18.682] error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
[2024-06-11 08:12:18] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
[2024-06-11 08:12:18]     at Client_PG.acquireConnection (/home/app/node_modules/knex/lib/client.js:332:26)
[2024-06-11 08:12:18]     at async Runner.ensureConnection (/home/app/node_modules/knex/lib/execution/runner.js:305:28)
[2024-06-11 08:12:18]     at async Runner.run (/home/app/node_modules/knex/lib/execution/runner.js:30:19)
[2024-06-11 08:12:18]     at async Object.execute (/home/app/node_modules/@strapi/database/dist/index.js:4248:22)
[2024-06-11 08:12:18]     at async Object.count (/home/app/node_modules/@strapi/database/dist/index.js:5009:19)
[2024-06-11 08:12:18]     at async Object.exists (/home/app/node_modules/@strapi/admin/server/services/user.js:148:11)
[2024-06-11 08:12:18]     at async Object.init (/home/app/node_modules/@strapi/admin/server/controllers/admin.js:40:22)
[2024-06-11 08:12:18]     at async returnBodyMiddleware (/home/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
[2024-06-11 08:12:18]     at async policiesMiddleware (/home/app/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
[2024-06-11 08:12:18]     at async /home/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
[2024-06-11 08:12:18]     at async serve (/home/app/node_modules/koa-static/index.js:59:5)
[2024-06-11 08:12:18]     at async returnBodyMiddleware (/home/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
[2024-06-11 08:12:18]     at async policiesMiddleware (/home/app/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
[2024-06-11 08:12:18]     at async /home/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
[2024-06-11 08:12:18]     at async /home/app/node_modules/@strapi/admin/server/routes/serve-admin-panel.js:64:7
[2024-06-11 08:12:18]     at async serve (/home/app/node_module`

### Additional context

- I use strapi cloud to host my strapi instance
- I use Strapi for an important feature in my app so this is very problematic

**Comment by derrickmehaffy** [comment]
Please use support@strapi.io, this is not the medium for support with cloud issues
