### ISSUE TITLE
Can't create projects on Debian

### ISSUE THREAD

**Issue by chuanxinwong** [strapi/strapi#20534]
### Required System information

- Node.js version: 20.14.0
- NPM version: 10.7.0
- Strapi version: 4.25.0
- Database: sqlite
- Operating system: debian 12
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I plan to start learning this project and follow the guidelines

```bash
npx create-strapi-app@latest my-project
```

The following errors appear:

<details>
<summary>error detail</summary>

```
user01@debian:~/my/learm$ npx create-strapi-app@latest my-project
? Choose your installation type Quickstart (recommended)
 
We can't find any auth credentials in your Strapi config.

Create a free account on Strapi Cloud and benefit from:

- ✦ Blazing-fast ✦ deployment for your projects
- ✦ Exclusive ✦ access to resources to make your project successful
- An ✦ Awesome ✦ community and full enjoyment of Strapi's ecosystem

Start your 14-day free trial now!


? Please log in or sign up. Skip
Creating a quickstart project.
Creating a new Strapi application at /home/user01/my/learm/my-project.
Creating files.
Error while installing dependencies:
npm warn config production Use `--omit=dev` instead.
npm warn config optional Use `--omit=optional` to exclude optional dependencies, or
npm warn config `--include=optional` to include them.
npm warn config
npm warn config       Default value does install optional deps unless otherwise omitted.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated mailcomposer@3.12.0: This project is unmaintained
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
npm warn deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm warn deprecated buildmail@3.10.0: This project is unmaintained
npm error code 1
npm error path /home/user01/my/learm/my-project/node_modules/sharp
npm error command failed
npm error command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm error sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-x64.tar.br
npm error sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm error sharp: Installation error: aborted

npm error A complete log of this run can be found in: /home/user01/.npm/_logs/2024-06-17T08_20_19_601Z-debug-0.log
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /home/user01/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/home/user01/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
    at createProject (/home/user01/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createQuickStartProject (/home/user01/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:18:3)
    at async initProject (/home/user01/.npm/_npx/2d56dd13733e9da7/node_modules/create-strapi-app/dist/create-strapi-app.js:206:3)
user01@debian:~/my/learm$ 
user01@debian:~/my/learm$ 
user01@debian:~/my/learm$ node -v
v20.14.0
user01@debian:~/my/learm$ npm -v
10.7.0
user01@debian:~/my/learm$ 

```
</details>

### try npm install

<details>
<summary>npm i error</summary>

```
user01@debian:~/my/learm/my-project$ npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated mailcomposer@3.12.0: This project is unmaintained
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
npm warn deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm warn deprecated buildmail@3.10.0: This project is unmaintained
npm error code 1
npm error path /home/user01/my/learm/my-project/node_modules/sharp
npm error command failed
npm error command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm error sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-x64.tar.br
npm error sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm error sharp: Installation error: aborted

npm error A complete log of this run can be found in: /home/user01/.npm/_logs/2024-06-17T08_30_35_039Z-debug-0.log
user01@debian:~/my/learm/my-project$ 

```
</details>

### This is NPM log  (filesize: 384kb)

[2024-06-17T08_30_35_039Z-debug-0.log](https://github.com/user-attachments/files/15864189/2024-06-17T08_30_35_039Z-debug-0.log)

**Comment by liweikui** [comment]
I encountered this error too, Anyone can help?

**Comment by derrickmehaffy** [comment]
You are missing some build tools.

I'd advise installing the Debian package `build-essential`

Also ensure you have python 3 installed as well.

**Comment by derrickmehaffy** [comment]
Closing this as it's not related to Strapi itself but a user environment issue.
