### ISSUE TITLE
[Strapi v5 RC]  when using multiple Strapi v5 on different port and Strapi develop , serveur is watching on the wrong port and  server start failed

### ISSUE THREAD

**Issue by tombombadilom** [strapi/strapi#20910]
### Required System information

- Node.js version: 20.15.1
- NPM version: 10.7.0
- Strapi version: 5.0.0-rc.5
- Database: PostgreSQL
- Operating system: Archlinux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have 3 Strapi v5 same version , each one use a different port 
Since Strapi 5.0.0-rc.3 , When I have one Strapi already open and that I want to open another 
I got that Error 
```
Now using node v20.15.1
> strapi develop

✔ Cleaning dist dir (9ms)
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (48ms)
✔ Creating admin (209ms)
✔ Loading Strapi (1289ms)
✔ Generating types (382ms)
✔ Cleaning dist dir (38ms)
✔ Compiling TS (1861ms)
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:5173
    at listenOnPrimaryHandle (node:net:1970:18)
    at rr (node:internal/cluster/child:163:12)
    at Worker.<anonymous> (node:internal/cluster/child:113:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:531:35)
    at process.processEmit [as emit] (/home/tom/build/Nugreen/Plateforme-V2/Back-End/Back-End-partners/node_modules/signal-exit/index.js:199:34)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at listenOnPrimaryHandle (node:net:1971:21)
    at rr (node:internal/cluster/child:163:12)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 5173
}
``` 
So Basicaly , what happend is that the serveur is lookink after de default vite port and not after the one in .env 
If I close all Strapi and open one , everything is fine and the Server open.

### Steps to reproduce the behavior

1. open one Strapi server on one port
```
strapi develop
```
3. Open the second strapi with a different port in .env
```
strapi develop
```

### Expected behavior
Was working perfectly in strapi 5.0.0-rc.2
Strapi server should watch the port that is in .env and not the default vite port
Maybe the.env is not completely read by this part of the code ?  

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by phil-janeapp** [comment]
I'm not completely sure, but I believe this is due to Vite websockets.  If so, you'd need to alter your vite configuration file to set [server.port](https://vitejs.dev/config/server-options#server-port) (maybe to something such as `process.env.PORT + x`)

**Comment by jvdbrink-netpulse** [comment]
Having same issues, tried various ports in new vite.config.ts, but keeps reverting to port 5173

**Comment by albertshrpv** [comment]
Same issue persists in Strapi V5 official release. As mentioned above, modifying vite config doesn't resolve the issue.

**Comment by InumanSoul** [comment]
Same error here, but I didn't even have other instance of strapi running locally, just the v5, the .env port is configured to 3042, but it doesn't work:

```
Create your first administrator 💻 by going to the administration panel at:

┌─────────────────────────────┐
│ http://localhost:3042/admin │
└─────────────────────────────┘

[2024-09-26 08:13:38.777] info: Strapi started successfully
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:5173
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)
    at listenOnPrimaryHandle (node:net:1940:18)
    at rr (node:internal/cluster/child:163:12)
    at Worker.<anonymous> (node:internal/cluster/child:113:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:530:35)
    at process.processEmit [as emit] (/Users/andersons.farinam./Developer/printit_help/node_modules/signal-exit/index.js:199:34)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at listenOnPrimaryHandle (node:net:1941:21)
    at rr (node:internal/cluster/child:163:12)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -48,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 5173
}

Node.js v20.11.0
fatal error: all goroutines are asleep - deadlock!
```

**Comment by imnaK** [comment]
> Same error here, but I didn't even have other instance of strapi running locally, just the v5, the .env port is configured to 3042, but it doesn't work:
> 
> ```
> Create your first administrator 💻 by going to the administration panel at:
> 
> ┌─────────────────────────────┐
> │ http://localhost:3042/admin │
> └─────────────────────────────┘
> 
> [2024-09-26 08:13:38.777] info: Strapi started successfully
> node:events:496
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: bind EADDRINUSE null:5173
>     at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
>     at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)
>     at listenOnPrimaryHandle (node:net:1940:18)
>     at rr (node:internal/cluster/child:163:12)
>     at Worker.<anonymous> (node:internal/cluster/child:113:7)
>     at process.onInternalMessage (node:internal/cluster/utils:49:5)
>     at process.emit (node:events:530:35)
>     at process.processEmit [as emit] (/Users/andersons.farinam./Developer/printit_help/node_modules/signal-exit/index.js:199:34)
>     at emit (node:internal/child_process:951:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
> Emitted 'error' event on Server instance at:
>     at listenOnPrimaryHandle (node:net:1941:21)
>     at rr (node:internal/cluster/child:163:12)
>     [... lines matching original stack trace ...]
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -48,
>   code: 'EADDRINUSE',
>   syscall: 'bind',
>   address: null,
>   port: 5173
> }
> 
> Node.js v20.11.0
> fatal error: all goroutines are asleep - deadlock!
> ```

do you have a vite app running before starting strapi?
you can see it throws an error because of "address already in use" with port "5173" which is the default port in vite apps i believe. i don't know why strapi v5 needs this port but it should work if you run strapi first and then vite. vite will use another port instead (typically counting up: 5174)

**Comment by imnaK** [comment]
i think it's this port in here: https://github.com/strapi/strapi/blob/99323ff7d720a309ae03d2fa50b232a25cf57116/packages/core/strapi/src/node/vite/watch.ts#L14

**Comment by Aseraphyss** [comment]
This is probably because Strapi v5 features Vite and hence refers to equal default. However, throwing an Error instead of changing ports, when the port is already used by an other Vite app for example, should be addressed.

**Comment by magicbart** [comment]
i have the same issue trying to launch a 2nd strapi instance on port 1338

**Comment by muammerkeles** [comment]
we can change strapi port but for vite we use "vite.config.js" ( or .ts)  file to edit port as well.
 server: {
      port: 5174, // 5176  or 5177 
    },

**Comment by muammerkeles** [comment]
waiting it to be resolved.
i have same issue

**Comment by christianmarzian** [comment]
same problem here. 
Configuration: strapi v 5.0.2, node v18.20.4

**Comment by nmquan2504** [comment]
I have same issue.
Configuration: Strapi v 5.0.5, node v20.16.0. 
Trying to run 2 Strapi instances in same machine. Only one can run with "strapi develop".
Waiting it to be resolved.

**Comment by jianhuatu** [comment]
i have same issue

**Comment by jianhuatu** [comment]
strapi develop --no-watch-admin

**Comment by KlingerMatheus** [comment]
> strapi develop --no-watch-admin

For my purpose it worked, thanks!

**Comment by pjlammertyn** [comment]
Overrule the vite config with your own vite.config.ts and pass a different port as an environment variable (ex; VITE_SERVER_HMR_PORT) en put it in your .env file.

```ts
import { mergeConfig, loadEnv, type UserConfig } from 'vite';

export default (config: UserConfig) => {
  const env = loadEnv(config.mode, process.cwd())

  console.log("VITE_SERVER_HMR_PORT: " +  env.VITE_SERVER_HMR_PORT)

  // Important: always return the modified config
  return mergeConfig(config, {
    server: { hmr: { port: env.VITE_SERVER_HMR_PORT } }
  });
};
```

**Comment by teddybee** [comment]
Same issue here, when I want to run 2 strapi instances on the same PC. 
Only --no-watch-admin switch helped, but it is not a good solution.

**Comment by giorgoslytos** [comment]
I face the same issue on linux pop os.
I just installed strapi with npx create-strapi-app@latest 
sqlite db, empty project
Node.js v20.17.0
Running nothing on port 5173

**Comment by derrickmehaffy** [comment]
Locking this as we are aware the issue exists, has been confirmed, and is awaiting scheduling by our engineering team so no further confirmation is required.
