### ISSUE TITLE
[v5] Unable to set Review Workflow Assignee

### ISSUE THREAD

**Issue by phil-janeapp** [strapi/strapi#20956]
## Bug report

Unable to set an "Assignee" for the **Review Workflows** section.  The server log has the following for that request:

```
[2024-08-06 23:01:41.181] error: select "t0"."id" from "public"."blog_posts" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "isj1gyoqryyiyw6bnlvx8h3f"
error: select "t0"."id" from "public"."blog_posts" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "isj1gyoqryyiyw6bnlvx8h3f"
    at Parser.parseErrorMessage (/strapi/app/tmp/cache/yarn/berry/cache/pg-protocol-npm-1.6.1-c0b26dda9d-10c0.zip/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/strapi/app/tmp/cache/yarn/berry/cache/pg-protocol-npm-1.6.1-c0b26dda9d-10c0.zip/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/strapi/app/tmp/cache/yarn/berry/cache/pg-protocol-npm-1.6.1-c0b26dda9d-10c0.zip/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/strapi/app/tmp/cache/yarn/berry/cache/pg-protocol-npm-1.6.1-c0b26dda9d-10c0.zip/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

### Required System information

- Node.js version: node/v20.15.1
- NPM version: N/A (yarn)
- Strapi version: 5.0.0-rc.8
- Database: postgres
- Operating system: linux-arm64
- Is your project Javascript or Typescript: TS

### Describe the bug

Unable to set an "Assignee" for the **Review Workflows** section.

### Steps to reproduce the behavior

1. Go to any custom content type
2. Click on **Assignee** in the **Review Workflows** card
3. Select any user

### Expected behavior

There is no error

### Screenshots

<img width="285" alt="image" src="https://github.com/user-attachments/assets/56bd1212-e175-43a1-8ef3-6da84c7eac5e">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Related to TID8842

**Comment by derrickmehaffy** [comment]
I was able to confirm this on v5.3.0:

![image](https://github.com/user-attachments/assets/927a03f1-025a-4cb2-ba1c-d0d57df7a9c3)
![image](https://github.com/user-attachments/assets/7a423f25-7df9-4584-b466-5242525cc211)
![image](https://github.com/user-attachments/assets/1e418bcc-30e8-4dfe-9747-cb58bc31e570)
![image](https://github.com/user-attachments/assets/20cde275-3422-45a8-ae25-cfc7005a7d1b)

Issue looks to be like it's looking up the assigned user based on the `id` but passing in the documentId instead.

**Comment by derrickmehaffy** [comment]
Raising Sev from high to critical since it impacts an EE customer
