### ISSUE TITLE
Unable to acquire a connection

### ISSUE THREAD

**Issue by garryismael** [strapi/strapi#20974]
### Required System information

- Node.js version: v20.16.0
- NPM version: 10.8.1
- Strapi version: v4.25.7
- Database: postgres
- Operating system: MacOS BigSur
- Is your project Javascript or Typescript: JS

### Describe the bug
```bash
Error: Unable to acquire a connection
    at Client_PG.acquireConnection (/Users/user/Documents/CodeandScale/jobmada/backend/node_modules/knex/lib/client.js:311:13)
    at Runner.ensureConnection (/Users/user/Documents/CodeandScale/jobmada/backend/node_modules/knex/lib/execution/runner.js:305:46)
    at Runner.run (/Users/user/Documents/CodeandScale/jobmada/backend/node_modules/knex/lib/execution/runner.js:30:30)
    at Target.then (/Users/user/Documents/CodeandScale/jobmada/backend/node_modules/knex/lib/builder-interface-augmenter.js:24:43)
error Command failed with exit code 1.
```

### Steps to reproduce the behavior
Running the server locally

### Expected behavior

The app start locally

### Code snippets
```javascript
// database.js
const path = require("path");

module.exports = ({ env }) => {
  const client = env("DATABASE_CLIENT", "sqlite");

  return {
    connection: {
      client,
      acquireConnectionTimeout: env.int("DATABASE_CONNECTION_TIMEOUT", 60000),
    },
  };
};
```

```javascript

// env/test/database.js

module.exports = ({ env }) => ({
  connection: {
    connectionString: env("DATABASE_URL"),
    host: env("DATABASE_HOST", "localhost"),
    port: env.int("DATABASE_PORT", 5432),
    database: env("DATABASE_NAME", "strapi"),
    user: env("DATABASE_USERNAME", "strapi"),
    password: env("DATABASE_PASSWORD", "strapi"),
    ssl: env.bool("DATABASE_SSL", false) && {
      key: env("DATABASE_SSL_KEY", undefined),
      cert: env("DATABASE_SSL_CERT", undefined),
      ca: env("DATABASE_SSL_CA", undefined),
      capath: env("DATABASE_SSL_CAPATH", undefined),
      cipher: env("DATABASE_SSL_CIPHER", undefined),
      rejectUnauthorized: env.bool("DATABASE_SSL_REJECT_UNAUTHORIZED", true),
    },
    schema: env("DATABASE_SCHEMA", "public"),
  },
  pool: {
    min: env.int("DATABASE_POOL_MIN", 2),
    max: env.int("DATABASE_POOL_MAX", 10),
  },
});

```

### Additional context
NB: The tables are created.

**Comment by derrickmehaffy** [comment]
This isn't a bug on our side, strapi can't connect to the database. 

Marking this as a question
