### ISSUE TITLE
Error when configuring the view of nested components

### ISSUE THREAD

**Issue by schloram** [strapi/strapi#20978]
### Required System information

- Node.js version: v20.16.0
- NPM version: 10.8.1
- Strapi version: 5.0.0-rc.9
- Database: PostgreSQL 16
- Operating system: Alpine Linux
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

I get the following error when configuring the view of nested components inside a Collection Type. It's a fresh Strapi 5 installation without any records or customizations. Only three Collection Type and two components.

```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at kce (https://my.strapi.de/admin/strapi-DTpLRmea.js:2445:9284)
    at https://my.strapi.de/admin/strapi-DTpLRmea.js:2445:11315
    at Array.map (<anonymous>)
    at https://my.strapi.de/admin/strapi-DTpLRmea.js:2445:11080
    at Array.map (<anonymous>)
    at BW (https://my.strapi.de/admin/strapi-DTpLRmea.js:2445:11071)
    at https://my.strapi.de/admin/strapi-DTpLRmea.js:2445:10648
    at Array.reduce (<anonymous>)
    at RRt (https://my.strapi.de/admin/strapi-DTpLRmea.js:2445:10616)
    at https://my.strapi.de/admin/strapi-DTpLRmea.js:2445:9897
```

### Steps to reproduce the behavior

1. Create a component (let's say `postalAddress`)
2. Create a second component (let's say `fullContact`) and add the first component to it
3. Create a Collection Type and add the second component (`fullContact`) to it
4. Go to the new Collection Type in the Content Manager
5. Click "Create new entry" (do not enter anything nor save the record)
6. Select "Configure the view" from the three dots on the top right of the page
7. Click on "Set the component's layout" on the first component (`fullContact`)
8. Change the label of the nested component (`postalAddress`)
9. Click "Finish"
10. Save the view by clicking "Save" on top of the page
11. Now go back with the "← Back" link on the top left of the page
12. Now either you see like ten flash messages appear or you get the mentioned error right away. I've seen these two different behaviours while trying to reproduce the error
13. (optional) When only seeing the flash messages (and not the breaking error) click on the Collection Type from step 4 in the side bar again.
14. At least now the error should occur
15. Now everytime you open this specific Collection Type in the Content Manager this error appears. Strapi in general and other Collection Types still work.

### Expected behavior

Configuring the view of nested components should not result in an error.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by NEDDL** [comment]
I just saw this problem, I faced the same issues on my side:
#21059 
#21058

Both related to the same problem here.

**Comment by tammyhart** [comment]
I am still getting an error on this:

- Node.js version: v20.16.0
- NPM version: 10.8.1
- Strapi version: 5.0.0-rc.13
- Database: SQLite
- Operating system: MacOS
- Is your project Javascript or Typescript: Javascript

```
TypeError: Cannot read properties of undefined (reading 'push')
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JD5QJZYX.js?v=d129b54f:2920:33
    at Array.reduce (<anonymous>)
    at formatEditLayout (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JD5QJZYX.js?v=d129b54f:2912:5)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JD5QJZYX.js?v=d129b54f:2865:32
    at updateMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=d129b54f:12230:27)
    at Object.useMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=d129b54f:12746:24)
    at Object.useMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BCGHH3YY.js?v=d129b54f:1094:29)
    at useDocumentLayout (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JD5QJZYX.js?v=d129b54f:2864:28)
    at ListViewPage (http://localhost:1337/node_modules/.strapi/vite/deps/ListViewPage-CdKd-PS_-JF2L5GJN.js?v=d129b54f:672:20)
    at renderWithHooks (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=d129b54f:11568:26)
```
