### ISSUE TITLE
[V5] After saving configure view, Strapi CRASHES

### ISSUE THREAD

**Issue by NEDDL** [strapi/strapi#21059]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-rc.11
Node/Yarn Version: npm/10.1.0 node/v20.9.0 darwin arm64 workspaces/false
Edition: Community
Database: postgres

### Describe the bug

After completing the configuration of the view of the component (with nested component in it), when I go back to the collection page that has this component shows error: "Cannot read properties of undefined (reading 'attributes')"

### Steps to reproduce the behavior

1. Go to a collection that has a component in it
2. Configure the view of the component and the nested component
3. Save the configuration of the view of the component
4. Click on go back
5. Collection page crashes

### Expected behavior

It shouldn't crash

### Screenshots

![Screenshot 2024-08-22 at 17 57 07](https://github.com/user-attachments/assets/61170dba-235a-4731-a8ff-8bdd0b7b036c)

### Additional context

Each time when that happens, npm run build helps.

Also the error:

```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at getMainField (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-EJIYP5C3.js?v=19721a75:2780:90)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-EJIYP5C3.js?v=19721a75:2939:20
    at Array.map (<anonymous>)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-EJIYP5C3.js?v=19721a75:2925:18
    at Array.map (<anonymous>)
    at convertEditLayoutToFieldLayouts (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-EJIYP5C3.js?v=19721a75:2924:15)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-EJIYP5C3.js?v=19721a75:2884:17
    at Array.reduce (<anonymous>)
    at formatEditLayout (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-EJIYP5C3.js?v=19721a75:2881:67)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-EJIYP5C3.js?v=19721a75:2822:32
```

```
The above error occurred in the <EditConfigurationPage> component:

    at EditConfigurationPage (http://localhost:1337/node_modules/.strapi/vite/deps/EditConfigurationPage-CjUrEewK-MOHDTIKB.js?v=19721a75:56:26)
    at Protect (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:4584:18)
    at ProtectedEditConfigurationPage (http://localhost:1337/node_modules/.strapi/vite/deps/EditConfigurationPage-CjUrEewK-MOHDTIKB.js?v=19721a75:170:23)
    at RenderedRoute (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4015:5)
    at Outlet (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4386:26)
    at div
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:45810:17
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at div
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:45810:17
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at RootLayout (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7ZL3HYHV.js?v=19721a75:10260:21)
    at Layout (http://localhost:1337/node_modules/.strapi/vite/deps/layout-ls3gxfpH-KA6MEVBN.js?v=19721a75:479:28)
    at RenderedRoute (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4015:5)
    at Outlet (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4386:26)
    at div
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:45810:17
    at div
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:45810:17
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:45998:11
    at div
    at O2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1267:6)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:45810:17
    at DndProvider2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-HZLKFRCJ.js?v=19721a75:1326:9)
    at PluginsInitializer (http://localhost:1337/node_modules/.strapi/vite/deps/AuthenticatedLayout-InmsyhP2-4PGWKDKG.js?v=19721a75:998:29)
    at E.t2.Provider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3724:74)
    at Provider2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3809:13)
    at AdminLayout (http://localhost:1337/node_modules/.strapi/vite/deps/AuthenticatedLayout-InmsyhP2-4PGWKDKG.js?v=19721a75:1147:35)
    at PrivateRoute (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-HIBF73ZN.js?v=19721a75:17:23)
    at PrivateAdminLayout
    at RenderedRoute (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4015:5)
    at Outlet (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4386:26)
    at Suspense
    at Provider4 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:8810:13)
    at ConfigurationProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:4818:3)
    at E.t2.Provider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3724:74)
    at Provider2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3809:13)
    at GuidedTourProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7ZL3HYHV.js?v=19721a75:9790:29)
    at TrackingProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:4741:27)
    at NotificationsProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:4234:32)
    at Provider4 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:8843:15)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:15239:11)
    at ot (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-43XC3YXW.js?v=19721a75:1207:32)
    at Provider22 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:45754:13)
    at DesignSystemProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:54391:3)
    at Theme (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:4925:16)
    at IntlProvider3 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:62469:45)
    at LanguageProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:4920:27)
    at E.t2.Provider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3724:74)
    at Provider2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3809:13)
    at HistoryProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7ZL3HYHV.js?v=19721a75:9692:26)
    at E.t2.Provider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3724:74)
    at Provider2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3809:13)
    at AuthProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:4083:3)
    at QueryClientProvider2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7ZL3HYHV.js?v=19721a75:3978:21)
    at Provider3 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JFXTKYH4.js?v=19721a75:65549:3)
    at E.t2.Provider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3724:74)
    at Provider2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-RSYWOS4R.js?v=19721a75:3809:13)
    at Providers (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7ZL3HYHV.js?v=19721a75:9959:20)
    at App (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7ZL3HYHV.js?v=19721a75:9988:14)
    at RenderedRoute (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4015:5)
    at RenderErrorBoundary (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:3975:5)
    at DataRoutes (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:5133:5)
    at Router (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4393:15)
    at RouterProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4948:5)

React will try to recreate this component tree from scratch using the error boundary you provided, RenderErrorBoundary.
```

```
React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'attributes')
    at getMainField (attributes.ts:36:41)
    at useDocumentLayout.ts:349:22
    at Array.map (<anonymous>)
    at useDocumentLayout.ts:328:8
    at Array.map (<anonymous>)
    at convertEditLayoutToFieldLayouts (useDocumentLayout.ts:326:15)
    at useDocumentLayout.ts:264:17
    at Array.reduce (<anonymous>)
    at formatEditLayout (useDocumentLayout.ts:261:67)
    at useDocumentLayout.ts:167:11 Object 
    at RenderErrorBoundary (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:3975:5)
    at DataRoutes (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:5133:5)
    at Router (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4393:15)
    at RouterProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-3523IN23.js?v=19721a75:4948:5)
```

```
      Uncaught TypeError: Cannot read properties of undefined (reading 'target')
    at content.js:8:344558
```

**Comment by NEDDL** [comment]
The problem was explained here with another problem: #21051

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/20978
