### ISSUE TITLE
Error when FIPS is enabled in RHEL related to usage of MD5

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#21053]
### Required System information

- Node.js version: v20
- NPM version: Yarn 1
- Strapi version: 4.x.x & 5.x.x-rc.x
- Database: SQLite
- Operating system: RHEL 8
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When FIPS is enabled on a RHEL system is forcefully disables any usage of MD5 and any attempt to use it throws an error such as:

```
1|gha-strapi | [2024-08-06 14:55:32.051] debug: ⛔️ Server wasn't able to start properly.
1|gha-strapi | [2024-08-06 14:55:32.053] error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
1|gha-strapi | Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
1|gha-strapi | at new Hash (node:internal/crypto/hash:80:19)
1|gha-strapi | at Object.createHash (node:crypto:142:10)
1|gha-strapi | at Object.hashSchema (/srv/www/gha-strapi/node_modules/@strapi/database/dist/index.js:1607:38)
1|gha-strapi | at Object.sync (/srv/www/gha-strapi/node_modules/@strapi/database/dist/index.js:1879:45)
1|gha-strapi | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|gha-strapi | at async Strapi.bootstrap (/srv/www/gha-strapi/node_modules/@strapi/strapi/dist/Strapi.js:402:5)
1|gha-strapi | at async Strapi.load (/srv/www/gha-strapi/node_modules/@strapi/strapi/dist/Strapi.js:426:5)
1|gha-strapi | at async Strapi.start (/srv/www/gha-strapi/node_modules/@strapi/strapi/dist/Strapi.js:216:9)
```

### Steps to reproduce the behavior

Note: This is operating system dependent

1. Create a virtual machine using RHEL 8
2. [Switch the OS into FIPS mode](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/security_hardening/switching-rhel-to-fips-mode_security-hardening)
3. Try to start a Strapi application

### Expected behavior

Either we need to change the usage of MD5 to some other FIPS compatible scheme or provide the user a configuration option to change it

### Screenshots

N/A

### Code snippets

There are only 2 places in Strapi that we use MD5 (none of which are security related so we aren't technically violating FIPS but it's brutally forceful in the way it imposes the restrictions)

Hashing the schema:

https://github.com/strapi/strapi/blob/8d950c6dc5e12964dce7f697f002102dca0a6df4/packages/core/database/src/schema/storage.ts#L54-L56

Webpack config:

https://github.com/strapi/strapi/blob/8d950c6dc5e12964dce7f697f002102dca0a6df4/packages/core/strapi/src/node/webpack/config.ts#L124-L172

### Additional context

Related to TID7748

Even though we aren't violating FIPS 140-2 or 140-3 since we don't use MD5 for anything security related, using the FIPS mode in RHEL completely disables the OS from using MD5 at all making it impossible for anyone to use FIPS mode while using Strapi without manually patching out the hash method in the database.

**Comment by derrickmehaffy** [comment]
Also related to TID: 8157 by the same person in TID: 7748

**Comment by nddipiazza** [comment]
@derrickmehaffy  could this be a configuration parameter in the .env by default is md5 then also supports the other hash?

That could be followed up with in 4.x and 5.x manual set of steps to "make your strapi 4 or strapi 5 instance fips compliant" 

So you would set the .env variable to switch hashAlgorithm from md5 to sha256

Then you would run a db migration as created here:

https://github.com/strapi-support-demo-apps/strapi-example-v5-fips-sha256/blob/main/patches/%40strapi%2Bdatabase%2B5.11.0.patch

Once it's done, you can remove the migration forever.

I'm going to see if this concept works to get me unblocked.
