### ISSUE TITLE
when user pm2 start the Strapi, something is wrong

### ISSUE THREAD

**Issue by skylerzhang1** [strapi/strapi#21126]
### Link to the documentation page or resource

https://docs.strapi.io/dev-docs/deployment/process-manager#start-pm2-with-a-serverjs-file

### Describe the bug

Start PM2 with the strapi command
![image](https://github.com/user-attachments/assets/705de8f7-e8f2-4cd9-ad5e-2098abf4d974)

C:\PROGRAM FILES\NODEJS\NPM.CMD:1
:: Created by npm, please don't edit manually.
^

SyntaxError: Unexpected token ':'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Object.<anonymous> (C:\Users\skylerzhang\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)

### Additional context

Start PM2 with a server.js file 
It can be success.

**Comment by pwizla** [comment]
Hello @skylerzhang1.
I'm sorry you're having issues with PM2. I'm transferring this issue to `strapi/strapi` as I can't see what the documentation could do for you at the moment. You might need to add the following additional information so that the Strapi Support team gets enough context:


## Bug report

### Required System information

* Please ensure you are using the Node LTS version (v18 or v20)
* Strapi v3 is no longer supported, please update to Strapi v4 
* If you are reporting a frontend bug please provide error logs after setting STRAPI_ENFORCE_SOURCEMAPS=true in your .env . This environment variable makes frontend errors easier to read and trace

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

_Did you know you can run `yarn strapi report` or `npm run strapi report` to get this information easier?_

### Describe the bug

A clear and concise description of what the bug is.

### Steps to reproduce the behavior

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior

A clear and concise description of what you expected to happen.

### Screenshots

If applicable, add screenshots to help explain your problem.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Add any other context about the problem here.

**Comment by skylerzhang1** [comment]
### Required System information

- Node.js version: v20.17.0
- NPM version: 10.8.2
- Strapi version: 4.25.9
- Database: mysql8.0
- Operating system: windows11
- Is your project Javascript or Typescript: Javascript 

_Did you know you can run `yarn strapi report` or `npm run strapi report` to get this information easier?_

### Describe the bug

when user pm2 start the Strapi, something is wrong

### Steps to reproduce the behavior

1. Open the terminal
2. go to the Strapi root path
3. execute the 'pm2 start npm --name app -- run start '
4. See error
![image](https://github.com/user-attachments/assets/bb0d9c41-4a89-4d2e-9d9c-7d9191a3af6b)
C:\PROGRAM FILES\NODEJS\NPM.CMD:1
:: Created by npm, please don't edit manually.
^

SyntaxError: Unexpected token ':'
at wrapSafe (node:internal/modules/cjs/loader:1378:20)
at Module._compile (node:internal/modules/cjs/loader:1428:41)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32)
at Module._load (node:internal/modules/cjs/loader:1104:12)
at Object. (C:\Users\skylerzhang\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
at Module._compile (node:internal/modules/cjs/loader:1469:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32)
at Module._load (node:internal/modules/cjs/loader:1104:12)

### Expected behavior

The project can start normally

### Screenshots

![image](https://github.com/user-attachments/assets/a885d4f1-503b-4f87-9b85-16857f2ad7d6)

### Code snippets

NA

### Additional context

Start PM2 with a server.js file
It can be success.
