### ISSUE TITLE
Migration core::5.0.0-discard-drafts (up) no such table: forms_form_localizations_lnk 

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#21186]
### Required System information

- Node.js version: 18
- NPM version:
- Strapi version: 5 rc 17
- Database: sqlite
- Operating system: macos
- Is your project Javascript or Typescript: js

### Describe the bug

The migration crashes on a select on a table that doesn't exist. I cannot find this code so I cannot debug it. I think it is somewhere in the `document().discardDraft()` code, which I cannot find.

### Steps to reproduce the behavior

1. Create a v4 without i18n
2. create a content type in a plugin
3. Migrate to v5
4. see MigrationError

### Expected behavior

no Error.

### Screenshots

<img width="1254" alt="Scherm­afbeelding 2024-09-07 om 13 09 49" src="https://github.com/user-attachments/assets/2fc0dc82-13dc-4a40-b156-32f840b5f9d6">

### Additional context

https://github.com/strapi/strapi/issues/20225

https://github.com/strapi/strapi/issues/21185

**Comment by jackbuehner** [comment]
I also get the same issue using postgres and Windows 10. Everything else is the same.

```
[2024-09-10 19:42:27.154] error: Migration core::5.0.0-discard-drafts (up) failed: Original error: select * from "public"."newsletters_localizations_lnk" where "inv_newsletter_id" in ($1) - relation "public.newsletters_localizations_lnk" does not exist
MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: select * from "public"."newsletters_localizations_lnk" where "inv_newsletter_id" in ($1) - relation "public.newsletters_localizations_lnk" does not exist
    at C:\Users\jackb\Workspace\content-manager\node_modules\umzug\lib\umzug.js:169:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Umzug.runCommand (C:\Users\jackb\Workspace\content-manager\node_modules\umzug\lib\umzug.js:125:20)
    at async Object.up (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\database\dist\index.js:6520:7)
    at async Object.up (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\database\dist\index.js:6544:11)
    at async Object.sync (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\database\dist\index.js:2246:9)
    at async Strapi.bootstrap (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\core\dist\Strapi.js:351:5)
    at async Strapi.load (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\core\dist\Strapi.js:315:5)
    at async Strapi.start (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\core\dist\Strapi.js:207:9)
[2024-09-10 19:42:27.155] info: Shutting down Strapi
```

**Comment by rohit-smartshore** [comment]
I am getting this error on a ubuntu 24 system after migrating from strapi 4.25.5

**Comment by jelmer-visser** [comment]
The same issue persists on macOS when using MySQL

**Comment by yunusyuksel** [comment]
That issue still persist with 5.10.0, Any solution ? 
```js
 MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: select distinct `t0`.`document_id`, `t0`.`locale`,                 ││   `t1`.`season_id` as `__strapiseason_id` from `stories_clusters` as `t0` left join `stories_clusters_season_lnk` as `t1` on `t0`.`id` =               ││   `t1`.`stories_cluster_id` where (`t1`.`season_id` in (1)) - Table 'hg_old.stories_clusters_season_lnk' doesn't exist
```

**Comment by yunusyuksel** [comment]
> Fix merged and will be included in next RC

Can you share the link to the solution ?
