### ISSUE TITLE
Node error when setting up new project for first time.

### ISSUE THREAD

**Issue by deckblad** [strapi/strapi#21248]
- Node.js version: v20.17.0
- NPM version: 10.8.3
- Strapi version: Latest
- Database: None
- Operating system: Debian 12.2.0-14 container on Proxmox Debian 12.2.0-14 host

Running following command as regular (non root) user in their own home folder, npx create-strapi-app@latest test001 fails

output:
`foobar@sandbutt:~/strapi$ npx create-strapi-app@latest test001
? Choose your installation type Quickstart (recommended)

We can't find any auth credentials in your Strapi config.

Create a free account on Strapi Cloud and benefit from:

- ✦ Blazing-fast ✦ deployment for your projects
- ✦ Exclusive ✦ access to resources to make your project successful
- An ✦ Awesome ✦ community and full enjoyment of Strapi's ecosystem

Start your 14-day free trial now!

? Please log in or sign up. Skip
Creating a quickstart project.
Creating a new Strapi application at /home/foobar/strapi/test001.
Creating files.
Dependencies installed successfully.

Your application was created at /home/foobar/strapi/test001.

Available commands in your project:

  npm run develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  npm run start
  Start Strapi without watch mode.

  npm run build
  Build Strapi admin panel.

  npm run deploy
  Deploy Strapi project.

  npm run strapi
  Display all available commands.

You can start by doing:

  cd /home/foobar/strapi/test001
  npm run develop

Running your Strapi application.

> test-001@0.1.0 develop
> strapi develop

/home/foobar/strapi/test001/node_modules/@swc/core/binding.js:333
    throw new Error('Failed to load native binding', { cause: loadErrors })
    ^

Error: Failed to load native binding
    at Object.<anonymous> (/home/foobar/strapi/test001/node_modules/@swc/core/binding.js:333:11)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/foobar/strapi/test001/node_modules/@swc/core/index.js:49:17)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) {
  [cause]: [
    Error: Cannot find module './swc.linux-x64-gnu.node'
    Require stack:
    - /home/foobar/strapi/test001/node_modules/@swc/core/binding.js
    - /home/foobar/strapi/test001/node_modules/@swc/core/index.js
    - /home/foobar/strapi/test001/node_modules/@vitejs/plugin-react-swc/index.cjs
    - /home/foobar/strapi/test001/node_modules/@strapi/pack-up/dist/index.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/action.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/command.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/index.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/cli.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/bin/strapi.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
        at Module._load (node:internal/modules/cjs/loader:1051:27)
        at Module.require (node:internal/modules/cjs/loader:1311:19)
        at require (node:internal/modules/helpers:179:18)
        at requireNative (/home/foobar/strapi/test001/node_modules/@swc/core/binding.js:211:16)
        at Object.<anonymous> (/home/foobar/strapi/test001/node_modules/@swc/core/binding.js:306:17)
        at Module._compile (node:internal/modules/cjs/loader:1469:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Module._load (node:internal/modules/cjs/loader:1104:12) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/foobar/strapi/test001/node_modules/@swc/core/binding.js',
        '/home/foobar/strapi/test001/node_modules/@swc/core/index.js',
        '/home/foobar/strapi/test001/node_modules/@vitejs/plugin-react-swc/index.cjs',
        '/home/foobar/strapi/test001/node_modules/@strapi/pack-up/dist/index.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/action.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/command.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/index.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/cli.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/bin/strapi.js'
      ]
    },
    Error: Cannot find module '@swc/core-linux-x64-gnu'
    Require stack:
    - /home/foobar/strapi/test001/node_modules/@swc/core/binding.js
    - /home/foobar/strapi/test001/node_modules/@swc/core/index.js
    - /home/foobar/strapi/test001/node_modules/@vitejs/plugin-react-swc/index.cjs
    - /home/foobar/strapi/test001/node_modules/@strapi/pack-up/dist/index.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/action.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/command.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/index.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/cli.js
    - /home/foobar/strapi/test001/node_modules/@strapi/strapi/bin/strapi.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
        at Module._load (node:internal/modules/cjs/loader:1051:27)
        at Module.require (node:internal/modules/cjs/loader:1311:19)
        at require (node:internal/modules/helpers:179:18)
        at requireNative (/home/foobar/strapi/test001/node_modules/@swc/core/binding.js:216:16)
        at Object.<anonymous> (/home/foobar/strapi/test001/node_modules/@swc/core/binding.js:306:17)
        at Module._compile (node:internal/modules/cjs/loader:1469:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Module._load (node:internal/modules/cjs/loader:1104:12) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/foobar/strapi/test001/node_modules/@swc/core/binding.js',
        '/home/foobar/strapi/test001/node_modules/@swc/core/index.js',
        '/home/foobar/strapi/test001/node_modules/@vitejs/plugin-react-swc/index.cjs',
        '/home/foobar/strapi/test001/node_modules/@strapi/pack-up/dist/index.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/action.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/actions/plugin/build-command/command.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/commands/index.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/dist/cli.js',
        '/home/foobar/strapi/test001/node_modules/@strapi/strapi/bin/strapi.js'
      ]
    }
  ]
}

Node.js v20.17.0
`

**Comment by deckblad** [comment]
I added this clause to my package.json, deleted package-lock.json, ran npm install. problem solved.

`"optionalDependencies": {
        "@swc/core-linux-x64-gnu": "^1.2.160"
    }`
