### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by jj-ivx** [strapi/strapi#21309]
### Required System information

- Node.js version: v20.13.1
- NPM version: 10.5.2
- Strapi version: 4.25.11
- Database: -
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Strapi does not seem to support native ESM. When using `npx create-strapi-app my-project --quickstart` and then changing `type` in `package.json` to `module`, you get the following error when running `npm run build`:

```sh
Error: Could not load js config file /User/workspace/my-project/config/admin.js: require() of ES Module /User/workspace/my-project/config/admin.js from         │
│   /User/workspace/my-project/node_modules/@strapi/utils/dist/index.js not supported.                                                                                                │
│   admin.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.          │
│   Instead either rename admin.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in    │
│   /User/workspace/my-project/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).                                                               │
│                                                                                                                                                                                                       │
│   at loadJsFile (/User/workspace/my-project/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:18:13)                                                      │
│   at Module.loadFile (/User/workspace/my-project/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:37:14)                                                 │
│   at /User/workspace/my-project/node_modules/@strapi/strapi/dist/core/app-configuration/config-loader.js:14:31                                                                      │
│   at Array.reduce (<anonymous>)                                                                                                                                                                       │
│   at loadConfigDir (/User/workspace/my-project/node_modules/@strapi/strapi/dist/core/app-configuration/config-loader.js:12:175)                                                     │
│   at loadConfiguration (/User/workspace/my-project/node_modules/@strapi/strapi/dist/core/app-configuration/index.js:49:41)                                                          │
│   at new Strapi (/User/workspace/my-project/node_modules/@strapi/strapi/dist/Strapi.js:124:23)                                                                                      │
│   at Object.initFn [as default] (/User/workspace/my-project/node_modules/@strapi/strapi/dist/Strapi.js:467:18)                                                                      │
│   at createBuildContext (/User/workspace/my-project/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:576:66)                                                               │
│   at Object.build (/User/workspace/my-project/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:663:21)
```

I've also tried setting `module` and `moduleResolution` in tsconfig.json to "NodeNext", but that results in the same error.

### Steps to reproduce the behavior

1. Run `npx create-strapi-app my-project --quickstart`
2. Add `"type": "module"` to package.json
3. Run `npm run build`

### Expected behavior

It just works with native ESM

**Comment by alexandrebodin** [comment]
We do not support native ESM for now but are looking forward to nodeJS compatibility implementation in node 22+.

However If you want to have ESM style imports you can use the typescript version of Strapi :)

Going to flag this as a feature request 👍

**Comment by BasitAli** [comment]
> We do not support native ESM for now but are looking forward to nodeJS compatibility implementation in node 22+.
> 
> However If you want to have ESM style imports you can use the typescript version of Strapi :)
> 
> Going to flag this as a feature request 👍

Any documentation on how we can use the typescript version?
