### ISSUE TITLE
[Error] con.batchInsert is not a function (v5, Cloud)

### ISSUE THREAD

**Issue by ryanvanderpol** [strapi/strapi#21352]
### Required System information

Not sure how to fill this out when running in Strapi Cloud. My project is on v5.0.0 (the first non-RC version that released today, but this has been happening since at least RC 12 or so)

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

This is only happening for me in Strapi Cloud. I contacted the Strapi Support team and they told me to report it here since they refuse to look at v5 issues.

I am not entirely sure what causes this error, but I have a Model that represents a navigation menu in a website. When trying to edit the Content for one item in that Model collection I cannot save changes because of the following error (pulled from Runtime Logs in my Strapi Cloud instance):

```
[2024-09-18 17:25:17] [2024-09-18 17:25:17.038] error: con.batchInsert is not a function
[2024-09-18 17:25:17] TypeError: con.batchInsert is not a function
[2024-09-18 17:25:17]     at /home/app/node_modules/@strapi/core/dist/services/document-service/utils/unidirectional-relations.js:52:17
[2024-09-18 17:25:17]     at /home/app/node_modules/@strapi/database/dist/index.js:6844:27
[2024-09-18 17:25:17]     at AsyncLocalStorage.run (node:async_hooks:346:14)
[2024-09-18 17:25:17]     at Object.run (/home/app/node_modules/@strapi/database/dist/index.js:2981:20)
[2024-09-18 17:25:17]     at Database.transaction (/home/app/node_modules/@strapi/database/dist/index.js:6835:27)
[2024-09-18 17:25:17]     at Module.sync (/home/app/node_modules/@strapi/core/dist/services/document-service/utils/unidirectional-relations.js:44:19)
[2024-09-18 17:25:17]     at publish (/home/app/node_modules/@strapi/core/dist/services/document-service/repository.js:237:35)
[2024-09-18 17:25:17]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-09-18 17:25:17]     at async /home/app/node_modules/@strapi/database/dist/index.js:6844:21
[2024-09-18 17:25:17]     at async Array.<anonymous> (/home/app/node_modules/@strapi/i18n/dist/server/index.js:52:20)
[2024-09-18 17:25:17] [2024-09-18 17:25:17.040] http: POST /content-manager/collection-types/api::menu.menu/usek1f3lgf2b2noicfia1wmn/actions/publish (415 ms) 500

```

### Expected behavior

I should be able to save my content with no errors.

### Screenshots

![Screenshot 2024-09-18 at 7 42 50 PM](https://github.com/user-attachments/assets/81a29e1f-a3ff-4b48-9a26-c9c044a691c3)

**Comment by alexandrebodin** [comment]
Hello @ryanvanderpol

Could you share the `schema.json` fiels of your models to help reproduce this issue ? 

I'll see if the cloud team is aware of anything



> [!NOTE]
> _Should not be related but so you are aware as you mentionned it_ 
> Have you cleared your database when moving from rc to stable ? We have tried our best to make it clear you should not reuse a RC app with the stable version. In particular the data might not be valid between different RC versions.

**Comment by ryanvanderpol** [comment]
@alexandrebodin here is my `schema.json` for the model that I am editing when the error occurs:

```
{
  "kind": "collectionType",
  "collectionName": "menus",
  "info": {
    "singularName": "menu",
    "pluralName": "menus",
    "displayName": "Menu",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "name": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string",
      "required": true,
      "unique": true
    },
    "title": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "items": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::menu-item.menu-item"
    },
    "secondaryItems": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::menu-item.menu-item"
    },
    "tertiaryItems": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::menu-item.menu-item"
    }
  }
}
```

**Comment by alexandrebodin** [comment]
@ryanvanderpol thanks ! could you also provide the menu-item schema to get the full picture 🙏 

The team will be work through all the new v5 issue in the upcoming days & weeks. We will do our best to fix everything as soon as we can 🙌

**Comment by ryanvanderpol** [comment]
yes, here is the `schema.json` for the `menu-item` schema:

```
{
  "kind": "collectionType",
  "collectionName": "menu_items",
  "info": {
    "singularName": "menu-item",
    "pluralName": "menu-items",
    "displayName": "Menu Item",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "url": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "title": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "icon": {
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ],
      "type": "media",
      "multiple": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    }
  }
}
```

**Comment by lokeshchoudharyprogrammer** [comment]
**resolve error "con.batchInsert is not a function.**
> node_modules\@strapi\core\dist\services\document-service\utils\unidirectional-relations.js


**Use knex.insert() instead of con.batchInsert()**

` await con.insert(newRelations).into(joinTable.name).transacting(trx); `
