### ISSUE TITLE
Deploy to Heroku does not work

### ISSUE THREAD

**Issue by jaubut** [strapi/strapi#2136]
**Informations**
- **Node.js version**: Node @latest
- **npm version**: @latest
- **Strapi version**: @latest
- **Database**: MongoDB
- **Operating system**: directly on heroku

**What is the current behavior?**

Application error after trying deploy to Heroku

**Steps to reproduce the problem**

Click the deploy to heroku button

**What is the expected behavior?**

no application error

**Suggested solutions**

**Comment by ryanbelke** [comment]
Adding to this, deployment from the CLI for a project and the push button Heroku deployment both fail with the same error:

Error message received in Heroku Logs:

2018-10-13T23:08:55.014388+00:00 app[web.1]: > server@0.1.0 start /app
2018-10-13T23:08:55.014390+00:00 app[web.1]: > node server.js
2018-10-13T23:08:55.014392+00:00 app[web.1]: 
2018-10-13T23:09:00.978879+00:00 app[web.1]: Query files
2018-10-13T23:09:00.979750+00:00 app[web.1]: Query role
2018-10-13T23:09:00.979902+00:00 app[web.1]: Query roles
2018-10-13T23:09:00.980143+00:00 app[web.1]: Mutation createRole
2018-10-13T23:09:00.980273+00:00 app[web.1]: Mutation updateRole
2018-10-13T23:09:00.980406+00:00 app[web.1]: Mutation deleteRole
2018-10-13T23:09:00.980580+00:00 app[web.1]: Mutation upload
2018-10-13T23:09:01.130935+00:00 app[web.1]: (node:22) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2018-10-13T23:09:01.244937+00:00 app[web.1]: error { MongoError: not authorized on strapi-production to execute command { find: "core_store", filter: { key: "plugin_content-manager_schema", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1539472133, 1), signature: { hash: BinData(0, 03C5C96D082B307649839F2D71B72457A3A4E40D), keyId: 6611834180592467969 } }, lsid: { id: UUID("ff43bf27-6a78-4db3-9d16-e1dbcc482ef6") }, $db: "strapi-production" }
2018-10-13T23:09:01.244954+00:00 app[web.1]:     at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:248:25)
2018-10-13T23:09:01.244956+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:532:18
2018-10-13T23:09:01.244958+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:61:11)
2018-10-13T23:09:01.244960+00:00 app[web.1]:   operationTime:
2018-10-13T23:09:01.244961+00:00 app[web.1]:    Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1539472133 },
2018-10-13T23:09:01.244963+00:00 app[web.1]:   ok: 0,
2018-10-13T23:09:01.244965+00:00 app[web.1]:   errmsg:
2018-10-13T23:09:01.244970+00:00 app[web.1]:    'not authorized on strapi-production to execute command { find: "core_store", filter: { key: "plugin_content-manager_schema", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1539472133, 1), signature: { hash: BinData(0, 03C5C96D082B307649839F2D71B72457A3A4E40D), keyId: 6611834180592467969 } }, lsid: { id: UUID("ff43bf27-6a78-4db3-9d16-e1dbcc482ef6") }, $db: "strapi-production" }',
2018-10-13T23:09:01.244972+00:00 app[web.1]:   code: 13,
2018-10-13T23:09:01.244973+00:00 app[web.1]:   codeName: 'Unauthorized',
2018-10-13T23:09:01.244975+00:00 app[web.1]:   '$clusterTime':
2018-10-13T23:09:01.244977+00:00 app[web.1]:    { clusterTime:
2018-10-13T23:09:01.244978+00:00 app[web.1]:       Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1539472133 },
2018-10-13T23:09:01.244980+00:00 app[web.1]:      signature: { hash: [Binary], keyId: [Long] } },
2018-10-13T23:09:01.244982+00:00 app[web.1]:   name: 'MongoError',
2018-10-13T23:09:01.244984+00:00 app[web.1]:   [Symbol(mongoErrorContextSymbol)]: {} }


Reproduce by deploying:
https://blog.strapi.io/deploying-a-strapi-api-on-heroku/

**Comment by xargr** [comment]
@ryanbelke the errors notice you not authorization, loot here: https://github.com/strapi/strapi/issues/2024#issuecomment-426718455

**Comment by kidtango** [comment]
I have similiar issues. My logs:
2018-10-16T12:08:46.601244+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-10-16T12:08:46.675887+00:00 heroku[web.1]: Process exited with status 137
2018-10-16T12:08:46.734614+00:00 heroku[web.1]: State changed from starting to crashed
2018-10-16T12:08:48.644265+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=uber-coral.herokuapp.com request_id=01d2be07-e002-49e8-a602-37d6bff71eb5 fwd="73.136.77.41" dyno= connect= service= status=503 bytes= protocol=https
2018-10-16T12:09:51.886946+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=uber-coral.herokuapp.com request_id=85386af0-2cd6-4175-a743-186d8f7ee930 fwd="73.136.77.41" dyno= connect= service= status=503 bytes= protocol=https
2018-10-16T12:09:52.280144+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=uber-coral.herokuapp.com request_id=73f3bfc7-9409-49cd-8b61-772058dae917 fwd="73.136.77.41" dyno= connect= service= status=503 bytes= protocol=https
2018-10-16T12:09:54.603545+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=uber-coral.herokuapp.com request_id=b82ea2bc-5264-4e2d-b310-6466d3fc072f fwd="73.136.77.41" dyno= connect= service= status=503 bytes= protocol=https
2018-10-16T12:09:54.832312+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=uber-coral.herokuapp.com request_id=04854a41-c8b6-4f91-80aa-fcafda60cc2d fwd="73.136.77.41" dyno= connect= service= status=503 bytes= protocol=https
2018-10-16T12:10:01.413834+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=uber-coral.herokuapp.com request_id=61501766-a8f6-4eeb-8465-b20abbebdc4b fwd="73.136.77.41" dyno= connect= service= status=503 bytes= protocol=https
2018-10-16T12:10:01.796525+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=uber-coral.herokuapp.com request_id=22ccdef3-a7a9-4d4d-8b8d-95f2fed8b9f1 fwd="73.136.77.41" dyno= connect= service= status=503 bytes= protocol=https

**Comment by juansaab** [comment]
Same issue here. Using the latest version. I remember to deploy using "strapi": "3.0.0-alpha.14" without problems. This is my current output:

`(node:22) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2018-10-17T00:57:45.610653+00:00 app[web.1]: error { MongoError: not authorized on strapi-production to execute command { find: "core_store", filter: { key: "plugin_content-manager_schema", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1539737860, 1), signature: { hash: BinData(0, 19F98F220DB4B40283B13F42C0A719CC52440AA7), keyId: 6613065466111852545 } }, lsid: { id: UUID("ab46e282-0782-4fda-8865-42f3f7fb9ac8") }, $db: "strapi-production" }`

**Comment by juansaab** [comment]
I managed to detect the release that stopped working on Heroku. I did downgrade the strapi dependency on my package.json from 14.3 to 14 and it deployed well. However, as soon as I updated to **3.0.0-alpha.14.1** it crashes. 

Hope it can help the team to start looking for the failure.

**Comment by kidtango** [comment]
@lauriejim, I tried everything! I even uploaded a test project to Heroku just to make sure it's nothing something else other than Strapi that may cause the remote server to not run. I even try to go through the Deliveroo project and followed the deployment instructions there! Same issue... I'm really not sure what is the problem. https://blog.strapi.io/strapi-next-deploy/

**Comment by juansaab** [comment]
> @lauriejim, I tried everything! I even uploaded a test project to Heroku just to make sure it's nothing something else other than Strapi that may cause the remote server to not run. I even try to go through the Deliveroo project and followed the deployment instructions there! Same issue... I'm really not sure what is the problem. https://blog.strapi.io/strapi-next-deploy/

If you're in a hurry, downgrade to version 14.0. I just did it and have it running. In order to downgrade you can update your package.json

`"dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-alpha.14",
    "strapi-hook-mongoose": "3.0.0-alpha.14"
  },`

**Comment by juansaab** [comment]
This issue might be related to #1831 but I'm not sure. @sundaycrafts

**Comment by juansaab** [comment]
@lauriejim I finally got alpha.14.3 working on heroku by applying #2153 last comment. It is important to note that on alpha.14 it was enough to set DATABASE_URI environment variable, this time, I was forced to set all the variables by hand. 

I took a long time checking diffs between both 14.0 and 14.3 tags and the only thing I noted was related to Mongo settings was the file modified by #1831 It might be a clue to fix both (Deploy Button and the DATABASE_URI as only variable) issues.

![image](https://user-images.githubusercontent.com/6313538/47062610-a64d7e80-d19c-11e8-8d98-b8c739dc8c5b.png)

**Comment by pierreburgy** [comment]
@juansaab yes it is related to #1831, please see my comment: https://github.com/strapi/strapi/pull/1831/files#diff-43153381da5552c728ec8acf21724e86R77.

**Comment by marieqg** [comment]
I had a similar issue today working. What solved it was in the package lock changing :"strapi": "3.0.0-beta.19.4" to "strapi": "3.0.0-beta.19". I'm just writting it so you are aware that this issue might still be existing in the beta version :)

**Comment by annie-elequin** [comment]
Yes, I also got to the "heroku open" part and the app crashed. 

The Heroku logs said it's an error code H10, with the path being "/" and "/favicon.ico". I'm almost positive I set everything up correctly, according to the instructions. 

I'm also on version beta.19.5

**Comment by lauriejim** [comment]
Here is 2 more video to deploy Strapi on Heroku. That can help.

[📺 Heroku + PG addon](https://www.youtube.com/watch?v=Qd-xpaT0c48&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=2&t=0s)

[📺 Heroku + MongoDB Atlas](https://www.youtube.com/watch?v=HHnRsZwFmR8&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=7&t=0s)

After that, your issue can be related to this one - https://github.com/strapi/strapi/issues/5696

But I just created a fresh new app with `3.0.0-beta.19.5` and successfully deployed it on Heroku + PG addon
