### ISSUE TITLE
Unable to publish an edited entry with a unidrectional relationship.

### ISSUE THREAD

**Issue by sbastias** [strapi/strapi#21408]
### Required System information

- Node.js version: v20
- NPM version: doesn't matter
- Strapi version: v5
- Database: postgres
- Operating system: linux
- Is your project Javascript or Typescript: JS

```
error: strapi.db.batchInsert is not a function
TypeError: strapi.db.batchInsert is not a function
    at /Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/core/dist/services/document-service/utils/unidirectional-relations.js:53:23
    at /Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/database/dist/index.js:6851:27
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.run (/Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/database/dist/index.js:2982:20)
    at Database.transaction (/Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/database/dist/index.js:6842:27)
    at Module.sync (/Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/core/dist/services/document-service/utils/unidirectional-relations.js:44:19)
    at publish (/Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/core/dist/services/document-service/repository.js:237:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/database/dist/index.js:6851:21
    at Array.<anonymous> (/Users/remed.io/Sites/2024/remedio/server/node_modules/@strapi/i18n/server/src/bootstrap.ts:34:21)
```

There is a missing await in unidirectional-relations.js (and mjs)
<img width="399" alt="image" src="https://github.com/user-attachments/assets/d38e2f3c-ce04-452e-a72a-ef5dd57f5c6f">

Adding await here fixed this bug.

HOWEVER - now I have a separate bug in the same function:

```
error: select * - SELECT * with no tables specified is not valid
    at Parser.parseErrorMessage (/Users/remed.io/Sites/2024/remedio/server/node_modules/pg-protocol/src/parser.ts:368:69)
    at Parser.handlePacket (/Users/remed.io/Sites/2024/remedio/server/node_modules/pg-protocol/src/parser.ts:187:21)
    at Parser.parse (/Users/remed.io/Sites/2024/remedio/server/node_modules/pg-protocol/src/parser.ts:102:30)
    at Socket.<anonymous> (/Users/remed.io/Sites/2024/remedio/server/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Steps to reproduce the behavior

1. Create a unidrectional relationship
2. Publish a record
3. Try update record

**Comment by sbastias** [comment]
I solved this in the database/index file and submitted a Pull Request #21412

**Comment by dzakki** [comment]
when is it going to be released?  @sbastias

**Comment by bolg55** [comment]
PR #18474 and #18857 should address this issue.

**Comment by Bassel17** [comment]
fixed by #21404
thanks for reporting this issue
