### ISSUE TITLE
documentId and refId of `/api/upload`

### ISSUE THREAD

**Issue by ukjinjang** [strapi/strapi#21427]
### Required System information

- Node.js version: 20.5.1
- NPM version: 9.8.0
- Strapi version: 5.0.0
- Database: PostgreSQL 16.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Operating system: MacOS 14.5
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I want to create a new entry and make a relation between the entry and media (image) via `/api/upload`, but an error occurs:

```
[2024-09-24 01:41:32.827] error: Expected a valid Number, got ash2dmlzgq5165le7dmddcjx
Error: Expected a valid Number, got ash2dmlzgq5165le7dmddcjx
    at NumberField.toDB (/Users/strapi/node_modules/@strapi/database/dist/index.js:2818:13)
    at castValue (/Users/strapi/node_modules/@strapi/database/dist/index.js:3934:42)
    at processSingleAttributeWhere (/Users/strapi/node_modules/@strapi/database/dist/index.js:3941:14)
    at /Users/strapi/node_modules/@strapi/database/dist/index.js:3957:31
    at Array.map (<anonymous>)
    at processAttributeWhere (/Users/strapi/node_modules/@strapi/database/dist/index.js:3957:18)
    at processSingleAttributeWhere (/Users/strapi/node_modules/@strapi/database/dist/index.js:3951:20)
    at processAttributeWhere (/Users/strapi/node_modules/@strapi/database/dist/index.js:3959:10)
    at processWhere (/Users/strapi/node_modules/@strapi/database/dist/index.js:4043:36)
    at processNested (/Users/strapi/node_modules/@strapi/database/dist/index.js:3965:10)
[2024-09-24 01:41:32.829] http: POST /api/upload (1196 ms) 500
```

### Steps to reproduce the behavior

1. Create a new entry by using `[POST] /api/{collection_name}`.
1. Get the `documentId` from the API call's response and use it as `refId` for `[POST] /api/upload`.
1. Encounter the error `Expected a valid Number, got {document_id}`.

### Expected behavior

According to the documentation [from v5 `document_id` replaces the role of `id`](https://docs.strapi.io/dev-docs/migration/v4-to-v5/breaking-changes/use-document-id), and example code shows that `refId` should accept a `document_id` (not a numeric `id`).

![image](https://github.com/user-attachments/assets/743ddd60-9cef-4298-b8e6-345bf834174e)

Additionally, the schema and type definitions state that `refId` accepts a `string` (... which means `document_id` I guess ...)

https://github.com/strapi/strapi/blob/d2d15ef227d67cce89c2673764c0555c841cd29c/packages/core/upload/documentation/content-api.json#L36-L39

https://github.com/strapi/strapi/blob/8dc5aa273027084a90fa711e4068dfa8fbd09e1e/packages/core/upload/server/src/types.ts#L29-L33

### Code snippets

```ts
const { data } = await fetch('/api/board-posts', { ... });

const body = new FormData();
body.append('files', file, filename);
body.append('ref', 'api::board-post.board-post');
body.append('refId', data.documentId); // `ash2dmlzgq5165le7dmddcjx`
body.append('field', 'thumbnail');

await fetch('/api/upload', { body });
```

### Additional context

If `refId` is not meant to accept `document_id` but rather a numeric `id`, how do I upload an image to display it in the collection table, as already raised in https://github.com/strapi/strapi/issues/21125#issuecomment-2323280759?

**Comment by Antonio112009** [comment]
Fun fact: Not documentId, but just ID. I faced the same issue

**Comment by Antonio112009** [comment]
I am with you!

**Comment by carlosmoncanstgo** [comment]
I am in the same situation. Any solution or recommendation?

**Comment by jumptrnr** [comment]
Not sure if is right but until this is fixed...  
I provided a custom generateUploadFileName in my plugins.js file like so .... 

Still testing but so far so good.

```
config: {
  provider: "@strapi-community/strapi-provider-upload-google-cloud-storage",
  providerOptions: {
    bucketName: env("PUBLIC_BUCKET") ,
    publicFiles: true,
    uniform: false,
    basePath: "",
    debug: true,

    generateUploadFileName: async (file) => {
      // Get related entity info
      const relatedEntity = file.related[0];
      const { __type: type, id } = relatedEntity;

      // Store original ID for reference
      file.documentId = id;

      // Fetch the full document using Strapi's Database API
      const document = await strapi.db.query(type).findOne({
        where: { documentId: id },
      });

      // Update related entity with document ID
      relatedEntity.id = document?.id;

      // Return the new name (modify this as needed)
      return file.name; // Or a different naming scheme if desired
    },
  },
},```

**Comment by Antonio112009** [comment]
Any updates on the issue?

**Comment by reslear** [comment]
same problem, any news?

**Comment by radulescuandrew** [comment]
Same issue here.

I created an entity, and I used the returned `documentId` to link the uploaded images. 

It didn't work, I receive the same issue as the OP and I switched to ID without thinking. Later realised the ID is different than the published entity ID, so it's not gonna work.

Is there any timeline for this issue? It seems a quick fix

**Comment by reslear** [comment]
![Image](https://github.com/user-attachments/assets/b378682a-6531-40e2-8cda-d449e4b9f439)

**Comment by Kaherdin** [comment]
No solutions or update ??!?

**Comment by garkuwa** [comment]
A temporary workaround is to override the `upload` method of the `upload` service in the `upload` plugin.
Create file `extensions/upload/strapi-server.ts` with the following code:

```
type MetasType = {
  refId: string;
  ref: string;
  field: string;
};

module.exports = (plugin) => {
  const oldUploadServiceUpload = plugin.services.upload;

  plugin.services.upload = ({ strapi }) => {
    const oldFunctions = oldUploadServiceUpload({ strapi });

    return {
      ...oldFunctions,
      upload: async ({ data, files }, opts) => {
        const { fileInfo, ...metas } = data;
        const { refId, ref, field } = metas as MetasType;

        let newMetas: MetasType = metas;

        if (refId && ref && field) {
          // Fetch the full document using Strapi's Database API
          const document = await strapi.db.query(ref).findOne({
            where: { documentId: refId },
          });

          newMetas = {
            ...metas,
            refId: document.id,
          };
        }

        return oldFunctions.upload(
          { data: { fileInfo, ...newMetas }, files },
          opts,
        );
      },
    };
  };

  return plugin;
};

```

It's not ideal, but it works.

**Comment by LeftoversTodayAppAdmin** [comment]
Hey folks!
Just upgraded to Strapi5 and I am running into the same issue. The upload API is expecting the integer ID of the document and fails when uploading with the new documentId that is used everywhere in Strapi5.

**Comment by Vicargo** [comment]
Any news?

**Comment by fahimrayhan** [comment]
![Image](https://github.com/user-attachments/assets/fd8b5866-6da3-4ee2-a84a-fa1b66ec7f30)

**Comment by alexandrebodin** [comment]
Hello, 

In v5 there is a breaking change with the new Draft & publish capabilities add multiple "versions" to each document, which means multiple rows in DB. Althgouh each version are independt so you can have different content between each. The result is that you cannot use the documentId in the image upload (we leave it as a low level if you really need to but this doesn't follow the d&p workflows) . The refId if you still want to use it should point to a low level `id`. 

We really recommand you  use what @hennzen shared which is the recommended way 
1. upload  the image.
2. use the image `id` in the Content API to connect to a media field

**Comment by laurentsenta** [comment]
Could you at least update the [documentation](https://docs.strapi.io/cms/api/rest/upload#upload-entry-files)?

It shows and example using

```html
  <input type="text" name="refId" value="5c126648c7415f0c0ef1bccd" />
```

Which is clearly not a numeric id but a documentId.

**Comment by manuelffernandez** [comment]
I ran into the same problem and worked around it by relying on the **response payload** from the Upload API. There’s also a second issue (see #21967): the numeric `id` that Strapi returns when you create/find a collection record doesn’t match what you see in the admin panel. That’s annoying because the `refId` field seems intended to use the numeric `id` rather than the `documentId` (even though the docs suggest otherwise), and you still can’t rely on it.

Fortunately, when you upload a file via the Upload API (`/api/upload`), the returned media `id` **does** match correctly—unlike what happens with custom collections. So my workaround is a two-step flow: first upload the file, then create the collection record using the uploaded media `id`. The downside is you need two requests to create a single record.

Suppose you have a `Pet` collection with these fields:

* `name` (string)
* `age` (number)
* `picture` (file)

```ts
// 1) Upload the file
const formData = new FormData();
formData.append("files", file);

const fileRes = await fetch(`${process.env.STRAPI_URL}/api/upload`, {
  method: "POST",
  body: formData,
  // headers: { Authorization: `Bearer ${TOKEN}` } // if your API is protected
});

if (!fileRes.ok) throw new Error("Upload failed");

const fileJson = await fileRes.json();
// Strapi upload usually returns an array of files
const uploaded = Array.isArray(fileJson) ? fileJson[0] : fileJson;
const mediaId = uploaded?.id;

if (!mediaId) throw new Error("No media id returned from /api/upload");

// 2) Create the record referencing the uploaded media id
const record = {
  data: {
    name: "Kitty",
    age: 6,
    picture: mediaId, // link the uploaded media
  },
};

const res = await fetch(`${process.env.STRAPI_URL}/api/pets`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    // Authorization: `Bearer ${TOKEN}`, // if required
  },
  body: JSON.stringify(record),
});

if (!res.ok) throw new Error("Creating pet failed");
const pet = await res.json();
```

Hope this help.

**Comment by sylvainGarnot** [comment]
@hennzen 's solution worked for me. Thanks !



```js
// UPLOAD FILE
const formData = new FormData();
formData.append('files', file);

await axios.post(`${API_URL_LOCAL}/upload`,
  formData
)
  .then(async (upload_file_response) => {
    const uploadData = upload_file_response.data[0];

    // UPDATE COLLECTIBLE WITH FILE RELATION
    await axios.put(`${API_URL_LOCAL}/collectibles/${collectible.documentId}`, {
      data: {
        image: {
          connect: [uploadData.id]
        }
      }
    })
  })
```

**Comment by EgleKat** [comment]
We encountered another issue with the API. We use C# ASP.NET to create an entry and then attach a file to that entry. As others pointed out, the api expects a numeric `id`, `documentID` did not work for us, so we had to use `id`.
Following that, we found that ASP.NET set the content headers as strings, which failed silently. Even if we set the content header for `refId` to null, the request would not succeed. 

After some testing, we found that the `ref` attribute header also has to be set to null. Hope this helps someone, cause the docs do not explain that.

```c#
            var fileContent = new StreamContent(fileStream);
            fileContent.Headers.ContentType = new MediaTypeHeaderValue(MimeTypeHelper.GetMimeTypeFromFileName(file.FileName));

            var formContent = new MultipartFormDataContent
            {
                { fileContent, "files", file.FileName },
                { new StringContent(entryId.ToString(), mediaType: null), "refId" },
                { new StringContent("api::article.article", mediaType: null), "ref" },
                { new StringContent("Image", mediaType: null), "field" }
            };
```
