### ISSUE TITLE
Type error thrown when exiting Strapi V5

### ISSUE THREAD

**Issue by birdzai** [strapi/strapi#21458]
### Required System information

- NPM version: npm/10.5.0 node/v20.12.2 darwin arm64 workspaces/false
- Strapi version: 5.0.0
- Database: Postgres 16.3 (running in Docker Alpine)
- Operating system: MacOS 15.0
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Received the following exception when stopping Strapi5 in dev mode by hitting CONTROL-C

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡️, go to:
http://localhost:1337

[2024-09-24 14:59:43.890] info: Strapi started successfully
^C[2024-09-24 14:59:46.317] info: Shutting down Strapi
[2024-09-24 14:59:46.318] info: Shutting down Strapi

[2024-09-24 14:59:46.336] info: Strapi has been shut down                                                                                   
/Users/dave/Code/Playground/7kwonders-strapi5/node_modules/@strapi/admin/server/src/destroy.ts:4
  const { conditionProvider, actionProvider } = getService('permission');
          ^
TypeError: Cannot destructure property 'conditionProvider' of 'getService$1(...)' as it is undefined.
    at Object.destroy$1 (/Users/dave/Code/Playground/7kwonders-strapi5/node_modules/@strapi/admin/server/src/destroy.ts:4:11)
    at Object.destroy (/Users/dave/Code/Playground/7kwonders-strapi5/node_modules/@strapi/core/dist/providers/admin.js:16:32)
    at Strapi.destroy (/Users/dave/Code/Playground/7kwonders-strapi5/node_modules/@strapi/core/dist/Strapi.js:396:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async process.terminateStrapi (/Users/dave/Code/Playground/7kwonders-strapi5/node_modules/@strapi/core/dist/utils/signals.js:8:7)

Node.js v20.12.2

### Steps to reproduce the behavior

1. yarn dev
2. hit CONTROL-C after startup

### Expected behavior

Clean shutdown

### Discord post

First discussed here(https://discord.com/channels/811989166782021633/1288243288926720041)

**Comment by ulmetum** [comment]
Same here
