### ISSUE TITLE
Serious issue, cannot find the Collection route I created in Create API Token

### ISSUE THREAD

**Issue by JiveCheng** [strapi/strapi#21478]
- Node.js version: v20.17.0
- NPM version: 10.8.1
- Strapi version: 5.0.1
- Database: sqlite
- Operating system: windows 11
- Is your project Javascript or Typescript: js

### Describe the bug

cannot find the Collection route I created in Create API Token

### Screenshots

![image](https://github.com/user-attachments/assets/ea7037eb-a295-4159-aa0b-b2c1a7bb3a9c)
![image](https://github.com/user-attachments/assets/dd9e7b41-9b76-4e31-abe8-9baffb770752)

### Additional context

[2024-09-26 16:54:26.349] error: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at filterContentAPI (C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\@strapi\core\dist\services\content-api\index.js:15:48)
    at Array.filter (<anonymous>)
    at C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\@strapi\core\dist\services\content-api\index.js:25:10
    at C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\lodash\lodash.js:3032:24)
    at C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\lodash\lodash.js:4936:18
    at Function.forEach (C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\lodash\lodash.js:9410:14)
    at Object.getRoutesMap (C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\@strapi\core\dist\services\content-api\index.js:19:24)
    at Object.getRoutes (C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\@strapi\admin\server\src\controllers\content-api.ts:13:47)
    at dispatch (C:\Users\jivec\Projects\buy4esg\goodthings\node_modules\koa-compose\index.js:42:32)
[2024-09-26 16:54:26.352] http: GET /admin/content-api/routes (33 ms) 500

**Comment by gacek1123** [comment]
Having this issue on Strapi v5.10.4, Node v22.14.0

**Comment by Adzouz** [comment]
Hi @JiveCheng, thanks a lot for reporting the issue! I tested it on my side but I couldn't reproduce.
Is it still broken? If so, can you provide more steps to reproduce the issue please?

Here's my test (on Strapi 5.14.0):
https://github.com/user-attachments/assets/8626dfb0-3c2c-424e-966e-9670b531796b

**Comment by GianlucaFrongia** [comment]
also having this issue in Strapi v5.19.0

**Comment by Adzouz** [comment]
Hi there! Sorry for the late answer, I checked and now I understand better the issue. Will do a PR asap to fix this. 🙏
