### ISSUE TITLE
MySQL database connection issues

### ISSUE THREAD

**Issue by AbsoDao** [strapi/strapi#21570]
When I use the Mysql database to install with localhost as the database hostname, I get the following error when I run npm run develop after installation:
❌
Error: Access denied for user 'strapi'@'127.0.0.1' (using password: YES)     
at Packet.asError (/mypath/strapi/node_modules/mysql2/lib/packets/packet.js:738:17)                                                   at ClientHandshake.execute (/mypath/strapi/node_modules/mysql2/lib/commands/command.js:29:26)                                         at Connection.handlePacket (/mypath/strapi/node_modules/mysql2/lib/connection.js:481:34)                                              at PacketParser.onPacket (/mypath/strapi/node_modules/mysql2/lib/connection.js:97:12)                                                 at PacketParser.executeStart (/mypath/strapi/node_modules/mysql2/lib/packet_parser.js:75:16)                                          at Socket.<anonymous> (/mypath/strapi/node_modules/mysql2/lib/connection.js:104:25)                                                   at Socket.emit (node:events:519:28) 
at Socket.emit (node:domain:488:12)
at addChunk (node:internal/streams/readable:559:12) 
at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
- Node.js version:v20.17.0
- NPM version:10.8.3
- Strapi version:5.0.2
- Database:mysql
- Operating system:Fedora Linux
- Is your project Javascript or Typescript:Typescript

**Comment by MuniKiranCh** [comment]
Once try this,
-- Replace 'your_password' with the actual password for the 'strapi' user
CREATE USER 'strapi'@'127.0.0.1' IDENTIFIED BY 'your_password';

-- Grant all privileges to the strapi user on the desired database (replace 'your_database' with the actual database name)
GRANT ALL PRIVILEGES ON your_database.* TO 'strapi'@'127.0.0.1';

-- Make sure to apply the changes
FLUSH PRIVILEGES;
