### ISSUE TITLE
Strapi 5 migration, unable to create index because it already exists

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#21583]
### Required System information

- Node.js version: v20
- NPM version: latest that comes with 20
- Strapi version: 5.0.2
- Database: Strapi Cloud
- Operating system: Strapi Cloud
- Is your project Javascript or Typescript: JS

### Describe the bug

When migrating the application from Strapi 4 to Strapi 5 and deploying on cloud, in some cases the following error will happen causing the migration to fail and automatic rollback to last known good config also fails (requires restoring a database backup)

```
2024-10-03T15:58:29.932875243Z [2024-10-03 15:58:29.929] [34mdebug[39m: ⛔️ Server wasn't able to start properly.
2024-10-03T15:58:29.941316973Z [2024-10-03 15:58:29.937] [31merror[39m: create index "admin_permissions_role_links_fk" on "public"."admin_permissions_role_links" ("permission_id") - relation "admin_permissions_role_links_fk" already exists
2024-10-03T15:58:29.941346537Z error: create index "admin_permissions_role_links_fk" on "public"."admin_permissions_role_links" ("permission_id") - relation "admin_permissions_role_links_fk" already exists
2024-10-03T15:58:29.941352103Z     at Parser.parseErrorMessage (/home/app/node_modules/pg-protocol/dist/parser.js:283:98)
2024-10-03T15:58:29.941356317Z     at Parser.handlePacket (/home/app/node_modules/pg-protocol/dist/parser.js:122:29)
2024-10-03T15:58:29.941361474Z     at Parser.parse (/home/app/node_modules/pg-protocol/dist/parser.js:35:38)
2024-10-03T15:58:29.941365559Z     at TLSSocket.<anonymous> (/home/app/node_modules/pg-protocol/dist/index.js:11:42)
2024-10-03T15:58:29.941370996Z     at TLSSocket.emit (node:events:519:28)
2024-10-03T15:58:29.941375536Z     at TLSSocket.emit (node:domain:488:12)
2024-10-03T15:58:29.941380295Z     at addChunk (node:internal/streams/readable:559:12)
2024-10-03T15:58:29.941385786Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2024-10-03T15:58:29.941390026Z     at Readable.push (node:internal/streams/readable:390:5)
2024-10-03T15:58:29.941394158Z     at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)
```

### Steps to reproduce the behavior

Unknown steps to reproduce at this time

### Expected behavior

Migration shouldn't fail and schema inspection shouldn't try to create indexes that already exist or fail gracefully

### Screenshots

N/A

### Code snippets

N/A

### Additional context

Related TID: 8413 and 8397

**Comment by derrickmehaffy** [comment]
Could be possibly fixed by https://github.com/strapi/strapi/pull/21576

**Comment by innerdvations** [comment]
We've narrowed down the reproduction:

- Start with Strapi 4
- content type with d&p disabled
- has an enum field
- there is invalid data for that enum field in the database, for example your enum allows red, green, and blue, but you have a value in your database of green
- migrate to Strapi 5
- Migration fails

Workaround until we fix the issue and allow copying over the "bad" data would be to clean the v4 database before migration of invalid enum data. You could search the db and add back any of those values to the enum attribute, or delete them from the database.
