### ISSUE TITLE
MigrationError: Migration core::5.0.0-discard-drafts

### ISSUE THREAD

**Issue by CROmartin** [strapi/strapi#21624]
### Required System information

- Node.js version: 20.12.2
- NPM version: 10.5
- Strapi version: 4.25.13
- Database: Postgresql
- Operating system: MacOS
- Is your project Javascript or Typescript: JS

### Describe the bug

I am working on an existing V4 Strapi project, which means that the Database is already full of all sorts of important data. Initially, this project was a low V4 version, in the meantime project was upgraded to a maximum V4 version, and after that, I tried upgrading it to V5, and then major issues occurred that I couldn't solve. 

First I installed V5 dependencies and then I executed this command:

(base) martinstaresincic@MacBook-Pro-3 humanava_backend % yarn develop
yarn run v1.22.21
$ strapi develop
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (88ms)
✔ Creating admin (481ms)
⠴ Loading Strapi(node:14287) Warning: S3 configuration options passed at root level of the plugin's providerOptions is deprecated and will be removed in a future release. Please wrap them inside the 's3Options:{}' property.
(Use `node --trace-warnings ...` to show where the warning was created)
⠦ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

 MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: con.batchInsert is not a function
at /Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/umzug/lib/umzug.js:169:27 
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Umzug.runCommand                                                                                              (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/umzug/lib/umzug.js:125:20)
at async Object.up                                                                                                 (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/@strapi/database/dist/index.js:6531:7)         
at async Object.up                                                                                                      (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/@strapi/database/dist/index.js:6555:11) at async Object.sync  (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/@strapi/database/dist/index.js:2246:9)
at async Strapi.bootstrap  (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/@strapi/core/dist/Strapi.js:351:5)
at async Strapi.load                        (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/@strapi/core/dist/Strapi.js:315:5) 
at async Module.develop                        (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/@strapi/strapi/dist/node/develop.js:177:28)
at async action (/Users/martinstaresincic/Documents/Nodejs/humanava_backend/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5) 

This resulted in a migration error, I have tried playing with the package version, and investigating what other people did, but it seems like generally people are getting stuck on V4 to V5 migration. At this point, I am wondering if making a clean V5 Strapi project and then slowly migrating relevant to it would make more sense than expecting Strapi to successfully apply migrations.

### Steps to reproduce the behavior

1. Create a Strapi V4 project with Postgresql DB
2. Populate DB with some data
3. Initialize migration to V5
4. Install packages
5. Start server
6. See error

### Expected behavior

Migrations were applied successfully without any error and the server started successfully. 

### Screenshots

<img width="896" alt="Screenshot 2024-10-08 at 11 46 31" src="https://github.com/user-attachments/assets/6474a0ab-60c3-4c1d-825a-3e688b04b938">

### Additional context

I would like to note here once again that this error occurs project that was first created on a low version of Strapi, maybe even Strapi V3, although I received this project when it was on a really low version of Strapi V4. Maybe the long history of the project causes errors somehow.

**Comment by FarisCode** [comment]
Facing same issue, I had my project initially built with Strapi v3, which I later migrated to v4 and now v5. 
While running it locally it keeps stuck on `Loading Strapi` and after a while throws the same error as above.
I am on 5.0.3 version (which claims to have fixed it)

**Comment by Marc-Roig** [comment]
working on this one! 

Fix should be in https://github.com/strapi/strapi/pull/21404 , but our upgrade tool tries to upgrade to 5.0.0 version instead of a latter version that contains the fix.

As a temporary measure, if you manually update your package json to the latest version it should work.

@FarisCode could you verify you were using the latest version while running the migration?

**Comment by softwareshaper** [comment]
hello, 
I had same issue,
workaround: 
just run 
`npx @strapi/upgrade minor`
after 
`npx @strapi/upgrade major`
it will upgrade to latest strapi version with the fix :
> Strapi started successfully

**Comment by alaindimabuyo** [comment]
this is painful none of the solutions work im on the latest version 5.0.6 and this errors comes up  core::5.0.0-discard-drafts 

upgrades and changing node versions dont work and i dont want to create another strapi project just to make it work
