### ISSUE TITLE
Column "auto_sync" in navigations_items 

### ISSUE THREAD

**Issue by MarwanEsm** [strapi/strapi#21772]
### Required System information

- Node.js version: v18.20.4
- NPM version: 10.8.1
- Strapi version: ^4.24.2
- Typescript:

### Describe the bug

column "auto_sync" of relation "navigations_items" does not exist

### Steps to reproduce the behavior

1. Go to UI Navigation 
2. Click on addd new item
3. Save it
4. See Strapi Error log : 
[2024-10-09 06:39:23.816] error: insert into "kag"."navigations_items" ("additional_fields", "auto_sync", "collapsed", "created_at", "menu_attached", "order", "path", "title", "type", "ui_router_key", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) returning "id" - column "auto_sync" of relation "navigations_items" does not exist
error: insert into "kag"."navigations_items" ("additional_fields", "auto_sync", "collapsed", "created_at", "menu_attached", "order", "path", "title", "type", "ui_router_key", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) returning "id" - column "auto_sync" of relation "navigations_items" does not exist
at Parser.parseErrorMessage (/opt/app/node_modules/pg-protocol/dist/parser.js:283:98)
at Parser.handlePacket (/opt/app/node_modules/pg-protocol/dist/parser.js:122:29)
at Parser.parse (/opt/app/node_modules/pg-protocol/dist/parser.js:35:38)
at Socket.<anonymous> (/opt/app/node_modules/pg-protocol/dist/index.js:11:42)
at Socket.emit (node:events:517:28)
at Socket.emit (node:domain:489:12)
at addChunk (node:internal/streams/readable:368:12)
at readableAddChunk (node:internal/streams/readable:341:9)
at Readable.push (node:internal/streams/readable:278:10)
at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

### Expected behavior
To save new navigation item without an issue

## Additional context
Will this error be fixed if I update to the new version ?
What would you recommand in case I want my project to be on the same current version ^4.24.2 ?

**Comment by bolg55** [comment]
Are you able to reproduce on multiple content types with relations, or is this limited to just the one? Seems like this might be specific to your project. Can you remove your node_modules and .lock file and try reinstalling? 

If you can reproduce with a different content type and share here, that would be useful. Also recommend upgrading to the most recent v4 version as well.
