### ISSUE TITLE
v4 -> v5 seems to cause error when signing jwt

### ISSUE THREAD

**Issue by KateCourt** [strapi/strapi#21939]
### Required System information

- Node.js version: v18.20.3
- NPM version: 10.7.0
- Strapi version: 5.1.0
- Database: mysql2
- Operating system: macOS 14.6.1 darwin-arm64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I followed the Strapi 5 migration guide after previously using Strapi 4. Logging in and providing user with a jwt was working previously. After migration, strapi builds successfully, but when logging in, I get this error 

```
[2024-10-22 15:02:04.925] error: secretOrPrivateKey must have a value
Error: secretOrPrivateKey must have a value
    at module.exports [as sign] (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/jsonwebtoken/sign.js:105:20)
    at issueJWT (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/src/extensions/users-permissions/strapi-server.js:27:14)
    at plugin.controllers.auth.callback (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/src/extensions/users-permissions/strapi-server.js:149:16)
    at async returnBodyMiddleware (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
    at async policiesMiddleware (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
    at async /Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
    at async /Users/nkc124/Documents/GitHub/orqa/orqa-strapi/src/middleware/register.js:5:7
    at async /Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
    at async /Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/middlewares/logger.js:6:5
    at async cors (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@koa/cors/index.js:64:16)
    at async /Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/middlewares/powered-by.js:9:5
    at async cors (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@koa/cors/index.js:106:16)
    at async /Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/middlewares/errors.js:8:7
    at async session (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/koa-session/index.js:41:7)
    at async middleware (/Users/nkc124/Documents/GitHub/orqa/orqa-strapi/node_modules/@strapi/strapi/dist/services/metrics/middleware.js:20:5)

```

### Steps to reproduce the behavior

1. Upgrade to v5 using `npx @strapi/upgrade major`
2. Submit request to login endpoint

### Expected behavior

User is supplied with a jwt. 

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Your missing the required environment variable in your .env, you should have a `.env.example` file that should show all of the env variables.

**Comment by KateCourt** [comment]
@derrickmehaffy thank you for your help. This is our (abbreviated) env file. Are you able to point me to the environment variable that needs adding please? Is this something that needs adding specifically when upgrading?
```
HOST=127.0.0.1
PORT=1337
URL='http://localhost:1337'
APP_KEYS="toBeModified1,toBeModified2"
API_TOKEN_SALT=tobemodified
REFRESH_SECRET=secret
REFRESH_TOKEN_EXPIRES=2d
JWT_SECRET_EXPIRES=360s
NODE_ENV=development
ADMIN_JWT_SECRET=tobemodified
JWT_SECRET=tobemodified
DATABASE_NAME=orqa
DATABASE_USERNAME=root
DATABASE_PASSWORD=tobemodified
DATABASE_SSL=true
DATABASE_PORT=3306
DATABASE_HOST=127.0.0.1
PUBLIC_URL=tobemodified
PUBLIC_ADMIN_URL=tobemodified
...
```

**Comment by KateCourt** [comment]
Thanks, yes this is an example one, the other one has the correct values (I am using it for strapi v4 with no problems). I have changed nothing on the branch that fails other than upgrading to v5

**Comment by derrickmehaffy** [comment]
Can you try reproducing this in a new project and see if the issue occurs there also?

Else I'd you can link me to your project code I could take a quick look

**Comment by KateCourt** [comment]
Thank you, I will try in a new project this morning and have sent you an invite to our project, that is very generous of you to offer
