### ISSUE TITLE
Multiple Relation Operations prevent Publishing via UI Admin

### ISSUE THREAD

**Issue by zmdavis15** [strapi/strapi#21959]
### Required System information

Environment: development
OS: win32-x64
Strapi Version: 5.1.1
Node/Yarn Version: npm/10.8.2 node/v20.14.0 win32 x64 workspaces/false
Edition: Community
Database: sqlite

### Describe the bug

When I remove a component's relation, add a new relation, rearrange the new relation, then try publishing, it fails/errors out. So basically -- multiple operations before publishing will cause error. Workaround is to publish between each operation.

### Steps to reproduce the behavior

1. Open Content Type entry for editing.
2. Find nested component (in this case, a repeatable component inside a component inside a dynamic zone)
3. Find component relation field.
4. Expand visible relations so all relations are showing.
5. Remove one relationship (press x on row)
6. add one relationship
7. re-arrange relationships by dragging newly added relationship upwards through list

### Expected behavior

I expect it to publish without error.

### Code snippets
```
[2024-10-23 12:54:55.638] error: Expected a valid Number, got dcigkgvfz8kwf7p5wr59adz6
Error: Expected a valid Number, got dcigkgvfz8kwf7p5wr59adz6
    at NumberField.toDB (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:2818:13)
    at castValue (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:3934:42)
    at processSingleAttributeWhere (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:3941:14)
    at C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:3957:31
    at Array.map (<anonymous>)
    at processAttributeWhere (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:3957:18)
    at processSingleAttributeWhere (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:3951:20)
    at processAttributeWhere (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:3959:10)
    at processWhere (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:4043:36)
    at processNested (C:\Users\user\Desktop\my_strapi_dir\my_strapi_project\strapi\node_modules\@strapi\database\dist\index.js:3965:10)
```

##### Related performance issues?
* Every letter that I type in the relation field makes an HTTP request (javascript does not wait for me to stop typing)
* When I drag a relation above or below an.other relation, Strapi makes an HTTP request.
* This happened in V5 (I migrated from V4 following the migration guide)

**Comment by derrickmehaffy** [comment]
This should be fixed in later versions of Strapi 5 as I couldn't reproduce in v5.4.2
