### ISSUE TITLE
`useContentManagerInitData` must be used within `StrapiApp` error in Strapi project

### ISSUE THREAD

**Issue by Liberty-slug** [strapi/strapi#21973]
This will be the first time I am getting this error message in strapi. I deployed my strapi project on shared host cpanel, I want able to deploy it to work. When I registered and logged in I got no error on the home page, but when I clicked on content manager, Media Library and Content-Type builder I got the following error.

For Content Manager

`Error: `useContentManagerInitData` must be used within `StrapiApp`
    at https://strapi.demia.org/admin/strapi-HBU9X4md.js:2448:6808
    at Kle (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2293:4907)
    at i (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2448:6775)
    at Fe (https://strapi.demia.org/admin/layout-CrTxOnCy-DGaBQwRX.js:28:1605)
    at Ye (https://strapi.demia.org/admin/layout-CrTxOnCy-DGaBQwRX.js:28:3638)
    at f$ (https://strapi.demia.org/admin/strapi-HBU9X4md.js:40:17031)
    at QX (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:44091)
    at WX (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39809)
    at ITe (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39735)
    at HS (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39585)`

For Media Library

`Error: `useRBAC` must be used within `Auth`
    at https://strapi.demia.org/admin/strapi-HBU9X4md.js:2448:6808
    at Kle (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2293:4907)
    at i (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2448:6775)
    at wl (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2463:2412)
    at dhe (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2575:64396)
    at Xs (https://strapi.demia.org/admin/index-fPsIi9fE-Dirr-e3P.js:14:119)
    at f$ (https://strapi.demia.org/admin/strapi-HBU9X4md.js:40:17031)
    at QX (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:44091)
    at WX (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39809)
    at ITe (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39735)`

For Content-Type Builder
`Error: `App` must be used within `GuidedTour`
    at https://strapi.demia.org/admin/strapi-HBU9X4md.js:2448:6808
    at Kle (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2293:4907)
    at i (https://strapi.demia.org/admin/strapi-HBU9X4md.js:2448:6775)
    at iT (https://strapi.demia.org/admin/index-BOhrbpg6-DvpaPyAk.js:179:23128)
    at f$ (https://strapi.demia.org/admin/strapi-HBU9X4md.js:40:17031)
    at QX (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:44091)
    at WX (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39809)
    at ITe (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39735)
    at HS (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:39585)
    at LO (https://strapi.demia.org/admin/strapi-HBU9X4md.js:42:35947)`

Has anyone experienced this to help kindly? All other pages are showing correctly without error.
![Screenshot 2024-10-24 103240](https://github.com/user-attachments/assets/dd1e168d-2dcb-483d-859f-ce1aa331bb5e)
![Screenshot 2024-10-24 103315](https://github.com/user-attachments/assets/07076c30-dcae-47df-9e27-4525af6e5bf5)
![Screenshot 2024-10-24 103338](https://github.com/user-attachments/assets/3df2effc-23b0-47f0-a3cd-0993c5f812dc)

**Comment by zhenzhenChange** [comment]
The problem may be with the `@strapi/strapi` dependency.

Reasons (may not be entirely correct):
- Missing this dependency
- Multiple instances of this dependency exist, there are multiple instances of this dependency, especially in monorepo

If you're in monorepo, set the `@strapi/strapi` dependency of the sub package to `peerDependencies`.

**Comment by innerdvations** [comment]
Duplicate of https://github.com/strapi/strapi/issues/21151
