### ISSUE TITLE
Minor update causes bug on every Strapi page

### ISSUE THREAD

**Issue by frontBOI** [strapi/strapi#21982]
### Required System information

- Node.js version: 20.17.0
- NPM version: 10.9.0
- Strapi version: 5.0.6
- Database: mysql
- Operating system: macos
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Whenever I update my Strapi version to an upward patch or minor version, I get different error messages.
For example, I have a project used in production on version 5.0.6; whenever I try to update to 5.1.1 I can successfully start Strapi and access the home page, but immediatly get this error message when trying to access the content page:
```
Error: `useContentManagerInitData` must be used within `StrapiApp`
    at https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:4694:4804
    at W9e (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:2465:6075)
    at r (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:4694:4771)
    at _e (https://api.tesnim.fr/admin/layout-DX_52HSH-CGfON6Jl.js:28:1605)
    at Ge (https://api.tesnim.fr/admin/layout-DX_52HSH-CGfON6Jl.js:28:3638)
    at rC (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:204:387)
    at LHe (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:220:10189)
    at yle (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:222:12182)
    at Ez (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:239:2168)
    at nce (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:235:22589)
```

Also this error on the Media Library page:
```
Error: `useRBAC` must be used within `Auth`
    at https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:4694:4804
    at W9e (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:2465:6075)
    at r (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:4694:4771)
    at m4 (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:4709:2456)
    at qOe (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:8964:94948)
    at Xs (https://api.tesnim.fr/admin/index-KOlbnYPl-tPc-iSvq.js:19:119)
    at rC (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:204:387)
    at LHe (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:220:10189)
    at yle (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:222:12182)
    at Ez (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:239:2168)
```

And this error on the Content Type Builder page:
```
Error: `App` must be used within `GuidedTour`
    at https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:4694:4804
    at W9e (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:2465:6075)
    at r (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:4694:4771)
    at AR (https://api.tesnim.fr/admin/index-CTEMO-m9-Cf9qfa09.js:2283:42184)
    at rC (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:204:387)
    at LHe (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:220:10189)
    at yle (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:222:12182)
    at Ez (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:239:2168)
    at nce (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:235:22589)
    at oze (https://api.tesnim.fr/admin/strapi-Da_QeCHX.js:235:22185)
```

But please note this please also arises when updating from 5.0.0-rc.15 to 5.0.1.
This problem is **blocking me in production**.

### Steps to reproduce the behavior

I don't think I can provide steps at this moment.

### Expected behavior

Updating Strapi version should work.

### Screenshots

<img width="535" alt="An error message" src="https://github.com/user-attachments/assets/c2efc546-e22a-4d0c-ba1d-9077f46c3d61">

**Comment by frontBOI** [comment]
Let me add that I cannot deploy anymore in production, even when keeping the same Strapi version: the same errors pop in production. **I am completely blocked and cannot ship any new feature**.

**Comment by frontBOI** [comment]
[somebody encounters the same problem here](https://stackoverflow.com/questions/79122491/usecontentmanagerinitdata-must-be-used-within-strapiapp-error-in-strapi-proj).

**Comment by derrickmehaffy** [comment]
This will be related to an installed plugin, can you please provide your package.json

**Comment by frontBOI** [comment]
@derrickmehaffy here is my `package.json`:
```json
{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "dev:watch": "strapi develop --watch-admin",
    "tsc-compile": "npx tsc-files --noEmit",
    "strapi": "strapi",
    "deploy": "strapi deploy"
  },
  "devDependencies": {
    "@types/got": "^9.6.12",
    "@types/koa-bodyparser": "^4.3.12",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  },
  "dependencies": {
    "@frontboi/mailing": "^1.0.11",
    "@frontboi/mondial-relay": "^1.2.18",
    "@react-email/components": "0.0.22",
    "@strapi/email": "5.0.0-rc.28",
    "@strapi/plugin-cloud": "5.0.0-rc.28",
    "@strapi/plugin-users-permissions": "5.0.0-rc.28",
    "@strapi/strapi": "5.0.0-rc.28",
    "better-sqlite3": "9.4.3",
    "googleapis": "^140.0.1",
    "got": "^11.0.0",
    "libphonenumber-js": "^1.11.7",
    "mysql2": "^3.10.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "stripe": "^16.2.0",
    "styled-components": "^6.0.0",
    "zod": "^3.23.8"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "..."
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

**Comment by derrickmehaffy** [comment]
Do you have any custom plugins?

**Comment by frontBOI** [comment]
@derrickmehaffy nope, but I do extend `users-permissions` like this in `src/extensions/users-permissions/strapi-server.ts`:
```ts
import { callback, logout, refresh, update } from './controller'
import { getCookies } from './middleware'
import customRoutes from './routes'

export default plugin => {
  strapi.log.info('Included JWT token in httpOnly cookies')

  plugin.middlewares = {
    ...plugin.middlewares,
    getCookies,
  }

  plugin.controllers.auth = {
    ...plugin.controllers.auth,
    callback,
    refresh,
    logout,
    update,
  }

  plugin.routes['content-api'].routes.push(...customRoutes)

  return plugin
}
```

**Comment by derrickmehaffy** [comment]
I think in your case you have some kind of cached packages or something.

I'd try manually changing your package.json to the 5.1.1 versions, delete your node_modules and your lock files.

The only time I've seen this error was custom plugins or community plugins that haven't been migrated completely or properly. I'm guessing somewhere you have a cached version of one of the core packages that wasn't migrated yet in that RC you are on.
