### ISSUE TITLE
Error creating endpoint GET /connect/(.*): Handler not found "auth.connect"

### ISSUE THREAD

**Issue by frontBOI** [strapi/strapi#22007]
### Required System information

- Node.js version: 20.17.0
- NPM version: 10.9.0
- Strapi version: 5.1.1
- Database: sqlite
- Operating system: macos
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I cannot start my Strapi project, I immediately get the following error:
```
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                               │
│   Error: Error creating endpoint GET /connect/(.*): Handler not found "auth.connect"                                                          │
│       at getAction (/Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/compose-endpoint.js:107:11)   │
│       at /Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/compose-endpoint.js:58:22                │
│       at createRoute (/Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/routing.js:71:5)            │
│       at /Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/routing.js:80:9                          │
│       at Array.forEach (<anonymous>)                                                                                                          │
│       at Object.addRoutes (/Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/routing.js:78:21)      │
│       at Object.routes (/Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/api.js:20:20)             │
│       at Object.routes (/Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/index.js:52:27)           │
│       at /Users/methem/Desktop/strapi-error-reproduce/node_modules/@strapi/core/dist/services/server/register-routes.js:56:23                 │
│       at /Users/methem/Desktop/strapi-error-reproduce/node_modules/lodash/lodash.js:4967:15                                                   │
│                                                                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```
### Steps to reproduce the behavior

1. Clone [this repository](https://github.com/frontBOI/strapi-5-error)
2. Run the following command: `npm install && npm run dev`
3. The error is triggered

### Expected behavior

Starpi starts successfully

**Comment by frontBOI** [comment]
hello, any news on this ticket ?

**Comment by muhsin097** [comment]
Anyone got any solution for this ?

**Comment by frontBOI** [comment]
hi guys, still waiting for some feedback :-)

**Comment by sebspi** [comment]
Facing the same issue... Having an extension for `users-permissions`.

I created a `strapi-server` file. Stopped working with strapi `5.1.1`
