### ISSUE TITLE
Cannot find folder /admin to run in development mode

### ISSUE THREAD

**Issue by abdullaalsayyed** [strapi/strapi#2200]
**Informations**
- **Node.js version**: 10.2.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3 
- **Database**: mongodb
- **Operating system**: ubuntu 16.04

**What is the current behavior?**
- when running "strapi" it returns:  
`
1internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'strapi-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/abdulla/Desktop/strapi-dev/strapi/packages/strapi/bin/strapi.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
`
- I cannot find folder "/admin" as referenced on the documentation [here](https://strapi.io/documentation/3.x.x/plugin-development/quick-start.html#plugin-deven lopment-setup) to run `npm start` after I've executed `npm run setup:build`

**Steps to reproduce the problem**
- cloned official repo after forking it.
- executed "npm run setup:build"
- then i couldn't find an admin folder to go through the next steps to run the frontend and the backend after that using `strapi start`, but its also shows an erorr.

**What is the expected behavior?**
run the admin panel successfully.

**Suggested solutions**
-

**Comment by jacargentina** [comment]
I've had some problems with installing the sources; thanks to a folk on slack i've found that i've got to correctly setup by running in a root shell
