### ISSUE TITLE
Cannot run tests for the API

### ISSUE THREAD

**Issue by dhoko** [strapi/strapi#22009]
👋 Hello
### Required System information

- Node.js version: v20.16.0
- Yarn version: 4.5.0
- Strapi version: 36632203b17974c18103c138ffbef53a82e448c3
- Database: sqlite
- Operating system: MacOS

### Describe the bug

I created a MR and I see I have some issues with the tests https://github.com/strapi/strapi/actions/runs/11554462108/job/32172410865?pr=22001 but, I'm unable to run the tests on my computer :/
I tried to follow this https://github.com/strapi/strapi/blob/develop/CONTRIBUTING.md#running-the-api-integration-tests but it doesn't work cf:

```sh
strapi git:(develop) yarn run test:api --db=sqlite

 Strapi   Creating a new application at /Users/dhoko/dev/strapi/test-apps/api

 Strapi   Your application was created!
          Available commands in your project:

          Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)
          yarn run develop

          Start Strapi without watch mode.
          yarn run start

          Build Strapi admin panel.
          yarn run build

          Deploy Strapi project.
          yarn run deploy

          Display all available commands.
          yarn run strapi

          To get started run

          cd /Users/dhoko/dev/strapi/test-apps/api
          yarn install
          yarn run develop
 FAIL   API integration tests  tests/api/core/strapi/api/populate/filtering/index.test.api.js
  ● Test suite failed to run

    The name `@strapi/core` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude f
iles until there remains only one of these:

      * `/Users/dhoko/dev/strapi/packages/core/core/package.json` (package)
      * `/Users/dhoko/dev/strapi/test-apps/cli/test-app-0/.yalc/@strapi/core/package.json` (package)

      1 | "use strict";
      2 | Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    > 3 | const core = require("@strapi/core");
        |              ^
      4 | Object.keys(core).forEach((k) => {
      5 |   if (k !== "default" && !Object.prototype.hasOwnProperty.call(exports, k))
      6 |     Object.defineProperty(exports, k, {

      at ModuleMap._assertNoDuplicates (node_modules/jest-haste-map/build/ModuleMap.js:189:11)
      at Module.Object.<anonymous> (packages/core/strapi/dist/index.js:3:14)
      at Object.<anonymous> (packages/utils/api-tests/strapi.js:6:26)
      at Object.<anonymous> (packages/utils/api-tests/models.js:4:34)
      at Object.<anonymous> (packages/utils/api-tests/builder/index.js:5:21)
      at Object.<anonymous> (tests/api/core/strapi/api/populate/filtering/index.test.api.js:5:31)
```
I also tried to run the github action, it's the same.

### Steps to reproduce the behavior

1. clone `develop`
2. `yarn`
3. follow this https://github.com/strapi/strapi/blob/develop/CONTRIBUTING.md#running-the-api-integration-tests 

### Expected behavior

I can see the same errors as the CI, I can run the tests.

### Screenshots

```sh
strapi git:(develop) yarn run test:api --db=sqlite

 Strapi   Creating a new application at /Users/dhoko/dev/strapi/test-apps/api

 Strapi   Your application was created!
          Available commands in your project:

          Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)
          yarn run develop

          Start Strapi without watch mode.
          yarn run start

          Build Strapi admin panel.
          yarn run build

          Deploy Strapi project.
          yarn run deploy

          Display all available commands.
          yarn run strapi

          To get started run

          cd /Users/dhoko/dev/strapi/test-apps/api
          yarn install
          yarn run develop
 FAIL   API integration tests  tests/api/core/strapi/api/populate/filtering/index.test.api.js
  ● Test suite failed to run

    The name `@strapi/core` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude f
iles until there remains only one of these:

      * `/Users/dhoko/dev/strapi/packages/core/core/package.json` (package)
      * `/Users/dhoko/dev/strapi/test-apps/cli/test-app-0/.yalc/@strapi/core/package.json` (package)

      1 | "use strict";
      2 | Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    > 3 | const core = require("@strapi/core");
        |              ^
      4 | Object.keys(core).forEach((k) => {
      5 |   if (k !== "default" && !Object.prototype.hasOwnProperty.call(exports, k))
      6 |     Object.defineProperty(exports, k, {

      at ModuleMap._assertNoDuplicates (node_modules/jest-haste-map/build/ModuleMap.js:189:11)
      at Module.Object.<anonymous> (packages/core/strapi/dist/index.js:3:14)
      at Object.<anonymous> (packages/utils/api-tests/strapi.js:6:26)
      at Object.<anonymous> (packages/utils/api-tests/models.js:4:34)
      at Object.<anonymous> (packages/utils/api-tests/builder/index.js:5:21)
      at Object.<anonymous> (tests/api/core/strapi/api/populate/filtering/index.test.api.js:5:31)
```

Same error for all of them, nothing runs.

### Code snippets

N/A
### Additional context

N/A

**Comment by dhoko** [comment]
found the issue, it was because of the cache.
