### ISSUE TITLE
Media Library image moving error

### ISSUE THREAD

**Issue by epnomis** [strapi/strapi#22036]
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 5.1.1
- Database: postgres
- Operating system: Win11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When selecting an image in Meda Library root folder and try to move it without chaging the destination location I get error message and crash.

### Steps to reproduce the behavior

1. Upload an image to Media Library (root folder)
2. Select it with ticking the checkmark
3. Select "move" btn
4. Leave the location as "Media Library" in the dialog
5. Click "move"
6. Error: 
7. d:\develop\DucatiWeb-strapi\ducati\node_modules\pg-protocol\src\parser.ts:368
      name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
                                                                    
error: select count("t0"."id") as "count" from "public"."upload_folders" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: ""
    at Parser.parseErrorMessage (d:\develop\strapi\test\node_modules\pg-protocol\src\parser.ts:368:69)
...

### Expected behavior

It should do nothing, shouldn't throw an error and strapi crashes.

### Additional context

The error msg I got:

d:\develop\strapi\test\node_modules\pg-protocol\src\parser.ts:368
      name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
                                                                    ^
																	
error: select count("t0"."id") as "count" from "public"."upload_folders" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: ""
    at Parser.parseErrorMessage (d:\develop\strapi\test\node_modules\pg-protocol\src\parser.ts:368:69)
    at Parser.handlePacket (d:\develop\strapi\test\node_modules\pg-protocol\src\parser.ts:187:21)
    at Parser.parse (d:\develop\strapi\test\node_modules\pg-protocol\src\parser.ts:102:30)
    at Socket.<anonymous> (d:\develop\strapi\test\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 209,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'D:\\a\\postgresql-packaging-foundation\\postgresql-packaging-foundation\\postgresql-13.16\\src\\backend\\utils\\adt\\numutils.c',
  line: '323',
  routine: 'pg_strtoint32'
}

Node.js v18.17.1

d:\develop\strapi\test>

**Comment by markkaylor** [comment]
I just tested this in strapi latest and I am unable to reproduce an error. I get a success message when trying to move the file to the folder where it already lives. Closing.
