### ISSUE TITLE
Project upgraded from strapi 5.0.5 to 5.2.0 and getting errors when running

### ISSUE THREAD

**Issue by Yobikap** [strapi/strapi#22045]
### Required System information

- Node.js version: 20.18.0
- NPM version:
- Strapi version:
- Database: sqlite
- Operating system: macOS Sonoma 14.6
- Is your project Javascript or Typescript: Type script

### Describe the bug

I have upgraded strapi 5.0.5 to 5.2.0, after the upgrade I have cleared my node_modules folder and ran "npm install". After running npm run develop I get the following error:

` Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Fri Nov 01 2024 11:43:27 GMT+0100 (Central Euro… │
│ Launched in        │ 7905 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 51902                                            │
│ Version            │ 5.2.0 (node v20.18.0)                            │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available                                                            

One more thing...
Create your first administrator 💻 by going to the administration panel at:

┌─────────────────────────────┐
│ http://localhost:1337/admin │
└─────────────────────────────┘

[2024-11-01 11:43:27.344] info: Strapi started successfully
[2024-11-01 11:43:27.847] http: GET /admin (148 ms) 200
✘ [ERROR] No matching export in "node_modules/@strapi/admin/dist/admin/index.mjs" for import "useClipboard"

    node_modules/@strapi/content-manager/dist/_chunks/Preview-DRJhcaIO.mjs:3:26:
      3 │ import { useNotification, useClipboard, useQueryParams, useHistory, createContext, useRBAC, Page } from "@strapi/admin/strapi-admin";
        ╵                           ~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@strapi/admin/dist/admin/index.mjs" for import "useHistory"

    node_modules/@strapi/content-manager/dist/_chunks/Preview-DRJhcaIO.mjs:3:56:
      3 │ import { useNotification, useClipboard, useQueryParams, useHistory, createContext, useRBAC, Page } from "@strapi/admin/strapi-admin";
        ╵                                                         ~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@strapi/admin/dist/admin/index.mjs" for import "useClipboard"

    node_modules/@strapi/upload/dist/_chunks/index-BjvAmZvH.mjs:6:82:
      6 │ ...nslatedErrors, useNotification, useFetchClient, useRBAC, useTracking, useClipboard, ConfirmDialog, useQueryParams, Layouts, Page, useField } from "@str...
        ╵                                                                          ~~~~~~~~~~~~

11:43:29 AM [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/@strapi/content-manager/dist/_chunks/Preview-DRJhcaIO.mjs:3:26: ERROR: No matching export in "node_modules/@strapi/admin/dist/admin/index.mjs" for import "useClipboard"
node_modules/@strapi/content-manager/dist/_chunks/Preview-DRJhcaIO.mjs:3:56: ERROR: No matching export in "node_modules/@strapi/admin/dist/admin/index.mjs" for import "useHistory"
node_modules/@strapi/upload/dist/_chunks/index-BjvAmZvH.mjs:6:82: ERROR: No matching export in "node_modules/@strapi/admin/dist/admin/index.mjs" for import "useClipboard"
    at failureErrorWithLog (/Users/x/IdeaProjects/x-api/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/x/IdeaProjects/x-api/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
    at /Users/x/IdeaProjects/x-api/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
^C[2024-11-01 11:47:01.932] info: Shutting down Strapi
[2024-11-01 11:47:01.953] info: Strapi has been shut down

### Steps to reproduce the behavior

1. Once the project has started go to the admin panel
2. It crashes
3. See error in terminal

### Expected behavior

The admin panel should run

**Comment by haswalt** [comment]
Can confirm same issue when upgrading.  Starting a fresh project with 5.2.0 works as expected.

After upgrading got my project to work:

1. Ensure all plugins are up to date, especially Strapi own plugins (most are at 5.2.0 also)
2. Clean up generated files: `dist` and `.strapi`
3. Delete `node_modules`
4. Re-install node modules (tested with npm install myself, assume yarn will behave the same)
5. Run `develop`, everything should work now.

**Comment by adrienbrault** [comment]
Just ran into the same issue. Turns out I had to update my plugins, ran `npm update @strapi/plugin-documentation` and the error went away
