### ISSUE TITLE
[BUG][Strapi 5] Content Manager - Something went wrong - SEO Plugin

### ISSUE THREAD

**Issue by dimitrisganotis** [strapi/strapi#22134]
### Required System information

- Node.js version: v20.15.1
- NPM version: v10.9.0
- Strapi version: v5.3.0
- Database: MySQL 8
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I try to fill in from another locale (EN -> DE) I get an error. The collection contains a dynamic zone, the SEO component and some standard fields.

TypeError: Cannot read properties of undefined (reading 'forEach')
    at jq (https://example.com/admin/strapi-1w9Q-PAL.js:3043:4793)
    at Ws (https://example.com/admin/strapi-1w9Q-PAL.js:3044:325)
    at https://example.com/admin/strapi-1w9Q-PAL.js:3046:1784
    at Array.forEach (<anonymous>)
    at https://example.com/admin/strapi-1w9Q-PAL.js:3046:1736
    at Array.forEach (<anonymous>)
    at https://example.com/admin/strapi-1w9Q-PAL.js:3046:1688
    at Array.forEach (<anonymous>)
    at Lfe (https://example.com/admin/strapi-1w9Q-PAL.js:3046:1484)
    at U$t (https://example.com/admin/strapi-1w9Q-PAL.js:3046:2450)

### Steps to reproduce the behavior

1. Enable multiple locales.
2. Create a collection that has a dynamic zone.
3. Create a record in the main locale.
4. Create a translation in another locale.
5. While every field is empty, try to fill in content from the main locale using the build in button.
6. See error.

### Expected behavior

The build in button should copy the content of the selected locale to the current locale.

### Screenshots

<img width="1540" alt="image" src="https://github.com/user-attachments/assets/96fbef47-d6dd-477c-86a8-fac687194d2e">

<img width="558" alt="image" src="https://github.com/user-attachments/assets/b91475ad-c16d-4b0d-9134-c089cd965969">

**Comment by dimitrisganotis** [comment]
After some research this is probably also related to SEO Plugin v2.0.2 (https://github.com/strapi/strapi-plugin-seo).

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/4de17a30-0b51-42e6-8b70-72510e2112eb">

When there are components in the dynamic zone and I try to add the SEO, I'm getting the same error.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/8dd1553b-0b51-4d8d-b4ff-d0d2d2fc3dfb">

Without any components in the dynamic zone I am able to add the SEO.

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/c757f0ec-4fd4-43d3-b9fc-ac747f0f550b">

On the other hand if I try to reset the SEO entry by pressing the delete icon, I get another error.

<img width="586" alt="image" src="https://github.com/user-attachments/assets/b4d30640-6a28-45f6-8cc7-025da3783a39">

I'm not sure if this is 100% an issue of the plugin or if something is broken on the latest version of Strapi. Seems more like a bug within the content manager module of strapi.

**Comment by dimitrisganotis** [comment]
The conflicting components in the dynamic zone are the ones that include a subcomponent like the following:

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/dea3a465-78b3-4be1-ada3-5c8acebf64d5">
