### ISSUE TITLE
core::5.0.0-discard-drafts (Cannot destructure property 'state') on strapi cloud

### ISSUE THREAD

**Issue by sorryForThatFR** [strapi/strapi#22152]
### Required System information
- Environment: Strapi Cloud
- Strapi version: 5.3.0
- Is your project Javascript or Typescript: js

### Describe the bug

Migrating from v4 to v5 on strapi cloud crashes core::5.0.0-discard-drafts. I've migrated locally (all was good), and then we pushed it to strapi cloud.

`[2024-11-14 02:39:00] MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: Cannot destructure property 'state' of '(intermediate value)' as it is null.
[2024-11-14 02:39:00]     at /home/app/node_modules/umzug/lib/umzug.js:169:27
[2024-11-14 02:39:00]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-11-14 02:39:00]     at async Umzug.runCommand (/home/app/node_modules/umzug/lib/umzug.js:125:20)
[2024-11-14 02:39:00]     at async Object.up (/home/app/node_modules/@strapi/database/dist/index.js:6533:7)
[2024-11-14 02:39:00]     at async Object.up (/home/app/node_modules/@strapi/database/dist/index.js:6557:11)
[2024-11-14 02:39:00]     at async Object.sync (/home/app/node_modules/@strapi/database/dist/index.js:2247:9)
[2024-11-14 02:39:00]     at async Strapi.bootstrap (/home/app/node_modules/@strapi/core/dist/Strapi.js:351:5)
[2024-11-14 02:39:00]     at async Strapi.load (/home/app/node_modules/@strapi/core/dist/Strapi.js:315:5)
[2024-11-14 02:39:00]     at async Strapi.start (/home/app/node_modules/@strapi/core/dist/Strapi.js:207:9)
[2024-11-14 02:39:00] [2024-11-14 02:39:00.364] info: Shutting down Strapi`

**Comment by sorryForThatFR** [comment]
Seems that happens because of some records in draft state
