### ISSUE TITLE
Replace graphql-depth-limit with eg @graphile/depth-limit

### ISSUE THREAD

**Issue by jorrit** [strapi/strapi#22247]
### Required System information

- Node.js version: v22.12.0
- NPM version: 10.9.0
- Strapi version: 5.2.0
- Database: postgresql
- Operating system: Windows 11
- Is your project Javascript or Typescript: TS

### Describe the bug

I accidently referenced an unexisting Fragment in a call to the Strapi GraphQL API, which caused a hard to debug error in `graphql-depth-limit`.

### Steps to reproduce the behavior

1. Install & enable the Strapi GraphQL plugin.
2. Make a call to the Strapi GraphQL API with a query with a reference to a non existing fragment.
```graphql
query {
    ...Nope
}
```
4. Internal error occurs.

This is returned to the GraphQL client:
```
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Internal server error",
        ]
      }
    }
  ]
}
```

This is logged in the console:

```
TypeError: Cannot read properties of undefined (reading 'kind')
    at determineDepth (....\node_modules\graphql-depth-limit\index.js:63:16)
    at determineDepth (....\node_modules\graphql-depth-limit\index.js:78:14)
    at ....\node_modules\graphql-depth-limit\index.js:72:9
    at Array.map (<anonymous>)
    at determineDepth (....\node_modules\graphql-depth-limit\index.js:71:59)
    at ....\node_modules\graphql-depth-limit\index.js:72:9
    at Array.map (<anonymous>)
    at determineDepth (....\node_modules\graphql-depth-limit\index.js:71:59)
    at ....\node_modules\graphql-depth-limit\index.js:72:9
    at Array.map (<anonymous>)
```

### Expected behavior

A proper error message should be returned.
If I hotpatch `graphql-depth-limit`, this error is returned instead.

```json
{
  "errors": [
    {
      "message": "Unknown fragment \"Nope\".",
      "locations": [
        {
          "line": 2,
          "column": 8
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED",
        "stacktrace": [
         ]
      }
    }
  ]
}
```

### Additional context

`graphql-depth-limit` does not check if a fragment exists when it tries to access it by name. I tried reporting this to `graphql-depth-limit`, but this project is unmaintained. The GitHub link on NPM refers to an nonexisting repository.
My suggestion is that Strapi moves away from this unmaintained project and implements the depth limit functionality with a package such as `@graphile/depth-limit`.

**Comment by jorrit** [comment]
I've updated the issue.

**Comment by markkaylor** [comment]
> [@markkaylor](https://github.com/markkaylor) Could this issue be reopened and addressed?

I've re-opened the issue. It will be reviewed by support before it is assigned to someone.
