### ISSUE TITLE
Strapi 5 upgrade error from v4 to v5.4+

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#22379]
### Required System information

- Strapi version: 4.25.x to 5.4+, 
- Database: Postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When upgrading Strapi from v4 to Strapi 5, users encountered issues with part of the process, presumably when database tables were being modified from v4 schema to Strapi 5 schema and the error below was thrown:

```bash
[2024-12-09 12:55:48] [2024-12-09 12:55:48.957] debug: ⛔️ Server wasn't able to start properly.
[2024-12-09 12:55:48] [2024-12-09 12:55:48.968] error: create index "admin_permissions_role_links_fk" on "public"."admin_permissions_role_links" ("permission_id") - relation "admin_permissions_role_links_fk" already exists
[2024-12-09 12:55:48] error: create index "admin_permissions_role_links_fk" on "public"."admin_permissions_role_links" ("permission_id") - relation "admin_permissions_role_links_fk" already exists
[2024-12-09 12:55:48]     at Parser.parseErrorMessage (/home/app/docroot/node_modules/pg-protocol/dist/parser.js:283:98)
[2024-12-09 12:55:48]     at Parser.handlePacket (/home/app/docroot/node_modules/pg-protocol/dist/parser.js:122:29)
[2024-12-09 12:55:48]     at Parser.parse (/home/app/docroot/node_modules/pg-protocol/dist/parser.js:35:38)
[2024-12-09 12:55:48]     at TLSSocket.<anonymous> (/home/app/docroot/node_modules/pg-protocol/dist/index.js:11:42)
[2024-12-09 12:55:48]     at TLSSocket.emit (node:events:517:28)
[2024-12-09 12:55:48]     at TLSSocket.emit (node:domain:489:12)
[2024-12-09 12:55:48]     at addChunk (node:internal/streams/readable:368:12)
[2024-12-09 12:55:48]     at readableAddChunk (node:internal/streams/readable:341:9)
[2024-12-09 12:55:48]     at Readable.push (node:internal/streams/readable:278:10)
[2024-12-09 12:55:48]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Steps to reproduce the behavior (according to what we know currently)

1. Upgrade code base to Strapi 5
2. Connect to a v4 database (with existing data)
3. Attempt to start your app

### Expected behavior

Ideally, a successful upgrade

### Additional context

So far, this seems to be happening to users who have existing data in their apps, from what I read: blank applications seem to go through the upgrade process just fine.

**Comment by kasonde** [comment]
Internal TID Ref: 
- 9264
- 9189

**Comment by derrickmehaffy** [comment]
Not possible to reproduce in a clean environment, we are asking customers from impacted tickets for their code and database dumps that we can provide to engineering

**Comment by derrickmehaffy** [comment]
Confirmed reports of the issue in both Cloud and Self-hosted

**Comment by CQuarterz** [comment]
I have had this issue as well, I had to restore everything in my database because I tried deleting those keys and usage in the database and it still wouldn't run. I hope this can get resolved soon so I can properly upgrade to Strapi v5!

**Comment by CQuarterz** [comment]
Not sure if this helps, but I upgrade from v4.25.0 then had to upgrade to 4.25.17 first so I did that, then I upgraded to major and I had this issue. So I reverted back to my original build, this time (today) upgraded to 4.25.18 (they released 17 hours ago), then I deleted my node_modules and package-lock.json files and all related strapi build files, and tried to upgrade to v5 major using their CLI tool and it ran but one of my custom plugins didn't build right so I just removed it for now and it built fine! Hope this helps!

**Comment by innerdvations** [comment]
We're working on this now, and trying to find the reproduction steps.

- Most importantly: can you tell me if you have set the `forceMigration` or `runMigrations` settings in your database config and if so what their values are?
- Is the error posted in the original issue encountered when running v4 again after a failed attempt to upgrade to v5?
- Or does that error somehow happen on v5? Do the internal migrations run or is that error thrown first?

**Comment by innerdvations** [comment]
If someone is facing this problem, could you please test (NOT on production data) this experimental: 0.0.0-experimental.cfda358b7f27015e34e739b8742a2962ae2e7aee

I can't recreate the original issue but if the issue is with creating indexes that already exist, this should fix it.

Although I'm confused by the error message in the original issue, because Strapi 5 should never be attempting to create an index with `_links` in it, so I'm wondering if that error message is what is shown by Strapi 4 after attempting to revert

**Comment by gorgsenegger** [comment]
> Not sure if this helps, but I upgrade from v4.25.0 then had to upgrade to 4.25.17 first so I did that, then I upgraded to major and I had this issue. So I reverted back to my original build, this time (today) upgraded to 4.25.18 (they released 17 hours ago), then I deleted my node_modules and package-lock.json files and all related strapi build files, and tried to upgrade to v5 major using their CLI tool and it ran but one of my custom plugins didn't build right so I just removed it for now and it built fine! Hope this helps!

This kind of worked for me as well. I upgraded from 4.25.12 to 4.25.18, ran `npx @strapi/upgrade major` and removed (I think) all plugins from my `package.json` so I could build and run the updated version. Now I'll have to fix my backend that I use to access strapi as there are breaking changes in how the data returned is structured (e.g. instead of `response.data[i].attributes.myField` it is now `response.data[i].myField`).

**Comment by gorgsenegger** [comment]
> If someone is facing this problem, could you please test this experimental (NOT on production data):0.0.0-experimental.ee7402bacc4656d268ab76aa9c334a7b7a951201 (updated: dec 17 15:11 CET)
> 
> I can't recreate the original issue but if the issue is with creating indexes that already exist, this should fix it.
> 
> Although I'm confused by the error message in the original issue, because Strapi 5 should never be attempting to create an index with `_links` in it since it is now `_lnk`, so I'm wondering if that error message is what is shown by Strapi 4 after attempting to revert

In my database the table name is still with `lnk`, some constraints and indexes are with `links`, one of many examples looks like this:

![image](https://github.com/user-attachments/assets/2bb2bcee-99fb-472b-af36-6ec84f2956b0)

Hope this helps.

**Comment by gorgsenegger** [comment]
Another question regarding this issue: Would this be fixed for version 4 as well? With version 5 the import/export functionality isn't working properly yet, but my version 4.25.18 does not work anymore due to the errors with the existing constraints and indexes.
