### ISSUE TITLE
No way to configure proxy for sendgrid requests

### ISSUE THREAD

**Issue by emaddoma** [strapi/strapi#22383]
### Required System information

- Node.js version: 18.19.1
- NPM version: 10.2.4
- Strapi version: 4.25.7
- Database: Postgres
- Operating system: darwin arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I need to use my Sendgrid account for email delivery and Sendgrid requires me to restrict requests by IP, so all of my uses have to be made through a proxy with a static IP. I also deploy to Heroku, which changes my application IP often.  The Sendgrid provider plugin does not provide a way to specify a proxy URL for me to use.

### Steps to reproduce the behavior

Send a test email via Sendgrid email provider with Sendgrid account that is IP restricted

### Expected behavior

Strapi's Sendgrid provider plugin should provide a way to specify a proxy URL or supply a custom agent

### Screenshots

NA

### Code snippets

`
2024-12-10T15:38:29.445906+00:00 app[web.1]: [2024-12-10 15:38:29.445] [31merror[39m: Couldn't send test email: Unauthorized.
2024-12-10T15:38:29.445922+00:00 app[web.1]: Error: Couldn't send test email: Unauthorized.
2024-12-10T15:38:29.445922+00:00 app[web.1]:     at Object.test (/app/node_modules/@strapi/plugin-email/dist/server/index.js:173:17)
2024-12-10T15:38:29.445923+00:00 app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-10T15:38:29.445923+00:00 app[web.1]:     at async returnBodyMiddleware (/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
2024-12-10T15:38:29.445934+00:00 app[web.1]:     at async policiesMiddleware (/app/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
2024-12-10T15:38:29.445934+00:00 app[web.1]:     at async /app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
2024-12-10T15:38:29.445935+00:00 app[web.1]:     at async /app/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
2024-12-10T15:38:29.445936+00:00 app[web.1]:     at async /app/node_modules/@strapi/strapi/dist/middlewares/powered-by.js:9:5
2024-12-10T15:38:29.445936+00:00 app[web.1]:     at async cors (/app/node_modules/@koa/cors/index.js:106:16)
2024-12-10T15:38:29.445937+00:00 app[web.1]:     at async /app/node_modules/@strapi/strapi/dist/middlewares/errors.js:8:7
2024-12-10T15:38:29.445937+00:00 app[web.1]:     at async /app/node_modules/@strapi/strapi/dist/middlewares/logger.js:6:5
2024-12-10T15:38:29.446543+00:00 app[web.1]: [2024-12-10 15:38:29.446] [32mhttp[39m: POST /email/test (151 ms) 500
`

### Additional context

NA

**Comment by derrickmehaffy** [comment]
Strapi itself has a global proxy for these types of needs (see the server config documentation).

As for adding a proxy only for sendgrid, that's more of an enhancement rather than a bug as it depends on the hosting environment.

You could consider forking that provider or contributing the enhancement to it.

**Comment by emaddoma** [comment]
@derrickmehaffy Are you saying that if I configure a global proxy the sendgrid email provider will use it?

**Comment by derrickmehaffy** [comment]
I believe so yes, so long as it's using the fetch client I believe it should
