### ISSUE TITLE
Uploading logos in project settings fails when provider doesn't implement uploadStream

### ISSUE THREAD

**Issue by jorrit** [strapi/strapi#22387]
### Required System information

Launched In: 3854 ms
Environment: production
OS: linux-x64
Strapi Version: 5.2.0
Node/Yarn Version: npm/10.8.2 node/v20.18.1 linux x64 workspaces/false
Edition: Community
Database: postgres
- Is your project Javascript or Typescript: TS

### Describe the bug

My upload provider only implements the `upload` method, not the `uploadStream` method. There is a warning about this on startup, but uploading regular files works fine.
However, uploading files in the two logo fields on the project settings form does not work. The server log shows:

```
[2024-12-11 08:04:41.691] error: strapi.plugin(...).provider.uploadStream is not a function
TypeError: strapi.plugin(...).provider.uploadStream is not a function
    at /src/node_modules/@strapi/admin/dist/server/index.js:4069:146
    at Array.map (<anonymous>)
    at uploadFiles (/src/node_modules/@strapi/admin/dist/server/index.js:4069:99)
    at Module.updateProjectSettings$1 [as updateProjectSettings] (/src/node_modules/@strapi/admin/dist/server/index.js:4095:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async returnBodyMiddleware (/src/node_modules/@strapi/core/dist/services/server/compose-endpoint.js:45:18)
    at async policiesMiddleware (/src/node_modules/@strapi/core/dist/services/server/policy.js:15:5)
    at async /src/node_modules/@strapi/core/dist/services/server/compose-endpoint.js:27:12
    at async /src/node_modules/@strapi/core/dist/middlewares/body.js:45:9
    at async /src/node_modules/@strapi/core/dist/middlewares/powered-by.js:9:5
```

### Steps to reproduce the behavior

1. Setup an upload provider that does not implement the uploadStream function.
2. Go to the project settings screen.
3. Select a new file for the Menu logo or Auth logo.
4. Submit the form.

### Expected behavior

The new files are uploaded through the upload provider.

### Code snippets

The related code in project-settings.ts is:

```ts
const uploadFiles = async (files: LogoFiles = {}) => {
  // Call the provider upload function for each file
  return Promise.all(
    Object.values(files)
      .filter((file) => file?.stream instanceof fs.ReadStream)
      .map((file) => strapi.plugin('upload').provider.uploadStream(file))
  );
};
```

Perhaps it works when the code reuses the code in the provider service of the upload plugin. I haven't tested this.

```ts
const uploadFiles = async (files: LogoFiles = {}) => {
  // Call the provider upload function for each file
  return Promise.all(
    Object.values(files)
      .filter((file) => file?.stream instanceof fs.ReadStream)
      .map((file) => strapi.plugin('upload').service('provider').upload(file))
  );
};
```

**Comment by Boegie19** [comment]
@jorrit Can I ask what upload provider you are using?

**Comment by jorrit** [comment]
I am using a provider that I've developed to pass uploaded images through the Tinify API before uploading to another provider. The tinify NPM module doesn't offer a stream based method, so I can't expose one either.
