### ISSUE TITLE
Update components programmatically 

### ISSUE THREAD

**Issue by samturrell** [strapi/strapi#22396]
### Required System information

- Node.js version: v20.18.1
- NPM version: 10.8.2
- Strapi version: 5.5.0
- Database: mysql
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

In v4 i could use the entity service to update components data, much like updating content types. In v5 this doesn't seem to be possible with either the document service or the deprecated entity service.

I'm currently migrating a v4 strapi project and its plugins to v5. The current plugin i'm working on listens on lifecycle events for when map marker components are created, and runs a geocode on provided postcodes and populates the lat/lng on the server on save so that the users don't have to input coordinates manually.

#### Using document service with id passed

 ```ts
strapi.documents('api::maps.marker').findOne(32356)
```

##### Error

```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at Module.getDeepPopulate (/***/node_modules/@strapi/core/dist/services/document-service/utils/populate.js:7:43)
    at Module.createEventManager (/***/node_modules/@strapi/core/dist/services/document-service/events.js:14:31)
    at Module.createContentTypeRepository (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:41:31)
    at Strapi.factory2 (/***/node_modules/@strapi/core/dist/services/document-service/index.js:17:37)
    at Object.updateLatLng (/***/src/plugins/map-markers-latlng/dist/server/index.js:2557:21)
    at Object.beforeUpdate (/***/src/plugins/map-markers-latlng/dist/server/index.js:2451:16)
    at Object.handleLifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:2427:20)
    at lifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:33:69)
    at Object.run (/***/node_modules/@strapi/database/dist/index.js:6827:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.update (/***/node_modules/@strapi/database/dist/index.js:5431:22)
    at async /***/node_modules/p-map/index.js:57:22
```

#### Using document service with id passed and no prefix

 ```ts
strapi.documents('maps.marker').findOne(32356)
```

##### Error

```
Error: Missing schema in defaultValidateFilters
    at /***/node_modules/@strapi/utils/dist/index.js:2585:13
    at Module.curried [as validateFilters] (/***/node_modules/@strapi/utils/dist/index.js:2377:14)
    at AsyncFunction.validateParams (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:34:22)
    at /***/node_modules/@strapi/utils/dist/index.js:1302:29
    at findOne (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:78:6)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:53
    at /***/node_modules/@strapi/database/dist/index.js:7036:27
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.run (/***/node_modules/@strapi/database/dist/index.js:2983:20)
    at Database.transaction (/***/node_modules/@strapi/database/dist/index.js:7027:27)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:46
    at /***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:35:45
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:16:16)
    at Array.<anonymous> (/***/node_modules/@strapi/i18n/dist/server/index.js:44:14)
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:14:38)
    at Array.databaseErrorsMiddleware (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/errors.js:13:18)
```

#### Using document service with document id

 ```ts
strapi.documents('api::maps.marker').findOne({ documentId: 32356 })
```

##### Error

```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at Module.getDeepPopulate (/***/node_modules/@strapi/core/dist/services/document-service/utils/populate.js:7:43)
    at Module.createEventManager (/***/node_modules/@strapi/core/dist/services/document-service/events.js:14:31)
    at Module.createContentTypeRepository (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:41:31)
    at Strapi.factory2 (/***/node_modules/@strapi/core/dist/services/document-service/index.js:17:37)
    at Object.updateLatLng (/***/src/plugins/map-markers-latlng/dist/server/index.js:2583:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.beforeUpdate (/***/src/plugins/map-markers-latlng/dist/server/index.js:2451:5)
    at async Object.handleLifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:2427:9)
    at async lifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:33:5)
    at async Object.run (/***/node_modules/@strapi/database/dist/index.js:6827:11)
    at async Object.update (/***/node_modules/@strapi/database/dist/index.js:5431:22)
    at async /***/node_modules/p-map/index.js:57:22
```

#### Using document service with document id and no prefix

 ```ts
strapi.documents('maps.marker').findOne({ documentId: 32356 })
```

##### Error

```
Error: Missing schema in defaultValidateFilters
    at /***/node_modules/@strapi/utils/dist/index.js:2585:13
    at Module.curried [as validateFilters] (/***/node_modules/@strapi/utils/dist/index.js:2377:14)
    at AsyncFunction.validateParams (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:34:22)
    at /***/node_modules/@strapi/utils/dist/index.js:1302:29
    at findOne (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:78:6)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:53
    at /***/node_modules/@strapi/database/dist/index.js:7036:27
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.run (/***/node_modules/@strapi/database/dist/index.js:2983:20)
    at Database.transaction (/***/node_modules/@strapi/database/dist/index.js:7027:27)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:46
    at /***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:35:45
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:16:16)
    at Array.<anonymous> (/***/node_modules/@strapi/i18n/dist/server/index.js:44:14)
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:14:38)
    at Array.databaseErrorsMiddleware (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/errors.js:13:18)
```

#### Using document service with id

 ```ts
strapi.documents('api::maps.marker').findOne({ id: 32356 })
```

##### Error

```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at Module.getDeepPopulate (/***/node_modules/@strapi/core/dist/services/document-service/utils/populate.js:7:43)
    at Module.createEventManager (/***/node_modules/@strapi/core/dist/services/document-service/events.js:14:31)
    at Module.createContentTypeRepository (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:41:31)
    at Strapi.factory2 (/***/node_modules/@strapi/core/dist/services/document-service/index.js:17:37)
    at Object.updateLatLng (/***/src/plugins/map-markers-latlng/dist/server/index.js:2609:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.beforeUpdate (/***/src/plugins/map-markers-latlng/dist/server/index.js:2451:5)
    at async Object.handleLifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:2427:9)
    at async lifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:33:5)
    at async Object.run (/***/node_modules/@strapi/database/dist/index.js:6827:11)
    at async Object.update (/***/node_modules/@strapi/database/dist/index.js:5431:22)
    at async /***/node_modules/p-map/index.js:57:22
```

#### Using document service with id and no prefix

 ```ts
strapi.documents('maps.marker').findOne({ id: 32356 })
```

##### Error

```
Error: Missing schema in defaultValidateFilters
    at /***/node_modules/@strapi/utils/dist/index.js:2585:13
    at Module.curried [as validateFilters] (/***/node_modules/@strapi/utils/dist/index.js:2377:14)
    at AsyncFunction.validateParams (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:34:22)
    at /***/node_modules/@strapi/utils/dist/index.js:1302:29
    at findOne (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:78:6)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:53
    at /***/node_modules/@strapi/database/dist/index.js:7036:27
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.run (/***/node_modules/@strapi/database/dist/index.js:2983:20)
    at Database.transaction (/***/node_modules/@strapi/database/dist/index.js:7027:27)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:46
    at /***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:35:45
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:16:16)
    at Array.<anonymous> (/***/node_modules/@strapi/i18n/dist/server/index.js:44:14)
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:14:38)
    at Array.databaseErrorsMiddleware (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/errors.js:13:18)
```

#### Using entity service

 ```ts
strapi.entityService.findOne('api::maps.marker', 32356)
```

##### Error

```
Error: Model api::maps.marker not found
    at Database.query (/***/node_modules/@strapi/database/dist/index.js:7004:13)
    at Object.findOne (/***/node_modules/@strapi/core/dist/services/entity-service/index.js:51:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.findOne (/***/node_modules/@strapi/core/dist/services/entity-service/index.js:150:18)
    at async Object.updateLatLng (/***/src/plugins/map-markers-latlng/dist/server/index.js:2635:7)
    at async Object.beforeUpdate (/***/src/plugins/map-markers-latlng/dist/server/index.js:2451:5)
    at async Object.handleLifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:2427:9)
    at async lifecycle (/***/src/plugins/map-markers-latlng/dist/server/index.js:33:5)
    at async Object.run (/***/node_modules/@strapi/database/dist/index.js:6827:11)
    at async Object.update (/***/node_modules/@strapi/database/dist/index.js:5431:22)
    at async /***/node_modules/p-map/index.js:57:22
```

#### Using entity service with no prefix

 ```ts
strapi.entityService.findOne('maps.marker', 32356)
```

##### Error

```
Error: Missing schema in defaultValidateFilters
    at /***/node_modules/@strapi/utils/dist/index.js:2585:13
    at Module.curried [as validateFilters] (/***/node_modules/@strapi/utils/dist/index.js:2377:14)
    at AsyncFunction.validateParams (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:34:22)
    at /***/node_modules/@strapi/utils/dist/index.js:1302:29
    at findOne (/***/node_modules/@strapi/core/dist/services/document-service/repository.js:78:6)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:53
    at /***/node_modules/@strapi/database/dist/index.js:7036:27
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.run (/***/node_modules/@strapi/database/dist/index.js:2983:20)
    at Database.transaction (/***/node_modules/@strapi/database/dist/index.js:7027:27)
    at /***/node_modules/@strapi/core/dist/services/document-service/common.js:4:46
    at /***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:35:45
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:16:16)
    at Array.<anonymous> (/***/node_modules/@strapi/i18n/dist/server/index.js:44:14)
    at next (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/middleware-manager.js:14:38)
    at Array.databaseErrorsMiddleware (/***/node_modules/@strapi/core/dist/services/document-service/middlewares/errors.js:13:18)
```

With the `api::` prefix omitted it seems to accept the provided model, so maybe this error is the culprit? `TypeError: Cannot read properties of undefined (reading 'attributes')`

### Expected behavior

I should be able to perform CRUD operations on components like in v4

**Comment by samturrell** [comment]
Also posted on discord https://discord.com/channels/811989166782021633/1316088688429629460/1316088688429629460

**Comment by raphaelMrci** [comment]
+1
