### ISSUE TITLE
strapi/plugin-documentation doesn't work with dynamic zones and components 

### ISSUE THREAD

**Issue by robozb** [strapi/strapi#22439]
Dear All,

Could you be so kind to help me with any advice?

Thanks: Bela

```
  "dependencies": {
    "@strapi/strapi": "4.15.5",
    "@strapi/plugin-users-permissions": "4.15.5",
    "@strapi/plugin-i18n": "4.15.5",
    "@strapi/plugin-cloud": "4.15.5",
    "better-sqlite3": "8.6.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3",
    "@retikolo/drag-drop-content-types": "^1.3.10",
    "@strapi/plugin-documentation": "^4.15.2",
    "mysql": "^2.18.1"
  },
```

```
strapi_it_app  | ┌──────────────────────────────────────────────────────────────────────────────┐│                                                                              ││  
 TypeError: Cannot read properties of undefined (reading 'attributes')      ││   
at /app/node_modules/@strapi/plugin-documentation/server/services/helper   ││  
s/utils/clean-schema-attributes.js:128:68                                  ││   
at Array.map (<anonymous>)                                                 ││  
 at cleanSchemaAttributes (/app/node_modules/@strapi/plugin-documentation   ││  
 /server/services/helpers/utils/clean-schema-attributes.js:127:49)          ││
   at getAllSchemasForContentType (/app/node_modules/@strapi/plugin-documen   ││
   tation/server/services/helpers/build-component-schema.js:94:25)            ││ 
  at loopContentTypeNames (/app/node_modules/@strapi/plugin-documentation/   ││ 
  server/services/helpers/utils/loop-content-type-names.js:48:10)            ││
   at buildComponentSchema (/app/node_modules/@strapi/plugin-documentation/   ││   
server/services/helpers/build-component-schema.js:251:10)                  ││ 
at Object.generateFullDoc (/app/node_modules/@strapi/plugin-documentatio   ││   
n/server/services/documentation.js:175:34)                                 ││
   at async module.exports [as bootstrap] (/app/node_modules/@strapi/plugin   ││ 
  -documentation/server/bootstrap.js:53:3)                                   ││ 
  at async Object.bootstrap                                                  ││   (/app/node_modules/@strapi/strapi/dist/core/domain/module/index.js:39:7)   ││  
 at async Object.bootstrap                                                  ││   (/app/node_modules/@strapi/strapi/dist/core/registries/modules.js:23:9)    ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
strapi_it_app exited with code 0

```
Dockerfile

```
# Kép kiválasztása
FROM node:18-alpine AS build
RUN apk --no-cache add curl
# Munkakönyvtár létrehozása
WORKDIR /app
# Függőségek másolása és telepítése
COPY package*.json ./
# App forráskódjának másolása
RUN npm install
COPY . .
RUN npx strapi telemetry:disable
RUN npm run build
CMD ["npm", "run","develop-contabo"]
# Production stage
#FROM node:18-slim
#
#WORKDIR /app
#COPY --from=build /app/build ./build
#COPY --from=build /app/node_modules ./node_modules
#COPY --from=build /app/package.json ./package.json
#
#CMD ["npm", "develop"]
```

**Comment by robozb** [comment]
Docker settings caused the problem!
The solution was to make the [/app]/src/components stateful with a volume.
