### ISSUE TITLE
Server crash on start after added Decimal/Float type in models

### ISSUE THREAD

**Issue by Leo1003** [strapi/strapi#2252]
**Informations**
- **Node.js version**: 10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0 (dev mode)
- **Database**: mongodb 4.0.3
- **Operating system**: Archlinux
- **mongoose version**: 5.3.8
- **mongoose-float**: 1.0.2

**What is the current behavior?**
When restarting the server, it crashed.
```text
(node:11556) UnhandledPromiseRejectionWarning: TypeError: Undefined type `Float` at `balance`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Mongoose.Schema.Schema.interpretAsType (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/mongoose/lib/schema.js:712:11)
    at Mongoose.Schema.Schema.path (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/mongoose/lib/schema.js:552:27)
    at Mongoose.Schema.add (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/mongoose/lib/schema.js:413:12)
    at Mongoose.Schema.Schema [as constructor] (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/mongoose/lib/schema.js:110:10)
    at new Mongoose.Schema (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/mongoose/lib/index.js:64:21)
    at _.after (/home/leo/strapi/packages/strapi-hook-mongoose/lib/index.js:293:30)
    at /home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:9999:23
    at _.forEach (/home/leo/strapi/packages/strapi-hook-mongoose/lib/index.js:446:15)
    at /home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:2996:24)
    at /home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/home/leo/strapi/packages/strapi-hook-mongoose/lib/index.js:304:15)
    at /home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:2996:24)
    at /home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/home/leo/strapi/packages/strapi-hook-mongoose/node_modules/lodash/lodash.js:9344:14)
    at mountModels (/home/leo/strapi/packages/strapi-hook-mongoose/lib/index.js:253:13)
    at _.forEach (/home/leo/strapi/packages/strapi-hook-mongoose/lib/index.js:452:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-11-02T16:02:30.881Z] debug ⛔️ Server wasn't able to start properly.
[2018-11-02T16:02:30.882Z] error (hook:mongoose) takes too long to load
(hook:mongoose) takes too long to load
```

**Steps to reproduce the problem**
Add a Float or Decimal field in Content Type Builder, then restart Strapi.
Then the server crash :(

**What is the expected behavior?**
Successfully restart.

**Suggested solutions**
There might have some problems between mongoose and mongoose-float

**Comment by skdigital** [comment]
I have exactly the same issue, I cant add decimal or float numbers in content type generator, server crashes with exactly the same message as above. I tried development on both linux and windows env but no luck crashes on both. I have also tried using different versions of node from 8xx to 10xx. I have have reinstalled node, rebooted servers, deleted node modules and this crash continues to happen. Seriously about to give up lol.

**Comment by rzylber** [comment]
I have the same issue!
