### ISSUE TITLE
New content types can be created but does not show up in left column: MySQL 5.7.21 / Mac OSX High Sierra

### ISSUE THREAD

**Issue by benjamin21st** [strapi/strapi#2256]
**Informations**
- **Node.js version**: v10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 
- **Database**: MySQL
- **Operating system**: Mac OS X High Sierra

**What is the current behavior?**
New content type not showing up in the left column after creation, even when following the official start up guide of creating the `post` content type. But oddly, newly created content type shows up in other places like "Content Type Builder" list.

> No matter how many new content types created, I can only see the default "User" type
![screen shot 2018-11-02 at 10 59 40 pm](https://user-images.githubusercontent.com/8607086/47947454-2f7de880-def3-11e8-9898-65bf47fc83d6.jpg)

> But they show up in other places
![screen shot 2018-11-02 at 10 59 50 pm](https://user-images.githubusercontent.com/8607086/47947462-46243f80-def3-11e8-8e34-00a05c2a6b21.jpg)

> Visiting http://localhost:1337/admin/plugins/content-manager/post shows an error pop up and as you can see there is a filter "isUndefined" for some reason 
![screen shot 2018-11-02 at 11 11 50 pm](https://user-images.githubusercontent.com/8607086/47947539-c0a18f00-def4-11e8-94c1-8e2e420e6946.jpg)
> There is error log in node when this happend, see below 
```
[2018-11-03T03:04:30.219Z] debug GET /content-manager/explorer/post/count?=undefined&_limit=10&_start=0&_sort=id%3AASC&source=null (41 ms)
{ Error: ER_BAD_FIELD_ERROR: Unknown column '' in 'where clause'
    at Query.Sequence._packetToError (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/mysql/lib/Connection.js:200:25)
    at /Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/knex/lib/dialects/mysql/index.js:154:18
From previous event:
    at Client_MySQL._query (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/knex/lib/dialects/mysql/index.js:148:12)
    at Client_MySQL.query (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/knex/lib/runner.js:48:21
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/knex/lib/runner.js:34:31)
    at Builder.Target.then (/Users/Prime/Documents/Projects/modern-u/modern-u/node_modules/knex/lib/interface.js:20:43)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'\' in \'where clause\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'select `posts`.* from `posts` where `` = \'undefined\' order by `id` ASC limit 10' }
```
> Removing that filter results in the posts being listed properly, and I can confirm that the API works correctly as well
![screen shot 2018-11-02 at 11 12 02 pm](https://user-images.githubusercontent.com/8607086/47947562-4291b800-def5-11e8-807d-b059008da971.jpg)

**Steps to reproduce the problem**
1. Make sure you have my hardware/software setup with correct/matching versions
2. Create a new content type, for example "post", with just one simple "string" field called "title"
3. Save the new content type, observe that once the page saves and reloads, no "posts" shows up in the left column

**What is the expected behavior?**
Upon creation of a new content type, and after the page refresh, the newly created content type should show up in the left column

**Suggested solutions**
The documentation does imply that the SQL support may not be as good, but I feel this might just be a small query issue in your "database adapter" code? Because as you can see from my screenshots and description above, the functionality works as expected, just not showing up in a user-accessible manner.

Thanks! Let me know if you need anything else

**Comment by benjamin21st** [comment]
> Somehow they all showed up 🤦‍♂️ , I have no idea how that happened.
![screen shot 2018-11-02 at 11 12 02 pm](https://user-images.githubusercontent.com/8607086/47947828-b4203500-defa-11e8-8197-478e9819ea07.jpg)

Anyway, I'll close this for now. If similar issues arise I'll re-open. 

Thank you all for the awesome work!

**Comment by benjamin21st** [comment]
Forget what I said earlier, after deleting a content type, the left column went back to just having the "users" item. I'll re-open this for further discussion 😂

**Comment by Globerada** [comment]
https://github.com/strapi/strapi/issues/2213
