### ISSUE TITLE
Database names cannot contain the character '.'

### ISSUE THREAD

**Issue by alexisab** [strapi/strapi#2268]
**Informations**
- **Node.js version**: v10.9.0
- **npm version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.14.4.0
- **Database**: MongoDB
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
When I create a new strapi project with a `.` in the name and if I keep the generated name for the database I get an error : 
```
MongoError: database names cannot contain the character '.'
    at Function.create (/tmp/strapifa462c8c1340/node_modules/mongodb-core/lib/error.js:43:12)
    at validateDatabaseName (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/operations/db_ops.js:704:24)
    at new Db (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/db.js:180:3)
    at MongoClient.db (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/mongo_client.js:268:14)
    at /tmp/strapifa462c8c1340/node_modules/mongoose/lib/connection.js:527:42
    at result (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/utils.js:406:9)
    at err (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/operations/mongo_client_ops.js:286:5)
    at connectCallback (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/operations/mongo_client_ops.js:241:5)
    at process.nextTick (/tmp/strapifa462c8c1340/node_modules/mongodb/lib/operations/mongo_client_ops.js:463:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Steps to reproduce the problem**
`npx strapi@3.0.0-alpha.14.4 new cms-14.4` then just accept default settings for the database connection.

**What is the expected behavior?**
The generated data base name must be a valid mongo database name.

**Suggested solutions**
[From the official MongoDB doc](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Database-Names-for-Windows) :
> For MongoDB deployments running on Windows, database names cannot contain any of the following characters:
> ```
> /\. "$*<>:|?
> ```
>
> For MongoDB deployments running on Unix and Linux systems, database names cannot contain any of the following characters:
> ```
> /\. "$
> ```

We could use these regex to check if the database name is valid or not.

**Comment by derrickmehaffy** [comment]
@lauriejim maybe a check to make sure that certain symbols aren't used when creating the project?

(honestly have no idea why someone would want a project with a period but that is a whole other issue :stuck_out_tongue_closed_eyes:  )

**Comment by alexisab** [comment]
in my case I was updating my project and I created a new project using the version number as the name (14.4)

**Comment by lauriejim** [comment]
Hello @alexisab , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by wortkotze** [comment]
I have same issues also on keys inside of an mongo db:
`Error: key navigation-system-type.mmi must not contain '.'
    at serializeInto (/Users/steve/Documents/Programming/tindermycar20/tmc_sw/node_modules/bson/lib/bson/parser/serializer.js:914:19)`

It seems to be a bug in mongodb-core? which version is used in strapi at the moment?

**Comment by MatheusRV** [comment]
Just prevent dot on web ui, this can avoid application breaks.

**Comment by CloudMaker97** [comment]
> Just prevent dot on web ui, this can avoid application breaks.

Good idea, i'll try to fix this. 😃

**Comment by bahdcoder** [comment]
@lauriejim I'll take this one ✋

**Comment by lauriejim** [comment]
Okay! See you for the review of your pull request.
