### ISSUE TITLE
Can't use number field in content

### ISSUE THREAD

**Issue by sidsaxena0** [strapi/strapi#2295]
**Informations**
- **Node.js version**: v10.13.0
- **npm version**:  6.4.1
- **Strapi version**:  3.0.0-alpha.14.4.0
- **Database**:  MongoDb
- **Operating system**:  Mac, Ubuntu 17.04 and Debian 9

**What is the current behavior?**

I can't add any number in a new content type, i am using admin ui to do that, below is my model : 

```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "address",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "default": "",
      "type": "string"
    },
    "city": {
      "default": "",
      "type": "string"
    },
    "building": {
      "default": "",
      "type": "string"
    },
    "lat": {
      "default": "",
      "type": "decimal"
    },
    "lng": {
      "default": "",
      "type": "decimal"
    },
    "country": {
      "default": "",
      "type": "string"
    }
  }
}
```

App just begin crashing immediately after saving, below is the log

```
(node:5570) UnhandledPromiseRejectionWarning: TypeError: Undefined type `Float` at `lat`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Mongoose.Schema.Schema.interpretAsType (/opt/api/table-top/node_modules/mongoose/lib/schema.js:713:11)
    at Mongoose.Schema.Schema.path (/opt/api/table-top/node_modules/mongoose/lib/schema.js:553:27)
    at Mongoose.Schema.add (/opt/api/table-top/node_modules/mongoose/lib/schema.js:414:12)
    at Mongoose.Schema.Schema [as constructor] (/opt/api/table-top/node_modules/mongoose/lib/schema.js:110:10)
    at new Mongoose.Schema (/opt/api/table-top/node_modules/mongoose/lib/index.js:64:21)
    at _.after (/opt/api/table-top/node_modules/strapi-hook-mongoose/lib/index.js:290:30)
    at /opt/api/table-top/node_modules/lodash/lodash.js:9999:23
    at _.forEach (/opt/api/table-top/node_modules/strapi-hook-mongoose/lib/index.js:443:15)
    at /opt/api/table-top/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/opt/api/table-top/node_modules/lodash/lodash.js:2996:24)
    at /opt/api/table-top/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/opt/api/table-top/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/opt/api/table-top/node_modules/strapi-hook-mongoose/lib/index.js:301:15)
    at /opt/api/table-top/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/opt/api/table-top/node_modules/lodash/lodash.js:2996:24)
    at /opt/api/table-top/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/opt/api/table-top/node_modules/lodash/lodash.js:9344:14)
    at mountModels (/opt/api/table-top/node_modules/strapi-hook-mongoose/lib/index.js:250:13)
    at _.forEach (/opt/api/table-top/node_modules/strapi-hook-mongoose/lib/index.js:449:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5570) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-11-12T08:10:16.623Z] debug ⛔️ Server wasn't able to start properly.
[2018-11-12T08:10:16.624Z] error (hook:mongoose) takes too long to load

```
**Steps to reproduce the problem**

Add any model and use float or decimal as a field type.

**What is the expected behavior?**
It should not crash

**Suggested solutions**

No idea yet.

**Comment by lauriejim** [comment]
Can you please search open / close issue. Github provide a feature to avoid duplicate issue.
https://github.com/strapi/strapi/issues/2251
