### ISSUE TITLE
GraphQL umlaut problems

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#2296]
**Informations**
- **Node.js version**:  10.8.0
- **npm version**:  6.2.0
- **Strapi version**:  alpha 14.4
- **Database**:  pg
- **Operating system**:  windows/WSL

**What is the current behavior?**

When there is an umlaut in an enum, graphql will fail to properly recognize them.

**Steps to reproduce the problem**

create an enum with characters such as umalut or dash (-).

This is the definition I have trouble with:

``` graphql
enum ENUM_LOCATION_COUNTRY {  Baden-Württemberg
 Bayern 
 Berlin 
 Brandenburg 
 Bremen 
 Hamburg 
 Hessen
 Japan 
 China }type Location {
  id: ID!
  latitude: String
  longitude: String
  country: ENUM_LOCATION_COUNTRY!
}"
```

this is the full stacktrace:

```
(node:21040) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Invalid number, expected digit but got: "W".
    at syntaxError (ssf/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at readDigits (ssf/plugins/graphql/node_modules/graphql/language/lexer.js:465:32)
    at readNumber (ssf/plugins/graphql/node_modules/graphql/language/lexer.js:418:16)
    at readToken (ssf/plugins/graphql/node_modules/graphql/language/lexer.js:303:14)
    at Object.lookahead (ssf/plugins/graphql/node_modules/graphql/language/lexer.js:60:43)
    at Object.advanceLexer [as advance] (ssf/plugins/graphql/node_modules/graphql/language/lexer.js:50:33)
    at expect (ssf/plugins/graphql/node_modules/graphql/language/parser.js:1459:11)
    at parseName (ssf/plugins/graphql/node_modules/graphql/language/parser.js:96:15)
    at parseEnumValueDefinition (ssf/plugins/graphql/node_modules/graphql/language/parser.js:1045:14)
    at many (ssf/plugins/graphql/node_modules/graphql/language/parser.js:1520:16)
    at parseEnumValuesDefinition (ssf/plugins/graphql/node_modules/graphql/language/parser.js:1033:50)
    at parseEnumTypeDefinition (ssf/plugins/graphql/node_modules/graphql/language/parser.js:1017:16)
    at parseTypeSystemDefinition (ssf/plugins/graphql/node_modules/graphql/language/parser.js:733:16)
    at parseDefinition (ssf/plugins/graphql/node_modules/graphql/language/parser.js:142:16)
    at many (ssf/plugins/graphql/node_modules/graphql/language/parser.js:1523:16)
    at parseDocument (ssf/plugins/graphql/node_modules/graphql/language/parser.js:113:18)
    at Object.parse (ssf/plugins/graphql/node_modules/graphql/language/parser.js:48:10)
    at Object.addPolymorphicUnionType (ssf/plugins/graphql/services/Types.js:152:8)
    at Object.generateSchema (ssf/plugins/graphql/services/Schema.js:179:15)
    at Function.initialize (ssf/plugins/graphql/hooks/graphql/index.js:148:50)
    at ssf/node_modules/strapi/lib/hooks/index.js:19:29
    at after (ssf/node_modules/strapi/lib/hooks/index.js:122:39)
    at ssf/node_modules/lodash/lodash.js:9997:23
    at Strapi.once (ssf/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at loadedModule.initialize.call.err (ssf/node_modules/strapi/lib/hooks/index.js:32:12)
    at Function.initialize (ssf/node_modules/strapi-hook-bookshelf/lib/index.js:999:7)
(node:21040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or
by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-11-12T23:16:04.522Z] debug ⛔️ Server wasn't able to start properly.
[2018-11-12T23:16:04.523Z] error (hook:graphql) takes too long to load
(hook:graphql) takes too long to load

```

When removing the dash, I get: 

```
Cannot parse the unexpected character "\u00FC".\n
```

**What is the expected behavior?**

it should work with special characters.

**Suggested solutions**

detect if quotes are required or always use them
escape the definition. double quotes do the trick.

**Comment by lauriejim** [comment]
Hello @MartinMuzatko I think it's the same issue as https://github.com/strapi/strapi/issues/1698

**Comment by MartinMuzatko** [comment]
correct! couldn't find it when searching :) closing this here
