### ISSUE TITLE
Crashing on Heroku

### ISSUE THREAD

**Issue by olimart** [strapi/strapi#2303]
**Informations**
- **Node.js version**: Whatever is set as part of Heroku button
- **npm version**: Whatever is set as part of Heroku button
- **Strapi version**: The latest since it clones repo upon installation
- **Database**: MongoDB
- **Operating system**: Mac/Linux

**What is the current behavior?**

App crashing on Heroku. From the logs, it seems that server cannot start.

```
Starting process with command `npm start`
 
> strapi-heroku-app@0.1.0 start /app
> node server.js

(node:22) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:22) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:22) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
error { MongoError: not authorized on strapi-production to execute command { find: "core_store", filter: { key: "plugin_content-manager_schema", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1542131332, 1), signature: { hash: BinData(0, 2E0170DCA0D75A6FA20135643493613FF3326EAC), keyId: 6580749470751784962 } }, lsid: { id: UUID("f46a1053-79ea-4871-a21e-ec2bab20c15b") }, $db: "strapi-production" }
at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:248:25)
at /app/node_modules/mongodb-core/lib/connection/pool.js:531:18
at process.internalTickCallback (internal/process/next_tick.js:70:11)
operationTime:
Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1542131332 },
ok: 0,
errmsg:
'not authorized on strapi-production to execute command { find: "core_store", filter: { key: "plugin_content-manager_schema", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1542131332, 1), signature: { hash: BinData(0, 2E0170DCA0D75A6FA20135643493613FF3326EAC), keyId: 6580749470751784962 } }, lsid: { id: UUID("f46a1053-79ea-4871-a21e-ec2bab20c15b") }, $db: "strapi-production" }',
code: 13,
codeName: 'Unauthorized',
'$clusterTime':
{ clusterTime:
Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1542131332 },
signature:
{ hash:
Binary {
_bsontype: 'Binary',
sub_type: 0,
position: 20,
buffer:
<Buffer 2e 01 70 dc a0 d7 5a 6f a2 01 35 64 34 93 61 3f f3 32 6e ac> },
keyId: Long { _bsontype: 'Long', low_: 2, high_: 1532200135 } } },
name: 'MongoError',
[Symbol(mongoErrorContextSymbol)]: {} }
(node:22) UnhandledPromiseRejectionWarning: MongoError: not authorized on strapi-production to execute command { find: "core_store", filter: { key: "core_application", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1542131332, 1), signature: { hash: BinData(0, 2E0170DCA0D75A6FA20135643493613FF3326EAC), keyId: 6580749470751784962 } }, lsid: { id: UUID("5a4bdcd9-16e4-4ee6-abb5-5270b1fd3e3b") }, $db: "strapi-production" }
at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:248:25)
at /app/node_modules/mongodb-core/lib/connection/pool.js:531:18
at process.internalTickCallback (internal/process/next_tick.js:70:11)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
at fs.readdir (/app/plugins/email/config/functions/bootstrap.js:53:40)
at _tickCallback (internal/process/next_tick.js:43:7)
at processImmediate (timers.js:605:7)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22) UnhandledPromiseRejectionWarning: MongoError: not authorized on strapi-production to execute command { find: "core_store", filter: { key: "plugin_users-permissions_grant", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1542131332, 1), signature: { hash: BinData(0, 2E0170DCA0D75A6FA20135643493613FF3326EAC), keyId: 6580749470751784962 } }, lsid: { id: UUID("91c95dd5-3d02-4e4d-b851-e8c9f6e67e5c") }, $db: "strapi-production" }
at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:248:25)
at /app/node_modules/mongodb-core/lib/connection/pool.js:531:18
at process.internalTickCallback (internal/process/next_tick.js:70:11)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:22) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
at fs.readdir (/app/plugins/upload/config/functions/bootstrap.js:55:40)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
warn Perhaps you forgot to call it?
warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
warn Perhaps you forgot to call it?
warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
warn Perhaps you forgot to call it?
Warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
warn Perhaps you forgot to call it?
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
Stopping process with SIGKILL
Process exited with status 137
State changed from starting to crashed
```

**Steps to reproduce the problem**

Deployed with Heroku button

**What is the expected behavior?**

Server starts & homepage is accessible

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Not a heroku issue, you have an issue with your database: 

```
not authorized on strapi-production to execute command { find: "core_store", filter: { key: "plugin_content-manager_schema", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1542131332, 1), signature: { hash: BinData(0, 2E0170DCA0D75A6FA20135643493613FF3326EAC), keyId: 6580749470751784962 } }, lsid: { id: UUID("f46a1053-79ea-4871-a21e-ec2bab20c15b") }, $db: "strapi-production" }',
code: 13,
codeName: 'Unauthorized',
```

**Comment by olimart** [comment]
Thanks @derrickmehaffy 
The MongoDB is provisioned and I can access it. Any suggestion?

**Comment by derrickmehaffy** [comment]
I'm guessing you either don't the correct authDB in the database.json (or you should be using env variables) that or your DB password contains an `@` symbol which has been known to cause issues.

**Comment by Froelund** [comment]
The default strapi database configuration sets the database to 'strapi-production' if the `DATABASE_NAME` is not set.
When running on heroku though your database name dictated by the database provider, e.g. Mongolab.
So what you need to do is either add the `DATABASE_NAME` environment variable in heroku. Or modify `config/environments/production/database.json` file from
```
// ...
"database": "${process.env.DATABASE_NAME || 'strapi-production'}",
// ...
```
To:
```
// ...
"database": "${process.env.DATABASE_NAME}",
// ...
```

**Comment by lauriejim** [comment]
Please check this wiki article https://github.com/strapi/strapi/wiki/Deploy-on-Heroku

**Comment by Froelund** [comment]
@lauriejim This is marked as help-wanted. Could you be specific on what to help with?

**Comment by derrickmehaffy** [comment]
@Froelund it just means the user needs help (IE us, giving help)

**Comment by lauriejim** [comment]
Some info about labels https://github.com/strapi/strapi/wiki#issues-labels

**Comment by olimart** [comment]
Setting up the environment variable `DATABASE_NAME` in Heroku resolved the "issue".
Thanks for your help.

**Comment by abegehr** [comment]
@ng-hai This should be added to the blog posts! ([https://blog.strapi.io/deploying-a-strapi-api-on-heroku/](https://blog.strapi.io/deploying-a-strapi-api-on-heroku/) and [https://blog.strapi.io/using-mlab-with-strapi/](https://blog.strapi.io/using-mlab-with-strapi/))

It worked for me after adding the DATABASE_AUTHENTICATION_DATABASE env_var., which was only mentioned here. The "Deploy on Heroku" button in the GitHub readme also only worked after applying @ng-hai's fixes.

@lauriejim, please add this info to the blog posts. It will make it easier for people to find the fix.

**Comment by VitorSavedra** [comment]
Works with solution above with 3.0.0-beta.16.8 version. :)

**Comment by lucacattide** [comment]
Followed @ng-hai instructions and still not working, throwing the usual error:
```
2019-10-10T08:38:20.119646+00:00 heroku[web.1]: Starting process with command `npm start`
2019-10-10T08:38:22.472971+00:00 app[web.1]: 
2019-10-10T08:38:22.472997+00:00 app[web.1]: > lucacattide-backend@0.1.0 start /app
2019-10-10T08:38:22.472999+00:00 app[web.1]: > NODE_ENV=production strapi start
2019-10-10T08:38:22.473000+00:00 app[web.1]: 
2019-10-10T08:38:23.925370+00:00 app[web.1]: [2019-10-10T08:38:23.924Z] warn (hook:bookshelf) wasn't loaded due to missing key `enabled` in the configuration
2019-10-10T08:38:23.926735+00:00 app[web.1]: [2019-10-10T08:38:23.926Z] warn (hook:knex) wasn't loaded due to missing key `enabled` in the configuration
2019-10-10T08:38:24.859245+00:00 app[web.1]: Make sure your MongoDB database is running...
2019-10-10T08:38:24.859549+00:00 app[web.1]: [2019-10-10T08:38:24.859Z] error Make sure your MongoDB database is running...
2019-10-10T08:38:24.870755+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-10-10T08:38:24.871026+00:00 app[web.1]: npm ERR! errno 1
2019-10-10T08:38:24.872065+00:00 app[web.1]: npm ERR! lucacattide-backend@0.1.0 start: `NODE_ENV=production strapi start`
2019-10-10T08:38:24.872232+00:00 app[web.1]: npm ERR! Exit status 1
2019-10-10T08:38:24.872397+00:00 app[web.1]: npm ERR!
2019-10-10T08:38:24.872543+00:00 app[web.1]: npm ERR! Failed at the lucacattide-backend@0.1.0 start script.
2019-10-10T08:38:24.872646+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-10T08:38:25.805477+00:00 heroku[web.1]: State changed from starting to crashed
```
Of course ```config/environments/production/database.json``` is updated with the above criteria.

Any suggestion? 

Thanks in advance
