### ISSUE TITLE
GraphQL updateUser mutations doesn't work

### ISSUE THREAD

**Issue by leafnetjake** [strapi/strapi#2327]
**Informations**
- **Node.js version**:  10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: mongodb
- **Operating system**: macos 10.14

**What is the current behavior?**
Error updating an existing User record via graphql mutation with varying results

**Steps to reproduce the problem**
```
// update field foo with value bar
   mutation updateAccount($id: ID!) {
        updateUser(input: {
            where: {
                id: $id
            },
            data: {
                foo: "bar"
            }
        }) {
            user {
                foo
            }
        }
    }
```
**Error:** Username and Email are required fields.
```
// update field foo with value bar 
// include username and email
   mutation updateAccount($id: ID!, $username: String!, $email: String!) {
        updateUser(input: {
            where: {
                id: $id
            },
            data: {
                username: $username,
                email: $email
                foo: "bar"
            }
        }) {
            user {
                username
                email
                foo
            }
        }
    }
```
**Error:** Email is already taken 
- Set username and email required to false in User.settings.json

```
Error:
{
    "errors":[{
        "message":"Bad Request",
        "locations":[{"line":3,"column":5}],
        "path":["updateUser","user"],
        "extensions":{
            "code":"INTERNAL_SERVER_ERROR",
            "exception":{
                "data":"values.hasOwnProperty is not a function",
                "isBoom":true,
                "isServer":false,
                "output":{
                    "statusCode":400,
                    "payload":{
                        "statusCode":400,
                        "error":"Bad Request",
                        "message":"Bad Request"
                    },
                    "headers":{}},
                    "message":"Bad Request",
                    "stacktrace":[
                        "Error: Bad Request",
                        "    at Object.strapi.app.response.(anonymous function) [as badRequest] (/strapi/node_modules/strapi/lib/middlewares/boom/index.js:68:34)","    at Object.proto.(anonymous function) [as badRequest] (/strapi/node_modules/delegates/index.js:40:31)","    at update (/strapi/plugins/users-permissions/controllers/User.js:153:11)","    at process._tickCallback (internal/process/next_tick.js:68:7)"
                    ]
                }
            
        }
    }],
    "data":{
        "updateUser":{
            "user":null,
            "__typename":"updateUserPayload"
        }
    }
}

```

**What is the expected behavior?**
Update the user field foo with value bar

**Comment by razza12** [comment]
Is it just the updateUser mutation that is not working? I have not been able to get the createUser mutation working either, getting a Bad Request response of  "data": "values.hasOwnProperty is not a function"
![screenshot_2018-11-26 playground - http localhost 1337 graphql](https://user-images.githubusercontent.com/8273040/48989732-acf9e900-f17f-11e8-9df6-3c04add76677.png)

**Comment by kkkkkt** [comment]
Is this feature solved？

I’m also encountered with this issue now.

Ok, I’ll upgrade Strapi version and try it.

**Comment by Aurelsicoko** [comment]
Keep me in touch when you will have upgrade to the latest version... It should be fixed 👍
