### ISSUE TITLE
[BUG] Can't get _id with GraphQL

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2352]
**Informations**
- **Node.js version**: 9.0.0
- **npm version**: 5.5.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MongoDB
- **Operating system**: Linux

**What is the current behavior?**
Can't get `_id` for user entity with GraphQL.

**Steps to reproduce the problem**
I try to get users list thought postman (REST) and it's return anything (include `_id`) well but when I run below GraphQL query it's return below error to me:
```
{
  users {
    _id,
    username
  }
}
```
```
{
  "errors": [
    {
      "message": "ID cannot represent value: { _bsontype: \"ObjectID\", id: <Buffer 5b de d1 c2 d7 5d c3 45 c0 ae 18 27> }",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "users",
        0,
        "_id"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: ID cannot represent value: { _bsontype: \"ObjectID\", id: <Buffer 5b de d1 c2 d7 5d c3 45 c0 ae 18 27> }",
            "    at GraphQLScalarType.serializeID [as serialize] (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/type/scalars.js:212:9)",
            "    at completeLeafValue (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:641:37)",
            "    at completeValue (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:587:12)",
            "    at completeValue (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:565:21)",
            "    at completeValueCatchingError (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:503:19)",
            "    at resolveField (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:447:10)",
            "    at executeFields (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:293:18)",
            "    at collectAndExecuteSubfields (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:717:10)",
            "    at completeObjectValue (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:707:10)",
            "    at completeValue (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:598:12)",
            "    at completeValueCatchingError (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:503:19)",
            "    at /home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:623:25",
            "    at Array.forEach (<anonymous>)",
            "    at forEach (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/iterall/index.js:83:25)",
            "    at completeListValue (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:619:24)",
            "    at completeValue (/home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:581:12)",
            "    at /home/username/Documents/Projects/appname/Backend/plugins/graphql/node_modules/graphql/execution/execute.js:500:16",
            "    at <anonymous>",
            "    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "users": [
      null
    ]
  }
}
```
When I remove `_id` from query it's working well:
```
{
  users {
    username
  }
}
```
```
{
  "data": {
    "users": [
      {
        "username": "admin"
      }
    ]
  }
}
```

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/2260
