### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by BroTrue** [strapi/strapi#2357]
**Informations**
- **Node.js version**:  v10.12.0
- **npm version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MongoDB
- **Operating system**: Debian

**What is the current behavior?**
When entering to create/edit User got blank page. with such error in console 
```
main.js:16 TypeError: Cannot read property 'type' of undefined
    at r.renderAttr (main.js:48)
    at Array.map (<anonymous>)
    at t.value (main.js:48)
    at Mo (main.js:16)
    at So (main.js:16)
    at Fo (main.js:16)
    at Jo (main.js:16)
    at Zo (main.js:16)
    at gn (main.js:16)
    at fn (main.js:16)
Ro @ main.js:16
main.js:72 uncaught at o TypeError: Cannot read property 'type' of undefined
    at r.renderAttr (https://mysite.com/admin/content-manager/main.js:48:311374)
    at Array.map (<anonymous>)
    at t.value (https://mysite.com/admin/content-manager/main.js:48:312290)
    at Mo (https://mysite.com/admin/main.js:16:42968)
    at So (https://mysite.com/admin/main.js:16:42763)
    at Fo (https://mysite.com/admin/main.js:16:46086)
    at Jo (https://mysite.com/admin/main.js:16:59256)
    at Zo (https://mysite.com/admin/main.js:16:59637)
    at gn (https://mysite.com/admin/main.js:16:65916)
    at fn (https://mysite.com/admin/main.js:16:65296)
```

**Steps to reproduce the problem**
I got this problem in my project when I migrate to new version. I followed all  steps in migration but doesnt help. Then I decided to install clean project with clean db, but got the same error.
![wd9qv6lat1](https://user-images.githubusercontent.com/23247940/48855275-09da5580-edb4-11e8-83bf-946e9a5cd1b2.gif)

**Comment by soupette** [comment]
@BroTrue do you have repository that I can check?

**Comment by BroTrue** [comment]
@soupette yes ofc, do you need clean one (that is on gif) or project where I made migration ?

**Comment by soupette** [comment]
You're current project

**Comment by almondevon** [comment]
I'm also running into this after creating a brand new project via the "strapi new <project>" command.

Node.js version: v11.2.0
npm version: 6.4.1
Strapi version: 3.0.0-alpha.14.5
Database: PostgreSQL
Operating system: Ubuntu 18

**Comment by lauriejim** [comment]
With a new database ?

**Comment by almondevon** [comment]
@lauriejim Yep, dropped the db and created a new blank one just to be sure.

**Comment by BroTrue** [comment]
@agni21 Yes,  I will create new issue with full info soon.

**Comment by BroTrue** [comment]
#2424

**Comment by hasanzahran** [comment]
I'm still having the same issue, any update on this?

**Comment by dobradovic** [comment]
Any update?

**Comment by derrickmehaffy** [comment]
@dobradovic this specific issue was fixed quite some time ago. Your issue is most likely different. Can you please open a new issue so we can try to reproduce. Include as much reproduction steps as you can.
