### ISSUE TITLE
Internal server error if missing required fields in request MongoDB

### ISSUE THREAD

**Issue by stockmind** [strapi/strapi#2363]
**Informations**
- **Node.js version**: 10.13.0
- **npm version**: 6.4.1
- **Strapi version**:  v3.0.0-alpha.14.5 
- **Database**: MongoDB 4.0.4
- **Operating system**: macOS 10.14.2

**What is the current behavior?**

When i try to POST invalid data to a route (missing required fields or wrong fields type) i get a 500 internal server error.

Log:
```log
{ ValidationError: Fattura validation failed: numero: Path `numero` is required., totale: Path `totale` is required., marca_da_bollo: Path `marca_da_bollo` is required., data: Path `data` is required.
    at ValidationError.inspect (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/error/validation.js:59:24)
    at formatValue (util.js:400:38)
    at inspect (util.js:294:10)
    at format (util.js:161:12)
    at Console.warn (console.js:145:21)
    at strapi.app.use (/usr/local/lib/node_modules/strapi/lib/middlewares/boom/index.js:34:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errors:
   { numero:
      { ValidatorError: Path `numero` is required.
    at new ValidatorError (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/error/validator.js:29:11)
    at validate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:871:13)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:924:11
    at Array.forEach (<anonymous>)
    at SchemaNumber.SchemaType.doValidate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:880:19)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/document.js:1904:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
        message: 'Path `numero` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'numero',
        value: null,
        reason: undefined,
        [Symbol(mongoose:validatorError)]: true },
     totale:
      { ValidatorError: Path `totale` is required.
    at new ValidatorError (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/error/validator.js:29:11)
    at validate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:871:13)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:924:11
    at Array.forEach (<anonymous>)
    at Float.SchemaType.doValidate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:880:19)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/document.js:1904:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
        message: 'Path `totale` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'totale',
        value: null,
        reason: undefined,
        [Symbol(mongoose:validatorError)]: true },
     marca_da_bollo:
      { ValidatorError: Path `marca_da_bollo` is required.
    at new ValidatorError (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/error/validator.js:29:11)
    at validate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:871:13)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:924:11
    at Array.forEach (<anonymous>)
    at SchemaString.SchemaType.doValidate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:880:19)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/document.js:1904:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
        message: 'Path `marca_da_bollo` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'marca_da_bollo',
        value: '',
        reason: undefined,
        [Symbol(mongoose:validatorError)]: true },
     data:
      { ValidatorError: Path `data` is required.
    at new ValidatorError (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/error/validator.js:29:11)
    at validate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:871:13)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:924:11
    at Array.forEach (<anonymous>)
    at SchemaDate.SchemaType.doValidate (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/schematype.js:880:19)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongoose/lib/document.js:1904:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
        message: 'Path `data` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'data',
        value: null,
        reason: undefined,
        [Symbol(mongoose:validatorError)]: true } },
  _message: 'Fattura validation failed',
  name: 'ValidationError' }
[2018-11-22T16:41:28.047Z] debug POST /fatturas/ (44 ms)
```

Same problem when i try to insert duplicated unique fields:

```log
{ MongoError: E11000 duplicate key error collection: database.fatture index: marca_da_bollo_1 dup key: { : "1231231234" }
    at Function.create (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongodb/lib/utils.js:149:22)
    at coll.s.topology.insert (/Users/stockmind/DockerProjects/fatture/server/node_modules/mongodb/lib/operations/collection_ops.js:844:39)
    at /Users/stockmind/DockerProjects/fatture/server/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 11000,
  errmsg: 'E11000 duplicate key error collection: database.fatture index: marca_da_bollo_1 dup key: { : "1231231234" }',
  [Symbol(mongoErrorContextSymbol)]: {} }
[2018-11-22T16:46:39.359Z] debug POST /fatturas/ (18 ms)
```

**Steps to reproduce the problem**

1. Create a Content Type with required fields.
2. POST objects with those fields missing or with invalid data or duplicated unique fields.
3. Get the "Internal server error"

**What is the expected behavior?**

I expect a json containing the validation errors in return or a status of the request, not an internal server error

**Suggested solutions**

**Comment by lauriejim** [comment]
Related to this feature/improvement https://portal.productboard.com/strapi/c/14-validations
Thank you for this feedback.
