### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by Charuru** [strapi/strapi#2381]
**Informations**
- **Node.js version**: v11.2.0
- **npm version**: 6.4.1
- **Strapi version**: Just installed today
- **Database**: mongodb
- **Operating system**: mac

**What is the current behavior?**
Attempted to create a new project with strapi new and got this error:
```
{ Error: Cannot find module '/tmp/strapie0ee81f6fc3a/node_modules/strapi-hook-mongoose/lib/utils/connectivity.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Promise.all.then (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:259:15) code: 'MODULE_NOT_FOUND' }
Error: An error occurred. The error exit was triggered on a switchback that is being handled with a callback function in userland. And since no truthy argument was provided, switchback created this anonymous error.
    at Function.error (/usr/local/lib/node_modules/strapi/node_modules/switchback/lib/normalize.js:40:23)
    at Promise.all.then (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:263:18)
```

**Comment by derrickmehaffy** [comment]
Please test with node 10

**Comment by Charuru** [comment]
Thanks @derrickmehaffy Downgraded to node v10.13.0 Same problem.

<img width="1948" alt="screen shot 2018-11-26 at 6 56 13 pm" src="https://user-images.githubusercontent.com/214436/49049442-00cef700-f1ad-11e8-8a63-4cbfbb2e1969.png">

**Comment by derrickmehaffy** [comment]
@Charuru this looks like a node issue, node shouldn't be trying to pull modules from /tmp

that folder is a temporary for downloading modules that get moved either into your global module storage or a project module storage.

**Comment by HedyHidouRy** [comment]
I had the same issue, trying this as sudo worked for me, and i actually don't know why

**Comment by MarvanN** [comment]
<img width="347" alt="Screenshot 2020-08-09 at 11 03 04 PM" src="https://user-images.githubusercontent.com/46482839/89738201-7d465e00-da94-11ea-939a-8abb96c22b73.png">
