### ISSUE TITLE
An error occurred during content-type-builder plugin installation.

### ISSUE THREAD

**Issue by zhouyuexie** [strapi/strapi#2388]
**Informations**
- **10.14.0**: 
- **6.4**: 
- **3.0.0-alpha.14.5**: 
- **mongodb: 3.2.21**: 
- **mac: 10.14.1**: 

**What is the current behavior?**

run `strapi new project_name` get install plugin error.

**Steps to reproduce the problem**

```shell
$ strapi new project_name
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
? Choose your main database: MongoDB
? Database name: guard
? Host: 192.168.10.30
? +srv connection: false
? Port (It will be ignored if you enable +srv): 27017
? Username: root
? Password: ****
? Authentication database (Maybe "admin" or blank): admin
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
⚠ An error occurred during content-type-builder plugin installation.
{ Error: Command failed: node /Users/quietboy/.nvm/versions/node/v10.14.0/lib/node_modules/strapi/bin/strapi.js install content-type-builder

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/quietboy/.nvm/versions/node/v10.14.0/lib/node_modules/strapi/bin/strapi.js install content-type-builder ' }
✔ Install plugin content-manager.
⚠ An error occurred during users-permissions plugin installation.
{ Error: Command failed: node /Users/quietboy/.nvm/versions/node/v10.14.0/lib/node_modules/strapi/bin/strapi.js install users-permissions

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/quietboy/.nvm/versions/node/v10.14.0/lib/node_modules/strapi/bin/strapi.js install users-permissions ' }
✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

👌 Your new application guard is ready at /Users/quietboy/git/guard.

⚡️ Change directory:
$ cd guard

⚡️ Start application:
$ strapi start
```

**What is the expected behavior?**

Even if you open the server and go to the plugin page, click the installation and it will not be installed successfully.

```shell
$ strapi install content-type-builder
[2018-11-28T05:38:03.030Z] debug Installation in progress...
[2018-11-28T05:38:03.032Z] debug Installing the plugin from npm registry.
[2018-11-28T05:38:06.510Z] error An error occurred during plugin installation.
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-content-type-builder
```

**Comment by zhouyuexie** [comment]
I found it to be a network problem, I can successfully install it after I set up the `taobao npm` image.

```shell
npm config set registry https://registry.npm.taobao.org
```

maybe you can try.
