### ISSUE TITLE
URL is not defined

### ISSUE THREAD

**Issue by anderson916** [strapi/strapi#2404]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 

**What is the current behavior?**

```
➜  strapi strapi start
[2018-11-29T15:43:27.694Z] debug ⛔️ Server wasn't able to start properly.
[2018-11-29T15:43:27.696Z] error URL is not defined
ReferenceError: URL is not defined
    at Strapi.module.exports.app (/usr/local/lib/node_modules/strapi/lib/core/configurations.js:333:10)
    at Strapi.load (/usr/local/lib/node_modules/strapi/lib/Strapi.js:222:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Steps to reproduce the problem**

```
strapi new project
cd project
strapi start
```

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@anderson916 please include the information:

```
Informations

Node.js version:
NPM version:
Strapi version:
Database:
Operating system:
```

**Comment by soupette** [comment]
@anderson916 please use node 10

**Comment by anderson916** [comment]
@soupette Thanks. Yes, I am using Node 8. Let me try Node 10 now.

**Comment by anderson916** [comment]
It works. Thanks.
