### ISSUE TITLE
EPERM error on strapi new

### ISSUE THREAD

**Issue by sylvainlap** [strapi/strapi#241]
**Node.js version**: 8.4.0
**npm version**: 5.2.0
**Strapi version**: 3.0.0-alpha.5.5
**Operating system**: Windows 10

On Windows 10, the `Linking `strapi` dependency to the project` step returns an `EPERM` error.

```
PS C:\Users\sylva\repos\strapi-test> strapi new
INFO (9500 on SYLVAINLAP-SP3): Creating your application... It might take a few seconds.
INFO (9500 on SYLVAINLAP-SP3): Copying the dashboard...
INFO (9500 on SYLVAINLAP-SP3): Installing dependencies...
INFO (9500 on SYLVAINLAP-SP3): Installing plugin `Settings Manager`...
INFO (9500 on SYLVAINLAP-SP3): Linking `strapi` dependency to the project...
fs.js:1020
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink 'C:\Users\sylva\AppData\Roaming\npm\node_modules\strapi' -> 'C:\Users\syl
va\repos\strapi-test\node_modules\strapi'
    at Object.fs.symlinkSync (fs.js:1020:18)
    at availableDependencies.forEach.dependency (C:\Users\sylva\AppData\Roaming\npm\node_modules\strapi\node_modules\str
api-generate-new\lib\after.js:94:14)
    at Array.forEach (<anonymous>)
    at exec (C:\Users\sylva\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\after.js:90:29)
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
```

As a result, after `npm start`, I got a `Error: Cannot find module 'strapi'` error.

**Comment by Steven-Sanseau** [comment]
I solve the problem with `npm link strapi`

**Comment by pierreburgy** [comment]
@sylvainlap, it looks like this is mostly a permission issue. Did you find a work arround?

It looks like your issue is very similar to this one: https://github.com/theintern/intern/issues/500. So the best solution may be to catch the EPERM error and copy instead of doing a symlink.

**Comment by Aurelsicoko** [comment]
You can also take a look at [this specific article](https://docs.npmjs.com/getting-started/fixing-npm-permissions) writing by the npm team. 

I'm closing the issue, feel free to open it again.
