### ISSUE TITLE
URL not defined error on strapi start

### ISSUE THREAD

**Issue by sidsaxena0** [strapi/strapi#2428]
**Informations**
- **Node.js version**:  8.12.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: Mongo
- **Operating system**: MAC OSx Mojave

**What is the current behavior?**

**Can't start strapi application. Crashes with message **URL is not defined** 

ReferenceError: URL is not defined
    at Strapi.module.exports.app (/Users/sid/Documents/web-projects/pokerhigh/pokeradmin/node_modules/strapi/lib/core/configurations.js:333:10)
    at Strapi.load (/Users/sid/Documents/web-projects/pokerhigh/pokeradmin/node_modules/strapi/lib/Strapi.js:222:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)**

**Steps to reproduce the problem**
Just create a new strapi app and start it with strapi start command 

**What is the expected behavior?**
It should simply start instead of crashing like this.

**Suggested solutions**
I tried this : 

As above log refer configuration.js file, so instead of this -

```
this.config.admin.url = this.config.admin.devMode ?
    (new URL(adminPath, `http://${this.config.host}:4000`)).toString():
    (new URL(adminPath, url)).toString();
```

Do this - 

`  this.config.admin.url = this.config.admin.devMode ? `http://${this.config.host}:4000/admin` : `http://${this.config.host}:1337/admin``

**Comment by derrickmehaffy** [comment]
@sidsaxena0 Node 10 is required see the README.md

**Comment by adamkhan** [comment]
Worked for me following Pierre's tutorial at https://blog.strapi.io/how-to-deploy-a-strapi-application/ for installing on Ubuntu. Thanks, @sidsaxena0

**Comment by faustofurtado** [comment]
@sidsaxena0 Hello I have the same error in Ubuntu.  How did you solve this problem?

`strapi console
[2019-02-13T13:16:34.316Z] info Starting the application in interactive mode...
[2019-02-13T13:16:36.280Z] debug ⛔️ Server wasn't able to start properly.
[2019-02-13T13:16:36.280Z] error URL is not defined
ReferenceError: URL is not defined
    at Strapi.module.exports.app (/usr/local/lib/node_modules/strapi/lib/core/configurations.js:332:10)
    at Strapi.load (/usr/local/lib/node_modules/strapi/lib/Strapi.js:222:29)
    at <anonymous>
`

**Comment by derrickmehaffy** [comment]
@faustofurtado https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#url-not-defined

Your using the wrong node version, Node 10 only

**Comment by Kriskasz** [comment]
Hi, I'm getting the same error on Ubuntu - 
debug ⛔️ Server wasn't able to start properly.
[2019-02-18T13:46:36.361Z] error URL is not defined
ReferenceError: URL is not defined
    at Strapi.module.exports.app (/usr/local/lib/node_modules/strapi/lib/core/configurations.js:332:10)
    at Strapi.load (/usr/local/lib/node_modules/strapi/lib/Strapi.js:222:29)
    at <anonymous>
I flowed this guide https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/ so project is completely new. Any help? It looks that issue still exist. 
OS: Ubuntu 16.04.4 LTS
nodejs version: v10.15.1
npm version:  6.8.0

**Comment by derrickmehaffy** [comment]
@Kriskasz that error only comes from the wrong node version.

I would double check what node is being used to run your Strapi instance

**Comment by Kriskasz** [comment]
I have only one node
nodejs -v
v10.15.1

**Comment by Kriskasz** [comment]
any help? How you see version of node is ok

**Comment by kamalbennani** [comment]
@Kriskasz I'm using the exact same version as you and it's seems to be working just fine, you can probably start the server in debug mode and try to figure out what's going on

**Comment by arielkuzminski** [comment]
My problem was that I got different service running on port 1337...
run `netstat -aon | findstr '[port_number]'` on Windows.

**Comment by Marvine89** [comment]
It look like there is an error on the `configurations.js` file inside `node_module/strapi/lib/core`  which state that URL is not defined.

There is a missing import` const { URL } = require('url');` on `configurations.js`.

this should be fixed by the strapi team

**Comment by derrickmehaffy** [comment]
@Marvine89 that error comes from using an old and unsupported node version: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#url-not-defined

**Comment by gfritzdev** [comment]
To fix this install node using Node Version Manager (NVM).  Once installed you can run command "nvm use 10.0.0" which will solve this issue.

https://github.com/nvm-sh/nvm
