### ISSUE TITLE
Content type and/or field being named "String" seemingly causes ObjectParameterError

### ISSUE THREAD

**Issue by w-biggs** [strapi/strapi#2453]
**Informations**
- **Node.js version**: `v10.12.0`
- **NPM version**: `6.4.1`
- **Strapi version**: `3.0.0-alpha.16`
- **Database**: MongoDB
- **Operating system**:
```
uname -a
Linux the-dell 4.4.0-17134-Microsoft #345-Microsoft Wed Sep 19 17:47:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**What is the current behavior?**
on running `yarn start`, I get this error:
```
yarn start
yarn run v1.10.1
$ node server.js

/mnt/d/Development/m-r/cms/node_modules/mongoose/lib/document.js:70
    throw new ObjectParameterError(obj, 'obj', 'Document');
    ^
ObjectParameterError: Parameter "obj" to Document() must be an object, got DeprecationWarning
    at new ObjectParameterError (/mnt/d/Development/m-r/cms/node_modules/mongoose/lib/error/objectParameter.js:25:11)
    at model.Document (/mnt/d/Development/m-r/cms/node_modules/mongoose/lib/document.js:70:11)
    at model.Model (/mnt/d/Development/m-r/cms/node_modules/mongoose/lib/model.js:93:12)
    at new model (/mnt/d/Development/m-r/cms/node_modules/mongoose/lib/model.js:4374:13)
    at model (/mnt/d/Development/m-r/cms/node_modules/mongoose/lib/model.js:4372:16)
    at process.emitWarning (internal/process/warning.js:131:22)
    at emitDeprecationWarning (internal/process/promises.js:95:13)
    at emitWarning (internal/process/promises.js:88:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Steps to reproduce the problem**
This happened when strapi restarted itself after I added a new content type. I may have been caused by me naming the content type "string" and a field inside that content type "string" as well... but honestly I have no clue, since the error seems to have nothing to do with that. Before this started happening, every time I started strapi I'd get `DeprecationWarning`s in the console (same as #1592), but I'm not sure why it only started causing problems after I added that content type.

**What is the expected behavior?**
It starts up normally, like it did before.

**Suggested solutions**
I deleted the "string" directory in the "api" directory, and now it starts up normally. I've attached the contents of that directory. It seems like this shouldn't be an issue, or there should be some protection against this becoming an issue, like refusing to allow content types and fields to be named "String".

**Comment by lauriejim** [comment]
Hello @w-biggs ! Thank you for this report.

Can you try with `npm` instead of `yarn` and tel me if it still happen ?

We not support `yarn` for now so I close issue relative to `yarn` 
https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#yarn

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Comment by oskareke** [comment]
I came across this issue as well, using npm.

**Comment by marcopesani** [comment]
Same here, using strapi Docker image. I've created a content type named "string" with three fields: key (string), value_it (text wyswyg), value_en (text wyswyg) 

`
/usr/src/api/conio-cms/node_modules/mongoose/lib/document.js:71
     throw new ObjectParameterError(obj, 'obj', 'Document');
     ^
 ObjectParameterError: Parameter "obj" to Document() must be an object, got DeprecationWarning
     at new ObjectParameterError (/usr/src/api/conio-cms/node_modules/mongoose/lib/error/objectParameter.js:25:11)
     at model.Document (/usr/src/api/conio-cms/node_modules/mongoose/lib/document.js:71:11)
     at model.Model (/usr/src/api/conio-cms/node_modules/mongoose/lib/model.js:93:12)
     at new model (/usr/src/api/conio-cms/node_modules/mongoose/lib/model.js:4486:13)
     at model (/usr/src/api/conio-cms/node_modules/mongoose/lib/model.js:4484:16)
     at process.emitWarning (internal/process/warning.js:132:22)
     at emitDeprecationWarning (internal/process/promises.js:95:13)
     at emitWarning (internal/process/promises.js:88:3)
     at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
     at process.internalTickCallback (internal/process/next_tick.js:78:34)
 2019-01-07T17:07:39.147+0000 I NETWORK  [conn39] end connection 172.26.0.3:47154 (0 connections now open)
`
