### ISSUE TITLE
Cannot start strapi because data truncated at First Name

### ISSUE THREAD

**Issue by eComEvo** [strapi/strapi#2473]
**Informations**
- **Node.js version**: 11.4.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MySQL 5.7
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
`strapi start` causes a crash with the following exception:
```
(node:22728) UnhandledPromiseRejectionWarning: Error: WARN_DATA_TRUNCATED: Data truncated for column 'First Name' at row 1
    at Query.Sequence._packetToError (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/forge/staging.api.example.com/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/forge/staging.api.example.com/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
    at Protocol._enqueue (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/forge/staging.api.example.com/node_modules/mysql/lib/Connection.js:200:25)
    at /home/forge/staging.api.example.com/node_modules/knex/lib/dialects/mysql/index.js:144:18
From previous event:
    at Client_MySQL._query (/home/forge/staging.api.example.com/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/home/forge/staging.api.example.com/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/home/forge/staging.api.example.com/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /home/forge/staging.api.example.com/node_modules/knex/lib/runner.js:47:21
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Runner.run (/home/forge/staging.api.example.com/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/home/forge/staging.api.example.com/node_modules/knex/lib/interface.js:23:43)
(node:22728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22728) UnhandledPromiseRejectionWarning: Error: WARN_DATA_TRUNCATED: Data truncated for column 'Last Name' at row 1
    at Query.Sequence._packetToError (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/forge/staging.api.example.com/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/forge/staging.api.example.com/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
    at Protocol._enqueue (/home/forge/staging.api.example.com/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/forge/staging.api.example.com/node_modules/mysql/lib/Connection.js:200:25)
    at /home/forge/staging.api.example.com/node_modules/knex/lib/dialects/mysql/index.js:144:18
From previous event:
    at Client_MySQL._query (/home/forge/staging.api.example.com/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/home/forge/staging.api.example.com/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/home/forge/staging.api.example.com/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /home/forge/staging.api.example.com/node_modules/knex/lib/runner.js:47:21
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Runner.run (/home/forge/staging.api.example.com/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/home/forge/staging.api.example.com/node_modules/knex/lib/interface.js:23:43)
(node:22728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2018-12-12T00:27:01.537Z] debug ⛔️ Server wasn't able to start properly.
[2018-12-12T00:27:01.539Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load
```

**Steps to reproduce the problem**
Add additional fields to the user model, one of which is "First Name"

**What is the expected behavior?**
`strapi start` boots the server

**Suggested solutions**

**Comment by henrych4** [comment]
check this out https://github.com/strapi/strapi/issues/2426#issuecomment-444043277

There exists some issues related to naming of fields.

**Comment by derrickmehaffy** [comment]
@eComEvo I added the following to the FAQ, for now you cannot use any different case styles on models and field names, you can however customize the "view" of fields inside the content-editor using the content management plugin.

See the following FAQ: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#model--field-naming-schemes

I am marking this issue as closed because it is not currently a bug with Strapi but due to improper use of case or symbols:

`First Name` instead of `firstname`
