### ISSUE TITLE
Relation tables not created when multi many-to-many relations 

### ISSUE THREAD

**Issue by pierreburgy** [strapi/strapi#2479]
**Informations**
- **Node.js version**: 11.4.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: Postgres
- **Operating system**: MacOS

**What is the current behavior?**
When I create two many-to-many relations on a Content Type, only the first one is created in the Postgres database.

**Steps to reproduce the problem**

 - Create two Content Types (`post` and `tags` for example)
 - Create a post
 - Create a many-to-many relation between posts and tags
 - Create a many-to-many relation between post and users
 - Edit the post

```
{ error: relation "pages_posts__posts_pages" does not exist
    at Connection.parseE (/Users/pierreburgy/Desktop/blog/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/pierreburgy/Desktop/blog/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/Users/pierreburgy/Desktop/blog/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
From previous event:
    at Client_PG._query (/Users/pierreburgy/Desktop/blog/node_modules/knex/lib/dialects/postgres/index.js:240:12)
    at Client_PG.query (/Users/pierreburgy/Desktop/blog/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/Users/pierreburgy/Desktop/blog/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Users/pierreburgy/Desktop/blog/node_modules/knex/lib/runner.js:47:21
From previous event:
    at Runner.run (/Users/pierreburgy/Desktop/blog/node_modules/knex/lib/runner.js:33:30)
    at Builder.Target.then (/Users/pierreburgy/Desktop/blog/node_modules/knex/lib/interface.js:23:43)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
  name: 'error',
  length: 124,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '158',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable' }
```

**What is the expected behavior?**
The relation table should be created.

**Suggested solutions**
If you move up the in second relation in `Page.settings.json`, it will be created.

**Comment by maksugr** [comment]
Are any news here?

**Comment by huberrom** [comment]
Same problem here, it's really blocking us.
Any progress on this @lauriejim ?

**Comment by tristantbg** [comment]
Same problem here :
https://github.com/strapi/strapi/issues/2185#issuecomment-464808490

Also the pages related are not saved as they should be on a MySQL DB. Everything is fine on MongoDB.
Any news about this ?

**Comment by georgepapas** [comment]
seeing the same issue here.. any updates?

**Comment by lauriejim** [comment]
It has been fixed in the beta version

**Comment by shahzaibmuneeb** [comment]
> It has been fixed in the beta version

When will this be released?

Is there a known temporary resolution? I've taken a look at the commit in the Beta branch for this and it looks like a significant change.

Thanks

**Comment by derrickmehaffy** [comment]
@shahzaibmuneeb within this month if everything goes to plan. And yes the beta is a huge change.
