### ISSUE TITLE
Create project problem

### ISSUE THREAD

**Issue by ANTEVETY** [strapi/strapi#2648]
**Informations**

**Node.js version: v10.13.0
npm version: 6.4.1
Strapi version: strapi@3.0.0-alpha.19
Database: postgres
Operating system: windows 10**

```
⏳ Testing database connection...
E:\Cache\UserTEMP\strapibfa6f9930259\node_modules\strapi-hook-bookshelf\node_modules\knex\lib\dialects\postgres\index.js:182
        resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
                                                                    ^

TypeError: Cannot read property '1' of null
    at Query.<anonymous> (E:\Cache\UserTEMP\strapibfa6f9930259\node_modules\strapi-hook-bookshelf\node_modules\knex\lib\dialects\postgres\index.js:182:69)
    at Query.handleReadyForQuery (E:\Cache\UserTEMP\strapibfa6f9930259\node_modules\pg\lib\query.js:125:10)
    at Connection.<anonymous> (E:\Cache\UserTEMP\strapibfa6f9930259\node_modules\pg\lib\client.js:192:19)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.<anonymous> (E:\Cache\UserTEMP\strapibfa6f9930259\node_modules\pg\lib\connection.js:125:12)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

**Comment by lauriejim** [comment]
Hello @ANTEVETY!

Did you check https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows ?
