### ISSUE TITLE
Server wasn't able to start properly

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2667]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I'm adding new content types with Strapi, and sometimes when I try to save, it breakes the whole project irreversibly and fails to strart. I cannot understnad why sometimes it happens and at other times it saves my new content types without an issue. Once it breakes, I don't know how to go back and have to use an earlier version of the project. I'm using node v.11.3.0 and strapi 3.0.0-alpha.18.
Thanks in advance
 My complete log is:

(node:9992) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:9992) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'join' of undefined
    at Object.keys.filter.map.attribute (E:\projects\CMS\cms1\server\plugins\graphql\services\Resolvers.js:106:34)
    at Array.map (<anonymous>)
    at models.reduce (E:\projects\CMS\cms1\server\plugins\graphql\services\Resolvers.js:99:10)
    at Array.reduce (<anonymous>)
    at Object.shadowCRUD (E:\projects\CMS\cms1\server\plugins\graphql\services\Resolvers.js:40:19)
    at E:\projects\CMS\cms1\server\plugins\graphql\services\Schema.js:163:24
    at Object.generateSchema (E:\projects\CMS\cms1\server\plugins\graphql\services\Schema.js:164:11)
    at Function.initialize (E:\projects\CMS\cms1\server\plugins\graphql\hooks\graphql\index.js:148:50)
    at E:\projects\CMS\cms1\server\node_modules\strapi\lib\hooks\index.js:19:29
    at after (E:\projects\CMS\cms1\server\node_modules\strapi\lib\hooks\index.js:122:39)
    at E:\projects\CMS\cms1\server\node_modules\lodash\lodash.js:9999:23
    at Strapi.once (E:\projects\CMS\cms1\server\node_modules\strapi\lib\hooks\index.js:133:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at loadedModule.initialize.call.err (E:\projects\CMS\cms1\server\node_modules\strapi\lib\hooks\index.js:32:12)
    at _.forEach (E:\projects\CMS\cms1\server\node_modules\strapi-hook-mongoose\lib\index.js:472:9)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:9992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-01-21T20:01:35.336Z] debug ⛔️ Server wasn't able to start properly.

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @omerfaran, can you try with last version of Strapi (`alpha.20`) and let me know if you still have this issue please.

**Comment by gethup** [comment]
Hi, I did get the same problem. 

Deleting the folder "/plugins/graphql" allowed the app to restart. 

Maybe it can help someone...

**Comment by lauriejim** [comment]
Duplicate of this issue https://github.com/strapi/strapi/issues/1612
Issue with GraphQL and windows

**Comment by omerfaran** [comment]
Hey guys,

I'm a bit afraid to update my Strapi version as I'm currently working on a project. But I did notice an action that seems to always break the project: when I try to add the Enumaration field (list of choices) in my Content Type plugin.
Once I add the field I have to save and restart, and then the project breaks.

For now I'm just not using that field.

Thanks in advance
