### ISSUE TITLE
Create project with postgres

### ISSUE THREAD

**Issue by alexesDev** [strapi/strapi#2677]
**Informations**
- **Node.js version**: v10.10.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.20
- **Database**: postgres
- **Operating system**: ArchLinux

**What is the current behavior?**
`strapi new content` crashes after choice postgres and enter a db name

**Steps to reproduce the problem**

```strapi new content                                                                                  alexes@pc
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
? Choose your main database: Postgres
? Database name: content
? Host: 127.0.0.1
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/tmp/strapi8d242835ee8a/node_modules/pg/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at exec (/usr/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:250:30)
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**What is the expected behavior?**
`strapi new content` should create a new project

**Comment by derrickmehaffy** [comment]
@alexesDev did you already create your database in postgres? Strapi will not create it for you.

Also that error you have with /tmp looks like a node problem. I would search around a bit as it seems node is acting strange or slow as you shouldn't be loading anything `/tmp`

**Comment by alexesDev** [comment]
@derrickmehaffy strapi crashes before I enter all the params.

> Also that error you have with /tmp looks like a node problem

strapi/node_modules/strapi-generate-new/lib/before.js:250
```
const lock = require(path.join(`${scope.tmpPath}`, '/node_modules/', `${scope.client.module}/package.json`));
```

strapi/node_modules/strapi-generate-new/lib/before.js:49
```
scope.tmpPath = path.resolve(os.tmpdir(), `strapi${ crypto.randomBytes(6).toString('hex') }`);
```

**Comment by alexesDev** [comment]
@derrickmehaffy you're right, its my problem.
```
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/end-of-stream: Integrity verification failed for sha512-5X5ZiS5qefp0EZdLw+1k/CLSvoaCGUJogWrjVoCaYEhgi1FRiLuoceYbPzwhX8JfU5CVkG4tgGUiTrjawDmLcA== (/home/alexes/.npm/_cacache/content-v2/sha512/e5/7e/59892e6a79fa7411974bc3ed64fc22d2be8682194268816ae356809a6048608b515188bba871e61b3f3c215fc25f539095906e2d8065224eb8dac0398b70)
```

But
```
// strapi-generate-new/lib/before.js
// npm install --prefix ...
exec(cmd, () => {
  // ... no error checking
```

**Comment by derrickmehaffy** [comment]
@alexesDev :stuck_out_tongue_winking_eye: I've seen this a few times

**Comment by derrickmehaffy** [comment]
I do agree though, there should be better error checking
