### ISSUE TITLE
The admin panel is unavailable... Impossible to open it in the browser.

### ISSUE THREAD

**Issue by nyzm** [strapi/strapi#2694]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.21
- **Database**: postgresql
- **Operating system**: Mac OS Mojave

**What is the current behavior?**
Projects generated via github cloned strapi is unable to start admin panel. 
It is not the case if strapi is installed via npm. 

**Steps to reproduce the problem**
1. git clone https://github.com/strapi/strapi.git
2. cd strapi && npm run setup
3. strapi -v 
 > 3.0.0-alpha.21
4. strapi new test
5. cd test && strapi start
[2019-01-25T07:51:17.489Z] info :comet:  Admin panel: http://localhost:4000/admin
[2019-01-25T07:51:17.489Z] info :zap: Server: http://localhost:1337
[2019-01-25T07:51:17.494Z] warn :warning:  The admin panel is unavailable... Impossible to open it in the browser.

**What is the expected behavior?**
Admin panel should start without an issue

**Comment by nyzm** [comment]
Hi @lauriejim ,
Well if I use `npm run setup:build` it will download the core plugins from internet and it works as expected. But I am trying to make additions on the core plugins so this won't work.
And if I try to npm start in admin folder I receive below error:

```
npm start

> strapi-admin@3.0.0-alpha.21 prestart /Users/nyzm/Projects/test/admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/nyzm/Projects/test/admin/node_modules/strapi-helper-plugin/node_modules/.bin/cross-env'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.21 prestart: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.21 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nyzm/.npm/_logs/2019-01-27T05_32_14_883Z-debug.log
```

**Comment by lauriejim** [comment]
@soupette any suggestion to this issue ?

@nyzm I think one issue like this already exist. I let you check that on closed issue.

**Comment by nyzm** [comment]
@lauriejim  I found out that above issue is about linking issue about strapi-helper-plugin according to issue #511 . 
After I linked the strapi-helper-plugin now I receive below error:

```
/test/admin  npm start

> strapi-admin@3.0.0-alpha.21 prestart /Users/nyzm/Projects/test/admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js


> strapi-admin@3.0.0-alpha.21 start /Users/nyzm/Projects/test/admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server

/Users/nyzm/Projects/strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js:71
    throw new Error(`Impossible to access to ${serverConfig}`);
    ^

Error: Impossible to access to /Users/nyzm/Projects/test/config/environments/development/server.json
    at Object.<anonymous> (/Users/nyzm/Projects/strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js:71:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/nyzm/Projects/strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.dev.babel.js:79:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.21 start: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.21 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nyzm/.npm/_logs/2019-01-27T14_24_50_338Z-debug.log
```

Which I found out is another linking issue. 

```
{ Error: Cannot find module '/Users/nyzm/Projects/test/admin/node_modules/strapi-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/nyzm/Projects/strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js:47:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/nyzm/Projects/strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.dev.babel.js:79:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32) code: 'MODULE_NOT_FOUND' }
```

After linking strapi-utils as well admin has been started.

```
Strapi plugin succesfully started in development mode. ✓

-----------------------------------
Access URL: http://localhost:4000/admin
-----------------------------------
Press CTRL-C to stop
```

When I try to access the page I receive below errors:

```
ERROR in Entry module not found: Error: Can't resolve '/Users/nyzm/Projects/test/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src/app.js' in '/Users/nyzm/Projects/test/admin'

ERROR in Entry module not found: Error: Can't resolve '/Users/nyzm/Projects/test/plugins/content-type-builder/node_modules/strapi-helper-plugin/lib/src/app.js' in '/Users/nyzm/Projects/test/admin'

ERROR in Entry module not found: Error: Can't resolve '/Users/nyzm/Projects/test/plugins/email/node_modules/strapi-helper-plugin/lib/src/app.js' in '/Users/nyzm/Projects/test/admin'

ERROR in Entry module not found: Error: Can't resolve '/Users/nyzm/Projects/test/plugins/settings-manager/node_modules/strapi-helper-plugin/lib/src/app.js' in '/Users/nyzm/Projects/test/admin'

ERROR in Entry module not found: Error: Can't resolve '/Users/nyzm/Projects/test/plugins/upload/node_modules/strapi-helper-plugin/lib/src/app.js' in '/Users/nyzm/Projects/test/admin'

ERROR in Entry module not found: Error: Can't resolve '/Users/nyzm/Projects/test/plugins/users-permissions/node_modules/strapi-helper-plugin/lib/src/app.js' in '/Users/nyzm/Projects/test/admin'
```

I am clueless

**Comment by nyzm** [comment]
More info on that : 
In each plugin folder strapi-helper-plugin is not in dependencies in package.json but in devDependencies. I haven't started the new project with `--dev` option. I regenerated the project. Now it works fine.

**Comment by DevarshiDave** [comment]
@nyzm having the same issue...when i start admin i am having that 'cannot resolve module' error...what to do?

**Comment by syedsimanta03** [comment]
no solution. Strapi should support all node versions

**Comment by derrickmehaffy** [comment]
@syedsimanta03 not going to happen, strapi will support node LTS versions only.

Right now node 10and node 12. All other versions are not supported and you use them at your own risk.

**Comment by syedsimanta03** [comment]
Tell me exact node version plz that is te best for strapi. Or share the node download link


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: DMehaffy <notifications@github.com> Date: 09/12/2019  7:22 p.m.  (GMT+06:00) To: strapi/strapi <strapi@noreply.github.com> Cc: syedsimanta03 <syed.simanta06@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [strapi/strapi] The admin panel is unavailable... Impossible to open it in the browser. (#2694) 
@syedsimanta03 not going to happen, strapi will support node LTS versions only.
Right now node 10and node 12. All other versions are not supported and you use them at your own risk.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/strapi/strapi/issues/2694?email_source=notifications\u0026email_token=AF46ELPBYSHBREFIFFIULW3QXZBCNA5CNFSM4GSNMGY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGJEYKY#issuecomment-563235883",
"url": "https://github.com/strapi/strapi/issues/2694?email_source=notifications\u0026email_token=AF46ELPBYSHBREFIFFIULW3QXZBCNA5CNFSM4GSNMGY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGJEYKY#issuecomment-563235883",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by derrickmehaffy** [comment]
https://nodejs.org/en/

![image](https://user-images.githubusercontent.com/8593673/70447212-9f966080-1a5b-11ea-8eeb-e6fda87546d2.png)

**Comment by syedsimanta03** [comment]
I am using 12.13.1 LTS still err

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@4.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@4.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/12/19,
21:28:33

**Comment by derrickmehaffy** [comment]
I'll need more information, most likely if you are on MacOS Catalina you are missing a bunch of dev depends that apple borked when they released that version.

**Comment by syedsimanta03** [comment]
USING node10.16 | win10 64bit 

43031 warn knex@0.20.4 requires a peer of mssql@^5.1.0 but none is installed. You must install peer dependencies yourself.
43032 warn knex@0.20.4 requires a peer of mysql@^2.17.1 but none is installed. You must install peer dependencies yourself.
43033 warn knex@0.20.4 requires a peer of mysql2@^1.7.0 but none is installed. You must install peer dependencies yourself.
43034 warn knex@0.20.4 requires a peer of pg@^7.12.1 but none is installed. You must install peer dependencies yourself.
43035 warn bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
43036 warn bookshelf@0.15.1 requires a peer of knex@>=0.13.0 <0.18.0 but none is installed. You must install peer dependencies yourself.
43037 verbose stack Error: gifsicle@4.0.1 postinstall: `node lib/install.js`
43037 verbose stack Exit status 1
43037 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
43037 verbose stack     at EventEmitter.emit (events.js:198:13)
43037 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
43037 verbose stack     at ChildProcess.emit (events.js:198:13)
43037 verbose stack     at maybeClose (internal/child_process.js:982:16)
43037 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
43038 verbose pkgid gifsicle@4.0.1
43039 verbose cwd C:\Users\Sam\Desktop\D-U\ecommerce-react-graphql-stripe\server
43040 verbose Windows_NT 10.0.18362
43041 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--no-optional"
43042 verbose node v10.16.0
43043 verbose npm  v6.9.0
43044 error code ELIFECYCLE
43045 error errno 1
43046 error gifsicle@4.0.1 postinstall: `node lib/install.js`
43046 error Exit status 1
43047 error Failed at the gifsicle@4.0.1 postinstall script.
43047 error This is probably not a problem with npm. There is likely additional logging output above.
43048 verbose exit [ 1, true ]

**Comment by syedsimanta03** [comment]
Please make stable version like npx create-react-app easy and works all the time

**Comment by derrickmehaffy** [comment]
@syedsimanta03 Can you please open up a new bug report and properly fill out the template so we can try to work on this issue.
