### ISSUE TITLE
Error when trying to use --dev command to create a new project on Windows

### ISSUE THREAD

**Issue by MatteoViera** [strapi/strapi#2707]
- Node.js version: Node 11.1.0
- NPM version: npm 6.4.1
- Strapi version: 3.0.0-alpha.21
- Database: MySQL
- Operating system: Windows 10

My error is this:
**Error: Cannot find module 'C:\Users\Utente\AppData\Local\Temp\strapi5f6b63b36451\node_modules\knex\package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at exec (C:\Users\Utente\WebstormProjects\strapi\packages\strapi-generate-new\lib\before.js:258:39)
    at ChildProcess.exithandler (child_process.js:280:7)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:387:11)**

**Steps to reproduce the problem**
I've cloned the git repository

npm run setup

strapi new strapiDev --dev

**What is the expected behavior?**
It should have created the project in dev mode, but it gives me this error ONLY if i try the --dev command

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Marking as closed as unsupported OS version/Type
