### ISSUE TITLE
GraphQL plugin installation issue

### ISSUE THREAD

**Issue by parikhdhruv24791** [strapi/strapi#2735]
**Informations**
- **Node.js version**: node v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.21 
- **Database**: Mongo 4.0.2
- **Operating system**: Windows x64
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When clicked from Plugin in Admin UI - Admin didnt respond, so i manually restarted strapi - there was error after restart:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Projects\strapi\my-project\plugins\graphql\node_modules\apollo-env\lib\polyfills\array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

So i removed the folder from plugins and reinstalled it from CLI:

strapi install graphql
Graph QL installed successfully from CLI but still same issue on starting strapi.

**Steps to reproduce the problem**

1. Go to admin panel and click install for GraphQL - wait for restart
OR
1. Go to CLI and execute "strapi install graphql"
2. Run strapi start

**What is the expected behavior?**

It should load the application

**Suggested solutions**

**Comment by giona69** [comment]
I have the same problem but with:

Database: mysql
Operating system: macosx

**Comment by merijnvanessen** [comment]
Whats your graphql plugin version?
I believe i created a new strapi project
Then installed the graphql plugin
Then added the API folder
And plugins/user-permissions/models folder

I have the Alpha 21 version as well, without problems

**Comment by aFINKndreas** [comment]
I also have the Alpha 21 for the graphql plugin.

**Comment by giona69** [comment]
alpha 21 version

**Comment by aFINKndreas** [comment]
just install core-js@3.0.0-beta.10 inside the graphql plugin folder. That worked for me as a quick fix.

**Comment by anitricks** [comment]
just started having this issue..

**Comment by parikhdhruv24791** [comment]
@aFINKndreas  Thanks that worked.. maybe plugin should be updated with same.

Solution:
> cd plugins/graphql
> npm i -S core-js@3.0.0-beta.10
> strapi start
