### ISSUE TITLE
Invalid token error doesn't handled on email-confirmation

### ISSUE THREAD

**Issue by EpicUsaMan** [strapi/strapi#2740]
**Informations**
- **Node.js version**: node 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0.alpha.21
- **Database**: mysql
- **Operating system**: linux

**What is the current behavior?**

Returns 500 error, in console not handled error Invalid token

**Steps to reproduce the problem**
1. Create account
2. Follow to link from email
3. Observe result of query

**What is the expected behavior?**

Error should be handled

**Comment by lauriejim** [comment]
Hello @EpicUsaMan !

I tried to reproduce your issue and all is working find for me.

Can you show me your error logs and give me your configuration.
And maybe more details of steps to reproduce.

**Comment by EpicUsaMan** [comment]
GET http://localhost:1337/auth/email-confirmation
(without any token)

![screenshot from 2019-02-04 22-13-25](https://user-images.githubusercontent.com/18231021/52234364-2291dc00-28ca-11e9-82c0-5edf24ce5934.png)

**Comment by lauriejim** [comment]
Ho okay! Thank you for this issue.

**Comment by dananw** [comment]
Hello, I got the same problem

Strapi Version:  3.0.0-beta.17.5 (node v10.16.2) 

`[2019-12-06T08:48:30.506Z] error Error: Invalid token.
    at /Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi-plugin-users-permissions/services/Jwt.js:64:27
    at Object.module.exports [as verify] (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/jsonwebtoken/verify.js:53:12)
    at /Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi-plugin-users-permissions/services/Jwt.js:56:11
    at new Promise (<anonymous>)
    at Object.verify (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi-plugin-users-permissions/services/Jwt.js:55:12)
    at Object.emailConfirmation (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi-plugin-users-permissions/controllers/Auth.js:582:20)
    at dispatch (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/koa-compose/index.js:44:32)
    at next (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/koa-compose/index.js:45:18)
    at dispatch (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at policies.push (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:67:28)
    at dispatch (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at module.exports (/Users/dananwijaya/Work/playground/strapi/my-project/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:111:9)`

Reproduce:
https://www.dropbox.com/s/anmoq1prs6wgbt4/Screen%20Recording%202019-12-06%20at%2015.47.35.mov?dl=0

**Comment by lauriejim** [comment]
Hello! You don't need to send the Authorization token for this route.
