### ISSUE TITLE
Possible missing module cross-spawn on new install

### ISSUE THREAD

**Issue by bovidiu** [strapi/strapi#2750]
**Informations**
- **Node.js version**:v10.6.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.21
- **Database**: mongodb 
- **Operating system**: OSX Mojave v10.14.2

**What is the current behavior?**
A fresh install of a project returned missing module `cross-spawn`.

```
$ strapi new uc
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
? Choose your main database: MongoDB
? Database name: sample_test
? Host: 127.0.0.1
? +srv connection: false
? Port (It will be ignored if you enable +srv): 32768
? Username:
? Password:
? Authentication database (Maybe "admin" or blank):
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
✔ Install plugin users-permissions.
✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

👌 Your new application uc is ready at /Users/ovidiubokar/uc.

⚡️ Change directory:
$ cd uc

⚡️ Start application:
$ strapi start

$ cd uc/

$ strapi start

{ Error: Cannot find module 'cross-spawn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/strapi/lib/utils/openBrowser.js:12:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module 'cross-spawn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/strapi/lib/utils/openBrowser.js:12:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
[2019-02-04T14:45:41.113Z] error Cannot read property 'start' of undefined

```

**Steps to reproduce the problem**
1. Install stapi globally
2. Create a new project `strapi new my_project` using mongodb
3. Try executing `strapi start` or `npm start` from `my_project`

**What is the expected behavior?**
Once `strapi start` or `npm start` the environment should start without any errors of missing modules.

i.e:
```$ strapi start
(node:16577) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:16577) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
[2019-02-04T14:46:27.267Z] info Time: Mon Feb 04 2019 14:46:27 GMT+0000 (Greenwich Mean Time)
[2019-02-04T14:46:27.268Z] info Launched in: 2777 ms
[2019-02-04T14:46:27.268Z] info Environment: development
[2019-02-04T14:46:27.268Z] info Process PID: 16577
[2019-02-04T14:46:27.268Z] info Version: 3.0.0-alpha.21 (node v10.6.0)
[2019-02-04T14:46:27.268Z] info To shut down your server, press <CTRL> + C at any time

[2019-02-04T14:46:27.268Z] info ☄️  Admin panel: http://localhost:1337/admin
[2019-02-04T14:46:27.269Z] info ⚡️ Server: http://localhost:1337
```

**Suggested solutions**
Add to package.json the missing module `cross-spawn` ?

**Comment by lauriejim** [comment]
Hello @bovidiu !
Sorry for this trouble.

Can you try with the version we publish today (alpha.22) and let me know it this issue still exist please.

**Comment by bovidiu** [comment]
@lauriejim sure, give me 30 min and i'll come back with an update.

**Comment by bovidiu** [comment]
@lauriejim I've retested the project using both options  `Quickstart` and  `Custom`; I wasn't able to reproduce it, this issue can be close because `alpha.22` seems to fix it.
