### ISSUE TITLE
Cannot destructure 'name' of undefined or 'null'

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2755]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.19
- **Database**:  mlab
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I'm just trying to edit a specific content type and when trying to save I get the error:

TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at updateModel (E:\projects\cms17-newrelations\server\plugins\content-type-builder\controllers\ContentTypeBuilder.js:94:111)
    at dispatch (E:\projects\cms17-newrelations\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\projects\cms17-newrelations\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at dispatch (E:\projects\cms17-newrelations\server\node_modules\koa-compose\index.js:42:32)
    at policies.push (E:\projects\cms17-newrelations\server\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:59:26)
    at dispatch (E:\projects\cms17-newrelations\server\node_modules\koa-compose\index.js:42:32)
    at module.exports (E:\projects\cms17-newrelations\server\plugins\users-permissions\config\policies\permissions.js:26:20)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

It doesn't matter what type of field I'm trying to add, actually even on removing a field and then trying to save I get this error.
I have no idea why it happened, it seems totally arbitrary. I don't know how to reproduce it either.
I'm feeling hopeless with all the unexpected bugs and behaviour:/

EDIT:
Reverting to an older project solves it, so something must have gone wrong on the way, but I don't know what. I used the program normally...

Thanks in advance

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by omerfaran** [comment]
Hello Laurie how are you?
Yes you're right to be honest I'm a bit hesitant to globally upgrady strapi, since I could theoretically lose my project settings.

Reverting is just using an older folder with all the strapi files (the server folder).

If you're sure it's the older version of strapi causing these problems then please close the issue.
Thank you(:

**Comment by lauriejim** [comment]
I'm pretty sure it come from one of this 2 points.
- Custom you may be did
- Migration issue

**Comment by omerfaran** [comment]
Thanks a lot Laurie
I'll update to the latest version of Strapi
Btw - how can I update from version * 3.0.0-alpha.19 ?
Should I just install the latest version globally?

**Comment by omerfaran** [comment]
Thanks I found the relavent article and installed the latest version

**Comment by lauriejim** [comment]
So what is the status ?

**Comment by omerfaran** [comment]
After merging my project with an older one it's working and I cannot tell what the problem was so it's ok to close it thanks!

**Comment by lauriejim** [comment]
Probably an issue on migration I think.
