### ISSUE TITLE
bootstraping error with user-permissions and upload modules

### ISSUE THREAD

**Issue by kidandcat** [strapi/strapi#2776]
**Informations**
- **Node.js version**: 10.14.2
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.21 and 3.0.0-alpha.22
- **Database**: MongoDB and SQlite (on alpha 22 only)
- **Operating system**: Ubuntu server 18.04

**What is the current behavior?**

🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕

Lets configurate the connection to your database:
? Choose your main database: MongoDB
? Database name: strapi-galax
? Host: 127.0.0.1
? +srv connection: false
? Port (It will be ignored if you enable +srv): 27017
? Username: 
? Password: 
? Authentication database (Maybe "admin" or blank): 
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
⚠ An error occurred during users-permissions plugin installation.
{ Error: Command failed: node /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js install users-permissions 
- Install users-permissions plugin
✖ An error occurred during plugin installation.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js install users-permissions ' }
✔ Install plugin email.
⚠ An error occurred during upload plugin installation.
{ Error: Command failed: node /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js install upload 
- Install upload plugin
✖ An error occurred during plugin installation.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js install upload ' }
✔ Link strapi dependency to the project.

👌 Your new application strapi-galax is ready at /root/strapi-galax.

⚡️ Change directory:
$ cd strapi-galax

⚡️ Start application:
$ strapi start

**Steps to reproduce the problem**

 - strapi new myapp

**What is the expected behavior?**

It should install successfully

**Suggested solutions**

**Comment by kidandcat** [comment]
It works nice with NPM. There is some kind of incompatibility with Yarn.

**Comment by kidandcat** [comment]
Update again: the error still exists, but NPM doesn't give any problem when installing, but when starting strapi, it gives errors:

error { MongoError: there are no users authenticated
    at /root/strapi-galax/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/root/strapi-galax/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/root/strapi-galax/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/root/strapi-galax/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/root/strapi-galax/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by derrickmehaffy** [comment]
@kidandcat https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#yarn

**Comment by kidandcat** [comment]
Thanks but as I said on a update, it is not working even with NPM. (it doesn't throws any error on installation, but later the same plugins fails, user-perms and upload)

**Comment by lauriejim** [comment]
I think it comes from your database connection settings.
Make sure your `./config/environments/development/database.json` settings are correct for the database you are trying to connect with.

**Comment by kidandcat** [comment]
It's a clean mongo installation. I think it has no user no pass. I'm letting them blank.

**Comment by lauriejim** [comment]
You mix yarn issue, installation issue and database connection issue.
So I don't understand what is your issue now... Can you make it clear please.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
