### ISSUE TITLE
ERROR: Impossible to find the plugin where `strapi.query` and Cannot read property 'count' of undefined 

### ISSUE THREAD

**Issue by Almusamim** [strapi/strapi#282]
I'm getting this error after generating an api and after going to the list product page.

Is there something I should do after generating  api?

```
DEBUG (5040 on DESKTOP-C2OQDKG): GET /content-manager/explorer/product?skip=0&limit=10&sort=_id (3 ms)
ERROR (5040 on DESKTOP-C2OQDKG): Impossible to find the plugin where `strapi.query` has been called.
ERROR (5040 on DESKTOP-C2OQDKG): Cannot read property 'count' of undefined
    TypeError: Cannot read property 'count' of undefined 
        at count (C:\Users\Hadi\Desktop\project\strapp\plugins\content-manager\controllers\ContentManager.js:45:55) 
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32) 
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18) 
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32) 
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:43:18) 
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:28:11 
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32) 
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:34:12 
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32) 
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18) 
        at validator (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:322:38) 
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32) 
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18) 
        at parsePayload (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:248:62) 
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32) 
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18) 
DEBUG (5040 on DESKTOP-C2OQDKG): GET /content-manager/explorer/product/count (4 ms)
DEBUG (5040 on DESKTOP-C2OQDKG): GET /admin/8b4f872c5de19974857328d06d3fe48f.woff2 (3 ms)
DEBUG (5040 on DESKTOP-C2OQDKG): GET /admin/c9cbbdc3762c340d5d37073a54971487.woff2 (2 ms)
DEBUG (5040 on DESKTOP-C2OQDKG): GET /favicon.ico (1 ms)
```

**Node.js version**: v8.1.3 
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.6.3
**Operating system**: Win 10

**Comment by hadihallak** [comment]
Oh boy, that was creepy.. thought I was reading my logs for a moment since we share the same windows username.
anyways. I get the same error in addition to a bunch of other errors for create, find, count
i tried on both the mysql and windows connector.

**Node.js version:** v8.2.1
**npm version:** 5.4.2
**Strapi version:** 3.0.0-alpha.6.3
**Operating system:** Win 10
```
ERROR (33260 on DESKTOP-A): Impossible to find the plugin where `strapi.query` has been called.
ERROR (33260 on DESKTOP-A): Cannot read property 'create' of undefined
    TypeError: Cannot read property 'create' of undefined
        at create (E:\ferasapp\plugins\content-manager\controllers\ContentManager.js:68:62)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:43:18)
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:28:11
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32)
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:34:12
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at validator (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:322:38)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at parsePayload (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:248:62)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
```
```
DEBUG (33260 on DESKTOP-A): GET /content-manager/explorer/to?skip=0&limit=10&sort=_id (34 ms)
ERROR (33260 on DESKTOP-A): Impossible to find the plugin where `strapi.query` has been called.
ERROR (33260 on DESKTOP-A): Cannot read property 'count' of undefined
    TypeError: Cannot read property 'count' of undefined
        at count (E:\ferasapp\plugins\content-manager\controllers\ContentManager.js:45:55)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:43:18)
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:28:11
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32)
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:34:12
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at validator (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:322:38)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at parsePayload (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:248:62)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
```
```
ERROR (33260 on DESKTOP-A): Impossible to find the plugin where `strapi.query` has been called.
ERROR (33260 on DESKTOP-A): Cannot read property 'find' of undefined
    TypeError: Cannot read property 'find' of undefined
        at find (E:\ferasapp\plugins\content-manager\controllers\ContentManager.js:32:57)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:43:18)
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:28:11
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:42:32)
        at C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-compose\index.js:34:12
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at validator (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:322:38)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at parsePayload (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-joi-router\joi-router.js:248:62)
        at dispatch (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\Hadi\AppData\Roaming\npm\node_modules\strapi\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
```

**Comment by Almusamim** [comment]
haha @hadihallak the coincidence  💃 

anyway @Aurelsicoko fixed this https://github.com/strapi/strapi/commit/2ef73c5b423dd9e6b8fd0ff850a0ba226d9b5316 error.

just change in node_module\strapi\lib\Strapi.js on line 274
From ``} else if (file.indexOf('/plugins/') !== -1) {``
to ```} else if (file.indexOf(path.sep + 'plugins' + path.sep) !== -1) {```

**Comment by Aurelsicoko** [comment]
It will be pushed in the next release. Thanks guys for pointing this out!
