### ISSUE TITLE
strapi won't start after adding content type with same name as JS type (Map)

### ISSUE THREAD

**Issue by jamesej** [strapi/strapi#2828]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: Mongo
- **Operating system**: Ubuntu 18:04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
strapi start throws this error:

(node:27168) UnhandledPromiseRejectionWarning: TypeError: Map is not a constructor
    at new Kareem (/home/ubuntu/firedrake-website-be/node_modules/kareem/index.js:4:16)
    at Mongoose.Schema.Schema [as constructor] (/home/ubuntu/firedrake-website-be/node_modules/mongoose/lib/schema.js:106:12)
    at new Mongoose.Schema (/home/ubuntu/firedrake-website-be/node_modules/mongoose/lib/index.js:67:21)
    at _.after (/home/ubuntu/firedrake-website-be/node_modules/strapi-hook-mongoose/lib/index.js:341:30)
    at /home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:9999:23
    at _.forEach (/home/ubuntu/firedrake-website-be/node_modules/strapi-hook-mongoose/lib/index.js:494:15)
    at /home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:2996:24)
    at /home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/home/ubuntu/firedrake-website-be/node_modules/strapi-hook-mongoose/lib/index.js:352:15)
    at /home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:2996:24)
    at /home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/home/ubuntu/firedrake-website-be/node_modules/lodash/lodash.js:9344:14)
    at mountModels (/home/ubuntu/firedrake-website-be/node_modules/strapi-hook-mongoose/lib/index.js:301:13)
    at _.forEach (/home/ubuntu/firedrake-website-be/node_modules/strapi-hook-mongoose/lib/index.js:500:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Steps to reproduce the problem**

After entering a number of content types, the UI started showing an error when trying to view a content type. Then the site showed a 502 error. On investigation the above error was found

**What is the expected behavior?**

Strapi starts successfully

**Suggested solutions**

**Comment by jamesej** [comment]
I believe this might have to do with creating a content type named 'Map', would this make sense? If so you should be blocking use of such reserved words as content types.

**Comment by jamesej** [comment]
Yes confirmed this was the cause as deleting api/map directory let strapi run again.

**Comment by lauriejim** [comment]
In fact it's related to this issue https://github.com/strapi/strapi/issues/2149
So I close this one to manage this topic in one issue.
