### ISSUE TITLE
Crash on adding model in SQLite

### ISSUE THREAD

**Issue by mpuz** [strapi/strapi#2891]
Node 10.4.1
The latest version of Strapi.

Started project as Quickstart, using SQLite.
Occasionally added model named "titles" at the Content Builder inside admin UI, on saving server crashed and never started again. 
Had to manually delete broken model subfolder at the API  folder. After this server started successfully , but the item named "titles" persist in the content menu and gives "error" when i try to modify it in any way

```strapi start
(node:42594) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
    at Client_SQLite3._query (/Volumes/WORK1/YANDEX_DISK/STEELTRADE/STRAPI/steeltrade/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/Volumes/WORK1/YANDEX_DISK/STEELTRADE/STRAPI/steeltrade/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/Volumes/WORK1/YANDEX_DISK/STEELTRADE/STRAPI/steeltrade/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Volumes/WORK1/YANDEX_DISK/STEELTRADE/STRAPI/steeltrade/node_modules/knex/lib/runner.js:47:21
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/Volumes/WORK1/YANDEX_DISK/STEELTRADE/STRAPI/steeltrade/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/Volumes/WORK1/YANDEX_DISK/STEELTRADE/STRAPI/steeltrade/node_modules/knex/lib/interface.js:23:43)
(node:42594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-26T17:24:39.484Z] debug ⛔️ Server wasn't able to start properly.
[2019-02-26T17:24:39.485Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load```

**Comment by derrickmehaffy** [comment]
@mpuz Please update your original post to follow the bug report template: https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

Marking as closed until the template is used.
