### ISSUE TITLE
Schema hasn\'t been registered for model "UploadFile" with Mongo Database

### ISSUE THREAD

**Issue by mdzzohrabi** [strapi/strapi#2895]
Hello

**Informations**

* **Node.js version**: v10.15.1
* **npm version**: 6.4.1
* **Strapi version**: 3.0.0-alpha.24.1
* **Database**: Mongo
* **Operating system**: Windows 10

In Content with File Field a got an Error :

```
MissingSchemaError: Schema hasn't been registered for model "UploadFile".
Use mongoose.model(name, schema)
```

```
Use mongoose.model(name, schema)
    at new MissingSchemaError (D:\Projects\expo\strapi\node_modules\mongoose\lib\error\missingSchema.js:22:11)
    at NativeConnection.Connection.model (D:\Projects\expo\strapi\node_modules\mongoose\lib\connection.js:825:11)
    at getModelsMapForPopulate (D:\Projects\expo\strapi\node_modules\mongoose\lib\model.js:4228:57)
    at populate (D:\Projects\expo\strapi\node_modules\mongoose\lib\model.js:3721:21)
    at _populate (D:\Projects\expo\strapi\node_modules\mongoose\lib\model.js:3691:5)
    at utils.promiseOrCallback.cb (D:\Projects\expo\strapi\node_modules\mongoose\lib\model.js:3664:5)
    at Object.promiseOrCallback (D:\Projects\expo\strapi\node_modules\mongoose\lib\utils.js:248:12)
    at Function.Model.populate (D:\Projects\expo\strapi\node_modules\mongoose\lib\model.js:3663:16)
    at cb (D:\Projects\expo\strapi\node_modules\mongoose\lib\query.js:1793:17)
    at result (D:\Projects\expo\strapi\node_modules\mongodb\lib\utils.js:414:17)
    at executeCallback (D:\Projects\expo\strapi\node_modules\mongodb\lib\utils.js:406:9)
    at handleCallback (D:\Projects\expo\strapi\node_modules\mongodb\lib\utils.js:128:55)
    at cursor.close (D:\Projects\expo\strapi\node_modules\mongodb\lib\operations\cursor_ops.js:224:62)
    at handleCallback (D:\Projects\expo\strapi\node_modules\mongodb\lib\utils.js:128:55)
    at completeClose (D:\Projects\expo\strapi\node_modules\mongodb\lib\cursor.js:893:14)
    at _endSession (D:\Projects\expo\strapi\node_modules\mongodb\lib\cursor.js:904:37)
    at Cursor._endSession (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:195:5)
    at Cursor._endSession (D:\Projects\expo\strapi\node_modules\mongodb\lib\cursor.js:226:59)
    at Cursor.close (D:\Projects\expo\strapi\node_modules\mongodb\lib\cursor.js:904:19)
    at cursor._next (D:\Projects\expo\strapi\node_modules\mongodb\lib\operations\cursor_ops.js:224:23)
    at handleCallback (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:204:5)
    at _setCursorNotifiedImpl (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:433:38)
    at self._endSession (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:441:46)
    at ClientSession.endSession (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\sessions.js:129:41)
    at Cursor._endSession (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:190:13)
    at Cursor._endSession (D:\Projects\expo\strapi\node_modules\mongodb\lib\cursor.js:226:59)
    at _setCursorNotifiedImpl (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:441:17)
    at setCursorNotified (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:433:3)
    at setCursorDeadAndNotified (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:426:3)
    at nextFunction (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:554:5)
    at Cursor.next (D:\Projects\expo\strapi\node_modules\mongodb-core\lib\cursor.js:763:3)
    at Cursor._next (D:\Projects\expo\strapi\node_modules\mongodb\lib\cursor.js:211:36)
    at fetchDocs (D:\Projects\expo\strapi\node_modules\mongodb\lib\operations\cursor_ops.js:217:12)
    at cursor._next (D:\Projects\expo\strapi\node_modules\mongodb\lib\operations\cursor_ops.js:243:7)
  message:
   'Schema hasn\'t been registered for model "UploadFile".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
```

**Comment by derrickmehaffy** [comment]
`D:\Projects\expo\strapi`

Windows is not currently supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Please test using WSL or a Linux VM, note when using WSL do not use a mapped windows drive, use one of the WSL drives (such as `/home/wslUser`)

**Comment by derrickmehaffy** [comment]
Marking as closed for now as unsupported OS, please do feel free to test on a supported platform, if the error still exists we can reopen.

**Comment by zero298** [comment]
I'm getting the same issue on macOS 10.14.5.  The paths are Unix paths, but the error is the same.  I use a created mongodb database and try to use a content-type that leverages the mongodb connection and add a Media field.  After it finishes saving and tries to restart the server, I get the exact same error as OP but with Unix paths.  This doesn't occur if I try with the default connection that uses the `strapi-hook-bookshelf` connector.

**Comment by WolvenSpirit** [comment]
I have the same issue on Ubuntu with mongoose 5.6.10 on a new project strapi@beta.15.

`error MissingSchemaError: Schema hasn't been registered for model "UploadFile".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/error/missingSchema.js:22:11)
    at NativeConnection.Connection.model (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/connection.js:946:11)
    at getModelsMapForPopulate (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:198:59)
    at populate (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/model.js:4093:21)
    at _populate (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/model.js:4063:5)
    at utils.promiseOrCallback.cb (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/model.js:4038:5)
    at Object.promiseOrCallback (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/utils.js:249:12)
    at Function.Model.populate (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/model.js:4037:16)
    at cb (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongoose/lib/query.js:1862:17)
    at result (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/utils.js:410:17)
    at executeCallback (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/utils.js:402:9)
    at handleCallback (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/operations/cursor_ops.js:224:62)
    at handleCallback (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/cursor.js:898:14)
    at _endSession (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/cursor.js:909:37)
    at Cursor._endSession (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/cursor.js:195:5)
    at Cursor._endSession (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/cursor.js:231:59)
    at Cursor.close (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/cursor.js:909:19)
    at cursor._next (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/operations/cursor_ops.js:224:23)
    at handleCallback (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/cursor.js:204:5)
    at _setCursorNotifiedImpl (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/cursor.js:426:38)
    at self._endSession (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/cursor.js:434:46)
    at ClientSession.endSession (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/sessions.js:134:41)
    at Cursor._endSession (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/cursor.js:190:13)
    at Cursor._endSession (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb/lib/cursor.js:231:59)
    at _setCursorNotifiedImpl (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/cursor.js:434:17)
    at setCursorNotified (/home/mihai/ng_app/strapi_project/strapi-api01/node_modules/mongodb-core/lib/cursor.js:426:3)`

**Comment by bitbreakr** [comment]
Same issue

**Comment by lucacattide** [comment]
As the others, but on Heroku:
```
2019-10-11T10:08:37.153002+00:00 app[web.1]: [2019-10-11T10:08:37.152Z] error MissingSchemaError: Schema hasn't been registered for model "UploadFile".
2019-10-11T10:08:37.153022+00:00 app[web.1]: Use mongoose.model(name, schema)
2019-10-11T10:08:37.153025+00:00 app[web.1]: at new MissingSchemaError (/app/node_modules/mongoose/lib/error/missingSchema.js:22:11)
2019-10-11T10:08:37.153027+00:00 app[web.1]: at NativeConnection.Connection.model (/app/node_modules/mongoose/lib/connection.js:973:11)
2019-10-11T10:08:37.153028+00:00 app[web.1]: at getModelsMapForPopulate (/app/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:200:59)
2019-10-11T10:08:37.153030+00:00 app[web.1]: at populate (/app/node_modules/mongoose/lib/model.js:4091:21)
2019-10-11T10:08:37.153031+00:00 app[web.1]: at _populate (/app/node_modules/mongoose/lib/model.js:4061:5)
2019-10-11T10:08:37.153033+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4036:5
2019-10-11T10:08:37.153034+00:00 app[web.1]: at Object.promiseOrCallback (/app/node_modules/mongoose/lib/utils.js:249:12)
2019-10-11T10:08:37.153036+00:00 app[web.1]: at Function.Model.populate (/app/node_modules/mongoose/lib/model.js:4035:16)
2019-10-11T10:08:37.153037+00:00 app[web.1]: at model.Query.Query._completeOne (/app/node_modules/mongoose/lib/query.js:2077:9)
2019-10-11T10:08:37.153038+00:00 app[web.1]: at Immediate.<anonymous> (/app/node_modules/mongoose/lib/query.js:2116:10)
2019-10-11T10:08:37.153039+00:00 app[web.1]: at Immediate.<anonymous> (/app/node_modules/mquery/lib/utils.js:116:16)
2019-10-11T10:08:37.153041+00:00 app[web.1]: at processImmediate (internal/timers.js:439:21)
```

**Comment by LYY** [comment]
Same issue.

I create a content type which is named 'Ads', upload a file in it. and then change the content type's name.
Now, go to the Files Upload, it shows an error:

```
[2019-11-28T05:18:52.574Z] debug GET /upload/files?_limit=10&_sort=hash%3AASC&_start=0 (11 ms) 500
[2019-11-28T05:19:23.088Z] debug GET /upload/files/count (5 ms) 200
[2019-11-28T05:19:23.093Z] error MissingSchemaError: Schema hasn't been registered for model "Ads".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/srv/app/node_modules/mongoose/lib/error/missingSchema.js:22:11)
    at NativeConnection.Connection.model (/srv/app/node_modules/mongoose/lib/connection.js:973:11)
    at getModelsMapForPopulate (/srv/app/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:200:59)
    at populate (/srv/app/node_modules/mongoose/lib/model.js:4091:21)
    at _populate (/srv/app/node_modules/mongoose/lib/model.js:4061:5)
    at /srv/app/node_modules/mongoose/lib/model.js:4036:5
    at Object.promiseOrCallback (/srv/app/node_modules/mongoose/lib/utils.js:249:12)
    at Function.Model.populate (/srv/app/node_modules/mongoose/lib/model.js:4035:16)
    at cb (/srv/app/node_modules/mongoose/lib/query.js:1914:17)
    at /srv/app/node_modules/mongodb/lib/operations/execute_operation.js:75:17
    at executeCallback (/srv/app/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/srv/app/node_modules/mongodb/lib/utils.js:129:55)
    at /srv/app/node_modules/mongodb/lib/operations/to_array.js:36:13
    at handleCallback (/srv/app/node_modules/mongodb/lib/utils.js:129:55)
    at completeClose (/srv/app/node_modules/mongodb/lib/cursor.js:859:16)
    at Cursor.close (/srv/app/node_modules/mongodb/lib/cursor.js:878:12)
    at /srv/app/node_modules/mongodb/lib/operations/to_array.js:35:25
    at handleCallback (/srv/app/node_modules/mongodb/lib/core/cursor.js:32:5)
    at /srv/app/node_modules/mongodb/lib/core/cursor.js:694:38
    at /srv/app/node_modules/mongodb/lib/core/cursor.js:703:39
    at Cursor._endSession (/srv/app/node_modules/mongodb/lib/core/cursor.js:404:7)
    at _setCursorNotifiedImpl (/srv/app/node_modules/mongodb/lib/core/cursor.js:703:10)
```
And the uploaded file was missed.

**Comment by ishan123456789** [comment]
Same for me 
```
2020-06-30T13:15:49.519Z] error MissingSchemaError: Schema hasn't been registered for model "test".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/Personal/iqge/tests/server/node_modules/mongoose/lib/error/missingSchema.js:22:11)
    at NativeConnection.Connection.model (/Personal/iqge/tests/server/node_modules/mongoose/lib/connection.js:1029:11)
    at getModelsMapForPopulate (/Personal/iqge/tests/server/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:201:59)
    at populate (/Personal/iqge/tests/server/node_modules/mongoose/lib/model.js:4250:21)
    at _populate (/Personal/iqge/tests/server/node_modules/mongoose/lib/model.js:4220:5)
    at utils.promiseOrCallback.cb (/Personal/iqge/tests/server/node_modules/mongoose/lib/model.js:4195:5)
    at Object.promiseOrCallback (/Personal/iqge/tests/server/node_modules/mongoose/lib/utils.js:261:12)
    at Function.Model.populate (/Personal/iqge/tests/server/node_modules/mongoose/lib/model.js:4193:16)
```
Here are my strapi versions :
```
"strapi": "3.0.0-beta.20.3",
    "strapi-admin": "3.0.0-beta.20.3",
    "strapi-utils": "3.0.0-beta.20.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20.3",
    "strapi-plugin-content-manager": "3.0.0-beta.20.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.20.3",
    "strapi-plugin-email": "3.0.0-beta.20.3",
    "strapi-plugin-upload": "3.0.0-beta.20.3",
    "strapi-connector-mongoose": "3.0.0-beta.20.3"
```
