### ISSUE TITLE
After install async error

### ISSUE THREAD

**Issue by bigelowgraphics** [strapi/strapi#2902]
strapi -v
/usr/lib/node_modules/strapi/node_modules/strapi-utils/lib/policy.js:101
    return async (ctx, next) => {
                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/strapi/node_modules/strapi-utils/lib/index.js:17:11)

This is after installation I have this issue.

**Comment by derrickmehaffy** [comment]
@bigelowgraphics please update your original post with the bug report template filled out properly, you see an example of the template here: https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

Please note on that template: `<!-- ⚠️ If you do not respect this template your issue will be closed. -->`

For now I am marking this as closed, please reply once you have updated your report with the template and this can be reopened. :+1:
