### ISSUE TITLE
Installation problem "glob"

### ISSUE THREAD

**Issue by dewid1985** [strapi/strapi#2926]
**Informations**
- **Node.js version**: 10.15.2
- **NPM version**: 6.4.1
- **Strapi version**: `Add Strapi Version`
- **Database**: `Add Database Type`
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: 

** [installation according to this documentation](https://strapi.io/documentation/3.x.x/plugin-development/quick-start.html#development-environment-setup)**

**log installation **

npm run setup

> @3.0.0-alpha.24.1 setup /home/strapi
> npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean

> @3.0.0-alpha.24.1 clean:all /home/strapi
> npm run removesymlinkdependencies && npx rimraf package-lock.json && npx rimraf packages/*/package-lock.json && npx rimraf packages/*/node_modules

> @3.0.0-alpha.24.1 removesymlinkdependencies /home/strapi
> node ./scripts/removeSymlinkDependencies.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/nodejs/rimraf/rimraf.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Please me!!!

**Comment by derrickmehaffy** [comment]
@dewid1985 Please finish updating the template to include the require options that I highlighted (just edit the original post above)

Can you please confirm that you do not have the Strapi global package installed (you can run `which strapi` in a terminal to see the location)

**Comment by DanLahav-TG** [comment]
run npm ls strapi -g
