### ISSUE TITLE
Error while creating new strapi app

### ISSUE THREAD

**Issue by ChristianLJ** [strapi/strapi#2944]
Using newest alpha release of strapi (alpha-24.1) with:
Node: 10.15.3
NPM: 6.9.0
Windows 10 Enterprise, Version 10.0.17763 Build 17763
MySQL 5.7.14

**What is the current behavior?**
When trying to create a new project i get the following errors:

```
The app has been connected to the database successfully!

🏗  Application generation:
√ Copy dashboard
‼ An error occurred during settings-manager plugin installation.
C:\Users\Christian:1
(function (exports, require, module, __filename, __dirname) { Zendesk Chat: LiveChatAPI call "button.setColor" is deprecated and may be removed in the future. Use "$zopim.livechat.theme.setColor" instead.
                                                                      ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

‼ An error occurred during content-type-builder plugin installation.
C:\Users\Christian:1
(function (exports, require, module, __filename, __dirname) { Zendesk Chat: LiveChatAPI call "button.setColor" is deprecated and may be removed in the future. Use "$zopim.livechat.theme.setColor" instead.
                                                                      ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

‼ An error occurred during content-manager plugin installation.
C:\Users\Christian:1
(function (exports, require, module, __filename, __dirname) { Zendesk Chat: LiveChatAPI call "button.setColor" is deprecated and may be removed in the future. Use "$zopim.livechat.theme.setColor" instead.
                                                                      ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

‼ An error occurred during users-permissions plugin installation.
C:\Users\Christian:1
(function (exports, require, module, __filename, __dirname) { Zendesk Chat: LiveChatAPI call "button.setColor" is deprecated and may be removed in the future. Use "$zopim.livechat.theme.setColor" instead.
                                                                      ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

‼ An error occurred during email plugin installation.
C:\Users\Christian:1
(function (exports, require, module, __filename, __dirname) { Zendesk Chat: LiveChatAPI call "button.setColor" is deprecated and may be removed in the future. Use "$zopim.livechat.theme.setColor" instead.
                                                                      ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

‼ An error occurred during upload plugin installation.
C:\Users\Christian:1
(function (exports, require, module, __filename, __dirname) { Zendesk Chat: LiveChatAPI call "button.setColor" is deprecated and may be removed in the future. Use "$zopim.livechat.theme.setColor" instead.
                                                                      ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

√ Link strapi dependency to the project.

👌 Your new application apitest2 is ready at C:\Users\Christian Leicht\Desktop\test\apitest\apitest2.

⚡️ Change directory:
$ cd apitest2

⚡️ Start application:
$ strapi start
```

The admin panel starts as expected but no plugins are installed.

**Steps to reproduce the problem**
```
npm i strapi@alpha -g
mkdir test
cd "test"
strapi new testproject
```

**What is the expected behavior?**
Plugins is installed as expected.

**Suggested solutions**
- Nothing yet.

**Comment by ChristianLJ** [comment]
Well i just saw the comments regarding strapi on Windows and installed WSL. 

Everything is working as expected now.

**Comment by Ashutosh421** [comment]
> Well i just saw the comments regarding strapi on Windows and installed WSL.
> 
> Everything is working as expected now.

WSL? I am having the same issue. How did you resolved this ?

**Comment by ChristianLJ** [comment]
> > Well i just saw the comments regarding strapi on Windows and installed WSL.
> > Everything is working as expected now.
> 
> WSL? I am having the same issue. How did you resolved this ?

Try following this guide which worked for me: https://docs.microsoft.com/en-us/windows/wsl/install-win10
