### ISSUE TITLE
Strapi Quickstart SQLite error

### ISSUE THREAD

**Issue by tpiros** [strapi/strapi#2952]
**Information**
- **Node.js version**: 10.15.0
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: SQLite version 3.24.0
- **Operating system**: Mac OS 10.14.3 

**What is the current behavior?**
SQLite throws errors after `strapi start`

**Steps to reproduce the problem**
I started with `strapi new [app-name]` and then selected `quickstart`. The installation went fine but at `strapi start` the following message appeared:

```
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
```

**What is the expected behavior?**
Not to see the error ;)

**Suggested solutions**
Just a thought: in https://github.com/strapi/strapi/blob/93cc29fe51cd42b65e5222dfe00c82e2be3f85f8/packages/strapi-hook-knex/lib/index.js#L105 it seems that the _.get() statement returns undefined.

This is how the automatically created database.json looks like:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "sqlite",
        "filename": ".tmp/data.db"
      },
      "options": {
        "useNullAsDefault": true
      }
    }
  }
}
```

So to access `useNullAsDefault` we should do `_.get(connection.options.default, 'useNullAsDefault');` I think.

**Comment by lauriejim** [comment]
Hello @tpiros !

Can you give me the full log please. From your `strapi new ...`

**Comment by tpiros** [comment]
sure @lauriejim - find it below.

```
⚡️ Start application:
$ strapi start

sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
(node:44604) UnhandledPromiseRejectionWarning: TypeError: Argument 0 must be a string
    at _bluebird.default (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:74:18)
    at Client_SQLite3.acquireRawConnection (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:73:12)
    at create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/client.js:282:21)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:5)
    at new Promise (<anonymous>)
    at callbackOrPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:275:32)
    at Pool._tryAcquireOrCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:212:12)
    at Pool.acquire (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:119:10)
    at _bluebird.default.try (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/client.js:333:50)
From previous event:
    at Client_SQLite3.acquireConnection (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/client.js:333:33)
    at Runner.ensureConnection (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/runner.js:224:24)
    at Runner.run (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/runner.js:33:41)
    at SchemaBuilder.Target.then (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/interface.js:23:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:44604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:44604) UnhandledPromiseRejectionWarning: TypeError: Argument 0 must be a string
    at _bluebird.default (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:74:18)
    at Client_SQLite3.acquireRawConnection (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:73:12)
    at create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/client.js:282:21)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:5)
    at new Promise (<anonymous>)
    at callbackOrPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:275:32)
    at Pool._tryAcquireOrCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:212:12)
    at delay.then (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:299:63)
(node:44604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:44604) UnhandledPromiseRejectionWarning: TypeError: Argument 0 must be a string
    at _bluebird.default (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:74:18)
    at Client_SQLite3.acquireRawConnection (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:73:12)
    at create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/client.js:282:21)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:5)
    at new Promise (<anonymous>)
    at callbackOrPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:275:32)
    at Pool._tryAcquireOrCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:212:12)
    at delay.then (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:299:63)
(node:44604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:44604) UnhandledPromiseRejectionWarning: TypeError: Argument 0 must be a string
    at _bluebird.default (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:74:18)
    at Client_SQLite3.acquireRawConnection (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:73:12)
    at create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/client.js:282:21)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:5)
    at new Promise (<anonymous>)
    at callbackOrPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:275:32)
    at Pool._tryAcquireOrCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:212:12)
    at delay.then (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:299:63)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
(node:44604) UnhandledPromiseRejectionWarning: TypeError: Argument 0 must be a string
    at _bluebird.default (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:74:18)
    at Client_SQLite3.acquireRawConnection (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/dialects/sqlite3/index.js:73:12)
    at create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/knex/lib/client.js:282:21)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:366:5)
    at new Promise (<anonymous>)
    at callbackOrPromise (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:275:32)
    at Pool._tryAcquireOrCreate (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:212:12)
    at delay.then (/Users/tpiros/Documents/development/strapi-test/my-app/node_modules/tarn/lib/Pool.js:299:63)
(node:44604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
[2019-03-11T18:19:00.007Z] debug ⛔️ Server wasn't able to start properly.
[2019-03-11T18:19:00.008Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load
```

**Comment by lauriejim** [comment]
You sent me your `strapi start` and not your `strapi new`

**Comment by tpiros** [comment]
my bad @lauriejim - updated ☝️

**Comment by lauriejim** [comment]
Arg looks weird!

I did a fresh install and all looks good.
Some one also have this issue ?

**Comment by tpiros** [comment]
OK, so based on your last comment I took another laptop where I have never used Strapi before and tried to replicate the error, but could not. Everything worked.

I came back to the "faulty" machine, and I found that the global npm packages were a bit borked:

```
$ npm list -g --depth=0
// list of packages and errors:
error: ENOENT: no such file or directory, stat '/Users/tpiros/.npm-global/lib/node_modules/strapi-admin
├──  error: ENOENT: no such file or directory, stat '/Users/tpiros/.npm-global/lib/node_modules/strapi-generate
├──  error: ENOENT: no such file or directory, stat '/Users/tpiros/.npm-global/lib/node_modules/strapi-generate-admin
```

So I deleted all global packages - and I mean I have actually `rm -rf .npm-global` ( 😉 ) then re-installed Strapi globally and things started to work.

I don't know what went wrong exactly but hopefully the above ☝️ will help people who run into something similar.

**Comment by simonschllng** [comment]
I get the same or very similar issue:
After doing

````
$ yarn create strapi-app strapi-test --quickstart
yarn create v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-strapi-app@3.0.1" with binaries:
      - create-strapi-app
[#########################################################################################] 168/168Creating a new Strapi application at /home/user/sandbox/strapi-test.

Creating a quickstart project.
Creating files.
Dependencies installed successfully.

Your application was created at /home/user/sandbox/strapi-test.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode.

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /home/user/sandbox/strapi-test
  yarn develop


> strapi-test@0.1.0 build /home/user/sandbox/strapi-test
> strapi build "--no-optimization"

Building your admin UI with development configuration ...

✔ Webpack
  Compiled successfully in 19.36s

Running your Strapi application.

> strapi-test@0.1.0 develop /home/user/sandbox/strapi-test
> strapi develop

[2020-06-02T09:37:57.213Z] info File created: /home/user/sandbox/strapi-test/extensions/users-permissions/config/jwt.js

 Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Tue Jun 02 2020 11:37:57 GMT+0200 (GMT+02:00)    │
│ Launched in        │ 3573 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 10478                                            │
│ Version            │ 3.0.1 (node v10.16.2)                            │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available                                                            

One more thing...
Create your first administrator 💻 by going to the administration panel at:

┌─────────────────────────────┐
│ http://localhost:1337/admin │
└─────────────────────────────┘


````

I was able to use the admin panel and create custom types etc. Then I closed the appilation and restarted:

````
$ yarn develop
yarn run v1.21.1
$ strapi develop
[2020-06-02T10:18:12.605Z] error The client `sqlite3` is not installed.
[2020-06-02T10:18:12.606Z] error You can install it with `$ npm install sqlite3 --save`.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````
