### ISSUE TITLE
Error creating new project with strapi with plugin installation

### ISSUE THREAD

**Issue by Ashutosh421** [strapi/strapi#2958]
Information:
- Node.js version: 10.13.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.24.1
- MongoDB: 4.0.6
- Operating System: Windows 

Error on plugin installations, for all the plugins

Error: Cannot find module 'C:\Users\Ashutosh'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

‼ An error occurred during content-type-builder plugin installation.
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'C:\Users\Ashutosh'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

How to reproduce?
1. strapi new (projectname)

**Comment by lauriejim** [comment]
Hello @Ashutosh421 

Can you uninstall strapi and try to install it again and create your project.

**Comment by Ashutosh421** [comment]
Hi Lauriejim.
        I have already tried that multiple times. Cleared npm cache, tried with yarn and npm as well. I think it is still not stable in windows. Please confirm?

**Comment by derrickmehaffy** [comment]
@Ashutosh421 https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

confirmed

**Comment by lauriejim** [comment]
We stabilised it and made improvement last few month.
I tried with the windows computer we have at the office and all works fine.

Did you use WSL ?

**Comment by Ashutosh421** [comment]
I tried it without WSL first. Without wsl it always shows plugin installation error. With wsl I'll have to further explore how exactly to do it as I have enabled WSL, installed ubuntu terminal through app store. Since the linux terminal does't find my npm. I'll further work on it and keep you posted. 
As of now I am sure it is having installation issues on windows.
