### ISSUE TITLE
Integer Enum with GraphQL Server Fails to start 

### ISSUE THREAD

**Issue by idrislab** [strapi/strapi#2960]
**Informations**
- **Node.js version**: v10.11.0 
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.24.1 
- **Database**: 10.3.13-MariaDB
- **Operating system**: macOS Mojave 10.14.1
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Using the admin UI with GraphQL installed i created a content type using the content type builder with an enum field containing integer values (ex: 1,2,3,4,5) when i save the server stops with an error.

When starting the server the following error is thrown:
```
(node:16933) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Expected Name, found Int "1"
    at syntaxError (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at expect (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:1445:32)
    at parseName (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:98:15)
    at parseEnumValueDefinition (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:1029:14)
    at many (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:1513:16)
    at parseEnumValuesDefinition (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:1017:50)
    at parseEnumTypeDefinition (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:1001:16)
    at parseTypeSystemDefinition (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:718:16)
    at parseDefinition (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:144:16)
    at many (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:1516:16)
    at parseDocument (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:115:18)
    at Object.parse (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/node_modules/graphql/language/parser.js:50:10)
    at Object.addPolymorphicUnionType (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/services/Types.js:154:8)
    at Object.generateSchema (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/services/Schema.js:179:15)
    at Function.initialize (/Users/luispittagros/Code/Hypnotic2018-backend/plugins/graphql/hooks/graphql/index.js:148:50)
    at /Users/luispittagros/.npm/lib/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/Users/luispittagros/.npm/lib/node_modules/strapi/lib/hooks/index.js:122:39)
    at /Users/luispittagros/.npm/lib/node_modules/strapi/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/Users/luispittagros/.npm/lib/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at Strapi.EventEmitter.emit (domain.js:442:20)
    at loadedModule.initialize.call.err (/Users/luispittagros/.npm/lib/node_modules/strapi/lib/hooks/index.js:32:12)
    at Function.initialize (/Users/luispittagros/Code/Hypnotic2018-backend/node_modules/strapi-hook-bookshelf/lib/index.js:1059:7)
(node:16933) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16933) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce the problem**
Using admin UI, install GraphQL and create a content type with an enum field containing integer values (ex: 1,2,3,4,5), server stops with an error.

**What is the expected behavior?**
Enum field should be created without errors.

After removing graphql the server starts without problems.

**Comment by lauriejim** [comment]
GraphQL require enum values to match [_A-Za-z][_0-9A-Za-z]

An in your case it start with a number. So you have to use `_` and the beginning of your enum values
