### ISSUE TITLE
Can not run GraphQL plugin on ru locale on windows

### ISSUE THREAD

**Issue by paulchertov** [strapi/strapi#3008]
**Informations**
- **Node.js version**: Node v10.15.3
- **NPM version**: npm 6.4.1 
- **Strapi version**:  Version: 3.0.0-alpha.24.1
- **Database**: MongoDb 4.0.6. 2008 R2Plus SSL (64 bit)
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**
After installing GraphQL plugin (installs successfully) i receive the following on "strapi start":
```
strapi start
(node:3352) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Cannot parse the unexpected character "\u0414".
    at syntaxError (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\error\syntaxError.js:24:10)
    at readToken (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\lexer.js:316:32)
    at Object.lookahead (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\lexer.js:62:43)
    at Object.advanceLexer [as advance] (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\lexer.js:52:33)
    at skipKeyword (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:1457:11)
    at expectKeyword (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:1471:8)
    at parseObjectTypeDefinition (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:807:3)
    at parseTypeSystemDefinition (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:709:16)
    at parseDefinition (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:152:12)
    at many (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:1516:16)
    at parseDocument (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:115:18)
    at Object.parse (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\node_modules\graphql\language\parser.js:50:10)
    at Object.addPolymorphicUnionType (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\services\Types.js:154:8)
    at Object.generateSchema (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\services\Schema.js:179:15)
    at Function.initialize (C:\Users\chert\Desktop\strapi\chpr\server\plugins\graphql\hooks\graphql\index.js:148:50)
    at C:\Users\chert\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:19:29
    at after (C:\Users\chert\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:122:39)
    at C:\Users\chert\AppData\Roaming\npm\node_modules\strapi\node_modules\lodash\lodash.js:9999:23
    at Strapi.once (C:\Users\chert\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:133:17)
    at Object.onceWrapper (events.js:277:13)
    at Strapi.emit (events.js:189:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at loadedModule.initialize.call.err (C:\Users\chert\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:32:12)
    at _.forEach (C:\Users\chert\Desktop\strapi\chpr\server\node_modules\strapi-hook-mongoose\lib\index.js:507:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-20T17:38:24.396Z] debug ⛔️ Server wasn't able to start properly.
[2019-03-20T17:38:24.402Z] error (hook:graphql) takes too long to load
(hook:graphql) takes too long to load

```

**Steps to reproduce the problem**
- create strapi project
- create test content type with cyryllic field descriptions (maybe not creates a problem)
- install graphql
- run strapi project

**What is the expected behavior?**
- app should run successfully

**Suggested solutions**
No idea. Looks like problem in cyryllic characters because \u0414 is Д letter

**Comment by lauriejim** [comment]
Hello! This issue is not related to Strapi but to GraphQL itself https://github.com/facebook/graphql/issues/256

So I suggest you to use more standard characters for your API attributes.
