### ISSUE TITLE
Not able to cook dishes </with Deliveroo Strapi Tutorial>

### ISSUE THREAD

**Issue by asharamseervi** [strapi/strapi#3059]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: v6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: mongodb
- **Operating system**: windows

**What is the current behavior?**
I was cooking dishes with "[Cooking a Deliveroo clone with Next.js (React), GraphQL, Strapiand Stripe - 🍔 Dishes list (part 3/7)](https://blog.strapi.io/strapi-next-dishes/)" but somehow dishes stayed raw, hence not able to completely cooked dishes only after adding salt (I mean, `yarn add express`).

**Steps to reproduce the problem**
After touching (creating) restaurants.js, and writing same code mentioned in gist on the tutorial. As mentioned to add express server as next step. Hence, completed adding express steps, produced errors on terminal. Surprisingly, [https://github.com/strapi/strapi-examples/blob/master/nextjs-react-strapi-deliveroo-clone-tutorial/frontend/server.js](https://github.com/strapi/strapi-examples/blob/master/nextjs-react-strapi-deliveroo-clone-tutorial/frontend/server.js) have same server.js file as mine, while @pierreburgy(CEO) able to succeed while I (user) not able to.

**What is the expected behavior?**
Obviously, I (user) should not get errors, it's totally unfair with me and our CEO. A user also commented there: https://blog.strapi.io/strapi-next-dishes/#comment-4350755000 but no one listened.

**Comment by derrickmehaffy** [comment]
Can you please clarify your issue? If this is about yarn it isn't supported. Also I'm not quite sure why you need express? O_o Strapi is koa based....

**Comment by asharamseervi** [comment]
Hey @derrickmehaffy, Thanks for inputs. If you follow above-mentioned tutorial which is published over Strapi Blog, you'll get to know, after adding `restaurants.js` at path `/frontend/pages/restaurants.js` code mentioned in [this gist](https://gist.github.com/ryanbelke/d32870974f49941a61c83904d053d94e#file-restaurants-js), the owner of mentioned gist is @ryanbelke.

It will produce an error in console, sometimes it will load dishes/restro, sometimes not. And, same issues faced by author @pierreburgy as well, that's why he himself mentioned/recommended for using express and provided code for the same. However, author may not got errors that time, but now things have changed.

Console errors are as follows: (After Express Server)
```
PS D:\Playground\strapi-deliveroo\frontend> yarn dev
yarn run v1.14.0
warning package.json: No license field$ node server.js

Compiled successfully!

Note that pages will be compiled when you first load them.Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.TypeError: Cannot read property 'pathname' of undefined
    at Object.makePublicRouterInstance (D:\Playground\strapi-deliveroo\frontend\.next\server\static\development\pages\restaurants.js:836:37)    at MyApp.getChildContext (D:\Playground\strapi-deliveroo\frontend\.next\server\static\development\pages\_app.js:1568:26)
    at processChild (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2957:29)    at resolve (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2795:5)
    at ReactDOMServerRenderer.render (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3175:22)
    at ReactDOMServerRenderer.read (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3134:29)
    at renderToStaticMarkup (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3634:27)
    at process (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-apollo\react-apollo.umd.js:118:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
'req.params.id = "5ca131031f16b4242cc46476"'
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
TypeError: Cannot read property 'pathname' of undefined
    at Object.makePublicRouterInstance (D:\Playground\strapi-deliveroo\frontend\.next\server\static\development\pages\restaurants.js:836:37)
    at MyApp.getChildContext (D:\Playground\strapi-deliveroo\frontend\.next\server\static\development\pages\_app.js:1568:26)
    at processChild (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2957:29)    at resolve (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2795:5)
    at ReactDOMServerRenderer.render (D:\Playground\strapi-deliveroo\frontend\node_modules\next-apollo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3175:22)
Compiled successfully!
Note that pages will be compiled when you first load them.
```

**Comment by derrickmehaffy** [comment]
Ah this isn't really the place to report bugs on example frontend code. For now I'll mark this as closed. Issues here should only be able verifiable bugs with strapi itself.
