### ISSUE TITLE
Cannot find module 'apollo-server-koa'

### ISSUE THREAD

**Issue by jdmb77** [strapi/strapi#3066]
Checked issues.

**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MongoDB
- **Operating system**: Win 10 Enterprise build 1709

**What is the current behavior?**
[2019-04-01T20:03:13.261Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-01T20:03:13.265Z] error Cannot find module 'apollo-server-koa'
{ Error: Cannot find module 'apollo-server-koa'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\hirschgd\Documents\BitbucketVHE\fast-de\backend\plugins\graphql\hooks\graphql\index.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.get [as load] (C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\lib\core\hooks.js:84:24)
    at C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\node_modules\lodash\lodash.js:2694:27
    at arrayEach (C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\node_modules\lodash\lodash.js:516:11)
    at baseClone (C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\node_modules\lodash\lodash.js:2691:7)
    at cloneDeep (C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\node_modules\lodash\lodash.js:11089:14)
    at config.hook.settings.Object.keys.reduce (C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\lib\core\configurations.js:310:39)
    at Array.reduce (<anonymous>)
    at Strapi.module.exports.app (C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\lib\core\configurations.js:308:54)
    at Strapi.load (C:\Users\hirschgd\AppData\Roaming\npm\node_modules\strapi\lib\Strapi.js:223:29) code: 'MODULE_NOT_FOUND' }

**Steps to reproduce the problem**
Install GraphQL via CLI or Admin UI. Fails on both.
I realize Strapi states Windows has issues, but I feel like this is something to do with the method in which the loading of the module is occurring. 

**What is the expected behavior?**
Enabling of GraphQL

**Suggested solutions**
Tried reinstalling. It is Windows so.....

**Comment by jdmb77** [comment]
This post resolved my issue on Windows 10. So HAPPY! https://github.com/strapi/strapi/issues/1612#issuecomment-419411724
Thanks so much for this @napop!
