### ISSUE TITLE
Error deploying with heroku

### ISSUE THREAD

**Issue by asotoglez** [strapi/strapi#3067]
**Informations**
- **Node.js version**: v10.8.0
- **NPM version**: 6.9.0
- **Strapi version**:3.0.0-alpha.25.2
- **Database**: Mongodb
- **Operating system**: WIN10

Why i get this error when deploying with heroku

2019-04-01T22:51:28.363751+00:00 app[api]: Deploy e86bb635 by user alesoto9113@gmail.com
2019-04-01T22:51:32.000000+00:00 app[api]: Build succeeded
2019-04-01T22:51:34.861130+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-04-01T22:51:34.861839+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-04-01T22:51:34.969568+00:00 heroku[web.1]: Process exited with status 137
2019-04-01T22:51:37.321048+00:00 heroku[web.1]: Starting process with command `npm start`
2019-04-01T22:51:39.476927+00:00 app[web.1]:
2019-04-01T22:51:39.476948+00:00 app[web.1]: > ftraining-api@0.1.0 start /app
2019-04-01T22:51:39.476950+00:00 app[web.1]: > node server.js
2019-04-01T22:51:39.476952+00:00 app[web.1]:
2019-04-01T22:51:41.833005+00:00 app[web.1]: [2019-04-01T22:51:41.831Z] warn (hook:strapi-mongoose) `strapi-hook-strapi-mongoose` is missing in your dependencies. Please run `npm install strapi-hook-strapi-mongoose`
2019-04-01T22:51:42.027374+00:00 app[web.1]: [2019-04-01T22:51:42.027Z] warn (hook:bookshelf) wasn't loaded due to missing key `enabled` in the configuration
2019-04-01T22:51:42.028286+00:00 app[web.1]: [2019-04-01T22:51:42.028Z] warn (hook:knex) wasn't loaded due to missing key `enabled` in the configuration
2019-04-01T22:51:42.256121+00:00 app[web.1]: error TypeError: strapi.models.core_store.forge is not a function
2019-04-01T22:51:42.256137+00:00 app[web.1]: at Object.get (/app/node_modules/strapi/lib/core/store.js:55:47)
2019-04-01T22:51:42.256139+00:00 app[web.1]: at module.exports (/app/plugins/content-manager/config/functions/bootstrap.js:312:42)
2019-04-01T22:51:42.256141+00:00 app[web.1]: at Promise (/app/node_modules/strapi/lib/Strapi.js:299:13)
2019-04-01T22:51:42.256143+00:00 app[web.1]: at new Promise (<anonymous>)
2019-04-01T22:51:42.256145+00:00 app[web.1]: at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:287:11)
2019-04-01T22:51:42.256147+00:00 app[web.1]: at Promise.all.Object.values.map.x (/app/node_modules/strapi/lib/Strapi.js:326:44)
2019-04-01T22:51:42.256149+00:00 app[web.1]: at Array.map (<anonymous>)
2019-04-01T22:51:42.256151+00:00 app[web.1]: at Strapi.bootstrap (/app/node_modules/strapi/lib/Strapi.js:326:35)
2019-04-01T22:51:42.256152+00:00 app[web.1]: at Strapi.start (/app/node_modules/strapi/lib/Strapi.js:109:18)
2019-04-01T22:51:42.257536+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
2019-04-01T22:51:42.257539+00:00 app[web.1]: at Object.get (/app/node_modules/strapi/lib/core/store.js:55:47)
2019-04-01T22:51:42.257540+00:00 app[web.1]: at module.exports (/app/plugins/documentation/config/functions/bootstrap.js:18:46)
2019-04-01T22:51:42.257542+00:00 app[web.1]: at Promise (/app/node_modules/strapi/lib/Strapi.js:299:13)
2019-04-01T22:51:42.257544+00:00 app[web.1]: at new Promise (<anonymous>)
2019-04-01T22:51:42.257546+00:00 app[web.1]: at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:287:11)
2019-04-01T22:51:42.257547+00:00 app[web.1]: at Promise.all.Object.values.map.x (/app/node_modules/strapi/lib/Strapi.js:326:44)
2019-04-01T22:51:42.257549+00:00 app[web.1]: at Array.map (<anonymous>)
2019-04-01T22:51:42.257551+00:00 app[web.1]: at Strapi.bootstrap (/app/node_modules/strapi/lib/Strapi.js:326:35)
2019-04-01T22:51:42.257552+00:00 app[web.1]: at Strapi.start (/app/node_modules/strapi/lib/Strapi.js:109:18)
2019-04-01T22:51:42.257646+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
2019-04-01T22:51:42.257733+00:00 app[web.1]: (node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-04-01T22:51:42.257810+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
2019-04-01T22:51:42.257812+00:00 app[web.1]: at Object.get (/app/node_modules/strapi/lib/core/store.js:55:47)
2019-04-01T22:51:42.257814+00:00 app[web.1]: at module.exports (/app/plugins/settings-manager/config/functions/bootstrap.js:17:26)
2019-04-01T22:51:42.257816+00:00 app[web.1]: at Promise (/app/node_modules/strapi/lib/Strapi.js:299:13)
2019-04-01T22:51:42.257817+00:00 app[web.1]: at new Promise (<anonymous>)
2019-04-01T22:51:42.257819+00:00 app[web.1]: at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:287:11)
2019-04-01T22:51:42.257821+00:00 app[web.1]: at Promise.all.Object.values.map.x (/app/node_modules/strapi/lib/Strapi.js:326:44)
2019-04-01T22:51:42.257823+00:00 app[web.1]: at Array.map (<anonymous>)
2019-04-01T22:51:42.257824+00:00 app[web.1]: at Strapi.bootstrap (/app/node_modules/strapi/lib/Strapi.js:326:35)
2019-04-01T22:51:42.257826+00:00 app[web.1]: at Strapi.start (/app/node_modules/strapi/lib/Strapi.js:109:18)
2019-04-01T22:51:42.257898+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
2019-04-01T22:51:42.257966+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
2019-04-01T22:51:42.257968+00:00 app[web.1]: at Object.get (/app/node_modules/strapi/lib/core/store.js:55:47)
2019-04-01T22:51:42.257970+00:00 app[web.1]: at module.exports (/app/plugins/users-permissions/config/functions/bootstrap.js:96:45)
2019-04-01T22:51:42.257972+00:00 app[web.1]: at Promise (/app/node_modules/strapi/lib/Strapi.js:299:13)
2019-04-01T22:51:42.257974+00:00 app[web.1]: at new Promise (<anonymous>)
2019-04-01T22:51:42.257975+00:00 app[web.1]: at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:287:11)
2019-04-01T22:51:42.257977+00:00 app[web.1]: at Promise.all.Object.values.map.x (/app/node_modules/strapi/lib/Strapi.js:326:44)
2019-04-01T22:51:42.257979+00:00 app[web.1]: at Array.map (<anonymous>)
2019-04-01T22:51:42.257980+00:00 app[web.1]: at Strapi.bootstrap (/app/node_modules/strapi/lib/Strapi.js:326:35)
2019-04-01T22:51:42.257982+00:00 app[web.1]: at Strapi.start (/app/node_modules/strapi/lib/Strapi.js:109:18)
2019-04-01T22:51:42.258052+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
2019-04-01T22:51:42.272396+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
2019-04-01T22:51:42.272403+00:00 app[web.1]: at fs.readdir (/app/plugins/email/config/functions/bootstrap.js:68:40)
2019-04-01T22:51:42.272482+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
2019-04-01T22:51:42.273785+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
2019-04-01T22:51:42.273788+00:00 app[web.1]: at fs.readdir (/app/plugins/upload/config/functions/bootstrap.js:70:40)
2019-04-01T22:51:42.273868+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
2019-04-01T22:51:45.751765+00:00 app[web.1]: [2019-04-01T22:51:45.751Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).2019-04-01T22:51:45.751949+00:00 app[web.1]: [2019-04-01T22:51:45.751Z] warn Perhaps you forgot to call it?
2019-04-01T22:51:45.753377+00:00 app[web.1]: [2019-04-01T22:51:45.753Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).2019-04-01T22:51:45.753501+00:00 app[web.1]: [2019-04-01T22:51:45.753Z] warn Perhaps you forgot to call it?
2019-04-01T22:51:45.753643+00:00 app[web.1]: [2019-04-01T22:51:45.753Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).2019-04-01T22:51:45.753755+00:00 app[web.1]: [2019-04-01T22:51:45.753Z] warn Perhaps you forgot to call it?
2019-04-01T22:51:45.753892+00:00 app[web.1]: [2019-04-01T22:51:45.753Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).2019-04-01T22:51:45.754003+00:00 app[web.1]: [2019-04-01T22:51:45.753Z] warn Perhaps you forgot to call it?
2019-04-01T22:51:45.754143+00:00 app[web.1]: [2019-04-01T22:51:45.754Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).2019-04-01T22:51:45.754251+00:00 app[web.1]: [2019-04-01T22:51:45.754Z] warn Perhaps you forgot to call it?
2019-04-01T22:51:46.643359+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-04-01T22:51:46.643528+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-04-01T22:51:46.813222+00:00 heroku[web.1]: Process exited with status 137
2019-04-01T22:52:37.479828+00:00 heroku[web.1]: State changed from starting to crashed
2019-04-01T22:52:37.369212+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-04-01T22:52:37.369383+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-04-01T22:52:37.463322+00:00 heroku[web.1]: Process exited with status 137
2019-04-01T22:52:39.195634+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apple-custard-85705.herokuapp.com request_id=2b163e6f-0604-4bf5-a6ac-34304e550f7a fwd="201.214.248.205" dyno= connect= service= status=503 bytes= protocol=https
2019-04-01T22:53:00.754703+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=apple-custard-85705.herokuapp.com request_id=a5b22936-8249-4154-9242-d99e1446b53f fwd="201.214.248.205" dyno= connect= service= status=503 bytes= protocol=https
2019-04-01T22:53:01.374356+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=apple-custard-85705.herokuapp.com request_id=d85eeb55-f3cd-445a-a246-e554b36ac8bb fwd="201.214.248.205" dyno= connect= service= status=503 bytes= protocol=https

**Comment by nikosolihin** [comment]
`npm i strapi-hook-strapi-mongoose`, commit and repush.

**Comment by alxnkt** [comment]
Looks like you hardcoded a port. Show your package.json. Port definition should look like ```process.env.PORT || 1337``` 
Heroku assings random port to your app, so you must refer to environment variable $PORT, that is set by heroku.

**Comment by derrickmehaffy** [comment]
> `npm i strapi-hook-strapi-mongoose`, commit and repush.

It should be `strapi-hook-mongoose` you have an extra `strapi` in there

**Comment by asotoglez** [comment]
> `npm i strapi-hook-strapi-mongoose`, commit and repush.

it looks like that package doesn't exist.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/strapi-hook-strapi-mongoose - Not found
npm ERR! 404
npm ERR! 404  'strapi-hook-strapi-mongoose@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ale\AppData\Roaming\npm-cache\_logs\2019-04-02T13_48_32_077Z-debug.log

**Comment by asotoglez** [comment]
> Looks like you hardcoded a port. Show your package.json. Port definition should look like `process.env.PORT || 1337`
> Heroku assings random port to your app, so you must refer to environment variable $PORT, that is set by heroku.

This my package.json

`{
  "name": "ftraining-api",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application.",
  "main": "./server.js",
  "scripts": {
    "setup": "cd admin && npm run setup",
    "start": "node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-react": "^7.7.0"
  },
  "dependencies": {
    "knex": "latest",
    "lodash": "^4.17.5",
    "sqlite3": "latest",
    "strapi": "3.0.0-alpha.25.2",
    "strapi-hook-bookshelf": "3.0.0-alpha.25.2",
    "strapi-hook-knex": "3.0.0-alpha.25.2"
  },
  "author": {
    "name": "A Strapi developer",
    "email": "",
    "url": ""
  },
  "maintainers": [
    {
      "name": "A Strapi developer",
      "email": "",
      "url": ""
    }
  ],
  "strapi": {
    "packageManager": "npm",
    "uuid": "5f953470-8b44-4ad2-9fec-59b9d9ac6510"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT"
}
`

This my server.json under config/production
`{
  "host": "localhost",
  "port": "${process.env.PORT || 1337}",
  "production": true,
  "proxy": {
    "enabled": false
  },
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
`

**Comment by nikosolihin** [comment]
> it looks like that package doesn't exist.
> npm ERR! code E404

Yea, I took that from your initial post. Like @derrickmehaffy said, it should be `strapi-hook-mongoose`. Maybe there's somethign in the fact that heroku complained about wrong package name?

**Comment by asotoglez** [comment]
I just tried that and it keeps saying the same thing.
![image](https://user-images.githubusercontent.com/24250413/55413542-e41e4380-553f-11e9-9bba-16e041c1243f.png)

**Comment by lauriejim** [comment]
Why did you have `strapi-hook-bookshelf` and `strapi-hook-knex` installed if you are using mongo ?

**Comment by asotoglez** [comment]
> Why did you have `strapi-hook-bookshelf` and `strapi-hook-knex` installed if you are using mongo ?

That's for dev enviroment , Could that be the problem?

**Comment by lauriejim** [comment]
Hum yap, can you duplicate your dev database config in your production environment.
