### ISSUE TITLE
Syntax Error: Cannot parse the unexpected character "\u00E3"

### ISSUE THREAD

**Issue by MatheusRV** [strapi/strapi#3078]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.25.2
- **Database**: Mongo
- **Operating system**: WSL

**What is the current behavior?**
Syntax Error: Cannot parse the unexpected character "\u00E3"

```
$ strapi start
(node:1755) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Cannot parse the unexpected character "\u00E3".
    at syntaxError (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at readToken (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/lexer.js:314:32)
    at Object.lookahead (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/lexer.js:62:43)
    at Object.advanceLexer [as advance] (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/lexer.js:52:33)
    at expectToken (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:1429:11)
    at parseName (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:98:15)
    at parseEnumValueDefinition (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:1031:14)
    at many (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:1524:16)
    at parseEnumValuesDefinition (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:1019:50)
    at parseEnumTypeDefinition (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:1003:16)
    at parseTypeSystemDefinition (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:720:16)
    at parseDefinition (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:144:16)
    at many (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:1524:16)
    at parseDocument (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:115:18)
    at Object.parse (/mnt/c/Dev/viacarro-backend/plugins/graphql/node_modules/graphql/language/parser.js:50:10)
    at Object.addPolymorphicUnionType (/mnt/c/Dev/viacarro-backend/plugins/graphql/services/Types.js:155:8)
    at Object.generateSchema (/mnt/c/Dev/viacarro-backend/plugins/graphql/services/Schema.js:179:15)
    at Function.initialize (/mnt/c/Dev/viacarro-backend/plugins/graphql/hooks/graphql/index.js:148:50)
    at /home/tanenbaum/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/home/tanenbaum/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:122:39)
    at /home/tanenbaum/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/home/tanenbaum/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:277:13)
    at Strapi.emit (events.js:189:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at loadedModule.initialize.call.err (/home/tanenbaum/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:32:12)
    at Function.initialize (/mnt/c/Dev/viacarro-backend/node_modules/strapi-hook-bookshelf/lib/index.js:1064:7)
(node:1755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-04-02T17:55:47.720Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-02T17:55:47.732Z] error (hook:graphql) takes too long to load
(hook:graphql) takes too long to load
```

**Steps to reproduce the problem**
```
npm install strapi@alpha -g
Install GraphQL on Marketplace using Web UI.
strapi start
```

**What is the expected behavior?**
Server Run.

**Comment by MatheusRV** [comment]
Looks related with https://github.com/strapi/strapi/issues/1698
