### ISSUE TITLE
Strapi Unable to start Mac OS

### ISSUE THREAD

**Issue by pawankorotane** [strapi/strapi#3095]
Hi Guys, 

I followed the get started guide but when I start the server I am getting this error:

2019-04-06T23:21:57.931Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-06T23:21:57.932Z] error URL is not defined
ReferenceError: URL is not defined
    at Strapi.module.exports.app (/Users/*****/.nvm/versions/node/v8.9.4/lib/node_modules/strapi/lib/core/configurations.js:333:10)
    at Strapi.load (/Users/*****/.nvm/versions/node/v8.9.4/lib/node_modules/strapi/lib/Strapi.js:223:29)
    at <anonymous>

**Comment by Throttle** [comment]
@pawankorotane you need to update Node version.
Required Node version is > v10

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#url-not-defined

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

Thank you.

> This is a templated message

**Comment by gwenf** [comment]
I updated the latest node version using nvm (version 12.3.1) and then ran `npm i` and then installed sqlite (`npm install sqlite3`). That fixed the issue for me.
