### ISSUE TITLE
strapi.utils.models.convertParams should support array format generated by strapi-javascript-sdk

### ISSUE THREAD

**Issue by voidlps** [strapi/strapi#3109]
**Informations**
- **Node.js version**: Node v10.15.3 
- **NPM version**:  npm 6.4.1 
- **Strapi version**:  3.0.0-alpha.25.2
- **Database**: postgresql v9.6.5
- **Operating system**: ubuntu 16.04, kernel 4.4.0-145-generic
- **(Optional) Link to your Project**: 

**What is the current behavior?**
using strapi-javascript-sdk, passing array as author_in value to apply whereIn  filter, like
```
{
  author_in: [1,3]
}
```
query string will become author_in[0]=1&author_in[1]=3, which leads to error on backend
log shows
```
TypeError: The operator "undefined" is not permitted
    at Formatter.operator (/home/strapi-cms/node_modules/knex/lib/formatter.js:179:13)
    at QueryCompiler_PG.whereBasic (/home/strapi-cms/node_modules/knex/lib/query/compiler.js:567:100)
    at QueryCompiler_PG.where (/home/strapi-cms/node_modules/knex/lib/query/compiler.js:350:34)
    at components.map.component (/home/strapi-cms/node_modules/knex/lib/query/compiler.js:96:67)
    at Array.map (<anonymous>)
    at QueryCompiler_PG.select (/home/strapi-cms/node_modules/knex/lib/query/compiler.js:96:35)
    at QueryCompiler_PG.toSQL (/home/strapi-cms/node_modules/knex/lib/query/compiler.js:50:29)
    at Builder.toSQL (/home/strapi-cms/node_modules/knex/lib/query/builder.js:72:44)
    at /home/strapi-cms/node_modules/knex/lib/runner.js:37:34
    at tryCatcher (/home/strapi-cms/node_modules/bluebird/js/release/util.js:16:23)
    at /home/strapi-cms/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/strapi-cms/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/strapi-cms/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/strapi-cms/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/strapi-cms/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/strapi-cms/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/strapi-cms/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/strapi-cms/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/strapi-cms/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-04-10T07:43:05.498Z] debug GET /post?author_in[]=1&author_in[]=3 (10 ms)
```

**Steps to reproduce the problem**
1. create a content type Post, with field author,title and content
2. add some post
3. use strapi-javascript-sdk to call
```
let authors = [1,3]
let results = await this.strapi.getEntries('posts', {
                    author_in: authors
                });
```

**What is the expected behavior?**
can use array in strapi-javascript-sdk to do whereIn filter directly

**Suggested solutions**
current workaround is in the service, to trim off [n] of params before pass to covertParams like this:
```
const ARRAY_PARAMETERS = /\[[0-9]+\]$/;

function fixParams(params) {
    return Object.entries(params).reduce((a,c) => {
        if (ARRAY_PARAMETERS.test(c[0])) {
            let key = c[0].replace(ARRAY_PARAMETERS,'');
            let array = a[key] || [];
            array.push(c[1]);
            a[key] = array;
        } else {
            a[c[0]] = c[1];
        }
        return a;
    },{});
}

fetchAll: (params) => {
     // Convert `params` object to filters compatible with Bookshelf.
    const filters = strapi.utils.models.convertParams('post', fixParams(params));
...
```

**Comment by voidlps** [comment]
with some more test, I found that the query string generated by strapi-javascript-sdk is in fact
author_in[0]=1&author_in[1]=3

in this case, the correct workaround should be applying this function to params:
```
const ARRAY_PARAMETERS = /\[[0-9]+\]$/;

function fixParams(params) {
    return Object.entries(params).reduce((a,c) => {
        if (ARRAY_PARAMETERS.test(c[0])) {
            let key = c[0].replace(ARRAY_PARAMETERS,'');
            let array = a[key] || [];
            array.push(c[1]);
            a[key] = array;
        } else {
            a[c[0]] = c[1];
        }
        return a;
    },{});
```

**Comment by alexandrebodin** [comment]
@soupette We should fix this in the sdk.

Koa already supports `?param_in=1&param_in=2` => `param_in = [1,2]` in the backend

**Comment by soupette** [comment]
Since it's not related to Strapi itself I'm closing this issue
