### ISSUE TITLE
Getting exec: internal error 

### ISSUE THREAD

**Issue by thedevxen** [strapi/strapi#3115]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: Default
- **Operating system**: Ubuntu 18.04.1 LTS
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I am trying to create a new project with Strapi using the following command:
`$ strapi new project-name` but it's ending up with the following error:

```🚀 Starting to create your Strapi application.

? Choose your installation type Quickstart (recommended)

✅ Connected to the database

exec: internal error
exec: internal error
🏗  Application generation:
✔ Copy dashboard
exec: internal error
exec: internal error
exec: internal error
exec: internal error
/usr/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/after.js:103
      if (data.stderr && data.code !== 0) {
               ^

TypeError: Cannot read property 'stderr' of null
    at module.exports (/usr/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/after.js:103:16)
    at async.each.err (/usr/lib/node_modules/strapi/node_modules/strapi-generate/lib/generate.js:150:16)
    at /usr/lib/node_modules/strapi/node_modules/async/dist/async.js:473:16
    at Function.iteratorCallback (/usr/lib/node_modules/strapi/node_modules/async/dist/async.js:1064:13)
    at Function.<anonymous> (/usr/lib/node_modules/strapi/node_modules/async/dist/async.js:969:16)
    at Function.success (/usr/lib/node_modules/strapi/node_modules/switchback/lib/normalize.js:33:31)
    at Function._switch (/usr/lib/node_modules/strapi/node_modules/switchback/lib/factory.js:58:28)
    at Function.success (/usr/lib/node_modules/strapi/node_modules/switchback/lib/normalize.js:33:31)
    at Function._switch (/usr/lib/node_modules/strapi/node_modules/switchback/lib/factory.js:58:28)
    at Function.success (/usr/lib/node_modules/strapi/node_modules/switchback/lib/normalize.js:33:31)
```

**Steps to reproduce the problem**

It was my first installation on my server and it just went wrong. But I am doing the exact steps on my local computer and it works fine.

**What is the expected behavior?**

**Suggested solutions**

**Comment by soupette** [comment]
@TheDevXen can you please follow the issue template?

I'm closing this issue, until it matches the template

**Comment by TheDevXen** [comment]
> @TheDevXen can you please follow the issue template?
> 
> I'm closing this issue, until it matches the template

Please check now

**Comment by derrickmehaffy** [comment]
@TheDevXen I've tweaked your issue, in the future please ensure you follow the template, also your missing the database type.

Can you also please include any possible steps to reproduce the issue.

**Comment by TheDevXen** [comment]
> @TheDevXen I've tweaked your issue, in the future please ensure you follow the template, also your missing the database type.
> 
> Can you also please include any possible steps to reproduce the issue.

Thanks! I try to use the given template from now onwards. I don't know what is my database, I am just trying to init my first project on database and this error occured

**Comment by lauriejim** [comment]
I just tried with a new instance and it works well.
Make sure you have write access on your instance.

**Comment by derrickmehaffy** [comment]
@thedevxen in that case then you are using SQLite. As @lauriejim said, make sure you have write access to the SQLite database file.

**Comment by derrickmehaffy** [comment]
Marking as closed as this issue can't be reproduced without more information.
