### ISSUE TITLE
Problem with creating new content type

### ISSUE THREAD

**Issue by jacobakiro** [strapi/strapi#3125]
**Informations**
- **Node.js version**: 11.14.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: 
- **Operating system**: Raspbian (Debian)
- **(Optional) Link to your Project**: 

**What is the current behavior?**
After adding new field of type enum into content type strapi is not starting anymore. Field had 3 values in it separated by commas and default advanced options. Error I get after start is below:

(node:28341) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
    at Client_SQLite3._query (/home/pi/cms/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/home/pi/cms/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/home/pi/cms/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /home/pi/cms/node_modules/knex/lib/runner.js:47:21
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Runner.run (/home/pi/cms/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/home/pi/cms/node_modules/knex/lib/interface.js:23:43)
(node:28341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-04-13T17:36:28.795Z] debug ⛔️ Server wasn't able to start properly.

**Steps to reproduce the problem**
1. Create new content type.
2. Add new field of type string and save the content type.
3. Add another field of type enum, add some values separated by commas and save again.

**What is the expected behavior?**
Content type should update and strapi restart,

**Suggested solutions**
Not sure, I am completely new to strapi, this was my first content type.

**Comment by jacobakiro** [comment]
I found a solution here, so I'm closing this issue. https://github.com/strapi/strapi/issues/2941
