### ISSUE TITLE
orm.load(...).buildQuery is not a function

### ISSUE THREAD

**Issue by mimamuh** [strapi/strapi#3142]
**Informations**
- **Node.js version**: 11.1.0
- **Strapi version**: 3.0.0-alpha.26
- **Database**: mongodb
- **Operating system**: macOS

**What is the current behavior?**
Tried to start strapi after upgrade from `3.0.0-alpha.25.2` to `3.0.0-alpha.26` following the migration guide and get the following error on start:
```
(node:17) UnhandledPromiseRejectionWarning: TypeError: orm.load(...).buildQuery is not a function
    at buildQuery (/usr/src/api/content/plugins/users-permissions/node_modules/strapi-utils/lib/buildQuery.js:116:21)
    at Function.count (/usr/src/api/content/plugins/users-permissions/config/queries/mongoose.js:21:12)
    at Object.initialize (/usr/src/api/content/plugins/users-permissions/services/UsersPermissions.js:339:67)
    at module.exports (/usr/src/api/content/plugins/users-permissions/config/functions/bootstrap.js:167:65)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by alexandrebodin** [comment]
Hi @mimamuh,

Could you check the version of the `strapi-hook-mongoose` dependency ? it should be alpha.26 too

**Comment by lauriejim** [comment]
Did you follow the migration guide here https://strapi.io/documentation/3.x.x/migration-guide/migration-guide-alpha.25-to-alpha.26.html

**Comment by mimamuh** [comment]
@alexandrebodin: Aaah, yes, that was my issue.  Thx for the help!!

**Comment by seshukumar291** [comment]
> Hi @mimamuh,
> 
> Could you check the version of the `strapi-hook-mongoose` dependency ? it should be alpha.26 too

This worked for me
