### ISSUE TITLE
MySQL is dumping .returning() errors to console

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3153]
**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: v26
- **Database**: MariaDB 10.3
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

At random during startup or during queries Strapi is dumping the following to the terminal:

`.returning() is not supported by mysql and will not have any effect.`

**Steps to reproduce the problem**

Create a new application with MySQL

**What is the expected behavior?**

Shouldn't be spamming the console with an error that doesn't matter

**Suggested solutions**

similar to the SQLite, this needs to be disabled: https://github.com/strapi/strapi/blob/b0f2b9b85700348d36c986a29020b62a44e1a7d2/packages/strapi-hook-knex/lib/index.js#L163-L167

**Comment by derrickmehaffy** [comment]
@lauriejim I think is is more of a bug than an enhancement

**Comment by michancio** [comment]
I have the same issue. I've tried install previous version of knex but didn't help.
**DB**: MySQL 8.0.15
**OS**: macOS Mojave
**NPM**: 6.7
**Node**: v10
**STRAPI**: v26

My core dependencies:

  "dependencies": {
    "axios": "^0.18.0",
    "check": "^1.0.0",
    "csvtojson": "^2.0.8",
    "knex": "^0.16.5",
    "lodash": "^4.17.5",
    "mysql": "2.16.0",
    "node-fetch": "^2.3.0",
    "pino-multi-stream": "^4.0.2",
    "strapi": "^3.0.0-alpha.26.1",
    "strapi-email-nodemailer-fork": "^1.0.10",
    "strapi-hook-bookshelf": "3.0.0-alpha.26.1",
    "strapi-hook-knex": "3.0.0-alpha.26.1"

**Comment by Fakkio** [comment]
Same error here but worst:
I'm trying to create new project with MySQL DB, after `strapi new strapi-test`, configuring the DB connection and `strapi start`, i get a long serie of
`.returning() is not supported by mysql and will not have any effect.`
and then a knex timeout.

strapi v3.0.0-alpha.26.2
node v10.15.3

Whole CLI output is provided below:
```
>strapi start
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
.returning() is not supported by mysql and will not have any effect.
(node:21740) UnhandledPromiseRejectionWarning: TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at _bluebird.default.try.tap.catch (D:\Documenti\www\strapi-test\node_modules\knex\lib\client.js:336:13)
From previous event:
    at Client_MySQL.acquireConnection (D:\Documenti\www\strapi-test\node_modules\knex\lib\client.js:335:13)
    at Runner.ensureConnection (D:\Documenti\www\strapi-test\node_modules\knex\lib\runner.js:226:24)
    at Runner.run (D:\Documenti\www\strapi-test\node_modules\knex\lib\runner.js:33:41)
    at Builder.Target.then (D:\Documenti\www\strapi-test\node_modules\knex\lib\interface.js:23:43)
    at Child.<anonymous> (D:\Documenti\www\strapi-test\node_modules\bookshelf\lib\model.js:1118:36)
From previous event:
    at Child.<anonymous> (D:\Documenti\www\strapi-test\node_modules\bookshelf\lib\model.js:1117:125)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Child.<anonymous> (D:\Documenti\www\strapi-test\node_modules\bookshelf\lib\model.js:1000:8)
From previous event:
    at Function.addPermission (D:\Documenti\www\strapi-test\plugins\users-permissions\config\queries\bookshelf.js:115:31)
    at Promise.all.toAdd.map.map.action (D:\Documenti\www\strapi-test\plugins\users-permissions\services\UsersPermissions.js:293:18)
    at Array.map (<anonymous>)
    at Promise.all.roles.map.role (D:\Documenti\www\strapi-test\plugins\users-permissions\services\UsersPermissions.js:292:16)
    at Array.map (<anonymous>)
    at Object.updatePermissions (D:\Documenti\www\strapi-test\plugins\users-permissions\services\UsersPermissions.js:288:15)
(node:21740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 177)
(node:21740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-05-04T09:31:50.546Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-05-04T09:31:50.548Z] warn Perhaps you forgot to call it?
```

**Comment by FerJSsilva** [comment]
Up =^

**Comment by derrickmehaffy** [comment]
No longer an issue on beta.7
