### ISSUE TITLE
Cannot read property 'services' of undefined

### ISSUE THREAD

**Issue by MatheusRV** [strapi/strapi#3164]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: alpha26 fresh instalation
- **Database**: MySQL 5.7
- **Operating system**: Ubuntu 18.04 bionic [Ubuntu on Windows 10]

**What is the current behavior?**
```
$ strapi start
[2019-04-20T18:30:33.047Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-20T18:30:33.051Z] error Cannot read property 'services' of undefined
TypeError: Cannot read property 'services' of undefined
    at Object.buildShadowCRUD (/mnt/d/Cloud/GitHub/guiacasi-api/plugins/graphql/services/Resolvers.js:25:55)
    at Object.generateSchema (/mnt/d/Cloud/GitHub/guiacasi-api/plugins/graphql/services/Schema.js:141:36)
    at Function.initialize (/mnt/d/Cloud/GitHub/guiacasi-api/plugins/graphql/hooks/graphql/index.js:145:78)
    at /home/turing/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:52:31
    at after (/home/turing/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:153:39)
    at /home/turing/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/home/turing/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:164:17)
    at Object.onceWrapper (events.js:277:13)
    at Strapi.emit (events.js:189:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at onFinish (/home/turing/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/lib/hooks/index.js:44:12)
    at Promise.all.then (/mnt/d/Cloud/GitHub/guiacasi-api/node_modules/strapi-hook-bookshelf/lib/index.js:1197:55)
```

**What is the expected behavior?**
Starpi open browser.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

**Comment by MatheusRV** [comment]
@lauriejim I'm using issue template.. BTW I update.

**Comment by lauriejim** [comment]
I need more context, you just say `Comand strapi start on terminal.`
I don't know what are previous action you did.

- Did you create a content type then you tried to restart your server
- You did a manual update of your config/controllers/service and then you get this issue
- You just killed the server and try to restart

There is many case possible. I need more detail, I can't help you if I haven't the context of your issue.
