### ISSUE TITLE
v26 Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by q-jason** [strapi/strapi#3167]
node 10.15.1

npm 6.4.1

strapi 3.0.0-alpha.26

**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
```bash
{ Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (F:\node\node_modules\strapi-hook-mongoose\lib\index.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.get [as load] (F:\node\node_modules\strapi\lib\core\hooks.js:84:24)
    at F:\node\node_modules\strapi\node_modules\lodash\lodash.js:2694:27
    at arrayEach (F:\node\node_modules\strapi\node_modules\lodash\lodash.js:516:11)
    at baseClone (F:\node\node_modules\strapi\node_modules\lodash\lodash.js:2691:7)
    at cloneDeep (F:\node\node_modules\strapi\node_modules\lodash\lodash.js:11089:14)
    at config.hook.settings.Object.keys.reduce (F:\node\node_modules\strapi\lib\core\configurations.js:310:39)
    at Array.reduce (<anonymous>)
    at Strapi.module.exports.app (F:\node\node_modules\strapi\lib\core\configurations.js:308:54)
    at Strapi.load (F:\node\node_modules\strapi\lib\Strapi.js:223:29)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }

```

**Steps to reproduce the problem**
```bash
npm i -g strapi@3.0.0-alpha.26
...
strapi new ./
...
error => Error: Cannot find module 'lodash'
```

**What is the expected behavior?**

**Suggested solutions**

**Comment by q-jason** [comment]
sorry
my English not well
I know my problem
