### ISSUE TITLE
Misleading enumeration placeholder

### ISSUE THREAD

**Issue by sseypt** [strapi/strapi#3177]
Hello and thank you for this wonderful tool.
I'd just like to make one small comment.

**Informations**
- **Node.js version**: any
- **NPM version**: any
- **Strapi version**: any
- **Database**: any
- **Operating system**: any

**What is the current behavior?**

There is a mismatch between `enumeration.placeholder`, which indicates a comma separation and the `enumeration.rules` which specify the line feeds.

https://github.com/strapi/strapi/blob/6ec2b17e80e567728b161c9104cf895fd5204d74/packages/strapi-plugin-content-type-builder/admin/src/translations/en.json#L45

and 

https://github.com/strapi/strapi/blob/6ec2b17e80e567728b161c9104cf895fd5204d74/packages/strapi-plugin-content-type-builder/admin/src/translations/en.json#L46

**Steps to reproduce the problem**

Edit an enumeration field.

**What is the expected behavior?**

```
Ex: morning
noon
evening
```

**Suggested solutions**

```
"form.attribute.item.enumeration.placeholder": "Ex: morning
noon
evening"
```

Cheers,
Steve

**Comment by derrickmehaffy** [comment]
@sseypt Feel free to submit a Pull Request to fix it :smiley:

**Comment by sseypt** [comment]
Hi @derrickmehaffy 

Veni, vidi, non vici 💥

I setup `strapi` for local builds using `boot2docker` and the `node` image used in [strapi-docker](https://github.com/strapi/strapi-docker).

I did not use shared folders to avoid filesystem problem with the windows host.

I installed missing packages required for `Linking strapi-helper-plugin...`

..and than failed 🙈 

**my setup**
```bash
# windows 10 // cmd
docker-machine create --driver virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.09.5/boot2docker.iso --virtualbox-hostonly-cidr 192.168.13.37/24 --virtualbox-cpu-count 2 --virtualbox-memory 2048 --virtualbox-disk-size 51200 node
docker-machine ssh node
docker run --tty -d -p 1337:1337 -p 4000:4000 --name strapi node:11.1.0-alpine sh
docker exec strapi sh -c "apk update && apk upgrade && apk add --no-cache bash git openssh" 
docker exec -it strapi bash
# following https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
git clone https://github.com/sseypt/strapi.git
cd strapi

npm run setup:build
# FIX >>> configure: error: no acceptable C compiler found in $PATH
apk add --update alpine-sdk
# FIX >>> /bin/sh: autoreconf: not found
apk add --update autoconf
# FIX >>> Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
apk add --update automake

npm run setup:build
```

**result**
```bash
bash-4.4# npm run setup:build

> @3.0.0-alpha.26.1 setup:build /strapi
> npm run setup --build


> @3.0.0-alpha.26.1 setup /strapi
> npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.26.1 clean:all /strapi
> npm run removesymlinkdependencies && npx rimraf package-lock.json && npx rimraf packages/*/package-lock.json && npx rimraf packages/*/node_modules


> @3.0.0-alpha.26.1 removesymlinkdependencies /strapi
> node ./scripts/removeSymlinkDependencies.js

npx: installed 12 in 4.596s
npx: installed 12 in 3.669s
npx: installed 12 in 3.822s
npm notice created a lockfile as package-lock.json. You should commit this file.
+ strapi-lint@3.0.0-alpha.26.1
added 52 packages from 61 contributors and audited 137 packages in 6.908s
found 0 vulnerabilities

npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> pre-commit@1.1.3 install /strapi/node_modules/pre-commit
> node install.js


> spawn-sync@1.0.13 postinstall /strapi/node_modules/spawn-sync
> node postinstall


> cypress@3.1.2 postinstall /strapi/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 3.1.2)

 ✔  Downloaded Cypress
 ✔  Unzipped Cypress
 ✔  Finished Installation /root/.cache/Cypress/3.1.2

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

npm WARN babel-loader@7.1.1 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1513 packages from 767 contributors and audited 1716705 packages in 318.15s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
6.4.1
v11.1.0

🕓  The setup process can take few minutes.

📦  Linking strapi-utils...
✅  Success

📦  Linking strapi-lint
✅  Success

📦  Linking strapi-generate...
✅  Success

📦  Linking strapi-generate-api...
✅  Success

📦  Linking strapi-helper-plugin...
✅  Success

📦  Linking strapi-admin
📦  Linking strapi-generate-admin...
✅  Success

📦  Linking strapi-generate-new
✅  Success

📦  Linking strapi-hook-mongoose...
✅  Success

📦  Linking strapi-hook-knex...
✅  Success

📦  Linking strapi-hook-bookshelf...
✅  Success

📦  Linking strapi...
✅  Success

📦  Linking strapi-plugin-graphql...
📦  Linking strapi-provider-upload-local...
📦  Linking strapi-provider-email-sendmail...
📦  Linking strapi-plugin-documentation...
📦  Linking strapi-plugin-email...
📦  Linking strapi-plugin-users-permissions...
📦  Linking strapi-plugin-content-manager...
📦  Linking strapi-plugin-settings-manager...
📦  Linking strapi-plugin-upload...
📦  Linking strapi-plugin-content-type-builder...
🏗  Building admin...
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! strapi-admin@3.0.0-alpha.26.1 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-25T11_02_54_877Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.26.1 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.26.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-25T11_02_55_185Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.26.1 setup:build: `npm run setup --build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.26.1 setup:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-25T11_02_55_258Z-debug.log
```
```bash
bash-4.4# cat /root/.npm/_logs/2019-04-25T11_02_54_877Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v11.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle strapi-admin@3.0.0-alpha.26.1~prebuild: strapi-admin@3.0.0-alpha.26.1
6 verbose lifecycle strapi-admin@3.0.0-alpha.26.1~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle strapi-admin@3.0.0-alpha.26.1~prebuild: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/packages/strapi-admin/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
8 verbose lifecycle strapi-admin@3.0.0-alpha.26.1~prebuild: CWD: /strapi/packages/strapi-admin
9 silly lifecycle strapi-admin@3.0.0-alpha.26.1~prebuild: Args: [ '-c',
9 silly lifecycle   'cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js' ]
10 silly lifecycle strapi-admin@3.0.0-alpha.26.1~prebuild: Returned: code: 0  signal: null
11 info lifecycle strapi-admin@3.0.0-alpha.26.1~build: strapi-admin@3.0.0-alpha.26.1
12 verbose lifecycle strapi-admin@3.0.0-alpha.26.1~build: unsafe-perm in lifecycle true
13 verbose lifecycle strapi-admin@3.0.0-alpha.26.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/packages/strapi-admin/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
14 verbose lifecycle strapi-admin@3.0.0-alpha.26.1~build: CWD: /strapi/packages/strapi-admin
15 silly lifecycle strapi-admin@3.0.0-alpha.26.1~build: Args: [ '-c',
15 silly lifecycle   'cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress' ]
16 silly lifecycle strapi-admin@3.0.0-alpha.26.1~build: Returned: code: 2  signal: null
17 info lifecycle strapi-admin@3.0.0-alpha.26.1~build: Failed to exec build script
18 verbose stack Error: strapi-admin@3.0.0-alpha.26.1 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
18 verbose stack Exit status 2
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18 verbose stack     at EventEmitter.emit (events.js:182:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:182:13)
18 verbose stack     at maybeClose (internal/child_process.js:970:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
19 verbose pkgid strapi-admin@3.0.0-alpha.26.1
20 verbose cwd /strapi/packages/strapi-admin
21 verbose Linux 4.14.111-boot2docker
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
23 verbose node v11.1.0
24 verbose npm  v6.4.1
25 error code ELIFECYCLE
26 error errno 2
27 error strapi-admin@3.0.0-alpha.26.1 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
27 error Exit status 2
28 error Failed at the strapi-admin@3.0.0-alpha.26.1 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 2, true ]
```
```bash
bash-4.4# cat /root/.npm/_logs/2019-04-25T11_02_55_185Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup',
1 verbose cli   '--build' ]
2 info using npm@6.4.1
3 info using node@v11.1.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle @3.0.0-alpha.26.1~presetup: @3.0.0-alpha.26.1
6 info lifecycle @3.0.0-alpha.26.1~setup: @3.0.0-alpha.26.1
7 verbose lifecycle @3.0.0-alpha.26.1~setup: unsafe-perm in lifecycle true
8 verbose lifecycle @3.0.0-alpha.26.1~setup: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle @3.0.0-alpha.26.1~setup: CWD: /strapi
10 silly lifecycle @3.0.0-alpha.26.1~setup: Args: [ '-c',
10 silly lifecycle   'npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean' ]
11 silly lifecycle @3.0.0-alpha.26.1~setup: Returned: code: 1  signal: null
12 info lifecycle @3.0.0-alpha.26.1~setup: Failed to exec setup script
13 verbose stack Error: @3.0.0-alpha.26.1 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
14 verbose pkgid @3.0.0-alpha.26.1
15 verbose cwd /strapi
16 verbose Linux 4.14.111-boot2docker
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup" "--build"
18 verbose node v11.1.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @3.0.0-alpha.26.1 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
22 error Exit status 1
23 error Failed at the @3.0.0-alpha.26.1 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
```bash
bash-4.4# cat /root/.npm/_logs/2019-04-25T11_02_55_258Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup:build' ]
2 info using npm@6.4.1
3 info using node@v11.1.0
4 verbose run-script [ 'presetup:build', 'setup:build', 'postsetup:build' ]
5 info lifecycle @3.0.0-alpha.26.1~presetup:build: @3.0.0-alpha.26.1
6 info lifecycle @3.0.0-alpha.26.1~setup:build: @3.0.0-alpha.26.1
7 verbose lifecycle @3.0.0-alpha.26.1~setup:build: unsafe-perm in lifecycle true
8 verbose lifecycle @3.0.0-alpha.26.1~setup:build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/strapi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle @3.0.0-alpha.26.1~setup:build: CWD: /strapi
10 silly lifecycle @3.0.0-alpha.26.1~setup:build: Args: [ '-c', 'npm run setup --build' ]
11 silly lifecycle @3.0.0-alpha.26.1~setup:build: Returned: code: 1  signal: null
12 info lifecycle @3.0.0-alpha.26.1~setup:build: Failed to exec setup:build script
13 verbose stack Error: @3.0.0-alpha.26.1 setup:build: `npm run setup --build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
14 verbose pkgid @3.0.0-alpha.26.1
15 verbose cwd /strapi
16 verbose Linux 4.14.111-boot2docker
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup:build"
18 verbose node v11.1.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @3.0.0-alpha.26.1 setup:build: `npm run setup --build`
22 error Exit status 1
23 error Failed at the @3.0.0-alpha.26.1 setup:build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any suggestions?
Could you provide a `Dockerfile` for building `strapi`?

Cheers,
Steve

**Comment by lauriejim** [comment]
Hello @sseypt!

Your second message is related to Docker, we have a repo dedicated to this type of issue.

**Comment by derrickmehaffy** [comment]
This is already been fixed:

![image](https://user-images.githubusercontent.com/8593673/62855252-96140c00-bca6-11e9-8d5f-0fe975b44cd8.png)
