### ISSUE TITLE
Changing default database name crashes server

### ISSUE THREAD

**Issue by corepay** [strapi/strapi#3184]
**Informations**
- **Node.js version**:  10.15.0
- **NPM version**:  6.4.1
- **Strapi version**:  latest cli install today 
- **Database**: PostgresSQL 11 local brew install
- **Operating system**:  MacOS latest
- **(Optional) Link to your Project**: 

**What is the current behavior?**  Server crashing when changing database name from default to anything else.  Unrecoverable, crashing restart also needs reinstall

**Steps to reproduce the problem**  

1. New manual install using local Postgresql
2.  Login new credentials
3.  Go to Configuration -> databases and change name from default to anything else
4.  On SAVE server crashes

```
[2019-04-24T21:27:18.828Z] debug PUT /settings-manager/configurations/databases/default/development (23 ms)
error TypeError: strapi.models.core_store.forge is not a function

error TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
    at module.exports (/Users/Numchucks/development/client/forms/cms/plugins/content-manager/config/functions/bootstrap.js:312:42)
    at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:299:13)
    at new Promise (<anonymous>)
    at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:287:11)
    at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:326:44)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:326:35)
    at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:109:18)
(node:95769) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
    at module.exports (/Users/Numchucks/development/client/forms/cms/plugins/settings-manager/config/functions/bootstrap.js:17:26)
    at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:299:13)
    at new Promise (<anonymous>)
    at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:287:11)
    at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:326:44)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:326:35)
    at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:109:18)
(node:95769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:95769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95769) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
    at module.exports (/Users/Numchucks/development/client/forms/cms/plugins/users-permissions/config/functions/bootstrap.js:96:45)
    at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:299:13)
    at new Promise (<anonymous>)
    at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:287:11)
    at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:326:44)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:326:35)
    at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:109:18)
(node:95769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:95769) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
    at fs.readdir (/Users/Numchucks/development/client/forms/cms/plugins/email/config/functions/bootstrap.js:68:40)
(node:95769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:95769) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
    at fs.readdir (/Users/Numchucks/development/client/forms/cms/plugins/upload/config/functions/bootstrap.js:70:40)
(node:95769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

**What is the expected behavior?**

Change default database name

**Suggested solutions**

**Comment by lauriejim** [comment]
Thank you @corepay for this report!
We will try to fix it soon as we can.

To fix you app, please rename your connection name manually to `default` and re-update your APIs models to use `default` connection.

**Comment by corepay** [comment]
Hello and thank you.  FWIW changing the name back to `default` in the `database.json` and restarting strapi results in same error - server will not start and I have to delete directory and reinstall.

**Comment by lauriejim** [comment]
The exact same ?

**Comment by jacargentina** [comment]
@lauriejim I've migrated from alpha to latest `3.0.0-beta.2` and getting same error, but i've looked on my configs and all environments are:

```json
{
    "defaultConnection": "default"
   ...
} 
```

Any advice?

**Comment by lauriejim** [comment]
Hum @jacargentina I think your issue is different.

Here it's because if you change `default` by an other name, in `core_store` model structuration, we force to `default` so it does exist at this time.

But in your case I don't know why.
You migrate from alpha ? or it was from beta.1 ?

**Comment by jacargentina** [comment]
@lauriejim discard my comment; my migration was wrong. Now it works.

**Comment by lucacattide** [comment]
Same issue here. falling back to the following setup worked for me - on development environment:
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "sqlite3",
        "filename": ".tmp/data.db",
        "enabled": true,
        "defaultConnection": "default",
        "host": "localhost"
      },
      "options": {
        "useNullAsDefault": true
      }
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
This is due to some instances of the `default` being hard coded into some models such as the strapi-administrators model and I believe the core_store
