### ISSUE TITLE
Deploy and then can't start app in container (google cloud)

### ISSUE THREAD

**Issue by eugenotop** [strapi/strapi#3185]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 
 "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-react": "^7.7.0"
  },
  "dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-alpha.26.1",
    "strapi-utils": "3.0.0-alpha.26.1",
    "strapi-hook-bookshelf": "3.0.0-alpha.26.1",
    "strapi-hook-knex": "3.0.0-alpha.26.1",
    "knex": "latest",
    "pg": "7.10.0"
  },

**What is the current behavior?**

internal/modules/cjs/loader.js:584

**Steps to reproduce the problem**

> strapi start

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/opt/application/cms/plugins/content-type-builder/services/ContentTypeBuilder.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cms@0.1.0 strapi:run: `strapi start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cms@0.1.0 strapi:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-24T16_20_43_747Z-debug.log
 

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
