### ISSUE TITLE
npm install -g strapi fails with build errors

### ISSUE THREAD

**Issue by yoDon** [strapi/strapi#3223]
**Informations**
- **Node.js version**: 10.15.3 
- **NPM version**: 6.4.1
- **Strapi version**: attempting to install current 
- **Database**: havent gotten there yet
- **Operating system**: Win10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Unable to install strapi

**Steps to reproduce the problem**

1) npm install -g strapi
2) see error spew

```
npm install -g strapi
npm WARN deprecated koa-gzip@0.1.0: please use koa-compress instead.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated nodemailer@1.10.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@2.1.0: This project is unmaintained
npm WARN deprecated buildmail@2.0.0: This project is unmaintained
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
C:\Users\don\AppData\Roaming\npm\strapi -> C:\Users\don\AppData\Roaming\npm\node_modules\strapi\bin\_spawn.js

> utf-8-validate@1.2.2 install C:\Users\don\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\don\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
  win_delay_load_hook.cc
c:\users\don\appdata\roaming\npm\node_modules\strapi\node_modules\utf-8-validate\node_modules\nan\nan_maybe_43_inl.h(8
8): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\validation.cc) [C:\Users\do
n\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\build\validation.vcxproj]
  C:\Users\don\.node-gyp\10.15.3\include\node\v8.h(3243): note: see declaration of 'v8::Object' (compiling source file
   ..\src\validation.cc)
C:\Users\don\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\node_modules\nan\nan.h(816): warning 
C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\validation.cc) [C:\Users\don\AppDat
a\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\build\validation.vcxproj]
  C:\Users\don\.node-gyp\10.15.3\include\node\node.h(182): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\validation.cc)
C:\Users\don\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\node_modules\nan\nan.h(830): warning 
C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\validation.cc) [C:\Users\don\AppDat
a\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\build\validation.vcxproj]
  C:\Users\don\.node-gyp\10.15.3\include\node\node.h(175): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\validation.cc)
C:\Users\don\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\node_modules\nan\nan.h(844): warning 
C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\validation.cc) [C:\Users\don\AppDat
a\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\build\validation.vcxproj]
  C:\Users\don\.node-gyp\10.15.3\include\node\node.h(168): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\validation.cc)
C:\Users\don\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\node_modules\nan\nan.h(1447): warning
 C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\validation.cc) [C:\Users\don\AppDa
ta\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate\build\validation.vcxproj]
  C:\Users\don\.node-gyp\10.15.3\include\node\node.h(182): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\validation.cc)
..\src\validation.cc(131): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\don\AppData\Roaming
\npm\node_modules\strapi\node_modules\utf-8-validate\build\validation.vcxproj]
  C:\Users\don\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\don\AppData\Roaming\npm\node_modules\strapi\node_modules\utf-8-validate
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\strapi\node_modules\utf-8-validate):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ strapi@1.6.4
updated 1 package in 30.322s
```

**What is the expected behavior?**

Strapi installs

**Suggested solutions**

**Comment by yoDon** [comment]
I've also tried to npx strapi new, which results in a completely different set of blocking errors, as reported in https://github.com/strapi/strapi/issues/3222

**Comment by alexandrebodin** [comment]
Hi,

Strapi must be used with the alpha version. You can read about it [here](https://strapi.io/documentation/3.x.x/getting-started/quick-start.html)
