### ISSUE TITLE
Strapi Start error after removing a field in content-type (hook:mongoose) takes too long to load

### ISSUE THREAD

**Issue by navichansy** [strapi/strapi#3237]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**:  6.4.1
- **Strapi version**: v3.0.0-alpha.26.2
- **Database**: MongoDB
- **Operating system**:  MacOS High Sierra 10.13.6 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I have created 3 content types via the admin panel. In one of them (no entry is created) when I removed a Date field, the app just timeout too long and then crashed. Running Strapi Start again I can see this error:
```
(node:2373) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.convertType (/Users/me/Strapi/cms/node_modules/strapi-hook-mongoose/lib/utils/index.js:25:28)
    at _.forEach (/Users/me/Strapi/cms/node_modules/strapi-hook-mongoose/lib/index.js:455:73)
    at /Users/me/Strapi/cms/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/me/Strapi/cms/node_modules/lodash/lodash.js:2996:24)
    at /Users/me/Strapi/cms/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/Users/me/Strapi/cms/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/Users/me/Strapi/cms/node_modules/strapi-hook-mongoose/lib/index.js:444:19)
    at /Users/me/Strapi/cms/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/me/Strapi/cms/node_modules/lodash/lodash.js:2996:24)
    at /Users/me/Strapi/cms/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/Users/me/Strapi/cms/node_modules/lodash/lodash.js:9344:14)
    at mountModels (/Users/me/Strapi/cms/node_modules/strapi-hook-mongoose/lib/index.js:369:17)
    at _.forEach (/Users/me/Strapi/cms/node_modules/strapi-hook-mongoose/lib/index.js:620:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-05-08T03:59:55.505Z] debug ⛔️ Server wasn't able to start properly.
[2019-05-08T03:59:55.505Z] error (hook:mongoose) takes too long to load
(hook:mongoose) takes too long to load
```
My MongoDB is running with these message:
```
2019-05-08T11:23:45.491+0800 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-05-08T11:24:07.664+0800 I NETWORK  [listener] connection accepted from 127.0.0.1:49802 #1 (1 connection now open)
2019-05-08T11:24:07.666+0800 I NETWORK  [conn1] received client metadata from 127.0.0.1:49802 conn1: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "17.7.0" }, platform: "Node.js v10.15.3, LE, mongodb-core: 3.2.3" }
2019-05-08T11:24:17.669+0800 I NETWORK  [conn1] end connection 127.0.0.1:49802 (0 connections now open)
```

I have tried to uninstall GraphQL plugin from CLI, increase the timeout of hock.json to 100000 but it didn't work. Finally I can get the app running again by manually remove the relationship fields between that content-type and user in *.settings.json respectively. 

**Steps to reproduce the problem**
I can't reproduce this problem though. I've tried add back the date and relationship fields described above and tried removed the fields again (both via admin panel & manually in code) but no error occur. 

**Suggested solutions**
I guess its something related to the timeout and the admin panel that crash the app. Unlike issue #563 or #2063 it seems nothing  to with the db setting or plugin installed, nor did I enter a unaccepted field name (e.g. uppercase, camelcase, space) that trigger the problem.
I know it would be clueless now for fixing this as I am not abled to reproduce the bug yet. But I hope it may help for someone else that face the same problem.

**Comment by derrickmehaffy** [comment]
@navichansy Thank you for the notification, in order to leave this open (for a fix) we need some steps to be able to reproduce the issue. For now I will mark this as closed, if you or other users come across this and are able to reproduce then we can look at reopening it.
