### ISSUE TITLE
BadRequestError: failed to decode after install

### ISSUE THREAD

**Issue by edbizarro** [strapi/strapi#3250]
**Informations**
- **Node.js version**: v11.15.0
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: sqlite
- **Operating system**: Arch
- **(Optional) Link to your Project**: 

**What is the current behavior?**

After install when run strapi start I'm getting this error

```
[2019-05-12T22:30:27.999Z] debug GET index.html (20 ms)
{ BadRequestError: failed to decode
    at Object.throw (/home/edbizarro/.node_modules/lib/node_modules/strapi/node_modules/koa/lib/context.js:97:11)
    at send (/home/edbizarro/.node_modules/lib/node_modules/strapi/node_modules/koa-send/index.js:63:36)
    at serve (/home/edbizarro/.node_modules/lib/node_modules/strapi/node_modules/koa-static/index.js:66:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) message: 'failed to decode' }
```

And the panel never shows up

**Steps to reproduce the problem**

- strapi new api
- Admin shows up, register
- CTRL + C to stop
- strapi start
- Access http://localhost:1337/admin
- Error

**What is the expected behavior?**

**Suggested solutions**

**Comment by edbizarro** [comment]
Update: running `npm run start` on the folder seems to work correctly

**Comment by lauriejim** [comment]
Hello!
What is the command you use to create your application?

**Comment by edbizarro** [comment]
`strapi new api`

**Comment by lauriejim** [comment]
Hum with this information, I have no idea!
I tried to reproduce and it's impossible..

If you create a new app, are you able to reproduce again this issue ?
