### ISSUE TITLE
An error occurred during settings-manager plugin installation

### ISSUE THREAD

**Issue by micobarac** [strapi/strapi#3255]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: ??
- **Operating system**: macOS Mojave 10.14.4 (18E226)

**What is the current behavior?**

```
An error occurred during settings-manager plugin installation

(node:6382) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/Users/milan/Sites/cms/plugins/users-permissions/config/functions/bootstrap.js:167:48)
(node:6382) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6382) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-05-14T06:45:36.276Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-05-14T06:45:36.278Z] warn Perhaps you forgot to call it?
```

**Steps to reproduce the problem**

```
npm install strapi@alpha -g
strapi new cms --quickstart
```

**What is the expected behavior?**

It should at least create a new CMS without errors

**Suggested solutions**

???

**Comment by lauriejim** [comment]
Can you send us full logs of your terminals (from the `strapi new`)
It will give us more context about the issue.

**Comment by madflow** [comment]
I have the same issue:

* node v10.15.0
* Arch Linux
* ZSH Shell

```
➜  ProjectX strapi new cms --quickstart
🚀 Starting to create your Strapi application.


✅ Connected to the database

🏗  Application generation:
✔ Copy dashboard
⚠ An error occurred during settings-manager plugin installation.
- Install settings-manager plugin
✖ An error occurred during plugin installation.

✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
⚠ An error occurred during users-permissions plugin installation.
- Install users-permissions plugin
✖ An error occurred during plugin installation.

⠼ Install plugin email.
✔ Install plugin email.
⚠ An error occurred during upload plugin installation.
- Install upload plugin
✖ An error occurred during plugin installation.

✔ Link strapi dependency to the project.
✔ Link strapi-utils dependency to the project.

👌 Your new application cms is ready at /home/flo/Projects/ProjectX/cms.

⚡️ Change directory:
$ cd cms

⚡️ Start application:
$ strapi start

(node:15945) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/home/flo/Projects/ProjectX/cms/plugins/users-permissions/config/functions/bootstrap.js:167:48)
(node:15945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15945) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-05-22T19:06:09.769Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-05-22T19:06:09.773Z] warn Perhaps you forgot to call it?
^C%                        
```

**Comment by lauriejim** [comment]
This issue is related to the alpha version.
Not append in beta version (beta.15) of strapi.
I close this issue.
