### ISSUE TITLE
Set the ssl true in options object for bookshelf/knex

### ISSUE THREAD

**Issue by gajus** [strapi/strapi#3271]
**Informations**
- **Node.js version**: v12.1.0
- **NPM version**: v6.9.0
- **Strapi version**: v3.0.0-alpha.26.2
- **Database**: PostgreSQL 11.3

**What is the current behavior?**

```
[2019-05-15T18:12:33.185Z] debug ⛔️ Server wasn't able to start properly.
[2019-05-15T18:12:33.187Z] error no pg_hba.conf entry for host "xxx", user "avnadmin", database "applaudience", SSL off
error: no pg_hba.conf entry for host "xxx", user "avnadmin", database "applaudience", SSL off
    at Connection.parseE (/Users/gajus/Documents/dev/applaudience/applaudience-data-management-web-app/applaudience-data-management-web-app/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/gajus/Documents/dev/applaudience/applaudience-data-management-web-app/applaudience-data-management-web-app/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/gajus/Documents/dev/applaudience/applaudience-data-management-web-app/applaudience-data-management-web-app/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 159,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '512',
  routine: 'ClientAuthentication'
}

```

**Steps to reproduce the problem**

Configuration:

```json
{
  "defaultConnection": "Mother",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "sqlite",
        "filename": ".tmp/data.db"
      },
      "options": {
        "useNullAsDefault": true
      }
    },
    "Mother": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "xxx",
        "port": 21291,
        "database": "applaudience",
        "username": "avnadmin",
        "password": "xxx"
      },
      "options": {
        "ssl": true
      }
    }
  }
}

```

**What is the expected behavior?**

Successful connection to the database.

**Suggested solutions**

N/A

**Comment by lauriejim** [comment]
Hello!!
Arg you are true. But it's because you have to set the `ssl` key in `settings` for bookshelf.
We have to fix it to use this as an options.

**Comment by lauriejim** [comment]
By following the docs - all works fine.
I link this issue to the one that concerne the connection transparency.
https://github.com/strapi/strapi/issues/2030

**Comment by fsobh** [comment]
i

> Hello!!
> Arg you are true. But it's because you have to set the `ssl` key in `settings` for bookshelf.
> We have to fix it to use this as an options.

This didn't make sense to me. What is it exactly? im still facing the same issue
