### ISSUE TITLE
Using Redis databased connection

### ISSUE THREAD

**Issue by it-nilesh** [strapi/strapi#3285]
error Impossible to determine the use of ORM for the model customer.
TypeError: Cannot read property 'find' of undefined
    at Object.fetchAll (D:\RND\Strapi\strapi-new\plugins\content-manager\services\ContentManager.js:19:52)
    at find (D:\RND\Strapi\strapi-new\plugins\content-manager\controllers\ContentManager.js:33:83)

When I view model in the strapi admin panel, throw the above exception.

npm package : *strapi-hook-redis*

**Comment by derrickmehaffy** [comment]
@it-nilesh please follow the bug report template, after you have updated your issue with the proper template this can be reopened.

Closing due to no template being used.
