### ISSUE TITLE
Strapi start Error "unexpected"

### ISSUE THREAD

**Issue by djeorges28** [strapi/strapi#329]
**Node.js version**:  6.11.4
**npm version**: 3.10.10
**Strapi version**: 3.0.0-ampha 6.4
**Operating system**: win7 64b

Hi all, I'm just starting to discover Strapi and "getting started guide".
installation and ipa generation ended with no errors 
But I get this error when starting strapi. 

Thank's for your help.

C:\DEV\apitest2>strapi start
ERROR (6848 on PC-Leo): Unexpected identifier
    C:\Users\Georges\AppData\Roaming\npm\node_modules\strapi\lib\Strapi.js:86
  async start(config = {}, cb) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Georges\AppData\Roaming\npm\node_modules\strapi\lib\index.js:12:
26)

**Comment by Redni** [comment]
Strapi Alpha required Node.js >= 8.

**Comment by djeorges28** [comment]
Thank's a lot. I have installed the latest version of node and now everything works well.
Let's continue the tutorial :-)
