### ISSUE TITLE
Cannot build on Window 10

### ISSUE THREAD

**Issue by hoangtrongphuc** [strapi/strapi#3303]
**Informations**
- **Node.js version**: 11.5.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: Mysql
- **Operating system**: Window 10

**What is the current behavior?**
I cannot rebuild plugin when I modify core frontend
🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...

Packages installed successfully

> strapi-admin@3.0.0-alpha.26.1 setup D:\Project\cms\admin
> node ./scripts/setup.js

🏗  Building the admin...
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! strapi-admin@3.0.0-alpha.26.1 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-05-21T07_51_31_773Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.26.1 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-05-21T07_51_32_028Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cms-vinhomes@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cms-vinhomes@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-05-21T07_51_32_097Z-debug.log

**Steps to reproduce the problem**
Run cmd as administrator
Run "npm run setup --plugins"

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Will be fixed in the beta due at the end of the month. Building on Windows is a well known problem as with the Alpha windows is completely supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

**Comment by Downloaddave** [comment]
I'm running into a similar issue on MacOSx, any ideas on what I can try?

**Node.js version:** 10.15.3
**NPM version:** 6.4.1
**Strapi version:** 3.0.0-alpha.26.2
**Database:** MongoDB
**Operating system:** macOS High Sierra Version 10.13.6

```
$ npm run setup:build

> @3.0.0-alpha.26.2 setup:build /Users/oxymoron/Industry/_clients/theglue/projects/ladot/code/at/strapi-core-engine-262a/strapi
> npm run setup --build


> @3.0.0-alpha.26.2 setup /Users/oxymoron/Industry/_clients/theglue/projects/ladot/code/at/strapi-core-engine-262a/strapi
> npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.26.2 clean:all /Users/oxymoron/Industry/_clients/theglue/projects/ladot/code/at/strapi-core-engine-262a/strapi
> npm run removesymlinkdependencies && npx rimraf package-lock.json && npx rimraf packages/*/package-lock.json && npx rimraf packages/*/node_modules


> @3.0.0-alpha.26.2 removesymlinkdependencies /Users/oxymoron/Industry/_clients/theglue/projects/ladot/code/at/strapi-core-engine-262a/strapi
> node ./scripts/removeSymlinkDependencies.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babel-loader@7.1.1 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.

+ strapi-lint@3.0.0-alpha.26.2
added 1 package from 1 contributor and updated 1 package in 14.268s
npm WARN babel-loader@7.1.1 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.

up to date in 11.184s
6.4.1
v10.1.0

🕓  The setup process can take few minutes.

📦  Linking strapi-utils...
✅  Success

📦  Linking strapi-lint
✅  Success

📦  Linking strapi-generate...
✅  Success

📦  Linking strapi-generate-api...
✅  Success

📦  Linking strapi-helper-plugin...
✅  Success

📦  Linking strapi-admin
📦  Linking strapi-generate-admin...
✅  Success

📦  Linking strapi-generate-new
✅  Success

📦  Linking strapi-hook-mongoose...
✅  Success

📦  Linking strapi-hook-knex...
✅  Success

📦  Linking strapi-hook-bookshelf...
✅  Success

📦  Linking strapi...
✅  Success

📦  Linking strapi-plugin-graphql...
📦  Linking strapi-provider-upload-local...
📦  Linking strapi-provider-email-sendmail...
📦  Linking strapi-plugin-documentation...
📦  Linking strapi-plugin-email...
📦  Linking strapi-plugin-users-permissions...
📦  Linking strapi-plugin-content-manager...
📦  Linking strapi-plugin-settings-manager...
📦  Linking strapi-plugin-upload...
📦  Linking strapi-plugin-content-type-builder...
🏗  Building admin...
🏗  Building plugin-content-manager...
🏗  Building plugin-content-type-builder...
🏗  Building plugin-documentation...
🏗  Building plugin-upload...
🏗  Building plugin-email...
🏗  Building plugin-users-permissions...
🏗  Building plugin-settings-manager...
 63% building modules 576/651 modules 75 active ...admin/src/assets/images/social_gh.png(node:15381) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code ELIFECYCLE                                                                  
npm ERR! errno 2
npm ERR! strapi-admin@3.0.0-alpha.26.2 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oxymoron/.npm/_logs/2019-05-27T03_07_42_676Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.26.2 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @3.0.0-alpha.26.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oxymoron/.npm/_logs/2019-05-27T03_07_42_820Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.26.2 setup:build: `npm run setup --build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @3.0.0-alpha.26.2 setup:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-05-27T03_07_42_853Z-debug.log
```

Here's a copy of ~/.npm/_logs/2019-05-27T03_07_42_853Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/oxymoron/.nvm/versions/node/v10.1.0/bin/node',
1 verbose cli   '/Users/oxymoron/.nvm/versions/node/v10.1.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup:build' ]
2 info using npm@6.4.1
3 info using node@v10.1.0
4 verbose run-script [ 'presetup:build', 'setup:build', 'postsetup:build' ]
5 info lifecycle @3.0.0-alpha.26.2~presetup:build: @3.0.0-alpha.26.2
6 info lifecycle @3.0.0-alpha.26.2~setup:build: @3.0.0-alpha.26.2
7 verbose lifecycle @3.0.0-alpha.26.2~setup:build: unsafe-perm in lifecycle true
8 verbose lifecycle @3.0.0-alpha.26.2~setup:build: PATH: /Users/oxymoron/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/oxymoron/Industry/_clients/theglue/projects/ladot/code/at/strapi-core-engine-262a/strapi/node_modules/.bin:/Users/oxymoron/.nvm/versions/node/v10.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin:/Users/oxymoron/.nvm/versions/node/v10.1.0/bin:/usr/local/sbin
9 verbose lifecycle @3.0.0-alpha.26.2~setup:build: CWD: /Users/oxymoron/Industry/_clients/theglue/projects/ladot/code/at/strapi-core-engine-262a/strapi
10 silly lifecycle @3.0.0-alpha.26.2~setup:build: Args: [ '-c', 'npm run setup --build' ]
11 silly lifecycle @3.0.0-alpha.26.2~setup:build: Returned: code: 1  signal: null
12 info lifecycle @3.0.0-alpha.26.2~setup:build: Failed to exec setup:build script
13 verbose stack Error: @3.0.0-alpha.26.2 setup:build: `npm run setup --build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/oxymoron/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/oxymoron/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:957:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
14 verbose pkgid @3.0.0-alpha.26.2
15 verbose cwd /Users/oxymoron/Industry/_clients/theglue/projects/ladot/code/at/strapi-core-engine-262a/strapi
16 verbose Darwin 17.7.0
17 verbose argv "/Users/oxymoron/.nvm/versions/node/v10.1.0/bin/node" "/Users/oxymoron/.nvm/versions/node/v10.1.0/bin/npm" "run" "setup:build"
18 verbose node v10.1.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @3.0.0-alpha.26.2 setup:build: `npm run setup --build`
22 error Exit status 1
23 error Failed at the @3.0.0-alpha.26.2 setup:build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
