### ISSUE TITLE
Strapi Development Environment for Plugin Broken

### ISSUE THREAD

**Issue by patientplatypus** [strapi/strapi#3307]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: N/A
- **Operating system**: osx 10.11.6 el capitan
- **(Optional) Link to your Project**: simple fork of the strapi repo

**What is the current behavior?**

Running the `Development Environment Setup` from (https://strapi.io/documentation/3.x.x/plugin-development/quick-start.html) exits with an error.

**Steps to reproduce the problem**

```
Last login: Tue May 21 21:06:53 on ttys003
woog-1s-Air:strapi woog_01$ ls
CODE_OF_CONDUCT.md	README.md		fileTransformer.js	lerna.json		package.json
CONTRIBUTING.md		cypress			jest.config.e2e.js	mkdocs.yml		packages
LICENSE.md		cypress.json		jest.config.front.js	node_modules		scripts
Makefile		docs			jest.config.js		package-lock.json	test
woog-1s-Air:strapi woog_01$ cd ..
woog-1s-Air:repositories woog_01$ ls
strapi
woog-1s-Air:repositories woog_01$ cd ..
woog-1s-Air:espnAccount woog_01$ ls
blog			gatsbyTest		repositories		strapi-api-gatsby-demo1	strapi-api-gatsby-demo3
cms			package.json		strapi-api-gatsby-demo	strapi-api-gatsby-demo2	tutorial
woog-1s-Air:espnAccount woog_01$ cd ..
woog-1s-Air:platypusNEST woog_01$ mkdir strapiTest
woog-1s-Air:platypusNEST woog_01$ cd strapiTest/
woog-1s-Air:strapiTest woog_01$ ls
woog-1s-Air:strapiTest woog_01$ git clone https://github.com/patientplatypus/strapi.git
Cloning into 'strapi'...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 90663 (delta 42), reused 76 (delta 24), pack-reused 90551
Receiving objects: 100% (90663/90663), 84.91 MiB | 26.17 MiB/s, done.
Resolving deltas: 100% (62772/62772), done.
woog-1s-Air:strapiTest woog_01$ ls
strapi
woog-1s-Air:strapiTest woog_01$ cd strapi/
woog-1s-Air:strapi woog_01$ ls
CODE_OF_CONDUCT.md	Makefile		cypress.json		jest.config.e2e.js	lerna.json		packages
CONTRIBUTING.md		README.md		docs			jest.config.front.js	mkdocs.yml		scripts
LICENSE.md		cypress			fileTransformer.js	jest.config.js		package.json		test
woog-1s-Air:strapi woog_01$ npm run setup

> @3.0.0-alpha.26.2 setup /Users/woog_01/Documents/platypusNEST/strapiTest/strapi
> npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.26.2 clean:all /Users/woog_01/Documents/platypusNEST/strapiTest/strapi
> npm run removesymlinkdependencies && npx rimraf package-lock.json && npx rimraf packages/*/package-lock.json && npx rimraf packages/*/node_modules


> @3.0.0-alpha.26.2 removesymlinkdependencies /Users/woog_01/Documents/platypusNEST/strapiTest/strapi
> node ./scripts/removeSymlinkDependencies.js

npx: installed 12 in 3.96s
npx: installed 12 in 2.24s
npx: installed 12 in 2.291s
npm notice created a lockfile as package-lock.json. You should commit this file.
+ strapi-lint@3.0.0-alpha.26.2
added 52 packages from 61 contributors and audited 137 packages in 5.472s
found 0 vulnerabilities

npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> fsevents@1.2.9 install /Users/woog_01/Documents/platypusNEST/strapiTest/strapi/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/woog_01/Documents/platypusNEST/strapiTest/strapi/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> pre-commit@1.1.3 install /Users/woog_01/Documents/platypusNEST/strapiTest/strapi/node_modules/pre-commit
> node install.js


> core-js@2.6.8 postinstall /Users/woog_01/Documents/platypusNEST/strapiTest/strapi/node_modules/core-js
> node -e "try { require('./scripts/postinstall'); } catch (e) { /* empty */ }"

Thank you for using core-js ( https://github.com/zloirock/core-js )!

Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> spawn-sync@1.0.13 postinstall /Users/woog_01/Documents/platypusNEST/strapiTest/strapi/node_modules/spawn-sync
> node postinstall


> cypress@3.1.2 postinstall /Users/woog_01/Documents/platypusNEST/strapiTest/strapi/node_modules/cypress
> node index.js --exec install


Cypress 3.1.2 is already installed in /Users/woog_01/Library/Caches/Cypress/3.1.2

npm WARN babel-loader@7.1.1 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.

added 1583 packages from 777 contributors and audited 1737239 packages in 47.018s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
6.4.1
v10.15.3

🕓  The setup process can take few minutes.

📦  Linking strapi-utils...
npm ERR! path /usr/local/lib/node_modules/strapi-utils
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/strapi-utils'
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/strapi-utils']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, unlink \'/usr/local/lib/node_modules/strapi-utils\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/lib/node_modules/strapi-utils' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/woog_01/.npm/_logs/2019-05-22T01_15_15_027Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.26.2 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @3.0.0-alpha.26.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/woog_01/.npm/_logs/2019-05-22T01_15_15_070Z-debug.log
woog-1s-Air:strapi woog_01$ cat  /Users/woog_01/.npm/_logs/2019-05-22T01_15_15_070Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle @3.0.0-alpha.26.2~presetup: @3.0.0-alpha.26.2
6 info lifecycle @3.0.0-alpha.26.2~setup: @3.0.0-alpha.26.2
7 verbose lifecycle @3.0.0-alpha.26.2~setup: unsafe-perm in lifecycle true
8 verbose lifecycle @3.0.0-alpha.26.2~setup: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/woog_01/Documents/platypusNEST/strapiTest/strapi/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @3.0.0-alpha.26.2~setup: CWD: /Users/woog_01/Documents/platypusNEST/strapiTest/strapi
10 silly lifecycle @3.0.0-alpha.26.2~setup: Args: [ '-c',
10 silly lifecycle   'npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean' ]
11 silly lifecycle @3.0.0-alpha.26.2~setup: Returned: code: 1  signal: null
12 info lifecycle @3.0.0-alpha.26.2~setup: Failed to exec setup script
13 verbose stack Error: @3.0.0-alpha.26.2 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @3.0.0-alpha.26.2
15 verbose cwd /Users/woog_01/Documents/platypusNEST/strapiTest/strapi
16 verbose Darwin 15.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @3.0.0-alpha.26.2 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
22 error Exit status 1
23 error Failed at the @3.0.0-alpha.26.2 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**What is the expected behavior?**

That I successfully get the dev environment to work.

**Suggested solutions**

I'm not sure. I checked if the linking was coming from my `bash_profile`, but that's empty as this is a new machine. I've tried running the command with sudo, changing the permissions on the file with chown/chmod, and npm installing first. 

I have also made sure there are no global packages as per the note on the page

```
Woog-1s-Air:strapi woog_01$ npm ls strapi
@3.0.0-alpha.26.2 /Users/woog_01/Documents/platypusNEST/strapiTest/strapi
└── (empty)
```

I've also tried cleaning my npm cache and updating strapi

```
sudo npm cache clean
sudo npm update -g strapi@alpha
```
I've also tried `sudo npm unlink /usr/local/lib/node_modules/strapi-utils `

Nothing so far has worked.

**Comment by derrickmehaffy** [comment]
```
Linking strapi-utils...
npm ERR! path /usr/local/lib/node_modules/strapi-utils
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
```

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Problem is permissions related to your global modules location, very common on Linux, same likely applies to Macs. Most of this is going to change with the beta anyway

**Comment by derrickmehaffy** [comment]
Also **never use sudo with npm** https://givan.se/do-not-sudo-npm/

**Comment by patientplatypus** [comment]
I've gotten farther but I still am getting this to break.

I run the following shell script to setup the development environment. It reinstalls a fresh copy of node through nvm so I don't have issues. Probably not the best way to do it but whatever.

```
echo ***************
echo ***kill 1337***
echo ***************

kill $(lsof -t -i :1337)

echo *****************
echo ***curling nvm***
echo *****************

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

echo ********************************
echo ***reinstalling node from nvm***
echo ********************************

nvm install node

echo ***************************
echo ***sourcing export paths***
echo ***************************

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo **********************
echo ***cloning git repo***
echo **********************

git clone https://github.com/patientplatypus/strapi.git

echo ************************************
echo ***cding into repo and run setup***
echo ************************************

cd strapi && npm run setup

echo ******************************************************
echo ***starting new dev environment in empty directory ***
echo ******************************************************

mkdir devEnv && cd devEnv && strapi new myDevelopmentProject --dev

echo *********************
echo ***starting strapi***
echo *********************

cd myDevelopmentProject
npm i
npm install sqlite3 --save
strapi start
```

Then I attempt to get the new `DevelopmentProject` to run using the following:

```
cd strapi/devEnv/myDevelopmentProject/
strapi generate:plugin my-plugin
cd admin && npm run setup
```
Here is the output of that code:

```
InRhythm-1s-MacBook-Air:admin inrhythm_01$ npm run setup

> strapi-admin@3.0.0-alpha.26.2 presetup /Users/inrhythm_01/Documents/platypusNEST/espnAccount/pluginTutorial/strapi/packages/strapi-admin
> node ./scripts/preSetup.js


🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...

Packages installed successfully

> strapi-admin@3.0.0-alpha.26.2 setup /Users/inrhythm_01/Documents/platypusNEST/espnAccount/pluginTutorial/strapi/packages/strapi-admin
> node ./scripts/setup.js

🏗  Building the admin...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.26.2 prebuild: `cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.2 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/inrhythm_01/.npm/_logs/2019-05-22T14_46_58_313Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.26.2 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/inrhythm_01/.npm/_logs/2019-05-22T14_46_58_365Z-debug.log
InRhythm-1s-MacBook-Air:admin inrhythm_01$ cat  /Users/inrhythm_01/.npm/_logs/2019-05-22T14_46_58_365Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/inrhythm_01/.nvm/versions/node/v12.3.0/bin/node',
1 verbose cli   '/Users/inrhythm_01/.nvm/versions/node/v12.3.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.3.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle strapi-admin@3.0.0-alpha.26.2~presetup: strapi-admin@3.0.0-alpha.26.2
6 verbose lifecycle strapi-admin@3.0.0-alpha.26.2~presetup: unsafe-perm in lifecycle true
7 verbose lifecycle strapi-admin@3.0.0-alpha.26.2~presetup: PATH: /Users/inrhythm_01/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/inrhythm_01/Documents/platypusNEST/espnAccount/pluginTutorial/strapi/packages/strapi-admin/node_modules/.bin:/Users/inrhythm_01/.nvm/versions/node/v12.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle strapi-admin@3.0.0-alpha.26.2~presetup: CWD: /Users/inrhythm_01/Documents/platypusNEST/espnAccount/pluginTutorial/strapi/packages/strapi-admin
9 silly lifecycle strapi-admin@3.0.0-alpha.26.2~presetup: Args: [ '-c', 'node ./scripts/preSetup.js' ]
10 silly lifecycle strapi-admin@3.0.0-alpha.26.2~presetup: Returned: code: 0  signal: null
11 info lifecycle strapi-admin@3.0.0-alpha.26.2~setup: strapi-admin@3.0.0-alpha.26.2
12 verbose lifecycle strapi-admin@3.0.0-alpha.26.2~setup: unsafe-perm in lifecycle true
13 verbose lifecycle strapi-admin@3.0.0-alpha.26.2~setup: PATH: /Users/inrhythm_01/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/inrhythm_01/Documents/platypusNEST/espnAccount/pluginTutorial/strapi/packages/strapi-admin/node_modules/.bin:/Users/inrhythm_01/.nvm/versions/node/v12.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
14 verbose lifecycle strapi-admin@3.0.0-alpha.26.2~setup: CWD: /Users/inrhythm_01/Documents/platypusNEST/espnAccount/pluginTutorial/strapi/packages/strapi-admin
15 silly lifecycle strapi-admin@3.0.0-alpha.26.2~setup: Args: [ '-c', 'node ./scripts/setup.js' ]
16 silly lifecycle strapi-admin@3.0.0-alpha.26.2~setup: Returned: code: 1  signal: null
17 info lifecycle strapi-admin@3.0.0-alpha.26.2~setup: Failed to exec setup script
18 verbose stack Error: strapi-admin@3.0.0-alpha.26.2 setup: `node ./scripts/setup.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/Users/inrhythm_01/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18 verbose stack     at EventEmitter.emit (events.js:200:13)
18 verbose stack     at ChildProcess.<anonymous> (/Users/inrhythm_01/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:200:13)
18 verbose stack     at maybeClose (internal/child_process.js:1021:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
19 verbose pkgid strapi-admin@3.0.0-alpha.26.2
20 verbose cwd /Users/inrhythm_01/Documents/platypusNEST/espnAccount/pluginTutorial/strapi/packages/strapi-admin
21 verbose Darwin 15.6.0
22 verbose argv "/Users/inrhythm_01/.nvm/versions/node/v12.3.0/bin/node" "/Users/inrhythm_01/.nvm/versions/node/v12.3.0/bin/npm" "run" "setup"
23 verbose node v12.3.0
24 verbose npm  v6.9.0
25 error code ELIFECYCLE
26 error errno 1
27 error strapi-admin@3.0.0-alpha.26.2 setup: `node ./scripts/setup.js`
27 error Exit status 1
28 error Failed at the strapi-admin@3.0.0-alpha.26.2 setup script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

So it appears that the admin folder simply can't build the `./scripts/setup.js` file.

Why is this broken, or what am I doing wrong?

**Comment by patientplatypus** [comment]
Also this

```
[2019-05-22T14:46:33.420Z] info ☄️  Admin panel: http://localhost:4000/admin
[2019-05-22T14:46:33.421Z] info ⚡️ Server: http://localhost:1337
```

Seems to be broken when I run the strapi server - `localhost:4000` isn't up (checked by browser and `lsof`), but `localhost:1337/admin` is. Should I expect `localhost:4000` to be up, or is that console a misprint?

**Comment by maxbaluev** [comment]
I have same problems with last version

**Comment by derrickmehaffy** [comment]
@maxbaluev there is no development environment on port :4000 with the beta.

**Comment by maxbaluev** [comment]
Yes, sry, i have cached npm with old strapi.
