### ISSUE TITLE
How to Create Multilevel Categories through Relationships？

### ISSUE THREAD

**Issue by cdwmhcc** [strapi/strapi#3325]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

![image](https://user-images.githubusercontent.com/8030134/58392233-9ae3ff00-806b-11e9-8cf1-5e9109ff6628.png)

**Comment by nightire** [comment]
This is how I did:

![image](https://user-images.githubusercontent.com/1104018/58404873-c3362280-8098-11e9-81e8-2e5b25f830aa.png)

The `parent` field can be `null` (by default) which indicates the category is a root level, otherwise, its `parent` field points to its upper-level category.

It works like:

![image](https://user-images.githubusercontent.com/1104018/58405084-35a70280-8099-11e9-875b-27fbd0c820b8.png)

FYI, the lowest level is `Article` not `Category`, I only need two-level deep, but you can get as many levels as you want by using this simple relationship.

**Comment by cdwmhcc** [comment]
> This is how I did:
> 
> ![image](https://user-images.githubusercontent.com/1104018/58404873-c3362280-8098-11e9-81e8-2e5b25f830aa.png)
> 
> The `parent` field can be `null` (by default) which indicates the category is a root level, otherwise, its `parent` field points to its upper-level category.
> 
> It works like:
> 
> ![image](https://user-images.githubusercontent.com/1104018/58405084-35a70280-8099-11e9-875b-27fbd0c820b8.png)
> 
> FYI, the lowest level is `Article` not `Category`, I only need two-level deep, but you can get as many levels as you want by using this simple relationship.

哇，谢谢你。应该是可以的，我来试一下。

**Comment by nightire** [comment]
@cdwmhcc 没想到还是自家人~ 😂

**Comment by cdwmhcc** [comment]
> @cdwmhcc 没想到还是自家人~ 😂

自家人自家人😂😂😂

**Comment by cdwmhcc** [comment]
> @cdwmhcc 没想到还是自家人~ 😂

![image](https://user-images.githubusercontent.com/8030134/58408987-af42ee80-80a1-11e9-8f3d-e4dc0a1cce67.png)

方便再麻烦你一下不，这个一保存就报错，我想添加一个多选框这个可以实现吗？

**Comment by nightire** [comment]
> 这个一保存就报错

你说的报错指的是这种吗：

<details>
<summary>error Syntax Error: Expected Name, found Float "1.0"</summary>
```
GraphQLError: Syntax Error: Expected Name, found Float "1.0"
    at syntaxError (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at expectToken (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:1433:32)
    at parseName (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:98:15)
    at parseEnumValueDefinition (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:1031:14)
    at many (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:1521:16)
    at parseEnumValuesDefinition (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:1019:50)
    at parseEnumTypeDefinition (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:1003:16)
    at parseTypeSystemDefinition (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:720:16)
    at parseDefinition (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:144:16)
    at many (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:1524:16)
    at parseDocument (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:115:18)
    at Object.parse (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/node_modules/graphql/language/parser.js:50:10)
    at Object.addPolymorphicUnionType (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/services/Types.js:159:8)
    at Object.generateSchema (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/services/Schema.js:168:59)
    at Function.initialize (/Users/nightire/Code/github.com/choice-form/os-help-service/plugins/graphql/hooks/graphql/index.js:145:78)
    at /Users/nightire/Code/github.com/choice-form/os-help-service/node_modules/strapi/lib/hooks/index.js:52:31
    at after (/Users/nightire/Code/github.com/choice-form/os-help-service/node_modules/strapi/lib/hooks/index.js:153:39)
    at /Users/nightire/Code/github.com/choice-form/os-help-service/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/Users/nightire/Code/github.com/choice-form/os-help-service/node_modules/strapi/lib/hooks/index.js:164:17)
    at Object.onceWrapper (events.js:277:13)
    at Strapi.emit (events.js:189:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at onFinish (/Users/nightire/Code/github.com/choice-form/os-help-service/node_modules/strapi/lib/hooks/index.js:44:12)
    at Promise.all.then (/Users/nightire/Code/github.com/choice-form/os-help-service/node_modules/strapi-hook-bookshelf/lib/index.js:1197:55)
```
</details>

**Comment by alexandrebodin** [comment]
Hi @cdwmhcc,

We are closing this issue as it is a topic for a [slack](https://slack.strapi.io) discussion.

Please try to keep the issues in english so everyone can help contribute :)

**Comment by nightire** [comment]
@cdwmhcc 

我试了一下你的设置，有以下几个问题：

1. Enumeration Field 的值应该是一行一个，而不是用逗号分割。这是一个 [known issue](https://github.com/strapi/strapi/pull/3261)

2. Enumeration Field 的值似乎不能是纯数字（以及小数，以及非纯数字但带有小数点，比如 `v1.1`等），这应该是 strapi 验证规则不够宽松导致的

以上问题目前也没什么太好的解决办法，我用了这样的办法：

![image](https://user-images.githubusercontent.com/1104018/58410242-5aed3e00-80a4-11e9-9525-31b38558bea4.png)

但你问的是多选框对吧？所以 Enumeration Field 可能无法满足你的需求，我有类似的需求（给文章打标签），用多对多的关系实现的。

**Comment by cdwmhcc** [comment]
> @cdwmhcc
> 
> 我试了一下你的设置，有以下几个问题：
> 
> 1. Enumeration Field 的值应该是一行一个，而不是用逗号分割。这是一个 [known issue](https://github.com/strapi/strapi/pull/3261)
> 2. Enumeration Field 的值似乎不能是纯数字（以及小数，以及非纯数字但带有小数点，比如 `v1.1`等），这应该是 strapi 验证规则不够宽松导致的
> 
> 以上问题目前也没什么太好的解决办法，我用了这样的办法：
> 
> ![image](https://user-images.githubusercontent.com/1104018/58410242-5aed3e00-80a4-11e9-9525-31b38558bea4.png)
> 
> 但你问的是多选框对吧？所以 Enumeration Field 可能无法满足你的需求，我有类似的需求（给文章打标签），用多对多的关系实现的。

明白了，原来是这样子的，用你的方法可以来做，没有问题。看来strapi有些地方还是有些不尽人意的。
非常谢谢你的帮助！好开心

**Comment by derrickmehaffy** [comment]
@cdwmhcc @nightire

Although this issue is closed please use English only on this project, you are welcome to reach out to each other via another means to use a different language

**Comment by cdwmhcc** [comment]
> @cdwmhcc @nightire
> 
> Although this issue is closed please use English only on this project, you are welcome to reach out to each other via another means to use a different language

OK
