### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by wawezz** [strapi/strapi#3362]
node server.js

/opt/shtrudel_campblog/back/server.js:15
  strapi.start();
         ^

TypeError: strapi.start is not a function
    at /opt/shtrudel_campblog/back/server.js:15:10
    at Object.<anonymous> (/opt/shtrudel_campblog/back/server.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camp_blog_main@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the camp_blog_main@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-02T19_31_44_875Z-debug.log
root@blog:/opt/shtrudel_campblog/back# strapi -v
3.0.0-alpha.26.2

**Comment by wawezz** [comment]
error when you run npm audit fix it change strapi version from alpha to next

**Comment by Turkyden** [comment]
OK, I have meeted the same problem too. You can try to fixed like this:

`/server.js`

```js
#!/usr/bin/env node
'use strict';

/**
 * Use `server.js` to run your application without `$ strapi start`.
 * To start the server, run: `$ npm start`.
 *
 * This is handy in situations where the Strapi CLI is not relevant or useful.
 */

process.chdir(__dirname);

(() => {
  const strapi = require('strapi');
  strapi().start();
})();
```

When you run npm audit fix it change strapi version from alpha to next.

In the v3.0.0 + of strapi  `strapi` => `strapi()`

```js
strapi().start();
```
