### ISSUE TITLE
Deployment on Apache2 + Passenger: Error in server.js

### ISSUE THREAD

**Issue by sschuchlenz** [strapi/strapi#3376]
When trying to deploy strapi to Apache + Passenger (we deploy a lot of meteorJS apps with this setup flawlessly), server.js leads to an error:

```
(() => {
  ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (module.js:384:17)
    at loadApplication (/usr/share/passenger/helper-scripts/node-loader.js:243:2)
    at setupEnvironment (/usr/share/passenger/helper-scripts/node-loader.js:214:2)
```

Has anyone run into that?

**Comment by alexandrebodin** [comment]
What version of node are you running ?

**Comment by sschuchlenz** [comment]
Nevermind, it was a problem with NVM (indeed using an outdated node version out of the box).
