### ISSUE TITLE
Beta version - creation of a new project throws error during "building your admin UI process"

### ISSUE THREAD

**Issue by AndreiGuk** [strapi/strapi#3383]
**Describe the bug**
Can't create new project after strapi start command. I receive an error during "building your admin UI process"

**Steps to reproduce the behavior**
NA

**Expected behavior**
Should build

**Screenshots**
NA

**Code snippets**
```
✖ Building your admin UI ...
{ Error: Command failed: npm run build
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! api@0.1.0 build: `strapi build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the api@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guk/.npm/_logs/2019-06-05T14_37_52_259Z-debug.log


> api@0.1.0 build /home/guk/futboloff/api
> strapi build

Building your admin UI with production configuration ...
ℹ Compiling Webpack

    at makeError (/usr/local/lib/node_modules/strapi/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/strapi/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 137,
  stdout:
   '\n> api@0.1.0 build /home/guk/futboloff/api\n> strapi build\n\nBuilding your admin UI with production configuration ...\nℹ Compiling Webpack\n',
  stderr:
   'Killed\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 137\nnpm ERR! api@0.1.0 build: `strapi build`\nnpm ERR! Exit status 137\nnpm ERR! \nnpm ERR! Failed at the api@0.1.0 build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/guk/.npm/_logs/2019-06-05T14_37_52_259Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run build',
  timedOut: false,
  killed: false }
```
**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.2
- Database: MongoDB
- Operating system: Ubuntu 18.04.

**Additional context**
NA

**Comment by gnimmelf** [comment]
@AndreiGuk check log for ENOMEM, as `errno 137 npm` is related to that.

**System**

Node.js version: 10.15.3
NPM version: 6.9.0
Strapi version: 3.0.0-beta.3
Database: SQLite3
Operating system: Ubuntu 18.04

**Additional context**

@strapi, I'm running this on a 1GB DO droplet, with install spikes CPU 73.04% and MEM 61.74. This should be OK, so I'm guessing that perhaps `node-sass` bumps it up too much on a spawn(?), as that is the last log entry before ENOMEM...

Would be swell if it could install on a mimimum DO droplet...

```
[...]
38552 verbose lifecycle node-sass@4.12.0~install: CWD: /opt/web-apps/io.intergate.strapi/node_modules/node-sass
38553 silly lifecycle node-sass@4.12.0~install: Args: [ '-c', 'node scripts/install.js' ]
38554 verbose stack Error: spawn ENOMEM
38554 verbose stack     at ChildProcess.spawn (internal/child_process.js:366:11)
38554 verbose stack     at spawn (child_process.js:538:9)
38554 verbose stack     at spawn (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:36:15)
38554 verbose stack     at runCmd_ (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:293:14)
38554 verbose stack     at runCmd (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:250:5)
38554 verbose stack     at runPackageLifecycle (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:213:3)
38554 verbose stack     at Array.<anonymous> (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
38554 verbose stack     at LOOP (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
38554 verbose stack     at chain (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
38554 verbose stack     at lifecycle_ (/home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:151:3)
38554 verbose stack     at /home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:90:9
38554 verbose stack     at /home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:203:12
38554 verbose stack     at /home/gnimmelf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:285:20
38554 verbose stack     at FSReqWrap.oncomplete (fs.js:154:5)
38555 verbose cwd /opt/web-apps/io.intergate.strapi
38556 verbose Linux 4.4.0-148-generic
38557 verbose argv "/home/gnimmelf/.nvm/versions/node/v10.15.3/bin/node" "/home/gnimmelf/.nvm/versions/node/v10.15.3/bin/npm" "install" "--production" "--no-optional"
38558 verbose node v10.15.3
38559 verbose npm  v6.9.0
38560 error code ENOMEM
38561 error errno ENOMEM
38562 error syscall spawn
38563 error spawn ENOMEM
38564 verbose exit [ 1, true ]

```

**Comment by alexandrebodin** [comment]
@AndreiGuk Try building the admin on a system with at least 2 to 4Go of ram. this error is due to Ram shortage.

**Comment by davidkartuzinski** [comment]
@AndreiGuk - You are correct in that Strapi can run on a minimal box.  A temporary solution is to build on a higher amount of RAM and after it is build, to downgrade back to the smaller box.

**Comment by heihachi88** [comment]
When you guys plan to fix this? You need a dedicated CI/CD machine to build this. But it can run easily on 512MB ram VPS.

**Comment by BriantAnthony** [comment]
All you have to do is modifying your .gitignore to include the build folder inside strapi. Run the build command locally, and push the code up to your production brand with the build folder in version control.

When you pull down your code on your live server you won't need to build it on your lower spec server :D

**Comment by alexandrebodin** [comment]
I'm closing this issue as it is clear what is the issue. We are already working on decreasing the memory footprint of the build. 

For now you can do the following:
- Build your admin locally and deploy it.
- Build in a CI with enough memory
- Increase your server RAM.
- commit (not the most recommended way) the build folder.
