### ISSUE TITLE
The new project created by the beta version can't be started

### ISSUE THREAD

**Issue by trlanfeng** [strapi/strapi#3390]
**Describe the bug**
I installed the new beta version. Then create a new project, but it can't be started.

**Steps to reproduce the behavior**
1. `npm i strapi@beta -g`
2. `strapi new strapi --quickstart`

**Code snippets**
```
➜  Code strapi new strapi --quickstart
🚀 Starting to create your Strapi application.


✅ Connected to the database

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
✔ Install plugin users-permissions.
✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

👌 Your new application strapi is ready at /Users/fengyu/Code/strapi.

⚡️ Change directory:
$ cd strapi

⚡️ Start application:
$ strapi start

[2019-06-06T06:10:30.855Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-06T06:10:30.857Z] error Error: Missing extensions folder. Please create one in your app root directory
    at module.exports (/Users/fengyu/.nvm/versions/node/v10.16.0/lib/node_modules/strapi/lib/core/load-extensions.js:18:11)
    at Strapi.load (/Users/fengyu/.nvm/versions/node/v10.16.0/lib/node_modules/strapi/lib/Strapi.js:242:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
➜  Code strapi start
⛔️ strapi start can only be used inside a Strapi project.
➜  Code cd strapi
➜  strapi strapi start
[2019-06-06T06:10:52.126Z] error strapi.start is not a function
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDB 4.0.9
- Operating system: macOS 10.14.5

**Comment by alexandrebodin** [comment]
Hi,

Sadly the process of installation you ran isn't beta but alpha (the logs arn't the same) 

It means that your global install of strapi somehow is still in alpha (you might need to run npm remove first or rm the global node module manually and all strapi related global modules).

Make sure to clear this before creating a new app.

**Comment by trlanfeng** [comment]
Thank you. I will do it.

**Comment by nvh95** [comment]
```
[2022-03-08T07:54:51.030Z] error Error: Missing api folder. Please create one in your app root directory
[2022-03-08T07:57:22.511Z] error Error: Missing extensions folder. Please create one in your app root directory
```
I experienced the same issue today and it turned out I had both `strapi` (version 3) and `@strapi/strapi` (version 4) in `package.json`. Just remove `strapi` and it's good.
```bash
npm uninstall strapi
```

```bash
yarn remove strapi
```
