### ISSUE TITLE
strapi-admin@3.0.0-alpha.6.7 postinstall bug node@4

### ISSUE THREAD

**Issue by clubery** [strapi/strapi#341]
I've never used strapi before, attempted to run the install following your docs here: https://strapi.io/documentation/getting-started/installation.html.

Installation fails with this:

```
> pngquant-bin@3.1.1 postinstall /opt/dev/strapi/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> strapi-admin@3.0.0-alpha.6.7 postinstall /opt/dev/strapi/node_modules/strapi-admin
> node ../strapi-helper-plugin/lib/internals/scripts/postinstall.js

/opt/dev/strapi/node_modules/strapi-helper-plugin/lib/internals/scripts/postinstall.js:2
const { exec } = require('child_process');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
(node) warning: possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at /usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:122:15
    at Array.filter (native)
    at load (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:120:21)
    at module.exports (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:35:5)
    at Object.Gauge._enableEvents (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/index.js:150:26)
    at Object.Gauge.enable (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/index.js:132:23)
    at EventEmitter.log.enableProgress (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:84:14)
    at stopRunning (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:19:45)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:44:24)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
`
npm WARN enoent ENOENT: no such file or directory, open '/opt/dev/strapi/package.json'
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-redux-saga@0.4.0 requires a peer of eslint@^3.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN strapi No description
npm WARN strapi No repository field.
npm WARN strapi No README data
npm WARN strapi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.6.7 postinstall: `node ../strapi-helper-plugin/lib/internals/scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.6.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pmax/.npm/_logs/2017-11-15T08_43_23_117Z-debug.log

**Comment by clubery** [comment]
Only seems to work with node v6.

**Comment by Aurelsicoko** [comment]
@clubery You're right, we highly recommend to use Node v8.x to use Strapi. We are using the latest available pattern so it won't work with the previous versions of Node.js.

I'm closing this issue, feel free to open a new one if you find an issue using Node v8.x.
