### ISSUE TITLE
Series content type name is not usable

### ISSUE THREAD

**Issue by trlanfeng** [strapi/strapi#3471]
**Describe the bug**
I created a new content type named 'series', if installed the 'graphql' plugin, the server can't be started. Uninstalled the 'graphql' plugin, then it works.

```
➜  strapi strapi develop
[2019-06-17T02:05:46.079Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-17T02:05:46.082Z] error Error: Field "Query.series" can only be defined once.
    at assertValidSDL (/Users/fengyu/Code/strapi/node_modules/graphql/validation/validate.js:89:11)
    at Object.buildASTSchema (/Users/fengyu/Code/strapi/node_modules/graphql/utilities/buildASTSchema.js:78:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/fengyu/Code/strapi/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:23:28)
    at makeExecutableSchema (/Users/fengyu/Code/strapi/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/fengyu/Code/strapi/node_modules/strapi-plugin-graphql/services/Schema.js:263:22)
    at Function.initialize (/Users/fengyu/Code/strapi/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:52:50)
    at /Users/fengyu/Code/strapi/node_modules/strapi/lib/hooks/index.js:52:31
    at after (/Users/fengyu/Code/strapi/node_modules/strapi/lib/hooks/index.js:153:39)
    at /Users/fengyu/Code/strapi/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/Users/fengyu/Code/strapi/node_modules/strapi/lib/hooks/index.js:164:17)
    at Object.onceWrapper (events.js:286:20)
    at Strapi.emit (events.js:198:13)
    at onFinish (/Users/fengyu/Code/strapi/node_modules/strapi/lib/hooks/index.js:44:12)
    at Promise.all.then (/Users/fengyu/Code/strapi/node_modules/strapi-hook-bookshelf/lib/index.js:890:56)
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.2
- Database: sqlite(--quickstart)
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
Please provide us your `Series.settings.json` file located in `api/series/models`

**Comment by trlanfeng** [comment]
```
{
  "connection": "default",
  "collectionName": "series",
  "info": {
    "name": "series",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "title": {
      "required": true,
      "type": "string"
    },
    "description": {
      "type": "text"
    },
    "posts": {
      "collection": "post",
      "via": "series"
    }
  }
}

```

I think the problem is the plural of 'series' is 'series' too.

**Comment by derrickmehaffy** [comment]
@trlanfeng I believe that is also the case, I would suggest you change the name of that model to see if that resolves the issue.

Either way, another look needs to be done with the plural converter for models.

**Comment by trlanfeng** [comment]
@derrickmehaffy After I changed the name of the model, it works fine.

**Comment by lauriejim** [comment]
Thank you for this report. I think we have the same issue with the content type `admin`.

**Comment by soupette** [comment]
You are right calling a content type `Series` with the `graphql` plugin installed breaks your app. However, your model's name should be singular so it should work with `Serie`.

**Comment by derrickmehaffy** [comment]
@soupette in english `series` is both singular and plural :wink:

**Comment by soupette** [comment]
My bad then

**Comment by ChristophAnastasiades** [comment]
I have the same problem with `audio`.

**Comment by soupette** [comment]
@ChristophAnastasiades I am not unable to reproduce the bug with audio as name for a content type.

Maybe the error is coming from somewhere else.

**Comment by jwerle** [comment]
@soupette I was able to reproduce this in my project. I was also able to reproduce this in a new project as well. Create an `audio` content type and set its collection name to `audio` as well. The issue occurs in the `strapi-plugin-graphql/services/schema-generator.js` because the plural form of `audio` is also `audio` while `audios` is also considered an accepted plural form of the word `audio`

The generated fields for the `Query` type appear to contain the duplicated property as expected:

```gql
audio(id: ID!): Audio                                                                                                                                                                                                                       
audio(sort: String, limit: Int, start: Int, where: JSON): [Audio]                                                                                                                                                                           
audioConnection(sort: String, limit: Int, start: Int, where: JSON): AudioConnection   
```

**Comment by loopion** [comment]
Hello. Just discovered a new reserved word while developing on it. 

1. Create a new app
1. Add GraphQL extension
1. Add a content-type called `energy`
1. run `strapi develop`

It will fail:

`[2020-05-09T21:18:37.563Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-09T21:18:37.565Z] error Error: Field "Query.energy" can only be defined once.
    at assertValidSDL (/Users/toto/strapi/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/Users/toto/strapi/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/toto/strapi/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (/Users/toto/strapi/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/toto/strapi/node_modules/strapi-plugin-graphql/services/schema-generator.js:85:20)
    at Object.initialize (/Users/toto/strapi/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:79:9)
    at /Users/toto/strapi/node_modules/strapi/lib/hooks/index.js:37:28`
