### ISSUE TITLE
Error after DB Connection Name change

### ISSUE THREAD

**Issue by LucasMatuszewski** [strapi/strapi#3482]
**Describe the bug**
I wanted to change Connection Name to something more descriptive (from "default" to "default local Mongo DEV". The Admin UI form passed this name but hang on Rebuild and I'v got an error in a console. I have to discard changes to build project again.

**Steps to reproduce the behavior**
1. Go to http://localhost:1337/admin/plugins/settings-manager/databases/development
2. Click on Connection Name and write something with spaces
3. Click on Save button
4. See error in a console

**Expected behavior**
If connection names should not contain spaces, please add this information + validation on a form.

**Screenshots**
![image](https://user-images.githubusercontent.com/28517564/59721796-673b6580-9222-11e9-8c09-6728827c93e7.png)

**Code snippets**
Error Log from Strapi in Console:
```
debug PUT /settings-manager/configurations/databases/default/development (54 ms)
[2019-06-18T21:23:53.637Z] info File changed: D:\Dev\Projects\Edukey_Next_Strapi\strapi\config\environments\development\database.json
error TypeError: strapi.models.core_store.forge is not a function
    at Object.get (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\core\init-core-store.js:61:12)
    at module.exports (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi-plugin-content-manager\config\functions\bootstrap.js:269:42)
    at Promise (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:344:11)
    at new Promise (<anonymous>)
    at execBootstrap (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:332:14)
    at Promise.all.Object.values.map.plugin (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:377:9)
    at Array.map (<anonymous>)
    at Strapi.runBootstrapFunctions (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:376:35)
    at Strapi.start (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:112:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-06-18T21:23:58.157Z] error TypeError: strapi.models.core_store.forge is not a function
    at Object.get (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\core\init-core-store.js:61:12)
    at module.exports (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi-plugin-email\config\functions\bootstrap.js:32:38)
    at Promise (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:344:11)
    at new Promise (<anonymous>)
    at execBootstrap (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:332:14)
    at Promise.all.Object.values.map.plugin (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:377:9)
    at Array.map (<anonymous>)
    at Strapi.runBootstrapFunctions (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:376:35)
    at Strapi.start (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\strapi\lib\Strapi.js:112:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**System**
- Node.js version: v10.14.1
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.5
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Closing as well known lack of validation on admin UI for unsupported/invalid entries containing spaces or special characters.
