### ISSUE TITLE
yarn setup failed in ubuntu18.4 and windows 10 (contribute propose)

### ISSUE THREAD

**Issue by aminsource** [strapi/strapi#3483]
for contribute propose 'yarn setup' in root of the repository failed in Ubuntu 18.4 and Windows 10 with following error
Nodejs version: v10.16.0
Npm version: 6.9.0
Yarn version: 1.16.0

```bash
.....
[5/5] Building fresh packages...
[1/17] ⠁ cypress
[2/17] ⠁ husky
[8/17] ⠁ node-sass
[7/17] ⠂ cwebp-bin
error /home/hooman/Projects/strapi/node_modules/metrohash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/hooman/Projects/strapi/node_modules/metrohash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/hooman/Projects/strapi/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hooman/Projects/strapi/node_modules/metrohash/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hooman/Projects/strapi/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hooman/.node-gyp/10.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hooman/.node-gyp/10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/hooman/Projects/strapi/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hooman/.node-gyp/10.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hooman/Projects/strapi/node_modules/metrohash',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/hooman/Projects/strapi/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/hooman/Projects/strapi/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/hooman/Projects/strapi/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/hooman/Projects/strapi/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/hooman/Projects/strapi/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/hooman/Projects/strapi/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.18.0-22-generic
gyp ERR! command "/usr/bin/node" "/home/hooman/Projects/strapi/node_modules/metrohash/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hooman/Projects/strapi/node_modules/metrohash




warning Error running install script for optional dependency: "/home/hooman/Projects/strapi/node_modules/xxhash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/hooman/Projects/strapi/node_modules/xxhash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/hooman/Projects/strapi/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hooman/Projects/strapi/node_modules/xxhash/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hooman/Projects/strapi/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hooman/.node-gyp/10.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hooman/.node-gyp/10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/hooman/Projects/strapi/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hooman/.node-gyp/10.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hooman/Projects/strapi/node_modules/xxhash',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/hooman/Projects/strapi/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/hooman/Projects/strapi/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/hooman/Projects/strapi/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/hooman/Projects/strapi/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/hooman/Projects/strapi/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/hooman/Projects/strapi/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.18.0-22-generic
gyp ERR! command \"/usr/bin/node\" \"/home/hooman/Projects/strapi/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/hooman/Projects/strapi/node_modules/xxhash
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by WeFlyCheap** [comment]
@aminsource for me it looks like you don't have 'make' installed on your ubuntu system? Try running the following command: sudo apt-get install build-essential.

**Comment by derrickmehaffy** [comment]
Aye yeah can confirm, it's one of the suggested packages with node

**Comment by aminsource** [comment]
> @aminsource for me it looks like you don't have 'make' installed on your ubuntu system? Try running the following command: sudo apt-get install build-essential.
Resolved thank you very much

**Comment by aminsource** [comment]
@WeFlyCheap  solved thank you very much
