### ISSUE TITLE
Files upload fails on files larger than 2mb strapi-provider-upload-aws-s3 

### ISSUE THREAD

**Issue by inverleighdigital** [strapi/strapi#3499]
**Describe the bug**
In strapi admin when attempting to uploading files greater than 2mb the upload fails.

**Steps to reproduce the behavior**
1. Go to strapi admin
2. Go to files upload
3. drag and drop or browse and select file greater than 2mb
4. wait for upload to fail and see error

**Expected behavior**
Files greater than 2mb should upload successfully.

**Screenshots**
none

**Code snippets**
NA
**System**
- Node.js version: 12.00
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.6 and 3.0.0-beta.6 . may impact earlier versions.
- Database: Mongo DB
- Operating system: Ubuntu linux

**Additional context**
Larger uploads worked fine in alpha versions.
Confirmed that Maximum size allowed (in MB) is set to 1000 and S3 bucket is setup correctly. Uploads to s3 bucket also work correctly.

**Comment by lauriejim** [comment]
Hello! This issue is probably caused by your nginx configuration.
Or a server config that not allow files upload on your server for 2mb and more.

This issue is not related to Strapi.

**Comment by inverleighdigital** [comment]
Thanks we can close this issue. I have tested and confirmed it is due nginx configuration.

**Comment by tommasongr** [comment]
Hi there! I'm actually experiencing this problem too. I'm trying to implement a provider for Linode Object Storage (S3 compatible) and file upload of more than 2mb fails. It can't be a file system problem since manually I'm able to upload files of any dimension.

The promise reject with this error:
```shell
[2020-10-22T21:42:15.336Z] [2020-10-22t21:42:15.331z] error Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ClientRequest.end (_http_outgoing.js:788:7)
    at features.constructor.writeBody (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/aws-sdk/lib/http/node.js:137:14)
    at ClientRequest.<anonymous> (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/aws-sdk/lib/http/node.js:102:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:606:11)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
[2020-10-22T21:42:15.337Z] error Error: Internal Server Error
    at convertToStrapiError (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/errors.js:36:26)
    at Object.upload (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.uploadFileAndPersist (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/services/Upload.js:153:5)
    at async Promise.all (index 0)
    at async Object.upload (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/services/Upload.js:139:12)
    at async uploadFiles (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/controllers/upload/admin.js:186:27)
    at async Object.upload (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/controllers/Upload.js:64:5)
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-utils/lib/policy.js:68:5
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-10-22T21:42:15.338Z] debug POST /upload (3016 ms) 500
```

This is the implementation:
```js
const AWS = require('aws-sdk')

const trimParam = (str) => (typeof str === 'string' ? str.trim() : undefined)

module.exports = {
    init(providerOptions) {
        const S3 = new AWS.S3({
            accessKeyId: trimParam(providerOptions.accessKeyId),
            secretAccessKey: trimParam(providerOptions.secretAccessKey),
            apiVersion: '2006-03-01',
            endpoint: new AWS.Endpoint(providerOptions.cluster),
            params: {
                Bucket: providerOptions.bucket,
            },
        })

        return {
            upload(file) {
                return new Promise((resolve, reject) => {
                    // upload file on S3 bucket
                    const path = file.path ? `${file.path}/` : ''
                    S3.upload(
                        {
                            Key: `${path}${file.hash}${file.ext}`,
                            Body: Buffer.from(file.buffer, 'binary'),
                            ACL: 'public-read',
                            ContentType: file.mime,
                        },
                        (err, data) => {
                            strapi.log.debug(this)
                            if (err) {
                                return reject(err)
                            }

                            file.url = data.Location

                            resolve()
                        }
                    )
                })
            },
            delete(file) {
                return new Promise((resolve, reject) => {
                    // delete file on S3 bucket
                    const path = file.path ? `${file.path}/` : ''
                    S3.deleteObject(
                        {
                            Key: `${path}${file.hash}${file.ext}`,
                        },
                        (err, data) => {
                            if (err) {
                                return reject(err)
                            }

                            resolve()
                        }
                    )
                })
            },
        }
    },
}
```

Any idea on what this could be? Thanks

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
