### ISSUE TITLE
If User or Roles are on another database Documentation plugin causes Strapi Crash

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3502]
**Describe the bug**

With my [project](https://github.com/canonn-science/CAPIv2-Strapi/tree/update/strapi-beta) if you override the `Users` or `Roles` models and change their default connection to another database (In my project both of these models are on the database connection `user` while the rest of my project is on the database connection `default`) and try to start Strapi in production or staging it will crash due to the documentation plugin. (If moving Roles and no documentation plugin it still crashes)

Removing these overrides for the default connection allows the application to start normally

Error message (with a console.log added):

```
dmehaffy:~/Github/Canonn/CAPIv2-Strapi$ NODE_ENV=production strapi start
[ 'plugins',
  'users-permissions',
  'models',
  'role',
  'associations' ]
(node:2174) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at Object.generateResponseComponent (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-documentation/services/Documentation.js:1042:8)
    at Object.keys.reduce (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-documentation/services/Documentation.js:203:18)
    at Array.reduce (<anonymous>)
    at Object.createPluginDocumentationFile (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-documentation/services/Documentation.js:195:45)
    at Object.checkIfPluginDocNeedsUpdate (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-documentation/services/Documentation.js:64:12)
    at pluginsWithDocumentationNeeded.forEach.plugin (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-documentation/config/functions/bootstrap.js:38:46)
    at Array.forEach (<anonymous>)
    at module.exports (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-documentation/config/functions/bootstrap.js:28:34)
(node:2174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2174) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2174) UnhandledPromiseRejectionWarning: Error: Impossible to determine the use ORM for the model role.
    at Strapi.query (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi/lib/Strapi.js:437:13)
    at Object.plugin.queries (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi/lib/core/bootstrap.js:159:21)
    at Object.initialize (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:501:8)
    at module.exports (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-users-permissions/config/functions/bootstrap.js:156:65)
(node:2174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2019-06-21T10:12:13.549Z] warn The bootstrap function is taking unusually long to execute (3500 miliseconds).
[2019-06-21T10:12:13.551Z] warn Make sure you call it?
[2019-06-21T10:12:13.553Z] warn The bootstrap function is taking unusually long to execute (3500 miliseconds).
[2019-06-21T10:12:13.553Z] warn Make sure you call it?
```

Console.log of `node_modules/strapi-plugin-documentation/services/Documentation.js`

```
    const associationGetter = isPlugin
      ? [...this.getModelForPlugin(tag, plugin), 'associations']
      : ['models', tag, 'associations'];
    console.log(associationGetter);   <------- HERE
    const attributesObject = _.get(strapi, attributesGetter);
    const privateAttributes = this.getPrivateAttributes(attributesObject);
    const modelAssociations = _.get(strapi, associationGetter);
    const { attributes } = this.getModelAttributes(attributesObject);
    const associationsWithUpload = modelAssociations
      .filter(association => {
        return association.plugin === 'upload';
      })
```

**Steps to reproduce the behavior**
1. Override your `User.settings.json` & `Role.settings.json` to another database
2. Install the Documentation plugin
3. Try to start your application in `production` or `staging`

**Expected behavior**
Overriding the Users and Roles should not cause Strapi to crash, I'm guessing that there was some hard coded paths somewhere or something isn't properly using the extensions override

**Screenshots**

![image](https://user-images.githubusercontent.com/8593673/59916244-79103a80-93d3-11e9-8616-761583899f5f.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10
- NPM version: v6
- Strapi version: Beta.6
- Database: MariaDB 10.3 (MySQL)
- Operating system: Ubuntu 18.04

**Additional context**

Side note, if you remove the documentation plugin and still override the roles, Strapi will still crash with a different error:

```
(node:3718) UnhandledPromiseRejectionWarning: Error: Impossible to determin
e the use ORM for the model role.
    at Strapi.query (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi/lib/Strapi.js:437:13)
    at Object.plugin.queries (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi/lib/core/bootstrap.js:159:21)
    at Object.initialize (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:501:8)
    at module.exports (/home/dmehaffy/Github/Canonn/CAPIv2-Strapi/node_modules/strapi-plugin-users-permissions/config/functions/bootstrap.js:156:65)
(node:3718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-06-21T10:24:10.063Z] warn The bootstrap function is taking unusually long to execute (3500 miliseconds).
[2019-06-21T10:24:10.065Z] warn Make sure you call it?
```

Removing the `Role` Override but keeping the `Users` one will allow strapi to start fine.

**Comment by derrickmehaffy** [comment]
I've created a test project for this in which you can see the errors: https://github.com/derrickmehaffy/strapi_issue_3502

Create two databases + users in MySQL:
```
user: test
pass: test
DB1: test
DB2: test_user
```

I've included two SQL dumps you can import that include both a normal user and admin user with:
```
username: test
password: test1234
```

**Comment by derrickmehaffy** [comment]
Nevermind, I'm an idiot and mistyped `users` as `user` :man_facepalming:
