### ISSUE TITLE
Strapi development environment build broken in Windows 10

### ISSUE THREAD

**Issue by kktam** [strapi/strapi#3509]
**Describe the bug**
Building development environment for strapi with "yarn setup" resulted in following error:

```
yarn run v1.16.0
$ yarn && yarn build
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.8: The platform "win32" is incompatible with this module.
info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > enzyme-adapter-react-16@1.12.1" has unmet peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.12.1" has unmet peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.11.0" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.8.6" has unmet peer dependency "react@^16.0.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.13.2" has unmet peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-plugin-redux-saga@1.0.0" has unmet peer dependency "redux-saga@>= 0.11.1 < 1 || >= 1.0.0".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-hook-bookshelf > bookshelf@0.14.2" has unmet peer dependency "knex@>=0.6.10 <0.15.0".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-plugin-documentation > react-intl@2.9.0" has unmet peer dependency "prop-types@^15.5.4".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-plugin-graphql > graphql-playground-middleware-koa@1.6.12" has unmet peer dependency "koa@^2".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-plugin-graphql > graphql-type-datetime@0.2.4" has incorrect peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-plugin-graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-f8ff7989-3c9f-4158-9c8f-c9a8ef71de69 > strapi-plugin-users-permissions > grant-koa@4.5.1" has unmet peer dependency "koa@>=0.x.x".
[5/5] Building fresh packages...
[8/17] ⠂ node-sass
[14/17] ⠂ core-js
[10/17] ⠂ metrohash
[11/17] ⠄ xxhash
error C:\Users\n\code\strapi\fork\strapi\node_modules\metrohash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\n\code\strapi\fork\strapi\node_modules\metrohash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\n\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
```

**Steps to reproduce the behavior**
1. Clone Strapi
2. run yarn setup

**Expected behavior**
Build success.

**Screenshots**
See error trace above.

**Code snippets**
latest version in Github

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0_beta.5
- Database: sqlite
- Operating system: Windows 10 professional
- Others:  python 2.7 and python 3.7 installed with Chocolatey

**Additional context**

**Comment by derrickmehaffy** [comment]
https://github.com/electron-userland/electron-forge/issues/585

**Comment by derrickmehaffy** [comment]
Guessing you are missing them in your %PATH%

**Comment by kktam** [comment]
by hand testing python 3.x command, python no longer accepts print without brackets.

the correct version is

```
>>> import sys; print ("%s.%s.%s" % sys.version_info[:3]);
3.7.3
```

**Comment by derrickmehaffy** [comment]
You need python 2.7 to rebuild native node modules.

Also: `3.0.0_beta.5` update to the latest version ;) beta.7

**Comment by derrickmehaffy** [comment]
Also `node-gyp` isn't something Strapi can control, it's another package's depends. So for now I'm marking this as closed as it isn't an issue with Strapi directly but user environment.

**Comment by derrickmehaffy** [comment]
another quick google search reference: https://github.com/nodejs/node-gyp

**Comment by kktam** [comment]
I had python 2.7 and 3.7 both installed. I now had to change the environment PATH to put 2.7 first.

Now that I passed the first error. I run into the next error.  Here is the error trace.

```
yarn run v1.16.0
$ yarn && yarn build
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.8: The platform "win32" is incompatible with this module.
info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > enzyme-adapter-react-16@1.12.1" has unmet peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.12.1" has unmet peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.11.0" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.8.6" has unmet peer dependency "react@^16.0.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.13.2" has unmet peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-plugin-redux-saga@1.0.0" has unmet peer dependency "redux-saga@>= 0.11.1 < 1 || >= 1.0.0".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-hook-bookshelf > bookshelf@0.14.2" has unmet peer dependency "knex@>=0.6.10 <0.15.0".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-plugin-documentation > react-intl@2.9.0" has unmet peer dependency "prop-types@^15.5.4".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-plugin-graphql > graphql-playground-middleware-koa@1.6.12" has unmet peer dependency "koa@^2".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-plugin-graphql > graphql-type-datetime@0.2.4" has incorrect peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-plugin-graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-d92a0876-f9a5-4867-b817-8b11b5d8d12e > strapi-plugin-users-permissions > grant-koa@4.5.1" has unmet peer dependency "koa@>=0.x.x".
[5/5] Building fresh packages...
[10/17] ⠄ metrohash
[11/17] ⠄ xxhash
[16/17] ⡀ strapi
[8/17] ⡀ node-sass
error C:\Users\n\code\strapi\fork\strapi\node_modules\metrohash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\n\code\strapi\fork\strapi\node_modules\metrohash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\metrohash\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\n\\.node-gyp\\10.15.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\n\\.node-gyp\\10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\n\\.node-gyp\\10.15.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\metrohash',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\metrohash\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\n\code\strapi\fork\strapi\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\n\code\strapi\fork\strapi\node_modules\metrohash
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0




warning Error running install script for optional dependency: "C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\xxhash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\xxhash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp info spawn C:\\Python27\\python.EXE
gyp info spawn args [ 'C:\\\\Users\\\\n\\\\code\\\\strapi\\\\fork\\\\strapi\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\n\\\\code\\\\strapi\\\\fork\\\\strapi\\\\node_modules\\\\xxhash\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\n\\\\code\\\\strapi\\\\fork\\\\strapi\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\n\\\\.node-gyp\\\\10.15.3\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\n\\\\.node-gyp\\\\10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\n\\\\code\\\\strapi\\\\fork\\\\strapi\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\n\\\\.node-gyp\\\\10.15.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\n\\\\code\\\\strapi\\\\fork\\\\strapi\\\\node_modules\\\\xxhash',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\n\\\\code\\\\strapi\\\\fork\\\\strapi\\\\node_modules\\\\xxhash\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp info spawn C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\node-gyp\\lib\\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\n\\\\code\\\\strapi\\\\fork\\\\strapi\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\n\\code\\strapi\\fork\\strapi\\node_modules\\xxhash
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
MSBUILD : error MSB4132: The tools version \"2.0\" is unrecognized. Available tools versions are \"4.0\"."
info This module is OPTIONAL, you can safely ignore this error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kktam** [comment]
Do I need to completely remove python 3.7 from the environment to build strapi?

**Comment by kktam** [comment]
xxhash [https://github.com/Cyan4973/xxHash](https://github.com/Cyan4973/xxHash) in Windows 10 required vs build tools to compile.

This solves my problem:

```
 npm install --global --production windows-build-tools
```

**Comment by kktam** [comment]
Build success.

```
yarn run v1.16.0
$ yarn && yarn build
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.8: The platform "win32" is incompatible with this module.
info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > enzyme-adapter-react-16@1.12.1" has unmet peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.12.1" has unmet peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.11.0" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.8.6" has unmet peer dependency "react@^16.0.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.13.2" has unmet peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-plugin-redux-saga@1.0.0" has unmet peer dependency "redux-saga@>= 0.11.1 < 1 || >= 1.0.0".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-hook-bookshelf > bookshelf@0.14.2" has unmet peer dependency "knex@>=0.6.10 <0.15.0".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-plugin-documentation > react-intl@2.9.0" has unmet peer dependency "prop-types@^15.5.4".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-plugin-graphql > graphql-playground-middleware-koa@1.6.12" has unmet peer dependency "koa@^2".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-plugin-graphql > graphql-type-datetime@0.2.4" has incorrect peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-plugin-graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-d00a15a5-743d-48a0-a871-86573b91918f > strapi-plugin-users-permissions > grant-koa@4.5.1" has unmet peer dependency "koa@>=0.x.x".
[5/5] Building fresh packages...
$ lerna run --stream build --no-private
lerna notice cli v3.13.4
lerna info Executing command in 1 package: "yarn run build"
strapi-helper-plugin: $ rimraf dist
strapi-helper-plugin: $ rollup -c
strapi-helper-plugin:
strapi-helper-plugin: ./lib/src/index.js → dist/strapi-helper-plugin.cjs.min.js, dist/strapi-helper-plugin.esm.min.js...
strapi-helper-plugin: ┌───────────────────────────────────────────────────────┐
strapi-helper-plugin: │                                                       │
strapi-helper-plugin: │   Destination: dist/strapi-helper-plugin.cjs.min.js   │
strapi-helper-plugin: │   Bundle Size:  126.83 KB                             │
strapi-helper-plugin: │   Minified Size:  126.82 KB                           │
strapi-helper-plugin: │   Gzipped Size:  20.85 KB                             │
strapi-helper-plugin: │                                                       │
strapi-helper-plugin: └───────────────────────────────────────────────────────┘
strapi-helper-plugin: ┌───────────────────────────────────────────────────────┐
strapi-helper-plugin: │                                                       │
strapi-helper-plugin: │   Destination: dist/strapi-helper-plugin.esm.min.js   │
strapi-helper-plugin: │   Bundle Size:  100.56 KB                             │
strapi-helper-plugin: │   Minified Size:  100.53 KB                           │
strapi-helper-plugin: │   Gzipped Size:  19.57 KB                             │
strapi-helper-plugin: │                                                       │
strapi-helper-plugin: └───────────────────────────────────────────────────────┘
strapi-helper-plugin: created dist/strapi-helper-plugin.cjs.min.js, dist/strapi-helper-plugin.esm.min.js in 8.5s
lerna success run Ran npm script 'build' in 1 package in 10.3s:
lerna success - strapi-helper-plugin
Done in 41.08s.
```

**Comment by ednsinf** [comment]
This issue occurs here so:

PS D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back> npm i --build-from-source sqlite3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> sqlite3@5.0.1 install D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
Compilando os projetos desta solução um por vez. Para habilitar o build paralelo, adicione a opção "-m".
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3\build\Release\\nothing.lib
  unpack_sqlite_dep
  'C:\Users\Edney' não é reconhecido como um comando interno
  ou externo, um programa operável ou um arquivo em lotes.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for '..\..\deps\sqlite-autoconf-3320300.tar.gz' exited with code 1. [D:\Meus Projetos\Comprebusca\comprebusca\compr
ebusca-back\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Edney Silva\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Edney Silva\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Meus Projetos\\Comprebusca\\comprebusca\\comprebusca-back\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\Meus Projetos\\Comprebusca\\comprebusca\\comprebusca-back\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Edney Silva\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Meus Projetos\\Comprebusca\\comprebusca\\comprebusca-back\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not o

**Comment by derrickmehaffy** [comment]
```
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "D:\Meus Projetos\Comprebusca\comprebusca\comprebusca-back\node_modules\sqlite3\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
```

It's trying to build a package from sources since a binary doesn't exist for your OS build version, I would suggest following the instructions for this package to install standard windows build tools:

https://www.npmjs.com/package/windows-build-tools
