### ISSUE TITLE
I can't send an image with graphQl request

### ISSUE THREAD

**Issue by renanbronchart** [strapi/strapi#3516]
**Describe the bug**
Hello,
I try to upload an image directly with graphQl mutation but it doesn't seem to work.

**Steps to reproduce the behavior**

- I work on Vue.js project
- I have form with input file.
```
      <input
        @change="upload($event)"
        ref="file"
        type="file"
        name="fileInput[]"
        id="fileInput"
        class="inputfile inputfile-upload"
        capture="user"
      >
```

- function ```upload```:
```
const formData = new FormData()

formData.append('file', this.$refs.file.files[0])
axios.post('/graphql', {
   query: createFile(formData.get('file')),
})
```

function ```createFile```:
```
createFile = (file) => {
  return `
    mutation {
      upload(file: "${file}") {
        name
        url
      }
    }`
}
```

- Error of response display on network:
```
{"errors":[{"message":"Expected type Upload!, found \"[object File]\"; ‘Upload’ scalar literal unsupported.","locations":[{"line":3,"column":20}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["Error: ‘Upload’ scalar literal unsupported.","    at GraphQLScalarType.parseLiteral (/var/www/api/plugins/graphql/node_modules/graphql-upload/lib/GraphQLUpload.js:14:11)","    at isValidScalar (/var/www/api/plugins/graphql/node_modules/graphql/validation/rules/ValuesOfCorrectType.js:175:28)","    at Object.StringValue (/var/www/api/plugins/graphql/node_modules/graphql/validation/rules/ValuesOfCorrectType.js:144:14)","    at Object.enter (/var/www/api/plugins/graphql/node_modules/graphql/language/visitor.js:334:29)","    at Object.enter (/var/www/api/plugins/graphql/node_modules/graphql/language/visitor.js:385:25)","    at visit (/var/www/api/plugins/graphql/node_modules/graphql/language/visitor.js:252:26)","    at Object.validate (/var/www/api/plugins/graphql/node_modules/graphql/validation/validate.js:63:22)","    at validate (/var/www/api/plugins/graphql/node_modules/apollo-server-core/dist/requestPipeline.js:175:32)","    at Object.<anonymous> (/var/www/api/plugins/graphql/node_modules/apollo-server-core/dist/requestPipeline.js:113:42)","    at Generator.next (<anonymous>)","    at fulfilled (/var/www/api/plugins/graphql/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}}}]}
```

- I try to send directly the image buffer, but this error was displayed:
```
{"statusCode":413,"error":"Request Entity Too Large","message":"request entity too large"}
```

- I try to send directly the image binary string, but this error was displayed:
```
{"errors":[{"message":"Syntax Error: Invalid character within String: \"\\u0000\".","locations":[{"line":3,"column":25}],...
```

**Expected behavior**
I would like to upload image with graphQl mutation.
What's the Upload type asked by api?

**System**
- Node.js version: 10.13.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.25.2

Thanks a lot for response.

**Comment by derrickmehaffy** [comment]
@renanbronchart `Strapi version: 3.0.0-alpha.25.2` please test with the Beta and a fresh project as the Alpha is no longer supported

**Comment by renanbronchart** [comment]
> @renanbronchart `Strapi version: 3.0.0-alpha.25.2` please test with the Beta and a fresh project as the Alpha is no longer supported

Hello,
thanks for reply, I updated my strapi version to 3.0.0-beta.7, and problem persist.
I can't upload image with upload endpoint on graphql.

Can you help me?
Thanks a lot
