### ISSUE TITLE
BSONObj size is invalid. Max size is 16MB

### ISSUE THREAD

**Issue by abhishekchotaliya** [strapi/strapi#3527]
**Describe the bug**
While executing the simple light weight graphql query, this is the issue I faced. The data is actually more than 16MB in this case.

**Steps to reproduce the behavior**
1. Go to GraphQL Playground
2. Execute simple query
3. The error will come

**Expected behavior**
The standard result

**Screenshots**
![Capture](https://user-images.githubusercontent.com/10126210/60104240-addb1380-977e-11e9-9a4d-afc4a02c5f8d.PNG)

**System**
- Node.js version: 10.16 LTS
- NPM version: 6.9.0
- Strapi version: 3.0.0 @beta.7
- Database: MongoDB
- Operating system: Linux (Ubuntu 18)

**Error**
```
{
 "errors": [
   {
     "message": "BSONObj size: 18443422 (0x1196C9E) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5d121edff1ae1b59c67f4edc')",
     "locations": [
       {
         "line": 2,
         "column": 3
       }
     ],
     "path": [
       "tblsessions"
     ],
     "extensions": {
       "code": "INTERNAL_SERVER_ERROR",
       "exception": {
         "ok": 0,
         "errmsg": "BSONObj size: 18443422 (0x1196C9E) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5d121edff1ae1b59c67f4edc')",
         "code": 10334,
         "codeName": "BSONObjectTooLarge",
         "name": "MongoError",
         "stacktrace": [
           "MongoError: BSONObj size: 18443422 (0x1196C9E) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5d121edff1ae1b59c67f4edc')",
           "    at Connection.<anonymous> (/opt/aiTester/api/node_modules/mongodb-core/lib/connection/pool.js:443:61)",
           "    at Connection.emit (events.js:198:13)",
           "    at processMessage (/opt/aiTester/api/node_modules/mongodb-core/lib/connection/connection.js:364:10)",
           "    at Socket.<anonymous> (/opt/aiTester/api/node_modules/mongodb-core/lib/connection/connection.js:533:15)",
           "    at Socket.emit (events.js:198:13)",
           "    at addChunk (_stream_readable.js:288:12)",
           "    at readableAddChunk (_stream_readable.js:269:11)",
           "    at Socket.Readable.push (_stream_readable.js:224:10)",
           "    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"
         ]
       }
     }
   }
 ],
 "data": {
   "tblsessions": null
 }
}
```

**Comment by lauriejim** [comment]
Hello!
I just check and this error come from MongoDB and it's not related to Strapi.
Can you confirm by checking this error on Google please.

**Comment by derrickmehaffy** [comment]
Aye I can confirm this is not a Strapi problem but is a mongo issue: https://jira.mongodb.org/browse/SERVER-14213

Marking as closed.
