### ISSUE TITLE
strapi 3.0.0@beta.7 not working. Failing during quickstart

### ISSUE THREAD

**Issue by vickylance** [strapi/strapi#3542]
**Describe the bug**

I installed strapi on my newly created gcloud vm instance. Using nodejs version 10.16.0

**Steps to reproduce the behavior**

1 Installed using `npm i -g strapi@beta`
2 tried to create a new project using `strapi new cms --quickstart`

**Expected behavior**

bootstrap a new strapi project

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.7
- Database: sqlite
- Operating system: ubuntu 18

**Additional context**

Error log:

```
vigneshs6993@vickylance:~/projects/vickylance$ strapi new temp --quickstart
🚀 Creating your Strapi application.
✅ Connected to the database
🏗  Application generation:
✔ Copying files ...
✖ Installing dependencies ...
{ Error: Command failed: npm install --production --no-optional
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated 
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated postcss-smart-import@0.7.6: This project is not maintained anymore. Please use postcss-import instead.
npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security pa
tches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security pa
tches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated @hapi/joi@15.0.0: This version has been deprecated
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security p
atches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security p
atches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and securi
ty patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
> node-sass@4.12.0 install /home/vigneshs6993/projects/vickylance/temp/node_modules/node-sass
> node scripts/install.js
    at makeError (/home/vigneshs6993/.nvs/node/10.16.0/x64/lib/node_modules/strapi/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/vigneshs6993/.nvs/node/10.16.0/x64/lib/node_modules/strapi/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
stdout:
   '\n> node-sass@4.12.0 install /home/vigneshs6993/projects/vickylance/temp/node_modules/node-sass\n> node scripts/install.js\n\n',
  stderr:
   'npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this\nnpm WARN deprecated package has been deprecated in favor of directly\nnpm WARN deprecated including core-js/stable (to polyfill ECMAScript\nn
pm WARN deprecated features) and regenerator-runtime/runtime\nnpm WARN deprecated (needed to use transpiled generator functions):\nnpm WARN deprecated \nnpm WARN deprecated   > import "core-js/stable";\nnpm WARN depr
ecated   > import "regenerator-runtime/runtime";\nnpm WARN deprecated postcss-smart-import@0.7.6: This project is not maintained anymore. Please use postcss-import instead.\nnpm WARN deprecated boom@5.2.0: This versi
on has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at thi
s time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at \'https://github.com/formatjs
/formatjs/tree/master/packages/intl-relativeformat#migration-guide\'\nnpm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to t
he latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated flatten@
1.0.2: I wrote this module a very long time ago; you should use something else.\nnpm WARN deprecated @hapi/joi@15.0.0: This version has been deprecated\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in mai
ntenance only, flatted is its successor.\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\nnpm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at le
ast to actual version of core-js@2.\nnpm WARN deprecated mailcomposer@3.12.0: This project is unmaintained\nnpm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this dis
tribution is no longer supported and may contain bugs and critical security issues.\nnpm WARN deprecated buildmail@3.10.0: This project is unmaintained\nnpm WARN deprecated hoek@2.16.3: This version has been deprecat
ed in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support
 is available for older versions (hapi.im/commercial).\nnpm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest ver
sion to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated cryptiles@2.0.5: This
 version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade 
at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer sup
ported and may contain bugs and critical security issues.\n\n',
  failed: true,
  signal: null,
  cmd: 'npm install --production --no-optional',
  timedOut: false,
  killed: false }
vigneshs6993@vickylance:~/projects/vickylance$ 
```

**Comment by f1evm** [comment]
Hi,
I have got something similar. 
Unable to start strapi 3.0.0-beta.8 on windows 7 neither on Debian Stretch.

With strapi@alpha both are OK.

Regards.
Jeff F1EVM

**Comment by cg219** [comment]
Running strapi 3.0.0-beta.8 on Ubunutu 16.0.5 And I can't get it pass the `strapi new` stage. I get this

```
Building: /usr/bin/node /projects/testcms/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

    at makeError (/usr/lib/node_modules/strapi/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/lib/node_modules/strapi/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout:
   '\n> node-sass@4.12.0 install /projects/testcms/node_modules/node-sass\n> node scripts/install.js\n\n\n> core-js@2.6.9 postinstall /projects/testcms/node_modules/core-js\n> node scripts/postinstall || echo "ignore"\n\n\u001b[96mThank you for using core-js (\u001b[94m https://github.com/zloirock/core-js \u001b[96m) for polyfilling JavaScript standard library!\u001b[0m\n\n\u001b[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: \u001b[0m\n\u001b[96m>\u001b[94m https://opencollective.com/core-js \u001b[0m\n\u001b[96m>\u001b[94m https://www.patreon.com/zloirock \u001b[0m\n\n\u001b[96mAlso, the author of core-js (\u001b[94m https://github.com/zloirock \u001b[96m) is looking for a good job -)\u001b[0m\n\n\n> core-js-pure@3.1.4 postinstall /projects/testcms/node_modules/core-js-pure\n> node scripts/postinstall || echo "ignore"\n\n\u001b[96mThank you for using core-js (\u001b[94m https://github.com/zloirock/core-js \u001b[96m) for polyfilling JavaScript standard library!\u001b[0m\n\n\u001b[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: \u001b[0m\n\u001b[96m>\u001b[94m https://opencollective.com/core-js \u001b[0m\n\u001b[96m>\u001b[94m https://www.patreon.com/zloirock \u001b[0m\n\n\u001b[96mAlso, the author of core-js (\u001b[94m https://github.com/zloirock \u001b[96m) is looking for a good job -)\u001b[0m\n\n\n> styled-components@4.3.2 postinstall /projects/testcms/node_modules/styled-components\n> node ./scripts/postinstall.js || exit 0\n\nUse styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components\n\n> node-sass@4.12.0 postinstall /projects/testcms/node_modules/node-sass\n> node scripts/build.js\n\nBuilding: /usr/bin/node /projects/testcms/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=\n',
  stderr:
   'npm WARN deprecated postcss-smart-import@0.7.6: This project is not maintained anymore. Please use postcss-import instead.\nnpm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at \'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide\'\nnpm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.\nnpm WARN deprecated @hapi/joi@15.0.0: This version has been deprecated\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.\nnpm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.\nnpm WARN deprecated mailcomposer@3.12.0: This project is unmaintained\nnpm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\nnpm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated buildmail@3.10.0: This project is unmaintained\nnpm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nUnable to save binary /projects/testcms/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir \'/projects/testcms/node_modules/node-sass/vendor\'\n    at Object.mkdirSync (fs.js:757:3)\n    at sync (/projects/testcms/node_modules/mkdirp/index.js:71:13)\n    at Function.sync (/projects/testcms/node_modules/mkdirp/index.js:77:24)\n    at checkAndDownloadBinary (/projects/testcms/node_modules/node-sass/scripts/install.js:114:11)\n    at Object.<anonymous> (/projects/testcms/node_modules/node-sass/scripts/install.js:157:1)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n  errno: -13,\n  syscall: \'mkdir\',\n  code: \'EACCES\',\n  path: \'/projects/testcms/node_modules/node-sass/vendor\' }\ngyp info it worked if it ends with ok\ngyp verb cli [ \'/usr/bin/node\',\ngyp verb cli   \'/projects/testcms/node_modules/node-gyp/bin/node-gyp.js\',\ngyp verb cli   \'rebuild\',\ngyp verb cli   \'--verbose\',\ngyp verb cli   \'--libsass_ext=\',\ngyp verb cli   \'--libsass_cflags=\',\ngyp verb cli   \'--libsass_ldflags=\',\ngyp verb cli   \'--libsass_library=\' ]\ngyp info using node-gyp@3.8.0\ngyp info using node@10.16.0 | linux | x64\ngyp verb command rebuild []\ngyp verb command clean []\ngyp verb clean removing "build" directory\ngyp verb command configure []\ngyp verb check python checking for Python executable "python2" in the PATH\ngyp verb `which` succeeded python2 /usr/bin/python2\ngyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.12\ngyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j\ngyp verb get node dir no --target version specified, falling back to host node version: 10.16.0\ngyp verb command install [ \'10.16.0\' ]\ngyp verb install input version string "10.16.0"\ngyp verb install installing version: 10.16.0\ngyp verb install --ensure was passed, so won\'t reinstall if already installed\ngyp verb install version is already installed, need to check "installVersion"\ngyp verb got "installVersion" 9\ngyp verb needs "installVersion" 9\ngyp verb install version is good\ngyp verb get node dir target node version installed: 10.16.0\ngyp verb build dir attempting to create "build" dir: /projects/testcms/node_modules/node-sass/build\ngyp ERR! configure error \ngyp ERR! stack Error: EACCES: permission denied, mkdir \'/projects/testcms/node_modules/node-sass/build\'\ngyp ERR! System Linux 4.15.0-1030-gcp\ngyp ERR! command "/usr/bin/node" "/projects/testcms/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="\ngyp ERR! cwd /projects/testcms/node_modules/node-sass\ngyp ERR! node -v v10.16.0\ngyp ERR! node-gyp -v v3.8.0\ngyp ERR! not ok \nBuild failed with error code: 1\nnpm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.\nnpm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint@^3.9.1 but none is installed. You must install peer dependencies yourself.\nnpm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none is installed. You must install peer dependencies yourself.\nnpm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none is installed. You must install peer dependencies yourself.\nnpm WARN eslint-config-airbnb-base@10.0.1 requires a peer of eslint@^3.9.1 but none is installed. You must install peer dependencies yourself.\n\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the node-sass@4.12.0 postinstall script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/kreativemente/.npm/_logs/2019-06-28T23_28_01_423Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install --production --no-optional',
  timedOut: false,
  killed: false }
```

**Comment by derrickmehaffy** [comment]
@cg219 `makeError`

Can you confirm you have the `build-essentials` package installed?

`sudo apt install build-essentials -y`

**Comment by derrickmehaffy** [comment]
Also @cg219 please confirm you are on Node v10 and not v8, v11, or v12 as none of those are supported

`node --version && npm --version`

**Comment by heihachi88** [comment]
so, is it safe to update from beta 6 to 8 right now?

**Comment by cg219** [comment]
@derrickmehaffy 

Node Version: 10.16.0
NPM Version: 6.9.0

I do not have `build-essentials` installed.

**Comment by derrickmehaffy** [comment]
@cg219 sorry just `build-essential` with no s

**Comment by derrickmehaffy** [comment]
No update from user so I'm marking as closed for now.

If this issue happens again we can reopen

**Comment by isabellachen** [comment]
@derrickmehaffy The same thing is happening to me on a mac. I don't have build-essential because I'm on a mac and I can't `apt install build essential`

**Comment by isabellachen** [comment]
Ok, in the end `strapi build` followed by `strapi start` did the trick. It was the --quickstart that was failing on me.

**Comment by davidkartuzinski** [comment]
@isabellachen - Could you please describe the exact commands that you used where `--quickstart` failed?  

Was it using NPM, NPX or Yarn? 

example, 

`yarn create strapi-app my-project --quickstart`. 

or

`npx create-strapi-app quickstart-test-npx --quickstart`

or

After installing Strapi globally, 

`npm install strapi@beta -g`
`strapi new my-project --quickstart`

Thank you.

**Comment by isabellachen** [comment]
Hi @davidkartuzinski , it was the standard commands that were in the quickstart docs, so
`npm install strapi@beta -g` followed by `strapi new my-project --quickstart` and that gave me the error.

**Comment by davidkartuzinski** [comment]
@isabellachen Thank you. I couldn't recreate that error.  However, I would suggest trying to update your Node.js version to the latest  Node.js Version 10 and see if you still get the errors. Are you on a Mac?

**Comment by sayanoffiicial1997** [comment]
Hey , i am working on windows 10 . My node.js version is v11.14.0 

 npm install strapi@beta -g

$ strapi new . --quickstart
Creating a new Strapi application at D:\strapi.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this ve
rsion is no longer maintained an may contain bugs and security issues.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this ve
rsion is no longer maintained an may contain bugs and security issues.
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Pl
ease, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
info sharp Using cached C:\Users\npm-cache\_libvips\libvips-8.9.0-win32-x64.tar.gz
info sharp Creating D:\strapi\node_modules\sharp\build\Release
info sharp Copying DLLs from D:\strapi\node_modules\sharp\vendor\lib to D:\strapi\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=11.14.0 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484
:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:
16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\n
ode-gyp.js" "rebuild"
gyp ERR! cwd D:\strapi\node_modules\sharp
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN rollback Rolling back is-arrayish@0.3.2 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\strap
i\node_modules\simple-swizzle\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current:
 {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules
\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current
: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\
fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current
: {"os":"win32","arch":"x64"})
npm WARN strapi-connector-bookshelf@3.0.0-beta.20.3 requires a peer of knex@^0.20.0 but none is installed. You must install peer dep
endencies yourself.
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.24.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node ins
tall/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm-cache\debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd D:\strapi && npm install

**Comment by vickylance** [comment]
@sayanoffiicial1997  Dont use the beta anymore. Stable release is released.

**Comment by sayanoffiicial1997** [comment]
how to work with Mysql instead of SQLite

**Comment by sayanoffiicial1997** [comment]
@derrickmehaffy Please help me in using strapi with Mysql

**Comment by derrickmehaffy** [comment]
@sayanoffiicial1997 this is not the place to ask for help (old closed issues).

1. Don't use the beta, use the stable release
2. You are on an unsupported node version (use either v10 or v12)
3. Either ask your questions on the discussion tab, or join the Slack.
