### ISSUE TITLE
Fail during quickstart on 3.0.0-beta.9

### ISSUE THREAD

**Issue by sklinov** [strapi/strapi#3563]
**Describe the bug**
Installed strapi globally using 
```
npm install strapi@beta -g
```
Then ran:
```
$ strapi new koneko --quickstart
```

**Expected behavior**
Dev server started as described in documentation

**Have this error**
```
$ strapi new koneko --quickstart
🚀 Creating your Strapi application.


✅ Connected to the database
🏗  Application generation:
- Copying files ...
√ Copying files ...
- Installing dependencies ...
× Installing dependencies ...
{ Error: Command failed: npm install --production --no-optional
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated postcss-smart-import@0.7.6: This project is not maintained anymore. Please use postcss-import instead.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated @hapi/joi@15.0.0: This version has been deprecated
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webpack@^4.29.6 (node_modules\strapi-admin\node_modules\webpack):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '....0","node-libs-browse'

npm ERR! Unexpected end of JSON input while parsing near '...1.0","invariant":"^2.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sergey\AppData\Roaming\npm-cache\_logs\2019-07-03T16_28_42_070Z-debug.log


    at makeError (C:\Users\Sergey\AppData\Roaming\npm\node_modules\strapi\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\Sergey\AppData\Roaming\npm\node_modules\strapi\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: '',
  stderr:
   'npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this\nnpm WARN deprecated package has been deprecated in favor of directly\nnpm WARN deprecated including core-js/stable (to polyfill ECMAScript\nnpm WARN deprecated features) and regenerator-runtime/runtime\nnpm WARN deprecated (needed to use transpiled generator functions):\nnpm WARN deprecated \nnpm WARN deprecated   > import "core-js/stable";\nnpm WARN deprecated   > import "regenerator-runtime/runtime";\nnpm WARN deprecated postcss-smart-import@0.7.6: This project is not maintained anymore. Please use postcss-import instead.\nnpm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.\nnpm WARN deprecated @hapi/joi@15.0.0: This version has been deprecated\nnpm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\nnpm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm WARN deprecated mailcomposer@3.12.0: This project is unmaintained\nnpm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated buildmail@3.10.0: This project is unmaintained\nnpm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: webpack@^4.29.6 (node_modules\\strapi-admin\\node_modules\\webpack):\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near \'....0","node-libs-browse\'\n\nnpm ERR! Unexpected end of JSON input while parsing near \'...1.0","invariant":"^2.\'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\Sergey\\AppData\\Roaming\\npm-cache\\_logs\\2019-07-03T16_28_42_070Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install --production --no-optional',
  timedOut: false,
  killed: false }

```
**System**
- Node.js version: 10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.9
- Database: 
- Operating system: Windows 7 Pro

**Comment by fouber** [comment]
got same issue on ``3.0.0-beta.9``

```
✅ Connected to the database
🏗  Application generation:
✔ Copying files ...
✖ Installing dependencies ...
{ Error: Command failed: yarnpkg install --production --no-optional
warning strapi > boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi > koa-joi-router > @hapi/joi@15.0.0: This version has been deprecated
warning strapi > strapi-utils > knex > @babel/polyfill@7.4.4: @babel/polyfill@7.4.4: ???? As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
error Couldn't find any versions for "strapi-generate" that matches "3.0.0-beta.9"
Error: Couldn't find any versions for "strapi-generate-api" that matches "3.0.0-beta.9"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find any versions for "strapi-generate-new" that matches "3.0.0-beta.9"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13
    at process._tickCallback (internal/process/next_tick.js:68:7)

yarn install v1.13.0
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at makeError (/Users/fouber/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/fouber/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout:
   'yarn install v1.13.0\ninfo No lockfile found.\n[1/5] Validating package.json...\n[2/5] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr:
   'warning strapi > boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nwarning strapi > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nwarning strapi > koa-joi-router > @hapi/joi@15.0.0: This version has been deprecated\nwarning strapi > strapi-utils > knex > @babel/polyfill@7.4.4: @babel/polyfill@7.4.4: ???? As of Babel 7.4.0, this\npackage has been deprecated in favor of directly\nincluding core-js/stable (to polyfill ECMAScript\nfeatures) and regenerator-runtime/runtime\n(needed to use transpiled generator functions):\n\n  > import "core-js/stable";\n  > import "regenerator-runtime/runtime";\nerror Couldn\'t find any versions for "strapi-generate" that matches "3.0.0-beta.9"\nError: Couldn\'t find any versions for "strapi-generate-api" that matches "3.0.0-beta.9"\n    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)\n    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)\n    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)\n    at Generator.next (<anonymous>)\n    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)\n    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nError: Couldn\'t find any versions for "strapi-generate-new" that matches "3.0.0-beta.9"\n    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)\n    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)\n    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)\n    at Generator.next (<anonymous>)\n    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)\n    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n',
  failed: true,
  signal: null,
  cmd: 'yarnpkg install --production --no-optional',
  timedOut: false,
  killed: false }
```

**Comment by derrickmehaffy** [comment]
@fouber yours is a different issue.

**Comment by sklinov** [comment]
Ok, problem solved. As I started getting same-looking issue on other libraries and frameworks, I realized that it is something to do with with `npm`. 
Running 
`npm cache clean --force` 
helped. Strapi installed and ran dev server.
