### ISSUE TITLE
Force convert String field into Integer

### ISSUE THREAD

**Issue by fouber** [strapi/strapi#3569]
**Describe the bug**
When I save a string value by using content-manager plugin, it force to convert string value into integer. It is a very very old bug, and I'm sure it's a bug, not feature!

**Steps to reproduce the behavior**
1. ![image](https://user-images.githubusercontent.com/536297/60668975-c8f50400-9e9f-11e9-84d1-5191c7e7c5c6.png)

2. ![image](https://user-images.githubusercontent.com/536297/60669067-fb9efc80-9e9f-11e9-8bd1-fa5b3fa92be9.png)

3. ![image](https://user-images.githubusercontent.com/536297/60669087-0ce80900-9ea0-11e9-983a-efe945bb078a.png)

**Expected behavior**

In admin dashboard, the plugin ``strapi-plugin-content-manager`` update value via form submit request, which content-type is ``multipart/form-data``, as ``koa-body`` middleware parse request body, we got data like this:

![image](https://user-images.githubusercontent.com/536297/60671083-e1b3e880-9ea4-11e9-98a4-cc12574dbb01.png)

so in the plugin, code run at [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/services/ContentManager.js#L121-L172), and try to parse request body as JSON string recursive.

```javascript
...
  edit: async (params, values, source) => {
    // Multipart/form-data.
    if (values.hasOwnProperty('fields') && values.hasOwnProperty('files')) {
      // Silent recursive parser.
      const parser = value => {
        try {
          const parsed = JSON.parse(value);
          // do not modify initial value if it is string except 'null'
          if (_.isObject(parsed) || _.isNull(parsed)) {
            value = parsed;
          }
        } catch (e) {
          // Silent.
        }

        return _.isArray(value) ? value.map(obj => parser(obj)) : value;
      };
```

If I post a String field with Number literal, it will not detect the field type, and force convert string into number.

**System**
- Node.js version: v10.15.3
- NPM version:6.4.1
- Strapi version: 3.0.0-beta.7

**Comment by derrickmehaffy** [comment]
I can confirm this issue on beta.9

**Comment by soupette** [comment]
Well I am also using the last version but with sqlite...

<img width="1440" alt="Screenshot 2019-07-04 at 21 15 34" src="https://user-images.githubusercontent.com/13311463/60684969-e24a8000-9ea0-11e9-8c1a-5ef62d53bebb.png">

**Comment by henrych4** [comment]
I have tested using latest version of strapi@3.0.0-beta.9 and it works normally on both sqlite and mongodb.
Then when downgrade to strapi@3.0.0-beta.7, the problem shows up as you described. Perhaps you can try upgrade to latest version and see if the issue still exists

**Comment by fouber** [comment]
@henrych4 i got another issue on beta.9

```
✅ Connected to the database
🏗  Application generation:
✔ Copying files ...
✖ Installing dependencies ...
{ Error: Command failed: yarnpkg install --production --no-optional
warning strapi > boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi > koa-joi-router > @hapi/joi@15.0.0: This version has been deprecated
warning strapi > strapi-utils > knex > @babel/polyfill@7.4.4: @babel/polyfill@7.4.4: ???? As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
error Couldn't find any versions for "strapi-generate" that matches "3.0.0-beta.9"
Error: Couldn't find any versions for "strapi-generate-api" that matches "3.0.0-beta.9"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find any versions for "strapi-generate-new" that matches "3.0.0-beta.9"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13
    at process._tickCallback (internal/process/next_tick.js:68:7)

yarn install v1.13.0
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at makeError (/Users/fouber/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/fouber/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout:
   'yarn install v1.13.0\ninfo No lockfile found.\n[1/5] Validating package.json...\n[2/5] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr:
   'warning strapi > boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nwarning strapi > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nwarning strapi > koa-joi-router > @hapi/joi@15.0.0: This version has been deprecated\nwarning strapi > strapi-utils > knex > @babel/polyfill@7.4.4: @babel/polyfill@7.4.4: ???? As of Babel 7.4.0, this\npackage has been deprecated in favor of directly\nincluding core-js/stable (to polyfill ECMAScript\nfeatures) and regenerator-runtime/runtime\n(needed to use transpiled generator functions):\n\n  > import "core-js/stable";\n  > import "regenerator-runtime/runtime";\nerror Couldn\'t find any versions for "strapi-generate" that matches "3.0.0-beta.9"\nError: Couldn\'t find any versions for "strapi-generate-api" that matches "3.0.0-beta.9"\n    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)\n    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)\n    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)\n    at Generator.next (<anonymous>)\n    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)\n    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nError: Couldn\'t find any versions for "strapi-generate-new" that matches "3.0.0-beta.9"\n    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)\n    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)\n    at Function.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:49808:13)\n    at Generator.next (<anonymous>)\n    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)\n    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:315:13\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n',
  failed: true,
  signal: null,
  cmd: 'yarnpkg install --production --no-optional',
  timedOut: false,
  killed: false }
```

**Comment by derrickmehaffy** [comment]
@fouber 

```
error Couldn't find any versions for "strapi-generate" that matches "3.0.0-beta.9"
Error: Couldn't find any versions for "strapi-generate-api" that matches "3.0.0-beta.9"
```

That sounds like a repo issue? Those versions exist in npm repo:

https://www.npmjs.com/package/strapi-generate
https://www.npmjs.com/package/strapi-generate-api

**Comment by fouber** [comment]
@derrickmehaffy got it, thanks a lot
