### ISSUE TITLE
The SQL database indexes haven't been generated successfully

### ISSUE THREAD

**Issue by servinlp** [strapi/strapi#3650]
**Describe the bug**
When trying to start the cms in production i get the following warning: `The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details`.

**Expected behavior**
To start the cms

**Code snippets**
The output when starting in production with debug mode on
```
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `upload_file`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_permission`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_permission`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_permission`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_permission`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_permission`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_permission`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_role`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_role`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_role`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_role`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_role`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
[ { sql: 'show columns from `users-permissions_user`',
    output: [Function: output],
    bindings: [] } ]
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_EVENT ON `event` (`titel`,`beschrijving`,`datum_maand`)',
  bindings: [],
  options: {},
  __knexQueryUid: 'c053f38c-933a-464e-bad3-56cb4ebe3e9c' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_KASTANJEBOOMDE ON `_kastanjeboomde` (`agenda`,`agenda_text`,`agenda_year`,`bieren`,`dagen1`,`dagen2`,`dagen3`,`dessert`,`desserts`,`diner`,`document_title`,`dranken`,`footer-tekst-1`,`footer-tekst-2`,`footer-tekst-3`,`frisdrank`,`geen`,`homepage_title`,`hoofdgerechten`,`imageslider_text`,`intro_text`,`keywords`,`koffie`,`language`,`lunch`,`meta_description`,`navigatie_agenda`,`navigatie_contact`,`navigatie_eat`,`navigatie_link`,`navigatie_link_sluiten`,`navigatie_menu`,`navigatie_openingstijden`,`navigatie_reserveren`,`navigatie_reviews`,`navigatie_vacatures`,`opening_text`,`opening_title`,`reservation_at`,`reservation_cancel`,`reservation_confirmation`,`reservation_confirmation_email`,`reservation_contact`,`reservation_datum`,`reservation_email`,`reservation_failed`,`reservation_fname`,`reservation_lname`,`reservation_people`,`reservation_remark`,`reservation_reservation_for`,`reservation_success`,`reservation_tel`,`reservation_time`,`reservation_today`,`reservation_try_again`,`reservation_until_then`,`reservation_your_data`,`tekst1`,`tekst2`,`tekst3`,`tekst4`,`tekst5`,`tekst6`,`tekst7`,`texels`,`tijden1`,`tijden2`,`tijden3`,`title`,`vegan`,`vegetarisch`,`voorgerechten`,`wijnen`,`zonder_diets`,`zonder_ei`,`zonder_gluten`,`zonder_melk`,`zonder_mosterd`,`zonder_noten`,`zonder_schaaldieren`,`zonder_schelpdieren`,`zonder_selderij`,`zonder_soja`,`zonder_vis`)',
  bindings: [],
  options: {},
  __knexQueryUid: 'b08c1a80-85a6-41fe-9731-cd01f483255f' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_LUNCHITEMS ON `lunchitems` (`titel`,`beschrijving`,`titel_en`,`beschrijving_en`,`titel_de`,`beschrijving_de`)',
  bindings: [],
  options: {},
  __knexQueryUid: '030c5730-1c69-430e-bd33-6527af3420ac' }
{ method: 'raw',
  sql: 'CREATE FULLTEXT INDEX SEARCH_MENUS ON `menus` (`Menuitem`)',
  bindings: [],
  options: {},
  __knexQueryUid: '8abbb80a-dcfc-43c5-a56a-0afda78245c8' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_VACATURES ON `vacatures` (`Functie`,`Beschrijving`)',
  bindings: [],
  options: {},
  __knexQueryUid: '89981606-a559-48e9-a414-1385cd6b0b29' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_VOORGERECHTS ON `voorgerechts` (`titel`,`beschrijving`,`titel_en`,`beschrijving_en`,`titel_de`,`beschrijving_de`)',
  bindings: [],
  options: {},
  __knexQueryUid: 'f2fffb8c-d5cb-46ea-9aaa-f97a1e8111f5' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_DESSERTS ON `desserts` (`titel`,`beschrijving`,`titel_en`,`beschrijving_en`,`titel_de`,`beschrijving_de`)',
  bindings: [],
  options: {},
  __knexQueryUid: '6d7a6993-eb6f-4915-9d19-e1fc58e75865' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_HOOFDGERECHTS ON `hoofdgerechts` (`titel`,`beschrijving`,`titel_en`,`beschrijving_en`,`titel_de`,`beschrijving_de`)',
  bindings: [],
  options: {},
  __knexQueryUid: '0f764065-e248-46fa-99b1-9ada1634e441' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_KASTANJEBOOMEN ON `_kastanjeboomen` (`agenda`,`agenda_text`,`agenda_year`,`bieren`,`dagen1`,`dagen2`,`dagen3`,`dessert`,`desserts`,`diner`,`document_title`,`dranken`,`footer-tekst-1`,`footer-tekst-2`,`footer-tekst-3`,`frisdrank`,`geen`,`homepage_title`,`hoofdgerechten`,`imageslider_text`,`intro_text`,`keywords`,`koffie`,`language`,`lunch`,`meta_description`,`navigatie_agenda`,`navigatie_contact`,`navigatie_eat`,`navigatie_link`,`navigatie_link_sluiten`,`navigatie_menu`,`navigatie_openingstijden`,`navigatie_reserveren`,`navigatie_reviews`,`navigatie_vacatures`,`opening_text`,`opening_title`,`reservation_at`,`reservation_cancel`,`reservation_confirmation`,`reservation_confirmation_email`,`reservation_contact`,`reservation_datum`,`reservation_email`,`reservation_failed`,`reservation_fname`,`reservation_lname`,`reservation_people`,`reservation_remark`,`reservation_reservation_for`,`reservation_success`,`reservation_tel`,`reservation_time`,`reservation_today`,`reservation_try_again`,`reservation_until_then`,`reservation_your_data`,`tekst1`,`tekst2`,`tekst3`,`tekst4`,`tekst5`,`tekst6`,`tekst7`,`texels`,`tijden1`,`tijden2`,`tijden3`,`title`,`voorgerechten`,`wijnen`,`zonder_diets`,`zonder_ei`,`zonder_gluten`,`zonder_melk`,`zonder_mosterd`,`zonder_noten`,`zonder_schaaldieren`,`zonder_schelpdieren`,`zonder_selderij`,`zonder_soja`,`zonder_vis`,`vegan`,`vegetarisch`)',
  bindings: [],
  options: {},
  __knexQueryUid: '22a38a9f-8eab-4de8-9f4d-1aaa0b91abe8' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_KASTANJEBOOMNEDERLANDS ON `_kastanjeboomnederlands` (`agenda`,`agenda_text`,`agenda_year`,`bieren`,`dagen1`,`dagen2`,`dagen3`,`dessert`,`desserts`,`diner`,`document_title`,`dranken`,`footer-tekst-1`,`footer-tekst-2`,`footer-tekst-3`,`frisdrank`,`geen`,`homepage_title`,`hoofdgerechten`,`imageslider_text`,`intro_text`,`keywords`,`koffie`,`language`,`lunch`,`meta_description`,`navigatie_agenda`,`navigatie_contact`,`navigatie_eat`,`navigatie_link`,`navigatie_link_sluiten`,`navigatie_menu`,`navigatie_openingstijden`,`navigatie_reserveren`,`navigatie_reviews`,`navigatie_vacatures`,`opening_text`,`opening_title`,`reservation_at`,`reservation_cancel`,`reservation_confirmation`,`reservation_confirmation_email`,`reservation_contact`,`reservation_datum`,`reservation_email`,`reservation_failed`,`reservation_fname`,`reservation_lname`,`reservation_people`,`reservation_remark`,`reservation_reservation_for`,`reservation_success`,`reservation_tel`,`reservation_time`,`reservation_today`,`reservation_try_again`,`reservation_until_then`,`reservation_your_data`,`tekst1`,`tekst2`,`tekst3`,`tekst4`,`tekst5`,`tekst6`,`tekst7`,`texels`,`tijden1`,`tijden2`,`tijden3`,`title`,`vegan`,`vegetarisch`,`voorgerechten`,`wijnen`,`zonder_diets`,`zonder_ei`,`zonder_gluten`,`zonder_melk`,`zonder_mosterd`,`zonder_noten`,`zonder_schaaldieren`,`zonder_schelpdieren`,`zonder_selderij`,`zonder_soja`,`zonder_vis`,`vacancy_title`,`vacancy_contact1`,`vacancy_contact2`)',
  bindings: [],
  options: {},
  __knexQueryUid: '60a49e3d-d4e7-493f-9394-5604a653f4c9' }
{ Error: ER_TOO_MANY_KEY_PARTS: Too many key parts specified; max 16 parts allowed
    at Query.Sequence._packetToError (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/Connection.js:201:25)
    at /var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/mysql/index.js:144:18
    at Promise._execute (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:138:36)
    at Runner.tryCatcher (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/method.js:15:34)
    at /var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:47:21
    at tryCatcher (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/util.js:16:23)
    at /var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:643:18)
    at PromiseArray._resolve (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise_array.js:144:14)
  code: 'ER_TOO_MANY_KEY_PARTS',
  errno: 1070,
  sqlMessage: 'Too many key parts specified; max 16 parts allowed',
  sqlState: '42000',
  index: 0,
  sql:
   'CREATE FULLTEXT INDEX SEARCH_KASTANJEBOOMDE ON `_kastanjeboomde` (`agenda`,`agenda_text`,`agenda_year`,`bieren`,`dagen1`,`dagen2`,`dagen3`,`dessert`,`desserts`,`diner`,`document_title`,`dranken`,`footer-tekst-1`,`footer-tekst-2`,`footer-tekst-3`,`frisdrank`,`geen`,`homepage_title`,`hoofdgerechten`,`imageslider_text`,`intro_text`,`keywords`,`koffie`,`language`,`lunch`,`meta_description`,`navigatie_agenda`,`navigatie_contact`,`navigatie_eat`,`navigatie_link`,`navigatie_link_sluiten`,`navigatie_menu`,`navigatie_openingstijden`,`navigatie_reserveren`,`navigatie_reviews`,`navigatie_vacatures`,`opening_text`,`opening_title`,`reservation_at`,`reservation_cancel`,`reservation_confirmation`,`reservation_confirmation_email`,`reservation_contact`,`reservation_datum`,`reservation_email`,`reservation_failed`,`reservation_fname`,`reservation_lname`,`reservation_people`,`reservation_remark`,`reservation_reservation_for`,`reservation_success`,`reservation_tel`,`reservation_time`,`reservation_today`,`reservation_try_again`,`reservation_until_then`,`reservation_your_data`,`tekst1`,`tekst2`,`tekst3`,`tekst4`,`tekst5`,`tekst6`,`tekst7`,`texels`,`tijden1`,`tijden2`,`tijden3`,`title`,`vegan`,`vegetarisch`,`voorgerechten`,`wijnen`,`zonder_diets`,`zonder_ei`,`zonder_gluten`,`zonder_melk`,`zonder_mosterd`,`zonder_noten`,`zonder_schaaldieren`,`zonder_schelpdieren`,`zonder_selderij`,`zonder_soja`,`zonder_vis`)' }
[2019-07-19T12:54:08.379Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_CORE_STORE ON `core_store` (`key`,`value`,`type`,`environment`,`tag`)',
  bindings: [],
  options: {},
  __knexQueryUid: 'df67f801-357e-41fc-ab56-387672f7e4e8' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_STRAPI_ADMINISTRATOR ON `strapi_administrator` (`username`,`resetPasswordToken`)',
  bindings: [],
  options: {},
  __knexQueryUid: 'f9568d8b-71ed-492f-b157-13aabcacd99b' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_UPLOAD_FILE ON `upload_file` (`name`,`hash`,`sha256`,`ext`,`mime`,`size`,`url`,`provider`,`public_id`)',
  bindings: [],
  options: {},
  __knexQueryUid: '30c5e5ef-f96f-4796-a98d-c149210d11dd' }
{ method: 'raw',
  sql:
   'CREATE FULLTEXT INDEX SEARCH_USERS_PERMISSIONS_PERMISSION ON `users-permissions_permission` (`type`,`controller`,`action`,`policy`)',
  bindings: [],
  options: {},
  __knexQueryUid: '3c2668ed-1937-46f9-8a58-4883cf935b31' }
{ Error: ER_TOO_MANY_KEY_PARTS: Too many key parts specified; max 16 parts allowed
    at Query.Sequence._packetToError (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/html/kastanjeboom/cms/node_modules/mysql/lib/Connection.js:201:25)
    at /var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/mysql/index.js:144:18
    at Promise._execute (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:138:36)
    at Runner.tryCatcher (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/method.js:15:34)
    at /var/www/html/kastanjeboom/cms/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:47:21
    at tryCatcher (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/util.js:16:23)
    at /var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise.js:643:18)
    at PromiseArray._resolve (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/www/html/kastanjeboom/cms/node_modules/bluebird/js/release/promise_array.js:144:14)
  code: 'ER_TOO_MANY_KEY_PARTS',
  errno: 1070,
  sqlMessage: 'Too many key parts specified; max 16 parts allowed',
  sqlState: '42000',
  index: 0,
  sql:
   'CREATE FULLTEXT INDEX SEARCH_KASTANJEBOOMEN ON `_kastanjeboomen` (`agenda`,`agenda_text`,`agenda_year`,`bieren`,`dagen1`,`dagen2`,`dagen3`,`dessert`,`desserts`,`diner`,`document_title`,`dranken`,`footer-tekst-1`,`footer-tekst-2`,`footer-tekst-3`,`frisdrank`,`geen`,`homepage_title`,`hoofdgerechten`,`imageslider_text`,`intro_text`,`keywords`,`koffie`,`language`,`lunch`,`meta_description`,`navigatie_agenda`,`navigatie_contact`,`navigatie_eat`,`navigatie_link`,`navigatie_link_sluiten`,`navigatie_menu`,`navigatie_openingstijden`,`navigatie_reserveren`,`navigatie_reviews`,`navigatie_vacatures`,`opening_text`,`opening_title`,`reservation_at`,`reservation_cancel`,`reservation_confirmation`,`reservation_confirmation_email`,`reservation_contact`,`reservation_datum`,`reservation_email`,`reservation_failed`,`reservation_fname`,`reservation_lname`,`reservation_people`,`reservation_remark`,`reservation_reservation_for`,`reservation_success`,`reservation_tel`,`reservation_time`,`reservation_today`,`reservation_try_again`,`reservation_until_then`,`reservation_your_data`,`tekst1`,`tekst2`,`tekst3`,`tekst4`,`tekst5`,`tekst6`,`tekst7`,`texels`,`tijden1`,`tijden2`,`tijden3`,`title`,`voorgerechten`,`wijnen`,`zonder_diets`,`zonder_ei`,`zonder_gluten`,`zonder_melk`,`zonder_mosterd`,`zonder_noten`,`zonder_schaaldieren`,`zonder_schelpdieren`,`zonder_selderij`,`zonder_soja`,`zonder_vis`,`vegan`,`vegetarisch`)' }
```

**System**
- Node.js version: 10.16.0
- npm version: 6.9.0 (tried both yarn and npm because of [this](https://github.com/strapi/strapi/issues/2857))
- yarn version: 1.12.3 (also tried 1.17.3)
- Strapi version: also tried 3.0.0-next.17
- Database: mysql
- Operating system: ubuntu 18.10

**Comment by derrickmehaffy** [comment]
`also tried 3.0.0-beta.17` Uhhhhh there is no beta.17 yet :P

**Comment by servinlp** [comment]
Woops, should be 3.0.0-next.17

**Comment by servinlp** [comment]
Problem with the firewall, not with strapi. Closing

**Comment by caiobiodere** [comment]
@servinlp what did you do to fix the error? Could you describe it better because I am having the same error here
