### ISSUE TITLE
GraphQL cannot use singularia tantum content type name => Error: Field "Query.staff" can only be defined once

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#3695]
**Describe the bug**
Creation of a content type with a singular name that results in an irregular plural (singularia tantum) causes Strapi to crash when used with GraphQL, I have not tried it without GraphQL but it seems linked to GraphQL only. Examples of names are "sheep", "staff" or "fish". It seems like when it is trying to generate plural queries for Graphql, the same singular Query results from the name since 'staff' singular is going to be 'staff' in plural form. This is the result of a findOne and find Query generation.

**Steps to reproduce the behavior**
1. Create a content type with name "staff"
2. Add a field to it and save so that Strapi restarts
3. Strapi will simply crash with the following error:
```js
Server wasn't able to start properly.
  [2019-07-30T07:57:05.046Z] error Error: Field "Query.staff" can only be defined once.
  at assertValidSDL (/Users/em/dev/projects/app/api/node_modules/graphql/validation/validate.js:80:11)
at Object.buildASTSchema (/Users/em/dev/projects/app/api/node_modules/graphql/utilities/buildASTSchema.js:69:34)
at Object.buildSchemaFromTypeDefinitions (/Users/em/dev/projects/app/api/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:23:28)
at makeExecutableSchema (/Users/em/dev/projects/app/api/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
at Object.generateSchema (/Users/em/dev/projects/app/api/node_modules/strapi-plugin-graphql/services/Schema.js:263:22)
at Function.initialize (/Users/em/dev/projects/app/api/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
at /Users/em/dev/projects/app/api/node_modules/strapi/lib/hooks/index.js:52:31
at /Users/em/dev/projects/app/api/node_modules/strapi/lib/hooks/index.js:153:39
at /Users/em/dev/projects/app/api/node_modules/lodash/lodash.js:9997:23
at Strapi.<anonymous> (/Users/em/dev/projects/app/api/node_modules/strapi/lib/hooks/index.js:164:17)
at Object.onceWrapper (events.js:291:20)
at Strapi.emit (events.js:203:13)
at onFinish (/Users/em/dev/projects/app/api/node_modules/strapi/lib/hooks/index.js:44:12)
at /Users/em/dev/projects/app/api/node_modules/strapi-hook-bookshelf/lib/index.js:890:56
```

**Expected behavior**
It was just supposed to create the content type, and restart the server without any issues.

**System**
- Node.js version: v12.6.0
- Yarn version: 1.16.0
- Strapi version: Strapi 3.0.0-beta.14
- Database: SQLite
- Operating system: Mac OS Mojave

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.

> This is a templated message
