### ISSUE TITLE
Latest Build Failing

### ISSUE THREAD

**Issue by hanyoonLDA** [strapi/strapi#3824]
**Describe the bug**
I've tried on several Ubuntu 18 machines now (one of which was brand new) with Node 10.16 and NPM 6.9. For some reason fsevent wants the OS to be "Darwin" although I'm not on a Mac. 

```
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
/root/.nvm/versions/node/v10.16.3/bin/strapi -> /root/.nvm/versions/node/v10.16.3/lib/node_modules/strapi/bin/strapi.js

> core-js@2.6.9 postinstall /root/.nvm/versions/node/v10.16.3/lib/node_modules/strapi/node_modules/core-js
> node scripts/postinstall || echo "ignore"

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v10.16.3/lib/node_modules/strapi/node_modules/core-js/scripts/postinstall'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
ignore

> strapi@3.0.0-beta.15 postinstall /root/.nvm/versions/node/v10.16.3/lib/node_modules/strapi
> node lib/utils/success.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v10.16.3/lib/node_modules/strapi/lib/utils/success.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/strapi/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@3.0.0-beta.15 postinstall: `node lib/utils/success.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi@3.0.0-beta.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**System**
- Strapi version:  Strapi 3 beta 15
- Database: MySQL
- Operating system: Ubuntu 18

Could it be an issue with NVM?

**Comment by sinh117801** [comment]
Which command you use to run?
`yarn develop`
or 
`strapi start`

**Comment by hanyoonLDA** [comment]
@sinh117801 these errors are during installation

**Comment by hanyoonLDA** [comment]
Fixed https://github.com/strapi/strapi/issues/3394
