### ISSUE TITLE
Cannot Create Rest Route

### ISSUE THREAD

**Issue by webface** [strapi/strapi#3849]
**Describe the bug**
Creating a custom route throws a mongo error

**Steps to reproduce the behavior**
1. Go to 'http://localhost:1337/genres/names/'

```
debug GET /genres/names (14 ms)
[2019-08-26T17:45:59.454Z] error CastError: Cast to ObjectId failed for value "names" at path "_id" for model "Genre"
    at new CastError (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/error/cast.js:29:11)
    at ObjectId.cast (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schema/objectid.js:244:11)
    at ObjectId.SchemaType.applySetters (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:948:12)
    at ObjectId.SchemaType._castForQuery (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:1362:15)
    at ObjectId.SchemaType.castForQuery (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:1352:15)
    at ObjectId.SchemaType.castForQueryWrapper (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:1331:15)
    at cast (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/cast.js:307:32)
    at model.Query.Query.cast (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/query.js:4608:12)
    at model.Query.Query._castConditions (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/query.js:1790:10)
    at model.Query.<anonymous> (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/query.js:2045:8)
    at model.Query._wrappedThunk [as _findOne] (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/kareem/index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Expected behavior**
api results containing id and genre name

**Code snippets**
```
'use strict';
/**
 * Read the documentation (https://strapi.io/documentation/3.0.0-beta.x/guides/controllers.html#core-controllers)
 * to customize this controller
 */
module.exports = {
	getNames: async ctx => {
        try {
            let response = [];
            const genres = await strapi.services.genre.find({'_limit':-1});
            genres.forEach(genre => response.push({
                id: genre['attributes']['id'],
                name: genre['attributes']['name']
            }))
            ctx.send(response);
        } catch(err) {
          console.log(err);
        }
    },
 };
 ```

**System**
- Node.js v10.15.3
- NPM version:6.4.1
- Strapi version: 3.0.0beta.15
- Database: Mongo DB
- Operating system: MacOS

**Additional context**
I also tried : 

```
module.exports = {
   getNames: async (ctx) => {
       const genres = Genre
         .find()
         .populate('genre','_id');
           ctx.body = genres;
   }
};
```

but I got the same error
Genre.settings.json:
```
{
  "connection": "default",
  "collectionName": "genre",
  "info": {
    "name": "genre",
    "description": ""
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "artists": {
      "collection": "artist",
      "via": "genres",
      "dominant": true
    },
    "genre": {
      "unique": true,
      "required": true,
      "type": "string"
    }
  }
}```

**Comment by soupette** [comment]
@webface 

I think it's an issue related to your code here's what I did to get it working

1. I have added the new endpoint to the routes config

`./api/genre/config/routes.json`

```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/genres",
      "handler": "Genre.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/genres/names",
      "handler": "Genre.getNames",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/genres/count",
      "handler": "Genre.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/genres/:_id",
      "handler": "Genre.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "POST",
      "path": "/genres",
      "handler": "Genre.create",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/genres/:_id",
      "handler": "Genre.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/genres/:_id",
      "handler": "Genre.delete",
      "config": {
        "policies": []
      }
    }
  ]
}
```

2. I have added the method:

`./api/genre/controllers/Genre.js`

```js
module.exports = {
  getNames: async ctx => {
    let response = [];
    try {
      const genres = await strapi.services.genre.find({ _limit: -1 });

      genres.forEach(genre =>
        response.push({
          id: genre.id,
          name: genre.name,
        }),
      );

      ctx.send(response);
    } catch (err) {
      // handle errors
    }
  },
};
```

Here's the response:

<img width="451" alt="Screenshot 2019-08-29 at 14 44 55" src="https://user-images.githubusercontent.com/13311463/63941287-99134880-ca6b-11e9-8b45-1786c1628ba8.png">

**Comment by webface** [comment]
@soupette thanks for looking into this but my code is identical to yours. The only difference is the content type genre does not have a field called "name" it has a field called "genre"

```
'use strict';

module.exports = {
	getNames: async ctx => {
	  let response = [];
	  try {
		const genres = await strapi.services.genre.find({ _limit: -1 });
  
		genres.forEach(genre =>
		  response.push({
			id: genre.id,
			name: genre.genre,
		  }),
		);
  
		ctx.send(response);
	  } catch (err) {
		// handle errors
	  }
	},
  };
```

and here is my routes config:

```
{
  "routes": [
    {
      "method": "GET",
      "path": "/genres",
      "handler": "Genre.find",
      "config": {
        "policies": []
      }
	},
	{
		"method": "GET",
		"path": "/genres/names",
		"handler": "Genre.getNames",
		"config": {
		  "policies": []
		}
	  },
    {
      "method": "GET",
      "path": "/genres/count",
      "handler": "Genre.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/genres/:_id",
      "handler": "Genre.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "POST",
      "path": "/genres",
      "handler": "Genre.create",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/genres/:_id",
      "handler": "Genre.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/genres/:_id",
      "handler": "Genre.delete",
      "config": {
        "policies": []
      }
	}
  ]
}

```

Its identical to yours except for the field name itself but I get the same error:
```
{
statusCode: 500,
error: "Internal Server Error",
message: "An internal server error occurred"
}

[2019-08-29T22:28:23.062Z] error CastError: Cast to ObjectId failed for value "names" at path "_id" for model "Genre"
    at new CastError (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/error/cast.js:29:11)
    at ObjectId.cast (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schema/objectid.js:244:11)
    at ObjectId.SchemaType.applySetters (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:948:12)
    at ObjectId.SchemaType._castForQuery (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:1362:15)
    at ObjectId.SchemaType.castForQuery (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:1352:15)
    at ObjectId.SchemaType.castForQueryWrapper (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/schematype.js:1331:15)
    at cast (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/cast.js:307:32)
    at model.Query.Query.cast (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/query.js:4608:12)
    at model.Query.Query._castConditions (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/query.js:1790:10)
    at model.Query.<anonymous> (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/query.js:2045:8)
    at model.Query._wrappedThunk [as _findOne] (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/Applications/MAMP/htdocs/PROJECTS/heroku-app/node_modules/kareem/index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[2019-08-29T22:28:23.062Z] debug GET /genres/names (4 ms)
[2019-08-29T22:28:23.206Z] debug GET /favicon.ico (1 ms)

```

**Comment by lauriejim** [comment]
Hello @webface!

I created a new `Genre` API.
Copy and Past your routes and controller function and it works.

Can you log something in your `getName` to make sure, this controller function is called.

**Comment by webface** [comment]
I just ran it again and it seems to work now. Don't know why it wasnt before. Thanks for looking into this.
