### ISSUE TITLE
Constantly getting Knex pool full error

### ISSUE THREAD

**Issue by jeremyrajan** [strapi/strapi#3867]
**Describe the bug**
This sounds a bit random, but intermittently I am getting the following the error on GCP (App engine + Cloud SQL postgres). This happens when I am trying to acces a certain resource to create a entry.

```
3t231157]  npm ERR! A complete log of this run can be found in:
2019-08-29 16:23:51 default[20190803t231157]  npm ERR!     /root/.npm/_logs/2019-08-29T16_23_51_461Z-debug.log
2019-08-29 16:24:28 default[20190804t143604]
2019-08-29 16:24:28 default[20190804t143604]  > admin@0.1.0 start /app
2019-08-29 16:24:28 default[20190804t143604]  > strapi start
2019-08-29 16:24:28 default[20190804t143604]
2019-08-29 16:24:39 default[20190804t143604]  { TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?      at Bluebird.try.then.catch (/app/node_modules/knex/lib/client.js:318:17)      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)      at /app/node_modules/bluebird/js/release/catch_filter.js:17:41      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)      at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)      at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:695:18)      at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)      at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)      at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)      at runCallback (timers.js:705:18)      at tryOnImmediate (timers.js:676:5)      at processImmediate (timers.js:658:5) sql: undefined, bindings: undefined }
2019-08-29 16:24:39 default[20190804t143604]  npm ERR! code ELIFECYCLE
2019-08-29 16:24:39 default[20190804t143604]  npm ERR! errno 1
2019-08-29 16:24:39 default[20190804t143604]  npm ERR! admin@0.1.0 start: `strapi start`
2019-08-29 16:24:39 default[20190804t143604]  npm ERR! Exit status 1
2019-08-29 16:24:39 default[20190804t143604]  npm ERR!
2019-08-29 16:24:39 default[20190804t143604]  npm ERR! Failed at the admin@0.1.0 start script.
2019-08-29 16:24:39 default[20190804t143604]  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-08-29 16:24:39 default[20190804t143604]
2019-08-29 16:24:39 default[20190804t143604]  npm ERR! A complete log of this run can be found in:
2019-08-29 16:24:39 default[20190804t143604]  npm ERR!     /root/.npm/_logs/2019-08-29T16_24_39_711Z-debug.log
```

**Steps to reproduce the behavior**
1. Deploy and check logs
2. Stuck at the loading screen

**Expected behavior**
1. Should be able to open the form for entry

**Screenshots**
![image](https://user-images.githubusercontent.com/2890683/63958499-0f8c6680-cabd-11e9-8358-c691dad4a4b1.png)

**System**
- Node.js version: 10
- NPM version:
- Strapi version: 3.0.0-beta.15 (I am using the latest version of knex)
- Database: Postgress
- Operating system: Google App Engine

**Additional context**

**Comment by derrickmehaffy** [comment]
You can try bumping up a few of the timeout values from knex.

In your database.json you can add these under the options config and tweak them as you need to:

```
      "options": {
        "acquireConnectionTimeout": 100000,
        "pool": {
          "min": 0,
          "max": 50,
          "createTimeoutMillis": 20000,
          "acquireTimeoutMillis": 20000,
          "idleTimeoutMillis": 3000,
          "reapIntervalMillis": 1000,
          "createRetryIntervalMillis": 100
        }
      }
```
