### ISSUE TITLE
Cant deploy on Heroku

### ISSUE THREAD

**Issue by barbgegrasse** [strapi/strapi#3883]
#Informations

*Node.js version: Whatever is set as part of Heroku button
*npm version: Whatever is set as part of Heroku button
*Strapi version: Strapi v3.0.0-beta.15
*Database: PostgreSQL
*Operating system: Windows
*What is the current behavior?

App crashing on Heroku. everything is fine locally.  
From the logs

`2019-09-01T23:05:37.379846+00:00 app[web.1]: npm ERR! cms@0.1.0 start: `strapi start`
2019-09-01T23:05:37.380011+00:00 app[web.1]: npm ERR! Exit status 1
2019-09-01T23:05:37.380267+00:00 app[web.1]: npm ERR!
2019-09-01T23:05:37.380489+00:00 app[web.1]: npm ERR! Failed at the cms@0.1.0 start script.
2019-09-01T23:05:37.380660+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-01T23:05:37.386179+00:00 app[web.1]:
2019-09-01T23:05:37.386332+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-09-01T23:05:37.386475+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-09-01T23_05_37_381Z-debug.log
2019-09-01T23:05:37.478007+00:00 heroku[web.1]: State changed from starting to crashed
2019-09-01T23:05:37.455776+00:00 heroku[web.1]: Process exited with status 1
2019-09-01T23:05:39.256915+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ramen-noob.herokuapp.com request_id=12b43fdd-0929-4d5c-a1f5-160b0060589b fwd="109.220.189.216" dyno= connect= service= status=503 bytes= protocol=https
2019-09-01T23:05:38.732746+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ramen-noob.herokuapp.com request_id=fa1bb1cb-9d0f-40eb-a8a5-a164f5d45cce fwd="109.220.189.216" dyno= connect= service= status=503 bytes= protocol=https
2019-09-01T23:09:46.822108+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/admin" host=ramen-noob.herokuapp.com request_id=0f05a34e-e9aa-43be-bd25-f9b775d51952 fwd="109.220.189.216" dyno= connect= service= status=503 bytes= protocol=https
2019-09-01T23:09:47.176357+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ramen-noob.herokuapp.com request_id=c42a3b9c-0548-4678-8d72-ff670e694815 fwd="109.220.189.216" dyno= connect= service= status=503 bytes= protocol=https
2019-09-01T23:12:52.149553+00:00 heroku[web.1]: State changed from crashed to starting
2019-09-01T23:13:01.561788+00:00 heroku[web.1]: Starting process with command `npm start`
2019-09-01T23:13:03.508235+00:00 app[web.1]:
2019-09-01T23:13:03.508257+00:00 app[web.1]: > cms@0.1.0 start /app
2019-09-01T23:13:03.508259+00:00 app[web.1]: > strapi start
2019-09-01T23:13:03.508261+00:00 app[web.1]:
2019-09-01T23:13:06.000540+00:00 app[web.1]: TypeError: Cannot convert undefined or null to object
2019-09-01T23:13:06.000575+00:00 app[web.1]: at Function.keys (<anonymous>)
2019-09-01T23:13:06.000578+00:00 app[web.1]: at Object.generateSchema (/app/node_modules/strapi-plugin-graphql/services/Schema.js:160:25)
2019-09-01T23:13:06.000581+00:00 app[web.1]: at Function.initialize (/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
2019-09-01T23:13:06.000583+00:00 app[web.1]: at /app/node_modules/strapi/lib/hooks/index.js:52:31
2019-09-01T23:13:06.000585+00:00 app[web.1]: at after (/app/node_modules/strapi/lib/hooks/index.js:153:39)
2019-09-01T23:13:06.000589+00:00 app[web.1]: at /app/node_modules/lodash/lodash.js:9997:23
2019-09-01T23:13:06.000591+00:00 app[web.1]: at Strapi.once (/app/node_modules/strapi/lib/hooks/index.js:164:17)
2019-09-01T23:13:06.000593+00:00 app[web.1]: at Object.onceWrapper (events.js:286:20)
2019-09-01T23:13:06.000595+00:00 app[web.1]: at Strapi.emit (events.js:198:13)
2019-09-01T23:13:06.000597+00:00 app[web.1]: at onFinish (/app/node_modules/strapi/lib/hooks/index.js:44:12)
2019-09-01T23:13:06.000599+00:00 app[web.1]: at Promise.all.then (/app/node_modules/strapi-hook-bookshelf/lib/index.js:890:56)
2019-09-01T23:13:06.003272+00:00 app[web.1]: [2019-09-01T23:13:06.002Z] error TypeError: Cannot convert undefined or null to object
2019-09-01T23:13:06.003276+00:00 app[web.1]: at Function.keys (<anonymous>)
2019-09-01T23:13:06.003279+00:00 app[web.1]: at Object.generateSchema (/app/node_modules/strapi-plugin-graphql/services/Schema.js:160:25)
2019-09-01T23:13:06.003281+00:00 app[web.1]: at Function.initialize (/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
2019-09-01T23:13:06.003284+00:00 app[web.1]: at /app/node_modules/strapi/lib/hooks/index.js:52:31
2019-09-01T23:13:06.003286+00:00 app[web.1]: at after (/app/node_modules/strapi/lib/hooks/index.js:153:39)
2019-09-01T23:13:06.003288+00:00 app[web.1]: at /app/node_modules/lodash/lodash.js:9997:23
2019-09-01T23:13:06.003291+00:00 app[web.1]: at Strapi.once (/app/node_modules/strapi/lib/hooks/index.js:164:17)
2019-09-01T23:13:06.003293+00:00 app[web.1]: at Object.onceWrapper (events.js:286:20)
2019-09-01T23:13:06.003295+00:00 app[web.1]: at Strapi.emit (events.js:198:13)
2019-09-01T23:13:06.003298+00:00 app[web.1]: at onFinish (/app/node_modules/strapi/lib/hooks/index.js:44:12)
2019-09-01T23:13:06.003300+00:00 app[web.1]: at Promise.all.then (/app/node_modules/strapi-hook-bookshelf/lib/index.js:890:56)
2019-09-01T23:13:06.021242+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-09-01T23:13:06.021963+00:00 app[web.1]: npm ERR! errno 1
2019-09-01T23:13:06.023886+00:00 app[web.1]: npm ERR! cms@0.1.0 start: `strapi start`
2019-09-01T23:13:06.024117+00:00 app[web.1]: npm ERR! Exit status 1
2019-09-01T23:13:06.024440+00:00 app[web.1]: npm ERR!
2019-09-01T23:13:06.024679+00:00 app[web.1]: npm ERR! Failed at the cms@0.1.0 start script.
2019-09-01T23:13:06.024925+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-01T23:13:06.034602+00:00 app[web.1]:
2019-09-01T23:13:06.034811+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-09-01T23:13:06.034979+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-09-01T23_13_06_026Z-debug.log
2019-09-01T23:13:06.119231+00:00 heroku[web.1]: State changed from starting to crashed
2019-09-01T23:13:06.097050+00:00 heroku[web.1]: Process exited with status 1
2019-09-01T23:36:43.483844+00:00 heroku[web.1]: State changed from crashed to starting
2019-09-01T23:36:53.999870+00:00 heroku[web.1]: Starting process with command `npm start`
2019-09-01T23:36:56.070087+00:00 app[web.1]:
2019-09-01T23:36:56.070106+00:00 app[web.1]: > cms@0.1.0 start /app
2019-09-01T23:36:56.070108+00:00 app[web.1]: > strapi start
2019-09-01T23:36:56.070110+00:00 app[web.1]:
2019-09-01T23:36:58.511164+00:00 heroku[web.1]: State changed from starting to crashed
2019-09-01T23:36:58.398668+00:00 app[web.1]: TypeError: Cannot convert undefined or null to object
2019-09-01T23:36:58.398712+00:00 app[web.1]: at Function.keys (<anonymous>)
2019-09-01T23:36:58.398715+00:00 app[web.1]: at Object.generateSchema (/app/node_modules/strapi-plugin-graphql/services/Schema.js:160:25)
2019-09-01T23:36:58.398717+00:00 app[web.1]: at Function.initialize (/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
2019-09-01T23:36:58.398719+00:00 app[web.1]: at /app/node_modules/strapi/lib/hooks/index.js:52:31
2019-09-01T23:36:58.398722+00:00 app[web.1]: at after (/app/node_modules/strapi/lib/hooks/index.js:153:39)
2019-09-01T23:36:58.398726+00:00 app[web.1]: at /app/node_modules/lodash/lodash.js:9997:23
2019-09-01T23:36:58.398728+00:00 app[web.1]: at Strapi.once (/app/node_modules/strapi/lib/hooks/index.js:164:17)
2019-09-01T23:36:58.398730+00:00 app[web.1]: at Object.onceWrapper (events.js:286:20)
2019-09-01T23:36:58.398733+00:00 app[web.1]: at Strapi.emit (events.js:198:13)
2019-09-01T23:36:58.398735+00:00 app[web.1]: at onFinish (/app/node_modules/strapi/lib/hooks/index.js:44:12)
2019-09-01T23:36:58.398737+00:00 app[web.1]: at Promise.all.then (/app/node_modules/strapi-hook-bookshelf/lib/index.js:890:56)
2019-09-01T23:36:58.401583+00:00 app[web.1]: [2019-09-01T23:36:58.401Z] error TypeError: Cannot convert undefined or null to object
2019-09-01T23:36:58.401586+00:00 app[web.1]: at Function.keys (<anonymous>)
2019-09-01T23:36:58.401589+00:00 app[web.1]: at Object.generateSchema (/app/node_modules/strapi-plugin-graphql/services/Schema.js:160:25)
2019-09-01T23:36:58.401591+00:00 app[web.1]: at Function.initialize (/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
2019-09-01T23:36:58.401593+00:00 app[web.1]: at /app/node_modules/strapi/lib/hooks/index.js:52:31
2019-09-01T23:36:58.401595+00:00 app[web.1]: at after (/app/node_modules/strapi/lib/hooks/index.js:153:39)
2019-09-01T23:36:58.401597+00:00 app[web.1]: at /app/node_modules/lodash/lodash.js:9997:23
2019-09-01T23:36:58.401599+00:00 app[web.1]: at Strapi.once (/app/node_modules/strapi/lib/hooks/index.js:164:17)
2019-09-01T23:36:58.401601+00:00 app[web.1]: at Object.onceWrapper (events.js:286:20)
2019-09-01T23:36:58.401603+00:00 app[web.1]: at Strapi.emit (events.js:198:13)
2019-09-01T23:36:58.401605+00:00 app[web.1]: at onFinish (/app/node_modules/strapi/lib/hooks/index.js:44:12)
2019-09-01T23:36:58.401608+00:00 app[web.1]: at Promise.all.then (/app/node_modules/strapi-hook-bookshelf/lib/index.js:890:56)
2019-09-01T23:36:58.414925+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-09-01T23:36:58.415422+00:00 app[web.1]: npm ERR! errno 1
2019-09-01T23:36:58.416991+00:00 app[web.1]: npm ERR! cms@0.1.0 start: `strapi start`
2019-09-01T23:36:58.417159+00:00 app[web.1]: npm ERR! Exit status 1
2019-09-01T23:36:58.417605+00:00 app[web.1]: npm ERR!
2019-09-01T23:36:58.417609+00:00 app[web.1]: npm ERR! Failed at the cms@0.1.0 start script.
2019-09-01T23:36:58.417611+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-01T23:36:58.431408+00:00 app[web.1]:
2019-09-01T23:36:58.431660+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-09-01T23:36:58.431891+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-09-01T23_36_58_418Z-debug.log
2019-09-01T23:36:58.494781+00:00 heroku[web.1]: Process exited with status 1
2019-09-01T23:42:29.287956+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ramen-noob.herokuapp.com request_id=1dba3324-5fd7-40ba-8f3e-bd2d1f5d4399 fwd="109.220.189.216" dyno= connect= service= status=503 bytes= protocol=https
2019-09-01T23:42:29.655599+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ramen-noob.herokuapp.com request_id=67822e07-6076-40bc-9f0f-6c148a4b92e2 fwd="109.220.189.216" dyno= connect= service= status=503 bytes= protocol=https`

**Expected behavior**
Same as local

**Additional context**
Everything was fine before on Heroku, Last modifications with strapi was about adding a new content type.
I added this on the model
`  afterCreate: async entry => {
    axios
      .post(strapi.config.currentEnvironment.staticWebsiteBuildURL, entry)
      .catch(() => {
        // Ignore
      });
  },

  // Before updating a value.
  // Fired before an `update` query.
  // beforeUpdate: async (model, attrs, options) => {},

  // After updating a value.
  // Fired after an `update` query.
  // afterUpdate: async (model, attrs, options) => {
  afterUpdate: async entry => {
    axios
      .post(strapi.config.currentEnvironment.staticWebsiteBuildURL, entry)
      .catch(() => {
        // Ignore
      });
  },

  // Before destroying a value.
  // Fired before a `delete` query.
  // beforeDestroy: async (model, attrs, options) => {},

  // After destroying a value.
  // Fired after a `delete` query.
  // afterDestroy: async (model, attrs, options) => {
  afterDestroy: async entry => {
    axios
      .post(strapi.config.currentEnvironment.staticWebsiteBuildURL, entry)
      .catch(() => {
        // Ignore
      });
  },`

Thanks for your help. I really love this project.

**Comment by barbgegrasse** [comment]
![baptemebiplan](https://user-images.githubusercontent.com/33042640/64099191-f60f4700-cd68-11e9-941c-427757a5dd3b.jpg)
Added a capture for a better reading.

**Comment by derrickmehaffy** [comment]
Users issue relates to a carrot in the graphql version (unrelated but another issue noticed was an alpha package in the beta project:

https://github.com/barbgegrasse/dev-strapi/commit/09dc4529862b1adf1a60218f9bdb6027aa4f03c1

`package.json`
`"strapi-plugin-graphql": "^3.0.0-beta.15",` => `"strapi-plugin-graphql": "3.0.0-beta.15",`
`"strapi-provider-upload-cloudinary": "^3.0.0-alpha.15",` => `"strapi-provider-upload-cloudinary": "3.0.0-beta.15",`
