### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by omgbox** [strapi/strapi#3888]
**OVH VPS, Debian 8 64 bit**
------------------------------------------------------------------------------------------------------

**Kernel info** 
-------------------------------------------------------------------------------------------------------
**\Linux version 2.6.32-042stab127.2 (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Thu Jan 4 16:41:44 MSK 2018**

**failed in**
--------------------------------------------------------------------------------------------------------
Command: node lib/install.js
Arguments:
Directory: /root/demo/node_modules/pngquant-bin
Output:
⚠ Command failed: /root/demo/node_modules/pngquant-bin/vendor/pngquant --version
FATAL: kernel too old

  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/root/demo/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
---------------------------------------------------------------------------------------------------------

**Comment by omgbox** [comment]
apt-get install libpng-dev 

fixed the issue, i was really blind
