### ISSUE TITLE
python, file upload: 500 internal server error: Cannot destructure property `refId` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by emptyopen** [strapi/strapi#3908]
Trying to send a simple file upload request in Python, but cannot get it to work. I can get it to work in Postman. 

**Describe the bug**
I send a request with Authorization and form-data including the file, but get a 500 internal server error: 

> [2019-09-05T18:50:04.751Z] error TypeError: Cannot destructure property `refId` of 'undefined' or 'null'.
>     at upload (/home/ubuntu/project.strapi/node_modules/strapi-plugin-upload/controllers/Upload.js:26:66)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

**Steps to reproduce the behavior**
Send a request with the Python code below. 

**Expected behavior**
A 200 response. 

**Screenshots**
I am able to successfully upload the file using the same process in Postman: 
![image](https://user-images.githubusercontent.com/18575100/64371059-88675300-cfd4-11e9-9895-ba5ee5a0cad6.png)

**Code snippets**
```
text = open(filepath, 'rb').read()
body = aiohttp.formdata.FormData()
body.add_field('files', text, filename=f'{filepath}')
resp = await session.post(url=self.ip_address + '/upload',
                          headers={'Authorization': f'Bearer {self.jwt}'},
                          data={'files': body})
resp.raise_for_status()
html = await resp.text()
return html
```

**System**
- Node.js version: v10.13.0
- NPM version: v6.4.1
- Strapi version: v3.0.0
- Database: MongoDB
- Operating system: Mac

**Additional context**

**Comment by emptyopen** [comment]
I resolved this by changing the parameter in post() to just data=body
