### ISSUE TITLE
Enumeration Field does not allow for special characters

### ISSUE THREAD

**Issue by sdoering** [strapi/strapi#3921]
**Description**
After having created a content model I wanted to add an enumeration field to an existing model. I created the field and put in following values (examples):

- Content (Reach)
- Content (Advertising)
- Branding

This produced the following error in my console window: 

```
[2019-09-09T12:23:59.663Z] error Syntax Error: Expected Name, found (
GraphQLError: Syntax Error: Expected Name, found (
    at syntaxError (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:1404:40)
    at Parser.parseName (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:94:22)
    at Parser.parseEnumValueDefinition (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:1014:21)
    at Parser.optionalMany (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:1497:28)
    at Parser.parseEnumValuesDefinition (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:1002:17)
    at Parser.parseEnumTypeDefinition (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:986:23)
    at Parser.parseTypeSystemDefinition (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:705:23)
    at Parser.parseDefinition (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:146:23)
    at Parser.many (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/node_modules/graphql/language/parser.js:36:17)
    at Object.addPolymorphicUnionType (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/services/Types.js:159:8)
    at Object.generateSchema (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/services/Schema.js:168:59)
    at Function.initialize (/Users/sven.doering/development/internalProjects/blueprints/concept/backend/plugins/graphql/hooks/graphql/index.js:145:78)
    at /usr/local/lib/node_modules/strapi/lib/hooks/index.js:52:31
    at /usr/local/lib/node_modules/strapi/lib/hooks/index.js:153:39
    at /usr/local/lib/node_modules/strapi/node_modules/lodash/lodash.js:9999:23
    at Strapi.<anonymous> (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:164:17)
    at Object.onceWrapper (events.js:288:20)
    at Strapi.emit (events.js:200:13)
    at Strapi.EventEmitter.emit (domain.js:471:20)
    at onFinish (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:44:12)
    at /Users/sven.doering/development/internalProjects/blueprints/concept/backend/node_modules/strapi-hook-bookshelf/lib/index.js:1215:55 {
  message: 'Syntax Error: Expected Name, found (',
  locations: [ { line: 126, column: 42 } ]
}
```

**Expected behavior**
Either have the filed throw an error and explain that non alphanumeric characters are not allowed or accept them as part of a string. 

**System**
- Node.js version:  v12.4.0
- NPM version: 6.10.2 
- Strapi version: 3.0.0-alpha.26.2
- Database: sqlite
- Operating system: MacOS

**Comment by alexandrebodin** [comment]
Hi enum values should never contain spaces nor parenthesis. these are always going to break graphql. As per the [graphql spec](https://graphql.github.io/graphql-spec/June2018/#sec-Names) you need to respect the following regex: `/[_A-Za-z][_0-9A-Za-z]*/`

**Comment by sdoering** [comment]
Thanks for the information. Shouldn't the form field then check for this? Wouldn't this help less experienced users?

**Comment by alexandrebodin** [comment]
It is now in beta.16 ;)
