### ISSUE TITLE
Creating entry with uploaded file isn't working after migration beta.15 -> beta.16

### ISSUE THREAD

**Issue by rejifald** [strapi/strapi#3943]
**Describe the bug**
I used to create entry by following algorithm:
1. Uploading and compressing images
2. Creating entry with a reference to uploaded file.
Example of payload
```
{
  "name": "New company 2",
  "description": "<p>New company description</p>",
  "isVIP": false,
  "logo": {
    "_id": "5d775bbf08e55100175e9f0e",
    "name": "310x204-@WALLPAPERS.jpg",
    "sha256": "eLqaq6VQDA0ba4fIJwvFci0ze7f88hC7qzksfAOm7jY",
    "hash": "70b90cb05be048058f9dc56e538af3e2",
    "ext": ".jpg",
    "mime": "image/jpeg",
    "size": "3.91",
    "url": "https://s3.eu-west-3.amazonaws.com/mc2.ub.am-uploads/70b90cb05be048058f9dc56e538af3e2.jpg",
    "provider": "aws-s3",
    "related": [],
    "createdAt": "2019-09-10T08:15:59.621Z",
    "updatedAt": "2019-09-10T08:15:59.636Z",
    "__v": 0,
    "id": "5d775bbf08e55100175e9f0e"
  },
  "addresses": [],
  "phones": [],
  "positions": [],
  "links": [],
  "region": "cern",
  "lang": "en",
  "categories": [
    "5d50129334b6a093412b568e"
  ]
}
```
But in beta.16 I get
```
[2019-09-10T08:15:59.827Z] error TypeError: Cannot read property 'globalId' of undefined 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at /app/node_modules/strapi-hook-mongoose/lib/relations.js:214:38 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at Array.map (<anonymous>) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at /app/node_modules/strapi-hook-mongoose/lib/relations.js:210:43 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at Array.reduce (<anonymous>) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at Function.update [as updateRelations] (/app/node_modules/strapi-hook-mongoose/lib/relations.js:38:59) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at runMicrotasks (<anonymous>) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at processTicksAndRejections (internal/process/task_queues.js:93:5) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at async Promise.all (index 0) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at async Function.update [as updateRelations] (/app/node_modules/strapi-hook-mongoose/lib/relations.js:300:5) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at async Object.create (/app/node_modules/strapi/lib/core-api/service.js:52:21) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at async Object.create (/app/api/company/controllers/Company.js:49:21) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at async /app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:67:22 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at async module.exports (/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:49:14) 
Sep 10 01:16:00 mc2-api-stage app/web.1:      at async /app/node_modules/strapi-utils/lib/policy.js:111:7 
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16
- Database: MongoDB
- Operating system: MacOS

**Comment by alexandrebodin** [comment]
@rejifald Have you tried sending the payload with `"logo": "5d775bbf08e55100175e9f0e"` ?

**Comment by rejifald** [comment]
> @rejifald Have you tried sending the payload with `"logo": "5d775bbf08e55100175e9f0e"` ?

Sure. And I get same result.

**Comment by rejifald** [comment]
How can I pull this fix ? Will it be in next release, or ... ?

**Comment by alexandrebodin** [comment]
@rejifald This will be released later today
