### ISSUE TITLE
Strapi unable to pull roles from alternative database

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3953]
**Describe the bug**
Related to this PR: https://github.com/strapi/strapi/pull/3934
(Sorry @alexandrebodin I forgot to test with my own project :man_facepalming: )

Error Stack Trace
```
[2019-09-10T18:44:12.558Z] error Error: ER_NO_SUCH_TABLE: Table 'capiv2_base.users-permissions_role' doesn't exist
    at Query.Sequence._packetToError (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/mysql/lib/Connection.js:201:25)
    at /mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/knex/lib/dialects/mysql/index.js:130:18
    at Promise._execute (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/knex/lib/dialects/mysql/index.js:124:12)
    at Client_MySQL.query (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/knex/lib/client.js:158:17)
    at /mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/knex/lib/transaction.js:325:24
    at Promise._execute (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.trxClient.query (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/knex/lib/transaction.js:320:12)
    at Runner.query (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/knex/lib/runner.js:135:36)
    at /mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/util.js:16:23)
    at /mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/mnt/storage/Github/Canonn/CAPIv2-Strapi/node_modules/bluebird/js/release/promise.js:699:18)
```

**Steps to reproduce the behavior**
1. Set default database to something like (strapi_data)
2. Set users-permissions_roles connection to an alternative database (strapi_users)
3. Attempt to start server
4. See that Strapi is not using the model connection setting properly

**Expected behavior**
Strapi should be reading the connection variable in the model.settings.json and appending it properly instead of using the default 

**Screenshots**

![image](https://user-images.githubusercontent.com/8593673/64641672-80872480-d3c1-11e9-95cd-7f701f460938.png)

![image](https://user-images.githubusercontent.com/8593673/64641712-9c8ac600-d3c1-11e9-932d-afcef5695891.png)

**Code snippets**
N/A

**System**
- Node.js version: v12
- NPM version: v6
- Strapi version: beta.16.1
- Database: MariaDB 10.4
- Operating system: Ubuntu 18.04 LTS

**Additional context**
N/A

**Comment by derrickmehaffy** [comment]
Reverting back to beta.16 Strapi works as intended.
