### ISSUE TITLE
Webpack error on strapi develop

### ISSUE THREAD

**Issue by martineon** [strapi/strapi#3981]
Hello !

First of all, thanks for the amazing work you're doing !

**Describe the bug**
I've got an issue with `strapi develop` on the latest beta version of Strapi when creating a new project.
I tried quick start and manual setting, and each time the `strapi develop` crash at 88% saying:  `Error: Conflict: Multiple assets emit to the same filename a32fc4c1a0dea6e8b686eb9f2fda5266.png`

i've tried multiple things such as:
 - `npm cache clean --force` => `rm -rf node_modules package-lock.json yarn.lock` => `npm install`
- using `yarn` instead of `npm`

But nothing seems to work...

I'm a bit in a deadlock... 😅

So if you have any solutions or advise to find out where it could came from ! 😉

**Code snippets**

Error :
````
$ strapi develop
Building your admin UI with development configuration ...

● Webpack █████████████████████████ after hashing (88%)


/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1994
				throw new Error(
				^

Error: Conflict: Multiple assets emit to the same filename a32fc4c1a0dea6e8b686eb9f2fda5266.png
    at Compilation.emitAsset (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1994:11)
    at Compilation.createModuleAssets (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:2075:11)
    at hooks.optimizeTree.callAsync.err (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1375:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1323:27)
    at compilation.finish.err (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compiler.js:675:18)
    at hooks.finishModules.callAsync.err (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1242:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1234:28)
    at hooks.make.callAsync.err (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compiler.js:672:17)
    at _done (eval at create (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at _addModuleChain (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1166:12)
    at processModuleDependencies.err (/Users/eonmartin/Documents/WORK/Escourbiac/site/test/node_modules/webpack/lib/Compilation.js:1078:9)
error Command failed with exit code 1.
````

`package.json`
```
{
  "name": "test",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "lint": "eslint ."
  },
  "devDependencies": {
    "babel-eslint": "^10.0.0",
    "eslint": "^6.0.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-react": "^7.14.0"
  },
  "dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-beta.16.2",
    "strapi-admin": "3.0.0-beta.16.2",
    "strapi-utils": "3.0.0-beta.16.2",
    "strapi-plugin-settings-manager": "3.0.0-beta.16.2",
    "strapi-plugin-content-type-builder": "3.0.0-beta.16.2",
    "strapi-plugin-content-manager": "3.0.0-beta.16.2",
    "strapi-plugin-users-permissions": "3.0.0-beta.16.2",
    "strapi-plugin-email": "3.0.0-beta.16.2",
    "strapi-plugin-upload": "3.0.0-beta.16.2",
    "strapi-hook-mongoose": "3.0.0-beta.16.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "2d209148-5e35-45b8-bdc7-77b3fecee052"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

**System**
- Node.js version: v10.15.0
- NPM version: 6.6.0
- Strapi version: 3.0.0-beta.16.2
- Database: Mongo v4.0.9
- Operating system: MacOS Mojave 10.14.5

**Comment by izzuddinnatsir** [comment]
Webpack 4.40.1 is out already with the fix for this bug

**Comment by epaprat** [comment]
> @epaprat how to do this downgrade? edit the pacakge.json inside node_modules?

just installed webpack@4.39.3 with npm to the project but as @izzuddinnatsir mentioned they already fix this issue with webpack.
