### ISSUE TITLE
Error when running "npx create-strapi-app my-project --quickstart"

### ISSUE THREAD

**Issue by rafaelsaback** [strapi/strapi#3982]
**Describe the bug**

When I try to create a Strapi app using the `npx` command, I get the following error:
```
Building your admin UI with development configuration ...

● Webpack █████████████████████████ after hashing (88%)  
 

/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1994
				throw new Error(
				^

Error: Conflict: Multiple assets emit to the same filename 4b01bcdb1773d629a105a7754dc9ded1.png
    at Compilation.emitAsset (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1994:11)
    at Compilation.createModuleAssets (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:2075:11)
    at hooks.optimizeTree.callAsync.err (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1375:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxx/workspace/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/workspace/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1323:27)
    at compilation.finish.err (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compiler.js:675:18)
    at hooks.finishModules.callAsync.err (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1242:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxx/workspace/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/workspace/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1234:28)
    at hooks.make.callAsync.err (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compiler.js:672:17)
    at _done (eval at create (/home/xxx/workspace/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (/home/xxx/workspace/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at _addModuleChain (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1166:12)
    at processModuleDependencies.err (/home/xxx/workspace/my-project/node_modules/webpack/lib/Compilation.js:1078:9)
```
**Steps to reproduce the behavior**
1. Run `npx create-strapi-app my-project --quickstart`

**Expected behavior**
The project should be created and run in development mode without errors

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.16.3 
- NPM version: 6.9.0
- Strapi version: I assume `npx` gets the latest Strapi version 
- Database: MongoDB
- Operating system: Ubuntu 18.04

**Additional context**

**Comment by fitztrev** [comment]
Webpack v4.40.1 has been released and fixes this.

**Comment by soupette** [comment]
@fitztrev do you feel like submitting a PR to update the package?

**Comment by fitztrev** [comment]
@soupette sure, I'm not familiar with this project (only found the linked issue because of searching the error message) but I'll try! - https://github.com/strapi/strapi/pull/3992
