### ISSUE TITLE
GraphQL Authentication confusing error message - should be just "Forbidden"

### ISSUE THREAD

**Issue by ceefour** [strapi/strapi#4001]
**Describe the bug**

GraphQL Authentication confusing error message: should be just "Forbidden"

**Steps to reproduce the behavior**
1. Set DB to MongoDB
2. Run any authenticated GraphQL query with `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkN2RjY2Y4NzQyODEzNDJhNDliZmQ0ZCIsImlhdCI6MTU2ODUyNjgwMSwiZXhwIjoxNTcxMTE4ODAxfQ.VZGU5Nb91Ac-lF16XeqcbopM3HawTMcVGY61QcwJ8go
`
3. Error:

```
[GraphQL error]: Message: Cast to ObjectId failed for value "1" at path "_id" for model "UsersPermissionsUser", Location: [object Object], Path: projects
GraphQL error occurred [getDataFromTree] { Error: GraphQL error: Cast to ObjectId failed for value "1" at path "_id" for model "UsersPermissionsUser"
    at new ApolloError (d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:92:26)
    at d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:1587:34
    at d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:2007:15
    at Set.forEach (<anonymous>)
    at d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:2005:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:2003:20)
    at d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:2130:19
    at Object.next (d:\project_amanah\soluvas\appstudio\node_modules\zen-observable\lib\Observable.js:308:23)
    at notifySubscription (d:\project_amanah\soluvas\appstudio\node_modules\zen-observable\lib\Observable.js:130:18)
    at onNotify (d:\project_amanah\soluvas\appstudio\node_modules\zen-observable\lib\Observable.js:165:3)
    at SubscriptionObserver.next (d:\project_amanah\soluvas\appstudio\node_modules\zen-observable\lib\Observable.js:219:7)
    at d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:1101:36
    at Set.forEach (<anonymous>)
    at Object.next (d:\project_amanah\soluvas\appstudio\node_modules\apollo-client\bundle.umd.js:1100:21)
    at notifySubscription (d:\project_amanah\soluvas\appstudio\node_modules\zen-observable\lib\Observable.js:130:18)
  graphQLErrors:
   [ { message:
        'Cast to ObjectId failed for value "1" at path "_id" for model "UsersPermissionsUser"',
       locations: [Array],
       path: [Array],
       extensions: [Object] } ],
  networkError: null,
  message:
   'GraphQL error: Cast to ObjectId failed for value "1" at path "_id" for model "UsersPermissionsUser"',
  extraInfo: undefined }
```

**Expected behavior**

If JWT `sub` and User ID in database doesn't match type, simply give `Forbidden` error.

**System**
- Node.js version: 10.16.3
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.16.3
- Database: MongoDB
- Operating system: Windows 10 1903

**Comment by lauriejim** [comment]
Hello, thank you for reporting this point. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by bahdcoder** [comment]
@lauriejim I'm taking this one ✋

**Comment by lauriejim** [comment]
Great thank you! 
Waiting to see your pull request!

**Comment by lauriejim** [comment]
The right error message is displayed in the last version of Strapi (at least betat.17.8)
