### ISSUE TITLE
Cannot create entries using lifecycle methods

### ISSUE THREAD

**Issue by wysher** [strapi/strapi#4003]
**Describe the bug**
I've updated strapi from beta.14 to beta.16.3 using migration guide and now I cannot create entries using lifecycle methods. In my case for each purchase should be created first payment, so I do (simplified):

```
// api/models/purchase/models/Purchase.js

  afterCreate: async (model, attrs, options) => {
    console.log('before create payment');
    await strapi.services.payment.create({ name: 'foo' });
    console.log('after create payment');
  },
```
Creating purchase causes app to freeze after consoling 'before create payment'.
After a while I'll get:

```
[2019-09-15T10:11:34.333Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Bluebird.try.then.catch (/home/wysher/apps/api/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:318:17)
    at tryCatcher (/home/wysher/apps/api/node_modules/bluebird/js/release/util.js:16:23)
    at /home/wysher/apps/api/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/home/wysher/apps/api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/wysher/apps/api/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/wysher/apps/api/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/wysher/apps/api/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/wysher/apps/api/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/home/wysher/apps/api/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/wysher/apps/api/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/wysher/apps/api/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/wysher/apps/api/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
```

**Expected behavior**
As before - allow to create entries using lifecycle methods as with beta.14.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: node 11.5
- NPM version: 6.7.0
- Strapi version: beta.16.3
- Database: sqlite
- Operating system: Manjaro Linux

**Comment by derrickmehaffy** [comment]
Marking as duplicate and linking to the rework issue: https://github.com/strapi/strapi/issues/1443
