### ISSUE TITLE
Compile error when starting strapi in development mode

### ISSUE THREAD

**Issue by cube-dan** [strapi/strapi#4015]
**Describe the bug**
After update from beta11 to beta16 following [the only available beta update guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/#beta-guides) I get this error on startup:
```
Error: Module not found: Error: Can't resolve 'react-intl/locale-data/ar' in '.../src/.cache/admin/src'
```
Full error output is below.

**Steps to reproduce the behavior**
1. Have a stable beta11 install running
2. Follow beta15 -> beta16 [update guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/#beta-guides) after altering bookshelf/knex dependency info to use mongoose. 

**Note**: Update guide for beta16 includes doing a `strapi build` step. At this point strapi would not build until I added "react-datetime" and "react-intl". After adding these dependencies the `strapi build` step from the beta16 update worked without any errors. I proceeded to the next step in the update doc "[Updating your code](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html#updating-your-code)" before moving to step 3, below.

3. Start up strapi, see error, delete src/.cache folder, startup strapi, see error.

3.5. notice that `strapi -v` is still returning 3.0.0-beta.11, run `npm install -g strapi@beta`, startup strapi, see different locale missing (see below), delete src/.cache folder, startup strapi, see error about "ar" locale again.

4. Say poop.

**Expected behavior**
Yo. Strapi should startup. Kid.

**Code snippets**
none

**System**
- Node.js version: v10.15.3 
- **Yarn** version: 1.17.3
- Strapi version: 3.0.0-beta.16.3 
- Database: mongod v4.0.3
- Operating system: MacOS 10.14.6

**A working theory**
I'm guessing that there are some migration guides missing on [the guides page](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/#beta-guides). As of this writing  
I've successfully migrated using the [alpha26 to beta guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html) to do a previous update. Since there was no guide for beta11 to beta16 available on the [guides list page](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/) I thought I'd give the beta15 to beta16 guide a shot. 

The beta15 to beta16 guide didn't mention that I'd need to install a couple of new dependencies (@ step "Building your administration panel", had to add "react-datetime" and "react-intl", see reproduction step #2, above) and the first section "[Upgrading your dependencies](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html#updating-your-code)" didn't mention steps to take if you're using mongoose (PR on the way for this) I'm guessing there are other details that need filling in. 

There's likely something I've missed along the way but I can't tell what that is from the available docs. Any help is appreciated. 

-Dan

**Additional context**
This is the full error output from `strapi build` when starting up from yarn using the `strapi develop` script.

```
Error: Module not found: Error: Can't resolve 'react-intl/locale-data/ar' in '.../src/.cache/admin/src'
    at compiler.run (.../src/node_modules/strapi-admin/index.js:144:23)
    at finalCallback (.../src/node_modules/webpack/lib/Compiler.js:220:39)
    at onCompiled (.../src/node_modules/webpack/lib/Compiler.js:228:20)
    at hooks.make.callAsync.err (.../src/node_modules/webpack/lib/Compiler.js:620:21)
    at _err1 (eval at create (.../src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at _addModuleChain (.../src/node_modules/webpack/lib/Compilation.js:1079:13)
    at processModuleDependencies.err (.../src/node_modules/webpack/lib/Compilation.js:1002:25)
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)
    at .../src/node_modules/neo-async/async.js:2818:7
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at ..../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)
```

This is the full error output from `strapi build`, when starting up from yarn using the `strapi develop` script, immediately after doing a `npm install -g strapi@beta` as mentioned in **Steps to reproduce the behavior** step 3.5

```
Error: Module not found: Error: Can't resolve 'react-intl/locale-data/de' in '.../src/.cache/admin/src'
    at compiler.run (.../src/node_modules/strapi-admin/index.js:144:23)
    at finalCallback (.../src/_/api/src/node_modules/webpack/lib/Compiler.js:220:39)
    at onCompiled (.../src/_/api/src/node_modules/webpack/lib/Compiler.js:228:20)
    at hooks.make.callAsync.err (.../src/_/api/src/node_modules/webpack/lib/Compiler.js:620:21)
    at _err1 (eval at create (.../src/_/api/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at _addModuleChain (.../_/api/src/node_modules/webpack/lib/Compilation.js:1079:13)
    at processModuleDependencies.err (.../src/_/api/src/node_modules/webpack/lib/Compilation.js:1002:25)
    at asyncLib.forEach.err (...//src/_/api/src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/_/api/src/node_modules/neo-async/async.js:2830:7
    at .../src/_/api/src/node_modules/neo-async/async.js:2830:7
    at done (...//src/_/api/src/node_modules/neo-async/async.js:2863:11)
    at .../src/_/api/src/node_modules/neo-async/async.js:2818:7
    at asyncLib.forEach.err (/...//src/_/api/src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/_/api/src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)
```

**Comment by cube-dan** [comment]
**Update:**
After downgrading from react-intl@3 (see note in "**Steps to reproduce the behavior**", above) using `yarn add react-intl@2.9.0` I was able to get past the `Can't resolve 'react-intl/locale-data/ar'` error and hit 3 more missing dependencies; full errors at bottom, errors came in this order between `yarn add` calls:
1. Error: Can't resolve 'video-react'
2. Error: Can't resolve 'react-select'
3. Error: Can't resolve 'draft-js'

After getting past the missing dependencies I hit this:
```
error TypeError: fn is not a function
    at execBootstrap (.../src/node_modules/strapi/lib/Strapi.js:381:15)
    at Strapi.runBootstrapFunctions (.../src/node_modules/strapi/lib/Strapi.js:399:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The migration docs mention that [your bootstrap function](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html#bootstrap-function) no longer takes a cb argument. Since I wasn't using any bootstrap function I made the mistake of replacing the the existing 
```
module.exports = (cb) => { 
  cb() 
};
```
with this:
```
module.exports = {}; 
```
...which caused the `fn is not a function` error. 

I dropped this in instead to get strapi back up. 
```
module.exports = () => {};
```

**The TL;DR is "you need to"**:
```
yarn add react-intl@2.9.0 react-datetime video-react react-select draft-js
```
... somewhere at the top of the beta15 to beta16 migration document ... unless something else is horribly broken with my strapi install and adding these deps magically fixed it!?

Thanks for your time guys. Strapi is starting up for me now. Please let me know if there was a better way to get strapi running again instead of doing `yarn fix stuff`.

**Full error output**:

```
Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (65%) 720/779 modules 59 active
 node_modules/react-dnd-html5-backend/dist/esm/NativeDragSources/index.js

Error: Module not found: Error: Can't resolve 'video-react' in '.../src/.cache/admin/src/components/OnboardingVideo'
    at compiler.run (.../src/node_modules/strapi-admin/index.js:144:23)
    at finalCallback (.../src/node_modules/webpack/lib/Compiler.js:220:39)
    at onCompiled (.../src/node_modules/webpack/lib/Compiler.js:228:20)
    at hooks.make.callAsync.err (.../src/node_modules/webpack/lib/Compiler.js:620:21)
    at _err1 (eval at create (.../src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at _addModuleChain (.../src/node_modules/webpack/lib/Compilation.js:1079:13)
    at processModuleDependencies.err (.../src/node_modules/webpack/lib/Compilation.js:1002:25)
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)
    at .../src/node_modules/neo-async/async.js:2818:7
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)

● Webpack █████████████████████████ building (66%) 1035/1098 modules 63 active
 babel-loader › .cache/plugins/strapi-plugin-content-manager/admin/src/containers/SettingViewModel/components.js

Error: Module not found: Error: Can't resolve 'react-select' in '.../src/.cache/plugins/strapi-plugin-content-manager/admin/src/components/SelectMany'
    at compiler.run (.../src/node_modules/strapi-admin/index.js:144:23)
    at finalCallback (.../src/node_modules/webpack/lib/Compiler.js:220:39)
    at onCompiled (.../src/node_modules/webpack/lib/Compiler.js:228:20)
    at hooks.make.callAsync.err (.../src/node_modules/webpack/lib/Compiler.js:620:21)
    at _err1 (eval at create (.../src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at _addModuleChain (.../src/node_modules/webpack/lib/Compilation.js:1079:13)
    at processModuleDependencies.err (.../src/node_modules/webpack/lib/Compilation.js:1002:25)
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)
    at .../src/node_modules/neo-async/async.js:2818:7
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)

● Webpack █████████████████████████ building (67%) 1226/1283 modules 57 active
 file-loader › .cache/plugins/strapi-plugin-content-type-builder/admin/src/assets/images/one_to_one.svg

Error: Module not found: Error: Can't resolve 'draft-js' in '.../src/.cache/plugins/strapi-plugin-content-manager/admin/src/components/Wysiwyg'
    at compiler.run (.../src/node_modules/strapi-admin/index.js:144:23)
    at finalCallback (.../src/node_modules/webpack/lib/Compiler.js:220:39)
    at onCompiled (.../src/node_modules/webpack/lib/Compiler.js:228:20)
    at hooks.make.callAsync.err (.../src/node_modules/webpack/lib/Compiler.js:620:21)
    at _err1 (eval at create (.../src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at _addModuleChain (.../src/node_modules/webpack/lib/Compilation.js:1079:13)
    at processModuleDependencies.err (.../src/node_modules/webpack/lib/Compilation.js:1002:25)
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)
    at .../src/node_modules/neo-async/async.js:2818:7
    at asyncLib.forEach.err (.../src/node_modules/webpack/lib/Compilation.js:918:13)
    at .../src/node_modules/neo-async/async.js:2830:7
    at .../src/node_modules/neo-async/async.js:2830:7
    at done (.../src/node_modules/neo-async/async.js:2863:11)
```

**Comment by lauriejim** [comment]
Did you remove your `yarn.lock` before installing dependencies ?

**Comment by cube-dan** [comment]
Jim, 

Looks like [I missed that step](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html#clean-your-node-modules). 

Thanks for the heads up! I'll try again and let you know the result here.

-Dan

**Comment by cube-dan** [comment]
Jim, 

To clarify. I had already successfully migrated from alpha26 to beta11 before I attempted the update from beta11 to beta16. 

I did clean my lock and node_modules when moving from alpha to beta but didn't clean everything out because that step wasn't listed in [the beta15 to beta16 guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html#updating-your-code).

What I'll do is try the 15->16 migration again and if it works I'll drop in a PR for the 15->16 guide to include the [cleanup step from the alpha->beta guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html#clean-your-node-modules).

Thanks again Jim.

-Dan

**Comment by lauriejim** [comment]
OKay thank you for the details, let me know.

**Comment by mateja176** [comment]
> Did you remove your `yarn.lock` before installing dependencies ?

The error persists:

```
Error: Module not found: Error: Can't resolve '@buffetjs/styles/webfonts/Lato-Black.woff2' in '.cache/admin/src/components/Fonts
```

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
