### ISSUE TITLE
Login with API no longer after update to beta16 from beta11

### ISSUE THREAD

**Issue by cube-dan** [strapi/strapi#4022]
**Describe the bug**
After updating to beta16 (from beta 11) login using API and using [login example in strapi documentation](https://strapi.io/documentation/3.0.0-beta.x/guides/authentication.html#local) is no longer possible because of error: 
```
error ObjectParameterError: Parameter "obj" to Document() must be an object, got ABSTRACT
```
**Steps to reproduce the behavior**
1. Have working strapi.beta11 install.
2. Follow [migration guide for beta15 to beta16](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html) but substitute:
```
"strapi-hook-bookshelf": "3.0.0-beta.16",
"strapi-hook-knex": "3.0.0-beta.16",
```
with
```
"strapi-hook-mongoose": "^3.0.0-beta.16"
```
3. Startup strapi, [hit API from axios](https://strapi.io/documentation/3.0.0-beta.x/guides/authentication.html#local)
4. Kaboom. Such sad. Much crying. So restore from backup.

**Expected behavior**
Status 200! Here's your JWT, Kid.

To get this fixed I attempted a fresh strapi build using `strapi new cool-project-name` and then migrating my existing API into the new {root}/api folder, and my existing {root}/extensions/users-permissions/models/User.settings.json into the new extensions folder. 

This didn't help. Same error happens in original project (migrated) and in newly shiny strapi project. 

Thanks in advance for your help on this team strapi. 

**System**
- Node.js version: v10.15.3 
- Yarn version: 1.17.3
- Strapi version: 3.0.0-beta.16.3 
- Database: mongod v4.0.3
- Operating system: MacOS 10.14.6

**Additional context**
```
Full error text: 
 error ObjectParameterError: Parameter "obj" to Document() must be an object, got ABSTRACT
    at new ObjectParameterError (.../src/node_modules/mongoose/lib/error/objectParameter.js:25:11)
    at model.Document (.../src/node_modules/mongoose/lib/document.js:74:11)
    at model.Model (.../src/node_modules/mongoose/lib/model.js:92:12)
    at new model (.../src/node_modules/mongoose/lib/model.js:4289:15)
    at classToInvokable (.../src/node_modules/sequelize/lib/utils/classToInvokable.js:12:10)
    at _.each (.../src/node_modules/sequelize/lib/data-types.js:1048:22)
    at .../src/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (.../src/node_modules/lodash/lodash.js:2990:24)
    at .../src/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (.../src/node_modules/lodash/lodash.js:9342:14)
    at Object.<anonymous> (.../src/node_modules/sequelize/lib/data-types.js:1047:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (.../src/node_modules/sequelize/lib/utils.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (.../src/node_modules/sequelize/lib/sequelize.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

**Comment by lauriejim** [comment]
Did you remove your `yarn.lock` file before installing dependencies?

**Comment by derrickmehaffy** [comment]
Also ensure your package.json doesn't have carrots `^` in front of strapi package versions

**Comment by cube-dan** [comment]
Jim, Derrick, 

I'll clean out *.lock and node_modules, remove the `^`s, give it all another go, and let you know how it turns out here.

Thanks for your help on this one; truly appreciated!

-Dan

**Comment by cube-dan** [comment]
Derrick,

Thanks for the heads up on the `^`s. Looking at my lock file it looks like I'm actually running "3.0.0-next.17" for most of my install ... not beta11.

I've removed the `^`s from all my strapi deps which should bring down the confusion!

I'll proceed as though I'm still on beta11 unless you (or Jim) have other advice for me. 

Thanks again for you help and keen eye ... must be all the carrots you're eating?

-Dan

**Comment by lauriejim** [comment]
Thank you for the detail, let us know if it works.

**Comment by derrickmehaffy** [comment]
For now marking this as closed, if you need further assistance @cube-dan let us know and this can be reopened.

**Comment by cube-dan** [comment]
Thanks for taking a look guys. I've migrated to from beta11 => 3.0.1 => 3.0.4 and whatever gook was gumming up the works it's been cleaned out and 3.0.4 is running like a dream. Thanks for the help and for making strapi so ... amazing!

-Dan
