### ISSUE TITLE
Don't have any user roles created on first creation of app

### ISSUE THREAD

**Issue by futbotism** [strapi/strapi#404]
**Node.js version**: v7.6.0
**npm version**: 4.1.2
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: mac osx high sierra

When i load the Auth & Permissions section of the admin interface the `http://localhost:1337/users-permissions/roles` doesn't load and i get a `{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Not found"}]}]}`

there doesn't seem to be a `guest` or `admin` role

This may be related, when i run `strapi start` i get the console error

```
    /Users/andrewalvino/Documents/projects/velocity/velocity-api/plugins/users-permissions/services/UsersPermissions.js:121
    )
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Strapi.loadFile (/Users/andrewalvino/Documents/projects/velocity/velocity-api/node_modules/strapi/lib/utils/index.js:18:14)
    at Object.setConfig (/Users/andrewalvino/Documents/projects/velocity/velocity-api/node_modules/strapi/lib/utils/index.js:32:19)
```

**Comment by futbotism** [comment]
when i changed the formatting in the console error to, 

`getRoleConfigPath: () => (path.join(strapi.config.appPath,'plugins','users-permissions','config','roles.json')),`

It worked 👍

**Comment by lauriejim** [comment]
Hello @futbotism , thank you for this issue.
If you upgrade to node `8` and npm `5` it will fix this problem.

Can you make a PR with your changes please. It will help users who use node `7`
