### ISSUE TITLE
Error after migrating from 14 to 16

### ISSUE THREAD

**Issue by nezzard** [strapi/strapi#4042]
After migrating from 14 to 16, i got error TypeError: Cannot read property 'bind' of undefined
`[2019-09-18T13:44:53.495Z] debug ⛔️ Server wasn't able to start properly.
[2019-09-18T13:44:53.496Z] error TypeError: Cannot read property 'bind' of undefined
    at routerChecker (D:\MegaSync\Работа\movie2\strapi\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:33:43)
    at D:\MegaSync\Работа\movie2\strapi\node_modules\strapi\lib\middlewares\router\utils\composeEndpoint.js:16:34
    at _.forEach.value (D:\MegaSync\Работа\movie2\strapi\node_modules\strapi\lib\middlewares\router\index.js:25:9)
    at arrayEach (D:\MegaSync\Работа\movie2\strapi\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (D:\MegaSync\Работа\movie2\strapi\node_modules\lodash\lodash.js:9342:14)
    at Object.initialize (D:\MegaSync\Работа\movie2\strapi\node_modules\strapi\lib\middlewares\router\index.js:24:9)
    at Promise.resolve.then (D:\MegaSync\Работа\movie2\strapi\node_modules\strapi\lib\middlewares\index.js:54:28)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**System**
- Node.js version: 11.13.0
- NPM version: 6.7.0
- Strapi version:  3.0.0-beta.16
- Database: MongoDB
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello! When you updated your application, did you remove your package-lock.json or your yarn.lock?

**Comment by nezzard** [comment]
> Hello! When you updated your application, did you remove your package-lock.json or your yarn.lock?

No

**Comment by derrickmehaffy** [comment]
> > Hello! When you updated your application, did you remove your package-lock.json or your yarn.lock?
> 
> No

best to delete node_modules, build, .cache, package-lock.json, and yarn.lock and rerun `npm i` / `yarn install` and `npm run build` / `yarn build`

**Comment by nezzard** [comment]
> > > Hello! When you updated your application, did you remove your package-lock.json or your yarn.lock?
> > 
> > 
> > No
> 
> best to delete node_modules, build, .cache, package-lock.json, and yarn.lock and rerun `npm i` / `yarn install` and `npm run build` / `yarn build`

I deleted node_modules, build, .cache, yarn.lock, than run yarn install, after that yarn build, after that yarn develop. and got an error

**Comment by nezzard** [comment]
Fixed, by full reinstall to new folder.
But now i have other problem, i can't see my content types in public user permissions, i can see it only in Authenticated
