### ISSUE TITLE
Documentation plugin in 3.0.0-beta.16.3 not working with group content-type.

### ISSUE THREAD

**Issue by akmdi** [strapi/strapi#4046]
Tried creating a group content-type through the admin panel. But got an error in the documentation plugin.

error Bootstrap function in plugin "documentation" failed
[2019-09-18T18:20:28.457Z] error TypeError: Cannot read property 'filter' of undefined
    at Object.keys.reduce (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:625:51)
    at Array.reduce (<anonymous>)
    at Object.generateMainComponent (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:605:36)
    at Object.keys.reduce (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:662:28)
    at Array.reduce (<anonymous>)
    at Object.generateMainComponent (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:605:36)
    at Object.generateResponseComponent (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:1071:32)
    at Object.keys.reduce (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:203:18)
    at Array.reduce (<anonymous>)
    at Object.createPluginDocumentationFile (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:195:45)
    at Object.checkIfPluginDocNeedsUpdate (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/services/Documentation.js:64:12)
    at pluginsWithDocumentationNeeded.forEach.plugin (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/config/functions/bootstrap.js:44:46)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/negd/MyApps/myproject/myproject-api/node_modules/strapi-plugin-documentation/config/functions/bootstrap.js:28:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.

**Comment by alexandrebodin** [comment]
@akmdi This is fixed in latest beta version. make sure to upgrade ;)
