### ISSUE TITLE
(hook:knex) wasn't loaded due to missing key `enabled`

### ISSUE THREAD

**Issue by ArkhipovK** [strapi/strapi#410]
**Node.js version**: v8.9.3
**npm version**:  5.5.1
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: Win7 Ultimate

Hello, yesterday i tried to start new strapi project with remote heroku database (postgres), but faced the couple of issues. 

My database.json configuration file:
`
{
    "defaultConnection": "default",
    "connections": {
        "default": {
            "connector": "strapi-bookshelf",
            "settings": {
                "client": "postgres",
                "host": "ec2-54-83-3-101.compute-1.amazonaws.com",
                "port": 5432,
                "username": "yemvqhgxorgmjt",
                "password": "************",
                "database": "******",
                "schema": "public"
            },
            "options": {}
        }
    }
}
`

The first time i tried to start strapi, it warned me that there is no strapi-bookshelf hook. It's weird, because "strapi-bookshelf" has to be the part of the framework.

> C:\Users\Admin\Documents\My Web Sites\boxing-therapy-backend\git\backend>strapi start
> **WARN (6384 on Admin-ÏÊ): (hook:bookshelf) `strapi-bookshelf` is missing in your dependencies. Please run `npm install strapi-bookshelf`**
> WARN (6384 on Admin-ÏÊ): (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration

So, as suggested, i invoked the 'npm install strapi-bookshelf' command and been stucked with such output after  'strapi start':

> C:\Users\Admin\Documents\My Web Sites\boxing-therapy-backend\git\backend>strapi start
> WARN (9172 on Admin-ÏÊ): (hook:knex) wasn't loaded due to missing key `enabled` in the configuration
> WARN (9172 on Admin-ÏÊ): (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
> DEBUG (9172 on Admin-ÏÊ): Server wasn't able to start properly.
> ERROR (9172 on Admin-ÏÊ): Cannot read property 'knex' of undefined
>     TypeError: Cannot read property 'knex' of undefined
>     at Function.initialize (C:\Users\Admin\Documents\My Web Sites\boxing-therapy-backend\git\backend\node_modules\strapi-bookshelf\lib\ind
> ex.js:41:25)
>     at C:\Users\Admin\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:21:31
>     at Promise (C:\Users\Admin\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:103:37)
>     at new Promise (<anonymous>)
>     at Promise.all.Object.keys.map.hook (C:\Users\Admin\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:48:9)
>     at Array.map (<anonymous>)
>     at Strapi.module.exports (C:\Users\Admin\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:46:28)
>     at Strapi.load (C:\Users\Admin\AppData\Roaming\npm\node_modules\strapi\lib\Strapi.js:185:23)
>     at <anonymous>

Please help.

**Comment by ArkhipovK** [comment]
Ok. I got it. I installed 'npm install strapi-bookshelf', but the correct action was 'npm install strapi-bookshelf@alpha'. This solved the problem.
