### ISSUE TITLE
How to delete uploaded file through API

### ISSUE THREAD

**Issue by emptyopen** [strapi/strapi#4103]
**Describe the bug**
Tried a DELETE request on `{ipaddress}/uploads/{file_id}`, but get a 404 Not Found. I am able to download files, so I know the format should be good. 

**Expected behavior**
Successful deletion. 

**Screenshots**
N/A

**Code snippets**
```
async with aiohttp.ClientSession() as session:
            resp = await session.delete(url=f'{self.ip_address}/uploads/{_id}',
                                        headers={'Authorization': f'Bearer {self.jwt}'})
            resp.raise_for_status()
            return resp
```

**System**
- Node.js version: v10+
- NPM version:
- Strapi version: latest
- Database:
- Operating system:

**Additional context**

**Comment by lauriejim** [comment]
Hello @emptyopen !
It's because you are not using the right API route.
Here is the correct one to delete a file - check the [route code 📦](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/config/routes.json#L94)
It's `DELETE /files/:id`
But thank you for reporting this, I will update the documentation to make it more understandable.

**Comment by emptyopen** [comment]
I'm still getting a 404 not found with that path - I should be using the hash id, correct?

**Comment by lauriejim** [comment]
Sorry, I forget to precise, plugins routes are auto prefixed by the plugin name.
So in your request, you will have to use `/files/:id`
And you will have to use the entry ID.

**Comment by emptyopen** [comment]
To be clear, what is the expected full format? 

For example, if I can get a list of all files with (including auth header):
http://35.162.82.83:1337/upload/files?_limit=10&_sort=hash&_start=0

How should I be able to delete the file with id 353fc063d51f44e280aa4fb4f886bda1?

http://35.162.82.83:1337/upload/files/353fc063d51f44e280aa4fb4f886bda1  -> 500 internal error
http://35.162.82.83:1337/upload/files?353fc063d51f44e280aa4fb4f886bda1 . -> 404 not found

**Comment by lauriejim** [comment]
Okay, your 500 error. Do you have more information?
Here is the issue that is interesting.

**Comment by miguelangeltorresfp** [comment]
I confirm I'm having the same problem.
`http://localhost:1337/upload/search/32bf4dce0c36426b8a37291966817d87 => Found`

```
http://localhost:1337/upload/files/32bf4dce0c36426b8a37291966817d87
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```
And in the strapi console :

```
[2019-10-25T19:39:48.939Z] error CastError: Cast to ObjectId failed for value "32bf4dce0c36426b8a37291966817d87" at path "_id" for model "Upl
oadFile"
    at new CastError (...\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (...\node_modules\mongoose\lib\schema\objectid.js:246:11)
    at ObjectId.SchemaType.applySetters (...\node_modules\mongoose\lib\schematype.js:969:12)
    at ObjectId.SchemaType._castForQuery (...\node_modules\mongoose\lib\schematype.js:1383:15)
    at ObjectId.SchemaType.castForQuery (...\node_modules\mongoose\lib\schematype.js:1373:15)
    at ObjectId.SchemaType.castForQueryWrapper (...\node_modules\mongoose\lib\schematype.js:1352:15)
    at cast (...\node_modules\mongoose\lib\cast.js:307:32)
    at model.Query.Query.cast (...\node_modules\mongoose\lib\query.js:4644:12)
    at model.Query.Query._castConditions (...\node_modules\mongoose\lib\query.js:1842:10)
    at model.Query.<anonymous> (...\node_modules\mongoose\lib\query.js:2097:8)
    at model.Query._wrappedThunk [as _findOne] (...\node_modules\mongoose\lib\helpers\query\wrapThunk.js
:16:8)
    at ...\node_modules\kareem\index.js:278:20
    at _next (...\node_modules\kareem\index.js:102:16)
    at process.nextTick (...\node_modules\kareem\index.js:507:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[2019-10-25T19:39:48.944Z] debug GET /upload/files/32bf4dce0c36426b8a37291966817d87 (113 ms) 500
```

**Comment by kamyh** [comment]
why is that issue closed ?

**Comment by yestellar** [comment]
Give access in "Roles and permissions" to destroy uploads, then you can delete file by /upload/files/:id

**Comment by Mustafa-Zahedi** [comment]
> Hello @emptyopen ! It's because you are not using the right API route. Here is the correct one to delete a file - check the [route code 📦](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/config/routes.json#L94) It's `DELETE /api/upload/files/:id` But thank you for reporting this, I will update the documentation to make it more understandable.
