### ISSUE TITLE
TypeError: Cannot read property 'globalId' of undefined

### ISSUE THREAD

**Issue by fcpauldiaz** [strapi/strapi#4140]
**Describe the bug**

TypeError: Cannot read property 'globalId' of undefined

**Steps to reproduce the behavior**

0. Create new strapi project
1. create new model `strapi generate:model instructions title:string body:string`
2. Go to Admin UI and create new Content Type with a Relationship to the Model created
3. Save Changes
4. Can't no longer start server

**Expected behavior**

To be able to create new Content Type with a field as a Relationship.

**Code snippets**
```
TypeError: Cannot read property 'globalId' of undefined
    at buildRelation (/Users/fcpauldiaz/Documents/node/uni-app-api/node_modules/strapi-hook-mongoose/lib/mount-models.js:513:31)
    at relationalAttributes.forEach.name (/Users/fcpauldiaz/Documents/node/uni-app-api/node_modules/strapi-hook-mongoose/lib/mount-models.js:74:7)
    at Array.forEach (<anonymous>)
    at Object.keys.map.model (/Users/fcpauldiaz/Documents/node/uni-app-api/node_modules/strapi-hook-mongoose/lib/mount-models.js:73:26)
    at Array.map (<anonymous>)
    at module.exports (/Users/fcpauldiaz/Documents/node/uni-app-api/node_modules/strapi-hook-mongoose/lib/mount-models.js:14:23)
    at mountApis (/Users/fcpauldiaz/Documents/node/uni-app-api/node_modules/strapi-hook-mongoose/lib/index.js:162:12)
    at Object.keys.filter.map (/Users/fcpauldiaz/Documents/node/uni-app-api/node_modules/strapi-hook-mongoose/lib/index.js:130:11)
```

**System**
- Node.js version: Node 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.6
- Database: Mongo
- Operating system: Mac Os.

**Comment by samohovets** [comment]
Same, trying to upload the file with correct `field`, `refId`, `ref`, `files` fields in FormData.

**Comment by jsonpj3wt** [comment]
This happens in Upload as well.  Was not a problem until beta@16 (used same code as before with setting refId and ref).

**Comment by jsonpj3wt** [comment]
Apparently, what we found is that ref is now case sensitive for Upload.

**Comment by lauriejim** [comment]
Hello @fcpauldiaz !
What is the relation type you created?
