### ISSUE TITLE
Bootstrap function in plugin "users-permissions" failed

### ISSUE THREAD

**Issue by merijnponzo** [strapi/strapi#4178]
Hello,

When I upgraded from 3.0.0-beta.13 to beta.16.7 I got errors when I try to reconnect my database - on a clean installation, after strapi develop. So it won't boot

```
error Bootstrap function in plugin "users-permissions" failed
error error: duplicate key value violates unique constraint "users-permissions_permission_pkey"
```
and 
```
Bootstrap function in plugin "content-manager" failed
duplicate key value violates unique constraint "core_store_pkey"
```

1. create strapi-app my-project
2. make sure a new strapi app install is working
3. copy your api, config and extensions folder to your new install
(make sure to install any extra plugins like strapi-graphql)
(make sure this app is a few versions behind, and already has content, edited permissions etc)
4. strapi develop 

My strapi application is a bit behind, but I would expect that the latest version would work with my database from 3.0.0-beta.13

NodeJs v12.11.1
NPM 6.11.3
Strapi beta.16.7
Database:Postgres
Operating system:Mac

Another upgrade method I tried is simply replace 3.0.0-beta.13 to 3.0.0-beta.16.7 in my package.json, remove my package-lock and node_modules and npm install. But this gave me the same error

**Comment by lauriejim** [comment]
Hello! Did you follow this migration guide?
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html

**Comment by merijnponzo** [comment]
Hello Laurie, thank you for your reply..
Is it possible to go from 13 to 16.7, or should I go from 13 to 16 first?

And should I rename all texts to richtexts?
I don't think this is the problem..


```
ponzo:puppyplaza_postdev_beta16.7 mac$ 
ponzo:puppyplaza_postdev_beta16.7 mac$ strapi develop
[2019-10-07T18:20:21.080Z] error Bootstrap function in plugin "users-permissions" failed
[2019-10-07T18:20:21.081Z] error error: duplicate key value violates unique constraint "users-permissions_permission_pkey"
    at Connection.parseE (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta16.7/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta16.7/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta16.7/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
ponzo:puppyplaza_postdev_beta16.7 mac$ 
```

**Comment by merijnponzo** [comment]
I updated from 13 to 15 first, then my app still works. Then I update from 15 to 16 and the error above occurs.

- I did a rebuild, first. I dont use custom bootstraps or hooks. 
- I dont return toJSON() directly in my custom controller

I don't think the WYSIWYG is causing this problem.


```
error Bootstrap function in plugin "users-permissions" failed
[2019-10-08T06:33:28.031Z] error error: duplicate key value violates unique constraint "users-permissions_permission_pkey"
    at Connection.parseE (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta5.0/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta5.0/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta5.0/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by derrickmehaffy** [comment]
@merijnponzo can you confirm that you also don't have any carrots in your strapi package version `^` or `~`

Based on the error something is going on with permissions trying to set a duplicate key. You may want to try backing up then purging that table in the database.

**Comment by merijnponzo** [comment]
Hi derrick, Only lodash and typy
```
 "dependencies": {
    "knex": "latest",
    "lodash": "^4.17.5",
    "pg": "latest",
    "strapi": "3.0.0-beta.16",
    "strapi-admin": "3.0.0-beta.16",
    "strapi-hook-bookshelf": "3.0.0-beta.16",
    "strapi-hook-knex": "3.0.0-beta.16",
    "strapi-plugin-content-manager": "3.0.0-beta.16",
    "strapi-plugin-content-type-builder": "3.0.0-beta.16",
    "strapi-plugin-email": "3.0.0-beta.16",
    "strapi-plugin-graphql": "3.0.0-beta.16",
    "strapi-plugin-settings-manager": "3.0.0-beta.16",
    "strapi-plugin-upload": "3.0.0-beta.16",
    "strapi-plugin-users-permissions": "3.0.0-beta.16",
    "strapi-utils": "3.0.0-beta.16",
    "typy": "^3.1.0"
  },
```

**Comment by derrickmehaffy** [comment]
@merijnponzo I would suggest you skip beta.16 directly and go straight to beta.16.8

The subversion number in this case are hotfixes for beta.16.

**Comment by merijnponzo** [comment]
I guess when building it's trying to create new keys like 'users-permissions_permission_pkey' to my permissions table. 

So I updated to 16.8, but still:

```
[2019-10-08T06:55:59.777Z] error Bootstrap function in plugin "users-permissions" failed
[2019-10-08T06:55:59.778Z] error error: duplicate key value violates unique constraint "users-permissions_permission_pkey"
    at Connection.parseE (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta5.0/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta5.0/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta5.0/node_modules/pg/lib/connection.js:121:22)
```

**Comment by derrickmehaffy** [comment]
@mtringuyen yeah like I said there must be something that got messed up during the upgrade. Do a backup of the table (or your entire DB) purge that permissions table and restart.

**Comment by merijnponzo** [comment]
Okey remobed my user-permissions_permission table
changed cb() in bootstrap to

````
module.exports = {
  defaults: {},
  async initialize(cb) {
    await cb();
  }
};
```
Now I got
```
 TypeError: fn is not a function
    at execBootstrap (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta16.8/node_modules/strapi/lib/Strapi.js:381:15)
    at Strapi.runBootstrapFunctions (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta16.8/node_modules/strapi/lib/Strapi.js:399:12)

```

**Comment by merijnponzo** [comment]
I changed the cb() to 
module.exports = () => {};

Now it works again - 

I will add my permissions manually just like the good old strapi-alpha times ;-)

This is a bug right? Not a 'help wanted'

Thanks!

**Comment by derrickmehaffy** [comment]
@merijnponzo I believe the migration guide states that all the cb() need to be removed but there was some issues with permissions that likely your jump to beta.16 directly caused

I believe that if you jumped from beta.x to beta.16.8 this issue wouldn't have happened directly. Either way glad you solved it, going to mark this is as closed unless someone else has the same problem.

**Comment by merijnponzo** [comment]
Hello,
I'm using 3.0.0-beta.17.4 for a while

NodeJs v12.11.1
NPM 6.11.3
Strapi beta.16.7
Database:Postgres
Operating system:Mac


If I import a copy of my production database to my local, strapi develop boots okay
But when I create a new content-type, the error is back

```
[2019-12-05T07:44:59.909Z] error Bootstrap function in plugin "users-permissions" failed
[2019-12-05T07:44:59.910Z] error error: duplicate key value violates unique constraint "users-permissions_permission_pkey"
    at Connection.parseE (/Applications/www/puppyplaza/puppyplaza_backend/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Applications/www/puppyplaza/puppyplaza_backend/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Applications/www/puppyplaza/puppyplaza_backend/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)

```
my bootstrap.js is still
```
module.exports = () => {};
```

I also already tried it with clearing my core_store. But this doesnt help

**Comment by lauriejim** [comment]
Make sure you well update your `sequence` values.
Because when you import data, you have to set all your tables' sequences to the last ID value of the table.

**Comment by merijnponzo** [comment]
Thanks laurie,
Is this postgres specific? 
```
ALTER SEQUENCE users-permissions_permission RESTART WITH last_id_of_table;
```

**Comment by lauriejim** [comment]
Yap! Many issues exist on StackOverflow.
Related to PG.

**Comment by shamseerahammedm** [comment]
Fresh install of strapi with mysql ( not quickstart ) gives the same error 
`error Bootstrap function in plugin "users-permissions" failed`
`error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

**Comment by guhandelta** [comment]
I face the same issue, on fresh create-strapi-app, Can anyone say, where can I find the config/ and resolve this issue?

**Comment by christopher4lis** [comment]
I fixed this ish—run:

`ALTER SEQUENCE "users-permissions_permission_id_seq" RESTART WITH 217;`

where `217` is _what would be_ the very next id in your `users-permissions_permission` table.

Same fix mentioned by @merijnponzo, but referencing the table's sequence which is required to prevent any duplicate primary keys.

**Comment by idesignzone** [comment]
In my case adding 
` options: {
        "pool":{
          "min":0,
           "max":15,
            "idleTimeoutMillis":30000,
            "createTimeoutMillis":30000,
           "acquireTimeoutMillis":30000
     }`
created a new error "error Error: SQLITE_BUSY: database is locked"
so I removed the min and max values like 
`"pool":{
            "idleTimeoutMillis":30000,
            "createTimeoutMillis":30000,
           "acquireTimeoutMillis":30000
     }`
and it worked.

**Comment by merijnponzo** [comment]
```
[2020-11-01T12:55:10.258Z] error Bootstrap function in admin failed
[2020-11-01T12:55:10.258Z] error error: duplicate key value violates unique constraint "strapi_permission_pkey"

```
Occured after adding new fields to a migrated postgres database

You can check the postgres sequences with
```
SELECT * FROM information_schema.sequences;
```
I checked the strapi_permission with
```
SELECT nextval('strapi_permission_id_seq');
```
Updated the sequence to a higher key with 
```
SELECT setval('strapi_permission_id_seq', (SELECT MAX(id) FROM strapi_permission));
```

from
https://medium.com/the-journey-learning-to-code-one-day-at-a-time/postgresql-duplicate-key-violates-unique-constraint-5d6eb3b61f7b

**Comment by kaka-ruto** [comment]
@merijnponzo that solved for me too! Thanks.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/app-on-heroku-crashed-after-update-from-v-3-3-4-to-v-3-4-0/1718/4

**Comment by ishan123456789** [comment]
I was getting the error above after I created a new role and deleted it manually from DB JFYI.
