### ISSUE TITLE
MongoError: server instance pool was destroyed

### ISSUE THREAD

**Issue by leonardyhuang** [strapi/strapi#4188]
**Describe the bug**
Suddenly the app stopped working with error `MongoError: server instance pool was destroyed`.
After restart, it works back to normal.

**Steps to reproduce the behavior**
Not really sure how to reproduce this issue.

**Expected behavior**
No such error.

**Code snippets**
```
2019-10-04T13:04:11.698357158Z app[web.1]: [2019-10-04T13:04:11.698Z] error MongoError: server instance pool was destroyed
2019-10-04T13:04:11.698389594Z app[web.1]:     at basicWriteValidations (/app/node_modules/mongodb/lib/core/sdam/server.js:388:12)
2019-10-04T13:04:11.698394696Z app[web.1]:     at basicReadValidations (/app/node_modules/mongodb/lib/core/sdam/server.js:395:17)
2019-10-04T13:04:11.698398885Z app[web.1]:     at Server.command (/app/node_modules/mongodb/lib/core/sdam/server.js:217:19)
2019-10-04T13:04:11.698402917Z app[web.1]:     at checkServer (/app/node_modules/mongodb/lib/core/sdam/monitoring.js:144:12)
2019-10-04T13:04:11.698406994Z app[web.1]:     at /app/node_modules/mongodb/lib/core/sdam/monitoring.js:197:7
2019-10-04T13:04:11.698410976Z app[web.1]:     at /app/node_modules/mongodb/lib/core/connection/pool.js:788:9
2019-10-04T13:04:11.698414699Z app[web.1]:     at eachAsync (/app/node_modules/mongodb/lib/core/utils.js:135:5)
2019-10-04T13:04:11.698418469Z app[web.1]:     at Pool.reset (/app/node_modules/mongodb/lib/core/connection/pool.js:765:3)
2019-10-04T13:04:11.698422311Z app[web.1]:     at /app/node_modules/mongodb/lib/core/sdam/monitoring.js:195:19
2019-10-04T13:04:11.698442763Z app[web.1]:     at /app/node_modules/mongodb/lib/core/sdam/monitoring.js:160:18
2019-10-04T13:04:11.698447923Z app[web.1]:     at Server.command (/app/node_modules/mongodb/lib/core/sdam/server.js:219:14)
2019-10-04T13:04:11.698451715Z app[web.1]:     at checkServer (/app/node_modules/mongodb/lib/core/sdam/monitoring.js:144:12)
2019-10-04T13:04:11.698456682Z app[web.1]:     at Object.monitorServer [as monitorFunction] (/app/node_modules/mongodb/lib/core/sdam/monitoring.js:186:3)
2019-10-04T13:04:11.698460552Z app[web.1]:     at Server.monitor (/app/node_modules/mongodb/lib/core/sdam/server.js:196:12)
2019-10-04T13:04:11.698464332Z app[web.1]:     at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:827:22)
2019-10-04T13:04:11.698468144Z app[web.1]:     at listOnTimeout (internal/timers.js:531:17)
2019-10-04T13:04:11.698471941Z app[web.1]:     at processTimers (internal/timers.js:475:7)
```

**System**
- Node.js version: 12.10.0
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.16.5
- Database: MongoDB 3.6.4
- Operating system: Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 (deployed via dokku version 0.18.3)

Kindly advise, apppreciate the help.

**Comment by lauriejim** [comment]
Hello! Without any other information, we can do nothing for you :/
It can come from your MongoDB database. Where is hosted your database?

**Comment by derrickmehaffy** [comment]
Marking as closed for now, @leonardyhuang if you have further information please do add it and this can be reopened. Thanks!

**Comment by leonardyhuang** [comment]
Sorry for the late reply, it is hosted on https://www.cloudclusters.io/. Probably there was an upgrade at that time.

Just thinking if it is possible for Strapi to auto-restart when this happens?
