### ISSUE TITLE
Get relation in a group fail with GraphQL

### ISSUE THREAD

**Issue by vHades0199** [strapi/strapi#4199]
I have a content-type **Order** with field **Items** is a group **OrderItem**.
In **OrderItem** have a relation to content-type **Product**.
In swagger it run normal, but in graphql when query product it fail.

Result swagger:
```json
{
    "total": 14600689,
    "discount": 12312312,
    "_id": "5d99dee073d6cb1d883fac41",
    "deliveryDate": "2019-10-01T17:00:00.000Z",
    "subtotal": 14600689,
    "description": "qwewqeq",
    "items": [
      {
        "discount": 0,
        "_id": "5d99dee073d6cb1d883fac43",
        "quantity": 12,
        "amount": 1477476,
        "createdAt": "2019-10-06T12:32:32.833Z",
        "updatedAt": "2019-10-06T12:32:32.952Z",
        "__v": 0,
        "product": {
          "isActive": true,
          "_id": "5d99de5773d6cb1d883fac37",
          "name": "test",
          "slug": "/test",
          "price": {
            "amount": 123123,
            "currency": "VND",
            "id": "5d99dea573d6cb1d883fac3f"
          },
          "createdAt": "2019-10-06T12:30:15.129Z",
          "updatedAt": "2019-10-06T13:19:45.736Z",
          "__v": 2,
          "image": "/uploads/769903a4058a48618779cd50674e0a2b.png",
          "id": "5d99de5773d6cb1d883fac37"
        },
        "id": "5d99dee073d6cb1d883fac43"
      }
    ],
    "__v": 1,
    "id": "5d99dee073d6cb1d883fac41"
  }
```

In graphql
```graphql
{
  order(id: "5d99e03073d6cb1d883fac46") {
    total
    items {
      quantity
      product{
        name
      }
    }
  }
}
```
```json
  {"errors": [
    {
      "message": "Cannot read property 'load' of undefined",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "order",
        "items",
        0,
        "product"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'load' of undefined",
            "    at resolver.(anonymous function) (\\node_modules\\strapi-plugin-graphql\\services\\Resolvers.js:190:75)",
            "    at field.resolve (\\node_modules\\graphql-extensions\\src\\index.ts:274:18)",
            "    at resolveFieldValueOrError (\\node_modules\\graphql\\execution\\execute.js:503:18)",
            "    at resolveField (\\node_modules\\graphql\\execution\\execute.js:470:16)",
            "    at executeFields (\\node_modules\\graphql\\execution\\execute.js:311:18)",
            "    at collectAndExecuteSubfields (\\node_modules\\graphql\\execution\\execute.js:747:10)",
            "    at completeObjectValue (\\node_modules\\graphql\\execution\\execute.js:737:10)",
            "    at completeValue (\\node_modules\\graphql\\execution\\execute.js:626:12)",
            "    at completeValueCatchingError (\\node_modules\\graphql\\execution\\execute.js:531:19)",
            "    at \\node_modules\\graphql\\execution\\execute.js:651:25",
            "    at Array.forEach (<anonymous>)",
            "    at forEach (\\node_modules\\iterall\\index.js:83:25)",
            "    at completeListValue (\\node_modules\\graphql\\execution\\execute.js:647:24)",
            "    at completeValue (\\node_modules\\graphql\\execution\\execute.js:609:12)",
            "    at completeValueCatchingError (\\node_modules\\graphql\\execution\\execute.js:531:19)",
            "    at resolveField (\\node_modules\\graphql\\execution\\execute.js:471:10)",
            "    at executeFields (\\node_modules\\graphql\\execution\\execute.js:311:18)",
            "    at collectAndExecuteSubfields (\\node_modules\\graphql\\execution\\execute.js:747:10)",
            "    at completeObjectValue (\\node_modules\\graphql\\execution\\execute.js:737:10)",
            "    at completeValue (\\node_modules\\graphql\\execution\\execute.js:626:12)",
            "    at \\node_modules\\graphql\\execution\\execute.js:528:16",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ]}
 
```

**System**
- Node.js version: v10.16.3
- Yarn version: v1.19.0
- Strapi version: 3.0.0-beta.16.8
- Database: MongoDB
- Operating system: Windows

**Comment by lauriejim** [comment]
Hello @vHades0199 !
Thank you for reporting this issue.
I ping @alexandrebodin about it.

**Comment by alexandrebodin** [comment]
@vHades0199 Can you share your model json files plz ?

**Comment by derrickmehaffy** [comment]
@alexandrebodin is this only reproducible with the groups feature?
