### ISSUE TITLE
Cannot install quickstart beta

### ISSUE THREAD

**Issue by rcollette** [strapi/strapi#4251]
**Describe the bug**
Error during quickstart installation 

```
- Installing dependencies:
Error while installing dependencies:
warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi-admin > buffetjs@1.0.6: Buffet.js is deprecated please use @buffetjs/core instead
warning strapi-admin > postcss-smart-import@0.7.6: This project is not maintained anymore. Please use postcss-import instead.
warning strapi-admin > react-intl > intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
warning strapi-admin > react-datetime > create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning strapi-admin > precss > postcss-preset-env > postcss-color-functional-notation > postcss-values-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning strapi-plugin-users-permissions > purest > request > node-uuid@1.4.8: Use uuid module instead
warning strapi-plugin-users-permissions > purest > request > hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning strapi-plugin-users-permissions > purest > request > hawk > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi-plugin-users-permissions > purest > request > hawk > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi-plugin-users-permissions > purest > request > hawk > boom > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi-plugin-users-permissions > purest > request > hawk > sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning strapi-plugin-users-permissions > purest > request > hawk > sntp > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi-plugin-users-permissions > purest > request > hawk > cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi-plugin-users-permissions > purest > request > hawk > cryptiles > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning "strapi-admin > buffetjs > react-dates@20.3.0" has unmet peer dependency "react-with-direction@^1.3.0".
warning "strapi-admin > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > strapi-helper-plugin > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "strapi-plugin-users-permissions > grant-koa@4.6.3" has unmet peer dependency "koa@>=0.x.x".
warning "strapi-hook-bookshelf > bookshelf@0.15.1" has incorrect peer dependency "knex@>=0.13.0 <0.18.0".
warning " > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.2.3".
warning " > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react-hooks@^1.7.0".
error /strapi-app/my-app/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /strapi-app/my-app/node_modules/gifsicle
Output:
⚠ spawn /strapi-app/my-app/node_modules/gifsicle/vendor/gifsicle ENOENT
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: not found


    at Promise.all.then.arr (/strapi-app/my-app/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Steps to reproduce the behavior**
Create the Dockerfile

```Dockerfile
FROM node:10-alpine
WORKDIR /strapi-app
ARG appName=my-app
RUN npm install -g create-strapi-app@3.0.0-beta.16.8
RUN create-strapi-app $appName --quickstart
```
Build the Dockerfile with `docker build -t strapi .`

**Expected behavior**
Should be created without error.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by rcollette** [comment]
And with that... Strapi is off the consideration list for my company.   This is what we call, trying to keep the issue list deceptively low.  You can't get much more specific than a Dockerfile to reproduce the issue.

**Comment by derrickmehaffy** [comment]
Sorry to hear that but the issue template is to make it easier to read and follow.

In your case you are missing a module `autoreconf` likely due to the alpline image base.

If you wanted to update the issue with the template it can be reopened, but a wall of text of an error message doesn't assist us in debugging the issue.
