### ISSUE TITLE
GroupBy connection values not works on GraphQL

### ISSUE THREAD

**Issue by vHades0199** [strapi/strapi#4297]
### query:
```graphql
{
 usersConnection {
    groupBy {
      createdUser {
        key
        connection {
          values {
            username
          }
        }
      }
    }
  }
}
```
### result:
```json
{
  "errors": [
    {
      "message": "Cast to ObjectId failed for value \"{ _bsontype: 'ObjectID', id: ']�ʒ�sX���$�' }\" at path \"createdUser\" for model \"UsersPermissionsUser\"",
      "locations": [
        {
          "line": 7,
          "column": 11
        }
      ],
      "path": [
        "usersConnection",
        "groupBy",
        "createdUser",
        0,
        "connection",
        "values"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Cast to ObjectId failed for value \"{ _bsontype: 'ObjectID', id: ']�ʒ�sX���$�' }\" at path \"createdUser\" for model \"UsersPermissionsUser\"",
          "name": "CastError",
          "stringValue": "\"{ _bsontype: 'ObjectID', id: ']�ʒ�sX���$�' }\"",
          "kind": "ObjectId",
          "value": {
            "_bsontype": "ObjectID",
            "id": "]�ʒ�sX���$�"
          },
          "path": "createdUser",
          "stacktrace": [
            "CastError: Cast to ObjectId failed for value \"{ _bsontype: 'ObjectID', id: ']�ʒ�sX���$�' }\" at path \"createdUser\" for model \"UsersPermissionsUser\"",
            "    at new CastError (.\\node_modules\\mongoose\\lib\\error\\cast.js:29:11)",
            "    at ObjectId.cast (.\\node_modules\\mongoose\\lib\\schema\\objectid.js:244:11)",
            "    at ObjectId.SchemaType.applySetters (.\\node_modules\\mongoose\\lib\\schematype.js:948:12)",
            "    at ObjectId.SchemaType._castForQuery (.\\node_modules\\mongoose\\lib\\schematype.js:1362:15)",
            "    at ObjectId.SchemaType.castForQuery (.\\node_modules\\mongoose\\lib\\schematype.js:1352:15)",
            "    at ObjectId.SchemaType.castForQueryWrapper (.\\node_modules\\mongoose\\lib\\schematype.js:1331:15)",
            "    at cast (.\\node_modules\\mongoose\\lib\\cast.js:252:34)",
            "    at cast (.\\node_modules\\mongoose\\lib\\cast.js:50:18)",
            "    at model.Query.Query.cast (.\\node_modules\\mongoose\\lib\\query.js:4608:12)",
            "    at model.Query.Query._castConditions (.\\node_modules\\mongoose\\lib\\query.js:1790:10)",
            "    at model.Query.<anonymous> (.\\node_modules\\mongoose\\lib\\query.js:1817:8)",
            "    at model.Query._wrappedThunk [as _find] (.\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:16:8)",
            "    at .\\node_modules\\kareem\\index.js:278:20",
            "    at _next (.\\node_modules\\kareem\\index.js:102:16)",
            "    at process.nextTick (.\\node_modules\\kareem\\index.js:499:38)",
            "    at process._tickCallback (internal/process/next_tick.js:61:11)"
          ]
        }
      }
    }
  ]
}
```
### model:
```json
{
  "connection": "default",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": "Manage users and permissions."
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "isActive": {
      "required": true,
      "default": true,
      "type": "boolean"
    },
    "createdUser": {
      "model": "user",
      "plugin": "users-permissions"
    },
    "updatedUser": {
      "model": "user",
      "plugin": "users-permissions"
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions"
    },
    "shouldChangePassword": {
      "type": "boolean"
    },
    "isLockout": {
      "type": "boolean"
    }
  }
}
```

**System**
- Node.js version: v10.16.3
- NPM version: 1.19.0
- Strapi version: 3.0.0-beta.17.1
- Database: MongoDB
- Operating system:

**Comment by lauriejim** [comment]
Hello! Your `createdUser` relation looks strange.
What is the relation type you created?

**Comment by vHades0199** [comment]
![Capture](https://user-images.githubusercontent.com/10781752/67304747-8292e600-f51e-11e9-92a6-a977ae25d0f5.PNG)

**Comment by vHades0199** [comment]
not only createdUser, all group by a ref content type is same error

**Comment by lauriejim** [comment]
Thank you for this report @vHades0199 !

**Comment by lauriejim** [comment]
Tested it with beta.17.8 and this issue no longer exit.
