### ISSUE TITLE
Heroku Application Error

### ISSUE THREAD

**Issue by hasankhalid** [strapi/strapi#4336]
I am trying to setup a Strapi application using MongoDB and PostGres SQL. I have created a local strapi project using MongoDB and it works fine but when i follow the deployment instructions the application fails. Here's the heroku log.

`2019-10-23T09:19:15.852272+00:00 app[web.1]: at Object.get (/app/node_modules/strapi/lib/core/store.js:55:47)
2019-10-23T09:19:15.852275+00:00 app[web.1]: at module.exports (/app/plugins/content-manager/config/functions/bootstrap.js:312:42)
2019-10-23T09:19:15.852277+00:00 app[web.1]: at /app/node_modules/strapi/lib/Strapi.js:299:13
2019-10-23T09:19:15.85228+00:00 app[web.1]: at new Promise (<anonymous>)
2019-10-23T09:19:15.852282+00:00 app[web.1]: at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:287:11)
2019-10-23T09:19:15.852284+00:00 app[web.1]: at /app/node_modules/strapi/lib/Strapi.js:326:44
2019-10-23T09:19:15.852286+00:00 app[web.1]: at Array.map (<anonymous>)
2019-10-23T09:19:15.852288+00:00 app[web.1]: at Strapi.bootstrap (/app/node_modules/strapi/lib/Strapi.js:326:35)
2019-10-23T09:19:15.85229+00:00 app[web.1]: at Strapi.start (/app/node_modules/strapi/lib/Strapi.js:109:18)
2019-10-23T09:19:15.853628+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
2019-10-23T09:19:15.853632+00:00 app[web.1]: at Object.get (/app/node_modules/strapi/lib/core/store.js:55:47)
2019-10-23T09:19:15.853634+00:00 app[web.1]: at module.exports (/app/plugins/settings-manager/config/functions/bootstrap.js:17:26)
2019-10-23T09:19:15.853636+00:00 app[web.1]: at /app/node_modules/strapi/lib/Strapi.js:299:13
2019-10-23T09:19:15.853638+00:00 app[web.1]: at new Promise (<anonymous>)
2019-10-23T09:19:15.85364+00:00 app[web.1]: at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:287:11)
2019-10-23T09:19:15.853642+00:00 app[web.1]: at /app/node_modules/strapi/lib/Strapi.js:326:44
2019-10-23T09:19:15.853644+00:00 app[web.1]: at Array.map (<anonymous>)
2019-10-23T09:19:15.853646+00:00 app[web.1]: at Strapi.bootstrap (/app/node_modules/strapi/lib/Strapi.js:326:35)
2019-10-23T09:19:15.853648+00:00 app[web.1]: at Strapi.start (/app/node_modules/strapi/lib/Strapi.js:109:18)
2019-10-23T09:19:15.853705+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
2019-10-23T09:19:15.853792+00:00 app[web.1]: (node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-10-23T09:19:15.853847+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
2019-10-23T09:19:15.853851+00:00 app[web.1]: at Object.get (/app/node_modules/strapi/lib/core/store.js:55:47)
2019-10-23T09:19:15.853853+00:00 app[web.1]: at module.exports (/app/plugins/users-permissions/config/functions/bootstrap.js:96:45)
2019-10-23T09:19:15.853856+00:00 app[web.1]: at /app/node_modules/strapi/lib/Strapi.js:299:13
2019-10-23T09:19:15.853858+00:00 app[web.1]: at new Promise (<anonymous>)
2019-10-23T09:19:15.85386+00:00 app[web.1]: at execBootstrap (/app/node_modules/strapi/lib/Strapi.js:287:11)
2019-10-23T09:19:15.853862+00:00 app[web.1]: at /app/node_modules/strapi/lib/Strapi.js:326:44
2019-10-23T09:19:15.853865+00:00 app[web.1]: at Array.map (<anonymous>)
2019-10-23T09:19:15.853867+00:00 app[web.1]: at Strapi.bootstrap (/app/node_modules/strapi/lib/Strapi.js:326:35)
2019-10-23T09:19:15.853869+00:00 app[web.1]: at Strapi.start (/app/node_modules/strapi/lib/Strapi.js:109:18)
2019-10-23T09:19:15.853918+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
2019-10-23T09:19:15.87059+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
2019-10-23T09:19:15.870594+00:00 app[web.1]: at /app/plugins/email/config/functions/bootstrap.js:68:40
2019-10-23T09:19:15.870672+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
2019-10-23T09:19:15.872961+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
2019-10-23T09:19:15.872974+00:00 app[web.1]: at /app/plugins/upload/config/functions/bootstrap.js:70:40
2019-10-23T09:19:15.873032+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
2019-10-23T09:19:19.34799+00:00 app[web.1]: [2019-10-23T09:19:19.347Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
2019-10-23T09:19:19.348211+00:00 app[web.1]: [2019-10-23T09:19:19.348Z] warn Perhaps you forgot to call it?
2019-10-23T09:19:19.348498+00:00 app[web.1]: [2019-10-23T09:19:19.348Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
2019-10-23T09:19:19.348768+00:00 app[web.1]: [2019-10-23T09:19:19.348Z] warn Perhaps you forgot to call it?
2019-10-23T09:19:19.349076+00:00 app[web.1]: [2019-10-23T09:19:19.349Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
2019-10-23T09:19:19.349318+00:00 app[web.1]: [2019-10-23T09:19:19.349Z] warn Perhaps you forgot to call it?
2019-10-23T09:19:19.349573+00:00 app[web.1]: [2019-10-23T09:19:19.349Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
2019-10-23T09:19:19.349869+00:00 app[web.1]: [2019-10-23T09:19:19.349Z] warn Perhaps you forgot to call it?
2019-10-23T09:19:27.92488+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=axiscms.herokuapp.com request_id=ef45bea5-74a1-47da-8865-a23405f6b723 fwd="43.245.11.122" dyno= connect= service= status=503 bytes= protocol=https
2019-10-23T09:20:11.03839+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-10-23T09:20:11.062476+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-10-23T09:20:11.157633+00:00 heroku[web.1]: Process exited with status 137
2019-10-23T09:20:11.206006+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-23T09:20:14.378667+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=axiscms.herokuapp.com request_id=4e7f4266-f110-4dc2-8845-bdf1809401e8 fwd="43.245.11.122" dyno= connect= service= status=503 bytes= protocol=https
2019-10-23T09:20:19.845791+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=axiscms.herokuapp.com request_id=8be3cc76-f7c9-44d6-8c38-968b9d16c8f0 fwd="43.245.11.122" dyno= connect= service= status=503 bytes= protocol=https
2019-10-23T09:20:21.444922+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=axiscms.herokuapp.com request_id=f4745e6d-7fce-4f95-a144-c63ec099edff fwd="43.245.11.122" dyno= connect= service= status=503 bytes= protocol=https
2019-10-23T09:30:42.415021+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=axiscms.herokuapp.com request_id=4a7f8593-40f7-4804-8382-dc867bd70253 fwd="43.245.11.122" dyno= connect= service= status=503 bytes= protocol=https
2019-10-23T09:30:44.36151+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=axiscms.herokuapp.com request_id=dd01f943-b8a4-45cd-867e-3ec97c01f73b fwd="43.245.11.122" dyno= connect= service= status=503 bytes= protocol=https
`

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by hasankhalid** [comment]
**Description of the issue**
I am trying to setup a strapi application and deploy it on Heroku. My application runs fine locally but when i use the deployment instructions in the documentation, it does not open on Heroku and gives an Application Error. A look at the Heroku logs shows H10 errors and an R10 error which says that Heroku could not connect to the specified port. There is also a warning that Bootstrap is taking too long to respond. I followed the steps to setup MongoDB and am trying to setup Heroku using Postgres

**Expected behavior**
Just want to setup Strapi on Heroku so that i can maintain content at an online link.

**Screenshots**
<img width="1429" alt="Screenshot 2019-10-23 at 4 40 45 PM" src="https://user-images.githubusercontent.com/20278920/67389488-24184700-f5b4-11e9-8971-c656101a835a.png">
<img width="1440" alt="Screenshot 2019-10-23 at 4 41 29 PM" src="https://user-images.githubusercontent.com/20278920/67389493-25e20a80-f5b4-11e9-8820-4c27de8bb3ad.png">
<img width="1440" alt="Screenshot 2019-10-23 at 4 41 38 PM" src="https://user-images.githubusercontent.com/20278920/67389494-27abce00-f5b4-11e9-85f4-d49256913368.png">

**System**
- Node.js version: 10.15.3
- NPM version: 6.11.3
- Strapi version: 3.0.0-alpha.26.2
- Database: mongodb set up locally, configured postgres on Heroku
- Operating system: MacOS Catalina 10.15

**Additional context**
Add any other context about the problem here.

**Comment by MayoudP** [comment]
Any update on this ?

**Comment by Seba-Monsalve** [comment]
same error here

**Comment by MayoudP** [comment]
@Seba-Monsalve On my side, I just created a new project with the very last versions and it fixed my pb
