### ISSUE TITLE
(hook:knex) wasn't loaded due to missing key `enabled` in the configuration

### ISSUE THREAD

**Issue by andyjessop** [strapi/strapi#436]
**Node.js version**: 8.6.0
**npm version**: 5.3.0
**Strapi version**: 3.0.0-alpha.7.3
**Operating system**: Mac Yosemite

I changed the database configuration to:
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "localhost",
        "port": 5432,
        "username": "me",
        "password": "",
        "database": "torch"
      },
      "options": {}
    }
  }
}
```
And created the database and installed `strapi-bookshelf`. When starting the app, I get the following error:

```
$ strapi start
WARN (26367 on laptop.home): (hook:knex) wasn't loaded due to missing key `enabled` in the configuration
WARN (26367 on laptop.home): (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
DEBUG (26367 on laptop.home): Server wasn't able to start properly.
ERROR (26367 on laptop.home): Cannot read property 'knex' of undefined
    TypeError: Cannot read property 'knex' of undefined
        at Function.initialize (/Users/me/strapi/server/node_modules/strapi-bookshelf/lib/index.js:41:24)
        at /usr/local/lib/node_modules/strapi/lib/hooks/index.js:21:31
        at Promise (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:103:37)
        at Promise (<anonymous>)
        at Promise.all.Object.keys.map.hook (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:48:9)
        at Array.map (<anonymous>)
        at Strapi.module.exports (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:46:28)
        at Strapi.load (/usr/local/lib/node_modules/strapi/lib/Strapi.js:185:23)
        at <anonymous>
```

**Comment by lauriejim** [comment]
Hi @andyjessop , I will investigate this point. 

For now make `$ npm install strapi-bookshelf@alpha strapi-knex@alpha knex mysql --save` it's have to work with that.

**Comment by ArkhipovK** [comment]
Quite enouth to install just npm install strapi-bookshelf@alpha --save
I had already opened ( and self-closed) similar issue cople of weeks ago.

https://github.com/strapi/strapi/issues/410
