### ISSUE TITLE
Mongo DB authentication problem with Strapi installation

### ISSUE THREAD

**Issue by Mario-Boss** [strapi/strapi#4417]
**Describe the bug**

I have a Mongo DB authentication problem with my Strapi installation.

Strapi is running fine when Mongo authentification is disabled in my config file /etc/mongod.conf
but it's not running when I try to enable authentication.
I provided my config files below - do you need any other info?
I provided the error generated by the Nginx, Mongo and Passenger below - do you need other?

**PS. to make it run I have added server.js file in the Strapi root folder:**

`const strapi = require('strapi');
strapi().start();`

**Expected behavior**

Strapi running with Mongo enabled authentication

**Code snippets**

**/etc/mongod.conf**

```
storage:
  dbPath: /var/lib/mongodb
  journal:
   enabled: true
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log
net:
  port: 27017
  bindIp: 127.0.0.1
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
security:
  authorization: "enabled"
```

**strapi_folder/config/environments/development/database.json**

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "database": "mongo_db_name_here",
        "host": "127.0.0.1",
        "srv": false,
        "port": 27017,
        "username": "mongo_db_user_here",
        "password": "mongo_db_password_here"
      },
      "options": {
        "authenticationDatabase": "mongo_db_name_here"
      }
    }
  }
}
```

**strapi_folder/config/environments/development/database.json**

```
{
  "host": "localhost",
  "port": 1337,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
```

**System**
- 1&1 VPS server with Ubuntu 18.04 and Plesk Onyx version: 17.8.11.
- Nginx version: 1.16.1 (Proxy mode in Plesk is disabled).
- Strapi version: 3.0.0-beta.17.4 installed globally 
- subdomain with Let's Encrypt certificate
- ports 1337, 1338, 1339, 27017 are unblocked.
- Mongo DB version: 4.2.1
- pm2 version: 3.5.1
- Nginx and Mongo are running in the background as services
- Node.js version: 10.16.0 - run as Node.js App in Plesk
- NPM version: 6.9.0
- Phusion Passenger version: 5.3.5

**Error from /var/log/nginx/error.log**

```
[ E 2019-10-31 09:48:33.2194 4378/T6 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-3] Cannot checkout session because a spawning error occurred. The identifier of the error is 41a8bac2. Please see earlier logs for details about the error.
App 5036 output: [2019-10-31T09:48:34.534Z] error An index error happened, it wasn't applied.
App 5036 output:        - command createIndexes requires authentication
App 5036 output: [2019-10-31T09:48:34.537Z] error An index error happened, it wasn't applied.
App 5036 output:        - command createIndexes requires authentication
App 5036 output: [2019-10-31T09:48:34.537Z] error An index error happened, it wasn't applied.
App 5036 output:        - command createIndexes requires authentication
App 5036 output: [2019-10-31T09:48:34.539Z] error Bootstrap function in plugin "content-manager" failed
App 5036 output: [2019-10-31T09:48:34.539Z] error MongoError: command find requires authentication
App 5036 output:     at Connection.<anonymous> (/var/www/vhosts/domain.com/subdomain.domain.com/api/node_modules/mongodb/lib/core/connection/pool.js:466:61)
App 5036 output:     at Connection.emit (events.js:198:13)
App 5036 output:     at processMessage (/var/www/vhosts/domain.com/subdomain.domain.com/api/node_modules/mongodb/lib/core/connection/connection.js:364:10)
App 5036 output:     at Socket.<anonymous> (/var/www/vhosts/domain.com/subdomain.domain.com/api/node_modules/mongodb/lib/core/connection/connection.js:533:15)
App 5036 output:     at Socket.emit (events.js:198:13)
App 5036 output:     at addChunk (_stream_readable.js:288:12)
App 5036 output:     at readableAddChunk (_stream_readable.js:269:11)
App 5036 output:     at Socket.Readable.push (_stream_readable.js:224:10)
App 5036 output:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[ E 2019-10-31 09:48:34.6091 4378/T13 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/vhosts/domain.com/subdomain.domain.com/api: The application process exited prematurely.
  Error ID: 23179845
  Error details saved to: /tmp/passenger-error-uOFlso.html
```

**error in /tmp/passenger-error-uOFlso.html**

```
"error" : {
      "category" : "INTERNAL_ERROR",
      "id" : "23179845",
      "problem_description_html" : "<p>The Phusion Passenger application server tried to start the web application through a Passenger-internal helper tool called the \"wrapper\". But Passenger was unable to execute that helper tool because it encountered an internal error.</p><p>The stdout/stderr output of the subprocess so far is:</p><pre>[2019-10-31T09:48:34.534Z] error An index error happened, it wasn&apos;t applied.\n\t- command createIndexes requires authentication\n[2019-10-31T09:48:34.537Z] error An index error happened, it wasn&apos;t applied.\n\t- command createIndexes requires authentication\n[2019-10-31T09:48:34.537Z] error An index error happened, it wasn&apos;t applied.\n\t- command createIndexes requires authentication\n[2019-10-31T09:48:34.539Z] error Bootstrap function in plugin &quot;content-manager&quot; failed\n[2019-10-31T09:48:34.539Z] error MongoError: command find requires authentication\n    at Connection.&lt;anonymous&gt; (/var/www/vhosts/domain.com/subdomain.domain.com/api/node_modules/mongodb/lib/core/connection/pool.js:466:61)\n    at Connection.emit (events.js:198:13)\n    at processMessage (/var/www/vhosts/domain.com/subdomain.domain.com/api/node_modules/mongodb/lib/core/connection/connection.js:364:10)\n    at Socket.&lt;anonymous&gt; (/var/www/vhosts/domain.com/subdomain.domain.com/api/node_modules/mongodb/lib/core/connection/connection.js:533:15)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n</pre>",
      "solution_description_html" : "<p class=\"sole-solution\">Unfortunately, Passenger does not know how to solve this problem. Please try troubleshooting the problem by studying the <strong>error message</strong> and the <strong>diagnostics</strong> reports. You can also consult <a href=\"https://www.phusionpassenger.com/support\">the Passenger support resources</a> for help.</p>",
      "summary" : "The application process exited prematurely."
   }
```

**logs in /var/log/mongodb/mongod.log**

```
2019-10-31T09:46:19.999+0000 I  ACCESS   [conn115] Successfully authenticated as principal mongo_db_user_here on mongo_db_name_here from client 127.0.0.1:49428
2019-10-31T09:46:20.035+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49430 #116 (5 connections now open)
2019-10-31T09:46:20.038+0000 I  NETWORK  [conn116] received client metadata from 127.0.0.1:49430 conn116: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-ge
neric" }, platform: "Node.js v10.16.3, LE" }
2019-10-31T09:46:20.041+0000 I  ACCESS   [conn116] Successfully authenticated as principal mongo_db_user_here on mongo_db_name_here from client 127.0.0.1:49430
2019-10-31T09:46:26.682+0000 I  NETWORK  [conn116] end connection 127.0.0.1:49430 (4 connections now open)
2019-10-31T09:46:26.682+0000 I  NETWORK  [conn115] end connection 127.0.0.1:49428 (3 connections now open)
2019-10-31T09:46:26.682+0000 I  NETWORK  [conn114] end connection 127.0.0.1:49426 (2 connections now open)
2019-10-31T09:46:26.682+0000 I  NETWORK  [conn113] end connection 127.0.0.1:49424 (1 connection now open)
2019-10-31T09:46:26.682+0000 I  NETWORK  [conn112] end connection 127.0.0.1:49422 (0 connections now open)
2019-10-31T09:48:28.371+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49444 #117 (1 connection now open)
2019-10-31T09:48:28.375+0000 I  NETWORK  [conn117] received client metadata from 127.0.0.1:49444 conn117: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-ge
neric" }, platform: "Node.js v10.16.3, LE" }
2019-10-31T09:48:28.392+0000 I  ACCESS   [conn117] Successfully authenticated as principal mongo_db_user_here on mongo_db_name_here from client 127.0.0.1:49444
2019-10-31T09:48:28.457+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49446 #118 (2 connections now open)
2019-10-31T09:48:28.459+0000 I  NETWORK  [conn118] received client metadata from 127.0.0.1:49446 conn118: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-ge
neric" }, platform: "Node.js v10.16.3, LE" }
2019-10-31T09:48:28.460+0000 I  ACCESS   [conn118] Successfully authenticated as principal mongo_db_user_here on mongo_db_name_here from client 127.0.0.1:49446
2019-10-31T09:48:28.461+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49448 #119 (3 connections now open)
2019-10-31T09:48:28.462+0000 I  NETWORK  [conn119] received client metadata from 127.0.0.1:49448 conn119: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-generic" }, platform: "Node.js v10.16.3, LE" }
2019-10-31T09:48:28.463+0000 I  ACCESS   [conn119] Successfully authenticated as principal mongo_db_user_here on mongo_db_name_here from client 127.0.0.1:49448
2019-10-31T09:48:28.466+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49450 #120 (4 connections now open)
2019-10-31T09:48:28.466+0000 I  NETWORK  [conn120] received client metadata from 127.0.0.1:49450 conn120: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-generic" }, platform: "Node.js v10.16.3, LE" }
2019-10-31T09:48:28.498+0000 I  ACCESS   [conn120] Successfully authenticated as principal mongo_db_user_here on mongo_db_name_here from client 127.0.0.1:49450
2019-10-31T09:48:28.530+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49452 #121 (5 connections now open)
2019-10-31T09:48:28.534+0000 I  NETWORK  [conn121] received client metadata from 127.0.0.1:49452 conn121: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-generic" }, platform: "Node.js v10.16.3, LE" }
2019-10-31T09:48:28.537+0000 I  ACCESS   [conn121] Successfully authenticated as principal mongo_db_user_here on mongo_db_name_here from client 127.0.0.1:49452
2019-10-31T09:48:33.124+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49462 #122 (6 connections now open)
2019-10-31T09:48:33.127+0000 I  NETWORK  [conn122] received client metadata from 127.0.0.1:49462 conn122: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-generic" }, platform: "Node.js v10.16.0, LE" }
2019-10-31T09:48:33.185+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49464 #123 (7 connections now open)
2019-10-31T09:48:33.190+0000 I  NETWORK  [conn123] received client metadata from 127.0.0.1:49464 conn123: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-generic" }, platform: "Node.js v10.16.0, LE" }
2019-10-31T09:48:33.190+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49466 #124 (8 connections now open)
2019-10-31T09:48:33.192+0000 I  NETWORK  [conn124] received client metadata from 127.0.0.1:49466 conn124: { driver: { name: "nodejs-core", version: "3.3.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-45-generic" }, platform: "Node.js v10.16.0, LE" }
2019-10-31T09:48:33.192+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:49468 #125 (9 connections now open)
2019-10-31T09:48:33.199+0000 I  NETWORK  [conn124] end connection 127.0.0.1:49466 (8 connections now open)
2019-10-31T09:48:33.199+0000 I  NETWORK  [conn122] end connection 127.0.0.1:49462 (7 connections now open)
2019-10-31T09:48:33.199+0000 I  NETWORK  [conn123] end connection 127.0.0.1:49464 (6 connections now open)
```

Thank you for any constructive help

**Comment by Mario-Boss** [comment]
hello 
anyone can help ?

**Comment by lauriejim** [comment]
Hello! I'm not a MongoDB expert. I know Strapi works fine with local and MongoDB atlas. I think it comes from your server configs.
Hope the community will be able to help you.

**Comment by Mario-Boss** [comment]
Correct.. Strapi is working fine with a not secure mode in my case.. The problem is appearing when the secure mode is enabled.

**Comment by Mario-Boss** [comment]
I have finally found a solution. For all people who can struggle with something similar please follow these steps:
1. open the /etc/nginx/nginx.conf to find worker user of nginx
2. Or _ps -ef | grep nginx_  and check which user is running worker process
_$ ps aux | grep "nginx: worker process" | awk '{print $1}'_
3. In my case it was nginx
4. Give access to that directory
_$ chown -R nginx.www-data /var/lib/nginx_

**Comment by lauriejim** [comment]
Okay thank you for these details
