### ISSUE TITLE
My strapi server suddenly crashed, GraphQLError: Syntax Error: Expected :, found Name "_id"

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [strapi/strapi#4425]
Hi, I'm building a headless cms for a e-commerce project.

**System**

- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.4
- Database: MongoDB atlas cloud
- Operating system: LinuxMint 19.2 Cinnamon
- Front-end : React 16.11.0

It has been working well during past two days, then today after I created some relation data (not sure if this is the cause), then my server suddenly crashed and the error message is below:

```
error GraphQLError: Syntax Error: Expected :, found Name "_id"
    at syntaxError (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:1404:40)
    at Parser.parseFieldDefinition (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:859:10)
    at Parser.optionalMany (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:1497:28)
    at Parser.parseFieldsDefinition (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:846:17)
    at Parser.parseObjectTypeDefinition (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:798:23)
    at Parser.parseTypeSystemDefinition (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:696:23)
    at Parser.parseDefinition (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:146:23)
    at Parser.many (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/graphql/language/parser.js:36:17)
    at Object.addPolymorphicUnionType (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-plugin-graphql/services/Types.js:178:8)
    at Object.generateSchema (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-plugin-graphql/services/Schema.js:189:15)
    at Object.initialize (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
    at /home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi/lib/hooks/index.js:43:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
I tried to uninstall the graphql and restarted the server, it would work. But if I install it again and restart, I have the above error. I definitely need graphql for my project, so I would like to know how to fix this problem, what has caused it?

**Comment by AnnieTaylorCHEN** [comment]
I found the one the of product model has a wrong name: product-types. I typed this in the adminUI and I think it caused the whole problem. Now I correct it in the code and can start my server again.
To avoid this issue, (as CMS will be used be a lot non-coders) I think it would be nice to have either notification, not hint on correct ways of writing, or automatically sanitation in the backend.

**Comment by idesignzone** [comment]
> I found the one the of product model has a wrong name: product-types. I typed this in the adminUI and I think it caused the whole problem. Now I correct it in the code and can start my server again.
> To avoid this issue, (as CMS will be used be a lot non-coders) I think it would be nice to have either notification, not hint on correct ways of writing, or automatically sanitation in the backend.

Could you please tell me where did you change the code? I created a single type and strapi crashed. now I realized name had a syntax error but I dont know where to fix it.
