### ISSUE TITLE
Command yarn setup fail

### ISSUE THREAD

**Issue by enBonnet** [strapi/strapi#4429]
**Describe the bug**
I'm trying to follow [Contributin Guide](https://github.com/enBonnet/strapi/blob/master/CONTRIBUTING.md) but command `yarn setup` always fail.

**Steps to reproduce the behavior**
1. `cd strapi`
2. `yarn setup`

**Response**
```shell
λ Adumar strapi → λ git master* → yarn setup
yarn run v1.17.3
$ yarn && yarn build
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > @testing-library/react@9.3.0" has unmet peer dependency "react@*".
warning " > @testing-library/react@9.3.0" has unmet peer dependency "react-dom@*".
warning " > @testing-library/react-hooks@2.0.3" has unmet peer dependency "react@>=16.9.0".
warning " > enzyme-adapter-react-16@1.15.1" has unmet peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.15.1" has unmet peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.12.1" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning " > react-test-renderer@16.10.2" has unmet peer dependency "react@^16.0.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.15.0" has unmet peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-plugin-redux-saga@1.1.1" has unmet peer dependency "redux-saga@>= 0.11.1 < 1 || >= 1.0.0".
warning "workspace-aggregator-a8a19004-ae2b-4079-a29f-ef9c1615f232 > strapi-admin > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-a8a19004-ae2b-4079-a29f-ef9c1615f232 > strapi-admin > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "workspace-aggregator-a8a19004-ae2b-4079-a29f-ef9c1615f232 > strapi-hook-bookshelf > bookshelf@0.15.1" has unmet peer dependency "knex@>=0.13.0 <0.18.0".
warning "workspace-aggregator-a8a19004-ae2b-4079-a29f-ef9c1615f232 > strapi-plugin-graphql > graphql-type-datetime@0.2.4" has incorrect peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-a8a19004-ae2b-4079-a29f-ef9c1615f232 > strapi-plugin-graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-a8a19004-ae2b-4079-a29f-ef9c1615f232 > strapi-admin > @buffetjs/styles > react-dates@21.2.0" has unmet peer dependency "react-with-direction@^1.3.1".
[5/5] 🔨  Building fresh packages...
[12/17] ⠈ metrohash
[-/17] ⠈ waiting...
[15/17] ⠈ sqlite3
[-/17] ⠈ waiting...
error /Volumes/DATOS/Proyectos/strapi/node_modules/metrohash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Volumes/DATOS/Proyectos/strapi/node_modules/metrohash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Volumes/DATOS/Proyectos/strapi/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/DATOS/Proyectos/strapi/node_modules/metrohash/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/DATOS/Proyectos/strapi/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/enderbonnet/.node-gyp/10.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/enderbonnet/.node-gyp/10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/Volumes/DATOS/Proyectos/strapi/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/enderbonnet/.node-gyp/10.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/DATOS/Proyectos/strapi/node_modules/metrohash',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Volumes/DATOS/Proyectos/strapi/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/enderbonnet/.nvm/versions/node/v10.16.3/bin/node" "/Volumes/DATOS/Proyectos/strapi/node_modules/metrohash/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Volumes/DATOS/Proyectos/strapi/node_modules/metrohash

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**System**
- Node.js version: v10.16.3
- NPM version: 6.12.0
- Strapi version: 
- Database:
- Operating system: MacOS Catalina 10.15.1

**Additional context**
Looking on google found [this](https://github.com/schnerd/d3-scale-cluster/issues/7) but when  try to reinstall xcode with `xcode-select --install` got:

```shell
λ Adumar strapi → λ git master* → xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by derrickmehaffy** [comment]
https://github.com/nodejs/node-gyp/issues/1464
https://github.com/nodejs/node-gyp/pull/1940

This appears to be an issue upstream from Strapi. I'll leave this open until the Strapi guy can confirm.

**Comment by lauriejim** [comment]
Ping @soupette and @alexandrebodin

**Comment by tranlehaiquan** [comment]
I also fail when follow Contributin Guide.

#### Response

```
yarn run v1.19.1
$ yarn && yarn build
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.1: The platform "win32" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @testing-library/react@9.3.0" has unmet peer dependency "react@*".
warning " > @testing-library/react@9.3.0" has unmet peer dependency "react-dom@*".
warning " > @testing-library/react-hooks@2.0.3" has unmet peer dependency "react@>=16.9.0".
warning " > enzyme-adapter-react-16@1.15.1" has unmet peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.15.1" has unmet peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.12.1" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning " > react-test-renderer@16.10.2" has unmet peer dependency "react@^16.0.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.15.0" has unmet peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-plugin-redux-saga@1.1.1" has unmet peer dependency "redux-saga@>= 0.11.1 < 1 || >= 1.0.0".
warning "workspace-aggregator-c2222daf-6224-478c-b517-a68dc9a19821 > strapi-admin > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-c2222daf-6224-478c-b517-a68dc9a19821 > strapi-admin > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "workspace-aggregator-c2222daf-6224-478c-b517-a68dc9a19821 > strapi-hook-bookshelf > bookshelf@0.15.1" has unmet peer dependency "knex@>=0.13.0 <0.18.0".
warning "workspace-aggregator-c2222daf-6224-478c-b517-a68dc9a19821 > strapi-plugin-graphql > graphql-type-datetime@0.2.4" has incorrect peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-c2222daf-6224-478c-b517-a68dc9a19821 > strapi-plugin-graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-c2222daf-6224-478c-b517-a68dc9a19821 > strapi-admin > @buffetjs/styles > react-dates@21.2.0" has unmet peer dependency "react-with-direction@^1.3.1".
[5/5] Building fresh packages...
[6/16] ⠄ cypress
[9/16] ⠄ pngquant-bin
[11/16] ⡀ metrohash
[12/16] ⡀ protobufjs
error C:\workspace\netgame\strapi\node_modules\metrohash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\workspace\netgame\strapi\node_modules\metrohash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\workspace\\netgame\\strapi\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\workspace\netgame\strapi\node_modules\metrohash

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### System

- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version:
- Database:
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
Hi the issue comes from the metrohash package that requires pythin and c++ toolchain to work. 

Wiating for this issue to be handled https://github.com/sebastian-software/asset-hash/issues/3 we can might have to consider removing the dependency somehow and if possible @soupette (it comme from roolup-plugin-rebase in the helper plugin)

**Comment by soupette** [comment]
Well we can "easily" remove the `rebase` which was mainly used for the assets of the helper plugin. Since they are all svgs we can easily convert them to react components... If someone feels like taking care of the migration I would love it, if not I'll see what I can do about it after we finished the `dynamicZone` feature.
