### ISSUE TITLE
use of strapi-bookshelf hints Table 'api.user' doesn't exist

### ISSUE THREAD

**Issue by gongchao** [strapi/strapi#443]
**Node.js version**:
v8.5.0
**npm version**:
5.5.1s
**Strapi version**:
3.0.0-alpha.7.3
**mysql version**:
5.6
**strapi-bookshelf version**
3.0.0-alpha.7.3
**Operating system**:
database.json
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "localhost",
        "port": 3306,
        "database": "api",
        "username": "root",
        "password": ""
      },
      "options": {}
    }
  }
}
```

```
ERROR (82159 on gongchaodeMacBook-Pro-2.local): select `user`.* from `user` where `role` = '0' limit 100 - ER_NO_SUCH_TABLE: Table 'api.user' doesn't exist
    Error: ER_NO_SUCH_TABLE: Table 'api.user' doesn't exist
        at Query.Sequence._packetToError (/Users/gongchao/Desktop/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
        at Query.ErrorPacket (/Users/gongchao/Desktop/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
        at Protocol._parsePacket (/Users/gongchao/Desktop/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
        at Parser.write (/Users/gongchao/Desktop/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
        at Protocol.write (/Users/gongchao/Desktop/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
        at Socket.<anonymous> (/Users/gongchao/Desktop/app/node_modules/mysql/lib/Connection.js:103:28)
        at emitOne (events.js:115:13)
        at Socket.emit (events.js:210:7)
        at addChunk (_stream_readable.js:266:12)
        at readableAddChunk (_stream_readable.js:253:11)
        at Socket.Readable.push (_stream_readable.js:211:10)
        at TCP.onread (net.js:585:20)
        at Protocol._enqueue (/Users/gongchao/Desktop/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
        at Connection.query (/Users/gongchao/Desktop/app/node_modules/mysql/lib/Connection.js:208:25)
        at /Users/gongchao/Desktop/app/node_modules/knex/lib/dialects/mysql/index.js:152:18
    From previous event:
        at Client_MySQL._query (/Users/gongchao/Desktop/app/node_modules/knex/lib/dialects/mysql/index.js:146:12)
        at Client_MySQL.query (/Users/gongchao/Desktop/app/node_modules/knex/lib/client.js:197:17)
        at Runner.<anonymous> (/Users/gongchao/Desktop/app/node_modules/knex/lib/runner.js:146:36)
    From previous event:
        at /Users/gongchao/Desktop/app/node_modules/knex/lib/runner.js:65:21
        at runCallback (timers.js:781:20)
        at tryOnImmediate (timers.js:743:5)
        at processImmediate [as _immediateCallback] (timers.js:714:5)
    From previous event:
        at Runner.run (/Users/gongchao/Desktop/app/node_modules/knex/lib/runner.js:51:31)
        at Builder.Target.then (/Users/gongchao/Desktop/app/node_modules/knex/lib/interface.js:35:43)
```

**Comment by ArkhipovK** [comment]
Right now you have to create this table by yourself. As decsribed here https://github.com/strapi/strapi/issues/365

**Comment by lauriejim** [comment]
Hi @gongchao and @ArkhipovK.

We will add a warn log in the next version to tell you to create user table. https://github.com/strapi/strapi/pull/416
