### ISSUE TITLE
Model errors when creating content types with caps or spaces

### ISSUE THREAD

**Issue by etx** [strapi/strapi#444]
I'm seeing a couple different kinds of errors when building content types from the admin UI. If you name the content type "Supdude" it works as expected. 

If I name the content type "Sup Dude" and restart the server I see an error when the model is called. 
`
ERROR (69527 on H8385.ad.hugeinc.com): ENOENT: no such file or directory, scandir '/Users/dkuschel/Desktop/strapi-dev/api/sup dude/models'
    Error: ENOENT: no such file or directory, scandir '/Users/dkuschel/Desktop/strapi-dev/api/sup dude/models'
        at Object.fs.readdirSync (fs.js:924:18)
        at Object.getModelPath (/Users/dkuschel/Desktop/strapi/packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js:112:25)
        at createModel (/Users/dkuschel/Desktop/strapi/packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js:53:35)
        at <anonymous>
`

If I name the content type "SupDude" and restart the server I see an error when the model is called. 
`
DEBUG (69539 on H8385.ad.hugeinc.com): GET /users-permissions/roles (5 ms)
ERROR (69539 on H8385.ad.hugeinc.com): Cannot read property 'fetchAll' of undefined
    TypeError: Cannot read property 'fetchAll' of undefined
        at find (/Users/dkuschel/Desktop/strapi-dev/api/supdude/controllers/SupDude.js:18:48)
        at dispatch (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
        at dispatch (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-compose/index.js:42:32)
        at next (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-compose/index.js:43:18)
        at module.exports (/Users/dkuschel/Desktop/strapi/packages/strapi-plugin-users-permissions/config/policies/permissions.js:41:11)
        at dispatch (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-compose/index.js:42:32)
        at next (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-compose/index.js:43:18)
        at /Users/dkuschel/Desktop/strapi/packages/strapi/lib/middlewares/router/utils/routerChecker.js:29:11
        at dispatch (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-compose/index.js:42:32)
        at /Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-compose/index.js:34:12
        at dispatch (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
        at validator (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-router-joi/joi-router.js:327:38)
        at dispatch (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/Users/dkuschel/Desktop/strapi/packages/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
`

**Node.js 9.3.0**:
**npm 5**:
**Strapi 3.0.0-alpha.7.3**:
**MacOS 10.12.6**:

**Comment by lauriejim** [comment]
Hello @etx thank you for your issue.

It seems looks like to this issue (https://github.com/strapi/strapi/issues/328)
