### ISSUE TITLE
"Impossible to register the 'core_store' model" when following AWS deployment guide

### ISSUE THREAD

**Issue by pbjer** [strapi/strapi#4448]
**Describe the bug**
When following the AWS deployment guide, I receive an error [at the end of step 6](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#_6-install-pm2-runtime) when I run `pm2 start ecosystem.config.js`

Error: `error Impossible to register the 'core_store' model.`

**Steps to reproduce the behavior**
Follow the AWS deployment guide to step 6 and start pm2 with `pm2 start ecosystem.config.js`

**Expected behavior**
My Strapi project should now be available at http://my-ip-address:1337/

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: `v10.17.0`
- NPM version: `6.11.3`
- Strapi version: `3.0.0-beta.17.4`
- Database: `postgresql`
- Operating system: `Ubuntu 18.04`

**Additional context**
I was not able to find another related issues, but this is my first bug report so my apologies if I messed up! Here is the error log:
```
[2019-11-05T02:53:41.956Z] error Impossible to register the 'core_store' model.
[2019-11-05T02:53:41.957Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Bluebird.try.then.catch (/home/ubuntu/sportex-strapi/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:318:17)
    at tryCatcher (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/util.js:16:23)
    at /home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/sportex-strapi/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by derrickmehaffy** [comment]
Seems your DB is responding too slow. Try adding the following to your database.json (under options which is included in the object)

```
      "options": {
        "debug": false,
        "acquireConnectionTimeout": 100000,
        "pool": {
          "min": 0,
          "max": 10,
          "createTimeoutMillis": 30000,
          "acquireTimeoutMillis": 600000,
          "idleTimeoutMillis": 20000,
          "reapIntervalMillis": 20000,
          "createRetryIntervalMillis": 200
        }
      }
```

**Comment by pbjer** [comment]
@derrickmehaffy Thank you. Unfortunately I am still encountering the same error. I should have mentioned I already added these options while trying to debug last night, apologies as I forgot to include in my report.

**Comment by derrickmehaffy** [comment]
:thinking: That timeout directly relates to the connection to the database meaning the DB is responding too slow or the connections are being killed to fast

**Comment by pbjer** [comment]
Hmm okay - I went ahead and checked RDS to see if there was any output there and it looks like there are some error logs:
```
2019-11-05 03:03:43 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:03:43 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.002 s, total=0.112 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16384 kB, estimate=16384 kB
2019-11-05 03:08:43 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:08:43 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.002 s, total=0.112 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16384 kB, estimate=16384 kB
2019-11-05 03:13:43 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:13:43 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.001 s, total=0.112 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16384 kB
2019-11-05 03:18:43 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:18:43 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.001 s, total=0.112 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16382 kB, estimate=16384 kB
2019-11-05 03:23:43 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:23:43 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.001 s, total=0.112 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16384 kB
2019-11-05 03:28:43 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:28:43 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.100 s, sync=0.001 s, total=0.111 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16384 kB
2019-11-05 03:33:43 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:33:43 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.002 s, total=0.113 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16383 kB, estimate=16384 kB
2019-11-05 03:38:44 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:38:44 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.001 s, total=0.111 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16384 kB
2019-11-05 03:43:44 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:43:44 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.102 s, sync=0.001 s, total=0.112 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16384 kB
2019-11-05 03:48:44 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:48:44 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.001 s, total=0.111 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16383 kB, estimate=16384 kB
2019-11-05 03:53:45 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:53:45 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.002 s, total=0.110 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16383 kB, estimate=16384 kB
2019-11-05 03:58:45 UTC::@:[5359]:LOG:  checkpoint starting: time
2019-11-05 03:58:45 UTC::@:[5359]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.101 s, sync=0.001 s, total=0.112 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16384 kB
```
is this likely an RDS issue then?

**Comment by derrickmehaffy** [comment]
That would be my guess, that error you are getting about the pool timeout comes from Knex's pool management called tarn. https://github.com/vincit/tarn.js/

**Comment by pbjer** [comment]
**SOLVED:**

Issue was caused due to default security group applied to Amazon RDS. Strapi's current documentation assumes the AWS account is fresh/has no other security groups already set. If AWS account already has a security group, the RDS instance will not have the newly created security group applied by default and it must be applied manually.

**Comment by derrickmehaffy** [comment]
Glad you figured it out :)

**Comment by xiaosu12138** [comment]
> **SOLVED:**
> 
> Issue was caused due to default security group applied to Amazon RDS. Strapi's current documentation assumes the AWS account is fresh/has no other security groups already set. If AWS account already has a security group, the RDS instance will not have the newly created security group applied by default and it must be applied manually.

So, what should I do? What should I change
