### ISSUE TITLE
hi I can't  do the command of develop 

### ISSUE THREAD

**Issue by HappyDaydayUp** [strapi/strapi#4455]
**Describe the bug**

**Steps to reproduce the behavior**

do the Quickstart command to create a Strapi project instantly:

1. Go to 'do the command npm develop '
  and the log is "
> strapi develop

Building your admin UI with development configuration ...

✖ Webpack
  Compiled with some errors in 12.95s

Error: ./node_modules/strapi-helper-plugin/dist/eMfGAxAx.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:770:11)
    at Socket._write (net.js:782:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at Socket.Writable.end (_stream_writable.js:594:10)
    at Socket.end (net.js:574:31)
    at handleInput (/Users/jili/Desktop/study/cms/my-project/node_modules/imagemin-pngquant/node_modules/execa/index.js:89:17)
    at module.exports (/Users/jili/Desktop/study/cms/my-project/node_modules/imagemin-pngquant/node_modules/execa/index.js:309:2)
    at /Users/jili/Desktop/study/cms/my-project/node_modules/imagemin-pngquant/index.js:52:13
    at /Users/jili/Desktop/study/cms/my-project/node_modules/strapi-admin/index.js:191:23
    at finalCallback (/Users/jili/Desktop/study/cms/my-project/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/jili/Desktop/study/cms/my-project/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/jili/Desktop/study/cms/my-project/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/jili/Desktop/study/cms/my-project/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/jili/Desktop/study/cms/my-project/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/jili/Desktop/study/cms/my-project/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jili/Desktop/study/cms/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/jili/Desktop/study/cms/my-project/node_modules/webpack/lib/Compilation.js:1414:32
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jili/.npm/_logs/2019-11-05T10_52_25_081Z-debug.log
终端进程已终止，退出代码: 1

"

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**.  macOS Catalina  10.15.1 
- Node.js version:  v12.12.0
- NPM version:  6.11.3
- Strapi version:  v3.0.0-beta.17.5
- Database: sql
- Operating system:

**Additional context**

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

Can you please clean you issue body it's not understandable. Thank you.

**Comment by vasydragan** [comment]
same error for me 2

**Comment by martinstanojevic** [comment]
Any news on this? I have the same problem.

**Comment by zeroedin** [comment]
I'm running into the same issue but with `yarn build` instead of `yarn develop`

**Describe the bug A clear and concise description of what the bug is.**

Running command `yarn build` after `strapi new cms` Errors out with the following error message:

```
$ yarn build
yarn run v1.19.1
$ strapi build
Building your admin UI with development configuration ...

✖ Webpack
  Compiled with some errors in 14.76s

Error: ./.cache/plugins/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_boolean.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
TypeError: Cannot read property 'end' of undefined
    at handleInput (/srv/strapi/cms/node_modules/imagemin-pngquant/node_modules/execa/index.js:89:17)
    at module.exports (/srv/strapi/cms/node_modules/imagemin-pngquant/node_modules/execa/index.js:309:2)
    at input (/srv/strapi/cms/node_modules/imagemin-pngquant/index.js:52:13)
    at compiler.run (/srv/strapi/cms/node_modules/strapi-admin/index.js:191:23)
    at finalCallback (/srv/strapi/cms/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/srv/strapi/cms/node_modules/webpack/lib/Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/strapi/cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/srv/strapi/cms/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/srv/strapi/cms/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/srv/strapi/cms/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/strapi/cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/srv/strapi/cms/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/srv/strapi/cms/node_modules/webpack/lib/Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/strapi/cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/srv/strapi/cms/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/srv/strapi/cms/node_modules/webpack/lib/Compilation.js:1423:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/strapi/cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/srv/strapi/cms/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/srv/strapi/cms/node_modules/webpack/lib/Compilation.js:1414:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Steps to reproduce the behavior**

* Install node version 10.17.0 
* Install yarn version 1.19.1
* Create new strapi cms `strapi new cms`
* Navigate to cms folder `cd cms`
* Build admin interface `yarn build`


**Expected behavior A clear and concise description of what you expected to happen.**

Expect Admin panel to build

**Screenshots If applicable, add screenshots to help explain your problem.**

**Code snippets If applicable, add code samples to help explain your problem.**

**System**

**Node.js version:** 10.17.0
**NPM version:** 6.11.3
**Strapi version:** 3.0.0-beta.17.5
**Database:**  Postgres 9.6.16
**Operating system:** Ubuntu 18.04

**Comment by zeroedin** [comment]
Looks like this is related:

https://github.com/imagemin/imagemin/issues/329

**Comment by rares-lupascu** [comment]
same here ... but i do not think anyone cares :/

**Comment by derrickmehaffy** [comment]
@zeroedin `sudo apt install libpng-dev build-essential -y`

**Comment by thedevxen** [comment]
I am getting
```Building your admin UI with production configuration ...

✖ Webpack
  Compiled with some errors in 12.67s

Error: ./.cache/admin/src/assets/images/logo_strapi.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):```

**Comment by soupette** [comment]
@thedevxen can you upgrade your app to **beta.18** , delete your `.cache` and `build`folders and restart your app?

This dependency has been removed so your issue should not be happening.

**Comment by riteshtailor2002** [comment]
Hi ,

I am getting the same error when i tried to add a file to get Count with GraphQL according to the documentation from here :https://strapi.io/documentation/v3.x/guides/count-graphql.html#setup-the-application

> strapi develop

Error while running command develop: undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forsale-forlease@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the forsale-forlease@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Please help. None of the command working.
I have tried clearing the cache, deleted the build folder, restarted the system but still not get fixed.

![Screen Shot 2020-07-15 at 4 51 41 AM](https://user-images.githubusercontent.com/30510793/87485649-e9c96b00-c656-11ea-9092-a0b1b5667e8b.png)

**Comment by AdelShokry** [comment]
i have the same error after install graphgl plugin
$ strapi develop
Error while running command develop: undefined
error Command failed with exit code 1.

**Comment by LesleyLiveWall** [comment]
> Hi ,
> 
> I am getting the same error when i tried to add a file to get Count with GraphQL according to the documentation from here :https://strapi.io/documentation/v3.x/guides/count-graphql.html#setup-the-application
> 
> > strapi develop
> 
> Error while running command develop: undefined
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! forsale-forlease@0.1.0 develop: `strapi develop`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the forsale-forlease@0.1.0 develop script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> Please help. None of the command working.
> I have tried clearing the cache, deleted the build folder, restarted the system but still not get fixed.
> 
> ![Screen Shot 2020-07-15 at 4 51 41 AM](https://user-images.githubusercontent.com/30510793/87485649-e9c96b00-c656-11ea-9092-a0b1b5667e8b.png)

@riteshtailor2002 Did you by any change found a way to fix this issue?

**Comment by LesleyDuyndam** [comment]
> Hi ,
> 
> I am getting the same error when i tried to add a file to get Count with GraphQL according to the documentation from here :https://strapi.io/documentation/v3.x/guides/count-graphql.html#setup-the-application
> 
> > strapi develop
> 
> Error while running command develop: undefined
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! forsale-forlease@0.1.0 develop: `strapi develop`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the forsale-forlease@0.1.0 develop script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> Please help. None of the command working.
> I have tried clearing the cache, deleted the build folder, restarted the system but still not get fixed.
> 
> ![Screen Shot 2020-07-15 at 4 51 41 AM](https://user-images.githubusercontent.com/30510793/87485649-e9c96b00-c656-11ea-9092-a0b1b5667e8b.png)

@riteshtailor2002 Did you by any change found a way to resolve this issue?

**Comment by malaDev** [comment]
@lauriejim why this issue has been closed? many people still encountering this. 

anyone has some insights?

**Comment by tarnacious** [comment]
I had a similar issue to the was caused by Strapi trying to load swap files Vim was creating in the ./config/functions/ directory. This took a while to debug because the actual error was not being logged or displayed. This has recently been fixed so it displays the actual error. https://github.com/strapi/strapi/pull/7388/files
