### ISSUE TITLE
Unable to hot reload when save file when --watch-admin

### ISSUE THREAD

**Issue by Cow258** [strapi/strapi#4532]
**Describe the bug**
Throw error when `Ctrl+S` save file using VSCode.
I have to focus terminal and `Ctrl+C` kill server and restart to see the update.
This bug only happen on Windows.
This bug will not happen on MacOS.

**Steps to reproduce the behavior**
1. `npm install -g strapi`
2. `strapi new cms --quickstart`
3. Kill th server
4. `cd cms`
6. `cp .cache/admin/src/Admin/index.js admin/src/Admin/index.js`
7. `strapi develop --watch-admin`
8. Using VSCode open `cms` folder
9. Edit `admin/src/Admin/index.js`
10. Save file

**Expected behavior**
Strapi should copy `admin/src/Admin/index.js` into `.cache` folder,
Then Webpack will compile this file automatically,
Then browser will refresh automatically.

**Screenshots**
When save file on Windows 10
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at FSWatcher.watcher.on (A:\git\strapi\cms\node_modules\strapi-admin\index.js:337:38)
    at FSWatcher.emit (events.js:198:13)
    at FSWatcher.emitWithAll (A:\git\strapi\cms\node_modules\strapi-admin\node_modules\chokidar\index.js:522:32)
    at FSWatcher._emit (A:\git\strapi\cms\node_modules\strapi-admin\node_modules\chokidar\index.js:613:10)
    at closer._watchWithNodeFs (A:\git\strapi\cms\node_modules\strapi-admin\node_modules\chokidar\lib\nodefs-handler.js:370:20)
```
![image](https://user-images.githubusercontent.com/14261588/68919896-8e389c00-07ae-11ea-9dd3-28e21aadd937.png)
at `Line 337` : `await fs.copy(filePath, path.join(destFolder, targetPath));`
The `targetPath` is `undefined`

**Code snippets**
N/A

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Database: SQLite
- Operating system: Windows 10 1903 (build: 18362.476)

**Additional context**
N/A

**Comment by Cow258** [comment]
## Update
Linux or MacOS is using `/`
but Windows is using `\`
so this bug happen
![image](https://user-images.githubusercontent.com/14261588/68920414-1cf9e880-07b0-11ea-9cfd-7f7d9e0fa0a5.png)

**Comment by lauriejim** [comment]
This is an issue for @soupette and @alexandrebodin

**Comment by alexandrebodin** [comment]
HI, the fix is now merged. Will be released in the beta17.6. Closing
