### ISSUE TITLE
request /upload api default User Content media return error

### ISSUE THREAD

**Issue by LightningVII** [strapi/strapi#4565]
**Describe the bug**
I add User Content a "Avatar" field, media type,
use /upload api ,  error!
![image](https://user-images.githubusercontent.com/13807519/69330529-0d860e00-0c8e-11ea-9129-889c719ec9f2.png)

but I upload Article Content, "background" filed, success

help me

**Steps to reproduce the behavior**
1. default User Content add type "Avatar" field, type is media,
2. request /upload api

**Expected behavior**
[2019-11-21T12:13:38.724Z] error TypeError: Cannot read property 'globalId' of undefined
    at acc.(anonymous function).property.map.obj (/Users/Ace/MyDemo/strapi-umi-gatsby/server/node_modules/strapi-hook-mongoose/lib/relations.js:218:50)
    at Array.map (<anonymous>)
    at params.parseRelationships.Object.keys.reduce (/Users/Ace/MyDemo/strapi-umi-gatsby/server/node_modules/strapi-hook-mongoose/lib/relations.js:214:43)
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (/Users/Ace/MyDemo/strapi-umi-gatsby/server/node_modules/strapi-hook-mongoose/lib/relations.js:38:59)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-11-21T12:13:38.726Z] debug POST /upload (76 ms) 500

**Screenshots**
![image](https://user-images.githubusercontent.com/13807519/69330529-0d860e00-0c8e-11ea-9129-889c719ec9f2.png)

**System**
- Node.js version: v10.17.0
- NPM version:6.13.0
- Strapi version: 3.0.0-beta.17.5
- Database:mongoDB
- Operating system:macOS

**Additional context**
Create "Articles" Content, add "background" field, type is media,
request /upload api, success!

**Comment by lauriejim** [comment]
Answered in your previous issue.
