### ISSUE TITLE
Crash on TypeError: Cannot read property 'nature' of undefined when trying to save new relationship to content type

### ISSUE THREAD

**Issue by juyshy** [strapi/strapi#4580]
**Describe the bug**
When adding new  relationship to content type strapi crashes

**Steps to reproduce the behavior**
1. when in http://localhost:1337/admin/plugins/content-type-builder/models/dialogue
2. Add Another Field type   Relation with "visual has many dialogues "
3. when click save, it reports "The restart takes longer than expected" and crashes
 
here is the output on command prompt: 
```
  [2019-11-22T18:22:27.518Z] info File changed: D:\dh\github\dialogues\api\dialogue\models\Dialogue.settings.json
  [2019-11-22T18:22:29.058Z] error Impossible to register the 'dialogue' model.
  [2019-11-22T18:22:29.060Z] error TypeError: Cannot read property 'nature' of undefined
    at getType (D:\dh\github\dialogues\node_modules\strapi-hook-bookshelf\lib\buildDatabaseSchema.js:379:22)
    at D:\dh\github\dialogues\node_modules\strapi-hook-bookshelf\lib\buildDatabaseSchema.js:86:22
    at Array.forEach (<anonymous>)
    at buildColumns (D:\dh\github\dialogues\node_modules\strapi-hook-bookshelf\lib\buildDatabaseSchema.js:84:28)
    at createColumns (D:\dh\github\dialogues\node_modules\strapi-hook-bookshelf\lib\buildDatabaseSchema.js:118:14)
    at TableBuilder._fn (D:\dh\github\dialogues\node_modules\strapi-hook-bookshelf\lib\buildDatabaseSchema.js:160:9)
    at TableBuilder.toSQL (D:\dh\github\dialogues\node_modules\strapi-hook-knex\node_modules\knex\lib\schema\tablebuilder.js:40:12)
    at SchemaCompiler_SQLite3.alterTable (D:\dh\github\dialogues\node_modules\strapi-hook-knex\node_modules\knex\lib\schema\compiler.js:72:25)
    at SchemaCompiler_SQLite3.toSQL (D:\dh\github\dialogues\node_modules\strapi-hook-knex\node_modules\knex\lib\schema\compiler.js:55:26)
    at SchemaBuilder.toSQL (D:\dh\github\dialogues\node_modules\strapi-hook-knex\node_modules\knex\lib\schema\builder.js:82:43)
    at D:\dh\github\dialogues\node_modules\strapi-hook-knex\node_modules\knex\lib\runner.js:30:36
    at tryCatcher (D:\dh\github\dialogues\node_modules\bluebird\js\release\util.js:16:23)
    at D:\dh\github\dialogues\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (D:\dh\github\dialogues\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (D:\dh\github\dialogues\node_modules\bluebird\js\release\promise.js:609:26)
 ```

**Expected behavior**
A new field saved and no crash

**Screenshots**
 
![chrome_2019-11-22_20-22-17](https://user-images.githubusercontent.com/4095012/69450995-0f6fd000-0d67-11ea-957c-6702026e9453.png)

**Code snippets**
here is the code 
https://github.com/juyshy/dialogues
clone, npm i, strapi develop 

**System**

- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.17.5
- Database: sqlite
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello! 

How did you create these 2 relations ?

```
"leftCharacter": {
    "model": "visual",
    "via": "dialogues"
},
"rightCharacter": {
    "model": "visual",
    "via": "dialogues"
}
```

**Comment by juyshy** [comment]
All fields and those two I created in the admin interface adding new relation type field.

**Comment by lauriejim** [comment]
The issue is caused by that I think.

You have one model (**Dialogue**) that have two relations in the same model (**Visual**) and with the same key (`dialogues`)
And that is not possible normally in Strapi. Cause in **Visual** model, you will not be able to see this 2 relation.

I suggest you update your `via` value to `dialoguesRight` and `dialoguesLeft` in your **Dialogue** model.
And in the **Visual** model, you update to match with that.

**Comment by lauriejim** [comment]
**Path —** `dialogues/api/visual/models/Visual.settings.json`
```json
{
  "connection": "default",
  "collectionName": "visuals",
  ...
  "attributes": {
    ...
    "rightDialogues": {
      "collection": "dialogue",
      "via": "rightCharacter"
    },
    "leftDialogues": {
      "collection": "dialogue",
      "via": "leftCharacter"
    }
  }
}
```

**Path —** `dialogues/api/dialogue/models/Dialogue.settings.json`
```json
{
  "connection": "default",
  "collectionName": "dialogues",
  ...
  "attributes": {
    ...
    "leftCharacter": {
      "model": "visual",
      "via": "leftDialogues"
    },
    "rightCharacter": {
      "model": "visual",
      "via": "rightDialogues"
    }
  }
}
```
