### ISSUE TITLE
fresh install fail

### ISSUE THREAD

**Issue by cesarve77** [strapi/strapi#4582]
**Describe the bug**
I just trying a fresh install (first time)

**Steps to reproduce the behavior**
in terminal
`yarn create strapi-app strapi --quickstart`

**Expected behavior**
installes strapi

**Code snippets**
```
yarn create strapi-app strapi --quickstart
yarn create v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > prisma-binding@2.1.6" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "prisma-binding > apollo-link@1.2.2" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".
warning "prisma-binding > graphql-binding@2.2.5" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "prisma-binding > graphql-import@0.5.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "prisma-binding > graphql-tools@3.1.0" has unmet peer dependency "graphql@^0.13.0".
warning "prisma-binding > subscriptions-transport-ws@0.9.8" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.1".
warning "prisma-binding > apollo-link-error > apollo-link@1.2.3" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
warning "prisma-binding > graphql-binding > graphql-import@0.5.3" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
[4/4] 🔨  Building fresh packages...
[1/1] ⢀ sqlite3
error /Users/cesarramos/.config/yarn/global/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/cesarramos/.config/yarn/global/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.15.1 | darwin | x64
node-pre-gyp info check checked for "/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
gypgyp  info it worked if it ends withinfo ok
 it worked if it ends with ok
gypgyp info  usinginfo  node-gyp@5.0.3
using node-gyp@5.0.3
gyp infogyp using  node@10.15.1 | darwin | x64
info using node@10.15.1 | darwin | x64
gyp infogyp ok 
 info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.1 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.1 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gypgyp  infoinfo  spawnspawn /usr/bin/python
 /usr/bin/python
gyp info spawn argsgyp [ '/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp  infoinfo  spawn argsspawn args [ '/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
   'binding.gyp',
gyp gypinfo  spawn args   'binding.gyp',
infogyp  info spawn argsspawn args   '-f',
   '-f',
gyp gypinfo  spawn args   'make',
infogyp  infospawn args spawn args   'make',
   '-I',
gypgyp  infoinfo spawn args    '/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/build/config.gypi',
spawn argsgyp    '-I',
info gypspawn args    '-I',
gypinfo  infospawn args   '/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/build/config.gypi',
 gypspawn args    '/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
infogyp  spawn args   '-I',
infogyp  infospawn args    '-I',
spawn argsgyp    '/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
info gypspawn args   '/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/common.gypi',
 gypinfo info  spawn argsspawn args   '-I',
   '-Dlibrary=shared_library',
gypgyp  infoinfo  spawn argsspawn args   '-Dvisibility=default',
   '/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/common.gypi',
gyp gypinfo  infospawn args    '-Dnode_root_dir=/Users/cesarramos/Library/Caches/node-gyp/10.15.1',
spawn argsgyp   '-Dlibrary=shared_library',
 gypinfo  infospawn args    '-Dnode_gyp_dir=/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp',
spawn argsgyp   '-Dvisibility=default',
 gypinfo  infospawn args    '-Dnode_lib_file=/Users/cesarramos/Library/Caches/node-gyp/10.15.1/<(target_arch)/node.lib',
spawn argsgyp   '-Dnode_root_dir=/Users/cesarramos/Library/Caches/node-gyp/10.15.1',
 gypinfo  infospawn args    '-Dmodule_root_dir=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3',
spawn argsgyp   '-Dnode_gyp_dir=/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp',
 gypinfo  infospawn args    '-Dnode_engine=v8',
spawn argsgyp   '-Dnode_lib_file=/Users/cesarramos/Library/Caches/node-gyp/10.15.1/<(target_arch)/node.lib',
 gypinfo  infospawn args    '--depth=.',
spawn argsgyp   '-Dmodule_root_dir=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3',
 gypinfo  infospawn args    '--no-parallel',
spawn argsgyp   '-Dnode_engine=v8',
 gypinfo  infospawn args    '--generator-output',
spawn argsgyp   '--depth=.',
gyp  infoinfo  spawn argsspawn args   'build',
   '--no-parallel',
gypgyp  infoinfo  spawn argsspawn args   '-Goutput_dir=.' ]
   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.1 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
sed: ./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw: No such file or directory
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/cesarramos/.nvm/versions/node/v10.15.1/bin/node" "/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd /Users/cesarramos/.config/yarn/global/node_modules/sqlite3
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/cesarramos/.nvm/versions/node/v10.15.1/bin/node /Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/cesarramos/.config/yarn/global/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/cesarramos/.nvm/versions/node/v10.15.1/bin/node" "/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/cesarramos/.config/yarn/global/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/cesarramos/.nvm/versions/node/v10.15.1/bin/node /Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64' (1)
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:169:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:162:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/cesarramos/Library/Caches/node-gyp/10.15.1/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/database.cc:144:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:525:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:625:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
8 warnings and 1 error generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/cesarramos/.nvm/versions/node/v10.15.1/bin/node" "/Users/cesarramos/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/cesarramos/.config/yarn/global/node_modules/sqlite3/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd /Users/cesarramos/.config/yarn/global/node_modules/sqlite3
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**System**
- Node.js version: v10.15.1 
- NPM version:
- Strapi version: latest
- Database: sqlite
- Operating system: OSX 10.14.6 (18G103)

**Additional context**
see https://github.com/strapi/strapi/issues/4083

**Comment by lauriejim** [comment]
Hello! How did you installed node?

**Comment by cesarve77** [comment]
I don't remember, it was long time ago

**Comment by cesarve77** [comment]
I tried npx and fail:

```
npx create-strapi-app strapi --quickstart
npx: installed 84 in 4.999s
Creating a new Strapi application at /Users/cesarramos/Documents/projects/test/strapi.

Creating a quickstart project.
Creating files.
Dependencies installed successfully.

Your application was created at /Users/cesarramos/Documents/projects/test/strapi.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode.

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /Users/cesarramos/Documents/projects/test/strapi
  yarn develop


> strapi@0.1.0 build /Users/cesarramos/Documents/projects/test/strapi
> strapi build "--no-optimization"

Missing envrionnment config for env: develoment.
Make sure the directory ./config/environments/develoment exists
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@0.1.0 build: `strapi build "--no-optimization"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cesarramos/.npm/_logs/2019-11-27T21_12_02_295Z-debug.log
```

**Comment by lauriejim** [comment]
Can you make sure you can WRITE files.

the following message mean files havn't been created by Strapi

```
Missing envrionnment config for env: develoment.
Make sure the directory ./config/environments/develoment exists
```

So the issue could come from here.

**Comment by cesarve77** [comment]
this works:

`
sudo npx create-strapi-app strapi --quickstart
`

**Comment by lauriejim** [comment]
Okay so if `sudo` works, it comes from the write access you have with `npm`
