### ISSUE TITLE
strapi build doesn't work in macOS

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4596]
**Describe the bug**

strapi build doesn't work in macOS

```
➜  my-api git:(master) ✗ yarn build
yarn run v1.19.1
$ strapi build
Building your admin UI with development configuration ...
✖ Webpack
  Compiled with some errors in 4.83s
Error: ./.cache/plugins/strapi-plugin-content-type-builder/admin/src/assets/icons/attributes/icon_enumeration.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: spawn /Users/abdonrd/Desktop/my-api/node_modules/optipng-bin/vendor/optipng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at compiler.run (/Users/abdonrd/Desktop/my-api/node_modules/strapi-admin/index.js:191:23)
    at finalCallback (/Users/abdonrd/Desktop/my-api/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/Users/abdonrd/Desktop/my-api/node_modules/webpack/lib/Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/abdonrd/Desktop/my-api/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/Users/abdonrd/Desktop/my-api/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/abdonrd/Desktop/my-api/node_modules/webpack/lib/Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/abdonrd/Desktop/my-api/node_modules/webpack/lib/Compilation.js:1423:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/abdonrd/Desktop/my-api/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/abdonrd/Desktop/my-api/node_modules/webpack/lib/Compilation.js:1414:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Steps to reproduce the behavior**

Just try to build the project.

**Expected behavior**

Build the project.

**System**
- Node.js version: v13
- NPM version: v6
- Strapi version: v3.0.0-beta.17.6
- Database: MongoDB
- Operating system: macOS

**Comment by abdonrd** [comment]
From now, locally, I disable `optipng` from the `image-webpack-loader` (`strapi-admin`).

Changing `optimizationLevel: 4,` to `enabled: false,`.

https://github.com/strapi/strapi/blob/9aff9af165f6dffaec77c71409bbf4e2ee75205e/packages/strapi-admin/webpack.config.js#L169

**Comment by matthewchick** [comment]
I can't see image-webpack-loader (strapi-admin) how to disable optipng
optimizationLevel:4 was already set inside strapi@3.0.0.beta.16.1

**Comment by derrickmehaffy** [comment]
@matthewchick you are quite a few versions behind, I'd recommend updating

**Comment by soupette** [comment]
@alexandrebodin can we close this issue as the webpack config has been updated?

**Comment by abdonrd** [comment]
Yes! The last version works fine on my laptop!
