### ISSUE TITLE
GraphQL fails when relation field is set to private

### ISSUE THREAD

**Issue by nicecatch** [strapi/strapi#4653]
As title, when using the graphql plugin and marking a relation field as private, the server does not start with this error:

```
2019-12-04T16:08:46.404Z] error TypeError: Cannot read property 'replace' of undefined
    at isPrimitiveType (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:23:22)
    at extractType (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:145:10)
    at C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:282:21
    at C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:74:26
    at C:\tests\strapi-final-test\node_modules\lodash\lodash.js:914:11
    at C:\tests\strapi-final-test\node_modules\lodash\lodash.js:4905:15
    at baseForOwn (C:\tests\strapi-final-test\node_modules\lodash\lodash.js:2990:24)
    at C:\tests\strapi-final-test\node_modules\lodash\lodash.js:4874:18
    at baseReduce (C:\tests\strapi-final-test\node_modules\lodash\lodash.js:911:5)
    at Function.reduce (C:\tests\strapi-final-test\node_modules\lodash\lodash.js:9681:14)
    at getFieldsByTypes (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:70:12)
    at generateConnectionFieldsTypes (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:279:27)
    at formatConnectionGroupBy (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:316:19)
    at Object.formatModelConnectionsGQL (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Aggregator.js:486:25)
    at C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Resolvers.js:483:42
    at Array.reduce (<anonymous>)
    at Object.buildShadowCRUD (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Resolvers.js:281:30)
    at Object.generateSchema (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\services\Schema.js:137:36)
    at Object.initialize (C:\tests\strapi-final-test\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:59:50)
    at C:\tests\strapi-final-test\node_modules\strapi\lib\hooks\index.js:43:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**System**
- Node.js version: 12.13.0
- Strapi version: 3.0.0-beta.17.8
- Database: mongodb
- Operating system: windowds 10 x64

**Comment by lauriejim** [comment]
Please can you well format your message with all required information to be able to reproduce and understand your issue, please.
