### ISSUE TITLE
can't install because of proquant

### ISSUE THREAD

**Issue by j2l** [strapi/strapi#4699]
**Describe the bug**
Just tried `npx create-strapi-app my-project --quickstart`
then `cd /my-project` and `npm i`

**Expected behavior**
Clean install

**Code snippets**
```
/my-project# npm i
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size

> pngquant-bin@5.0.2 postinstall /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Command failed: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant --version
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 1: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant:ELF: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 7: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: G@Pu%@G8Pu%��L0Pu%pG(Pu%�%G Pu%P�LPu%GH�H��H��t��H���%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��H��0�R��
                                                                                       �pyR��yR�҃H�� �R��
��                                                                                                      �pyR��yR赃H����R���PyR�0}R蘃H����R��@�R�K�R諹�H��(�S1��V�

f.�f�H�au5H��t���O�H���u�H���:�f.�SA���H�ĀdH�%(H�D$x1�H��H���H�H��D���D$X�?����H����H�T$xdH3%(uH��[���e
AWAVAUATUSH��
�q5H��t�H��녿�D�5q5�V�@0��I���I�Z5H�?Z5H��I���<�Z5H��q5HH��H���VE1�A��5�p5����A��~oE�Ҿt_�A���1�E1�A�A��yD����tH������������u%@��t������%�A��A��A�����
H���H�H��H��E��uE��tL��Mc�H�I��I��L�H�`p5H���1����)��������     ��I���� ��H���� I�����M�����I=�wK�����ǉ�t
�����uFLŁ��v���������o�����y5�����`�������
�Ǹ������L����H�H��I���A��
�E�����1�A��@�ǉ�!�E������A�
                           �<   ������D�΅���D����D�N��ہ������������u�@��t�A��A������C�A�����A��A!��@���I��������%�A���.���L��A���A�����1������@���g���A����A��A�������A��A��A!ڃ���>���A��A���E��~dA��A�BunE���fn5�dn5tdA��D����������������7��&��������H�HHH��H�¸AD�������A��t�1�E�������������r���1�E�����������A��A�������A��A��A!��@���A����!��\����1�I��^H��H���PTI����DH���DH���@g�6��DU��kuH=�]��ku��D]�fD��kuUH���kuH��H��H��H��?H�H��t�H��t
                                               ]��ku��]�fD�=y`5uUH���~�����lOH��t: File name too long
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 1: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: G: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 1: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: �S: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 8: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: �T��5]Ð��@f.��@jOH��tU�: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 9: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: Syntax error: ")" unexpected
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 1: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: Gu�$�=: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 1: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: Gu: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 1: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant:Q�tdR�td: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 1: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: Gu: not found
/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: 2: /mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant: @@h�@8@@@�9�9: not found


  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at /mnt/dietpi_userdata/node-red/my-project/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
npm WARN rollback Rolling back pngquant-bin@5.0.2 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin'
npm WARN rollback Rolling back image-webpack-loader@4.6.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/mnt/dietpi_userdata/node-red/my-project/node_modules/image-webpack-loader/node_modules/pngquant-bin'
npm WARN bookshelf@0.15.1 requires a peer of knex@>=0.13.0 <0.18.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/strapi-admin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-10T21_47_09_701Z-debug.log

```

**System**
- Node.js version: v13.2.0
- NPM version: 6.13.1
- Strapi version: strapi@3.0.0-beta.17.8
- Database: SQLite
- Operating system: Debian

**Additional context**
Attached is npm log file
[2019-12-10T21_47_09_701Z-debug.log](https://github.com/strapi/strapi/files/3947310/2019-12-10T21_47_09_701Z-debug.log)

**Comment by j2l** [comment]
I noticed about libpng-dev and tried `npm i libpng-dev`
got:
```
 npm i libpng-dev
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/libpng-dev - Not found
npm ERR! 404
npm ERR! 404  'libpng-dev@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-10T22_00_10_385Z-debug.log

```
Then I realized that libpng-dev is a debian package, so I run `apt-get install libpng-dev`
proquant installed! I'll test tomorrow.

**Comment by derrickmehaffy** [comment]
Yes you need libpng-dev.

Going to mark this one as closed for now, feel free to reply if we need to reopen.
