### ISSUE TITLE
Strapi don't check if current directory is actually a strapi project

### ISSUE THREAD

**Issue by edimitchel** [strapi/strapi#481]
On requesting start-up of my strapi application, before anything, strapi don't check if the current directory is a strapi project.. 
I type this command in the wrong directory `NODE_ENV=production strapi start`.

A little enhancement may be ?

Here my logs :
```
ERROR (17578 on vps46677): Cannot find module '/opt/config/environments/development/server.json'
    Error: Cannot find module '/opt/config/environments/development/server.json'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Command.module.exports (/usr/lib/node_modules/strapi/bin/strapi-start.js:45:20)
        at Command.listener (/usr/lib/node_modules/strapi/node_modules/commander/index.js:315:8)
        at emitTwo (events.js:126:13)
        at Command.emit (events.js:214:7)
        at Command.parseArgs (/usr/lib/node_modules/strapi/node_modules/commander/index.js:653:12)
        at Command.parse (/usr/lib/node_modules/strapi/node_modules/commander/index.js:475:21)
```

**Comment by lauriejim** [comment]
Hi @edimitchel thank for this issue.
Really low impact on Strapi so it's not in our priority.

**Comment by edimitchel** [comment]
Yes, but I want to let you deliver a perfect solution, so this issue is appropriate ;)

**Comment by lauriejim** [comment]
If you still need it, submit a PR with this little check :)
Will appreciate your contribution !
