### ISSUE TITLE
Error with MySQL in 3.0.0-beta.18.3

### ISSUE THREAD

**Issue by hamzaozturk** [strapi/strapi#4826]
**Describe the bug**
Creating project with database option MySQL with version 3.0.0-beta.18.3.

```
error Bootstrap function in plugin "users-permissions" failed
error TypeError: Cannot read property 'id' of null at permissions.reduce.toKeep
```

**Steps to reproduce the behavior**
1. `yarn create strapi-app my-project`
2. Choose your installation type `Custom (manual settings)`
3. Choose your default database client `mysql`
4. Enter db details
5. cd my-project
6. yarn develop
7. See error

**Expected behavior**
Expected strapi to start

**System**
- Node.js version: v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.3
- Database: MySQL
- Operating system: macOS Catalina 10.15.2

**Comment by hamzaozturk** [comment]
Rows in the table users-permissions_permission with role set to null:

```
userspermissions	updaterole
userspermissions	getemailtemplate
userspermissions	updateemailtemplate
userspermissions	getadvancedsettings
userspermissions	updateadvancedsettings
userspermissions	getproviders
userspermissions	updateproviders
```

**Comment by lauriejim** [comment]
Hello @hamzaozturk !
I just tested your steps and it works well.
📺[Here](https://www.loom.com/share/1649e3676cd641098f3a68f80ea4b715) is a short record of what I did.
Let me know if I missed something.

**Comment by hamzaozturk** [comment]
Hello @lauriejim !
I have just tested it again and it is still not working.
[Here](https://www.loom.com/share/df7ea6774fa04bfc848815d692b7d26c) is a short record.
Let me know if I missed something.

**Comment by Mikeez** [comment]
I am also stuck with this. I believe the problem is your servers MySQL. I do not know how to fix it though...

Mine runs after running npm develop again (yarn develop) but under user-permision for PUBLIC users I do not have Auth settings (as if mysql doesn't add them all)

**Comment by jeliasson** [comment]
@hamzaozturk By any chance you Azure Database for MySQL? If so, we are in the same boat in #5265.

**Comment by objmj-itminds** [comment]
Same issue here.
Strapi version 3.0.0-beta.18.7
Azure Database for MySQL version 8.0.15.

**Comment by VGamezz19** [comment]
same here.

**Comment by derrickmehaffy** [comment]
Can you guys please test again on the latest beta (as of writing beta.19.5)

**Comment by hamzaozturk** [comment]
Still not working.

```
[2020-04-15T09:30:57.449Z] warn The bootstrap function is taking unusually long to execute (3500 miliseconds).
[2020-04-15T09:30:57.458Z] warn Make sure you call it?
[2020-04-15T09:30:58.189Z] error Bootstrap function in plugin "users-permissions" failed
[2020-04-15T09:30:58.189Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/knex/lib/client.js:318:17
    at tryCatcher (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/hamzaozturk/Desktop/strapi/tiyatrobu/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
