### ISSUE TITLE
 updateRelations on mysql save operation does not update relationships and not errors are thrown

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi#4859]
**Describe the bug**
Is there a way to start Strapi with a option of not attempting to alter DB ?

**Steps to reproduce the behavior**
either overriding the api operation or not the relations are not set.

**Expected behavior**
a new record added with all it's relations and if not an error thrown.

**Screenshots**
I wonder if the fact that the api starts with a an error from the migration:
`
2019-12-31T03:25:15.484Z] error Migration failed
[2019-12-31T03:25:15.485Z] error Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'game_id': used in a foreign key constraint 'FK_D7098951E48FD905'
    at Query.Sequence._packetToError (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
    --------------------
    at Protocol._enqueue (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\mysql\lib\Connection.js:201:25)
    at C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\dialects\mysql\index.js:130:18
    at Promise._execute (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\promise.js:103:10)
    at Client_MySQL._query (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\dialects\mysql\index.js:124:12)
    at Client_MySQL.query (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\client.js:158:17)
    at C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\transaction.js:331:24
    at Promise._execute (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\promise.js:103:10)
    at Client_MySQL.trxClient.query (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\transaction.js:326:12)
    at Runner.query (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\runner.js:135:36)
    at Runner.queryArray (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\runner.js:224:14)
    at C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\knex\lib\runner.js:37:25
    at tryCatcher (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Workspaces\Repeat-WKS\repeat_admin\node_modules\bluebird\js\release\promise.js:649:10)
`

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.3.1  
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.18.2 
- Database: mysql
- Operating system: Windows 10

**Additional context**

**Comment by derrickmehaffy** [comment]
`Is there a way to start Strapi with a option of not attempting to alter DB ?` Short answer is no there is not currently. If you are trying to use an existing database I would not recommend it.

**Comment by jmchza** [comment]
I will close this ticket and for other as a conclusion as @derrickmehaffy has suggested too, guys do not use strapi api with an already DB schema as there are lot of enhancements still to be added to the platform to support such a thing.
i.e: issues: 
*  with created_at
* issues with renaming column names 
* issues updating relations, I guess the issue is foreing key that have an index or fk constraint associated are still pending to be added.
