### ISSUE TITLE
I can't access custom field from from users/me via GraphQL

### ISSUE THREAD

**Issue by geosigno** [strapi/strapi#4878]
Hi,

**Describe the bug**
I can't access some data via GraphQL versus simple fetch.

**Steps to reproduce the behavior**
1- Create a new _avatar_ media field on users. 
2- Try to get that avatar via the below GraphQL query:
````graphql
query {
  me {
    username
    avatar {url}
  }
}
````
3)- You'll get the below error:
_"Cannot query field \"avatar\" on type \"UsersPermissionsMe\"."_ with a _GRAPHQL_VALIDATION_FAILED_ code.

**Code snippets**
The below fetch if returning the avatar object:

http://localhost:1337/users/me/

````json
{
    "id": 20,
    "username": "***",
    "email": "***@gmail.com",
    "provider": "local",
    "confirmed": true,
    "blocked": null,
    "created_at": "2019-12-26T19:17:36.847Z",
    "updated_at": "2020-01-01T20:11:46.181Z",
    "avatar": {
        "id": 12,
        "url": "/uploads/8dd5de998ffa4de09fc264c0fab924ab.jpg"
    }
}
````

**System**
- Node.js version: 10.17.0
- NPM version: 6.11.3
- Strapi version: v3.0.0-beta.18.3
- Database: sqlite
- Operating system: macod

**Expected behavior**
I should be able to get the avatar data from GraphQL

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by geosigno** [comment]
@derrickmehaffy I just update the issue template, thank for re-opening it :)

**Comment by lauriejim** [comment]
Thank you for reporting this issue.

The [definition UsersPermissionsMe](https://github.com/strapi/strapi/blob/632bf537ecf624019f2710f6b63dd2a93c6f74f0/packages/strapi-plugin-users-permissions/config/schema.graphql#L22) that is used for the `me` query is static.
We should make it a little bit more dynamic based on the User model structure.

A workaround is to use the [customization concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html#plugin-extensions) to override the `schema.graphql` file of the **Users & Permissions** plugin.

**Comment by geosigno** [comment]
Since I update to the latest version of Strapi, even the simple fetch doesn't return the avatar object.

I read the documentation about the customization concept but there is no `schema.graphql` in the extension folder. Grateful if you could share some hints.

**Comment by theo-stocchetti** [comment]
I think my problem is on relation of this topic.
"users/me" return only custom fields but not relationships, its for this reason avatar (files, images) is not listed.

Auth.callback ("auth/local") return all datas correctly, using the same process for User.me (users/me) without the jwt outpout, this would be the solution ?

**Comment by edeuxk** [comment]
Have the same problem.

**Comment by alhill** [comment]
I don't know if overriding the schema of the plugin works in a different way than overriding controllers or services but pasting `node-modules/strapi-plugin-users-permissions/config/schema.graphql` into `extensions/users-permisions/config` for editing the later one doesn't override it but tries to re-register it

```
[2020-02-07T09:15:41.870Z] error Error: There can be only one type named "UsersPermissionsMe".

Field "UsersPermissionsMe.id" can only be defined once.

Field "UsersPermissionsMe.username" can only be defined once.

Field "UsersPermissionsMe.name" can only be defined once.

Field "UsersPermissionsMe.email" can only be defined once.

Field "UsersPermissionsMe.confirmed" can only be defined once.

Field "UsersPermissionsMe.blocked" can only be defined once.

Field "UsersPermissionsMe.role" can only be defined once.

There can be only one type named "UsersPermissionsMeRole".

Field "UsersPermissionsMeRole.id" can only be defined once.

Field "UsersPermissionsMeRole.name" can only be defined once.

Field "UsersPermissionsMeRole.description" can only be defined once.

Field "UsersPermissionsMeRole.type" can only be defined once.

There can be only one type named "UsersPermissionsLoginInput".

Field "UsersPermissionsLoginInput.identifier" can only be defined once.

Field "UsersPermissionsLoginInput.password" can only be defined once.

Field "UsersPermissionsLoginInput.provider" can only be defined once.

There can be only one type named "UsersPermissionsLoginPayload".

Field "UsersPermissionsLoginPayload.jwt" can only be defined once.

Field "UsersPermissionsLoginPayload.user" can only be defined once.

Field "Query.me" can only be defined once.

Field "Mutation.login" can only be defined once.

Field "Mutation.register" can only be defined once.
    at assertValidSDL (/home/ec2-user/environment/Molecula-dev/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/home/ec2-user/environment/Molecula-dev/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/home/ec2-user/environment/Molecula-dev/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:23:28)
    at makeExecutableSchema (/home/ec2-user/environment/Molecula-dev/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/home/ec2-user/environment/Molecula-dev/node_modules/strapi-plugin-graphql/services/Schema.js:300:22)
    at Object.initialize (/home/ec2-user/environment/Molecula-dev/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
    at Promise.resolve.then (/home/ec2-user/environment/Molecula-dev/node_modules/strapi/lib/hooks/index.js:37:28)
```

But editing the node-modules one doesn't work neither. I have just copied the type UsersPermissionsUser from the autogenerated file `exports/graphql/schema.graphql` into the type UsersPermissionsMe of `node-modules/strapi-plugin-users-permissions/config/schema.graphql` and it doesn't return any error but querying a field which wasn't there (related or not) renders a GraphQL validation error. I suppose this schema is not the one which is being used for the validation...

**Comment by lauriejim** [comment]
Can you please share the content of the `schema.graphql` file.

**Comment by alhill** [comment]
Just one line added, the "name: String" in line 25, but name cannot be queried through the me modek in graphql

```
const _ = require('lodash');
const { ApolloError } = require('apollo-server-koa');

/**
* Throws an ApolloError if context body contains a bad request
* @param contextBody - body of the context object given to the resolver
* @throws ApolloError if the body is a bad request
*/
function checkBadRequest(contextBody) {
  if (_.get(contextBody, 'output.payload.statusCode', 200) !== 200) {
    const statusCode = _.get(contextBody, 'output.payload.statusCode', 400);
    const message = _.get(contextBody, 'output.payload.message', 'Bad Request');
    throw new ApolloError(message, statusCode, _.omit(contextBody, ['output']));
  }
}

module.exports = {
  type: {
    UsersPermissionsPermission: false, // Make this type NOT queriable.
  },
  definition: `
    type UsersPermissionsMe {
      id: ID!
      username: String!
      name: String
      email: String!
      confirmed: Boolean
      blocked: Boolean
      role: UsersPermissionsMeRole
    }

    type UsersPermissionsMeRole {
      id: ID!
      name: String!
      description: String
      type: String
    }

    input UsersPermissionsLoginInput {
      identifier: String!
      password: String!
      provider: String = "local"
    }

    type UsersPermissionsLoginPayload {
      jwt: String!
      user: UsersPermissionsMe!
    }
  `,
  query: `
    me: UsersPermissionsMe
  `,
  mutation: `
    login(input: UsersPermissionsLoginInput!): UsersPermissionsLoginPayload!
    register(input: UserInput!): UsersPermissionsLoginPayload!
  `,
  resolver: {
    Query: {
      me: {
        resolverOf: 'User.me',
        resolver: {
          plugin: 'users-permissions',
          handler: 'User.me',
        },
      },
      role: {
        plugin: 'users-permissions',
        resolverOf: 'UsersPermissions.getRole',
        resolver: async (obj, options, { context }) => {
          context.params = {...context.params, ...options.input};

          await strapi.plugins[
            'users-permissions'
          ].controllers.userspermissions.getRole(context);

          return context.body.role;
        },
      },
      roles: {
        description: `Retrieve all the existing roles. You can't apply filters on this query.`,
        plugin: 'users-permissions',
        resolverOf: 'UsersPermissions.getRoles', // Apply the `getRoles` permissions on the resolver.
        resolver: async (obj, options, { context }) => {
          context.params = {...context.params, ...options.input};

          await strapi.plugins[
            'users-permissions'
          ].controllers.userspermissions.getRoles(context);

          return context.body.roles;
        },
      },
    },
    Mutation: {
      createRole: {
        description: 'Create a new role',
        plugin: 'users-permissions',
        resolverOf: 'UsersPermissions.createRole',
        resolver: async (obj, options, { context }) => {
          await strapi.plugins[
            'users-permissions'
          ].controllers.userspermissions.createRole(context);

          return { ok: true };
        },
      },
      updateRole: {
        description: 'Update an existing role',
        plugin: 'users-permissions',
        resolverOf: 'UsersPermissions.updateRole',
        resolver: async (obj, options, { context }) => {
          await strapi.plugins[
            'users-permissions'
          ].controllers.userspermissions.updateRole(
            context.params,
            context.body
          );

          return { ok: true };
        },
      },
      deleteRole: {
        description: 'Delete an existing role',
        plugin: 'users-permissions',
        resolverOf: 'UsersPermissions.deleteRole',
        resolver: async (obj, options, { context }) => {
          await strapi.plugins[
            'users-permissions'
          ].controllers.userspermissions.deleteRole(context);

          return { ok: true };
        },
      },
      createUser: {
        description: 'Create a new user',
        plugin: 'users-permissions',
        resolverOf: 'User.create',
        resolver: async (obj, options, { context }) => {
          context.params = _.toPlainObject(options.input.where);
          context.request.body = _.toPlainObject(options.input.data);

          await strapi.plugins['users-permissions'].controllers.user.create(
            context
          );

          return {
            user: context.body.toJSON ? context.body.toJSON() : context.body,
          };
        },
      },
      updateUser: {
        description: 'Update an existing user',
        plugin: 'users-permissions',
        resolverOf: 'User.update',
        resolver: async (obj, options, { context }) => {
          context.params = _.toPlainObject(options.input.where);
          context.request.body = _.toPlainObject(options.input.data);

          await strapi.plugins['users-permissions'].controllers.user.update(
            context
          );

          return {
            user: context.body.toJSON ? context.body.toJSON() : context.body,
          };
        },
      },
      deleteUser: {
        description: 'Delete an existing user',
        plugin: 'users-permissions',
        resolverOf: 'User.destroy',
        resolver: async (obj, options, { context }) => {
          // Set parameters to context.
          context.params = _.toPlainObject(options.input.where);
          context.request.body = _.toPlainObject(options.input.data);

          // Retrieve user to be able to return it because
          // Bookshelf doesn't return the row once deleted.
          await strapi.plugins['users-permissions'].controllers.user.findOne(
            context
          );
          // Assign result to user.
          const user = context.body.toJSON
            ? context.body.toJSON()
            : context.body;

          // Run destroy query.
          await strapi.plugins['users-permissions'].controllers.user.destroy(
            context
          );

          return {
            user,
          };
        }
      },
      register: {
        description: 'Register a user',
        plugin: 'users-permissions',
        resolverOf: 'Auth.register',
        resolver: async (obj, options, {context}) => {
          context.request.body = _.toPlainObject(options.input);

          await strapi.plugins['users-permissions'].controllers.auth.register(context);
          let output = context.body.toJSON ? context.body.toJSON() : context.body;

          checkBadRequest(output);
          return {
            user: output.user || output, jwt: output.jwt
          };
        }
      },
      login: {
        resolverOf: 'Auth.callback',
        plugin: 'users-permissions',
        resolver: async (obj, options, {context}) => {
          context.params = {...context.params, provider: options.input.provider};
          context.request.body = _.toPlainObject(options.input);

          await strapi.plugins['users-permissions'].controllers.auth.callback(context);
          let output = context.body.toJSON ? context.body.toJSON() : context.body;

          checkBadRequest(output);
          return {
            user: output.user || output, jwt: output.jwt
          };
        }
      }
    }
  }
};

```

**Comment by lauriejim** [comment]
Hello! You don't need to copy the entire file.

```js
module.exports = {
  definition: `
    extend type UsersPermissionsMe {
      name: String
    }
  `
}
```

**Comment by matepaiva** [comment]
Thanks for your comment @lauriejim, really helpful!

**Comment by alhill** [comment]
Now I reached the other problem, it works with plain fields but it just returns null with relationships

With this schema in `extensions/users-permisions/config`...
```
module.exports = {
  definition: `
    extend type UsersPermissionsMe {
      name: String
      comments(sort: String, limit: Int, start: Int, where: JSON): [Comment]
    }
  `
}
```

... and this query ...
```
{
    me{
        name
        messages{
            _id
        }
    }
}
```

... I'm getting this response
```
{
    "data": {
        "me": {
            "name": "Mig",
            "messages": null
        }
    }
}
```

**Comment by lauriejim** [comment]
You also have to add `messages` in your extension.

**Comment by alhill** [comment]
My fault, I copied it wrong but the code was well, I have edited the post.

**Comment by lauriejim** [comment]
Ho yes I confirm!

**Comment by geosigno** [comment]
Same for me.

extensions/users-permisions/config/schema.graphql
`````
module.exports = {
  definition: `
    extend type UsersPermissionsMe {
      avatar: UploadFile
    }
  `
}
`````
the query
````
# Write your query or mutation here
query {
  me {
    username
    email
    avatar {
      url
    }
  }
}
````

the result
`````
{
  "data": {
    "me": {
      "username": "geo",
      "email": "email@.com",
      "avatar": null
    }
  }
}
````

any workaround to get to get that value?

**Comment by unolee** [comment]
@geosigno Same for me.

**Comment by unolee** [comment]
@geosigno Same for me. 
@lauriejim 

`query{
  me {
    id
    username
    user_info {
        name
        birthday
    }
    user_status {
        securityLevel
    }
  }
}`

`
{
    "data": {
        "me": {
            "id": "1",
            "username": "ImUser1",
            "user_info": {
                "name": null,
                "birthday": null
            },
            "user_status": {
                "securityLevel": null
            }
        }
    }
}
`

I am also trying another way, but it doesn't work for me.
https://github.com/strapi/strapi/issues/2627

**Comment by unolee** [comment]
I solved this issue with #2627 and below query is working well.

    query{

    me {
        id
        username
    }
    self {
        user_info {
            name
            birthday
        }
        user_status {
            securityLevel
        }
    }

    }

**Comment by remi2j** [comment]
I'm commenting here since #2627 is locked, and both issues are very related. I had to make a few adjustments to the fix mentioned by @unolee 

I wanted to query relationship linked to the authenticated user. I created a file named `extensions/users-permissions/config/schema.graphql.js` with this content:

```js
module.exports = {
  query: `
    self: UsersPermissionsUser
  `,
  resolver: {
    Query: {
      self: {
        resolver: 'plugins::users-permissions.user.me'
      },
    },
  }
};
```

Custom fields are now working fine, if you replace `me` by `self` in your queries.

**Comment by mbernwieser** [comment]
@remi2j 

As @lauriejim said in https://github.com/strapi/strapi/issues/2627#issuecomment-568257332 you shouldn't use `self: UsersPermissionsUser` here out of security reasons.

Instead create a further Type with restricted fields, e.g.: 

```
  definition: `
    type Self {
      id: ID
      username: String
      email: String
      additionalField1: String
      additionalField2: String
      ...
    }
  `,
  query: `
      self: Self
  `,
  resolver: {
      Query: {
          self: {
              resolver: 'plugins::users-permissions.user.me'
          },
      },
  }
```

Or extend UsersPermissionsMe as seen in: https://github.com/strapi/strapi/issues/4878#issuecomment-584106410

**Comment by geosigno** [comment]
I confirm the workaround by replacing _me_ with _self_ is working fine.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-cant-access-custom-fields-from-users-me-via-graphql/13744/1

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/get-all-items-related-to-user/14159/1

**Comment by derrickmehaffy** [comment]
should be fixed in v4 I believe
