### ISSUE TITLE
Problem Deploying to Heroku error ConnectorError: connector "strapi-hook-bookshelf" not found: Cannot find module 'strapi-connector-strapi-hook-bookshelf'

### ISSUE THREAD

**Issue by scullabyte** [strapi/strapi#4953]
**Describe the bug**
I am getting this weird error for `'strapi-connector-strapi-hook-bookshelf'`, inside heroku when running `heroku logs --t` after deploy. I cannot find   `strapi-connector-strapi-hook-bookshelf` anywhere running an `ack` search in `node_modules`, nor does it exist anywhere on google or in this repo. I'm assuming somewhere it is conflating two package names? 

**Steps to reproduce the behavior**
1. Follow all steps here: https://strapi.io/blog/building-a-static-website-using-gatsby-and-strapi

**Expected behavior**
Deploy and work on heroku the same as it does locally

**Code snippets**
```2020-01-08T23:09:11.581424+00:00 app[web.1]: [2020-01-08T23:09:11.580Z] debug ⛔️ Server wasn't able to start properly.
2020-01-08T23:09:11.582314+00:00 app[web.1]: [2020-01-08T23:09:11.582Z] error ConnectorError: connector "strapi-hook-bookshelf" not found: Cannot find module 'strapi-connector-strapi-hook-bookshelf'
2020-01-08T23:09:11.582316+00:00 app[web.1]: at requireConnector (/app/node_modules/strapi-database/lib/require-connector.js:21:11)
2020-01-08T23:09:11.582318+00:00 app[web.1]: at DatabaseManager.initialize (/app/node_modules/strapi-database/lib/database-manager.js:35:25)
2020-01-08T23:09:11.582320+00:00 app[web.1]: at Strapi.load (/app/node_modules/strapi/lib/Strapi.js:362:19)
2020-01-08T23:09:11.582321+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2020-01-08T23:09:11.594341+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-01-08T23:09:11.594721+00:00 app[web.1]: npm ERR! errno 1
2020-01-08T23:09:11.595968+00:00 app[web.1]: npm ERR! trancend-cms@0.1.4 start: `strapi start`
2020-01-08T23:09:11.596081+00:00 app[web.1]: npm ERR! Exit status 1
2020-01-08T23:09:11.596326+00:00 app[web.1]: npm ERR!
2020-01-08T23:09:11.596479+00:00 app[web.1]: npm ERR! Failed at the trancend-cms@0.1.4 start script.
2020-01-08T23:09:11.596590+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-01-08T23:09:11.602024+00:00 app[web.1]:
2020-01-08T23:09:11.602213+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-01-08T23:09:11.602303+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-01-08T23_09_11_597Z-debug.log
2020-01-08T23:09:11.656826+00:00 heroku[web.1]: State changed from starting to crashed```


**System**
- Node.js version: 10.15.2
- NPM version: 6.13.2
- Strapi version: 3.0.0-beta.18.4
- Database: postgres
- Operating system: OSX10.15

**Comment by scullabyte** [comment]
I just ran through this tutorial:
https://strapi.io/documentation/3.0.0-alpha.x/guides/deployment.html#heroku

Everything worked. I'm assuming the problem was with using yarn on a couple of installs along the way.

**Comment by jojoucsd** [comment]
I also run into the same problem. Following the Strapi and Gatsby tutorial guide as well. Any updates ?

**Comment by derrickmehaffy** [comment]
@scullabyte @jojoucsd that link is for the Alpha docs, you need to use the beta docs: https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku

**Comment by jojoucsd** [comment]
got it! Thanks for reply

**Comment by ngoclammevn** [comment]
In my case 
- The problem comes from the Nodejs package
So I upgrade the package strapi in file `package.json`
- Change package `strapi-hook-bookshelf` -> `strapi-connector-bookshelf`
Because package `strapi-hook-bookshelf` has been deprecated
Also change `"connector": "strapi-hook-bookshelf" `->  `"connector": "bookshelf"` in config strapi
