### ISSUE TITLE
Migration failed after upgrade to beta.18.4

### ISSUE THREAD

**Issue by adrienharnay** [strapi/strapi#5011]
**Describe the bug**

After upgrading to beta.18.4, when starting the server, this message appears:

```
[2020-01-17T09:52:39.224Z] error Migration failed
[2020-01-17T09:52:39.225Z] error error: operator class "gin_trgm_ops" does not accept data type numeric
    at Connection.parseE (/fakepath/node_modules/pg/lib/connection.js:606:13)
    at Connection.parseMessage (/fakepath/node_modules/pg/lib/connection.js:403:19)
    at TLSSocket.<anonymous> (/fakepath/node_modules/pg/lib/connection.js:123:22)
    at TLSSocket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:181:23)
```

When adding `console.log(fields);` to pg/lib/connection.js, l.603, I get this before the above error:

```
{
  S: 'ERROR',
  V: 'ERROR',
  C: '42704',
  M: 'constraint "upload_file_size_unique" of relation "upload_file" does not exist',
  F: 'tablecmds.c',
  L: '8576',
  R: 'ATExecDropConstraint'
}
{
  S: 'ERROR',
  V: 'ERROR',
  C: '42704',
  M: 'constraint "upload_file_updated_at_unique" of relation "upload_file" does not exist',
  F: 'tablecmds.c',
  L: '8576',
  R: 'ATExecDropConstraint'
}
{
  S: 'ERROR',
  V: 'ERROR',
  C: '42704',
  M: 'constraint "upload_file_created_at_unique" of relation "upload_file" does not exist',
  F: 'tablecmds.c',
  L: '8576',
  R: 'ATExecDropConstraint'
}
{
  S: 'ERROR',
  V: 'ERROR',
  C: '42804',
  M: 'operator class "gin_trgm_ops" does not accept data type numeric',
  F: 'indexcmds.c',
  L: '1392',
  R: 'ResolveOpClass'
}
```

**Steps to reproduce the behavior**
1. Create a project with strapi@3.0.0-beta.18.3, create a DB and initiate it
2. Upgrade to 3.0.0-beta.18.4
3. Run

**Expected behavior**
No error

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.4
- Database: postgresql
- Operating system: MacOS

Thanks in advance!

**Comment by lauriejim** [comment]
Hello! I just tried to reproduce your steps and it works well.
Here is what I did - https://www.loom.com/share/bf0bec6fb1674efdbf4734af42b898bc
Let me know if I missed something.

**Comment by ScottAgirs** [comment]
I have a very similar or the same issue. I will try to create a clean project with reproduction. If there is anything specific that can help, please make it known ✌️

**Comment by avdkishore** [comment]
This issue still persists in the latest build 3.0.0-beta.18.6.

**Comment by adrienharnay** [comment]
Hey, just found the culprit and how to fix it:
- it seems with the last upgrade, a migration tries to change the `size` column of the `upload_file` table from a string to an int. But there is a GIN index linked to that column, and a GIN index can only be linked to a string. Removing the GIN index fixes the error.

**Comment by lauriejim** [comment]
Thank you @adrienharnay for highlighting this point.
Here is the info in the migration guide - https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#file-model

**Comment by cawoodm** [comment]
The migration guide does not mention "GIN" indexes but says to `DROP INDEX SEARCH_UPLOAD_FILE ON upload_file;`
We have already done this and are still getting the error:

```
[2020-08-04T07:07:38.076Z] error Migration failed
[2020-08-04T07:07:38.077Z] error error: alter table "upload_file" alter column "size" type decimal(10, 2) using ("size"::decimal(10, 2)) - operator class "gin_trgm_ops" does not accept data type numeric
    at Connection.parseE (D:\services\strapi\node_modules\pg\lib\connection.js:614:13)
    at Connection.parseMessage (D:\services\strapi\node_modules\pg\lib\connection.js:413:19)
    at Socket.<anonymous> (D:\services\strapi\node_modules\pg\lib\connection.js:129:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by lauriejim** [comment]
Hello, please can you please create a new issue and fill out the issue template to let us know everything about your application.
