### ISSUE TITLE
GraphQL does not pull single Role using MongoDB

### ISSUE THREAD

**Issue by wdhodges** [strapi/strapi#5013]
**Describe the bug**
When using GraphQL, you are not able to pull a single Role by ID.

**Steps to reproduce the behavior**
Run the following in http://localhost:1337/graphql:

```
query {
  role(id: "5e1e5392793daa2610f139d8") {
    name
    description
  }
}
```

You get the following error: 

```
"message": "Cannot destructure property 'id' of 'ctx.params' as it is undefined.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "role"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
```

Here is the stack trace directly: 
```
"TypeError: Cannot destructure property 'id' of 'ctx.params' as it is undefined.",
            "    at Object.getRole (c:\\projects\\projectName\\node_modules\\strapi-plugin-users-permissions\\controllers\\UsersPermissions.js:102:13)",
            "    at resolver (c:\\projects\\projectName\\node_modules\\strapi-plugin-users-permissions\\config\\schema.graphql:71:42)",
            "    at c:\\projects\\projectName\\node_modules\\strapi-plugin-graphql\\services\\Query.js:300:25",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

**Expected behavior**
Return the role back to you with specified information.

**System**
- Node.js version: v13.5
- NPM version: 6.13.6
- Strapi version: v3.0.0-beta.18.4
- Database: Mongo
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
I created a PR to fix it.
