### ISSUE TITLE
An internal server error occurred.

### ISSUE THREAD

**Issue by smachs** [strapi/strapi#505]
**Node.js version**: 8.0.0
**npm version**: 5.0.0
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Ubuntu 16.04 LTS

My connection with mongodb is flowing normally but when I try to do some post or query I get these errors:

`DEBUG (28854 on electron-smachs): GET /employeefunction (116 ms)
DEBUG (28854 on electron-smachs): GET /favicon.ico (25 ms)
ERROR (28854 on electron-smachs): Cannot read property 'add' of undefined
    TypeError: Cannot read property 'add' of undefined
        at create (/home/electron-smachs/famagas-production-release/api/test-api-v1/api/employeefunction/controllers/EmployeeFunction.js:44:56)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:43:18)
        at module.exports (/home/electron-smachs/famagas-production-release/api/test-api-v1/plugins/users-permissions/config/policies/permissions.js:44:11)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:43:18)
        at /home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:29:11
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
        at /home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:34:12
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
        at validator (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router-joi/joi-router.js:327:38)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
DEBUG (28854 on electron-smachs): POST /employeefunction (445 ms)
ERROR (28854 on electron-smachs): Cannot read property 'fetchAll' of undefined
    TypeError: Cannot read property 'fetchAll' of undefined
        at find (/home/electron-smachs/famagas-production-release/api/test-api-v1/api/employeefunction/controllers/EmployeeFunction.js:18:56)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:43:18)
        at module.exports (/home/electron-smachs/famagas-production-release/api/test-api-v1/plugins/users-permissions/config/policies/permissions.js:44:11)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:43:18)
        at /home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:29:11
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
        at /home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-compose/index.js:34:12
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
        at validator (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router-joi/joi-router.js:327:38)
        at dispatch (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
        at next (/home/electron-smachs/.nvm/versions/node/v8.0.0/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
DEBUG (28854 on electron-smachs): GET /employeefunction (150 ms)`

Thanks for helping me!

**Comment by lauriejim** [comment]
I think it's this issue https://github.com/strapi/strapi/issues/328 ?
Can you try with a content type without space or camelcase ?

**Comment by smachs** [comment]
@lauriejim WOW Resolved! Many thanks, I'm sorry if this question sounded like a newbie, I'm still learning to manipulate the Strapi, great work, continue like this!!
