### ISSUE TITLE
Silent save fail + workaround

### ISSUE THREAD

**Issue by virgil9306** [strapi/strapi#5070]
**Describe the bug**

Saving `Content Type` fails silently. Restarting the server displays the `Content Type` in `Content Type Builder`. Clicking on the `Content Type` inside `Content Types` will result in error:

```
error TypeError: Cannot read property 'uid' of undefined
    at Object.getComponentsSchemas (/Users/user/projectfolder/node_modules/strapi-plugin-content-manager/services/Components.js:39:40)
    at Object.getComponentInformations (/Users/user/projectfolder/node_modules/strapi-plugin-content-manager/services/Components.js:24:30)
    at async Object.getComponentsSchemas (/Users/user/projectfolder/node_modules/strapi-plugin-content-manager/services/Components.js:59:45)
    at async Object.findContentType (/Users/user/projectfolder/node_modules/strapi-plugin-content-manager/controllers/ContentTypes.js:53:19)
    at async /Users/user/projectfolder/strapi/lib/middlewares/router/utils/routerChecker.js:83:22
    at async module.exports (/Users/user/projectfolder/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:40:14)
    at async /Users/user/projectfolder/node_modules/strapi-utils/lib/policy.js:118:7
```

**Steps to reproduce the behavior**
1. Run `npm run strapi start` or `npm run strapi dev` or `npm start` with fresh, vanilla Strapi
2. Click `Content Type Builder` -> `Create new content-type`
3. Click save -- server does not warn of restart
4. Nothing displays, so Ctrl+C to shut down server
5. Start up server again, log into Admin panel, and click on the Content Type on the top left under `Content Types`. Error message will display.

**Expected behavior**

Clicking `Save` will save, update UI, and consequently work.

**How did I resolve issue**

Something seems to have gone wrong with the Content Type or Component that I created before encountering this bug. Deleting that Content Type **and everything that I used it with** seems to have resolved this issue -- very unfortunate as I lost some work doing this. 

Could it be lack of checks on creating a Content Type or Component that results in creating bad data which will make the system hang, thus failing when a Ctrl+C + restart is done?

**System**
- Node.js version: LTS
- NPM version: 6.x?
- Strapi version: Latest
- Database: whatever the default Strapi tutorial is running with
- Operating system: OSX (latest)

**Comment by lauriejim** [comment]
Hello @virgil9306 ! Thank you for this issue (well defined, thanks)
Here is the same issue - https://github.com/strapi/strapi/issues/5038

**Comment by virgil9306** [comment]
Excellent, thanks @lauriejim . Definitely need to work on the UI/UX for this as it's very prone to misuse. If I have time I will look into a PR but for the time being I will use as intended.

**Comment by virgil9306** [comment]
Forgot to mention that part of this bug was upon server restart, the new Content Types were created BUT the database was corrupted somehow, forcing me to delete a lot of stuff and losing work. Maybe that needs to be looked into as well, so perhaps this covers aspects that #5038 does not?

**Comment by Jaikant** [comment]
I had the same issue, the problem came, when I created a component using the GUI. I then deleted the component from the GUI. But could not delete it completely. So from the cli I deleted the json files. But, I forgot that I had attached the component to a collection. Hence was getting the error. I then deleted the entry of the component from the collection and the error dissapeared.

**Comment by michaelstokes** [comment]
Hello, 

I'm currently experiencing a similar issue and it seems following adding uid type columns to my tables. The reason for the addition was that I can generate a uid value such that I can reference a `person` via uid as opposed to id.

Regardless I'm experiencing the issue when deploying to heroku and the application works as expected in development.

Please see the following error message:

```
2020-08-04T18:30:34.350683+00:00 heroku[web.1]: Starting process with command `npm start`
2020-08-04T18:30:38.000000+00:00 app[api]: Build succeeded
2020-08-04T18:30:38.990717+00:00 app[web.1]: 
2020-08-04T18:30:38.990739+00:00 app[web.1]: > backend@0.1.0 start /app
2020-08-04T18:30:38.990740+00:00 app[web.1]: > strapi start
2020-08-04T18:30:38.990740+00:00 app[web.1]: 
2020-08-04T18:30:41.985919+00:00 app[web.1]: [2020-08-04T18:30:41.985Z] error Bootstrap function in plugin "content-manager" failed
2020-08-04T18:30:41.986596+00:00 app[web.1]: [2020-08-04T18:30:41.986Z] error TypeError: Cannot read property 'uid' of undefined
2020-08-04T18:30:41.986596+00:00 app[web.1]: at toUID (/app/node_modules/strapi-plugin-content-manager/services/ContentTypes.js:15:16)
2020-08-04T18:30:41.986598+00:00 app[web.1]: at formatAttribute (/app/node_modules/strapi-plugin-content-manager/services/ContentTypes.js:95:49)
2020-08-04T18:30:41.986598+00:00 app[web.1]: at /app/node_modules/strapi-plugin-content-manager/services/ContentTypes.js:70:16
2020-08-04T18:30:41.986599+00:00 app[web.1]: at Array.reduce (<anonymous>)
2020-08-04T18:30:41.986599+00:00 app[web.1]: at formatAttributes (/app/node_modules/strapi-plugin-content-manager/services/ContentTypes.js:69:40)
2020-08-04T18:30:41.986600+00:00 app[web.1]: at formatContentTypeSchema (/app/node_modules/strapi-plugin-content-manager/services/ContentTypes.js:108:10)
2020-08-04T18:30:41.986600+00:00 app[web.1]: at createDefaultConfiguration (/app/node_modules/strapi-plugin-content-manager/services/utils/configuration/index.js:26:18)
2020-08-04T18:30:41.986600+00:00 app[web.1]: at generateNewConfiguration (/app/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:49:13)
2020-08-04T18:30:41.986600+00:00 app[web.1]: at /app/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:67:34
2020-08-04T18:30:41.986601+00:00 app[web.1]: at Array.map (<anonymous>)
2020-08-04T18:30:41.986601+00:00 app[web.1]: at updateContentTypes (/app/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:67:23)
2020-08-04T18:30:41.986601+00:00 app[web.1]: at async syncContentTypesSchemas (/app/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:33:3)
2020-08-04T18:30:41.986602+00:00 app[web.1]: at async syncSchemas (/app/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:21:3)
2020-08-04T18:30:41.986602+00:00 app[web.1]: at async execBootstrap (/app/node_modules/strapi/lib/Strapi.js:394:9)
2020-08-04T18:30:41.986603+00:00 app[web.1]: at async Promise.all (index 0)
2020-08-04T18:30:41.986603+00:00 app[web.1]: at async Strapi.runBootstrapFunctions (/app/node_modules/strapi/lib/Strapi.js:408:5)
2020-08-04T18:30:41.998510+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-08-04T18:30:41.998775+00:00 app[web.1]: npm ERR! errno 1
2020-08-04T18:30:42.001054+00:00 app[web.1]: npm ERR! backend@0.1.0 start: `strapi start`
2020-08-04T18:30:42.001146+00:00 app[web.1]: npm ERR! Exit status 1
2020-08-04T18:30:42.001244+00:00 app[web.1]: npm ERR!
2020-08-04T18:30:42.001320+00:00 app[web.1]: npm ERR! Failed at the backend@0.1.0 start script.
2020-08-04T18:30:42.001387+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-08-04T18:30:42.009407+00:00 app[web.1]: 
2020-08-04T18:30:42.009559+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-08-04T18:30:42.009641+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-08-04T18_30_42_002Z-debug.log
2020-08-04T18:30:42.064685+00:00 heroku[web.1]: Process exited with status 1
2020-08-04T18:30:42.093924+00:00 heroku[web.1]: State changed from starting to crashed
```

Thanks so much,

Michael

**Comment by derrickmehaffy** [comment]
@michaelstokes can you please open up a new issue or discussion so we can have a clean place to try and debug the issue.

Thank you
