### ISSUE TITLE
Babel error when building Admin Panel.

### ISSUE THREAD

**Issue by Aaditya-Sahay** [strapi/strapi#5082]
**Describe the bug**

*The admin panel fails to build*

I first noticed the bug when upgrading ``strapi-admin": "3.0.0-beta.18.3"`` to ``strapi-admin": "3.0.0-beta.18.4"`` , coincidentally babel had released their version 7.8.0 the previous day (11 Jan 2020).

The issue still persists in beta.18.6  version of strapi.

I removed .cache folder  as suggested in the docs and retried the build which failed again.
I then did a fresh install of strapi in a different directory and faced the same issue (console output below).

```
> strapi build
Building your admin UI with development configuration ...

✖ Webpack
  Compiled with some errors in 606.56ms

Error: ./.cache/admin/src/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Package exports for '/Users/aadityasahay/Documents/code/test/cmstest/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
    at applyExports (internal/modules/cjs/loader.js:485:15)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at /Users/aadityasahay/Documents/code/test/cmstest/node_modules/strapi-admin/index.js:191:23
    at finalCallback (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/aadityasahay/Documents/code/test/cmstest/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/aadityasahay/Documents/code/test/cmstest/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/aadityasahay/Documents/code/test/cmstest/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/aadityasahay/Documents/code/test/cmstest/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aadityasahay/Documents/code/test/cmstest/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/aadityasahay/Documents/code/test/cmstest/node_modules/webpack/lib/Compilation.js:1414:32
```

**Steps to reproduce the behavior**
1. Create new strapi application.
```console
npx create-strapi-app test
```
2. Build the admin panel.
```console
npm run build
```
additionally --quickstart flag will build the admin panel for you and fails as well. 
```console
npx create-strapi-app test --quickstart
```
3. See error

**Expected behavior**
The Admin panel should build successfully.

**System**
- Node.js version: v13.1.0
- NPM version:  6.13.3
- Strapi version: 3.0.0-beta.18.6
- Database: MongoDB
- Operating system: macOS catalina (v10.15.2)

**Additional context**
Making sure babel v7.7.0 and not 7.8.0 was installed, and then running build had fixed the issue last time. I have no validation for this claim right now though, will be attempting to do it later and post an update.

**Comment by derrickmehaffy** [comment]
`Node.js version: v13.1.0` - Node v13 is not supported only v10/12
`Strapi version: 3.0.0-beta.18.6` - Can you please try testing again on the latest beta? (beta.19.5)

**Comment by Aaditya-Sahay** [comment]
The latest beta resolves the issue.
