### ISSUE TITLE
Component with field `ID` crashes

### ISSUE THREAD

**Issue by creslinux** [strapi/strapi#5087]
When creating a component with a number field named 'id' as integer the system errors.
The system cannot be restarted after this. 

The workaround is to find the model under `components/' and remove the offending json file. 

**Steps to reproduce the behavior**
> content builder
> new component
> Add another field, name "id" numeric "integer"

> shutdown strapi
> start strapi 

Error prevents startup: 
```
yarn run v1.21.1
$ strapi start
[2020-01-24T16:46:27.643Z] error Impossible to register the 'field1.field' model.
[2020-01-24T16:46:27.643Z] error error: column "id" specified more than once
    at Connection.parseE (/idc/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/idc/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/idc/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Client_PG._query (/idc/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/idc/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/idc/node_modules/knex/lib/runner.js:135:36)
    at Runner.queryArray (/idc/node_modules/knex/lib/runner.js:224:14)
    at /idc/node_modules/knex/lib/runner.js:37:25
From previous event:
    at Runner.run (/idc/node_modules/knex/lib/runner.js:25:16)
    at SchemaBuilder.Target.then (/idc/node_modules/knex/lib/interface.js:14:43)
error Command failed with exit code 1.
```
**Expected behavior**
A field name that will conflict is not allowed to be added to the GUI, the user informed of error.
No offending json files will be created into components/ directory
The system will start 

** System 
3.0.0-beta.18.6 (node v10.18.1) 

**Additional context**
Workaround is to head into components/ dir find the form file and edit out the offending json.
This is problematic in a microservice as the filesystem is not accessible.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue! 

We will fix this soon as possible.

**Comment by aminimalanimal** [comment]
I would like to query data by an ID that I specify. Is it possible to fix this so that adding an ID field to the Content Type allows users to override the default generated ID?

**Comment by doftorul** [comment]
+1 on the ability to add custom ID fields that can be also used in the relationships between components as the anchor

**Comment by lauriejim** [comment]
This issue has been fixed in the stable version of Strapi.
