### ISSUE TITLE
Error plugin in development setup

### ISSUE THREAD

**Issue by lucasdu4rte** [strapi/strapi#511]
**Node.js version**: v9.4.0
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.8
**Operating system**: Ubuntu 17.10

Hello, I'm trying a plugin for the strapi following the documentation, but there was a problem saying that you miss the strapi-admin module.

```
lucas@lucas-notebook:~/apps/myDevelopmentProject/admin$ sudo npm start

> strapi-admin@3.0.0-alpha.8 start /usr/local/lib/node_modules/strapi/node_modules/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server

module.js:557
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/strapi/node_modules/strapi-admin/node_modules/strapi-helper-plugin/node_modules/.bin/cross-env'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.8 start: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucas/.npm/_logs/2018-01-24T16_21_44_265Z-debug.log

```

Should I install manually? Or is the step by step outdated?

**Comment by soupette** [comment]
Hello! It looks like the `strapi-helper-plugin` is not linked correctly...

Could you run `cd myDevelopmentProject/admin && npm link strapi-helper-plugin`and see if the problem still occurs?

**Comment by lucasdu4rte** [comment]
thaks my friend `npm link strapi-helper-plugin` it's work!

but there is still a problem
```
> strapi-admin@3.0.0-alpha.8 start /usr/local/lib/node_modules/strapi/node_modules/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server


Strapi plugin succesfully started in development mode. ✓

-----------------------------------
Access URL: http://localhost:4000
-----------------------------------
Press CTRL-C to stop
    
(node:26904) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack built 6084a2aada7a15f72c3f in 10623ms
```

after I start the server, access the `localhost:4000` link, but returns this gigantic error
[error.txt](https://github.com/strapi/strapi/files/1662320/error.txt)

**Comment by soupette** [comment]
Did you generate your project with `strapi new myDevelopmentProject --dev` ?

**Comment by lucasdu4rte** [comment]
@soupette 
Yes, as it is in the documentation.
I did everything the same as the documentation, just to see if it was the complexity

**Comment by soupette** [comment]
Just to make sure you cloned the repository and and did `npm run setup` in the it?

**Comment by lauriejim** [comment]
Hi @lucasdu4rte can you give us an update about this issue please

**Comment by derrickmehaffy** [comment]
I too seem to be having this issue. I may be reading the docs wrong but there doens't seem to be a clear setup process for working the development environment. (I would recommend a more detailed guide be made in the future as it seems the https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md may be slightly out of date)

Something that might be causing general confusion is why is there a need to remove the strapi npm packages: 
```
Note: If the installation failed, please remove the global packages related to Strapi. The command npm ls strapi will help you to find where your packages are installed globally.
```

As by default the globally installed packages also allow you to create development projects, in my example using strapi v3.0.0-alpha.10.2.

![screenshot from 2018-02-25 08-08-45](https://user-images.githubusercontent.com/8593673/36643014-88783202-1a03-11e8-9d7b-110c26213548.png)

**Comment by derrickmehaffy** [comment]
It does seem however that the --dev is creating the wrong symlinks: 

![screenshot from 2018-02-25 08-14-43](https://user-images.githubusercontent.com/8593673/36643069-05edbd38-1a04-11e8-8465-ea05ecd30acb.png)

As those files/directories don't exist:

![screenshot from 2018-02-25 08-16-23](https://user-images.githubusercontent.com/8593673/36643091-3105f62a-1a04-11e8-8bce-e1d0a71115c2.png)

**Comment by lauriejim** [comment]
@derrickmehaffy Impossible to reproduce your issue...where are stored your Strapi node module when you make a `npm run setup` ?

**Comment by lauriejim** [comment]
Hey guys some news about this issue ?

**Comment by wsalazar-peakactivity** [comment]
Any resolution on this? 3.0.0-alpha.14 and I'm still getting this. Not sure why this issue was closed.

**Comment by derrickmehaffy** [comment]
@wsalazar-peakactivity If no one responds with updated information on how to reproduce the issue is closed. Also the current version is v14.4. If you can test on the latest and provided detailed step by step instructions to reproduce the issue, then I'm sure it can be reopened.

**Comment by greatwitenorth** [comment]
I'm seeing the same issue with incorrect symlinks. Here's the exact steps:

```
cd Projects
strapi new strapi-dev --dev
# filled in mysql db info
cd strapi-dev
strapi start
```

I then see the following error message:

```
strapi start                                                                                                                                            12:57:06
error ENOENT: no such file or directory, stat '/Users/nickv/Projects/strapi-dev/plugins/content-manager'
```

```
cd plugins
ls -la

total 0
drwxr-xr-x   8 nickv  staff  256 Dec 11 12:56 .
drwxr-xr-x  17 nickv  staff  544 Dec 11 12:56 ..
lrwxr-xr-x   1 nickv  staff   73 Dec 11 12:56 content-manager -> /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-content-manager
lrwxr-xr-x   1 nickv  staff   78 Dec 11 12:56 content-type-builder -> /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-content-type-builder
lrwxr-xr-x   1 nickv  staff   63 Dec 11 12:56 email -> /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-email
lrwxr-xr-x   1 nickv  staff   74 Dec 11 12:56 settings-manager -> /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-settings-manager
lrwxr-xr-x   1 nickv  staff   64 Dec 11 12:56 upload -> /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-upload
lrwxr-xr-x   1 nickv  staff   75 Dec 11 12:56 users-permissions -> /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-users-permissions
```

The symlinks are pointing to folders which don't exist:

```
ls -la /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-content-manager                                                                         13:16:44
ls: /Users/nickv/.npm-packages/lib/node_modules/strapi-plugin-content-manager: No such file or directory
```

**Comment by yeomann** [comment]
same thing, i don't know why it is closed?


```
 danishreza  ~  Develpoment  ServerDev  strapi new test --dev
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️
🦄 Dev mode is activated!

Lets configurate the connection to your database:
? Choose your main database: MongoDB
? Database name: test
? Host: 127.0.0.1
? +srv connection: false
? Port (It will be ignored if you enable +srv): 27017
? Username: 
? Password: 
? Authentication database (Maybe "admin" or blank): 
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
✔ Install plugin users-permissions.
✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.
✔ Link strapi-hook-mongoose dependency to the project.

👌 Your new application test is ready at /Users/danishreza/Develpoment/ServerDev/test.

⚡️ Change directory:
$ cd test

⚡️ Start application:
$ strapi start
 danishreza  ~  Develpoment  ServerDev  cd test/
 danishreza  ~  Develpoment  ServerDev  test  strapi start
[2019-01-19T10:54:31.628Z] error ENOENT: no such file or directory, stat '/Users/danishreza/Develpoment/ServerDev/test/plugins/content-manager'
 danishreza  ~  Develpoment  ServerDev  test  strapi -v
3.0.0-alpha.18
 danishreza  ~  Develpoment  ServerDev  test  cd admin
 danishreza  …  ServerDev  test  admin  cd ..
 danishreza  ~  Develpoment  ServerDev  test  cd plugins/
 danishreza  …  ServerDev  test  plugins  ls -la
total 48
drwxr-xr-x   8 danishreza  staff  272 Jan 19 12:53 .
drwxr-xr-x  16 danishreza  staff  544 Jan 19 12:53 ..
lrwxr-xr-x   1 danishreza  staff   57 Jan 19 12:53 content-manager -> /usr/local/lib/node_modules/strapi-plugin-content-manager
lrwxr-xr-x   1 danishreza  staff   62 Jan 19 12:53 content-type-builder -> /usr/local/lib/node_modules/strapi-plugin-content-type-builder
lrwxr-xr-x   1 danishreza  staff   47 Jan 19 12:53 email -> /usr/local/lib/node_modules/strapi-plugin-email
lrwxr-xr-x   1 danishreza  staff   58 Jan 19 12:53 settings-manager -> /usr/local/lib/node_modules/strapi-plugin-settings-manager
lrwxr-xr-x   1 danishreza  staff   48 Jan 19 12:53 upload -> /usr/local/lib/node_modules/strapi-plugin-upload
lrwxr-xr-x   1 danishreza  staff   59 Jan 19 12:53 users-permissions -> /usr/local/lib/node_modules/strapi-plugin-users-permissions
 danishreza  …  ServerDev  test  plugins  ls -la /usr/local/lib/node_modules/
total 0
drwxr-xr-x   7 root        wheel   238 Jan 11 18:06 .
drwxrwxr-x  34 danishreza  admin  1156 Jan 11 18:29 ..
drwxr-xr-x   9 root        wheel   306 Dec 23 22:35 expo-cli
drwxr-xr-x  12 root        wheel   408 Dec  4 20:41 flow-bin
drwxr-xr-x  23 root        wheel   782 Nov 28 01:57 npm
drwxr-xr-x   6 root        wheel   204 Nov 28 13:35 react-native-cli
drwxr-xr-x  10 root        wheel   340 Jan 11 18:06 strapi
 danishreza  …  ServerDev  test  plugins  

```

**Comment by yeomann** [comment]
EDIT: so the solution involves correcting all links. (so many days struggles :/ ) 😄 

```
 danishreza  ~  Develpoment  ServerDev  Testing  strapi start
[2019-01-19T12:58:40.684Z] error ENOENT: no such file or directory, stat '/Users/danishreza/Develpoment/ServerDev/Testing/plugins/content-type-builder'
 danishreza  ~  Develpoment  ServerDev  Testing  ln -nfs ~/Develpoment/ServerDev/strapi/packages/strapi-plugin-content-type-builder/  ./plugins/content-type-builder 
 danishreza  ~  Develpoment  ServerDev  Testing  strapi start
[2019-01-19T12:59:03.480Z] error ENOENT: no such file or directory, stat '/Users/danishreza/Develpoment/ServerDev/Testing/plugins/email'
 danishreza  ~  Develpoment  ServerDev  Testing  ln -nfs ~/Develpoment/ServerDev/strapi/packages/strapi-plugin-email/  ./plugins/email 
 danishreza  ~  Develpoment  ServerDev  Testing  strapi start
[2019-01-19T12:59:27.294Z] error ENOENT: no such file or directory, stat '/Users/danishreza/Develpoment/ServerDev/Testing/plugins/settings-manager'
 danishreza  ~  Develpoment  ServerDev  Testing  ln -nfs ~/Develpoment/ServerDev/strapi/packages/strapi-plugin-settings-manager/  ./plugins/settings-manager 
 danishreza  ~  Develpoment  ServerDev  Testing  strapi start
[2019-01-19T12:59:48.155Z] error ENOENT: no such file or directory, stat '/Users/danishreza/Develpoment/ServerDev/Testing/plugins/upload'
 danishreza  ~  Develpoment  ServerDev  Testing  ln -nfs ~/Develpoment/ServerDev/strapi/packages/strapi-plugin-upload/  ./plugins/upload 
 danishreza  ~  Develpoment  ServerDev  Testing  strapi start
[2019-01-19T13:00:09.770Z] error ENOENT: no such file or directory, stat '/Users/danishreza/Develpoment/ServerDev/Testing/plugins/users-permissions'
 danishreza  ~  Develpoment  ServerDev  Testing  ln -nfs ~/Develpoment/ServerDev/strapi/packages/strapi-plugin-users-permissions/  ./plugins/users-permissions 
 danishreza  ~  Develpoment  ServerDev  Testing  strapi start

```

**Comment by Aurelsicoko** [comment]
@yeomann So it was caused by the symlinks? Can you submit a PR to fix them? The symlinks are created in this file (https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/after.js#L165).

**Comment by yeomann** [comment]
@Aurelsicoko ok. let me see if i can get some progress. first i would not to put some console and git clone my repo of strapi to understand the console logs. Is there any faster method to test/debug? because its take ages to first install and link plugins when i run `npm run setup`
