### ISSUE TITLE
Strapi crashes on startup with graphql v14.6.0

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#5112]
**Describe the bug**
When either `strapi develop` or `strapi start` is run, the API crashes while trying to start.

```$ strapi start
[2020-01-28T08:37:39.717Z] debug ⛔️ Server wasn't able to start properly.
[2020-01-28T08:37:39.718Z] error Error: Cannot find module 'apollo-server-koa'
Require stack:
- <path to api root>/node_modules/strapi-plugin-users-permissions/config/schema.graphql
- <path to api root>/node_modules/strapi/lib/load/load-files.js
- <path to api root>/node_modules/strapi/lib/load/load-config-files.js
- <path to api root>/node_modules/strapi/lib/core/load-config.js
- <path to api root>/node_modules/strapi/lib/core/index.js
- <path to api root>/node_modules/strapi/lib/Strapi.js
- <path to api root>/node_modules/strapi/lib/index.js
- <path to api root>/node_modules/strapi/lib/commands/start.js
- <path to api root>/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (<path to api root>/node_modules/strapi-plugin-users-permissions/config/schema.graphql:2:25)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loadFiles (<path to api root>/node_modules/strapi/lib/load/load-files.js:35:17)
    at async loadPluginsGraphqlConfig (<path to api root>/node_modules/strapi-plugin-graphql/hooks/graphql/load-config.js:13:20)
    at async Promise.all (index 1)
    at async module.exports (<path to api root>/node_modules/strapi-plugin-graphql/hooks/graphql/load-config.js:33:53)
    at async beforeInitialize (<path to api root>/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:26:44)
    at async Promise.all (index 0)
    at async Strapi.module.exports (<path to api root>/node_modules/strapi/lib/hooks/index.js:58:3)
    at async Strapi.load (<path to api root>/node_modules/strapi/lib/Strapi.js:366:5)
    at async Strapi.start (<path to api root>/node_modules/strapi/lib/Strapi.js:196:7)
error Command failed with exit code 1.
```

**Steps to reproduce the behavior**
1. Upgrade `graphql` to 14.6.0.
2. Have `strapi-plugin-users-permissions` installed.

**Expected behavior**
The API should start normally.

**System**
- Node.js version: `v13.5.0`
- NPM version: `v6.13.4` (I'm using yarn, that's `v1.21.1`)
- Strapi version: `3.0.0-beta.18.2`
- Database: MongoDB
- Operating system: Windows 10 1909, using WSL (Ubuntu 18.04.3 LTS)

**Additional context**

Here is my `dependencies` section is `package.json`.
```json
  "dependencies": {
    "graphql": "14.6.0",
    "slugify": "^1.3.6",
    "strapi": "3.0.0-beta.18.2",
    "strapi-admin": "3.0.0-beta.18.2",
    "strapi-connector-mongoose": "3.0.0-beta.18.2",
    "strapi-plugin-content-manager": "3.0.0-beta.18.2",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.2",
    "strapi-plugin-email": "3.0.0-beta.18.2",
    "strapi-plugin-graphql": "3.0.0-beta.18.2",
    "strapi-plugin-upload": "3.0.0-beta.18.2",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.2",
    "strapi-utils": "3.0.0-beta.18.2"
  },
```

It still doesn't work when I update strapi to `3.0.0-beta.18.6` (same error). That was the whole point, I came across this issue while trying to upgrade strapi and later found it was related to graphql.

**Comment by derrickmehaffy** [comment]
@diogotcorreia 

For clarification, Strapi doesn't support Node `v13.5.0` yet so all testing needs to be done on the latest Node LTS version (v12).

I did test this locally in my own WSL and it works fine (although updating that package on it's own isn't really an issue with Strapi itself as the version in the graphql plugin is 14.5.0):

![image](https://user-images.githubusercontent.com/8593673/73249997-3e456080-4173-11ea-9e61-44fcd35a0cbf.png)

![image](https://user-images.githubusercontent.com/8593673/73250032-4a312280-4173-11ea-8185-51e73e8aed1b.png)

![image](https://user-images.githubusercontent.com/8593673/73250075-62a13d00-4173-11ea-9e4a-0a970d1fc363.png)

**Comment by diogotcorreia** [comment]
@derrickmehaffy 

I've downgraded to Node `v12.4.0`, but it still throws the same error. I tried using `npm` instead of `yarn`, but I couldn't get it to work (it would throw errors during `npm i`, related to permissions and not finding files). Please tell me if you need the NPM logs.

**Comment by derrickmehaffy** [comment]
@diogotcorreia is your project somewhere public where I can look at it? (Github, Gitlab, Bitbucket). As I don't think this is directly an issue with Strapi but somewhere in your project. The npm logs aren't going to tell me much here I'm afraid.

**Comment by diogotcorreia** [comment]
@derrickmehaffy Unfortunately the project is private, but I've created a public repository that has the same error (by copying my repo and deleting all custom stuff).
https://github.com/diogotcorreia/strapi-graphql-error-example

This time I tried to reproduce the issue in a Ubuntu 18.04.3 LTS machine and the result is the same.

Just tried to use NPM in this machine instead of yarn and it worked. So it might be an issue with yarn or just a matter of deleting `yarn.lock`.

**Comment by lauriejim** [comment]
Hello! I don't really understand, why did you updated or installed a graphql dependency?

**Comment by diogotcorreia** [comment]
@lauriejim Hi, I was following this tutorial on your blog (https://strapi.io/blog/strapi-next-restaurants/), but it seems like I forgot to `cd` before installing the `graphql` dependency. Which doesn't matter anyway since the tutorial is outdated.

But yeah, it seems like I can get rid of that dependency altogether.

**Comment by lauriejim** [comment]
Yes this article is quite old.
The strapi GraphQL plugin work with his own specific version (defined in its package.json file)
If you are trying to change the GraphQL version of your app and that the plugin doesn't manage it, it couldn't work (logic).
