### ISSUE TITLE
Heroku deploy  TypeError [ERR_INVALID_URL]: Invalid URL: http://undefined:undefined

### ISSUE THREAD

**Issue by carljustineoyales** [strapi/strapi#5128]
**Describe the bug**
getting TypeError [ERR_INVALID_URL]: Invalid URL: http://undefined:undefined when deploying to heroku even follwing the documentaion of strapi and JawsDB

**Steps to reproduce the behavior**
1. Create heroku account
2. Follow steps in deploying strapi(MySQL) to heroku
3. install add on JawsDB
4. Configure package.json like this

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.DATABASE_HOST}",
        "port": "${process.env.DATABASE_PORT}",
        "database": "${process.env.DATABASE_NAME}",
        "username": "${process.env.DATABASE_USERNAME}",
        "password": "${process.env.DATABASE_PASSWORD}"
      },
      "options": {}
    }
  }
}

```
5. Deploy
**Expected behavior**
should deploy without any problems

**Code snippets**
Here's my logs
```
2020-01-29T16:22:53.000000+00:00 app[api]: Build succeeded
2020-01-29T16:23:00.665208+00:00 heroku[web.1]: Starting process with command `npm start`
2020-01-29T16:23:03.355553+00:00 app[web.1]:
2020-01-29T16:23:03.355571+00:00 app[web.1]: > strapiproject@0.1.0 start /app
2020-01-29T16:23:03.355573+00:00 app[web.1]: > strapi start
2020-01-29T16:23:03.355575+00:00 app[web.1]:
2020-01-29T16:23:05.972513+00:00 app[web.1]: [2020-01-29T16:23:05.970Z] debug ⛔️ Server wasn't able to start properly.
2020-01-29T16:23:05.974178+00:00 app[web.1]: [2020-01-29T16:23:05.974Z] error TypeError [ERR_INVALID_URL]: Invalid URL: http://undefined:undefined
2020-01-29T16:23:05.974182+00:00 app[web.1]: at onParseError (internal/url.js:257:9)
2020-01-29T16:23:05.974184+00:00 app[web.1]: at new URL (internal/url.js:333:5)
2020-01-29T16:23:05.974186+00:00 app[web.1]: at new URL (internal/url.js:330:22)
2020-01-29T16:23:05.974189+00:00 app[web.1]: at module.exports (/app/node_modules/strapi/lib/core/bootstrap.js:375:29)
2020-01-29T16:23:05.974191+00:00 app[web.1]: at Strapi.load (/app/node_modules/strapi/lib/Strapi.js:381:11)
2020-01-29T16:23:05.974193+00:00 app[web.1]: at async Strapi.start (/app/node_modules/strapi/lib/Strapi.js:224:7)
2020-01-29T16:23:06.001041+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-01-29T16:23:06.001965+00:00 app[web.1]: npm ERR! errno 1
2020-01-29T16:23:06.003748+00:00 app[web.1]: npm ERR! strapiproject@0.1.0 start: `strapi start`
2020-01-29T16:23:06.004072+00:00 app[web.1]: npm ERR! Exit status 1
2020-01-29T16:23:06.004406+00:00 app[web.1]: npm ERR!
2020-01-29T16:23:06.004645+00:00 app[web.1]: npm ERR! Failed at the strapiproject@0.1.0 start script.
2020-01-29T16:23:06.004936+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-01-29T16:23:06.026158+00:00 app[web.1]:
2020-01-29T16:23:06.027949+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-01-29T16:23:06.028463+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-01-29T16_23_06_006Z-debug.log
2020-01-29T16:23:06.150755+00:00 heroku[web.1]: State changed from starting to crashed
2020-01-29T16:23:06.132010+00:00 heroku[web.1]: Process exited with status 1
2020-01-29T16:23:14.019215+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=peaceful-peak-28060.herokuapp.com request_id=b8c9a390-a6e1-4697-9be9-077f6197b7d4 fwd="203.189.116.189" dyno= connect= service= status=503 bytes= protocol=https
2020-01-29T16:23:15.435756+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=peaceful-peak-28060.herokuapp.com request_id=f5e586f8-29c3-4fc8-b041-ac51d9eaf395 fwd="203.189.116.189" dyno= connect= service= status=503 bytes= protocol=https
```

**System**
- Node.js version: v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.6
- Database: MySQL
- Operating system: Windows 10 64bit

**Comment by takahiro-yonei** [comment]
I thins that you need to parse heroku config vars `JAWSDB_URL` before boot strapi.
( -> `config/functions/bootstrap.js` )

heroku config vars `JAWSDB_URL` has DB connection info. (host, port, dbname, user, password)
so you need to parse this value into host, port, dbname, user and password.
and set host value as `DATABASE_HOST`, dbname as `DATABASE_NAME`, and so on.

this is a sample code using heroku postgres as DB. (not JawsDB)
I'm really glad that it would be helpful for you.

`config/functions/bootstrap.js`
```
'use strict';

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */

//--------------------------------------------------------
require('dotenv').config();
const url = require('url');
const db = url.parse(process.env.DATABASE_URL);

process.env.DATABASE_HOST = db.hostname || 'localhost';
process.env.DATABASE_PORT = db.port || 5432;
process.env.DATABASE_NAME = db.path ? db.path.substr(db.path.indexOf('/') + 1, db.path.length) : '';
process.env.DATABASE_USERNAME = db.auth ? db.auth.substr(0, db.auth.indexOf(':')) : '';
process.env.DATABASE_PASSWORD = db.auth ? db.auth.substr(db.auth.indexOf(':') + 1, db.auth.length) : '';

module.exports = () => {};
```

**Comment by carljustineoyales** [comment]
I appreciate the help. Thank you.

I think it can also be fixed by doing this to the server.js in the production folder

```
 "host": "${process.env.APP_HOST || 'localhost'}",
  "port": "${process.env.PORT || 1337}",
```

it's strange that when I put 127.0.01 instead of localhost I get a "This site can't be reached" error
