### ISSUE TITLE
cannot not start strapi project

### ISSUE THREAD

**Issue by sashank** [strapi/strapi#513]
I installed latest strapi as described in getting started page , am getting below error

```
strapi start
/usr/lib/node_modules/strapi/lib/Strapi.js:86
  async start(config = {}, cb) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/strapi/lib/index.js:13:28)
/usr/lib/node_modules/strapi/lib/Strapi.js:86
  async start(config = {}, cb) {
        ^^^^^

```

**Node.js version**:  v6.12.2
**npm version**: 3.10.10
**Strapi version**: strapi@alpha
**Operating system**: Ubuntu 16.04.3 LTS

**Comment by sashank** [comment]
Please ignore i was using older version of Node , i upgraded it now and its working fine !
