### ISSUE TITLE
ER_TOO_MANY_KEY_PARTS: Too many key parts specified; max 16 parts allowed

### ISSUE THREAD

**Issue by MarcosRenato266** [strapi/strapi#5131]
**Describe the bug**
I just create a project using sqlite and after some work I switch to MySQL, everything is working fine, is saving data, my schemas still there but when I startup my server I just got:
```
...

cancelOnTimeout: false,
  bindings: [ 'db_model_strapi_administrator', 1 ],
  __knexQueryUid: '8f98faae-97bc-4016-8e50-9b1115a1969e',
  sql:
   'select `core_store`.* from `core_store` where `core_store`.`key` = ? limit ?' }
{ Error: ER_TOO_MANY_KEY_PARTS: Too many key parts specified; max 16 parts allowed
    at Query.Sequence._packetToError (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/knex/lib/dialects/mysql/index.js:130:18
    at Promise._execute (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL._query (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/knex/lib/dialects/mysql/index.js:124:12)
    at Client_MySQL.query (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/knex/lib/runner.js:135:36)
    at /Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/marcosnunes/Documents/Github/cms-resmed-api/node_modules/bluebird/js/release/promise.js:649:10)
  code: 'ER_TOO_MANY_KEY_PARTS',
  errno: 1070,
  sqlMessage: 'Too many key parts specified; max 16 parts allowed',
  sqlState: '42000',
  index: 0,
  sql:

...
```

 but no problem, everything works, but when I go to `users and privileges` and click on `Authenticated` my schemas and functions from my controller are there to config, but in public one schema is not showing up. this is related with the mysql error? if not how can I know what is happening? there is nothing beeing returned from terminal or console.

**System**
- Node.js version: 10.16.1
- yarn version: 1.17.0
- Strapi version: Strapi v3.0.0-beta.18.3
- Database: mysql 8+ (not sure about what 8 version is)

**Additional context**
That problem is happening on develop and staging enviroments (*not tested in prod) but before the database change was everything fine.

**How you change the database**
Just installed the mysql dependencies and change `config/enviroments/development/database.json`

Print on auth user: https://prnt.sc/qusn6l
Print on Public: https://prnt.sc/qusnf7 

Course Schema missing

**Comment by lauriejim** [comment]
Hello! Sorry about this issue.
Did you have this error message at every re-start?
About the content type missing in role permissions - here is the same issue - https://github.com/strapi/strapi/issues/4045

**Comment by MarcosRenato266** [comment]
@lauriejim  first of all thank you for your attention, you looks an awesome guy, you being help on forums and here even being a CTO, thank you. About the questions, yes, I got the message that something went wrong and I should use debug mode, when I do that I can see that error.

**Comment by lauriejim** [comment]
About the core_store issue, can you try to go in your database, then in thee core_store table and delete the line that have the key `db_model_strapi_administrator`.
Restart your app and tell me if the issue persists.


Thank you for these words, I really appreciate.

**Comment by Lith** [comment]
Hello,

I've the same issue, because of one of my schema has more than 16 columns (mysql limitation with innodb).

Strapi try to create a FULLTEXT index with all columns, but in my case, I've 18 on `customers` table.

```
code: 'ER_TOO_MANY_KEY_PARTS',
  errno: 1070,
  sqlMessage: 'Too many key parts specified; max 16 parts allowed',
  sqlState: '42000',
  index: 0,
  sql:
   'CREATE FULLTEXT INDEX SEARCH_CUSTOMERS ON `customers` (`lastname`,`firstname`,`gender`,`birth_city`,`description`,`phone`,`address`,`city`,`license_number`,`license_type`,`license_country`,`facebook_id`,`locale`,`timezone`,`stripe_id`,`imported_id`,`bank_account_owner`,`bank_account_iban`)' }
```

@MarcosRenato266 Are you sure the error happened on `core_store` DB table ? 
Do you have a table with more 16 columns ?

@lauriejim The best would be to create a FULLTEXT index on max 16 columns (maybe split it on more index?)

Thanks :)

**Comment by lpouvreau** [comment]
Hi,

Is there any improvement on the FULLTEXT index issue ?

So far I've not been able to spot any way of configuring models fulltext index columns. 

I reckon a per model configuration that would allow the user to limit the fulltext search fields would be a good solution.

Cheers,

**Comment by lpouvreau** [comment]
Hello there,

I reckon this https://github.com/strapi/strapi/pull/5991 would fix the index issue, right?
