### ISSUE TITLE
When a Strapi app running in Development mode connects to a Postgres database of the same Strapi app running in Production mode, an error is shown.

### ISSUE THREAD

**Issue by MaheshCasiraghi** [strapi/strapi#5224]
When a Strapi app running in Development mode connects to a Postgres database of the same Strapi app running in Production mode, an error is shown.

**Steps to reproduce the behavior**
1. Build and Run a Strapi Application with a PG with NODE_ENV set to production.
2. Build and Run the same Strapi Application with connecting to the same PG instance with NODE_ENV set to develop.
3. If the core_store table is not swapped clean each time, the below error is shown in console:

**Error**
```
2020-02-11T13:58:56.334Z] error error: syntax error at or near "check"
    at Connection.parseE (/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Expected behavior**
In all previous versions I was able to connect to same PG db with both develop and production app instances.

**System**
Node 12.7
Strapi Beta 18.7

**Comment by MaheshCasiraghi** [comment]
For everybody dealing with the same problem: A unicity constraint was set in production db, but not in development component configuration. As a result the component configuration record in core_store "clashed" with db constraint. As a solution, either edit or remove component's configuration options in core_store.
