### ISSUE TITLE
Problems with Roles & Permissions using MySQL

### ISSUE THREAD

**Issue by jeliasson** [strapi/strapi#5265]
**Describe the bug**
Page `Roles & Permissions` returns status code `400` and `Advanced Settings` crashes the server with the stack trace below. This both when adding MySQL afterwards, and during installation.

**Steps to reproduce the behavior**
1. Create a strapi app `yarn create strapi-app test --quickstart --no-run`
2. Cd into the project `cd test`
3. Install mysql deps `yarn add mysql`
4. Update `config/development/database.json` with MySQL connection
5. Start Strapi `yarn develop` (it will build the Admin UI and create 6 tables)
6. Login to the Admin UI and create a user
7. Go to `Roles & Permissions` (400) and then `Advanced Settings` which crashes the server.

**Expected behavior**
Show Roles & Permissions and Advanced Settings

**Screenshots**
N/A

**Code snippets**
```txt
[2020-02-18T20:53:47.791Z] error Error: ER_PARSE_ERROR: You have an error 
in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`users-permissions_role` as `users-permissions_role_1` on `users-permissions_ro' at line 1
    at Query.Sequence._packetToError (/c/[...]/test/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/c/[...]/test/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/c/[...]/test/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/c/[...]/test/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/c/[...]/test/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/c/[...]/test/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/c/[...]/test/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/c/[...]/test/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    --------------------
    at Protocol._enqueue (/c/[...]/test/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/c/[...]/test/node_modules/mysql/lib/Connection.js:198:25)
    at /c/[...]/test/node_modules/knex/lib/dialects/mysql/index.js:130:18
    at Promise._execute (/c/[...]/test/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/c/[...]/test/node_modules/bluebird/js/release/promise.js:518:18)    
    at new Promise (/c/[...]/test/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL._query (/c/[...]/test/node_modules/knex/lib/dialects/mysql/index.js:124:12)
    at Client_MySQL.query (/c/[...]/test/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/c/[...]/test/node_modules/knex/lib/runner.js:135:36)
    at /c/[...]/test/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/c/[...]/test/node_modules/bluebird/js/release/util.js:16:23)
    at /c/[...]/test/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/c/[...]/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/c/[...]/test/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/c/[...]/test/node_modules/bluebird/js/release/promise.js:604:18)
```

**System**
- Node.js version: 13.5.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: mysql 5.7.27-log
- Operating system: Ubuntu via WSL

**Additional context**

**Comment by jeliasson** [comment]
I notice this error during first startup of a fresh project, more specifically `Bootstrap function in plugin "users-permissions" failed`. I mean, it's not the best performing MySQL server but it should definitely be able to handle a initial run. :)

```
▶ yarn develop
yarn run v1.21.1
$ strapi develop
Building your admin UI with development configuration ...

✔ Webpack
  Compiled successfully in 15.19s

[2020-02-18T21:27:53.920Z] info File created: /c/[...]/test/extensions/users-permissions/config/jwt.json  
[2020-02-18T21:27:57.377Z] warn The bootstrap function is taking unusually long to execute (3500 miliseconds).
[2020-02-18T21:27:57.378Z] warn Make sure you call it?
[2020-02-18T21:27:58.380Z] error Bootstrap function in plugin "users-permissions" failed
[2020-02-18T21:27:58.381Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) 
call?
    at /c/[...]/test/node_modules/knex/lib/client.js:318:17
    at tryCatcher (/c/[...]/test/node_modules/bluebird/js/release/util.js:16:23)
    at /c/[...]/test/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/c/[...]/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/c/[...]/test/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/c/[...]/test/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/c/[...]/test/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/c/[...]/test/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/c/[...]/test/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/c/[...]/test/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/c/[...]/test/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/c/[...]/test/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:445:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jeliasson** [comment]
https://github.com/strapi/strapi/issues/4826 seems to be having a similar problem.

**Comment by derrickmehaffy** [comment]
`Database: mysql` Need to know the version

**Comment by jeliasson** [comment]
> `Database: mysql` Need to know the version

It's `5.7.27-log`.

**Comment by lauriejim** [comment]
Hello! I just tried to reproduce but it works on my side.
Here is what I did - https://www.loom.com/share/a6d7c50f357b47a694ef76f2738e9ee3
Did I missed something?

**Comment by jeliasson** [comment]
> Here is what I did - https://www.loom.com/share/a6d7c50f357b47a694ef76f2738e9ee3
Strange. It's loading 80% and getting stuck, while seems like it's doing playback in the background. 

Anyway, I guess this is very specific to either a version or e.g. Azure's SaaS offering. I have asked in the other issue reporting what kind of database they use. Did you use a local installation of MySQL/MariaDB?

**Comment by lauriejim** [comment]
Yap I saw that, lets try to know why this issue happens.

**Comment by jeliasson** [comment]
Yeah, I'm giving up on Strapi. Not only did this occur on Azure Database for MySQL, but also in a high performance MySQL cluster running in Kubernetes. That along with relational issues (see all `globalId`-threads) is not worth it.

I'm closing this issue as there are other active.
