### ISSUE TITLE
[BUG] Fail on npm run script ?

### ISSUE THREAD

**Issue by storm1er** [strapi/strapi#527]
**Node.js version**:
v8.9.4
**npm version**:
5.6.0
**Strapi version**:
V3 on master d1f8fd8f
**Operating system**:
Ubuntu 17.10

I can't get `npm run setup` to work.

```log
0 info it worked if it ends with ok
1 verbose cli [ '/home/storm1er/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/storm1er/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle @3.0.0-alpha.8.3~presetup: @3.0.0-alpha.8.3
6 info lifecycle @3.0.0-alpha.8.3~setup: @3.0.0-alpha.8.3
7 verbose lifecycle @3.0.0-alpha.8.3~setup: unsafe-perm in lifecycle true
8 verbose lifecycle @3.0.0-alpha.8.3~setup: PATH: /home/storm1er/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/storm1er/github/strapi/node_modules/.bin:/home/storm1er/.nvm/versions/node/v8.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/storm1er/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/home/storm1er/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/home/storm1er/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/home/storm1er/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/home/storm1er/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/home/storm1er/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/home/storm1er/.antigen/bundles/zsh-users/zsh-syntax-highlighting
9 verbose lifecycle @3.0.0-alpha.8.3~setup: CWD: /home/storm1er/github/strapi
10 silly lifecycle @3.0.0-alpha.8.3~setup: Args: [ '-c',
10 silly lifecycle   'npm run clean:all && npm install && node ./scripts/setup.js && npm run clean' ]
11 silly lifecycle @3.0.0-alpha.8.3~setup: Returned: code: 1  signal: null
12 info lifecycle @3.0.0-alpha.8.3~setup: Failed to exec setup script
13 verbose stack Error: @3.0.0-alpha.8.3 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/storm1er/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/storm1er/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @3.0.0-alpha.8.3
15 verbose cwd /home/storm1er/github/strapi
16 verbose Linux 4.13.0-31-generic
17 verbose argv "/home/storm1er/.nvm/versions/node/v8.9.4/bin/node" "/home/storm1er/.nvm/versions/node/v8.9.4/bin/npm" "run" "setup"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @3.0.0-alpha.8.3 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
22 error Exit status 1
23 error Failed at the @3.0.0-alpha.8.3 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by storm1er** [comment]
I was missing libpng-dev package, I did `apt install libpng-dev`, then it works.
