### ISSUE TITLE
strapi-utils: Cannot read property `buildQuery` of undefined

### ISSUE THREAD

**Issue by gmolau** [strapi/strapi#5306]
**Describe the bug**
I'm trying to programmatically use the request params for filtering as described in the [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/parameters.html#extracting-requests-filters), but the import of the `buildQuery` function fails.

**Steps to reproduce the behavior**
1. Install a fresh Strapi instance as described in the quickstart, but only create an empty `article` content type without any attributes. 
2. Allow public access to everything under `Roles & Permissions`.
3. Try to use the `buildQuery` function in `api/article/services/article.js` as describes in it's documentation:

```
'use strict';

const {buildQuery} = require('strapi-utils');

module.exports = {
  find() {buildQuery({model: 'article'})}
};
```

4. Now calling `localhost:1337/article` gives the following error:

```
[2020-02-24T15:03:59.872Z] error TypeError: Cannot read property 'buildQuery' of undefined
    at buildQuery (/private/tmp/strapi/my-project/node_modules/strapi-utils/lib/buildQuery.js:145:5)
    at Object.find (/private/tmp/strapi/my-project/api/article/services/article.js:11:11)
    at Object.find (/private/tmp/strapi/my-project/node_modules/strapi/lib/core-api/controller.js:26:34)
    at dispatch (/private/tmp/strapi/my-project/node_modules/koa-compose/index.js:44:32)
    at next (/private/tmp/strapi/my-project/node_modules/koa-compose/index.js:45:18)
    at dispatch (/private/tmp/strapi/my-project/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at policies.push (/private/tmp/strapi/my-project/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:83:28)
    at dispatch (/private/tmp/strapi/my-project/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
    at module.exports (/private/tmp/strapi/my-project/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:112:9)
[2020-02-24T15:03:59.875Z] debug GET /articles (25 ms) 500

```

Note that the error is actually happening in [`strapi-utils/lib/buildQuery.js`](https://github.com/strapi/strapi/blob/c05dcec622bb7fb9a2517dbcf691f60b3d13eeea/packages/strapi-utils/lib/buildQuery.js#L145), not in `article.js` itself.

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0 (but using yarn 1.21.1)
- Strapi version: 3.0.0-beta. 18.7
- Database: SQLite
- Operating system: macOS 10.15.3

**Comment by lauriejim** [comment]
The usage of this utils is no longer documented and recommended to use.
I'm closing this issue.
