### ISSUE TITLE
Migration failed after upgrading from 3.0.0.Beta 17.7 to Beta 18.7

### ISSUE THREAD

**Issue by onexdata** [strapi/strapi#5326]
**Describe the bug**
I followed the migration guide here: https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html

However, I'm getting a generic error that seems to say I cannot connect to my datasource.
```
[2020-02-26T04:11:31.633Z] error Migration failed
[2020-02-26T04:11:31.635Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at C:\Users\njste\code\experience-engine\platform\node_modules\knex\lib\client.js:348:17
    at tryCatcher (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\catch_filter.js:17:41
    at tryCatcher (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
[2020-02-26T04:11:31.638Z] error Impossible to register the 'strapi_webhooks' model.
[2020-02-26T04:11:31.639Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at C:\Users\njste\code\experience-engine\platform\node_modules\knex\lib\client.js:348:17
    at tryCatcher (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\catch_filter.js:17:41
    at tryCatcher (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\njste\code\experience-engine\platform\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)`
```

**Code snippets**
My database.json:
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "mysql",
        "database": "platform",
        "host": "localhost",
        "port": 3306,
        "username": "root",
        "password": ""
      },
      "options": {}
    },
    "whisper": {
      "connector": "mongoose",
      "settings": {
        "client": "mongo",
        "host": "localhost",
        "port": 27017,
        "database": "platform",
        "username": "",
        "password": ""
      },
      "options": {}
    }
  }
}
```

My Dependencies:
```
    "axios": "^0.19.0",
    "config": "^3.2.4",
    "core-js": "^2.5.7",
    "hashids": "^2.1.0",
    "jest": "^24.9.0",
    "knex": "latest",
    "lodash": "^4.17.15",
    "magento-api-rest": "^1.1.0",
    "mysql": "latest",
    "node-cache": "^5.1.0",
    "paypal-rest-sdk": "^1.8.1",
    "strapi": "3.0.0-beta.18.7",
    "strapi-admin": "3.0.0-beta.18.7",
    "strapi-connector-bookshelf": "3.0.0-beta.18.7",
    "strapi-connector-mongoose": "^3.0.0-beta.18.7",
    "strapi-plugin-content-manager": "3.0.0-beta.18.7",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.7",
    "strapi-plugin-documentation": "3.0.0-beta.18.7",
    "strapi-plugin-email": "3.0.0-beta.18.7",
    "strapi-plugin-graphql": "3.0.0-beta.18.7",
    "strapi-plugin-upload": "3.0.0-beta.18.7",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.7",
    "strapi-provider-upload-google-cloud-storage": "^3.0.0-beta.18",
    "strapi-utils": "3.0.0-beta.18.7",
    "stripe": "^7.14.0",
    "taxjar": "^3.1.0",
    "validator": "^12.1.0",
    "woocommerce-api": "^1.5.0"
```

**Additional Context***
I have both a MySQL and MongoDB data connection.

**Comment by derrickmehaffy** [comment]
```
"strapi-connector-mongoose": "^3.0.0-beta.18.7",
```

Can you try removing the carrot `^` as that can mess up which package is actually installed.

Although your timeouts appear to be coming from the database itself not responding.

**Comment by lauriejim** [comment]
Hello @onexdata, can you give us an update about this issue, please.

**Comment by hossam-96** [comment]
I'm having nearly the same problem after upgrading from 3.0.0.Beta 16.8 to Beta 19.3
I have a mysql RDS database.
I have followed the migration guides.
`$ yarn develop`
`yarn run v1.21.0`
`$ strapi develop`
`[2020-03-30T09:02:20.524Z] error Migration failed`
`[2020-03-30T09:02:20.526Z] error KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_MySQL.acquireConnection (\node_modules\knex\lib\client.js:347:26)`

**Comment by romanmandryk** [comment]
I had the same problem using PG database.
It disappeared after adding temporarily this "connections.default.options.pool" setting in to config/environments/development/database.json
`"pool": {
          "min": 0,
          "max": 50,
          "acquireTimeoutMillis": 20000,
          "createTimeoutMillis": 20000,
          "idleTimeoutMillis": 30000
        }`

**Comment by lauriejim** [comment]
Thank you @romanmandryk for this fix!

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/heroku-error-knextimeouterror-knex-timeout-acquiring-a-connection-the-pool-is-probably-full-are-you-missing-a-transacting-trx-call/2618/2
