### ISSUE TITLE
Crash on initial yarn run develop

### ISSUE THREAD

**Issue by omar-enrique** [strapi/strapi#5350]
I started a new MongoDB Strapi project using "yarn create strapi-app"
After the project was set up, I ran yarn run develop.  After Webpack finishes bundling everything up, the process straight up crashes and tells me the following:

```
yarn run develop
yarn run v1.22.0
$ strapi develop
Building your admin UI with development configuration ...

√ Webpack
  Compiled successfully in 29.41s

[2020-02-28T04:54:35.106Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:35.364Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:35.365Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:35.972Z] info File created: C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\extensions\users-permissions\config\jwt.json
[2020-02-28T04:54:36.639Z] error Bootstrap function in plugin "email" failed
[2020-02-28T04:54:36.648Z] error MongoError: w has to be a number or a string
    at Connection.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\pool.js:460:61)
    at Connection.emit (events.js:189:13)
    at processMessage (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_mo    at TLSSocket.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\connection.js:537:15)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms> strapi dev
[2020-02-28T04:54:50.922Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:51.201Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:51.202Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:52.285Z] error Bootstrap function in plugin "email" failed
[2020-02-28T04:54:52.289Z] error MongoError: w has to be a number or a string
    at Connection.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\pool.js:460:61)
    at Connection.emit (events.js:189:13)
    at processMessage (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\connection.js:368:10)
    at TLSSocket.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\connection.js:537:15)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Does anyone know what's going on?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
