### ISSUE TITLE
Crash on initial "yarn run develop" (mongo strapi app)

### ISSUE THREAD

**Issue by omar-enrique** [strapi/strapi#5364]
**Describe the bug**
I started a new MongoDB Strapi project using "yarn create strapi-app"
After the project was set up, I ran yarn run develop. After Webpack finishes bundling everything up, the process straight up crashes and produces error output which I have down in the code snippets section.

**Steps to reproduce the behavior**
1. Run "yarn create strapi-app portfolio-mongo-cms" to create strapi app.
2. Prompted for set-up options. Options I chose:
- Installation type: Custom
- Database client: Mongo
- Database name: *Same as my mongo cluster name*
- Host: *Same as Mongo connection string after @ symbol*
- srv connection: false
- Port: 27017
- Username: *Mongo Admin username*
- Password: *Mongo admin password*
- Authentication database: *blank*
- Enable SSL Connection: Yes

**Expected behavior**
I have another Strapi project in which I followed the Blog tutorial for Nuxt.js to set up:
https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo

I used the --quickstart tag for creating the strapi app, and thus used all default options.  When I ran yarn run develop on this strapi project, it actually did serve a locally hosted cms that I could log into and interact with on port 1337.  I was expecting a similar behavior when I made a new MongoDB based strapi project.

**Screenshots**
Not applicable

**Code snippets**
```
yarn run develop
yarn run v1.22.0
$ strapi develop
Building your admin UI with development configuration ...

√ Webpack
  Compiled successfully in 29.41s

[2020-02-28T04:54:35.106Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:35.364Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:35.365Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:35.972Z] info File created: C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\extensions\users-permissions\config\jwt.json
[2020-02-28T04:54:36.639Z] error Bootstrap function in plugin "email" failed
[2020-02-28T04:54:36.648Z] error MongoError: w has to be a number or a string
    at Connection.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\pool.js:460:61)
    at Connection.emit (events.js:189:13)
    at processMessage (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_mo    at TLSSocket.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\connection.js:537:15)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms> strapi dev
[2020-02-28T04:54:50.922Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:51.201Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:51.202Z] error An index error happened, it wasn't applied.
        - w has to be a number or a string
[2020-02-28T04:54:52.285Z] error Bootstrap function in plugin "email" failed
[2020-02-28T04:54:52.289Z] error MongoError: w has to be a number or a string
    at Connection.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\pool.js:460:61)
    at Connection.emit (events.js:189:13)
    at processMessage (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\connection.js:368:10)
    at TLSSocket.<anonymous> (C:\Users\winto\OneDrive\Documents\Portfolio Site\portfolio-mongo-cms\node_modules\mongodb\lib\core\connection\connection.js:537:15)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**System**
- Node.js version: >=10.0.0
- NPM version: >=6.0.0
- Strapi version: 3.0.0
- Database: MongoDB
- Operating system: Windows 10

**Additional context**
N/A

**Comment by kubuntux** [comment]
Hello.

In "Host: Same as Mongo connection string after @ symbol," please try to remove the "w" parameter.

In my case, I removed "w=majority".

**Comment by derrickmehaffy** [comment]
```
Node.js version: >=10.0.0
NPM version: >=6.0.0
Strapi version: 3.0.0
```

Please give exact versions to assist with duplicating the issue.

**Comment by omar-enrique** [comment]
@derrickmehaffy 
NPM version: 6.4.1
Node.js version: 10.15.3

**Comment by omar-enrique** [comment]
@kubuntux Thank you for your response. I removed the w parameter from the connection string and I was able to build and run my strapi project. I don't know if that is going to cause problems in the future but that seemed to have solved this issue.

**Comment by derrickmehaffy** [comment]
@omar-enrique `Strapi version: 3.0.0` and your exact Strapi version (you can find this in your package.json)
