### ISSUE TITLE
Disconnect from MongoDB

### ISSUE THREAD

**Issue by Compaurum** [strapi/strapi#5408]
**Describe the bug**
We have remote mongo db (Atlas cluster). After the 2-4 weeks of working, it suddenly stops. Error is caused by mongoDB pool (logs are attached). It looks like there is some leak of mongo connections. I use only strapi instruments to update DB. I don't use direct access to mongoDB through mongoose. It already happened 3 times.

**Steps to reproduce the behavior**
1. Just working webserver. Nothing special.

**Expected behavior**
Expect not to have this error or reconnect to mognoDB if it happens.

**System**
- I use docker strapi/strapi images. Strapi version: ^3.0.0-beta.17.8
- Database: Atlas MongoDB
- Mongoose: 5.7.4

**Logs**
```
[2020-03-03T21:24:51.690Z] error MongoError: server instance pool was destroyed
    at basicWriteValidations (/srv/app/node_modules/mongodb/lib/core/sdam/server.js:388:12)
    at basicReadValidations (/srv/app/node_modules/mongodb/lib/core/sdam/server.js:395:17)
    at Server.command (/srv/app/node_modules/mongodb/lib/core/sdam/server.js:217:19)
    at checkServer (/srv/app/node_modules/mongodb/lib/core/sdam/monitoring.js:144:12)
    at /srv/app/node_modules/mongodb/lib/core/sdam/monitoring.js:197:7
    at /srv/app/node_modules/mongodb/lib/core/connection/pool.js:788:9
    at eachAsync (/srv/app/node_modules/mongodb/lib/core/utils.js:135:5)
    at Pool.reset (/srv/app/node_modules/mongodb/lib/core/connection/pool.js:765:3)
    at /srv/app/node_modules/mongodb/lib/core/sdam/monitoring.js:195:19
    at /srv/app/node_modules/mongodb/lib/core/sdam/monitoring.js:160:18
    at Server.command (/srv/app/node_modules/mongodb/lib/core/sdam/server.js:219:14)
    at checkServer (/srv/app/node_modules/mongodb/lib/core/sdam/monitoring.js:144:12)
    at Object.monitorServer [as monitorFunction] (/srv/app/node_modules/mongodb/lib/core/sdam/monitoring.js:186:3)
    at Server.monitor (/srv/app/node_modules/mongodb/lib/core/sdam/server.js:196:12)
    at Timeout._onTimeout (/srv/app/node_modules/mongodb/lib/core/sdam/topology.js:827:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-03-03T21:25:39.368Z] error MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout._onTimeout (/srv/app/node_modules/mongodb/lib/core/sdam/topology.js:850:16)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-03-03T21:26:12.080Z] error MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout._onTimeout (/srv/app/node_modules/mongodb/lib/core/sdam/topology.js:850:16)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-03-03T21:28:17.767Z] error MongoTimeoutError: Server selection timed out after 30000 ms

```

**Comment by Compaurum** [comment]
It happened again

**Comment by iicdii** [comment]
see #4311 issue. Since v3.0.0-beta.18 version update mongoose version from v5.7.4 to v5.8.0 it resolved some connection issues. try to migrate your strapi version to beta.18

**Comment by Compaurum** [comment]
I've have updated to image to strapi/strapi:3.0.0-beta.19.3. It happened again

**Comment by yapnel** [comment]
I have the same issue as well with the latest strapi when deployed onto Cloud Foundry. It works perfectly when running locally on my machine. Any advice please?

**Comment by lauriejim** [comment]
Hello! I'm not 100% sure, can you try to increase the value in `config/hook.json` file.
Database connectors were hooks before, I'm not if configs changed or not.
So you can try that, I have to check with the dev team.

**Comment by yapnel** [comment]
Hi,

I have resolved my issue i was facing and it seems really strange. I can push to Pivotal Cloud Foundry (PCF) PaaS successfully. However, the command i'm using to start strapi in dev mode is "npm run develop" but somehow it was starting in production mode instead!  This has caused the error i was facing because i didn't configure anything for production mongodb. I did a test with a new strapi project and with postgres db this time to test and it has the same behaviour. Could this be a bug? Seems like i can't start in dev mode pushing to PCF

**Comment by lauriejim** [comment]
Hum this could not be random.
The `development` or `production` environment depends on the `NODE_ENV` variable.
And will the the `config/environment/[development/procution]` depending on the value.

**Comment by joeczar** [comment]
Hi, I'm also unable to connect to Atlas. Using "strapi": "3.0.0-beta.20.3". Getting the same results as everyone else.
`$ strapi develop
[2020-05-26T11:20:34.326Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-26T11:20:34.329Z] error Error connecting to the Mongo database. Server selection timed out after 30000 ms
error Command failed with exit code 1.`

**Comment by derrickmehaffy** [comment]
I just tested again on beta.20.3 and rc.1 releases using my old template for the database.json and it worked fine: https://gist.github.com/derrickmehaffy/aea3c635e0b9704b14fd1693fc56fea2

**Comment by joeczar** [comment]
I was able to solve this by using the same link as MongoDBCompas instead of the URI. 

mongodb+srv://<user>:<pass>@goal-tracker-f72do.mongodb.net/test
