### ISSUE TITLE
MissingSchemaError after migrating Groups to components (v17.x => v18.x)

### ISSUE THREAD

**Issue by cupofnestor** [strapi/strapi#5453]
**Describe the bug**
After migration, Clicking 'Files Upload' in Admin UI generates mongoose MissingSchemaError 

**Steps to reproduce the behavior**

Generate a new project using strapi version > 18
Migrate (cut 'n' paste) models from previous version 17 project
Change 'kind' strings in groups,  database collection names for groups, and model collection names according to [migration guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html)

**Expected behavior**
100% working Strapi instance running version >18

**Actual Behavior**
All models/components behave properly in new ui, however clicking Files Upload list generates:
Mongoose Schema error referring to removed Group:

```
error MissingSchemaError: Schema hasn't been registered for model "GroupBentonexplore".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/usr/src/api/node_modules/mongoose/lib/error/missingSchema.js:22:11)
    at NativeConnection.Connection.model (/usr/src/api/node_modules/mongoose/lib/connection.js:1029:11)
    at getModelsMapForPopulate (/usr/src/api/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:201:59)
    at populate (/usr/src/api/node_modules/mongoose/lib/model.js:4250:21)
    at _populate (/usr/src/api/node_modules/mongoose/lib/model.js:4220:5)
    at utils.promiseOrCallback.cb (/usr/src/api/node_modules/mongoose/lib/model.js:4195:5)
    at Object.promiseOrCallback (/usr/src/api/node_modules/mongoose/lib/utils.js:261:12)
    at Function.Model.populate (/usr/src/api/node_modules/mongoose/lib/model.js:4193:16)
    at cb (/usr/src/api/node_modules/mongoose/lib/query.js:1948:17)
    at result (/usr/src/api/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/usr/src/api/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/usr/src/api/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.close (/usr/src/api/node_modules/mongodb/lib/operations/to_array.js:36:13)
    at handleCallback (/usr/src/api/node_modules/mongodb/lib/utils.js:129:55)
    at completeClose (/usr/src/api/node_modules/mongodb/lib/cursor.js:859:16)
    at Cursor.close (/usr/src/api/node_modules/mongodb/lib/cursor.js:878:12)
```

**System**
- Node.js version: v10 
- NPM version:
- Strapi version: tested on 18.6 and 19.3
- Database: mongo
- Operating system: ubuntu

**Comment by cupofnestor** [comment]
## Update
I found that the upload-files associated with my old groups still contained a `kind` field referencing the migrated groups.  I've updated those field, but am still having problems.
