### ISSUE TITLE
Deep populate fails with array like populate syntax 

### ISSUE THREAD

**Issue by naren389** [strapi/strapi#5520]
**Describe the bug**
I am trying to populate role object fields in user profile GET API which has reference to user object, with the below populate syntax.

let data = await strapi.query('user-profile').find(ctx.query, ['user', 'user.role']);

While deep filter works fine, strapi is not populating role object  fields in the API response. 

Below syntax, however is populating role object fields, but deep filters like user.role.name=xyz throws 500 error.

 let data = await strapi.query('user-profile').find(ctx.query, [{path : 'user', populate : {path: 'user.role'}}]);

500 Error stack trace below:
---------------------------------- 
[2020-03-16T16:52:56.011Z] warn Deep filtering queries should be used carefully (e.g Can cause performance issues).
When possible build custom routes which will in most case be more optimised.
[2020-03-16T16:52:56.022Z] error TypeError: path.split is not a function
    at findModelPath (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-connector-mongoose\lib\buildQuery.js:518:22)
    at populate.map.map.path (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-connector-mongoose\lib\buildQuery.js:175:18)
    at Array.map (<anonymous>)
    at computePopulatedPaths (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-connector-mongoose\lib\buildQuery.js:175:6)
    at buildDeepQuery (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-connector-mongoose\lib\buildQuery.js:63:41)
    at Object.buildQuery (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-connector-mongoose\lib\buildQuery.js:26:10)
    at buildQuery (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-utils\lib\buildQuery.js:129:6)
    at Object.find (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-connector-mongoose\lib\queries.js:414:12)
    at Query.find (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-database\lib\queries\create-query.js:47:32)
    at Object.find (C:\MyUserData\Lab\sciens\easyvenue_api\api\user-profile\controllers\user-profile.js:29:55)
    at dispatch (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at dispatch (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\koa-compose\index.js:42:32)
    at policies.push (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:83:28)
    at dispatch (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\koa-compose\index.js:42:32)
    at module.exports (C:\MyUserData\Lab\sciens\easyvenue_api\node_modules\strapi-plugin-users-permissions\config\policies\permissions.js:112:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-03-16T16:52:56.026Z] debug GET \user-profiles?user.role.name=admin (37 ms) 500

**Steps to reproduce the behavior**

**Expected behavior**
.find(ctx.query, ['user', 'user.role']) should populate role object fields in API response.

**Screenshots**

**Code snippets**

find: async (ctx) => {
        if (_.has(ctx.query, '_q')) {
            console.log (ctx.query);
            // use core strapi query to search for users
            return await strapi.query('user-profile').search(ctx.query, ['user', 'user.role']);
        }
    
        let data = await strapi.query('user-profile').find(ctx.query, ['user', 'user.role']);
       
        return data.map( entity =>  sanitizeEntity(entity, { model: strapi.models['user-profile'] }));
    }

**System**
- Node.js version:  v10.16.3
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.18.3
- Database: mongo
- Operating system: Windows10

**Additional context**

**Comment by lauriejim** [comment]
Hello! Your issue is not simply readable, can you please update your issue body to make it understandable for me. 
Thank you.

**Comment by naren389** [comment]
@lauriejim I am expecting the below statement to populate all fields from role table in the API response, but it is not.

let data = await strapi.query('user-profile').find(ctx.query, ['user', 'user.role']);

What is the best way to deep populate fields in strapi ?

**Comment by lauriejim** [comment]
Hello! It's how it works but... please well format your issue and comments please.

Here is the documentation about that - https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html#custom-queries

`let data = await strapi.query('user', users-permissions').find(ctx.query, ['user', 'user.role']);`

**Comment by Pablo-Aldana** [comment]
Hi unfortunatelly this does not work for me when using mongo.  If I use postgres everything work smoothly and I don't even need to use any option on the find method. I'm using v3.0.4.
My structure is
Programs has many workouts.
Workouts has many Exercises.

If I call:

(I concatenate the ctx.query that is "users.username=emailaddress" with user premium true)

`entities =  await strapi.services.program.find(Object.assign(ctx.query,{"users.premium":"true"}), ['workouts', 'workouts.exercises'],);`

The exercises is returned as ids
```

    {
        "free": true,
        "workouts": [
            {
                "exercises": [
                    "5ef4a36b8d006288485c8013",
                    "5ef4a34f8d006288485c8010"
                ],
                "_id": "5ef4a3078d006288485c800e",
```

However if I use instead the ctx.query a hardcorded query:

`secondquery = await strapi.services.program.find({"users":{$eq:[]}}, {path:'workouts', populate:{path:'exercises'}});`

it works and returns the associated exercises

```
"free": false,
        "workouts": [
            {
                "exercises": [
                    {
                        "exerciseImages": [
                            {
                                "_id": "5ef4a3688d006288485c8012",
                                "name": "medium_maxresdefault_b2da8febdf",
                                "alternativeText": "",
                                "caption": "",
                                "hash": "medium_maxresdefault_b2da8febdf_089ba98663",
                                "ext": ".jpeg",
                                "mime": "image/jpeg",

and so...

```

After a week of trying to solve this I'm giving up and using postgress instead MongoDB but it would be great to have this issue solved.

**Comment by pupubird** [comment]
For anyone who is still looking for a solution, here is what I found:

say with an example of `find(query,params)`

The `params` here is what you will be looking for, there are 3 kinds of input you can put:

1. An array of strings 

```javascript
params = [ 'users', 'events' ]
```

2. An object,

```javascript 
params = {
  path: "users",
  populate: {
    path: "roles"
  }
}
```

3. An array of an object:

```javascript 
params = [
  {
    path: "users",
    populate: {
      path: "roles"
  },
  {
    path: "blogs",
    populate: {
      path: "roles"
  },
}
```

Hope that helps

*Note, this is the case for MongoDB database

**Comment by borm** [comment]
@pupubird 

> For anyone who is still looking for a solution, here is what I found:
> 
> say with an example of `find(query,params)`
> 
> The `params` here is what you will be looking for, there are 3 kinds of input you can put:
> 
> 1. An array of strings
> 
> ```js
> params = [ 'users', 'events' ]
> ```
> 
> 1. An object,
> 
> ```js
> params = {
>   path: "users",
>   populate: {
>     path: "roles"
>   }
> }
> ```
> 
> 1. An array of an object:
> 
> ```js
> params = [
>   {
>     path: "users",
>     populate: {
>       path: "roles"
>   },
>   {
>     path: "blogs",
>     populate: {
>       path: "roles"
>   },
> }
> ```
> 
> Hope that helps
> 
> *Note, this is the case for MongoDB database

```
MongooseError: If you are populating a virtual, you must set the localField and foreignField options
```
