### ISSUE TITLE
Relational fields search MySQL ER_PARSE_ERROR

### ISSUE THREAD

**Issue by loongmxbt** [strapi/strapi#5535]
**Describe the bug**
When I search in the right side relational fields, whenever I type a letter, there is an error occurred.
```
ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc) AGAINST('*test*' IN BOOLEAN MODE) limit 20' at line 1
```
Only the top fields in the pre-load list can be found, I have to scroll down to load additional fields, then I can filter the result.
I assume this should be search all related entries.
MySQL database encoding is utf8mb4_unicode_ci

**Steps to reproduce the behavior**
1. Go to 'entry edit page'
2. Click on 'relational fields'
3. Type a letter to search
```
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc) AGAINST('*te*' IN BOOLEAN MODE) limit 20' at line 1
```

**Expected behavior**
When I type a letter, mysql should be able to return the fields contains this letter.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.13.1
- NPM version: 6.13.4
- Strapi version: beta.19
- Database: MySQL 5.7.28  encoding utf8mb4_unicode_ci
- Operating system: MacOS
Also I tested in another Ubuntu18.04+MySQL5.7+beta.19

**Additional context**

```
[2020-03-18T12:40:47.731Z] debug GET /content-manager/explorer/application::service.service?_q=test&_limit=20&_start=0 (25 ms) 500
[2020-03-18T12:40:48.226Z] error Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc) AGAINST('*test1*' IN BOOLEAN MODE) limit 20' at line 1
    at Query.Sequence._packetToError (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
    --------------------
    at Protocol._enqueue (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/knex/lib/dialects/mysql/index.js:130:18
    at Promise._execute (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL._query (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/knex/lib/dialects/mysql/index.js:124:12)
    at Client_MySQL.query (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/knex/lib/runner.js:135:36)
    at /Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/dragonszy/Github/zhongbao/zhongbao-strapi/node_modules/bluebird/js/release/promise.js:649:10)
```

**Comment by lauriejim** [comment]
Hello! I just tried and it works well on my side.
Here is what I did - https://www.loom.com/share/14b69516ee3749988e764c3bf0058654
Can you tell me if I'm missing something

**Comment by loongmxbt** [comment]
Hi, thank you for your testing. Here is my loom video https://www.loom.com/share/f9e33505f763402598c84153f310b774
In my localhost development, I can search the `caseinfos` and `myunits` relational fields. But the strange thing is searching `caseinfos` returns nothing while searching `myunits` returns the correct entires. Also the logs seems fine.

Dev Environment:
MacOS
Your MySQL connection id is 108
Server version: 5.7.28 Homebrew
```
[2020-03-25T06:47:49.645Z] debug GET /content-manager/explorer/application::caseinfo.caseinfo?_limit=20&_start=0 (6 ms) 200
[2020-03-25T06:47:51.176Z] debug GET /content-manager/explorer/application::caseinfo.caseinfo?_q=D (6 ms) 200
[2020-03-25T06:47:52.822Z] debug GET /content-manager/explorer/application::caseinfo.caseinfo?_limit=20&_start=0 (7 ms) 200
[2020-03-25T06:47:54.122Z] debug GET /content-manager/explorer/application::caseinfo.caseinfo?_q=D (4 ms) 200
[2020-03-25T06:47:54.804Z] debug GET /content-manager/explorer/application::caseinfo.caseinfo?_q=D3 (4 ms) 200
[2020-03-25T06:47:55.873Z] debug GET /content-manager/explorer/application::caseinfo.caseinfo?_q=D (4 ms) 200
[2020-03-25T06:47:55.903Z] debug GET /content-manager/explorer/application::caseinfo.caseinfo?_limit=20&_start=0 (7 ms) 200
[2020-03-25T06:48:00.042Z] debug GET /content-manager/explorer/application::myunit.myunit?_q=unit (7 ms) 200
[2020-03-25T06:48:01.676Z] debug GET /content-manager/explorer/application::myunit.myunit?_q=unit2 (6 ms) 200
[2020-03-25T06:48:02.557Z] debug GET /content-manager/explorer/application::myunit.myunit?_q=unit (7 ms) 200
[2020-03-25T06:48:03.211Z] debug GET /content-manager/explorer/application::myunit.myunit?_q=unit3 (4 ms) 200
[2020-03-25T06:48:04.097Z] debug GET /content-manager/explorer/application::myunit.myunit?_q=unit (7 ms) 200
[2020-03-25T06:48:04.636Z] debug GET /content-manager/explorer/application::myunit.myunit?_q=unit4 (4 ms) 200
```

In my production env, later in the video. Both the search returns error.
Production environment:
Ubuntu18.04 LTS
Your MySQL connection id is 2654
Server version: 5.7.27-0ubuntu0.18.04.1 (Ubuntu)
```
0|elecsim-cloud-strapi  | [2020-03-25T07:08:51.083Z] debug GET /content-manager/explorer/plugins::users-permissions.user?_limit=20&_start=0 (14 ms) 200
0|elecsim-cloud-strapi  | [2020-03-25T07:09:34.115Z] error Error: ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list
0|elecsim-cloud-strapi  |     at Query.Sequence._packetToError (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
0|elecsim-cloud-strapi  |     at Query.ErrorPacket (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
0|elecsim-cloud-strapi  |     at Protocol._parsePacket (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
0|elecsim-cloud-strapi  |     at Parser._parsePacket (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
0|elecsim-cloud-strapi  |     at Parser.write (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
0|elecsim-cloud-strapi  |     at Protocol.write (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
0|elecsim-cloud-strapi  |     at Socket.<anonymous> (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/Connection.js:91:28)
0|elecsim-cloud-strapi  |     at Socket.<anonymous> (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/Connection.js:525:10)
0|elecsim-cloud-strapi  |     at Socket.emit (events.js:210:5)
0|elecsim-cloud-strapi  |     at addChunk (_stream_readable.js:308:12)
0|elecsim-cloud-strapi  |     at readableAddChunk (_stream_readable.js:289:11)
0|elecsim-cloud-strapi  |     at Socket.Readable.push (_stream_readable.js:223:10)
0|elecsim-cloud-strapi  |     at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
0|elecsim-cloud-strapi  |     --------------------
0|elecsim-cloud-strapi  |     at Protocol._enqueue (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
0|elecsim-cloud-strapi  |     at Connection.query (/var/www/elecsim-cloud-strapi/node_modules/mysql/lib/Connection.js:201:25)
0|elecsim-cloud-strapi  |     at /var/www/elecsim-cloud-strapi/node_modules/knex/lib/dialects/mysql/index.js:135:18
0|elecsim-cloud-strapi  |     at Promise._execute (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/debuggability.js:411:9)
0|elecsim-cloud-strapi  |     at Promise._resolveFromExecutor (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/promise.js:518:18)
0|elecsim-cloud-strapi  |     at new Promise (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/promise.js:103:10)
0|elecsim-cloud-strapi  |     at Client_MySQL._query (/var/www/elecsim-cloud-strapi/node_modules/knex/lib/dialects/mysql/index.js:129:12)
0|elecsim-cloud-strapi  |     at Client_MySQL.query (/var/www/elecsim-cloud-strapi/node_modules/knex/lib/client.js:165:17)
0|elecsim-cloud-strapi  |     at Runner.query (/var/www/elecsim-cloud-strapi/node_modules/knex/lib/runner.js:135:36)
0|elecsim-cloud-strapi  |     at /var/www/elecsim-cloud-strapi/node_modules/knex/lib/runner.js:39:23
0|elecsim-cloud-strapi  |     at tryCatcher (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/util.js:16:23)
0|elecsim-cloud-strapi  |     at /var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/using.js:185:26
0|elecsim-cloud-strapi  |     at tryCatcher (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/util.js:16:23)
0|elecsim-cloud-strapi  |     at Promise._settlePromiseFromHandler (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/promise.js:547:31)
0|elecsim-cloud-strapi  |     at Promise._settlePromise (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/promise.js:604:18)
0|elecsim-cloud-strapi  |     at Promise._settlePromise0 (/var/www/elecsim-cloud-strapi/node_modules/bluebird/js/release/promise.js:649:10)
```
I think in production the 500 error maybe related to MySQL, the message `error Error: ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list` maybe helpful, I'll do some more testing directly on production server. But I'm sure I can search relational fields in previous versions(I keep upgrading the beta).
In dev environment I can't figure out how the inconsistency occur.

**Comment by lauriejim** [comment]
@alexandrebodin any idea about this?

**Comment by alexandrebodin** [comment]
Hi @loongmxbt 
It seems strapi couldn't create the search index on your production server. It might be realted to the permissions of your database user. Can you check the granted permissions you have in prod vs dev ?

**Comment by loongmxbt** [comment]
@alexandrebodin Thanks for your guide. I'll check both mysql users and permissions and try to fix the problem.
