### ISSUE TITLE
how to export and import data(database, uploads )

### ISSUE THREAD

**Issue by superway117** [strapi/strapi#5542]
## question about how to import  and export data
my purpose is to replicate the enviroment on server to my local pc.

currently i use sqlite as database, i want to backup all files in server, including data.db and all file in upload folder, i am not sure there are enough. 
then i replace my local data.db and upload folder using the above files(data.db and all files in upload folder) , then i run strapi in my local pc, looks the data.db do not load successfully

i found error here, i am not sure what i am missed
```
[2020-03-19T05:40:20.598Z] debug GET /upload/files/count (28 ms) 200
[2020-03-19T05:40:20.619Z] error Error: The target polymorphic type "displayed_plugins" is not one of the defined target types
    at Object.morphCandidate (c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\helpers.js:140:13)
    at c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\eager.js:52:15
    at c:\workshop\zbs-site\strapi\node_modules\lodash\lodash.js:13401:38
    at c:\workshop\zbs-site\strapi\node_modules\lodash\lodash.js:4905:15
    at baseForOwn (c:\workshop\zbs-site\strapi\node_modules\lodash\lodash.js:2990:24)
    at Function.mapValues (c:\workshop\zbs-site\strapi\node_modules\lodash\lodash.js:13400:7)
    at EagerRelation.morphToFetch (c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\eager.js:51:28)
    at EagerRelation.eagerFetch (c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\eager.js:25:19)
    at EagerRelation.<anonymous> (c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\base\eager.js:67:14)
    at EagerRelation.tryCatcher (c:\workshop\zbs-site\strapi\node_modules\bluebird\js\release\util.js:16:23)
    at EagerRelation.fetch (c:\workshop\zbs-site\strapi\node_modules\bluebird\js\release\method.js:15:34)
    at c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\eager.js:95:73
    at tryCatcher (c:\workshop\zbs-site\strapi\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\workshop\zbs-site\strapi\node_modules\bluebird\js\release\method.js:39:29)
    at EagerRelation._eagerLoadHelper (c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\eager.js:82:23)
    at Sync.<anonymous> (c:\workshop\zbs-site\strapi\node_modules\bookshelf\lib\eager.js:31:31)
```

thanks in advance!

**Comment by superway117** [comment]
thanks anyway, i just sync all files changed on server, then works on my local pc
