### ISSUE TITLE
Change fieldname case

### ISSUE THREAD

**Issue by kaemu** [strapi/strapi#5583]
Hello
Change the fieldname case (ie "Date" => "date") in the Content type builder makes the app crash (not restarting)

Logs:

[2020-03-23T23:05:12.606Z] error Impossible to register the 'distribution' model.
[2020-03-23T23:05:12.607Z] error Error: ER_DUP_FIELDNAME: Duplicate column name 'date'
    at Query.Sequence._packetToError (/srv/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/srv/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/srv/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)

**Comment by christianguevara** [comment]
Hi!, I think is because MySQL by default is case insensitive meaning the field "Date" and "date" in database level is the same column, and it can't be created twice.

**Comment by bschlintz** [comment]
+1, hit this with MongoDB as well.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
