### ISSUE TITLE
Error on start: (hook:mongoose) takes too long to load

### ISSUE THREAD

**Issue by sobrio** [strapi/strapi#563]
**Node.js version**:
8.9.4
**npm version**:
5.1.0
**Strapi version**:
3.0.0-alpha.9.1
**Operating system**:
Windows 10

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

D:\applications\strap>strapi start
DEBUG (3340 on Monolite): Server wasn't able to start properly.
ERROR (3340 on Monolite): (hook:mongoose) takes too long to load

**If the current behavior is a bug, please provide the steps to reproduce the problem**

> npm install strapi@alpha -g
> strapi new strap
> cd strap

(MongoDB is running)

**What is the expected behavior?**
The node server should start

**Comment by keyus4** [comment]
Also having the same issue. strapi start error.

C:\Projects\strapi\my-project>strapi start 
DEBUG (3252 on MY-PC): Server wasn't able to start properly.
ERROR (3252 on MY-PC): (hook:mongoose) takes too long to load

**Comment by keyus4** [comment]
I think i was able to get it to work. 
I opened my-project folder => config => environments => development.
I then opened my database json file on notepad++ and I replaced localhost with 127.0.0.1 and it worked!!!

Here! replace
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "host": "localhost",
        "port": "27017",
        "database": "myUberApp",
        "username": "",
        "password": ""
      },
      "options": {}
    }
  }
}

with

{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "host": "127.0.0.1",
        "port": "27017",
        "database": "myUberApp",
        "username": "",
        "password": ""
      },
      "options": {}
    }
  }
}

**Comment by JLKM** [comment]
Nice workaround replacing the default `"host": "localhost"` with `"host": "127.0.0.1"`.

This made it possible for me to actually create a project with Strapi CLI.

```
PS F:\data\fullstack\strapi> strapi new alphanow
INFO (14176 on JLKM1): Creating your application... It might take a few seconds.
INFO (14176 on JLKM1): Lets configurate the connection to your database:
 Choose your main database: MongoDB (highly recommended)
 Database name: strapi
 Host: localhost
 Port: 27017
 Username: something
 Password: something
INFO (14176 on JLKM1): Testing database connection...
INFO (14176 on JLKM1): Copying the dashboard...
INFO (14176 on JLKM1): Installing dependencies...
INFO (14176 on JLKM1): The plugin settings-manager has been successfully installed.
INFO (14176 on JLKM1): The plugin content-type-builder has been successfully installed.
INFO (14176 on JLKM1): The plugin content-manager has been successfully installed.
INFO (14176 on JLKM1): The plugin users-permissions has been successfully installed.
INFO (14176 on JLKM1): The plugin email has been successfully installed.
INFO (14176 on JLKM1): The plugin analytics has been successfully installed.
INFO (14176 on JLKM1): Linking `strapi` dependency to the project...
INFO (14176 on JLKM1): Your new application `alphanow` is ready at `F:\data\fullstack\strapi\alphanow`.

```

But then the next error occurs at `strapi start`:

```
PS F:\data\fullstack\strapi> cd alphanow
PS F:\data\fullstack\strapi\alphanow> strapi start
ERROR (9580 on JLKM1): Unexpected token ...
    F:\data\fullstack\strapi\alphanow\plugins\users-permissions\services\UsersPermissions.js:30
                ...params.permissions[type].controllers[controller][action]
                ^^^

    SyntaxError: Unexpected token ...
        at createScript (vm.js:74:10)
        at Object.runInThisContext (vm.js:116:10)
        at Module._compile (module.js:533:28)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Strapi.loadFile (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\utils\index.js:18:14)
        at Object.setConfig (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\utils\index.js:32:19)
        at files.map.p (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\core\apis.js:46:30)
        at Array.map (native)
        at glob (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\core\apis.js:46:15)
        at f (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\node_modules\once\once.js:25:25)
        at Glob.<anonymous> (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\node_modules\glob\glob.js:151:7)
DEBUG (9580 on JLKM1): Server wasn't able to start properly.
ERROR (9580 on JLKM1): (hook:mongoose) takes too long to load
PS F:\data\fullstack\strapi\alphanow> strapi start
ERROR (13460 on JLKM1): Unexpected token ...
    F:\data\fullstack\strapi\alphanow\plugins\users-permissions\services\UsersPermissions.js:30
                ...params.permissions[type].controllers[controller][action]
                ^^^

    SyntaxError: Unexpected token ...
        at createScript (vm.js:74:10)
        at Object.runInThisContext (vm.js:116:10)
        at Module._compile (module.js:533:28)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Strapi.loadFile (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\utils\index.js:18:14)
        at Object.setConfig (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\utils\index.js:32:19)
        at files.map.p (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\core\apis.js:46:30)
        at Array.map (native)
        at glob (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\core\apis.js:46:15)
        at f (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\node_modules\once\once.js:25:25)
        at Glob.<anonymous> (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\node_modules\glob\glob.js:151:7)
DEBUG (13460 on JLKM1): Server wasn't able to start properly.
ERROR (13460 on JLKM1): Make sure your MongoDB database is running...
PS F:\data\fullstack\strapi\alphanow> strapi start
ERROR (1228 on JLKM1): Unexpected token ...
    F:\data\fullstack\strapi\alphanow\plugins\users-permissions\services\UsersPermissions.js:30
                ...params.permissions[type].controllers[controller][action]
                ^^^

    SyntaxError: Unexpected token ...
        at createScript (vm.js:74:10)
        at Object.runInThisContext (vm.js:116:10)
        at Module._compile (module.js:533:28)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Strapi.loadFile (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\utils\index.js:18:14)
        at Object.setConfig (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\utils\index.js:32:19)
        at files.map.p (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\core\apis.js:46:30)
        at Array.map (native)
        at glob (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\lib\core\apis.js:46:15)
        at f (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\node_modules\once\once.js:25:25)
        at Glob.<anonymous> (C:\Users\Jan\AppData\Roaming\npm\node_modules\strapi\node_modules\glob\glob.js:151:7)
INFO (1228 on JLKM1): Server started in F:\data\fullstack\strapi\alphanow
INFO (1228 on JLKM1): Your server is running at http://localhost:1337
```
Something works though:
1. The server is showing the project homepage at localhost:1337
2. MongoDB has created a database named strapi (in this case)
3. The strapi database on MongoDB contains two collections named `users-permission_role` and `users-permissions_user` incl. content.

But it's not possible to create a user in the admin-section. `localhost:1337/admin/` only directs to a blank html-page, and terminal starts to throw the following errors:

```
DEBUG (1228 on JLKM1): Time: Sat Feb 03 2018 20:01:50 GMT+0100 (Rom, normaltid)DEBUG (1228 on JLKM1): Launched in: 2332 ms
DEBUG (1228 on JLKM1): Environment: development
DEBUG (1228 on JLKM1): Process PID: 1228
DEBUG (1228 on JLKM1): Version: 3.0.0-alpha.9.1 (node v8.1.2)
INFO (1228 on JLKM1): To shut down your server, press <CTRL> + C at any time
DEBUG (1228 on JLKM1): GET index.html (26 ms)
DEBUG (1228 on JLKM1): GET /favicon.ico (1 ms)
DEBUG (1228 on JLKM1): GET index.html (5 ms)
DEBUG (1228 on JLKM1): GET vendor.dll.js (6 ms)
DEBUG (1228 on JLKM1): GET main.js (5 ms)
DEBUG (1228 on JLKM1): GET plugins.json (4 ms)
DEBUG (1228 on JLKM1): GET 1e1c7ab14f4a5847f9eb5756f13fb532.png (4 ms)
DEBUG (1228 on JLKM1): GET main.js (12 ms)
DEBUG (1228 on JLKM1): GET main.js (10 ms)
DEBUG (1228 on JLKM1): GET main.js (10 ms)
DEBUG (1228 on JLKM1): GET main.js (13 ms)
DEBUG (1228 on JLKM1): GET main.js (11 ms)
DEBUG (1228 on JLKM1): GET main.js (11 ms)
ERROR (1228 on JLKM1): Cannot read property '_id' of null
    TypeError: Cannot read property '_id' of null
        at module.exports (F:\data\fullstack\strapi\alphanow\plugins\users-permissions\config\policies\permissions.js:31:15)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:208:7)
DEBUG (1228 on JLKM1): GET /content-type-builder/autoReload (29 ms)
ERROR (1228 on JLKM1): Cannot read property '_id' of null
    TypeError: Cannot read property '_id' of null
        at module.exports (F:\data\fullstack\strapi\alphanow\plugins\users-permissions\config\policies\permissions.js:31:15)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:208:7)
DEBUG (1228 on JLKM1): GET /users-permissions/init (5 ms)
ERROR (1228 on JLKM1): Cannot read property '_id' of null
    TypeError: Cannot read property '_id' of null
        at module.exports (F:\data\fullstack\strapi\alphanow\plugins\users-permissions\config\policies\permissions.js:31:15)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:208:7)
DEBUG (1228 on JLKM1): GET /settings-manager/autoReload (4 ms)
```
So close, and still so far away from using this awesome headless cms tool...

Any suggestions?

OS: Windows 10
node: 8.1.2
npm: 5.6.0
terminal: vs code

**Comment by pedrocruzio** [comment]
@JLKM I had similar problems as you and I  just fixed it by updating node to the latest version.

My configuration is:

OS: Ubuntu 16.04 LTS
Node: 8.9.4
NPM: 5.6.0

**Comment by JLKM** [comment]
Thank you for your tip, @pedrocruzio 

An upgrade fra Node 8.1.2 to 8.9.4 LTS made the whole thing run like a charm on my Windows machine - and with no errors at all in vs code terminal.
