### ISSUE TITLE
The build doesn't work on Strapi v3.0.0-beta.19.4

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#5651]
**Describe the bug**

The build doesn't work on Strapi v3.0.0-beta.19.4

**Steps to reproduce the behavior**

1. Run `npm run build`
2. Error:

```
> ***@0.1.0 build /home/runner/work/***/***
> strapi build

Building your admin UI with production configuration ...
[info] [webpackbar] Compiling Webpack
[success] [webpackbar] Webpack: Compiled with some errors in 56.14s
Error: 1.0cd3c615.chunk.js from Terser
TypeError: Cannot read property 'variables' of undefined
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:209686
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:211321
    at AST_Call.optimize (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:137138)
    at ri.before (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:136915)
    at AST_Call.transform (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:87028
    at ri.before (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:136887)
    at AST_Binary.transform (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:87057
    at ri.before (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:136887)
    at AST_Binary.transform (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84817
    at ri.before (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:136887)
    at AST_SimpleStatement.transform (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84275
    at l (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:931)
    at e (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:1251)
    at e (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:1251)
    at Nn (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84249)
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84861
    at ri.before (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:136887)
    at AST_BlockStatement.transform (/home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/runner/work/***/***/node_modules/terser/dist/bundle.min.js:1:85629
    at /home/runner/work/***/***/node_modules/strapi-admin/index.js:188:23
    at finalCallback (/home/runner/work/***/***/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/runner/work/***/***/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/***/***/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/***/***/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/runner/work/***/***/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/runner/work/***/***/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/***/***/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/***/***/node_modules/tapable/lib/Hook.js:154:20)
    at /home/runner/work/***/***/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/***/***/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/***/***/node_modules/tapable/lib/Hook.js:154:20)
    at /home/runner/work/***/***/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/***/***/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/***/***/node_modules/tapable/lib/Hook.js:154:20)
    at /home/runner/work/***/***/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (/home/runner/work/***/***/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /home/runner/work/***/***/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at step (/home/runner/work/***/***/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at done (/home/runner/work/***/***/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
    at tryCatcher (/home/runner/work/***/***/node_modules/cacache/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/***/***/node_modules/cacache/node_modules/bluebird/js/release/promise.js:547:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ***@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ***@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-03-30T20_00_14_560Z-debug.log
##[error]Process completed with exit code 1.
```

**Expected behavior**

Working.

**Screenshots**

<img width="898" alt="Screenshot 2020-03-30 at 23 30 50" src="https://user-images.githubusercontent.com/1007051/77964026-b4368700-72de-11ea-87c5-fd22d718f3e6.png">

**System**
- Node.js version: v12
- NPM version: v6
- Strapi version: v3.0.0-beta.19.4
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Please make sure you delete the following files/folders:

- `build`
- `.cache`
- `node_modules`
- `package-lock.json`
- `yarn.lock`

Then reinstall/rebuild (use either of these):

- `yarn` then `yarn build`
- `npm install` then `npm run build`

**Comment by abdonrd** [comment]
Yes, I'm doing a clean install and build from GitHub Actions.

**Comment by pushandplay** [comment]
I have the same error with this version

System

- Node.js version: v13.12.0
- NPM version: v6.14.4
- Strapi version: v3.0.0-beta.19.4
- Database: MongoDB
- Operating system: MacOS

**Comment by abdonrd** [comment]
The new version of Terser seems to fix it!

https://github.com/terser/terser/blob/master/CHANGELOG.md#v469
