### ISSUE TITLE
Transaction query already complete when using promise.all

### ISSUE THREAD

**Issue by chanhnv91** [strapi/strapi#5656]
### I am having problems with transactions when inserting multiple rows using promise.all

This is my code at the controller
```js
      try {
            // Do something
           return strapi.connections[strapi.models.notification.connection].transaction(async t => {
                notificationEntity = await baseServices.create(notificationData, t);
                let userNotificationModels = [], userNotificationData = {};
                userArr.map(user => {
                    const userObj = {
                        userId: user,
                        notification:  notificationEntity.id
                    }
                    userNotificationModels.push(userObj);
                });
                userNotificationData.nameTable = enums.tables.USER_NOTIFICATION;
                userNotificationData.models = userNotificationModels;
                userNotificationEntities = await baseServices.createBatch(userNotificationData, t);

                if (!notificationEntity || !userNotificationEntities) return error.SAVE_FAILED;
                if (!userNotificationEntities) return error.SAVE_FAILED;

                return userNotificationEntities;
            })
             .then( data => {
                 return {
                     message: success.SAVE_SUCCESS,
                     data
                 };
            }).catch( error => {
                 logger.error(error);
                 return t.rollback();
             })
        } catch (error) {
            logger.error(error);
        }
```

This is  my code create data at the service:
**t : a transaction object** 
 ```js
createBatch: async (params, t) => {
        try {
            const promises = (params, t) => {
                let res = [];
                const table = params.nameTable;
                params.models.map(async model => {
                    res.push(await strapi.query(`${table}`).create(model, { transacting: t }));
                });
                return res;
            };

            return await Promise.all(promises(params, t));
        } catch (error) {
            logger.error(error);
        }
    },
```

**And these are the errors I got
Many thanks**
`
[2020-03-31T05:48:29.928Z] debug POST /notifications/privatePushCreate (446 ms) 200
(node:27281) UnhandledPromiseRejectionWarning: Error: Transaction query already complete, run with DEBUG=knex:tx for more info
    at completedError (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/knex/lib/transaction.js:364:9)
    at /Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/knex/lib/transaction.js:330:24
    at Promise._execute (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL.trxClient.query (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/knex/lib/transaction.js:326:12)
    at Runner.query (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/knex/lib/runner.js:135:36)
    at /Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:673:18)
(node:27281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27281) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27281) UnhandledPromiseRejectionWarning: Error: Transaction query already complete, run with DEBUG=knex:tx for more info
    at completedError (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/knex/lib/transaction.js:364:9)
    at /Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/knex/lib/transaction.js:330:24
    at Promise._execute (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/admin/Documents/NexlePrj/StarClub/star-club-api/node_modules/bluebird/js/release/promise.js:518:18)
`

**Comment by alexandrebodin** [comment]
Have you tried returning a promise instead of passing an async function to transaction ? I'm pretty sure kenx doesn't support this. You need to do 

```js
connection.transaction(trx => doSomething(trx))

const doSomething = async() => {}
```

instead of 

```js
connection.transaction(async trx => {})
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
