### ISSUE TITLE
Error .split() is undefined for obj assoc (Mongo)

### ISSUE THREAD

**Issue by crhraphael** [strapi/strapi#5757]
https://github.com/strapi/strapi/blob/7b9d72e210bb5da6ad6b793b12efcc3438e36473/packages/strapi-connector-mongoose/lib/buildQuery.js#L524

## PROBLEM

using deep filters and deep populate with strapi-connector-mongoose like 'model.slug'='veehicle-01' i throws error .split() is undefined, because my populate items is an object and it expects a string.

It's nice to mention that the populate with object works if no filters are given to the method. Giving the impression that some test cases are missing if the behavior is intentional.

GET to /vehicles?model.slug='veehicle-01'
```
strapi.query('vehicle').find(filters, [{
  path: 'model',
  populate: {
    path: 'slug'
  }
}])
```

Is there another way to use populate besides string? Because deep associations like 'model.brand' with mongoose doesn't work at all for me, using `3.0.0-beta.19.5`

[EDIT]

Looking further, `computePopulatedPaths` does the trick for both deep filtering and populates, since populate in mongoose can be used as object, there should be a way to handle with path as object for populate there.

#### STEP 1:
- Create 3 models: brand, model, vehicle with title as text field for example:

brand belongsToMany models
models hasMany brands
models belongsToMany vehicles
models hasMany vehicles

#### STEP 2:
- populate the collections with the admin panel.. 2 of each for testing api query filters..

#### STEP 3:
- override the vehicle api controller find() to always populate with ['model.brand']

#### STEP 4: 
- run GET http://127.0.0.1:8080/vehicles

##### Notice that populate didn't work

instead use the mongoose populate...

```
	{
		path: 'model',
		populate: {
			path: 'brand',
		}
	},
```

Then it populates correctly.

#### STEP 5:

- run GET http://127.0.0.1:8080/vehicles?model.brand.title=filter-a-brand

Then the exception is thrown:

```
error TypeError: path.split is not a function
    at findModelPath (/home/.../node_modules/strapi-connector-mongoose/lib/buildQuery.js:524:22)
    at populate.map.map.path (/home/.../node_modules/strapi-connector-mongoose/lib/buildQuery.js:175:18)
    at Array.map (<anonymous>)
    at computePopulatedPaths (/home/.../node_modules/strapi-connector-mongoose/lib/buildQuery.js:175:6)
    at buildDeepQuery (/home/.../node_modules/strapi-connector-mongoose/lib/buildQuery.js:64:41)
    at Object.buildQuery (/home/.../node_modules/strapi-connector-mongoose/lib/buildQuery.js:28:10)
    at buildQuery (/home/.../node_modules/strapi-connector-mongoose/node_modules/strapi-utils/lib/buildQuery.js:145:6)
    at Object.find (/home/.../node_modules/strapi-connector-mongoose/lib/queries.js:391:12)
    at Query.find (/home/.../node_modules/strapi-database/lib/queries/create-query.js:48:32)
    at Object.find (/home/.../api/vehicle/services/vehicle.js:54:33)
    at Object.find (/home/.../node_modules/strapi/lib/core-api/controller.js:72:34)
    at dispatch (/home/.../node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/home/.../node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at dispatch (/home/.../node_modules/koa-compose/index.js:42:32)
    at policies.push (/home/.../node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:77:28)
    at dispatch (/home/.../node_modules/koa-compose/index.js:42:32)
    at module.exports (/home/.../node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:97:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-04-14T16:18:44.215Z] debug GET /vehicles?model.brand.title=Audi (421 ms) 500
```

### POSSIBLE SOLUTION

Add this: 

```
const pathObjToPathString = (pathObj, pathStr = '') => {
	if(!pathObj.path) return pathObj;
	
	pathStr += (pathStr === '')
		? pathObj.path
		: '.' + pathObj.path
	
	if(pathObj.populate) {
		pathStr = pathObjToPathString(pathObj.populate, pathStr);
	}

	return pathStr;
};
```

Change this:

```
const computePopulatedPaths = ({ model, populate = [], where = [] }) => {
  const castedPopulatePaths = populate
		.map(el => (Array.isArray(el) 
			? el.join('.') 
			: (el.path) 
				? pathObjToPathString(el)
				: el))

...
```

**Comment by lauriejim** [comment]
Hello @crhraphael !
Thank you for reporting this.
Can you please provide the exact steps to be able to reproduce your issue.
Thank you.

**Comment by crhraphael** [comment]
It's there now.

**Comment by lauriejim** [comment]
This is working on the stable version of Strapi.
We only support strings for the data population (Bookshelf and Mongoose)
