### ISSUE TITLE
GraphQL plugin and the register mutation input customization

### ISSUE THREAD

**Issue by gfpacheco** [strapi/strapi#5834]
**Describe the bug**
The `UserInput` for the `register` mutation has all the private fields in it.

**Steps to reproduce the behavior**

1. Create a new project `yarn create strapi-app my-project --quickstart`
2. Install GraphQL plugin
3. Open the GraphQL Playground: http://localhost:1337/graphql
4. You can register sending all the fields:

```
type UserInput {
  username: String!
  email: String!
  provider: String
  password: String
  resetPasswordToken: String
  confirmed: Boolean
  blocked: Boolean
  role: ID
}
```

**Expected behavior**
You shouldn't be able to send `resetPasswordToken`, `confirmed`, `blocked` and `role`.

**System**

Node.js version: v12.16.1
NPM version: 6.13.4
Strapi version: 3.0.0-beta.19.5
Database: SQLite
Operating system: Mac

Any instructions on how to customize the `UserInput` schema while this isn't fixed?

**Comment by lauriejim** [comment]
Hello @gfpacheco ! 
I ping @alexandrebodin to have his point of view.
If we do that in the GraphQL schema, why not in the REST API too?

After that, I just followed the documentation - https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#customise-the-graphql-schema
But the extension file I generated is merged with the original one.

**Path —** `extensions/users-permissions/config/schema.graphql.js`
```js
module.exports = {
  definition: `
    type UserInput {
      username: String!
      email: String!
    }
  `,
};
```
**Error message**
```
error Error: There can be only one type named "UserInput".

Field "UserInput.username" can only be defined once.

Field "UserInput.email" can only be defined once.
    at assertValidSDL (/Users/jimlaurie/Documents/Applications/sqilte/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/Users/jimlaurie/Documents/Applications/sqilte/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/jimlaurie/Documents/Applications/sqilte/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (/Users/jimlaurie/Documents/Applications/sqilte/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/jimlaurie/Documents/Applications/sqilte/node_modules/strapi-plugin-graphql/services/schema-generator.js:85:20)
    at Object.initialize (/Users/jimlaurie/Documents/Applications/sqilte/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:79:9)
    at /Users/jimlaurie/Documents/Applications/sqilte/node_modules/strapi/lib/hooks/index.js:37:28
```

**Comment by alexandrebodin** [comment]
Hi, Indeed we should review this schema. 
Types cannot be overwritten in graphql like @lauriejim. What you can do is overwritte the resolver so you ignore those parameters for now.

This would be a quick PR to make if you feel like it @gfpacheco ;)

**Comment by gfpacheco** [comment]
@alexandrebodin That sounds like a good first PR!

I already overwrote the resolver [for another reason](https://github.com/strapi/strapi/pull/5675#issuecomment-615270921).
