### ISSUE TITLE
"Strapi start" sometimes crashes with an error, also when calling graphql same error appears

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#5918]
**Describe the bug**
Sometimes when I start the server with "strapi start" I get this error. Also if the server started successfully sometimes when I do graphql call it prints the same error. This error is random and new I was using the same project for a long time, also it happens with another live project of mine.
This is the compelte log after I use strapi start:

```
(node:244) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
[2020-04-23T08:49:42.079Z] info File changed: E:\driveE\hadas backup 19-4-20\cms\server/plugins/graphql/config/generated/schema.graphql
(node:244) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
(node:244) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
[2020-04-23T08:49:45.544Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2020-04-23T08:49:45.544Z] warn Perhaps you forgot to call it?
[2020-04-23T08:49:45.550Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2020-04-23T08:49:45.551Z] warn Perhaps you forgot to call it?
(node:244) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
undefined:1
return typeof s === "string" ? %FlattenString(s) : s
                               ^

SyntaxError: Unexpected token '%'
    at EventEmitter.pinoWrite (E:\driveE\hadas backup 19-4-20\cms\server\node_modules\pino\pino.js:225:18)
    at EventEmitter.LOG (E:\driveE\hadas backup 19-4-20\cms\server\node_modules\pino\lib\tools.js:93:10)
    at restart (C:\Users\Omer\AppData\Roaming\npm\node_modules\strapi\bin\strapi-start.js:63:22)
    at StatWatcher.<anonymous> (C:\Users\Omer\AppData\Roaming\npm\node_modules\strapi\bin\strapi-start.js:90:45)
    at StatWatcher.emit (events.js:315:20)
    at StatWatcher.EventEmitter.emit (domain.js:485:12)
    at StatWatcher.onchange (internal/fs/watchers.js:57:8)
```

After the error the server is stuck and you should restart it

**Steps to reproduce the behavior**
run "strapi start", or make a graphql call
The error is random, happens 40% of the time

**Expected behavior**
No error should be printed

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version:  13.12
- NPM version: 6.14
- Strapi version:  latest
- Database: mLab
- Operating system: windows 10 (also happens on Linux)

**Additional context**

**Comment by lauriejim** [comment]
Hello! Can you please precise the version of Strapi you are using.
I think the latest is no longer the latest.

**Comment by lauriejim** [comment]
If the error happens "sometimes", it will be hard to help you.
It's probably related to server performance strapi or database.
