### ISSUE TITLE
Collection type field validation is not case-insensitive

### ISSUE THREAD

**Issue by Lion7de** [strapi/strapi#5963]
First of all: Great work! I'm only experimenting with strapi for a couple of days now but i already fell in love with it.

**Describe the bug**
I just ran into an issue when i edited one of my collections and accidentally gave two fields in my collection type the same name but not the same letter casing. 
Looks like the name validation for collection type field is not case-insensitive, but the GraphQL validation is. (See logs - I didn't reproduce the issue without graphql installed.)

Collection Type Name: "Categories"
1. Text field with Name: "name"
2. UID field with Name: "Name"

**Steps to reproduce the behavior**
The steps are exactly what i did but of course it should be reproducable with any names for the collection and fields.

1. Create a Collection Type named "Categories" with a text field "name"
2. Edit the Collection Type again and add a UID field "Name" attached to the "name" field.
3. Strapi/Docker will stop working. 

**Expected behavior**
Although i it doesn't make sense to give two fields the same name, input validation should have warned that the name already exists.

**Logs before server shut down**

```[2020-04-26T22:12:20.238Z] debug GET /content-type-builder/components (89 ms) 200
[2020-04-26T22:12:20.275Z] debug GET /content-type-builder/content-types (33 ms) 200
[2020-04-26T22:12:47.009Z] info File changed: /srv/app/api/categories/models/categories.settings.json
[2020-04-26T22:12:47.013Z] debug PUT /content-type-builder/content-types/application::categories.categories (66 ms) 201
[2020-04-26T22:12:47.015Z] info The server is restarting

[2020-04-26T22:13:03.229Z] debug ⛔️ Server wasn't able to start properly.
[2020-04-26T22:13:03.233Z] error Error: There can be only one type named "CategoriesConnectionName".

Field "CategoriesConnectionName.key" can only be defined once.

Field "CategoriesConnectionName.connection" can only be defined once.
    at assertValidSDL (/srv/app/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/srv/app/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/srv/app/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (/srv/app/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/srv/app/node_modules/strapi-plugin-graphql/services/schema-generator.js:85:20)
    at Object.initialize (/srv/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:79:9)
    at /srv/app/node_modules/strapi/lib/hooks/index.js:37:28
Starting your app...
[2020-04-26T22:18:56.177Z] debug ⛔️ Server wasn't able to start properly.
[2020-04-26T22:18:56.179Z] error Error: There can be only one type named "CategoriesConnectionName".

Field "CategoriesConnectionName.key" can only be defined once.

Field "CategoriesConnectionName.connection" can only be defined once.
    at assertValidSDL (/srv/app/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/srv/app/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/srv/app/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (/srv/app/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/srv/app/node_modules/strapi-plugin-graphql/services/schema-generator.js:85:20)
    at Object.initialize (/srv/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:79:9)
    at /srv/app/node_modules/strapi/lib/hooks/index.js:37:28
```

**System**
- Docker image: strapi/strapi
- Node.js version: v12.13.0
- Strapi version: 3.0.0-beta.20
- Database: MongoDB

**Comment by lauriejim** [comment]
This issue has been fixed in the stable version of Strapi, this is not possible.
