### ISSUE TITLE
TypeError: Cannot read property 'queries' of undefined

### ISSUE THREAD

**Issue by ABoyd002** [strapi/strapi#6043]
Hello, I am having an issue when I try to run `npm run develop` I keep getting this error,

```
$ strapi develop
[2020-05-03T18:35:32.297Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-03T18:35:32.299Z] error TypeError: Cannot read property 'queries' of undefined
ger.js:91:7)
    at createWebhookStore (C:\Users\arran\WebstormProjects\wynx\wynx_backend\node_modules\strapi\lib\services\webhook-store.js
:57:29)
    at Strapi.load (C:\Users\arran\WebstormProjects\wynx\wynx_backend\node_modules\strapi\lib\Strapi.js:278:25)
    at async Strapi.start (C:\Users\arran\WebstormProjects\wynx\wynx_backend\node_modules\strapi\lib\Strapi.js:130:7)
error Command failed with exit code 1.
```
I was using v3.0.0-beta.20 when this happend and tried to update the packages but I still get the error.

**System**

- Node.js version: 12.16.3
- NPM version: 6.13.6
- Strapi version: v3.0.0-beta.20.1
- Database: SQLite
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
@ABoyd002 this is likely due some cached package, purge the following files/folders and reinstall/rebuild

- `build`
- `node_modules`
- `.cache`
- `package-lock.json`
- `yarn.lock`

I'm going to close this as it isn't an issue with Strapi directly but if you need further help don't hesitate to reply

**Comment by ABoyd002** [comment]
@derrickmehaffy I deleted all the files/folders you said to but I still get the same error

**Comment by derrickmehaffy** [comment]
Do you have any custom controllers/services or any modifications to plugins via extensions?
