### ISSUE TITLE
App broken after installing graphql plugin

### ISSUE THREAD

**Issue by aidenBarrett96** [strapi/strapi#6090]
**Describe the bug**
A clear and concise description of what the bug is

After installing the Graphql plugin I can no longer start the application. I originally added the plugin on the UI admin area, this took a very long time and eventually restarted with no prompt telling me it was installed, the graphql endpoint was still not available.

After this didn't work I tried to restart the application and was given the following error: 
```
yarn run v1.16.0
$ strapi develop
[2020-05-06T10:04:49.770Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-06T10:04:49.772Z] error Error: There can be only one type named "ComponentProjectCategoryInput".

There can be only one type named "editComponentProjectCategoryInput".

Field "editComponentProjectCategoryInput.id" can only be defined once.
    at assertValidSDL (D:\projects\npk-media-v2\strapi_v2\node_modules\graphql\validation\validate.js:108:11)
    at Object.buildASTSchema (D:\projects\npk-media-v2\strapi_v2\node_modules\graphql\utilities\buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (D:\projects\npk-media-v2\strapi_v2\node_modules\graphql-tools\dist\generate\buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (D:\projects\npk-media-v2\strapi_v2\node_modules\graphql-tools\dist\makeExecutableSchema.js:26:29)
    at Object.generateSchema (D:\projects\npk-media-v2\strapi_v2\node_modules\strapi-plugin-graphql\services\schema-generator.js:85:20)
    at Object.initialize (D:\projects\npk-media-v2\strapi_v2\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:79:9)
    at D:\projects\npk-media-v2\strapi_v2\node_modules\strapi\lib\hooks\index.js:37:28
error Command failed with exit code 1.
```

I then tried to uninstall the plugin from the CLI and reinstall from here, also resulting in the same error message.

**System**

- Node.js version: v12.12.0
- NPM version:6.14.4
- Strapi version: 3.0.0-beta.20.1
- Database: Mongo
- Operating system: Windows

**Comment by mihaiblaga89** [comment]
would be nice if you added a comment with the solution instead of just closing the issue...
