### ISSUE TITLE
Unable to delete single image

### ISSUE THREAD

**Issue by DarkTraveler** [strapi/strapi#6235]
Hey
**Describe the bug**
On version beta.20.3, you can’t delete single photos. Multiple load fields have no such problems.

When I try to delete the image, I get the following message: Cast to ObjectId failed for value "[]" at path "test"

**before:**
![80867057-73fb6780-8cd5-11ea-8c84-6d298764c2bf](https://user-images.githubusercontent.com/16899697/82122962-22290600-97da-11ea-9455-964bbb49bf0d.png)

**after i try to delete images:**
![80867077-8ecddc00-8cd5-11ea-9909-655f6c337928](https://user-images.githubusercontent.com/16899697/82122974-379e3000-97da-11ea-8af3-8031312f97f4.png)

**then i delete the images from the multiple field:**
![80867120-bde44d80-8cd5-11ea-9c22-e37600a5576e](https://user-images.githubusercontent.com/16899697/82122993-4a186980-97da-11ea-9ff6-7afa5a3ee4af.png)

**and then again try to remove from a single:**
![80867139-d2c0e100-8cd5-11ea-8170-f390aec8f256](https://user-images.githubusercontent.com/16899697/82123009-5ac8df80-97da-11ea-9ed0-97f8a3b6cd03.png)

**reload page**
![80867143-e2402a00-8cd5-11ea-83bf-951de539e5ff](https://user-images.githubusercontent.com/16899697/82123016-687e6500-97da-11ea-8a8d-68d835543a9f.png)

**System**
nodejs v12.14.1
NPM v6.13.4
Strapi version: 3.0.0-beta.20.3
Database: mongodb
Operating system: WSL Windows 10 - Ubuntu 18.04/Ubuntu 20.4

while I was able to get around this problem in the following way:

![image](https://user-images.githubusercontent.com/16899697/82123872-11c75a00-97df-11ea-8ac5-4032dfd9c0d5.png)

**Comment by DimitrieStraoanu** [comment]
I have the same problem too. I've tested the beta-20 release and found the same behaviour.

System
nodejs v12.14.0
NPM v6.14.5
Strapi version: 3.0.0-beta.20.3
Database: mongodb
Operating system: Windows 10

**Comment by lsliwaradioluz** [comment]
I discovered that today as well. Tested with two separate beta-20 apps of mine. Both throw the same error while trying to delete single image.

**Comment by lauriejim** [comment]
Hello! Can you let me know when I should save the update, for each screen ?

**Comment by DimitrieStraoanu** [comment]
Hello,  @lauriejim if you are trying to reproduce the error this are the steps to follow:

1. create a content type with a field type **single media**
![Asset 3-80](https://user-images.githubusercontent.com/48469159/82790758-44272600-9e75-11ea-825f-82b84ab5a316.jpg)

2. create an entry, add an image click finish then save
![Asset 2-80](https://user-images.githubusercontent.com/48469159/82790775-4c7f6100-9e75-11ea-999e-ffd045de4f27.jpg)

3. then open the entry, delete the image and try to save the entry
![Asset 1-80](https://user-images.githubusercontent.com/48469159/82790784-51441500-9e75-11ea-8a2b-dbdfd204fc7e.jpg)

this is the error from the console:
``
[2020-05-25T07:43:31.440Z] error CastError: Cast to ObjectId failed for value "[]" at path "image"
    at new CastError (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\error\cast.js:39:11)
    at ObjectId.cast (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\schema\objectid.js:246:11)
    at ObjectId.SchemaType.applySetters (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\schematype.js:975:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\schematype.js:1389:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\schematype.js:1379:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\schematype.js:1358:15)
    at castUpdateVal (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\helpers\query\castUpdate.js:511:19)
    at walkUpdatePath (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\helpers\query\castUpdate.js:338:22)
    at castUpdate (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\helpers\query\castUpdate.js:95:18)
    at model.Query._castUpdate (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\query.js:4495:10)
    at castDoc (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\query.js:4523:18)
    at model.Query._updateThunk (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\query.js:3722:20)
    at model.Query.<anonymous> (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\query.js:3817:23)
    at model.Query._wrappedThunk [as _updateOne] (C:\Users\Home\Desktop\strapi-app\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at C:\Users\Home\Desktop\strapi-app\node_modules\kareem\index.js:278:20
    at _next (C:\Users\Home\Desktop\strapi-app\node_modules\kareem\index.js:102:16)
``
