### ISSUE TITLE
Strapi fails if we create a collection called "files"

### ISSUE THREAD

**Issue by jmaferreira** [strapi/strapi#6236]
**Describe the bug**

Strapi fails if we create a collection called "files".

```
error Error: There can be only one type named "FileInput".

There can be only one type named "editFileInput".
    at assertValidSDL (/Users/mferreira/git/strapi-tests/folder-scanner/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/Users/mferreira/git/strapi-tests/folder-scanner/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/mferreira/git/strapi-tests/folder-scanner/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (/Users/mferreira/git/strapi-tests/folder-scanner/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/mferreira/git/strapi-tests/folder-scanner/node_modules/strapi-plugin-graphql/services/schema-generator.js:85:20)
    at Object.initialize (/Users/mferreira/git/strapi-tests/folder-scanner/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:79:9)
    at Promise.resolve.then (/Users/mferreira/git/strapi-tests/folder-scanner/node_modules/strapi/lib/hooks/index.js:37:28)
```
**Steps to reproduce the behavior**

1. Go to 'Contet-Type Builder'
2. Create a Collection called "files"
4. The application crashes with the error shown above.

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by jmaferreira** [comment]
You're right. Updating the node version to v12 fixed the issue. Thanks.
