### ISSUE TITLE
Knex: Timeout acquiring a connection after upgrade to beta.20.3

### ISSUE THREAD

**Issue by skrty** [strapi/strapi#6249]
**Describe the bug**
Knex: Timeout acquiring a connection after upgrade to beta.20.3.

**Steps to reproduce the behavior**
After upgrading from beta.20.2 to beta.20.3 I receive following error.
Manual downgrade of strapi-connector-bookshelf to version 3.0.0-beta.20.2 fixes the issue.

```ssh
[2020-05-18T13:15:20.010Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-18T13:15:20.014Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\knex\lib\client.js:318:17
    at tryCatcher (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\catch_filter.js:17:41
    at tryCatcher (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Work\digital-congress\digital_congress_webpage_strapi\dcw_api\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

**System**

- Node.js version: 
- NPM version: v12.16.1
- Strapi version: beta.20.3
- Database: PostgreSQL 10 (Azure hosted)
- Operating system: linux / windows

**Comment by derrickmehaffy** [comment]
@alexandrebodin I'm seeing more and more of this as of late, wondering if we need to start applying some default increased timeouts with the tarn pooling configs :thinking:

**Comment by derrickmehaffy** [comment]
@skrty see the pool config part of the database docs: https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#database

**Comment by skrty** [comment]
I can confirm that updating database.json with 
```json
      "options": {
        "pool": {
          "acquireTimeoutMillis": 10000,
          "createTimeoutMillis": 10000
        }
      }
```

resolved the issue. Thanks!
