### ISSUE TITLE
Enum cannot have value Null

### ISSUE THREAD

**Issue by werty37** [strapi/strapi#6287]
**Describe the bug**
Strapi not letting a string/value of "Null" in an ENUM type in a Collection. 

**Steps to reproduce the behavior**
1. Go to any Collection type
2. Click on the edit icon on any one ENUM type.
3. In the values, add "Null" as one of the values.
4. Click Finish button
5. Hit Save button

**Expected behavior**
Strapi to accept the value of "Null" in ENUM type.

**System**
- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: v3.0.0-beta.20.3
- Database:  PostgreSQL 12.3 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit
- Operating system: macOS Mojave 10.14.6

**Additional context**
```
[2020-05-20T06:51:45.881Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-20T06:51:45.883Z] error Error: Enum type ENUM_TRANSACTIONSRAZORPAY_REFUND_STATUS cannot include value: null.
    at assertValidSchema (/Volumes/Application/dr_api/node_modules/graphql/type/validate.js:71:11)
    at assertValidExecutionArguments (/Volumes/Application/dr_api/node_modules/graphql/execution/execute.js:136:35)
    at executeImpl (/Volumes/Application/dr_api/node_modules/graphql/execution/execute.js:86:3)
    at Object.execute (/Volumes/Application/dr_api/node_modules/graphql/execution/execute.js:64:63)
    at Object.generateSchemaHash (/Volumes/Application/dr_api/node_modules/apollo-server-core/dist/utils/schemaHash.js:14:32)
    at ApolloServer.generateSchemaDerivedData (/Volumes/Application/dr_api/node_modules/apollo-server-core/dist/ApolloServer.js:283:41)
    at new ApolloServerBase (/Volumes/Application/dr_api/node_modules/apollo-server-core/dist/ApolloServer.js:198:38)
    at new ApolloServer (/Volumes/Application/dr_api/node_modules/apollo-server-koa/dist/ApolloServer.js:63:1)
    at Object.initialize (/Volumes/Application/dr_api/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:119:22)
    at /Volumes/Application/dr_api/node_modules/strapi/lib/hooks/index.js:37:28
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! a@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the a@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/werrt37/.npm/_logs/2020-05-20T06_51_45_896Z-debug.log
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by werty37** [comment]
@derrickmehaffy I have updated the bug report.

**Comment by lauriejim** [comment]
Hello! I just tried and it works well on my side.
Can you send me a screenshot of the textarea that contains your values please. Thank you.

**Comment by werty37** [comment]
Hi, Here are the screenshots. The server does not restart. I have also included the error thrown in the terminal.

<img width="1552" alt="1" src="https://user-images.githubusercontent.com/22869624/83001644-aa54aa00-a029-11ea-86a7-0f5cb4bf43ca.png">
<img width="1552" alt="2" src="https://user-images.githubusercontent.com/22869624/83001650-ab85d700-a029-11ea-8db0-b0727ac89d4f.png">
<img width="1552" alt="3" src="https://user-images.githubusercontent.com/22869624/83001617-a2950580-a029-11ea-95c1-2d6a8298573e.png">
<img width="1552" alt="4" src="https://user-images.githubusercontent.com/22869624/83001639-a9237d00-a029-11ea-8d7e-24d92538a6ce.png">

```
[2020-05-27T09:20:02.251Z] info The server is restarting

[2020-05-27T09:20:04.184Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-27T09:20:04.186Z] error Error: Enum type ENUM_TRANSACTIONSRAZORPAY_TESTENUM cannot include value: null.
    at assertValidSchema (/Volumes/DATA/Projects/tele_api/node_modules/graphql/type/validate.js:71:11)
    at assertValidExecutionArguments (/Volumes/DATA/Projects/tele_api/node_modules/graphql/execution/execute.js:136:35)
    at executeImpl (/Volumes/DATA/Projects/tele_api/node_modules/graphql/execution/execute.js:86:3)
    at Object.execute (/Volumes/DATA/Projects/tele_api/node_modules/graphql/execution/execute.js:64:63)
    at Object.generateSchemaHash (/Volumes/DATA/Projects/tele_api/node_modules/apollo-server-core/dist/utils/schemaHash.js:14:32)
    at ApolloServer.generateSchemaDerivedData (/Volumes/DATA/Projects/tele_api/node_modules/apollo-server-core/dist/ApolloServer.js:283:41)
    at new ApolloServerBase (/Volumes/DATA/Projects/tele_api/node_modules/apollo-server-core/dist/ApolloServer.js:198:38)
    at new ApolloServer (/Volumes/DATA/Projects/tele_api/node_modules/apollo-server-koa/dist/ApolloServer.js:63:1)
    at Object.initialize (/Volumes/DATA/Projects/tele_api/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:119:22)
    at /Volumes/DATA/Projects/tele_api/node_modules/strapi/lib/hooks/index.js:37:28
```

**Comment by derrickmehaffy** [comment]
Do you have the enum set as required with no default? (also you should not put `null` in the list of values)

**Comment by werty37** [comment]
@derrickmehaffy I have not set the enum as required. Please see the screenshots. A dependency (Razorpay) is returning null as one of the return values for refund_status, hence I am trying to use it without any change.

https://razorpay.com/docs/api/payments/#payment-entity

I am attaching screenshots to show the process. 
<img width="1552" alt="1" src="https://user-images.githubusercontent.com/22869624/83116220-177b4480-a0e9-11ea-85ce-7e8d4b552f9f.png">
<img width="1552" alt="2" src="https://user-images.githubusercontent.com/22869624/83116226-1b0ecb80-a0e9-11ea-9540-3d96eaaf5619.png">
<img width="1552" alt="3" src="https://user-images.githubusercontent.com/22869624/83116254-2530ca00-a0e9-11ea-8a81-7a7ea1c2c982.png">
<img width="1552" alt="4" src="https://user-images.githubusercontent.com/22869624/83116289-32e64f80-a0e9-11ea-81ad-17aa1b4663be.png">
![Uploading 5.png…]()

This is the JSON model of the collection to which I added the enum to.

```
{
  "kind": "collectionType",
  "collectionName": "medical_specialists",
  "info": {
    "name": "medical_specialist"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "specialism": {
      "type": "string"
    },
    "refund_status": {
      "type": "enumeration",
      "enum": [
        "null",
        "partial",
        "full"
      ]
    }
  }
}
```

**Comment by lauriejim** [comment]
Hello! I just tried again with laster version of Strapi 3.0.1 and this version of PG 12.1-1.pgdg100+1
And every thing works well.
I think it's coming from your database configuration, I'm not seeing anything else.

**Comment by jorisw** [comment]
I can confirm that `null` will not work in an enum. `"null"` might, but that's a string and not `null`.

Your best bet is to not use an enum if you want to able to set `null`.

This may differ between platforms/languages, but in this case we're talking about GraphQL types. The GraphQL layer will throw:

```
Error: Enum type ENUM_COMPONENTSTATUSESSTATUS_STATUS cannot include value: null
```
