### ISSUE TITLE
Error on start with mongo rc.1

### ISSUE THREAD

**Issue by sandrotaje** [strapi/strapi#6296]
**Describe the bug**
Error on start with mongo rc.1

**Steps to reproduce the behavior**

1. Init with npx create-strapi-app@rc my-test --quickstart
2. Change database.js with this 

```javascript 
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        client: 'mongo',
        "host": env("DATABASE_HOST",""),
        "port": env("DATABASE_PORT",""),
        "database": env("DATABASE_NAME",""),
        "username": env("DATABASE_USERNAME",""),
        "password": env("DATABASE_PASSWORD","")
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});
```

3. yarn develop

**Expected behavior**
Strapi should start

**System**

- Node.js version: v12.11.1
- NPM version: 6.14.4
- Strapi version: rc.1
- Database: mongo
- Operating system: Window 10

**Additional context**
The stacktrace say this:
```
[2020-05-20T15:02:49.678Z] error TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at checkReservedAttributeNames (C:\Users\Sandro.LAPTOP-JQ2UC9CT\workspaces\intellij\test-strapi-3\node_modules\strapi-database\lib\validation\check-reserved-names.js:20:54)
    at C:\Users\Sandro.LAPTOP-JQ2UC9CT\workspaces\intellij\test-strapi-3\node_modules\strapi-database\lib\validation\check-reserved-names.js:65:5
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Sandro.LAPTOP-JQ2UC9CT\workspaces\intellij\test-strapi-3\node_modules\strapi-database\lib\validation\check-reserved-names.js:63:68)
    at validateModelSchemas (C:\Users\Sandro.LAPTOP-JQ2UC9CT\workspaces\intellij\test-strapi-3\node_modules\strapi-database\lib\validation\index.js:8:3)
    at DatabaseManager.initialize (C:\Users\Sandro.LAPTOP-JQ2UC9CT\workspaces\intellij\test-strapi-3\node_modules\strapi-database\lib\database-manager.js:34:5)
    at Strapi.load (C:\Users\Sandro.LAPTOP-JQ2UC9CT\workspaces\intellij\test-strapi-3\node_modules\strapi\lib\Strapi.js:299:19)
    at async Strapi.start (C:\Users\Sandro.LAPTOP-JQ2UC9CT\workspaces\intellij\test-strapi-3\node_modules\strapi\lib\Strapi.js:162:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by derrickmehaffy** [comment]
`useNullAsDefault: true,` Need to remove this, and did you also install the proper connector for mongoose?

**Comment by sandrotaje** [comment]
Yes this is my package.json
```javascript
{
  "name": "test-strapi-3",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "cross-env PORT=1338 strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {
    "cross-env": "^7.0.2"
  },
  "dependencies": {
    "strapi": "3.0.0-rc.1",
    "strapi-admin": "3.0.0-rc.1",
    "strapi-utils": "3.0.0-rc.1",
    "strapi-plugin-content-type-builder": "3.0.0-rc.1",
    "strapi-plugin-content-manager": "3.0.0-rc.1",
    "strapi-plugin-users-permissions": "3.0.0-rc.1",
    "strapi-plugin-email": "3.0.0-rc.1",
    "strapi-plugin-upload": "3.0.0-rc.1",
    "strapi-connector-bookshelf": "3.0.0-rc.1",
    "strapi-connector-mongoose": "3.0.0-rc.1",
    "knex": "<0.20.0",
    "sqlite3": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "74deb859-5575-4ced-ae71-5340f3283bcc"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

I tried to remove `useNullAsDefault: true` but error remain.

**Comment by alexandrebodin** [comment]
@sandrotaje Didi you cleanup your yarn lock ? I think you still have code from the beta running

**Comment by alexandrebodin** [comment]
I might have found an issue, did you delete a timestamps key in one of your models ?

**Comment by lauriejim** [comment]
Hello! I just tried and it works well.
Fresh new app using your command, used your `database.js` config and all worked well.

**Comment by sandrotaje** [comment]
I retried from start and now it works, the only thing that I have changed from the first time is the options useNullAsDefault: true.
Now I started the first time without it and it works. Perhaps is this the problem. 
Anyway now it works. 
Thank you for your time, and congratulation for the awesome job.
