### ISSUE TITLE
Cannot run Strapi on Heroku with mongodb (Atlas)

### ISSUE THREAD

**Issue by podeig** [strapi/strapi#6435]
Hi,
The project works locally with connection to Atlas, but on Heroku I get error:

**Error: listen EADDRNOTAVAIL: address not available 34.249.148.208:3140**

```
2020-05-29T14:54:19.247173+00:00 heroku[web.1]: Starting process with command `npm start`
2020-05-29T14:54:22.459182+00:00 app[web.1]: 
2020-05-29T14:54:22.459242+00:00 app[web.1]: > oskogen-cms-mongo@0.1.0 start /app
2020-05-29T14:54:22.459243+00:00 app[web.1]: > strapi start
2020-05-29T14:54:22.459243+00:00 app[web.1]: 
2020-05-29T14:54:24.499126+00:00 app[web.1]: (node:23) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
2020-05-29T14:54:24.499164+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2020-05-29T14:54:24.499792+00:00 app[web.1]: (node:23) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
2020-05-29T14:54:24.499905+00:00 app[web.1]: (node:23) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
2020-05-29T14:54:24.499997+00:00 app[web.1]: (node:23) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
2020-05-29T14:54:25.481257+00:00 app[web.1]: [2020-05-29T14:54:25.480Z] error Error: listen EADDRNOTAVAIL: address not available 34.249.148.208:3140
2020-05-29T14:54:25.481265+00:00 app[web.1]:     at Server.setupListenHandle [as _listen2] (net.js:1296:21)
2020-05-29T14:54:25.481266+00:00 app[web.1]:     at listenInCluster (net.js:1361:12)
2020-05-29T14:54:25.481267+00:00 app[web.1]:     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:7)
2020-05-29T14:54:25.481268+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
```

I defined the following app vars:
HOST=0.0.0.0
PORT=1337
DATABASE_HOST="odega.......mongodb.net/test?retryWrites=true"
DATABASE_PORT="27017"
DATABASE_NAME="od...db"
DATABASE_USERNAME="Ode...er"
DATABASE_PASSWORD="******"
HOST=oskogen-cms-mongo.herokuapp.com
PORT=""

Database.js
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        client: "mongo",
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', ''),
        password: env('DATABASE_PASSWORD', ''),
        srv: true,
        ssl: { rejectUnauthorized: false }
      },
      options: {
        ssl: true,
        authenticationDatabase: "",
        useUnifiedTopology: true,
        debug: false,
      }
    },
  },
});
```

Server.js
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
});
```

Please HELP! I have user so much time to fix it :-(

I use "strapi": "3.0.1",

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
