### ISSUE TITLE
Unable to install Media Library in Strapi 3.0.1

### ISSUE THREAD

**Issue by asdutoit** [strapi/strapi#6472]
Hi Guys, 

I am unable to install Media Library for Strapi 3.0.1

The following is an output from terminal during the installation:

```
[2020-05-31T12:07:04.689Z] info Installing upload...
[2020-05-31T12:07:19.428Z] error Error: Command failed: npm run strapi -- install upload
- Installing dependencies
Command failed: yarn add strapi-plugin-upload@3.0.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning "strapi-admin > @buffetjs/core > react-dates@21.8.0" has unmet peer dependency "react-with-direction@^1.3.1".
warning "strapi-plugin-graphql > graphql-playground-middleware-koa@1.6.14" has unmet peer dependency "koa@^2".
warning "strapi-plugin-graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
warning "strapi-plugin-users-permissions > grant-koa@5.1.1" has unmet peer dependency "koa@>=2.0.0".
error /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi-plugin-upload/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi-plugin-upload/node_modules/sharp
Output:
info sharp Using cached /Users/stephandutoit/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.3.0 runtime=node arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi-plugin-upload/node_modules/sharp
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-project-1@0.1.0 strapi: `strapi "install" "upload"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the new-project-1@0.1.0 strapi script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephandutoit/.npm/_logs/2020-05-31T12_07_19_410Z-debug.log


> new-project-1@0.1.0 strapi /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1
> strapi "install" "upload"


    at makeError (/Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/execa/index.js:174:9)
    at /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.installPlugin (/Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi-admin/controllers/Admin.js:82:7)
    at async /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
    at async module.exports (/Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:35:14)
    at async /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi-utils/lib/policy.js:52:5
    at async /Users/stephandutoit/Dropbox/Training/Strapi/new-project-1/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-05-31T12:07:19.429Z] debug POST /admin/plugins/install (14743 ms) 400
```

**Describe the bug**
Seems like the issue has something to do with "sharp".

**Steps to reproduce the behavior**

This was a new clean installation of strapi using the `yarn create strapi-app` command.   
Installation of graphql plugin worked fine.   

**I am using Node v14.3.0.   Could that be the cause?**

**Expected behavior**
Successful installation.

**System**

- Node.js version: v14.3.0
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database: MongoDB
- Operating system:  Mac OS Catalina 10.15.5 (19F96)

**Comment by derrickmehaffy** [comment]
`I am using Node v14.3.0. Could that be the cause?` well it certainly is t going to help since it's not supported yet :p

**Comment by asdutoit** [comment]
Lol.  Yeah, I thought there might be something there.   Ill start the downgrade...

**Comment by asdutoit** [comment]
Yup, was the version of Node...  🤦‍♂️
