### ISSUE TITLE
strapi new strapiProject not working 

### ISSUE THREAD

**Issue by kapil019** [strapi/strapi#648]
**Node.js version**: v6.10.2

**npm version**: 3.10.10

**Strapi version**: 3.0.0-alpha.10.1

**Operating system**: Ubuntu 14

**Do you want to request a *feature* or report a *bug*?** report a *bug*

**What is the current behavior?**  strapi new strapiProject not working 

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?** strapi new strapiProject should work

INFO (15123 on ITPL-LPTP-038): Creating your application... It might take a few seconds.
ERROR (15123 on ITPL-LPTP-038): Invalid `new` generator.
/root/.node/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:125
          ...databaseChoice.value
          ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.node/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/index.js:21:11)

**Comment by soupette** [comment]
You need to update your node version to `v8.6` minimum. Here is the [link](https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version)
