### ISSUE TITLE
Error: Invalid format, expected an ISO compatible date

### ISSUE THREAD

**Issue by frenchqwerty** [strapi/strapi#6508]
Describe the bug
After an update from alpha to stable, I have an error when I access to Collection in Admin panel.

Steps to reproduce the behavior

Update to Beta from Alpha
Open admin panel
Open Collection
Open Row in Collection
See a message error
```
[2020-06-02T09:07:02.485Z] debug GET /content-manager/explorer/application::destination.destination/5cfcbcc36306f611c760ef51 (19 ms) 200
/srv/app/node_modules/mongodb/lib/utils.js:133
      throw err;
      ^

Error: Invalid format, expected an ISO compatible date
    at parseDate (/srv/app/node_modules/strapi-utils/lib/parse-type.js:37:11)
    at parseType (/srv/app/node_modules/strapi-utils/lib/parse-type.js:89:14)
    at model.set (/srv/app/node_modules/strapi-connector-mongoose/lib/utils/index.js:42:25)
    at SchemaString.SchemaType._applySetters (/srv/app/node_modules/mongoose/lib/schematype.js:944:22)
    at SchemaString.SchemaType.applySetters (/srv/app/node_modules/mongoose/lib/schematype.js:968:16)
    at SchemaString.SchemaType.getDefault (/srv/app/node_modules/mongoose/lib/schematype.js:922:25)
    at $__applyDefaults (/srv/app/node_modules/mongoose/lib/document.js:375:22)
    at model.Document (/srv/app/node_modules/mongoose/lib/document.js:123:5)
    at model.Model (/srv/app/node_modules/mongoose/lib/model.js:99:12)
    at new model (/srv/app/node_modules/mongoose/lib/model.js:4579:15)
    at Object.createModel (/srv/app/node_modules/mongoose/lib/queryhelpers.js:106:10)
    at completeMany (/srv/app/node_modules/mongoose/lib/helpers/query/completeMany.js:39:22)
    at cb (/srv/app/node_modules/mongoose/lib/query.js:1943:9)
    at /srv/app/node_modules/mongodb/lib/operations/execute_operation.js:75:17
    at executeCallback (/srv/app/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/srv/app/node_modules/mongodb/lib/utils.js:129:55)
```

System

Node.js version: 12.13
NPM version: 6.12
Strapi version: v3.0.0
Database: Mongo
Operating system: Via Docker

**Comment by lauriejim** [comment]
Hello! Can you please specify your migration's step.
You talked about the alpha beta and stable, it's confusing.
Can you please make sure you followed all migrations guide step by step.
I migrate in discussions because it's a migration issue you have.
