### ISSUE TITLE
More accurate auth/local/login error handling

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#6511]
**Describe the bug**
There are two issues we need to address here probably.
I get an error for a not-username relevant error, when in reality the error is something else.
So we can
1. fix the error reporting and
2. fix the error I had ;)

https://github.com/strapi/strapi/blob/1f9d6af6c9fb1aa37b1d87f166aa9b6ff03a8b46/packages/strapi-plugin-users-permissions/controllers/Auth.js#L559-L567

Probably related issues: #4463 #1361

**Steps to reproduce the behavior**

1. Create a field on content type user that is required (e.g. generates NOT NULL, no default value)
2. Register a new user through API
3. get "Username already exists"

**Expected behavior**
Since this is a highly specific MySQL error, 

**Screenshots**
![image](https://user-images.githubusercontent.com/2950505/83519336-10cf4180-a4dc-11ea-9d16-eef29ca6d98c.png)

**Code snippets**

```

Error: ER_NO_DEFAULT_FOR_FIELD: Field 'firstname' doesn't have a default value
    at Query.Sequence._packetToError (/usr/src/api/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/usr/src/api/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/usr/src/api/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/src/api/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/src/api/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/src/api/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/src/api/app/server/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/usr/src/api/app/server/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    --------------------
    at Protocol._enqueue (/usr/src/api/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/usr/src/api/app/server/node_modules/mysql/lib/Connection.js:198:25)
    at /usr/src/api/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/usr/src/api/app/server/node_modules/knex/lib/dialects/mysql/index.js:129:12)
    at Client_MySQL.query (/usr/src/api/app/server/node_modules/knex/lib/client.js:169:17)
    at /usr/src/api/app/server/node_modules/knex/lib/transaction.js:321:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/usr/src/api/app/server/node_modules/knex/lib/transaction.js:316:12)
    at Runner.query (/usr/src/api/app/server/node_modules/knex/lib/runner.js:134:36)
    at /usr/src/api/app/server/node_modules/knex/lib/runner.js:40:23
    at /usr/src/api/app/server/node_modules/knex/lib/runner.js:260:24 {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: "Field 'firstname' doesn't have a default value",
  sqlState: 'HY000',
  index: 0,
  sql: "insert into `users-permissions_user` (`created_at`, `email`, `password`, `provider`, `updated_at`, `username`) values ('2020-06-02 12:07:33.803', 'arafad@hat-kein-fara.hd', '$2a$10$16sPS3Gxh2tnGLZynOB0Qeu8kTyf.o5OV1kmvpySWnlL9razrjUba', 'local', '2020-06-02 12:07:33.803', 'arafad@hat-kein-fara.hd')"    
}
```

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.3 - code is same in current stable release also
- Database: MariaDB
- Operating system: Ubuntu Linux

**Comment by lauriejim** [comment]
Hello here is a discussion about that topic - https://github.com/strapi/strapi/issues/5560
