### ISSUE TITLE
GraphQL not installed

### ISSUE THREAD

**Issue by nanocreaator** [strapi/strapi#6538]
**Describe the bug**
Strapi was installed with OneClickApp in Digital Ocean. I tried to set GraphQl through the interface that informed me that the server took to much time to restart.

**Steps to reproduce the behavior**

1. Go to the app and enable GraphQl

2. Check logs from PM2
 [2020-06-03T21:14:47.726Z] debug ⛔️ Server wasn't able to start properly.
[2020-06-03T21:14:47.730Z] error Error: Cannot find module '/srv/strapi/strapi-development/node_modules/strapi-plugin-graphql/node_modules/graphql/index'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:319:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/srv/strapi/strapi-development/node_modules/strapi-plugin-graphql/node_modules/apollo-server-errors/dist/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
error Command failed with exit code 1.

**Expected behavior**
A GraphQl installed
**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.3"
- Database: PG
- Operating system: Ubuntu

When run in dev mode and clicking to remove the AddOn I have:

> strapi "uninstall" "graphql" "-d"
    at makeError (/srv/strapi/strapi-development/node_modules/execa/index.js:174:9)
    at /srv/strapi/strapi-development/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.uninstallPlugin (/srv/strapi/strapi-development/node_modules/strapi-admin/controllers/Admin.js:122:7)
    at async /srv/strapi/strapi-development/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
    at async module.exports (/srv/strapi/strapi-development/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:35:14)
    at async /srv/strapi/strapi-development/node_modules/strapi/node_modules/strapi-utils/lib/policy.js:52:5
[2020-06-03T22:01:57.503Z] debug DELETE /admin/plugins/uninstall/graphql (975 ms) 400

**Comment by derrickmehaffy** [comment]
Can you provide your package.json from `/srv/strapi/strapi-development/package.json` please?

**Comment by L-Naej** [comment]
Same problem on the Digital Ocean Strapi marketplace droplet (v0.0.3), created today.
Content of `/srv/strapi/strapi-development/package.json`

```
{
  "name": "strapi-development",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "latest",
    "strapi": "3.0.1",
    "strapi-admin": "3.0.1",
    "strapi-connector-bookshelf": "3.0.1",
    "strapi-plugin-content-manager": "3.0.1",
    "strapi-plugin-content-type-builder": "3.0.1",
    "strapi-plugin-email": "3.0.1",
    "strapi-plugin-graphql": "3.0.1",
    "strapi-plugin-upload": "3.0.1",
    "strapi-plugin-users-permissions": "3.0.1",
    "strapi-utils": "3.0.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "64fbf3eb-cf20-483e-945a-a1d2be5643a1"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```
