### ISSUE TITLE
Error: write ECONNRESET and Error: write EPIPE

### ISSUE THREAD

**Issue by sourgoyal** [strapi/strapi#6715]
**Describe the bug**
We are getting two errors ECONNRESET and EPIPE back to back. We are running strapi + gcloudsql-proxy + istio proxy containers in GKE in a POD

**Steps to reproduce the behavior**

1. This is keep on happening without even doing anything
We can only see these logs: 
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: 'a1d5d687-89ba-4e61-9dc4-688498e70e1a',
  sql: 'select "strapi_administrator".* from "strapi_administrator" limit ?'
}
  Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:150:25)
      at writeGeneric (internal/stream_base_commons.js:141:3)
      at Socket._writeGeneric (net.js:770:11)
      at Socket._write (net.js:782:8)
      at doWrite (_stream_writable.js:431:12)
      at writeOrBuffer (_stream_writable.js:415:5)
      at Socket.Writable.write (_stream_writable.js:305:11)
      at ServerResponse._writeRaw (_http_outgoing.js:295:17)
      at ServerResponse._send (_http_outgoing.js:271:15)
      at ServerResponse.end (_http_outgoing.js:729:10)
      at Gzip.onend (_stream_readable.js:691:10)
      at Object.onceWrapper (events.js:299:28)
      at Gzip.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  Error: write ECONNRESET
      at afterWriteDispatched (internal/stream_base_commons.js:150:25)
      at writeGeneric (internal/stream_base_commons.js:141:3)
      at Socket._writeGeneric (net.js:770:11)
      at Socket._write (net.js:782:8)
      at doWrite (_stream_writable.js:431:12)
      at writeOrBuffer (_stream_writable.js:415:5)
      at Socket.Writable.write (_stream_writable.js:305:11)
      at ServerResponse._writeRaw (_http_outgoing.js:295:17)
      at ServerResponse._send (_http_outgoing.js:271:15)
      at ServerResponse.end (_http_outgoing.js:729:10)
      at Gzip.onend (_stream_readable.js:691:10)
      at Object.onceWrapper (events.js:299:28)
      at Gzip.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Expected behavior**
These logs should not come

**System**

- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.18.5
- Database: gcloud-sql Postgres
- Operating system: linux/amd64

**Additional context**

**Comment by derrickmehaffy** [comment]
Sorry but `Strapi version: 3.0.0-beta.18.5` the Strapi beta version is no longer supported.

Only issues that be reliability reproduced on the stable release or issues during the migration process are supported here.

**Comment by derrickmehaffy** [comment]
@sourgoyal can you test this on the latest stable release (as I too use gzip and have not encountered this issue). If you can reproduce it on the stable release then I can reopen this.
