### ISSUE TITLE
strapi new generating error: Unexpected token ...

### ISSUE THREAD

**Issue by rudolph2907** [strapi/strapi#673]
**Node.js version**:
8.5
**npm version**:
3.10.9
**Strapi version**:
Newest
**Operating system**:
Windows

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I am trying to generate a new app: strapi new test and getting th following error: 
C:\Program Files (x86)\Nodist\bin\node_modules\strapi\node_modules\strapi-generate-new\lib\before.js:125
          ...databaseChoice.value
          ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\strapi\node_modules\strapi-generate-new\lib\index.js:21:11)

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Run the new command

**What is the expected behavior?**
Generate new app

**Comment by lauriejim** [comment]
Please use node 9

**Comment by rudolph2907** [comment]
Hi Jim

Still getting the same issue with v9.5

![image](https://user-images.githubusercontent.com/4610580/36424256-570235bc-164b-11e8-9594-82c0f3ebf7c5.png)
