### ISSUE TITLE
Deployment on Heroku Strapi collections returning 500 errors after a couple of minutes to hours (CMS)

### ISSUE THREAD

**Issue by jshaw** [strapi/strapi#6767]
After deployment on Heroku Strapi collections starts to return 500 errors after a couple of minutes to hours. Doing another release seems to fixes the issue but then it happens again after a random amount of time after the next release.

**Describe the bug**
I can deploy my Strapi instance on Heroku using Postgresql DB and it is a success at first, but it seems after a couple of days when I come back and load my admin I get query errors. 

I was finding I was having this error for a few weeks during my dev process. I was originally using Strapi 3.0.0-beta.20 and two days ago updated to Strapi 3.0.0 thinking it would fix the issue of throwing this error after a couple of hours. Updating to 3.0.0 did not fix this bug.

**Steps to reproduce the behaviour**

1. Release Strapi to Heroku SERVICE: heroku-postgresql / PLAN: hobby-dev
2. Deployment is a success, can add content to the CMS. No errors etc.
3. Between 6-24 hours later, load the CMS admin again, and I start see errors in the from end.
4. The errors that I get are in the browser Strapi returns this message: `An error occurred during models config fetch.`. in dev tools the console error is a 500 `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Expected behaviour**
The expected behaviour is that the page and the content would be loaded and displayed without throwing an error.

**Screenshots**
N/A

**Code snippets**

Error Message:
```
2020-06-22T15:46:02.932217+00:00 app[web.1]: [2020-06-22T15:46:02.932Z] error Error: Field cannot be empty
2020-06-22T15:46:02.932219+00:00 app[web.1]: at /app/node_modules/strapi-utils/lib/convertRestQueryParams.js:69:13
2020-06-22T15:46:02.932220+00:00 app[web.1]: at Array.forEach (<anonymous>)
2020-06-22T15:46:02.932221+00:00 app[web.1]: at convertSortQueryParams (/app/node_modules/strapi-utils/lib/convertRestQueryParams.js:64:24)
2020-06-22T15:46:02.932221+00:00 app[web.1]: at convertRestQueryParams (/app/node_modules/strapi-utils/lib/convertRestQueryParams.js:26:32)
2020-06-22T15:46:02.932222+00:00 app[web.1]: at Object.find (/app/node_modules/strapi-connector-bookshelf/lib/queries.js:62:21)
2020-06-22T15:46:02.932222+00:00 app[web.1]: at Object.find (/app/node_modules/strapi-database/lib/queries/create-query.js:73:45)
2020-06-22T15:46:02.932479+00:00 app[web.1]: [2020-06-22T15:46:02.932Z] debug GET /content-manager/explorer/application::artwork.artwork?_limit=&_sort=:&_start=NaN (8 ms) 500
2020-06-22T15:46:02.935038+00:00 app[web.1]: [2020-06-22T15:46:02.934Z] error Error: Field cannot be empty
2020-06-22T15:46:02.935040+00:00 app[web.1]: at /app/node_modules/strapi-utils/lib/convertRestQueryParams.js:69:13
2020-06-22T15:46:02.935040+00:00 app[web.1]: at Array.forEach (<anonymous>)
2020-06-22T15:46:02.935041+00:00 app[web.1]: at convertSortQueryParams (/app/node_modules/strapi-utils/lib/convertRestQueryParams.js:64:24)
2020-06-22T15:46:02.935041+00:00 app[web.1]: at convertRestQueryParams (/app/node_modules/strapi-utils/lib/convertRestQueryParams.js:26:32)
2020-06-22T15:46:02.935042+00:00 app[web.1]: at Object.count (/app/node_modules/strapi-connector-bookshelf/lib/queries.js:77:23)
2020-06-22T15:46:02.935042+00:00 app[web.1]: at Object.count (/app/node_modules/strapi-database/lib/queries/create-query.js:73:45)
2020-06-22T15:46:02.935043+00:00 app[web.1]: at async Object.count (/app/node_modules/strapi-plugin-content-manager/controllers/ContentManager.js:89:15)
2020-06-22T15:46:02.935043+00:00 app[web.1]: at async /app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
2020-06-22T15:46:02.935043+00:00 app[web.1]: at async module.exports (/app/node_modules/strapi-plugin-content-manager/config/policies/routing.js:52:3)
2020-06-22T15:46:02.935044+00:00 app[web.1]: at async module.exports (/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:35:14)
2020-06-22T15:46:02.935045+00:00 app[web.1]: at async /app/node_modules/strapi-utils/lib/policy.js:52:5
2020-06-22T15:46:02.935045+00:00 app[web.1]: at async /app/node_modules/strapi/lib/middlewares/xss/index.js:26:9
2020-06-22T15:46:02.935284+00:00 app[web.1]: [2020-06-22T15:46:02.935Z] debug GET /content-manager/explorer/application::artwork.artwork/count?_limit=&_sort=:&_start=NaN (8 ms) 500
```

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0
- Database: Heroku SERVICE: heroku-postgresql / PLAN: hobby-dev
- Operating system: locally I'm macOS 10.14.6

**Additional context**
N/A

**Comment by akhilmhdh** [comment]
@jshaw The error from my experience is due to multiple user-plugins entry in db or the entries got corrupted. Are you using Postgresql free version. Try to look into the db. You may find your problem

**Comment by derrickmehaffy** [comment]
@jshaw just to confirm you aren't trying to create new models on the Heroku deployed version correct?

**Comment by lauriejim** [comment]
Do you use Media fields in your application?
If yes, can you make sure you are using a upload provider to not host your media in the Heroku server (the default provider is local in Strapi and this will not work with PG.)

**Comment by jshaw** [comment]
Hey all, thanks for the questions for further clarifications.

@akhilmhdh, hum interesting. I am using using the hobby dev free version. I'm fortunate the project is still being developed so it has little test data. I've actually reset the DB in Heroku and found this still happened.

@derrickmehaffy, correct, I'm not trying to update or alter the db once deployed.

@lauriejim Yes, I have media files hosted, I'm hosting the media on Cloudinary.com and not trying to store any reference to them on Heroku' Posgresql DB.

it happened again a couple days ago. I was working on something else so left it for a few hours and when I came back, wasn't throwing an error any more. Same thing happened today, this morning error, around noon it was gone for the rest of the day. Going to check again on it tomorrow to see if I can catch when or any additional logs.

Very odd...

**Comment by derrickmehaffy** [comment]
Can you update your project to the latest version? What I'm guessing is happening is that Heroku is killing the dyno every few hours (when there is no activity) and you see the initial reload of the dyno, but when it fetches the code, builds, and runs it you are seeing errors (in which maybe it's auto-restarting til the errors go away?)

**Comment by jshaw** [comment]
Hum, interesting. This morning, no errors either. Will continue to check periodically.

@derrickmehaffy, to conform your suggestion is to update to Strapi to v3.0.5?

**Comment by derrickmehaffy** [comment]
Yes, and if possible, can you share a link to your project on GitHub/gitlab/wherer ever?

**Comment by derrickmehaffy** [comment]
Hello!
As we have not received any new or updated information in over 7 days we are marking this issue/discussion as closed. Should you have new information please feel free to respond and we can consider reopening it.

For others finding this closed issue and you have updated information, please open up a new bug report and simply reference this closed bug report so that we can get any new information you may have. If you have questions please refer to the [contributor's guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue) on opening issues.

Thank you and have a great day!
