### ISSUE TITLE
strapi start race: core_store table does not exist

### ISSUE THREAD

**Issue by christophemacabiau** [strapi/strapi#6792]
**Describe the bug**
At the first start, I get sometimes this error:
```
[2020-06-18T14:49:58.504Z] debug ⛔️ Server wasn't able to start properly.
[2020-06-18T14:49:58.506Z] error error: relation "core_store" does not exist
    at Parser.parseErrorMessage (/srv/app/node_modules/pg-protocol/dist/parser.js:241:15)
    at Parser.handlePacket (/srv/app/node_modules/pg-protocol/dist/parser.js:89:29)
    at Parser.parse (/srv/app/node_modules/pg-protocol/dist/parser.js:41:38)
    at Socket.<anonymous> (/srv/app/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
From previous event:
    at Client_PG._query (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/srv/app/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/srv/app/node_modules/knex/lib/runner.js:135:36)
    at /srv/app/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/srv/app/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/srv/app/node_modules/knex/lib/interface.js:14:43)
    at processImmediate (internal/timers.js:439:21)
```

**Steps to reproduce the behavior**
1. create a container using the strapi/strapi v3.0.2 image

**Expected behavior**
strapi starts correctly

**System**
- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.2
- Database: Postgresql 12.3
- Operating system: fedora 32

**Additional context**
Seems to be the same bug as strapi/strapi#5067

**Comment by juandl** [comment]
This issue is happing also with Travis CI when it tries to run the tests in Postgresql. @alexandrebodin I guess should have more priority xD

**Comment by isadorastan** [comment]
Happening also with me :(
