### ISSUE TITLE
Unable to retrieve media files after saved 

### ISSUE THREAD

**Issue by AnudeepG1507** [strapi/strapi#6852]
created a content type with 1 string field and 1 media type.  Added 1 content to content type and everything is good. Media files are getting saved in the uploads folder. When i click on media library to check files uploaded. Getting the below mentioned error.  I have used shared volume and folder has read write permissions and built using strapi image on docker.

getting this issue:

 error Error: The target polymorphic type "tests" is not one of the defined target types
    at Object.morphCandidate (/srv/app/node_modules/bookshelf/lib/helpers.js:140:13)
    at /srv/app/node_modules/bookshelf/lib/eager.js:52:15
    at /srv/app/node_modules/lodash/lodash.js:13401:38
    at /srv/app/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/srv/app/node_modules/lodash/lodash.js:2990:24)
    at Function.mapValues (/srv/app/node_modules/lodash/lodash.js:13400:7)
    at EagerRelation.morphToFetch (/srv/app/node_modules/bookshelf/lib/eager.js:51:28)
    at EagerRelation.eagerFetch (/srv/app/node_modules/bookshelf/lib/eager.js:25:19)
    at EagerRelation.<anonymous> (/srv/app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /srv/app/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/srv/app/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/srv/app/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (/srv/app/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/srv/app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/srv/app/node_modules/bookshelf/lib/collection.js:527:73)
    at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/collection.js:179:27)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/collection.js:177:12)
From previous event:
    at Child.fetchAll (/srv/app/node_modules/bookshelf/lib/model.js:878:10)
    at Object.find (/srv/app/node_modules/strapi-connector-bookshelf/lib/queries.js:66:8)
    at Object.find (/srv/app/node_modules/strapi-database/lib/queries/create-query.js:73:45)
    at async Object.find (/srv/app/node_modules/strapi-plugin-upload/controllers/Upload.js:104:18)
    at async /srv/app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
    at async module.exports (/srv/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:35:14)
    at async /srv/app/node_modules/strapi-utils/lib/policy.js:52:5
    at async /srv/app/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-06-29T16:02:43.818Z] debug **GET /upload/files?_limit=10&_start=0&_sort=updated_at:DESC (49 ms) 500**

my docker compose **file:**

version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: **
      DATABASE_HOST: **
      DATABASE_PORT: ***
      DATABASE_USERNAME: ****
      DATABASE_PASSWORD: ****
      NODE_ENV: development
    ports:
      - '22700:1337'
    volumes:
      - ./app:/srv/app

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
