### ISSUE TITLE
Unable to retrieve media files after saved

### ISSUE THREAD

**Issue by AnudeepG1507** [strapi/strapi#6853]
**Describe the bug**

created a content type with 1 string field and 1 media type. Added 1 content to content type and everything is good. Media files are getting saved in the uploads folder. When i click on media library to check files uploaded. Getting the below mentioned error. I have used shared volume and folder has read write permissions and built using strapi image on docker.

**Steps to reproduce the behavior**

1. Go to admin panel and create a content type with media type and save
2. Click on created content type and add a media file and save it. All the files are saved to uploads directory
3. click on media Library plugin. media library error- not showing uploaded files
4. Error getting 500 response on /upload/files...... 

**Expected behavior**
Show all the uploaded files of any type

**Screenshots**

![image](https://user-images.githubusercontent.com/40441857/86046572-0a68b280-ba13-11ea-90d5-3ec1d79f70e3.png)

**Code snippets**
error Error: The target polymorphic type "tests" is not one of the defined target types
at Object.morphCandidate (/srv/app/node_modules/bookshelf/lib/helpers.js:140:13)
at /srv/app/node_modules/bookshelf/lib/eager.js:52:15
at /srv/app/node_modules/lodash/lodash.js:13401:38
at /srv/app/node_modules/lodash/lodash.js:4905:15
at baseForOwn (/srv/app/node_modules/lodash/lodash.js:2990:24)
at Function.mapValues (/srv/app/node_modules/lodash/lodash.js:13400:7)
at EagerRelation.morphToFetch (/srv/app/node_modules/bookshelf/lib/eager.js:51:28)
at EagerRelation.eagerFetch (/srv/app/node_modules/bookshelf/lib/eager.js:25:19)
at EagerRelation. (/srv/app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
at /srv/app/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
at EagerRelation._eagerLoadHelper (/srv/app/node_modules/bookshelf/lib/eager.js:83:23)
at Sync. (/srv/app/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
at EagerRelation.eagerFetch (/srv/app/node_modules/bookshelf/lib/eager.js:31:8)
at EagerRelation. (/srv/app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
at Child._handleEager (/srv/app/node_modules/bookshelf/lib/collection.js:527:73)
at Child. (/srv/app/node_modules/bookshelf/lib/collection.js:179:27)
at processImmediate (internal/timers.js:456:21)
From previous event:
at Child. (/srv/app/node_modules/bookshelf/lib/collection.js:177:12)
From previous event:
at Child.fetchAll (/srv/app/node_modules/bookshelf/lib/model.js:878:10)
at Object.find (/srv/app/node_modules/strapi-connector-bookshelf/lib/queries.js:66:8)
at Object.find (/srv/app/node_modules/strapi-database/lib/queries/create-query.js:73:45)
at async Object.find (/srv/app/node_modules/strapi-plugin-upload/controllers/Upload.js:104:18)
at async /srv/app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
at async module.exports (/srv/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:35:14)
at async /srv/app/node_modules/strapi-utils/lib/policy.js:52:5
at async /srv/app/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-06-29T16:02:43.818Z] **debug GET /upload/files?_limit=10&_start=0&_sort=updated_at:DESC (49 ms) 500**

**System**

strapi/strapi image from docker hub
Docker running on  CentOS 7

**Additional context**
my docker compose file:

version: '3'
services:
strapi:
image: strapi/strapi
container_name: strapi
environment:
DATABASE_CLIENT: mysql
DATABASE_NAME: **
DATABASE_HOST: **
DATABASE_PORT: ***
DATABASE_USERNAME: ****
DATABASE_PASSWORD: ****
NODE_ENV: development
ports:
- '22700:1337'
volumes:
- ./app:/srv/app

**Comment by gpiccin** [comment]
Delete the registry in table 'upload_file_morph' where related_type is equal 'tests' and try again. This works for me.

**Comment by lauriejim** [comment]
Thank you for reporting this issue, we already have one related to this.
Thank you for the solution to fix.
