### ISSUE TITLE
Content Type not defined

### ISSUE THREAD

**Issue by Fdom92** [strapi/strapi#6867]
**Describe the bug**
After migrating from beta 18 to beta 20, I followed all the guides and got Strapi deployed on Heroku. I can enter the admin panel and update the Content Types (i.e adding media to the items).

But when going to get data from the API endpoints I'm getting errors saying the content type is not defined.

**Code snippets**
This is the log I see on Heroku when trying to make a GET to Strapi Test content type:

```
2020-06-30T16:33:33.362685+00:00 app[web.1]: [2020-06-30T16:33:33.359Z] error ReferenceError: Test is not defined
2020-06-30T16:33:33.362692+00:00 app[web.1]:     at Object.fetchAll (/app/api/test/services/Test.js:24:5)
2020-06-30T16:33:33.362693+00:00 app[web.1]:     at Object.find (/app/api/test/controllers/Test.js:18:33)
2020-06-30T16:33:33.362693+00:00 app[web.1]:     at dispatch (/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
2020-06-30T16:33:33.362694+00:00 app[web.1]:     at next (/app/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
2020-06-30T16:33:33.362694+00:00 app[web.1]:     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
2020-06-30T16:33:33.362694+00:00 app[web.1]:     at /app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:28
2020-06-30T16:33:33.362695+00:00 app[web.1]:     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
2020-06-30T16:33:33.362696+00:00 app[web.1]:     at module.exports (/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:97:9)
2020-06-30T16:33:33.362698+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-06-30T16:33:33.362699+00:00 app[web.1]:     at async /app/node_modules/strapi-utils/lib/policy.js:52:5
2020-06-30T16:33:33.362699+00:00 app[web.1]:     at async serve (/app/node_modules/koa-static/index.js:59:5)
```
The route, controller and service is the default generated ones.

**System**
- Node.js version: >= 12.18.2,
- NPM version: >= 6.14.5
- Strapi version: 3.0.0-beta.20
- Database: MongoDB
- Operating system:

**Comment by Fdom92** [comment]
I was digging into this issue and seems like in the controllers `Test` is no longer the model. I added this line `const Test = strapi.query('test').model;` at the start of each service function and now is returning the data.

Wondering where I miss something, I created this Strapi project back on old versions and was working till beta 18, but when migrating to beta 20 stopped working.

All the controllers and services were generated back in the start of Strapi so that might have something to do, just in case this new info helps.
