### ISSUE TITLE
GraphQl queries error out when using where clause

### ISSUE THREAD

**Issue by devskope** [strapi/strapi#6882]
**Describe the bug**
Getting an error (`"$in requires an array as a second argument, found: missing"`) when I send GraphQL queries containing a `where` clause:

Request:
```javascript
{
    featuredProducts: products(
      limit: 6
      sort: "createdAt:desc"

      where: { tags: { name: "featured" } }      // using where here

    ) {
      name
      slug
      summary
      images {
        formats
      }
    }
    latestProducts: products(limit: 6, sort: "createdAt:desc" ) {
      name
      slug
      summary
      images {
        formats
      }
    }
    categories(limit: 4, sort: "createdAt:asc") {
      name
      image {
        url
      }
    }
}
```

Response:
```javascript
{
  "errors": [
    {
      "message": "$in requires an array as a second argument, found: missing",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "featuredProducts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "ok": 0,
          "errmsg": "$in requires an array as a second argument, found: missing",
          "code": 40081,
          "codeName": "Location40081",
          "name": "MongoError",
          "stacktrace": [
            "MongoError: $in requires an array as a second argument, found: missing",
            "    at Connection.<anonymous> (/home/toye/Dev/js/node/hair-store-cms/node_modules/mongodb/lib/core/connection/pool.js:460:61)",
            "    at Connection.emit (events.js:210:5)",
            "    at processMessage (/home/toye/Dev/js/node/hair-store-cms/node_modules/mongodb/lib/core/connection/connection.js:368:10)",
            "    at Socket.<anonymous> (/home/toye/Dev/js/node/hair-store-cms/node_modules/mongodb/lib/core/connection/connection.js:537:15)",
            "    at Socket.emit (events.js:210:5)",
            "    at addChunk (_stream_readable.js:309:12)",
            "    at readableAddChunk (_stream_readable.js:290:11)",
            "    at Socket.Readable.push (_stream_readable.js:224:10)",
            "    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)"
          ]
        }
      }
    }
  ],
  "data": {
    "featuredProducts": null,              // error
    "latestProducts": [
      {
        "name": "",
        "slug": "",
        "summary": "",
        "images": [ ]
      }
    ],
    "categories": [
      {
        "name": "",
        "image": {
          "url": ""
        }
      },
    ]
  }
}
```

**System**

- Node.js version:  12
- Strapi version:  3.0.5
- Database: mongoDB
- Operating system: Ubuntu

**Comment by devskope** [comment]
Figured this out,  turned out the document relationships somehow got messed up.  Closing this

**Comment by hoangcd92** [comment]
Hi @devskope , I am experiencing the same error. Could you please tell me how do you resolve this issue?

**Comment by devskope** [comment]
> Hi @devskope , I am experiencing the same error. Could you please tell me how do you resolve this issue?

@hoangcd92    I had to drop all the documents in the db.  Somehow the relationship between some # documents got messed up.

**Comment by hoangcd92** [comment]
In my case it's because I added Relation in the content-type after create some documents.
In these documents, the data in that relation field is empty, instead [ ].
I just need to insert [ ] to all of these missing documents, and the error is resolved.
