### ISSUE TITLE
Upload gets timeout while bulk uploading images

### ISSUE THREAD

**Issue by collegewap** [strapi/strapi#6935]
**Upload gets timeout while bulk uploading images**
* When I upload 20 images at a time I get the timeout. The issue was replicable with 4 images as well.
* I have Strapi deployed to Heroku with Cloudinary
* If I upload in small numbers, like 2-3 it gets uploaded
**Steps to reproduce the behavior**

Upload more than 5 images, each having a size between 2-4MB to Media Library.

**Expected behavior**
Images should get uploaded without throwing error

**Code snippets**
Logs

```
2020-07-08T06:29:36.482856+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/upload" host=****.herokuapp.com request_id=b3f94313-2052-4ad2-b4b4-73744d6e0024 fwd="106.200.44.109" dyno=web.1 connect=0ms service=74817ms status=503 bytes=0 protocol=http
2020-07-08T06:29:36.533550+00:00 app[web.1]: [2020-07-08T06:29:36.533Z] error Error: Request aborted
2020-07-08T06:29:36.533586+00:00 app[web.1]: at IncomingMessage.<anonymous> (/app/node_modules/formidable/lib/incoming_form.js:122:19)
2020-07-08T06:29:36.533588+00:00 app[web.1]: at IncomingMessage.emit (events.js:314:20)
2020-07-08T06:29:36.533588+00:00 app[web.1]: at abortIncoming (_http_server.js:535:9)
2020-07-08T06:29:36.533589+00:00 app[web.1]: at socketOnClose (_http_server.js:528:3)
2020-07-08T06:29:36.533589+00:00 app[web.1]: at Socket.emit (events.js:326:22)
2020-07-08T06:29:36.533590+00:00 app[web.1]: at TCP.<anonymous> (net.js:673:12)
2020-07-08T06:29:36.533827+00:00 app[web.1]: [2020-07-08T06:29:36.533Z] debug POST /upload (74752 ms) 500
```
**System**
- Node.js version: 14.5.0
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: Postgres
- Operating system: Linux

**Additional Context **

Tried increasing the timeout using the below methods, but did not work:

* Updating server.js

```
module.exports = (strapi) => {
  return {
    start() {
      strapi.server.setTimeout(18000000); //change to 0 to wait forever
    },
  };
};

```

* Updating bootstrap.js (apparently it is not supported anymore: https://github.com/strapi/strapi/issues/5869#issuecomment-616527372)

**Comment by lauriejim** [comment]
Hello! do you have the same issue when your app is running locally by uploading your 20 images?

**Comment by derrickmehaffy** [comment]
As we have no updated information from the user, marking as closed.

**Comment by adityaumeshacharya** [comment]
I am facing a similar issue, the only change is that getting the error for bigger videos or anything that takes longer than a minute to upload. PFA the log image, here I tried to upload a 500mb video and got this error.

![cms_error1](https://user-images.githubusercontent.com/35888089/135054792-4ce5b33a-fab9-44d9-a651-d8c62608760a.PNG)
