### ISSUE TITLE
strapi server start issue 

### ISSUE THREAD

**Issue by iamwebdev** [strapi/strapi#6941]
I have imported mongo db into staging server and now on starting server i am getting error.

[2020-07-08T10:07:31.573Z] error Bootstrap function in plugin "users-permissions" failed
[2020-07-08T10:07:31.574Z] error TypeError: Cannot read property '_id' of null
    at permissions.reduce.toKeep (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:437:116)
    at Array.reduce (<anonymous>)
    at Object.removeDuplicate (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:435:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.initialize (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:469:7)
    at async execBootstrap (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:441:9)
    at async Promise.all (index 4)
    at async Strapi.runBootstrapFunctions (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:457:5)
    at async Strapi.start (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:219:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EMR@0.1.0 start: `strapi start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EMR@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-07-08T10_07_31_587Z-debug.log

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by iamwebdev** [comment]
Strapi version:- 3.0.0-beta.20.3
npm version:- 6.14.4
node: v12.16.3
MongoDB shell version v3.6.3

I have imported mongo db into staging server and now on starting server i am getting error.

[2020-07-08T10:07:31.573Z] error Bootstrap function in plugin "users-permissions" failed
[2020-07-08T10:07:31.574Z] error TypeError: Cannot read property '_id' of null
at permissions.reduce.toKeep (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:437:116)
at Array.reduce ()
at Object.removeDuplicate (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:435:31)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Object.initialize (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:469:7)
at async execBootstrap (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:441:9)
at async Promise.all (index 4)
at async Strapi.runBootstrapFunctions (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:457:5)
at async Strapi.start (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:219:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EMR@0.1.0 start: strapi start
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EMR@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ubuntu/.npm/_logs/2020-07-08T10_07_31_587Z-debug.log
