### ISSUE TITLE
server start issue after importing db

### ISSUE THREAD

**Issue by iamwebdev** [strapi/strapi#6942]
**Strapi version:- 3.0.0-beta.20.3
npm version:- 6.14.4
node: v12.16.3
MongoDB shell version v3.6.3**

I have imported mongo db into staging server and now on starting server i am getting error.

[2020-07-08T10:07:31.573Z] error Bootstrap function in plugin "users-permissions" failed
[2020-07-08T10:07:31.574Z] error TypeError: Cannot read property '_id' of null
at permissions.reduce.toKeep (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:437:116)
at Array.reduce ()
at Object.removeDuplicate (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:435:31)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Object.initialize (/var/www/api.staging.emr.infinilive.com/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:469:7)
at async execBootstrap (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:441:9)
at async Promise.all (index 4)
at async Strapi.runBootstrapFunctions (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:457:5)
at async Strapi.start (/var/www/api.staging.emr.infinilive.com/node_modules/strapi/lib/Strapi.js:219:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EMR@0.1.0 start: strapi start
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EMR@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ubuntu/.npm/_logs/2020-07-08T10_07_31_587Z-debug.log

**Comment by derrickmehaffy** [comment]
`3.0.0-beta.20.3`

The beta version of Strapi is no longer supported, please update to the latest stable. The migration guides are on the documentation: https://strapi.io/documentation/v3.x/migration-guide/

Also in the future, please follow the required issue template and please read the contributing guide before creating new bug reports: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

Questions should be directed towards discussions: https://github.com/strapi/strapi/discussions
