### ISSUE TITLE
Failure to start on OSX - `strapi.models['core_store'].orm` undefined in `lib/core/store.js`

### ISSUE THREAD

**Issue by tapvt** [strapi/strapi#698]
**Node.js version**: v8.3.0

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.10.2

**Operating system**: OSX 10.13.2 (17C88)

**Do you want to request a *feature* or report a *bug*?**
Bug or lacking documentation of dependencies to manually install.

**What is the current behavior?** 
Having installed strapi following the [quick start doc](https://strapi.io/documentation/getting-started/quick-start.html), selecting mongodb as a db backend and successfully connecting with it, I cd into new project directory. `strapi start`

Fails w/ following error:

```
WARN (19307 on ****): (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
(node:19307) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: strapi.models.core_store.forgeis not a function
(node:19307) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19307) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: strapi.models.core_store.forgeis not a function
WARN (19307 on ****): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (19307 on ****): Perhaps you forgot to call it?
WARN (19307 on ****): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (19307 on ****): Perhaps you forgot to call it?
```

**If the current behavior is a bug, please provide the steps to reproduce the problem**

`$ strapi new my-project`
(select mongodb, get successful connection to mongo)
`$ cd my-project/`
`$ strapi start`

**What is the expected behavior?**
The server should start.

**Comment by derrickmehaffy** [comment]
@tapvt I believe the requirements now state Node v9 needs to be installed. Not sure if the pull request was pulled in and is live yet. Seen a few issues related to this.

**Comment by derrickmehaffy** [comment]
aye it does look like they have been updated: https://strapi.io/documentation/getting-started/installation.html

**Comment by tapvt** [comment]
@derrickmehaffy Great. I'll take a look. Thanks.

**Comment by tapvt** [comment]
@derrickmehaffy, after upgrading to node v9.6.1, the above error still occurs.

**Comment by derrickmehaffy** [comment]
@tapvt This seems related to a few other issues that have popped up just looking at previously closed issues. Not exactly but it seems for them the resolve was to manually call `npm install strapi-bookshelf@alpha --save` 

I would also try creating another new project since you have updated node. Else some of the strapi Devs might be able to point you in a better direction.

**Comment by tapvt** [comment]
Thanks for the ideas, @derrickmehaffy. Unfortunately, a fresh installation did not solve the issue. I manually ensured that `strapi-mongoose` is installed as well.

I am getting better stack traces now. So, `strapi start` yields:

```
(node:35160) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/Users/bweller/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/core/store.js:58:47)
    at module.exports (/Users/bweller/src/nusa/crmServer/plugins/settings-manager/config/functions/bootstrap.js:17:26)
    at Promise (/Users/bweller/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:222:9)
    at new Promise (<anonymous>)
    at execBootstrap (/Users/bweller/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:212:61)
    at Promise.all.Object.values.map.x (/Users/bweller/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:250:17)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/Users/bweller/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:250:8)
    at Strapi.start (/Users/bweller/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:95:18)
    at <anonymous>
```

So I decided to have a look in `/lib/core/store.js`.

Turns out, `strapi.models['core_store'].orm` is undefined for me.

Anyone have any ideas here? I'm going to keep digging. Really want to play with this. Thanks in advance!

**Comment by derrickmehaffy** [comment]
@tapvt Hmmm I'm wondering if this is an issue to Mac based systems. As I've never seen something like that issue on Windows or linux.

**Comment by tapvt** [comment]
@derrickmehaffy Huh. Lemme fire up a linux VM and give it a shot.

**Comment by pedrosimao** [comment]
I have the same issue here.
I am using Mac OsX, Node v. 9.6.1 and MySQL.
It's very frustrating not being able to start strapi and test for the first time.

**Comment by derrickmehaffy** [comment]
@pedrosimao I believe that might be the case, I would recommend you try running it in a VM using Ubuntu/Centos to see. My dev system runs on Linux Mint (Ubuntu) but I've tested on windows 7/10 and haven't seen this before.

**Comment by tapvt** [comment]
@derrickmehaffy, @pedrossimao:

I fired up an ec2 micro, and had no problems. So, this is some type of environmental issue.

I am using identical versions of Strapi, node and mongod on both machines.

Strapi: 3.0.0-alpha.10.2
Node: v9.6.1
mongod: v3.6.3

If anyone can point me in a direction regarding `strapi.models['core_store']` , I'm happy to dig in and figure out why its `orm` property is undefined on mac.

Cheers!

**Comment by derrickmehaffy** [comment]
Looks like there are some references to core_store in a pull request that was made about 19 days ago: https://github.com/strapi/strapi/commit/f5031d01554455a803c0f12a85e95bdb814bb22b

And it seems there was a related issue from mysql/postgres. 

https://github.com/strapi/strapi/issues/485

All of which appear to be related to Mac OS. So I agree this seems like an environmental issue. I know in some rare cases Mac tends to hot swap stuff out for their own versions.

**Comment by derrickmehaffy** [comment]
Just curious @tapvt can you try forking and pulling the base strapi code. As I think there were some changes made that haven't been pushed out into a release yet. This issue might have been solved in that pull request. There should be some instructions about building a dev environment on here: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

And on the documentation page: https://strapi.io/documentation/advanced/customize-admin.html (I know this is based around building out new features on the admin panel, I've already suggested to the devs on building better documentation about working in the dev environment)

**Comment by tapvt** [comment]
Sure @derrickmehaffy, I'll have a go at it.

**Comment by derrickmehaffy** [comment]
I don't have a Mac to test on myself *shakes fist at apple and their lack of VM support*

**Comment by pedrosimao** [comment]
@derrickmehaffy I have just tested in a Ubuntu VPS with Node v.9.5.0 and I got the exact same issue.
I think the problem is related to Mysql and not to Mac OSX.
I got the following error messages:

> (node:5824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:5824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> WARN (5824 on bitmondo.com.br): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
> WARN (5824 on bitmondo.com.br): Perhaps you forgot to call it?

**Comment by pedrosimao** [comment]
The problem is actually coming from those lines:

**Comment by derrickmehaffy** [comment]
@pedrosimao thats after you created the tables in MySQL? (I too wished to use MySQL over MongoDB but will likely wait until better support is done on strapi to automatically create and manage the tables and columns)

**Comment by pedrosimao** [comment]
The problem is actually coming from the following lines:
node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14
...
 at Object.set (/usr/lib/node_modules/strapi/lib/core/store.js:126:57)

**Comment by tapvt** [comment]
@derrickmehaffy @pedrosimao - I'm feeling like these might be separate issues. I was hitting an issue way earlier in `store.js`. Line 57.

**Comment by tapvt** [comment]
@derrickmehaffy I can confirm that this is still an issue running against latest master (443d6b81) on OSX.

Same trace:

```
16:02 $ strapi start
WARN (43775 on ****): (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
(node:43775) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/Users/bweller/src/strapi/packages/strapi/lib/core/store.js:57:47)    at module.exports (/Users/bweller/src/osx-test-latest/plugins/settings-manager/config/functions/bootstrap.js:17:26)
    at Promise (/Users/bweller/src/strapi/packages/strapi/lib/Strapi.js:222:9)
    at new Promise (<anonymous>)
    at execBootstrap (/Users/bweller/src/strapi/packages/strapi/lib/Strapi.js:212:61)
    at Promise.all.Object.values.map.x (/Users/bweller/src/strapi/packages/strapi/lib/Strapi.js:250:17)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/Users/bweller/src/strapi/packages/strapi/lib/Strapi.js:250:8)
    at Strapi.start (/Users/bweller/src/strapi/packages/strapi/lib/Strapi.js:95:18)
    at <anonymous>
```

**Comment by derrickmehaffy** [comment]
Aye then @tapvt This is something the strapi devs will have to dive into. @lauriejim will probably need to check it.

**Comment by lauriejim** [comment]
Can you please guys try again with clean install of the last Strapi version please.

**Comment by tapvt** [comment]
@lauriejim - Thanks for keeping us Mac users in mind! It'll really ramp up my productivity when I can run a dev server locally.

Unfortunately, I just did a clean install of `3.0.0-alpha.11.1`, and the issue is still present. Same failure trace. Slightly different log formatting, though.

**Node.js version:** v9.6.1
**npm version:** 5.7.1
**Strapi version:**: 3.0.0-alpha.11.1
**Operating system:** OSX 10.13.3

```
[2018-03-12T20:42:55.546Z] warn (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
(node:82967) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/Users/username/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/core/store.js:57:47)
    at module.exports (/Users/username/src/foobar/plugins/settings-manager/config/functions/bootstrap.js:17:26)
    at Promise (/Users/username/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:222:9)
    at new Promise (<anonymous>)
    at execBootstrap (/Users/username/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:212:61)
    at Promise.all.Object.values.map.x (/Users/username/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:250:17)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/Users/username/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:250:8)
    at Strapi.start (/Users/username/.nvm/versions/node/v9.6.1/lib/node_modules/strapi/lib/Strapi.js:95:18)
    at <anonymous>

```

**Comment by tapvt** [comment]
This whole issue revolves around `strapi.models['core_store'].orm` being undefined. I'm using mongoose, btw. Since the logic explicitly checks for `=== 'mongoose'`, it defaults and tries to use forge, which obviously won't work.

I don't know the internals of the strapi bootstrap process, but I'm willing to dig in since I can reproduce on my machine reliably.

Maybe someone could point me to where `strapi.models['core_store']` is built up at boot and where the value for `orm` is set?

```
...

const data = strapi.models['core_store'].orm === 'mongoose'
? await strapi.models['core_store'].findOne(where)
: await strapi.models['core_store'].forge(where).fetch().then(config => {

...
```

**Comment by lauriejim** [comment]
Hi @tapvt !
To follow the loading process it's here https://github.com/strapi/strapi/blob/master/packages/strapi/lib/Strapi.js
And for the store setup it's here https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/store.js

**Comment by kis** [comment]
@lauriejim any progress with that? facing the same issue

**Comment by lauriejim** [comment]
Hi @kis ! We can't reproduce (see the label) so difficult for us to fix it if it's not happen in our machine.

It's why we need your help to fix it. Please see my last message to investigate on.

**Comment by tapvt** [comment]
This is hilarious and embarrassing at the same time... After digging around in the code for a bit, I tried explicitly setting my environment. Lo and behold everything works w/ `3.0.0-alpha.11.1`. Turns out my `.bashrc` was setting it to `dev`, which is standard for some projects, but Strapi prefers `development`.

So, @kis, can you try `export NODE_ENV="development" && strapi start` and let us know if that works for you?

@lauriejim, I guess if that works for @kis, then we can close this issue. Thanks for the guidance on the codebase. Might consider displaying a warning on start if a given environment has no directory in `./config/environments`, or if a non-standard environment name is detected during `strapi new`?

**Comment by aaimaawebs** [comment]
Hello Everyone, a new headache for us. I had fresh installed Strapi on Ubuntu 16.04, via Script & everything installed & configured via them. Oh, everything went well for Development ('strapi start') but when I configured mlab with production (I doubly check everything, is fine as per all Strapi Tutorials on Blog).

So, decided to hit `NODE_ENV=production npm start` and WTH, there are similar issues as you guys are discussing. Instead, here with me, NO Mac, No SQL. Just mongo, Ubuntu, Script & Production. Error's are as follows:

```
root@strapi:~/strapi# NODE_ENV=production npm start

> strapi@0.1.0 start /root/strapi
> node server.js

(node:2088) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/core/store.js:57:47)
    at module.exports (/root/strapi/plugins/settings-manager/config/functions/bootstrap.js:17:26)
    at Promise (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:222:9)
    at new Promise (<anonymous>)
    at execBootstrap (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:212:61)
    at Promise.all.Object.values.map.x (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:250:17)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:250:8)
    at Strapi.start (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:95:18)
    at <anonymous>
(node:2088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:2088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2088) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
    at Object.get (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/core/store.js:57:47)
    at module.exports (/root/strapi/plugins/users-permissions/config/functions/bootstrap.js:37:26)
    at Promise (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:222:9)
    at new Promise (<anonymous>)
    at execBootstrap (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:212:61)
    at Promise.all.Object.values.map.x (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:250:17)
    at Array.map (<anonymous>)
    at Strapi.bootstrap (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:250:8)
    at Strapi.start (/root/.nvm/versions/node/v9.8.0/lib/node_modules/strapi/lib/Strapi.js:95:18)
    at <anonymous>
(node:2088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:2088) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
    at fs.readdir (/root/strapi/plugins/upload/config/functions/bootstrap.js:97:40)
    at <anonymous>
(node:2088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[2018-03-16T17:31:36.657Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2018-03-16T17:31:36.659Z] warn Perhaps you forgot to call it?
[2018-03-16T17:31:36.659Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2018-03-16T17:31:36.659Z] warn Perhaps you forgot to call it?
[2018-03-16T17:31:36.659Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2018-03-16T17:31:36.660Z] warn Perhaps you forgot to call it?
```

**Comment by Aurelsicoko** [comment]
@aaimaawebs It's because you don't have any models in your app, I guess. Please refers to this message (https://github.com/strapi/strapi/issues/698#issuecomment-372462360), can you make a PR to fix it? 

You need to check if the `strapi.models['core_store'].orm` is not `undefined`...

**Comment by lauriejim** [comment]
Can you guys give us an update about this issue and logs of `.orm` value.

**Comment by tapvt** [comment]
I explicitly `unset NODE_ENV` to re-create my earlier issue. Here's the output w/ a `console.log()` of just `.orm()`

Looks good to me.

```
mongoose                                                                                                                
mongoose                                                                                                                
mongoose                                                                                                                
mongoose                                                                                                                
mongoose                                                                                                                
mongoose                                                                                                                
[2018-03-28T11:56:54.039Z] info Server started in /Users/bweller/src/latestTestStrapi                                   
[2018-03-28T11:56:54.040Z] info Your server is running at http://localhost:1337                                         
[2018-03-28T11:56:54.041Z] debug Time: Wed Mar 28 2018 06:56:54 GMT-0500 (CDT)                                          
[2018-03-28T11:56:54.041Z] debug Launched in: 2948 ms                                                                   
[2018-03-28T11:56:54.041Z] debug Environment: development                                                               
[2018-03-28T11:56:54.041Z] debug Process PID: 885                                                                       
[2018-03-28T11:56:54.042Z] debug Version: 3.0.0-alpha.11.2 (node v9.6.1)                                                
[2018-03-28T11:56:54.042Z] info To shut down your server, press <CTRL> + C at any time
```

**Comment by lauriejim** [comment]
A PR will be rewrite about this point - https://github.com/strapi/strapi/pull/793
