### ISSUE TITLE
Media library 500 error

### ISSUE THREAD

**Issue by jessjohnstonuk** [strapi/strapi#7012]
**Describe the bug**

Media Library doesn't display any uploaded assets

**Steps to reproduce the behavior**

1. Open developer tools
2. Go to 'Media Library'
3. See error

**Expected behavior**
Visible list of all uploaded media assets

**Screenshots**
![Screenshot 2020-07-14 at 13 13 02](https://user-images.githubusercontent.com/17690946/87433685-87825300-c5e1-11ea-90fa-bd81fc7b94f2.png)
![Screenshot 2020-07-14 at 14 52 03](https://user-images.githubusercontent.com/17690946/87433750-9a952300-c5e1-11ea-9b2a-3c9e392d1aa8.png)

**Code snippets**
Below is the server log
```
[2020-07-14T14:11:08.453Z] debug GET upload (12 ms) 200
[2020-07-14T14:11:08.530Z] debug GET main.7c8613d5.chunk.js (5 ms) 200
[2020-07-14T14:11:08.531Z] debug GET runtime~main.6d3a9728.js (10 ms) 200
[2020-07-14T14:11:09.432Z] debug GET immer.esm.js.map (3 ms) 200
[2020-07-14T14:11:09.488Z] debug GET /users-permissions/init (20 ms) 200
[2020-07-14T14:11:09.542Z] debug GET /favicon.ico (1 ms) 200
[2020-07-14T14:11:09.545Z] debug GET /admin/init (1 ms) 200
[2020-07-14T14:11:09.594Z] debug GET /content-manager/content-types (10 ms) 200
[2020-07-14T14:11:09.610Z] debug GET /content-manager/content-types (10 ms) 200
[2020-07-14T14:11:09.770Z] debug GET cc1d824d8f006f0a47c72638f4ce0376.png (8 ms) 200
[2020-07-14T14:11:09.776Z] error Error: The target polymorphic type "components_featured_image_featured_images" is not one of the defined target types
    at Object.morphCandidate (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/helpers.js:140:13)
    at /Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/eager.js:52:15
    at /Users/jess/Web/website-2020-cms/node_modules/lodash/lodash.js:13427:38
    at /Users/jess/Web/website-2020-cms/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/jess/Web/website-2020-cms/node_modules/lodash/lodash.js:2990:24)
    at Function.mapValues (/Users/jess/Web/website-2020-cms/node_modules/lodash/lodash.js:13426:7)
    at EagerRelation.morphToFetch (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/eager.js:51:28)
    at EagerRelation.eagerFetch (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/eager.js:25:19)
    at EagerRelation.<anonymous> (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/collection.js:527:73)
    at Child.<anonymous> (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/collection.js:179:27)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Child.<anonymous> (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/collection.js:177:12)
From previous event:
    at Child.fetchAll (/Users/jess/Web/website-2020-cms/node_modules/bookshelf/lib/model.js:878:10)
    at Object.find (/Users/jess/Web/website-2020-cms/node_modules/strapi-connector-bookshelf/lib/queries.js:66:8)
    at Object.find (/Users/jess/Web/website-2020-cms/node_modules/strapi-database/lib/queries/create-query.js:73:45)
    at async Object.find (/Users/jess/Web/website-2020-cms/node_modules/strapi-plugin-upload/controllers/Upload.js:104:18)
    at async /Users/jess/Web/website-2020-cms/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
    at async module.exports (/Users/jess/Web/website-2020-cms/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:35:14)
    at async /Users/jess/Web/website-2020-cms/node_modules/strapi-utils/lib/policy.js:52:5
    at async /Users/jess/Web/website-2020-cms/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-07-14T14:11:09.791Z] debug GET /upload/files?_limit=10&_start=0&_sort=updated_at:DESC (55 ms) 500
[2020-07-14T14:11:09.804Z] debug GET /upload/files/count? (54 ms) 200
[2020-07-14T14:11:09.807Z] debug GET 85d339d916479f729938d2911b85bf1f.ttf (13 ms) 200
[2020-07-14T14:11:09.807Z] debug GET e631d2735799aa943d93d301abf423d2.ttf (12 ms) 200
[2020-07-14T14:11:09.810Z] debug GET 2d36b1a925432bae7f3c53a340868c6e.ttf (13 ms) 200
[2020-07-14T14:11:09.814Z] debug GET 57d69e1d4ce0cc10ace9264b4af92cf1.ttf (16 ms) 200
[2020-07-14T14:11:10.002Z] debug GET 412a43d6840addd683665ec12c30f810.woff2 (1 ms) 200
```

**System**

- Node.js version: 14.2.0
- NPM version: 6.14.5
- Strapi version: 3.0.4
- Database: SQLite
- Operating system: MacOS 10.15.5

**Comment by derrickmehaffy** [comment]
Node.js version: 14.2.0 this version of node isn't supported, please downgrade to v12, also please provide your server logs not chrome

**Comment by jessjohnstonuk** [comment]
**Update**
This issue only occurs when there are less than 7 uploads in the media library

**Comment by burydmitri** [comment]
I have the same problem. And so funny, that first tab of Media doesn't worked, but second is displayed. 
Also, If I try to use Media lib in components, nothing is displayed.

![Screenshot_34](https://user-images.githubusercontent.com/54257598/88474142-94ca0680-cf2c-11ea-946e-52d2575f8fad.png)
![Screenshot_35](https://user-images.githubusercontent.com/54257598/88474143-95fb3380-cf2c-11ea-94c9-d2e198da7b83.png)
![Screenshot_36](https://user-images.githubusercontent.com/54257598/88474144-97c4f700-cf2c-11ea-864e-5ab21916bbc3.png)

**Comment by lauriejim** [comment]
Hello! Do you have any way to reproduce your issue with a new fresh project?
Because everything is going well on my side... so it will be hard to help :/

**Comment by burydmitri** [comment]
> Hello! Do you have any way to reproduce your issue with a new fresh project?
> Because everything is going well on my side... so it will be hard to help :/

I will try today at evening

**Comment by burydmitri** [comment]
Now I can't reproduce this error. The only difference from the repository with an error is the version of the Strapi. Was 3.1.0 - now 3.1.1   ¯\\_(ツ)_/¯
Sorry. If I reproduce the error I will write

**Comment by soupette** [comment]
@burydmitri should we close the issue then?

**Comment by jessjohnstonuk** [comment]
Trying to find a way to reproduce. Feel free to close, and I'll come back when I have some more information

**Comment by soupette** [comment]
Thank you! Closing it then
