### ISSUE TITLE
Unable to run Strapi - MODULE_NOT_FOUND KOA

### ISSUE THREAD

**Issue by katlegomoilwa** [strapi/strapi#7031]
Node: v13.2.0
NPM: 6.13.1
Operating System: Windows 10
Database: SQLite

I followed the getting started guide and upon running npm run strapi develop I got the error below.

Katlego@MOilWA-ThinkPad MINGW64 ~/Development/strapi/my-project
$ npm run strapi develop
Debugger listening on ws://127.0.0.1:51543/d48170bf-ae1c-435a-af5e-6ac5f85ab2f2
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:51543/d48170bf-ae1c-435a-af5e-6ac5f85ab2f2
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:51549/e92c920b-5582-4c4c-bdf4-da6051a7594a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> my-project@0.1.0 strapi C:\Users\Katlego\Development\strapi\my-project
> strapi "develop"

Debugger listening on ws://127.0.0.1:51556/2fcd18c0-a3a2-4647-a86e-eef5105df530
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:51556/2fcd18c0-a3a2-4647-a86e-eef5105df530
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:614
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\Katlego\Development\strapi\my-project\node_modules\koa'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (C:\Users\Katlego\Development\strapi\my-project\node_modules\strapi\lib\Strapi.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 strapi: `strapi "develop"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.1.0 strapi script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Debugger listening on ws://127.0.0.1:5npm1549/e92c920b-5582-4c4c-bdf4-da6051a7594a
 For help, see: https://nodejs.org/en/docs/inspector
ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Katlego\AppData\Roaming\npm-cache\_logs\2020-07-16T09_26_44_487Z-debug.log

**Comment by katlegomoilwa** [comment]
Having checked the documentation again, I found my mistake was my Node version
