### ISSUE TITLE
Error process.exit called with "1" during unit testing

### ISSUE THREAD

**Issue by alpha771** [strapi/strapi#7048]
**Describe the bug**
Running test using jest throwing an error process.exit called with "1"

**Steps to reproduce the behavior**

1. npx create-strapi-app example
2. Follow this guide [https://strapi.io/documentation/v3.x/guides/unit-testing.html](url)
3. npm run test

**Screenshots**
![Screenshot from 2020-07-17 17-02-03](https://user-images.githubusercontent.com/53975050/87774930-78084180-c84f-11ea-8622-e21936efd1ac.png)

**Code snippets**
https://github.com/alpha771/strapi-unit-testing/

**System**
- Node.js version: 14.3.0
- NPM version: 6.14.5
- Strapi version: 3.0.6
- Database: SQLite
- Operating system: Ubuntu 20.04

**Additional context**
Unit testing running successfully when using strapi v3.0.0

**Comment by derrickmehaffy** [comment]
`Node.js version: 14.3.0`

Node v14 is not LTS and thus is not supported yet.

**Comment by alpha771** [comment]
> `Node.js version: 14.3.0`
> 
> Node v14 is not LTS and thus is not supported yet.

Unfortunately, it is still not working. I am trying using node v12.18.2

**Steps to reproduce the behavior**
1. Uninstall node v14, then install node LTS
2. Restarting OS
3. Create new strapi app using npx
4. Follow this guide https://strapi.io/documentation/v3.x/guides/unit-testing.html
5. npm test

![Screenshot from 2020-07-18 00-44-15](https://user-images.githubusercontent.com/53975050/87815450-d523e780-c88f-11ea-8de7-661897e030e6.png)

**Comment by finfa** [comment]
Having exactly the same issue.

Tested on a vanilla Strapi, followed the instructions.

Strapi v3.0.5
node v12.13.0
Jest 26.1.0

```
Debugger listening on ws://127.0.0.1:9229/a7a6da10-ca27-4d47-b69f-456b94c7a153
For help, see: https://nodejs.org/en/docs/inspector
{
  "configs": [
    {
      "automock": false,
      "cache": true,
      "cacheDirectory": "/tmp/jest_rs",
      "clearMocks": false,
      "coveragePathIgnorePatterns": [
        "/node_modules/"
      ],
      "cwd": "/home/fede/repos/cms",
      "detectLeaks": false,
      "detectOpenHandles": true,
      "errorOnDeprecated": false,
      "extraGlobals": [],
      "forceCoverageMatch": [],
      "globals": {},
      "haste": {
        "computeSha1": false,
        "throwOnModuleCollision": false
      },
      "moduleDirectories": [
        "node_modules"
      ],
      "moduleFileExtensions": [
        "js",
        "json",
        "jsx",
        "ts",
        "tsx",
        "node"
      ],
      "moduleNameMapper": [],
      "modulePathIgnorePatterns": [],
      "name": "ebda16bed2e34f461135889da11d2e98",
      "prettierPath": "prettier",
      "resetMocks": false,
      "resetModules": false,
      "restoreMocks": false,
      "rootDir": "/home/fede/repos/cms",
      "roots": [
        "/home/fede/repos/cms"
      ],
      "runner": "jest-runner",
      "setupFiles": [],
      "setupFilesAfterEnv": [],
      "skipFilter": false,
      "snapshotSerializers": [],
      "testEnvironment": "/home/fede/repos/cms/node_modules/jest-environment-jsdom/build/index.js",
      "testEnvironmentOptions": {},
      "testLocationInResults": false,
      "testMatch": [
        "**/__tests__/**/*.[jt]s?(x)",
        "**/?(*.)+(spec|test).[tj]s?(x)"
      ],
      "testPathIgnorePatterns": [
        "/node_modules/",
        ".tmp",
        ".cache"
      ],
      "testRegex": [],
      "testRunner": "/home/fede/repos/cms/node_modules/jest-jasmine2/build/index.js",
      "testURL": "http://localhost",
      "timers": "real",
      "transform": [
        [
          "^.+\\.[jt]sx?$",
          "/home/fede/repos/cms/node_modules/babel-jest/build/index.js",
          {}
        ]
      ],
      "transformIgnorePatterns": [
        "/node_modules/"
      ],
      "watchPathIgnorePatterns": []
    }
  ],
  "globalConfig": {
    "bail": 0,
    "changedFilesWithAncestor": false,
    "collectCoverage": false,
    "collectCoverageFrom": [],
    "coverageDirectory": "/home/fede/repos/cms/coverage",
    "coverageProvider": "babel",
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "clover"
    ],
    "detectLeaks": false,
    "detectOpenHandles": true,
    "errorOnDeprecated": false,
    "expand": false,
    "findRelatedTests": false,
    "forceExit": false,
    "json": false,
    "lastCommit": false,
    "listTests": false,
    "logHeapUsage": false,
    "maxConcurrency": 5,
    "maxWorkers": 1,
    "noStackTrace": false,
    "nonFlagArgs": [],
    "notify": false,
    "notifyMode": "failure-change",
    "onlyChanged": false,
    "onlyFailures": false,
    "passWithNoTests": false,
    "projects": [],
    "reporters": [
      [
        "/home/fede/Programmini/WebStorm-201.8538.32/plugins/JavaScriptLanguage/helpers/jest-intellij/lib/jest-intellij-reporter.js",
        {}
      ]
    ],
    "rootDir": "/home/fede/repos/cms",
    "runTestsByPath": false,
    "skipFilter": false,
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testSequencer": "/home/fede/repos/cms/node_modules/@jest/test-sequencer/build/index.js",
    "testTimeout": 20000,
    "updateSnapshot": "new",
    "useStderr": false,
    "verbose": true,
    "watch": false,
    "watchAll": false,
    "watchman": true
  },
  "version": "26.1.0"
}
  console.log
    [Error: SQLITE_BUSY: database is locked] {
      errno: 5,
      code: 'SQLITE_BUSY'
    }

      at node_modules/strapi/lib/Strapi.js:377:17
          at async Promise.all (index 0)

[2020-07-22T17:09:52.026Z] error Bootstrap function in plugin "content-manager" failed
[2020-07-22T17:09:52.029Z] error undefined
  ●  process.exit called with "1"

       7 |   if (!instance) {
       8 |     /** the following code in copied from `./node_modules/strapi/lib/Strapi.js` */
    >  9 |     await Strapi().load();
         |     ^
      10 |     instance = strapi; // strapi is global now
      11 |     await instance.app
      12 |       .use(instance.router.routes()) // populate KOA routes

      at Strapi.stop (node_modules/strapi/lib/Strapi.js:238:13)
      at node_modules/strapi/lib/Strapi.js:380:16
          at async Promise.all (index 0)
      at Strapi.runBootstrapFunctions (node_modules/strapi/lib/Strapi.js:384:5)
      at Strapi.load (node_modules/strapi/lib/Strapi.js:301:5)
      at setupStrapi (tests/helpers/strapi.js:9:5)
      at Object.<anonymous> (tests/app.test.js:6:3)

Process finished with exit code 1

```

**Comment by ptrckhjnl** [comment]
I fixed it by writing the following in `config/env/test/database.js`:

```js
module.exports = {
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "sqlite",
        filename: ".tmp/test.db",
      },
      options: {
        useNullAsDefault: true,
        pool: {
          min: 0,
          max: 1,
        },
      },
    },
  },
};
```
The important bit is the `max: 1` (in the documentation it's 15). There seems to be a problem with multiple connections in SQLite.

**Comment by alpha771** [comment]
> I fixed it by writing the following in `config/env/test/database.js`:
> 
> ```js
> module.exports = {
>   defaultConnection: "default",
>   connections: {
>     default: {
>       connector: "bookshelf",
>       settings: {
>         client: "sqlite",
>         filename: ".tmp/test.db",
>       },
>       options: {
>         useNullAsDefault: true,
>         pool: {
>           min: 0,
>           max: 1,
>         },
>       },
>     },
>   },
> };
> ```
> 
> The important bit is the `max: 1` (in the documentation it's 15). There seems to be a problem with multiple connections in SQLite.

Work like a charm !! Thank you @ptrckhjnl

**Comment by lauriejim** [comment]
Thank you :)
