### ISSUE TITLE
 Unit Test Strapi Instance with .tmp/test.db

### ISSUE THREAD

**Issue by pigman8857** [strapi/strapi#7064]
I have followed the document about unit testing, create Strapi instance

https://strapi.io/documentation/v3.x/guides/unit-testing.html#strapi-instance

I have database.js under config/env/test

```
module.exports = ({ env }) => ({
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "sqlite",
        "filename": ".tmp/test.db"
      },
      "options": {
        "useNullAsDefault": true,
        "pool": {
          "min": 0,
          "max": 15
        }
      }
    }
  }
});

```

and here is the strapi.js under ./tests/helpers/
```
const Strapi = require('strapi');
const http = require('http');

let instance;

async function setupStrapi() {

    if (!instance) {
        /** the following code in copied from `./node_modules/strapi/lib/Strapi.js` */
        console.log();
        await Strapi().load();
        instance = strapi; // strapi is global now
        await instance.app
            .use(instance.router.routes()) // populate KOA routes
            .use(instance.router.allowedMethods()); // populate KOA methods

        instance.server = http.createServer(instance.app.callback());
    }
    console.log('finish setupStrapi ');
    return instance;
}
module.exports = { setupStrapi };
```

But when i start test with ./tests/app.test.js

```
const fs = require('fs');
const { setupStrapi } = require('./helpers/strapi');

/** this code is called once before any test is called */
beforeAll(async done => {
  await setupStrapi(); // singleton so it can be called many times
  done();
});

/** this code is called once before all the tested are finished */
afterAll(async done => {
  const dbSettings = strapi.config.get('database.connections.default.settings');

  //delete test database after all tests
  if (dbSettings && dbSettings.filename) {
    const tmpDbFile = `${__dirname}/../${dbSettings.filename}`;
    if (fs.existsSync(tmpDbFile)) {
      fs.unlinkSync(tmpDbFile);
    }
  }
  done();
});

it('strapi is defined', async done => {
  expect(strapi).toBeDefined();
  done();
});

```

it says there is a problem at  await Strapi().load(); and    ●  process.exit called with "1", If i dont have .tmp/test.db created before hand.

If i created.tmp/test.db from .tmp/dev.db, then Strapi().load(); will work normally but then another issue happens

```
    error found  Error: EBUSY: resource busy or locked, unlink 'D:/Workspaces/my-project/.tmp/test.db'
        at Object.unlinkSync (fs.js:1129:3)
        at Object.<anonymous> (D:\Workspaces\my-project\tests\app.test.js:21:20)
        at D:\Workspaces\my-project\node_modules\jest-jasmine2\build\queueRunner.js:47:12
        at new Promise (<anonymous>)
        at mapper (D:\Workspaces\my-project\node_modules\jest-jasmine2\build\queueRunner.js:30:19)
        at D:\Workspaces\my-project\node_modules\jest-jasmine2\build\queueRunner.js:77:41
        at fn (D:\Workspaces\my-project\node_modules\jest-jasmine2\build\treeProcessor.js:43:7)
        at Env.execute (D:\Workspaces\my-project\node_modules\jest-jasmine2\build\jasmine\Env.js:296:11)
        at jasmine2 (D:\Workspaces\my-project\node_modules\jest-jasmine2\build\index.js:233:3)
        at runTestInternal (D:\Workspaces\my-project\node_modules\jest-runner\build\runTest.js:375:16) {
      errno: -4082,
      syscall: 'unlink',
      code: 'EBUSY',
      path: 'D:/Workspaces/my-project/.tmp/test.db'
    }
```

Not sure why and how both of issue happen.

Does .tmp/test.db really need to be added before hand every time i test?  If i don't have it it will create test.db and test.db-journal and await Strapi().load(); will fail.

If i have .tmp/test.db then fs.unlinkSync(tmpDbFile); will fail with     
error found  Error: EBUSY: resource busy or locked, unlink 'D:/Workspaces/my-project/.tmp/test.db'
        at Object.unlinkSync (fs.js:1129:3)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
