### ISSUE TITLE
Strapi does not start the server after run npm run develop

### ISSUE THREAD

**Issue by krittiyaclark** [strapi/strapi#7105]
I clone Strapi project from production and run `npm install && npm run develop ` but it failed at `npm run develop`

**ERROR output**

`
strapi develop

[2020-07-21T20:50:36.391Z] debug ⛔️ Server wasn't able to start properly.
[2020-07-21T20:50:36.392Z] error Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
From previous event:
    at Client_PG.acquireRawConnection (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/knex/lib/dialects/postgres/index.js:108:12)
    at create (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/knex/lib/client.js:258:21)
    at /Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/Pool.js:389:34
    at Object.tryPromise (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/utils.js:53:24)
    at /Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/Pool.js:389:17
    at new Promise (<anonymous>)
    at callbackOrPromise (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/Pool.js:380:12)
    at Pool._create (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/Pool.js:290:9)
    at Pool._doCreate (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/Pool.js:260:36)
    at Pool._tryAcquireOrCreate (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/Pool.js:211:18)
    at Pool.acquire (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/tarn/lib/Pool.js:117:14)
    at /Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/knex/lib/client.js:312:43
From previous event:
    at Client_PG.acquireConnection (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/knex/lib/client.js:312:26)
    at Runner.ensureConnection (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/knex/lib/runner.js:246:8)
    at Runner.run (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/knex/lib/runner.js:25:27)
    at SchemaBuilder.Target.then (/Users/krittiyaclark/Documents/vintage-react-tech-store-api/node_modules/knex/lib/interface.js:14:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tech-store-api@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tech-store-api@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krittiyaclark/.npm/_logs/2020-07-21T20_50_36_402Z-debug.log`

**package.json**

```
{
  "name": "tech-store-api",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "^8.3.0",
    "sqlite3": "latest",
    "strapi": "3.0.6",
    "strapi-admin": "3.0.6",
    "strapi-connector-bookshelf": "3.0.6",
    "strapi-plugin-content-manager": "3.0.6",
    "strapi-plugin-content-type-builder": "3.0.6",
    "strapi-plugin-email": "3.0.6",
    "strapi-plugin-upload": "3.0.6",
    "strapi-plugin-users-permissions": "3.0.6",
    "strapi-provider-upload-cloudinary": "^3.0.6",
    "strapi-utils": "3.0.6",
    "stripe": "^8.76.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "fc4e0701-0a91-435f-b6b0-0e35886c34ed"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**System**

- Node.js version: v14.5.0
- NPM version: 6.14.5
- Strapi version: 3.0.6
- Database:
- Operating system: mac os Catalina version 10.15.5

**Comment by derrickmehaffy** [comment]
`Node.js version: v14.5.0`
Node v14 isn't supported yet, only the latest LTS version which is node v12

Also that error is stating that it cannot connect to your MongoDB database (ECONNREFUSED typically means you have an issue with your auth)

**Comment by krittiyaclark** [comment]
> Also that error is stating that it cannot connect to your MongoDB database (ECONNREFUSED typically means you have an issue with your auth)

How to solve this issue? Thank you!

**Comment by iCianan** [comment]
Getting the same error on old strapi project and when created a brand new one using:
yarn create strapi-app my-project --quickstart
"Error: bind EACCES 0.0.0.0:1337" 
Running node 12.13.1

**Comment by krittiyaclark** [comment]
> Getting the same error on old strapi project and and brand new one using:
> yarn create strapi-app my-project --quickstart
> "Error: bind EACCES 0.0.0.0:1337"
> Running node 12.13.1

Did you solve it?

**Comment by krittiyaclark** [comment]
In database.js. We replaced the code from 

 ```
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "sqlite",
        filename: env("DATABASE_FILENAME", ".tmp/data.db"),
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});
```

to this. That why it did not work. So I had to switch back to the above one and the server start again.

```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', ''),
        password: env('DATABASE_PASSWORD', ''),
      },
      options: {
        ssl: false,
      },
    },
  },
});
```

**Comment by derrickmehaffy** [comment]
@krittiyaclark If you are using MongoDB you should be using the mongoose connector see the following documentation: https://strapi.io/documentation/v3.x/concepts/configurations.html#database

In your previous example you had the `connector: 'bookshelf',` which is only used for SQL databases.

**Comment by iCianan** [comment]
The only way I was able to get strapi to build was by changing the port number from 1337 to something else in the server.js file. This is on a brand new project using the quickstart flag. 

Tried on multiple machines. Worked fine last week not sure what changed.
