### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full

### ISSUE THREAD

**Issue by robclouth** [strapi/strapi#7129]
After upgrading from 3.0.5 to 3.1.0 strapi no longer starts and produces this error:
```
debug ⛔️ Server wasn't able to start properly.
[2020-07-23T08:54:47.494Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Volumes/Data/Projects/Apps/SCGIS/backend/node_modules/knex/lib/client.js:318:17
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Client_PG.acquireConnection (/Volumes/Data/Projects/Apps/SCGIS/backend/node_modules/knex/lib/client.js:317:15)
    at Runner.ensureConnection (/Volumes/Data/Projects/Apps/SCGIS/backend/node_modules/knex/lib/runner.js:246:8)
    at Runner.run (/Volumes/Data/Projects/Apps/SCGIS/backend/node_modules/knex/lib/runner.js:25:27)
    at SchemaBuilder.Target.then (/Volumes/Data/Projects/Apps/SCGIS/backend/node_modules/knex/lib/interface.js:14:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
I've tried setting the pool options to really high values: 
```
pool: {
          min: 0,
          max: 20,
          createTimeoutMillis: 30000,
          acquireTimeoutMillis: 600000,
          idleTimeoutMillis: 30000
        }
```

But it still fails. Before the upgrade strapi started almost immediately. What's changed?

I can connect to the db fine with psql and other tools. I'm aware of the other similar issues but the solutions proposed don't resolve this.

**Comment by robclouth** [comment]
Ah it seems that raising the max to 50 worked.
