### ISSUE TITLE
Register user throws an exception "Auth.form.error.email.taken"

### ISSUE THREAD

**Issue by dobregons** [strapi/strapi#7148]
**Describe the bug**
The register mutation is not working when the User collection is modified and required fields are added. It is throwing an exception with the message "Auth.form.error.email.taken", however I am using a new email.

**Steps to reproduce the behavior**
Go to graphql playground and try to call the `register` mutation with a valid object.
Mutation:
```json
mutation register($input:UsersPermissionsRegisterInput!) {
  register(input :$input) {
    jwt
    user{
      id
      username
      email
      confirmed
      blocked
      role{
        id
        name
        description
        type
      }
    }
  }
}
```
Query Variables:
```json
{
  "input": {
    "username": "dobregon",
    "email": "pepito@hotmail.com",
    "password": "Aq123456"
  }
}
```

Response.
```json
{
  "errors": [
    {
      "message": "Bad Request",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "register"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": 400,
          "data": {
            "statusCode": 400,
            "error": "Bad Request",
            "message": [
              {
                "messages": [
                  {
                    "id": "Auth.form.error.email.taken",
                    "message": "Email already taken"
                  }
                ]
              }
            ],
            "data": [
              {
                "messages": [
                  {
                    "id": "Auth.form.error.email.taken",
                    "message": "Email already taken"
                  }
                ]
              }
            ]
          },
          "stacktrace": [
            "Error: Bad Request",
            "    at checkBadRequest (/usr/src/app/node_modules/strapi-plugin-users-permissions/config/schema.graphql.js:11:23)",
            "    at resolver (/usr/src/app/node_modules/strapi-plugin-users-permissions/config/schema.graphql.js:196:11)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
This is my current `User.settings.json`.
```json
{
  "kind": "collectionType",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "birthday": {
      "type": "date"
    },
    "weight": {
      "type": "float"
    },
    "height": {
      "type": "float"
    },
    "name": {
      "type": "string",
      "required": true
    },
    "document_number": {
      "type": "string",
      "required": true
    },
    "gender": {
      "type": "integer"
    },
    "home_address": {
      "type": "string"
    },
    "contact_number": {
      "type": "string",
      "maxLength": 10
    },
    "document_type": {
      "model": "document-types"
    }
  }
}

```

I was able to force a succesful response removing the required fields that I created in the User object. I mean, removing `document_number` and `name` from required fields.

**Expected behavior**
Register should work indepently of the required fields in the User collection.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10051456/88359460-4b18ca80-cd38-11ea-96c2-822b64b51aa9.png)

**System**

- Node.js version: v12.18.2 
- NPM version:  6.14.5
- Strapi version: v3.0.5
- Database: MongoDB v4.2
- Operating system: Ubuntu 18.04

**Additional context**
In https://github.com/strapi/strapi/issues/6182 there was an issue describing the same behavior. It seems that [matrixersp](https://github.com/matrixersp) is experiencing the same error with strapi v3.0.6.

**Comment by lauriejim** [comment]
Hello I'm closing this issue because it's the same as this one - https://github.com/strapi/strapi/issues/5479
