### ISSUE TITLE
Travis builds are failing for PR's made from forks

### ISSUE THREAD

**Issue by cyp3rius** [strapi/strapi#7157]
**Describe the bug**
For PR's created from forks to strapi the Travis builds are failing on the same tests suites:

```
packages/strapi-admin/test/admin-auth.test.e2e.js
packages/strapi-admin/test/admin-role.test.e2e.js
packages/strapi-admin/test/admin-user.test.e2e.js
```

with errors like:

```
[2020-07-23T15:40:42.099Z] debug DELETE /admin/roles/1 (13 ms) 405
[2020-07-23T15:40:42.121Z] error error: select distinct "strapi_role".* from "strapi_role" where "strapi_role"."id" = $1 limit $2 - invalid input syntax for integer: "undefined"
    at Connection.parseE (/home/travis/build/strapi/strapi/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/travis/build/strapi/strapi/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/travis/build/strapi/strapi/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Sync.<anonymous> (/home/travis/build/strapi/strapi/node_modules/bookshelf/lib/sync.js:204:8)
From previous event:
    at Child.<anonymous> (/home/travis/build/strapi/strapi/node_modules/bookshelf/lib/collection.js:160:12)
From previous event:
    at Child.fetchAll (/home/travis/build/strapi/strapi/node_modules/bookshelf/lib/model.js:878:10)
    at find (/home/travis/build/strapi/strapi/packages/strapi-connector-bookshelf/lib/queries.js:66:8)
    at Object.findOne (/home/travis/build/strapi/strapi/packages/strapi-connector-bookshelf/lib/queries.js:54:27)
    at fn (/home/travis/build/strapi/strapi/packages/strapi-database/lib/queries/helpers.js:31:54)
    at Object.findOne (/home/travis/build/strapi/strapi/packages/strapi-database/lib/queries/helpers.js:15:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-23T15:40:42.121Z] debug PUT /admin/roles/undefined (15 ms) 500
```

or even not starting like below:
```
The command "yarn run -s test:generate-app -- $DB_STRING" exited with 0.
$ yarn run -s test:start-app & wait-on http://localhost:1337
[2020-07-24T08:28:35.396Z] debug ⛔️ Server wasn't able to start properly.
[2020-07-24T08:28:35.397Z] error error: select "core_store".* from "core_store" where "core_store"."key" = $1 limit $2 - relation "core_store" does not exist
    at Connection.parseE (/home/travis/build/strapi/strapi/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/travis/build/strapi/strapi/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/travis/build/strapi/strapi/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Sync.<anonymous> (/home/travis/build/strapi/strapi/node_modules/bookshelf/lib/sync.js:204:8)
From previous event:
    at Sync.<anonymous> (/home/travis/build/strapi/strapi/node_modules/bookshelf/lib/sync.js:66:17)
From previous event:
    at Child.<anonymous> (/home/travis/build/strapi/strapi/node_modules/bookshelf/lib/model.js:713:12)
From previous event:
    at Child.fetch (/home/travis/build/strapi/strapi/node_modules/bookshelf/lib/model.js:702:19)
    at storeTable (/home/travis/build/strapi/strapi/packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js:441:6)
    at createOrUpdateTable (/home/travis/build/strapi/strapi/packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js:165:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Couple example PR's that Travis fails by the same way:
https://github.com/strapi/strapi/pull/6955
https://github.com/strapi/strapi/pull/7130
https://github.com/strapi/strapi/pull/7150

**Expected behavior**
Travis builds pass, changes in PR's were independent from the roles / users E2E (2 of them were just docs changes as I seen).

**Comment by alexandrebodin** [comment]
Hi @cyp3rius thank you noticing this. we are already aware of this issue. I'm going to close this as it isn't an issue with the product itself. We need to change a few things in the CI setup hope to get to it soon

**Comment by cyp3rius** [comment]
Thanks @alexandrebodin. I will be really glad if you can notify in this issue once the changes to CI going to be applied. Than I will back to work :)

**Comment by alexandrebodin** [comment]
@cyp3rius The PR is open :)
