### ISSUE TITLE
Migration from Strapi 3.0 to Strapi 3.1  The model user can't be found.

### ISSUE THREAD

**Issue by aguerram** [strapi/strapi#7164]
**Describe the bug**
When I merged from strapi 3.0 to Strapi 3.1, this message appeared : Error: The model user can't be found.

```
at DatabaseManager.query (C:\Users\agurr\Desktop\Workspace\summit events\mediaexpressbackend\node_modules\strapi-database\lib\database-manager.js:75:13)
    at Strapi.query (C:\Users\agurr\Desktop\Workspace\summit events\mediaexpressbackend\node_modules\strapi\lib\Strapi.js:417:20)
    at Object.isInitialised (C:\Users\agurr\Desktop\Workspace\summit events\mediaexpressbackend\node_modules\strapi\lib\utils\index.js:17:51)
    at onListen (C:\Users\agurr\Desktop\Workspace\summit events\mediaexpressbackend\node_modules\strapi\lib\Strapi.js:198:41)
    at Server.<anonymous> (C:\Users\agurr\Desktop\Workspace\summit events\mediaexpressbackend\node_modules\strapi\lib\Strapi.js:230:7)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:327:22)
    at emitListeningNT (net.js:1347:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)

```

**Comment by aguerram** [comment]
This issue fixed by updating all the packages using: ```yarn upgrade```, but I can't open admin panel, when I check console it says that : **http://localhost:1337/users-permissions/init** :  not found 404

**Comment by aguerram** [comment]
All issues resolved but I'm so disappointed when I find that new roles feature not for free, I thought Strapi is open source

**Comment by derrickmehaffy** [comment]
> All issues resolved but I'm so disappointed when I find that new roles feature not for free, I thought Strapi is open source

@aguerram there are free parts to it, but open source != free in every context. We do offer quite a bit for free we just limit the number of Admin roles and very detailed field level permissions in the admin.

**Comment by aguerram** [comment]
> > All issues resolved but I'm so disappointed when I find that new roles feature not for free, I thought Strapi is open source
> 
> @aguerram there are free parts to it, but open source != free in every context. We do offer quite a bit for free we just limit the number of Admin roles and very detailed field level permissions in the admin.

@derrickmehaffy I was hoping to use it for a project I'm working on because I'm running out of time, but I think after all I have to integrate react admin

**Comment by mitch104** [comment]
> This issue fixed by updating all the packages using: `yarn upgrade`, but I can't open admin panel, when I check console it says that : **http://localhost:1337/users-permissions/init** : not found 404

Hi @aguerram, how did you resolve the `users-permissions/init` 404 issue, I am also encountering the same after upgrading to Strapi 3.1.1?

**Comment by mitch104** [comment]
Ahh fixed by following https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html
