### ISSUE TITLE
search not working in admin panel using postgresql db

### ISSUE THREAD

**Issue by bbober987** [strapi/strapi#7188]
**Describe the bug**

If I start a new project with yarn create strapi-app, and connect to a postgresql database, the search functionality at the top bar for searching within a collection in the admin panel causes an error "An error occurred during models config fetch." Note it happens for any collection type, only where the query string contains _q, and this functionality appears fine when I use a local sqlite database on a fresh project.  Debug logs show the following:

2020-07-26T19:20:21.830Z] error error: column "users-permissions_user.username" must appear in the GROUP BY clause or be used in an aggregate function
    at Parser.parseErrorMessage (/home/bbober/Desktop/test/test/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/bbober/Desktop/test/test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/bbober/Desktop/test/test/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/bbober/Desktop/test/test/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
From previous event:
    at Client_PG._query (/home/bbober/Desktop/test/test/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/home/bbober/Desktop/test/test/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/home/bbober/Desktop/test/test/node_modules/knex/lib/runner.js:135:36)
    at /home/bbober/Desktop/test/test/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/home/bbober/Desktop/test/test/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/home/bbober/Desktop/test/test/node_modules/knex/lib/interface.js:14:43)
    at processImmediate (internal/timers.js:456:21)
[2020-07-26T19:20:21.830Z] debug GET /content-manager/explorer/plugins::users-permissions.user/count?_limit=10&_sort=username%3AASC&_q=test&_start=0 (298 ms) 500
[2020-07-26T19:20:21.999Z] debug GET /content-manager/explorer/plugins::users-permissions.user?_limit=10&_sort=username%3AASC&_q=test&_start=0 (464 ms) 200

**Steps to reproduce the behavior**

1. Start a fresh project on 3.1.1
2. switch the database to a postgresql database
3. Load the admin panel
4. Try to search on the top bar

**System**

- Node.js version: 12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.1
- Database: Postgresql 12
- Operating system: Linux mint 19.3

**Comment by lauriejim** [comment]
Hello! Please see there related issue - https://github.com/strapi/strapi/issues?q=is%3Aissue+must+appear+in+the+GROUP+BY+is%3Aclosed
Is has been fixed.
