### ISSUE TITLE
error MissingSchemaError: Schema hasn't been registered for model

### ISSUE THREAD

**Issue by vladcazacu** [strapi/strapi#7304]
**Describe the bug**
I'm getting this error: `error MissingSchemaError: Schema hasn't been registered for model "product".` when accessing the Products collection admin listing page. Somehow it seems related to the collection names, more details below.

**Steps to reproduce the behavior**

1. Go to the Content-Types Builder
2. Create a "Product" collection type
3. Create a new product
4. Create a "Product Variant" collection type and add a "Product has many Product Variants" relation
5. Try going back to the products listing, here you will see the error

Removing the "Product Variant" relation fixes the issue.

It gets weird when trying the following:
1. Remove "Product Variant" relation from "Product", now the products will display properly
2. Create the "Product Attribute" collection type and add a "Product has many Product Attributes" relation
3. Go back to the products listing, there will be no error

Somehow naming the collection "Product Variant" breaks the listing, but naming it "Product Attribute" doesn't.

**Expected behavior**
It should display the products without errors.

**System**

- Node.js version: v12
- NPM version: 6.14.4
- Strapi version: 3.1.3
- Database: MongoDB 4.2.6
- Operating system: macOS Catalina

**Additional context**
I've tested this on a fresh Strapi install with an empty database.

https://www.loom.com/share/4d2f1ff59fa74a73ab524cb40c732269

```
error MissingSchemaError: Schema hasn't been registered for model "product".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/error/missingSchema.js:22:11)
    at NativeConnection.Connection.model (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/connection.js:1029:11)
    at getModelsMapForPopulate (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:201:59)
    at populate (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/model.js:4250:21)
    at _populate (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/model.js:4220:5)
    at /Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/model.js:4195:5
    at Object.promiseOrCallback (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/utils.js:261:12)
    at Function.Model.populate (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/model.js:4193:16)
    at cb (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongoose/lib/query.js:1948:17)
    at /Users/vladcazacu/projects/strapi-test-project/node_modules/mongodb/lib/operations/execute_operation.js:75:17
    at executeCallback (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongodb/lib/utils.js:129:55)
    at /Users/vladcazacu/projects/strapi-test-project/node_modules/mongodb/lib/operations/to_array.js:36:13
    at handleCallback (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongodb/lib/utils.js:129:55)
    at completeClose (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongodb/lib/cursor.js:859:16)
    at Cursor.close (/Users/vladcazacu/projects/strapi-test-project/node_modules/mongodb/lib/cursor.js:878:12)```

**Comment by vladcazacu** [comment]
Found the issue in `node_modules/strapi-connector-mongoose/lib/mount-models.js` on line 122, caused by `key.replace('_v', '')`. Removing the `replace` call fixes my issue, but I'm assuming it's there for a reason? Looks like this would break any relation with a "_v" in the name tho, would be good to get some advice on how to permanently fix this.

![image](https://user-images.githubusercontent.com/4677592/89272597-aa32e500-d63e-11ea-8007-8a32bc6de35d.png)

**Comment by lauriejim** [comment]
Helloè! I tried to reproduce your steps and it works on my side.
Can you please provide the "Product" and "Product Variant" models (need to know the attributes)

**Comment by vladcazacu** [comment]
Hey @lauriejim, I've pushed the test project here https://github.com/vladcazacu/strapi-test-project. It's fully generated using the CLI and admin interface, haven't touched the code directly.

**Comment by lauriejim** [comment]
Thank you for this resource.
Probably a conflict due to attributes's name `product`.
Ping @alexandrebodin about that.
```json
"product_attributes": {
  "via": "product",
  "collection": "product-attribute"
},
"product_variants": {
  "via": "product",
  "collection": "product-variant"
}
```

**Comment by alexandrebodin** [comment]
the issue is what @vladcazacu shared. This replace should ne be implemted like that it breaks the product_variants because of the **_v**.  as a workaround you can rename the field @vladcazacu  :)

**Comment by vladcazacu** [comment]
Thanks for the feedback @alexandrebodin, I'll rename the fields for now. Is there going to be a fix for this anytime soon? Those names do make sense for my use case and I'd like to keep them when releasing the project if possible.

**Comment by alexandrebodin** [comment]
@vladcazacu yes will write one soon :) you could convert to camelCase to keep the same name just not use the `_v` :)

**Comment by lauriejim** [comment]
Thank you @alexandrebodin for all these details.
