### ISSUE TITLE
Could not run on Ubuntu Server 17.10

### ISSUE THREAD

**Issue by daominhsangvn** [strapi/strapi#731]
**Node.js version**:
8.9.4
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.3
**Operating system**:
Ubuntu Server 17.10

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Run `$ node server.js` in Ubuntu server not working
**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. Create new project in local then push to Git (github, bitbucket...)
2. Login to Ubuntu server, pull the project
3. `$ npm install` and `$ node server.js`

**What is the expected behavior?**
It should start the project

Outputs:
```
root@ubuntu:~/node-myportfolio# node server.js 
ERROR (15420 on ubuntu): Cannot find module 'sendmail'
    Error: Cannot find module 'sendmail'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/root/node-myportfolio/plugins/email/services/Email.js:10:18)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
ERROR (15420 on ubuntu): Cannot find module 'jsonwebtoken'
    Error: Cannot find module 'jsonwebtoken'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/root/node-myportfolio/plugins/users-permissions/services/Jwt.js:10:13)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
ERROR (15420 on ubuntu): Cannot find module 'request'
    Error: Cannot find module 'request'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/root/node-myportfolio/plugins/users-permissions/services/Providers.js:9:17)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
ERROR (15420 on ubuntu): Cannot find module 'bcryptjs'
    Error: Cannot find module 'bcryptjs'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/root/node-myportfolio/plugins/users-permissions/services/User.js:11:16)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
ERROR (15420 on ubuntu): Cannot find module 'request'
    Error: Cannot find module 'request'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/root/node-myportfolio/plugins/users-permissions/services/UsersPermissions.js:6:17)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
(node:15420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: strapi.plugins.users-permissions.services.userspermissions.syncSchema is not a function
(node:15420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
WARN (15420 on ubuntu): Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
WARN (15420 on ubuntu): Perhaps you forgot to call it?
```

**Comment by lauriejim** [comment]
Hi @daominhsangvn do you try to follow this article to did it ?
https://blog.strapi.io/how-to-deploy-a-strapi-application/

**Comment by daominhsangvn** [comment]
@lauriejim Yes i did, i guess i found the issue, it's because i ignore the package-lock.json inside the plugin folder and it's stop working. I tried to init another project from the Ubuntu server then clone it to local and re-run it, it's working good now.

**Comment by amouratoglou** [comment]
hey @daominhsangvn how did you manage to make it work? I have the same error message.
