### ISSUE TITLE
SQLITE_ERROR: duplicate column name

### ISSUE THREAD

**Issue by stentas** [strapi/strapi#7319]
**Describe the bug**
This is the first time I'm testing Strapi and the first time I try out SQLite (I've always used MySQL).

So I had created some fields and saved it. Then I regretted using CamelBack and I went ahead and modified the name to camel_back.

Upon saving Strapi throws the error "SQLITE_ERROR: duplicate column name: type" after modifying field name.
Now it seems I have to deelte the DB and start over again. This is a horrible weakness and should not be possible from a admin GUI like Strapi.

**Steps to reproduce the behavior**
1. Create and save some fields
2. Edit the field names 
3. Click Save button
4. See error:

error Error: SQLITE_ERROR: duplicate column name: type
    at Client_SQLite3._query (F:\web\www\RAW\strapi\node_modules\knex\lib\dialects\sqlite3\index.js:99:12)
    at Client_SQLite3.query (F:\web\www\RAW\strapi\node_modules\knex\lib\client.js:158:17)
    at Runner.query (F:\web\www\RAW\strapi\node_modules\knex\lib\runner.js:135:36)
    at Runner.<anonymous> (F:\web\www\RAW\strapi\node_modules\knex\lib\runner.js:228:25)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Runner.queryArray (F:\web\www\RAW\strapi\node_modules\knex\lib\runner.js:227:12)
    at F:\web\www\RAW\strapi\node_modules\knex\lib\runner.js:37:25
From previous event:
    at Runner.run (F:\web\www\RAW\strapi\node_modules\knex\lib\runner.js:25:16)
    at SchemaBuilder.Target.then (F:\web\www\RAW\strapi\node_modules\knex\lib\interface.js:14:43)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Expected behavior**
Strapi deals witht his well know weakness of using SQLite so that users like me don't have to worry about it.
(I found this out in en earlier reported problem: https://github.com/strapi/strapi/issues/3490. It was closed without being fixed.)

**System**
- Node.js version: 12.16.1
- NPM version: 6.14.2
- Strapi version: 3.1.3
- Database: SQLite 3.32
- Operating system: Win 10

**Comment by derrickmehaffy** [comment]
Hello!

Please see the following issue, this one is a duplicate: https://github.com/strapi/strapi/issues/1114

For now I will mark this as closed, but if you want to quickly fix it, you will need to update the database manually for the moment.

**Comment by stentas** [comment]
@derrickmehaffy The other one has been "This conversation has been locked as too heated and limited to collaborators." and no one has done enything about it since 2018...

**Comment by derrickmehaffy** [comment]
It is something that we are aware of and have discussed in that issue, but currently it's something we plan to review with the database changes scheduled for v4: https://portal.productboard.com/strapi/1-public-roadmap/c/73-database-layer-v4
