### ISSUE TITLE
Crash when renaming case sensitive fields

### ISSUE THREAD

**Issue by NicoHood** [strapi/strapi#7484]
**Describe the bug**
The server crashs when you try to rename "Name" to "name" for example.

**Steps to reproduce the behavior**

1. Install strapi quickstart as described in the docs
2. Follow the tutorial BUT type "Name" instead of name" in step 3
3. Continue with step 4 (might not be required)
4. Try to rename "Name" to "name"

**Expected behavior**
The server restarts and the rename was successful

**Screenshots**
```
[2020-08-15T19:00:09.849Z] info The server is restarting

[2020-08-15T19:00:11.741Z] debug ⛔️ Server wasn't able to start properly.
[2020-08-15T19:00:11.743Z] error Error: SQLITE_ERROR: duplicate column name: name
    at Client_SQLite3._query (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/dialects/sqlite3/index.js:99:12)
    at Client_SQLite3.query (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:135:36)
    at Runner.queryArray (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:224:14)
    at /home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:37:25
From previous event:
    at Runner.run (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:25:16)
    at SchemaBuilder.Target.then (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/interface.js:14:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-08-15T19_00_11_758Z-debug.log
error Command failed.
Exit code: 1
Command: /home/user/.yarn/bin/create-strapi-app
Arguments: my-project --quickstart
Directory: /home/user/Documents/Sport/BikeFitting/Haendler/strapi
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

After that the sqlite database seems to be broken:
```
[2020-08-15T19:06:45.370Z] debug ⛔️ Server wasn't able to start properly.
[2020-08-15T19:06:45.372Z] error Error: SQLITE_ERROR: duplicate column name: name
    at Client_SQLite3._query (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/dialects/sqlite3/index.js:99:12)
    at Client_SQLite3.query (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:135:36)
    at Runner.queryArray (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:224:14)
    at /home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:37:25
From previous event:
    at Runner.run (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/runner.js:25:16)
    at SchemaBuilder.Target.then (/home/user/Documents/Sport/BikeFitting/Haendler/strapi/my-project/node_modules/knex/lib/interface.js:14:43)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**System**

- Node.js version: 14.8.0
- NPM version: ---
- Strapi version: 3.1.4
- Database: sqlite
- Operating system: archlinux

**Comment by lauriejim** [comment]
Hello! I'm closing this issue.
It's related to this big, massive topic - https://github.com/strapi/strapi/issues/1114

**Comment by NicoHood** [comment]
Oh that is a bummer that the bug already exists 2 years and is not planned to get fixed :-(

**Comment by lauriejim** [comment]
In fact, I think it's planned to be fixed when we will review the database layer of Strapi (we are currently working on it)
I will let @alexandrebodin give more details.

We know that thing is annoying.
The thing is that we are still a small team and we have a ton of topics to manage.
We are trying to juggle between, new features, important fixes, and architecture update to help Strapi to scale in the time.
From an internal point of view, it's not an easy equation and we have to make everyone in the community happy with what we are doing.

I assure you I would also love everything fixed asap :p I'm facing your (community issues / message) every day.
But you know, we are doing the best as we can.

Have a good day.

**Comment by jorisw** [comment]
Anyone know how to recover from this problem? Strapi won't start now after I renamed a `Title` property to `title`.
