### ISSUE TITLE
Internal Server Error [500] on POST /auth

### ISSUE THREAD

**Issue by Demonicious** [strapi/strapi#7506]
**Cannot access Login, Register, Reset Password and other such routes**
I have installed a fresh copy of Strapi, created some collection types and some users to play around with. But the first time I tried testing the sign in feature with the route `/auth/local`, It resulted in a 500 error. I tried the Registration and Reset Password routes, but they resulted in the exact same error log.
```bash
[2020-08-18T08:47:49.291Z] error C:\xampp2\htdocs\project\api-v2\node_modules\mongodb\lib\core\topologies\server.js:4
  f = require('util').format,�  EventEmitter = require('events').EventEmitter,


SyntaxError: Invalid or unexpected token
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\xampp2\htdocs\project\api-v2\node_modules\mongodb\lib\core\index.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\xampp2\htdocs\project\api-v2\node_modules\mongodb\index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
[2020-08-18T08:47:49.293Z] debug POST /auth/local/ (347 ms) 500
```
I'm not sure if `mongodb` related files should appear in the logs, since I am using **MySQL** in my application.
This is how my `database.js` Config file looks like:
```js
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: env('DATABASE_ADAPTER', 'mysql'),

        host:     env('DATABASE_HOST',     'localhost'),
        username: env('DATABASE_USERNAME', 'root'),
        password: env('DATABASE_PASSWORD', ''),
        database: env('DATABASE_NAME',     'api-v2'),
        port:     env.int('DATABASE_PORT', 3306),
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});
```

**Expected behavior**
The `/auth/local` route should validate my Credentials and provide a Token along with User-information.

**System**

- Node.js version: **v12.18.0**
- NPM version: **6.14.8**
- Strapi version: **3.1.4**
- Database: **MySQL**
- Operating system: **Windows 10 64-Bit**

**Additional Context:**
My `package.json` files looks as such:
```json
{
  "name": "api-v-2",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "mysql": "^2.18.1",
    "sqlite3": "latest",
    "strapi": "3.1.4",
    "strapi-admin": "3.1.4",
    "strapi-connector-bookshelf": "3.1.4",
    "strapi-middleware-cache": "^1.0.7",
    "strapi-plugin-content-manager": "3.1.4",
    "strapi-plugin-content-type-builder": "3.1.4",
    "strapi-plugin-email": "3.1.4",
    "strapi-plugin-upload": "3.1.4",
    "strapi-plugin-users-permissions": "3.1.4",
    "strapi-provider-email-sendgrid": "^3.1.4",
    "strapi-utils": "3.1.4"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "daed1c1f-1711-4e59-9903-4500c0b1609a"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

Could this be because I chose `quickstart` which includes SQLite3 instead of MySQL ?

**Comment by Demonicious** [comment]
Looks like the issue was just selecting the correct database during installation. My bad for not looking out for that.

Cheers.
