### ISSUE TITLE
ERROR:  relation "strapi_webhooks" does not exist

### ISSUE THREAD

**Issue by Gamsake** [strapi/strapi#7654]
**Describe the bug**
I have complex models and Initial database(pg) tables creation fails with clean start.
Even if deleting the cache folder, build folder, and db files, the results are always the same.
I don't even know what to do first.
Thanks!

```
[2020-08-31T03:44:50.119Z] debug ⛔️ Server wasn't able to start properly.
[2020-08-31T03:44:50.120Z] error error: relation "strapi_webhooks" does not exist
    at Parser.parseErrorMessage (/strapi/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/strapi/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/strapi/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/strapi/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
From previous event:
    at Client_PG._query (/strapi/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/strapi/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/strapi/node_modules/knex/lib/runner.js:135:36)
    at /strapi/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/strapi/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/strapi/node_modules/knex/lib/interface.js:14:43)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**System**
- Node.js version: 12.x lts
- Strapi version: 3.1.4 
- Database: postgres 12.x
- Operating system: Docker container (node:lts image)

**Comment by derrickmehaffy** [comment]
I'm not able to reproduce this, `strapi_webhooks` doesn't have a relation to anything. It would appear some part of your code is messed up somewhere, do you have a link to your project somewhere on Github?

https://github.com/strapi/strapi/blob/77be3ea4c596543d63e244a3bd7e92b486e2ba23/packages/strapi/lib/services/webhook-store.js#L6-L33

**Comment by Gamsake** [comment]
Before this issues raised, I realize that some tables are deleted on db.
But, I still do not understand that it doesn't solve even though I delete all db, caches, build files, docker images, docker containers.

**I solved this issue by recreating a new folder and doing clean installation step.**
