### ISSUE TITLE
error Error: secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by jonnyd70** [strapi/strapi#7680]
I was changing the server over to 80 from 1337 to throw up on AWS, and now I am getting this:

[2020-09-01T19:23:02.639Z] error Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\jsonwebtoken\sign.js:107:20)
    at Object.createJwtToken (C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\strapi-admin\services\token.js:32:14)
    at C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\strapi-admin\controllers\authentication.js:35:46
    at dispatch (C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\koa-compose\index.js:42:32)
    at C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\strapi-admin\controllers\authentication.js:27:16
    at callback (C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\koa-passport\lib\framework\koa.js:93:25)
    at Strategy.strategy.success (C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\passport\lib\middleware\authenticate.js:219:18)
    at verified (C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\passport-local\lib\strategy.js:83:10)
    at C:\Users\john.david\OneDrive - AMPTHINK LLC\strapi-project\mb-strapi\node_modules\strapi-admin\middlewares\auth\index.js:16:43
[2020-09-01T19:23:02.641Z] debug POST /admin/login (383 ms) 500

I removed my changes and built it back out, but the error is persisting. Not sure why, didn't change JWT or anything. Now it is not working on Hosted or localhost. Please help.

**Comment by derrickmehaffy** [comment]
You appear to be missing the `ADMIN_JWT_SECRET` for the Admin Panel authentication, please follow the bug report and we can try to assist you.

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by angelmeraz** [comment]
Stumbled upon this thread as I was having the same issue while trying to run v4.0.7. It looks that v4 docs aren't fully ready yet.
I resolved this error by adding a `./config/admin.js` file with the following config:

```module.exports = ({ env }) => ({
  apiToken: {
    salt: env('API_TOKEN_SALT', 'someRandomLongString'),
  },
  auth: {
    secret: env('ADMIN_JWT_SECRET', 'someSecretKey'),
  },
});
```
https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/admin-panel.html#available-options
