### ISSUE TITLE
can't update strapi CLI

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#794]
**Node.js version**:
9.7.1
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.3
**Operating system**:
Linux Mint 18.1

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I run `npm install strapi@alpha -g` to update my strapi but it's return below error on my console:

```
npm install strapi@alpha -g
npm ERR! code ETARGET
npm ERR! notarget No matching version found for mime-db@~1.33.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mime-types'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mnlbox/.npm/_logs/2018-03-17T16_05_55_215Z-debug.log
```

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Maybe Related:** #787

**Comment by lauriejim** [comment]
Hi @mnlbox I can't reproduce your issue. 
What is the npm registry you use ?

**Comment by mnlbox** [comment]
I use default npm registery. Now I have strapi version **3.0.0-alpha.10.3** and want to update to **3.0.0-alpha.11.1** so just run `npm install strapi@alpha -g` and this is my output:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for mime-db@~1.33.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mime-types'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mnlbox/.npm/_logs/2018-03-17T16_05_55_215Z-debug.log
```

**Comment by mnlbox** [comment]
@lauriejim I search a lot and some people said that clean npm cache can solve similar problem so I run `npm cache clean --force` and after that again run `npm install strapi@alpha -g` and anything works well now. :wink:

**Comment by mnlbox** [comment]
@lauriejim I want update my Strapi again but I faced new problem. My update process done completely without any issue but after run `strapi new myProject` I got this error:
```
mnlbox@mnlbox-pc ~/Desktop/Untitled Folder 6 $ strapi new myProject
[2018-04-03T08:15:03.090Z] info Creating your application... It might take a few seconds.
[2018-04-03T08:15:03.510Z] info Lets configurate the connection to your database:
 Choose your main database: MongoDB (highly recommended)
 Database name: strapi
 Host: 127.0.0.1
 Port: 27017
 Username: 
 Password: 
 Authentication database: 
 Enable SSL connection: false
[2018-04-03T08:15:19.776Z] info Testing database connection...
[2018-04-03T08:15:23.463Z] info The app has been connected to the database successfully!
[2018-04-03T08:15:23.499Z] info Copying the dashboard...
[2018-04-03T08:15:26.722Z] info Installing dependencies...
[2018-04-03T08:15:32.029Z] info The plugin settings-manager has been successfully installed.
[2018-04-03T08:15:33.951Z] error An error occurred during content-type-builder plugin installation.
[2018-04-03T08:15:33.952Z] error Command failed: node /home/mnlbox/.npm-global/lib/node_modules/strapi/bin/strapi.js install content-type-builder 
[2018-04-03T08:15:35.651Z] info The plugin content-manager has been successfully installed.
[2018-04-03T08:15:51.657Z] info The plugin users-permissions has been successfully installed.
[2018-04-03T08:15:55.321Z] info The plugin email has been successfully installed.
[2018-04-03T08:16:00.184Z] info The plugin upload has been successfully installed.
[2018-04-03T08:16:01.386Z] info The plugin analytics has been successfully installed.
[2018-04-03T08:16:01.386Z] info Linking `strapi` dependency to the project...
[2018-04-03T08:16:01.387Z] info Your new application `myProject` is ready at `/home/mnlbox/Desktop/Untitled Folder 6/myProject`.
```
And when I try to run my app I got another error about **Lodash** installation:
```
mnlbox@mnlbox-pc ~/Desktop/Untitled Folder 6 $ cd myProject
mnlbox@mnlbox-pc ~/Desktop/Untitled Folder 6/myProject $ strapi start
module.js:545
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mnlbox/Desktop/Untitled Folder 6/myProject/admin/controllers/Admin.js:5:11)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

And again It's fixed again after run `npm cache clean --force` why I need clear my cache every time for update CLI?
Is it normal? :thinking:

**Comment by lauriejim** [comment]
@mnlbox if you switch between local and npm installation, you will have to ren `npm i strapi@alpha -g` two times.

What is you actual version of Strapi ?

**Comment by mnlbox** [comment]
@lauriejim No I have only a global npm installation. I want update from 3.0.0-alpha.11.1to 3.0.0-alpha.11.2

**Comment by lauriejim** [comment]
So it works now ?

And cache problems come from your npm, I don't think it's come from Strapi.

**Comment by mnlbox** [comment]
It's work but I need clean my npm cache every time. I have some other npm in my system and none of them has this issue and my other global packages works well. :thinking:

**Comment by thebetterjort** [comment]
I have same issue from strapi-docker.
