### ISSUE TITLE
Cannot login as admin after upgrade from 3.0.5 to 3.1.5

### ISSUE THREAD

**Issue by Rigel772** [strapi/strapi#8056]
**Describe the bug**
I am not able to login at /admin
My Strapi works in docker container.
I noticed that new version require email address as login so before upgrading changed admin user name to email.
Could login without problem (on 3.0.5)
Than upgraded all dependacies in package.json to 3.1.5, rebuilt the UI and created new docker image which deployed with docker-compose.
The server works but when I try to login i get error 500.
```
[2020-09-25T18:28:56.433Z] debug POST /admin/login (132 ms) 500
[2020-09-25T18:29:26.054Z] error Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/api/node_modules/jsonwebtoken/sign.js:107:20)
    at Object.createJwtToken (/api/node_modules/strapi-admin/services/token.js:32:14)
    at /api/node_modules/strapi-admin/controllers/authentication.js:35:46
    at dispatch (/api/node_modules/koa-compose/index.js:42:32)
    at /api/node_modules/strapi-admin/controllers/authentication.js:27:16
    at callback (/api/node_modules/koa-passport/lib/framework/koa.js:93:25)
    at Strategy.strategy.success (/api/node_modules/passport/lib/middleware/authenticate.js:219:18)
    at verified (/api/node_modules/passport-local/lib/strategy.js:83:10)
    at /api/node_modules/strapi-admin/middlewares/auth/index.js:16:43
```
I tried to reset password and received email but when trying to submit new password I get error 400 Bad request.
```
[2020-09-25T18:56:42.992Z] debug GET /admin/auth/reset-password?code=66fcea8860dce50560bb628ad03943461c7ea0d7 (4 ms) 200
[2020-09-25T18:56:43.081Z] debug GET /admin/runtime~main.ee01ac0f.js (5 ms) 200
[2020-09-25T18:56:43.082Z] debug GET /admin/main.b44f2e43.chunk.js (3 ms) 200
[2020-09-25T18:56:45.808Z] debug GET /admin/init (5 ms) 200
[2020-09-25T18:56:45.988Z] debug GET /admin/07109cdae9f760e8d97c89788c9dc9df.png (2 ms) 200
[2020-09-25T18:56:46.018Z] debug GET /admin/75614cfcfedd509b1f7ac1c26c53bb7f.woff2 (4 ms) 200
[2020-09-25T18:56:46.021Z] debug GET /admin/842e7845f3f8e943ff712a39617b6b70.svg (7 ms) 200
[2020-09-25T18:56:46.032Z] debug GET /admin/a6069540692725c247f13984a9598a92.woff2 (8 ms) 200
[2020-09-25T18:56:46.034Z] debug GET /admin/21b3848a32fce5b0f5014948186f6964.woff2 (4 ms) 200
[2020-09-25T18:57:10.156Z] error Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/api/node_modules/jsonwebtoken/sign.js:107:20)
    at Object.createJwtToken (/api/node_modules/strapi-admin/services/token.js:32:14)
    at Object.resetPassword (/api/node_modules/strapi-admin/controllers/authentication.js:168:44)
    at async /api/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async /api/node_modules/strapi-utils/lib/policy.js:68:5
    at async /api/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-09-25T18:57:10.156Z] debug POST /admin/reset-password (164 ms) 500
[2020-09-25T18:58:17.422Z] debug GET /admin/main.b44f2e43.chunk.js (5 ms) 200
[2020-09-25T18:58:22.159Z] debug POST /admin/reset-password (12 ms) 400
```

What can I do?

**Steps to reproduce the behavior**

All described above.

**Comment by derrickmehaffy** [comment]
`error Error: secretOrPrivateKey must have a value` It appears you missed a step in one of our migration guides, see this one: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html#_2-define-the-admin-jwt-token

**Comment by derrickmehaffy** [comment]
Also be aware that admin panel logins are email only now

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed but please let us know know if you have more issues :smiley:

**Comment by Rigel772** [comment]
All clear now. Thank you

**Comment by sg1asgard** [comment]
Hi all,

We have the exact same issue but we cannot solve it as per documentation for migration.
If we add in line 7 of serve.js a second parameter for JWT I can login, like so:
`auth: {
      secret: env('ADMIN_JWT_SECRET', 'anything_string'),
    },`

If I just use as it should be, we cannot login:
`auth: {
      secret: env('ADMIN_JWT_SECRET'),
    },`
