### ISSUE TITLE
Connection Error: Connection ended unexpectedly

### ISSUE THREAD

**Issue by cawoodm** [strapi/strapi#8117]
We suddently started getting outages (strapi not responding, or responding with 500 errors). The logs are basically `Connection Error: Connection ended unexpectedly` which if you [google](https://www.google.com/search?q=%22Connection+ended+unexpectedly%22) results in several knex issues.

When we stop and start strapi the api responds again with 200 for a while.

There are no errors logged by the Postgress DB Server.

**System**
* NODE_ENV: production            
* Strapi Version: 3.1.0
* Node Version: v13.14.0
* Edition: Community             
*  Database: PostgreSQL
* Operating system: Windows 2012R2 and Linux (CentOS 7)

## Logs
```
[33mConnection Error: Connection ended unexpectedly[39m
[2020-09-30T19:20:27.666Z] error Error: select distinct "users-permissions_role".* from "users-permissions_role" where "users-permissions_role"."type" = $1 limit $2 - read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[33mConnection Error: Connection ended unexpectedly[39m
[2020-09-30T19:40:25.391Z] error Error: select distinct "users-permissions_role".* from "users-permissions_role" where "users-permissions_role"."type" = $1 limit $2 - Connection terminated unexpectedly
    at Connection.<anonymous> (D:\services\strapi\node_modules\pg\lib\client.js:255:9)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (D:\services\strapi\node_modules\pg\lib\connection.js:78:10)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[33mConnection Error: Connection ended unexpectedly[39m
[2020-09-30T19:40:45.971Z] error Error: select distinct "users-permissions_role".* from "users-permissions_role" where "users-permissions_role"."type" = $1 limit $2 - Connection terminated unexpectedly
    at Connection.<anonymous> (D:\services\strapi\node_modules\pg\lib\client.js:255:9)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (D:\services\strapi\node_modules\pg\lib\connection.js:78:10)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[33mConnection Error: Connection ended unexpectedly
```

**Comment by derrickmehaffy** [comment]
Couple of things that may or may not be related:

- `Node Version: v13.14.0` Strapi doesn't support node v13 or higher. We only support Node 10 and 12, and are actively working on support for v14 (which doesn't go LTS until the end of October).
- `Strapi Version: 3.1.0`  We have released 6 hotfixes for various issues since v3.1.0 and the current is v3.1.6, can you please try updating?
- Related to the `Error: Connection ended unexpectedly` Strapi is losing it's connection to the database and it appears the connection isn't being reestablished. I've tested a few different deployment types but I've never seen it not be able to reconnect. Based on the logs I'm guessing this is running on a Windows Server? Is the DB also on the same machine or is it remote?

**Comment by cawoodm** [comment]
The issue was network connectivity (connections being terminated by an F5  load balancer) and is now resolved.

**Comment by salihteyek** [comment]
I did a lot of research to solve this problem. These `pg` configurations solved my problem

`  
  acquireConnectionTimeout: 5000,
  pool: {
    min: 0,
    max: 10,
    createTimeoutMillis: 8000,
    acquireTimeoutMillis: 8000,
    idleTimeoutMillis: 8000,
    reapIntervalMillis: 1000,
    createRetryIntervalMillis: 100,
  },
`
