### ISSUE TITLE
Bootstrap Error Upgrading from 3.1.0 to 3.1.6

### ISSUE THREAD

**Issue by cawoodm** [strapi/strapi#8123]
Followed the [guide](https://strapi.io/documentation/v3.x/guides/update-version.html) but I cannot build the admin interface. The error is `Error: Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap.css' in 'C:\services\strapi\.cache\admin\src'`.

We've run `npm install` and also retried after a `npm prune`.

We've tried deleting `./build` and `.cache` directories.

* NodeJS: v12.2.0
* NPM: 6.9.0
* Host: Windows 10

## Logs
```
Error: Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap.css' in 'C:\services\strapi\.cache\admin\src'
    at C:\services\strapi\node_modules\strapi-admin\index.js:70:23
    at finalCallback (C:\services\strapi\node_modules\webpack\lib\Compiler.js:257:39)
    at onCompiled (C:\services\strapi\node_modules\webpack\lib\Compiler.js:265:20)
    at C:\services\strapi\node_modules\webpack\lib\Compiler.js:670:21
    at eval (eval at create (C:\services\strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:1173:13
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:1096:25
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:1017:13
    at C:\services\strapi\node_modules\neo-async\async.js:2830:7
    at C:\services\strapi\node_modules\neo-async\async.js:2830:7
    at done (C:\services\strapi\node_modules\neo-async\async.js:2863:11)
    at C:\services\strapi\node_modules\neo-async\async.js:2818:7
    at errorAndCallback (C:\services\strapi\node_modules\webpack\lib\Compilation.js:883:7)
    at errorOrWarningAndCallback (C:\services\strapi\node_modules\webpack\lib\Compilation.js:918:17)
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:924:16
    at C:\services\strapi\node_modules\webpack\lib\NormalModuleFactory.js:401:22
```

## Dependencies
```
    "knex": "^0.21.6",
    "pg": "^7.14.0",
    "sqlite3": "latest",
    "strapi": "3.1.6",
    "strapi-admin": "3.1.6",
    "strapi-connector-bookshelf": "3.1.6",
    "strapi-plugin-content-manager": "3.1.6",
    "strapi-plugin-content-type-builder": "3.1.6",
    "strapi-plugin-email": "3.1.6",
    "strapi-plugin-upload": "3.1.6",
    "strapi-plugin-users-permissions": "3.1.6",
    "strapi-utils": "3.1.6"
```

**Comment by derrickmehaffy** [comment]
I have seen this issue come up a few times and the only way I've ever seen to resolve it properly is:
- Delete the following files and folders:
`build .cache node_modules yarn.lock package-lock.json`
- Clear any local package cache you may have (NPM and/or Yarn)
- Reinstall packages
- Rebuild the Admin

**Comment by cawoodm** [comment]
That has not helped unfortunately.

## npm install log
```
npm WARN knex@0.21.6 requires a peer of mssql@^6.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.21.6 requires a peer of mysql@^2.18.1 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.21.6 requires a peer of mysql2@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN strapi-connector-bookshelf@3.1.6 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1545 packages in 5.523s
found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by derrickmehaffy** [comment]
The messages in that log aren't errors and are just warnings that can be ignored

**Comment by derrickmehaffy** [comment]
As no error found, marking as closed.

**Comment by cawoodm** [comment]
Sorry, I was away. There seems to be a misunderstanding: the original error posted has not gone away and we cannot start the admin ui at `/admin` (404):

`npm build` or `node ./node_modules/strapi/bin/strapi.js build` 

```
> strapi@1.0.1 build C:\services\strapi
> node ./node_modules/strapi/bin/strapi.js build

Building your admin UI with development configuration ...

* Webpack █████████████████████████ building (10%) 2/14 modules 12 active
 babel-loader » .cache\admin\src\containers\NotificationProvider\actions.js

Error: Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap.css' in 'C:\services\strapi\.cache\admin\src'
    at C:\services\strapi\node_modules\strapi-admin\index.js:70:23
    at finalCallback (C:\services\strapi\node_modules\webpack\lib\Compiler.js:257:39)
    at onCompiled (C:\services\strapi\node_modules\webpack\lib\Compiler.js:265:20)
    at C:\services\strapi\node_modules\webpack\lib\Compiler.js:670:21
    at eval (eval at create (C:\services\strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:1173:13
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:1096:25
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:1017:13
    at C:\services\strapi\node_modules\neo-async\async.js:2830:7
    at C:\services\strapi\node_modules\neo-async\async.js:2830:7
    at done (C:\services\strapi\node_modules\neo-async\async.js:2863:11)
    at C:\services\strapi\node_modules\neo-async\async.js:2818:7
    at errorAndCallback (C:\services\strapi\node_modules\webpack\lib\Compilation.js:883:7)
    at errorOrWarningAndCallback (C:\services\strapi\node_modules\webpack\lib\Compilation.js:918:17)
    at C:\services\strapi\node_modules\webpack\lib\Compilation.js:924:16
    at C:\services\strapi\node_modules\webpack\lib\NormalModuleFactory.js:401:22
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by cawoodm** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Prg\\node\\nodejs\\node.exe',
1 verbose cli   'C:\\Prg\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle strapi@1.0.1~prebuild: strapi@1.0.1
6 info lifecycle strapi@1.0.1~build: strapi@1.0.1
7 verbose lifecycle strapi@1.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle strapi@1.0.1~build: CWD: C:\services\strapi
10 silly lifecycle strapi@1.0.1~build: Args: [ '/d /s /c', 'node ./node_modules/strapi/bin/strapi.js build' ]
11 silly lifecycle strapi@1.0.1~build: Returned: code: 1  signal: null
12 info lifecycle strapi@1.0.1~build: Failed to exec build script
13 verbose stack Error: strapi@1.0.1 build: `node ./node_modules/strapi/bin/strapi.js build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Prg\node\nodejs12\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Prg\node\nodejs12\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
14 verbose pkgid strapi@1.0.1
15 verbose cwd C:\services\strapi
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Prg\\node\\nodejs\\node.exe" "C:\\Prg\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.2.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error strapi@1.0.1 build: `node ./node_modules/strapi/bin/strapi.js build`
22 error Exit status 1
23 error Failed at the strapi@1.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by derrickmehaffy** [comment]
`strapi@1.0.1` You appear to have some issues either in your package.json, package-lock.json/yarn.lock, or some kind of critical caching error. Strapi 1.0.1 hasn't been used in over 3 years.

**Comment by cawoodm** [comment]
Our package.json contains `"version": "1.0.1",` this is the version of our strapi project and should make no difference to anyone. The strapi dependency is `"strapi": "3.1.6",`.

**Comment by cawoodm** [comment]
## package.json

```
{
  "name": "strapi",
  "version": "1.0.1",
  "description": "",
  "main": "server.js",
  "private": true,
  "scripts": {
    "foo": "echo foo",
    "develop": "node ./node_modules/strapi/bin/strapi.js develop",
    "start": "node ./node_modules/strapi/bin/strapi.js start",
    "build": "node ./node_modules/strapi/bin/strapi.js build",
    "strapi": "node ./node_modules/strapi/bin/strapi.js"
  },
  "dependencies": {
    "knex": "^0.21.6",
    "pg": "^8.3.3",
    "sqlite3": "latest",
    "strapi": "3.1.6",
    "strapi-admin": "3.1.6",
    "strapi-connector-bookshelf": "3.1.6",
    "strapi-plugin-content-manager": "3.1.6",
    "strapi-plugin-content-type-builder": "3.1.6",
    "strapi-plugin-email": "3.1.6",
    "strapi-plugin-upload": "3.1.6",
    "strapi-plugin-users-permissions": "3.1.6",
    "strapi-utils": "3.1.6"
  },
  "engines": {
    "node": ">=12.0.0",
    "npm": ">=6.0.0"
  }
}
```

**Comment by cawoodm** [comment]
Bumping the package.json version to 3.1.6 makes no difference.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@3.1.6 build: `node ./node_modules/strapi/bin/strapi.js build`
npm ERR! Exit status 1
```

**Comment by derrickmehaffy** [comment]
That makes it a little more clear then :wink: 

If this error is still showing up:
`Error: Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap.css' in 'C:\services\strapi\.cache\admin\src'`

I'm still leaning towards a cache problem, can you try to delete your `node_modules`, `package-lock.json`, `yarn.lock`, `build`, and `.cache` folders then reinstall the node_modules and attempt to rebuild the admin? 

Also it may be verify your npm registry: 
![image](https://user-images.githubusercontent.com/8593673/96510867-07d4d780-1213-11eb-99d0-379693df4e1d.png)

**Comment by cawoodm** [comment]
Yep, doing that again fixed it this time thanks.
