### ISSUE TITLE
Cannot Login After Migration

### ISSUE THREAD

**Issue by emaddoma** [strapi/strapi#8134]
**Describe the bug**
I am migrating from 3.0.0-beta.19.5 to 3.1.6

**Steps to reproduce the behavior**

I followed the closest migration guide available.  I created config/server.js and config/jwt.js.  My database is configured properly and the host for the application is being set correctly as well.  I deleted my strapi_administrator record and started the server.  I filled out the registration form and the new user is created, but I immediately get an error and cannot login.  If I log out the ADMIN_JWT_SECRET and JWT_SECRET from either of the configs they appear to be set correct from my .env file.

`[2020-10-01T16:14:18.731Z] error Error: Invalid token.
    at /Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/strapi-plugin-users-permissions/services/Jwt.js:58:27
    at /Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/jsonwebtoken/verify.js:133:14
    at getSecret (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/jsonwebtoken/verify.js:94:10)
    at /Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/strapi-plugin-users-permissions/services/Jwt.js:52:11
    at new Promise (<anonymous>)
    at Object.verify (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/strapi-plugin-users-permissions/services/Jwt.js:51:12)
    at Object.getToken (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/strapi-plugin-users-permissions/services/Jwt.js:38:17)
    at module.exports (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/extensions/users-permissions/config/policies/permissions.js:49:32)
    at dispatch (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/koa-compose/index.js:42:32)
    at /Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/strapi-utils/lib/policy.js:68:11
    at dispatch (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/koa-compose/index.js:42:32)
    at /Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/erikmadsen/Documents/Projects/GWBD/tripchat-la-api/node_modules/koa-router/lib/router.js:346:16`

**Expected behavior**
I should be logged in or able to log in after new administrator is created.

**Screenshots**
N/A

**Code snippets**
N/A

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.1.6
- Database: Postgres 11
- Operating system: macOS 10.15.7

**Additional context**

**Comment by derrickmehaffy** [comment]
Is your project somewhere I can take a look. Also where did you get the `./config/jwt.js` from as I don't believe that is actually used?

**Comment by derrickmehaffy** [comment]
Also did you follow all of the migration guides:
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.html
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html

**Comment by derrickmehaffy** [comment]
It would appear some stuff isn't quite right with the migration, do you have a link to your project on GitHub so I can take a look?

**Comment by emaddoma** [comment]
@derrickmehaffy I ended up creating a new application with the CLI, updating the config and copying the api directory contents from the old version to the new version and it works fine.

**Comment by MattieBelt** [comment]
Hey @amirulabu, please read the guide again. 

You need to create a new token for the new feature in the admin panel JWT.
So you need to create a new token for the config in `./config/server.js`, the JWT you are referring to (the users-permissions plugin JWT) does not need to be changed.
