### ISSUE TITLE
"Query for sharded findAndModify must contain the shard key" when creating a new field

### ISSUE THREAD

**Issue by Blacknosaur** [strapi/strapi#8186]
**Describe the bug**
In Strapi 3.1.4, running Mongoose with a sharded MongoDB cluster, when creating a new field in a model through the CMS or manually in the whichevermodel.settings.json, it doesn't reload anymore.

**Steps to reproduce the behavior**
Just create a field or relation and let it restart make it crash and doesn't go up again with this error

```
[2020-10-05T11:10:50.668Z] error Bootstrap function in admin failed
[2020-10-05T11:10:50.675Z] error MongoError: Query for sharded findAndModify must contain the shard key
    at Connection.<anonymous> (/Users/blacknosaur/CODE/kids-and-us-strapi/node_modules/mongodb/lib/core/connection/pool.js:460:61)
    at Connection.emit (events.js:315:20)
    at processMessage (/Users/blacknosaur/CODE/kids-and-us-strapi/node_modules/mongodb/lib/core/connection/connection.js:368:10)
    at TLSSocket.<anonymous> (/Users/blacknosaur/CODE/kids-and-us-strapi/node_modules/mongodb/lib/core/connection/connection.js:537:15)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
error Command failed with exit code 1.
```

The only way I have found to make it run again is deleting the references to the new field from the settings.json.

Searching in Mongoose documentation I saw the [shardKey property](https://mongoosejs.com/docs/guide.html#shardKey) which seemed unconfigured in strapi-mongoose-connector but I couldn't make it work. I tracked this Mongoose options to the file mount-models.js and edited this shardKey option there, adding `schema.set('shardKey', { location: 1 })` or 
```
const schema = new instance.Schema(
      _.omitBy(definition.loadedModel, ({ type }) => type === 'virtual'),
     { shardKey: { location: 1 } } 
);
```
(Location should be the shardKey, btw)

**Expected behavior**
It should restart after modifying the model and work as usual

**System**

- Node.js version: v12.18.3
- NPM version: v6.14.6
- Strapi version: v3.1.4
- Database: Sharded MongoDB cluster (Mongo Atlas with globalWrites, two servers, one in EU and one in USA)
- Operating system: Ubuntu 18

**Comment by derrickmehaffy** [comment]
> Mongo Atlas with globalWrites, two servers, one in EU and one in USA
O_o? 

Can you provide any of the configuration options you are passing in your database.js file?

**Comment by derrickmehaffy** [comment]
Closing as user hasn't responded
