### ISSUE TITLE
Spread Operator not recognized by babel when building

### ISSUE THREAD

**Issue by sorob** [strapi/strapi#844]
**Node.js version**: v9.9.0

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: OSX

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
After cloning and building the repo, generating a new project with --dev, linking the strapi in both root and admin forlder, I managed to create and debug my plugin successfully. Now when I try to build with
```
osx:admin $ npm run build --plugins
```
I get errors about babel not recognizing the spread operator!

```

> strapi-admin@3.0.0-alpha.11.1 build /Users/sorob/Documents/strapi/packages/strapi-admin
> APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress


> strapi-admin@3.0.0-alpha.11.1 build:dll /Users/sorob/Documents/strapi/packages/strapi-admin
> APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.dll.babel.js --color -p --progress

Hash: 6c4619afab00f2f13390                                                              
Version: webpack 3.11.0
Time: 6512ms
            Asset       Size  Chunks                    Chunk Names
    vendor.dll.js     493 kB       0  [emitted]  [big]  vendor
vendor.dll.js.map  168 bytes       0  [emitted]         vendor
 [135] dll vendor 12 bytes {0} [built]
    + 381 hidden modules
  0% compiling/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/sorob/Documents/strapi/packages/strapi-plugin-users-permissions/services/UsersPermissions.js: Unexpected token (34:12)
  32 |             controller,
  33 |             action: action.toLowerCase(),
> 34 |             ...params.permissions[type].controllers[controller][action]
     |             ^
  35 |           }));
  36 |         });
  37 |       });
    at Parser.pp$5.raise (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$3.parseArrowExpression (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:4190:8)
    at Parser.pp$3.parseExprAtom (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3665:21)
    at Parser.pp$3.parseExprSubscripts (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/sorob/Documents/strapi/packages/strapi-helper-plugin/node_modules/babylon/lib/index.js:3474:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.11.1 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.11.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sorob/.npm/_logs/2018-03-25T19_54_50_105Z-debug.log
```
**What is the expected behavior?**
Should build the plugins?

**Comment by soupette** [comment]
You should run `npm run build` in your app directory instead of the strapi's repository

**Comment by abdonrd** [comment]
It seems the same problem as https://github.com/strapi/strapi/issues/858.
