### ISSUE TITLE
Uploading a file of more than 2mb with a S3 compatible provider fails with ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by tommasongr** [strapi/strapi#8449]
### Describe the bug

I'm trying to implement a provider for Linode Object Storage (S3 compatible) but uploading a file of more than 2mb fails.

### Steps to reproduce the behavior

1. Go to 'Media Library'
2. Click on 'Upload assets'
3. Select a file of more than 2mb
4. Click 'Upload'

### Expected behavior

The file should be uploaded as well as all the other files under 2mb

### Screenshots

<img width="920" alt="Schermata 2020-10-22 alle 23 57 51" src="https://user-images.githubusercontent.com/25225746/96934453-7f7c5e00-14c2-11eb-8982-6e082d3ad2d0.png">

### Code snippets

The promise reject with this error:
```shell
[2020-10-22T21:42:15.336Z] [2020-10-22t21:42:15.331z] error Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ClientRequest.end (_http_outgoing.js:788:7)
    at features.constructor.writeBody (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/aws-sdk/lib/http/node.js:137:14)
    at ClientRequest.<anonymous> (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/aws-sdk/lib/http/node.js:102:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:606:11)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
[2020-10-22T21:42:15.337Z] error Error: Internal Server Error
    at convertToStrapiError (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/errors.js:36:26)
    at Object.upload (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.uploadFileAndPersist (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/services/Upload.js:153:5)
    at async Promise.all (index 0)
    at async Object.upload (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/services/Upload.js:139:12)
    at async uploadFiles (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/controllers/upload/admin.js:186:27)
    at async Object.upload (/Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-plugin-upload/controllers/Upload.js:64:5)
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi-utils/lib/policy.js:68:5
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /Users/tommaso/Developer/Websites/rise-media/rise-backend/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-10-22T21:42:15.338Z] debug POST /upload (3016 ms) 500
```

This is the provider implementation:
```js
const AWS = require('aws-sdk')

const trimParam = (str) => (typeof str === 'string' ? str.trim() : undefined)

module.exports = {
    init(providerOptions) {
        const S3 = new AWS.S3({
            accessKeyId: trimParam(providerOptions.accessKeyId),
            secretAccessKey: trimParam(providerOptions.secretAccessKey),
            apiVersion: '2006-03-01',
            endpoint: new AWS.Endpoint(providerOptions.cluster),
            params: {
                Bucket: providerOptions.bucket,
            },
        })

        return {
            upload(file) {
                return new Promise((resolve, reject) => {
                    // upload file on S3 bucket
                    const path = file.path ? `${file.path}/` : ''
                    S3.upload(
                        {
                            Key: `${path}${file.hash}${file.ext}`,
                            Body: Buffer.from(file.buffer, 'binary'),
                            ACL: 'public-read',
                            ContentType: file.mime,
                        },
                        (err, data) => {
                            strapi.log.debug(this)
                            if (err) {
                                return reject(err)
                            }

                            file.url = data.Location

                            resolve()
                        }
                    )
                })
            },
            delete(file) {
                return new Promise((resolve, reject) => {
                    // delete file on S3 bucket
                    const path = file.path ? `${file.path}/` : ''
                    S3.deleteObject(
                        {
                            Key: `${path}${file.hash}${file.ext}`,
                        },
                        (err, data) => {
                            if (err) {
                                return reject(err)
                            }

                            resolve()
                        }
                    )
                })
            },
        }
    },
}
```

### System

- Node.js version: v14.14.0
- NPM version: v6.14.8
- Strapi version: v3.2.4
- Database: postgresql
- Operating system: macOS Beta 11.0

### Additional context

This is not a Linode limitation since manual upload works with no problem. Their support team confirmed it.

**Comment by tommasongr** [comment]
I did more tests and with DigitalOcean this problem goes away, apparently is a Linode fall or at this point I guess a problem with the request header their API needs.

Although with DigitalOcean I'm having another UI problem.
<img width="1233" alt="Schermata 2020-10-23 alle 13 00 16" src="https://user-images.githubusercontent.com/25225746/96996193-bb99d800-152f-11eb-9e85-7bff7c5f1eb3.png">
As you can see fairly large images are not shown correctly in the media library

**Comment by derrickmehaffy** [comment]
@tommasongr is this a custom provider or are you using our existing s3 provider: https://github.com/strapi/strapi/tree/master/packages/strapi-provider-upload-aws-s3

**Comment by derrickmehaffy** [comment]
While it's a different error (likely due to some missing parser middleware configs, going to mark as a duplicate of https://github.com/strapi/strapi/issues/8620
