### ISSUE TITLE
Error: Value.map is not a function. Happens upon adding data to a relation data type inside a dynamic zone.

### ISSUE THREAD

**Issue by Givemeurcookies** [strapi/strapi#8473]
### Describe the bug

I get value.map is not a function after trying to add data to a relation data type that is inside a dynamic zone.

`error TypeError: value.map is not a function
    at reducerFn (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/strapi-utils/lib/sanitize-entity.js:77:29)
    at /home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:914:11
    at /home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:2990:24)
    at /home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:4894:18
    at baseReduce (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:911:5)
    at Function.reduce (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:9707:14)
    at sanitizeEntity (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/strapi-utils/lib/sanitize-entity.js:95:12)
    at reducerFn (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/strapi-utils/lib/sanitize-entity.js:68:11)
    at /home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:914:11
    at /home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:2990:24)
    at /home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:4894:18
    at baseReduce (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:911:5)
    at Function.reduce (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/lodash/lodash.js:9707:14)
    at sanitizeEntity (/home/mrgemeco/web/libs/strapi/Bitkraken-v20/node_modules/strapi-utils/lib/sanitize-entity.js:95:12)`

### Steps to reproduce the behavior

1. Create a collection type (I'll name this one A01 for clearity). Add an entry.
2. Create a component containing a relation data type.
3. Create another collection type (A02) with a dynamic zone with the component that has the relation data type inside it.
4. Create a new entry in A02, add dynamic zone, try to link the entry at collection A01.
5. This is where I get the error value.map is not a function. If I go to another site and try to access the collection A02 again I will get "An error occured during models config fetch.

### Expected behavior

I expect to be able to link other collections inside dynamic zones.

### System

- Node.js version: 12.19.0
- NPM version:  6.14.8
- Strapi version: 3.2.5
- Database: SQLite
- Operating system: Debian Stretch

**Comment by derrickmehaffy** [comment]
@Givemeurcookies can you please provide a sample project to test with as the relational structure you laid out in your steps isn't very clear.

**Comment by derrickmehaffy** [comment]
Test Project:
[test8473.zip](https://github.com/strapi/strapi/files/5560839/test8473.zip)

Unable to reproduce this in v3.3.3, going to mark as closed for now as the user didn't respond to clarify if we are missing something.
