### ISSUE TITLE
knex compiler error when i create collection named "Query" and create foreign key to it

### ISSUE THREAD

**Issue by Zverushko** [strapi/strapi#8538]
hello!
subject

i give error:
error Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [queries.id] query: select distinct `queries`.* from `queries` where `queries`.`id` = ? limit ?
    at QueryCompiler_SQLite3.toSQL (/home/zverushko/promodb/node_modules/knex/lib/query/compiler.js:101:13)
    at Builder.toSQL (/home/zverushko/promodb/node_modules/knex/lib/query/builder.js:76:44)
    at /home/zverushko/promodb/node_modules/knex/lib/runner.js:30:36
From previous event:
    at Runner.run (/home/zverushko/promodb/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/home/zverushko/promodb/node_modules/knex/lib/interface.js:14:43)
    at processImmediate (internal/timers.js:461:21)

fresh install

**Comment by Zverushko** [comment]
if i renamed "Query" to "Request" - error lost

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
