### ISSUE TITLE
Strapi + Heroku RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN

### ISSUE THREAD

**Issue by jddelia** [strapi/strapi#8555]
I am experiencing this issue when I try to deploy to Heroku.

The logs show:

[2020-11-03T03:11:18.771Z] error RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.
2020-11-03T03:11:18.771421+00:00 app[web.1]: at validatePort (internal/validators.js:211:11)
2020-11-03T03:11:18.771422+00:00 app[web.1]: at lookupAndConnect (net.js:1000:5)
2020-11-03T03:11:18.771422+00:00 app[web.1]: at Socket.connect (net.js:976:5)
2020-11-03T03:11:18.771423+00:00 app[web.1]: at Connection.connect (/app/node_modules/pg/lib/connection.js:39:17)
2020-11-03T03:11:18.771423+00:00 app[web.1]: at Client._connect (/app/node_modules/pg/lib/client.js:113:11)
2020-11-03T03:11:18.771423+00:00 app[web.1]: at Client.connect (/app/node_modules/pg/lib/client.js:161:12)
2020-11-03T03:11:18.771423+00:00 app[web.1]: at /app/node_modules/knex/lib/dialects/postgres/index.js:110:18
2020-11-03T03:11:18.771424+00:00 app[web.1]: at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:384:9)
2020-11-03T03:11:18.771424+00:00 app[web.1]: at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:518:18)
2020-11-03T03:11:18.771424+00:00 app[web.1]: at new Promise (/app/node_modules/bluebird/js/release/promise.js:103:10)
2020-11-03T03:11:18.771427+00:00 app[web.1]: at Client_PG.acquireRawConnection (/app/node_modules/knex/lib/dialects/postgres/index.js:108:12)
2020-11-03T03:11:18.771428+00:00 app[web.1]: at create (/app/node_modules/knex/lib/client.js:258:21)
2020-11-03T03:11:18.771428+00:00 app[web.1]: at /app/node_modules/tarn/lib/Pool.js:389:34
2020-11-03T03:11:18.771428+00:00 app[web.1]: at Object.tryPromise (/app/node_modules/tarn/lib/utils.js:53:24)
2020-11-03T03:11:18.771428+00:00 app[web.1]: at /app/node_modules/tarn/lib/Pool.js:389:17
2020-11-03T03:11:18.771429+00:00 app[web.1]: at new Promise (<anonymous>)
2020-11-03T03:11:18.792609+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-11-03T03:11:18.792881+00:00 app[web.1]: npm ERR! errno 1
2020-11-03T03:11:18.797854+00:00 app[web.1]: npm ERR! jamasia-eats-cms@0.1.0 start: `strapi start`
2020-11-03T03:11:18.797947+00:00 app[web.1]: npm ERR! Exit status 1
2020-11-03T03:11:18.798048+00:00 app[web.1]: npm ERR!
2020-11-03T03:11:18.798125+00:00 app[web.1]: npm ERR! Failed at the jamasia-eats-cms@0.1.0 start script.
2020-11-03T03:11:18.798198+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-11-03T03:11:18.803983+00:00 app[web.1]: 
2020-11-03T03:11:18.804117+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-11-03T03:11:18.804207+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-11-03T03_11_18_798Z-debug.log
2020-11-03T03:11:18.854711+00:00 heroku[web.1]: Process exited with status 1
2020-11-03T03:11:18.886481+00:00 heroku[web.1]: State changed from starting to crashed
2020-11-03T03:11:33.000000+00:00 app[api]: Build succeeded
2020-11-03T03:12:14.646802+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=jamasia-eats-cms.herokuapp.com request_id=0b85fdbe-95b1-4715-8875-62641d874081 fwd="75.74.17.84" dyno= connect= service= status=503 bytes= protocol=https

I've tried the suggested solution on issue 6673 (https://github.com/strapi/strapi/issues/6673), no effect.

Any help would be appreciated.

**Comment by derrickmehaffy** [comment]
While your issue likely doesn't need the full bug report template it is still required, however your issue likely relates to something setting your `PORT` environment variable to something that isn't a number (or undefined) please try setting your Heroku environment variable `PORT` to `1337` either via the heroku CLI or in their web interface.

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by jddelia** [comment]
## Bug report

### Describe the bug

I am getting a bad port error.

error RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.

Here is my server.js:

module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', process.env.PORT || 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '<SECRET>'),
    },
  },
});

### Steps to reproduce the behavior

I followed the steps on (postgres) https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html

After pushing to heroku, the error occurs.

### Expected behavior

It should deploy without error.

### Screenshots

If applicable, add screenshots to help explain your problem.

### Code snippets

2020-11-04T02:13:11.000000+00:00 app[api]: Build succeeded
2020-11-04T02:13:16.006193+00:00 heroku[web.1]: Starting process with command `npm start`
2020-11-04T02:13:18.884594+00:00 app[web.1]: 
2020-11-04T02:13:18.884618+00:00 app[web.1]: > jamasia-eats-cms@0.1.0 start /app
2020-11-04T02:13:18.884619+00:00 app[web.1]: > strapi start
2020-11-04T02:13:18.884619+00:00 app[web.1]: 
2020-11-04T02:13:20.763968+00:00 app[web.1]: [2020-11-04T02:13:20.762Z] debug ⛔ Server wasn't able to start properly.
#2020-11-04T02:13:20.764919+00:00 app[web.1]: [2020-11-04T02:13:20.764Z] error RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.
2020-11-04T02:13:20.764921+00:00 app[web.1]: at lookupAndConnect (net.js:988:13)
2020-11-04T02:13:20.764922+00:00 app[web.1]: at Socket.connect (net.js:963:5)
2020-11-04T02:13:20.764922+00:00 app[web.1]: at Connection.connect (/app/node_modules/pg/lib/connection.js:39:17)
2020-11-04T02:13:20.764923+00:00 app[web.1]: at Client._connect (/app/node_modules/pg/lib/client.js:113:11)
2020-11-04T02:13:20.764923+00:00 app[web.1]: at Client.connect (/app/node_modules/pg/lib/client.js:161:12)
2020-11-04T02:13:20.764923+00:00 app[web.1]: at /app/node_modules/knex/lib/dialects/postgres/index.js:110:18
2020-11-04T02:13:20.764924+00:00 app[web.1]: at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:384:9)
2020-11-04T02:13:20.764925+00:00 app[web.1]: at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:518:18)
2020-11-04T02:13:20.764925+00:00 app[web.1]: at new Promise (/app/node_modules/bluebird/js/release/promise.js:103:10)
2020-11-04T02:13:20.764926+00:00 app[web.1]: at Client_PG.acquireRawConnection (/app/node_modules/knex/lib/dialects/postgres/index.js:108:12)
2020-11-04T02:13:20.764927+00:00 app[web.1]: at create (/app/node_modules/knex/lib/client.js:258:21)
2020-11-04T02:13:20.764927+00:00 app[web.1]: at /app/node_modules/tarn/lib/Pool.js:389:34
2020-11-04T02:13:20.764928+00:00 app[web.1]: at Object.tryPromise (/app/node_modules/tarn/lib/utils.js:53:24)
2020-11-04T02:13:20.764928+00:00 app[web.1]: at /app/node_modules/tarn/lib/Pool.js:389:17
2020-11-04T02:13:20.764928+00:00 app[web.1]: at new Promise (<anonymous>)
2020-11-04T02:13:20.764929+00:00 app[web.1]: at callbackOrPromise (/app/node_modules/tarn/lib/Pool.js:380:12)
2020-11-04T02:13:20.782115+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-11-04T02:13:20.782582+00:00 app[web.1]: npm ERR! errno 1
2020-11-04T02:13:20.792126+00:00 app[web.1]: npm ERR! jamasia-eats-cms@0.1.0 start: `strapi start`
2020-11-04T02:13:20.792502+00:00 app[web.1]: npm ERR! Exit status 1
2020-11-04T02:13:20.792827+00:00 app[web.1]: npm ERR!
2020-11-04T02:13:20.793056+00:00 app[web.1]: npm ERR! Failed at the jamasia-eats-cms@0.1.0 start script.
2020-11-04T02:13:20.793234+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-11-04T02:13:20.799565+00:00 app[web.1]: 
2020-11-04T02:13:20.799691+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-11-04T02:13:20.799790+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-11-04T02_13_20_794Z-debug.log
2020-11-04T02:13:20.845441+00:00 heroku[web.1]: Process exited with status 1
2020-11-04T02:13:20.882207+00:00 heroku[web.1]: State changed from starting to crashed


### System

- Node.js version: 12.13.0
- NPM version: 6.11.2
- Strapi version: 3.0.0-alpha.25.2
- Database: Postgres
- Operating system: Ubuntu 18.04

### Additional context

Add any other context about the problem here.

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-alpha.25.2` You are using a version of Strapi we no longer support and haven't supported in probably 2 years. Can you please test with a fresh project on the latest version and should that work you will need to update your project following our migration guides: https://strapi.io/documentation/v3.x/migration-guide/#instructions

**Comment by jddelia** [comment]
When I run `strapi --version`, I get this: `3.0.0-alpha.25.2`

The package json has always looked like this:

`{
  "name": "test-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "^8.4.2",
    "sqlite3": "latest",
    "strapi": "3.2.5",
    "strapi-admin": "3.2.5",
    "strapi-connector-bookshelf": "3.2.5",
    "strapi-plugin-content-manager": "3.2.5",
    "strapi-plugin-content-type-builder": "3.2.5",
    "strapi-plugin-email": "3.2.5",
    "strapi-plugin-upload": "3.2.5",
    "strapi-plugin-users-permissions": "3.2.5",
    "strapi-utils": "3.2.5"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": ""
  },
  "engines": {
    "node": "12.13.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}`

So I gave the wrong version.

**Comment by derrickmehaffy** [comment]
Can you please provide your `./config/server.js` and if you have one your `./config/env/production/server.js` (Exclude any private information)

**Comment by jddelia** [comment]
Here is the `./config/server.js`:

module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', process.env.PORT || 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '<SECRET>'),
    },
  },
});

I dont have `./config/env/production/server.js`

**Comment by derrickmehaffy** [comment]
`port: env.int('PORT', process.env.PORT || 1337)` you don't need to specify the `process.env` as that function `env.int()` parses environment variables.

All you need is:
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '<SECRET>'),
    },
  },
});
```

But if you still have problem you can just statically define the port:

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: 1337,
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '<SECRET>'),
    },
  },
});
```

**Comment by renrizzolo** [comment]
Not sure if this helps anyone, but I had this issue when I copied the database.json config from here: https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html#_4-update-your-database-config-file into my existing database.js file, without realizing they were different files. So I just had to remove the quotes from the JSON strings.

**Comment by jddelia** [comment]
> Not sure if this helps anyone, but I had this issue when I copied the database.json config from here: https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html#_4-update-your-database-config-file into my existing database.js file, without realizing they were different files. So I just had to remove the quotes from the JSON strings.

FIXED when following this suggestion.

Thanks

**Comment by tobiasjayas** [comment]
> Not sure if this helps anyone, but I had this issue when I copied the database.json config from here: https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html#_4-update-your-database-config-file into my existing database.js file, without realizing they were different files. So I just had to remove the quotes from the JSON strings.

what do you mean by remove the quotes from the JSON strings?

**Comment by renrizzolo** [comment]
I had copied JSON into a JS file without realizing.

`"host": "${process.env.DATABASE_HOST}",`
Needed to be changed to
```host: process.env.DATABASE_HOST,```

**Comment by tobiasjayas** [comment]
> I had copied JSON into a JS file without realizing.
> 
> `"host": "${process.env.DATABASE_HOST}",`
> Needed to be changed to
> `host: process.env.DATABASE_HOST,`

okay thanks bro

**Comment by NLeRoy917** [comment]
I ran into this too. I think I was looking at the wrong docs. [These](https://strapi.io/documentation/v3.x/deployment/heroku.html) are the most recent docs for deployment to Heroku. I used these, and it worked perfectly. If anyone stumbles on this, try these docs instead. To be specific, this is the text required in the `config/database.js` file

```
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL);

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: config.host,
        port: config.port,
        database: config.database,
        username: config.user,
        password: config.password,
      },
      options: {
        ssl: false,
      },
    },
  },
});
```

**Comment by agomez99** [comment]
This helped my Postgres configuration thanks!
