### ISSUE TITLE
Error on create strapi-app

### ISSUE THREAD

**Issue by hugofabricio** [strapi/strapi#8637]
## Bug report
Error on create strapi app with npm or yarn.

### Describe the bug
When I try to create a new project, I get errors relating to a few libs, I tried to test on 2 more computers and I received the same error.

### Steps to reproduce the behavior

1. yarn create strapi-app project-name or npx create-strapi-app project-name
2. Configure database settings and proceed to install dependencies.
3. See error

```
yarn create strapi-app api-lp
yarn create v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-strapi-app@3.3.2" with binaries:
      - create-strapi-app
Creating a new Strapi application at /Users/user/Sites/react-avancado/react-avancado-api/api-lp.

? Choose your installation type Custom (manual settings)
? Choose your default database client mysql
? Database name: strapi
? Host: 127.0.0.1
? Port: 3306
? Username: strapi
? Password: ******
? Enable SSL connection: No

Creating a project with custom database options.
Creating files.
Error while installing dependencies:
warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi-admin > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning strapi-admin > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > react-intl > @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
warning strapi-admin > react-intl > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > react-intl > intl-messageformat > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning strapi-admin > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.25" required by "@buffetjs/core@3.3.1" on the "npm" registry.
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.14.0" required by "strapi-admin@3.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.11.2" required by "@buffetjs/core@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.10.2" required by "@buffetjs/styles@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.7" required by "strapi-admin@3.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.4" required by "@buffetjs/core@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.4" required by "@buffetjs/styles@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/fontawesome-free@^5.11.2" required by "strapi-admin@3.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/fontawesome-free@^5.12.0" required by "@buffetjs/styles@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.32" required by "strapi-admin@3.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.22" required by "@buffetjs/styles@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/free-brands-svg-icons@^5.11.2" required by "strapi-admin@3.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/free-regular-svg-icons@^5.11.2" required by "@buffetjs/core@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@fortawesome/free-regular-svg-icons@^5.10.2" required by "@buffetjs/styles@3.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd /Users/user/Sites/react-avancado/react-avancado-api/api-lp && yarn install

error Command failed.
Exit code: 1
Command: /usr/local/bin/create-strapi-app
Arguments: api-lp
Directory: /Users/user/Sites/react-avancado/react-avancado-api
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### Expected behavior
Success when creating a new strapi app.

### System

- Node.js version: v12.16.2 or v14
- NPM version: 6.14.8
- Yarn version: 1.22.4
- Strapi version: 3.3.2
- Database: any
- Operating system: macOS Mojave and macOS Catalina

**Comment by derrickmehaffy** [comment]
Double check your npm or yarn registry as you may have the enterprise fontawesome one set.

**Comment by hugofabricio** [comment]
@derrickmehaffy  thanks, that right, a found a fontawesome key on my computer, I didn't understand because on the other computer I tested I didn't have and the error was the same. Thank you!
