### ISSUE TITLE
strapi error Error: maxFileSize exceeded, received 209779528 bytes

### ISSUE THREAD

**Issue by AmelieNapoli** [strapi/strapi#8648]
## Bug report
[2020-11-13T15:56:51.369Z] error Error: maxFileSize exceeded, received 209779580 bytes of file data
    at Stream.<anonymous> (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:222:19)
    at Stream.emit (events.js:321:20)
    at MultipartParser.parser.onPartData (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:387:14)
    at callback (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/multipart_parser.js:102:31)
    at dataCallback (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/multipart_parser.js:112:11)
    at MultipartParser.write (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/multipart_parser.js:305:3)
    at IncomingForm.write (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:159:34)
    at IncomingMessage.<anonymous> (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:125:12)
    at IncomingMessage.emit (events.js:321:20)
    at IncomingMessage.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:979:34)
    at resume_ (_stream_readable.js:960:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-11-13T15:56:51.372Z] debug POST /upload?id=5faa9d4b96efda5b4c6cb513 (7425 ms) 50

### Steps to reproduce the behavior

1. I have a collection with a field type MEDIA
2. If i try to upload in the STRAPI collections a file .mp4 greather then 209779528 bytes I have this error “strapi error Error: maxFileSize exceeded, received 209779528 bytes”.
I modified /…/strapi/config/middleware.js file in this way and after run “npm run build”, but it dosen’ work.
Could you help me?

### Expected behavior
I want to upload file, mp3 or mp4 greather then 209779528 bytes

### Screenshots
[2020-11-13T15:56:51.369Z] error Error: maxFileSize exceeded, received 209779580 bytes of file data
    at Stream.<anonymous> (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:222:19)
    at Stream.emit (events.js:321:20)
    at MultipartParser.parser.onPartData (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:387:14)
    at callback (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/multipart_parser.js:102:31)
    at dataCallback (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/multipart_parser.js:112:11)
    at MultipartParser.write (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/multipart_parser.js:305:3)
    at IncomingForm.write (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:159:34)
    at IncomingMessage.<anonymous> (/home/marco/prg/Ideha/strapi/node_modules/formidable/lib/incoming_form.js:125:12)
    at IncomingMessage.emit (events.js:321:20)
    at IncomingMessage.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:979:34)
    at resume_ (_stream_readable.js:960:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-11-13T15:56:51.372Z] debug POST /upload?id=5faa9d4b96efda5b4c6cb513 (7425 ms) 50

### Code snippets  config/middleware.js

module.exports = {
  settings: {
      parser: {
        enabled: true,
        multipart: true,
        formidable: {
          maxFileSize: 545259520,
        },
      },
    },
  load: {
      before: ['timer', 'responseTime', 'logger', 'cors', 'responses', 'gzip'],
      order: [],
      after: ['parser', 'router'],
    },
  };

### System
    Strapi Version: 3.0.4
    Operating System: Ubuntu 20.10
    Database: MongoDB
    Node Version: v13.7.0
    NPM Version: 6.13.6

![Screenshot_2020-11-13 Strapi - Content Manager](https://user-images.githubusercontent.com/18345572/99093474-ceee0f80-25d2-11eb-816a-7898c9386e47.png)

**Comment by derrickmehaffy** [comment]
Can you please try testing with the current latest version? v3.3.3 (you specified `Strapi Version: 3.0.4` as your version)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/strapi-error-maxfilesize-exceeded-received-209779528-bytes/1119/2

**Comment by derrickmehaffy** [comment]
Closing as related forum thread instead
