### ISSUE TITLE
[GraphQL] oneMorphToMany relation emits error on create

### ISSUE THREAD

**Issue by darron1217** [strapi/strapi#8651]
### Describe the bug
I made `oneMorphToMany` polymorphic relation like below.

message.settings.json
```
    "sender": {
      "model": "*",
      "filter": "field"
    }
```
User.settings.json (from `users-permissions` plugin)
```
    "messages": {
      "collection": "message",
      "via": "sender"
    }
```

It does not work when I insert `Message` model with `sender` field.

On graphQL mutation
```
        variables: {
          data: {
            sender: currentUser.id,
          },
        },
```

Stack Trace
```
0: "TypeError: Cannot read property 'uid' of undefined"
1: "    at resolver.<computed> (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/strapi-plugin-graphql/services/type-definitions.js:208:34)"
2: "    at field.resolve (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql-extensions/dist/index.js:134:26)"
3: "    at field.resolve (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)"
4: "    at resolveFieldValueOrError (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:502:18)"
5: "    at resolveField (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:460:16)"
6: "    at executeFields (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:297:18)"
7: "    at collectAndExecuteSubfields (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:748:10)"
8: "    at completeObjectValue (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:738:10)"
9: "    at completeValue (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:626:12)"
10: "    at completeValueCatchingError (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:530:19)"
11: "    at resolveField (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:461:10)"
12: "    at executeFields (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:297:18)"
13: "    at collectAndExecuteSubfields (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:748:10)"
14: "    at completeObjectValue (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:738:10)"
15: "    at completeValue (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:626:12)"
16: "    at /Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:527:16"
```

I've also tried changing my `message.settings.json` like below.
```
    "sender": {
      "model": "*",
      "filter": "field",
      "plugin": "users-permissions"
    }
```
But it's doesn't work either.

### Steps to reproduce the behavior

Follow above example

### Expected behavior

Data inserted without error.

### Code snippets

The line which emits error
https://github.com/strapi/strapi/blob/d3c249c876c1f7918db5bf047abea6d80f09309b/packages/strapi-plugin-graphql/services/type-definitions.js#L208

(Maybe) The real cause of error
https://github.com/strapi/strapi/blob/d3c249c876c1f7918db5bf047abea6d80f09309b/packages/strapi-plugin-graphql/services/type-definitions.js#L180

### System

- Node.js version: 12.18.3
- NPM version: 6.14.8
- Strapi version: 3.3.2
- Database: mongoDB latest
- Operating system: Mac OS Catalina

**Comment by darron1217** [comment]
I found that my case is `oneMorphToMany` relation. (the value of `association.nature`)
I guess it's missing case on switch. Like below.

https://github.com/strapi/strapi/blob/d3c249c876c1f7918db5bf047abea6d80f09309b/packages/strapi-plugin-graphql/services/type-definitions.js#L182-L187

I've added `oneMorphToMany` on the case and got the error below.
```
0: "GraphQLError: Abstract type "Morph" must resolve to an Object type at runtime for field "InquiryMessage.sender" with value {}, received "null". Either the "Morph" type should provide a "resolveType" function or each possible type should provide an "isTypeOf" function."
1: "    at ensureValidRuntimeType (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:702:11)"
2: "    at completeAbstractValue (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:695:42)"
3: "    at completeValue (/Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:620:12)"
4: "    at /Users/darron/Documents/stormWorkspace/enre-web/backend/node_modules/graphql/execution/execute.js:527:16"
5: "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
6: "    at async Promise.all (index 4)"
7: "    at async Promise.all (index 0)"
```

**Comment by derrickmehaffy** [comment]
Confirmed on v3.3.3, although I'm not sure if we support it yet, so leaving the attached feature request.

**Comment by darron1217** [comment]
I think this issue is related to https://github.com/strapi/strapi/issues/4145

**Comment by derrickmehaffy** [comment]
Should be fixed in v4, if not please open a new issue
