### ISSUE TITLE
Error on upload to media lib (500 Internal Server Error) in production env

### ISSUE THREAD

**Issue by git-antonyuk** [strapi/strapi#8653]
## Bug report
Error on upload to media lib media lib (500 Internal Server Error) in production env

### Describe the bug
When trying to upload anything to the media library in production I'm getting a 500 Internal Server Error. On localhost development and production builds work's perfectly and media uploaded with out bugs.

### Steps to reproduce the behavior

1. Deploy strapi application to VPS server
2. Go to 'Media Library'
3. Try to upload any file
4. Get 500 Internal Server Error

### Expected behavior

Upload file on production env without errors

### Screenshots

<img width="1678" alt="Снимок экрана 2020-11-14 в 18 56 20" src="https://user-images.githubusercontent.com/17859567/99152619-89e9dc00-26ab-11eb-8a7a-214c29a89e89.png">
<img width="1261" alt="Снимок экрана 2020-11-14 в 18 56 41" src="https://user-images.githubusercontent.com/17859567/99152627-92421700-26ab-11eb-8d99-5565e8cc1416.png">

### Code snippets

```
backend      | [2020-11-14T15:47:19.208Z] error Error: ENOENT: no such file or directory, open '/backend/public/uploads/error_page_bg_dt_4c40fb8868.jpg'
backend      | [2020-11-14T15:47:19.209Z] error Error: Internal Server Error
backend      |     at convertToStrapiError (/backend/node_modules/strapi-plugin-upload/errors.js:36:26)
backend      |     at Object.upload (/backend/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
backend      | [2020-11-14T15:47:19.211Z] debug POST /upload (307 ms) 500
```

### System

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.3.2
- Database: Mango
- Operating system: Ubuntu

### Additional context

Try to install local provider and so on, nothing helps. On local machine all works great, on production is error. 
Folder uploads exist  and writable... 
<img width="1261" alt="Снимок экрана 2020-11-14 в 19 04 21" src="https://user-images.githubusercontent.com/17859567/99152738-4479de80-26ac-11eb-8155-1fdb62ae9291.png">

**Comment by derrickmehaffy** [comment]
I am unable to reproduce this on DigitalOcean (Droplets), AWS EC2, Vultr, or locally.

Can you please give me some more information as to where you are trying this? Also you should not generate a Strapi project as a root user (nor should you run a node.js application as a root user)

**Comment by git-antonyuk** [comment]
I created a 
new user for generation Stapi App. I used Ubuntu 20 on the server, docker-compose, Nginx. Locally uploader of files works perfectly, but after deploying smth goes wrong. 

<img width="1680" alt="Снимок экрана 2020-11-19 в 01 54 55" src="https://user-images.githubusercontent.com/17859567/99602953-0e6d8f00-2a0b-11eb-86a9-ea0ec071b09a.png">

Docker composer config:
```
version: "3"

services:
  backend:
    build: ./backend/
    container_name: backend
    restart: always
    ports:
      - "3333:3333"
    command:
      "npm run start"

  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
    depends_on:
      - backend
```

Frontend Docker file 
```
FROM node:12.16.1

# Create app directory
WORKDIR /frontend
ADD . /frontend/

# global install & update
RUN rm -rf .nuxt
RUN rm -rf dist
RUN rm -rf node_modules

RUN npm i

RUN npm run build

ENV HOST 0.0.0.0
EXPOSE 3000

# start command
CMD [ "npm", "run", "start" ]
```

Backend Docker file 
```
FROM node:12.16.1

# Create app directory
WORKDIR /backend
ADD . /backend/

ENV NODE_ENV production
ENV HOST 0.0.0.0

# global install & update
RUN rm -rf .cache
RUN rm -rf build
RUN rm -rf node_modules
RUN npm i 
RUN npm run build

EXPOSE 3333

# start command
CMD [ "npm", "run", "start" ]
```

Nginx default config
```
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Server configuration for NUXT.js 
map $sent_http_content_type $expires {
    "text/html"                 epoch;
    "text/html; charset=utf-8"  epoch;
    default                     off;
}

server {
	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/--HOST--/frontend;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name --HOST-- www.--HOST--;
    
    # Backend API 
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://strapi;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }

    # Backend admin panel
    location /dashboard {
        proxy_pass http://strapi/dashboard;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }

    location / {
        expires $expires;

        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_read_timeout          1m;
        proxy_connect_timeout       1m;
        proxy_pass                          http://127.0.0.1:3000; # set the address of the Node.js instance here
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/--HOST--fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/--HOST--privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.--HOST--) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = --HOST--) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80 default_server;
	listen [::]:80 default_server;

	server_name --HOST-- www.--HOST--;
    return 404; # managed by Certbot
}
```

**Comment by derrickmehaffy** [comment]
Uhhhh that looks like the file isn't being written to the file system, either due to permissions or something.

**Comment by git-antonyuk** [comment]
@derrickmehaffy Thank you for your help and advice. Yep, it's true. Permission stuff. https://www.internalpointers.com/post/right-folder-permission-website

Not a Strapi bug! Uploads work as expected.

**Comment by danielehrhardt** [comment]
> @derrickmehaffy Thank you for your help and advice. Yep, it's true. Permission stuff. https://www.internalpointers.com/post/right-folder-permission-website
> 
> Not a Strapi bug! Uploads work as expected.

I have the same Problem, but my Public Folder does have the correct Permission. What exactly have you changed?

**Comment by chloesun** [comment]
I also experienced the same issue. Do I need to use a provider?

**Comment by chloesun** [comment]
Follow up: I made it work by making myself the owner of the directory:
example : `chown -R chloe /var/www/my-website.com/`

**Comment by Ladvace** [comment]
I hosted mine on railway: https://railway.app/template/strapi and I'm getting the same error
