### ISSUE TITLE
Initial Build fails with npx create-strapi-app

### ISSUE THREAD

**Issue by gaurangrshah** [strapi/strapi#8725]
### Describe the bug

While installing a brand new instance of strapi locally i encounter the following error: 'Can't resolve 'es-abstract/2020/ArraySpeciesCreate''

### Steps to reproduce the behavior

1. simply run 
```
npx create-strapi-app app-name --quickstart
```

### Expected behavior

Should install strapi and build with default --quickstart settings

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.14.0
- NPM version:  6.14.4
- Strapi version: 
- Database: sqlite3
- Operating system: Osx High Sierra

here's a copy of the error:
```bash
Building your admin UI with development configuration ...
● Webpack █████████████████████████ building (69%) 2901/2939 modules 38
 active
 node_modules/core-js/modules/_string-context.js
Error: Module not found: Error: Can't resolve 'es-abstract/2020/ArraySpec
iesCreate' in '/Users/bunty/gsdev/proto/server/node_modules/array.prototy
pe.flat'
    at /Users/bunty/gsdev/proto/server/node_modules/strapi-admin/index.js
:70:23
    at finalCallback (/Users/bunty/gsdev/proto/server/node_modules/webpac
k/lib/Compiler.js:257:39)
    at onCompiled (/Users/bunty/gsdev/proto/server/node_modules/webpack/l
ib/Compiler.js:265:20)
    at /Users/bunty/gsdev/proto/server/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/Users/bunty/gsdev/proto/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/bunty/gsdev/proto/server/node_modules/webpack/lib/Compilation.js:1173:13
    at /Users/bunty/gsdev/proto/server/node_modules/webpack/lib/Compilation.js:1096:25
    at /Users/bunty/gsdev/proto/server/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/bunty/gsdev/proto/server/node_modules/neo-async/async.js:2830:7
    at /Users/bunty/gsdev/proto/server/node_modules/neo-async/async.js:2830:7
    at done (/Users/bunty/gsdev/proto/server/node_modules/neo-async/async.js:2863:11)
    at /Users/bunty/gsdev/proto/server/node_modules/neo-async/async.js:2818:7
    at /Users/bunty/gsdev/proto/server/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/bunty/gsdev/proto/server/node_modules/neo-async/async.js:2830:7
    at /Users/bunty/gsdev/proto/server/node_modules/neo-async/async.js:2830:7
    at done (/Users/bunty/gsdev/proto/server/node_modules/neo-async/async.js:2863:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.1.0 build: `strapi build "--no-optimization"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bunty/.npm/_logs/2020-11-23T18_10_59_964Z-debug.log
```

**Comment by derrickmehaffy** [comment]
This isn't an issue with Strapi and is most likely an outdated cache (either upstream from you or locally)

See for example: https://stackoverflow.com/questions/59325626/webpack-suddenly-fails-to-compile-due-to-module-not-found-error-cant-resolve

You can try to apply some of the feedback there, but the easiest way is probably to clear your npm or yarn cache.

Marking as closed as not a Strapi bug but a user environment issue.
