### ISSUE TITLE
graphql count with nested object filtering

### ISSUE THREAD

**Issue by blukasho** [strapi/strapi#8880]
### Describe the bug

Hello!
Bug with restaurantCount according to this guide with the use of nested object filter.

### POST request to /graphql

```graphql
query {
    restaurantsCount ( 
        where : { 
            administrator : {
                id : 1
            }
        } 
    ) 
}
```
### response: 
```json
{
    "errors": [
        {
            "message": "select distinct count(*) as \"count\" from \"restaurants\" left join \"strapi\".\"public\".\"administrators\" as \"administrators_1\" on \"administrators_1\".\"id\" = \"restaurants\".\"administrator\" where \"administrators_1\".\"id\" = $1 - invalid input syntax for integer: \"{\"id\":1}\"",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "restaurantsCount"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "length": 90,
                    "name": "error",
                    "severity": "ERROR",
                    "code": "22P02",
                    "file": "numutils.c",
                    "line": "62",
                    "routine": "pg_atoi",
                    "stacktrace": [
                        "error: invalid input syntax for integer: \"{\"id\":1}\"",
                        "    at Parser.parseErrorMessage (/root/projects/agra/strapi/node_modules/pg-protocol/dist/parser.js:278:15)",
                        "    at Parser.handlePacket (/root/projects/agra/strapi/node_modules/pg-protocol/dist/parser.js:126:29)",
                        "    at Parser.parse (/root/projects/agra/strapi/node_modules/pg-protocol/dist/parser.js:39:38)",
                        "    at Socket.stream.on (/root/projects/agra/strapi/node_modules/pg-protocol/dist/index.js:10:42)",
                        "    at Socket.emit (events.js:198:13)",
                        "    at addChunk (_stream_readable.js:288:12)",
                        "    at readableAddChunk (_stream_readable.js:269:11)",
                        "    at Socket.Readable.push (_stream_readable.js:224:10)",
                        "    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
                        "From previous event:",
                        "    at Client_PG._query (/root/projects/agra/strapi/node_modules/knex/lib/dialects/postgres/index.js:234:12)",
                        "    at Client_PG.query (/root/projects/agra/strapi/node_modules/knex/lib/client.js:158:17)",
                        "    at Runner.query (/root/projects/agra/strapi/node_modules/knex/lib/runner.js:135:36)",
                        "    at /root/projects/agra/strapi/node_modules/knex/lib/runner.js:39:23",
                        "From previous event:",
                        "    at Runner.run (/root/projects/agra/strapi/node_modules/knex/lib/runner.js:25:16)",
                        "    at Builder.Target.then (/root/projects/agra/strapi/node_modules/knex/lib/interface.js:14:43)",
                        "    at runCallback (timers.js:705:18)",
                        "    at tryOnImmediate (timers.js:676:5)",
                        "    at processImmediate (timers.js:658:5)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```
### POST request to /graphql

```qraphql
query {
    restaurantsCount ( 
        where : { 
            id : 1
        }
    ) 
}
```

### response:

```json
{
    "data": {
        "restaurantsCount": 1
    }
}
```

### response:

```json
[
    {
        "id": 1,
        "title": "Steak House ",
        "created_by": {
            "id": 1,
            "firstname": "Bogdan",
            "lastname": "Lukashov",
            "username": "blukasho"
        },
        "updated_by": {
            "id": 1,
            "firstname": "Bogdan",
            "lastname": "Lukashov",
            "username": "blukasho"
        },
        "created_at": "2020-12-12T14:42:14.961Z",
        "updated_at": "2020-12-12T14:42:14.968Z",
        "administrator": {
            "id": 1,
            "name": "Felix",
            "created_by": 1,
            "updated_by": 1,
            "created_at": "2020-12-12T14:41:13.284Z",
            "updated_at": "2020-12-12T14:41:13.293Z"
        }
    },
    {
        "id": 2,
        "title": "Doner Market",
        "created_by": {
            "id": 1,
            "firstname": "Bogdan",
            "lastname": "Lukashov",
            "username": "blukasho"
        },
        "updated_by": {
            "id": 1,
            "firstname": "Bogdan",
            "lastname": "Lukashov",
            "username": "blukasho"
        },
        "created_at": "2020-12-12T14:42:48.873Z",
        "updated_at": "2020-12-12T14:42:48.881Z",
        "administrator": {
            "id": 2,
            "name": "Hloe",
            "created_by": 1,
            "updated_by": 1,
            "created_at": "2020-12-12T14:41:21.253Z",
            "updated_at": "2020-12-12T14:41:21.259Z"
        }
    },
    {
        "id": 3,
        "title": "Biscotti",
        "created_by": {
            "id": 1,
            "firstname": "Bogdan",
            "lastname": "Lukashov",
            "username": "blukasho"
        },
        "updated_by": {
            "id": 1,
            "firstname": "Bogdan",
            "lastname": "Lukashov",
            "username": "blukasho"
        },
        "created_at": "2020-12-12T14:43:11.301Z",
        "updated_at": "2020-12-12T14:43:11.310Z",
        "administrator": {
            "id": 1,
            "name": "Felix",
            "created_by": 1,
            "updated_by": 1,
            "created_at": "2020-12-12T14:41:13.284Z",
            "updated_at": "2020-12-12T14:41:13.293Z"
        }
    }
]
```

### api/restaurant/models/restaurant.settings.json

```json
{
  "kind": "collectionType",
  "collectionName": "restaurants",
  "info": {
    "name": "restaurant"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "administrator": {
      "model": "administrator"
    }
  }
}
```

### api/restaurant/config/schema.graphql.js

```javascript
module.exports = {
	query: `restaurantsCount(where: JSON): Int!`,
	resolver: {
		Query: {
			restaurantsCount: {
				description: 'Return the count of restaurants',
				resolverOf: 'application::restaurant.restaurant.count',
				resolver: async (obj, options, ctx) => {
					return await strapi.api.restaurant.services.restaurant.count(options.where || {});
				},
			},
		},
	},
};

```

- Node.js version:  v12.19.1
- NPM version: 6.14.8
- Strapi version: v3.3.2 
- Database: PostgreSQL 13.1
- Operating system: Ubuntu 16.04.5 LTS

**Comment by ashmore11** [comment]
Running into this issue myself. Did you find a solution @blukasho ?

**Comment by blukasho** [comment]
@ashmore11 

No, the problem is a little deeper, in the same way I get an error with REST API.

**Comment by p-gw** [comment]
I've ran into the same or similar issue. In my case the count query did not throw an error, but always returned 0 when using nested filters. 

It turns out that the `options.where` object is not correctly flattened for nested queries, so instead of `{administrator.id: 1}` the object looks like this: `{ administrator: { id: 1 }`.

Flattening `objects.where` fixed the issue for me. For this I used the following function:

```javascript
var flattenObject = function (ob) {
  return Object.keys(ob).reduce(function (toReturn, k) {
    if (Object.prototype.toString.call(ob[k]) === "[object Date]") {
      toReturn[k] = ob[k].toString();
    } else if (typeof ob[k] === "object" && !Array.isArray(ob[k]) && ob[k]) {
      console.log(typeof ob[k]);
      var flatObject = flattenObject(ob[k]);
      Object.keys(flatObject).forEach(function (k2) {
        toReturn[k + "." + k2] = flatObject[k2];
      });
    } else {
      toReturn[k] = ob[k];
    }

    return toReturn;
  }, {});
};
```

You then just have to modify `options.where` before passing it to `count`.

```javascript
resolver: async (obj, options, ctx) => {
  if (options.where === undefined) {
    options.where = {};
  }
   options.where = flattenObject(options.where);
   return await strapi.api.restaurant.services.restaurant.count(options.where);
},
```

I hope this helps. I am running the latest version of strapi, 3.5.4.

**Comment by derrickmehaffy** [comment]
count routes were removed in v4 as all requests have a meta count now
