### ISSUE TITLE
error where running migrate-3.4.0.js

### ISSUE THREAD

**Issue by violabg** [strapi/strapi#8971]
I'm running the command
` node migrate-3.4.0.js mc-intra-api/`
as mention on the documentation page, but I'm getting this error:

` debug ⛔️ Server wasn't able to start properly.
[2020-12-22T08:24:37.058Z] error error: password authentication failed for user "root"
    at Parser.parseErrorMessage (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/var/www/mc-intra-api/node_modules/pg-protocol/dist/index.js:10:42)`

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
