### ISSUE TITLE
Serious Fatal Error: rename the field from small letter to capital letter

### ISSUE THREAD

**Issue by codyng** [strapi/strapi#9000]
## Bug report
Just rename the field from "name" to "Name" and it causes the fatal error:

error Error: SQLITE_ERRORf: duplicate column name: name

    at Client_SQLite3._query (/somepath/node_modules/knex/lib/dialects/sqlite3/index.js:99:12)
    at Client_SQLite3.query (/somepath/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/somepath/node_modules/knex/lib/runner.js:135:36)
    at Runner.queryArray (/somepath/node_modules/knex/lib/runner.js:224:14)
    at /somepath/node_modules/knex/lib/runner.js:37:25

And then the server can't be restarted anymore...

**Comment by codyng** [comment]
What I need to do is to fix it by modifying it's appropriated model JSON.

Is it It's perfect if it can handle this in DB layer.

**Comment by derrickmehaffy** [comment]
Duplicate #1114
