### ISSUE TITLE
500 Internal Server Error by post request to `/auth/local`

### ISSUE THREAD

**Issue by kwiat1990** [strapi/strapi#9058]
Hi, 

I have managed to set a server cookie in order to authenticate a user. It all works just fine on dev server: I can log in and access secured endpoints. In order to do that I followed this article: [https://talke.dev/strapi-user-permissions-jwt-cookies](https://talke.dev/strapi-user-permissions-jwt-cookies).

After I deployed Strapi onto server in production mode and with SSL it doesn't work anymore. Database connection seems to work correctly - I can retrieve all the data and access the public endpoints. But somehow as soon as I try to log in (from my client app or from Postman) I get 500 error in return. I have created 2 users, direct in Strapi and I can see them in my database.

I just don't get why the code breaks in production. Can it be related entirely to HTTPS?  

Server log:
```
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
App 420095 output:     at async /home/p563709/nodevenv/project/12/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
App 420095 output:     at Object.callback (/home/p563709/project/extensions/users-permissions/controllers/Auth.js:137:21)
App 420095 output:     at Cookies.set (/home/p563709/nodevenv/project/12/lib/node_modules/koa/node_modules/cookies/index.js:94:11)
```

### System:
- Node.js version: v12.9.0
- NPM version: 6.10.2
- Strapi version: 3.4.1
- Database: MySQL

**Comment by derrickmehaffy** [comment]
Bug reports are only for Strapi Native code and not extensions, for extending Strapi with custom logic please open a thread on our forum: https://forum.strapi.io
