### ISSUE TITLE
strapi start in heroku TypeError: ext[key].bind is not a function

### ISSUE THREAD

**Issue by milindsingh** [strapi/strapi#9075]
## Bug report
TypeError: ext[key].bind is not a function

### Describe the bug
I am facing this error in Heroku on `strapi start`. Can anyone direct me in the right direction?

```
[2021-01-09T09:47:25.184Z] error TypeError: ext[key].bind is not a function
api-cms-adapttive-com | 15:17:25     at /workspace/node_modules/css-select/node_modules/domutils/index.js:12:28
api-cms-adapttive-com | 15:17:25     at Array.forEach (<anonymous>)
api-cms-adapttive-com | 15:17:25     at /workspace/node_modules/css-select/node_modules/domutils/index.js:11:19
api-cms-adapttive-com | 15:17:25     at Array.forEach (<anonymous>)
api-cms-adapttive-com | 15:17:25     at Object.<anonymous> (/workspace/node_modules/css-select/node_modules/domutils/index.js:10:3)
api-cms-adapttive-com | 15:17:25     at Module._compile (internal/modules/cjs/loader.js:1063:30)
api-cms-adapttive-com | 15:17:25     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
api-cms-adapttive-com | 15:17:25     at Module.load (internal/modules/cjs/loader.js:928:32)
api-cms-adapttive-com | 15:17:25     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
api-cms-adapttive-com | 15:17:25     at Module.require (internal/modules/cjs/loader.js:952:19)
api-cms-adapttive-com | 15:17:25 error Command failed with exit code 1.
```

### Steps to reproduce the behavior

1. Go to Digital Ocean App Platform
2. Deploy Strapi

### Expected behavior

As strapi build is working. strapi start should work.

### System

- Node.js version: v14.15.4
- Yarn version: 1.22.10
- Strapi version: 3.4.1
- Database: Mongo Cloud
- Operating system: Heroku Digital Ocean App

### Additional context

**Related to 3.4 upgrades**

**Comment by milindsingh** [comment]
This was fixed by upgrading strapi documentation plugin to 3.5 next branch.

**Comment by derrickmehaffy** [comment]
Can you clarify which branch you are referring to?

**Comment by derrickmehaffy** [comment]
Marking as closed as the user stated it was fix (though not sure how)
