### ISSUE TITLE
Error: Invalid format, expected a timestamp or an ISO date

### ISSUE THREAD

**Issue by IlchukPasha** [strapi/strapi#9093]
### Describe the bug

When trying to query data from a database, the error "Error: Invalid format, expected a timestamp or an ISO date".

### Steps to reproduce the behavior

1. Create a Strapi project using mongoose
2. Create a content type with a date field (datetime type)
3. Attempt to query data from a database for that type

### Expected behavior

The query should work without errors

### Code snippets

```
{
  "kind": "collectionType",
  "collectionName": "schedulings",
  "info": {
    "name": "scheduling"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "startTime": {
      "required": true,
      "type": "datetime"
    },
    "endTime": {
      "type": "datetime",
      "required": true
    },
    "therapists": {
      "collection": "therapists",
      "via": "scheduling",
      "plugin": ""
    }
  }
}
```

```
const searchResults = await strapi.query('scheduling').find(
        { startTime: { $lte: new Date() } }
);
```

```
Error: Invalid format, expected a timestamp or an ISO date
    at parseDateTimeOrTimestamp (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-utils/lib/parse-type.js:52:11)
    at parseType (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-utils/lib/parse-type.js:93:14)
    at castValue (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-utils/lib/build-query.js:75:10)
    at castInput (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-utils/lib/build-query.js:63:7)
    at /Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-utils/lib/build-query.js:132:27
    at Array.map (<anonymous>)
    at normalizeWhereClauses (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-utils/lib/build-query.js:115:6)
    at buildQuery (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-utils/lib/build-query.js:182:23)
    at Object.find (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-connector-mongoose/lib/queries.js:407:12)
    at fn (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.find (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-database/lib/queries/helpers.js:15:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.beforeCreate (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/api/scheduling/models/scheduling.js:38:29)
    at async executeLifecycle (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-database/lib/utils/lifecycles.js:7:5)
    at async Object.create (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/node_modules/strapi-database/lib/queries/helpers.js:12:3)
    at async Object.login (/Users/pasha/projects/choosing-therapy/choosing-therapy-admin/api/test/controllers/test.js:8:21)

```

### System

- Node.js version: v12.16.3
- NPM version: v6.14.4
- Strapi version: v3.4.1
- Database: MongoDB v4.2.11
- Operating system: macOS Catalina Version 10.15.5

**Comment by alexandrebodin** [comment]
Hi the field expects an iso date so a string :) you can do new Date().toISOString() ;)

**Comment by IlchukPasha** [comment]
@alexandrebodin  i have tried it but unfortunetly it doesn`t works

**Comment by alexandrebodin** [comment]
hum I don't see the issue then. the function is pretty straight forward it should even allowed the date objecta ctually. can you check the version of the package strapi-utils that you have in your project ?

**Comment by IlchukPasha** [comment]
this is my package.json

"dependencies": {
    "strapi-plugin-content-manager": "3.4.1",
    "strapi-plugin-content-type-builder": "3.4.1",
    "strapi-plugin-email": "3.4.1",
    "strapi-plugin-upload": "3.4.1",
    "strapi-plugin-users-permissions": "3.4.1",
    "strapi-utils": "3.4.1"
  },

**Comment by derrickmehaffy** [comment]
```
{ startTime: { $lte: new Date() } }
```

This is the wrong format, try with:

```
{ startTime_lte: new Date() }
```

As you are using a Strapi native filter, not a mongoose one. If you want to use mongoose based filters you need to use the custom query: https://strapi.io/documentation/developer-docs/latest/concepts/queries.html#mongoose

Marking as closed, let me know if this solution doesn't work.

**Comment by alexandrebodin** [comment]
Nice catch @derrickmehaffy  👍

**Comment by IlchukPasha** [comment]
@derrickmehaffy thanks, it works

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy thanks, it works

If you want to see our filter parameters @IlchukPasha : https://strapi.io/documentation/developer-docs/latest/content-api/parameters.html

**Comment by MuizU** [comment]
Still having this issue in v4 for postgres

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
