### ISSUE TITLE
Syntax Error in @purest library

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#9113]
### Describe the bug

Error message on all new fresh projects due to external library

```
[2021-01-13T09:52:18.107Z] error SyntaxError: /home/dmehaffy/Development/testPurest/node_modules/@purest/providers/config/providers.json: Unexpected token } in JSON at position 27052
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1049:22)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dmehaffy/Development/testPurest/node_modules/@purest/providers/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce the behavior

N/A affects all projects

### Expected behavior

Should not error out :) 

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/104436378-c40c1880-554a-11eb-9e89-57c23123e3ae.png)

### Code snippets

N/A

### System

- Node.js version: v12.19.0
- NPM version: 6.14.8
- Strapi version: v3.4.1
- Database: SQLite
- Operating system: Linux Mint 20.1 (Ubuntu 20.04.1)

### Additional context

External Library issue: https://github.com/simov/purest-providers/pull/4

**Comment by derrickmehaffy** [comment]
Related fix: https://github.com/simov/purest-providers/pull/7

**Comment by derrickmehaffy** [comment]
Issue has been fixed upstream, solution if you hit this error:

- delete your node_modules, yarn.lock, and package-lock.json
- wipe any local system cache of packages (yarn/npm)
- reinstall node_modules

**Comment by derrickmehaffy** [comment]
Marking as closed
