### ISSUE TITLE
Strapi is not starting properly

### ISSUE THREAD

**Issue by cayirtepeomer** [strapi/strapi#9153]
**Describe the bug**

I'm not able to start strapi properly. It's giving below error. I couldn't find the same error anywhere. I've been trying to fix this for 3 days. It was working before and I didn't change anything. I just deleted node_modules and ran `npm install`

> debug ⛔️ Server wasn't able to start properly.
> [2021-01-17T16:31:46.052Z] error Error: Cannot find module '../../../test/helpers/strapi'
> Require stack:
> - /Users/omer/workspace/guideapp/node_modules/strapi-plugin-upload/tests/graphqlUpload.test.e2e.js
> - /Users/omer/workspace/guideapp/node_modules/strapi/lib/load/load-files.js
> - /Users/omer/workspace/guideapp/node_modules/strapi/lib/core/load-apis.js
> - /Users/omer/workspace/guideapp/node_modules/strapi/lib/core/load-modules.js
> - /Users/omer/workspace/guideapp/node_modules/strapi/lib/Strapi.js
> - /Users/omer/workspace/guideapp/node_modules/strapi/lib/index.js
> - /Users/omer/workspace/guideapp/node_modules/strapi/lib/commands/develop.js
> - /usr/local/lib/node_modules/strapi/bin/strapi.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/Users/omer/workspace/guideapp/node_modules/strapi-plugin-upload/tests/graphqlUpload.test.e2e.js:6:34)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)

**Package.json**

> {
  "name": "guideapp",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "graphql": "^15.4.0",
    "knex": "<0.20.0",
    "pg": "^8.5.1",
    "pg-connection-string": "^2.4.0",
    "sqlite3": "latest",
    "strapi": "3.4.1",
    "strapi-admin": "3.4.1",
    "strapi-connector-bookshelf": "3.4.1",
    "strapi-connector-mongoose": "^3.4.1",
    "strapi-plugin-content-manager": "3.4.1",
    "strapi-plugin-content-type-builder": "3.4.1",
    "strapi-plugin-email": "3.4.1",
    "strapi-plugin-upload": "^3.4.1",
    "strapi-plugin-users-permissions": "3.4.1",
    "strapi-provider-email-sendgrid": "^3.4.1",
    "strapi-provider-upload-cloudinary": "^3.4.1",
    "strapi-utils": "3.4.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "***"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

**System**

    Strapi Version: 3.4.1
    Operating System: Debian
    Database: Postgres
    Node Version: 12.18.4
    NPM Version: 6.14.6

**Comment by cayirtepeomer** [comment]
Updated strapi version to 3.4.3 and then it started working properly.
