### ISSUE TITLE
Strapi image upload to cloudinary not working on production mode

### ISSUE THREAD

**Issue by bahadryalcn** [strapi/strapi#9157]
Hello to everyone. I was using "strapi-provider-upload-cloudinary" to upload images to cloudinary. Everything was fine until 2 days ago. But now I am facing a strange error. I did a test by opening a new cloudinary account. The same error occurred. I realized in the past that I could change the cloudinary account name but now I can't. At first I thought there was a problem with cloudinary, but my account is active and I have enough credits. Also, while the image upload process is running in development mode, it doesn't work in production mode. I have no idea about the solution to the problem either. I would be very happy if you could help.

Strapi Version: 3.4.3
Node Version: v14.15.1
npm Version: 6.14.8

`error Error: Error uploading to cloudinary: cloud_name is disabled
    at Object.unknownError (D:\Projects\Excellence Yeni\backend\node_modules\strapi-plugin-upload\errors.js:16:17)
    at D:\Projects\Excellence Yeni\backend\node_modules\strapi-provider-upload-cloudinary\lib\index.js:26:38  
    at D:\Projects\Excellence Yeni\backend\node_modules\cloudinary\lib\utils\index.js:1152:14
    at IncomingMessage.<anonymous> (D:\Projects\Excellence Yeni\backend\node_modules\cloudinary\lib\uploader.js:402:9)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2021-01-18T15:50:45.526Z] error Error: Internal Server Error
    at convertToStrapiError (D:\Projects\Excellence Yeni\backend\node_modules\strapi-plugin-upload\errors.js:38:26)
    at Object.upload (D:\Projects\Excellence Yeni\backend\node_modules\strapi-plugin-upload\config\functions\bootstrap.js:35:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.uploadFileAndPersist (D:\Projects\Excellence Yeni\backend\node_modules\strapi-plugin-upload\services\Upload.js:154:5)
    at async Promise.all (index 0)
    at async Object.upload (D:\Projects\Excellence Yeni\backend\node_modules\strapi-plugin-upload\services\Upload.js:140:12)
    at async uploadFiles (D:\Projects\Excellence Yeni\backend\node_modules\strapi-plugin-upload\controllers\upload\admin.js:187:27)
    at async Object.upload (D:\Projects\Excellence Yeni\backend\node_modules\strapi-plugin-upload\controllers\Upload.js:65:5)
    at async D:\Projects\Excellence Yeni\backend\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:79:22
    at async D:\Projects\Excellence Yeni\backend\node_modules\strapi\node_modules\strapi-utils\lib\policy.js:68:5
    at async D:\Projects\Excellence Yeni\backend\node_modules\strapi\lib\middlewares\parser\index.js:48:23
    at async D:\Projects\Excellence Yeni\backend\node_modules\strapi\lib\middlewares\xss\index.js:26:9
[2021-01-18T15:50:45.547Z] debug POST /upload (1571 ms) 500`

![image](https://user-images.githubusercontent.com/19354443/104938061-99ddaf00-59bf-11eb-84d0-83631210e870.png)

Here is my server.js
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1338),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'secret'),
    },
  },
});
```

plugins.js

```
module.exports = ({ env }) => ({
  upload: {
    provider: 'cloudinary',
    providerOptions: {
      cloud_name: env('CLOUDINARY_NAME', "cloud name"),
      api_key: env('CLOUDINARY_KEY', "api key"),
      api_secret: env('CLOUDINARY_SECRET', "secret key"),
    },
  },
});
```

database.json

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "mongoose",
      "settings": {
        "uri": " uri"
      },
      "options": {
        "ssl": true
      }
    }
  }
}

```

**Comment by Mortalife** [comment]
Looks like your `CLOUDINARY_NAME` environment variable isn't being set? Are you able to confirm?

**Comment by bahadryalcn** [comment]
> Looks like your `CLOUDINARY_NAME` environment variable isn't being set? Are you able to confirm?

it is looks like that but i added Cloudinary_name to .env file and plugins.js . İ had to create new project and now everything's working fine. I couldnt fine any other solution.

**Comment by derrickmehaffy** [comment]
`Cloudinary_name` Keep in mind this needs to be all caps as it is case-sensitive, however marking as closed since the user managed to get it working.
