### ISSUE TITLE
Server fails to start when package.json contains shell parameter expansions

### ISSUE THREAD

**Issue by ackro** [strapi/strapi#916]
**Information**

- **Node.js version**: 9.6.1
- **npm version**: 5.8.0
- **Strapi version**: 3.0.0-alpha.11.3
- **Database**: MongoDB
- **Operating system**: MacOS

**What is the current behavior?**

Strapi server fails to start when package.json contains shell parameter syntax, e.g. a script containing `FOO=${BAZ:-foo}`.

Shell parameters could normally be used with npm but Strapi interprets them as JS and throws a syntax error.

```shell
[2018-04-09T05:42:07.122Z] debug Server wasn't able to start properly.
SyntaxError: Missing } in template expression
    at Object.keys.reduce (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:379:38)
    at Array.reduce (<anonymous>)
    at templateConfigurations (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:375:27)
    at Object.keys.reduce (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:377:18)
    at Array.reduce (<anonymous>)
    at templateConfigurations (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:375:27)
    at Object.keys.reduce (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:377:18)
    at Array.reduce (<anonymous>)
    at templateConfigurations (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:375:27)
    at Strapi.module.exports.app (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:94:19)
    at Strapi.load (/private/tmp/test/node_modules/strapi/lib/Strapi.js:197:29)
    at <anonymous>
```

**Steps to reproduce the problem**

1. `> strapi new test` (accept defaults)
1. add the conflicting code to `scripts` in package.json:
`"test": "FOO=${BAZ:-foo} sh -c 'echo $FOO'"`
1. NPM runs the script normally
`> export BAZ=bar`
`> npm test`
`bar`
1. Start Strapi
`> npm start`
`SyntaxError: Missing } in template expression`

**What is the expected behavior?**

Server starts normally.

**Suggested solutions**

Template literals in configuration are ignored if they contain `()` characters indicating a function call.

https://github.com/strapi/strapi/blob/648bf52a3c69b50df14fe69e1625029ab31f093e/packages/strapi/lib/core/configurations.js#L371-L374

They could also be ignored if they contain shell parameter expansion characters: `: = - ` etc. [(Bash docs)](http://wiki.bash-hackers.org/syntax/pe#overview).

I don't think these shell characters would appear when using dynamic configuration as intended.

**Workaround**

Insert an inline comment containg a bracket `` `#(` `` so that Strapi ignores the expression.

e.g.
```js
"scripts": {
    "test": "FOO=${BAZ:-foo`#(`} sh -c 'echo $FOO'"
}
```

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hi @ackro that's a good point. Can you please submit a PR to fix it.
Will appreciate your help.

**Comment by derrickmehaffy** [comment]
@ackro any update on this? Just wanted to see if could close out some old issues.

**Comment by ackro** [comment]
hey @derrickmehaffy, not as yet but would like to submit a PR soon.
