### ISSUE TITLE
Quick start installation instructions cannot resolve dependencies of strapi-connector-bookshelf

### ISSUE THREAD

**Issue by KerimG** [strapi/strapi#9206]
### Describe the bug

The installation instruction described in the Quick Start Guide does not work. The knex package could not be resolved.  There seems to be a dependency tree issue in strapi-connector-bookshelf.

### Steps to reproduce the behavior

Simply run `npx create-strapi-app my-project --quickstart`

### Expected behavior

Creation of a folder called my-project with the project data and installation of dependencies.

### Code snippets
```
λ npx create-strapi-app my-project --quickstart
Creating a new Strapi application at /Volumes/Code/tf/my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.4.4
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.4.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/kg/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kg/.npm/_logs/2021-01-25T09_11_22_830Z-debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd /Volumes/Code/tf/my-project && npm install

npm ERR! code 1
npm ERR! path /Volumes/Code/tf
npm ERR! command failed
npm ERR! command sh -c create-strapi-app my-project --quickstart

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kg/.npm/_logs/2021-01-25T09_11_23_866Z-debug.log
```

### System

- Node.js version: 15.5.0
- NPM version: 7.3.0
- Operating system: macOS 11.1 20C69 arm64

**Comment by KerimG** [comment]
I thought it might be a Node/NPM version error and downgraded to node@14.15.4 and npm@6.14.10 but then got the following error:

```
λ npx create-strapi-app my-project --quickstart
npx: installed 91 in 3.041s
Creating a new Strapi application at /Volumes/Code/tf/my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-darwin-arm64v8.tar.br
ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kg/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/Users/kg/.nvm/versions/node/v14.15.4/bin/node" "/Users/kg/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Code/tf/my-project/node_modules/sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN strapi-connector-bookshelf@3.4.4 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @buffetjs/utils@3.3.3-next.2 requires a peer of yup@^0.27.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.6.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.26.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.26.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kg/.npm/_logs/2021-01-25T09_32_19_478Z-debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd /Volumes/Code/tf/my-project && npm install
```

**Comment by passchn** [comment]
I'm having the same issue. Could you solve it somehow?

**Comment by passchn** [comment]
It worked now with the --legacy-peer-deps flag: 

`npx --legacy-peer-deps create-strapi-app my-project --quickstart`

At least I got to the Register admin page, could create a user and everything seems to work. But there might be some dependency issues now, I guess. It's my first time trying npm and strapy though, so I don't really know what to check.

**Comment by derrickmehaffy** [comment]
> Node.js version: 15.5.0

We don't support node v15 (or any odd version of node) and it's quite likely the npx being used is coming from v15. I would suggest a clean install of node + npm or using nvm if you are on mac/linux.

Marking as closed as it's an unsupported node, npm, or npx version.
See: https://github.com/strapi/strapi#-requirements
Or: https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#recommended-requirements

**Comment by KerimG** [comment]
@derrickmehaffy that's what I thought. Please see my first response to this thread. I downgraded to node 14 using NVM and then tried a clean install. It didn't work either. Should I create a new issue for that?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy that's what I thought. Please see my first response to this thread. I downgraded to node 14 using NVM and then tried a clean install. It didn't work either. Should I create a new issue for that?

It's likely still trying to resolve packages with npm7, its something we have seen before. Certain systems you have to purge the existing packages to downgrade unless you are using nvm

**Comment by KerimG** [comment]
> It's likely still trying to resolve packages with npm7, its something we have seen before. Certain systems you have to purge the existing packages to downgrade unless you are using nvm

I did use nvm. I just tried it again in a clean folder with cleared npm cache and everything. See:

```
λ node -v
v14.15.4
~/code/tf
λ npm -v
6.14.10
~/code/tf
λ nvm ls
->     v14.15.4
        v15.5.0
default -> 15.5.0 (-> v15.5.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v15.5.0) (default)
stable -> 15.5 (-> v15.5.0) (default)
lts/* -> lts/fermium (-> v14.15.4)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.23.1 (-> N/A)
lts/erbium -> v12.20.1 (-> N/A)
lts/fermium -> v14.15.4
~/code/tf
```

but I get the following error:

```
λ npx create-strapi-app my-project --quickstart
npx: installed 91 in 4.676s
Creating a new Strapi application at /Volumes/Code/tf/my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-darwin-arm64v8.tar.br
ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kg/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/Users/kg/.nvm/versions/node/v14.15.4/bin/node" "/Users/kg/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Code/tf/my-project/node_modules/sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN strapi-connector-bookshelf@3.4.5 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @buffetjs/utils@3.3.3-next.2 requires a peer of yup@^0.27.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.6.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.26.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.26.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kg/.npm/_logs/2021-01-26T15_33_09_257Z-debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd /Volumes/Code/tf/my-project && npm install
```

It looks like Apple M1 architecture isn't supported, yet.

**Comment by derrickmehaffy** [comment]
```
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-darwin-arm64v8.tar.br
ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kg/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/Users/kg/.nvm/versions/node/v14.15.4/bin/node" "/Users/kg/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Code/tf/my-project/node_modules/sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

> libvips-8.10.0-darwin-arm64v8.tar.br

Yup the ARM M1 based chip has known issues: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#development-workflow


For users running on Apple Silicon M1, you may encounter errors thrown by sharp. You may need to re-install libvps or to build sharp manually following this [issue comment](https://github.com/lovell/sharp/issues/2460#issuecomment-751491241) in order to start the project.

**Comment by hyeonhong** [comment]
I had the same issue today and I found the solution from [this answer](https://stackoverflow.com/questions/66038828/strapi-heroku-deployment-failednpm-err-code-eresolve).

Basically, you should update `package.json` as below.

```
"engines": {
  "node": "<=14.x.x",
  "npm": "<=6.x.x"
}
```

In the quickstart, the range was  `"npm": ">=6.0.0"`, which caused npm v7 to run.

**Comment by derrickmehaffy** [comment]
Ah thank you @hyeonhong let me check what we generate with as we may need to adjust the default engines object for new projects
