### ISSUE TITLE
Error: Action must be defined to build a permission query

### ISSUE THREAD

**Issue by 01hossein10** [strapi/strapi#9268]
### Bug description

When I update my Strapi to version 3.4.5, then I try to click on one of collection types (it was the same for all of my collection types) Strapi doesn't load the data and make pop-up error. You can see the error in the terminal, at the Code snippets.

### Code snippets

Stack trace of the error:

`[2021-01-30T07:14:25.940Z] error Error: Action must be defined to build a permission query`

    at Object.getQuery (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/strapi-admin/services/permission/permissions-manager/index.js:31:13)
    at Object.queryFrom (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/strapi-admin/services/permission/permissions-manager/index.js:38:34)
    at Object.buildPermissionQuery (/home/hossein/Workspace/Projects/Paziresh24/strapi/extensions/content-manager/services/permission-checker.js:46:60)
    at Object.find (/home/hossein/Workspace/Projects/Paziresh24/strapi/extensions/content-manager/controllers/collection-types.js:37:47)
    at dispatch (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at dispatch (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/koa-compose/index.js:42:32)
    at /home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:28
    at dispatch (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/koa-compose/index.js:42:32)
    at /home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/strapi-plugin-content-manager/config/policies/hasPermissions.js:27:12
    at dispatch (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/koa-compose/index.js:42:32)
    at module.exports (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/strapi-admin/config/policies/isAuthenticatedAdmin.js:8:10)
    at dispatch (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/koa-compose/index.js:42:32)
    at module.exports (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/strapi-plugin-content-manager/config/policies/routing.js:26:9)
    at dispatch (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/koa-compose/index.js:42:32)
    at module.exports (/home/hossein/Workspace/Projects/Paziresh24/strapi/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:10:12)

### System

- Node.js version:  v14.15.3
- NPM version: 6.14.9
- Strapi version: from 3.4.3 to 3.4.5
- Database: MySQL
- Operating system: Linux (Ubuntu 20.04)

**Comment by derrickmehaffy** [comment]
> /home/hossein/Workspace/Projects/Paziresh24/strapi/extensions/content-manager/controllers/collection-types.js:37:47

You have some extensions, per our [update guide](https://strapi.io/documentation/developer-docs/latest/guides/update-version.html#extensions) you will need to manually review your version of the extended file to that of the release and make the required changes.

We cannot account for custom user code in migration guides, if you use the extensions system you will need to do this on all version updates.

**Comment by 01hossein10** [comment]
@derrickmehaffy Thanks
