### ISSUE TITLE
 error Error: Cannot find module 'strapi-admin/package.json'

### ISSUE THREAD

**Issue by bijarniya** [strapi/strapi#9285]
mukesh$ yarn develop
yarn run v1.22.10
$ strapi develop
[2021-02-01T15:57:54.587Z] debug ⛔️ Server wasn't able to start properly.
[2021-02-01T15:57:54.588Z] error Error: Cannot find module 'strapi-admin/package.json'
Require stack:
- /Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/load/package-path.js
- /Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/core/load-admin.js
- /Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/core/load-modules.js
- /Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/Strapi.js
- /Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/index.js
- /Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/commands/develop.js
- /Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at module.exports (/Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/load/package-path.js:8:24)
    at module.exports (/Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/core/load-admin.js:8:21)
    at module.exports (/Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/core/load-modules.js:37:5)
    at Strapi.load (/Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/Strapi.js:306:27)
    at Strapi.start (/Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/Strapi.js:190:18)
    at module.exports (/Users/mukesh/Desktop/project/web/intglobal-strapi/node_modules/strapi/lib/commands/develop.js:99:29)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
