### ISSUE TITLE
File upload, related fields returning null

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#9308]
### Describe the bug

In one of the more recent updates, something has broken and now file uploads are returning an array of null values for the `related` field.

See the following two APIs:

Sample Project (Production) on v3.0.4: https://api.canonn.tech/upload/files/1
Sample Project (Staging) on v3.4.5: https://api.canonn.tech:2083/upload/files/1

Link to project code (no customization of the upload plugin or it's models has been done): https://github.com/canonn-science/capiv2-strapi

A point to note however is these files were uploaded long before the update, but even new files still provide a null related value: 
https://api.canonn.tech:2083/upload/files/193

### Steps to reproduce the behavior

1. Create a model with a media field
2. Add file to the media field
3. Attempt to directly query the files on the `/upload/files` or `/upload/files/:id` 

### Expected behavior

Response pre-whatever update caused this returned an array of objects containing the data and an injected `__contentType` key

### Screenshots

v3.0.4:

![image](https://user-images.githubusercontent.com/8593673/106766862-83f2ff80-65f7-11eb-9e0b-a7481c57cff1.png)

v3.4.5:

![image](https://user-images.githubusercontent.com/8593673/106766909-92d9b200-65f7-11eb-8659-d1c39f7151bc.png)

### System

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.4.5 (working on at least v3.0.4)
- Database: MariaDB 10.5 LTS
- Operating system: Ubuntu Server 20.04 LTS

### Additional context

You can confirm the versions of each server here:

Production: https://api.canonn.tech/version
Staging: https://api.canonn.tech:2083/version

**Comment by Mortalife** [comment]
This change appears to have broken polymorphic save of images within the admin dashboard.

```[2021-02-10T13:31:41.710Z] debug PUT /content-manager/collection-types/application::blog-post.blog-post/1 (815 ms) 200
[2021-02-10T13:31:46.978Z] debug GET /upload/files/count? (31 ms) 200
[2021-02-10T13:31:46.988Z] debug GET /upload/files?_limit=10&_start=0&_sort=updated_at%3ADESC (39 ms) 200
[2021-02-10T13:31:49.989Z] error TypeError: Cannot read property '__contentType' of null
    at sanitizeFn (/home/matt/code/smtj/strapi/node_modules/strapi-utils/lib/sanitize-entity.js:74:56)
    at Array.map (<anonymous>)
    at reducerFn (/home/matt/code/smtj/strapi/node_modules/strapi-utils/lib/sanitize-entity.js:85:52)
    at /home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:914:11
    at /home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:2990:24)
    at /home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:4894:18
    at baseReduce (/home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:911:5)
    at Function.reduce (/home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:9707:14)
    at sanitizeEntity (/home/matt/code/smtj/strapi/node_modules/strapi-utils/lib/sanitize-entity.js:112:12)
    at sanitizeFn (/home/matt/code/smtj/strapi/node_modules/strapi-utils/lib/sanitize-entity.js:79:11)
    at Array.map (<anonymous>)
    at reducerFn (/home/matt/code/smtj/strapi/node_modules/strapi-utils/lib/sanitize-entity.js:85:52)
    at /home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:914:11
    at /home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/matt/code/smtj/strapi/node_modules/lodash/lodash.js:2990:24)```

**Comment by derrickmehaffy** [comment]
Reopening due to the above mentioned comment and also an issue with media relations on components.

**Comment by derrickmehaffy** [comment]
Valid in v4 for components only (normal relations work)

**Comment by petersg83** [comment]
@derrickmehaffy Hello :) I don't understand everything about this issue. Would you have time to explain it a bit more in sync?

**Comment by derrickmehaffy** [comment]
Yeah sure poke me next week @petersg83 but basically if you create a relation field inside of component (multiple levels or single) you can't see that relation on the media side.

**Comment by ifdotpy** [comment]
Guys are there any updates? I have this issue in my project and it stops me from going to production. I link an image to a component and the image disappears right in the next moment.

**Comment by derrickmehaffy** [comment]
Confirmed on v4.2.3 (nested compo with a media field doesn't set the related)
