### ISSUE TITLE
Cannot read property 'associations' of undefined

### ISSUE THREAD

**Issue by MarkFuller1** [strapi/strapi#9340]
### Describe the bug
When I try to upload an image to an existing entry, it fails to create association, however succeeding to upload. 

### Steps to reproduce the behavior

1. Using the following schema
```json
{
      "name": "page rows",
      "description": "",
      "connection": "default",
      "kind": "collectionType",
      "collectionName": "page_rows",
      "attributes": {
        "row": {
          "type": "json"
        },
        "images": {
          "type": "media",
          "multiple": true,
          "required": false,
          "allowedTypes": [
            "images"
          ]
        }
      }
    },
```
2. Upload a "page rows" without an image value
3. upload the image value with the following header values. 

```
file = fileToUpload
entryModel = "page_rows"
entryID = id
entryField = "images"
source = "users-permissions"
```

### Expected behavior

The image should be uploaded as well as associated with the specified entry

Instead throws the following error

``` bash
[2021-02-07T21:01:35.334Z] error TypeError: Cannot read property 'associations' of undefined
at /srv/app/node_modules/strapi-connector-mongoose/lib/relations.js:250:43
at Array.forEach (<anonymous>)
at /srv/app/node_modules/strapi-connector-mongoose/lib/relations.js:235:20
at Array.reduce (<anonymous>)
at Function.update [as updateRelations] (/srv/app/node_modules/strapi-connector-mongoose/lib/relations.js:97:68)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Object.add (/srv/app/node_modules/strapi-plugin-upload/services/Upload.js:253:17)
at async Promise.all (index 0)
at async Object.upload (/srv/app/node_modules/strapi-plugin-upload/services/Upload.js:105:12)
at async Object.upload (/srv/app/node_modules/strapi-plugin-upload/controllers/Upload.js:82:18)
at async /srv/app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
at async module.exports (/srv/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:97:3)
at async /srv/app/node_modules/strapi-utils/lib/policy.js:52:5
[2021-02-07T21:01:35.334Z] debug POST /upload (564 ms) 500

```

### System

- Node.js version: 10.16.0
- NPM version: 6.14.9
- Strapi version: docker image strapi/strapi:3.0.0-beta.20-node12
- Database:  docker image  `mongo:4.2.5-bionic`
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
> docker image strapi/strapi:3.0.0-beta.20-node12

You are using an unsupported version of Strapi. Please see: https://github.com/strapi/strapi/security/policy

We only support Stable versions, and generally we will always ask you to test bugs on the latest version (as of writing it's v3.4.6)

Please see the migration guides and update your docker container: https://strapi.io/documentation/developer-docs/latest/migration-guide/
