### ISSUE TITLE
Unable to start Strapi container

### ISSUE THREAD

**Issue by alphonso06** [strapi/strapi#9403]
## Bug report
The message "debug ⛔️ Server wasn't able to start properly" appears before the container starts.

### Describe the bug
While starting the containers, the MariaDB starts just fine, Strapi encounters a problem with the error code: `ETIMEDOUT`.

### Steps to reproduce the behavior

1. Follow the documentation to install Strapi using Docker, as seen [here](https://strapi.io/documentation/developer-docs/latest/installation/docker.html)
2. See error

### Expected behavior
The Strapi container will start properly and show the admin login.

### Output logs
```
Starting your app...
[2021-02-15T10:35:21.519Z] debug ⛔️ Server wasn't able to start properly.
[2021-02-15T10:35:21.521Z] error Error: connect ETIMEDOUT
at Connection._handleConnectTimeout (/srv/app/node_modules/mysql/lib/Connection.js:409:13)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:314:20)
at Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
at Protocol._enqueue (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
at Protocol.handshake (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
at Connection.connect (/srv/app/node_modules/mysql/lib/Connection.js:116:18)
at /srv/app/node_modules/knex/lib/dialects/mysql/index.js:68:18
From previous event:
at Client_MySQL.acquireRawConnection (/srv/app/node_modules/knex/lib/dialects/mysql/index.js:63:12)
at create (/srv/app/node_modules/knex/lib/client.js:258:21)
at /srv/app/node_modules/tarn/lib/Pool.js:389:34
at Object.tryPromise (/srv/app/node_modules/tarn/lib/utils.js:53:24)
at /srv/app/node_modules/tarn/lib/Pool.js:389:17
at new Promise (<anonymous>)
at callbackOrPromise (/srv/app/node_modules/tarn/lib/Pool.js:380:12)
at Pool._create (/srv/app/node_modules/tarn/lib/Pool.js:290:9)
at Pool._doCreate (/srv/app/node_modules/tarn/lib/Pool.js:260:36)
at Pool._tryAcquireOrCreate (/srv/app/node_modules/tarn/lib/Pool.js:211:18)
at Pool.acquire (/srv/app/node_modules/tarn/lib/Pool.js:117:14)
at /srv/app/node_modules/knex/lib/client.js:312:43
From previous event:
at Client_MySQL.acquireConnection (/srv/app/node_modules/knex/lib/client.js:312:26)
at Runner.ensureConnection (/srv/app/node_modules/knex/lib/runner.js:246:8)
at Runner.run (/srv/app/node_modules/knex/lib/runner.js:25:27)
at SchemaBuilder.Target.then (/srv/app/node_modules/knex/lib/interface.js:14:43)
```

### System

- Strapi version: latest image from Docker hub
- Database: MariaDB latest image from Docker hub
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Please provide your environment variables used with the `./config/server.js` specifically the host and port keys.

Strapi will bind literally on the host address, so typically it needs to be either `127.0.0.1` / `localhost` / `0.0.0.0` for containers. Our default host is `0.0.0.0` which should work with docker.

**Comment by derrickmehaffy** [comment]
closing as no new information
