### ISSUE TITLE
MongoDB nested component media causes unique validation error

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#9438]
### Describe the bug

When using a dynamic zone with nested components that contain a media field, if you try to attach the same media to multiple entries you will get the following error:

Admin Panel: 
`Invalid input data. Please verify unique constraints`

Server side:
```
[2021-02-17T21:21:39.352Z] error TypeError: Cannot read property '__contentType' of null
    at sanitizeFn (/home/dmehaffy/Development/testVMBug/node_modules/strapi-utils/lib/sanitize-entity.js:74:56)
    at Array.map (<anonymous>)
    at reducerFn (/home/dmehaffy/Development/testVMBug/node_modules/strapi-utils/lib/sanitize-entity.js:85:52)
    at /home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:914:11
    at /home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:2990:24)
    at /home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:4894:18
    at baseReduce (/home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:911:5)
    at Function.reduce (/home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:9707:14)
    at sanitizeEntity (/home/dmehaffy/Development/testVMBug/node_modules/strapi-utils/lib/sanitize-entity.js:112:12)
    at sanitizeFn (/home/dmehaffy/Development/testVMBug/node_modules/strapi-utils/lib/sanitize-entity.js:79:11)
    at Array.map (<anonymous>)
    at reducerFn (/home/dmehaffy/Development/testVMBug/node_modules/strapi-utils/lib/sanitize-entity.js:85:52)
    at /home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:914:11
    at /home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/dmehaffy/Development/testVMBug/node_modules/lodash/lodash.js:2990:24)
```
### Steps to reproduce the behavior

1. Create a content-type
2. Create a dynamic zone with 2 nested components (I used a single compo + a nested repeat compo)
3. Add a media field to the repeat compo
4. create one entry with a media entry added
5. create another entry and try to reuse the same media
6. See error

### Expected behavior

Should be able to reuse media without any validation errors

### Screenshots

No screenshots but see video:

https://www.loom.com/share/06b02b5968fc41f3b69efceaba6a5285

### Code snippets

N/A

### System

- Node.js version: v12
- NPM version: v6
- Strapi version: 3.4.6
- Database: MongoDB
- Operating system: Linux Mint 20 (Ubuntu 20.04)

### Additional context

Only happens on MongoDB, all other databases (SQL) are not affected

**Comment by derrickmehaffy** [comment]
Link to sample reproduce project: 
[testVMBug.zip](https://github.com/strapi/strapi/files/5998760/testVMBug.zip)

**Comment by cgonzalezsan** [comment]
I added the changes from the related PR, but I'm still getting the same error upon save

```
error Error: Some of the provided components in text are not related to the entity
    at /Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:354:21
    at Array.forEach (<anonymous>)
    at deleteOldComponents (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:352:15)
    at updateComponents (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:212:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async update (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:493:5)
    at async Object.update (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:64:14)
    at async Object.update (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-database/lib/queries/helpers.js:15:18)
    at async Promise.all (index 0)
    at async updateComponents (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:243:30)
    at async update (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:493:5)
    at async Object.update (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-connector-mongoose/lib/queries.js:64:14)
    at async Object.update (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-database/lib/queries/helpers.js:15:18)
    at async Object.update (/Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi/lib/services/entity-service.js:116:17)
    at async /Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-plugin-content-manager/controllers/collection-types.js:118:29
  Error: Invalid input data. Please verify unique constraints
      at /Users/carlos/GitHub/Walter-Knoll-CMS/node_modules/strapi-plugin-content-manager/utils/wrap-bad-request.js:13:25
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-18T17:58:17.842Z] debug PUT /content-manager/collection-types/application::product.product/5f8098d9ce5b10093b829b23 (342 ms) 400
8:00
it’s throwing that when trying to save
```

**Comment by alexandrebodin** [comment]
@cgonzalezsan Please open a new issue with more details. We need the models & the steps to reproduce. the video is lacking in context.


The error in the issue we just closed was "error TypeError: Cannot read property '__contentType' of null" and we fixed this one :)
