### ISSUE TITLE
strapi 3.5.0 quickstart fails on admin panel build

### ISSUE THREAD

**Issue by djpogo** [strapi/strapi#9448]
### Describe the bug

Executing `npx create-strapi-app my-project --quickstart` stops on building admin panel.

### Steps to reproduce the behavior

1. execute `npx create-strapi-app my-project --quickstart`
2. See error

### Expected behavior

A working quickstart strapi.

### Code snippets

**console output**:
```
…
strapi build "--no-optimization"

internal/modules/cjs/loader.js:430
      throw e;
      ^

Error: Cannot find module '/home/raoul/work/me/my-project/node_modules/@babel/runtime/helpers/interopRequireDefault.js'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:842:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:835:15)
    at resolveExports (internal/modules/cjs/loader.js:424:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/raoul/work/me/my-project/node_modules/yup/lib/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/raoul/work/me/my-project/node_modules/strapi-utils/lib/validators.js:3:13) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/raoul/work/me/my-project/node_modules/@babel/runtime/package.json'
```

**package.json dependencies**:
```
"dependencies": {
    "strapi": "3.5.0",
    "strapi-admin": "3.5.0",
    "strapi-utils": "3.5.0",
    "strapi-plugin-content-type-builder": "3.5.0",
    "strapi-plugin-content-manager": "3.5.0",
    "strapi-plugin-users-permissions": "3.5.0",
    "strapi-plugin-email": "3.5.0",
    "strapi-plugin-upload": "3.5.0",
    "strapi-connector-bookshelf": "3.5.0",
    "knex": "<0.20.0",
    "sqlite3": "5.0.0"
  },
```

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 3.5.0
- Database: sqlite
- Operating system: ubuntu 20.10

**Comment by djpogo** [comment]
i tried again today an it works fine. sorry.
