### ISSUE TITLE
Unable to deploy with external database: cross-database references are not implemented: "pool1.public.strapi_role"

### ISSUE THREAD

**Issue by fandy** [strapi/strapi#9546]
Strapi seems unable to deploy when you set the `DATABASE_URL` to an external managed database. In my case, I'm using a DigitalOcean Droplet with their managed database and kept getting this error:

```
{
         method: 'select',
         options: {},
         timeout: false,
         cancelOnTimeout: false,
         bindings: [ 'strapi-editor', 1 ],
         __knexQueryUid: '5aa31833-777a-4fa6-9aab-e87cdc9ffa43',
         sql: 'select distinct "strapi_role".* from "strapi_role" where "strapi_role"."code" = ? limit ?'
       }
       {
         method: 'select',
         options: {},
         timeout: false,
         cancelOnTimeout: false,
         bindings: [
           'strapi::permission',
           'plugins::content-manager.explorer.read',
           'plugins::content-manager.explorer.update',
           'plugins::content-manager.explorer.create',
           'plugins::content-manager.explorer.delete',
           2,
           100
         ],
         __knexQueryUid: 'd7d1dc01-de9c-4188-896d-3998cb390f17',
         sql: 'select distinct "strapi_permission".* from "strapi_permission" left join "pool1"."public"."strapi_role" as "strapi_role_1" on "strapi_role_1"."id" = "strapi_permission"."role" where "strapi_permission"."subject" = ? and "strapi_permission"."action" in (?, ?, ?, ?) and "strapi_role_1"."id" = ? limit ?'
       }
       [2021-02-28T20:58:21.215Z] error Bootstrap function in admin failed
       [2021-02-28T20:58:21.216Z] error error: cross-database references are not implemented: "pool1.public.strapi_role"
           at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
           at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
           at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
           at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)
           at TLSSocket.emit (events.js:315:20)
           at TLSSocket.EventEmitter.emit (domain.js:467:12)
           at addChunk (internal/streams/readable.js:309:12)
           at readableAddChunk (internal/streams/readable.js:284:9)
           at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
           at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! mammal@0.1.0 start: `strapi start`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the mammal@0.1.0 start script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2021-02-28T20_58_21_235Z-debug.log
       > mammal@0.1.0 start /app
       > strapi start
=====> end content web container output
```

**Comment by nickw-mindera** [comment]
> Upstream issue with Knex, not directly with Strapi. Knex itself doesn't support pooled databases [...]

@derrickmehaffy Hi, could I ask for some clarity on this, given the docs say:

> `pool` Options used for database connection pooling. For default value and more information, look at [Knex's pool config documentation](https://knexjs.org/#Installation-pooling).
> https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database

Is there some specific issue with Knex you're referring to, rather than support (sorry if I'm missing something entirely)?

**Comment by derrickmehaffy** [comment]
> > Upstream issue with Knex, not directly with Strapi. Knex itself doesn't support pooled databases [...]
> 
> @derrickmehaffy Is it possible to get a bit more clarity on this, I'm a bit lost, as the docs say:
> 
> > `pool` Options used for database connection pooling. For default value and more information, look at [Knex's pool config documentation](https://knexjs.org/#Installation-pooling).
> > https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database
> 
> Is there some specific issue with Knex you're referring to (sorry if I'm missing something entirely)?

There is a difference between **connection pooling** and **database pooling**

Connection pooling is a group of connections to a database that can be reused (instead of opening a connection, requesting data, and closing it will keep the connection alive to request more data on another request.) **Connection pooling is about reducing connection latency**

Database pooling AKA Database clustering is entirely different and typically means you have a primary database node and multiple read-replicas. Knex.js doesn't support Database pooling.

**Comment by Keith-Hon** [comment]
Hi @derrickmehaffy , Could you please include that database pooling not supported in the strapi documentation and suggest an official way to setup a database cluster with strapi?

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy , Could you please include that database pooling not supported in the strapi documentation and suggest an official way to setup a database cluster with strapi?

Most likely not as database clustering is extremely subjective and would require a lot of effort on our side to provide documentation on a part of some software that we do not build, maintain, or have any open communication channels with. There are far better resources out there than our docs on how to build a MariaDB Galera cluster

**Comment by Keith-Hon** [comment]
> > Hi @derrickmehaffy , Could you please include that database pooling not supported in the strapi documentation and suggest an official way to setup a database cluster with strapi?
> 
> 
> 
> Most likely not as database clustering is extremely subjective and would require a lot of effort on our side to provide documentation on a part of some software that we do not build, maintain, or have any open communication channels with. There are far better resources out there than our docs on how to build a MariaDB Galera cluster

How about separating the read and write database connections at the application level? When there are more collection types, the initial startup time for strapi becomes very slow even with connection pooling. Separating the read connections to a scalable read replica could solve this issue. (I'm using Postgres in my case)

**Comment by derrickmehaffy** [comment]
> > > Hi @derrickmehaffy , Could you please include that database pooling not supported in the strapi documentation and suggest an official way to setup a database cluster with strapi?
> > 
> > 
> > Most likely not as database clustering is extremely subjective and would require a lot of effort on our side to provide documentation on a part of some software that we do not build, maintain, or have any open communication channels with. There are far better resources out there than our docs on how to build a MariaDB Galera cluster
> 
> How about separating the read and write database connections at the application level? When there are more collection types, the initial startup time for strapi becomes very slow or unable to start even with connection pooling. Separating the read connections to a scalable read replica set could solve this issue. (I'm using Postgres in my case)

That's the main issue I see is you really only need to do this for PostgreSQL as for example MySQL and MariaDB have options that don't require the application to do any of that.

EG: ProxySQL or MariaDB Maxscale which allow for read/write splitting, monitoring, logging, and even caching which far exceed anything we can (or will do) at the application level.

**Comment by Keith-Hon** [comment]
> > > > Hi @derrickmehaffy , Could you please include that database pooling not supported in the strapi documentation and suggest an official way to setup a database cluster with strapi?
> > > 
> > > 
> > > Most likely not as database clustering is extremely subjective and would require a lot of effort on our side to provide documentation on a part of some software that we do not build, maintain, or have any open communication channels with. There are far better resources out there than our docs on how to build a MariaDB Galera cluster
> > 
> > 
> > How about separating the read and write database connections at the application level? When there are more collection types, the initial startup time for strapi becomes very slow or unable to start even with connection pooling. Separating the read connections to a scalable read replica set could solve this issue. (I'm using Postgres in my case)
> 
> That's the main issue I see is you really only need to do this for PostgreSQL as for example MySQL and MariaDB have options that don't require the application to do any of that.
> 
> EG: ProxySQL or MariaDB Maxscale which allow for read/write splitting, monitoring, logging, and even caching which far exceed anything we can (or will do) at the application level.

Thanks for the reply. I ended up using pgpool to solve the issue.
https://pgpool.net/mediawiki/index.php/Main_Page

**Comment by joedeveloper** [comment]
> > > > > Hi @derrickmehaffy , Could you please include that database pooling not supported in the strapi documentation and suggest an official way to setup a database cluster with strapi?
> > > > 
> > > > 
> > > > Most likely not as database clustering is extremely subjective and would require a lot of effort on our side to provide documentation on a part of some software that we do not build, maintain, or have any open communication channels with. There are far better resources out there than our docs on how to build a MariaDB Galera cluster
> > > 
> > > 
> > > How about separating the read and write database connections at the application level? When there are more collection types, the initial startup time for strapi becomes very slow or unable to start even with connection pooling. Separating the read connections to a scalable read replica set could solve this issue. (I'm using Postgres in my case)
> > 
> > 
> > That's the main issue I see is you really only need to do this for PostgreSQL as for example MySQL and MariaDB have options that don't require the application to do any of that.
> > EG: ProxySQL or MariaDB Maxscale which allow for read/write splitting, monitoring, logging, and even caching which far exceed anything we can (or will do) at the application level.
> 
> Thanks for the reply. I ended up using pgpool to solve the issue. https://pgpool.net/mediawiki/index.php/Main_Page

Could you share more information on how you used / configured pgpool?
I am running into the same issue as you and would also like to be able to use pgbouncer / postgres on DO
