### ISSUE TITLE
Build fails when using pnpm

### ISSUE THREAD

**Issue by Nick-Mazuk** [strapi/strapi#9604]
### Describe the bug

When using pnpm instead of yarn, the build fails.

```
Error: Module not found: Error: Can't resolve 'function.prototype.name' in 'repo/node_modules/airbnb-prop-types/build/helpers'
    at repo/node_modules/.pnpm/strapi-admin@3.5.2/node_modules/strapi-admin/index.js:71:23
    at finalCallback (repo/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (repo/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/Compiler.js:265:20)
    at repo/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (repo/node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at repo/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/Compilation.js:1173:13
    at repo/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/Compilation.js:1096:25
    at repo/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/Compilation.js:1017:13
    at repo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2830:7
    at repo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2830:7
    at done (repo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2863:11)
    at repo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2818:7
    at repo/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/Compilation.js:1017:13
    at repo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2830:7
    at repo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2830:7
    at done (repo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2863:11)
 ERROR  Command failed with exit code 1.
```

### Steps to reproduce the behavior

```
npx create-strapi-app strapi --quickstart
rm -rf node_modules
```

Next, there are a lot of [missing dependencies](https://pnpm.js.org/en/faq#pnpm-does-not-work-with-your-project-here), in someone's `package.json`, so add them to your `package.json`

```
"@babel/runtime": "^7.13.9",
"@buffetjs/styles": "^3.3.4",
"@fortawesome/fontawesome-free": "^5.15.2",
"@fortawesome/react-fontawesome": "^0.1.14",
"@redux-saga/core": "^1.1.3",
"@redux-saga/deferred": "^1.1.2",
"@redux-saga/delay-p": "^1.1.2",
"@redux-saga/is": "^1.1.2",
"@redux-saga/symbols": "^1.1.2",
"@sindresorhus/slugify": "^1.1.0",
"@sindresorhus/transliterate": "^0.1.1",
"axios": "^0.21.1",
"bootstrap": "^4.6.0",
"byte-size": "^7.0.1",
"codemirror": "^5.59.4",
"cropperjs": "^1.5.11",
"css-loader": "^5.1.1",
"deepmerge": "^4.2.2",
"draft-js": "^0.11.7",
"escape-string-regexp": "^4.0.0",
"fbjs": "^3.0.0",
"file-loader": "^6.2.0",
"font-awesome": "^4.7.0",
"formik": "^2.2.6",
"function.prototype.name": "^1.1.4",
"ip-regex": "^4.3.0",
"is-ip": "^3.1.0",
"knex": "0.21.18",
"lodash": "^4.17.21",
"lodash.deburr": "^4.1.0",
"lru-cache": "^6.0.0",
"markdown-it-emoji": "^2.0.0",
"markdown-it-footnote": "^3.0.2",
"markdown-it-ins": "^3.0.1",
"markdown-it-mark": "^3.0.1",
"markdown-it-sub": "^1.0.0",
"markdown-it-sup": "^1.0.0",
"match-sorter": "^6.3.0",
"parse-domain": "^3.0.3",
"pluralize": "^8.0.0",
"react-dates": "^21.8.0",
"redux-saga": "^1.1.3",
"regenerator-runtime": "^0.13.7",
"remove-accents": "^0.4.2",
"sanitize-html": "^2.3.2",
"sanitize.css": "^12.0.1",
"semver": "^7.3.4",
"sqlite3": "5.0.0",
```

Then finish the install and build.

```
pnpm i
pnpm run build
```

### Expected behavior

The build to succeed.

### Debug steps

- Installed the missing module: `function.prototype.name`
- Used the [readPackage hook](https://pnpm.js.org/en/pnpmfile#hooks)

### System

- Node.js version: 12.17.0, 12.22.0
- NPM version: 7.6.0
- PNPM version: 5.18.1
- Strapi version: 3.5.2
- Create strapi app version: 3.5.2
- Database: sqlite, postgress
- Operating system: macOS 11.2,  Ubuntu 20.04 (LTS) x64

**Comment by derrickmehaffy** [comment]
pnpm is not currently supported, marking as closed. The functionality of pnpm is something planned in npm v7+ and yarn v2+ and we will add support for those 2 when we have time. I would imagine after support those is added pnpm would work but it's not something we plan to officially support.

**Comment by TechQuery** [comment]
It fixed in https://github.com/strapi/strapi/issues/15511#issuecomment-1792679398
