### ISSUE TITLE
Getting MongoDB error while reusing a common relation between different content types

### ISSUE THREAD

**Issue by xcorman** [strapi/strapi#9626]
## Bug report

I wanted to use common content type `Tags` as global relations which can be added as relation to other content types. While I add to 1st content type `Template` the filter URL works perfectly but while I try to add in 2nd content type `Blog` and run filter URL, it throws 500 error

- It works for first content type - `Templates` 
 `/templates?tags.title=gero (626 ms) 200`

- The error produces when I run filter in 2nd content type - `Blogs`
```
[2021-02-06T15:10:34.849Z] error MongoError: $in requires an array as a second argument, found: missing
    at MessageStream.messageHandler (LOCATION\node_modules\mongodb\lib\cmap\connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:486:12)
    at processIncomingData (LOCATION\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (LOCATION\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.ondata (_stream_readable.js:719:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
[2021-02-06T15:10:34.850Z] debug GET /blogs?tags.title=gero (268 ms) 500
```

Relation with tags is **hasMany** tags

### Expected behavior

I want Tags collection to work with all content types not in just type.

### System

- Node.js version: 14.15.0
- NPM version: 6.14.8
- Strapi version: 3.3.0
- Database: MongoDB
- Operating system: Windows 10 (Latest)

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.3.0

Please try updating to the latest release, v3.5.2 as this issue should already be fixed

**Comment by xcorman** [comment]
Thanks @derrickmehaffy , it worked!
