### ISSUE TITLE
Error: component is not defined on the model

### ISSUE THREAD

**Issue by gustavpursche** [strapi/strapi#9671]
## Bug report

Re-using a component as repeatable sub-component throws the error "component is not defined on the model"

### Describe the bug

What I am doing:

1. I've create a component called media, which consists of fields for a file and a wysiwyg caption field
2. I'm re-using this component in a dynamic zone
3. Now I've created a media gallery, which has this repeatable media component as child
4. I've assigned the media gallery component to be allowed in the same dynamic zone of the page content type
5. When I'm now loading the pages overview, the following error is thrown:

```
[2021-03-10T09:42:31.912Z] error Error: component is not defined on the model.
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:50:15)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:31)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at EagerRelation.eagerFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:71:25)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:65:12
    at /home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:3585:27
    at /home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:3032:24)
    at /home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:4936:18
    at baseMap (/home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:9622:14)
    at EagerRelation.morphToFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:56:9)
    at EagerRelation.eagerFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:25:19)
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/collection.js:527:73)
    at Child.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/collection.js:179:27)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Child.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/collection.js:177:12)
From previous event:
    at Child.fetchAll (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/model.js:878:10)
    at find (/home/gustav/Development/seebruecke/cms/node_modules/strapi-connector-bookshelf/lib/queries.js:79:8)
    at /home/gustav/Development/seebruecke/cms/node_modules/strapi-database/lib/queries/paginated-queries.js:11:25
    at async /home/gustav/Development/seebruecke/cms/node_modules/strapi-database/lib/queries/helpers.js:15:18
    at async Object.findWithRelationCounts (/home/gustav/Development/seebruecke/cms/node_modules/strapi-database/lib/queries/relations-counts-queries.js:27:37)
    at async Object.find (/home/gustav/Development/seebruecke/cms/node_modules/strapi-plugin-content-manager/controllers/collection-types.js:31:37)
    at async /home/gustav/Development/seebruecke/cms/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async module.exports (/home/gustav/Development/seebruecke/cms/node_modules/strapi-plugin-content-manager/config/policies/routing.js:26:3)
    at async /home/gustav/Development/seebruecke/cms/node_modules/strapi-utils/lib/policy.js:68:5
    at async /home/gustav/Development/seebruecke/cms/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /home/gustav/Development/seebruecke/cms/node_modules/strapi/lib/middlewares/xss/index.js:26:9
```

### Steps to reproduce the behavior

You can see the problem on this repo: https://github.com/seebruecke-org/cms
using this branch: https://github.com/seebruecke-org/cms/pull/1/files

### Expected behavior

I expect to be able to re-use the media component as a child of media gallery.

### Screenshots

None.

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: 3.5.2
- Database: sqlite
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
Confirmed bug on v3.5.2 and also was reported to us by an enterprise customer with the same issue but using MongoDB. (Customer was also testing v3.5.2 upgrade)

**Comment by gustavpursche** [comment]
So this issue gets even weirded. I've done some refactoring of the schema here https://github.com/seebruecke-org/cms/pull/2/files

For some unknown reason the `helper-blocks.media` component now works in most cases ([even the gallery](https://github.com/seebruecke-org/cms/pull/2/files#diff-82a430abb7fec4568ecb966d072485520c06e7b6ca4c5c413c34c379bb702287R12-R13)), but not in some others. E.g. it's [broken now on the teaser large component](https://github.com/seebruecke-org/cms/pull/2/files#diff-0e1492bbe092f44340dbe88b5fbc208f70bea446ca0d7b1e2791a73dee939ba6R10-R13).

```
2021-03-27T14:15:45.190Z] error Error: upload_file is not defined on the model.
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:50:15)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:31)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at EagerRelation.eagerFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:71:25)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:65:12
    at /home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:3585:27
    at /home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:3032:24)
    at /home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:4936:18
    at baseMap (/home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/home/gustav/Development/seebruecke/cms/node_modules/lodash/lodash.js:9622:14)
    at EagerRelation.morphToFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:56:9)
    at EagerRelation.eagerFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:25:19)
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/model.js:1526:56)
    at Child.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/model.js:732:27)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Child.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/model.js:730:12)
From previous event:
    at Child.fetch (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/model.js:702:19)
    at Function.findOne (/home/gustav/Development/seebruecke/cms/node_modules/strapi-connector-bookshelf/lib/relations.js:65:8)
    at Function.update [as updateRelations] (/home/gustav/Development/seebruecke/cms/node_modules/strapi-connector-bookshelf/lib/relations.js:100:51)
    at runCreate (/home/gustav/Development/seebruecke/cms/node_modules/strapi-connector-bookshelf/lib/queries.js:115:20)
```

@derrickmehaffy Do you have any idea, how I could work around that issue?

**Comment by gustavpursche** [comment]
Sorry, me again: I figured the problem basically boils down to: https://github.com/strapi/strapi/issues/9150 [Changing all field names from media to image](https://github.com/seebruecke-org/cms/pull/2/commits/1a3e551cfa21ef9da04a02fa5a348769a4c8e81d) works for now.

**Comment by gustavpursche** [comment]
Closing this issue as duplicate of https://github.com/strapi/strapi/issues/9150, which describes the issue much clearer.
