### ISSUE TITLE
Error trying to install graphql on Strapi 3.12 

### ISSUE THREAD

**Issue by Lengatox** [strapi/strapi#971]
Node.js version: 9.11.1
npm version: 5.6.0
Strapi version: 3.0.0-alpha.12
Database: MongoDB
Operating system: Ubuntu 16.0.4

When i tried to start strapi with the installation of graphql on the latest version occurs the next problem:

 Error: Cannot find module '/home/ubuntu/strapiTest/node_modules/strapi/lib/utils'

which one could be the problem?

**Comment by lauriejim** [comment]
Hello @Lengatox did you use Strapi CLI or admin interface to install graphql plugin ?

**Comment by Lengatox** [comment]
Hello @lauriejim  I use Strapi CLI, but i made a test and verified that those directory doesn't exist before installation of graphql, and even after installation of the plugin.

**Comment by Moeface** [comment]
Having the same issue.

Running on Windows 10 x64.

Starting the Strapi server without the graphql plugin installed works fine, however when I install the graphql plugin and then try to start the Strapi server, I get the following error:

```
debug Server wasn't able to start properly.
{ Error: Cannot find module 'C:\Development\strapireal\node_modules\strapi\lib\utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Function.beforeInitialize (C:\Development\strapireal\plugins\graphql\hooks\graphql\index.js:24:21)
    at Promise.all.Object.keys.map (C:\Users\Moe\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:55:47)
    at Array.map (<anonymous>)
    at Strapi.module.exports (C:\Users\Moe\AppData\Roaming\npm\node_modules\strapi\lib\hooks\index.js:46:28)
    at Strapi.load (C:\Users\Moe\AppData\Roaming\npm\node_modules\strapi\lib\Strapi.js:208:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) code: 'MODULE_NOT_FOUND' }
```
Uninstalling the plugin and starting the server then works again.

**Comment by Aurelsicoko** [comment]
The issue has been fixed (https://github.com/strapi/strapi/pull/982). The other solution is to run this command at the root of your project to remove the symlink of the `node_modules/strapi` folder.

```bash
cd /path/to/your/project
npm install strapi@alpha
```

**Comment by miguelangeltorresfp** [comment]
Having the same issue running on Windows 10 x64 Pro.

The solution proposed by @Aurelsicoko worked for me but only in a fresh install, not with an old project.
Although the error shown in the old one is different:

`$ strapi start
(node:3432) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Invalid number, expected digit but got: "i".
    at syntaxError (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\error\syntaxError.js:24:10)
    at readDigits (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\lexer.js:466:32)
    at readNumber (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\lexer.js:419:16)
    at readToken (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\lexer.js:305:14)
    at Object.lookahead (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\lexer.js:62:43)
    at Object.advanceLexer [as advance] (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\lexer.js:52:33)
    at expect (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:1441:11)
    at parseName (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:98:15)
    at parseInputValueDef (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:904:14)
    at many (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:1516:16)
    at parseInputFieldsDefinition (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:1067:50)
    at parseInputObjectTypeDefinition (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:1051:16)
    at parseTypeSystemDefinition (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:721:16)
    at parseDefinition (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:144:16)
    at many (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:1516:16)
    at parseDocument (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:115:18)
    at Object.parse (F:\CODE\strapi\old-project-strapi\plugins\graphql\node_modules\graphql\language\parser.js:50:10)
    at Object.addPolymorphicUnionType (F:\CODE\strapi\old-project-strapi\plugins\graphql\services\Types.js:154:8)
    at Object.generateSchema (F:\CODE\strapi\old-project-strapi\plugins\graphql\services\Schema.js:179:15)
    at Function.initialize (F:\CODE\strapi\old-project-strapi\plugins\graphql\hooks\graphql\index.js:148:50)
    at F:\CODE\strapi\old-project-strapi\node_modules\strapi\lib\hooks\index.js:19:29
    at after (F:\CODE\strapi\old-project-strapi\node_modules\strapi\lib\hooks\index.js:122:39)
    at F:\CODE\strapi\old-project-strapi\node_modules\lodash\lodash.js:9999:23
    at Strapi.once (F:\CODE\strapi\old-project-strapi\node_modules\strapi\lib\hooks\index.js:133:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at Strapi.EventEmitter.emit (domain.js:442:20)
    at loadedModule.initialize.call.err (F:\CODE\strapi\old-project-strapi\node_modules\strapi\lib\hooks\index.js:32:12)
(node:3432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-19T00:12:22.433Z] debug ⛔️ Server wasn't able to start properly.
[2019-02-19T00:12:22.436Z] error (hook:graphql) takes too long to load
(hook:graphql) takes too long to load`
