### ISSUE TITLE
Error Strapi 3.5.2 to Mongo Atlas - Node 14.16.0

### ISSUE THREAD

**Issue by xAgustin93** [strapi/strapi#9721]
### Describe the bug

For several days when a Strapi project with node version 14.x has been created and connects as a database to Mongo Atlas it is generating the following flaw.
**Video error example:** https://youtu.be/lG0sZ7hDPbA

```
[2021-03-15T07:31:10.544Z] error Bootstrap function in plugin "users-permissions" failed
[2021-03-15T07:31:10.545Z] error TypeError: Cannot read property '_id' of undefined
    at /Users/agustinnavarro/Desktop/aaaa/server-strapi/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:263:59
    at Array.map (<anonymous>)
    at Object.updatePermissions (/Users/agustinnavarro/Desktop/aaaa/server-strapi/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:262:46)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/Users/agustinnavarro/Desktop/aaaa/server-strapi/node_modules/strapi-plugin-users-permissions/config/functions/bootstrap.js:205:3)
    at async Promise.all (index 2)
    at async Strapi.runBootstrapFunctions (/Users/agustinnavarro/Desktop/aaaa/server-strapi/node_modules/strapi/lib/Strapi.js:432:5)
    at async Strapi.load (/Users/agustinnavarro/Desktop/aaaa/server-strapi/node_modules/strapi/lib/Strapi.js:364:5)
    at async Strapi.start (/Users/agustinnavarro/Desktop/aaaa/server-strapi/node_modules/strapi/lib/Strapi.js:191:9)
error Command failed with exit code 1.
```

### Steps to reproduce the behavior

1. Create Stripe proyect
2. Connect to Mongo Atlas
3. yarn develop

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.5.2
- Database: MongoDB to Mongo Atlas
- Operating system: MacOS

**Comment by aksdevac** [comment]
its mongo network error, you have omitted that line from error logs, I have not tried but it may be related Atlas ip restrictions & not related to strapi.

**Comment by xAgustin93** [comment]
> its mongo network error, you have omitted that line from error logs, I have not tried but it may be related Atlas ip restrictions & not related to strapi.

I have always generated the projects in the same way and this time it is the first time it generates this error, and it was after the strapi update.
