### ISSUE TITLE
upload-aws-s3: Missing required key 'Bucket' in params

### ISSUE THREAD

**Issue by vphilot** [strapi/strapi#9754]
## Bug report

Upload with S3 throws error: `MissingRequiredParameter: Missing required key 'Bucket' in params` even tho all the keys are correctly configured.

### Describe the bug

After installing `strapi-provider-upload-aws-s3` and populating the file according to [the provider readme](https://www.npmjs.com/package/strapi-provider-upload-aws-s3), any attempt to upload an image from Strapi throws the following error:

```bash
MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (<mydir>/cms/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (<mydir>/cms/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (<mydir>/cms/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (<mydir>/cms/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (<mydir>/cms/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (<mydir>/cms/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (<mydir>/cms/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at <mydir>/cms/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (<mydir>/cms/node_modules/aws-sdk/lib/config.js:386:7)
    at <mydir>/cms/node_modules/aws-sdk/lib/config.js:428:9
    at Object.<anonymous> (<mydir>/cms/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:111:13)
    at Object.arrayEach (<mydir>/cms/node_modules/aws-sdk/lib/util.js:521:32)
    at resolveNext (<mydir>/cms/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:110:20)
    at <mydir>/cms/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
    at <mydir>/cms/node_modules/aws-sdk/lib/credentials.js:124:23
    at <mydir>/cms/node_modules/aws-sdk/lib/credentials.js:212:15
[2021-03-17T22:19:27.033Z] error Error: Internal Server Error
    at convertToStrapiError (<mydir>/cms/node_modules/strapi-plugin-upload/errors.js:38:26)
    at Object.upload (<mydir>/cms/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.uploadFileAndPersist (<mydir>/cms/node_modules/strapi-plugin-upload/services/Upload.js:154:5)
    at async Promise.all (index 0)
    at async Object.upload (<mydir>/cms/node_modules/strapi-plugin-upload/services/Upload.js:140:12)
    at async uploadFiles (<mydir>/cms/node_modules/strapi-plugin-upload/controllers/upload/admin.js:187:27)
    at async Object.upload (<mydir>/cms/node_modules/strapi-plugin-upload/controllers/Upload.js:65:5)
    at async <mydir>/cms/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async <mydir>/cms/node_modules/strapi-utils/lib/policy.js:68:5
    at async <mydir>/cms/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async <mydir>/cms/node_modules/strapi/lib/middlewares/xss/index.js:26:9
```

### Steps to reproduce the behavior

1. Set up a new Strapi project from scratch with the s3 provider
2. try to upload an image through the UI

### Expected behavior

File gets uploaded to S3 without errors.

### Code snippets

current `config.plugins.js` :

```js
module.exports = ({ env }) => ({
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: env('key'),
      secretAccessKey: env(key'),
      region: env('region'),
      params: {
        Bucket: env('bucket'),
      },
    },
  },
})
```

### System

- Node.js version: v14.15.0
- NPM version: 7.6.3
- Strapi version: 3.5.3
- Database: SQLite
- Operating system: MacOS 11.1

**Comment by derrickmehaffy** [comment]
Can't reproduce on v3.5.4:

![image](https://user-images.githubusercontent.com/8593673/112905656-9e99a000-909f-11eb-82c3-651d6a25eb6d.png)

![image](https://user-images.githubusercontent.com/8593673/112905731-c426a980-909f-11eb-807b-8ad2b2ac93b2.png)

Marking as closed unless reproduction steps can be provided.
