### ISSUE TITLE
Error: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value

### ISSUE THREAD

**Issue by gustavpursche** [strapi/strapi#9782]
## Bug report

1. I have a component called :"subnavigation" which has a repeatable sub-component called "item"
2. I have a second component called "stage_large"
3. As soon as I add "subnavigation - item" as a repeatable sub-component on "stage_large", I get the following error:

```
error Error: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Query.Sequence._packetToError (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    --------------------
    at Protocol._enqueue (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/virtual/seeb/html/cms/node_modules/mysql/lib/Connection.js:198:25)
    at /var/www/virtual/seeb/html/cms/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/client.js:134:12)
    at /var/www/virtual/seeb/html/cms/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/execution/runner.js:272:20)
    at async Runner.run (/var/www/virtual/seeb/html/cms/node_modules/knex/lib/execution/runner.js:30:19)
[2021-03-19T16:25:51.344Z] debug PUT /content-manager/collection-types/application::campaign.campaign/2 (116 ms) 400
```

when saving the content row. I wasn't able to reproduce the problem in sqlite. It only seems to happen in production, where the database is mysql.

### Expected behavior

I expect that I'm able to save "subnavigation - items" as part of the component.

### Screenshots

None

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.16.0
- NPM version: 6.14.10
- Strapi version: 3.5.3
- Database: mysql
- Operating system: Ubuntu / CentOS

### Additional context

You can find the repository here: https://github.com/seebruecke-org/cms

**Comment by derrickmehaffy** [comment]
You are using custom plugins that are causing this error, removing the plugins yields in blocks with no context in the content-manager. This is not an issue with Strapi directly, I suggest you bring the topic up on our forum: https://forum.strapi.io

**Comment by gustavpursche** [comment]
@derrickmehaffy This is not true :) The error happened already before I started working on the plugins. There seems to be a case where the schema becomes corrupted in mysql, if you add a repeatable component as sub-component. I wasn't able to reproduce this in sqlite.

However - there might a chance, that this is connected to: https://github.com/strapi/strapi/issues/9150 so I'm fine with leaving this closed. 🤞🏽 for the v4 refactoring you've mentioned in slack.

**Comment by cakandari** [comment]
There is no bug. "ER_NO_DEFAULT_FOR_FIELD: Field 'fieldName' doesn't have a default value"  arises only when you are creating or updating a row that doesn't have primary field data value. Let's say you have primary key 'pan' and you are creating a record with a data that doesn't have key value pair for 'pan', then mysql will throw error. Hope problem is resolved.
