### ISSUE TITLE
Renaming component category causes errors

### ISSUE THREAD

**Issue by multiwebinc** [strapi/strapi#9794]
### Bug description

Renaming component category causes errors:

```
[2021-03-22T06:25:55.554Z] debug GET /content-manager/content-types/application::inicio.inicio/configuration (58 ms) 200
[2021-03-22T06:25:55.607Z] error MissingSchemaError: Schema hasn't been registered for model "ComponentPaginasTexto".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (/path/to/strapi/node_modules/mongoose/lib/connection.js:1192:11)
    at getModelsMapForPopulate (/path/to/strapi/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:285:59)
    at populate (/path/to/strapi/node_modules/mongoose/lib/model.js:4320:21)
    at _populate (/path/to/strapi/node_modules/mongoose/lib/model.js:4290:5)
    at /path/to/strapi/node_modules/mongoose/lib/model.js:4266:5
    at promiseOrCallback (/path/to/strapi/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Function.Model.populate (/path/to/strapi/node_modules/mongoose/lib/model.js:4264:10)
    at cb (/path/to/strapi/node_modules/mongoose/lib/query.js:1944:17)
    at /path/to/strapi/node_modules/mongodb/lib/utils.js:674:5
    at handleCallback (/path/to/strapi/node_modules/mongodb/lib/utils.js:102:55)
    at /path/to/strapi/node_modules/mongodb/lib/cursor.js:838:66
    at /path/to/strapi/node_modules/mongodb/lib/utils.js:674:5
    at /path/to/strapi/node_modules/mongodb/lib/cursor.js:923:9
    at Cursor._endSession (/path/to/strapi/node_modules/mongodb/lib/core/cursor.js:394:7)
    at /path/to/strapi/node_modules/mongodb/lib/cursor.js:921:12
    at maybePromise (/path/to/strapi/node_modules/mongodb/lib/utils.js:662:3)
```

### Steps to reproduce the behavior

1. Create a component
2. Create a collection type (I used single type) and add the component to the collection type
3. Rename the component's category to something else. In my case, the original name was `Paginas`, which is what shows up in the error message. Rename it to anything else.
4. Click to your collection type and look in the console.

### Expected behavior

You should be able to rename component category

### System

- Node.js version: 14.16.0
- NPM version: 7.6.3
- Strapi version: 3.5.3
- Database: mongodb
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
This is due to other references of the component in other models/components. I'm marking as closed but you should review your code base for the previous name and change it there.
