### ISSUE TITLE
/bin/sh required

### ISSUE THREAD

**Issue by Nainterceptor** [strapi/strapi#9920]
### Describe the bug

As a devSecOps Engineer, I want to package Strapi in a distroless container. In this kind of container, the strict minimum tools are available on runtime. But Strapi seems to need `sh` to fork process somewhere. And in distroless container, there is no `sh`.

OK to share ou Dockerfile.

### Dockerfile 

```Dockerfile
FROM node:14 AS base
ADD . /app
WORKDIR /app

FROM base as prod-install
WORKDIR /app
RUN npm ci --cache .npm --prefer-offline --only=production

FROM base as prod-build
WORKDIR /app
COPY --from=prod-install /app/node_modules /app/node_modules
RUN npm ci --cache .npm --prefer-offline
ARG NODE_ENV=production
RUN npm run build

FROM gcr.io/distroless/nodejs:14
WORKDIR /app
COPY --from=base /app /app
COPY --from=prod-install /app/node_modules /app/node_modules
COPY --from=prod-build /app/build /app/build

EXPOSE 3000
EXPOSE 9091
ENV HOST=0.0.0.0
ENV PORT=3000
ENV STRAPI_DISABLE_UPDATE_NOTIFICATION=true
ENV STRAPI_TELEMETRY_DISABLED=true

CMD [ "node_modules/.bin/strapi", "start" ]
```

### Steps to reproduce the behavior

1. Build the dockerfile
2. Start the container
3. See error

```
[2021-03-31T14:41:59.332Z] debug ⛔️ Server wasn't able to start properly.
[2021-03-31T14:41:59.334Z] error Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:602:24)
    at execSync (child_process.js:647:15)
    at u (/app/node_modules/node-machine-id/dist/index.js:1:7825)
    at module.exports (/app/node_modules/strapi/lib/services/metrics/sender.js:25:20)
    at createTelemetryInstance (/app/node_modules/strapi/lib/services/metrics/index.js:29:18)
    at Strapi.load (/app/node_modules/strapi/lib/Strapi.js:333:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Strapi.start (/app/node_modules/strapi/lib/Strapi.js:193:9)
```

### Expected behavior

Should not fail 🤷‍♂️

### Additional context

Variables to disable telemetry has been added, I had hope to workaround by disabling Telemetry mentionned in stack trace.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/8389
