### ISSUE TITLE
Unable to use the Mailgun Plugin to send test email 500 Error

### ISSUE THREAD

**Issue by Cpaczek** [strapi/strapi#9945]
### Description

After following the setup guide for the [Mailgun email provider](https://www.npmjs.com/package/strapi-provider-email-mailgun) I am unable to send a test email (or any email)

### Steps to reproduce the behavior

1. Install a new strapi instance using npx `npx create-strapi-app my-project --quickstart`
2. Make a `plugins.js` file within the `config` folder
3. install the mailgun service provider `npm install strapi-provider-email-mailgun --save`
4. Make a copy of .env.example and rename it .env
5. fill in the relevant mailgun api details
6. Paste this into the plugins.js
```
module.exports = ({ env }) => ({
  // ...
  email: {
    provider: 'mailgun',
    providerOptions: {
      apiKey: env('MAILGUN_API_KEY'),
      domain: env('MAILGUN_DOMAIN'), //Required if you have an account with multiple domains
      host: env('MAILGUN_HOST', 'api.mailgun.net'), //I changed it from api.us.mailgun.net to api.mailgun.net because that is the proper endpoint
    },
    settings: {
      defaultFrom: 'noreply@m.yourdomain.com',
      defaultReplyTo: 'support@yourdomain.com',
    },
  },
  // ...
});
```
### Expected behavior

When navigating to `http://localhost:1337/admin/settings/email` and typing in the your email into the send test email box it will send a test email.

However when I do this I get an error on the UI and a 500 in the console

```
[2021-04-03T02:30:10.203Z] error Error: Couldn't send test email: Forbidden.
    at Object.test (C:\Users\Cameron Paczek\exclnetworks-strapi-test\exclnetworks-strapi\node_modules\strapi-plugin-email\controllers\Email.js:48:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-04-03T02:30:10.203Z] debug POST /email/test (206 ms) 500
```

I also tried doing this with a password reset email and I get the same error.

```
[2021-04-03T02:40:02.451Z] error Error: Forbidden
    at IncomingMessage.<anonymous> (C:\Users\Cameron Paczek\exclnetworks-strapi-test\exclnetworks-strapi\node_modules\mailgun-js\lib\request.js:327:17)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### System

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.5.4
- Database: SQL Lite (I think just used quickstart)
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Check your email templates in the admin panel, those email settings in the config are for the email API but aren't always used.

**Comment by Cpaczek** [comment]
@derrickmehaffy 
Looking at the email templates it doesn't seem like there is a Test email template however for the password reset I changed the shipper email to my mailgun email yet and tried resetting my password and it does not work I still get a Forbidden error. 

```
[2021-04-03T02:40:02.451Z] error Error: Forbidden
    at IncomingMessage.<anonymous> (C:\Users\Cameron Paczek\exclnetworks-strapi-test\exclnetworks-strapi\node_modules\mailgun-js\lib\request.js:327:17)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
Still not sure if this error is from mailgun or strapi.

**Comment by derrickmehaffy** [comment]
Did you set the authorized emails in mailgun? You have to "register" the email with them I believe.

**Comment by Cpaczek** [comment]
![](https://i.gyazo.com/dd1b69bcd2e54cde8db72fabde38976d.png)
Yes I added a sending API key and put it in my env.

**Comment by derrickmehaffy** [comment]
Also how are you setting the environment variables?

**Comment by Cpaczek** [comment]
@derrickmehaffy I made a copy of .env.example and renamed it .env and this is what it looks like
```
HOST=0.0.0.0
PORT=1337
MAILGUN_API_KEY=[REDACTED]
MAILGUN_DOMAIN=m.exclnetworks.com
MAILGUN_HOST=api.mailgun.net
```

**Comment by Cpaczek** [comment]
Oh My God. Just figured it out, so our sysadmin added an IP whitelist to our mailgun and I wasn't on it so I just added my IP and it worked.
