### ISSUE TITLE
Execute Complex query using Graphql

### ISSUE THREAD

**Issue by Lengatox** [strapi/strapi#997]
Node.js version: 9.11.1
npm version: 5.6.0
Strapi version: 3.0.0-alpha.12
Database: MongoDB
Operating system: Ubuntu 16.0.4

Hi guys, I was trying to execute a complex query using graphql, i can run the query using the interface (GraphiQL), but when i create the new file named: schema.graphql in the next directory: ./api/*/config/schema.graphql, and then tryied to run strapi server throws me the next error: 

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Strapi.loadFile (/home/ubuntu/dev-cms/node_modules/strapi/lib/utils/index.js:20:12)
    at Object.setConfig (/home/ubuntu/dev-cms/node_modules/strapi/lib/utils/index.js:29:19)
    at p (/home/ubuntu/dev-cms/node_modules/strapi/lib/utils/index.js:105:26)
    at /home/ubuntu/dev-cms/node_modules/async/dist/async.js:1008:9
    at eachOfArrayLike (/home/ubuntu/dev-cms/node_modules/async/dist/async.js:941:9)
    at eachOf (/home/ubuntu/dev-cms/node_modules/async/dist/async.js:991:5)
    at _asyncMap (/home/ubuntu/dev-cms/node_modules/async/dist/async.js:1006:5)
    at /home/ubuntu/dev-cms/node_modules/async/dist/async.js:996:16
    at Promise.all.Promise (/home/ubuntu/dev-cms/node_modules/strapi/lib/utils/index.js:104:9)
    at new Promise (<anonymous>)
    at Strapi.loadConfig (/home/ubuntu/dev-cms/node_modules/strapi/lib/utils/index.js:103:7)
    at glob (/home/ubuntu/dev-cms/plugins/graphql/hooks/graphql/index.js:49:30)
    at f (/home/ubuntu/dev-cms/plugins/graphql/node_modules/once/once.js:25:25)

maybe you could help me to solve the problem. 
 
With this new version, it is possible to make group to organize the models in the strapi admin panel?

**Comment by Lengatox** [comment]
this is a copy of the file that has to be placed in the : ./api/wllogin/config/
[schema.txt](https://github.com/strapi/strapi/files/1936563/schema.txt)(with graphql extension)

I use to test the query that generate the graphql plugin for the model, but the complex query that i want to use it's something like this: 
[graphql- query.txt](https://github.com/strapi/strapi/files/1936577/graphql-.query.txt)

**Comment by Aurelsicoko** [comment]
You don't need to `{` in the query property. Also the `type` property is a JSON object so you've to follow the JSON format to make it work.

```js
module.exports = {
  definition: `
    type Wllogin {
      _id: String
      created_at: String
      updated_at: String
      status: Boolean
      errorMessage: String
      button: Lbutton
      link: Llink
      form: Lform
      design: Ldesign
      terms: Lterms
    }
 `,
  query: `
    wllogins(sort: String, limit: Int, start: Int, where: JSON): [Wllogin]
  `,
  type: {},
  resolver: {
     Query: {
	wllogin: {
	  description: 'Return  login',
	  resolver: 'Wllogin.findByParams' // It will use the action `findByParams` located in the `Wllogin.js` controller.
	}
     }
  }
};
```

**Comment by Lengatox** [comment]
Thanks, it works with the changes that you made in the syntax, but when i try to replace the query generated by graphql, for a personalized query it tells me that  expected a ",".

Maybe you could help me by giving me an example of how to make a complex query and Link it to a controller action.

**Comment by Lengatox** [comment]
@lauriejim 
This is an example of the query I try to execute following the guide that is in the Strapi documentation.

I already have models and relationships created.

module.exports = {
  definition: '',
  query:
	 'wllogins { status errorMessage form { user{ name placeholder width errorText validation } } } ',
  type: {},
  resolver: {
     Query: {
	wllogin: {
	  description: 'Return  login',
	  resolver: 'Wllogin.findByParams' // It will use the action `findByParams` located in the `Wllogin.js` controller.
	}
     }
  }
};

**Comment by Aurelsicoko** [comment]
```
module.exports = {
  definition: `
    type Wllogin {
      _id: String
      created_at: String
      updated_at: String
      status: Boolean
      errorMessage: String
      button: Lbutton
      link: Llink
      form: Lform
      design: Ldesign
      terms: Lterms
    }
 `,
  query: `
    myComplexQuery(sort: String, limit: Int, start: Int, where: JSON): [Wllogin]
  `,
  type: {},
  resolver: {
    Query: {
      myComplexQuery: {
        description: 'Return  login',
        resolver: 'Wllogin.myComplexAction' // It will use the action `myComplexAction` located in the `Wllogin.js` controller
      }
     }
  }
};
```

Did you try something like this?

**Comment by Lengatox** [comment]
hi @Aurelsicoko, as always thanks for your help, but i tryed to execute the solution that you recomend above, just with little changes like this: 

`module.exports = {
  definition: `
    type Wllogin {
      _id: String
      created_at: String
      updated_at: String
      status: Boolean
      errorMessage: String
      button: Lbutton
      link: Llink
      form: Lform
      design: Ldesign
      terms: Lterms
    }
 `,
  query: `
    wllogin(sort: String, limit: Int, start: Int, where: JSON): [Wllogin]
  `,
  type: {
     Wllogin: false
  },
  resolver: {
    Query: {
      myComplexQuery: {
        description: 'Return  login',
        resolver: 'Wllogin.findTest' // It will use the action `myComplexAction` located in the `Wllogin.js` controller
      }
     }
  }
};`

In this file: "schema.graphql" in the next directory: "/home/ubuntu/dev-cms/api/wllogin/config/" throws me the next error: 

Error: Type "Wllogin" was defined more than once.
    at Object.buildASTSchema (/home/ubuntu/dev-cms/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:116:17)
    at buildSchemaFromTypeDefinitions (/home/ubuntu/dev-cms/plugins/graphql/node_modules/graphql-tools/dist/schemaGenerator.js:182:28)
    at _generateSchema (/home/ubuntu/dev-cms/plugins/graphql/node_modules/graphql-tools/dist/schemaGenerator.js:97:18)
    at makeExecutableSchema (/home/ubuntu/dev-cms/plugins/graphql/node_modules/graphql-tools/dist/schemaGenerator.js:110:20)
    at Object.generateSchema (/home/ubuntu/dev-cms/plugins/graphql/services/GraphQL.js:663:20)
    at Function.initialize (/home/ubuntu/dev-cms/plugins/graphql/hooks/graphql/index.js:101:62)
    at /home/ubuntu/dev-cms/node_modules/strapi/lib/hooks/index.js:21:31
    at after (/home/ubuntu/dev-cms/node_modules/strapi/lib/hooks/index.js:127:39)
    at /home/ubuntu/dev-cms/node_modules/lodash/lodash.js:9989:23
    at Strapi.once (/home/ubuntu/dev-cms/node_modules/strapi/lib/hooks/index.js:138:17)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Strapi.emit (events.js:208:7)
    at loadedModule.initialize.call.err (/home/ubuntu/dev-cms/node_modules/strapi/lib/hooks/index.js:34:14)
    at NativeConnection.instance.connection.on (/home/ubuntu/dev-cms/node_modules/strapi-mongoose/lib/index.js:420:11)
    at emitNone (events.js:106:13)
    at NativeConnection.emit (events.js:208:7)
    at /home/ubuntu/dev-cms/node_modules/mongoose/lib/connection.js:476:13
    at result (/home/ubuntu/dev-cms/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/ubuntu/dev-cms/node_modules/mongodb/lib/utils.js:406:9)
    at /home/ubuntu/dev-cms/node_modules/mongodb/lib/mongo_client.js:273:5
    at connectCallback (/home/ubuntu/dev-cms/node_modules/mongodb/lib/mongo_client.js:955:5) 

but if a remove the "definition type", it seem that strapi compile but when i run my complex action in the server just shows me the information with the ID of the the others model that i have related.

[Result not expected.txt](https://github.com/strapi/strapi/files/2002711/Result.not.expected.txt)

**Comment by Aurelsicoko** [comment]
@Lengatox So it means there is an issue here...

**Comment by derrickmehaffy** [comment]
@Lengatox can you check with the latest version to see if this still exists (given graphiql isn't installed anymore, playground is) Trying to see if we can close out old issues.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
