### ISSUE TITLE
Internal plugin loading should use softlinks

### ISSUE THREAD

**Issue by 0b1kn00b** [strapi/strapi#9974]
## Bug report
I had a plugin using `yarn add link:...`, which creates a softlink. When building the admin, an internal module chokes on it

```
yarn run v1.22.10
$ strapi build
Building your admin UI with production configuration ...
Error: Cannot find module 'strapi-plugin-content-export-import/package.json'
Require stack:
- /usr/src/app/node_modules/strapi-admin/index.js
- /usr/src/app/node_modules/strapi/lib/commands/build.js
- /usr/src/app/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at getPkgPath (/usr/src/app/node_modules/strapi-admin/index.js:14:49)
    at /usr/src/app/node_modules/strapi-admin/index.js:185:34
    at Array.filter (<anonymous>)
    at createCacheDir (/usr/src/app/node_modules/strapi-admin/index.js:182:59)
    at Object.build (/usr/src/app/node_modules/strapi-admin/index.js:41:9)
    at module.exports (/usr/src/app/node_modules/strapi/lib/commands/build.js:29:6)
    at /usr/src/app/node_modules/strapi/bin/strapi.js:50:14
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/strapi-admin/index.js',
    '/usr/src/app/node_modules/strapi/lib/commands/build.js',
    '/usr/src/app/node_modules/strapi/bin/strapi.js'
  ]
}
```
error Command failed with exit code 1.

### Expected behavior

Should follow the softlink to the repo
### Code snippets

`"strapi-plugin-content-export-import": "link:vendor/plugins/content-export-import",`

```
{
  "name": "strapi-development",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop" : "strapi develop ",
    "start"   : "strapi start",
    "build"   : "strapi build",
    "strapi"  : "strapi",

    "test-server": "NODE_ENV=test node tests/server-test.js",
    "test-server-poke": "NODE_ENV=test POKE=1 node tests/server-test.js",
    "test-common": "NODE_ENV=test node tests/common-test.js",
    "test-common-poke": "NODE_ENV=test POKE=1 node tests/common-test.js",
    "test-client": "NODE_ENV=test node tests/client-test.js",
    "test-client-poke": "NODE_ENV=test POKE=1 node tests/client-test.js"
  },
  "devDependencies": {},
  "dependencies": {
    "@jest/core": "^26.6.3",
    "@jest/globals": "^26.6.2",
    "@sentry/node": "^6.2.0",
    "@shopify/jest-koa-mocks": "^2.3.3",
    "@types/bookshelf": "^1.2.1",
    "@types/form-data": "^2.5.0",
    "@types/node-fetch": "^2.5.8",
    "faker": "^5.3.1",
    "form-data": "^3.0.0",
    "hashi-vault-js": "^0.4.1",
    "jest": "^26.6.3",
    "jquery": "^3.5.1",
    "knex": "^0.21.17",
    "koa": "^2.13.1",
    "koa-create-context": "link:vendor/koa-create-context",
    "koa-log-requests": "^1.0.0",
    "koa-socket-2": "link:./vendor/koa-socket-2",
    "node-fetch": "^2.6.1",
    "node-mocks-http": "^1.10.1",
    "pg": "^8.5.1",
    "popper.js": "^1.16.1",
    "socket.io": "^3.1.2",
    "source-map-support": "^0.5.19",
    "sqlite3": "5.0.0",
    "strapi": "3.5.4",
    "strapi-admin": "3.5.4",
    "strapi-connector-bookshelf": "3.5.4",
    "strapi-generate": "3.5.4",
    "strapi-generate-controller": "^3.5.4",
    "strapi-plugin-comments": "^1.0.1-beta.6",
    "strapi-plugin-content-export-import": "link:vendor/plugins/content-export-import",
    "strapi-plugin-content-manager": "3.5.4",
    "strapi-plugin-content-type-builder": "3.5.4",
    "strapi-plugin-documentation": "3.5.4",
    "strapi-plugin-email": "3.5.4",
    "strapi-plugin-graphql": "3.5.4",
    "strapi-plugin-upload": "3.5.4",
    "strapi-plugin-users-permissions": "3.5.4",
    "strapi-provider-email-sendgrid": "^3.5.4",
    "strapi-provider-upload-aws-s3": "^3.5.4",
    "strapi-utils": "3.5.4",
    "strapio": "^1.0.11",
    "stripe": "^8.135.0",
    "vault-env": "^5.0.0-beta.2",
    "vaultenv": "https://github.com/tngan/vaultenv.git",
    "yup": "link:vendor/yup"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "DO-5f646f8d-7610-4546-ba3c-5228caf67608"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by derrickmehaffy** [comment]
shouldn't be an issue in v4 now though you may still need to set the resolve option in the plugins.js config file
